### ISSUE TITLE
GitHub "star" -> "stars"

### ISSUE THREAD

**Issue by nschloe** [badges/shields#1003]
The current Github badge indicating the number of stars says `star`. This can be misunderstood since it could indicate that the badge is really another button to star the repository in question while it really is a link to the Github repo. I've seen users avoid the link.

To prevent this, I would suggest changing "star" to "stars".

**Comment by Daniel15** [comment]
Seems reasonable. Would you like to submit a pull request for this?

**Comment by paulmelnikow** [comment]
Addressed in #1019.
