### ISSUE TITLE
Consider recoloring CC0 license and adding 0BSD

### ISSUE THREAD

**Issue by xuhdev** [badges/shields#10058]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Neither [Free Software Foundation](https://www.gnu.org/licenses/license-list.html#CC0) nor [Open Source Initiative](https://opensource.org/faq#cc-zero) recommend releasing software under CC0 due to patent grant issues, and only Free Software Foundation considers CC0 as a free license. However, it is currently being [colored as the least restrictive](https://github.com/badges/shields/blame/cb2d25ea6ef44a397e9fc92ef944443bb2f7f249/services/licenses.js#L90). The license is controversial at best.

One real no-attribution license in the software world is [0BSD](https://spdx.org/licenses/0BSD.html), which is not included by shield.io.

### 💡 Possible Solution

Recolor or remove CC0, and add 0BSD to the public domain color list.

**Comment by calebcartwright** [comment]
Thanks for reaching out. I confess my initial reaction seeing this is the typical "I'm not a lawyer, I don't even want to pretend to be able to adjudicate open source licenses", but I also fully recognize the badge coloring is, to an extent, already doing just that.

I'll be curious to hear thoughts from other maintainers, but I think there's two separate items here: the addition of 0BSD which should be fairly noncontroversial, and potential changes on CC0 which will have some level of blast radius consideration and controversy

**Comment by xuhdev** [comment]
Yeah I agree regarding CC0. That's exactly why I put the opinions of [Free Software Foundation](https://www.gnu.org/licenses/license-list.html#CC0) nor [Open Source Initiative](https://opensource.org/faq#cc-zero) in the original post, not my own opinion :wink:

**Comment by chris48s** [comment]
Broadly speaking, I'm against us just freestyling this and making our own judgements.

Looking over the comments in https://github.com/badges/shields/blob/master/services/licenses.js and the discussion in https://github.com/badges/shields/pull/1190 it seems that we're mostly deferring to choosealicense.com on this.

Looking over the table on https://choosealicense.com/appendix/ and http://landley.net/toybox/license.html I agree with adding 0BSD to this category :+1: 

On removing CC0: Badges are not only for software projects (although I acknowledge that is the primary use). Data projects can use badges too. You can use one on your eBook if you want :shrug:
I'm not sure I necessarily _love_ the fact that we've decided to apply semantic colours to licenses, but given is where we are starting from, I don't think "suitability for software projects" is one of the characteristics we've attempted to encode. "CC-BY-SA-4.0" probably isn't a great license for software, but we still code it as "copyleft".
I think I am :-1: on removing CC0 from the "public domain" group. Even if it is not advised for software, it is still a public domain license.

**Comment by jNullj** [comment]
Change is available for merge in PR #10092 
Added 0BSD to the public domain type (and spec test)
Also noticed we can add 0BSD in PyPi License service helper, as PyPi is not using the short spdx name but a longer format.

**Comment by calebcartwright** [comment]
> I'm not sure I necessarily love the fact that we've decided to apply semantic colours to licenses, but given is where we are starting from

I had this exact same reaction too but talked myself into not opening that can of worms. The more I think about it, the more I feel like the license fits squarely into that blue/informational pattern that we use for data elements I'd consider to be very similar in nature.

Given #10092 I'm going to go ahead and close this, as one half of this has already been resolved and there's some objections and concerns on the other half of this issue around removing CC0 from the public domain group.

Separately, I would be open to discussing dropping our current default behavior of applying semantic coloring to licenses and just using blue/informational by default, as people can always adjust to whatever color they want (in fact, reviewing my own personal usages of this badge I was reminded that I seem to always drop a `color=blue` on mine anyway :shrug:)
