### ISSUE TITLE
Proposal for New Badges for Hugging Face Hub

### ISSUE THREAD

**Issue by dhakalnirajan** [badges/shields#10056]
### 📋 Description

We propose the addition of new badges to represent various aspects of Hugging Face's offerings and contributions to the machine learning community. These badges aim to enhance visibility and recognition for Hugging Face users and contributors across different platforms and projects.

Ideas for New Badges:

    Hugging Face Models Badge: Displays information about Hugging Face models, including the model's icon and name.
        Example: Models-{model-icon} or Models-model_name

    Hugging Face Transformers Badge: Indicates details about Hugging Face transformer architectures, including the transformer's icon and name.
        Example: Transformers-{transformers-icon} or Transformers-Architecture_name

    Hugging Face Datasets Badge: Provides information about Hugging Face datasets, including the dataset's icon and name.
        Example: Datasets-{datasets-icon} or Datasets-dataset_name

### 🔗 Data

The data for these badges can be retrieved from the Hugging Face Hub API, which offers access to a wide range of models, transformers, and datasets. The API is publicly accessible and does not require authentication. Detailed documentation for the API can be found at:
[https://huggingface.co/brand](https://huggingface.co/brand).

### 🎤 Motivation

These new badges serve several purposes:

- Enhanced Visibility: By displaying Hugging Face badges, developers can easily showcase their use of Hugging Face resources on their profiles, projects, and platforms.

- Community Recognition: Badges serve as a badge of honor, recognizing contributors and users of Hugging Face's resources within the machine learning community.

- Promotion of Open-Source ML: By promoting Hugging Face badges, we encourage the adoption of open-source machine learning tools and foster collaboration within the community.

Implementing these badges aligns with the ethos of Hugging Face as a collaborative platform for the machine learning community and will further solidify its position as a leading provider of open-source ML resources.

**Comment by chris48s** [comment]
Can you give a bit more detail about the data points that would be fetched from the upstream service and where they would come from. You've said "documentation for the API can be found at.." and then linked to the brand guidelines.

If you're really looking for icons, our named icons come from the simple-icons project. You might want to follow
https://github.com/simple-icons/simple-icons/issues/6074
https://github.com/simple-icons/simple-icons/pull/9259

**Comment by dhakalnirajan** [comment]
In the Brand Guidelines webpage, there are three logos that Hugging Face primarily uses.

They also have a space where they host logo in few image formats. It is available at: [https://huggingface.co/spaces/Chunte/HFBA](https://
huggingface.co/spaces/Chunte/HFBA).

I think this should serve as the data points for the icons and can be used in creating new badges.

**Comment by chris48s** [comment]
As I say, the named icons used by shields come from the simple-icons project and there's an open issue/PR to add a hugging face logo to the set linked above.

Shields badges don't show logos by default (that's a user choice) and we don't add specific routes for badges which only show static information (it is [already possible to make these](https://shields.io/docs/static-badges) ).

I'm going to close this because it seems like this request is only about icons, and does not contain any concrete detail about data points (e.g: version, number of downloads, likes) that would be fetched from an upstream service. You can re-open it if you want to add those.
