### ISSUE TITLE
pytest badge

### ISSUE THREAD

**Issue by Formartha** [badges/shields#10061]
### 📋 Description

Heya,

Can you please add a pytest badge as an option?

### 🔗 Data

https://docs.pytest.org/en/8.0.x/_static/pytest_logo_curves.svg

### 🎤 Motivation

For enhancing GitHub profile expertise.

**Comment by calebcartwright** [comment]
Thanks for the request but going to close. Our service provides the ability for users to generate static badges, but we don't create static badges on behalf of users.

**Comment by chris48s** [comment]
Just FYI, the simpleicons set already includes a pytest logo, so you can already make something like
![](https://img.shields.io/badge/py-test-blue?logo=pytest) https://img.shields.io/badge/py-test-blue?logo=pytest
or whatever
