### ISSUE TITLE
Mastodon "remote_follow" URL does not work for newer versions of Mastodon

### ISSUE THREAD

**Issue by ramsey** [badges/shields#10078]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The badge generated for [Mastodon Follow](https://shields.io/badges/mastodon-follow) includes a link to follow the user, using a URL constructed as:

```javascript
`${domain}/users/${username}/remote_follow`
```

The source code for this is available here: https://github.com/badges/shields/blob/60056fcd6c27341ef01d988595f854336c0707ac/services/mastodon/mastodon-follow.service.js#L61

Unfortunately, the `remote_follow` route was removed from Mastodon in version 4.0: https://github.com/mastodon/mastodon/pull/19319/commits/f7a13998a24d5958a18a9907ad3a52f2eec63c6a#diff-9185eb9ca37cb2c8878e5006b357d404910be53f0089687b8fbb52be98296c61

So, this URL no longer works for anyone who has upgraded to Mastodon 4.

### 🔗 Link to the badge

![](https://img.shields.io/mastodon/follow/000000001?domain=https%3A%2F%2Fphpc.social&style=flat-square)

Here is the SVG generated for this badge. Note the first `<a>` tag has an `xlink:href` of `https://phpc.social/users/ramsey/remote_follow`.

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="132" height="20">
    <g shape-rendering="crispEdges">
        <rect width="97" height="20" fill="#555"/>
        <rect x="97" width="35" height="20" fill="#9f9f9f"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
        <a target="_blank" xlink:href="https://phpc.social/users/ramsey/remote_follow">
            <rect width="97" x="0" height="20" fill="rgba(0,0,0,0)"/>
            <text x="495" y="140" transform="scale(.1)" fill="#fff" textLength="870">
                follow @ramsey
            </text>
        </a>
        <a target="_blank" xlink:href="https://phpc.social/users/ramsey/followers">
            <rect width="35" x="97" height="20" fill="rgba(0,0,0,0)"/>
            <text x="1135" y="140" transform="scale(.1)" fill="#fff" textLength="250">
                3.9k
            </text>
        </a>
    </g>
</svg>
```

### 💡 Possible Solution

I'm not sure what the correct approach is for this. Otherwise, I would have submitted a PR. 😄 

I can't find what new Mastodon URL we should use to replace this. Perhaps, we should just link to the user's profile instead (remove `/remote_follow` from the URL)?

```javascript
`${domain}/users/${username}`
```

I'm happy to submit a PR, if others think this is the correct approach.

**Comment by chris48s** [comment]
Having read some issues on the mastodon repo, I don't think there is a way to directly link to this now. I agree with your suggestion - just replace it with a link to the user's profile :+1:
