### ISSUE TITLE
Waffle.io badges missing background color

### ISSUE THREAD

**Issue by jhermsmeier** [badges/shields#1008]
Badges where it displays `0` look fine, but where the count is non-zero, the background color is missing. Examples:

![](https://img.shields.io/waffle/label/resin-io/etcher/does%20not%20extist.svg?style=flat-square)
– https://img.shields.io/waffle/label/resin-io/etcher/does%20not%20extist.svg

![](https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg?style=flat-square)
– https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg

Overriding the background color also doesn't appear to work:

![](https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg?colorB=334455&style=flat-square)
– https://img.shields.io/waffle/label/resin-io/etcher/in%20progress.svg?colorB=334455

**Comment by paulmelnikow** [comment]
Hi! Indeed, looks like a bug. Could you make a pull request?

**Comment by jhermsmeier** [comment]
@paulmelnikow oh, looks like I didn't get around to that in time – thanks a lot @ritwickdey!
