### ISSUE TITLE
GitHub contributors NaN

### ISSUE THREAD

**Issue by tedmiston** [badges/shields#1010]
I'm currently seeing the contributors badge on [requests](https://github.com/requests/requests) displaying NaN instead of a number.

<img width="1041" alt="screen shot 2017-06-10 at 1 01 20 pm" src="https://user-images.githubusercontent.com/366688/27004747-ee5ed524-4ddc-11e7-96f2-7f77ce08d98f.png">

**Comment by erasche** [comment]
I am too, and going to https://img.shields.io/github-auth to try and use the OAuth to increase rate-limit returns an error.

**Comment by Daniel15** [comment]
Looks okay now - Have you seen this again recently at all?

**Comment by tedmiston** [comment]
I saw it for a day or two then didn't check it regularly after that.  Do you think it's rate limiting?

**Comment by Daniel15** [comment]
It's possible, although I thought that the badge would show "inaccessible" in that case.

**Comment by paulmelnikow** [comment]
If this issue is still occurring, please ping the issue.
