### ISSUE TITLE
How to use jsonpath in yaml file？

### ISSUE THREAD

**Issue by ChangJieWuAi** [badges/shields#10113]
:clock11: **When did the problem start?**

I have a problem using jsonpath in yaml file

:camera: **Live badge**

![Dynamic YAML Badge](https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fargoproj%2Fargocd-example-apps%2Fmaster%2Fguestbook%2Fguestbook-ui-deployment.yaml&query=%24.spec.template.spec.containers.image)

:wrench: **Is the live badge working?**

no

:link: **file link**
I want to display the image version in this file
https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml

:lady_beetle: **Stack trace**
My query statement is
```
$.spec.template.spec.containers.image
```

:bulb: **Possible solution**

What should I write when encountering a minus sign when using jsonpath in a yaml file? I searched for information but couldn't find it. Does anyone know?

**Comment by chris48s** [comment]
containers is an array, so your query wants to be `$.spec.template.spec.containers[0].image`

working badge:

![](https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fargoproj%2Fargocd-example-apps%2Fmaster%2Fguestbook%2Fguestbook-ui-deployment.yaml&query=%24.spec.template.spec.containers%5B0%5D.image
) - https://img.shields.io/badge/dynamic/yaml?url=https%3A%2F%2Fraw.githubusercontent.com%2Fargoproj%2Fargocd-example-apps%2Fmaster%2Fguestbook%2Fguestbook-ui-deployment.yaml&query=%24.spec.template.spec.containers%5B0%5D.image
