### ISSUE TITLE
Open/Closed State badge for github issues.

### ISSUE THREAD

**Issue by justbill2020** [badges/shields#1011]
I just forked the repo to add open/closed issue state badges, i'll send a PR when its complete... 

this will be useful for our Readme file's known issue section.

https://github.com/evancohen/smart-mirror/blob/master/README.md

**Comment by paulmelnikow** [comment]
Hi! PR #1012 has gone stale and needs work. If you'd like to pick it up, or if anyone would like to adopt it, please do!
