### ISSUE TITLE
PowerShell Gallery

### ISSUE THREAD

**Issue by ebekker** [badges/shields#1013]
Any chance to add support for PowerShell Gallery?  It's nuget based like many other services here.

**Comment by Daniel15** [comment]
Would you like to try submitting a pull request to add it? If it's NuGet-based, it should be very easy to add (see `mapNugetFeed` and `mapNugetFeedV2` in `server.js`)

**Comment by ebekker** [comment]
@Daniel15, great suggestion, thanks -- I've submitted a PR.

**Comment by cormacpayne** [comment]
@ebekker @Daniel15 Hey Eugene and Daniel, I saw that this functionality was added in commit https://github.com/badges/shields/commit/ce0eb7b3369b81205e56beac9461dcfd25d72deb , but it does not appear that the functionality is working (the examples added to `try.html` in the commit are both broken, as seen [here](https://img.shields.io/powershellgallery/dt/ACMESharp.svg) and [here](https://img.shields.io/powershellgallery/v/Zyborg.Vault.svg)). Any clue why this would be the case? I would love to add this to the [Azure PowerShell](https://github.com/Azure/azure-powershell) repository 😃 

Thanks in advance!

**Comment by Daniel15** [comment]
It's likely the site hasn't been redeployed yet. @espadrine manages all that stuff, so I'll let him chime in here 😃

**Comment by cormacpayne** [comment]
@Daniel15 @espadrine perfect, thanks for the update!

**Comment by ebekker** [comment]
Is there a way to see what *version* of the code base is deployed to the public site?  I was trying to find a way to match against a tag or something in GitHub but it doesn't look to be there?

Or alternatively, is there any indication in the GitHub repo when a release is deployed, like a tag, a PR or an issue?  Or maybe a tweet or announcement some other way?  I couldn't find any convention.

**Comment by Daniel15** [comment]
Not sure, sorry 😢 . I haven't really handled that side of things. I'll try pinging @espadrine again as I haven't heard back.

**Comment by paulmelnikow** [comment]
This has been deployed now.

For future reference, to see the version that's currently deployed, you can look at the [gh-pages branch](https://github.com/badges/shields/commits/gh-pages). The deploy process updates the servers and force-pushes a deploy commit to that branch. Github Pages hosts https://shields.io/index.html. @ebekker @Daniel15

**Comment by ebekker** [comment]
@paulmelnikow thank you!

**Comment by cormacpayne** [comment]
@paulmelnikow thanks Paul!

**Comment by cormacpayne** [comment]
@jzabroski Hey John, here's an example of how we use it in the [Azure PowerShell repository](https://github.com/Azure/azure-powershell/blob/preview/README.md#modules):

```
[![AzureRM](https://img.shields.io/powershellgallery/v/AzureRM.svg?style=flat-square&label=AzureRM)](https://www.powershellgallery.com/packages/AzureRM/)
```

_Note_: the PowerShell Gallery badges are currently broken -- see [this issue](https://github.com/badges/shields/issues/2078)

**Comment by jzabroski** [comment]
Ah, the #2078 is why I was having troubles. Thanks!
