### ISSUE TITLE
Bitbucket not completely finished workflow returns invalid response data

### ISSUE THREAD

**Issue by ArcherEmiya05** [badges/shields#10137]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

We have a workflow that has success step but not complete due to manual trigger, the build status badge for Bitbucket returns `invalid response data`

### 🔗 Link to the badge

https://img.shields.io/bitbucket/pipelines/devsbitwise/cryptonian/master?label=📦%20CI%2FCD%20pipeline

**Comment by chris48s** [comment]
OK, so what's happening here is:

We call
https://api.bitbucket.org/2.0/repositories/devsbitwise/cryptonian/pipelines/?fields=values.state&page=1&pagelen=2&sort=-created_on&target.ref_type=BRANCH&target.ref_name=master

That returns

```json
{
  "values": [
    {
      "state": {
        "name": "IN_PROGRESS",
        "type": "pipeline_state_in_progress",
        "stage": {
          "name": "PAUSED",
          "type": "pipeline_state_in_progress_paused"
        }
      }
    },
    {
      "state": {
        "name": "COMPLETED",
        "type": "pipeline_state_completed",
        "result": {
          "name": "SUCCESSFUL",
          "type": "pipeline_state_completed_successful"
        }
      }
    }
  ]
}
```

We fail validation with

```
"values[0].state.result" is required
```

so I guess we would need to make the `result` key optional in the schema and then adjust the code to handle the fact that property may or may not exist.

https://github.com/badges/shields/blob/96525e52d7d1589916f3c035779565b4a7297c3d/services/bitbucket/bitbucket-pipelines.service.js#L84-L86

**Comment by ArcherEmiya05** [comment]
Any update on this? Thanks

**Comment by chris48s** [comment]
fix for this is now merged and deployed
