### ISSUE TITLE
chrome web store "downloads" badge actually shows total active users

### ISSUE THREAD

**Issue by rahiel** [badges/shields#1016]
The badge says it's the number of downloads, but it's actually the number of (active) users.

For example, on [my extension's page](https://chrome.google.com/webstore/detail/archiveror/cpjdnekhgjdecpmjglkcegchhiijadpb), it shows "483 users", this is parsed by shields but shown as number of downloads: ![](https://img.shields.io/chrome-web-store/d/cpjdnekhgjdecpmjglkcegchhiijadpb.svg).

The confusion arises from where the number is parsed: `<meta itemprop="interactionCount" content="UserDownloads:483" />`. The meta tag is misleading. [Here](https://stackoverflow.com/a/21255294) another clarification on the number:

> The number [of weekly users] you see in the Chrome Web Store is the amount of users whose Chrome browser has checked for an update of your app within the last week. It is not the number of people who have installed your item.

**Comment by ShivanKaul** [comment]
+1. It should be something like `weekly active users`.

**Comment by paulmelnikow** [comment]
Woo! That is worth fixing! Would someone like to open a pull request? **active users** seems like a good label.

**Comment by RedSparr0w** [comment]
a temp work around until a PR has been made/merged is to add `?label=users` to end of the URL
example:
![](https://img.shields.io/chrome-web-store/d/cpjdnekhgjdecpmjglkcegchhiijadpb.svg?label=users)
`https://img.shields.io/chrome-web-store/d/cpjdnekhgjdecpmjglkcegchhiijadpb.svg?label=users`

**Comment by rahiel** [comment]
> Woo! That is worth fixing! Would someone like to open a pull request? active users seems like a good label.

I think just `users` would be a better label: it's consistent with the badge showing the number of Firefox users of an add-on: ![](https://img.shields.io/amo/users/archiveror.svg). Saying it's about "active" users seems redundant.

**Comment by ShivanKaul** [comment]
"users" as a label is ambiguous: number of users who downloaded the
extension? Who currently have it downloaded and not disabled?

"active users", or even "weekly active users", represents what the number
actually is.

**Comment by rahiel** [comment]
> "active users", or even "weekly active users", represents what the number actually is.

That would be misleading, the [linked stackoverflow answer](https://stackoverflow.com/questions/21248397/how-are-chrome-extensions-weekly-users-counted-is-it-the-number-of-users-who-h/21255294#21255294) says that number is:

> the amount of users whose Chrome browser has checked for an update of your app within the last week

This **includes** users who have the app/extension installed, but have it disabled: Chrome also auto-updates disabled extensions. 

The Chrome Web Store itself labels that number with "users".

**Comment by RedSparr0w** [comment]
Agree with @rahiel and because it keeps it consistent with the Mozilla addons, just makes more sense IMO.

If someone wanted it to say `active users` they could always manually change the label.

**Comment by ShivanKaul** [comment]
Interesting, didn't realize that disabled extensions also get auto-updated!

**Comment by AkhileshThite** [comment]
> a work around until a PR has been made/merged is to add `?label=users` to the end of the URL example: ![](https://camo.githubusercontent.com/36c132f36884cd35a727edbddf1b5da0c1214e114be5681297d87b0a8e11a911/68747470733a2f2f696d672e736869656c64732e696f2f6368726f6d652d7765622d73746f72652f642f63706a646e656b68676a646563706d6a676c6b63656763686869696a616470622e7376673f6c6162656c3d7573657273) `https://img.shields.io/chrome-web-store/d/cpjdnekhgjdecpmjglkcegchhiijadpb.svg?label=users`

Thanks!
