### ISSUE TITLE
Chrome Web Store Version “not found”

### ISSUE THREAD

**Issue by lmk123** [badges/shields#10165]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Chrome version “not found”：

![img](https://img.shields.io/chrome-web-store/v/ikhdkkncnoglghljlkmcimlnlhkeamad)

This extension exists in the web store as normal:

https://chromewebstore.google.com/detail/ikhdkkncnoglghljlkmcimlnlhkeamad

### 🔗 Link to the badge

https://img.shields.io/chrome-web-store/v/ikhdkkncnoglghljlkmcimlnlhkeamad

**Comment by smashedr** [comment]
This is now happening on all my chrome extensions.

**Comment by chris48s** [comment]
This one relies on a library. I've raised an issue upstream https://github.com/awesome-webextension/webextension-store-meta/issues/7

**Comment by henriquelbsouza** [comment]
Chrome changed the URL's from chrome.google.com to chromewebstore.google.com, probably related.

**Comment by chris48s** [comment]
fix for this is deployed - might take a few mins for old badges to drop out of cache
