### ISSUE TITLE
Discord Embed not rendering

### ISSUE THREAD

**Issue by sympherjim** [badges/shields#10161]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I created an embed object and added a static shield badge like this and sent this via a webhook url
```
{
  "title": "Embed Test",
  "color":  "11194456",
  "image":  {
    "url": "https://img.shields.io/badge/any%20text-you%20like-blue"
  }
}
```
I'm getting this
![image](https://github.com/badges/shields/assets/148425183/799721ca-1fc4-4ee7-b0bd-2f1b62e98ea8)

instead of 
![image](https://github.com/badges/shields/assets/148425183/a3693703-8d90-40d9-a40f-ca90acf150c3)
from https://message.style/app/editor

### 🔗 Link to the badge

https://img.shields.io/badge/any%20text-you%20like-blue

**Comment by calebcartwright** [comment]
Going to close, please feel free to follow up if necessary
