### ISSUE TITLE
GitLab badges are not working

### ISSUE THREAD

**Issue by ogarcia** [badges/shields#10178]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

It seems that several GitLab badges are not working properly. At least I have detected License and Release.

### 🔗 Link to the badge

For example, for [this GitLab project](https://gitlab.com/ogarcia/lesma), the project id is 42779682. The shields shows _project not found_:

![GitLab Release](https://img.shields.io/gitlab/v/release/42779682)
![GitLab License](https://img.shields.io/gitlab/license/42779682)

The same applies if you use the project path `ogarcia/lesma`.

**Comment by calebcartwright** [comment]
I do, although to the best of my recollection, any token should do. GitLab declined to give us a token with a higher rate limit, and in fairness I don't rate limiting has been an issue.

Additionally, I don't believe GitLab supports renewing/modifying the expiration date on an existing token so a new one will indeed be needed. I'll try to dig up the credentials (I thought I'd shared them privately in Discord), though anyone of us with a GitLab account should be able to create and provide an alternative token if I'm unable to do this expeditiously.

**Comment by chris48s** [comment]
Thanks.
Just set the new key. GitLab badges should be working now (or at least coming back as things drop out of cache).
I had not focused that we just have a standard PAT for GitLab. I'll make a note of this in the docs when I get a sec.

**Comment by calebcartwright** [comment]
Glad to hear it. Let me know if we run into an issues with the token. I think I selected all the relevant scopes we'd need but can't say I'm particularly familiar with them
