### ISSUE TITLE
llm trainning framework and libraries

### ISSUE THREAD

**Issue by pabl-o-ce** [badges/shields#10180]
### 📋 Description

- Axolotl: https://github.com/OpenAccess-AI-Collective/axolotl
- Unsloth AI: https://github.com/unslothai/unsloth
- Llama Factory: https://github.com/hiyouga/LLaMA-Factory
- TRL: https://huggingface.co/docs/trl/index
- Hugging Face: https://huggingface.co

### 🔗 Data

- Axolotl: [<img src="https://raw.githubusercontent.com/OpenAccess-AI-Collective/axolotl/main/image/axolotl-badge-web.png" alt="Built with Axolotl" width="200" height="32"/>](https://github.com/OpenAccess-AI-Collective/axolotl)
- Unsloth AI: [<img src="https://raw.githubusercontent.com/unslothai/unsloth/main/images/made%20with%20unsloth.png" alt="Built with Axolotl" width="200" height="60"/>](https://github.com/OpenAccess-AI-Collective/axolotl) https://github.com/unslothai/unsloth/tree/main/images
- Llama Factory: ![image/png](https://cdn-avatars.huggingface.co/v1/production/uploads/642fef28a043f0ac7defa8a9/6d8hJAhoJYfZzmAxxSLb3.jpeg)
- TRL: ![image/png](https://huggingface.co/datasets/trl-internal-testing/example-images/resolve/main/images/trl_banner_dark.png)
- Hugging Face: ![image/svg](https://huggingface.co/front/assets/huggingface_logo-noborder.svg)

### 🎤 Motivation

model card on hugging faces

**Comment by calebcartwright** [comment]
Thanks for reaching out, but my understanding of this request is for a set of static badges to be provided so I'm going to close.

Our service provides a static badge builder feature that can be used to create such badges, but we don't add any such pre-canned instances of static badges.

**Comment by pabl-o-ce** [comment]
no problem sorry the noise!
