### ISSUE TITLE
Badge of supported django versions from python classifiers

### ISSUE THREAD

**Issue by ad-m** [badges/shields#1018]
Hello,

There is PyPI badge for published python package version: [![PyPI](https://img.shields.io/pypi/v/nine.svg)]()

I suggest add badge for Django versions support based on PyPI classifiers. Each Python packages defines classifiers. Some classifiers define supported Django versions (see https://github.com/YourAcclaim/Acclaim-Badges-for-EDX/blob/master/setup.py#L59 , https://pypi.org/project/acclaim-badges/ ). It will be useful to list supported Django versions in badge:
[![](https://img.shields.io/badge/django%20versions-1.8%2C%201.9%2C%201.11-blue.svg)]()

This changes promote classifiers, improve usability of them. Classifiers is important for search engine on pypi.org (see https://pypi.org/search/?c=Framework+%3A%3A+Django+%3A%3A+1.11 ).

Greetings,

**Comment by Daniel15** [comment]
Would you like to submit a pull request to add this feature? We're happy to help you get started if you like :)
