### ISSUE TITLE
crates.io dependents

### ISSUE THREAD

**Issue by czy-29** [badges/shields#10204]
### 📋 Description

It's good to have a badge showing the number of reverse dependencies of a crate in crates.io.

### 🔗 Data

https://crates.io/api/v1/crates/:crate/reverse_dependencies
Then in the `meta::total` field, you can get the total number of `reverse dependencies`.

### 🎤 Motivation

This is an important indicator of the popularity of a project.

**Comment by erayerdin** [comment]
@chris48s Can I take this on?

**Comment by chris48s** [comment]
Yep. Go for it :+1:
