### ISSUE TITLE
Docker Image Size arch error

### ISSUE THREAD

**Issue by Qinka** [badges/shields#10224]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Shield.io cannot handle loongarch64.
Example: https://hub.docker.com/layers/qinka/dockerroot-base/unstable/images/sha256-cc1db4e19dcb60613ae7fa3e6e1c8600af609a0d606f48622e751220f609bce9?context=repo

### 🔗 Link to the badge

![ Docker Image Size (tag) ]( https://img.shields.io/docker/image-size/qinka/dockerroot-base/unstable?arch=loong64 )

### 💡 Possible Solution

Add tag for loongarch

**Comment by PyvesB** [comment]
Hello @Qinka, thanks for the report, a fix is on its way!
