### ISSUE TITLE
Color not consistent

### ISSUE THREAD

**Issue by shinokada** [badges/shields#10268]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

![image](https://github.com/badges/shields/assets/147320/c4f10c31-db66-4a72-be5a-ab68f9812af5)

The above badges are made from the following code:

```
<img src="https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&amp;logo=&quot;&quot;&amp;" alt="NPM version of svelte-5-ui-lib">

<img src="https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&amp;logo=&quot;&quot;&amp;color=&quot;&quot;" alt="NPM version of svelte-5-ui-lib">

<img src="https://img.shields.io/npm/v/svelte?style=flat&amp;logo=&quot;&quot;&amp;" alt="NPM version of svelte">

<img src="https://img.shields.io/npm/v/svelte?style=flat&amp;logo=&quot;&quot;&amp;color=&quot;&quot;" alt="NPM version of svelte">
```

When I use color param in different ways it changes the color. For example, 
1. the first one has no color param
2. the second one `color=''`
3. the third one with different package name
4. with `color=''` for different package name

It seems, If you define the color param, then the following badges use the previously defined color unless set `color=''`.

The `logo` param is similar. If you set the logo for the first badge, the following badges use the logo even if you don't set the logo.

**Comment by chris48s** [comment]
Not totally sure what you're trying to do here tbh. `?color=''` is not a valid value for `color`, so we're defaulting to `brightgreen`.

If you were to pass a valid value like a named color or a hex value, that would work as expected e.g:

- ![](https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=black) - https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=black
- ![](https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=00008b) - https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=00008b
- etc

I'm not really sure what output you'd expect by putting `&amp;logo=&quot;&quot;&amp;` in your URL :shrug: but if you want to use a logo, try one of the named logos e.g:

- ![](https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&logo=npm) - https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&logo=npm
- ![](https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&logo=javascript) - https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&logo=javascript

**Comment by shinokada** [comment]
Is `brightgreen` the default for all badges? I thought blue is the default color.

**Comment by chris48s** [comment]
It does appear that's what you get if you pass an invalid color e.g:

![](https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=definitely-not-a-real-color) - https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat&color=definitely-not-a-real-color

I'm not convinced that is the best fallback for that situation, but that is why that is happening if you try to pass `''` as the value of the `color` param

**Comment by shinokada** [comment]
Why do I get red without color param?

https://img.shields.io/npm/v/svelte-5-ui-lib?style=flat

<img width="92" alt="image" src="https://github.com/badges/shields/assets/147320/96365d58-22a2-4a88-9331-af50cf37c4f9">

**Comment by chris48s** [comment]
If you request a version badge, we apply semantic colouring
blue for a stable version, orange for a pre-release
You can also choose to override that (as you've said you want to) and just pick a single color (which then doesn't change based on the content)

Similarly, if you request a build status badge with no `?color=` param, you get brightgreen for passing, red for failing, etc. If you pass a `?color=`, you can override it. You pick a a single color (which then doesn't change based on the build status)

**Comment by akiirui** [comment]
@chris48s 
> If you request a version badge, we apply semantic colouring
> blue for a stable version, orange for a pre-release

But Github Release always using orange now. How to mark it as stable? Thanks.

**Comment by chris48s** [comment]
For the GitHub releases badge, it should use orange if the latest release is a pre-release and blue otherwise. So blue if this is off, orange if it is on:

![Image](https://github.com/user-attachments/assets/89541abe-df6d-4d2a-a57f-baf507e3de4a)

If you're still having issues, create a new issue or discussion and link to the badge/repo you're asking about
