### ISSUE TITLE
NPM Downloads by package author returns inaccessible

### ISSUE THREAD

**Issue by shinokada** [badges/shields#10261]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When I use [NPM Downloads by package author](https://shields.io/badges/npm-downloads-by-package-author) example, it returns "inaccessible".

### 🔗 Link to the badge

https://img.shields.io/npm-stat/dw/shinichiokada

**Comment by PyvesB** [comment]
Hello @shinokada 👋🏻 

Looks like npm-stat is down, I've reported the issue here: https://github.com/pvorb/npm-stat.com/issues/141

**Comment by PyvesB** [comment]
Upstream service was fixed, and badges are working again. Closing the issue! 🚀

**Comment by shinokada** [comment]
Why `https://img.shields.io/npm-stat/dw/shinichiokada?style=flat` doesn't work but without style `https://img.shields.io/npm-stat/dw/shinichiokada` works?

**Comment by PyvesB** [comment]
The badge works for me. There's a cache of several hours on badges for this service, maybe you happened to hit that?

**Comment by shinokada** [comment]
This is what I get on all browsers.

![image](https://github.com/user-attachments/assets/ff6f0f7e-c336-4a46-8843-0c0a9182d45d)
