### ISSUE TITLE
Is it possible to set urls to always open on a new tab?

### ISSUE THREAD

**Issue by slugb0t** [badges/shields#10269]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm wondering when I add a url to direct users to another site if the badge has a property to strictly make links open in new tabs?

### 🔗 Link to the badge

[![Metadata](https://img.shields.io/badge/Add_Metadata-dc2626.svg)](${url})

**Comment by chris48s** [comment]
Depends, but not on anything we control. If you put this on your own website

```
<a href="https://example.com/" target="_blank">
  <img src="https://img.shields.io/badge/Add_Metadata-dc2626.svg" />
</a>
```

it'll open in a new tab. Put it in your GitHub README and it won't because GitHub will strip the `target` attribute, but this is equally true of

```
<a href="https://example.com/" target="_blank">
  some text
</a>
```

**Comment by slugb0t** [comment]
Thank you for the reply!
