### ISSUE TITLE
How to use Mozilla AMO badges?

### ISSUE THREAD

**Issue by hckr** [badges/shields#1026]
How to use "Mozilla Add-on", such as:
version: [![Mozilla Add-on](https://img.shields.io/amo/v/dustman.svg?style=flat-square)](https://addons.mozilla.org/en-US/firefox/addon/facebook-post-screenshot/)
rating: [![Mozilla Add-on](https://img.shields.io/amo/stars/dustman.svg?style=flat-square)](https://addons.mozilla.org/pl/firefox/addon/facebook-post-screenshot/)

SVG file probably should take add-on name (or something else) as an argument.
Currently all values are hard-coded and thus mentioned badges are useless.

**Comment by perceptron8** [comment]
The same is true for Chrome Web Store and possibly Opera Add-ons when they arrive. As one extension may be published in several stores, I would vote for store name as a default label. This way one's able to tell which badge applies to which store. It's rather obvious that "★★★★☆" and "3.4/5" means rating, so current labels are redundant. Please, compare <ins>"mozilla add-ons | 4/5"</ins> against <del>"rating | 4/5</del>. By the way, <ins>"mozilla add-ons | 7k downloads"</ins> would also be better than <del>"downloads | 7k total"</del>.

Of course customized labels should be possible too!

**Comment by paulmelnikow** [comment]
Hi! When you say the values are hard-coded, does that mean you can't override using `?label=`?

**Comment by ritwickdey** [comment]
Hi, @paulmelnikow . Yep, It's hard-coded.

 I check that code for Mozilla AMO badges. This issue is for 
https://github.com/badges/shields/blob/c1a8166af26d79ec2b966a56b0d0b55920df6b8d/server.js#L4150

This line should be 
```js
badgeData.text[0] = getLabel('downloads',data)
``` 
or 
```js
badgeData.text[0] = data.label || 'downloads' 
```

Same is for rating|stars|users label

**Comment by paulmelnikow** [comment]
Thanks @RedSparr0w for the fix!
