### ISSUE TITLE
Mbin

### ISSUE THREAD

**Issue by chris-y** [badges/shields#10264]
### 📋 Description

Mbin subscriber count badge same as the Lemmy one.

### 🔗 Data

Public API: https://fedia.io/api/docs/

The following will get information for any named magazine:
https://{server}/api/magazine/name/{magazine name}
There's a subscriptionscount key which provides the value.

### 🎤 Motivation

Mbin exists on the Fediverse. We already have subscriber count badges for Lemmy, and Mbin will federate with it, so for consistency it would be useful to be able to get this data from Mbin too.

**Comment by chris48s** [comment]
> https://{server}/api/magazine/name/{magazine name}

Are you able to give an example of a public mbin instance (and magazine name if discovering one is non-trivial) we can call this on?

**Comment by chris-y** [comment]
Yes, there are others although I'm not sure if there is a list of them anywhere.  Kbin.run is another example.

**Comment by M4rtineski** [comment]
Mbin instaces: https://fedidb.org/software/mbin

Kbin instances: https://fedidb.org/software/kbin

**Comment by chris48s** [comment]
I guess the worry here is hitting the rate limits on popular instances.
Just having a look at other fediverse services (mastodon, lemmy) as a reasonable-ish point of comparison: In the last hour we've served just over 1000 from the origin for both of those so a rate limit of 60 reqs/minute per instance seems like its in a ballpark where Mbin/Kbin badges could get as widely used as mastodon/lemmy currently are and we'd be mostly under the limits - especially if there are multiple instances in play. It does risk being a flaky integration at times though.

I'm inclined to say go with it. We do need to care about rate limits, but not every service is going to be NPM.
