### ISSUE TITLE
AUR Popularity

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10289]
### 📋 Description

AUR
Popularity | 7.99

### 🔗 Data

IDK, however it is that the existing AUR badges work.

### 🎤 Motivation

Simple-icons assessing popularity rule 4.
https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity

This badge would streamline pull requests for the simple icons project.

**Comment by chris48s** [comment]
Example API call

```
curl "https://aur.archlinux.org/rpc?v=5&type=info&arg=android-studio" | jq .results[0].Popularity
```
