### ISSUE TITLE
Nix Version

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10295]
### 📋 Description

Nix
Version | 0.20.0

### 🔗 Data

https://nixos.org/manual/nixpkgs/stable/
https://nix.dev/manual/nix/2.22/stable

### 🎤 Motivation

It's like other package version badges.

**Comment by chris48s** [comment]
I am not seeing a link to docs for an API we could use here.
Is this functionally a duplicate of either https://github.com/badges/shields/issues/10025 or https://github.com/badges/shields/issues/9551 ?

**Comment by MichaelHinrichs** [comment]
Oh, it's the same as #10025. Nevermind.
