### ISSUE TITLE
Scoop Licence

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10297]
### 📋 Description

Scoop
Licence | AGPL-3.0-only

### 🔗 Data

IDK, however it is that the existing Scoop version badge works.

### 🎤 Motivation

It's like other License Badges.

**Comment by chris48s** [comment]
Scoop's manifest format does include a license property.
Example: https://github.com/ScoopInstaller/Main/blob/ef612ca0fc7ff2c3a6eee21eb896d88f18368adf/bucket/ngrok.json#L5-L7

**Comment by VISHESH0932** [comment]
@chris48s  can i work on  this issue?

**Comment by MichaelHinrichs** [comment]
Yeah, anyone is welcome to.
