### ISSUE TITLE
Snapcraft Licence

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10299]
### 📋 Description

Snapcraft
License | AGPL 1.0 or later

### 🔗 Data

IDK, however it is that the existing Snapcraft version badge works.

### 🎤 Motivation

It's like the other Licence badges.

**Comment by chris48s** [comment]
Example call:

```
curl "https://api.snapcraft.io/v2/snaps/info/thunderbird" --header "Snap-Device-Series: 16" | jq .snap.license
```

This property is exposed at snap level so does not need to support `track` / `risk` params

**Comment by davide-pi** [comment]
Hi @chris48s  I've created a PR to add this badge #10520 🙇
