### ISSUE TITLE
Snapcraft Last updated

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10300]
### 📋 Description

Snapcraft
Last updated | 21 June 2024

### 🔗 Data

IDK, however it is that the existing Snapcraft version badge works.

### 🎤 Motivation

It's like the other "Last Updated" badges.

**Comment by chris48s** [comment]
Snapcraft exposes a `released-at` property.
I'd probably frame this one in terms of release date rather than "last update".
This is exposed at the `track` / `risk` level so would need those params like the snapcraft version badge.

**Comment by abdullateef97** [comment]
@chris48s I'd like to work on this, how do I get started

**Comment by chris48s** [comment]
There is a tutorial for adding new badges at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md
The code for the existing snapcraft version badge is at https://github.com/badges/shields/tree/master/services/snapcraft
You might also find it useful to refer to the PR adding at that badge at https://github.com/badges/shields/pull/9976

**Comment by Aditi-908** [comment]
Is this issue still open?

**Comment by chris48s** [comment]
yep
