### ISSUE TITLE
Add To X badge

### ISSUE THREAD

**Issue by tylerl0706** [badges/shields#1031]
In the age of chat bots in every chat app, it'd be nice to have something like this:

[Add To Slack](https://img.shields.io/badge/Add%20To%20Slack--green.svg?style=social&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAGcAAABnEAIAAADCsxftAAAACXBIWXMAAABIAAAASABGyWs%2BAAAACXZwQWcAAABnAAAAZwAqn3%2BLAAAABmJLR0T%2F%2F%2F%2F%2F%2F%2F8JWPfcAAAgcUlEQVR42u2deTzU2%2F%2FH%2B%2BZb3fq1KqZIZGw36payM9J6S1RKaVOpoR1RKo1WDZIaS7JUKlmzFTKEsjOWkH0GY5%2FBMAYzZju%2FSff7%2B3W%2FN5Waz9yr5j2Px%2BtPnzPnPL1f57zPOZ8ZB4QhDIHEOGEXCEOImjCEqAlDGELUhCFE7YeLHlAD4pkvOifjXtHUizZc3kR5kbLdpKZ7QcKO1fBuWtJ5w1BqSW6ALZ0R3FSd2AhcuBtZpULUhDGK4Ej1hzYH92Sm7963htQeFgj%2FN4kUFgaHj6jksGC4WPfKhBOr8cwr5N%2FyXYb%2FDFeImjBGDFY%2BpaPiaGdWTKLaxi%2FgNYKSTSJ%2BU5xIJzVOi0kXoiaMTwTXcEiM0tilH0fTLv42yP4E3P4IF8UW1v90LSm2EaImjD9FX3ehKOr490P2sVImYkU2AfAKzObghagJA3AvMcdR9clxkUXKxvxFjaeP4dOZi0nSOZFC1IQBGIzmHKwTqYM3tYfxHTWe9j0u4F5IFqImDDBwvXLW3QwoIPugnXkxzmoTgROng9kvRO2njv6cshYPAnSokdrD7sn2DxHa32QeF6L2U8dgSZ36kwQIUftgoycLZp47I0RNcMH5o7D5DypvslwpuuV5PCBC4NIQ2mhANGm5ObjKKWfShajxOTrc6bP6JJ8U1s8v8D%2B7qMgpNuLAiex3wbcPteWKhpxxan%2BblPD4xZ7mlPLL%2FYOsjKHtf1sPZQBZDrcr%2FsVVfRFIc1sgfPxQTvu4NydH0bZk0Ao6OmcwtJl%2BqSXtiT2BD6XxYR1SmOVVli3eXuzqS61GIZwGS9JAIbp7PG32UDEnmLvlp0Bt6DjHjMXwdqy2e5O1qjvF2GsQgcBiMZgRVRObhLmzKSktzm9z%2FIpmank7OALSgL%2Fgu4lGfzsLfRFyG12Rv%2Fzs7BEb0Qp6QH%2BnDeMwMzulu%2F2XHgV3x4qMZgdbmcJfCCI2NjgcHj%2BiHsXl4%2FEopbd7GooKUF2mffdBAmgEXT8gagP%2BLNbQk%2BP2%2BT4RlxFa7wH6AmR%2FVSPsK0wApr3K%2FbU80AGxQKAzG5Zdt0fZSlJvWKBsP4Q2ahx9UPXfYAfHaagVNAEaoHWtYkQxu1PntJ%2FvOXbreOWM5pe2K3lgTfkCWJ9XN1wJvj7WoSmz61fgBcoB4UdBbSkIAQ6O7iWoF54IPR40o4fsY5XHxmKuR0Q1nis%2BK9C01gbQXGJX2Ysm%2FU5IUGOGPYErVOcGyyoYJvW%2FPZloecuoUrw5wXZm4WQ8%2BC6wRlJbXDGekHWKPJ866wdBLTOTFIFPQehjEzBu3wXZR7o2%2FJWcz7HOGIYJrUKghQ%2Bl0vGuz%2FkAFjcsBr6wRiUYqaAaZeO3bzH1iqjHSrVnlnLoOG3Jo2FBJmcu8IAowhMhgewjPWdS7FKf2m%2FJCuLMHsuoDQAmoJ%2F0LtgfGcsvyD7W%2B%2BPqvHLyBWqjJyna5amkJp6NDo0CLMBT2Vr54EB5EJ3nl7DY7%2BoEj8dqZ5Bc9CttGSQSjdbW%2Flgtf78Zu0bcZlF%2BZrUk1Kh90DSbdnpP%2FBhGrX85y4KRv3Jb8h5PByhQ26OXGf9oL1gJwsA5AbGGBxe5WV298f4GPSOCRedZoVztluBABZHoYr%2BMxY%2BvWnqkqZlZiqKjtBf%2BFaxP6EG0s7bSye2JoRGRgkHt7rMa9zaRMYxa1ePe5o7tiLnY55grUKCGsMZmYQLrjPukyIYCtdFTpf3uJn8cB5ocFg2H12KCnyuIxjT4T1rsfO2lx4CanGUZuk2r%2F6vAGkGPYh4m2nGGbbQJatSuV5U1EH15LsTg%2BdBYRK3kDkWyuR0SyD5SP4fa3VmvBUTZcGm5q4dEKUfGJvkbLl537bpHndpayxJ0oxYHefjbwfqEja64abx6h41ivnnVHqhRu%2BFS7k0EPNCGAHtMotbk0P%2Bcoqf3DhuIMYMOtd3TMjcExXIjgD2Q53cZkNfxnN5AJoI97g2dpN%2FriOFWFbTk2p4qHIcvtTqKiTd5yC%2BwPqGH0de0VU5OSkgLK4IatfvOdfT2qDFsoBxHbhf34KYHabf84BDmtoM8Gw2o%2BZ16jLToO8EaAizqIeZ19tpMX1I5daaXSvXGVoRtbaEZQfmvw3N8Rpi963wIUftgo14PxU4H8Z5YjO%2BABLXDuDx8FW5Tl2df9ZgvdqB7yvHJb6C2Ud%2BBmrzMxtG2rW8Ns4ntmIkiNVEneHlVW7XqnrYtPEcwszn15UE6lZtulm6LPIF20J4GHWqWOjdVV9FtlPLqKydDgZpzYflOYh9bhuvO7RnzqOWVdu5pCEUs4C0OLkGHmplPRtHDQu5zcAEs%2BEQj6DwrZFGHmNXsHVluZD2qnndIdWNrwGnnwisE028eqhj8AysHT5PtShDmNkv0de1FJ9USNENv8xeyM9pFxwjsxs39uowJP0gJlxnDwbNDjA6l4f08IcxtE7CPMPZVkb3Ujj9mbH0Mlgw7PPsK2YXq5B1QndJ653RuYRzh2NdkrK%2FX4%2BvCF7pdhtxGLz64ZGvIe2IJP2zUwaTYoB5V6dF7ZSDxB9wDdT3%2BLjAFkkIuwgCbisHoHEn0uF1gb5S7J0nax6dGpTXxNKMwimBvcxLaCfWpxnTca0ekHdpP%2BzCENirmFmQQajM172mFyze2Vg%2F3Cl%2FuHVGd0%2BpKukAPYpr%2BsCc7ClS7ZjVeQ8hgozFXvwusldgUHliuieG3S5eaRI5z9ZAzePDkKl4i2kcMlSP%2FNOCg6282U3Bn8aaCKX7a2OJC8JesnLxkd8yENLdd1152ck58dsi6r2rVEVw%2BvsZp6C2p0SDKk9jb%2BZA4rt%2BBoQqIgAYGfvBDRCxTrhxHzPhMupq%2FyagyVjrGW8cu8e1t6tKNEQOubnLaD7yuVkmwfcxQDRIS3t4o1J9UzNsLZWu%2BJP18rpuAUPtgo7Lh5e6zIbdR6wezbCYOF3Wb%2F9SG3bxVZOXFjrfaDbkRxo1B5Lw68z7bwbecVCAF9oF%2FTAj0vJobqWLWq8%2FtHKTwwLqbiLvNWWoZaeiaKLf%2FQfO1WZJzfW47iXwCrBHUYG%2FUlNDHgkTtVN5r2zdk5Fl0gXYyhDYq4tqkX209lHe%2FAnlhXolmw8KQ5oa1pN5qNeq%2BQRH2ZW4QmA3%2BwSFQ1HBxXW7EHQgJbALmMs8KkzGeOh2J4M7kpeWRnq5lcrsfEK9NlKD47EN1S8zj5SfU1%2BP1scp1%2BJNdLlozcQfxSwUG3Ct8oVWiV%2BxOQz5DtounOidMXbW0ZnqHem1SNShWLkdFJ7Oec024NWBMhUBR61vCTGSJ602ODfG8IJf7cOE1JUkJHycU99uQGknncb2voSz2rU9Lz7koUBs1j9h36%2FsWB%2BboG9rax265VGlZYaw896pmpfndL1xU3zo91FgOTuoOC4fL9tZmso%2BKgTEYEKI2SGajOQE4qS73PkLA1Dp4u7wdu2gqIVEvM%2BL%2Bkxf8xeuvutLj2d6QIIHaKOeNViYbeQLto33gK7ee3s%2FANFxctO56%2FIJxWX48ZXlgi7JD88kQphyKRAuLgMt%2B4n0fryLTlGdxk5gZNIWfETUuAPRd7CBODE68y7svM0CtTrl9mr1bkSahaLiOVffxkOyOTl2e6S4xzdsdZQMdanIS%2Fij0Desi3OK6SgEBZ4drJcCtwrzazBZ%2FAqxD7%2FWIvoumFs7t7Z2s5awk1cDpKirELSGH5N6SBt5nrK86%2Ffb%2Bnv1chlRjflzET4Ha0FnORe7ywkPdE2hSgVfqAtvNzmwuQtWPtznx%2FrrE54fE%2BkhBf52lbI7f0xtLIcxtM7wxqFN7fdIOZLsK1EZ3RpR5JH3IWFZ%2BLqJa79AJd6avuBJPCtiuEtyw%2FmmzvByJzYNG5nvO8fZmZ8pZlo6td7SNBjUt8AxkZz8iu1GPXlxd0tngY3OUt8yu%2B4ZaVCGegLgUKRXsCbWN6gdGtj8tEgxktujCFQSJOxeKXhdNjGv2j11chK95ul4%2BkDTEs8KF%2FL2LQA6P9F8UwnVimvZN%2BqFQ4y4HRsD56Yb6HNJ9m%2BPvy4PfPzB73qUSstokxnu7oo5Ahxr8sF%2F%2FjQ7r0wX0Oic%2B41WJo%2BKHPNCVbs30dFTH0Z6BHqOhXFYWaAb14DXFGBtm3ArpZb5gOIxe3zg9pv9HQo3z%2FFmzf9dLGyQPsmp%2BDZV1Gk6mjgjX8Wu6kQZhbpvpfQt1dk9salVW%2F3e1uRFHwfe64SsQzYtSDNuqekS6ljDCmR8q7584TjgQXplzL2IYC1nogOs9mWF0%2BOIPglpz8YAPo802mWcNi6AwHf1tkWFPz0Bto4iGSIunMz4Y91e1zZ8nRHTuu0VN9knKrVkUzY4o%2Bg7mLJAP2sFXHbbhjOuXb3IjzwxXk3OHDjXyzchffl3HvcZUoIaPedQeJxEIpPHQzW%2F2BqVtzn7Ds1FnlAV0qMm2%2B724sdNatiC%2BbtYndwxxeOL1mPJfiE%2Fjq1rsus1bIwbXDe0Ex0E6ePuN%2FToAiCCNYp98awsVUhsNhS%2BgVzToRpWPYdQ4Z4AI2HjudXFUfSp0qFk34tbUceE9%2FhvQ%2ByDMbZO80aije2alIrNm2uzGFeDrr7SUshuH4o43L%2B1ybrIamMBAgRUgDvD5jsJAfVVDgDbkNir9ZpfF8TGMWrcig8HSsIHjYvGQr%2BBWSj6TCjGGBDIx3lwNJdVyb80lmwO3U7fEzG2YTcukJ3M9gBXwgrpzOYv7y1tWk2eE68n5QWij5yOKfhXh7hg600Mdk6i1B9LhzPk2q3EJ%2BFKoUduHTp%2BQkyUx2fs66uR3gQXzxqAuSqn7OlyaqtT%2FxMH5vNqa2EXuFnrVWC2M8WbF9LP%2BT9lXuf4cQV1U5oAh0E9BJXNMzCG10RC4JB1Tbxi5d0yiRu1lPmPv5U2l86GvSFk%2Fxi2oK5Kr8S9zGU3hYx4PLNT8al%2B4U6XSpMc3rjNWbI0xvInXi0oCmEWfODkiio3FOBXN7WI0SQiyiwdFq8Pvr4XcRhe%2FTjjwfGwuCw7yZi6Fl9tLAxp9BVICJazMeXY5dPZnwPLkgSV3F%2BPkq6j4yP36meXoaLObe%2FWWJDnfqULoY5O%2F7gzczbiKna%2BIguxiztYBg9bTZOVwC%2FkpENrouYhjihXcbUNzKKPfQ0Cx2zgYhn%2B%2BSs1bqvId8Resblu7l0He3fvttIJUentu0Z67MzRy1lYRgAO7m%2BMOyQo0jtR8pEtA1%2FnN96Y75kZLyHn7oew%2B4CXp6dPltFLhQFDSdWnVjKizbn26hCT1O7nDZ3G%2F8aaC0Ya0Dr%2B7bHvuXY6gXuHOBp2grGd8St32xRCvRqXps%2FGksC%2B9WegxdxLXmJGKE6%2BbQPFybAixa%2BleGnVmFrER9i%2BkKZEIgyGRn9BGcTbSuE1ee7qj7OC8l%2BOLrAAd1AI831Drc2L2sJ3OkYvx9e8gRO0Eb1WItzcvpBHE1KxDVW77LIt45uvmruv1EnfnynDG4t8VmHnYaMy1gttd0xufCdRGt9bcfOgzjMVC6IDrCU9PNJ%2F6pwencDdwHw0tLR6P76AwLsHCzrcuUs05q0KsE29Grh4RrM8rCXYZ6dMz7TIl%2FBgo5JYCET6g9iHemlLO0xi2fYXbCBp8AMv6vdpZFBYTXO9tr4W3ncoP7Zrf5zp4lW3Buezze%2FWrjE1Q3xt1KX63NkVboDZ6YaCwjUieH35J3gJCG10cHq2ApvfggkrKe9yuvoyUaz2yYsjhIQ%2BsTuSGbwRrJK0VpyA3UR29YhPq%2BLfdzn5%2FhqBYvzuPFuhgULy8HjlavE4vKTxLWO1NqwatATky5GxqQP841lV2y18fVbW3N7%2Fj34gZ2AiMPXSobXqWFuu3mTWDO4vdIyDWuLwPm9L%2FKmIH%2F1ajuDBbuEpL4B09%2BGDdhIPN8htKcSssFAJqMiSiN%2BnwGawRtOnGfNyRh6wrDSodND4fIqLUDHmy%2FCN1Ggc7JzsGlqQ0XLAxw2Xha2z24TLw72zW4FLxZXZLCjMIlzH9VW9acjJCSJ69b6jtzNfs3cNv8P7SpHUtiAVXd5RkGD4gQpjb4NgYjHO%2BaGdwQ4NAbdS6duujjd%2B4Gq0IQ8IVWzoxz%2BHEuruHGuTXlsmqVSj4FeVIcxQVi4pkZP6j5XOl3ml4EVtg85C2ggGOsu981NNZEB6N5BwFU8AG8mvGNKZXfSitkv6umTHgzmijL2M%2F5kS8f7kK7%2FNN4buhxi7zBtQ2eoNRbpusKFAbTRzEk0zI8uGH5Wd8Aay6MD%2F4r63KXsvgfXWVyE75jWXHNbwUgovqZJCK8I%2FB%2BqsWq0kDpc0NzXPl9rsJBjWeTXc6%2BAIWIIz8Zt1%2F6E9k1KynniNN0WvDBmAsoEPNkJC25V4p05qTwfYS5LfrWZ9K2nX7T2B1huHhcq0FPv5wIl7XylFeo%2By1VpPCuSKyzHNFuc%2BDNYIq1DhLTjTMEJCNzpkXYOnIdR%2FUZdwZY6iBScAb7Ny1LHNu0BIIc9t8bBTmcq4FubG%2BSKA2ml%2FnG6zUBvM9BE%2FFRx%2F1k1csF9eZouBeVC2zV1Hhm8D6hJa9k2JqTCY2w8SQpyEHrkLc73AfV44aNbhxrKE2HP6za22yANQ26qxa1oZVhfBr9IMKUM2e3IzvTOrT86Vhp7S2rsc5thX%2FKpOqSOMXWJ%2Bw0d%2BkGUorGtpg7P0ykGe1MhmDY7vBdvZMtueYRK1OrW8u%2BTeEKTYe4wcdahszUhn35jGlOf5sI76sNAFgse3axSgifa7%2BhslvOrZvsrzR3wSbp2x5hjcw4rzhaeGpVflEqW4NBHSofdAae4lKw01Qo9bhsomMPgXhsgDymAP8gcWeWZkJjwwgzG2K2ATMrWxLMpzwYtQtZAEqoLJfdkT1yPT1PpicOrXjhXGVS3jT8nkoy%2BQ%2FwBpheGpSJV5t0oMatbJEKY66JbERJoo8ARFqc5CH%2BvIDCa%2BsxjJqwxG4sE41ZyPUNnrtZtm6pK8q6nL%2B1SnSG0s79sgwfTdJxcTMrbhpvUSXlf1wpx%2F%2B%2BkFqnAQj748v1pRuUzoIIXAsGTHFqIaEuarmZZCsPSctizmTxr05QGY8GfOo4Ql9CZ2SCBlsJOY0dKhtoKYG%2B8YPiXN2sdL%2BBJYnhU6zpyU%2F8XlNJj029b41r2mfpJZVJK%2BjZ48GrE9oEw9Nm3IdqTyNDsht1EBy5sZ4%2FkLWIvVrjU3e0L7iekIb%2F3YL%2Ft44DFKA595lWRKPKBDmNiVsKubWm%2BO1G0tD%2Bk3CErP0yTN2rb19pclBss1q8INNQJEVaookaje9%2FFCegNBGXRdsU8vnrUZhSOvvanM3zBP5mPzKvMqzm32gbVd3Kt%2B22%2F85cb%2Bijp6rz0e83mL8Eatj5G7W6yIurrEp0Dq%2F%2BoDJZduQeTM2GhLJvIxlKZiKVKPU3MkHVItXS3OVzkOY2zgy%2F6N4vyFw7gJzp1G1cBryQNOgzJVjXZ26FiE%2B1YzDufXV5WAQEMCoX04zZlCrH09b30lCXMEWY%2BJHDZY%2BNgtzD2ERJ%2BLeqbvH6ZItRevOWrCNpF4FS9SRV1cXnaq5gqeimpoItGi2tl%2FdMdjWQ%2B8EgxqxASaJtC7fLpWt6Qq1jVb3ScpvlPxMe2YjLZr8pG4enUQO25uNqe4vfvYoJ4s7tc9ucDKURyP%2FaaENYsElc5WsvidiX8QrA%2BODuPxc9tY5XdcrynbLtZ6s79jert42N1QHq64mOllT%2FQNYn1AV0RmaauHLxU%2FsKBIQasNaO0cizmgT5KtRpQVhK9p4c0RJ5Enec8WQh5tMJbWtgkivdjTcetsvF7IjI4Lj33OD1gi4gMnvX2YZY7%2Fd%2FnAt3iJv4n%2BBlYm5i7B6EeuxQffOta32t7UqNzrvWKPOnndE90PGUhsRrBHU%2BtScoPUXiB08CARloxaw%2FAO1xXrSfUrBEBZ1tReiFP3aDhmXorxoW4Ls03Ac%2BS4j6nXBjN0YQ63BjBbZ5YvIjC%2B6%2FYtupjPuTKZWv5HDzjINKYlI3SL1FaIi%2F7HC71G930UztfVqs2A3D0ULMLedKreSitEs4xteVJkBRdnydwgvBSvCrpOn5Ke25funwoMGZ1bvDFwv%2BLEbC6jNGyKydOgzXsWXRnSdPjkl8N72AwvK1kmqa4j%2BW3PZ94P1CV3KU43Q0%2BKKO5YK1EZnSoQb3ftGsFpkAhUVyqfoTFNwwYcfGyc%2Fv03RNxZeQmoLewGX%2F3hrn%2BKa7LKlFrBBD6j5uVH7lXmDlUc3Tn9UfqB7nq3uwzXNVCUl60AiUXwQufPDkLgTxJCbDSCB7CM9NXGO3XpZIgU2F3lEQDbqCss7uLrYSrpRqegLYBFlLirKlR3XaFdA4adZWslrtp70PgfvIrWEZcAXfeGk7uxwGTk5jkq%2FTtPAz4TaHlYNO5sekXG5wqz7sr3Uo6MtusrjbFcT68UpSMORhiTnBGy6%2BVZ1CdG5mirQoaZnIxqpbVhdDnM8JC2g3PZ%2Bb%2FRkeYeUndbT%2F8JrhqJ8KXFFtoJ%2FnbZFtfy2li7MbjiDlB%2B2%2F0tgjaQDr6uM%2FEp%2BcNR4a5yz%2FeN6%2FK9rR1a0XFFpPf1k%2BDaO6SjOESzlZRqb7blzZqwMhTC3KYvO1NR42iG%2BwrRboDbqIqFpvL10%2BlKcQn7trf128odalD2W8MB6EyYJV%2BHXYXHKEmzVZhNAB52CslGBosY4mLuk%2BkHLDRWf0%2Fe%2Bf0g8gsTQm3FQ2%2BiJe3Pc1lUR%2B3j5BhobbRRnIve0FP%2B2xl6E4uLoF7KKfi5Xv4RDdo7896LJEF54%2BVf4HLnt7HraLeL0Hwo1RnC%2BV61CE1Xm8LEWfg1SrhtM2jxO%2FbzoGs290KGmm8GzUYWqTNgui04%2BtJwgTkIat6xXXmp7qvvJmXuPNRiw7AlVqsCW%2FZxz%2BOMe672WEYVsgPTe6Hsbda685vvwB0GNu4CmNhjUOm3Z1TOv%2BJwPXsLkkbt3ZM7OMZCEMLctFp2tqR6MFp9i6jvqFtbzJga7ml8rpJxK7Z5lTXiwn27GW%2B5YAC0mjkX%2FfL%2FRhxp3xYbzgHgKl4QONYoSdo9RD6CCt8BnzKNGlb7t%2B%2BIsdNvVt%2FvE7LYoQW2jx2fMcVjnQKTynjiyjTbCRJD7mvfAqSfIXZuOUvw9By9i40qOcnuGbjB7R%2F0vGs2k0lzJyZH3FuEhtNFfwifKzWIn9vU0hI1l1JqBNXBsbdBsuvAbdJPovBCY5H5RDZjo75pu0KGmIyIaphVZFQYztij%2Bv6fPQO5vYsqcO%2Fa60%2Bqw2N2wgVcvQnBnuP6DFxiV%2FOrC3txMd6sUyG20oqrQv2cMo8YZ1%2Fl7bwGxRDwJORnCVVspbAHS3ExzdofBBQhz24r3%2BqRrvp6ZH%2Fnu3j7Pcf2UZ5E5zdyVtKZBFoRzXFmi8vN%2BHhBBcHHoUKOicoxP3RvDqA29Kb%2FYwCISxSuQa6EuEGBuil3cglZX4xteMzQ11P3FnLSnaZnrZ25x0hU%2Fv9B64Xl4pukzhCDX7Nw4JoeWSS58tkRlBYRv%2BghO37NPZwyjxtxQBWuqJtaKpyPVoEat4CJMc%2F9xDWVRLU3Xb8TLY85ZLSeteTr3jU11aPaJJwoRKyPyXW8hDLAEzIMPW%2Furm1NCvM%2FTrrFUGUhBsTZso%2F1ZB48mQ%2FhuNvsMPejfFA4hatwd%2FVn0rU2qElMssyC%2FHLYAJo08v8thdq9B9leBZS9K04zU7NCYZtimk2jjdOwqYkFoALqXB1Yh5v6Ix5M0sS8xt5J2tR6sNBZoPdKjSSS%2Bdfgnf0ShQI3WUdKLho3lZQEb0ACtA2PkhY4STJ3dkynmu6XpE2CZid7QPK%2BZoErcEKGDPrH%2FyO96XcG5N0wQ%2BthKzL3RHrQ8e6XobmyBQG20nuUzgOicGTV5yW4%2Bo9Ye5is7yFxLOph7YswXOwYUYpbknSA2incit0GNWuFy2Nn9XA11UVPNu5qXlnitt9AxtspGduq1BvVcX4lYjy37TMb6al1FTtH0YvZNZfrSBfpebVpoCex6BZ%2FrakuwCkaXQCZYwOGMedRAJOcd93eSr6mdOwsSyJpgMsitbTBtkwtDvRtcCqPplqzwIt8NiF3YqxhrSC68aGOTMLcTjVuSKxYKNLcFMB37rLuiXjghevlQUbOMcFTsYo3vWl7s%2BUNtTHFuUZppL9tvrNt6tWO09yX%2Fq0w6G2neekVtjQOz59LV8siVQyVlmMbpoJTLAX8MfPj6hrai51DfG7V%2FUDQ%2FJuv%2Fp%2B6CCvYu6t66wC6JOFWtCd8ImUmEkqIMndY4IebHPUTE9RnUYjynRKN0Quc1PZLqP3rw8%2Fe%2FiXjxGuSq1klL356RpeBQe0NNGczCDvwiEM4hc7eN9BRSFB3Vh9GvTNbw3AUdaqvUk4e83KhrmPvpsn%2FD6RjXwV%2Fbz%2FWezZh1iE1ihFXA3b4IWRB8YvfOBOpaFeZ58rx8ZcG3%2BW87r8auINX1TqLZPHqZHtptdHrpwz5yt3mbl1vXRKuee8zeM26WMVzG8bwTNbuBNfsaZ9VoSwTHovNPR0yAMLdp8%2FROfF7L5ne7%2Fq4%2BBBRQBu6wlLqV3jbRsksuOrf17Ez1NMvtNk90WJdNOZd8f6tSn3q%2B0VlTRntzDzYWuHFXsGL%2BrsaOsbsFo5giJjQySn5F6L0HAjrgzq4p8oiN%2F8d9%2Be94iaIQtVFHZy3DiJa9UjvZxPMidKgZPUgr83vIPQ7WcDuBMH5O1ACL9xk6cTufGSkKHWoG45NDPAGDxTnAahPC9LOiNhxRT4gub1dBh9oaQkqBdylrCVeKPSiE6adGrauCEdbvsJKZ%2FMyzEwrUzA9lVT1Z8n5JCBhCmH5q1AAJDIBeaxpOPuoXKFC7e6Lmt8zxQoyEqP0RWVWkQcIhxA5sOv9%2BQGi1dMoO7%2BltzoOHeoeEGAlR%2B0%2BsB3HA1ZFQ4vQCP1z%2B%2BD7U5LEJGPQjGsEwf5sQICFqn4iBDazWoUtHB%2FMXhqcNF2BHD5kKNhFz3SXmnX7KUq4SWMWtFAIkRG3EGJrK0WVFY95WXXytZ2CcnO017wt4DWfB3xNS9%2FjKPTtAFCux5haAi0BXiI4Qta8NLgBtvw2u6w1%2BiMSj85bZ%2BOM8o9B7BrLWPV5hPiGr5YnmuaXFZnFFz44QlUuu9U1lRtD9hLgIUROGEDVhCEOImjCEqAlDiJowhPEd8b93orvgekwryAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAxNy0wNy0xMFQwMToyNDo1MyswMjowMI0oPcsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMTctMDctMTBUMDE6MjQ6NTMrMDI6MDD8dYV3AAAAAElFTkSuQmCC)

That would link you to adding your bot to a Slack group.

Others could include:
Telegram,
Skype,
Microsoft Teams,
Messenger

I had exercised the thought of making [my own solution to this problem](https://github.com/tylerl0706/RGB-Randomly-Generated-Buttons) and then I found Shields.io and thought that it might be the perfect candidate to handle this :) 

Let me know if there's something I can do to help - big fan of the project already

**Comment by Daniel15** [comment]
You can already make your own plain-text buttons, see the very bottom of the site at https://shields.io/

**Comment by tylerl0706** [comment]
@Daniel15: that's actually how I created the Svg in the first link but I couldn't seem to get it to embed properly in this thread.

Plus, it's a really ugly url because of the base64 encoded image of the Slack logo.

It's a similar concept to that of the "Tweet" shield:
![](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)

**Comment by DavidXochipilli** [comment]
+1
An own graphic for [Telegram](https://telegram.org/) would be awesome!

**Comment by paulmelnikow** [comment]
As part of resolving #983 I'd like to add the capability to pull in a logo by reference. So, we could have named logos like slack, etc, and then you could just say something like `?logo=slack`.

Apart from that, the only badge like this which does not hit an API is the gitter badge:

[![Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg)]()

I'm ambivalent about whether to add more API-free badges like this, or simply use the custom badge route like Daniel suggests. On the one hand, it makes standardization and updating easy. On the other, it clutters the project with unnecessary code.

**Comment by tylerl0706** [comment]
@paulmelnikow I think your suggestion to pull in common logos sounds great :) 

If I'm able to add a badge on my open source bots that link to opening up the bot in Messenger, Telegram, Slack, etc - but without having to embed an entire image, I'm happy.

For the named logos, I have a few suggestions:

* Slack
* Telegram
* Facebook Messenger
* Skype
* Microsoft Teams
* Amazon Alexa
* Cortana
* Kik

**Comment by paulmelnikow** [comment]
I opened #1092 which includes support for named logos, while turning off logos by default. Reviews / +1's on that could be helpful. And, perhaps finding some optimized SVGs for these services would be helpful too!

**Comment by paulmelnikow** [comment]
Looks like we'll handle this using the custom badge and named logos, for now. Anyone, please feel free to open a new issue if you'd like to discuss further.
