### ISSUE TITLE
country\flag icons?

### ISSUE THREAD

**Issue by stokebreakup** [badges/shields#10317]
### 📋 Description

Depending on the open or closed source application, I think it would be interesting to inform where the data is kept for security and privacy reasons in relation to GDPR

### 🔗 Data

Is there a public API?
No.

Does the API require authentication or an API key?
No.

Link to the API documentation
there are open source libraries that have this(https://github.com/lipis/flag-icons)

### 🎤 Motivation

GDPR(open policy), open source, open design.

**Comment by chris48s** [comment]
This has come up before. We don't plan to add a full set of country flag icons, but if this is something you want to make, you have options.

1. You can use emoji in the text on badges e.g:

- ![](https://img.shields.io/badge/%F0%9F%87%B3%F0%9F%87%B4%20made%20in%20norway-gray.svg) - https://img.shields.io/badge/%F0%9F%87%B3%F0%9F%87%B4%20made%20in%20norway-gray.svg
- ![](https://img.shields.io/badge/made%20in-%F0%9F%87%A7%F0%9F%87%AA%20belgium-blue.svg) - https://img.shields.io/badge/made%20in-%F0%9F%87%A7%F0%9F%87%AA%20belgium-blue.svg

2. You can use custom SVG images on badges e.g:

![](https://img.shields.io/badge/made%20in%20chile-gray.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgc3R5bGU9Ii1tcy10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7LXdlYmtpdC10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7dHJhbnNmb3JtOnJvdGF0ZSgzNjBkZWcpIj48cGF0aCBmaWxsPSIjZWMxYzI0IiBkPSJNMCAzMnYxMWMwIDYgMyAxMSAxMCAxMWg0NGM3IDAgMTAtNSAxMC0xMVYzMkgweiIvPjxwYXRoIGZpbGw9IiNlNmU3ZTgiIGQ9Ik01NCAxMEgyM3YyMmg0MVYyMWMwLTYtMy0xMS0xMC0xMSIvPjxwYXRoIGZpbGw9IiMyYjM5OTAiIGQ9Ik0yMyAxMEgxMEMzIDEwIDAgMTUgMCAyMXYxMWgyM1YxMHoiLz48cGF0aCBmaWxsPSIjZTZlN2U4IiBkPSJNMTIgMTRsMiA1aDVsLTQgNCAxIDUtNC0zLTUgMyAxLTUtNC00aDV6Ii8+PHBhdGggZmlsbD0icmdiYSgwLCAwLCAwLCAwKSIgZD0iTTAgMGg2NHY2NEgweiIvPjwvc3ZnPg==) - https://img.shields.io/badge/made%20in%20chile-gray.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgc3R5bGU9Ii1tcy10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7LXdlYmtpdC10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7dHJhbnNmb3JtOnJvdGF0ZSgzNjBkZWcpIj48cGF0aCBmaWxsPSIjZWMxYzI0IiBkPSJNMCAzMnYxMWMwIDYgMyAxMSAxMCAxMWg0NGM3IDAgMTAtNSAxMC0xMVYzMkgweiIvPjxwYXRoIGZpbGw9IiNlNmU3ZTgiIGQ9Ik01NCAxMEgyM3YyMmg0MVYyMWMwLTYtMy0xMS0xMC0xMSIvPjxwYXRoIGZpbGw9IiMyYjM5OTAiIGQ9Ik0yMyAxMEgxMEMzIDEwIDAgMTUgMCAyMXYxMWgyM1YxMHoiLz48cGF0aCBmaWxsPSIjZTZlN2U4IiBkPSJNMTIgMTRsMiA1aDVsLTQgNCAxIDUtNC0zLTUgMyAxLTUtNC00aDV6Ii8+PHBhdGggZmlsbD0icmdiYSgwLCAwLCAwLCAwKSIgZD0iTTAgMGg2NHY2NEgweiIvPjwvc3ZnPg==

See the docs at https://shields.io/docs/logos#custom-logos

3. You might also be interested in the flag-badges project https://github.com/pedromxavier/flag-badges This is not our project, but they're out there doing their thing.
