### ISSUE TITLE
Dependabot suggestion

### ISSUE THREAD

**Issue by ccoVeille** [badges/shields#10352]
May I suggest you to use the groups feature in dependabot?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

This could reduce the number of PRs

You can have a look at what was done in this repository when I suggested it

Zxilly/go-size-analyzer@ec9c028

It would drastically reduce the number of PRs opened by dependabot because they will be grouped.

**Comment by ccoVeille** [comment]
This request is somehow related to 

- https://github.com/badges/shields/issues/10351

**Comment by ccoVeille** [comment]
I'm watching the repository, and I'm getting so much notification about dependabot updates that wants to bump things

**Comment by ccoVeille** [comment]
My issue finds some replies in what posted there

https://github.com/badges/shields/issues/10351#issuecomment-2226884026

While reducing the frequency could help, I think that some dependency could get bumped together

**Comment by chris48s** [comment]
OK. Personally I find a PR like this
https://github.com/encode/httpx/pull/3233
is just unhelpful to try and review and difficult to unpick if something fails. I care about that more than the number of notifications.

If you like this feature and want to use it on your own repos, enjoy.

If you want to watch the repo anyway, maybe GitHub's watch settings can help you focus on the stuff you are interested in:

![Screenshot at 2024-07-13 14-13-29](https://github.com/user-attachments/assets/6bce8fed-da7b-405c-8883-4df783e97782)

**Comment by ccoVeille** [comment]
I understand. Thanks for replying
