### ISSUE TITLE
Funkwhale badges

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10365]
### 📋 Description

For funkwhale.audio.
![Static Badge](https://img.shields.io/badge/Funkwhale-data-05719e?logo=Funkwhale)

### 🔗 Data

https://docs.funkwhale.audio/swagger/#

### 🎤 Motivation

Stats for tracks, playlists, users, and artists.

**Comment by PyvesB** [comment]
Hey there!

I'm not familiar with Funwhale, but it seems to be a music streaming service. Is it widely used by developers?

**Comment by MichaelHinrichs** [comment]
They have a [dev forum](https://forum.funkwhale.audio), a [Mattermost server](https://hub.funkwhale.audio), a [self-hosted Gitlab](https://dev.funkwhale.audio), and a [weblate instance](https://translate.funkwhale.audio). It's describes as "a decentralized, open network".
https://www.funkwhale.audio/contribute/
https://docs.funkwhale.audio/

**Comment by PyvesB** [comment]
Well yes, pretty much any platform out there is _built_ by developers, but is it widely _used_ by developers? For example, are there many software engineering podcasts on there, or do developers commonly go there to download audio assets to be used in their apps?

**Comment by MichaelHinrichs** [comment]
Isn't having a developer community enough?

**Comment by PyvesB** [comment]
No, our [guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines) indicate the following:

> Shields.io hosts integrations for services which are primarily used by developers or which are widely used by developers.

**Comment by MichaelHinrichs** [comment]
Nevermind then.
