### ISSUE TITLE
App Center badges

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10367]
### 📋 Description

For Visual Studio App Center.
![Static Badge](https://img.shields.io/badge/service%20connection%20displayName-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/service%20connection%20serviceType-apple-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/service%20connection%20credentialType-credentials-CB2E6D?logo=VisualStudioAppCenter)

![Static Badge](https://img.shields.io/badge/user%20id-3fa85f64--5717--4562--b3fc--2c963f66afa6-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20avatar%20url-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20can%20change%20password-true-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20display%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20email-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20permissions-manager-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/user%20origin-appcenter-CB2E6D?logo=VisualStudioAppCenter)

![Static Badge](https://img.shields.io/badge/tester%20displayName-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/tester%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/tester%20email-string-CB2E6D?logo=VisualStudioAppCenter)

![Static Badge](https://img.shields.io/badge/team%20member%20displayName-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20member%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20member%20email-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20member%20role-maintainer-CB2E6D?logo=VisualStudioAppCenter)

![Static Badge](https://img.shields.io/badge/team%20id-3fa85f64--5717--4562--b3fc--2c963f66afa6-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20display%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/team%20description-string-CB2E6D?logo=VisualStudioAppCenter)

![Static Badge](https://img.shields.io/badge/organization%20id-3fa85f64--5717--4562--b3fc--2c963f66afa6-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20display%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20name-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20avatar%20url-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20origin-appcenter-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20created%20at-string-CB2E6D?logo=VisualStudioAppCenter)
![Static Badge](https://img.shields.io/badge/organization%20updated%20at-string-CB2E6D?logo=VisualStudioAppCenter)
But with the VS App Center logo, which I couldn't make work even though I know it's in simpleicons.

### 🔗 Data

https://openapi.appcenter.ms/#/account/sharedconnection_Connections
Yes an API key is needed.

### 🎤 Motivation

visualize data about users, teams, team members, organizations, apps, and other things.

**Comment by PyvesB** [comment]
Hey there!

Similar to what I mentionned in https://github.com/badges/shields/issues/10364#issuecomment-2230440078, all of the examples you listed are unlikely to change over time, I feel that these badges would be better served by a static badge rather than having to perform auth-based API calls.

**Comment by chris48s** [comment]
> the VS App Center logo, which I couldn't make work even though I know it's in simpleicons

There was previous an icon for this in the simple-icons set. However, all icons related to Microsoft products were removed in Simple Icons v13. There's more details on this in:

- https://github.com/simple-icons/simple-icons/releases/tag/13.0.0
- https://github.com/simple-icons/simple-icons/pull/10019
