### ISSUE TITLE
Node 22 CI workflows failing

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#10378]
`npm ci` is failing with the following error:
> Exit handler never called!

This error has been reported multiple times already, e.g.: https://github.com/npm/cli/issues/7657

We could do some version pinning, but hopefully this can be resolved in the next few days, I suggest we wait for the fix to be rolled out, and trust the output of our Node 20 workflows for the time being.

**Comment by chris48s** [comment]
This is now fixed upstream apparently
https://github.com/npm/cli/issues/7657#issuecomment-2239308353

There's a bunch of PRs approved and ready to merge. Might be worth seeing if node v22.5.1 is available to GH actions yet. If it is then the builds should be able to pass now.

If it is not, I reckon just bypass the checks on those PRs for now to get them merged.

**Comment by chris48s** [comment]
node 22.5.1 is available to github actions and node 22 builds are running as expected
