### ISSUE TITLE
Cannot add shields.io as Github Application?

### ISSUE THREAD

**Issue by mitchellkrogza** [badges/shields#1038]
Hi there, one of your pages suggests adding shields.io as a Github application to a repo if badges are not loading due to rate limiting. But cannot find shields.io as an application to add to a repo and visiting your link gives `GitHub OAuth authentication failed to provide a code.`how does one actually add shields.io to a repo?

**Comment by cjwhitsitt** [comment]
Adding some extra info here.

* Link given: https://img.shields.io/github-auth
* URL that shows the above error: https://img.shields.io/github-auth/done?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

Config issue with redirect URI?

**Comment by paulmelnikow** [comment]
Yikes, let's get this fixed!

**Comment by espadrine** [comment]
Hi folks, I think I fixed it with 95ef1da7. Please do re-open if I am wrong.

**Comment by paulmelnikow** [comment]
Thanks @espadrine!

**Comment by paulmelnikow** [comment]
My boyfriend just authorized his github account, so I can confirm this is working! 👍

**Comment by mitchellkrogza** [comment]
👍  confirmed fixed, I visited https://img.shields.io/github-auth and it authorized instantly. Well done @espadrine

**Comment by waja** [comment]
It actually throws a 'GitHub OAuth authentication failed to provide a code.' again.

**Comment by paulmelnikow** [comment]
Thanks for the heads up. I opened #1243.

**Comment by Quezler** [comment]
I stumbled across the link to and added my account as well 👍
