### ISSUE TITLE
 MDN HTTP Observatory is launched, and Mozilla Observatory is now deprecated. 

### ISSUE THREAD

**Issue by yestalgia** [badges/shields#10396]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Today I noticed our [Mozilla Observatory Grade](https://shields.io/badges/mozilla-http-observatory-grade) badge was no longer working. 

After revieing the [linked page](https://observatory.mozilla.org/analyze/docs.qlcplus.org) I noticed that the service has been moved.

![image](https://github.com/user-attachments/assets/462a8c09-ec1b-4f48-9b7a-4f77517550d9)

Please see link to the blog post: https://developer.mozilla.org/en-US/blog/mdn-http-observatory-launch/

> Today, we are delighted to announce that the HTTP Observatory's new home is MDN! This blog post explains a little bit of the history behind the tool, how we got to where we are now, what the migration means for Observatory and MDN, and what Observatory tests.

### 🔗 Link to the badge

https://shields.io/badges/mozilla-http-observatory-grade

### 💡 Possible Solution

I think we will need to embrace the new MDN HTTP observatory and change the badge accordingly.

https://developer.mozilla.org/en-US/observatory

**Comment by yestalgia** [comment]
The badge not working could be unrelated as the project is apparently going to be sunset in September. 

<a href="https://observatory.mozilla.org/analyze/docs.qlcplus.org" alt="Mozilla HTTP Observatory Grade">
        <img src="https://img.shields.io/mozilla-observatory/grade-score/docs.qlcplus.org?publish" /></a>

**Comment by chris48s** [comment]
OK. If I go to https://observatory.mozilla.org/ and search for any domain, I get " Error: HTTP Observatory is down". Maybe it is an outage, maybe they've retired it earlier than documented.

There is now a new thing.

With the old Mozilla Observatory, the API we were using was actually a public documented API https://github.com/mozilla/http-observatory/blob/main/httpobs/docs/api.md

From reverse-engineering the site, it does appear to be possible to call a URL like https://observatory-api.mdn.mozilla.net/api/v2/analyze?host=shields.io but I can't see anywhere this API is actually documented as a public API we're allowed to use.

Before we do anything else, I've raised an issue upstream at https://github.com/mdn/mdn-http-observatory/issues/43 requesting some clarification. Lets see where that goes.

**Comment by yestalgia** [comment]
Thank you

**Comment by chris48s** [comment]
Someone from MDN has confirmed we're good to use that endpoint, so I think this is good to work on if someone wants to pick it up. I've not really looked at how much difference there is between the new and old API response format.

**Comment by chris48s** [comment]
actually, I will submit a PR for this one
