### ISSUE TITLE
GitHub Lines Of Code badge

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10394]
### 📋 Description

For [ghloc](https://ghloc.vercel.app/).
![Endpoint Badge](https://img.shields.io/endpoint?url=https%3A%2F%2Fghloc.vercel.app%2Fapi%2Fbadges%2Fshields%2Fbadge)

### 🔗 Data

https://github.com/pajecawav/ghloc-web
No API key.

### 🎤 Motivation

Count lines of code in GitHub.

**Comment by PyvesB** [comment]
See #10391.

**Comment by MichaelHinrichs** [comment]
Oh come on! This is a simple one!
