### ISSUE TITLE
Chinese translating

### ISSUE THREAD

**Issue by ASKLL-STAR** [badges/shields#10393]
:clipboard: **Description**

Whether to consider translating the content to make it more accessible to those who do not speak the same language
Machine translation is so strange!!!

**Comment by chris48s** [comment]
I think there are two really big problems with trying to maintain translations for an open source project in multiple languages (be that Chinese or anything else):

1. It is basically impossible for me meaningfully review a pull request of the form "translate X into Japanese" (or any other language I don't speak) in the same way I can review a code submission. Is this a high quality translation of the site? Did someone just run it through google translate, call it a day and submit it? Is it mostly our site content but with occasional bits of QAnon propaganda inserted in strategic places? Who knows..

2. A nice person appears and submits a PR translating our site in to Swedish. Yay for Open Source. They mean well. Some time later down the line, we want to change the English content on the site, or just add more content. We now need a Swedish translator. If the person who originally submitted them isn't interested any more for whatever reason, we're stuck. We either have a Swedish version of the site which gradually becomes more out of sync with the English version over time or which progressively has more and more bits of it replaced by English. Eventually we retire the Swedish translations.

I've only ever really seen this work when there is someone on the project core team who speaks the target language and is willing to commit to maintaining the translations over a long period of time, or if the project has budget to pay for translations. We have neither.

**Comment by ASKLL-STAR** [comment]
> I think there are two really big problems with trying to maintain translations for an open source project in multiple languages (be that Chinese or anything else):
> 
> 1. It is basically impossible for me meaningfully review a pull request of the form "translate X into Japanese" (or any other language I don't speak) in the same way I can review a code submission. Is this a high quality translation of the site? Did someone just run it through google translate, call it a day and submit it? Is it mostly our site content but with occasional bits of QAnon propaganda inserted in strategic places? Who knows..
> 
> 2. A nice person appears and submits a PR translating our site in to Swedish. Yay for Open Source. They mean well. Some time later down the line, we want to change the English content on the site, or just add more content. We now need a Swedish translator. If the person who originally submitted them isn't interested any more for whatever reason, we're stuck. We either have a Swedish version of the site which gradually becomes more out of sync with the English version over time or which progressively has more and more bits of it replaced by English. Eventually we retire the Swedish translations.
> 
> I've only ever really seen this work when there is someone on the project core team who speaks the target language and is willing to commit to maintaining the translations over a long period of time, or if the project has budget to pay for translations. We have neither.

I would be very interested in translating this project into Chinese if possible, I used to be a member of a localization team (translating foreign games into the source language of Chinese) and I think it would be very good to have a Chinese translation of this project, since China has a huge population base of 1409.67 million people, there will always be people who will need this project. Take me for example, but when I saw the dazzling English, I silently turned on my browser's own translation function, but the translated sentences were strange and bizarre! If possible, I would like to do a Chinese translation for this project for free (the above paragraph is machine translated, so it may read a bit strange)

Translated with DeepL.com (free version)
