### ISSUE TITLE
deepscan badge

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10390]
### 📋 Description

For [Deepscan](https://deepscan.io/home/)
![Static Badge](https://img.shields.io/badge/build-passing-green)

### 🔗 Data

https://deepscan.io/docs/enterprise/tools/npm#api

### 🎤 Motivation

Another code scanning app, reviewing javascript.

**Comment by chris48s** [comment]
Basically the issue with something like this is: For performance reasons, we couldn't:

- pull down some code
- run a scan on it
- render a badge with the result

in the context of a web request.

For shields.io, there would need to be an upstream service making the scan results available.

**Comment by MichaelHinrichs** [comment]
Darn.

**Comment by MichaelHinrichs** [comment]
Can't you get the scan result from DeepScan after it scans the code itself?
What Chris said would make sense if DeepScan was a locally installed API, but it's online.
https://deepscan.io/docs/guides/get-started/basics
https://deepscan.io/docs/guides/get-started/project
https://deepscan.io/docs/guides/get-started/grades

**Comment by calebcartwright** [comment]
> Can't you get the scan result from DeepScan after it scans the code itself?

If there's a web-accessible api call we can make to get the results of a previous scan then it could be possible. If you believe something like that exists then please post the details
