### ISSUE TITLE
Project Discovery Badges

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10392]
### 📋 Description

For projectdiscovery.io
Scan results and vulnerabilities.

### 🔗 Data

https://docs.projectdiscovery.io/api-reference/results/get-scan-results

### 🎤 Motivation

self explanatory.

**Comment by PyvesB** [comment]
See #10391.

**Comment by MichaelHinrichs** [comment]
If there are so many FRACKIN rules for issues, then they should be in the issue template!
