### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by nathany** [badges/shields#104]
Now that we've consolidated a number of projects, this seems like a good time to revisit licensing.

* The CC0 license for badges
* The license for gh-badges and any additional services (analytics backend or what-not)
* Do we need a CLA for vendors contributing webhooks? (if we move forward with that second form of the API https://github.com/badges/shields/issues/100#issuecomment-32057540)
* Do we have any license requirements for third-party badge requirements https://github.com/badges/shields/issues/88#issuecomment-32058681

Related to this is setting up a Shields, LLC. https://github.com/badges/shields/issues/39#issuecomment-31805605

**Comment by olivierlacan** [comment]
@pluma Yup! :-)
