### ISSUE TITLE
Wheelmap badges broken

### ISSUE THREAD

**Issue by chris48s** [badges/shields#10404]
:clock11: **When did the problem start?**

This seems to have been broken since we reinstated the daily test runs a couple of weeks ago

:camera: **Live badge**

https://img.shields.io/wheelmap/a/26699541
![](https://img.shields.io/wheelmap/a/26699541)

:wrench: **Is the live badge working?**

Nope

:lady_beetle: **Stack trace**

We're throwing a `NotFound` in response to receiving a 404.
The response we're getting is a HTML page, not a JSON response.

In the tests we're seeing
```
AssertionError: message mismatch: expected 'node not found' to equal 'yes'
AssertionError: message mismatch: expected 'node not found' to equal 'limited'
AssertionError: message mismatch: expected 'node not found' to equal 'no'
```

:bulb: **Possible solution**

We seem to be getting a 404 response from the wheelmap API for any node ID. This includes nodes that do exist, For example https://wheelmap.org/node/26699541 is valid but https://img.shields.io/wheelmap/a/26699541 fails.
I suspect wheelmap may have just got rid of their API completely.
Given nobody seems to have noticed or complained, maybe it is time to retire this service?

**Comment by PyvesB** [comment]
Yeah, these have been failing for some time. I had woked on this badge a few years ago, and I think I own the CI/staging token. I can take a look. :)

**Comment by chris48s** [comment]
Thanks. Will leave it with you to see if you can find out more before I write the PR removing it.

**Comment by PyvesB** [comment]
Hmmm... `https://osm-api.wheelmap.tech/api/v1/legacy/api/node/{nodeId}` seems to do the job. I've sent an email to the Wheelmap team to ask which API endpoint we should be hitting nowadays, but maybe we can switch to this in the meantime, and get on with our lives.

**Comment by PyvesB** [comment]
I did get an initial response from the CTO of the company owning Wheelmap, stating that the API had not been publicly supported for a long time, and enquiring about our use case. I did not get a response after that, despite attempting to follow up.

I suggest we go ahead and deprecate these badges.
