### ISSUE TITLE
Add "Master" branch Latest commit time of a GitHub repo

### ISSUE THREAD

**Issue by gabrielizalo** [badges/shields#1041]
It will be cool to know when was the latest update of a repo.
You [can see in this file](https://github.com/gabrielizalo/JavaScript-Crypto-Libraries/blob/master/js-crypto-libraries.md) several badges. 
I'm missing the "latest update" badge of all repos.

**Comment by paulmelnikow** [comment]
Hi! See #928. Will try to get that merged soon, at least the part that shows the last commit date.

**Comment by gabrielizalo** [comment]
Duplicated issue!
