### ISSUE TITLE
Pivotal Tracker badges

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10418]
### 📋 Description

For [Pivotal Tracker](https://www.pivotaltracker.com/)
![Static Badge](https://img.shields.io/badge/project%20updated%20at-2024--07--23T12%3A00%3A00Z-blue)
![Static Badge](https://img.shields.io/badge/story%20review%20updated%20at-2024--07--23T12%3A00%3A00Z-blue)
![Static Badge](https://img.shields.io/badge/project%20current%20iteration%20number-1-blue)
![trends](https://github.com/user-attachments/assets/701a6b02-200e-483c-8c45-7f25e28a233c)
![iteration report](https://github.com/user-attachments/assets/1880b979-1935-47bd-a026-956364f92f5d)

### 🔗 Data

https://www.pivotaltracker.com/help/api

### 🎤 Motivation

It's another bug tracking app.

**Comment by chris48s** [comment]
VMware have announced that the Pivotal Tracker service will be shut down in April 2025
https://www.pivotaltracker.com/blog/2024-09-18-end-of-life
Given the service will be sunset in the near future, I don't think it would make sense for anyone to spend time on adding this integration now.
