### ISSUE TITLE
Why is the windows logo gone?

### ISSUE THREAD

**Issue by lalakii** [badges/shields#10423]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I remember it being there before, and I'd like to know for what reason it was removed.

### 🔗 Link to the badge

https://img.shields.io/badge/windows-0078D4?logo=windows

**Comment by calebcartwright** [comment]
Thanks for reaching out, the details can be found in https://github.com/badges/shields/issues/10338#issuecomment-2211265731
