### ISSUE TITLE
Add CodeSponsor.io badge

### ISSUE THREAD

**Issue by cavneb** [badges/shields#1042]
CodeSponsor.io is a platform that connects sponsorship to open-source projects. Projects earn money from sponsors and this badge would indicate the amount earned per project.

The API to be hit is a simple GET request to 
 https://app.codesponsor.io/shields/[token]/[username]/[repo_name]

For example: https://app.codesponsor.io/shield/YOURTOKEN/hopsoft/bg

Example Results:

```json
{
  "distribution_cents": 13625,
  "ts": 1505088625
}
```

**Comment by rstacruz** [comment]
neat, how do you get your token? :D
