### ISSUE TITLE
Go modules showing the same version number

### ISSUE THREAD

**Issue by scottschreckengaust** [badges/shields#10442]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The version for Go modules are all the "same" currently showing `v1.18` at the time of writing.

### 🔗 Link to the badge

https://shields.io/badges/git-hub-go-mod-go-version

Here are two examples (at the time both showing `v1.18`:

1. ![GitHub go.mod Go version](https://img.shields.io/github/go-mod/go-version/projen/projen-go?filename=projen%2Fgo.mod) should be [v0.85.0](https://github.com/projen/projen-go/commit/dfcd4b306d6e42c89cb2e9e7e019c5d95417496c)
2. ![GitHub go.mod Go version](https://img.shields.io/github/go-mod/go-version/cdklabs/generative-ai-cdk-constructs-go?filename=generative-ai-cdk-constructs%2Fgo.mod) should be [v0.1.238](https://github.com/cdklabs/generative-ai-cdk-constructs-go/commit/deb66f0af52b8edc86af222241f70dee3eb98bfc)

Screenshot:
![image](https://github.com/user-attachments/assets/97afc606-9ea9-4de5-b912-94589028fe58)

**Comment by scottschreckengaust** [comment]
I see that `go 1.18` is in the `go.mod` files...maybe that is the "issue"...

**Comment by chris48s** [comment]
The badge you're requesting shows the supported go version for the given repo, not the package version itself. So these are working as expected. So if you request https://img.shields.io/github/go-mod/go-version/gohugoio/hugo for example, it will tell you v1.21.8 which is correct https://github.com/gohugoio/hugo/blob/665ac949bdc2e54d378ef5c00778c830440a1a9d/go.mod#L172

There is one issue here though, which is that the documentation page for this should be under the "Platform & Version Support" category, not "Version" which probably led to the confusion here. I've submitted https://github.com/badges/shields/pull/10444 fixing that.

**Comment by scottschreckengaust** [comment]
So grateful for the rapid response. I'll use the GitHub tag method instead to derive the package version.
