### ISSUE TITLE
Maven central badges seem to be outdated

### ISSUE THREAD

**Issue by mkouba** [badges/shields#1046]
Hi all,
Maven central badges seem to be outdated, e.g. 
[![Maven Central](http://img.shields.io/maven-central/v/org.jboss.weld.vertx/weld-vertx-core.svg)](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22weld-vertx-core%22)
shows currently version 1.0.0.CR6 (10-Apr-2017). However, there are two newer versions, 1.0.0.Final (26-Jun-2017) and 1.1.0.Final (01-Aug-2017). The same applies to other [Weld](http://weld.cdi-spec.org/) artifacts, e.g. http://img.shields.io/maven-central/v/org.jboss.weld.se/weld-se-shaded.svg shows 3.0.0.CR2 (03-Mar-2017) but the current version is 3.0.0.Final (12-May-2017).

Could it be a caching issue?

Thanks,
Martin

**Comment by paulmelnikow** [comment]
Hi! Thanks for your question.

Hmmm, I'm not seeing 3.0.0.Final. Could this be a server-side problem?

From http://repo1.maven.org/maven2/org/jboss/weld/se/weld-se-shaded/maven-metadata.xml:

```xml
<metadata>
   <groupId>org.jboss.weld.se</groupId>
   <artifactId>weld-se-shaded</artifactId>
   <versioning>
      <latest>3.0.0.CR2</latest>
      <release>3.0.0.CR2</release>
      <versions>
         <version>3.0.0.Alpha2</version>
         <version>3.0.0.Alpha3</version>
         <version>3.0.0.Alpha4</version>
         <version>3.0.0.Alpha5</version>
         <version>3.0.0.Alpha6</version>
         <version>3.0.0.Alpha7</version>
         <version>3.0.0.Alpha8</version>
         <version>3.0.0.Alpha9</version>
         <version>3.0.0.Alpha10</version>
         <version>3.0.0.Alpha11</version>
         <version>3.0.0.Alpha12</version>
         <version>3.0.0.Alpha13</version>
         <version>3.0.0.Alpha14</version>
         <version>3.0.0.Alpha15</version>
         <version>3.0.0.Alpha16</version>
         <version>3.0.0.Alpha17</version>
         <version>3.0.0.Beta1</version>
         <version>3.0.0.CR1</version>
         <version>3.0.0.CR2</version>
      </versions>
      <lastUpdated>20170303115222</lastUpdated>
   </versioning>
</metadata>
```

**Comment by mkouba** [comment]
Well, I can see the latest versions when using central repo UI: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jboss.weld.se%22%20AND%20a%3A%22weld-se-shaded%22. But yes, it looks like the `maven-metadata.xml` file is broken. I will send a question to sonatype guys. Thanks.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed

**Comment by mkouba** [comment]
`maven-metadata.xml` files were updated in Maven central repo and everything seems to work again. Thanks a lot!
