### ISSUE TITLE
Team Services Plugin

### ISSUE THREAD

**Issue by chwebdude** [badges/shields#1047]
Hi everyone

I just wanted to tell you, that I created a plugin for TFS and Visual Studio Team Services which will create a badge on the build process using shields.io.
You can grab it here: [https://marketplace.visualstudio.com/items?itemName=chwebdude.badge-creator](https://marketplace.visualstudio.com/items?itemName=chwebdude.badge-creator)

Thanks
Fabrice

**Comment by paulmelnikow** [comment]
👍
