### ISSUE TITLE
Update Jenkins Plugin Installs for new stats.jenkins.io

### ISSUE THREAD

**Issue by chris48s** [badges/shields#10534]
:clipboard: **Description**

Refs https://github.com/badges/shields/pull/10522

As a stop-gap we are using old.stats.jenkins.io but this will be retired at some point.

It looks like a feature allowing us to grab machine-readable data from the new stats.jenkins.io will be introduced. Once that happens, we update our code to use that instead.

**Comment by timja** [comment]
It has been added now you can revert the temporary change

**Comment by lemeurherveCB** [comment]
Ref for the record: https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2350107931
