### ISSUE TITLE
Add 'Funding' category

### ISSUE THREAD

**Issue by mattbk** [badges/shields#1054]
Experimented with this on https://github.com/badges/shields/pull/1053, but it should probably be pulled out for separate consideration. 

There are at least a few shields (e.g., Gratipay, Beerpay, Bountysource) that relate to the amount of funding a project is getting. Considering that [OSS is dealing with funding issues right now](https://gratipay.news/open-source-captures-almost-none-of-the-value-it-creates-9015eb7e293e), pulling these out into a separate category than 'Miscellaneous' seems warranted.

**Comment by triggerman722** [comment]
Once #1069 is merged, I'd really like to see this issue resolved as well. Codetally deals with the cost side of funding and would ideally be in the funding category with Gratipay, Beerpay, and Bountysource.

**Comment by paulmelnikow** [comment]
This is a fantastic idea!

**Comment by paulmelnikow** [comment]
Resolved in #1212.
