### ISSUE TITLE
Badge Request: crates.io total downloads of an author

### ISSUE THREAD

**Issue by Nugine** [badges/shields#10614]
### 📋 Description

This badge shows the total downloads of all the crates that an author publishs.

![Static Badge](https://img.shields.io/badge/total_downloads-123456-blue)

### 🔗 Data

`https://crates.io/api/v1/users/{user_id}/stats`
It is a public API.

Example: https://crates.io/api/v1/users/3618/stats
```json
{"total_downloads":6096699151}
```

### 🎤 Motivation

Showing that this crate author is trustworthy because of high total downloads.

**Comment by calebcartwright** [comment]
Sounds reasonable, especially since there's already an API for it. I wouldn't personally conflate download numbers as inherently implying trust, but certainly seems like a badge we can incorporate if someone is willing to work on it.
