### ISSUE TITLE
How is issue-pr working ?

### ISSUE THREAD

**Issue by aashutoshrathi** [badges/shields#1061]
There is no column in API containing the data for PRs, then how is it showing it.
For eg :- https://img.shields.io/github/issues-pr/iiitv/ChefLib.svg

**Comment by paulmelnikow** [comment]
Hi! Here is [the code that handles that](https://github.com/badges/shields/blob/20ab540fb2967ad81b1e641e5e493dc91cb317fd/server.js#L3393-L3396).

If that doesn't answer your question, please reopen!
