### ISSUE TITLE
[BadgeReq] ORCID

### ISSUE THREAD

**Issue by MrT-tak** [badges/shields#10643]
### 📋 Description

- Service: ORCID
-  it should show 
(logo) ORCID id | (the id)
or
(logo) (username) | (the id)

I've tried using static badge but the parser fails when using large text and the - doesn't work well even with double --. 

### 🔗 Data

I don't think you need a public API but ORCID does have an API.
https://info.orcid.org/what-is-orcid/services/public-api/
this requires an account to generate an API key, similar to GitHub apps or OAuth.

### 🎤 Motivation

I would love to use it in my README.MD and my website.
The HTML they provide you isn't smooth and inline with other things in my readme!
They give you the following to embed:

[https://orcid.org/0009-0005-7450-170X](![An ORCID logo](https://orcid.org/sites/default/files/images/orcid_16x16.png) https://orcid.org/0009-0005-7450-170X)

`    <a
    id="cy-effective-orcid-url"
    class="underline"
     href="https://orcid.org/0009-0005-7450-170X"
     target="orcid.widget"
     rel="me noopener noreferrer"
     style="vertical-align: top">
     <img
        src="https://orcid.org/sites/default/files/images/orcid_16x16.png"
        style="width: 1em; margin-inline-start: 0.5em"
        alt="ORCID iD icon"/>
      https://orcid.org/0009-0005-7450-170X
    </a>`

### note:
ORCID id is really long! It is similar to UUIDs.
My ORCID: 0009-0005-7450-170X

**Comment by MrT-tak** [comment]
Also can someone add help request badge also if needed? Thanks!

**Comment by chris48s** [comment]
Hello. Can you explain what you mean by

> the parser fails when using large text

I see no reason this can't be done with the static badge

example:
- https://img.shields.io/badge/orcid_id-0009--0005--7450--170X-blue?logo=orcid
- ![](https://img.shields.io/badge/orcid_id-0009--0005--7450--170X-blue?logo=orcid)

As noted in the issue template

> This issue template is for suggesting new badges which
> **fetch and display data from an upstream service**.
> If your suggestion is for a static badge
> (which shows the same information every time it is requested), it is
> [already possible to make these](https://shields.io/docs/static-badges).
> We don't add specific routes for badges which only show static information.

**Comment by MrT-tak** [comment]
> Hello. Can you explain what you mean by
> 
> > the parser fails when using large text
> 
> I see no reason this can't be done with the static badge
> 
> example:
> 
> * https://img.shields.io/badge/orcid_id-0009--0005--7450--170X-blue?logo=orcid
> * ![](https://camo.githubusercontent.com/8855a4c1170adedda6767f7617d05b03a377f04f5f30c78e95da311aef3e8178/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6f726369645f69642d303030392d2d303030352d2d373435302d2d313730582d626c75653f6c6f676f3d6f72636964)
> 
> As noted in the issue template
> 
> > This issue template is for suggesting new badges which
> > **fetch and display data from an upstream service**.
> > If your suggestion is for a static badge
> > (which shows the same information every time it is requested), it is
> > [already possible to make these](https://shields.io/docs/static-badges).
> > We don't add specific routes for badges which only show static information.

Oh wow. Thanks @chris48s ! I was on the static badge generator page and it kept going to 404 https://img.shields.io/badge/0009-0005-7450-170X?logo=orcid&label=ORCID

**Comment by MrT-tak** [comment]
I had the syntax wrong lol
@chris48s Thank you very much!
