### ISSUE TITLE
Any probability of adding Chinese support?

### ISSUE THREAD

**Issue by duoduoeeee** [badges/shields#1068]
As the title goes.

I note that the program squeezes badges when there are Chinese characters on it.

For instance check out my example

https://badges.duoee.cn/api/badge/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90-GO-brightgreen.svg

In contrast, all badges in English are working properly:

https://badges.duoee.cn/api/

Is there any possibility to add a ttf or something so that the service recognises Chinese characters and handles them properly?

Thanks

**Comment by paulmelnikow** [comment]
Hi, thanks for your question. You can put whatever font you'd like in the directory where Shields is installed. Just call it `Verdana.ttf`, even if it's some other font. Shields should load and use that. Hope that helps!
