### ISSUE TITLE
Proportions / Specification out of date?

### ISSUE THREAD

**Issue by Tethik** [badges/shields#1071]
I'm working on my own port of this in python to generate badges offline via cli. So I'm trying to follow the [specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) to generate the same badges.

I looked at the specification which has this image:
![Proportions image](https://github.com/badges/shields/blob/master/spec/proportions.png?raw=true)

However when comparing this with the actual generated badges from shields.io I get a inconsistent padding depending on the length of the text. Longer text labels/value seem to get shorter paddings. See examples below.

Is the specification wrong or is there an issue with the rendering? Apologies if I missed the documentation on this somewhere.

## Example
![](https://img.shields.io/badge/some%20slightly%20longer%20label-value-green.svg)
Has a 3px padding on the left instead of 6px as per the proportions image. The padding between label and value texts is also shorter (6px vs expected 8px). 
![some slightly longer label-value-green](https://user-images.githubusercontent.com/298627/30165118-2f98f676-93df-11e7-98ff-2931e782b905.png)

Looking at the first example image I get something closer to the specification but still slightly wrong.
![https://img.shields.io/travis/rust-lang/rust.svg](https://img.shields.io/travis/rust-lang/rust.svg)

Paddings in order: 6 + 6 (!) + 4 + 6
![rust](https://user-images.githubusercontent.com/298627/30165487-86c85e68-93e0-11e7-9975-409ab025c15a.png)

**Comment by RedSparr0w** [comment]
Think this can be closed now due to #1161 🤞

**Comment by paulmelnikow** [comment]
@RedSparr0w You should be able to close these now, right? If not, look for an invite like in your email. 😄

**Comment by RedSparr0w** [comment]
Yes you are right 😄 
Will take some getting used to.

Closing as fixed via #1161 
_If you feel this issue has not been resolved feel free to re-open._
