### ISSUE TITLE
website-up-down returning down, but website is up

### ISSUE THREAD

**Issue by SamThilmany** [badges/shields#1072]
I've some websites running on my server and for one of them (the only WordPress installation), the `website-up-down`-badge returns `down` although the website is definitely up. For all the other websites on the same server, the badge displays `up`, which is correct.

---

### Live Demo

[![Website](https://img.shields.io/website-up-down-green-red/https/laborecke.de.svg?label=Website%20status)](https://laborecke.de)

```
[![Website status](https://img.shields.io/website-up-down-green-red/https/laborecke.de.svg?label=Website%20status)](https://laborecke.de)
```

---

How does `shields` check for the current status of a website? Could this check be blocked by any setting?

**Comment by paulmelnikow** [comment]
Hi! Thanks for your question. Basically it just makes an HTTP request and checks that the status code is < 310. The code that handles is is [here](https://github.com/badges/shields/blob/master/server.js#L6155-L6194). 

Note that results could be cached for a while on the production server.

Are you still seeing this problem? Can you reproduce it running a local copy of Shields?

**Comment by SamThilmany** [comment]
@paulmelnikow Well my question is 15 days old now and as you see, I included a live demo which is still saying, that my website is down. I don‘t think that your cache keeps the result for two weeks, is it?

When I have time, I‘ll install a local copy and check, but I think that your IP is being blocked by WordPress. This is the only website on that server running on WP and it‘s the only website showing this issue. I don‘t think that this is a coincidence.

**Comment by paulmelnikow** [comment]
Hmm, I have the same problem on my local machine.

The HTTP request made is a HEAD request, not a GET, and it looks like Wordpress is not responding appropriately. It should be a 200, but it's a 403.

I can reproduce the problem using curl:

```sh
$ curl --head https://laborecke.de
HTTP/1.1 403 Forbidden
Server: nginx
Date: Fri, 22 Sep 2017 19:45:59 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Vary: Accept-Encoding
Vary: Accept-Encoding
```

**Comment by SamThilmany** [comment]
Fixed it. A WordPress Plugin was setting `RewriteCond %{REQUEST_METHOD} ^(HEAD|TRACE|DELETE|TRACK) [NC]` and therefore the requests were forbidden. I now removed `HEAD` from the string and now it works well.

**Comment by ParveenBhadooOfficial** [comment]
My website bhadoo.uk shows down, its WordPress. Can you tell me what is needed to be done to fix?

**Comment by geminiloh** [comment]
@ParveenBhadooOfficial how do you fixed the issue? I saw your website is up
https://img.shields.io/website.svg?color=ff69b4&url=http%3A%2F%2Fbhadoo.uk
