### ISSUE TITLE
Maintainance "/no/" color

### ISSUE THREAD

**Issue by c33s** [badges/shields#1073]
shouldn't https://img.shields.io/maintenance/no/2017.svg be red? "/no/" should always be red, should it?

**Comment by paulmelnikow** [comment]
Sounds like a bug to me! Would you like to add a test and open a pull request?

**Comment by c33s** [comment]
@paulmelnikow i would happily make a PR if the code would be in php and the tests would be in phpunit but as it is js i have to say "sorry, no".

**Comment by paulmelnikow** [comment]
Fixed in #1089.
