### ISSUE TITLE
Badge Request: sonarcloud.io

### ISSUE THREAD

**Issue by gucong3000** [badges/shields#1075]
[SonarCloud](https://sonarcloud.io) is online service base on SonarQube, Do you have any plan for support it?

**Comment by gucong3000** [comment]
It's a little bit different from the local SonarQube, it has a parameter called "organization".

**Comment by paulmelnikow** [comment]
Would you like to open a pull request?

**Comment by paulmelnikow** [comment]
Hi, thanks for your question. Would you like to open a pull request?

**Comment by capslocky** [comment]
By the way, SonarCloud itself has badge [plugin](https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/wiki/Quality-Gate-status-badges):
[https://sonarcloud.io/api/badges/gate?key=WcfSoapLogger](https://sonarcloud.io/api/badges/gate?key=WcfSoapLogger)

**Comment by gucong3000** [comment]
When I tried Sonarcloud.io, I decided to drop the plan about this issue.

**Comment by replaysMike** [comment]
> By the way, SonarCloud itself has badge [plugin](https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/wiki/Quality-Gate-status-badges):
> https://sonarcloud.io/api/badges/gate?key=WcfSoapLogger

It does not function with private repos.
