### ISSUE TITLE
Optional option for longer delay for „last-commit“ badge color updates

### ISSUE THREAD

**Issue by dariusptrs** [badges/shields#10766]
:clipboard: **Description**

I’d like to suggest adding different levels or longer delays for how quickly the “Last Commit” badge colors change. For example, in our case of a student project where updates naturally occur less frequently, the current system may mark them as outdated too quickly. An optional delay where badges turn yellow after 1 year and red only after 2–3 years would better reflect the nature of such projects, where files can remain relevant for a longer time.

**Comment by jNullj** [comment]
Hey @dariusptrs.
This is very similar to some other requests we had in the past, take a look at #6135.
This is more then just "last-commit" you could argue for adding this for all badge of the same category similar to a PR #10685.

In short, we usually don't add configuration options that breaks the consistency across badges.

**Comment by dariusptrs** [comment]
I understand your point. 

Especially if extended to other badges that also rely on date metrics. But I think in the last commit badge, the date itself is more important than the color, meaning that consistency wouldn’t truly be broken. People focus on the date rather than relying solely on the color. 

An `update-frequency` parameter could define thresholds that align with different standards for updates in different projects.

Also keeping the current state as the default threshold would ensure consistency across existing projects while still offering flexibility for others.

Let me know what you guys think 😃

**Comment by jNullj** [comment]
Thank you for elaborating on your perspective, let me try and make a bit of a more detailed discussion:

last-commit uses the standard `renderDateBadge` helper function, this is used for many shield badges.
This functions would set colors with the following logic:
| age(days) | color      |
|------------|------------|
| 7          | brightgreen|
| 30         | green      |
| 180        | yellowgreen|
| 365        | yellow     |
| 730        | red        |

This standard ensures that users can quickly understand and interpret the age of a project based on colors, regardless of the badge type. Uniformity across badges is a project goal.

While I see the value in your suggestion, particularly for use cases where files remain relevant for longer, adding customizable thresholds could introduce inconsistencies. Users might find it confusing if the same colors imply different things across projects.
This is a law of nature, when trying to make one value to fit all we are bound to miss edge cases.

That said, your idea of maintaining the current thresholds as defaults does mitigate this concern to some extent. However, flexibility might also dilute the clarity of what the colors represent on a broader scale.
Yes the value is a more explicit, but why break coherence with the color which delivers information just as well? even more so where this specific function is so common in badges. imo consistency is more impotent here.

For highly specific needs, like a custom update-frequency parameter, hosting an instance with tailored thresholds could be a viable solution. This ensures the broader system remains consistent while still accommodating unique use cases.

Do you think a tailored instance is a good balance for this case?
If you still have some points to bring up feel free to do so, i would also love if you could mention specific use cases with values.
If you still think this change does not conflict with the project's goals i could mark the issue as `needs-discussion` to try and get other maintainers to join the conversation, as i understand our discussion so far boils down to what role colors play in badge consistency and informing users.

**Comment by dariusptrs** [comment]
Thanks for your message. I think a tailored instance might be worth a try. I just need to change the values in my fork and follow the guidelines for hosting from source then?

**Comment by dariusptrs** [comment]
And do you think I can make it work with AWS Lambda?

**Comment by chris48s** [comment]
One possible option here for you're project would be to use a custom `color=`
e.g:
https://img.shields.io/github/last-commit/badges/shields?color=blue
![](https://img.shields.io/github/last-commit/badges/shields?color=blue)
That would show the date, but then the colour doesn't change based on the value. That doesn't give you the ability to inject a custom scale/thresholds, but if your problem is "we want to show the last commit date, but we disagree with the colour scheme", maybe that's a viable solution?

**Comment by dariusptrs** [comment]
> One possible option here for you're project would be to use a custom `color=`
> 
> e.g:
> 
> https://img.shields.io/github/last-commit/badges/shields?color=blue
> 
> ![](https://img.shields.io/github/last-commit/badges/shields?color=blue)
> 
> That would show the date, but then the colour doesn't change based on the value. That doesn't give you the ability to inject a custom scale/thresholds, but if your problem is "we want to show the last commit date, but we disagree with the colour scheme", maybe that's a viable solution?

I thought about that idea, but we do not disagree with the current color scheme. I like the fact that the colors resemble how "up-to-dare" a project is. 

The thing is that our student project offers cheat sheets and summaries for other students. These are usually very up-to-date with current lectures even if the last update was one or two years ago. If cheat sheets are shown as red too early they might be misinterpreted as outdated, even if they are still relevant. That is our specific use case. You can have a look [here](https://latex4ei.de). Also since the same lecture is only repeated every second semester, updates are naturally not consistent throughout a year.

Is there a badge for GitHub's "last updated" already? I mean the date that updates on every activity in the repo (also on new issues or pull requests). Maybe the threshold could be included only in there, which would not break any concictency with currently used badges?

**Comment by chris48s** [comment]
As a general principle, the ability to set custom thresholds for the values where colour changes take place via URL params isn't a customisation we plan to offer for any badge.

We don't have a badge for github repo last updated. If it is something you're interested in, feel free to open a badge request for that one https://github.com/badges/shields/issues/new?template=3_Badge_request.yml
