### ISSUE TITLE
Linkedin Badge Custom Color

### ISSUE THREAD

**Issue by Heber-Dsouza** [badges/shields#10775]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hello, there is an issue when I apply a custom color to the LinkedIn icon. Any color other than #0A66C2 causes the icon to disappear.

### 🔗 Link to the badge

https://img.shields.io/badge/LinkedIn-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white

try any color other than #0A66C2

**Comment by Heber-Dsouza** [comment]
This error is happening when I'm using this badge inside my github's README.md profile.

**Comment by LitoMore** [comment]
The icon has been removed since Simple Icons 14. See:

- #10772
- https://github.com/simple-icons/simple-icons/pull/11380

You can still see the icon now because there is a cache.

**Comment by Heber-Dsouza** [comment]
> The icon has been removed since Simple Icons 14. See:
> 
>     * [🚀 SimpleIcons 14 #10772](https://github.com/badges/shields/issues/10772)
> 
>     * [Remove LinkedIn simple-icons/simple-icons#11380](https://github.com/simple-icons/simple-icons/pull/11380)
> 
> 
> You can still see the icon now because there is a cache.

Okay, thank you. Sorry for creating a duplicate issue.

**Comment by chris48s** [comment]
Going to close this one. No action to be taken here.
