### ISSUE TITLE
colorB is ignored on all docker badges

### ISSUE THREAD

**Issue by joshuaavalon** [badges/shields#1080]
Use `alpine` as an example.

Docker Stars (Color A): ![](https://img.shields.io/docker/stars/_/alpine.svg?colorA=dfb317)
Docker Stars (Color B): ![](https://img.shields.io/docker/stars/_/alpine.svg?colorB=dfb317)

They behavior the same on all docker badges.

**Comment by paulmelnikow** [comment]
Thanks @ritwickdey!
