### ISSUE TITLE
Provide an Asciidoc copy/paste snippet in popup

### ISSUE THREAD

**Issue by mkobit** [badges/shields#1104]
![No Asciidoc copy and paste snippet provided](https://user-images.githubusercontent.com/1447148/30918881-75e911f2-a365-11e7-8d41-700677ccb0ac.png)

Would be nice to have an Asciidoc snippet provided an addition to Markdown and reStructuredText

**Comment by paulmelnikow** [comment]
What would the asciidoc snippet look like? Also, would you be interested in making a pull request?

**Comment by mkobit** [comment]
An example:

Markdown:

```
[![Codeship](https://img.shields.io/codeship/d6c1ddd0-16a3-0132-5f85-2e35c05e22b1/master.svg)]()
```

An Asciidoc example (not supplying `alt`, `title`, `caption` or other attributes):

```
image:https://img.shields.io/codeship/d6c1ddd0-16a3-0132-5f85-2e35c05e22b1/master.svg[Codeship]
```

I can take a quick shot at a PR

**Comment by paulmelnikow** [comment]
All that stuff is in right in `try.html`. I haven't played around with it yet, so I'm really not sure about the state of the code. Let me know if you have questions and I'll do my best to help.
