### ISSUE TITLE
Add Travis CI logo to build badge

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1107]
Basically same as https://github.com/badges/shields/issues/507 (AppVeyor logo)

It would be very handy to have a logo on the badge for travis too.
With the upcoming `?logo=` (#1092) addition we are fully customizable then. 👍 

Logo could be the travis `T` or the helmet for example. The complete travis face might have too much details for a little logo.

**Comment by paulmelnikow** [comment]
In #1092 @tylerl0706 asked:

> If I want to contribute an svg, are there any requirements? (single color, etc)

Good question. Definitely compressed using SVGo. Single color is a good idea, too. Level of detail should be reduced enough that it looks decent on a badge without being unnecessarily large.

**Comment by techtonik** [comment]
If helmet could be reduced to just basic recognizable silhouette - that would be cool.

**Comment by RedSparr0w** [comment]
Full logo does look a bit too large for the badge, although still recognizable.
![image](https://user-images.githubusercontent.com/7288322/32297751-1270815c-bfb5-11e7-8c6c-798abf87f442.png)
![image](https://user-images.githubusercontent.com/7288322/32298044-fe1ef502-bfb5-11e7-98a0-0b8fbb0303d0.png)
The hat also looks quite small
![image](https://user-images.githubusercontent.com/7288322/32297884-8b4666a0-bfb5-11e7-9264-bd76325d6a6a.png)
unless you use `&logoWidth=18`
![image](https://user-images.githubusercontent.com/7288322/32298087-1c3f0126-bfb6-11e7-9aa6-cd403210830e.png)
or `&logoWidth=20`
![image](https://user-images.githubusercontent.com/7288322/32297963-c3795b2c-bfb5-11e7-86c5-3a2b827f33ac.png)

**Comment by paulmelnikow** [comment]
Here's a link to a reduced(?) favicon. Is it any better?

https://cdn.travis-ci.org/images/favicon-c566132d45ab1a9bcae64d8d90e4378a.svg

**Comment by RedSparr0w** [comment]
Think the lines might be a little too thin on that one
![image](https://user-images.githubusercontent.com/7288322/32301121-6c8be58a-bfc1-11e7-8a3b-b99069b59872.png)

**Comment by RedSparr0w** [comment]
or maybe `style=logo`?
![image](https://user-images.githubusercontent.com/7288322/32301799-4c40e43a-bfc4-11e7-9855-d3472de99736.png)
with `label=%20`
![image](https://user-images.githubusercontent.com/7288322/32301842-8089c2ca-bfc4-11e7-9ac2-502c1321f968.png)
with a single color logo
![image](https://user-images.githubusercontent.com/7288322/32301573-62bbf39a-bfc3-11e7-92b9-77d87b9367f6.png)
_looks better with a black background when the logo is white_
![image](https://user-images.githubusercontent.com/7288322/32301913-deb66baa-bfc4-11e7-982d-ed3b72e905c9.png)

But this does go against the spec
>The left-hand side of a badge should not advertize. It should be a noun describing succinctly the meaning of the right-hand-side data.

**Comment by paulmelnikow** [comment]
What about just using the mustache?

**Comment by tooomm** [comment]
>What about just using the mustache?

Or the travis `T` with the mustache on top. The mustache overlay would need to cut in the T to make it more distinct and visible maybe. Maybe it looks really bad, just throwing one idea more.
Recognizable options are limited it looks like...

**Comment by RedSparr0w** [comment]
Good ideas will have to give them a try when I get near a computer!
Although not sure how travis-ci would feel about us rebranding their logo for badges 😆

**Comment by techtonik** [comment]
Black on white logo is recognizable. Colored as well. Inversed not so. Maybe leave it on white background somehow?

**Comment by RedSparr0w** [comment]
Don't think just the mustache works too well:

![image](https://user-images.githubusercontent.com/7288322/32581333-6a727632-c54e-11e7-98e4-df8cb9f3f396.png)
`logoWidth=26`:
![image](https://user-images.githubusercontent.com/7288322/32581309-556b05ec-c54e-11e7-9c3f-18642b9df01f.png)

I would say if anything it would have to be one of the following:
![image](https://user-images.githubusercontent.com/7288322/32297751-1270815c-bfb5-11e7-8c6c-798abf87f442.png)
![image](https://user-images.githubusercontent.com/7288322/32298044-fe1ef502-bfb5-11e7-98a0-0b8fbb0303d0.png)
![image](https://user-images.githubusercontent.com/7288322/32581402-b7e79c80-c54e-11e7-8650-ba6a944ada4b.png)

**Comment by tylerl0706** [comment]
What about just an outlined version of the `T` sorry I can't contribute a visual right now

**Comment by techtonik** [comment]
![](https://user-images.githubusercontent.com/7288322/32298044-fe1ef502-bfb5-11e7-98a0-0b8fbb0303d0.png)
but if colored is preferred, then
![](https://user-images.githubusercontent.com/7288322/32581402-b7e79c80-c54e-11e7-8650-ba6a944ada4b.png)

**Comment by tooomm** [comment]
>https://github.com/badges/shields/issues/1107#issuecomment-343005239

Mustache only doesn't work, yes... :)

It looks like the black version on light background is easiest to recognize! But the badge left part is darkish...
I mean, the original Appveyor logo is white (https://ci.appveyor.com), but we use a greyish version: ![appveyor logo](https://user-images.githubusercontent.com/9874850/32603205-28b7182e-c549-11e7-9879-3b3207855f93.png)
A lesser vivid white version of travis might do the trick here too!

**Comment by phonicmouse** [comment]
I want this !!!!!

**Comment by techtonik** [comment]
> A lesser vivid white version of travis might do the trick here too!

+1

**Comment by RedSparr0w** [comment]
Color | Example | Preffered
:-- | :--: | :--:
`#ccc` | ![image](https://user-images.githubusercontent.com/7288322/32639238-c6b81ba2-c627-11e7-9580-5191df42f808.png) | 👍 
`#fff` | ![image](https://user-images.githubusercontent.com/7288322/32298044-fe1ef502-bfb5-11e7-98a0-0b8fbb0303d0.png) | 😄 
`color` | ![image](https://user-images.githubusercontent.com/7288322/32639304-1b5bbe3e-c628-11e7-971e-e1fe41d109c2.png) | 🎉 

Add a reaction for your preferred logo style(s) and i will try get a PR started in the next few days.

**Comment by paulmelnikow** [comment]
@RedSparr0w Do you have svg links for those? Would be curious to see what they look like @ 2x.

**Comment by tooomm** [comment]
Here is a side-to-side comparison, most people might end up putting them next to each other:
- ![](https://user-images.githubusercontent.com/7288322/32639419-c091acd8-c628-11e7-97de-6ea22dc4d990.png) ![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=appveyor&style=flat-square)

<br>

- ![](https://user-images.githubusercontent.com/7288322/32298044-fe1ef502-bfb5-11e7-98a0-0b8fbb0303d0.png) ![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=appveyor&style=flat-square)

<br>

- ![](https://user-images.githubusercontent.com/7288322/32639304-1b5bbe3e-c628-11e7-971e-e1fe41d109c2.png) ![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=appveyor&style=flat-square)

<br>

I tend to like the white one more here, a bit easier to recognize then the appveyor-grey (ddd). But did you play around with a not as bright white? Like 80-90% white?
Is colored a real consideration? Regarding the other logos only twitter is colored.
Maybe we want some design decision there too... for consistancy and a clean look. Only whitish/greyish logos for example. Or black.
Most of them are white; appveyor is grey; twitter colored; github, gitter and telegram are black...

**Comment by phonicmouse** [comment]
The coloured one is just really bad I think...i prefer the 100% white one, I think it suits better near the build label which is white.

**Comment by RedSparr0w** [comment]
A quick mockup svg with the travis logo here:
`http://shields.redsparr0w.com/static/badge.svg?logo=travis&color=white`
change color to whatever you like `rgb(255,255,255)` `black` `ccc` `ffffff` etc.
![](http://shields.redsparr0w.com/static/badge.svg?logo=travis&color=white)
![](http://shields.redsparr0w.com/static/badge.svg?logo=travis&color=ddd)
![](http://shields.redsparr0w.com/static/badge.svg?logo=travis&color=rgb\(200,200,200\))
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=travis&color=white" height="40"/>

**Comment by paulmelnikow** [comment]
Thanks, those are super helpful. Could you drop them into your post above?

**Comment by RedSparr0w** [comment]
Updated post above,
Looks like `#fff` is the favorite currently, will most likely create the PR on Monday.
I may start working on a PR to allow logo color selection sometime soon too.

**Comment by ppalaga** [comment]
I cannot see `travis.svg` in https://github.com/badges/shields/tree/gh-pages/logo . Maybe somebody should just publish the master to gh-pages?

**Comment by paulmelnikow** [comment]
The copy of `travis.svg` needs to be on the server, so the server needs to be deployed.

**Comment by techtonik** [comment]
I thought shield.io is continuous deployment, but well.. Is there a doc about deployment process?

**Comment by paulmelnikow** [comment]
Deploys usually happen every 1–3 weeks. Thaddée, who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account is shared with other services he runs.

**Comment by techtonik** [comment]
Hosting is Cloudflare. Is that some special offer?

**Comment by RedSparr0w** [comment]
I may be wrong, but i don't think Cloudflare offers hosting?
They are just the name server from what i can see.

**Comment by techtonik** [comment]
https://check-host.net/ip-info?host=shields.io shows that shields.io IP belongs to Cloudflare.

**Comment by Thedude7054** [comment]
I'm a little confused. Has this been implemented? And if so, how does an end user access and use the travis logo?

**Comment by calebcartwright** [comment]
@Thedude7054 - yes logos are available

https://github.com/badges/shields/blob/master/doc/logos.md

For example
https://img.shields.io/travis/rust-lang/rust?logo=travis
![](https://img.shields.io/travis/rust-lang/rust?logo=travis)
