### ISSUE TITLE
GitHub now caches SSL images in README on main repository badge

### ISSUE THREAD

**Issue by sqs** [badges/shields#111]
GitHub apparently must have just recently started caching SSL images in READMEs on a repository's main page.

For example, go to https://github.com/bower/bower and check the image URLs for the Travis CI and Sourcegraph badges. They are cache URLs: `https://github-camo.global.ssl.fastly.net/007fb2bce5...`.

But if you go to https://github.com/bower/bower/blob/master/README.md, the badge image URLs are the original URLs (https://secure.travis-ci.org/bower/bower.png?branch=master and https://sourcegraph.com/api/repos/github.com/bower/bower/counters/views-24h.png and).

The HTTP headers include a link to https://camo.githubapp.com/, which suggests that GitHub is **camo**uflaging these HTTP requests. It's not just camouflaging, though; GitHub's CDN also appears to be caching the images in violation of (for a longer duration than allowed by) the origin server's cache headers.

I wanted to bring this up because it affects how dynamic the badges can be. Previously, I think we had all assumed that GitHub would not cache SSL images.

**Comment by hobbyquaker** [comment]
I made a little tool to clear the camo cache, you can call that in your build process to keep your badges always up to date. https://github.com/hobbyquaker/camo-purge
