### ISSUE TITLE
download count for latest pre-release

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1113]
We have a download count badge with several options for github releases, e.g. for a fixed tag or more importantly last release (since it updates automatically with your new releases):
![dl from latest-pre](https://user-images.githubusercontent.com/9874850/31031491-fc8c240c-a558-11e7-9f59-5dd4d4ce4240.png)

I request a download count for "latest pre-release" as well. Some repos use releases for stable versions and
pre-releases for betas for example. So both badges would show always up to date data without the need to update the badge to a hard coded tag all the time.

**Comment by platan** [comment]
As fas as I can see [GitHub REST API](https://developer.github.com/v3/repos/releases/) does not allow to get latest prerelease or even filter all releases to get only prereleases. So we have to list all releases and find prerelease. Do we want to do in this way? We could add some limits, e.g. check only first page of results (30 by default, max 100).

**Comment by paulmelnikow** [comment]
If 2.0.0-rc2 is followed by 2.0.0, it's not helpful to see stats for 2.0.0-rc2 on a badge. So, the Shields semantics for "latest (pre-)release" is "latest release including prereleases." `downloads-pre` includes prereleases, and `downloads` excludes prereleases. It's the same idea as #1133.

**Comment by platan** [comment]
Thanks! OK. I will do it in this way.

**Comment by paulmelnikow** [comment]
Done in #1140.

**Comment by tooomm** [comment]
So I wait for the next deploy now. A lot of great PR's with interesting new possibilities recently! 👍
