### ISSUE TITLE
how to add several customizations to a badge

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1124]
For example:
How to add both, a custom label on the left and a custom color to the right of a badge

I tried `https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test?color=orange`
but it returns: ![](https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test?color=orange)

**Comment by paulmelnikow** [comment]
Hi, thanks for your question. You need to separate them with an `&`:

`https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test&color=orange`

**Comment by tooomm** [comment]
I experimented with several separators and connectors before opening this pr, without success.
Your example isn't working either: ![](https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test&color=orange)

But I realized now that I copy and pasted the wrong url, I actually have to use `colorB` instead `color`.
If I use that with your customization I get this result:  ![](https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test&colorB=orange)

**Very weird that it changes from blue to green, even though the input is wrong...**

<br>

Whit correct HEX color codes as stated on the website it works finally, my bad. ![](https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg?label=test&colorB=f37f40)

**Comment by paulmelnikow** [comment]
I noticed the syntax looked correct but didn't notice the color. Glad you figured it out. Agreed, it would be good if the same color parameters worked consistently everywhere.
