### ISSUE TITLE
Add badge for gradle plugin portal

### ISSUE THREAD

**Issue by StefMa** [badges/shields#1125]
It would be cool if we have a badge for the [gradle plugin portal](https://plugins.gradle.org/).

I image it like similar the maven central or the bintray badge.
[![Bintray](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg)]() (If it's working of course 🙃)
[![Maven Central](https://img.shields.io/maven-central/v/org.apache.maven/apache-maven.svg)]()
plugin portal | v0.9.95

You can use this URL for example: (don't know how shields works, but I think you need that 😄)
https://plugins.gradle.org/plugin/org.shipkit.java-publish/0.9.95

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion. Do they have a public API?

**Comment by StefMa** [comment]
I can't find one :disappointed:
Even something like `_latest` doesn't work...

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed

**Comment by radarsh** [comment]
In the meantime, can't we just parse the output of `https://plugins.gradle.org/plugin/<plugin-id>` and extract the output? This would be abstracted by the shields.io API so when Gradle does expose a public API for getting just the version, we could always update the shields.io implementation.

**Comment by paulmelnikow** [comment]
Shields has limited server resources so we avoid parsing HTML for performance reasons.

Wanted to link gradle/gradle#1477 which is the request for an API.

**Comment by loosebazooka** [comment]
@paulmelnikow I wrote a dumb parser, it should work for most cases. It currently redirects to a shield badge, which does not appear to be the way the maven badge thing works, but this is just a prototype, happy to rewrite it to match the shields.io style for plugins(?).

https://github.com/loosebazooka/gradle-plugin-badges

**Comment by StefMa** [comment]
Just for reference:
https://github.com/badges/shields/issues/1839 & https://github.com/gradle/gradle/issues/1477#issuecomment-410068172

**Comment by Horcrux7** [comment]
With the maven repo https://plugins.gradle.org/m2/  and the Maven metadata URL it work for me.

[![Maven metadata URL](https://img.shields.io/maven-metadata/v?label=Plugin&metadataUrl=https%3A%2F%2Fplugins.gradle.org%2Fm2%2Fde%2Finetsoftware%2Fjwebassembly%2Fde.inetsoftware.jwebassembly.gradle.plugin%2Fmaven-metadata.xml)](https://plugins.gradle.org/plugin/de.inetsoftware.jwebassembly)

`[![Maven metadata URL](https://img.shields.io/maven-metadata/v?label=Plugin&metadataUrl=https%3A%2F%2Fplugins.gradle.org%2Fm2%2Fde%2Finetsoftware%2Fjwebassembly%2Fde.inetsoftware.jwebassembly.gradle.plugin%2Fmaven-metadata.xml)](https://plugins.gradle.org/plugin/de.inetsoftware.jwebassembly)`

**Comment by anatawa12** [comment]
@paulmelnikow Can you/we add the Gradle Plugin Portal badge as an alias of https://github.com/badges/shields/issues/1125#issuecomment-588435609? 

The plugin marker artifact's group id is the id of the plugin and artifact id is `<gradle plugin id>.gradle.plugin` so It's possible to make an alias. I think it's not undocumented or reverse-engineered API endpoints because the Plugin Marker Artifact system is documented at [Using Gradle Plugins](https://docs.gradle.org/7.0/userguide/plugins.html#sec:plugin_markers).
