### ISSUE TITLE
Text for Mozilla Addon Rating is wrong

### ISSUE THREAD

**Issue by xmcp** [badges/shields#1130]
![](https://img.shields.io/amo/rating/adblock-plus.svg)

The `/amo/rating/` badge should display "rating x/5", but it now displays "downloads x/5".

**Comment by paulmelnikow** [comment]
Thanks. That was just fixed in #1127 which is waiting for review.

**Comment by paulmelnikow** [comment]
Fixed in #1127.

**Comment by xmcp** [comment]
The text is still buggy on shield.io

**Comment by paulmelnikow** [comment]
Last deploy was 11 days ago. You can keep an eye on https://github.com/badges/shields/tree/gh-pages to see when the deploy happens.
