### ISSUE TITLE
github issue count badge isn't working for label with spaces

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1134]
Label with spaces in between, like "help wanted", aren't displaying the correct value. They always display "0".

https://github.com/Cockatrice/Cockatrice/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+Change%22
One would use this badge url in the above case I guess:
"https://img.shields.io/github/issues/Cockatrice/Cockatrice/Easy%20Change.svg"

**Comment by paulmelnikow** [comment]
I opened #1135.
