### ISSUE TITLE
[GitHub] Add repository main programming language badge

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#1139]
Hello,

Opening an issue beforehand before diving into any implementation, as suggested by the guidelines.

I believe that there is no badge to display the main programming language of a repository. This could be a useful addition! 

A [Github API endpoint](https://developer.github.com/v3/repos/#list-languages) is available to retrieve the list of all languages used in the repository, alongside the number of bytes of code written in each language.

Does this seem like a desirable new badge?

Cheers,

Pyves

**Comment by paulmelnikow** [comment]
Nice idea! Though one thought I have is, is this something that is likely to change once a repository is created? We could avoid making an API call to Github by constructing the badge like this:

https://img.shields.io/badge/language-javascript-blue.svg

**Comment by PyvesB** [comment]
I would say it depends on the repository. Some might be on the tipping edge between two languages, some specific repositories might drift over time (for instance [this one](https://github.com/PyvesB/hello-world) has progressively moved towards assembly). I guess it would be useful to have the choice to use a slightly more elaborate version that also includes the percentage for that top language?

**Comment by ritwickdey** [comment]
Hi, do you meant like that? ![](https://img.shields.io/badge/language-javascript%2035.5%25-blue.svg)

**Comment by PyvesB** [comment]
Yes, something like that. I'll attempt an implementation and see how things turn out.

**Comment by paulmelnikow** [comment]
How about this?

![](https://img.shields.io/badge/javascript-35%25-blue.svg)

**Comment by PyvesB** [comment]
I like this new version, best we've got so far!

**Comment by ritwickdey** [comment]
Would you like to submit a PR?

**Comment by PyvesB** [comment]
@ritwickdey yes, I'm making progress on this piece of work.
