### ISSUE TITLE
How does the overall architecture work?

### ISSUE THREAD

**Issue by dogweather** [badges/shields#114]
Hi, I'm very intrigued by the product, but I couldn't figure out:
- How are badges dynamically generated?
- Is this a hosted service?
- Is the code open?
- Or is this simply a design specification, or is there code?
- Is this intended for use by other projects which would like to issue badges?
- If so, how would this be used?

Thanks!

**Comment by zbeekman** [comment]
+1 for FAQ and better documentation

**Comment by espadrine** [comment]
@zbeekman I feel like it would make sense if an FAQ and technical walk-through would reside in CONTRIBUTING.md (to which we can link from the homepage). Please contribute all questions you'd like to have answered, I'll work on that this week-end.

**Comment by paulmelnikow** [comment]
After #2661 we'll have some pretty decent documentation of the production hosting which explains the architecture of the system pretty well.

A high-level walkthrough of the code would be helpful. Let's track that in #2684. Feel like the rest of this is pretty well covered by now :)
