### ISSUE TITLE
[Request] Add clojars downloads badge

### ISSUE THREAD

**Issue by flyboarder** [badges/shields#1152]
Would be awesome to get clojars downloads.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. Is there a public API for downloads?

**Comment by flyboarder** [comment]
@paulmelnikow Yes! https://github.com/clojars/clojars-web/wiki/Data#download-stats

**Comment by paulmelnikow** [comment]
Excellent!

We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). Would you be interested in making a pull request?

**Comment by flyboarder** [comment]
@paulmelnikow I took a look through the tutorial  but couldn't figure out how to parse the statistical data, it's in edn format.

**Comment by paulmelnikow** [comment]
It looks like the artifacts endpoint provides download stats. It would also safe us fetching that entire file, which would be good.

**Comment by flyboarder** [comment]
@paulmelnikow thanks, PR added!
