### ISSUE TITLE
[Request] Version badge for JetBrains Plugin

### ISSUE THREAD

**Issue by ice1000** [badges/shields#1162]
It would be great if we have Version badge for JetBrains Plugin.

I see there's download badge for JetBrains Plugin, and I'm looking forward to the version badge for it.

**Comment by paulmelnikow** [comment]
Hi! Is there a public API for this?

**Comment by ice1000** [comment]
Yeah! You can get the newest version from an xml, i.e.

https://plugins.jetbrains.com/plugins/list?pluginId=9630-a8translate.json

**Comment by platan** [comment]
We are already using this API for JetBrains plugin downloads badge https://github.com/badges/shields/blob/master/server.js#L6534, here you can find tests https://github.com/badges/shields/blob/master/service-tests/jetbrains.js

Would you like to submit a PR?

**Comment by ice1000** [comment]
OK, after I finish this when will it be merged?

**Comment by ice1000** [comment]
Created pr #1164
