### ISSUE TITLE
impossible to use certain characters for badge label names

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1170]
I wanted to name a travis badge `linux & unix build`, to make crystal clear what's going on in comparison to the appveyor badge named `win build`.

While I made the spaces work with `%20` (no documentation about that!), it was not possible to display `&` or `+`. I tried different html codes like `&amp`, without success.
While any attempt to make a "&" appear resulted in the following text being cut off.
All efforts to display a "+" made all text appear, just without the plus symbol itself.

**Comment by paulmelnikow** [comment]
You need to URL-encode it the string. Indeed, `%20` is a space, and `%26` is an ampersand, so `linux & unix build` is `linux%20%26%20unix%20build`.

![](https://img.shields.io/badge/foo-bar-blue.svg?label=linux%20%26%20unix%20build)

A tool like https://meyerweb.com/eric/tools/dencoder/ could also help.

Want to add something to the documentation?

**Comment by tooomm** [comment]
Thank you very much. Quick and helpful, as always! :)

Will look into a PR

**Comment by paulmelnikow** [comment]
Here's a reference you could include: https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding
