### ISSUE TITLE
provide dynamic badges for HuBoard

### ISSUE THREAD

**Issue by whit537** [badges/shields#118]
Requested by @rauhryan in [IRC](https://botbot.me/freenode/gittip/msg/11089085/).

What metadata do we want to show for this?

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
