### ISSUE TITLE
Support renaming badges for Jenkins private instances

### ISSUE THREAD

**Issue by kathy-er** [badges/shields#1191]
Thanks for providing such a great tool!

I'm curious how does Shields io support private Jenkins jobs. My build is private and anonymous only has ViewStatus permission. I'd like to create Markdown badge and rename the label for it.

Tried the following links and both show `my_project | unresponsive`

- https://img.shields.io/jenkins/s/https/jenkins.cchh.io/job/TestAutomation-ApiAuthorizationTests-Bizcore.svg?label=my_project
- https://img.shields.io/jenkins/s/https/jenkins.cchh.io/buildStatus/icon.svg?label=my_project&job=TestAutomation-ApiAuthorizationTests-Bizcore (unprotected URL suggested by Jenkins)

It'll be great if we can dynamically show the status for builds like this :) 

<img width="127" alt="screen shot 2017-10-20 at 11 16 05 am" src="https://user-images.githubusercontent.com/15787849/31835867-2158aeec-b588-11e7-905c-a7d6e6fca786.png">

**Updated**: this sample badge comes from https://img.shields.io/badge/my__project-passing-brightgreen.svg

**Comment by paulmelnikow** [comment]
Hi there! This request is timing out:

https://jenkins.cchh.io/job/TestAutomation-ApiAuthorizationTests-Bizcore/api/json?tree=color

The **my_project** label seems to be overriding just fine.

**Comment by kathy-er** [comment]
@paulmelnikow Thanks for following up! There's no problem with label overriding, but project status is not showing correctly (`unresponsive`).

If using Jenkins official badge link it won't allow re-label: https://jenkins.cchh.io/job/TestAutomation-ApiAuthorizationTests-Bizcore/badge/icon?label=my_project

What would you recommend in my case?

**Comment by paulmelnikow** [comment]
This project has no control over what a Jenkins endpoint returns, so you could try one of these three options:

1. Make your Jenkins server publicly accessible, and load the badge from img.shields.io
2. Ask Jenkins to support relabeling in their official badge.
3. Host your own Shields server, on a machine with access to your Jenkins server.

**Comment by kathy-er** [comment]
Thanks for sharing the possible options.
