### ISSUE TITLE
Badge request: Bintray package downloads

### ISSUE THREAD

**Issue by nisrulz** [badges/shields#1193]
Consider a badge for displaying total download stats of a package from a Bintray repository. 

The API call is explained at 
+ https://bintray.com/docs/api/#_get_total_downloads
+ https://blog.bintray.com/tag/download-statistics/

Other possible stats 
1. [Get Daily Downloads](https://bintray.com/docs/api/#_get_daily_downloads)
1. [Get Downloads by Country](https://bintray.com/docs/api/#_get_downloads_by_country)

Proposed syntax:

```
https://img.shields.io/bintray/downloads/stats/:subject/:repo/:package/total.svg
https://img.shields.io/bintray/downloads/stats/:subject/:repo/:package/latest/total.svg
https://img.shields.io/bintray/downloads/stats/:subject/:repo/:package/v1.0.0/total.svg
```

**Comment by paulmelnikow** [comment]
For consistency, would suggest:
```
https://img.shields.io/bintray/dt/:subject/:repo/:package.svg
https://img.shields.io/bintray/dt/:subject/:repo/:package/latest.svg
https://img.shields.io/bintray/dt/:subject/:repo/:package/v1.0.0.svg
```

**Comment by mwz** [comment]
+1

**Comment by nisrulz** [comment]
Any updates on this?

**Comment by paulmelnikow** [comment]
Would you be interested in implementing it? We have a good tutorial: https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by nisrulz** [comment]
@paulmelnikow I could give it a try. Thank you for putting a reference to the tutorial, so now I have a starting point 😸

**Comment by GuilhE** [comment]
> The Bintray REST API requires an applicative API key. An API key can be obtained from the user profile page. Authentication is achieved using HTTP Basic Authentication with the user’s name as username and the API key as the password. Authenticated REST calls should only be used via HTTPs.

[docs](https://bintray.com/docs/api/)

Isn't this a problem? 🙄 
Does shields query any authenticated API?

**Comment by mwz** [comment]
Hi @nisrulz, did you manage to get anywhere with this?

**Comment by nisrulz** [comment]
@mwz no. I have been occupied at work a lot and haven't been able to readup and implement this. I hope to pick it up sometime later.

**Comment by mpetuska** [comment]
#5316 implements the following: 
```
https://img.shields.io/bintray/dt/:subject/:repo/:package.svg (total count)
https://img.shields.io/bintray/dt/:subject/:repo/:package/latest.svg (count for latest version)
https://img.shields.io/bintray/dt/:subject/:repo/:package/v1.0.0.svg (count for specific version)
```
