### ISSUE TITLE
Support renewed Code Climate's ratings

### ISSUE THREAD

**Issue by blooper05** [badges/shields#1196]
They have changed their measurement policy.
http://blog.codeclimate.com/blog/2017/09/21/a-new-clearer-way-to-understand-code-quality/

And official badge's designs too.
https://docs.codeclimate.com/docs/overview#section-badges

**Comment by Nickersoft** [comment]
Was just about to post this same thing... while the CC code coverage badge still works, the regular CC badge doesn't. Would love to see this fixed as I just upgraded my Code Climate to the new format 👍

**Comment by paulmelnikow** [comment]
We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). Would you like to make a pull request?

**Comment by Nickersoft** [comment]
@paulmelnikow I can look into it.. wasn't aware there was a tutorial. Good to see to see it's well documented! Would you happen to know if the current Code Climate badge requires an auth token of some sort? It seems the new API requires one at least.

**Comment by paulmelnikow** [comment]
No, it doesn't look like [the code for the current badges](https://github.com/badges/shields/blob/a54338afa8cfa1cf480117bf9d6b56b06f69ebec/server.js#L2490-L2614) makes use of one.

**Comment by Nickersoft** [comment]
@paulmelnikow How's this? https://github.com/badges/shields/pull/1236

**Comment by PyvesB** [comment]
We have recently rewritten the code for all Code Climate badges (see #1387 and #1368) and we're effectively supporting their new rating system. Therefore closing this issue. 😉
