### ISSUE TITLE
new "for the badge" style preview wrong size

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1206]
![styles](https://user-images.githubusercontent.com/9874850/31994435-eea95f94-b980-11e7-9e44-313d4b2befe4.png)

For all used instances on the shields site the "for the badge" style has the correct styling, but has the same size as all other badges.
Actually this new ones are like double the size if you use them, which is correct. But the available styles list and per-badge previews should account for that and show realistic previews.

Size comparison: (lower one with `?style=for-the-badge` attached)
![comparison](https://user-images.githubusercontent.com/9874850/32011997-c9ba35ce-b9b6-11e7-8734-2304fa623aba.png)

**Comment by paulmelnikow** [comment]
Yup, makes sense.

How's your HTML/CSS? Are you up for trying to fix it?
