### ISSUE TITLE
Badge request: GitHub milestones

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1209]
https://developer.github.com/v3/issues/milestones/

Would be cool to use a milestone badge to show progress regarding specific targets in the repo, like
- `Next Release | 15/20` (15 issues open from 20 total)
- `Next Release | 75%` (15 issues open from 20 total)
- `Core Restructure | 3 left` (3 open)
- `UI Rewrite | 3 total` ( 3 total open+closed)
- `Modularization | 5 done` (5 closed)
- `New API | 100% done` (all closed)

or milestone count, names, due date etc
- `Milestones | 4 open`
- `Newest Milestone | v3 Release`
- `v3 Release | due until 31.12.2017`

and maybe others

**Comment by M-ZubairAhmed** [comment]
@pathawks i would like to know how can i contribute to this issue ? Could you please some guidance

**Comment by paulmelnikow** [comment]
Hi! We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) which is a good place to start! Then search for `\/github` in `server.js` and you can see how some of the other github badges are handled.

You could start by implementing something like **Next Release | 15 of 20 completed**.

It's worth discussing the design and URL scheme further before you get too far into coding them all.

@tooomm: Would you like to push the discussion further with some proposals on the badges that will be implemented, along with their URLs? One request I would make is that we try to choose a good default over configuration wherever possible. So let's not have a percentage and a count, where a count will do for most use cases.

You can add badge examples to your post with `![](https://img.shields.io/badge/something-else-blue.svg)`.

**Comment by tooomm** [comment]
I can think of this types:
- overall progress (`%` and `closed/total` style)
- issues total + issues open + issues closed
- due time

(all for particular milestones, newest milestone and all milestones combined)
- showing name of newest milestone
- other possibilities would involve status (open, closed), or other time related information (created, updated, closed) - not sure if those would be very useful

**Comment by wrzosdev** [comment]
@M-ZubairAhmed you're working on this? Just need due time, and if you are not maybe i'll take it

**Comment by M-ZubairAhmed** [comment]
@wrzosdev sorry got caught up, please feel free to take it

**Comment by xin-lai** [comment]
？？

**Comment by PyvesB** [comment]
@MacroPower implemented GitHub milestone badges as part of #4747! 🍾 

The new badges should be available soonish, you can track deployment status here: https://github.com/badges/shields/pull/4747#issuecomment-596780843

Will close this issue - if you any ideas to further extend things and improve our badge offering, feel free to open new issues. 😉
