### ISSUE TITLE
License logos

### ISSUE THREAD

**Issue by KOLANICH** [badges/shields#1219]
Some licenses have own logos, sometimes official, sometimes nonofficial ones. So I propose to use them. They may meed to be modified to use here. Here is the list:

* [GNU](https://www.gnu.org/graphics/license-logos.html)
* [WTFPL](http://www.wtfpl.net/download/)
* [CC](https://creativecommons.org/about/downloads/) (some other logos from that page can be useful to describe licenses traits)
* For Apache I guess a feather should be ok (not necessiarely the one used in Apache foundation logo).
* For MIT you should ask the institute if we can use their logos for marking the licenses having the same name
* For BSD I think it'd be fine to use devil emoji with a number of clauses
* [Open Font License](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_logo)
* OdbL doesn't seem to have own logo, but it has [some icons](https://opendatacommons.org/licenses/odbl/summary/) which may be helpful.

Also alongside with colors it'd be nice to have generic logos for licenses.
* ☠️ - for the proprietary ones
* ☣️ - for the viral ones
* mirrored copyright sign - for the copyleft ones
* striked copyright sign - for public domain ones

**Comment by paulmelnikow** [comment]
Per #2510 we won't be adding more icons directly here.

The best place to make this request would be in [simple-icons](https://github.com/simple-icons/simple-icons). Based on a quick check, most of these don't yet exist there.
