### ISSUE TITLE
shields-badge-data (formerly shields-badges-urls)

### ISSUE THREAD

**Issue by mightyiam** [badges/shields#1226]
So, I wrote this little thing, that is related to this project. It would be nice to get a review from the core developers. I'd love your reviews, actually. Before publishing a version to npm.

https://github.com/mightyiam/shields-badges-urls

The biggest challenge is figuring out the `link` property of the return value for each service. Have any tips on that? And while you're at it, if you could [implement a service](https://github.com/mightyiam/shields-badges-urls/issues/5) that you know, that would be sweet. Or **just give a tip regarding the `link` property** for a service that is not [implemented](https://github.com/mightyiam/shields-badges-urls/blob/master/src/services-params.ts), that would also help. I think I made it real easy and simple, with neat code and full coverage tests and CI.

**Comment by paulmelnikow** [comment]
Neat project!

I'd be happy to help with this. People have asked for functionality like this for programmatic use (#776) and in the UI for shields.io (#466 #701).

What would be the best way to leave comments?

Also… could I ask you to relicense under CC0? It would be great to incorporate this functionality into the UI someday, and I can only incorporate public-domain code into this repo.

**Comment by mightyiam** [comment]
Thanks!

Leave comments in the project issues, please.

Yeah, sure. I'll change the license to CC0.

**Comment by paulmelnikow** [comment]
Let's continue at mightyiam/shields-badges-urls#22!

**Comment by paulmelnikow** [comment]
Will leave this open, since others may want to take note and participate as well.
