### ISSUE TITLE
Coveralls badge showing "coverage | unknown"

### ISSUE THREAD

**Issue by radarsh** [badges/shields#1229]
The coveralls.io badge is rendering unknown value for coverage.

## Shields.io badge
```
![Coveralls branch](https://img.shields.io/coveralls/github/radarsh/gradle-test-logger-plugin/develop.svg)
```
![Coveralls branch](https://img.shields.io/coveralls/github/radarsh/gradle-test-logger-plugin/develop.svg)

## Coveralls.io badge
```
![Coverage Status](https://coveralls.io/repos/github/radarsh/gradle-test-logger-plugin/badge.svg?branch=develop)
```
![Coverage Status](https://coveralls.io/repos/github/radarsh/gradle-test-logger-plugin/badge.svg?branch=develop)

Attached screenshot shows what it is currently being rendered as.

<img width="243" alt="screen shot 2017-10-30 at 23 12 17" src="https://user-images.githubusercontent.com/534512/32200121-ee445996-bdc7-11e7-956d-1d892f9ffecc.png">

**Comment by paulmelnikow** [comment]
Hi! Thanks for your question. The Shields URL shouldn't have `github` in it.

```![Coveralls branch](https://img.shields.io/coveralls/radarsh/gradle-test-logger-plugin/develop.svg)```

![Coveralls branch](https://img.shields.io/coveralls/radarsh/gradle-test-logger-plugin/develop.svg)

**Comment by radarsh** [comment]
Oops sorry about that. I do remember seeing the badge rendering fine with the same incorrect URL though.
