### ISSUE TITLE
Github Contributors badge not working

### ISSUE THREAD

**Issue by aayush26** [badges/shields#1248]
The following badge link isn't working:
https://img.shields.io/github/contributors/aayush26/pirant.svg

Actual Output:
[![GitHub contributors](https://img.shields.io/github/contributors/aayush26/pirant.svg)](https://github.com/aayush26/pirant/graphs/contributors)

Its failing in https://shields.io/ too in line:

GitHub contributors: |   | https://img.shields.io/github/contributors/cdnjs/cdnjs.svg
-- | -- | --

**Comment by paulmelnikow** [comment]
Confirmed. I'm seeing **vendor | unresponsive** on all three servers, while other Github badges are working.

**Comment by aayush26** [comment]
Any update? or ETA? 

Thanks.

**Comment by paulmelnikow** [comment]
Given the other Github badges are working, I think the problem is in the code or API, not the production system.

Has anyone tried to reproduce this locally?

**Comment by aayush26** [comment]
Resolving it. Its working fine now.
@paulmelnikow Thanks for checking it out and confirming it wasn't working.

I would like to know what happened actually.

**Comment by paulmelnikow** [comment]
Glad it's working again. A deploy was made 11 days ago, perhaps the github fixes in there resolved this issue too.
