### ISSUE TITLE
Sensiolabs badge stopped working

### ISSUE THREAD

**Issue by salaros** [badges/shields#1249]
Sensiolabs badge stopped working for me, how can we fix it?

Here are some examples of my project (the first one) and another project:
[![SensioLabs Insight](https://img.shields.io/sensiolabs/i/f5764af3-0382-444c-ada6-3c2b0f8bf39b.svg)](https://insight.sensiolabs.com/projects/f5764af3-0382-444c-ada6-3c2b0f8bf39b)
[![SensioLabs Insight](https://img.shields.io/sensiolabs/i/287d9498-12cc-4e5f-8d5d-685823ff0347.svg)](https://insight.sensiolabs.com/projects/287d9498-12cc-4e5f-8d5d-685823ff0347)

**Comment by calebcartwright** [comment]
@salaros are you still seeing this issue? Our tests are showing our SensioLabs badges (Grades, Stars, and Violations) as being stable, and we haven't had any other reports.

If this issue has gone away then I'd like to close this out.

**Comment by salaros** [comment]
@calebcartwright unfortunately I'm not using it anymore, because of the issues I had with its badges

**Comment by calebcartwright** [comment]
Thanks @salaros, I'm going to close this out then
