### ISSUE TITLE
Badge for modules that come with TypeScript type definitions

### ISSUE THREAD

**Issue by sindresorhus** [badges/shields#1252]
Would be nice to have a badge to indicate that a module comes with TypeScript type definitions. This can either be a package written in TypeScript or one written in plain JavaScript with a handwritten type definition file.

I'm thinking something along the line of:

- `[TypeScript friendly]`
- `[TypeScript ready]`

For example, [this module](https://github.com/chalk/chalk/blob/master/types/index.d.ts) comes with handwritten type definitions and could have used such badge.

**Comment by SamVerschueren** [comment]
This would be awesome!

**Comment by paulmelnikow** [comment]
Hi! It's a nice idea.

This project hasn't tackled the idea of consistent static badges. We do have a gitter badge, but that is the only one. As I wrote in #1031:

> I'm ambivalent about whether to add more API-free badges like this, or simply use the custom badge route like Daniel suggests. On the one hand, it makes standardization and updating easy. On the other, it clutters the project with unnecessary code.

We could take it on if people think it makes sense.

**Comment by FezVrasta** [comment]
I'm happy to send a PR if you like the idea to get the static badges definitions from a json file.

**Comment by Falieson** [comment]
https://github.com/ellerbrock/typescript-badges

This project has version badges but only the 1.8 badge works. I made a ticket on the project months ago, but it seems abandoned.

I would love a shield for TS 2.5 !

**Comment by paulmelnikow** [comment]
In the spirit of Shields' design goals, how do these look?

![](https://img.shields.io/badge/type%20definitions-TypeScript%20v2.5-blue.svg)

![](https://img.shields.io/badge/type%20definitions-Flow%20v0.59-blue.svg)

Would it make sense to infer the language / versions from `package.json` so the badge automatically stays up to date?

**Comment by paulmelnikow** [comment]
I could see doing something similar for the React version of a component, inferred from the `package.json` or maybe the dependency graph on npmjs.com. This would be in the spirit of the new Django version badge (#1286), which uses classifiers pulled from PyPI.

**Comment by Falieson** [comment]
```In the spirit of Shields' design goals, how do these look?
Would it make sense to infer the language / versions from package.json so the badge automatically stays up to date?```
@paulmelnikow The badges look great! and the ability for TS version to update from package.json would be very sweet.

**Comment by paulmelnikow** [comment]
I implemented this. You can play around with it using the review app. Feedback appreciated!

Examples: https://github.com/badges/shields/pull/1541#issuecomment-370254274

**Comment by Falieson** [comment]
@paulmelnikow sorry but can you provide example? I don't see it listed on `shields.io`

**Comment by paulmelnikow** [comment]
Hi, sorry, it's waiting to be deployed. (#1538)

Meanwhile though, you could play around with it on our staging site:
https://shields-staging.herokuapp.com/

On the staging site, letter spacing will be messed up due to #1309.

**Comment by axelpale** [comment]
Link to the badge documentation: https://shields.io/badges/npm-type-definitions
