### ISSUE TITLE
Appveyor tests / same link?!

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1254]
`Appveyor tests` and ` Appveyor tests branch` have the exact same links:
![av_tests](https://user-images.githubusercontent.com/9874850/32518764-dfe9dc7e-c40a-11e7-8bab-3526694564f2.png)

**Comment by paulmelnikow** [comment]
Looks like this happened in #1065.

An easy fix, PR appreciated.

**Comment by tooomm** [comment]
After the move away from `try.html` I don't know where to apply the change anymore. :)

It looks like in the mentioned PR he just forgot an appending `/master`...

**Comment by PyvesB** [comment]
Hey there! I believe you have to apply the change to [lib/all-badge-examples.js](https://github.com/badges/shields/blob/master/lib/all-badge-examples.js) now. 😉

**Comment by tooomm** [comment]
@PyvesB thanks ;)

https://github.com/badges/shields/blob/master/lib/all-badge-examples.js#L54

Looking at this and the other badges around, my first thought was we could remove it completely.
But after searching all that file for `exampleUri` + comparing with the live shields.io page... I'm not certain anymore when we want/need to use that at all.

**Comment by M-ZubairAhmed** [comment]
@tooomm would you be submitting this PR. If not i am happy to help

**Comment by tooomm** [comment]
Regarding the open questions (to me), I'm not submitting a PR @M-ZubairAhmed.

**Comment by paulmelnikow** [comment]
There are a couple other `exampleUri`s that could use fixing. These errors will happen less often now that we're not using `try.html`. Since we're defining the URIs in JavaScript, and with less duplication, it's a lot clearer what is what.
