### ISSUE TITLE
Buildkite badge support

### ISSUE THREAD

**Issue by KevinGrandon** [badges/shields#1261]
[Buildkite](https://buildkite.com/) is a continuous integration service which is starting to provide support for open source builds, and currently has badge usage.

An example badge looks like: ![Build status](https://badge.buildkite.com/<hash>.svg?branch=master)

You can find an example of that badge in use here: https://github.com/buildkite/agent

It would be great if we could have support for buildkite badges on shields.io.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. Is there a public API, or just the badge URL?

**Comment by KevinGrandon** [comment]
I don't believe there's a public API for this currently. CCing a few buildkite folks in case they know. @toolmantim @keithpitt

**Comment by toolmantim** [comment]
I've checked out the shields source, and figured out the JSON endpoint you'd probably need. I've added that, along with some documentation here:
https://buildkite.com/docs/builds/build-status-badges#json-output

Let me know if there's anything else!

**Comment by raulriera** [comment]
Trying to add support in https://github.com/badges/shields/pull/1657 would love some feedback or help adding more tests

**Comment by toolmantim** [comment]
🎉

Thanks @raulriera and @RedSparr0w! 🙏🏼
