### ISSUE TITLE
Ability to pick any font

### ISSUE THREAD

**Issue by espadrine** [badges/shields#127]
Especially OpenSans.

Idea: use SVG `<path>` to draw each glyph, extracting information from a big JSON structure corresponding to a font.

This issue is the new forum of discussion for font creation; it is a follow-up to https://github.com/badges/gh-badges/issues/14.

**Comment by paulmelnikow** [comment]
Rendering paths into the svg's is something I could see doing in the future. Also, I could see embedding the entire font width as a lookup table, as badgen has done. However Verdana seems to be the standard, and I don't see the need to support additional fonts on our server.
