### ISSUE TITLE
Google Maps API and JSON?

### ISSUE THREAD

**Issue by cummingsrob** [badges/shields#1292]
I'm trying to display travel time in a badge using the Google Maps API. The problem is coming from the JSON query, I think. It appears to be returning the proper text string using web-based JSON query tools, but it's not displaying in the SVG shield image.

Here's the link I'm using to generate the shield (use your own Google Maps API key):
https://img.shields.io/badge/dynamic/json.svg?label=Travel%20Time&colorB=&prefix=&suffix=&query=$..duration.text&uri=https%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fdistancematrix%2Fjson%3Funits%3Dimperial%26origins%3DNew%2BYork%26destinations%3DLos%2BAngeles%26key%3D[yourAPIkeyhere]

Here's the link to the Google Maps API (use your own Google Maps API key):
https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=New+York&destinations=Los+Angeles&key=[yourAPIkeyhere]

A couple caveats, in no particular order: I don't think, speak, or write in code, so I'm limited to using Shields (or a similar service) and lucky trial-and-error hacking to generate the dynamic image. It needs to be an image that will ultimately display in a kiosk.

Does anyone have any insight as to why it wouldn't work?

**Comment by paulmelnikow** [comment]
It's probably a problem with your API key. Without a key I see this:

<img width="84" alt="screen shot 2017-11-29 at 1 22 15 pm" src="https://user-images.githubusercontent.com/1487036/33391915-83b5546a-d508-11e7-921f-68c85403c1e1.png">

and when I got the key correct I see this:

<img width="168" alt="screen shot 2017-11-29 at 1 22 26 pm" src="https://user-images.githubusercontent.com/1487036/33391922-8af8f222-d508-11e7-97ab-55e5b69cf835.png">

What result are you seeing?

For future use, here's a nice [JSONPath test page](http://jsonpath.com/). You can paste your JSON result into that page and experiment with the query.

Also, a caveat: for security reasons, do not send secrets to the Shields server. Be sure the key you're using is suitable for public consumption and is limited to the minimum, read-only access.

**Comment by cummingsrob** [comment]
I was using the JSONPath page. I used that to figure out the $..duration.text query.

If I hit the Google API URL directly, it returns all the JSON information, including origin, destination, duration and distance. But when I put it in the Shields.io URL with the query, I'm getting the blank results that you're getting without the key. https://user-images.githubusercontent.com/1487036/33391915-83b5546a-d508-11e7-921f-68c85403c1e1.png

How would I figure out the correct key?

Thanks for your help!

**Comment by cummingsrob** [comment]
Oh, wait! I generated a new key and it works like a charm! Don't know why the other key wouldn't work. Now to restrict it. Thanks for that tip as well.

Thanks for your help!
