### ISSUE TITLE
Badge request: Keybase

### ISSUE THREAD

**Issue by yzgyyang** [badges/shields#1299]
[Keybase](https://keybase.io) is a great platform for public-key cryptography, and Badges/Shields support is a long-wanted feature in the community (https://github.com/keybase/keybase-issues/issues/849). I have written some initial code and got it working, and I would hope that it will be merged and become officially-supported badges.

Examples:
![yzgyyang](https://user-images.githubusercontent.com/16748524/33473051-d89cf354-d6af-11e7-8742-0a74610837d9.png): /keybase/yzgyyang.svg
![pgp](https://user-images.githubusercontent.com/16748524/33473050-d86c0e38-d6af-11e7-80f2-bd56f318e11a.png): /keybase/yzgyyang/pgp.svg

Keybase offers straightforward APIs without authentication, the documents are here: https://keybase.io/docs/api/1.0

I am not really a nodejs guy, so please let me know if I didn't code something the right way (like, where to put the code?), and after my implementation is nearly finished, I will open a PR here. I would also like to know what are the other forms of badges that are wanted for the Keybase service.
My working repo: https://github.com/yzgyyang/shields

Thanks!

**Comment by mendhak** [comment]
Hey am I missing something, I can't see any changes in [your repo](https://github.com/badges/shields/compare/master...yzgyyang:keybase-initial-dev)?

**Comment by SkypLabs** [comment]
I just submitted a PR to add different Keybase badges: #2969.

**Comment by paulmelnikow** [comment]
Closed via #2969.

**Comment by donatj** [comment]
Doesn't seem like #2969 added a simple keybase profile badge like the post requested?

Ala: 
![image](https://user-images.githubusercontent.com/133747/92947440-9d639700-f41d-11ea-9a3f-d8ccb0a6e8b2.png)

**Comment by calebcartwright** [comment]
@donatj - that would just be a static badge, and is already available
