### ISSUE TITLE
Stars in badges broken (staging server misses font)

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1309]
- on live page: `working`
![stars_live](https://user-images.githubusercontent.com/9874850/33507242-f81e3d84-d6f3-11e7-9302-6051c4bdcc56.png)

- on Heroku review app for these two staging links: `unreadable`
    - https://shields-staging.herokuapp.com/
    - https://shields-staging-pr-1305.herokuapp.com/
![stars_staging](https://user-images.githubusercontent.com/9874850/33507328-7041af4e-d6f4-11e7-8159-b42602333711.png)

**Comment by paulmelnikow** [comment]
This is a problem with the staging server, which does not have the correct font installed. As a result the text width computation is off. The stars do look especially bad. If you look closely, nearly all the badges are a bit off.

Agree it would be nice to fix this.

**Comment by tooomm** [comment]
>If you look closely, nearly all the badges are a bit off (on staging server).

This is hard to tell since all badges on live shields.io page look a bit off on Firefox anyway. :)

**Comment by espadrine** [comment]
The right font is from the Mac's Verdana TTF. Unfortunately, for licensing issues, we cannot transmit it.

**Comment by paulmelnikow** [comment]
I'm delighted to say this was fixed in #2311!
