### ISSUE TITLE
issues with new frontend rewrite

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1311]
Most likely introduced in https://github.com/badges/shields/pull/1273 (not live yet, but on staging):
![untitled](https://user-images.githubusercontent.com/9874850/33516646-9671a908-d776-11e7-958d-3532495ae5b5.png)

- [ ] Crazy big preview window with a lot of empty white space around
--> Make the preview box smaller in size. Like 25-30% in width and 10-15% in height
- [ ] If you put something in the link field, the copy-able boxes in the middle adjust. But one has no clue that something happened because it's hidden at the end of the code. For other boxes you might not even see all code from the beginning (used to be problematic with old version too)
--> Make these fields bigger or allow them to be several lines like one code box

**Comment by paulmelnikow** [comment]
1. is probably an easy fix (though personally I would rather work on bigger changes to this screen like #701).

2. Seems an easy fix.

If anyone would like to tackle, feel free!

**Comment by tooomm** [comment]
Actually the badges involving `GitHub` have a Documentation paragraph further down:
![untitled](https://user-images.githubusercontent.com/9874850/33518073-5b9ba40a-d78f-11e7-831c-0327787b03bf.png)
So it would be needed to adjust the size dynamically regarding its content.

By the way:
Note how I have to use Chromium to make these preview windows show up at all - with other browsers they are broken for me as reported in https://github.com/badges/shields/pull/1305#issuecomment-348643834

**Comment by paulmelnikow** [comment]
Yea, we should definitely fix that. It's an issue in [this function](https://github.com/badges/shields/blob/master/frontend/lib/resolve-uri.js) which I tried to implement on top of the new [WHATWG URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL) though it's proven to be more trouble than it's worth. Should replace it either with an established isomorphic library or our home-grown code from the old frontend.

**Comment by paulmelnikow** [comment]
Popup should be fixed in #1322. Two issues mentioned in top post remain pending.

**Comment by RedSparr0w** [comment]
in regards to the 2nd problem:
do you think it would be best to change the `<input>` to a `<textarea>` or `<code>` element?
Or maybe even something else?

I think `<code>` would be the best option as it could auto resize if it needed to wrap.

**Comment by paulmelnikow** [comment]
Going to close this. #2496 should address a bunch of this. Feel free to open new targeted issues for whatever is still problematic.
