### ISSUE TITLE
wrong last commit link in <shields.io>

### ISSUE THREAD

**Issue by kamontat** [badges/shields#1313]
please check..

**Comment by paulmelnikow** [comment]
Hi! Sorry, I don't understand. Could you elaborate?

**Comment by kamontat** [comment]
last commit badge in <shield.io>, link on the back is `	https://img.shields.io/github/commits/google/skia/last.svg`
 But it’s should be `https://img.shields.io/github/last-commit/google/skia.svg`

**Comment by paulmelnikow** [comment]
Thanks for the report. This was fixed recently in #1297, which is pending deploy.
