### ISSUE TITLE
Badge request: Singularity Hub

### ISSUE THREAD

**Issue by gipert** [badges/shields#1323]
It would be really nice (and hopefully very similar to the Docker Hub badges implementation?).

**Comment by gipert** [comment]
Well, looking at the that badges are already available for the Docker Hub, there could be a "build automated" badge and a "build status" badge. The first one should be pretty straightforward, and the Hub itself already provides a similar one:

[![https://www.singularity-hub.org/static/img/hosted-singularity--hub-%23e32929.svg](https://www.singularity-hub.org/static/img/hosted-singularity--hub-%23e32929.svg)](https://singularity-hub.org/collections/297)

The second one is trickier, because, differently from the Docker Hub, the Singularity Hub associates GitHub repositories to "container collections". It follows that a unique "build status" badge would not make much sense, one should think about a badge for each container...

**Comment by paulmelnikow** [comment]
I think this is probably out of scope for img.shields.io, though it's a good opportunity to use an Endpoint badge: https://shields.io/endpoint
