### ISSUE TITLE
for-the-badge style not available in style dropdown (preview window)

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1330]
The new `for-the-badge` style isn't available in the preview window anymore.
In https://github.com/badges/shields/pull/1242 its display size got fixed there, but now it's not available in the selection anymore at all:
![preview](https://user-images.githubusercontent.com/9874850/33618837-ecaa4b12-d9e3-11e7-97aa-a6bf17e48e45.png)

Also something related to the big rewrite maybe? @paulmelnikow 

Verified at: https://shields-staging.herokuapp.com/

**Comment by paulmelnikow** [comment]
Ooph, good catch. In addition to showing the wrong options, it looks like that picker has been broken since some point during the rewrite. Could you do some more testing on the review app for #1331?
