### ISSUE TITLE
whitespace missing in footer

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1334]
Same as #1318 needs to be applied to the footer at the very bottom:

![footer](https://user-images.githubusercontent.com/9874850/33635395-195ff560-da18-11e7-9905-3df62618e955.png)

**Comment by RedSparr0w** [comment]
Also as a side note in regards to the spacing,
The `social` style badge has extra white space at the end which needs to be fixed,
the `svg` element is 5px wider than it needs to be
![image](https://user-images.githubusercontent.com/7288322/33635939-e279d392-da7e-11e7-9c5a-2daaed93a1d2.png)
![image](https://user-images.githubusercontent.com/7288322/33635958-f3e7d2c8-da7e-11e7-9465-77e3b62fdb93.png)

**Comment by tooomm** [comment]
Thanks for fixing the pixel issue already in  #1337 @RedSparr0w 

Now, the initial issue can be spotted better:
![footer](https://user-images.githubusercontent.com/9874850/33661395-ffa14c8a-da87-11e7-800f-1625fa97c3e4.png)

**Comment by paulmelnikow** [comment]
It's a matter of adding ` { }` after elements that need spaces, as in #1318.

If you want to give it a shot, @RedSparr0w or I can ship a review app which will let you test it through the browser.

**Comment by RedSparr0w** [comment]
No worries, ill give it a go!
