### ISSUE TITLE
Windows server symbolic links just shows path in browser

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#1336]
Symbolic links do not seem to function as they should through the browser and instead just shows the path the sym link directs to:
![image](https://user-images.githubusercontent.com/7288322/33637198-7b9f9a7a-da84-11e7-8067-801e54e3c5cb.png)
Whenever i run start the server i have to copy the files over from the builds dir to the public dir to view the homepage correctly.

OS: `Windows 10`
Browsers tested: `Chrome 62`, `Internet Explorer 11`
Node: `v8.7.0`

_Note: not a new problem, just hasn't really been too much of an issue_

**Comment by paulmelnikow** [comment]
Yea, valid for sure.

Sort of an aside, have you tried the new `npm start`, which runs a separate frontend server? I imagine it will work. Maybe that is a good enough workaround for dev…

**Comment by RedSparr0w** [comment]
The new `npm start` doesn't work for me,
Think its the same problem as #1259
```cmd
npm start

> gh-badges@1.3.0 prestart C:\Users\Dan\Documents\GitHub\shields
> npm run frontend-depcheck


> gh-badges@1.3.0 frontend-depcheck C:\Users\Dan\Documents\GitHub\shields
> check-node-version --node ">= 8.0"


> gh-badges@1.3.0 start C:\Users\Dan\Documents\GitHub\shields
> concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 next dev"

[server] 'ALLOWED_ORIGIN' is not recognized as an internal or external command,
[server] operable program or batch file.
[frontend] 'BASE_URL' is not recognized as an internal or external command,
[frontend] operable program or batch file.
[server] ALLOWED_ORIGIN=http://localhost:3000 npm run start:server exited with code 1
[frontend] BASE_URL=http://[::]:8080 next dev exited with code 1

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v8.7.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gh-badges@1.3.0 start: `concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 next dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gh-badges@1.3.0 start script 'concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 next dev"'.
```

**Comment by RedSparr0w** [comment]
@paulmelnikow If i set `npm start` to the following it works for me on Windows 10, could you test if it still functions at it should for you?
`concurrently --names server,frontend \"(ALLOWED_ORIGIN=http://localhost:3000 || set ALLOWED_ORIGIN=http://localhost:3000 ) && npm run start:server\" \"(BASE_URL=http://[::]:8080 || set BASE_URL=http://localhost:8080) && next dev\"`

**Comment by paulmelnikow** [comment]
As far as I can tell, we don't have any more symlinks in the codebase. I think I removed the last of them in #2906. 😄
