### ISSUE TITLE
Bintray seems to have broken

### ISSUE THREAD

**Issue by fosskers** [badges/shields#1345]
Seems to have broken since yesterday?

[![Bintray](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg)]()

**Comment by fosskers** [comment]
Nevermind, it seems fixed just now.

**Comment by maelvalais** [comment]
Seems to be broken right now, can anyone confirm?

**Comment by fosskers** [comment]
I'm seeing "invalid" on my bintray badge here.

**Comment by RedSparr0w** [comment]
Seems to be working again, bintray may have been down or may be rate limiting shields.io servers.
![](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg)
![image](https://user-images.githubusercontent.com/7288322/36077818-359c1ffa-0fd4-11e8-8dc9-7ff95b70c8e9.png)
