### ISSUE TITLE
missing discord logo

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1350]
https://discordapp.com/branding

**Comment by RedSparr0w** [comment]
I feel like it looks a little small when it's placed on a standard sized badge:
![](http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=white)`@1x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=white" height="30px"/>`@1.5x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=white" height="40px"/>`@2x`
![](http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb\(114,137,218\))`@1x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb(114,137,218)" height="30px"/>`@1.5x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb(114,137,218)" height="40px"/>`@2x`
![](http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb\(153,170,181\))`@1x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb(153,170,181)" height="30px"/>`@1.5x`
<img src="http://shields.redsparr0w.com/static/badge.svg?logo=discord&color=rgb(153,170,181)" height="40px"/>`@2x`

**Comment by tooomm** [comment]
Hmm, only use the inner "ghost" instead all talk bubble?

**Comment by RedSparr0w** [comment]
Doesn't look like they provide/endorse the use of just the "ghost" as their logo in the link you provided,
May be worth sending them an [email](mailto:support@discordapp.com) to check though.

**Comment by RedSparr0w** [comment]
Here it is without the 'chat bubble':
![image](https://user-images.githubusercontent.com/7288322/34429117-c74dbd12-ecb8-11e7-896d-46369cd0de5b.png)
![image](https://user-images.githubusercontent.com/7288322/34429152-141689f8-ecb9-11e7-8003-b5a10a5fcb29.png)

**Comment by tooomm** [comment]
I like the white one a lot!
