### ISSUE TITLE
Support consistant unicode/emoji symbols by using a dedicated True Type Font

### ISSUE THREAD

**Issue by NZSmartie** [badges/shields#1351]
Based on observations with inconstancies in emoji and Unicode symbol across multiple platforms in #1321 
Would it be realistic to include an additional True Type Font (next to `Verdana.ttf`) that could be used to make sure the look of Unicode symbols are constant across platforms?

**Comment by NZSmartie** [comment]
For example, here is a free-to-use licensed emoji font: https://emojisymbols.com/emojilist.php

**Comment by NZSmartie** [comment]
Or Google' Nato font (Licensed under SIL Open Font License, Version 1.1)
https://www.google.com/get/noto/#emoji-zsye

**Comment by NZSmartie** [comment]
Crap. Browsers do not support loading fonts fora SVG unless the SVG is embedded inside HTML. so there's no way to fix this...

**Comment by paulmelnikow** [comment]
I think the only way to do this is to create paths from the font on the server. See #127 / #552.

**Comment by RedSparr0w** [comment]
I **think** you can also include fonts in the svg when you display it via `<object>`,
But i'm also fairly certain you cant use the `<object>` tag on GitHub, Forums & most other places where badges are generally included.
