### ISSUE TITLE
several official badges provided by their vendors have style problems

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1363]
It looks like `AppVeyor` and `Gitter` changed their official badges to be *flat-squared* and no longer in the flat design with rounded edges, our default design.
The official `Greenkeeper` badge is also squared (but the design is off!).

Does anyone knows why? Should we adopt if there is a movement starting...?

Examples:
- ![](https://ci.appveyor.com/api/projects/status/github/gruntjs/grunt?branch=master&svg=true) (from https://www.appveyor.com/docs/status-badges)
- ![](https://badges.gitter.im/gitterHQ/gitter.svg) (from http://blog.gitter.im/2014/01/27/badgers, but svg version!)

**Comment by RedSparr0w** [comment]
The examples you posted are still showing as flat style for me, I personally prefer the flat-square style myself but I feel the flat style should probably stay as the default for now.

**Comment by espadrine** [comment]
We created the flat and flat squared styles roughly at the same time. Back then (2014 IIRC), I ran a month-long popularity contest to determine which to use by default, and the flat style won. I kept the squared style because there was still significant use.

I don't recommend changing the default style, since it would change the way badges look for a large number of users, which may dissatisfy them.

**Comment by tooomm** [comment]
>The examples you posted are still showing as flat style for me

For me they don't anymore (on Windows 10 with Firefox 57):
![untitled](https://user-images.githubusercontent.com/9874850/33932515-69c25670-dff3-11e7-86f7-edf803f5fd5d.png)
Funny, they display normal on Chromium... all other badges I see around didn't change though.
Another "broken" example is the official codecov badge: ![](https://codecov.io/gh/Unidata/MetPy/branch/master/graph/badge.svg)
<br>

>I don't recommend changing the default style

Sure, nobody wants to change it out of randomness.

I just wanted to raise awareness and start a discussion about it, because I realized the mentioned change for some big + popular services.
But it seems to be a specific handling in Firefox. Any idea what could cause this?

**Comment by chris48s** [comment]
Don't think its a firefox thing. Here's a screen grab from Firefox on Ubuntu:

![screenshot at 2017-12-13 19 58 52](https://user-images.githubusercontent.com/6025893/33959721-4a07bc06-e040-11e7-94d8-620653485f97.png)

**Comment by RedSparr0w** [comment]
Looks like they are using an outdated badge template, as the corners aren't rounded properly on iOS.
_Will upload an image soon._

**Comment by RedSparr0w** [comment]
Looks like they are using an outdated badge template, as the corners aren't rounded properly on iOS.
This was fixed in #352

GreenKeeper:
![image](https://user-images.githubusercontent.com/7288322/33960450-a9b20a3e-e0af-11e7-9d33-d1eaa6f509c1.png)
shields.io:
![image](https://user-images.githubusercontent.com/7288322/33960532-e869337e-e0af-11e7-81e0-37a30d2f3374.png)

**Comment by paulmelnikow** [comment]
Ooh, good catch.

Would someone like to reach out to Greenkeeper and Gitter to let them know?

**Comment by paulmelnikow** [comment]
We still have those popularity stats! I wonder where flat-square is in relationship to flat.

**Comment by tooomm** [comment]
>Would someone like to reach out to Greenkeeper and Gitter to let them know?

AppVeyor and codecov show the same style problems on firefox. Don't know about others.
Maybe they have the same style issues due to an outdated teamplate and not properly rounded corners as @RedSparr0w pointed out for greenkeaper?

**Comment by RedSparr0w** [comment]
@tooomm Yeah from what i can see all the ones you have mentioned in this thread all have the same issue.
- AppVeyor
- Codecov
- Greenkeeper
- Gitter

Not too sure of any other services hosting shields.io style badges that may also be using the old layout.

**Comment by tooomm** [comment]
Besides `Greenkeeper` we have our own version for all of them.

The official `Travis` badge seems ok by the way.

**Comment by RedSparr0w** [comment]
The travis badge never seemed to have this problem #732 
They are rounding all the corners using `rx="3"` and then fixing the left of the right hand side with an extra `<path>`
heres how the badge looks without the extra `<path>`
![image](https://user-images.githubusercontent.com/7288322/34228080-4aab48e0-e634-11e7-9761-31fa07175888.png)

**Comment by espadrine** [comment]
> They are rounding all the corners using rx="3" and then fixing the left of the right hand side with an extra <path>

That sounds exactly like a trick I had on badges before.

**Comment by paulmelnikow** [comment]
Not sure there's any action for us to take here.

**Comment by tooomm** [comment]
I think this can be closed maybe, a the example badges are showing fine for me now.
Probably a browser thing as described in https://github.com/badges/shields/issues/1363#issuecomment-351342004.

Or did they manage to update their badge templates? @RedSparr0w

**Comment by RedSparr0w** [comment]
Still seems to be a problem on iOS 9 & iOS 12.

But agree this should be closed, as not a lot we can do about this.
