### ISSUE TITLE
How to get the monthly download badge in markdown

### ISSUE THREAD

**Issue by elect86** [badges/shields#1371]
Sorry for the dummy question, but I'm out of ideas..

but how am I supposed to use the npm badge?
[![npm](https://img.shields.io/npm/dm/localeval.svg)]()

I tried
`[![npm](https://img.shields.io/npm/dm/kotlin-graphics/kotlin-unsigned.svg)]()` [![npm](https://img.shields.io/npm/dm/kotlin-graphics/kotlin-unsigned.svg)]()

but returns 0.. (which cannot be because I saw the github statistics)

**Comment by chris48s** [comment]
The project you're trying to get stats for doesn't appear to be an npm package. It looks like you want the github release downloads badge:

`[![Github All Releases](https://img.shields.io/github/downloads/kotlin-graphics/kotlin-unsigned/total.svg)]()`

[![Github All Releases](https://img.shields.io/github/downloads/kotlin-graphics/kotlin-unsigned/total.svg)]()

**Comment by paulmelnikow** [comment]
@elect86 Hope that is helpful! Please let us know if not.
