### ISSUE TITLE
Badge request: docs.rs

### ISSUE THREAD

**Issue by suhr** [badges/shields#1382]
See https://docs.rs/about

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. Is there a JSON API that returns the build status?

The red badge doesn't convey the failing doc build very clearly. I wonder if we should provide some more helpful text like **docs | build failed**.

**Comment by onur** [comment]
Hi @paulmelnikow. We have a JSON API to check build status, example URL for `cargo-0.23.0`: https://docs.rs/crate/cargo/0.23.0/builds.json`. This will return a list of builds and first one in the list is always the very latest build attempt. `build_status` will tell you if build was a success or not.

Unfortunately this JSON API will always require a version to work (it is actually only designed to work with crates.io). Docs.rs badge URL doesn't require any version.

**Comment by paulmelnikow** [comment]
Ah, gotcha. Hmmm, well we could parse the badges. Is a build status endpoint something you'd consider adding? Hitting a JSON API is more reliable.

**Comment by paulmelnikow** [comment]
Ref: rust-lang/docs.rs#170

**Comment by blakehawkins** [comment]
To help progress this request, can I suggest starting with a MVP that just links to `docs.rs/crate/`?

`cargo publish` by default will build docs in advance, so docs.rs should rarely have failing docs builds.

The following works great for me:

```
[![Docs badge]][docs.rs]

[Docs badge]: https://img.shields.io/badge/docs.rs-rustdoc-green
[docs.rs]: https://docs.rs/mycrate/
```

**Comment by paulmelnikow** [comment]
A question was just posted about this at rust-lang/docs.rs#170. If anyone has interest and capacity to respond, please do.
