### ISSUE TITLE
Library error handling

### ISSUE THREAD

**Issue by felixfbecker** [badges/shields#1389]
I spent almost half an hour trying to figure out why my badge generation wouldn't work. Then I noticed that the first parameter passed to the callback is not an Error as it's the convention, but the result. The error seems to be the second parameter. That is extremely counter-intuitive.

How about just returning a Promise?

**Comment by paulmelnikow** [comment]
I think this is a dup of #360 which was fixed in #1233.

We should definitely do a release, though. Let's track that in #1388.
