### ISSUE TITLE
Bower Badge Not up to Date

### ISSUE THREAD

**Issue by julmot** [badges/shields#1441]
Yesterday I've released v8.11.1 of [mark.js](https://github.com/julmot/mark.js/). npm and bower installs are successfully installing the newest version and the npm badge shows the correct version. However, the bower badge shows an old version:

![topic](https://user-images.githubusercontent.com/8310677/34872782-a56dc446-f792-11e7-8249-4ab5c55e1a10.png)

What could be the reason?

**Comment by chris48s** [comment]
The bower badge gets its data from the libraries.io api. If you have a look at the relevant page over there https://libraries.io/bower/mark.js it is reporting the version as 8.11.0 so that's what is used on the badge. I'm not sure on how often libraries.io synchronises data from various package managers or what the process is, but there is some delay there which is outside our control.

**Comment by julmot** [comment]
@andrew Can you help us clarify the situation? For example, I've manually triggered re-sync yesterday:

```bash
Last synced: 2018-01-11 23:18:02 UTC
```

Also I've suggested the version update on libraries.io itself. However, it still seems not to fetch the right version?

**Comment by julmot** [comment]
@andrew I've just noticed that even the npm version isn't up to date:

![topic](https://user-images.githubusercontent.com/8310677/34910207-8213e2a4-f8b0-11e7-9b82-d06ea807d210.png)

https://libraries.io/npm/mark.js

Maybe a fetching issue of libraries.io?

**Comment by julmot** [comment]
LOL: This is what it says on the npm page of mark.js:

![topic](https://user-images.githubusercontent.com/8310677/34915977-4a1fedae-f930-11e7-8e48-435044fcd805.png)

I've now triggered the resync button and now the npm and also the bower version is correcty determined – even though I've already manually clicked the sync button on the bower page which leaded to no update. This is very confusing. Also it's not clear to me why a manual action is necessary at all.

**Comment by paulmelnikow** [comment]
Would you like to reach out to the folks at libraries.io and ask for some clarification? It would be great to have a definitive answer, for benefit of everyone else in the future...

**Comment by andrew** [comment]
Sorry for the delay, we had a very backed up queue around the time, which might explain why there were some delays, sorry about that!

**Comment by julmot** [comment]
Closing and hoping it won't happen again.
