### ISSUE TITLE
User color overrides Error color

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#1446]
When `colorB` is specified this color will override any of the badges error colorscheme colors.

badge | actual | expected
:-- | :--: | :--:
`/travis/rust-lang/notarepo.svg?colorB=10ADED` | ![](https://img.shields.io/:build-unknown-10ADED.svg) | ![](https://img.shields.io/:build-unknown-9F9F9F.svg)
`/notabadge.svg?colorB=10ADED` | ![](https://img.shields.io/:404-badge%20not%20found-10ADED.svg) | ![](https://img.shields.io/:404-badge%20not%20found-e05d44.svg)
`/notabadge.svg?label=Label&colorB=10ADED` | ![](https://img.shields.io/:Label-badge%20not%20found-10ADED.svg) | ![](https://img.shields.io/:404-badge%20not%20found-e05d44.svg)

**Comment by paulmelnikow** [comment]
Hmm, interesting. Yes, I suppose I agree this is a bug, and that the user's specified color should only  apply when a badge is presented successfully.

**Comment by RedSparr0w** [comment]
I don't think it's too much of a problem, but should probably be fixed in the `node-8` branch along the way.

**Comment by paulmelnikow** [comment]
For whoever may pick this up, there's some useful discussion here: https://github.com/badges/shields/pull/2399#issuecomment-445024154
