### ISSUE TITLE
it's displaying the wrong npm package version

### ISSUE THREAD

**Issue by cyrusdavid** [badges/shields#145]
Example:

![](http://img.shields.io/npm/v/gulp-livereload.png)

When you check [the registry](http://npmjs.org/package/gulp-livereload) the latest version is `1.2.0`.

**Comment by binarykitchen** [comment]
@espadrine I think this bug still exists

**Comment by espadrine** [comment]
Just for reference, I believe @binarykitchen describes what they mean [here](https://github.com/badges/shields/issues/419).
