### ISSUE TITLE
Badge request: MediaWiki extension usage counts from WikiApiary

### ISSUE THREAD

**Issue by jthingelstad** [badges/shields#146]
Allow shields for extension usage count using WikiApiary data. This can pull the data directly from MediaWiki using the Semantic MediaWiki Ask API.

Format: 

`/wikiapiary-ext/ParserFunctions.svg`
`/wikiapiary-ext/Semantic%20MediaWiki.svg`

**Comment by paulmelnikow** [comment]
PR was opened but closed by OP, unmerged: #147

**Comment by paulmelnikow** [comment]
@SethFalco Wow, way to close out our oldest open issue! 😁 💯
