### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 6

### ISSUE THREAD

**Issue by k-five** [badges/shields#1461]
I coyed your own JSON file for test. I tried to test it.
https://img.shields.io/badge/dynamic/json.svg?uri=https://github.com/k-five/tmp/blob/master/package.json&query=$.name&label=Shields.io&prefix=v&suffix=-master&colorB=10ADED&style=flat-square
but either I am getting Syntax Error or Invalid resource
I used  your own JSON file: https://raw.githubusercontent.com/badges/shields/master/package.json

**Comment by chris48s** [comment]
Try encoding the JSON URL, so it is pased like `https%3A%2F%2Fraw.githubusercontent.com%2Fbadges%2Fshields%2Fmaster%2Fpackage.json`

e.g:
https://img.shields.io/badge/dynamic/json.svg?uri=https%3A%2F%2Fraw.githubusercontent.com%2Fbadges%2Fshields%2Fmaster%2Fpackage.json&query=$.name&label=Shields.io&prefix=v&suffix=-master&colorB=10ADED&style=flat-square

You might need to tweak your query a bit to get the exact result you were after.

**Comment by RedSparr0w** [comment]
the first link you provided is just linking to the file on github, you will need to link to the raw file
your uri:
`https://github.com/k-five/tmp/blob/master/package.json`
![](https://img.shields.io/badge/dynamic/json.svg?uri=https://github.com/k-five/tmp/blob/master/package.json&query=$.name&label=Shields.io&prefix=v&suffix=-master&colorB=10ADED&style=flat-square)
raw uri:
`https://raw.githubusercontent.com/k-five/tmp/master/package.json`
![](https://img.shields.io/badge/dynamic/json.svg?uri=https://raw.githubusercontent.com/k-five/tmp/master/package.json&query=$.name&label=Shields.io&prefix=v&suffix=-master&colorB=10ADED&style=flat-square)

**Comment by k-five** [comment]
I got it. Thanks.

**Comment by paulmelnikow** [comment]
@RedSparr0w I wonder if we should change the error message to something like "invalid json". It's equivalent semantically, though a little prettier.

**Comment by nateblog** [comment]
In my case it was the package-lock.json that is having a merge conflict that causes this error.

**Comment by paulmelnikow** [comment]
Since #2399 I think we've begun to show our new standard message, **unparseable json response** instead of the more specific exception pointing to the line number and position.
