### ISSUE TITLE
question: what is "Uptime Robot ratio" displaying?

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1462]
There are these badges for *Uptime Robot*:
- `Uptime Robot status`
- `Uptime Robot ratio`
- `Uptime Robot ratio (7days)`

The middle one is not exactly clear to me, which time frame is the ratio calculated on?

**Comment by chris48s** [comment]
The default is 30 days:

https://github.com/badges/shields/blob/1d8926672c6d1f4ecb3ac8a95fcb121449db5f6e/server.js#L7462-L7466

I've opened a PR to clarify this in the docs

**Comment by tooomm** [comment]
Thanks for your quick answer and UI improvement! 👍
