### ISSUE TITLE
Badges render inconsistently on mobile

### ISSUE THREAD

**Issue by wlandau** [badges/shields#1470]
Here is a screenshot of the mobile version of https://github.com/ropensci/drake on Android 7.0.0 and Chrome 64.0.3282.123. If I request the desktop site, the problem goes away.

![screenshot_20180128-090913](https://user-images.githubusercontent.com/1580860/35483075-b7c90418-040b-11e8-9f80-6f4952eb7c28.png)

**Comment by RedSparr0w** [comment]
I am fairly sure it is a problem with the tables auto scaling the images,
A couple of test below.

### Table from the [Readme](https://github.com/ropensci/drake/blob/master/README.md):

<details>
  <summary>Markdown</summary>

```text
| Release | Usage | Development |
|:--------|:------|:------------|
![JOSS](http://joss.theoj.org/papers/10.21105/joss.00550/status.svg) | ![Licence](https://img.shields.io/badge/licence-GPL--3-blue.svg) | ![AppVeyor](https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true)
![rOpenSci](https://badges.ropensci.org/156_status.svg) | ![minimal R version](https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg) | ![Travis](https://travis-ci.org/ropensci/drake.svg?branch=master)
![CRAN](http://www.r-pkg.org/badges/version/drake) | ![downloads](http://cranlogs.r-pkg.org/badges/drake) | ![Codecov](https://codecov.io/github/ropensci/drake/coverage.svg?branch=master)
![Zenodo](https://zenodo.org/badge/82609103.svg) | |
```
</details>

| Release | Usage | Development |
|:--------|:------|:------------|
![JOSS](http://joss.theoj.org/papers/10.21105/joss.00550/status.svg) | ![Licence](https://img.shields.io/badge/licence-GPL--3-blue.svg) | ![AppVeyor](https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true)
![rOpenSci](https://badges.ropensci.org/156_status.svg) | ![minimal R version](https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg) | ![Travis](https://travis-ci.org/ropensci/drake.svg?branch=master)
![CRAN](http://www.r-pkg.org/badges/version/drake) | ![downloads](http://cranlogs.r-pkg.org/badges/drake) | ![Codecov](https://codecov.io/github/ropensci/drake/coverage.svg?branch=master)
![Zenodo](https://zenodo.org/badge/82609103.svg) | |

### Individual Badges:

<details>
  <summary>Markdown</summary>

```text
![JOSS](http://joss.theoj.org/papers/10.21105/joss.00550/status.svg)
![Licence](https://img.shields.io/badge/licence-GPL--3-blue.svg)
![AppVeyor](https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true)
![rOpenSci](https://badges.ropensci.org/156_status.svg)
![minimal R version](https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg)
![Travis](https://travis-ci.org/ropensci/drake.svg?branch=master)
![CRAN](http://www.r-pkg.org/badges/version/drake)
![downloads](http://cranlogs.r-pkg.org/badges/drake)
![Codecov](https://codecov.io/github/ropensci/drake/coverage.svg?branch=master)
![Zenodo](https://zenodo.org/badge/82609103.svg)
```
</details>

![JOSS](http://joss.theoj.org/papers/10.21105/joss.00550/status.svg)
![Licence](https://img.shields.io/badge/licence-GPL--3-blue.svg)
![AppVeyor](https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true)
![rOpenSci](https://badges.ropensci.org/156_status.svg)
![minimal R version](https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg)
![Travis](https://travis-ci.org/ropensci/drake.svg?branch=master)
![CRAN](http://www.r-pkg.org/badges/version/drake)
![downloads](http://cranlogs.r-pkg.org/badges/drake)
![Codecov](https://codecov.io/github/ropensci/drake/coverage.svg?branch=master)
![Zenodo](https://zenodo.org/badge/82609103.svg)

### Table from the [Readme](https://github.com/ropensci/drake/blob/master/README.md) with height attribute applied:

<details>
  <summary>Markdown</summary>

```text
| Release | Usage | Development |
|:--------|:------|:------------|
<img alt="JOSS" height="20px" src="http://joss.theoj.org/papers/10.21105/joss.00550/status.svg" /> | <img alt="Licence" height="20px" src="https://img.shields.io/badge/licence-GPL--3-blue.svg" /> | <img alt="AppVeyor" height="20px" src="https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true" />
<img alt="rOpenSci" height="20px" src="https://badges.ropensci.org/156_status.svg" /> | <img alt="minimal R version" height="20px" src="https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg" /> | <img alt="Travis" height="20px" src="https://travis-ci.org/ropensci/drake.svg?branch=master" />
<img alt="CRAN" height="20px" src="http://www.r-pkg.org/badges/version/drake" /> | <img alt="downloads" height="20px" src="http://cranlogs.r-pkg.org/badges/drake" /> | <img alt="Codecov" height="20px" src="https://codecov.io/github/ropensci/drake/coverage.svg?branch=master" />
<img alt="Zenodo" height="20px" src="https://zenodo.org/badge/82609103.svg" /> | |
```
</details>

| Release | Usage | Development |
|:--------|:------|:------------|
<img alt="JOSS" height="20px" src="http://joss.theoj.org/papers/10.21105/joss.00550/status.svg" /> | <img alt="Licence" height="20px" src="https://img.shields.io/badge/licence-GPL--3-blue.svg" /> | <img alt="AppVeyor" height="20px" src="https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true" />
<img alt="rOpenSci" height="20px" src="https://badges.ropensci.org/156_status.svg" /> | <img alt="minimal R version" height="20px" src="https://img.shields.io/badge/R%3E%3D-3.2.0-blue.svg" /> | <img alt="Travis" height="20px" src="https://travis-ci.org/ropensci/drake.svg?branch=master" />
<img alt="CRAN" height="20px" src="http://www.r-pkg.org/badges/version/drake" /> | <img alt="downloads" height="20px" src="http://cranlogs.r-pkg.org/badges/drake" /> | <img alt="Codecov" height="20px" src="https://codecov.io/github/ropensci/drake/coverage.svg?branch=master" />
<img alt="Zenodo" height="20px" src="https://zenodo.org/badge/82609103.svg" /> | |

**Comment by wlandau** [comment]
Thanks for trying. The trouble is that GitHub suppresses css in the README.md, and I have so many badges that it's worth organizing them in a grid rather than mashing them together.

**Comment by tooomm** [comment]
@RedSparr0w All your example above look the same to me on Firefox...

On the other hand, I run into the same scaling issue within tables when editing a table containing a badge on a GitHub wiki page.
They rendered unreadable because they shrink down in a narrow table with a short caption. :(

**Comment by RedSparr0w** [comment]
@tooomm Yeah i was hoping the 3rd example wouldn't scale the images because of the fixed height, but could only test it by posting it :laughing: , unfortunately it wasn't the case.

The second example just shows that all the badges should be the same size on mobile when not in a table.

I've tried a few different things but everything just seems to result in the same problem with the tables.

I would put this down to a problem with markdown/tables rather than shields.

**Comment by wlandau** [comment]
Very well. I submitted chjj/marked#1040, and hopefully they will repair this part of GitHub-flavored Markdown.
