### ISSUE TITLE
[GitHub] Downloads per week, month etc. missing

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1475]
Like npm, packagist, hex.pm etc. have it.

**Comment by RedSparr0w** [comment]
Unfortunately i don't think the github API provides this information, Although i may be incorrect.

Here's the API url we currently get the download info from: https://api.github.com/repos/atom/atom/releases

**Comment by tooomm** [comment]
Hmm, and calculating that would only work for certain releases. Not total downloads.

**Comment by RedSparr0w** [comment]
Not even sure it would be possible for specific releases either.

**Comment by RedSparr0w** [comment]
Closing as i don't believe that either GitHub or a 3rd party service can provide us with the required information currently.
If this changes in the future feel free to reopen this issue and we can look at it providing this again :smile:
