### ISSUE TITLE
Can't make Travis-CI build status badge to indicate specified branch?

### ISSUE THREAD

**Issue by librae8226** [badges/shields#1479]
expected:
https://travis-ci.org/alibaba/AliOS-Things.svg?branch=master

however, shields does not work like above:
https://img.shields.io/travis/alibaba/AliOS-Things.svg?branch=master

It seems the parameter `branch=master` doesn't make any difference on `img.shields.io`.

Apologize, the `master` is now build-passing, as well as all other branches, so we may not see the actual result, but I guess the question is clear.

**Comment by RedSparr0w** [comment]
I believe the correct format for specifying a branch is:
`https://img.shields.io/travis/USER/REPO/BRANCH.svg`

So in your case the url would be:
`https://img.shields.io/travis/alibaba/AliOS-Things/master.svg`
![](https://img.shields.io/travis/alibaba/AliOS-Things/master.svg)

Hope that helps :smile:

**Comment by librae8226** [comment]
quite helpful, thanks a lot @RedSparr0w

**Comment by 1138-4EB** [comment]
@RedSparr0w the format you suggested is only supported for projects at travis-ci.org, not at travis-ci.com, isn't it?

**Comment by bertrandg** [comment]
@1138-4EB Check this merged PR, should works now: https://github.com/badges/shields/pull/1711

Use:
/travis/com/USER/REPO.(svg|png|gif|jpg|json)
/travis-ci/com/USER/REPO.(svg|png|gif|jpg|json)

**Comment by JulienDemarque** [comment]
The Doc in shields.io is not showing this update!!

**Comment by paulmelnikow** [comment]
What's missing. Could you clarify?

<img width="801" alt="screen shot 2018-12-05 at 11 58 46 pm" src="https://user-images.githubusercontent.com/1487036/49562487-c91d2900-f8e9-11e8-85aa-e46647800fa4.png">

**Comment by JulienDemarque** [comment]
@paulmelnikow My bad, I didn't realise there was a Travis.org and a Travis.com
