### ISSUE TITLE
[Bug][reStructuredText] Badges displayed on GitHub as block elements

### ISSUE THREAD

**Issue by Kristinita** [badges/shields#1491]
### 1. Summary

**If** my badge from shields.io:

    it displayed as block element on GitHub.

**elif** my badge from another service:

    it displayed as inline element on GitHub.

I don't think, that badges displaying as block element — it expected behavior.

#### 2.1. GitHub

See **<https://github.com/Kristinita/SashaShieldsIoDebugging>** repository:

![GitHub](https://i.imgur.com/NuYa54h.png)

`python`, `wheel` and `commitizen` badges — from img.shields.io.

See [**source**](https://raw.githubusercontent.com/Kristinita/SashaShieldsIoDebugging/master/Readme.rst) of my Readme.rst .

#### 2.2. PyPI

In [**PyPI site**](https://pypi.python.org/pypi/erichek) all my badges — from shiels.io and another services — display as inline elements:

![PyPI](https://i.imgur.com/Ae08FU3.png)

### 3. Not helped

1. I don't find in badge setting, that I can change inline and block displaying.
1. I try plastic style instead of default flat — I get same behavior.

Thanks.

**Comment by chris48s** [comment]
This appears to be a quirk of the way GitHub renders RST. I can't reproduce it in another RST Editor. As a workaround, if you set a link target on the badges, that will get them to render inline. I've forked your repo to demonstrate. See:

https://github.com/chris48s/SashaShieldsIoDebugging/blob/master/Readme.rst

https://github.com/chris48s/SashaShieldsIoDebugging/commit/27cd54957bdf219e0e5e4874eef46b41bb58de0e

I expect if you remove the link targets from the other badges you'll probably see the same behaviour but I have not tested it.

**Comment by Kristinita** [comment]
Thanks! Maybe you add in README, that `target` necessary for GitHub?
