### ISSUE TITLE
Tracking Drone.io’s adoption of these badges

### ISSUE THREAD

**Issue by mathiasbynens** [badges/shields#150]
I’d like [Drone.io](https://drone.io/) to offer their badges as SVG using the format used in this project.

They currently offer PNG badges that look like ![](https://drone.io/github.com/bestiejs/punycode.js/status.png), with URL format `https://drone.io/github.com/bestiejs/punycode.js/status.png`.

I think these are all the badges Drone.io needs:

| Badge | Link to example SVG code |
| --- | :-: |
| ![build passing](https://img.shields.io/badge/build-passing-brightgreen.svg) | [`/build-passing-brightgreen.svg`](https://img.shields.io/badge/build-passing-brightgreen.svg) |
| ![build failing](https://img.shields.io/badge/build-failing-red.svg) | [`/build-failing-red.svg`](https://img.shields.io/badge/build-failing-red.svg) |
| ![build unknown](https://img.shields.io/badge/build-unknown-lightgrey.svg) | [`/build-unknown-lightgrey.svg`](https://img.shields.io/badge/build-unknown-lightgrey.svg) |

**Comment by anacrolix** [comment]
How's progress on this? I'm using drone.io, and still getting the crappy old badges.

**Comment by mathiasbynens** [comment]
ping @bradrydzewski

**Comment by simleb** [comment]
Pleeaase… It feels like these are the only crappy badges left on Github! @mathiasbynens did most of the work already!

**Comment by bradrydzewski** [comment]
The discussion has been moved to the following issue:
https://github.com/badges/shields/issues/294#issuecomment-155906875

I have provided the necessary endpoints and suggested design for implementing shields with drone, so as the project maintainer pointed out, it is a matter of someone sending him a pull request.
