### ISSUE TITLE
Badge request: Microsoft Store

### ISSUE THREAD

**Issue by 304NotModified** [badges/shields#1500]
Please add a badge for Microsoft Store apps, e.g.

https://www.microsoft.com/store/p/nuget-package-explorer/9wzdncrdmdm3

9wzdncrdmdm3 is the app id

**Comment by paulmelnikow** [comment]
Hi there! Thanks for the suggestion. Is there a public API that provides this information?

**Comment by damieng** [comment]
That link says you can only get package information for your own packages once authenticated with your account. That doesn't appear flexible enough for a shield badge.

**Comment by paulmelnikow** [comment]
Gotcha. Thanks for tracking down that information.

P.S. Thanks also for contributing to our Open Collective! 🌟

**Comment by JasonWei512** [comment]
I made one with undocumented API.
https://github.com/JasonWei512/Microsoft-Store-Badge
![image](https://user-images.githubusercontent.com/16899918/230699544-46cfa16f-4a88-4b26-87d1-23effcfea68f.png)
