### ISSUE TITLE
Specify country or region for iTunes Store 

### ISSUE THREAD

**Issue by equt** [badges/shields#1503]
Currently, the shields server uses `https://itunes.apple.com/lookup` to lookup for certain app in [server.js](https://github.com/badges/shields/blob/master/server.js#L2055). But this would break if the app is not submitted to the U.S store.

That would be great if a country or region code is added as a param in the request URL, say `https://img.shields.io/itunes/v/BUNDLE_ID.svg?cc=code`. Since this could be elided, current working badges won't break.

**Comment by wolther47** [comment]
After a second thought on this issue, I choose to add an optional country or region code in the URL path instead. Current working badges also won't break, and, more importantly, this will not break the rule that parameters only change how badges look like.

**Comment by paulmelnikow** [comment]
Related: #1515
