### ISSUE TITLE
[Bitucket] Add support for Bitbucket Pipelines build results

### ISSUE THREAD

**Issue by pstreule** [badges/shields#1509]
Bitbucket supports builds through Bitbucket Pipelines and showing the build status of a repository or branch is a frequently requested feature: https://bitbucket.org/site/master/issues/13522/provide-project-status-build-status-badges

The Pipelines badge would work the same way as the existing Bitbucket badges:

`/bitbucket/pipelines/<user>/<repo>.svg`
or
`/bitbucket/pipelines/<user>/<repo>/<branch>.svg`

**Comment by RedSparr0w** [comment]
closed via #1510
