### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by ashtonhogan** [badges/shields#1511]

**Comment by PyvesB** [comment]
@ashtonhogan do you know if GitHub provides such information through some of their existing API endpoints?

**Comment by chris48s** [comment]
http://isitmaintained.com/ have badges for this.

Their code is probably a good starting point to see how it is done, but based on https://github.com/mnapoli/IsItMaintained#run

> The first time a badge is generated takes a few seconds,

it may be difficult to calculate in a performant way.

**Comment by ashtonhogan** [comment]
@chris48s it appears that this repository is quite limited because it does not allow you to limit average time by issue label. It's just a generic "average time for all issues" type of deal... I contacted the author as well and asked to add this feature but he said that he does not have time to add new features...

@PyvesB it must be possible because it's already being done to some extent: https://github.com/mnapoli/IsItMaintained - I guess the main challenge might be performance but I guess if it's been done before it must be possible

**Comment by bkdotcom** [comment]
Looks like the relevant isItMaintained code is here
https://github.com/mnapoli/IsItMaintained/blob/master/src/Maintained/Statistics/StatisticsComputer.php

**Comment by PyvesB** [comment]
I believe it would be straightforward to filter issues per label as the [GitHub API](https://developer.github.com/v3/issues/#list-issues) supports an optional `labels` parameter.

Nevertheless, as several of you have alluded to, I'm also concerned about performance. The API calls are paginated and return at most 30 issues, which is already quite a big blob of data (over 1600 lines of JSON returned when trying to retrieve one page from one of my personal repositories). On a bigger project such as Shields, we would need to make 26 such API calls if we want to perform a "brute force" averaging of the response time for all issues. This would really put a huge load on the server just to retrieve the data.

If we want to implement such a badge in a way that is acceptable performance-wise, we should either rely on a third-party to do the computations (does IsItMaintained itself have an API?) provided they offer good response times, or adopt a statistical model in shields by only averaging on a subset of the issues (but we may still need rather big samples to have meaningful data).

**Comment by mnapoli** [comment]
IsItMaintained does not have an API. What I do however is that I cache the data and recompute each badge once in a while. But yes, on big projects it takes time, avoiding reaching GitHub's API limit is also a problem.

**Comment by ashtonhogan** [comment]
maybe we can ask @github (or another appropriate handle) to improve their API for these kinds of requests?

**Comment by chris48s** [comment]
> the shields business model

:smile:  [donations welcome](https://opencollective.com/shields)

**Comment by ashtonhogan** [comment]
@chris48s no problem but I need the shield above first

**Comment by ashtonhogan** [comment]
@mnapoli why confused emoji? I need the above badge and am willing to pay for it. Simple business transaction. I can't get it anywhere else so that's why I'm asking here

**Comment by mnapoli** [comment]
Who are you going to pay and how much? This is very confusing, this is an open source project, it's not a matter of saying "I'll pay for it" and voilà the job is done.

**Comment by bkdotcom** [comment]
@mnapoli 
per @chris48s  :  https://opencollective.com/shields

**Comment by ashtonhogan** [comment]
@mnapoli open source != non-profit

**Comment by paulmelnikow** [comment]
There are some other badges people have asked for which require caching some data that goes beyond what we have in the API. The main one that comes to mind are the total aggregate NPM download stats #1278, which is something I could totally see doing in Shields, either if we find a way to do it cheaply, or get some more resources.

"Is it maintained" isn't just a matter of caching. It's more complicated and involves more nuanced design challenges. I think it deserves the focus of its own project. I could see running something like that under the Shields organization if people were interested, hosting it separately, and providing an API that the Shields badge could hit. Though, why don't we just join forces with isitmaintained, and try to build the caching in on their end?

**Comment by ashtonhogan** [comment]
@paulmelnikow I agree with pretty much all of that except isitmaintained has already explicitly stated that they have no time and will not be growing any time soon so you may as well just rule that out right now...

As far as resources go, I'm all in, tell me the price, I'm ready to enter my credit card details

**Comment by RedSparr0w** [comment]
I don't know that they wouldn't be willing to add this feature, they just stated they do not have time to work on implementing the feature themselves.

[From their readme:](https://github.com/mnapoli/IsItMaintained#feature-requests)
>If you want a feature to be added, pull requests are welcome.

**Comment by ashtonhogan** [comment]
@bkdotcom if someone isn't willing to pay for a service, are they really worth bending over backwards for? I'd rather pay for a license once-off or subscription monthly than donate. If you ask me to donate, I'm probably not going to, just because I feel like no one else is and therefore I'd feel alone in my support for your product

**Comment by paulmelnikow** [comment]
Engaging with you on this feels weird. I agree this badge is a good idea, and one I’d like to help make happen. However this project doesn’t sell licenses or subscriptions. It’s public domain and free to use, so that’s just not how it works. You’re sort of dangling a carrot, and then taking it away.
