### ISSUE TITLE
Add Depfu badges

### ISSUE THREAD

**Issue by AlexWayfer** [badges/shields#1523]
[Gemnasium will shut down](https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/), so I want to switch to [Depfu](https://depfu.com/), and I didn't found their badges in your service.

**Comment by chris48s** [comment]
Thanks for raising this. We'll also want to replace the existing Gemnasium integrations with an error message (refs #1449 ) when the service goes away on May 15th

**Comment by chris48s** [comment]
Having a quick look, depfu does not appear to have an API but they do appear to offer their own badges: https://github.com/depfu/example-ruby/blob/master/README.md

**Comment by AlexWayfer** [comment]
> Having a quick look, depfu does not appear to have an API but they do appear to offer their own badges: https://github.com/depfu/example-ruby/blob/master/README.md

It looks like they added badges only 9 days ago.

I asked for API in their feedback repo.
