### ISSUE TITLE
Add Core Infrastructure Initiative (CII) Best Practices badge

### ISSUE THREAD

**Issue by Athari** [badges/shields#1530]
https://bestpractices.coreinfrastructure.org/ provides a "checklist" for OSS projects, guiding in project management, CI, security etc. It supports its own badge, but no options for it. Example:

`[![Linux Kernel Badge](https://bestpractices.coreinfrastructure.org/projects/34/badge)](https://bestpractices.coreinfrastructure.org/projects/34)`
[![Linux Kernel Badge](https://bestpractices.coreinfrastructure.org/projects/34/badge)](https://bestpractices.coreinfrastructure.org/projects/34)

REST API URL: https://bestpractices.coreinfrastructure.org/projects/34/badge.json (34 is project id)

**Comment by calebcartwright** [comment]
I'll start working on this one
