### ISSUE TITLE
Welcome new maintainers 🍻

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1533]
I’d like to welcome three new members to the Shields maintainer team! @platan, @PyvesB, and @chris48s, you've worked consistently, cordially and effectively over the past few months. I’ve appreciated your technical chops, collegiality, dedication, and thoughtfulness. I’d like to make sure you’re not blocked or frustrated awaiting review from me or @RedSparr0w.

I’d suggest we use these review guidelines to start:

1. Try to get an opinion from @espadrine or me on anything “core” related
2. Try to get an opinion from @RedSparr0w or @espadrine on anything badge-template related
3. _Definitely_ get @espadrine’s approval on anything ops related
4. You may **otherwise merge with two of your ✅'s**.

@RedSparr0w, please continue to seek input and merge at your discretion. You have great judgement about that.

We're starting to have a lot of people, which is great! As the team grows, we may need to institute some more process like a technical advisory committee, to make sure we don’t run off the rails. Though I don’t think that’s necessary to start. Let’s see how this works out and revisit in a few months.

From a more practical standpoint, would you please join the Discord room and post your handles here? I’ll ask there for your email address. There may be other things to discuss. Let’s coordinate here.

Welcome to the team!

/cc @Daniel15

**Comment by PyvesB** [comment]
Hey there, thanks for the warm welcome to the team! Let's bring this project to the next level! 👍 

Still completely new to Discord, but I believe my profile name is the following: Pyves#4777

**Comment by chris48s** [comment]
I am `chris48s#7718` :)

**Comment by platan** [comment]
@paulmelnikow thank you. @PyvesB and @chris48s - well done! And my Discord username is `platan#9710`.

**Comment by RedSparr0w** [comment]
Welcome to the team!
Glad to have you all join :smile:
