### ISSUE TITLE
Deploy status (was: What is the lifecycle of shields.io build?)

### ISSUE THREAD

**Issue by binhbbbb** [badges/shields#1538]
Hi there, 3 weeks ago I have added *Vaadin-Directory* service and the request has been merged. However, I noticed that the service has not been up yet.  

Can I have an estimation to when you guys would build the whole thing again and publish? We would love to have the badge as soon as possible.  

The PRs: https://github.com/badges/shields/pull/1474 https://github.com/badges/shields/pull/1496

**Comment by PyvesB** [comment]
Hello @binhbbui411 !

Quoting @paulmelnikow:

> Deploys usually happen every 1–3 weeks. Thaddée, who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account (and maybe the servers too) are shared with other services he runs.

You're definitely right, we've been slightly on the slow side in terms of release lifecyle lately. Let's be patient! 😉 

Cheers,

Pyves

**Comment by binhbbui411** [comment]
I see. Good to know things are still progressing somehow. 

Thanks for the update, PyvesB!

**Comment by paulmelnikow** [comment]
@kachkaev asked at https://github.com/badges/shields/issues/1518#issuecomment-373948524:

> Meanwhile, will it be OK if use a staging badge at `https://shields-staging.herokuapp.com/codeclimate/coverage/gicentre/prettier-plugin-elm.svg?style=flat-square`?

I'd request that the staging server be restricted to testing. Since we're on the free plan, Heroku limits the number of hours per month the server can be used. If we exceed those with production usage, the staging server becomes unusable for testing, which is why it's there. That said, you're welcome to host your own server on Heroku!

**Comment by samlanning** [comment]
@paulmelnikow I'm wandering if you've considered asking someone like heroku for free hosting as a sponsorship / partnership deal? Or if you've considered auto-deployments in general?

**Comment by paulmelnikow** [comment]
I have cherry-picked #1774 onto 57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf and deployed it to gh-pages which brings it in sync with production. See https://github.com/badges/shields/pull/1742#issuecomment-398785495. It's live at https://shields.io/ and seems to be working find, though it's my first time doing this. Let me know if you see any issues!

**Comment by paulmelnikow** [comment]
I'm seeing a security warning, which I did not get when I deployed it under my own account. I'm looking into it now. Stay tuned!

**Comment by PyvesB** [comment]
It's no longer useful to keep this issue opened, let's close it! We've gotten much better at deployments recently. 😉
