### ISSUE TITLE
Encoding of logos has changed

### ISSUE THREAD

**Issue by greysteil** [badges/shields#1540]
Hey team,

1) Shields.io is awesome! Thanks for all your work on it.
2) It looks like the required encoding of logos has changed. Previously, [this link](https://img.shields.io/badge/compatibility-90%25-brightgreen.svg?logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyBoZWlnaHQ9IjE5MSIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMTkxIiB4%0AbWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5r%0APSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KICAgIDxyZWN0IGZp%0AbGw9Im5vbmUiIGhlaWdodD0iMTAwJSIgaWQ9ImJhY2tncm91bmRyZWN0IiBz%0AdHJva2U9Im5vbmUiIHdpZHRoPSIxMDAlIiB4PSIwIiB5PSIwIi8%2BCiAgICA8%0AdGl0bGU%2BRGVwZW5kYWJvdCBsb2dvIGZvciBiYWRnZTwvdGl0bGU%2BCiAgICA8%0AZGVzYz5EZXBlbmRhYm90IGxvZ28gZm9yIGJhZGdlPC9kZXNjPgogICAgPGRl%0AZnMvPgogICAgPGcgY2xhc3M9ImN1cnJlbnRMYXllciI%2BCiAgICAgICAgPHRp%0AdGxlPkxheWVyIDE8L3RpdGxlPgogICAgICAgIDxnIGNsYXNzPSIiIGlkPSJH%0Acm91cC0yMC1Db3B5Ij4KICAgICAgICAgICAgPHJlY3QgZmlsbD0iI0ZGRkZG%0ARiIgaGVpZ2h0PSIxMTguNjkxNzcyNzA2MjExOSIgaWQ9IkNvbWJpbmVkLVNo%0AYXBlIiB3aWR0aD0iMTYwLjM2MDAzOTg3MzU1NTkzIiB4PSIxNC42MzIyMDk5%0ANDk1NTcxODYiIHk9IjU2LjE2ODkwNzcxMjk0NzE3NCIvPgogICAgICAgICAg%0AICA8cG9seWdvbiBmaWxsPSIjNTU1NTU1IiBpZD0iQ29tYmluZWQtU2hhcGUi%0AIHBvaW50cz0iNTcuNjU1NjM1ODMzNzQwMjM0LDExNS41MTQ3ODc5NzE5NzM0%0AMiA0OS44MzMxOTQ3MzI2NjYwMTYsMTA3LjYwMjAwNzIxMDI1NDY3IDQyLjAx%0AMDc1MzYzMTU5MTgsMTE1LjUxNDc4Nzk3MTk3MzQyIDU3LjY1NTYzNTgzMzc0%0AMDIzNCwxMzEuMzQwMzQ5NDk1NDEwOTIgODEuMTIyOTU1MzIyMjY1NjIsMTA3%0ALjYwMjAwNzIxMDI1NDY3IDczLjMwMDUyMTg1MDU4NTk0LDk5LjY4OTIzNDA3%0ANzkzMDQ1ICIgdHJhbnNmb3JtPSIiLz4KICAgICAgICAgICAgPHBvbHlnb24g%0AZmlsbD0iIzU1NTU1NSIgaWQ9IkNvbWJpbmVkLVNoYXBlLUNvcHktMiIgcG9p%0AbnRzPSIxMjQuMTQ2NDA4MDgxMDU0NjksMTE1LjUxNDc4Nzk3MTk3MzQyIDEx%0ANi4zMjM5MzY0NjI0MDIzNCwxMDcuNjAyMDA3MjEwMjU0NjcgMTA4LjUwMTQ5%0ANTM2MTMyODEyLDExNS41MTQ3ODc5NzE5NzM0MiAxMjQuMTQ2NDA4MDgxMDU0%0ANjksMTMxLjM0MDM0OTQ5NTQxMDkyIDE0Ny42MTM2OTMyMzczMDQ3LDEwNy42%0AMDIwMDcyMTAyNTQ2NyAxMzkuNzkxMjc1MDI0NDE0MDYsOTkuNjg5MjM0MDc3%0AOTMwNDUgIi8%2BCiAgICAgICAgICAgIDxyZWN0IGZpbGw9IiNGRkZGRkYiIGhl%0AaWdodD0iMzUuNjA3NTMxMTQ3NTk0MzQ0IiBpZD0iUmVjdGFuZ2xlLTE1LUNv%0AcHkiIHdpZHRoPSIzNS4yMDA5ODUwOTE1NjM4OCIgeD0iNzcuMjExNzM5MDAx%0AMjI2MyIgeT0iOC42OTIyMDM5NDQ2MTYyNjciLz4KICAgICAgICAgICAgPHJl%0AY3QgZmlsbD0iI0ZGRkZGRiIgaGVpZ2h0PSIzNS4zNTg1MjY1MDQyMjc2MiIg%0AaWQ9IlJlY3RhbmdsZS0xNS1Db3B5LTQiIHdpZHRoPSIxMS43MzM2NjE2OTcx%0AODc5NTkiIHg9IjEwMC42NzkwNjkwMzgyOTQ1NiIgeT0iMzIuNDMwNTU1ODI4%0ANzgxNzIiLz4KICAgICAgICAgICAgPHJlY3QgZmlsbD0iI0ZGRkZGRiIgaGVp%0AZ2h0PSIzNS42MDc1MzExNDc1OTQzNDQiIGlkPSJSZWN0YW5nbGUtMTUtQ29w%0AeS0yIiB3aWR0aD0iMjMuNTIwNzMyMzAxMzg4NzQ0IiB4PSIyLjg5ODU1MTU3%0AMzcxNTM5NDYiIHk9IjExMS41NTgzOTk4NzExMjgxIi8%2BCiAgICAgICAgICAg%0AIDxyZWN0IGZpbGw9IiNGRkZGRkYiIGhlaWdodD0iMzUuNjA3NTMxMTQ3NTk0%0AMzQ0IiBpZD0iUmVjdGFuZ2xlLTE1LUNvcHktMyIgd2lkdGg9IjIzLjUyMDcz%0AMjMwMTM4ODc0NCIgeD0iMTYzLjIwNTE5MDg0MzYyMzkiIHk9IjExMS41NTgz%0AOTk4NzExMjgxIi8%2BCiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K%0A) would include a logo (the base64 in it has been url-encoded). Now, instead or URL-encoding the base64, I have to delete any newlines in it and substitute any `+` signs for `%2b` (and not url-encode it) to get the same logo ([here](https://img.shields.io/badge/compatibility-90%25-brightgreen.svg?logo=data:image/svg%2bxml;base64,PHN2ZyBoZWlnaHQ9IjE5MSIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMTkxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KICAgIDxyZWN0IGZpbGw9Im5vbmUiIGhlaWdodD0iMTAwJSIgaWQ9ImJhY2tncm91bmRyZWN0IiBzdHJva2U9Im5vbmUiIHdpZHRoPSIxMDAlIiB4PSIwIiB5PSIwIi8%2bCiAgICA8dGl0bGU%2bRGVwZW5kYWJvdCBsb2dvIGZvciBiYWRnZTwvdGl0bGU%2bCiAgICA8ZGVzYz5EZXBlbmRhYm90IGxvZ28gZm9yIGJhZGdlPC9kZXNjPgogICAgPGRlZnMvPgogICAgPGcgY2xhc3M9ImN1cnJlbnRMYXllciI%2bCiAgICAgICAgPHRpdGxlPkxheWVyIDE8L3RpdGxlPgogICAgICAgIDxnIGNsYXNzPSIiIGlkPSJHcm91cC0yMC1Db3B5Ij4KICAgICAgICAgICAgPHJlY3QgZmlsbD0iI0ZGRkZGRiIgaGVpZ2h0PSIxMTguNjkxNzcyNzA2MjExOSIgaWQ9IkNvbWJpbmVkLVNoYXBlIiB3aWR0aD0iMTYwLjM2MDAzOTg3MzU1NTkzIiB4PSIxNC42MzIyMDk5NDk1NTcxODYiIHk9IjU2LjE2ODkwNzcxMjk0NzE3NCIvPgogICAgICAgICAgICA8cG9seWdvbiBmaWxsPSIjNTU1NTU1IiBpZD0iQ29tYmluZWQtU2hhcGUiIHBvaW50cz0iNTcuNjU1NjM1ODMzNzQwMjM0LDExNS41MTQ3ODc5NzE5NzM0MiA0OS44MzMxOTQ3MzI2NjYwMTYsMTA3LjYwMjAwNzIxMDI1NDY3IDQyLjAxMDc1MzYzMTU5MTgsMTE1LjUxNDc4Nzk3MTk3MzQyIDU3LjY1NTYzNTgzMzc0MDIzNCwxMzEuMzQwMzQ5NDk1NDEwOTIgODEuMTIyOTU1MzIyMjY1NjIsMTA3LjYwMjAwNzIxMDI1NDY3IDczLjMwMDUyMTg1MDU4NTk0LDk5LjY4OTIzNDA3NzkzMDQ1ICIgdHJhbnNmb3JtPSIiLz4KICAgICAgICAgICAgPHBvbHlnb24gZmlsbD0iIzU1NTU1NSIgaWQ9IkNvbWJpbmVkLVNoYXBlLUNvcHktMiIgcG9pbnRzPSIxMjQuMTQ2NDA4MDgxMDU0NjksMTE1LjUxNDc4Nzk3MTk3MzQyIDExNi4zMjM5MzY0NjI0MDIzNCwxMDcuNjAyMDA3MjEwMjU0NjcgMTA4LjUwMTQ5NTM2MTMyODEyLDExNS41MTQ3ODc5NzE5NzM0MiAxMjQuMTQ2NDA4MDgxMDU0NjksMTMxLjM0MDM0OTQ5NTQxMDkyIDE0Ny42MTM2OTMyMzczMDQ3LDEwNy42MDIwMDcyMTAyNTQ2NyAxMzkuNzkxMjc1MDI0NDE0MDYsOTkuNjg5MjM0MDc3OTMwNDUgIi8%2bCiAgICAgICAgICAgIDxyZWN0IGZpbGw9IiNGRkZGRkYiIGhlaWdodD0iMzUuNjA3NTMxMTQ3NTk0MzQ0IiBpZD0iUmVjdGFuZ2xlLTE1LUNvcHkiIHdpZHRoPSIzNS4yMDA5ODUwOTE1NjM4OCIgeD0iNzcuMjExNzM5MDAxMjI2MyIgeT0iOC42OTIyMDM5NDQ2MTYyNjciLz4KICAgICAgICAgICAgPHJlY3QgZmlsbD0iI0ZGRkZGRiIgaGVpZ2h0PSIzNS4zNTg1MjY1MDQyMjc2MiIgaWQ9IlJlY3RhbmdsZS0xNS1Db3B5LTQiIHdpZHRoPSIxMS43MzM2NjE2OTcxODc5NTkiIHg9IjEwMC42NzkwNjkwMzgyOTQ1NiIgeT0iMzIuNDMwNTU1ODI4NzgxNzIiLz4KICAgICAgICAgICAgPHJlY3QgZmlsbD0iI0ZGRkZGRiIgaGVpZ2h0PSIzNS42MDc1MzExNDc1OTQzNDQiIGlkPSJSZWN0YW5nbGUtMTUtQ29weS0yIiB3aWR0aD0iMjMuNTIwNzMyMzAxMzg4NzQ0IiB4PSIyLjg5ODU1MTU3MzcxNTM5NDYiIHk9IjExMS41NTgzOTk4NzExMjgxIi8%2bCiAgICAgICAgICAgIDxyZWN0IGZpbGw9IiNGRkZGRkYiIGhlaWdodD0iMzUuNjA3NTMxMTQ3NTk0MzQ0IiBpZD0iUmVjdGFuZ2xlLTE1LUNvcHktMyIgd2lkdGg9IjIzLjUyMDczMjMwMTM4ODc0NCIgeD0iMTYzLjIwNTE5MDg0MzYyMzkiIHk9IjExMS41NTgzOTk4NzExMjgxIi8%2bCiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K)).

The above is totally fine, but I noticed the change and you suggested I raise it as an issue in https://github.com/badges/shields/pull/1516.

My JavaScripts are no good, or I'd have a go at fixing this myself - sorry!

✌️

**Comment by paulmelnikow** [comment]
Seems we should be able to support both formats. @RedSparr0w would you like to look into this?

**Comment by RedSparr0w** [comment]
Thanks for opening this issue,
I believe this is caused by the way query parameters are handled by default,
`+` signs are converted to spaces when given to a webpage,
(to test this just add `?label=test+test` which will show: ![](https://img.shields.io/:label-message-blue.svg?label=test+test))

`+` signs should no longer need to be encoded with the merge of #1527 

In terms of the newline characters, they are not supported in data URIs:

>[In actual URIs, including data URIs, control characters (ASCII 0 to 31, and 127) and spaces (ASCII 32) are "excluded characters". This means that whitespace characters are not permitted in data URIs.](https://en.wikipedia.org/wiki/Data_URI_scheme#HTML)

I will try open a PR soon though which will just remove any new line chars and that should hopefully fix this :smile:
