### ISSUE TITLE
How do you add your own image to custom badges?

### ISSUE THREAD

**Issue by ashtonhogan** [badges/shields#1548]
For example, appveyor has it:

<img src="https://camo.githubusercontent.com/e38e1f4c608fd9b5bc64b8dca06ef7b08319770e/68747470733a2f2f63692e6170707665796f722e636f6d2f6170692f70726f6a656374732f7374617475732f6769746875622f617368746f6e686f67616e2f6f62766f796167653f6272616e63683d6d6173746572267376673d74727565" />

Instead of just choosing subject, status, color - why not also allow svg text for a glyph on the left or right hand side of the badge?

**Comment by chris48s** [comment]
You can add this to any badge by passing `?logo=appveyor` as a param - any of the logos in https://github.com/badges/shields/tree/gh-pages/logo can be referenced by name

Alternatively if you want to use your own, you can pass a base64 encoded image using something like `?logo=data:image/png;base64,...` There's a nice example of this here: https://github.com/badges/shields/pull/1516#issuecomment-367517225

**Comment by ashtonhogan** [comment]
Thanks @chris48s - Could you possibly merge my PR: https://github.com/badges/shields/pull/1552

I've added the logo that I want to use. Once I've tested and confirmed the above, I will close this issue

**Comment by ashtonhogan** [comment]
@chris48s @RedSparr0w can you please reopen this, I've applied some changes to my contribution and recreated my pull request: https://github.com/badges/shields/pull/1555
