### ISSUE TITLE
How can I create a custom badge with the latest release?

### ISSUE THREAD

**Issue by ashtonhogan** [badges/shields#1549]
Something like this:

![MyRepo](https://img.shields.io/badge/MyRepo-1.0.5-brightgreen.svg)

Except when a newer tag is published, it should automatically update the version

**Comment by chris48s** [comment]
`https://img.shields.io/github/tag/yourusername/yourrepo.svg` should do the job for you

**Comment by ashtonhogan** [comment]
@chris48s do you know if it's possible to change the text from "tag" to something else?

**Comment by RedSparr0w** [comment]
just add `?label=mycustomlabel` to the end of the url

example for shields: 
![](https://img.shields.io/github/tag/badges/shields.svg?label=shields%20tag)
`https://img.shields.io/github/tag/badges/shields.svg?label=shields%20tag`

note there are other params you can use to customise your badge:
https://shields.io/#styles (they are just below the styles section)
