### ISSUE TITLE
VersionEye: Badge for the number of references

### ISSUE THREAD

**Issue by reiz** [badges/shields#155]
It would be nice to have a badge for the number of references. VersionEye is showing how many references a project has. Log4r for example is used by 208 other Gems. Here is the list of log4r references:  

https://www.versioneye.com/ruby/log4r/references

This is the badge.

http://img.shields.io/badge/references-208-green.svg

It would be nice to have it this way: 

http://img.shields.io/versioneye/ruby/log4r/references.svg

**Comment by paulmelnikow** [comment]
VersionEye has sunset, so closing.

https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
