### ISSUE TITLE
Github Release Date badge is way off.

### ISSUE THREAD

**Issue by chris001** [badges/shields#1554]
It should say "January".  

But it says "may 2014".

[![Release date](https://img.shields.io/github/release-date/OfflineIMAP/offlineimap.svg)](https://github.com/OfflineIMAP/offlineimap/releases)

Bug?

**Comment by RedSparr0w** [comment]
On mobile right now so can't investigate properly, but if you visit https://github.com/OfflineIMAP/offlineimap/releases/latest it shows the latest release as May 2014. Think we had a similar issue awhile ago, not sure if it got solved though.

**Comment by chris48s** [comment]
This is the relevant post: https://github.com/badges/shields/issues/1355#issuecomment-350102951

On your repo, v6.5.6 (25 May 2014) is a _release_, whereas v7.1.5 (13 Jan 2018) is a _tag_ but confusingly GitHub uses these terms slightly differently in the web front-end and the API which sometimes causes confusion.

**Comment by paulmelnikow** [comment]
Let us know if you have other questions!

**Comment by chris001** [comment]
Is there any way to get this latest release date information from the github version tags?  For a repo which has no github "release" objects.  Or for a repo where the latest "release" object is many, many "tags" behind.  For example, this repo:   https://github.com/OfflineIMAP/offlineimap/releases/latest

**Comment by paulmelnikow** [comment]
Yes, you can use `/github/tag`:
![](https://img.shields.io/github/tag/OfflineIMAP/offlineimap.svg)
https://img.shields.io/github/tag/OfflineIMAP/offlineimap.svg

However it's not 100% reliable. See #875.
