### ISSUE TITLE
Is it possible to create just a badge without the first text?

### ISSUE THREAD

**Issue by acki-m** [badges/shields#1561]
I want to add colors to my changelog, therefore I would like to add something like that:

- [![Generic badge](https://img.shields.io/badge/-FEATURE-green.svg)](https://shields.io/) new class `XY` added

The black in the front of the button is not needed, how can I remove it?

**Comment by RedSparr0w** [comment]
unfortunately there is currently no way to remove part of the badge on anything other than `social` style badges (by not specifying right hand text), but this doesn't support custom colors:
![](https://img.shields.io/badge/LABEL--x.svg?style=social)
`https://img.shields.io/badge/LABEL--x.svg?style=social`

Though you could do something like this:
![](https://img.shields.io/:[-SOME%20LABEL%20]-x.svg?colorA=2ecc71&colorB=2ecc71)
`https://img.shields.io/badge/[-SOME%20LABEL%20]-x.svg?colorA=2ecc71&colorB=2ecc71`

![](https://img.shields.io/badge/•-SOME%20LABEL-x.svg?colorA=e74c3c&colorB=e74c3c)
`https://img.shields.io/badge/•-SOME%20LABEL-x.svg?colorA=e74c3c&colorB=e74c3c`

![](https://img.shields.io/badge/►-SOME%20LABEL-x.svg?colorA=3498db&colorB=3498db)
`https://img.shields.io/badge/►-SOME%20LABEL-x.svg?colorA=3498db&colorB=3498db`

![](https://img.shields.io/badge/😀-SOME%20LABEL-x.svg?colorA=34495e&colorB=34495e)
`https://img.shields.io/badge/😀-SOME%20LABEL-x.svg?colorA=34495e&colorB=34495e`

**Comment by paulmelnikow** [comment]
This is a dup of #343.

Nice workarounds!
