### ISSUE TITLE
Heads-up about the new PyPI

### ISSUE THREAD

**Issue by brainwane** [badges/shields#1569]
Hi. I'm the project manager for the new Python Package Index (Warehouse), which is currently in pre-production at http://pypi.org/ . Your code integrates with the old PyPI API, so I wanted to make sure you knew that, on [the Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap), it looks like the full switch will happen sometime in April. Here's a heads-up about why we're switching, what's changed, and what to expect.

The legacy PyPI site at https://pypi.python.org started in the early 2000s. In recent years, users faced outages, malicious packages, and spam attacks, and the legacy codebase made it hard to maintain and even harder to develop new features.

The new PyPI has a far more modern look, and is up-to-date under the hood as well; a proper web framework (Pyramid), 100% backend test coverage, and a Docker-based development environment, make it easier for current and new developers to maintain it and add features.

Thanks to [Mozilla's Open Source Support funding](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), developers have added many new features, overhauled infrastructure, and made steady progress towards redirecting traffic to the new site and shutting down the old one. As of the middle of last year, package releases must go through the new PyPI, and as of late February, new user account registration is only available on the new site. The full switch will include redirecting browser and `pip install` traffic from the old site; then, sometime in late April or early May, the legacy site will be entirely shut down.

Shields will probably be able to seamlessly switch to the new site, and thanks to redirects, may not have to change anything immediately. [Here's a migration guide.](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi) And [here's the reference for the updated APIs.](https://warehouse.readthedocs.io/api-reference/)

Some new PyPI features:

* mobile-responsive UI
* easy-to-read project activity journal for project maintainers
* support for multiple project URLs (e.g., [for a homepage and a repo](https://packaging.python.org/tutorials/distributing-packages/#project-urls))
* no need to "register" a project before initial upload

Things that are going away, or already have (sometimes for policy or spam-fighting reasons), include:

* pythonhosted.com documentation hosting (pypa/warehouse#582)
* [download counts visible in the API](https://warehouse.readthedocs.io/api-reference/xml-rpc/#changes-to-legacy-api), as you saw in #716 (instead, use [the Google BigQuery service](https://packaging.python.org/guides/analyzing-pypi-package-downloads/))
* package maintainers being able to upload a new release via the web UI (instead, the recommended command-line tool is [Twine](http://twine.readthedocs.io/))
* package maintainers being able to log in and update release descriptions via the web UI (to update release metadata, they need to upload a new release; see [distutils-sig discussion](https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html))
* users being able to upload a package without verifying their email address with PyPI first
* [HTTP access to APIs; now it's HTTPS-only](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html)

And in the works:

* [PEP 541](https://www.python.org/dev/peps/pep-0541/) will enable more timely package takeovers, as people get package names transferred to them after conflict resolution
* Now that PEP 566 has been approved, [developers are working to get Markdown supported for README files on PyPI](https://github.com/pypa/warehouse/issues/869#issuecomment-340928703)

You can subscribe to [this announcements list](https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/) to get a heads-up when the big changes are about to happen.

Thank you for integrating with PyPI, and please [let us know](https://github.com/pypa/warehouse/issues/new) if you have any questions or problems with the new site!

**Comment by chris48s** [comment]
Hi @brainwane - thanks for posting about this. As a python user I'm eagerly awaiting the removal of the red pre-prod banner.

> Shields will probably be able to seamlessly switch to the new site

I've tried switching the base API URL to `https://pypi.org/`, run the test suite for the pypi integrations and it all passes, so I think you are right :)

Would you advise us to switch our production server over to querying warehouse instead of legacy PyPI now while warehouse is still technically in pre-prod, or would you advise that we should stick with legacy PyPI until April?

**Comment by brainwane** [comment]
@chris48s Thank you! My take is that, now that you've checked and your test suite passes, you should wait till you get the email that says "switch now" via https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/ which will probably be in April.

Also is there any chance you'll be at either of [the packaging sprints](https://wiki.python.org/psf/PackagingSprints) in the next few months?

**Comment by chris48s** [comment]
> you should wait till you get the email that says "switch now" via https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/ 

Sorted - cheers. I've signed up to that mailing list. I'll leave this issue open for now and close it once we switch over.

> Also is there any chance you'll be at either of the packaging sprints in the next few months?

I don't currently have plans to, but thanks for the info :)
