### ISSUE TITLE
Support Visual Studio Team Service Release Badge

### ISSUE THREAD

**Issue by iKaew** [badges/shields#1570]
VSTS just support release badge. It would be great if we can get it from here as same as build status. 
https://docs.microsoft.com/en-us/vsts/release-notes/2018/mar-05-vsts#share-deployment-status-using-a-badge

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. Would you be interested in working on this? We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md).

**Comment by Thilas** [comment]
I'm interested in such release badges and I have started to work on something.

**Comment by paulmelnikow** [comment]
Thanks @Thilas! Seems like this can be closed now. If I've misunderstood, please post a comment and someone will reopen.

**Comment by Thilas** [comment]
I confirm, everything seems good to me.
