### ISSUE TITLE
Shippable badge colors not changing

### ISSUE THREAD

**Issue by wltjr** [badges/shields#1571]
I have both badges for Travis and Shippable set for the build text area normally gray to be purple. For some reason across all my projects. The badge for Shippable does not change color. The code is the same for Travis and Shippable badges, with regard to changing color A.

```
[![Build Status](https://img.shields.io/travis/Obsidian-StudiosInc/os-xtoo/master.svg?colorA=9977bb&style=plastic)](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo)
[![Build Status](https://img.shields.io/shippable/5840e5d8e2ab4d0f0058b4b7/master.svg?colorA=9977bb&style=plastic)](https://app.shippable.com/projects/5840e5d8e2ab4d0f0058b4b7/)
```
But you can see they render differently. Both plastic style, but only Travis colors update, Shippable does not, no clue why.
[![Build Status](https://img.shields.io/travis/Obsidian-StudiosInc/os-xtoo/master.svg?colorA=9977bb&style=plastic)](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo) [![Build Status](https://img.shields.io/shippable/5840e5d8e2ab4d0f0058b4b7/master.svg?colorA=9977bb&style=plastic)](https://app.shippable.com/projects/5840e5d8e2ab4d0f0058b4b7/)

If someone could look into and address that issue, it would be greatly appreciated!!! Thank you!

**Comment by PyvesB** [comment]
Hello @wltjr !

Thanks for reporting this, I'll have a look into the problem and see whether I can spot any issues with our implementation. 😉 

Cheers,

Pyves

**Comment by wltjr** [comment]
Your welcome, and thanks for taking a look. Its a minor issue.

**Comment by PyvesB** [comment]
After looking through the code, if I'm not mistaken, this has already been fixed by @chris48s when he worked on pull request #1362.

Previously we had the following snippet in the code for the Shippable badge:
`badgeData.colorA = defaultOpts.colorA;`

This was basically overriding anything set by the user inside the URL.

Unfortunately the relevant pull request was merged just after our last release to production, so the fix is not yet actually available. Let's be patient! ^^

**Comment by wltjr** [comment]
Oh ok, so I had nice timing. Seen this for a while, finally file an issue after its been fixed. figures... No worries, no rush. Glad its been addressed already!

**Comment by paulmelnikow** [comment]
Meanwhile if you'd like to confirm for yourself that it's fixed, you could try the staging server: https://shields-staging.herokuapp.com

Let's track the deploy status in #1538. 😄
