### ISSUE TITLE
Badge request: SourceForge open ticket count

### ISSUE THREAD

**Issue by benibela** [badges/shields#1573]
It would be nice if there were a badge for the number sourceforge tickets similarly to the number of github issues badge.

There is a stats page that should be easy to parse:

https://sourceforge.net/p/texstudio/bugs/stats/
https://sourceforge.net/p/texstudio/feature-requests/stats/

There is also an API, but it only seems to give the number of total tickets, while the number of open issues is far more interesting

https://sourceforge.net/rest/p/texstudio/bugs?limit=1
https://sourceforge.net/rest/p/texstudio/feature-requests?limit=1

**Comment by PyvesB** [comment]
Hello @benibela !

Thank you for your suggestion. We would definitely try to use the API if possible, as parsing the stats page directly will likely be much more resource intensive.

I'm not familiar with the SourceForge API, but I believe we can use search terms in the API queries. For instance the following encoded API URL gives me direct access to the number of open issues:
[https://sourceforge.net/rest/p/texstudio/bugs/search?limit=1&q=status%3Aopen](https://sourceforge.net/rest/p/texstudio/bugs/search?limit=1&q=status%3Aopen)

Would you like to have a go at adding these new badges? We've got a [nice little tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) explaining how to add badges! 😉 

Cheers,

Pyves

**Comment by benibela** [comment]
This appears to work: https://img.shields.io/badge/dynamic/json.svg?label=open%20bugs&url=https%3A%2F%2Fsourceforge.net%2Frest%2Fp%2Ftexstudio%2Fbugs%2Fsearch%3Flimit%3D1%26q%3Dstatus%3Aopen&query=%24.count&colorB=green

**Comment by Prouser123** [comment]
Does anyone mind if I take this?

**Comment by calebcartwright** [comment]
> Does anyone mind if I take this?

Go for it!

**Comment by Prouser123** [comment]
Also I'm going to go with a dropdown to switch between bugs and suggestions to keep it as one badge.

Although with that said, I'm always open to suggestions :D
