### ISSUE TITLE
Badge without Subject

### ISSUE THREAD

**Issue by Eun** [badges/shields#1576]
It would be helpful if we were able to create a badge without the `Subject` at all.

The closest thing that is possible now is that:
https://img.shields.io/badge/-Hello-green.svg:
![badge](https://img.shields.io/badge/-Hello-green.svg)

**Comment by chris48s** [comment]
@RedSparr0w posted a nice workaround for this a few days ago: https://github.com/badges/shields/issues/1561#issuecomment-372143528

**Comment by paulmelnikow** [comment]
Let's track this in #343.
