### ISSUE TITLE
NuGet Badges fail to render most of the time

### ISSUE THREAD

**Issue by TAGC** [badges/shields#1588]
99 times out of 100, the NuGet badges on my READMEs fail to render. For example this shield: [![NuGet](https://img.shields.io/nuget/v/AsyncEvent.svg)](https://www.nuget.org/packages/AsyncEvent) from [this README](https://github.com/TAGC/AsyncEvent/blob/master/README.md).

Often what I notice is that once it manages to render once, it will continue to successfully render on page refreshes (<kbd>Ctrl+R</kbd>) until I force a page reload without caches (<kbd>Ctrl+Shift+R</kbd>).

**Comment by paulmelnikow** [comment]
Hi, thanks, sounds like this is #1568.
