### ISSUE TITLE
Update failing service tests

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1591]
I did a full run of the service test suite as part of reviewing #1563 and there are a few failures we should probably look into. I've not properly investigated any of them, but some probably require updates:

```
     dotnet-status
       get nuget package status
         
	[ GET http://localhost:1111/dotnetstatus/gh/jaredcnance/dotnet-status/API.json ]:
     ValidationError: child "value" fails because ["value" must be one of [up to date, out of date, processing]]
```

```
     dotnet-status
       get nuget package status
         
	[ GET http://localhost:1111/dotnetstatus/gh/jaredcnance/dotnet-status/invalid-project.json ]:

      AssertionError: expected { Object (name, value) } to deeply equal { Object (name, value) }
      + expected - actual

       {
         "name": "dependencies"
      -  "value": "inconclusive"
      +  "value": "project not found"
       }
```

```
     Github
       Public domain license
         
	[ GET http://localhost:1111/github/license/badges/shields.json?style=_shields_test ]:

      AssertionError: expected { Object (colorB, name, ...) } to deeply equal { Object (name, value, ...) }
      + expected - actual

       {
      -  "colorB": "#9f9f9f"
      +  "colorB": "#7cd958"
         "name": "license"
      -  "value": "unknown"
      +  "value": "CC0-1.0"
       }
```

```
      MicroBadger
       image size without a specified tag
         
	[ GET http://localhost:1111/microbadger/image-size/jumanjiman/puppet.json ]:
     ValidationError: child "value" fails because ["value" with value "unknown" fails to match the required pattern: /^[0-9]*[.]?[0-9]+\s(B|kB|MB|GB|TB|PB|EB|ZB|YB)$/]
```

```
      MicroBadger
       image size without a specified tag and no download size data returned
         
	[ GET http://localhost:1111/microbadger/image-size/_/centos.json ]:

      AssertionError: expected { name: 'image size', value: '73 MB' } to deeply equal { Object (name, value) }
      + expected - actual

       {
         "name": "image size"
      -  "value": "73 MB"
      +  "value": "unknown"
       }
```

**Comment by PyvesB** [comment]
Hey @chris48s !

Regarding dotnet-status, I had noticed a while back and opened [this issue](https://github.com/jaredcnance/dotnet-status/issues/18) in the author's repository. I was planning to let at least a month go by, and if he service is still down at that point, I would open a deprecation pull request for our badges. Does this make sense?

For MicroBadger, I had fixed the tests in #1536, but they seem to have broken once again. The returned data seems to regularly change and that makes the tests very unstable. I'll have another look at them sometime in the week-end. 😉

**Comment by chris48s** [comment]
Good work. Looks like you're already on the :briefcase:

**Comment by chris48s** [comment]
- [x] ~dotnet-status~ removed in #1630
- [x] ~microbadger~ examples updated in #1600
- [ ] Github Public domain license

**Comment by PyvesB** [comment]
Some of the MicroBadger tests have started failing once again. I've opened [this issue](https://github.com/microscaling/microbadger/issues/38) to flag the problems with their service. Hopefully we'll be able to get reliable API responses sometime soon. 😉
