### ISSUE TITLE
BuildHive badges

### ISSUE THREAD

**Issue by nicoulaj** [badges/shields#16]
[BuildHive](https://buildhive.cloudbees.com) is a CI service.
Example of their badge [here](https://github.com/nicoulaj/idea-markdown#idea-markdown-)...
It would be great if they could be involved in this project.

**Comment by olivierlacan** [comment]
@espadrine Do you really want to keep building these integrations for external services? Any way we can make it possible for people to create them simply based on an integration template of sorts so anyone can field a PR if they want their favorite service integrated?

The sheer amount of issues for obscure services is what's making me ask.

**Comment by espadrine** [comment]
@olivierlacan Whenever we can, we try to be generic (see for instance Jenkins support). Services are systematically encouraged to rely on Shields.io to serve exact badges (through `/badge/…`). However, the reason people ask for support is that they don't have badge consistency, and some services don't want consistency, just publicity.

**Comment by larsbrinkhoff** [comment]
I guess this can be closed now:
https://www.cloudbees.com/whats-next
