### ISSUE TITLE
GitHub Releases Broken

### ISSUE THREAD

**Issue by GrahamCampbell** [badges/shields#161]
The GitHub releases badge for many of my repos don't work. Here is one of them: https://img.shields.io/github/release/GrahamCampbell/Bootstrap-CMS.svg.
Here are the tags for the repo: https://github.com/GrahamCampbell/Bootstrap-CMS/releases.

---

[![Latest Version](https://img.shields.io/github/release/GrahamCampbell/Bootstrap-CMS.svg)](https://github.com/GrahamCampbell/Bootstrap-CMS/releases)

**Comment by gocanto** [comment]
any clue? I just came around this issue

**Comment by espadrine** [comment]
The main issue left is rate limiting, which is this issue: https://github.com/badges/shields/issues/529.
