### ISSUE TITLE
Github commit merge status in branch

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1616]
With an eye to reusability, here's a design for a new badge. This came up for our own use at https://github.com/badges/shields/pull/1605#issuecomment-376595800, though a lot of folks use branches for their deploy pipelines, so I feel like it could be handy beyond Shields.

https://img.shields.io/github/commit-status/gh-pages/ed419b0a77d89094e11466797dfae68d92a2fab9

![](https://img.shields.io/badge/commit%20status-not%20in%20gh--pages-yellow.svg)
![](https://img.shields.io/badge/commit%20status-in%20gh--pages-brightgreen.svg)

https://img.shields.io/github/commit-status/gh-pages/ed419b0a77d89094e11466797dfae68d92a2fab9?label=deploy%20status

![](https://img.shields.io/badge/deploy%20status-not%20in%20gh--pages-yellow.svg)
![](https://img.shields.io/badge/deploy%20status-in%20gh--pages-brightgreen.svg)

A future enhancement could allow overriding the message. Though that suggestion has come up before on other badges, and it might be a good problem to solve in a more global way.

**Comment by platan** [comment]
This badge format would be useful when you have commit id. It's not a problem for a bot or when you know where to find id ;-) I was thinking about a simpler API, where we know branch name and PR id. It would take one extra API call to get commit id from PR. 
But since we are going to automatically put a badge with deploy info in PR you proposal would do the job!

**Comment by paulmelnikow** [comment]
Love the idea of showing the merge status of a PR! Perhaps I wrongly inferred it would be difficult to get the commit ID from an API call. Maybe then, the default label should be **merge status**.

**Comment by platan** [comment]
I'm working on this badge (https://github.com/badges/shields/pull/1605#issuecomment-391477654).

**Comment by platan** [comment]
Implemented in https://github.com/badges/shields/pull/1709
