### ISSUE TITLE
Badge request: Homebrew Cask

### ISSUE THREAD

**Issue by FranklinYu** [badges/shields#1638]
[Homebrew Cask](https://caskroom.github.io/) is now officially part of Homebrew. Now that we already have a badge for Homebrew, it makes sense to also include Homebrew Cask.

**Comment by chris48s** [comment]
Is there an API for cask?

**Comment by franklinyu** [comment]
I don't think there is one like <http://formulae.brew.sh>. I thought GitHub API works, doesn't it?

**Comment by paulmelnikow** [comment]
We have [a nice tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). If anyone would like to give it a go, please do! If you have questions, feel free to post in this thread and a maintainer will help.

**Comment by pnowaczyk** [comment]
I'll look into this
