### ISSUE TITLE
Failed to fetch StackExchange badges randomly

### ISSUE THREAD

**Issue by Atry** [badges/shields#1639]
The badge at https://img.shields.io/stackexchange/stackoverflow/t/augeas.svg offen responses an HTTP 504 to me

![](https://img.shields.io/stackexchange/stackoverflow/t/augeas.svg)

**Comment by RedSparr0w** [comment]
Thanks for reporting this, I think this may be related to #1568.
Closing Issue [Duplicate], Please feel free to continue discussions in #1568.

-------------
_**Note**: If you do think this is a different problem, Please re-open this issue._
