### ISSUE TITLE
“Error fetching resource” using total downloads badge - badge fails to load in README

### ISSUE THREAD

**Issue by mayankk2308** [badges/shields#1640]
My repos are not showing the downloads badge anymore. I have extended the rate limits as instructed on the shields website. Exmaple repo: [purge-wrangler](https://github.com/mayankk2308/purge-wrangler). It was working fine yesterday (no changes made since then). Clicking the badge (no link set) you get an “error fetching resource” message in a separate tab.

**Comment by mayankk2308** [comment]
Update: Badges seem to be working again.

**Comment by RedSparr0w** [comment]
Glad to hear your badges are showing correctly again, I think this may be related to #1568.
Closing Issue [Duplicate, Solved], Please feel free to continue discussions in #1568.

-------------
_**Note**: If you do think this is a different problem (& is not resolved), Please re-open this issue._
