### ISSUE TITLE
Travis / Appveyor status badges rendering very slowly

### ISSUE THREAD

**Issue by mratsim** [badges/shields#1643]
It seems like status badges are rendering extremely slowly on several (all?) repo.

Examples:
 - https://github.com/nim-lang/Nim
 - https://github.com/status-im/nimbus

**Comment by RedSparr0w** [comment]
Unfortunately it's not just Travis/Appveyor badges that are affected, See #1568.
Closing Issue [Duplicate], Please feel free to continue discussions in #1568.

-------------
_**Note**: If you do think this is a different problem, Please re-open this issue._
