### ISSUE TITLE
Codeship badge return "Build: Unknown"

### ISSUE THREAD

**Issue by wanderingstan** [badges/shields#1654]
The [codeship badges](https://img.shields.io/codeship/e7d56d99-e092-4f45-952d-fdd445139c7a.svg) on https://shields.io/ are "returning Build: Unknown", as are the badges I attempted to create for my new codeship tests. 

![image](https://user-images.githubusercontent.com/673455/39074285-fe424d7c-44ad-11e8-8abc-afae8ba37517.png)

The [codeship api](https://apidocs.codeship.com/v2/authentication/access-and-permissions) seems to indicate that all calls need an access token. Perhaps this requirement was added after the shields.io badge was coded up? 

If codeship cannot be supported, then we should remove it.

**Comment by dennisnewel** [comment]
that is correct that the API requires authentication.

Not sure about what is possible on the shields.io end, but the codeship badge URLs return parsable SVG which include the status. Here's an example: https://app.codeship.com/projects/c3c92d10-63f1-0133-8a1d-5a56884200ab/status?branch=master which contain the element `<g id="status_success" clip-path="url(#clip0)">` indicating success. Perhaps that's useful to determine state?

**Comment by RedSparr0w** [comment]
Seems to be working again:
![image](https://user-images.githubusercontent.com/7288322/39331674-470dff88-49f9-11e8-8ffe-529b9b78fa7d.png)
Not sure what would have changed though.

@dennisnewel
Just had a look throught the code and looks like we are already [parsing the svg](https://github.com/badges/shields/blob/master/server.js#L4926) image header to determine the state:
![image](https://user-images.githubusercontent.com/7288322/39331752-7e2e265a-49f9-11e8-9895-070fe60d6ba1.png)

**Comment by mikkabouzu** [comment]
@RedSparr0w the problem seems to be with the regexp checking the header:                       `.match(/filename="status_(.+)\.png"/)`
Codeship returns svg instead of png, so it's not matching. 
The file extension doesn't seem to matter, so changing it to `.match(/filename="status_(.+)\./)` should solve the issue, right?

**Comment by dennisnewel** [comment]
That could probably explain it. We (Codeship) don't have any rate limits in place on the badges

**Comment by RedSparr0w** [comment]
Nice catch! Are you up for creating a PR or would you like me to?

**Comment by RedSparr0w** [comment]
@dennisnewel That's good to know, Thanks.
Is the `?branch=` parameter required for the badges?
Because i noticed on the badge link you provided above , if you remove `?branch=master` it errors:
`https://app.codeship.com/projects/c3c92d10-63f1-0133-8a1d-5a56884200ab/status`:
![](https://app.codeship.com/projects/c3c92d10-63f1-0133-8a1d-5a56884200ab/status)
`https://app.codeship.com/projects/c3c92d10-63f1-0133-8a1d-5a56884200ab/status?branch=master`:
![](https://app.codeship.com/projects/c3c92d10-63f1-0133-8a1d-5a56884200ab/status?branch=master)

**Comment by dennisnewel** [comment]
i can't see why it shouldn't work though...the only small thing is that we've moved from `https://codeship.com` to `https://app.codeship.com` for the badges, so maybe something get's stuck in the load balancer?

@mrz1836 when did it stop working for you?

**Comment by mrz1836** [comment]
About a week ago. Are you able to replicate the issue?

**Comment by dennisnewel** [comment]
yeah, the codeship badges work fine ![codeship](https://app.codeship.com/projects/cdb18f20-d75d-0134-dcb2-760971575778/status) but not when using shields.io ![shields](https://img.shields.io/codeship/cdb18f20-d75d-0134-dcb2-760971575778.svg) even though i'm using the same project uuid

**Comment by mrz1836** [comment]
I'm glad it's not just me ;-). I have the exact same situation @dennisnewel . Oh well, out goes the sheilds.io image for now...

**Comment by dennisnewel** [comment]
there has been some changes to the badges around a week ago or so, basically to make them work better on retina screens, but also the switch from `png` to `svg` (including changing the content type to `svg+xml`). I just don't see how those changes could cause the shields.io process to stop working...

**Comment by dennisnewel** [comment]
🤦‍♂️ sorry...not sure why i assumed it was already in production.

nice detail with the logo!

**Comment by RedSparr0w** [comment]
No worries, it's definitely a common assumption 😄

Thanks!

**Comment by mikkabouzu** [comment]
@RedSparr0w is there an ETA on the production rollout?

**Comment by RedSparr0w** [comment]
@mikkabouzu see #1538:

Quoting @paulmelnikow:

> Deploys usually happen every 1–3 weeks. Thaddée, who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account (and maybe the servers too) are shared with other services he runs.

It's been a bit over a month now (last commit Mar 25) so hopefully it shouldn't be too far off. 
:crossed_fingers:
