### ISSUE TITLE
How to properly use discord badge

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1659]
Where do one find the needed id?

**Comment by tooomm** [comment]
Thanks, found the ID. It now displays `widget disabled` at least...

**Comment by RedSparr0w** [comment]
Think this issue has been resolved?

If not feel free to re-open this!
😄

**Comment by zardini123** [comment]
Discord now has the Widget section just showing "Streamer Mode Enabled."  Where do you go now to enable these "server widgets"?

**Comment by C0rn3j** [comment]
The Server Widget option is now at the bottom of Engagement:

<img width="1050" height="1268" alt="Image" src="https://github.com/user-attachments/assets/4399f732-9091-452b-b611-e61b3fa159ab" />
