### ISSUE TITLE
Travis-ci.com support

### ISSUE THREAD

**Issue by fubar-coder** [badges/shields#1674]
Travis CI starts merging open source and private repositories on travis-ci.com. Does shields.io support travis-ci.com instead of travis-ci.org?

**Comment by chris48s** [comment]
link for context: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

At the moment, we call the `travis-ci.org` api. Based on the details available so far, I'm unclear what changes we will need to make to support this.

**Comment by webknjaz** [comment]
I think change "org" to "com": https://github.com/badges/shields/blob/master/services/travis/travis.tester.js#L32

But this should be a separate badge.

**Comment by RedSparr0w** [comment]
I'm not sure creating a seperate badge would be the best option as they say all `.org` will be merged to `.com`
>_You can continue to use both your travis-ci.org and travis-ci.com accounts as usual for now._ **Over the next several months, we’ll be migrating all travis-ci.org repositories and customers to travis-ci.com. Though this will not happen right away,** _you can go ahead and read more about what to expect [in the docs](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/)._

Would be good to be able to just automatically swap people over from `.org` to `.com` when the change happens without having to keep support for a seperate badge/users having to update their own badges.

**Comment by webknjaz** [comment]
You could probably do two API calls and see which one is enabled.

**Comment by panva** [comment]
Contacted support after migrating my repos about this.

> The build status badges need to be recreated/links changed as the current ones would direct to the old repo on travis-ci.org.

I guess a separate badge is needed. Calling the old still reports the last status for migrated repos.

**Comment by RedSparr0w** [comment]
>You could probably do two API calls and see which one is enabled.

>Calling the old still reports the last status for migrated repos

Could call the new api, then the old api if non existant.
Then eventually remove the old api once everything has been migrated over.

**Comment by panva** [comment]
> Could call the new api, then the old api if non existant.
> Then eventually remove the old api once everything has been migrated over.

Prone to wrong status, repos on .com might exist but not be used anymore or setup. For instance mine used to be private and tested on.com, then moved over to .org until now. Before the migration calling .com would still work and returned a status from years ago.

**Comment by RedSparr0w** [comment]
ah, didn't realise you previously had the option. makes sense.
