### ISSUE TITLE
Add a template for a "new badge request"

### ISSUE THREAD

**Issue by platan** [badges/shields#1678]
Recently GitHub [improved issue templates](https://blog.github.com/2018-05-02-issue-template-improvements/). I think we could add template for a "new badge request". Template could have some questions like:
- What is the badge for?
- Which API do you want to use? (Does it have a public API? Does the API requires an API key? Where the API documentation can by found?)
and other questions which which usually appears in issues requesting support for a new service.

**Comment by RedSparr0w** [comment]
Good idea, this would definitely be a useful addition.
