### ISSUE TITLE
Support authentication for private nexus repo

### ISSUE THREAD

**Issue by rockerhieu** [badges/shields#1699]
I couldn't find a way to use badge for a private nexus repo which requires authentication.

Please troubleshoot. Thanks!

**Comment by paulmelnikow** [comment]
Happy to support this. It looks like this will require two things: (1) a small modification to `server.js` to read the nexus secret from `serverSecrets` if it exists, and (2) self-hosting an instance of Shields. If you are able to work on that, or if anyone else reading this wants this feature, and you need help moving that forward, feel free to ask here and one of the maintainers can help.

**Comment by rockerhieu** [comment]
Hey @paulmelnikow, let me know the next steps. I'm ready to move forward.

**Comment by paulmelnikow** [comment]
Great!

You could take a look at [the Jira badge](https://github.com/badges/shields/blob/def1bc331cf90509e75038c1e1d8681c65aefe8f/server.js#L209-L265), which pulls the secret value from `serverSecrets`. You could add code to the Nexus section, also in `server.js`, to do something similar. You can test it out locally using your authorization information, and open a pull request with the change.

You could also add a test that uses a mock to show that the authorization information is passed to the API as expected, though that might be more effort than it's worth. This is the test code:

https://github.com/badges/shields/blob/def1bc331cf90509e75038c1e1d8681c65aefe8f/services/nexus/nexus.tester.js

There are some general contribution guidelines in https://github.com/badges/shields/blob/master/CONTRIBUTING.md and a lot of step-by-step help in the new badge tutorial https://github.com/badges/shields/blob/master/doc/TUTORIAL.md.
