### ISSUE TITLE
Deployment status in PR

### ISSUE THREAD

**Issue by platan** [badges/shields#1708]
The idea started in https://github.com/badges/shields/pull/1605#issuecomment-376595800. We want "to post a comment at the end of a PR thread, which indicates whether it's been deployed yet".

There are two things we need:
- Badge with Github commit merge status in branch (https://github.com/badges/shields/issues/1616)
- a [probot](https://probot.github.io/) app for creating a comment in closed PR

**Comment by platan** [comment]
I think we have all required building blocks. We need to put them together. 
- Badge with Github commit merge status in branch (#1616) is merged to master #1709. We have to wait for a deployment. Meanwhile, we can use a temporary instance deployed at Now by me
https://shields-deployment.now.sh/github/commit-status/badges/shields/gh-pages/9d90bd1f9549b3c8b59ad8338a8acd92e1e36f3c.svg?label=deploy%20status (https://github.com/badges/shields/commit/9d90bd1f9549b3c8b59ad8338a8acd92e1e36f3c)
![](https://shields-deployment.now.sh/github/commit-status/badges/shields/gh-pages/9d90bd1f9549b3c8b59ad8338a8acd92e1e36f3c.svg?label=deploy%20status)
https://shields-deployment.now.sh/github/commit-status/badges/shields/gh-pages/fe4ac0bf1cbd0dbe04bf2cc439a2eee51f4c3907.svg?label=deploy%20status (https://github.com/badges/shields/commit/fe4ac0bf1cbd0dbe04bf2cc439a2eee51f4c3907)
![](https://shields-deployment.now.sh/github/commit-status/badges/shields/gh-pages/fe4ac0bf1cbd0dbe04bf2cc439a2eee51f4c3907.svg?label=deploy%20status)
- A https://github.com/bkeepers/workflow configuration. I've deployed an instance of the workflow app  https://github.com/apps/shields-deployment and used it in an example repo https://github.com/platan/shields-deployment-status-example, configuration https://github.com/platan/shields-deployment-status-example/blob/master/.github/probot.js, PR examples https://github.com/platan/shields-deployment-status-example/pull/4, https://github.com/platan/shields-deployment-status-example/pull/6. This example repo has branches similar to these in the shields repo (`master` + `gh-pages`). 

What's next?
- We need a workflow app. We can use https://github.com/apps/shields-deployment (name, description, log can be changed). This instance is deployed by me at Now and is available or everyone. Alternatively we can create a new app (https://probot.github.io/docs/deployment/) at https://github.com/badges/shields or https://github.com/shields-ci
- We need someone who can install workflow app at https://github.com/badges/shields. Who can do it?
- We need a workflow configuration. I can create a PR with https://github.com/platan/shields-deployment-status-example/blob/master/.github/probot.js as a first version.

**Comment by chris48s** [comment]
Great work on this:

![screenshot at 2018-06-07 19 34 21](https://user-images.githubusercontent.com/6025893/41120286-fa199084-6a8c-11e8-87d7-ed9b4abfcbe6.png)

> We need someone who can install workflow app at https://github.com/badges/shields. Who can do it?

If I click 'install' on https://github.com/apps/shields-deployment/ I seem to have permission to add the app to this repo with 'Read and write access to pull requests'. You should be able to do it as well - we have the same repo permissions.

If we add https://github.com/apps/shields-deployment and wanted to move it later, does it become problematic to move? Presumably we revoke one app and add another? If that's the case, I reckon submit a PR to add https://github.com/platan/shields-deployment-status-example/blob/master/.github/probot.js and we add https://github.com/apps/shields-deployment . If it there is a reason to move it later, we can do..

**Comment by platan** [comment]
I haven't check if I can install this app in Shields ;-) Thanks. 
After installing this app we can change it's description/logo and even a name. New name is immediately visible in all comments. And we can always uninstall this app. I'll create a PR with a workflow configuration.

**Comment by platan** [comment]
#1724 is merged and we are ready to go. Would you like me to install https://github.com/apps/shields-deployment in shields (or one of you can do it if you want :smile:)?

**Comment by chris48s** [comment]
I pressed the buttons :D

![alive](https://user-images.githubusercontent.com/6025893/41485720-9b1a3e46-70d9-11e8-9afa-46d5b3420f80.jpg)

**Comment by paulmelnikow** [comment]
Awesome work on this! It's really exciting to see 😄

**Comment by chris48s** [comment]
@platan - is the final remaining job on this to switch `shields-deployment.now.sh` to `shields.io` after the next deploy gets done?

**Comment by platan** [comment]
@chris48s Additionally I would like to turn off "shields-deployment.now.sh". Therefore we should update all badges linking to the old domain: https://github.com/badges/shields/search?q=%22This+badge+displays+deployment+status%3A%22&type=Issues (switch to "shields.io").

**Comment by RedSparr0w** [comment]
Looks like its live on shields now:
![](https://img.shields.io/github/commit-status/badges/shields/gh-pages/9d90bd1f9549b3c8b59ad8338a8acd92e1e36f3c.svg?label=deploy%20status)
`https://img.shields.io/github/commit-status/badges/shields/gh-pages/9d90bd1f9549b3c8b59ad8338a8acd92e1e36f3c.svg?label=deploy%20status`

**Comment by platan** [comment]
All badges in comments created by bot (https://github.com/badges/shields/search?q=%22This+badge+displays+deployment+status%3A%22&type=Issues) are served from img.shields.io.
