### ISSUE TITLE
Add Badge for Travis-ci.com

### ISSUE THREAD

**Issue by ivandelabeldad** [badges/shields#1710]
Travis-ci is migrating all the projects from `travis-ci.org` to `travis-ci.com`.

[https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps)

Like has been said in [#1674](https://github.com/badges/shields/issues/1674) there is the requirement of a new badge because travis can report the status of already migrated projects.

**Comment by tooomm** [comment]
can be closed, see #1711

**Comment by chris48s** [comment]
We tend to close when we merge rather than when we deploy. https://github.com/badges/shields/pull/1711#issuecomment-397862508 will indicate when the feature is live.

Cheers
