### ISSUE TITLE
The release shield displays undefined.

### ISSUE THREAD

**Issue by vim2meta** [badges/shields#1714]
If the only release is a pre-release, than the badge displays undefined. It should display `0.1.0` in a orange color like NPM pre-release badges.
URL: https://img.shields.io/github/release/LJNeon/ffa.svg

**Comment by RedSparr0w** [comment]
You need to add `/all` to the end of the url:
```
https://img.shields.io/github/release/LJNeon/ffa/all.svg
```
![LJNeon/ffa release badge](https://img.shields.io/github/release/LJNeon/ffa/all.svg)
Otherwise it is just looking for the lastest `release` not `pre-release`.
