### ISSUE TITLE
Scoped packages = invalid

### ISSUE THREAD

**Issue by sdgluck** [badges/shields#1732]
I can see an [issue here](https://github.com/badges/shields/issues/429) that claims to add support for scoped packages.

However, notice that the examples of scoped packages read "invalid":

![image](https://user-images.githubusercontent.com/3265173/41203584-1413e8ea-6cd1-11e8-8dfe-5afc071b79b0.png)

**Comment by chris48s** [comment]
Every time I've checked it over the past couple of days https://registry.npmjs.org/-/package/%40cycle%2Fcore/dist-tags has returned valid output and the last few daily runs of the NPM tests have worked so I'm going to close this - I think it is now stable again.
