### ISSUE TITLE
fix scrutinizer error handling

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1739]
At the moment we're doing this: ![](https://img.shields.io/badge/coverage-NaN%25-brightgreen.svg)

![screenshot at 2018-06-17 12 23 08](https://user-images.githubusercontent.com/6025893/41507382-587a14fc-7229-11e8-875e-80ca23359c05.png)

**Comment by PyvesB** [comment]
I'm going to be quite busy in the next week or so, but I'm happy to pick this up after that and add some tests for this service. 😉
