### ISSUE TITLE
Travis CI domain migration

### ISSUE THREAD

**Issue by Richienb** [badges/shields#1747]
Travis CI will migrate along with all of it's projects from [travis-ci.org](https://travis-ci.org) to [travis-ci.com](https://travis-ci.com) at 30/06/18 according to a Travis CI [blog post](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org) which at the time of writing is only 6 more days! After those 6 more days, the Travis CI shield will stop working as the badge only serves the `.org` version of the site.

**Comment by tiagoporto** [comment]
Check #1711

**Comment by Richienb** [comment]
Oh, ok. Thanks.
