### ISSUE TITLE
Add functionality for change color dynamically

### ISSUE THREAD

**Issue by chandankumar4** [badges/shields#1752]
- Add functionality to change color dynamically for badge just like their data while creating the dynamic badge

**Comment by RedSparr0w** [comment]
#1525 Adds this functionality 😄

**Comment by paulmelnikow** [comment]
It could be nice to support in the standard json badge as well. I can't remember if the code in #1525 is doing that.

**Comment by paulmelnikow** [comment]
I think the endpoint badge, when it's merged, will be a good way of handling this. Let's track in #2473.

**Comment by chandankumar4** [comment]
Thanks @paulmelnikow for adding this feature
