### ISSUE TITLE
Setting up with Internal GitHub?

### ISSUE THREAD

**Issue by Aghassi** [badges/shields#1753]
https://github.com/badges/shields/blob/9882a44e565bf973f279d164dbdcf43629e89fc2/lib/github-auth.js#L69

This line seems to suggest this will only ever hit external github, even if a custom GITHUB_URL is provided. Is this correct?

**Comment by paulmelnikow** [comment]
Hi, thanks for your question. That code is for the API endpoint that lets you grant a github API token to Shields. It's not really relevant to self-hosting.

All the badges respect `GITHUB_URL` and your configured `gh_token`.

**Comment by Aghassi** [comment]
Yeah so maybe I have this setup wrong then 😄 .

I have a `GITHUB_URL` in my docker-compose that is under `environment`.
I also have `GH_TOKEN` (just like that) in a `shields.env` file that mount via `env_file` in the docker-compose.
I also have `gh_token` (just like that) in a `private/secret.json` file that I map in the compose via `volumes`

```
    volumes:
      - ~/private/secret.json:private/secret.json
```

Is that not the right way to pass the token? I think I was trying everything, but wasn't seeing results. Not sure the best way to validate it is working... Most of my badges show `undefined` for GitHub, even when I correct/change the example to a repo I know exists.
