### ISSUE TITLE
Badge request: Stryker

### ISSUE THREAD

**Issue by tiagoporto** [badges/shields#1758]
Shields.io is going to add support [Stryker Mutation](https://stryker-mutator.io/blog/2018-02-08/get-your-mutation-score-badge-now.html)?

**Comment by RedSparr0w** [comment]
@tiagoporto Thank you for your suggestion!
If you would like to give this a try we have a [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) available on how to add new badges!
😄

**Comment by paulmelnikow** [comment]
Is there a public API?

**Comment by regseb** [comment]
The URL of the API is `https://badge-api.stryker-mutator.io/github.com/{username}/{repository_name}/{branch}`. For example for _stryker-js_ : https://badge-api.stryker-mutator.io/github.com/stryker-mutator/stryker-js/master. With the answer:

```json
{
    "color": "orange",
    "label": "Mutation score",
    "message": "75.6%",
    "schemaVersion": 1
}
```

**Comment by PyvesB** [comment]
The aforementioned API endpoint can be used by our Endpoint badge:
https://img.shields.io/endpoint?url=https://badge-api.stryker-mutator.io/github.com/stryker-mutator/stryker-js/master
![](https://img.shields.io/endpoint?url=https://badge-api.stryker-mutator.io/github.com/stryker-mutator/stryker-js/master)

**Comment by PyvesB** [comment]
In the absence of a non-Shields specific API (see https://github.com/badges/shields/pull/6368#issuecomment-815496467 for more details), the aforementioned endpoint badge is  the best we can provide at the moment. Will close this issue for now, but can always reopen at a later point if things change on the Stryker side.
