### ISSUE TITLE
Support to Travis private repo?

### ISSUE THREAD

**Issue by Fazendaaa** [badges/shields#1766]
Hey, I'm trying to make a badge to a  private repo integrated to TravisCI in my master branch, right now I've tried a lot of possibilities, my last one is the following:

    [![Build Status](https://img.shields.io/travis/c/token/MYTOKENHERE/github/Fazendaaa/PRIVATEREPO/master.svg?style=flat-square)](https://travis-ci.com/Fazendaaa/PRIVATEREPO)

What am I doing wrong?

**Comment by RedSparr0w** [comment]
I don't believe we support private repositories on travis-ci **yet**

If you feel up to it, you could create a PR to include this functionality,
A good place to start would be to take a look at the circle-ci implementation:
https://github.com/badges/shields/blob/b05d93c9c11cf1657b978d7abb19915a88109a8c/server.js#L2437-L2439

**Comment by Fazendaaa** [comment]
Thanks, @RedSparr0w :)

After I finished this project I will look into how to do it this.

**Comment by paulmelnikow** [comment]
I'd add that in general we don't implement badges which pass secrets in the URLs, as they make the secret available to anyone looking at the badge. Self-hosting is a better way to handle these. The Circle badge has been an exception.
