### ISSUE TITLE
Add Hugo Theme Shield

### ISSUE THREAD

**Issue by jhabdas** [badges/shields#1769]
I know I dropped the ball on #662 after someone else dropped the ball. But things are different this time, mmmkay? I'd like to create a Hugo theme shield which looks at the `min_version` in a `theme.toml` file and makes a pretty badge with a gopher.

Example theme toml:
https://git.habd.as/comfusion/after-dark/src/branch/master/theme.toml#L45

The growing list of blessed Hugo themes:
https://themes.gohugo.io

Any guidance high-level or RTFM is highly appreciated. Thanks!

**Comment by chris48s** [comment]
Docs for adding a new badge are here: https://github.com/badges/shields/blob/master/doc/TUTORIAL.md Your PR should also include tests. Docs for writing tests are in: https://github.com/badges/shields/blob/master/doc/service-tests.md

I don't think we have any badges which process toml yet, so you will also need to find a toml parser for javascript and add it to the project requirements.

If you need more help as you work on it, feel free to ask questions.

**Comment by PyvesB** [comment]
I've often seen files using such a format, but I didn't know it was called TOML, thanks for enlightening me!

**Comment by jhabdas** [comment]
> I've often seen files using such a format, but I didn't know it was called TOML, thanks for enlightening me!

[Tom's Obvious, Minimal Language](https://github.com/toml-lang/toml) is hands down the best way to write configuration files. The learning curve is about the same as YAML and it's waaaay more forgiving than JSON when it comes to parsing, which helps prevent errors when you derp a fatfinger.

**Comment by jhabdas** [comment]
Awaiting design assets. [Check here](https://discourse.gohugo.io/t/a-shield-for-hugo-themes/12799/2?u=balibebas) for status.

**Comment by paulmelnikow** [comment]
Feel free to implement the badge first! In general, we won't merge a logo without a badge, though we can definitely merge the badge without the logo.

**Comment by jhabdas** [comment]
Thanks @paulmelnikow. May circle back on this later. There doesn't seem to be much desire based on the response from the Hugo forums. Maybe later. :)

**Comment by jhabdas** [comment]
Thanks @paulmelnikow. May circle back on this later. There doesn't seem to be much desire based on the response from the Hugo forums. Perhaps that'll change in time.
