### ISSUE TITLE
Licenses from NPM

### ISSUE THREAD

**Issue by jhabdas** [badges/shields#1772]
Currently licenses are pulled from GitHub which is great but not everyone uses it. As opposed to attempting to grab licenses from self-hosted git servers (which could get ugly) perhaps a happy middle ground would be to add the ability to pull licenses from NPM in addition to GitHub.

The workaround is to create a static badge using the flexible URL structure.

**Comment by chris48s** [comment]
The NPM license badge pulls its license info from the NPM API. For example if I call

https://img.shields.io/npm/l/express.svg

that is taking the license from

https://registry.npmjs.org/express/latest

**Comment by jhabdas** [comment]
Excellent. I tried to guess a similar route but was unsuccessful after reading the doc.
