### ISSUE TITLE
Error Fetching Resource

### ISSUE THREAD

**Issue by sirkadirov** [badges/shields#1775]
All Shields badges in all repos (but not on Shields website) are broken for me ("Error Fetching Resource" status). I think something wrong with caching images by camo.githubusercontent.com. What's happening?

**Comment by kopax** [comment]
I have the same error :  

https://github.com/yeutech-lab/accept-dot-path/blob/master/README.md

![image](https://user-images.githubusercontent.com/1866564/42641101-fdfa63d4-861d-11e8-892d-b0c645458cac.png)

Work fine on npm:

![image](https://user-images.githubusercontent.com/1866564/42641137-0f0f1854-861e-11e8-8723-ae55a539ef90.png)

**Comment by sirkadirov** [comment]
I thought that something wrong with `svg` file types and checked with `png`. Same problem.

**Comment by sirkadirov** [comment]
Duplication #1568

**Comment by FahadBinHussain** [comment]
`Error Fetching Resource` on `https://camo.githubusercontent.com/`

Any solution?

**Comment by Gerfy1** [comment]
Same error
