### ISSUE TITLE
Jenkins tests always returns 'invalid'

### ISSUE THREAD

**Issue by HansBrende** [badges/shields#1776]
The following markup:

`[![Jenkins tests](https://img.shields.io/jenkins/t/https/builds.apache.org/Any23-trunk.svg?maxAge=86400)](https://builds.apache.org/job/Any23-trunk)`

produces:

[![Jenkins tests](https://img.shields.io/jenkins/t/https/builds.apache.org/Any23-trunk.svg?maxAge=86400)](https://builds.apache.org/job/Any23-trunk)

**Comment by RedSparr0w** [comment]
Closing as fixed via #1777
