### ISSUE TITLE
My first deploy

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1783]
Hey maintainers,

I'd like to attempt a deploy on my own: see https://github.com/badges/shields/pull/1742#issuecomment-404249968 and https://github.com/badges/shields/pull/1742#issuecomment-398796144.

Would someone like to tag-team with me? The most helpful thing would be to monitor Sentry, though I know @espadrine hasn't been comfortable with anyone else having access to that. I think you could help in other ways, though, by hitting the server directly, monitoring the issues queue / twitter, and looking at the server status page.

This could be an evening this week, Oregon time, or Sunday afternoon, Chicago time. I've some availability next week too. Let me know if you're interested and let's see if we can find a time.

**Comment by paulmelnikow** [comment]
Just wanted to add: let's not cram to get stuff merged. If this deploy goes well let's plan on doing another one in a week.

**Comment by RedSparr0w** [comment]
I'd recommend during the weekend if possible, as we have pretty good uptimes.

I could modify my script at http://shields.redsparr0w.com/1568/ to send an email/notification during the time period if it detects any notable downtime?

**Comment by chris48s** [comment]
I should be available to keep an eye on things if you do Sunday afternoon central time. Evening pacific time doesn't co-ordinate well with my timezone.

Just in terms of what timezones maintainers are in (useful to know if we're trying to schedule stuff), based on the timestamp on everyone's last commit in the git log:

@chris48s +0100
@platan +0200
@PyvesB +0100
@RedSparr0w +1200

Might be easiest to co-ordinate on Discord for this one.

**Comment by paulmelnikow** [comment]
Mine's -0400 when I'm home, though I'm often working on the road, between -0500 and -0700. It's interesting to see everyone's time zones!

@RedSparr0w Maybe you could send the notifications to a new discord channel?

@chris48s Cool! Let's plan on Sunday.

**Comment by espadrine** [comment]
I'm eager to tag along! I am in CEST (+0200).

**Comment by paulmelnikow** [comment]
Cool! Things are lined up for when @chris48 is gets online, which is a little over an hour from now, shortly after 10 a.m. UTC-5. Will be great for you to be around in case anything goes dreadfully wrong! At Chris's suggestion, let's coordinate on Discord.

**Comment by paulmelnikow** [comment]
s0 is live. We're going to monitor and if all looks good in a few hours we'll deploy to the other servers and the frontend.

**Comment by paulmelnikow** [comment]
And… it's live! 

<img width="169" alt="screen shot 2018-07-22 at 4 39 28 pm" src="https://user-images.githubusercontent.com/1487036/43050414-e5773d84-8dcd-11e8-9909-314b2ce81e1f.png">

Thanks & congrats, everyone!

If anything systemic comes up, feel free to post here and one of the maintainers can reopen.
