### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#1784]
It looks like we are missing `favicon.png` on the main website.

**Edit:** the staging server still has the favicon

**Comment by paulmelnikow** [comment]
Ah, probably it broke in the last deploy. I can’t remember if we are setting the favicon path manually or depending on the default.

**Comment by RedSparr0w** [comment]
Looks like that should do the trick :+1:

**Comment by paulmelnikow** [comment]
Is it working for you now?

**Comment by RedSparr0w** [comment]
Sure is!
