### ISSUE TITLE
CLI raster badges are broken

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1788]
As observed at https://github.com/badges/shields/pull/1774/files#r203522813, the CLI isn't generating raster badges correctly.

```sh
node lib/badge-cli.js '' '' '#bada55' .png > favicon.png
```

Observed output:
![favicon](https://user-images.githubusercontent.com/1487036/42918125-535afb52-8ac1-11e8-88a4-b2918125ebd6.png)

Expected output:
![](https://img.shields.io/:--bada55.png?style=plastic)

**Comment by platan** [comment]
```bash
# prepare a test
cat test.sh 
node lib/badge-cli.js '' '' '#bada55' .svg > favicon-tested.svg
grep 'width="22"' favicon-tested.svg

# find a bad commit
git bisect start HEAD 438e47adfb74e9a775e3fed7a5547959f343c009
git bisect run ./test.sh

# result
b216bcc17e667a2fb09bede7be0d1c67e731d767 is the first bad commit
```
the bad commit -> https://github.com/badges/shields/commit/b216bcc17e667a2fb09bede7be0d1c67e731d767

**Comment by platan** [comment]
But:
```
node lib/badge-cli.js '' '' '#bada55' .png > favicon.png
```

gives me: 
- ![favicon](https://user-images.githubusercontent.com/1526000/44352988-05955800-a4a6-11e8-9060-549e0ad61969.png) in master
- ![favicon](https://user-images.githubusercontent.com/1526000/44353002-1514a100-a4a6-11e8-8a5e-1c71e555fdfc.png) in 438e47adfb74e9a775e3fed7a5547959f343c009 (random old commit)
- ![favicon](https://user-images.githubusercontent.com/1526000/44353142-763c7480-a4a6-11e8-8d67-56397945818e.png) in b216bcc17e667a2fb09bede7be0d1c67e731d767
- ![favicon](https://user-images.githubusercontent.com/1526000/44353163-83f1fa00-a4a6-11e8-9b70-97f11be80757.png) in b216bcc17e667a2fb09bede7be0d1c67e731d767 (one commit before b216bcc17e667a2fb09bede7be0d1c67e731d767)

**Comment by paulmelnikow** [comment]
Seems like this may be a "wontfix," given discussion in #3587 and #3112.

**Comment by paulmelnikow** [comment]
As discussed at https://github.com/badges/shields/pull/3644#issuecomment-508947740 it seems these work fine on some systems.

I've just upgraded imagemagick, and this is what I'm seeing now:

`node lib/badge-cli.js build passed :green .png > mybadge.png`

![mybadge](https://user-images.githubusercontent.com/1487036/60760376-72eca180-a002-11e9-9fa2-965bc719efe4.png)

The summary of other discussions we've had is that:

- We want this to work more reliably.
- It'll be through an `optionalDependency` to keep the gh-badges footprint smaller.
- We can switch from gm / imagemagick to Puppeteer using the more modern rasterization library [convert-svg-to-png](https://www.npmjs.com/package/convert-svg-to-png) – that's the one that's being used in [svg-to-image-proxy](https://github.com/badges/svg-to-image-proxy).

**Comment by brettz9** [comment]
Whenever the change might be made, could the functionality be added on the programmatic side as well?

**Comment by paulmelnikow** [comment]
This functionality is being removed in #4756, so closing this.
