### ISSUE TITLE
Our test badge incorrectly stays green

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1792]
Our tests went red on master a couple days ago. There were failures in the main tests, not just the service tests. The badge has shown passing I think that entire time, and still is. I thought the problem was that Circle was showing results from the most recent tests on any branch instead of just master. However if I get the badge for master, I see the same thing.

https://img.shields.io/circleci/project/github/badges/shields/master.svg
![](https://img.shields.io/circleci/project/github/badges/shields/master.svg)

https://github.com/badges/shields/commits/master

**Comment by chris48s** [comment]
Quick look at this suggests this is because the badge is only looking at the first build status (`data[0]`), so this will be affecting any users of this badge with >1 pipelines in their build. We should modify this to look at all of the builds in the array.

**Comment by paulmelnikow** [comment]
I reopened this in light of a discussion @chris48s and I were having here: https://github.com/badges/shields/pull/1927#discussion_r211068591.

Sorry I didn't post that before!
