### ISSUE TITLE
Disable danger for dependabot PRs

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1826]
Danger messages are intended for humans. Bots talking to bots is not so helpful :) All the dependabot PRs are on a branch called `dependabot/something` so this should be reasonably easy to pick up in CI.

Refs #1822

**Comment by paulmelnikow** [comment]
No danger message in #1860 but seeing one in #1861, so it looks like the fix worked!

**Comment by paulmelnikow** [comment]
Yea, good callout. Let’s handle it in #1827.
