### ISSUE TITLE
Reduce noise from shields-ci and shields-deployment bots

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1827]
The shields-ci bot (danger) currently says thank you in every PR, to all kind of contributors.
Maybe reduce that the new contributors only (if possible). It would be more helpful if it provides some useful link or hint in a way to those first timers.

The other hints like doc updates or warnings are fine I think.

See https://github.com/badges/shields/pull/1822#issuecomment-409715601

<br>

~~Also, from https://github.com/badges/shields/issues/1826#issuecomment-409728536~~
>~~We may also want to disable the shields-deployment [bot] status info (for dependabot update PR's).~~

👍 Addressed in #1924

**Comment by chris48s** [comment]
This should be sorted now  #1843 and #1924 are merged

**Comment by chris48s** [comment]
I'm not sure off the top of my head how to efficiently work out if the user submitting the PR has previously contributed to the repository or not (when I say "efficiently", I mean using either the data provided by danger in the `danger.github` object or one additional GitHub API call), but I'm sure it is do-able. If anyone wants to pick this up, this probot integration https://github.com/behaviorbot/new-pr-welcome does it, so the code for that probably contains the answer to that question.
