### ISSUE TITLE
Gradle plugin badges can be served by maven-metadata but needs to have configurable naming

### ISSUE THREAD

**Issue by loosebazooka** [badges/shields#1839]
The gradle plugin repository can be referenced by maven-metadata:

https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/maven-metadata.xml.svg

However, this looks like this ![some text](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/maven-metadata.xml.svg) 

But it's really the gradle plugin version. Maybe a way to customize the text here would make it useful to gradle plugin developers.

**Comment by RedSparr0w** [comment]
Thanks for opening this issue,
I believe you can achieve this by adding `?label=gradle` to the end of your badges url:
[`https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/maven-metadata.xml.svg?label=gradle`](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/maven-metadata.xml.svg?label=gradle)
![badge](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/maven-metadata.xml.svg?label=gradle)

------------------
Closing as solved
**Note:**_If this doesn't solve your issue, feel free to re-open :smile:_
