### ISSUE TITLE
Show only examples/explanations for dynamic badges type which is selected

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1844]
Currently all three are shown together, would be better to only show the selected and relevant ones:
![dynamic examples](https://user-images.githubusercontent.com/9874850/43668776-eeae6ffc-977e-11e8-95f9-ab04d81c3439.png)

**Comment by tooomm** [comment]
bump :)

**Comment by MonliH** [comment]
@tooomm by "selected and relevant ones," do you mean the one selected in the dropdown above? I could implement this if others think it provides a better UX.

**Comment by tooomm** [comment]
@MonliH Exactly, once a user decides for a format, the other examples and query links are only disturbing and not helpful.

To be in line with the rest of the page, it makes sense to always show a single more general example that's always visible:
`https://img.shields.io/badge/dynamic/<TYPE>?url=<URL>&label=<LABEL>&query=<QUERY>&color=<COLOR>&prefix=<PREFIX>&suffix=<SUFFIX>`

And change that for the specific one once a data type is selected in the dropdown?

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/

The new version of the site has separate pages for the dynamic json/xml/yaml bages

- https://shields.io/badges/dynamic-json-badge
- https://shields.io/badges/dynamic-xml-badge
- https://shields.io/badges/dynamic-yaml-badge

so I'm going to close this issue
