### ISSUE TITLE
Swap out a couple dev tools

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1847]
I'd like to suggest we swap out two of our dev tools.

I've had great luck using yarn on other projects, and have started using it exclusively on my own. It's faster than the npm CLI, and I've found it to be more reliable as well. It uses the same package repository, so in that dimension nothing is changing. Curious other people's experience. This one may have to wait for @espadrine because I'm not sure how dependencies are installed during our server deploy process. That process may directly invoke npm install. In theory that would still install them, however we wouldn't want to lose the benefits we're getting now from the lockfile.

I also suggest we switch from mocha to jest. I have less personal experience with it, but what I've heard from other people is very positive. It has a watch mode which splits tests between multiple processes, and re-runs failed tests first. Overall it sounds like a superior developer experience. Right now IcedFrisby only supports mocha, so we'd still run the service tests in mocha (at least until I can adapt IcedFrisby for jest). I expect the conversion process would be fairly straightforward.

**Comment by chris48s** [comment]
Relevant reading: https://mixmax.com/blog/to-yarn-and-back-again-npm

**Comment by paulmelnikow** [comment]
Interesting. In my experience, when switching back and forth between branches with slightly different package.json and package-lock.json, running `npm install` takes quite a long time. I do think the install time from empty node modules is pretty comparable with newer npm.

I forgot to mention that @Daniel15 is also a maintainer of yarn 😄

He's on the thread of the "bad regression" that post links to. Indeed, it was a bad one, though to yarn's credit, it was patched the next day and fixed within a week in all versions. I've run into serious bugs in the npm cli which have sat open for years. That's probably true in yarn, too. Though I think the reason yarn was created was frustration with npm's slowness addressing certain critical features.

> Frequently when engineers would run yarn after pulling down a project's latest changes, their yarn.lock files would become dirty due to Yarn making optimizations. Resolving this required engineers to make and push commits unrelated to their work. Yarn should perform these optimizations when commands update yarn.lock, not the next time yarn is run.

I'm curious about this one… 🤔

**Comment by Daniel15** [comment]
For what it's worth, Jest is very good! I'd recommend it 😃

**Comment by paulmelnikow** [comment]
Any thoughts on the yarn.lock optimization / dirtying issue the mixmax folks raised?

**Comment by Daniel15** [comment]
Hmm, not sure. I don't actually work on the code for Yarn, I've just worked on its packaging (.deb package, Windows installer, etc). I think the issue there is that the optimization algorithm can change between Yarn versions, so it may optimize it when you run Yarn. I'm not sure why it doesn't only do that when you run `yarn add`, though.

I don't think it's an issue if you ensure everyone uses the same Yarn versions. Yarn does have an option to commit the Yarn release to source control as a .js file, and redirect all `yarn` calls to use the committed version rather than the globally installed version. AFAIK that's what we do internally at Facebook.

**Comment by chris48s** [comment]
> I don't think it's an issue if you ensure everyone uses the same Yarn versions

That is a crazy large "if" in an open source project with a wide contributor base :D It is inevitable that various nodes in that cat-herd are going to be running different versions.

> Yarn does have an option to commit the Yarn release to source control as a .js file

Do you have a docs link for that feature? Would be useful to read more about this.

**Comment by Daniel15** [comment]
> Do you have a docs link for that feature? Would be useful to read more about this.

It's a `.yarnrc` config option: https://yarnpkg.com/lang/en/docs/yarnrc/#toc-yarn-path

Not sure if there's other docs on it... @bestander, @arcanis or @BYK may know.

**Comment by bestander** [comment]
At FB we just check in [yarn.js](https://github.com/yarnpkg/yarn/releases/download/v1.9.4/yarn-1.9.4.js) into source code, our install scripts use it directly with node, e.g. "node /path/to/yarn.js install".

https://yarnpkg.com/lang/en/docs/yarnrc/#toc-yarn-path looks legit as well if you want to keep using yarn commands, I haven't used it personally.

**Comment by arcanis** [comment]
We actually also use `yarn-path` at Facebook, to ensure that anyone using the Yarn commands manually (for example to add, remove, or upgrade a package) will use the exact same version. It's super handy because it's completely transparent to the user 😃 

I want to write a blogpost about this, but time is scarce lately 😅

**Comment by paulmelnikow** [comment]
A recent discussion on Zeit's chat about yarn vs npm:

https://spectrum.chat/thread/c9c89f78-b7a9-4b6a-9b3c-ba99660badcb

**Comment by paulmelnikow** [comment]
I've had negative experience with Jest's handling of before hooks and the npm CLI has continued to improve. This is seeming like less of a priority right now.
