### ISSUE TITLE
Flatten Badges

### ISSUE THREAD

**Issue by caffinatedmonkey** [badges/shields#185]
In the past few weeks github has been flattening its design by removing gradients and drop shadows across the board. The badges don't fit into github's design as well as they used to :cry:

Something like this:

![flat](https://rawgit.com/caffinatedmonkey/2984360a6bd20545f5ce/raw/1163b88608f0ffb9ecbf52457c7f211f4c5fbf06/build.svg)

Instead of:

![gradient](https://rawgit.com/caffinatedmonkey/2984360a6bd20545f5ce/raw/0327715a4736d5e974f13a09069e58fe4575ee95/gradient.svg)

This also shaves 100B off the request.

**Comment by mgedmin** [comment]
Feb 1 is approaching.  It would be nice to get some confirmation if that date is still "tentative".

**Comment by espadrine** [comment]
@mgedmin Barring unforeseeable events, it will be done at the planned date.

**Comment by mgedmin** [comment]
The front page still has the following bit:

![screenshot](https://cloud.githubusercontent.com/assets/159967/5996814/2d97210c-aab9-11e4-9752-135ad272089c.png)

It would be nice to mention that the "flat" style became default on 2015-02-01 and that the older style is called "plastic".
