### ISSUE TITLE
Badge to show dependents of a GitHub repo

### ISSUE THREAD

**Issue by sindresorhus** [badges/shields#1858]
The number you find here: https://github.com/chalk/chalk/network/dependents

GitHub has a GraphQL API endpoint for it: https://developer.github.com/changes/2018-04-24-preview-dependency-graph-and-vulnerability-hooks/

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion.

That endpoint doesn't seem to provide access to the dependents number, only the dependencies number.

IIRC scraping github violates their ToS so I'm not sure the best way forward here.

Libraries.io has a different number available, but it doesn't match Github; see librariesio/libraries.io#2005. I added a badge for that in #1895.

This looks like this the same request as #1550 so I will close this issue and repost this response there.
