### ISSUE TITLE
shields.io images are currently broken

### ISSUE THREAD

**Issue by natefinch** [badges/shields#191]
Going to the homepage shows broken images everywhere, and generated image links return an application error

**Comment by jonahoffline** [comment]
Running into this right now!

**Comment by espadrine** [comment]
@jonahoffline thanks for telling me! It crashed. I restarted it.

Because of Heroku's changes, it may be unstable this week.

Hopefully [this](https://github.com/badges/shields/issues/459) will change things for the better!

**Comment by jonahoffline** [comment]
@espadrine no worries, thanks :) 
I :heart: `Shields`

**Comment by zirho** [comment]
broken from LA

**Comment by espadrine** [comment]
Linux crashed. It should be better now.

**Comment by lsloan** [comment]
It seems broken right now:
* ![Packagist](https://img.shields.io/packagist/v/kherge/json.svg)
* ![Packagist Pre Release](https://img.shields.io/packagist/vpre/kherge/json.svg)

**Comment by espadrine** [comment]
There is more information on the current status at https://github.com/badges/shields/issues/868#issuecomment-277758447.
