### ISSUE TITLE
Shortcut to run all tests for service family

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1923]
In a case like [librariesio](https://github.com/badges/shields/tree/master/services/librariesio) where we have split tests out across multiple files, it would be helpful if  `npm run test:services -- --only=librariesio` ran all of the rests in `librariesio/*.tester.js`.

This would mean a PR that needs to run them all could just have `[librariesio]` in the title instead of  `[librariesio-dependent-repos librariesio-dependents librariesio-sourcerank]`

**Comment by paulmelnikow** [comment]
This is addressed in #1933.
