### ISSUE TITLE
Adopt CRA or Gatsby

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1943]
We should also adopt Gatsby, create-react-app, or something similar designed for static sites, to eliminate the unnecessary runtime dependency on Next.js while also letting someone else maintain our front-end tooling.

This has been said many times before, though there was no issue for it.

Hopefully this will take care of #1941.

**Comment by paulmelnikow** [comment]
Nice overview on Gatsby: https://medium.freecodecamp.org/why-you-should-use-gatsbyjs-to-build-static-sites-4f90eb6d1a7b

I'm running into some issues with styled-components on the examples page and think it might be time to finally tackle this.

**Comment by mbrandau** [comment]
Haven't had too much time to look at it by now 😕 But from what I was able to oversee, I think we also need to implement some sort of GraphQL API to build the example pages. If we had to look at that, we could also implement a base GraphQL service while at it.
I'll follow up with more information when I have more time.

**Comment by paulmelnikow** [comment]
Gatsby has built-in support for GraphQL which is neat, though I don't think we have to use it. It might be neat for the servers to advertise their services that way, though I think running a GraphQL server is unnecessary overhead; we could have a yaml and/or json endpoint instead. Gatsby uses webpack under the hood, so we could continue to load the yaml file as we're doing now. It'd be less fancy but should work fine.
