### ISSUE TITLE
Failing libraries.io service tests

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1959]
The test failures suggest there may be something wrong with our error handling code

```diff
-  "value": "not found"
+  "value": "package not found"
```

but it is hard to tell when the valid cases are also failing with a timeout. Lets check this again when the upstream API calls are responding in a more stable way.

**Comment by PyvesB** [comment]
Yes, there is a problem in our error handling for the libraries.io service. #1895 and #1888 were in flight at about the same time, therefore the service is now still using the old error handling style. I'll submit a pull request to address this shortly. 😉
