### ISSUE TITLE
Convert more badges to use static previews

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1961]
We show example badges on our home page but they don't need to show real data. For performance reasons, it is useful to render a badge using some fake example data instead of making a call to a real API. It is also useful to show the URL format in a parametrised form.

We can do this by switching from defining a `previewUrl` to defining:

* ~~`urlPattern`~~ `pattern` (the URL format in a parameterised form)
* ~~`exampleUrl` (a real badge URL the user can call if they want to)~~ `namedParams` (mappings of pattern placeholders to values for a real, working example)
* `staticExample` (a JSON object or call to the service's `render()` function which generates a fake badge)

You can find examples of service badges which use a `previewUrl` using this search:

https://github.com/search?utf8=%E2%9C%93&q=previewUrl+user%3Abadges+repo%3Ashields+path%3A%2Fservices+language%3AJavaScript&type=Code&ref=advsearch&l=JavaScript&l=

An example pull request will probably look like this:

https://github.com/badges/shields/pull/2230/files

**Comment by paulmelnikow** [comment]
@chris48s I tagged this "good first issue." Would you be up for updating your top post with a few sentences about how new contributors could go about helping with this?

**Comment by chris48s** [comment]
no probs. I've updated the top post
