### ISSUE TITLE
Add F-Droid version badge

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#1963]
## Context
The [F-Droid] app store publishes open-source Android apps. In https://gitlab.com/fdroid/fdroiddata/issues/1325, I asked, how to implement a badge which shows the latest published version.

## Motivation
Since F-Droid allows continuous deployment, this could allow developers to fast-feedback and encourage contributions.

## Evaluation
There are over 2600 apps in the app store. Some would use the badge.

[F-Droid]: https://f-droid.org

Questions:
- Where should new services be added? The tutorial suggests into the server.js file.

**Comment by PyvesB** [comment]
> Where should new services be added? The tutorial suggests into the server.js file.

We're slowly migrating services away from the _server.js_ model, but have not yet updated the relevant parts of the documentation. You could have a go at using our new service model. You can refer to _/services/apm_ or _/services/wercker_ for example of how this can be done. 😉 

One question though: does F-Droid have an API?

**Comment by chris48s** [comment]
> One question though: does F-Droid have an API?

I found it _slightly_ unclear but my reading was that it doesn't and the [linked issue](https://gitlab.com/fdroid/fdroiddata/issues/1325) is a feature request for F-Droid to add a suitable API. If I've misunderstood that, feel free to remove the "needs upstream help" tag.

**Comment by niccokunzmann** [comment]
Thanks for the fast responses!

I do not know if f-droid has an API. But the page is built reliably using jekyll and such we know what it looks like. https://gitlab.com/fdroid/fdroid-website/blob/9ae61894a18889ed749d36d5afbd0db3d0b0cfdd/_layouts/package.html#L147

**Comment by niccokunzmann** [comment]
I git the badge working. Now,  I can focus on the nice things.

- [ ] add tests
- [ ] use new service model
- [ ] document the new service model

**Comment by niccokunzmann** [comment]
The new service model could be ok. I will try.
@PyvesB about the tests: https://github.com/badges/shields/blob/master/services/wercker/wercker.tester.js#L28 Where is the fake response located?

**Comment by PyvesB** [comment]
Our tests generally query the real service when run. For hard to reproduce error cases, we sometimes intercept requests and return fake responses, see _apm.tester.js_ for some examples.

I'm concerned that F-Droid does not have an API. Performing scraping on the website's pages directly is more brittle and CPU intensive. I'm inclined to make some noise on the F-Droid project so that they document their API if it exists or so that they create one otherwise. 😉

**Comment by niccokunzmann** [comment]
`__snapshots__/make-badge.spec.js` what is this for? I should not commit this, should I?

**Comment by paulmelnikow** [comment]
Nope; something's wrong with that. See #1925.

**Comment by niccokunzmann** [comment]
Tests are added. However, I think, one needs to give examples. I will do that shortly.
