### ISSUE TITLE
Pull request message about tests should mention the documentation

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#1968]
In PR #1965, I can see the message

> This PR modified the server but none of the service tests. That's okay so long as it's refactoring existing code.

I would like to add this to make more clear how to proceed.

> Otherwise, please consider adding tests to the service: https://github.com/badges/shields/blob/master/doc/service-tests.md#readme.

**Comment by PyvesB** [comment]
Seem like a sensible thing to add in my opinion!
