### ISSUE TITLE
All tests run if only specific tests are specified

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#1971]
When I run 
```
$ npm run test:services -- --only:travis

> gh-badges@1.3.0 test:services /home/user/shields
> HANDLE_INTERNAL_ERRORS=false mocha --delay lib/service-test-runner/cli.js "--only:travis"

Running all service tests.

```
as specified in https://github.com/badges/shields/blob/master/doc/service-tests.md#readme,
all tests run and not only the travis tests.

**Comment by niccokunzmann** [comment]
```
npm run test:services -- --grep droid
```

only runs if I put `droid` in the 

```
t.create('f-droid Package is not found')
  .get('/org.pacien.tincapp.json')
  .intercept(nock =>
    nock('https://f-droid.org')
      .get('/en/packages/org.pacien.tincapp/')
      .reply([404, manyVersions])
  )
  .expectJSON({ name: 'F-Droid', value: 'app not found' })
```

If it is in the Tester creation, this does not run.

**Comment by niccokunzmann** [comment]
It seems that the title is responsible 

    1) F-Droid app store

And upper and lower-case is important.

**Comment by paulmelnikow** [comment]
Hiya! `--only:travis` should be `--only=travis` which I think should fix the issue. If it’s not working for droid, check the `id` that’s passed to the ServiceTester constructor.
