### ISSUE TITLE
Issue Stats badges broken

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#1977]
It has been over two weeks since the Issue Stats service has gone down. See [this related issue](https://github.com/hstove/issue_stats/issues/50).

I've tried following up with the author, but if there aren't any news in the coming weeks we should consider deprecating this service and removing the badge examples.

**Comment by RedSparr0w** [comment]
I think it may be worth depreciating them sooner than later, as the commit can always be reverted when/if they come back online.

**Comment by PyvesB** [comment]
Yeah, I was planning on tackling this in the weekend if no responses from the author by then.
