### ISSUE TITLE
Question: Fast branch deployment for review?

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#1978]
Docker and heroku both allow buttons to deploy from a URL. Maybe, we could allow danger to add a link so one can deploy pull requests by one click on demand. Would this be a useful feature?

Danger output:

> If you like to see how this service works, you can [click here](), to start an instance.

- Example button: https://hub.docker.com/_/wordpress/ ![](https://github.com/play-with-docker/stacks/raw/cff22438cb4195ace27f9b15784bbb497047afa7/assets/images/button.png)
- Related deployed Pull Request : #1965

**Comment by niccokunzmann** [comment]
In #1965, there is an auto-deployment to heroku. I believe it is possible. Although I do not know how, this is resolved for the developers here. One can ask for such a pull request deployment.

**Comment by paulmelnikow** [comment]
For some background: #1155 #960

Heroku review apps auto-deploy for branches of the main repo. For forks a maintainer needs to deploy them manually. New maintainers can be added to the Heroku staging app which allows them to do that.

Zeit Now also offers this for PRs. I think you can configure it to use forks as well, which could be useful.

Would be great to document this in CONTRIBUTING.md as the OP in #960 pointed out. Probably a maintainer should run though the steps and make sure it's clear enough to follow the first time around.
