### ISSUE TITLE
Codacy badges broken

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#1985]
Codacy have updated their own badges and we are no longer able to retrieve any relevant information using our `fetchFromSvg` function. As our result, Shields's badges are no longer working properly:

![](https://img.shields.io/codacy/grade/e27821fb6289410b8f58338c7e0bc686.svg)
![](https://img.shields.io/codacy/coverage/e27821fb6289410b8f58338c7e0bc686.svg)

They do have a proper API documented [here](https://api.codacy.com/swagger), but an API token is required. When none is provided, requests are rejected, even for public projects:

> {"error":"not found"}

We may need to contact support to get this sorted.

**Comment by nemchik** [comment]
I have reached out to Codacy support to make them aware of the issue. I will report back with any relevant responses.

**Comment by nemchik** [comment]
Received a response from Codacy support. They have added the information required back into the badges. It seems like previously they only included two text fields in the SVG but now they include 3, so the index of the field needed for shields has increased by one for both badges.

**Comment by PyvesB** [comment]
This is great, thanks for keeping us updated!

The way forward is probably something along these lines:
* add tests to our Codacy service implementation. This will allow us to maintain it more easily in the future.
* extend `fetchFromSvg` to allow specifying a match index other than 1.
* make sure we keep an eye on #2031 to avoid any clashes with the ongoing work around some other SVG services.

I'm happy to look into this over the week-end, but if someone wants to help out and submit a pull request before that, please feel free to do so (simply make some noise here so that we don't both start working on the same thing). 😉

**Comment by PyvesB** [comment]
Okay, a proposed fix has now been merged into the `master` branch and will likely be deployed in the coming days. 👍

**Comment by PyvesB** [comment]
All good, we are live since yesterday:
![](https://img.shields.io/codacy/grade/e27821fb6289410b8f58338c7e0bc686.svg)
![](https://img.shields.io/codacy/coverage/59d607d0e311408885e418004068ea58.svg)

We're doing some more work to further improve the user experience with our Codacy badges, see #2102 for more information. 😉
