### ISSUE TITLE
A couple minor issues in the badge listings

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1987]
I did a review of staging vs production to validate #1958 before deployment, and ran into a few minor issues.

Not sure any of them are related to #1958, though they all need fixing!

1. ![](https://shields-staging.herokuapp.com/discord/102860784329052160.svg) - displaying as **chat | inaccessible ** https://shields-staging.herokuapp.com/discord/102860784329052160.svg
2. The PyPI django version and python version badges appear twice in the listing.
3. Bundlephobia is showing in version, though it belongs in size.

**Comment by RedSparr0w** [comment]
1. Looks like this may have been a 1 off/fixed? showing as expected for me now.
2. Nice spotting
3. :+1:

**Comment by paulmelnikow** [comment]
These are all fixed.
