### ISSUE TITLE
Fix wercker examples, make static examples less error prone

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1994]
![screenshot at 2018-08-28 15 15 15](https://user-images.githubusercontent.com/6025893/44728833-41977100-aad5-11e8-9f81-8944741051c8.png)

I think this is probably the only one currently broken on `master`, but I just made the exact same mistake and didn't notice it in PR #1927 :man_facepalming: 

Fix will look like https://github.com/badges/shields/pull/1927/commits/64974cb8c35f7e97acdb5ee649d8e8694457278e

Clearly the way I've done this is a bit fiddly/error prone. I think I need to add some additional error checking to the base class or better assumptions so it is easier to "fall into the pit of success" :hole:

**Comment by PyvesB** [comment]
I noticed something else that doesn't seem like correct behaviour: when clicking on a badge URL on the homepage, the badge that appears in the window is broken, as it tries to render it using the placeholder URL:
![screenshot 123](https://user-images.githubusercontent.com/10694593/44881925-37c66700-aca9-11e8-88b2-239a811adc64.png)

**Comment by PyvesB** [comment]
Hmm... I didn't realise it would automatically refresh when you typed. Ignore me.
