### ISSUE TITLE
Lowercase badge labels

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1997]
Let's review the badge labels and make sure they are all lowercase. We're very close, though there are a select few like AUR and OSS Lifecycle are not.

Let's also document this requirement in the [badge guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines).

Ref: https://github.com/badges/shields/pull/1965#discussion_r213098278

**Comment by RedSparr0w** [comment]
Sounds like a plan,
labels + messages are both generally lowercase _(with the exception of the `for-the-badge` style)_

although i think some do justify not being lowercase:
![license](https://img.shields.io/:license-MIT-blue.svg)
_(not sure about the AUR and OSS badges)_

**Comment by PyvesB** [comment]
I think messages are fine, we should probably only enforce lower-casing for the left hand-side of badges. 😉
