### ISSUE TITLE
GitHub release badge broken?

### ISSUE THREAD

**Issue by PalatinCoder** [badges/shields#2017]
Hi everyone,
since a few days the Github release badge is broken for my repos, it shows `release | repo not found`.
package version seems to work fine for some repos, but not all of mine.

Is anyone experiencing the same problems?

**Comment by chris48s** [comment]
I can see that if I request this badge on a repo that has no releases e.g:

https://img.shields.io/github/release/PalatinCoder/DuttweilerApp.svg
![](https://img.shields.io/github/release/PalatinCoder/DuttweilerApp.svg)
or
https://img.shields.io/github/release/chris48s/arcgis2geojson.svg
![](https://img.shields.io/github/release/chris48s/arcgis2geojson.svg)

I'm getting that result, although the badge is working normally for repos that have releases e.g:

https://img.shields.io/github/release/qubyte/rubidium.svg
![](https://img.shields.io/github/release/qubyte/rubidium.svg)

It looks like the reason for this is that we're getting a `200 OK` status code with a completely empty response from the GH api for repos which match this pattern e.g:

https://api.github.com/repos/PalatinCoder/DuttweilerApp/releases
https://api.github.com/repos/chris48s/arcgis2geojson/releases

but we're getting sensible responses for a repo with releases:

https://api.github.com/repos/PalatinCoder/DuttweilerApp/releases

I'm not really familiar with the GH integrations as I've not done much work on them, so I'm not totally sure what we would normally expect that response to look like, but it seems unusual. Does anyone a bit more familiar with this have any thoughts?

**Comment by RedSparr0w** [comment]
if you add `/all` to the end of your addresses it should work as expected:
https://img.shields.io/github/release/PalatinCoder/DuttweilerApp/all.svg
![](https://img.shields.io/github/release/PalatinCoder/DuttweilerApp/all.svg)
https://img.shields.io/github/release/chris48s/arcgis2geojson/all.svg
![](https://img.shields.io/github/release/chris48s/arcgis2geojson/all.svg)
https://img.shields.io/github/release/qubyte/rubidium/all.svg
![](https://img.shields.io/github/release/qubyte/rubidium/all.svg)

As without `/all` the api link returns `404` for the latest release:
https://api.github.com/repos/PalatinCoder/DuttweilerApp/releases/latest

Not sure if there is anyway we could work around this.

----------------
Closing as solved :+1: 

If this issue still persist or you feel it hasn't been resolved correctly please re-open this issue.
