### ISSUE TITLE
CircleCI Badge Error

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#2030]
CircleCI badges are showing an error of **unparseable json response**. Not sure if there is an issue on the Circle side, but seeing this with all my projects and it can also be seen in this very repo:

![image](https://user-images.githubusercontent.com/13042488/44886040-ba3f2e80-ac89-11e8-9a42-b88098cc0467.png)

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this. It's new code and we'll track down the problem. Could you post a link to the project where you're seeing the problem, so we make sure the fix works in that case too?

@chris48s let me know if you want to tackle this.

**Comment by calebcartwright** [comment]
Thanks for the quick response! I've seen it in a lot of places, but first noticed it on [this project](https://www.npmjs.com/package/vsts-bump)

**Comment by chris48s** [comment]
@paulmelnikow  I've had a really quick look and left a note at https://github.com/badges/shields/issues/2034#issuecomment-417759121

If its still open tomorrow I'll try and spend some more time looking into it

**Comment by paulmelnikow** [comment]
There’s a fix pending: #2036

**Comment by paulmelnikow** [comment]
The fix is live! Thanks again for the report!
