### ISSUE TITLE
NPM Download inaccessible 

### ISSUE THREAD

**Issue by jcubic** [badges/shields#2033]
Just notice that download from npm shows inaccessible:

![badg](https://img.shields.io/npm/dm/jquery.terminal.svg?style=flat)

**Comment by hamzahamidi** [comment]
Same Here

**Comment by paulmelnikow** [comment]
Hi, thanks for opening this.

This post corresponds to some momentary downtime observed here, on one of the servers:

https://status.shields.io/779605534

There's also this report from npm, which says download counts were temporarily offline:

https://status.npmjs.org/incidents/kh5969s21pjz

Looks like an upstream issue which is now resolved. Please comment or reopen if not!
