### ISSUE TITLE
Uptimerobot unparseable json format

### ISSUE THREAD

**Issue by KSchreuder** [badges/shields#2034]
Uptime robot badge gives `unparseable json format`

**Comment by KSchreuder** [comment]
Same issue as https://github.com/badges/shields/issues/2030

**Comment by chris48s** [comment]
Cheers for reporting this @KSchreuder 

I've had a really quick look at this. I haven't quite worked it out, but if I check the repo out to e37c0b6 CircleCI and UptimeRobot aren't throwing this error. As soon as I apply 11fa611 they fail. I think something about changing the inheritance pattern so `BaseJsonService` inherits from `BaseHTTPService` has had an unexpected knock-on effect.

I'm not going to have a proper chance to work on this tonight, but if anyone else is able to pick it up, that's probably roughly where you're looking. This might be more immediately obvious to someone who participated in the review of #1965

**Comment by paulmelnikow** [comment]
Interesting. That narrows things down a lot! I'm looking into it now.

**Comment by paulmelnikow** [comment]
It's a simple fix: beef866. Thanks for the pointer; it narrowed it down quickly!

**Comment by paulmelnikow** [comment]
The fix is live! Thanks again for the report!
