### ISSUE TITLE
NuGet badges for multiple packages

### ISSUE THREAD

**Issue by adamralph** [badges/shields#204]
Some projects/repos, e.g. https://github.com/scriptcs/scriptcs, produce a number of NuGet packages, e.g. https://www.nuget.org/profiles/scriptcs/.

It would be nice to be have NuGet badges which took all packages into account, certainly for download count.

Version would also work if the versions of all the packages are the same. If they differ, perhaps the badge could display the latest version, a version range, or just '4 packages'.

I think the name of each package would have to be specified in the URL, e.g. `http://img.shields.io/nuget/multi/dt/shields.svg?ScriptCs.Contracts&ScriptCs.Core&ScriptCs.Engine.Roslyn&ScriptCs.Hosting`

Specifying the packages using a filter is difficult since the only options are search, author and tags. The only one under definitive control of the publisher is author, but even that will only be narrowly useful since most projects don't create an author specifically for their package publishing. Even if they did, it would be fairly common that they would publish packages from many repos which means the badge wouldn't be useful for puttting on a repo specific readme. Still, that could also provided as an option, e.g. `http://img.shields.io/nuget/profile/dt/scriptcs.svg`.

I guess another badge could give package count, e.g. `http://img.shields.io/nuget/multi/pc/shields.svg?ScriptCs.Contracts&ScriptCs.Core&ScriptCs.Engine.Roslyn&ScriptCs.Hosting` and `http://img.shields.io/nuget/profile/pc/scriptcs.svg`.

**Comment by jnm2** [comment]
I've had several uses for this.

**Comment by paulmelnikow** [comment]
Hi, could you provide links?

**Comment by jnm2** [comment]
Things that would be good to group, especially for packages whose name has changed:

---

https://www.nuget.org/packages/NUnit.Runners/
https://www.nuget.org/packages/NUnit.ConsoleRunner/
https://www.nuget.org/packages/NUnit.Console/

---

https://www.nuget.org/packages/NUnitLite/
https://www.nuget.org/packages/NUnitLite.SL50/
https://www.nuget.org/packages/NUnitLiteCF/

---

Potentially all NUnit.* downloads for a total count.

---
https://www.nuget.org/packages/AsyncBridge/
https://www.nuget.org/packages/AsyncBridge.Net35/
https://www.nuget.org/packages/AsyncBridge.Portable/

**Comment by Giorgi** [comment]
Can we have an option to show the nuget package in the badge ? This way we could at least add different badges and it would be easy to identify which one is which

**Comment by paulmelnikow** [comment]
Yup, you can do that with the query string! e.g.

https://img.shields.io/nuget/dt/Microsoft.AspNet.Mvc.svg?label=aspnet.mvc%20downloads

**Comment by paulmelnikow** [comment]
I think we are not going to provide this because it requires too much bandwidth and time for a single badge render. However we're working on an endpoint badge #2473 which will make it easy to write your own Runkit endpoint to perform the logic, and then the badge can point to that.
