### ISSUE TITLE
Reduce duplication in badge regex/url patterns

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2050]
Can we use something like [url-pattern](https://github.com/snd/url-pattern) or [path-to-regexp](https://github.com/pillarjs/path-to-regexp) to define routes in a nicer way so we don't have to define this twice?

relevant discussions:
https://github.com/badges/shields/pull/2042#discussion_r214523205
https://github.com/badges/shields/pull/1582#discussion_r176912366

**Comment by paulmelnikow** [comment]
I played with `path-to-regexp` a bit back in March. This is based on what I did then:

```js
const pathToRegexp = require('path-to-regexp')

const keys = []
const re = pathToRegexp('/appveyor/ci/:user/:repo/:branch?.:ext(png|gif)', keys, {
  delimiter: '.',
  strict: true,
  sensitive: true,
})

console.log(re)

const result = {}
re.exec('/appveyor/ci/foo/bar/baz.png').slice(1).forEach((match, i) => {
  result[keys[i].name] = match
})
console.log(result)
```

Output:

```
/^\/appveyor\/ci\/([^\/]+?)\/([^\/]+?)\/([^\/]+?)?\.(png|gif)$/
{ user: 'foo', repo: 'bar', branch: 'baz', ext: 'png' }
```

Cool stuff!

The `compile()` method would be useful in the frontend to build a badge URL from user input. I ran into some issues with that, IIRC. It'd be good to make sure that works before we settle on this library.

**Comment by paulmelnikow** [comment]
`compile()` seems to be working now!

```js
const toPath = pathToRegexp.compile('/appveyor/ci/:user/:repo/:branch?.:ext(png|gif)', {
  delimiter: '.',
  strict: true,
  sensitive: true,
})

console.log(toPath({ user: 'foo', repo: 'bar', branch: 'baz', ext: 'png' }))
```

What do you think? Should we move forward with this approach?

**Comment by paulmelnikow** [comment]
#2279 is about ready for merge!

The next step would be to reduce duplication in defining examples, and maybe do this with an eye toward #701 and #776.
