### ISSUE TITLE
Logo color not changing for service badges

### ISSUE THREAD

**Issue by TobiasRoeddiger** [badges/shields#2057]
Hello. I realized that for services I am able to add a logo but when I try to change the color, the parameter is not applied.

Examples: 
(1) [https://img.shields.io/cdnjs/v/jquery.svg?logo=apple&logoColor=green](https://img.shields.io/cdnjs/v/jquery.svg?logo=apple&logoColor=green)
(2) [https://img.shields.io/apm/l/vim-mode.svg?logo=apple&logoColor=red](https://img.shields.io/apm/l/vim-mode.svg?logo=apple&logoColor=red)

**Comment by chris48s** [comment]
Thanks for this report.

For info, if anyone is looking into this, it seems to be an issue only on badges which extend the new `BaseService` class. This does work as expected on badges which use the legacy architecture (extending `LegacyService`) e.g:

https://img.shields.io/travis/rust-lang/rust.svg?logo=apple&logoColor=red
![](https://img.shields.io/travis/rust-lang/rust.svg?logo=apple&logoColor=red)
