### ISSUE TITLE
Add more tests for base class overrides

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2060]
It would be great to have more tests for all of these overrides:

https://github.com/badges/shields/blob/a265cab3545ce1ff4a5966f46ac9651da03c9372/services/base.js#L240-L249

At the moment we only have 2:

https://github.com/badges/shields/blob/322f3ff3053c62a5b514e2ef3a71761da787c26f/services/base.spec.js#L278-L294

**Comment by calebcartwright** [comment]
Is this still up for grabs? If so I'll give it a try as it looks simple enough (famous last words :smile:)
