### ISSUE TITLE
Appveyor badge shows internal error if there are no builds

### ISSUE THREAD

**Issue by Tschrock** [badges/shields#2073]
When trying to get an Appveyor badge for a project that doesn't have any builds yet, shields generates an internal error:
![ss1536772059-5026](https://user-images.githubusercontent.com/2406499/45441442-07a99b80-b68d-11e8-8e34-d847a3a61ac7.png)

Glancing at the service file, it queries their JSON API and extracts the build status from the `build.status` property - however for projects that have no builds the `build` property does not exist.

**Comment by platan** [comment]
@Hi @Tschrock! Thanks for reporting this. Can you give an example of user/repo or alternatively a JSON response for ci and tests resource from Appveyor? Or would you like to fix this bug in Shields - we can guide you how to do this :-)?

**Comment by chris48s** [comment]
Marking as question until we've got an example call that throws this error

**Comment by Tschrock** [comment]
I've set up a test repo now, so here's some extra details:

Project: https://github.com/Tschrock/appveyor-shields-test
AppVeyor link (with no current builds): https://ci.appveyor.com/project/tschrock/appveyor-shields-test

Build shield:
https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test.svg
![AppVeyor CI](https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test.svg)

 Build + branch shield:
https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test/master.svg
![AppVeyor CI branch](https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test/master.svg)

Tests shield:
https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test.svg
![AppVeyor Tests](https://img.shields.io/appveyor/ci/tschrock/appveyor-shields-test.svg)

Tests + branch shield:
https://img.shields.io/appveyor/tests/tschrock/appveyor-shields-test/master.svg
![AppVeyor Tests branch](https://img.shields.io/appveyor/tests/tschrock/appveyor-shields-test/master.svg)

For reference, this is how AppVeyor's built-in badges behave:
https://ci.appveyor.com/api/projects/status/x822ux3fgu8k4552?svg=true
![Build status](https://ci.appveyor.com/api/projects/status/x822ux3fgu8k4552?svg=true)
https://ci.appveyor.com/api/projects/status/x822ux3fgu8k4552/branch/master?svg=true
![master branch status](https://ci.appveyor.com/api/projects/status/x822ux3fgu8k4552/branch/master?svg=true)

And the JSON responses from their API:
<details><summary>Click to expand</summary>

https://ci.appveyor.com/api/projects/tschrock/appveyor-shields-test
```json
{
    "project": {
        "projectId": 492227,
        "accountId": 39236,
        "accountName": "Tschrock",
        "builds": [],
        "name": "appveyor-shields-test",
        "slug": "appveyor-shields-test",
        "repositoryType": "gitHub",
        "repositoryScm": "git",
        "repositoryName": "Tschrock/appveyor-shields-test",
        "repositoryBranch": "master",
        "isPrivate": false,
        "skipBranchesWithoutAppveyorYml": false,
        "enableSecureVariablesInPullRequests": false,
        "enableSecureVariablesInPullRequestsFromSameRepo": false,
        "enableDeploymentInPullRequests": false,
        "saveBuildCacheInPullRequests": false,
        "rollingBuilds": false,
        "rollingBuildsDoNotCancelRunningBuilds": false,
        "rollingBuildsOnlyForPullRequests": false,
        "alwaysBuildClosedPullRequests": false,
        "tags": "",
        "nuGetFeed": {
            "id": "appveyor-shields-test-s8c2ul5u0aru",
            "name": "Project appveyor-shields-test",
            "accountId": 39236,
            "projectId": 492227,
            "isPrivateProject": false,
            "publishingEnabled": false,
            "accountTimeZoneId": "Eastern Standard Time",
            "created": "2018-09-14T07:10:18.8624358+00:00"
        },
        "created": "2018-09-14T07:10:17.4092543+00:00"
    }
}
```

https://ci.appveyor.com/api/projects/tschrock/appveyor-shields-test/branch/master 
```json
{
    "message": "Build not found or access denied."
}
```

</details>
<br>

It looks like the api can't tell if a branch exists without a build, so I don't think there's any way to make the + branch options work for that case.

**Comment by chris48s** [comment]
Thanks for the additional info on this. :+1: We should at least improve the error handling in the case where there are no builds and no branch is specified.
