### ISSUE TITLE
Deprecate libscore

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2077]
Calls to the libscore API have been systematically failing in the daily builds for some time. e.g: http://api.libscore.com/v1/libraries/jQuery

It seems this service has been unmaintained for some time:
https://github.com/julianshapiro/libscore/issues/13

Shall we deprecate it? The fact that nobody has noticed it has stopped working is probably a sign we can drop it.. :)

**Comment by PyvesB** [comment]
I agree, we should probably deprecate it. 😉

**Comment by RedSparr0w** [comment]
👍
