### ISSUE TITLE
F-Droid badge not working?

### ISSUE THREAD

**Issue by Catfriend1** [badges/shields#2083]
Hi,
I'm trying to add a badge for my github project published on f-droid.
URL is: https://img.shields.io/f-droid/v/com.github.catfriend1.syncthingandroid.svg
So far I'm just seeing "app not found", but that's not true.
See here, it's on the repository:
https://f-droid.org/packages/com.github.catfriend1.syncthingandroid/
Please help me on this.
Thanks in advance
Catfriend1

**Comment by PyvesB** [comment]
Hello @Catfriend1,

Our current implementation uses _.txt_ metadata files (see [this code line](https://github.com/badges/shields/blob/ee2ce3747f57a3b04cb49f472233a9d419df3c55/services/f-droid/f-droid.service.js#L10)). Unfortunately your app seems to be one of the rare ones having a _.yml_ metadata file, therefore the badge is not working properly.

Pinging @niccokunzmann as he may be able to assist you further or give us some additional information. 😉 

Cheers,

Pyves

**Comment by niccokunzmann** [comment]
@Catfriend1 I should be easy to add the badge for the .yml files, too. yml can be converted to JSON and from there, we can get all the necessary information.

This line constructs the URL:
https://github.com/badges/shields/blob/master/services/f-droid/f-droid.service.js#L11
```
const url = `https://gitlab.com/fdroid/fdroiddata/raw/master/metadata/${appId}.txt`
```
You can see what to change...

These lines parse the URL:

      // we assume the layout as provided here:
      // https://gitlab.com/fdroid/fdroiddata/raw/master/metadata/axp.tool.apkextractor.txt
      const positionOfCurrentVersionAtEndOfTheFile = metadata.lastIndexOf(
        'Current Version:'
      ) // credits: https://stackoverflow.com/a/11134049
      const lastVersion = metadata.substring(
        positionOfCurrentVersionAtEndOfTheFile
      )
      const match = lastVersion.match(/^Current Version:\s*(.*?)\s*$/m)


I see two ways to go forward which I ask @PyvesB to give input about:

1. Query .txt and if not present, query .yml - this would leave the badge svg url intact
2. create one badge for txt and one for .yml

**Comment by Catfriend1** [comment]
Thanks @niccokunzmann  for your suggestion, looks good to me. I hope it can get implemented.

**Comment by niccokunzmann** [comment]
By the way: We have the tutorial in the docs folder on setup and
implementation of a badge. If you find anything you like to change
there, you are welcome to contribute. It is quite new.

**Comment by niccokunzmann** [comment]
I voiced the concern here: https://gitlab.com/fdroid/fdroiddata/issues/1330#note_97907652

**Comment by Catfriend1** [comment]
Honestly

**Comment by vxcamiloxv** [comment]
the best will be an [API](https://gitlab.com/fdroid/fdroiddata/issues/1449) from F-droid, but for now, a query in the option https://github.com/badges/shields/pull/2377, the migration to .yml for all apps is far away because is a big migration and can have side effects

**Comment by Catfriend1** [comment]
Thanks, it works now like expected:-)

**Comment by ghost** [comment]
please delete issue
