### ISSUE TITLE
Stuck in infinite redirect

### ISSUE THREAD

**Issue by bsoyka** [badges/shields#2109]
When visiting the site, I get stuck in an infinite redirect between `http://shields.io` and `http://shields.io/#`.

**Comment by agboom** [comment]
Are you hosting the server yourself or does this occur on the official Shields.io website? I don't experience this on shields.io.

An infinite redirect may indicate that the `REDIRECT_URI` or `INFOSITE` variable is set to the same url as the `BASE_URI`.

**Comment by chris48s** [comment]
I also can't reproduce this. If its on shields.io can you let us know what browser you're seeing this behaviour in.

**Comment by bsoyka** [comment]
It appears I can no longer reproduce the issue, and so I am closing this issue.
