### ISSUE TITLE
Steam workshop item stats to shield

### ISSUE THREAD

**Issue by Jaxe-Dev** [badges/shields#2121]
Any chance for getting Steam workshop item subscribers and other info on a shield? That info I believe can be freely retrieved so I assume it could be used for a shield

**Comment by chris48s** [comment]
When you say "can be freely retrieved", is there an API that this can be fetched from. That will help is anyone is interested in contributing this

**Comment by TagnumElite** [comment]
There is an API documented [here](https://partner.steamgames.com/doc/webapi/ISteamRemoteStorage)!

The important calls are:
1. `GetCollectionDetails`
2. `GetPublishedFileDetails`

The rest all require API keys and are not useful in this case.

Example `GetPublishedFileDetails`
```curl
curl -i -X POST \
   -H "Content-Type:application/x-www-form-urlencoded" \
   -d "itemcount=1" \
   -d "publishedfileids[0]=1489377853" \
 'https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/?format=json'
```

Example `GetCollectionDetails`
```sh
curl -i -X POST \
   -H "Content-Type:application/x-www-form-urlencoded" \
   -d "collectioncount=2" \
   -d "publishedfileids[0]=180077636" \
   -d "publishedfileids[1]=116572450" \
 'https://api.steampowered.com/ISteamRemoteStorage/GetCollectionDetails/v1/?format=json'
```
