### ISSUE TITLE
remove use of componentWillReceiveProps()

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2122]
The following lifecycle method are deprecated in react 16.3+

* `componentWillMount`
* `componentWillReceiveProps`
* `componentWillUpdate`

and will be removed in 17: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Fortunately we're not leaning too heavily on them. We have a single use of `componentWillReceiveProps()` which we will need to remove:

https://github.com/badges/shields/blob/04290e890bcbb27264a69f6693fa27ec4cb69359/frontend/components/markup-modal.js#L34-L54

**Comment by piekar294** [comment]
Hi, i would like to fix it :)
