### ISSUE TITLE
Badge request: Visual Studio App Center

### ISSUE THREAD

**Issue by ghost** [badges/shields#2127]
It would be awesome to have shields support for Visual Studio App Center build badges. Notably because they don't support custom labels at this time like VSTS builds. I don't believe you would be able to have separate badges for builds/distributions since there doesn't appear to be a distribution badge available currently. However, builds in App Center can be set to distribute too so arguably a user could have both included into one badge if their build is configured for that.

I did some poking around yesterday, and I'm not sure it's entirely possible to fulfill this request since they don't have an API for pulling the information. Maybe someone could reverse engineer their badge URL to make it work, but that's a bit beyond my understanding of the project.

App Center API documentation:
https://openapi.appcenter.ms/#/

Example of their badge URL:
https://build.appcenter.ms/v0.1/apps/d3124a04-aa78-4963-8489-20e54dc01ba8/branches/DEV/badge

I saw some progress on Hockey App, which App Center is the successor of I believe, but I don't think that code would work for App Center.

**Comment by PyvesB** [comment]
Hello @DougMurphyABA, thank you for your suggestion. Would you like to have a go at implementing these new badges? We've got a [nice tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to help you out. 😉

**Comment by DougMurphyABA** [comment]
Hello @PyvesB. I thought about it, but I don't really have the available free time to work on it. Hopefully someone else will be able. :)

**Comment by Prouser123** [comment]
Slightly late to the party here but I've had a look at the API but if we want to use it the end-user will have to specify a (hopefully read-only) API key from a user with access to their app.

**Comment by Prouser123** [comment]
And FYI I have started work on this once more, I hope to send a PR soon :)
