### ISSUE TITLE
Infinite Redirect in Edge Browser

### ISSUE THREAD

**Issue by paolobarbolini** [badges/shields#2164]
Are you experiencing this issue on shields.io or your own instance?
 - [x] shields.io
 - [ ] My instance

**Browser Info**:
Microsoft Edge 41.16299.699.0
Microsoft EdgeHTML 16.16299

:beetle: **Description**:
* Visit shields.io in Edge browser
* Click on an example, like _Chat_ (it doesn't happen with all examples, so trying the test with different ones might be necessary)
* Press the back button
* You will be stuck in a infinite redirect between https://shields.io/ and https://shields.io/#/ and the only option will be to kill the process.

Might be related to #2109

**Comment by chris48s** [comment]
Thanks for reporting this with steps to reproduce. I've just tried this on a windows machine and I see the same thing in Edge. No idea what is causing it though :thinking:

**Comment by paulmelnikow** [comment]
Pretty sure this will have been fixed by #2906 😄

**Comment by calebcartwright** [comment]
I just tried to reproduce in Edge, with every category, and was unable to reproduce so I'm thinking it was indeed addressed by #2906
