### ISSUE TITLE
Add the ability to create badges without a status

### ISSUE THREAD

**Issue by lukeeey** [badges/shields#2176]
It may be useful to have badges with only one word on them and one solid colour across the entire badge.

**Comment by chris48s** [comment]
You can already do this. For example:

https://img.shields.io/badge/all%20one%20color-red.svg
![](https://img.shields.io/badge/all%20one%20color-red.svg)

**Comment by lukeeey** [comment]
Oh that's cool it's not obvious on the site

**Comment by platan** [comment]
So "subject" is optional. Maybe we can indicate it in the static badge form?
![obraz](https://user-images.githubusercontent.com/1526000/46921445-9b0f1d00-cffb-11e8-83da-5588a8e34c09.png)
