### ISSUE TITLE
http://shields.io/#your-badge links to an empty page

### ISSUE THREAD

**Issue by platan** [badges/shields#2180]
Are you experiencing this issue on shields.io or your own instance?
 - [x] shields.io
 - [ ] My instance

:beetle: **Description**
The link "Make your own badges!" http://shields.io/#your-badge from https://github.com/badges/shields#examples links to an empty page.

**Comment by chris48s** [comment]
There's some detail on this here: https://github.com/badges/shields/issues/1954#issuecomment-415138623

**Comment by paulmelnikow** [comment]
Let's track this in #1954.
