### ISSUE TITLE
file size badge show wrong file size

### ISSUE THREAD

**Issue by BenjaminHoegh** [badges/shields#2210]
file size badge show wrong file size, on my computer and on GitHub my file is 16.1kb but when using shields.io badges to show the size, it show it is 17.1kb.

**Comment by chris48s** [comment]
Can you post a link to the badge you're having problems with?

**Comment by BenjaminHoegh** [comment]
> Can you post a link to the badge you're having problems with?

https://img.shields.io/github/size/benjaminhoegh/chameleon/build/chameleon-mini.css.svg

**Comment by chris48s** [comment]
That URL is saying "repo or file not found". Are you sure that's right?

Either way, there's an explanation of how we get the size of a GH repo in this issue https://github.com/badges/shields/issues/2153 - basically we'll be calling https://api.github.com/repos/{your-user-name}/{your-repo-name}/languages and adding up the numbers in there.

**Comment by BenjaminHoegh** [comment]
> That URL is saying "repo or file not found". Are you sure that's right?
> 
> Either way, there's an explanation of how we get the size of a GH repo in this issue #2153 - basically we'll be calling [https://api.github.com/repos/{your-user-name}/{your-repo-name}/languages](https://api.github.com/repos/%7Byour-user-name%7D/%7Byour-repo-name%7D/languages) and adding up the numbers in there.

Yes sorry the repo is temporary private as I'm working on setting the last settings up

**Comment by paulmelnikow** [comment]
If you'd like us to look into this again when the repo is published, let us know!
