### ISSUE TITLE
Badge Request: npm audit

### ISSUE THREAD

**Issue by shellscape** [badges/shields#2218]
:clipboard: **Description**

Since the deprecation/decomissioning of NSP, the badges for the service have stopped functioning (and rightly so). `npm audit` has become the default security check service, but there are no badges to indicate status.

I would like to propose a pass/fail state badge for the result of `npm audit`.

:link: **Data**

https://docs.npmjs.com/getting-started/running-a-security-audit
https://docs.npmjs.com/cli/audit

I've been unable to track down an API endpoint for this. `audit` seems to be available via the node package (thought that's generally frowned upon). Alternatively, `execa` or the like could be used to execute the npm binary and the badge could be generated from its process exit code.

**Comment by chris48s** [comment]
This would be a helpful badge, but checking out someone else's repo, running `npm audit` and reporting the result on an ad-hoc basis would be impossible for us to implement for performance reasons. In order to be able to report this we would need to be able to pull pre-computed data from somewhere in a performant way.

**Comment by shellscape** [comment]
@chris48s ah interesting. so ideally we'd have to hook into some kind of CI service that ran that automatically for builds?

**Comment by chris48s** [comment]
Yeah, it may be that there is a 3rd party service you could hook into. For example I think https://snyk.io/ does something like this (see https://snyk.io/docs/snyk-for-nodejs ) so you might be able to do a vulnerable dependencies yes/no badge for projects that use that service.

I don't think we would be able to do it for any arbitrary NPM package unless that data were exposed by the NPM registry itself.

**Comment by paulmelnikow** [comment]
We've got Snyk badges now: #2566.

Going further requires help from npm, so going to close this as needing upstream help.
