### ISSUE TITLE
Not all logos from simple-icons will work?

### ISSUE THREAD

**Issue by Sopor-** [badges/shields#2223]
It is possible to use logos from different projects and even from [simple-icons](https://simpleicons.org). I have tested a lot of them on simple-icons and they work, but not [Lua](https://img.shields.io/badge/style-flat-green.svg?logo=lua) and that is the icon i want to use. I noticed that `SparkFun` is not working either.
Shouldn't all of them work?

**Comment by RedSparr0w** [comment]
It looks like any icons added after `v1.9.7` are not showing on shields badges.
Which is strange as we should currently be using the latest `simple-icons` version (`v1.9.9`) in production:
[![](https://img.shields.io/github/commit-status/badges/shields/gh-pages/59fba5d173652bed9cb6d4e2d68951743b4e47a7.svg?label=deploy%20status)](https://github.com/badges/shields/commit/59fba5d173652bed9cb6d4e2d68951743b4e47a7)

@paulmelnikow Do you think maybe the npm packages weren't updated in the latest deploy?

**Comment by paulmelnikow** [comment]
It runs npm install every time, though it doesn’t respect package-lock. This is frustrating, of course, because locking deps in production is the whole point of using package-lock on an application.

Is simple-icons bumped in package.json?

**Comment by paulmelnikow** [comment]
Ref: #1988
