### ISSUE TITLE
GitHub Releases Still Very Temperamental

### ISSUE THREAD

**Issue by GrahamCampbell** [badges/shields#226]
Every other time I look at my readmes, it's always the github releases badges that are broken. I'd prefer them to return a badge, then have github's cdn timeout waiting for a response that isn't coming.

**Comment by dwijnand** [comment]
Not seeing it as fixed :( https://img.shields.io/github/release/GrahamCampbell/Bootstrap-CMS.svg

**Comment by espadrine** [comment]
@dwijnand To be fair, this isn't our fault this time:

```bash
curl 'https://api.github.com/repos/GrahamCampbell/Bootstrap-CMS/releases'
```

I have a feeling that <https://img.shields.io/github/release/BootstrapCMS/CMS.svg> will work better.

**Comment by dwijnand** [comment]
Ah I see, the "releases" tab in GitHub is best-effort falling back on tags. Thanks.

**Comment by GrahamCampbell** [comment]
@dwijnand I have moved my repository to an organisation since. That's why this old badge isn't working...

**Comment by gocanto** [comment]
@GrahamCampbell hey, what did u do to have them working?

**Comment by espadrine** [comment]
There are still occasional hiccups related to https://github.com/badges/shields/issues/529.
