### ISSUE TITLE
LeanPub Badges

### ISSUE THREAD

**Issue by bkimminich** [badges/shields#2270]
:clipboard: **Description**
Badges for [LeanPub](https://leanpub.com) books
- [ ] "pages | 226" (= `page_count` of Book Summary Information `json` response)
- [ ] "readers | 2691" (= `total_copies_sold` of Book Summary Information `json` response)
- [ ] "revenue | $ 985.05" (= `total_revenue` of Book Summary Information `json` response)

* All above badges should by default link to the `url` of their Book Summary Information `json`

:link: **Data**
* API Documentation: https://leanpub.com/help/api
* Book Summary Information: `https://leanpub.com/<book>.json` for example: https://leanpub.com/juice-shop.json (no API Key required)

**Comment by PyvesB** [comment]
Thank you for your suggestion @bkimminich ! You you like to have a go at implementing these new badges? We have a [nice tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that will help you get started. 😉

**Comment by calebcartwright** [comment]
Is anyone working on this yet? If not I'll give it a whirl

**Comment by paulmelnikow** [comment]
Go for it!

**Comment by calebcartwright** [comment]
FYI revenue (`total_revenue`) is only available via API when providing the book author's API Key, which means that particular badge would only be available via a self-hosted Shields server (at least based on my understanding).

Similarly for the page count field, there's a slight difference between what is available publicly/anonymously (`page_count_published`) vs. privately for the book author, see the below note taken from the linked API docs that defines the difference between the two (private/book author can see page counts from previewed version):

```
page_count_published is the page count of the latest published version. page_count is the page count of the latest previewed or published version. 
```

I can add badges for total copies sold (via `total_copies_sold`) and page count (via `page_count_published` and if there's value/desire for `total_revenue` then I can add that for self-hosted instances.

However, I'm not entirely sure if/how to differentiate `page_count` vs. `page_count_published` for self-hosted shields servers though (for example should we always use `page_count_published`, or should self-hosted always use `page_count` instead, or should those be exposed as different badges, etc.) 

Thoughts?

**Comment by bkimminich** [comment]
Hi @calebcartwright! All mentioned fields were publicly visible when I opened this ticket, because I'm sure I never actually provided my API key. I guess the published pages and sold copies are perfectly fine. No need for more complicated private information on my end at least.

**Comment by calebcartwright** [comment]
@bkimminich you are the author of the `juice-shop` book though correct? I'd venture to say you might have already been authenticated with LeanPub so when you made the API call you were recognized as the author (even though you didn't _explicitly_ provide the API key) 

I've already added support for self-hosted Shields instances to be able to render the `revenue` badge but  based on the LeanPub API docs (and what I'm seeing in API responses) `revenue` won't be available outside self-hosted instances
