### ISSUE TITLE
migrating from gh-badges to 1.3.0 to 2.0.0

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2297]
[gh-badges v2.0.0](https://www.npmjs.com/package/gh-badges/v/2.0.0) declares a new public interface which is synchronous. If your version 1.3.0 looked like this:

```js
const badge = require('gh-badges')

const format = {
  text: ['build', 'passed'],
  colorscheme: 'green',
  template: 'flat',
}

badge.loadFont('/path/to/Verdana.ttf', err => {
  badge(format, (svg, err) => {
    // svg is a string containing your badge
  })})
```

To upgrade to version 2.0.0, refactor you code to:

```js
const { BadgeFactory } = require('gh-badges')

const bf = new BadgeFactory({ fontPath: '/path/to/Verdana.ttf' })

const format = {
  text: ['build', 'passed'],
  colorscheme: 'green',
  template: 'flat',
}

const svg = bf.create(format)
```

**Comment by chris48s** [comment]
I suspect some people who haven't thought about this package for some time may appear seeking help upgrading. Lets leave this open here for a bit ^^

**Comment by ctaepper** [comment]
@chris48s or even better: put it in the README please :)

**Comment by paulmelnikow** [comment]
He's added it to the changelog in this PR: https://github.com/badges/shields/pull/2300/files#diff-15aafd020967f222d8ddfcee3457317f.

**Comment by ctaepper** [comment]
Ok so this changelog is very invisible to the regular github user. I would expect changes either to be listed in the releases or in a changelog file which I would expect in the project root.

Not judging this projects structure, just stating what I would expect :)

**Comment by paulmelnikow** [comment]
Appreciate your perspective. It's a tricky balance to provide what's helpful without unduly confusing people.

For what it's worth, the main thing going on in this repo is the badge service, and most people who come here don't know or care that we publish an npm package. I feel including that entire code block is too much detail, though having some kind of link to upgrade instructions or a changelog seems worthwhile.

Do you want to take a look at the root readme in that PR and comment with some suggested edits?

**Comment by stclairdaniel** [comment]
Maybe a dumb question, but before my code was like this:
``` 
const badge = require("gh-badges"),
badge(
        {
          text: ["storybook", "up to date"],
          colorscheme: "orange",
          template: "flat"
        },
        function(svg, err) {
          fs.writeFileSync(folder + outputFile, svg);
        }
      );
```

I don't use a `fontPath` but I get this error now:
```  constructor({ fontPath, fallbackFontPath, precomputeWidths = false }) {
                ^

TypeError: Cannot destructure property `fontPath` of 'undefined' or 'null'.```

I don't see anything about `BadgeFactory` documented anywhere - am I looking in the wrong place?

**Comment by ctaepper** [comment]
@paulmelnikow I'm sorry, I didn't realize, that this is a ongoing PR. There is already a [link in the root README](https://github.com/badges/shields/pull/2300/files#diff-04c6e90faac2675aa89e2176d2eec7d8R47) to the changelog file. From my point of view this should be sufficient!

And yes, as you said, most people just use the service. In my case, we use the npm package in order to run our custom badge service which uses our custom tokens to display badges from private services. Our CI failed with gh-badges v2 and I had a hard time tracking down the changelog. Looking at the github issues tab was my last resort :)

**Comment by paulmelnikow** [comment]
Sorry you had a hard time finding the information; glad you found it!

It's cool to hear from people who use the package! I'd be curious to have your input about improvements going forward. One question, out of curiosity: do you use the raster badges (.gif, .png) or only SVG?

**Comment by ctaepper** [comment]
We use SVG only.

I'm also not sure if we will update to v2... v1 is running flawless and we will probably not touch the system until we need to implement new private services to generate badges from.

**Comment by chris48s** [comment]
now #2300 is merged and we've got this linked somewhere a bit more obvious I'm going to close this
