### ISSUE TITLE
CI doesn't always run the service tests

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2314]
CircleCI builds often don't correctly detect that they are on a PR. Currently the only way to know whether or not the service tests ran is to inspect the build logs.

That's because there is no way to reliably distinguish branch and PR builds in CircleCI.

Somtimes the cause is having CircleCI set up on the fork where the PR originates, triggering a branch build ahead of time, though we've also had cases where this happened on forks _without_ CircleCI. Plus Dependabot branches are never on a fork.

As it turns out, there is a workaround [suggested by Danger](https://danger.systems/js/guides/getting_started.html): configure CircleCI to run _only on PRs_.

That would necessitate either:

1. A separate CI service – or simply a separate repo – to run the daily tests
2. A PR-triggered bot that triggers the service-test builds on Circle programmatically
3. A cron-triggered bot that triggers the nightly Circle build programmatically

I experimented in #1936 with a radically different alternative, which is to specify the affected services in the commit history. This has an advantage of making development a bit easier, but it didn't really pan out. Maybe that work could be harvested for a dev-only tool.

**Comment by paulmelnikow** [comment]
I went ahead and set up [another repo](https://github.com/badges/daily-tests) with Circle, and got [Coveralls](https://coveralls.io/builds/20137843) working as well. (Thanks for the reminder about that!)

The reason I chose Circle is because #979 was a long-standing issue solved by Circle, and I didn't want to solve _that_ problem again.

I turned on "Only build PRs" for the main repo. I _think_ the service test runner should start working reliably now, without other changes. Though let's see!

**Comment by paulmelnikow** [comment]
This is looking good. Coveralls is looking nice, too!

**Comment by chris48s** [comment]
Just thinking about this is slightly more detail, was the `CI_PULL_REQUEST` variable the thing that we couldn't rely on?

If so, now that we only run on PR, should we also remove the checks on that e.g:

https://github.com/badges/shields/blob/b922fca982fbd19f90f5d034a8bb9c506c650696/.circleci/config.yml#L176
