### ISSUE TITLE
Rewrite GitHub services

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2320]
In #2253 I got the ball rolling with rewriting the GitHub services. The changes to the service in that PR are a good model for rewriting any of the remaining services.

You can ignore the changes to the base services and to the GithubAuthService.

~~There have been some small enhancements to BaseService since then which should also be taken into account: #2278 #2279 (and #2308 once it's merged)~~

If folks are comfortable taking any of the remaining `LegacyService`s in `services/github/` and rewriting them along the lines of #2253, please give it a go!

~~At the moment there's also a pull request open (#2309) to move the rest of the GitHub badge examples into `services/github/`, though that hopefully will be merged soon.~~

Ref #1358

**Comment by paulmelnikow** [comment]
If anyone is interested in helping with this, we've now got some tips!

https://github.com/badges/shields/blob/master/doc/rewriting-services.md

**Comment by paulmelnikow** [comment]
Seems like we may as well close this out in favor of #2863. Is there any more info we should add there related to the GitHub services? Maybe pointers to some which are done?

**Comment by calebcartwright** [comment]
Once I split out the GH services in our spreadsheet, I can add the remaining list of GH services needing refactor in here for reference, and links to the classes that have already been refactored. 

Given the number of GH services and some of the complexity I think it may also make sense to add a pointer over to here from #2863 

Thoughts?

**Comment by calebcartwright** [comment]
Sure, will do

**Comment by calebcartwright** [comment]
I've finished splitting out the GH services in the spreadsheet. On second thought I don't want to add them inline here as it will inevitably slide out of date, but I'll pick out one to refactor and update this accordingly

**Comment by paulmelnikow** [comment]
These have gotten easier!

#3095 #3098 #3099

**Comment by paulmelnikow** [comment]
Just three of these left! Let's track at https://github.com/badges/shields/issues/2863#issuecomment-482874488.
