### ISSUE TITLE
powershellgallery: returns Invalid Response Data when package with highest version is unlisted

### ISSUE THREAD

**Issue by thedavecarroll** [badges/shields#2331]
Are you experiencing an issue with...
 - [X] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
The version and download count badge shows **invalid response data** for package [PoShGroupPolicy](https://www.powershellgallery.com/packages/PoShGroupPolicy).

The latest version (1.0) status is *Unlisted*, while the current version (0.3) is *Listed*. I actually published the 1.0 first and was not able to delete it.

![image](https://user-images.githubusercontent.com/37391437/48654000-dcb22f80-e9ce-11e8-8194-b0c86e36fdd7.png)

```console
curl -H "Accept: application/atom+xml,application/xml" "https://www.powershellgallery.com/api/v2/Packages()?%24filter=Id%20eq%20'PoShGroupPolicy'%20and%20IsLatestVersion%20eq%20true"
```

\
\
I suspect this to be a limited, perhaps even rare, scenario. I'm only raising the issue for general awareness and do not expect any work to be done, unless the maintainers feels it's warranted.
\
\
Also, thank you for closing #2078.
\
\
:link: **Link to the badge**
[https://img.shields.io/powershellgallery/dt/PoShGroupPolicy.svg?style=for-the-badge](https://img.shields.io/powershellgallery/dt/PoShGroupPolicy.svg?style=for-the-badge)

[https://img.shields.io/powershellgallery/v/PoShGroupPolicy.svg?style=for-the-badge](https://img.shields.io/powershellgallery/v/PoShGroupPolicy.svg?style=for-the-badge)

**Comment by paulmelnikow** [comment]
Hi, thanks for the detailed report!

Here's the output of that request (which is still failing):

```json
{
  "feed": {
    "id": "http://schemas.datacontract.org/2004/07/",
    "title": "",
    "updated": "2018-11-17T02:31:51Z",
    "link": "",
    "entry": {
      "id": "https://www.powershellgallery.com/api/v2/Packages(Id='PoShGroupPolicy',Version='0.3.0')",
      "category": "",
      "link": [
        "",
        ""
      ],
      "title": "PoShGroupPolicy",
      "updated": "2018-11-12T12:00:39Z",
      "author": {
        "name": "Dave Carroll"
      },
      "content": "",
      "properties": {
        "Id": "PoShGroupPolicy",
        "Version": 0.3,
        "NormalizedVersion": "0.3.0",
        "Authors": "Dave Carroll",
        "Copyright": "(c) 2018 Dave Carroll. All rights reserved.",
        "Created": "2018-03-24T04:18:50.567",
        "Dependencies": "",
        "Description": "PowerShell module to assist with Group Policy",
        "DownloadCount": 136,
        "GalleryDetailsUrl": "https://www.powershellgallery.com/packages/PoShGroupPolicy/0.3.0",
        "IconUrl": "",
        "IsLatestVersion": true,
        "IsAbsoluteLatestVersion": true,
        "IsPrerelease": false,
        "Language": "",
        "LastUpdated": "2018-11-12T12:00:39.567",
        "Published": "2018-03-24T04:18:50.567",
        "PackageHash": "g2SYyk4/wfa3v0M4fyloM8Vi+lB2Awe5+bfzMGYjH4GCoNmn1VggyiW+CNbKkyHkCBcpKhMWjpelQpHEPzhUYw==",
        "PackageHashAlgorithm": "SHA512",
        "PackageSize": 11761,
        "ProjectUrl": "https://github.com/thedavecarroll/PoShGroupPolicy",
        "ReportAbuseUrl": "https://www.powershellgallery.com/packages/PoShGroupPolicy/0.3.0/ReportAbuse",
        "ReleaseNotes": "https://github.com/thedavecarroll/PoShGroupPolicy/blob/master/RelaseNotes.md",
        "RequireLicenseAcceptance": true,
        "Summary": "",
        "Tags": "PoshGroupPolicy GroupPolicy Group-Policy PowerShell GPO PSModule PSFunction_Get-GPSetting PSCommand_Get-GPSetting PSIncludes_Function",
        "Title": "",
        "VersionDownloadCount": 129,
        "MinClientVersion": "",
        "LastEdited": "",
        "LicenseUrl": "https://github.com/thedavecarroll/PoShGroupPolicy/blob/master/LICENSE",
        "LicenseNames": "",
        "LicenseReportUrl": "",
        "ItemType": "Module",
        "FileList": "PoShGroupPolicy.nuspec|LICENSE|PoShGroupPolicy.Format.ps1xml|PoShGroupPolicy.psd1|PoShGroupPolicy.psm1|README.md|ReleaseNotes.md|en-US\\about_PoShGroupPolicy.help.txt|Private\\Get-GPKnownFolderId.ps1|Public\\Get-GPSetting.ps1",
        "GUID": "fa6fcad4-9c3f-4258-8475-bbf11060b779",
        "PowerShellVersion": 3,
        "PowerShellHostVersion": "",
        "DotNetFrameworkVersion": "",
        "CLRVersion": "",
        "ProcessorArchitecture": "",
        "CompanyName": "Unknown",
        "Owners": "thedavecarroll"
      }
    }
  }
}
```

**Comment by PrzemyslawKlys** [comment]
Having a similar issue for one of my projects:

https://github.com/EvotecIT/Statusimo
https://www.powershellgallery.com/packages/Statusimo

Any way to get this fixed?

**Comment by paulmelnikow** [comment]
Just wanted to put out there that Shields is a community project, and that means if you're reading this, you can can help make this happen! 👐 We'd welcome anyone who would like to dig into this! Our maintainer team is happy to review code and answer questions (feel free to post in Discord, or right in this thread). We've worked hard to create a good developer experience for first-time contributors, and gotten many positive reports, including from some first-time JavaScript developers.

**Comment by PrzemyslawKlys** [comment]
@paulmelnikow I understand but without pointers I can't really help ;-) And even with pointers it seems to be JS mostly which I don't know :-) like at all.
