### ISSUE TITLE
Bintray download badge

### ISSUE THREAD

**Issue by aalmiray** [badges/shields#234]
Consider a badge for displaying downloadable versions from a Bintray repository. The API call is explained at https://bintray.com/docs/api/#_get_version

Proposed syntax:

    http://img.shields.io/bintray/version/joe/maven/artifact.svg  // latest
    http://img.shields.io/bintray/version/joe/maven/artifact/1.2.3.svg  // 1.2.3

Suggested syntax uses `version` in the path as Bintray might support download numbers via API calls in the future. If so that service could be added at a later stage.

**Comment by pathikrit** [comment]
+1

**Comment by hastebrot** [comment]
The link to the API documentation is 404'ed. New link is: https://bintray.com/docs/api/#_get_version

**Comment by espadrine** [comment]
@hastebrot Thanks!

The main issue remains rate-limiting. I don't know where to draw the line exactly, but 300 requests/day is very far below that line. GitHub's initial 1440 req/day was not enough at all, for instance.

**Comment by hastebrot** [comment]
And what about the caching machanism for requests and secret credentials for a dedicated account? Is this possible?

**Comment by hastebrot** [comment]
Ah, I see, we have `cache()` and `serverSecrets` in `server.js` for this.

**Comment by espadrine** [comment]
The cache fills up very fast, so uncommon requests get deleted just as fast.

**Comment by jhermann** [comment]
Quoting @jbaruch: “We can consider lifting the limits for a dedicated account or for a specific API. We've done the same for other services in the past.”

**Comment by hawkw** [comment]
+1

**Comment by keilw** [comment]
I'd say for those projects transparent enough to share them, download numbers either total or for the latest version over a period like last 30 days would be a cool badge, too ;-)

**Comment by adjohnson916** [comment]
+1

**Comment by espadrine** [comment]
Implemented by https://github.com/badges/shields/pull/517/files.
