### ISSUE TITLE
Improve handling of query params in examples

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2357]
In https://github.com/badges/shields/pull/2339#discussion_r234446985 @chris48s suggested a nice improvement to the way we handle query params in example URLs:

> pattern: `service/v/:package?branch=:branch`
> example: `service/v/mypackage?branch=master`

Constructing URLs with the colons requires a little bit of work. `queryString` will URL-encode the colons, so that substitution may have to be made after the fact. Or we can build the query string ourselves. (My least favorite kind of code!)

Also, we'll need to at least clarify the semantics of `query` in examples. Will the keys of the `query` object determine which querystring placeholders are included in the composed pattern?

Semi-related: `examples` use `query` while `route` uses `queryParams`. To avoid programmer errors we should pick one and make them the same.

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/
Closing this issue as it relates to the previous frontend
