### ISSUE TITLE
Azure DevOps coverage badge always returns 0 for JaCoCo coverage reports

### ISSUE THREAD

**Issue by mehmetseckin** [badges/shields#2370]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Azure DevOps coverage service does not calculate the coverage correctly if the coverage report format is `JaCoCo`.

The service only accepts the stats with label `Lines`, but JaCoCo XML format publishes the stats with the label `Line` as in [this example](https://dev.azure.com/azuredevops-powershell/azuredevops-powershell/_apis/test/codecoverage/?buildId=18&api-version=5.0-preview.1) (trimmed JSON for brevity):

```json
{
   "coverageData":[
      {
         "coverageStats":[
            {
               "label":"Line",
               "position":4,
               "total":86,
               "covered":35,
               "isDeltaAvailable":true,
               "delta":0.0
            },
```

:link: **Link to the badge**
The following badge should render `41%`, but it renders `0%` instead.
```
https://img.shields.io/azure-devops/coverage/azuredevops-powershell/azuredevops-powershell/1.svg
```
![Azure DevOps Coverage](https://img.shields.io/azure-devops/coverage/azuredevops-powershell/azuredevops-powershell/1.svg)

:bulb: **Possible Solution**
Please see #2369

**Comment by calebcartwright** [comment]
Good catch on this btw. I thought ADO homogenized the coverage metric labels across the different coverage formats but apparently not. 

I don't have any C#/MSTest code handy but it might also be worth checking to see if the coverage results generated by the Visual Studio Test task for that world uses something _other_ than `Line` or `Lines`
