### ISSUE TITLE
Joomla Badges Missing

### ISSUE THREAD

**Issue by chandanndeep** [badges/shields#2382]
Hello Team,

I see lots of badges in your this repositories but can't see the Joomla Bages. Am very thankful if you add the Joomla Badges also.

Thanks,
Chandan

**Comment by chris48s** [comment]
Can you provide a bit more info in case someone is interested in working on this

* What sort of information should this badge show?
* Where should the data come from?
  * Is there a public API?
  * Does the API requires an API key?
  * Link to the API documentation.

Cheers

**Comment by paulmelnikow** [comment]
Feel free to add some more information and we can reopen this!
