### ISSUE TITLE
Badge request: Lerna

### ISSUE THREAD

**Issue by amaurymartiny** [badges/shields#2413]
:clipboard: **Description**

- Which service is this badge? Lerna

- What sort of information should this badge show? `lerna | v1.2.3` or `lerna | independent`

:link: **Data**

- Is there a public API?

No need for public API, it's inside the `version` key in `lerna.json`,  in the root folder.

Example: https://github.com/babel/babel/blob/master/lerna.json

**Comment by chris48s** [comment]
If you're interested in adding it we welcome PRs from new contributors. We've got a tutorial on adding new badges that you can follow: https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by cowchimp** [comment]
@chris48s I'm thinking of submitting a PR for this.

I'm wondering what the best way to read the data from the `lerna.json` file is.
Are there any existing badge services I can be inspired from that don't read from any public registry or anything like that, but rather just need to read from a certain file in the source code?

Thanks.

**Comment by calebcartwright** [comment]
> I'm thinking of submitting a PR for this.

Awesome!

> Are there any existing badge services I can be inspired from that don't read from any public registry or anything like that, but rather just need to read from a certain file in the source code?

We do have a few services grabbing a json file from GitHub that should serve as a good reference. For example: https://github.com/badges/shields/blob/master/services/github/github-package-json.service.js

If you do take a look at this one, feel free to open an early draft PR if you have any questions, and/or ping us on this thread, and/or on Discord 😄

**Comment by pedrofracassi** [comment]
What would the `lerna.json` file look like for the badge to show `independent`?

**Comment by pedrofracassi** [comment]
Assign this one to me please?
