### ISSUE TITLE
Matrix chat badge

### ISSUE THREAD

**Issue by spacekitteh** [badges/shields#2419]
:clipboard: **Description**
Matrix is a chat system which is starting to become popular. It would be nice to have support for Matrix communities/rooms as badges.

:link: **Data**
Each Matrix server communicates via (I believe) JSON over HTTP, for both data and metadata. A room ID includes the server's address, so it's a straightforward matter of extracting it from the room ID and using the API. 

Protocol spec: https://matrix.org/docs/spec/

**Comment by fr1kin** [comment]
I've submitted [#2417](https://github.com/badges/shields/pull/2417) to implement this feature. I'll tag this issue in the thread.

**Comment by paulmelnikow** [comment]
Closed via #2417!
