### ISSUE TITLE
TUTORIAL.md: Replace Wercker with some public service API

### ISSUE THREAD

**Issue by techtonik** [badges/shields#2423]
:question: **Question**

Attempt to find out more info about Wercker leads to Oracle page about company acquisition. I think that's not as interesting and inspiring as working with some open API, such as Travis CI, GitLab or Travis. Would be nice to see some open source examples there.

**Comment by paulmelnikow** [comment]
It looks like wercker is only mentioned as an example of a service that has a single `.service.js` file. We could replace it with `readthedocs`, which has a single file and is likely to stay that way – and also a well known and free developer tool.

**Comment by techtonik** [comment]
Wercker is also the subject of testing tutorial - https://github.com/badges/shields/blob/master/doc/service-tests.md#tutorial

**Comment by paulmelnikow** [comment]
Ah, gotcha. That would be a lot of work to change, then.

**Comment by chris48s** [comment]
now more important: https://github.com/badges/shields/pull/8642
