### ISSUE TITLE
C# dependencies based on NuGet

### ISSUE THREAD

**Issue by rodchenkov** [badges/shields#2424]
:clipboard: **Description**
It will be nice to get status of dependencies like Libraries.io for GitHub for C# projects based on NuGet
- Which service is this badge for?
C# NuGet dependencies 
- What sort of information should this badge show?
"dependencies | 3 out of date" or "dependencies | up to date"

:link: **Data**
- Where can we get the data from?
https://libraries.io/api#project-dependencies
e.g.: https://libraries.io/api/NuGet/Aurochses.AspNetCore.Razor/latest/dependencies?api_key=e72d1cfe1e4083b0f23397231eab8b17

**Comment by paulmelnikow** [comment]
Hi, thanks for this suggestion!

We've been having terrible luck with the libraries.io API. It's extremely slow. We want to render badges in < 1 second. When we take longer than 3 seconds, GitHub will give up and show a broken image. I've been thinking about deprecating the libraries.io badge until we can find a better solution.

This information doesn't change all that often, so maybe we can put some kind of caching in front of libraries.io. That's been discussed in #1545.

Another option is reaching out to Libraries about adding a downstream cache. It would greatly improve their service. We use Cloudflare for that, which costs us nothing.

**Comment by paulmelnikow** [comment]
The librariesio API is running much faster now. Maybe they added a cache!

**Comment by rodchenkov** [comment]
Just found that we already have badge for nuget dependencies
It is 'Libraries,io for releases' under Dependencies group BUT looks like it has limitation.

If I use this:
https://libraries.io/api/nuget/EntityFramework?api_key=e72d1cfe1e4083b0f23397231eab8b17
https://img.shields.io/librariesio/release/nuget/EntityFramework.svg
all works fine

But when I use package with dot in name like: Newtonsoft.Json or Aurochses.Runtime than badge is not avaliable
https://img.shields.io/librariesio/release/nuget/Newtonsoft.Json.svg
but libraries.io show all as expected
https://libraries.io/api/nuget/Newtonsoft.Json?api_key=e72d1cfe1e4083b0f23397231eab8b17

Can you please check and help me?

**Comment by paulmelnikow** [comment]
Ah, thanks for sorting that out. I pushed a fix for that issue in #2434:

http://shields-staging-pr-2434.herokuapp.com/librariesio/release/nuget/Newtonsoft.Json.svg
![](http://shields-staging-pr-2434.herokuapp.com/librariesio/release/nuget/Newtonsoft.Json.svg)

**Comment by rodchenkov** [comment]
@paulmelnikow thank you! Waiting for release
