### ISSUE TITLE
New Project: inch-ci.org

### ISSUE THREAD

**Issue by justinkim** [badges/shields#245]
[Inch CI](http://inch-ci.org/) provides badges that show the level and quality of inline documentation for Ruby projects.

Here is an example of one of their badges: [![Inline docs](http://inch-ci.org/github/guard/guard.png?branch=master)](http://inch-ci.org/github/guard/guard)

They provide SVG and PNG badges for every repository, accessible at the top of [any project page](http://inch-ci.org/github/guard/guard).

I checked [shields.io](http://shields.io/) and did not find the Inch CI badge available. The contributing guidelines instructed me to open an issue, so here it is!

Thanks

**Comment by s3ththompson** [comment]
+1

**Comment by coderanger** [comment]
This might be hard to adapt to the shields format because the "value" is a gradient instead of text but I would love to see it too.

**Comment by amercier** [comment]
+1

**Comment by KapuzenSohn** [comment]
+1

**Comment by rrrene** [comment]
+1

To summarize: [Inch CI](https://inch-ci.org/) provides badges that show an assesment of your inline docs like this: [![Inline docs](http://inch-ci.org/github/rom-rb/rom-model.svg?branch=master)](http://inch-ci.org/github/rom-rb/rom-model)

Green, light-green, red and purple mean "Excellent", "Good", "Something seems wrong" and "Undocumented" parts of your code. Supported languages for the analysis are Ruby, Elixir & JavaScript.

I would very much support the effort to get a Shields integration of the ground, if there is any interest. A good starting point might be the available JSON data: 

https://inch-ci.org/github/rom-rb/rom-model.json

```
{
  "user_name": 'rom-rb',
  "repo_name": 'rom-model',
  "branch_name": 'master',
  "revision_sha1": '45998a91',
  "grade_shares": [0.5,0.167,0.167,0.167],
  "grade_map": {
    "A": 9,
    "B": 3,
    "C": 3,
    "U": 3
  }
}
```

and the SVG template I am currently using to produce "shields style" badges: https://github.com/rrrene/inch-badge/blob/master/assets/badge-shields.svg.erb

**Comment by espadrine** [comment]
It is a very interesting service!

However, it doesn't fit well in shields.io's current design. Plus, adding it to shields.io wouldn't provide additional functionality.

**Comment by DanielRamosAcosta** [comment]
+1

**Comment by paulmelnikow** [comment]
We could support a percentage documented badge if there were a way to get this information from an API.

The Inch badges themselves are really lovely! However I don't see a benefit from integrating them into Shields directly, nor an easy way to do it.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
