### ISSUE TITLE
Token pool test occasionally fails because of timing

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2466]
See https://circleci.com/gh/badges/shields/27276. I can't remember if this test is using mock timers. If it's not, hopefully setting that up will fix it.

Ref: https://github.com/badges/shields/pull/2465#issuecomment-444776440

**Comment by calebcartwright** [comment]
Looks like it isn't using mock timers. I already need to update a different test, so I can also add mock timers to this test
