### ISSUE TITLE
Broken Wheelmap badges

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#2469]
The wheelmap badges seem to be broken. Even when trying with different identifiers, they systematically seem to return void:
![](https://img.shields.io/wheelmap/a/2790497168.svg)

We should fix this service and add some tests.

**Comment by paulmelnikow** [comment]
Wheelmap still exists. It would be good to locate new API documentation! 

cc @rubiii

**Comment by PyvesB** [comment]
The API documentation is [here](http://classic.wheelmap.org/en/api/docs). Unlike previously, an API key seems to be required for every single request (not great for testing!). I've signed up for an account, I'll have a dig around and see what I can come up with.

**Comment by paulmelnikow** [comment]
Ahh that's a little tricky, especially for local testing! For CI, we could drop a token into Circle config like we do for GitHub, and use a different one for production.
