### ISSUE TITLE
Support static preview with social style

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2479]
The social badges have typically included `?style=social`. However `staticPreview` returns `serviceData` which does not support the `style` parameter. This makes it impossible to render a static preview for the social badges.

e.g. 

https://github.com/badges/shields/blob/f8b0472b4c26a7bafcf4c91a527414054d5ac922/services/github/github-followers.service.js#L32-L36

This also came up in #2473 where I was adding an Endpoint badge, and thinking we should make it possible for a developer to make a badge which defaults to a particular style.

I'm not totally convinced we should do that. In some ways it violates a user's expectation, which is that Shields will always default to flat. Should we also let the developer specify `flat-square` or `for-the-badge`? At the same time, these are _custom_ badges, and it's useful to be able to include especially logos by default. Maybe it's okay, for custom badges.

**Comment by chris48s** [comment]
Given we've only got 6 social badges in the home page examples (out of some-hundred in total), I reckon static preview for social badges would be nice to have but its quite low priority.

**Comment by paulmelnikow** [comment]
It's true it's not so important to render it statically, though it would be nice to drop support for `exampleUrl` which adds complexity in BaseService and the frontend.
