### ISSUE TITLE
Path in modal should work with URL base

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2495]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Since deploying #2441 to production, the 'path' field expects the content _not_ to have a URL base set, but we use one everywhere else:

this doesn't work:

![screenshot at 2018-12-09 16-36-37](https://user-images.githubusercontent.com/6025893/49700099-35da4100-fbd2-11e8-8650-b16274a93d85.png)

you have to do this to get a preview to render:

![screenshot at 2018-12-09 16-37-10](https://user-images.githubusercontent.com/6025893/49700102-3ecb1280-fbd2-11e8-831b-f2e297c70f4b.png)

This was difficult to pick up on staging because there is no base set.

**Comment by paulmelnikow** [comment]
Ah, hmm. I mentioned this change in the PR. Local dev looks like production. I didn't realize staging looked so different.

To be honest, I feel like the long URLs everywhere have to go. They make the page look incredibly busy:

<img width="1169" alt="screen shot 2018-12-09 at 8 18 44 pm" src="https://user-images.githubusercontent.com/1487036/49705853-ab083f00-fbef-11e8-9662-aa9515e42963.png">

I suppose you copied and pasted the example URL into the Path box and expected it to render. Is that right?

If so, I wonder if this can be made clearer. I have an idea about a possible solution.

Reverting the behavior is a possibility too.

**Comment by paulmelnikow** [comment]
After discussing offline we decided to hold off on changing this given the changes in #2496 will wipe out this part of the workflow.
