### ISSUE TITLE
Remove third-party images from homepage

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2498]
Shields has a no-tracking promise. I interpret that to mean we should not load third-party images from https://shields.io/.

At some point OpenCollective images snuck in:

<img width="179" alt="screen shot 2018-12-09 at 10 16 04 pm" src="https://user-images.githubusercontent.com/1487036/49708967-135f1c80-fc00-11e8-9ebf-549194c19708.png">

I like having them there. Maybe we could replace them with Shields-rendered badges.

**Comment by chris48s** [comment]
Should be possible to re-implement these badges using their API: https://developer.opencollective.com/#/api/collectives

**Comment by mbrandau** [comment]
I'm gonna try and implement #808 to get this started.

**Comment by paulmelnikow** [comment]
@mbrandau Feel free to hit us up on #808 or on Discord if you have questions!

**Comment by paulmelnikow** [comment]
@mbrandau Want to tackle this next?

**Comment by mbrandau** [comment]
Sure!
