### ISSUE TITLE
Only seeing "invalid" test badge for Azure Devops Test Results badge url

### ISSUE THREAD

**Issue by JGCreator** [badges/shields#2502]
Are you experiencing an issue with...
 - [ x] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
I'm attempting to use the Azure Devops Test Results badge for a specific build definition on my organizations main project, but the badge that is returned after acquiring the documented necessary information I only see a gray badge that says "Tests"|"Invalid"
![image](https://user-images.githubusercontent.com/5280734/49759323-f3267080-fc86-11e8-90ee-2f16f1a829fe.png)

:link: **
https://img.shields.io/azure-devops/tests/:organization/:project/:definitionId.svg?compact_message
**

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
thanks @JGCreator.

Does the pipeline you're attempting to use for the badges reside in a [public](https://docs.microsoft.com/en-us/azure/devops/organizations/public/create-public-project?view=vsts&tabs=new-nav) Azure DevOps project? 

The main shields.io service can only provide badges for Public Azure DevOps projects, whereas a self-hosted Shields instance would be required to connect to private projects. 

Assuming you are working with a public project/pipeline, can you please provide the link to your pipeline and/or a screenshot of the test results view for your pipeline?

For example something like [this](https://dev.azure.com/swellaby/OpenSource/_build/results?buildId=1101&view=ms.vss-test-web.test-result-details)

![image](https://user-images.githubusercontent.com/13042488/49759840-68467580-fc88-11e8-8bb0-7aa811a45835.png)

**Comment by JGCreator** [comment]
It is in fact a private project, but how then would I be able to see an expected result from a different badge?
![image](https://user-images.githubusercontent.com/5280734/49760198-65985000-fc89-11e8-8e4f-82b5ee0cf8b6.png)

**Comment by calebcartwright** [comment]
The first badge looks like the native badge provided directly by Azure Pipelines (not by Shields). I cannot tell from your screenshot what the badge in the middle (`build | passing`) is pointed to, but Microsoft does make the build status available publicly, even for private projects. 

However, test results and code coverage from private projects are not available publicly.

**Comment by calebcartwright** [comment]
Just as something to consider @JGCreator, hosting your own shields instance is pretty easy (runnable via Docker).

I run my own shields instance at my day job where we have it connected to private projects/tools, including our private Azure DevOps projects. If you decide to go that route and have any questions (how to plug in your Azure DevOps PAT, etc.) let me know and I'd be happy to help!

**Comment by calebcartwright** [comment]
If you've never worked with Docker before at all then you may also find these guides helpful:

* https://docs.docker.com/install/#supported-platforms 
  * https://docs.docker.com/install/linux/docker-ce/ubuntu/
* https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04 
  * I haven't used DO in a while but I've found their documentation is usually pretty good, regardless of what platform you target

**Comment by robertoalfonso** [comment]
> Just as something to consider @JGCreator, hosting your own shields instance is pretty easy (runnable via Docker).
> 
> I run my own shields instance at my day job where we have it connected to private projects/tools, including our private Azure DevOps projects. If you decide to go that route and have any questions (how to plug in your Azure DevOps PAT, etc.) let me know and I'd be happy to help!

HI! I would like that kind of help :) !!  I already have a docker container running a shields instance but I can t figure out how to connect it to my private project and get badges ie for code coverage por tests? 
Can you help me with that?

BTW I already have Azure DevOps PAT  set up on a file called shields.env that I use to start docker with the following command:

docker run --rm -p 8080:80 --env-file shields.env --name shields shields

Thanks

**Comment by chris48s** [comment]
> I can t figure out how to connect it to my private project and get badges ie for code coverage por tests?
> Can you help me with that?

Hello. You can use env vars or `config/local.yml` to set credentials for some services to access private projects. See these docs https://github.com/badges/shields/blob/master/doc/server-secrets.md

**Comment by calebcartwright** [comment]
@robertoalfonso - happy to help, though it's difficult to offer much insight without knowing more. Feel free to open up a new issue too

**Comment by robertoalfonso** [comment]
@calebcartwright Should I open it as a support question?
I ll be focusing all day on this and will try what
 @chris48s  suggested
