### ISSUE TITLE
Delegate logos to simple-icons

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2510]
As discussed at https://github.com/badges/shields/pull/2463#issuecomment-445571253:

> I think we should try to defer all icons to [simple-icons](https://github.com/simple-icons/simple-icons).

I agree, I don't see a real advantage to keeping our own collection of icons.

Tasks:

- [ ] Modify our logo guidelines to say we are no longer accepting new logos
- [ ] Match up our existing logo collection with simple-icons, and get our existing logos matched in there. Maybe in the process, one of us could ask to join as a co-maintainer.
- [ ] Remove our existing logos, leaving aliases in place for if needed for backward compatibility.

**Comment by chris48s** [comment]
I've had a quick pass over our logos dir. These ones are already in simpleicons:

* bitcoin.svg
* circleci.svg
* discord.svg
* docker.svg
* github.svg
* gitlab.svg
* gitter-white.svg
* npm.svg
* paypal.svg
* serverfault.svg
* slack.svg
* stackexchange.svg
* stackoverflow.svg
* superuser.svg
* telegram.svg
* travis.svg
* twitter.svg
* windows.svg

The simpleicons version isn't the _exact_ same logo in all cases, but I'm in favour of just standardizing on the simpleicons version.

These ones don't exist in simpleicons:

* appveyor.svg
* azuredevops.svg
* codeship.svg
* dependabot.svg
* eclipse.svg
* lgtm.svg
* liberapay.svg
* matrix.svg
* postgresql.svg
* scrutinizer.svg
* sourcegraph.svg
* tfs.svg

I'm not sure if every single one of these will definitely meet all of their [guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon), but its worth a bash submitting some PRs and seeing where we get to.

We do also carry a couple of logos relating to deprecated services:

* bithound.svg https://github.com/badges/shields/blob/master/services/bithound/bithound.service.js
* gratipay.svg https://github.com/badges/shields/blob/master/services/gratipay/gratipay.service.js

which we should take the opportunity to remove.

**Comment by RedSparr0w** [comment]
Thanks for that list @chris48s,
I've done a quick mock up showing the differences between each of the logos:

Icon | Shields | Simple-Icons
:-- | :--: | :--:
bitcoin | ![](https://svgshare.com/i/9vB.svg) | ![](https://svgshare.com/i/9wJ.svg)
circleci | ![](https://svgshare.com/i/9tp.svg) | ![](https://svgshare.com/i/9wx.svg)
discord | ![](https://svgshare.com/i/9wR.svg) | ![](https://svgshare.com/i/9vm.svg)
docker | ![](https://svgshare.com/i/9wn.svg) | ![](https://svgshare.com/i/9va.svg)
github | ![](https://svgshare.com/i/9wy.svg) | ![](https://svgshare.com/i/9wS.svg)
gitlab | ![](https://svgshare.com/i/9vb.svg) | ![](https://svgshare.com/i/9vC.svg)
gitter-white | ![](https://svgshare.com/i/9wc.svg) | ![](https://svgshare.com/i/9vt.svg)
npm | ![](https://svgshare.com/i/9vu.svg) | ![](https://svgshare.com/i/9vn.svg)
paypal | ![](https://svgshare.com/i/9wb.svg) | ![](https://svgshare.com/i/9v4.svg)
serverfault | ![](https://svgshare.com/i/9vo.svg) | ![](https://svgshare.com/i/9x8.svg)
slack | ![](https://svgshare.com/i/9wo.svg) | ![](https://svgshare.com/i/9wU.svg)
stackexchange | ![](https://svgshare.com/i/9wK.svg) | ![](https://svgshare.com/i/9wd.svg)
stackoverflow | ![](https://svgshare.com/i/9x9.svg) | ![](https://svgshare.com/i/9vQ.svg)
superuser | ![](https://svgshare.com/i/9vv.svg) | ![](https://svgshare.com/i/9v5.svg)
telegram | ![](https://svgshare.com/i/9vc.svg) | ![](https://svgshare.com/i/9vR.svg)
travis | ![](https://svgshare.com/i/9vS.svg) | ![](https://svgshare.com/i/9xA.svg)
twitter | ![](https://svgshare.com/i/9xB.svg) | ![](https://svgshare.com/i/9vT.svg)
windows | ![](https://svgshare.com/i/9v6.svg) | ![](https://svgshare.com/i/9wL.svg)

**Comment by paulmelnikow** [comment]
Thanks for putting those together!

It's a bit of a mixed bag, isn't it?

*Looks better multicolor*

Icon | Shields | Simple-Icons
:-- | :-- | :--
bitcoin | ![](https://svgshare.com/i/9vB.svg) | ![](https://svgshare.com/i/9wJ.svg)
gitlab | ![](https://svgshare.com/i/9vb.svg) | ![](https://svgshare.com/i/9vC.svg)
npm | ![](https://svgshare.com/i/9vu.svg) | ![](https://svgshare.com/i/9vn.svg)
paypal | ![](https://svgshare.com/i/9wb.svg) | ![](https://svgshare.com/i/9v4.svg)
stackexchange | ![](https://svgshare.com/i/9wK.svg) | ![](https://svgshare.com/i/9wd.svg)

*Looks better in simple-icons*

Icon | Shields | Simple-Icons
:-- | :-- | :--
docker | ![](https://svgshare.com/i/9wn.svg) | ![](https://svgshare.com/i/9va.svg)
github | ![](https://svgshare.com/i/9wy.svg) | ![](https://svgshare.com/i/9wS.svg)
twitter | ![](https://svgshare.com/i/9xB.svg) | ![](https://svgshare.com/i/9vT.svg)
slack | ![](https://svgshare.com/i/9wo.svg) | ![](https://svgshare.com/i/9wU.svg)
stackoverflow | ![](https://svgshare.com/i/9x9.svg) | ![](https://svgshare.com/i/9vQ.svg)
windows | ![](https://svgshare.com/i/9v6.svg) | ![](https://svgshare.com/i/9wL.svg)

*Shields color looks better*

Icon | Shields | Simple-Icons
:-- | :-- | :--
circleci | ![](https://svgshare.com/i/9tp.svg) | ![](https://svgshare.com/i/9wx.svg)
discord | ![](https://svgshare.com/i/9wR.svg) | ![](https://svgshare.com/i/9vm.svg)

*Other*

Icon | Shields | Simple-Icons | Note
:-- | :-- | :-- | :--
gitter-white | ![](https://svgshare.com/i/9wc.svg) | ![](https://svgshare.com/i/9vt.svg) | simple-icons color conflicts with shields name
serverfault | ![](https://svgshare.com/i/9vo.svg) | ![](https://svgshare.com/i/9x8.svg) | don't love either of these
superuser | ![](https://svgshare.com/i/9vv.svg) | ![](https://svgshare.com/i/9v5.svg) | simple-icons scale is better though I kind of like our two-color version
telegram | ![](https://svgshare.com/i/9vc.svg) | ![](https://svgshare.com/i/9vR.svg) | our color looks bad on dark
travis | ![](https://svgshare.com/i/9vS.svg) | ![](https://svgshare.com/i/9xA.svg) | don't love either of these

**Comment by ericcornelissen** [comment]
Hi everyone 👋 I'm a maintainer over at SimpleIcons and noticed some PRs/issues referencing this issue. First of all, I'm glad to hear you folks are considering using the icons we provide! I'm not all to familiar with this project but I'm willing to learn and help you guys with integrating SimpleIcons 😃 

First of, let me say that I think it is possible to make icons available for your usage even if they do not necessarily meet our strictest requirements (which currently is based on [Alexa rankings](https://www.alexa.com/siteinfo)), but to be honest I don't expect any issues at all in this regard.

I think that the color of the icons is going to be the biggest issue. We try to specify the main brand color, rather then a color that looks good on a shield. My first suggestion here - although I have no clue if its feasible - is to allow your users to just use a white version of the icon if they wish to.

As for the multicolored icons, we have a related issue on that topic (https://github.com/simple-icons/simple-icons/issues/1060), but I don't see it happening anytime soon...

One last note, looking at @paulmelnikow I see for example that the Travis CI icon doesn't look very good on badges. Unless Travis CI has guidelines restricting us to change the icon, I'm totally fine with updating the Travis CI icon (and the same goes for other icons of course). Relatedly, if a brand has guidelines that say you should use a specific version of the logo, arguably you should use that even if it doesn't look as good on a badge 🤔

**Comment by RedSparr0w** [comment]
Thanks for chiming in @ericcornelissen 😄 
>First of all, I'm glad to hear you folks are considering using the icons we provide! I'm not all to familiar with this project but I'm willing to learn and help you guys with integrating SimpleIcons 😃

We are currently already using simple-icons for our badges where we do not already have an icon of our own, Glad to see simple-icons using our badges on the readme 👍  

>I think that the color of the icons is going to be the biggest issue. We try to specify the main brand color, rather then a color that looks good on a shield. My first suggestion here - although I have no clue if its feasible - is to allow your users to just use a white version of the icon if they wish to.

Currently we by default use the brand color when a user doesn't specify the icon color:
`https://img.shields.io/badge/Nintendo-Switch-E60012.svg?logo=nintendo-switch`
![](https://img.shields.io/badge/Nintendo-Switch-E60012.svg?logo=nintendo-switch)
Or the user can specify any specific color using `?logoColor=whitesmoke`
_support rgb(a), hsl(a), hex(FF0000), css color names_
`https://img.shields.io/badge/Nintendo-Switch-E60012.svg?logo=nintendo-switch&logoColor=whitesmoke`
![](https://img.shields.io/badge/Nintendo-Switch-E60012.svg?logo=nintendo-switch&logoColor=whitesmoke)

>Unless Travis CI has guidelines restricting us to change the icon, I'm totally fine with updating the Travis CI icon (and the same goes for other icons of course). Relatedly, if a brand has guidelines that say you should use a specific version of the logo, arguably you should use that even if it doesn't look as good on a badge 🤔

We try to consult any documentation we could find before merging logos to make sure we followed the brand guidelines, although some may have changed since the design was implemented.

>Having seen them all laid out next to each other I'm going to row back slightly on my "I'm in favour of just standardizing on the simpleicons version" comment. There are a few where the one we're using is a better choice in the situation where its going to be displayed really small. Equally, the number where ours is 'better' (read: more optimised for our use-case) vs the number where the one in SimpleIcons is is 'better' is about the same.

I don't think we need to move all our icons over to simple icons _(specifically the multi color ones which don't look as good monochrome)_, but any that already look very similar should probably be moved over.

We also should still accept the odd logo which wont fit simple-icons guidelines.

**Comment by ericcornelissen** [comment]
Thanks for the clarification @RedSparr0w 👍 


> Currently we by default use the brand color when a user doesn't specify the icon color

In that case my advice would be to by default use a color that is legible on the badge and add a color keyword like `"brandColor"` that will pull the brand color from SimpleIcons. But I guess that decision is up to the maintainers.


> We try to consult any documentation we could find before merging logos to make sure we followed the brand guidelines, although some may have changed since the design was implemented.

Makes sense, just wanted to point out that our versions are also not set in stone 🙂

**Comment by chris48s** [comment]
Update: simple-icons v1.9.18 now also includes a version of all our custom logos except for LGTM, which is [still under review](https://github.com/simple-icons/simple-icons/pull/1158). Here's a table comparing the new icons:

| Shields | Simple Icons (default) | Simple Icons (white) |
|---|---|---|
| ![https://svgshare.com/s/AVu](https://svgshare.com/i/AVu.svg) | ![https://svgshare.com/s/AVg](https://svgshare.com/i/AVg.svg) | ![https://svgshare.com/s/AVA](https://svgshare.com/i/AVA.svg) |
| ![https://svgshare.com/s/AVh](https://svgshare.com/i/AVh.svg) | ![https://svgshare.com/s/AXE](https://svgshare.com/i/AXE.svg) | ![https://svgshare.com/s/AVv](https://svgshare.com/i/AVv.svg) |
| ![https://svgshare.com/s/AVU](https://svgshare.com/i/AVU.svg) | ![https://svgshare.com/s/AW3](https://svgshare.com/i/AW3.svg) | ![https://svgshare.com/s/AVw](https://svgshare.com/i/AVw.svg) |
| ![https://svgshare.com/s/AWP](https://svgshare.com/i/AWP.svg) | ![https://svgshare.com/s/AWi](https://svgshare.com/i/AWi.svg) | ![https://svgshare.com/s/AVi](https://svgshare.com/i/AVi.svg) |
| ![https://svgshare.com/s/AXR](https://svgshare.com/i/AXR.svg) | ![https://svgshare.com/s/AW4](https://svgshare.com/i/AW4.svg) | ![https://svgshare.com/s/AWB](https://svgshare.com/i/AWB.svg) |
| ![https://svgshare.com/s/AXF](https://svgshare.com/i/AXF.svg) | ![https://svgshare.com/s/AWC](https://svgshare.com/i/AWC.svg) | ![https://svgshare.com/s/AXS](https://svgshare.com/i/AXS.svg) |
| ![https://svgshare.com/s/AX5](https://svgshare.com/i/AX5.svg) | ![https://svgshare.com/s/AW5](https://svgshare.com/i/AW5.svg) | ![https://svgshare.com/s/AWD](https://svgshare.com/i/AWD.svg) |
| ![https://svgshare.com/s/AXb](https://svgshare.com/i/AXb.svg) | ![https://svgshare.com/s/AXT](https://svgshare.com/i/AXT.svg) | ![https://svgshare.com/s/AWE](https://svgshare.com/i/AWE.svg) |
| ![https://svgshare.com/s/AW6](https://svgshare.com/i/AW6.svg) | ![https://svgshare.com/s/AXG](https://svgshare.com/i/AXG.svg) | ![https://svgshare.com/s/AWj](https://svgshare.com/i/AWj.svg) |
| ![https://svgshare.com/s/AXU](https://svgshare.com/i/AXU.svg) | ![https://svgshare.com/s/AXc](https://svgshare.com/i/AXc.svg) | ![https://svgshare.com/s/AXd](https://svgshare.com/i/AXd.svg) |

There are a few cases where there is a naming difference. e.g: scrutinizer in our logos, scrutinizer-ci in simple-icons, eclipse in our logos, eclipse-ide in simple-icons but we can always alias those for legacy compatibility.

As we've already identified there are a lot of cases where simple-icons holds a good icon, but the default colour doesn't look good on a dark background (in many cases, our icon is basically identical apart from the default colour). It seems excessive to maintain our own icon in these situations. I think I'm becoming more convinced the ideal solution to this is https://github.com/badges/shields/issues/2431

btw, fair play for assembling that first table @RedSparr0w - having just gone through the process of generating each of those images, saving them off, uploading them and making a markdown table, I know exactly how laborious the process is!

**Comment by RedSparr0w** [comment]
Wow, Nice work getting all those logos merged!

>It seems excessive to maintain our own icon in these situations. I think I'm becoming more convinced the ideal solution to this is #2431

I will look into implementing #2431 soon, once i get back into the flow of things :smile:

>btw, fair play for assembling that first table @RedSparr0w - having just gone through the process of generating each of those images, saving them off, uploading them and making a markdown table, I know exactly how laborious the process is!

Haha yeah, i thought about trying to automate it a bit, but figured it would just be quicker & easier to just manually do it all.

**Comment by chris48s** [comment]
Most of our icons are deleted in #2857

#2872 #2873 and #2874 are open proposing some further edits to some of the multi-coloured ones we're keeping.

There are 4 outstanding..

* LGTM: currently ignoring this one as simple-icons 1.9.19 will have an icon for this. We can probably drop it.
* Telegram: We've kept our icon, but the default is black on dark background. I think I want to see if I can improve this. Maybe this version https://commons.wikimedia.org/wiki/File:Telegram_logo.svg would work?
* Travis, Serverfault: Don't know what to do with these. Our version isn't great, neither is simple-icons. They're just a bit too fiddly/detailed to work well that this size really :/

I also want to review the logo submission guidelines before we close this off

**Comment by paulmelnikow** [comment]
> * Maybe this version https://commons.wikimedia.org/wiki/File:Telegram_logo.svg would work?

That looks nice. Are you thinking it would be white on a blue circle for both the light and dark badges (sort of like Bitcoin)?

**Comment by chris48s** [comment]
Had a go at this. This version has a lot more contrast, but it loses quite a lot of detail at small size:

* ![](https://svgshare.com/i/ApF.svg)
* ![](https://svgshare.com/i/AmQ.svg)

not sure if that is better..

**Comment by paulmelnikow** [comment]
It looks good on Retina!

I guess you could try darkening the gray along the “fuselage” to preserve contrast at small sizes.

**Comment by chris48s** [comment]
Once simple-icons 1.9.19 is available, I'll do another PR to remove the LGTM logo in favour of the SI version. Beyond that, I think everything under this banner is done or there's a PR open for it so I'm going to close this off. If anything else is still outstanding, feel free to re-open

**Comment by metaa** [comment]
I'm glad this topic is being discussed!
Just today I stumbled across a few icons that did ignore the `logoColor` parameter, but then I realized that those are the ones that *overlay* the `simple-icons` ones.

**Comment by paulmelnikow** [comment]
Ah, that probably should be included in the documentation for `logoColor`.

**Comment by Borda** [comment]
Hi, do you have an example of how to use `simple-icons` and is there an indication of which version is used?

**Comment by chris48s** [comment]
@borda Logos can be included with the logo param e.g: https://img.shields.io/npm/v/npm.svg?logo=javascript
We're currently using 4.25. There's a PR open to deal with the non backwards-compatible changes in v5
See https://github.com/badges/shields/discussions/5369 for more info on upgrade schedule
