### ISSUE TITLE
Old pypi version in README

### ISSUE THREAD

**Issue by rominf** [badges/shields#2514]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I have https://github.com/rominf/jira-oauth library, it uses PyPI version shield in `README.md`. The problem is that version is old:
![Screenshot with the problem](https://user-images.githubusercontent.com/3449635/49852545-79f95b80-fdf5-11e8-9cab-c111b9f0e0fa.png)

:link: **Link to the badge**

https://img.shields.io/pypi/v/jira-oauth.svg

:bulb: **Possible Solution**

?

**Comment by chris48s** [comment]
![](https://img.shields.io/pypi/v/jira-oauth.svg)

Looks like you posted this just after pushing a release. We cache version badges for 5 minutes for performance reason, so it may take up to 5 mins for the version badge to catch up. Some upstream services also have their own caching. If it was longer than that, its possible the PyPI API outputs also have a bit of cache latency on them.

**Comment by rominf** [comment]
OK. Thank you for an explanation.

Is there a way to force cache refresh?
