### ISSUE TITLE
Document badge deprecation

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2528]
It would be helpful to mention in our contributing guidelines how to handle deprecated badges. Sometimes people come around and helpfully remove them and then [we have to point them in the right direction](https://github.com/badges/shields/pull/2410#issuecomment-442103338). And sometimes people just ask! Since the deprecated badges don't currently appear in the UI, that we handle them specially may be unexpected.

Here's a recent example: #2352.

**Comment by chris48s** [comment]
closed in #2529
