### ISSUE TITLE
Docker image size display 0

### ISSUE THREAD

**Issue by aggresss** [badges/shields#2532]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

/microbadger/image-size/:imageId+.svg

:link: **Link to the badge**

https://github.com/aggresss/docker-library
:bulb: **Possible Solution**

**Comment by PyvesB** [comment]
Hello @aggresss,

The download size for your image does not seem to be available on the [Microbadger web interface](https://microbadger.com/images/aggresss/elementary). We aren't getting it through the API response either:
````
{
	"LatestSHA": "3f8d418f03a59faf9ecb4c228a7e11c2e8485d5b655d018f8553f4374f4578f3",
	"WebhookURL": "https://hooks.microbadger.com/images/aggresss/elementary/2s5IXJtxFjjLHsRxqwMJrSSbq_4=",
	"UpdatedAt": "2018-12-14T08:47:51.363852Z",
	"Description": "elementary",
	"LastUpdated": "2018-12-13T03:47:02.082565Z",
	"PullCount": 462,
	"StarCount": 1,
	"Versions": [
		{
			"SHA": "237db9807b572f31d4d34e57b296ff1e59f936afbcf6abe9c4337076f17718f7",
			"Tags": [
				{
					"tag": "stretch"
				}
			],
			"ImageName": "aggresss/elementary",
			"Author": "aggresss \u003caggresss@163.com\u003e",
			"Labels": {
				"DOCKER_IMAGE": "aggresss/elementary:stretch"
			},
			"LayerCount": 11,
			"DownloadSize": 0,
			"Created": "2018-12-13T03:33:54.258382Z"
		},
		...
	"Id": "3f8d418f03a59faf9ecb4c228a7e11c2e8485d5b655d018f8553f4374f4578f3",
	"ImageName": "aggresss/elementary",
	"ImageURL": "https://hub.docker.com/r/aggresss/elementary/",
	"Author": "aggresss \u003caggresss@163.com\u003e",
	"LayerCount": 11,
	"Labels": {
		"DOCKER_IMAGE": "aggresss/elementary:jessie"
	},
	"LatestVersion": "jessie"
}
````

We've had problems in the past with the data returned from the Microbadger service (see [this issue](https://github.com/microscaling/microbadger/issues/38) I raised a while back on their repository), however, contrarily to last time some of the metadata is present and calling the webhook manually does not solve the problem. I would recommend that you open an issue on Microbadger's repository and enquire why the size is not showing for you image.

Cheers,

Pyves

**Comment by aggresss** [comment]
@PyvesB Thanks a lot.
