### ISSUE TITLE
Remove <object> backdoor

### ISSUE THREAD

**Issue by KOLANICH** [badges/shields#2534]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)

:beetle: **Description**
The stuff currently uses `object` html tag.

>https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

>The HTML object element represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a **plugin**.

Usage of plugins considered to be a backdoor.

:bulb: **Possible Solution**
Replace with more suitable tags.

**Comment by paulmelnikow** [comment]
We don’t use plugins and `<object>` is not a back door. I think there’s some misunderstanding.

**Comment by KOLANICH** [comment]
>We don’t use plugins

How can you be sure that the remote party have not sent an object? Images should use `img` tag. Webpages should use `iframe` tag (it also may send an object, but at least this doesn't confuse NoScript treating everything in `object` tag as an object).

**Comment by paulmelnikow** [comment]
What do you mean, an object? What remote party? You seem to suggest that using object for a self-hosted image exposes the user to a security vulnerability. Do you have references for that?

**Comment by KOLANICH** [comment]
>What remote party?

Do I understand right, that everything from `img.shields.io` is shipped via a CDN?

**Comment by KOLANICH** [comment]
>You seem to suggest that using object for a self-hosted image exposes the user to a security vulnerability.

I suggest that `object` and `embed` are the tags used to embed object processed by plugins. That's why they are blocked by software like `noscript` because plugins are dangerous stuff (that's why I don't have any plugins in my browser enabled since 2009). It may make sense to use `img` tag for that.

**Comment by chris48s** [comment]
There are 3 badges on the index page where we are using `<object>`. Is that the only place where we are using `<object>` or are there other places?

If so, are we gaining anything by using `<object data="">` instead of `<img src="">` there?

**Comment by paulmelnikow** [comment]
It's what makes it possible to provide clickable links inside the SVG. It's probably useful to showcase that somewhere. (For what it's worth, I'm curious how much people use that `link` feature…)

**Comment by paulmelnikow** [comment]
Happy to reconsider this if there's evidence we're putting users at risk. I don't see a huge usability issue since it's only our own social buttons which are being hidden.
