### ISSUE TITLE
Badge request: GitHub closed PRs/Issues by label

### ISSUE THREAD

**Issue by MattIPv4** [badges/shields#2536]
:clipboard: **Description**
GitHub badge exactly the same as the current closed issues/pull requests badges with by the label filtering ability of the open issues/pull request badges.

:link: **Data**
Presumably the same place as the existing badges?

**Comment by chris48s** [comment]
example API call: https://api.github.com/repos/badges/shields/issues?labels=documentation

**Comment by MattIPv4** [comment]
Call would actually be https://api.github.com/repos/badges/shields/issues?labels=documentation&state=closed to get only closed
