### ISSUE TITLE
GitHub dynamic issue/pull request badges

### ISSUE THREAD

**Issue by MattIPv4** [badges/shields#2537]
:clipboard: **Description**
The current issue/pull request based badges for GitHub require the user to input the number of the issue/pull request which makes it very hard to implement them into a .github template.
Would it be possible to accept a value (such as `CURRENT`) in place of the issue/pull request number and make use of the referer header data to generate the badge based on the current issue/pull request, allowing the badges to work in a template without a user having to update the url?

:link: **Data**
Same way as the current issue/pull request specific GitHub badges but making use of the Referer header to identify which issue/pull request it is, instead of the value given in the url.

**Comment by MattIPv4** [comment]
Badges this would be able to work on:
- https://img.shields.io/github/issues/detail/s/badges/shields/979.svg
- https://img.shields.io/github/issues/detail/title/badges/shields/1290.svg
- https://img.shields.io/github/issues/detail/u/badges/shields/979.svg
- https://img.shields.io/github/issues/detail/label/badges/shields/979.svg
- https://img.shields.io/github/issues/detail/comments/badges/shields/979.svg
- https://img.shields.io/github/issues/detail/age/badges/shields/979.svg
- https://img.shields.io/github/issues/detail/last-update/badges/shields/979.svg
- https://img.shields.io/github/status/s/pulls/badges/shields/1110.svg
- https://img.shields.io/github/status/contexts/pulls/badges/shields/1110.svg

**Comment by paulmelnikow** [comment]
Hi! Cool idea!

GitHub serves images through an anonymizing proxy called camo. It’s designed to prevent servers from getting details about the requests, and precludes this approach.

Here’s a long time Shields maintainer’s answer to a similar question on SO: https://stackoverflow.com/a/46174423/893113

What badge are you using in an issue template?

I think GitHub would have to make it possible to embed an issue number placeholder when creating an issue (which seems complicated) or modify camo to allow the Referer header to pass through.

**Comment by MattIPv4** [comment]
@paulmelnikow Ah okay, that's a shame that they proxy everything to hide it.

I was wanting to be able to use the label badge and the checks w/ context badge in templates.

**Comment by chris48s** [comment]
closing this as I don't think there's anything we can do to take it further
