### ISSUE TITLE
Private Travis badges

### ISSUE THREAD

**Issue by laserlemon** [badges/shields#254]
Travis badges for private repos are accessed using a secret token query parameter. For example:

```
https://magnum.travis-ci.com/foo/bar?token=DcdFsOhhUow9Ba8XAUyG
```

Is there any possibility to support these private badges? Same question for other services like Code Climate, Gemnasium, etc.

**Comment by olivierlacan** [comment]
Up-to-date Shields badges for private repos are available from Travis now so I'm going to close this.

**Comment by eproxus** [comment]
@olivierlacan Cannot find any documentation for this. How is it done? I tried `http://img.shields.io/travis/org/repo/TOKEN.svg` but it doesn't work.

**Comment by espadrine** [comment]
@eproxus We don't currently support badges for private Travis repos. Travis does, though.

**Comment by eproxus** [comment]
@espadrine Ah, I see. Why was the issue closed then?
