### ISSUE TITLE
Badge request: Snapcraft

### ISSUE THREAD

**Issue by antonmedv** [badges/shields#2544]
:clipboard: **Description**
Add support for snap: https://snapcraft.io
:link: **Data**
Don't know.

**Comment by chris48s** [comment]
relevant API docs: https://dashboard.snapcraft.io/docs/api/snap.html#obtaining-information-about-a-snap

**Comment by solemcaelum** [comment]
What exact data would you be looking to add?
Could do Snap Status: 
[![snapcraft status](https://img.shields.io/badge/snap%20status-published-brightgreen.svg)](https://snapcraft.io/discord)
Or Snap Price:
[![snapcraft price](https://img.shields.io/badge/snap%20price-$%200-blue.svg)](https://snapcraft.io/discord)

Though besides those two applications, I can't think of much else you could add.

**Comment by paulmelnikow** [comment]
Hi! Price is good. Some other ideas: license, the latest version released in a particular channel, and stats like installed base and device change.

We have a published/unpublished badge for vaadin directory and TBH I'm not sure it's helpful.

**Comment by solemcaelum** [comment]
Alrighty, I can start on a Pull Request to see about adding Price, and I'll leave out Published. 
I think I can also work the Latest Version, Installed Base, and Device Change though I'm not so sure about the last two. 

Would making a badge featuring the Architectures that snap is available on be helpful?

**Comment by antonmedv** [comment]
@solemcaelum version will be cool.

**Comment by calebcartwright** [comment]
@solemcaelum - awesome! 

Be sure to check out our [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) for writing badge services if you haven't already done so. 

Feel free to ping us on this thread and/or in Discord if we can be of any help!

**Comment by chris48s** [comment]
Lets start off with price, version (and installed base, if you want/can) as a starting point - its easier for us to review a smaller unit of work. PRs that add a whole kitchen sink of badges all at once often spend a lot of time in review and take a long time to land which can be frustrating for the contributor.

If we're not sure if a badge is useful, lets leave it for now.. if someone is using the snap badges and really wants a architectures badge, they'll raise an issue for it :)

**Comment by VilhelmPrytz** [comment]
Any updates regarding this? :smiley:

**Comment by LeoDog896** [comment]
Was this *actually* finished? I can't find any reference to it at all. By the way, here are the new [REST API docs](https://snapcraft.io/docs/snapd-api).

**Comment by chris48s** [comment]
No. We don't have any snapcraft badges.
The original author closed the issue.
The PR referencing this issue is from a different  repo.
