### ISSUE TITLE
Coverage is misreported for the frontend

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2552]
Some of the files aren't being reported:

<img width="890" alt="screen shot 2018-12-18 at 4 24 20 pm" src="https://user-images.githubusercontent.com/1487036/50183875-682a2380-02e1-11e9-9e46-d125d2113d44.png">

Maybe it's transpiler-related?

**Comment by chris48s** [comment]
If all the missing files are ones that aren't covered by tests, we might need to run `nyc` with the `--all` flag (we should probably do this everywhere). If there is stuff missing that is covered, you might be right about transpilation. In that case, we may need to explicitly whitelist relevant files/dirs?

**Comment by paulmelnikow** [comment]
There's coverage on stuff that's missing, e.g. `meta.js`, `headers.js`. Also e.g. `usage.js` should be shallow-rendering, which I think would get it to 100%.

**Comment by calebcartwright** [comment]
I was wondering earlier whether adding an `nyc` config file might be useful. I was looking at it from the perspective of the service tests (and how coverage is getting dinged incorrectly because lines like [this](https://github.com/badges/shields/blob/master/services/create-service-tester.js#L18) in test helper code aren't getting hit, but it may be useful elsewhere too

**Comment by paulmelnikow** [comment]
We've got one :)

https://github.com/badges/shields/blob/master/.nycrc.json

I guess we are setting `all: true`; presumably that's the same as `--all`.

Ah, yea, being a test helper, `create-service-tester.js` probably should be ignored.

**Comment by calebcartwright** [comment]
so weird. my editor was hiding it from me, my bad!

**Comment by paulmelnikow** [comment]
I wonder if this is what we need to do:

- https://github.com/istanbuljs/nyc#nyc
- https://github.com/istanbuljs/babel-plugin-istanbul#mocha-on-nodejs-through-nyc
