### ISSUE TITLE
Badge for another repo queried issues 

### ISSUE THREAD

**Issue by apobekiaris** [badges/shields#2568]
hi 

I generated this badge
```
[![](https://img.shields.io/github/issues/eXpandFramework/Packages.svg?style=flat-square)](https://github.com/eXpandFramework/eXpand/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apackages).
```

at the moment of posting the query returns 1 issue 

![image](https://user-images.githubusercontent.com/159464/50277776-01764880-044e-11e9-900d-a260195c7234.png)

however the badge displays zero

![image](https://user-images.githubusercontent.com/159464/50277831-25d22500-044e-11e9-86c5-19a3a1f695c4.png)
![image](https://user-images.githubusercontent.com/159464/50277911-60d45880-044e-11e9-8af7-609732eb2469.png)

**Comment by apobekiaris** [comment]
here the solution 

[![GitHub issues](https://img.shields.io/github/issues/eXpandFramework/expand/Packages.svg)]

**Comment by paulmelnikow** [comment]
Aha! I wonder if we can improve the error handling there. That's one of the badges which hasn't been refactored yet.

**Comment by apobekiaris** [comment]
though this project is super powerfull it's a bit hard to understand how to configure when you first comer. Maybe you should unit test the examples on the site, or provide more realistic ones that work and not just images.

**Comment by paulmelnikow** [comment]
Improving error messages is something we've been working on over the last year or so, though as I look closer at this, I'm not sure we could do any better here. [You have a repo in the same org called `Packages`](https://github.com/expandframework/packages), which means the badge you asked for is valid. This is the test of the "repo not found" case for that badge:

https://github.com/badges/shields/blob/872aede5bef91b0042e1747856e5426cb83f62e9/services/github/github-issues.tester.js#L112-L117

Was the difficulty figuring out how to plug the values into the right place? I'm working on #2496 along those lines, which should make it easier to correctly construct a badge URL from parts.

In case it's helpful to you in the meantime, all of the badges have one fully working example. It's either there from the start, like this one:

<img width="629" alt="example1" src="https://user-images.githubusercontent.com/1487036/50309424-cc2d2300-046c-11e9-86af-1e9a50629615.png">

Or is listed as a separate Example, like this one:

<img width="621" alt="screen shot 2018-12-20 at 3 35 31 pm" src="https://user-images.githubusercontent.com/1487036/50309483-01397580-046d-11e9-9ae0-debae9afb8a3.png">

Finally, we're serious about improving this stuff, though we're all volunteers. There are lots of ways you can help: https://github.com/badges/shields/labels/good%20first%20issue
