### ISSUE TITLE
Matrix live test is flaky

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2630]
https://circleci.com/gh/badges/daily-tests/56

```
  1) Matrix
       test on real matrix room for API compliance
         
	[ GET /twim:matrix.org.json?style=_shields_test ]:
     Error: Request timed out after 10000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)
```

First time noticing this. Hopefully it goes away on its own! 🤞

**Comment by chris48s** [comment]
This badge seems fairly sluggish in production too. If/when we do https://github.com/badges/shields/issues/2547 that should help in the live environment but this is always going to be slow in CI given how many requests it has to make. Its probably worth giving it a longer timeout than usual

**Comment by paulmelnikow** [comment]
Another timeout: https://circleci.com/gh/badges/shields/32618

**Comment by paulmelnikow** [comment]
Seems this has been better lately?

**Comment by PyvesB** [comment]
Haven't noticed any Matrix test failures recently, will go ahead and close this issue.
