### ISSUE TITLE
Don't encode slashes in examples

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2649]
Sometimes we need to be able to pass a parm to a service which is a path with some arbitrary number of slashes in it.

When we set an example for this, it will render like `foo%2Fbar%2Fbaz` when we show the example in the front end, but it would be nicer if it rendered as `foo/bar/baz`

refs https://github.com/badges/shields/pull/2639#discussion_r245489576

**Comment by paulmelnikow** [comment]
Related: pillarjs/path-to-regexp#177

**Comment by chris48s** [comment]
I think now that we display these as `param+` or `param*` on the index (rather than populating with an example), this is now irrelevant. The examples look correct in the modals
