### ISSUE TITLE
Remove IP filtering code for prometheus metrics

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2657]
After discussion in #ops there was a decision not to filter metrics by IP addresses. There does not seem to be a significant performance hit.

After this change, prometheus metrics can either be on or off.

**Comment by platan** [comment]
Alternatively, we can change default value of `allowedIps` to `.+` (allow all). This way it will we possible to limit access to metrics in the future/for self-hosted instances.

**Comment by paulmelnikow** [comment]
I imagine most self-hosted instances won't need monitoring and if they do, I'm not sure they would need access checks. It seems like one more piece of code we have to test and maintain, and I think our effort is better put on other things.
