### ISSUE TITLE
High-level code walkthrough

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2684]
It would be helpful to provide a high-level walk-through of the code. This has been asked for in a couple forms in the past: #114 #811.

After #2661 we'll have some pretty decent documentation of the production hosting which explains the architecture of the system pretty well.

**Comment by paulmelnikow** [comment]
I have a draft of this in the "High-level code walkthrough" section:

https://docs.google.com/document/d/11RCKeEqMQmKnh8Ij0sywRZPE66wxQBwHqiE9-OAZqhQ/edit#heading=h.bq9faurn4rs.

It's so much faster to iterate on copy in Google Docs. @chris48s and @calebcartwright, could I ask you to review / comment / edit that section? (Comments welcome from anyone else too!)

Once you guys are happy with it, I'll reformat it in Markdown and we can push through a PR.

The rest of that document is a work in progress. Comments are certainly welcome! Though it's not necessarily ready for review.

**Comment by calebcartwright** [comment]
Wow! You have been busy. I did not realize how much you already had out there.

**Comment by calebcartwright** [comment]
Also I goofed up a comment 🤦‍♂️ No big deal but you will know it when you see it 😉 Apologies in advance

**Comment by paulmelnikow** [comment]
> Wow! You have been busy. I did not realize how much you already had out there.

Yea! Mostly I organized a bunch of notes I've been collecting over the past couple years, and also pasted in bits I've written or seen other people write since I started the document.

**Comment by paulmelnikow** [comment]
@chris48s @calebcartwright Is there anything else you think needs updating before I move the code walkthrough into Markdown?

**Comment by calebcartwright** [comment]
I thought it was good to go already on my first read. Will give it another read here shortly or tomorrow

**Comment by chris48s** [comment]
> @chris48s @calebcartwright Is there anything else you think needs updating before I move the code walkthrough into Markdown?

I reckon its good to submit a PR for it :+1:
