### ISSUE TITLE
Modernize field names in JSON-format badge responses

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2686]
In our badges we're using **label** and **message** which are semantically really good names, however our JSON endpoint still uses **name** and **value**… and so do all our service tests.

I'd suggest we deprecate **name** and **value** in the JSON response (maybe keep them around for a year or two?) and add **label** and **message** as synonyms. At the same time, we can add **color**.

Most services do not consider it a breaking change to add another item to an object. However there is a slight chance that adding unexpected keys could break someone's integration.

The service tests will need to be modified to accept extra keys. However we could take the opportunity to make those tests more concise (#2687).

**Comment by chris48s** [comment]
I would be really interested to understand what JSON format badges are being used for, outside of our own test suite.

**Comment by paulmelnikow** [comment]
Good question 🤔 

One thought if we do #2674 is that JSON could be handled in a query parameter and/or request header. That way we could keep the old `.json` format around for a while, while using the Endpoint schema (#2473) for the new one

**Comment by paulmelnikow** [comment]
> But really I can't actually see it being use outside of our testing, do we have any metrics for format usage?

No, we don't, but it would be a good idea to include that when we do #966.
