### ISSUE TITLE
Experiment with retry() for failed service tests

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2688]
Often service tests fail once, only to run correctly the next time through. IcedFrisby has a [`retry()` function](https://github.com/IcedFrisby/IcedFrisby/blob/master/API.md#retrycount-backoff) which may be a good solution for isolated failures. It could make the daily suite, and especially PR builds, more reliable, with a teeny tiny amount of effort.

We could experiment with:

- Turning this on for all the tests
- Attaching it to flaky tests
- Turning it on for all the tests, but only in the daily tests (or PRs?)

**Comment by platan** [comment]
Retries are enabled in daily tests and in PR tests. I'm closing this issue now, but I'm happy to experiment with different options if needed.

**Comment by paulmelnikow** [comment]
Thanks @platan!
