### ISSUE TITLE
Better dynamic badge with more dynamic content

### ISSUE THREAD

**Issue by truongsinh** [badges/shields#2694]
:clipboard: **Description**

with params:
- subjectQuery
- statusQuery
- colorBQuery
- prefixQuery
- suffixQuery

in this format `https://img.shields.io/badge/dynamic/yaml.svg?url=<URL>&subjectQuery=<LABEL>&statusQuery=<$.DATA.SUBDATA>&colorBQuery=<COLOR>&prefixQuery=<PREFIX>&suffixQuery=<SUFFIX>`

for any of the params that is static instead dynamic, we can use json string, e.g `https://img.shields.io/badge/dynamic/yaml.svg?url=<URL>&subjectQuery=<LABEL>suffixQuery="myStaticStatus"`

The reason for this request is that at https://github.com/truongsinh/flutter-plugins , i'm generating dynamic badge from test coverage data, and i would like to display `colorB` from data source as well instead of static test.

I'm happy to make PR for this.

**Comment by calebcartwright** [comment]
Would #2473 help with this one too @paulmelnikow ?

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. Yes I agree with @calebcartwright that #2473 is perfect for your use case. It inverts the whole paradigm without you having to define a mapping.

Does that make sense @truongsinh? i.e. does it seem like #2473 will solve your problem?

(Also ref #1752)

**Comment by truongsinh** [comment]
@calebcartwright @paulmelnikow close enough, in my use case, I prefer to keep all the data in one file (because this file is machine-generated too). If we could for example have `/badge/endpoint.svg?url=<URL>&style=<STYLE>&entry=$.0` or `/badge/endpoint.svg?url=<URL>&style=<STYLE>&entry=$.mykey` it would perfectly suitable for me needs

**Comment by paulmelnikow** [comment]
How big will the file be?

**Comment by truongsinh** [comment]
~40 entries, each entries I assume 100 bytes = ~4KB

**Comment by paulmelnikow** [comment]
The [Endpoint badge][] is live!

If you decide to use the new feature, your feedback is much appreciated! Please feel free to comment on [the Endpoint beta issue][beta] if you have feedback or questions about how to use it.

[endpoint badge]: https://shields.io/#/endpoint
[tools]: https://github.com/badges/shields/issues/2259#issuecomment-444186589
[beta]: https://github.com/badges/shields/issues/2838
