### ISSUE TITLE
New Badge: Hakiri Support: Monitor gems for security issues

### ISSUE THREAD

**Issue by NullVoxPopuli** [badges/shields#270]
example: 
https://hakiri.io/github/NullVoxPopuli/MetaHash/master/shield

**Comment by espadrine** [comment]
Hakiri APIs are mentionned [here](https://hakiri.io/legal/security) but otherwise, I can't see a page where they explain their public API.

**Comment by sirwolfgang** [comment]
Ya, I see what you see. I just sent them a message, so maybe they can shed some light.

**Comment by vasinov** [comment]
Hakiri doesn't have any public APIs but I could provide a special call for shields.io. What would you need from me?

**Comment by espadrine** [comment]
Something as simple as an X- HTTP field with one of a list of exclusive valid values would be great. Having it be the contents of the right of the badge, for instance, is just fine. That technique is not uncommon, either.

(Scraping the SVG itself is also feasible, but much more error-prone, from experience.)

**Comment by NullVoxPopuli** [comment]
Any updates? :-)

**Comment by chrisb** [comment]
Would also love to see this :)

**Comment by paulmelnikow** [comment]
@vasinov Is there any update on a public API?

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
