### ISSUE TITLE
Auto-alphabetize imports

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2701]
@Daniel15 suggested at https://github.com/badges/shields/pull/2554#pullrequestreview-190125958:

> In general, does this project have rules about alphabetization? At Facebook we alphabetize `require()` statements and JSX props (the latter enforced using [react/jsx-sort-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md) lint rule).

If we can automate this, seems easy enough and will help keep things tidy. I do tend to spend a bit of time putting these in order when I move things around.

**Comment by Daniel15** [comment]
I actually suggested two things: Alphabetize imports, and alphabetize props 😃
