### ISSUE TITLE
Shields for terminal

### ISSUE THREAD

**Issue by jade28** [badges/shields#2703]
Hi guys, 
I have a question: :question: Can `shields`  display on `terminal`  ?  :question: How to display it?
Thanks!

**Comment by paulmelnikow** [comment]
Like a script you can run which hits a badge URL and renders it with colors in the terminal?

**Comment by chris48s** [comment]
A couple of command line options:

1. Generate a badge image in the terminal using the NPM package: https://github.com/badges/shields/tree/master/gh-badges#on-the-console

2. Get a badge from shields.io in json on the terminal:

```sh
$ curl "https://img.shields.io/travis/rust-lang/rust.json"
{
  "name": "build",
  "value": "passing"
}
```

You could slice it and dice it from there by pipe it to [jq](https://stedolan.github.io/jq/)


Either of those do the job?

**Comment by jade28** [comment]
Thank @chris48s and @paulmelnikow . `shields ` is 🎉 awesome !!
