### ISSUE TITLE
Unable to get CircleCI badge working for private repo

### ISSUE THREAD

**Issue by paulcanning** [badges/shields#2713]
I made an API key with the `all` scope, and filled in the rest of the URL parts, but it simply states `project not found`.

`/circleci/token/<API-key>/project/bb/<owner>/<repo>/develop.svg`

**Comment by calebcartwright** [comment]
Can you try using `bitbucket` instead of `bb` for the vcsType? It looks like our badge service is expecting `github` or `bitbucket` for that param

**Comment by paulcanning** [comment]
Yea, that was it. Annoyingly, CircleCI use `bb` in their URLs when referring to a Bitbucket repo.

**Comment by calebcartwright** [comment]
Glad it's working now! And yeah the Circle API uses the full `github` and `bitbucket` values for the vcs type whereas the url for viewing jobs/projects uses the shorthands `gh` and `bb`. 

We could probably augment our example docs for the Circle badges to call that out
