### ISSUE TITLE
GitHub package.json badge croaks on dependencies with github links

### ISSUE THREAD

**Issue by AdityaTD** [badges/shields#2719]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
I'm getting `Invalid Response Data` while trying to use the badge for `package.json` version.

:link: **Link to the badge**
https://img.shields.io/github/package-json/v/AdityaTD/PenguBot.svg?style=for-the-badge

:bulb: **Possible Solution**
Not really, I'm not sure why this is happening.

**Comment by paulmelnikow** [comment]
Ah, this is a bug. Shields' schema validation for `package.json` is failing because of the github dependencies. Thanks for reporting!

**Comment by PyvesB** [comment]
Fixed in linked pull request, closing. 😉
