### ISSUE TITLE
Coverity Scan Service is Down

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#2722]
The Coverity Scan service has been offline for emergency maintenance for a couple days now. This outage means our Coverity badges are unavailable and it has also been causing our [daily builds to fail](https://circleci.com/gh/badges/daily-tests). 

There's not anything actionable we can do on our end, but opening this for awareness.

https://twitter.com/CoverityScan/status/1082446527493066752

**Comment by paulmelnikow** [comment]
https://community.synopsys.com/s/article/Coverity-Scan-Update

Why don't we deprecate this, at least temporarily. Perhaps we could use a custom message like **coverity | extended downtime** to help clarify that the problem is not with the project.

**Comment by calebcartwright** [comment]
Yeah I think that's probably a good idea considering. Should this be possible with the standard `deprecatedService` function (including with the `extended downtime` message) or will we need to do something different?

**Comment by calebcartwright** [comment]
Sounds good, I'll take a look at doing this here shortly

**Comment by calebcartwright** [comment]
I think Coverity is back online (at least in some capacity). I'll poke around and if it seems usable again I'll open a PR to un-deprecate the service
