### ISSUE TITLE
Errorneous "invalid response data"

### ISSUE THREAD

**Issue by okou19900722** [badges/shields#2729]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

 the message is invalid response data

groupId: tk.okou
artifactId: vertx-lang-jphp
link to [nexus](https://oss.sonatype.org/content/repositories/snapshots/tk/okou/vertx-lang-jphp/)

:link: **Link to the badge**

click [![a](https://img.shields.io/nexus/s/https/oss.sonatype.org/tk.okou/vertx-lang-jphp.svg)](https://img.shields.io/nexus/s/https/oss.sonatype.org/tk.okou/vertx-lang-jphp.svg)

:bulb: **Possible Solution**

none

**Comment by calebcartwright** [comment]
Can you please also add your relevant information, including the group id, artifact id, links to the Nexus repository, etc.

**Comment by okou19900722** [comment]
Edited

**Comment by calebcartwright** [comment]
FYI the Artifact Id in your POM file is showing as `vertx-lang-php-parent` https://img.shields.io/nexus/r/https/oss.sonatype.org/tk.okou/vertx-lang-php-parent.svg
Which is rendering a valid badge:
![https://oss.sonatype.org/content/repositories/releases/tk/okou/vertx-lang-jphp/3.6.0/vertx-lang-jphp-3.6.0.pom](https://img.shields.io/nexus/r/https/oss.sonatype.org/tk.okou/vertx-lang-php-parent.svg)

**Comment by okou19900722** [comment]
thanks

**Comment by calebcartwright** [comment]
The problem you see when you try to use `r` or `s` is due to the versions `3.6.0.CR1` and `3.6.0.CR2` If those had been `3.6.0-CR1` instead it would be fine. 

I'm no expert on Maven versioning, but I believe those (i.e. 3.6.0.CR1) are invalid https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8905
