### ISSUE TITLE
All GitHub badges throw error with no token set

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2754]
:question: **Question**

It used to be possible to run your dev copy with no `GH_TOKEN` set. The allowance is too low to do a full test run, but the anon allowance is enough to render a few badges in the front-end.
Now if no `GH_TOKEN` is set, all GH badges will fail to render. This is probably unexpected to new/casual contributors.

Is this change intentional, or is it a mistake that has been introduce in the recent work around server secrets/GH auth?

**Comment by paulmelnikow** [comment]
Yes, this is a usability regression that should be fixed. (I mentioned it in the top post of #2733.) Let’s track it here.

**Comment by chris48s** [comment]
Basically the issue here is that if `config.private.gh_token` is set, we'll use that. Otherwise, we'll use polling.

In reality, there should be 3 valid options:

- `config.private.gh_token` is set --> use global token
- `config.private.postgres_url` is set --> use token pooling
- neither `config.private.gh_token` nor `config.private.postgres_url` is set --> use anonymous access

The most important block is here
https://github.com/badges/shields/blob/528165f65c546af969dafa8aa0ccca89ee9740f8/services/github/github-constellation.js#L22-L44
