### ISSUE TITLE
Error has occurred when making badge

### ISSUE THREAD

**Issue by JohnTitor** [badges/shields#2784]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I tried to make the "GitHub contributors" badge, but unexpected error has occurred always.
I encounter this error on Chrome(Windows) and Safari(iOS).

<img width="433" alt="screenshot 8689412" src="https://user-images.githubusercontent.com/25030997/51274067-8df63580-1a11-11e9-8827-645223fc46e2.png">

:link: **Link to the badge**

"GitHub contributors" badge in this page(https://shields.io/#/examples/activity)

**Comment by paulmelnikow** [comment]
Thanks for reporting this. The fix is live!
