### ISSUE TITLE
Badges for Semaphore

### ISSUE THREAD

**Issue by vlasar** [badges/shields#28]
Hello,

I'm working on [Semaphore](https://semaphoreapp.com/) and would like to get it "shielded".

We uses badges for the following **build statuses**:
- passing
- pending
- failing
- unknown

Build badges from here:
![Shields Badges](https://raw.github.com/olivierlacan/shields/master/shields_white.png)

suite our color taste but we need a badge for the "unknown" status instead of the "error" status.

Could you create those badges for us or what is the standard workflow?

**Comment by stevelacey** [comment]
Would be nice if these were updated to match the new badges:

![screen shot 2015-02-17 at 12 03 25](https://cloud.githubusercontent.com/assets/289531/6227887/010a5c9a-b69d-11e4-9ae5-0c106a5a1b37.png)

**Comment by espadrine** [comment]
@stevelacey Are the Semaphore badges not defaulting to the right style? Do they rely on `?style=flat`?

**Comment by stevelacey** [comment]
@espadrine https://semaphoreapp.com/api/v1/projects/eb289e04-3982-4de1-9e66-8436a67cf607/262663/shields_badge.svg?style=flat doesn't seem to do anything – they self-hosted – so need an update? Dunno – there's a few services with outdated badges though, see https://github.com/crysalead/kahlan

**Comment by espadrine** [comment]
Indeed. @vlasar do you have information on that? Do you need help?

**Comment by vlasar** [comment]
I'm no longer working on Semaphore, but I am trying to get in touch with them. cc @markoa

**Comment by markoa** [comment]
Hi folks, it looks like it is now expected that shields.io is proxying the badge URLs to the CI service, while on Semaphore we're still hosting the images ourselves. What is the procedure to do it the proxy way?

**Comment by espadrine** [comment]
@markoa To avoid having to deal with image updates manually, the simplest way to do is to request the badge from shields.io at `https://img.shields.io/badge/build-passing-brightgreen.svg`. If possible, supporting the `?style=` modifier would be great (eg, `https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat-square`.)

If you wish to continue to self-host those badges, you can of course download them from shields.io, and update them periodically.

**Comment by markoa** [comment]
@espadrine Thanks for the explanation. I think we'll start requesting the badge from shields.io. Would it be useful to post here when we implement it?

**Comment by espadrine** [comment]
@markoa Yes! Definitely.

**Comment by stevelacey** [comment]
@markos any progress on this?

**Comment by markos** [comment]
@stevelacey wrong person :)

**Comment by stevelacey** [comment]
@markos well that's just unfair! :)

**Comment by rastasheep** [comment]
We have updated our badges to match current design used by other services. Unfortunately because we're self-hosting them, optional params for themes are not supported yet, but in future we'll provide that option too.

**Comment by NHellFire** [comment]
@rastasheep How about redirecting to shields.io (including the query string)? Then we'll have whatever customization shields.io offers. As well as they'll always match other shields badges on the same page (right now [Semaphore](https://semaphoreci.com/api/v1/renderedtext/semaphore-docs-new/branches/master/shields_badge.svg) badges are a slightly different size and text spacing to [Shields.io](https://img.shields.io/badge/build-passed-brightgreen.svg)).
