### ISSUE TITLE
Popup menu gets hidden behind rest of modal content

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2806]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

After clicking the drop-down menu to copy badge markup, the markup options appear but are partly obscured.

<img width="1067" alt="screen shot 2019-01-18 at 6 11 24 am" src="https://user-images.githubusercontent.com/1487036/51383885-a9803f80-1ae8-11e9-9a1b-b13a8999801a.png">

It's easily workaroundable, just not quite as nice as if the menu were fully visible.

:bulb: **Possible Solution**

Probably something involving z-axis?

**Comment by paulmelnikow** [comment]
Fix had to be reverted; see #3513 and #3517.

**Comment by paulmelnikow** [comment]
As I mentioned at https://github.com/badges/shields/pull/3510#issuecomment-498045780:

> I'm guessing to deal with this specific issue we'd need to find out why the `menuPlacement` prop is sometimes not working as intended and fix it upstream. Feel free to dig further if you'd like… or to find something else to tackle!

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/
Closing this issue as it relates to the previous frontend
