### ISSUE TITLE
Make PR merging easier

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2807]
We do a good job in this project making small PRs, which is great because they are easy to review. We also have really strict branch protection, requiring that tests pass in an up to date branch before merging. I think there are enough moving parts in this project that it's good that we do this; otherwise we'd have things broken often in master.

However, as a result, it takes a while to get branches merged after PR approval. There's updating the branch, waiting for tests to pass, and then merging. And worse, if another maintainer is doing this at the same time, the process has to be repeated.

I'd like to consider a couple solutions to reduce the effort needed:

1. Encourage everyone to merge PRs upon approval. Reviews are generally happening one at a time, so it's often easier – and satisfying! – to merge as the review is happening.
2. Use a merge queue, something like [bulldozer](https://github.com/palantir/bulldozer), [github-merge-bot](https://github.com/depop/github-merge-bot), or [bors](https://github.com/bors-ng/bors-ng). The way this would work is that we'd give the bot rights to merge PRs when there's an approval and the status checks pass.

**Comment by calebcartwright** [comment]
> 1. Encourage everyone to merge PRs upon approval.

Does that mean the merge responsibility will be placed on the approver?

**Comment by paulmelnikow** [comment]
> Does that mean the merge responsibility will be placed on the approver?

Maybe more like the approver is encouraged to merge. I don't want to discourage people from 👍-ing things or create more burden.

**Comment by calebcartwright** [comment]
Gotcha thanks! I'm 👍 on the proposed objectives (and automation in general!)

I've not worked with any of those bots before, but thinking through auto-merges.. I'd guess there may be some PRs where the submitter may want to get 2+ approvals vs the usual 1., and would _not_ want a bot to merge on the first approval. 

Is that a conceivable scenario, and if so does anyone with experience with any of those bots/services know if scenarios like that are supported? Would also be curious if anyone can speak to pros/cons between those offerings as well

**Comment by paulmelnikow** [comment]
Yea, that makes sense to me. Whichever tool we choose, I'd think we'd want to have a human add the PR to the merge queue.

**Comment by calebcartwright** [comment]
Ah okay, so basically the PR opener will have the ability to flag the PR as ready for the bot which lets them maintain some control, and the bots will only start on it once the approver has given the 👍 **and** our defined quality checks have been met. 

It's crazy how many cool things bots can do these days!

**Comment by paulmelnikow** [comment]
I was thinking that after the review is done, someone, either the author or the reviewer, says, "okay bot, merge!" and then it enters the queue.

**Comment by calebcartwright** [comment]
I like it!

**Comment by chris48s** [comment]
On the subject of cool things bots can do: https://github.com/jessfraz/branch-cleanup-action :smile:

**Comment by chris48s** [comment]
I had a look at enabling [repo ranger](https://reporanger.com/) for this project earlier, but I think I don't have enough permissions on the badges org to do it. I don't have badges listed in the "Account" drop-down on https://github.com/marketplace/ranger :(

**Comment by platan** [comment]
I have the same result. But https://github.com/marketplace/ranger:

> For personal accounts only
> [...]
> Contact us to beta test in org. accounts and private repos 
So it's not a matter of permissions.

**Comment by paulmelnikow** [comment]
Yea, same issue here.

I was able to add the app through https://github.com/apps/repo-ranger, want to see if you can get anywhere with that?

**Comment by chris48s** [comment]
Oh yeah. I think using the out-of-the-box config we should just be able to apply the "merge when passing" label to PRs once we've reviewed them and it will do that once the branch is up-to-date and all the tests have passed.

![Screenshot at 2019-05-30 19-29-33](https://user-images.githubusercontent.com/6025893/58655098-4a8dcb00-8311-11e9-924a-f82cb0808b9b.png)

Lets give it a go next time dependabot has a pile of PRs for us..

**Comment by paulmelnikow** [comment]
Repo Ranger is working pretty well for us! Cool with closing this?
