### ISSUE TITLE
Add an action button format

### ISSUE THREAD

**Issue by jankeromnes** [badges/shields#2824]
:clipboard: **Description**

Idea from https://github.com/badges/shields/pull/2783/files#r248766176:

> I could also see adding an action button format to Shields if there's interest. Here's some inspiration of one that I think is done well: https://devcenter.heroku.com/articles/heroku-button.

It may be useful to add a new "action button" format to Shields.io, for SVG buttons that don't show or link to the status of something, but rather offer to trigger some action.

Here are few third-party "action button" examples:

![Deploy to Heroku](https://www.herokucdn.com/deploy/button.svg)

![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)

**Comment by paulmelnikow** [comment]
Our badges were designed to show status. When they are used to invite an action I feel like the wording and message become at odds with the design:

![](https://img.shields.io/badge/deploy-to%20heroku-7057bf.svg)
![](https://img.shields.io/badge/open-in%20gitpod-1966d2.svg)
![](https://img.shields.io/gitter/room/nwjs/nw.js.svg)

So yea, I think an action format for the static badge would be a great addition to the community. We could recommend using it when there is no meaningful status to show, and the only purpose of the badge is to initiate some action.

**Comment by jankeromnes** [comment]
Another example that could be great as an action button:

[![back on open collective](https://img.shields.io/badge/back-on%20open%20collective-%233385ff.svg)](https://opencollective.com/shields)

**Comment by paulmelnikow** [comment]
It's true, though the status badges make sense:

![](https://img.shields.io/opencollective/all/shields.svg)

**Comment by chris48s** [comment]
You can get pretty close to this.. if you really want to make it with shields:

https://img.shields.io/badge/Deploy%20to%20Heroku-purple.svg?logo=heroku&logoColor=white&style=for-the-badge

![](https://img.shields.io/badge/Deploy%20to%20Heroku-purple.svg?logo=heroku&logoColor=white&style=for-the-badge)

You could supply a custom logo with base64 as well, if you wanted.. https://github.com/badges/shields/blob/master/CONTRIBUTING.md#logos I'm not sure there is a strong case to add a special style for this.

**Comment by paulmelnikow** [comment]
The for-the-badge one looks decent though I think with the rounded ones it's clearer it's an action button. I think changing the left and right text color is helpful. I also think it looks better without the text shadow, and with a little more whitespace.

**Comment by chris48s** [comment]
I think the conclusion of this was that these can already be created (with a bit of acrobatics) and over the last year or so, we've headed in the direction of removing some of the more esoteric template styles (2x popouts) and resisted adding more (e.g: the 'pill' style).
Its unlikely that we will do explicitly add another template to directly support this so I'm going to close it.
