### ISSUE TITLE
Abuse rate limiting on large PRs

### ISSUE THREAD

**Issue by chris48s** [badges/shields#2826]
@paulmelnikow  wrote:

> We're getting abuse rate limited. We use GitHub in a lot of ways so there are a lot of possibilities, though this has only happened twice and both times was while working on #2809. That makes me suspect that Danger is triggering more requests when there are lot of files changed. #2825 could also help, or perhaps dialing down the number of requests made in the integration tests.

> Aha! https://twitter.com/orta/status/1087439065321033735

Some more possible options:

* Add a flag we can use to skip the danger step of the build on large PRs?
* If we merge these 2 blocks into one loop, will that halve the number of requests? https://github.com/badges/shields/blob/558576dfb75779c8b2777f53ce1e08ca3323e250/dangerfile.js#L121-L149
* Are these checks adding enough value that they're worth the large number of requests?

**Comment by paulmelnikow** [comment]
Ha! I _just_ had the same thought. I opened #2827 a moment after this which implements (2) and a programmatic version of (1).
