### ISSUE TITLE
Add support for Bintray Latest Version Download badge

### ISSUE THREAD

**Issue by itavero** [badges/shields#284]
Bintray offers it's own Latest Version Download badge, which looks like this:
[ ![Download](https://api.bintray.com/packages/amnl/gradle/gradle-pylizard/images/download.svg) ](https://bintray.com/amnl/gradle/gradle-pylizard/_latestVersion)

As far as I know they do have a [public REST API](https://bintray.com/docs/api.html#_get_version) that gives information about the available versions.
It would be cool to have a nicely styled shield! :wink:

**Comment by espadrine** [comment]
Implemented by https://github.com/badges/shields/pull/517/files.
