### ISSUE TITLE
The AppVeyor badge shows "invalid response data" when the build is starting

### ISSUE THREAD

**Issue by justalemon** [badges/shields#2848]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I saw this problem recently on [this](https://github.com/justalemon/ServerManager) project. When the AppVeyor build is starting (the "vm" is booting up) we get `invalid response data` on the badge.

![a](https://user-images.githubusercontent.com/11861253/51566398-2e65b300-1e73-11e9-8045-35e3f3debdc8.PNG)

![b](https://user-images.githubusercontent.com/11861253/51566404-3291d080-1e73-11e9-8fb5-11e40541c68c.PNG)

:link: **Link to the badge**

https://img.shields.io/appveyor/ci/justalemon/servermanager.svg?label=appveyor

(only if the build is starting)

:bulb: **Possible Solution**

If you guys are using https://ci.appveyor.com/api/projects/justalemon/servermanager, the `status` value in `jobs` is set to `queued`:

<details><summary>Response from the API when a build is starting</summary>

```js
{
    "project": {
        "projectId": 529560,
        "accountId": 77050,
        "accountName": "justalemon",
        "builds": [],
        "name": "ServerManager",
        "slug": "servermanager",
        "repositoryType": "gitHub",
        "repositoryScm": "git",
        "repositoryName": "justalemon/ServerManager",
        "repositoryBranch": "master",
        "isPrivate": false,
        "isGitHubApp": false,
        "skipBranchesWithoutAppveyorYml": false,
        "enableSecureVariablesInPullRequests": false,
        "enableSecureVariablesInPullRequestsFromSameRepo": false,
        "enableDeploymentInPullRequests": false,
        "saveBuildCacheInPullRequests": false,
        "rollingBuilds": false,
        "rollingBuildsDoNotCancelRunningBuilds": false,
        "rollingBuildsOnlyForPullRequests": false,
        "alwaysBuildClosedPullRequests": false,
        "tags": "",
        "nuGetFeed": {
            "id": "servermanager-9g17g3c2v337",
            "name": "Project ServerManager",
            "accountId": 77050,
            "projectId": 529560,
            "isPrivateProject": false,
            "publishingEnabled": false,
            "accountTimeZoneId": "Pacific SA Standard Time",
            "created": "2019-01-04T04:33:52.0493437+00:00"
        },
        "securityDescriptor": {
            "accessRightDefinitions": [
                {
                    "name": "View",
                    "description": "View"
                },
                {
                    "name": "RunBuild",
                    "description": "Run build"
                },
                {
                    "name": "Update",
                    "description": "Update settings"
                },
                {
                    "name": "Delete",
                    "description": "Delete project"
                }
            ],
            "roleAces": [
                {
                    "roleId": 142565,
                    "name": "Administrator",
                    "isAdmin": true,
                    "accessRights": [
                        {
                            "name": "View",
                            "allowed": true
                        },
                        {
                            "name": "RunBuild",
                            "allowed": true
                        },
                        {
                            "name": "Update",
                            "allowed": true
                        },
                        {
                            "name": "Delete",
                            "allowed": true
                        }
                    ]
                },
                {
                    "roleId": 142566,
                    "name": "User",
                    "isAdmin": false,
                    "accessRights": [
                        {
                            "name": "View"
                        },
                        {
                            "name": "RunBuild"
                        },
                        {
                            "name": "Update"
                        },
                        {
                            "name": "Delete"
                        }
                    ]
                }
            ]
        },
        "disablePushWebhooks": false,
        "disablePullRequestWebhooks": false,
        "created": "2019-01-04T04:33:50.5648889+00:00",
        "updated": "2019-01-04T04:36:49.2154988+00:00"
    },
    "build": {
        "buildId": 21813816,
        "projectId": 0,
        "jobs": [
            {
                "jobId": "x40nh5t5nach3gak",
                "name": "",
                "osType": "Windows",
                "allowFailure": false,
                "messagesCount": 0,
                "compilationMessagesCount": 0,
                "compilationErrorsCount": 0,
                "compilationWarningsCount": 0,
                "testsCount": 0,
                "passedTestsCount": 0,
                "failedTestsCount": 0,
                "artifactsCount": 0,
                "status": "queued",
                "created": "2019-01-22T21:40:15.9767891+00:00"
            }
        ],
        "buildNumber": 68,
        "version": "0.4.0.68",
        "message": "Updated compatible versions of Windows",
        "messageExtended": "Based on the FXServer supported systems",
        "branch": "master",
        "isTag": false,
        "commitId": "5e93b9a5afb274573fe74a69282ac2e17ffefab1",
        "authorName": "Hannele Ruiz",
        "authorUsername": "justalemon",
        "committerName": "Hannele Ruiz",
        "committerUsername": "justalemon",
        "committed": "2019-01-22T21:40:06+00:00",
        "messages": [],
        "status": "queued",
        "created": "2019-01-22T21:40:13.8830024+00:00"
    }
}
```

</details>

**Comment by calebcartwright** [comment]
Is the `status` field set to `queued` (as shown in the API response) or as `queue` as you mentioned above?

**Comment by justalemon** [comment]
Sorry, is `queued`.

**Comment by calebcartwright** [comment]
Thanks for the clarification. `queued` is one of our known/allowed build statuses, so a `queued` status would not be an issue and would not cause the the `invalid response data` message. Appveyor schema can be viewed [here](https://github.com/badges/shields/blob/master/services/appveyor/appveyor-base.js#L8) for reference. 

I think the most likely cause would be that the Appveyor API response does not include the `jobs` key ins the response

**Comment by paulmelnikow** [comment]
@justalemon Maybe you could snag the complete API response for us the next time you see it in this state?

**Comment by justalemon** [comment]
Ehm... that is actually the complete API response.

**Comment by paulmelnikow** [comment]
Ah, I missed it there. Thanks!

**Comment by calebcartwright** [comment]
I was able to reproduce this with one of my own badges, but did not catch the API response in time. I saw this with both the Build Status badge and the Test Results badge. It was a window of only a couple seconds so I expect it will take some experimentation to grab whatever the API response is that fails our schema validation during those first couple seconds

**Comment by paulmelnikow** [comment]
I'd missed it originally, though there's an example of a failing response in the top post :)

**Comment by calebcartwright** [comment]
Yeah I saw that but I'm not 100% convinced that API response is the same as the response received on these badges. In part because that response passes our schema validation, and also based on how quickly the `invalid response data` message goes away

**Comment by calebcartwright** [comment]
I'm trying to trigger a build and fire off an API request immediately after to see if I can't get a response that will fail our validation, but the short time window makes it tricky. I also wonder if some of this depends on things on the Appveyor side which are non-deterministic (how long between commit hook and job queue, etc.)

**Comment by arcanedev-maroc** [comment]
Same issue here: ![Insight Badge](https://img.shields.io/sensiolabs/i/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat-square)

Repo: https://github.com/ARCANEDEV/noCAPTCHA

**Comment by paulmelnikow** [comment]
@arcanedev-maroc That's a different badge; could you open a new issue?

**Comment by arcanedev-maroc** [comment]
Hi @paulmelnikow 

I've create a new issue :+1: 

Issue: https://github.com/badges/shields/issues/2928

**Comment by calebcartwright** [comment]
Alright I've found the underlying issue. Once a new build is triggered there's a period of time (duration is typically brief, but does last a little while at times) where the job is in a `starting` state which is not in our list of expected build statuses. 

Here's a subset of the json response that shows the starting state:
```json
"build": {
  "buildId": 22249956,
  "projectId": 0,
  "jobs": [...],
  "buildNumber": 63,
  "version": "63",
  "message": "chore: dep version and meta updates",
  "branch": "npm-audit",
  "isTag": false,
  "commitId": "4e255a45546c115eb6f332d52deee4a9b781ba54",
  "authorName": "calebcartwright",
  "authorUsername": "calebcartwright",
  "committerName": "calebcartwright",
  "committerUsername": "calebcartwright",
  "committed": "2019-02-09T21:15:17+00:00",
  "messages": [],
  "status": "starting",
  "created": "2019-02-09T21:15:32.1378654+00:00",
  "updated": "2019-02-09T21:15:37.5069415+00:00"
}
```
