### ISSUE TITLE
Support for Ansible Galaxy

### ISSUE THREAD

**Issue by tersmitten** [badges/shields#286]
There's a REST API available [at](https://galaxy.ansible.com/api/).

* Example [user call](https://galaxy.ansible.com/api/v1/users/5826/)
* Example [role call](https://galaxy.ansible.com/api/v1/roles/1354/)

**Comment by igormukhingmailcom** [comment]
Hi, @espadrine!
For example, I have some ansible role at https://github.com/ansible-roles/ansible-role-sublimetext3_packagecontrol and published at Galaxy https://galaxy.ansible.com/list#/roles/3078

So, 3078 is the role ID that used in API calls.

I think there will be cool if next badges for ansible will be available at shields.io:

Badge Name | API Call URL | Keys used to generate result | Result / Badge Value example
--- | --- | --- | ---
Role name | https://galaxy.ansible.com/api/v1/roles/3078/ | summary_fields->owner->username + '.' + name | igor_mukhin.sublimetext3_packagecontrol
Minimum ansible version | https://galaxy.ansible.com/api/v1/roles/3078/ | min_ansible_version | 1.4 
Versions count | https://galaxy.ansible.com/api/v1/roles/3078/versions/ | count | 3
Latest version | https://galaxy.ansible.com/api/v1/roles/3078/versions/ | first(results)->name | v0.2.0

To generate all this badges we need get only role ID from user. Or even just role's galaxy URL and then automatically extract ID from hash.

**Comment by espadrine** [comment]
Thanks a lot for this information! That is tremendously helpful.

I notice that they send a cookie (`Set-Cookie: sessionid=oxd81rvw70noo42xqwg594t6ngc8ncsq; expires=Mon, 25-May-2015 19:16:28 GMT; httponly; Max-Age=1209600; Path=/`), that is a bit odd. Otherwise, it all seems straightforward.

**Comment by igormukhingmailcom** [comment]
@espadrine Don't think that cookies matter something.
You can just get information and not care about cookies.

Try `wget -qO - https://galaxy.ansible.com/api/v1/roles/3078/versions/`.

**Comment by igormukhingmailcom** [comment]
@espadrine Hi. How can I help you to force some progress on this?

**Comment by espadrine** [comment]
I tried making the first one, with this kind of style: ![](http://img.shields.io/badge/role-igor_mukhin.sublimetext3_packagecontrol-blue.svg)

I am unsure of whether that suits the notion of "role" that users are familiar with, or how easy it is to figure out where to find the role id.

**Comment by igormukhingmailcom** [comment]
Oh, cool :)

Role Id assigned to role once it added to galaxy.
For example this is list of my roles: https://galaxy.ansible.com/list#/users/9737

**Comment by smiller171** [comment]
@igormukhingmailcom does getting the information like this still work? I can't find IDs on my roles.

**Comment by tersmitten** [comment]
Ansible galaxy 2 uses "name based" urls now, but old urls should be
redirected.

**Comment by smiller171** [comment]
Sounds like we probably need a PR to fix this functionality then

**Comment by danvaida** [comment]
@smiller171 here's a one-liner for finding your role's ID once it's on Galaxy:
```
$ ansible-galaxy info YourUser.RoleName | grep -E 'id: [0-9]' | awk {'print $2'}
```
This works on Ansible `2.2.2.0` but I recon it's working on older versions, too.

**Comment by quocvu** [comment]
@igormukhingmailcom how did you get the 3078 id for your role?

**Comment by andy-maier** [comment]
Since this issue comes up at the top of the result list when searching for how to get a badge that shows the latest version of a collection on Ansible Galaxy, I'll post our solution for that.

Ansible Galaxy returns the latest version of a collection using an HTTP GET on
https://galaxy.ansible.com/api/v2/collections/{NS}/{COLL}/ as follows:
```
{
    . . .
    "latest_version": {
        "version": "1.0.0-dev1",
    }
}
```

That allows using the dynamic badge creation feature of shields.io, e.g. in Markdown syntax:

```
![Version on Galaxy](https://img.shields.io/badge/dynamic/json?style=flat&label=galaxy&prefix=v&url=https://galaxy.ansible.com/api/v2/collections/ibm/ibm_zos_core/&query=latest_version.version)
```

Resulting in this badge:

![Version on Galaxy](https://img.shields.io/badge/dynamic/json?style=flat&label=galaxy&prefix=v&url=https://galaxy.ansible.com/api/v2/collections/ibm/ibm_zos_core/&query=latest_version.version)

**Comment by calebcartwright** [comment]
Thanks for sharing @andy-maier! Given the above, it seems like we should be able to add a native version badge if you or anyone else would be interested in submitting a PR

**Comment by IronTooch** [comment]
For anyone who finds this search, you can use the API to query for a role directly. E.g.

`https://galaxy.ansible.com/api/v1/roles/?search=myrole`

And once you get the role ID, you can use this to get the downloads count:

https://img.shields.io/badge/dynamic/json?color=blueviolet&label=Galaxy%20Downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2FROLEID%2F%3Fformat%3Djson
