### ISSUE TITLE
Badge request: JSDelivr

### ISSUE THREAD

**Issue by douglasg14b** [badges/shields#2862]
:clipboard: **Description**

Add a badge for the JSDeliver Service for versioning.

The version information for a package can be retrieved from their API https://github.com/jsdelivr/data.jsdelivr.com#list-package-versions

**Comment by calebcartwright** [comment]
Thanks for the suggestion! We've got a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) for writing new services if anyone would like to work on this!

**Comment by paulmelnikow** [comment]
They also have [download stats](https://www.jsdelivr.com/blog/jsdelivr-reloaded-2017/)!

This would be a high impact badge to implement.
