### ISSUE TITLE
Add UI elements for the remaining badge options

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2867]
:clipboard: **Description**

#2496 and #2554 made a big step forward in the modal popup.

One of the big pieces of functionality left is to add UI elements for all the badge options, preferably in a way that doesn't clutter up the UI for rarely used options.

I've an idea of how that could work and probably could work it up in Sketch or a wireframe first.

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/
Closing this issue as it relates to the previous frontend

If this one is still relevant in the new design, lets re-frame it in a new issue
