### ISSUE TITLE
Accessibility status for locations via wheelmap.org

### ISSUE THREAD

**Issue by rubiii** [badges/shields#287]
Hey,

I would like to add support for a badge displaying the accessibility status for a location (or node as they call it) via wheelmap.org. This could be implemented by having the user provide a node-id and then just return a green-yellow-red-grey badge depending on the status for that location.

The accessibility for a location can be retrieved from wheelmap.org via a simple GET request and the status is in that JSON under node/wheelchair. it’s one of "yes", "no", "limited" or "unknown".

http://wheelmap.org/nodes/2323004600.json

What do you think?

**Comment by PyvesB** [comment]
We'vre done some work to rewrite and modernise these badges in #2486. They will soon be working as expected again! 😉
