### ISSUE TITLE
How to gen contributor img profile

### ISSUE THREAD

**Issue by umanusorn** [badges/shields#2881]
:question: **Question**
How to gen contributor img profile like this
![image](https://user-images.githubusercontent.com/1754362/51809489-e2cc6280-22d3-11e9-80de-5d574d9fdc8a.png)

**Comment by calebcartwright** [comment]
If you take a look at the [raw version of our README file](https://raw.githubusercontent.com/badges/shields/master/README.md) you can see a detailed reference on how this is done, but basically it's the Contributors svg for our [Shields collective](https://opencollective.com/shields) on [open collective](https://opencollective.com) with a specified width 

https://opencollective.com/shields/contributors.svg?width=890

**Comment by umanusorn** [comment]
Is there a way to gen for any other repo?

**Comment by umanusorn** [comment]
Thanks I wish to have a link to   **open collective that I need to register over there and set things up**

**Comment by calebcartwright** [comment]
I included the link in my initial response

https://opencollective.com/
