### ISSUE TITLE
Add support for bountysource.com

### ISSUE THREAD

**Issue by lo1tuma** [badges/shields#289]
It would be awesome if you support bountysoure.com badges.

A badge looks like this:
[![Bountysource](https://www.bountysource.com/badge/team?team_id=133&style=bounties_received)](https://www.bountysource.com/teams/mozilla/issues?utm_source=Mozilla&utm_medium=shield&utm_campaign=bounties_received)

They have an API it is documented [here](http://bountysource.github.io/).

**Comment by svnpenn** [comment]
https://github.com/bountysource/bountysource.github.io/issues/7

**Comment by svnpenn** [comment]
https://github.com/bountysource/core/issues/978
