### ISSUE TITLE
shields.io with self-host gitlab & private repo

### ISSUE THREAD

**Issue by gkl1368** [badges/shields#2911]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I used my own gitlab instance and private repo. When I used with shield.io, the link is: https://img.shields.io/badge/dynamic/json.svg?label=build&colorB=brightgreen&&query=$.last_pipeline.status&url=https://${gitlab_url}/api/v4/projects/${projects_id}/repository/commits/master?private_token=${private_toke}
but it always shows 
![image](https://user-images.githubusercontent.com/12904884/52172665-67752000-27af-11e9-95be-f70a150f99af.png)
And I confirm that url with my gitlab_url has correct answer with json format
![image](https://user-images.githubusercontent.com/12904884/52172696-1154ac80-27b0-11e9-90a7-9d1b7a904a50.png)

UPDATE：
  When url link is ecc certificate， it will show inaccessible. But when you use rsa certificate, it will be ok.

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by gkl1368** [comment]
When I used encoded url after url= , like 
https://img.shields.io/badge/dynamic/json.svg?label=build&colorB=brightgreen&&query=$.last_pipeline.status&url=https%3A%2F%2F${gitlab_url}%2Fapi%2Fv4%2Fprojects%2F${project_id}%2Frepository%2Fcomm
its%2Fmaster%3Fprivate_token%3D${private_token}

It also shows inaccessible

**Comment by paulmelnikow** [comment]
There's a double && in there that should be a single &. And maybe URL-encode the query too?

**Comment by gkl1368** [comment]
I have tried a single & and url_encode the query, like this link:
https://img.shields.io/badge/dynamic/json.svg?label=build&colorB=brightgreen&query=%24.last_pipeline.status&url=https%3A%2F%2F${gitlab_url}%2Fapi%2Fv4%2Fprojects%2F7%2Frepository%2Fcommits%2Fmaster%3Fprivate_token%3D${private_toke}

but nothing changes, also shows  inaccessible

**Comment by gkl1368** [comment]
I used public shield.io not self-host

**Comment by calebcartwright** [comment]
Perhaps this would be more easily accomplished using the new Endpoint service badge (https://github.com/badges/shields/issues/2838)?

It looks like with this current approach you are hardcoding the badge color to brightgreen, regardless of the pipeline status. If you deployed a custom endpoint it might make debugging a bit easier and allow for some custom logic around status, etc.

**Comment by gkl1368** [comment]
I have try to delete &colorB=brightgreen in the links, but no changes.

**Comment by gkl1368** [comment]
When I try with endpoint with json file, it also show inaccessable

**Comment by calebcartwright** [comment]
> When I try with endpoint with json file, it also show inaccessable

Sorry I don't understand what you mean. If you have developed, and deployed a custom endpoint that you are using with the Endpoint badge, can you please share the link to your Endpoint?

**Comment by gkl1368** [comment]
Now I use this link: https://img.shields.io/badge/endpoint.svg?url=https://badge.kellyok.tk/dnsmasq/build.json

**Comment by gkl1368** [comment]
I found the problem, If use ecc certificate in url, it will show inaccessable, but if use rsa certificate, it's ok, no problem.

**Comment by paulmelnikow** [comment]
Huh, I wonder if that's related to #2812.

**Comment by gkl1368** [comment]
So how can i solve this problem?

**Comment by paulmelnikow** [comment]
We'll work on updating our Node client in #2812 which might help, and hopefully will add our own GitLab badges in #2771, which could then be used with self-hosting for private repos.

Beyond that, there isn't enough information here to solve this. I'm sorry.

**Comment by jgroom33** [comment]
this works:

h_t_t_p_s://img.shields.io/badge/dynamic/json?color=blue&label=extracted_version&query=version&url=https%3A%2F%2F`your_host`%2Fapi%2Fv4%2Fprojects%2F%{project_id}%2Frepository%2Ffiles%2Fversion%252Ejson%2Fraw%3Fref%3Dmaster%26private_token%3D`your_token`

^ this extracts the version property from a file version.json in the master branch
