### ISSUE TITLE
Mozilla Observatory (HTTP security headers rating)

### ISSUE THREAD

**Issue by yvele** [badges/shields#2912]
:clipboard: **Description**

A clear and concise description of the new badge.

- Which service is this badge for
  - [Mozilla Observatory](https://observatory.mozilla.org/)
- What sort of information should this badge show?
  - Grade and score `observatory | A+ (115/100)`
  - With the appropriate grade color
  - Link should point to https://observatory.mozilla.org/analyze/github.com
- Examples (with the [exact same colors](https://github.com/mozilla/http-observatory-website/blob/master/css/httpobs.css) used on https://observatory.mozilla.org)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-2d882d.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-B%20(80/110)-aaaa39.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-C+%20(65/110)-aa7039.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-D--%20(15/110)-652770.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-F%20(0/110)-aa3939.svg)](https://observatory.mozilla.org/analyze/baidu.com)

:link: **Data**

- Is there a public API?
  - https://http-observatory.security.mozilla.org/api/v1/analyze?host=github.com
- Does the API requires an API key?
  - No
- Link to the API documentation.
  - https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md

This issue is related to https://github.com/mozilla/http-observatory/issues/96

:microphone: **Motivation**

Show Website HTTP security headers rating/score, and promote HTTP header configuration for a safer internet. See real time rating, and detect miss configurations.

**Comment by yvele** [comment]
With the [exact same colors](https://github.com/mozilla/http-observatory-website/blob/master/css/httpobs.css) used on https://observatory.mozilla.org), the badges looks a bit sad
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-2d882d.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-B%20(80/110)-aaaa39.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-C+%20(65/110)-aa7039.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-D--%20(15/110)-652770.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-F%20(0/110)-aa3939.svg)](https://observatory.mozilla.org/analyze/baidu.com)

Should we use custom colors?

  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-B%20(80/110)-green.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-C+%20(65/110)-yellow.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-D--%20(15/110)-orange.svg)](https://observatory.mozilla.org/analyze/github.com)
  - [![Mozilla Observatory](https://img.shields.io/badge/observatory-F%20(0/110)-red.svg)](https://observatory.mozilla.org/analyze/baidu.com)

**Comment by calebcartwright** [comment]
Personally, I think I prefer the second set of colors. Are the grade values you have listed the complete set or just a sample (for example is there an `A-`, `B+`, etc.)?

I suppose we could pick a default color scheme and also include a param (probably a query param) on the badge that would allow the user to pick the other if he/she preferred that

**Comment by paulmelnikow** [comment]
Agreed that the Shields color scheme looks better and a bit clearer.

Also a thought on the text formatting: we could split these into two separate badges like we do with Code Climate coverage and maintainability badges. So the user can choose between a tidy letter grade and a tidy **65/110** score, as they prefer. I don't mind supporting this format as a third option if you feel strongly about it @yvele.

**Comment by yvele** [comment]
I personally would prefer choosing between a short `grade` badge and a medium `grade (score/100)` badge instead of a naked `score/100`. Observatory grade should always be present. Does that make sense?

- Short: [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+%20(115/110)-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)
- Long: [![Mozilla Observatory](https://img.shields.io/badge/observatory-A+-brightgreen.svg)](https://observatory.mozilla.org/analyze/github.com)

**Comment by yvele** [comment]
We need to describe the cache behaviour in the documentation, something like

> The badge return a cached site result if the site has been scanned anytime in the previous 24 hours. If you need to force invalidating the cache, you can to do it manually through the [Mozilla Observatory Website](https://observatory.mozilla.org)

**Comment by yvele** [comment]
We need to handle a `hidden` badge parameter not to include the site in the public results 🚨 

The `hidden` parameter can be passed straight to the Observatory API call, see https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#invoke-assessment

**Comment by paulmelnikow** [comment]
I like the idea of the short and long forms. Maybe calling it `grade` and something like `long` or `full` would give us room to add a number badge in the future if there’s demand.

Makes sense about hidden. I wonder if we should make hidden the default, and let people opt in to publishing. That seems less unexpected.

> The badge return a cached site result if the site has been scanned anytime in the previous 24 hours. If you need to force invalidating the cache, you can to do it manually through the [Mozilla Observatory Website](https://observatory.mozilla.org)

Good call. Let’s make it clear it’s the service that’s doing the caching here — and that the Shields cache is on top of that.

> After running an analysis, Mozilla Observatory caches results for 24 hours. You can trigger a re-scan through the [Mozilla Observatory website](https://observatory.mozilla.org). Shields’ own caching may cause stale results to appear for a few minutes after Mozilla Observatory updates.

**Comment by yvele** [comment]
The Mozilla Observatory API has 2 relevant endpoints for our use case.

Actually in my PR I'm using the **[Retrieve Assessment](https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#retrieve-assessment)** GET endpoint.

> Retrieve the results of an existing, ongoing, or completed scan
>
>  - URL: `/api/v1/analyze?host=www.mozilla.org`
>  - Method: `GET`

<details><summary>The problem is that this endpoint is NOT triggering a scan, but only retrieving existing results.</summary>
<p>

This will return an error if the host has never been scanned:

`{"error":"recent-scan-not-found","text":"Recently completed scan for foo.com not found"}`

We will the have to handle an unknown badge:

[![Mozilla Observatory](https://img.shields.io/badge/observatory-unknown-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)

The user will have to click on the badge and trigger a scan manually (choosing itself whether the result is hidden or public). But we still have the problem that the scan result will NEVER be updated with that implementation (I'm not talking about cache).

</p>
</details>

<br>

I need to switch to the **[Invoke Assessment](https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#invoke-assessment)** endpoint

> Invoke a new scan of a website. Will return a cached site result if the site has been scanned anytime in the previous 24 hours
>
>  - URL: `/api/v1/analyze?host=www.mozilla.org`
>  - Method: `POST hidden=true&rescan=true`

Note that the documentation says that this cannot be called at a frequency greater than every 3 minutes, but I've not seen any errors 🤔 (only cached results.. which is ok for us)

The only thing with this POST endpoint is that the grade and score will be unknown while the scan is running for the first time, I'll get those responses:

```json
{
  "algorithm_version": 2,
  "end_time": null,
  "grade": null,
  "hidden": true,
  "likelihood_indicator": null,
  "response_headers": null,
  "scan_id": 9948017,
  "score": null,
  "start_time": "Sat, 09 Feb 2019 17:26:16 GMT",
  "state": "PENDING",
  "status_code": null,
  "tests_failed": 0,
  "tests_passed": 0,
  "tests_quantity": 12
}
```

```json
{
  "algorithm_version": 2,
  "end_time": null,
  "grade": null,
  "hidden": true,
  "likelihood_indicator": null,
  "response_headers": null,
  "scan_id": 9948019,
  "score": null,
  "start_time": "Sat, 09 Feb 2019 17:28:28 GMT",
  "state": "RUNNING",
  "status_code": null,
  "tests_failed": 0,
  "tests_passed": 0,
  "tests_quantity": 12
}
```

We need to handle that in the badge with 2 additional states:

[![Mozilla Observatory](https://img.shields.io/badge/observatory-pending-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)
[![Mozilla Observatory](https://img.shields.io/badge/observatory-running-lightgrey.svg)](https://observatory.mozilla.org/analyze/github.com)

**Comment by paulmelnikow** [comment]
If we only used the retrieve endpoint, would it show a stale result as time goes by? Or does it cache for a while and then revert to unknown? Or rescan?

**Comment by yvele** [comment]
Retrieve endpoint only get the last result and don't scan or re-scan. The invoke endpoint definitely is the way to go (PR already updated).

Now I only need to add the documentation part, the `public` param and the `long`/`short` param

**Comment by paulmelnikow** [comment]
It would be helpful to get clarification from Mozilla Observatory that what we're doing is okay with them. Out of curiosity, have you been in touch with anyone there?

**Comment by yvele** [comment]
> It would be helpful to get clarification from Mozilla Observatory that what we're doing is okay with them.

Sure.. but we're not doing crazy stuff anyway.
You're afraid that may trigger too many requests?

> Out of curiosity, have you been in touch with anyone there?

Nope... I posted a message here https://github.com/mozilla/http-observatory/issues/96 but get no responses

**Comment by yvele** [comment]
@paulmelnikow I asked for a review and apparently it's ok for @april

> That works for me! :)

and @jeffbryner

> LGTM

**Comment by calebcartwright** [comment]
The Mozilla folks have given the 👍 and the PR is looking good. I just wanted to confirm that we don't want to support the 3 badge formats:

1. grade, ex `A-`
2. score, ex `115/100`
3. long/both, ex `A+ (135/100)`

And that we only need options 1 and 3? If we don't think we need option 2 then I think that is okay (we could always add it later down the road by adding a `score` route option if users ask for it)

**Comment by yvele** [comment]
Yes the grade is the most important thing and always should be present.

**Comment by yvele** [comment]
There also is a case when the score is at max (`135` actually, but can be determined in API response when there is [no more change recommendation](https://observatory.mozilla.org/analyze/observatory.mozilla.org) 🎉) we can make a special things in the badge ( party 🎉 emoji? Make a `A++` grade?) but this can be discussed later.. and should even be discussed in https://github.com/mozilla/http-observatory 

Let's keep things simple.. and release the badge
