### ISSUE TITLE
HSTS preload list status (HTTP security)

### ISSUE THREAD

**Issue by yvele** [badges/shields#2913]
:clipboard: **Description**

A clear and concise description of the new badge.

- Which service is this badge for
  - [Chrome's HTTP Strict Transport Security (HSTS) preload list](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
- What sort of information should this badge show?
  - HSTS status `hsts | status`
  - Status may be `preloaded`, `pending` or `unknow`
  - Link should points to https://hstspreload.org/?domain=github.com
- Examples
  - [![hsts](https://img.shields.io/badge/hsts-preloaded-brightgreen.svg)](https://hstspreload.org/?domain=github.com)
  - [![hsts](https://img.shields.io/badge/hsts-pending-green.svg)](https://hstspreload.org/?domain=apviz.io)
  - [![hsts](https://img.shields.io/badge/hsts-unknow-red.svg)](https://hstspreload.org/?domain=baidu.com)

Edit: Replace `no` with `unknow`

:link: **Data**

Where can we get the data from?

- Is there a public API?
  - https://hstspreload.org/api/v2/status?domain=github.com
- Does the API requires an API key?
  - No
- Link to the API documentation.
  - https://hstspreload.org/

Edit: Replace `no` with `unknow`

:microphone: **Motivation**

Please explain why this feature should be implemented and how it would be used.

- What is the specific use case?
  - Show HTST approval status.
  - Track approval and regressions in real time. Alert on potential miss configuration.
  - Promote security for a safer Internet

Kind of related to #2912 and https://github.com/mozilla/http-observatory/issues/96

**Comment by pxgamer** [comment]
I've started work on this in a [feature branch][branch].

I noticed that the API returns `unknown` rather than `no` for both invalid and non-preload URIs. Should I keep it as `no` in the badge content?

[branch]: https://github.com/badges/shields/compare/master...pxgamer:feature/hsts-badge?files=1

**Comment by paulmelnikow** [comment]
> I noticed that the API returns `unknown` rather than `no` for both invalid and non-preload URIs. Should I keep it as `no` in the badge content?

How about **not preloaded**?

**Comment by calebcartwright** [comment]
> How about **not preloaded**?

I'd vote for that as well

**Comment by pxgamer** [comment]
@paulmelnikow, that sounds good to me. :+1:

I think that the Firefox HSTS list is based on Chromes list afaik. :thinking: But if mentioning Chrome is more useful, I'm up for that.

**Comment by yvele** [comment]
Yes Firefox use the same list

> Most major browsers (Chrome, Firefox, Opera, Safari, IE 11 and Edge) also have HSTS preload lists based on the Chrome list. (See the HSTS compatibility matrix.)

**Comment by yvele** [comment]
> I've started work on this in a [feature branch](https://github.com/badges/shields/compare/master...pxgamer:feature/hsts-badge?files=1).
> 
> I noticed that the API returns `unknown` rather than `no` for both invalid and non-preload URIs. Should I keep it as `no` in the badge content?

Maybe `unknow` (red) is more explicit 🤔

**Comment by yvele** [comment]
> > How about **not preloaded**?
> 
> I'd vote for that as well

**Comment by pxgamer** [comment]
Ok 👍 Will change to unknown again 😋

And yeah, I was just using your examples for the colours 👍

**Comment by yvele** [comment]
Yeah pending is a good thing but it's still not preloaded.. I was thinking about yellow (less alarmist than orange) 🤔 


  - [![hsts](https://img.shields.io/badge/hsts-preloaded-brightgreen.svg)](https://hstspreload.org/?domain=github.com)
  - [![hsts](https://img.shields.io/badge/hsts-pending-yellow.svg)](https://hstspreload.org/?domain=apviz.io)
  - [![hsts](https://img.shields.io/badge/hsts-unknow-red.svg)](https://hstspreload.org/?domain=baidu.com)

**Comment by pxgamer** [comment]
That sounds great to me. 👍

**Comment by calebcartwright** [comment]
I'm a little confused how we could go from a message indicative of a definitive "no" to an inconclusive "unknown" state. 

I know you'd prefer the `hsts` label, but if you want to use green|yellow|red badge colors then I'd suggest considering a badge label such as `hsts preloaded` with statuses such as `yes, pending, no`.

The concern with using `unknow` (which I assume should actually be `unknown`) is that badge colors are all associated with a status, and red is indicative of failure. It looks odd to have a color indicating failure with a conflicting, inconclusive message

**Comment by yvele** [comment]
> I'm a little confused how we could go from a message indicative of a definitive "no" to an inconclusive "unknown" state.

Because when I made the issue I was stupid, and only thinking about myself. I prefer matching the HSTS workflow semantics

> I know you'd prefer the `hsts` label, but if you want to use green|yellow|red badge colors then I'd suggest considering a badge label such as `hsts preloaded` with statuses such as `yes, pending, no`.

If you are choosing to add an `hsts` badge to your readme, of course `unknow` is a failure, and should be red. Otherwise you don't add an `hsts` badge at all.

> The concern with using `unknow` (which I assume should actually be `unknown`) is that badge colors are all associated with a status, and red is indicative of failure. It looks odd to have a color indicating failure with a conflicting, inconclusive message

The thing with hsts and `unknown` (not `unknow` 😉 ) is that the API returns the same state whatever you have an hsts HTTP header, set to preload or not, and submitted or not. That's why there only is an `unknown` I think 🤔 

Let's focus on the badge and NOT on the hsts API.. of let's open an issue on their repo 😄 

My opinon: Stick to the API, focus on the badge

**Comment by paulmelnikow** [comment]
What we do at Shields is make badges that convey information as clearly as possible. That sometimes means using slightly different semantics or terminology than upstream APIs. We value consistency and clarity in the badges over strict adherence to the upstream terminology. You'll find lots of examples of code in Shields that smooths out the rough edges in APIs. Not that we always do this perfectly! But it's what we strive for. That's the sense in which we focus on the badge.

An argument could be made that **unknown** makes sense from the context of the API. However in the context of a badge, I agree with @calebcartwright that **unknown** is completely uninformational. It sounds like a transient error, whereas the intended message is "this host is not in the list." That's not the absence of information, it's a real failure.

I still think **not preloaded** could work, and to avoid any confusion with **pending**, that could be changed to **preload pending**.

Other possible alternatives: **unknown host** or **not listed**.

**hsts preload** is tempting, though since "preload" is more of a state than a noun, it feels nicer to push it into the right text if possible. Maybe **commit status | in master** is analogous: it's better than **commit merged to master | yes**.

**Comment by pxgamer** [comment]
I understand that `unknown` isn't particularly helpful, `not preloaded` is what is shown when using the [hstspreload.org](https://hstspreload.org) website. @paulmelnikow, so you are suggesting the following? 🙂

![](https://img.shields.io/badge/hsts-preloaded-brightgreen.svg)
![](https://img.shields.io/badge/hsts-preload%20pending-yellow.svg)
![](https://img.shields.io/badge/hsts-not%20preloaded-red.svg)

And @calebcartwright is suggesting:

![](https://img.shields.io/badge/hsts%20preloaded-yes-brightgreen.svg)
![](https://img.shields.io/badge/hsts%20preloaded-pending-yellow.svg)
![](https://img.shields.io/badge/hsts%20preloaded-no-red.svg)

Personally I prefer the first, but I think I'll wait until we come to a conclusion before updating to the final look. 😋

**Comment by yvele** [comment]
@paulmelnikow thanks for your arguments, I agree 👍 

@pxgamer I also personally prefer the first 👍

**Comment by yvele** [comment]
@paulmelnikow thanks for your arguments, I agree 👍 

@pxgamer the second proposition from @calebcartwright looks super clean 😮 👍

**Comment by paulmelnikow** [comment]
> **hsts preload** is tempting, though since "preload" is more of a state than a noun, it feels nicer to push it into the right text if possible. Maybe **commit status | in master** is analogous: it's better than **commit merged to master | yes**.

This is my response from above.

Think I still feel that way; that

![](https://img.shields.io/badge/hsts-preloaded-brightgreen.svg)

conveys meaning more elegantly than

![](https://img.shields.io/badge/hsts%20preloaded-yes-brightgreen.svg)

in a similar way that

![](https://img.shields.io/badge/commit%20status-in%20master-brightgreen.svg)

is more elegant than

![](https://img.shields.io/badge/commit%20merged%20to%20master-yes-brightgreen.svg)

**Comment by yvele** [comment]
Yeah but the badge is much more about specific **HSTS preaload service** than [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) in general.

The [HSTS preload service](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Preloading_Strict_Transport_Security) is not part of the HSTS (HTTP Strict-Transport-Security) specification.

It may be important not to reduce HSTS to HSTS preloading, and to be explicit in the label of that specific badge 🤔

**Comment by yvele** [comment]
Chromium is a bit restrictive as the list is used by Chrome, Firefox, IE, etc...

> Most major browsers (Chrome, Firefox, Opera, Safari, IE 11 and Edge) also have HSTS preload lists based on the Chrome list. 

https://hstspreload.org/

Also it's a bit long for nothing..

**Comment by pxgamer** [comment]
That seems quite long. But it definitely is informative on which hsts this is.

Thinking about this, should the links stay as `/hsts/{uri}.svg`, or be something like `/hsts/preload/{uri}.svg`?

**Comment by yvele** [comment]
To the best of my knowledge there is only one HSTS preload list 😉

**Comment by pxgamer** [comment]
I haven't heard of any others, but it is the Chromium project's list. :yum: I'm not too bothered about whether or not we include Chromium.

**Comment by yvele** [comment]
[![hsts](https://img.shields.io/badge/google%20open%20source%20chromium%20hsts%20preloaded-yes-brightgreen.svg)](https://hstspreload.org/?domain=github.com) come on 🙄 

Some people have to show many badge, on a single table in a readme.. one row of badge per environments. The name "Chromium" adds no relevant informations.. it's quite implicit to the HSTS preload list project.

**Comment by paulmelnikow** [comment]
My concern is about providing enough context to people who are reading this badges, particularly those who haven't heard of this. Let's keep the feedback constructive, please.

After reading some more and marinating for a couple days, I'm think I'm convinced. Let's do this:

1. Keep the badge label **hsts preloaded** with **yes**, **pending**, **no**.
2. Put "Chromium" in the **title** in the Shields badge listing, e.g. **Chromium HSTS preload**.
3. Link to the [HSTS preload list](https://github.com/chromium/hstspreload) and the [list submission site](https://hstspreload.org/) in the badge **documentation**.

**Comment by yvele** [comment]
@paulmelnikow super cool!

Juste a little thing about the documentation, are you sure you want to link to the HSTS preload list on GitHub https://github.com/chromium/hstspreload instead of the main Chromium project page https://www.chromium.org/hsts ?

**Comment by paulmelnikow** [comment]
Hah, no, I think I must be confusing that repo with some other page I was looking at. I thought the actual list was in that repo, though it's somewhere else entirely: https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json

Honestly none of these links are very newcomer friendly! Though I guess https://chromium.org/hsts is the closest.

**Comment by pxgamer** [comment]
Just pushed points 1 and 2. For number 3, where do I add the links to?

**Comment by paulmelnikow** [comment]
How's this sound?

> [`Strict-Transport-Security` is an HTTP response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) that signals that browsers should only access the site using HTTPS.
>
> For a higher level of security, it's possible for a domain owner to [preload this behavior into participating web browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Preloading_Strict_Transport_Security). Chromium maintains the [HSTS preload list](https://www.chromium.org/hsts), which is the de facto standard that has been adopted by several browsers. This service checks a domain's status in that list.

**Comment by pxgamer** [comment]
@paulmelnikow, here's how it looks:
![image](https://user-images.githubusercontent.com/1899334/52468930-06b85f80-2b82-11e9-8f41-5f961bd4c81d.png)

**Comment by yvele** [comment]
@paulmelnikow Your intro is nice, but yes we should use https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Preloading_Strict_Transport_Security intro as it specify those really important things:

> While the service is hosted by Google, all browsers have stated an intent to use (or actually started using) the preload list. However, it is not part of the HSTS specification and should not be treated as official.

**Comment by paulmelnikow** [comment]
Can you add it to the PR? The formatting looks odd. Are you using <p> tags?

No worries if it doesn’t look perfect. The frontend styling is a work in process.

**Comment by pxgamer** [comment]
@paulmelnikow, done. It's using `<p>` tags, but should it be all one line? Or is there a line-length limit? (I wrapped it a bit.

**Comment by paulmelnikow** [comment]
It’s interpreted as plain HTML which isn’t whitespace sensitive (a space and a newline are treated the same). So line breaks are fine.
