### ISSUE TITLE
Bug Badge GitHub package.json version

### ISSUE THREAD

**Issue by Angelk90** [badges/shields#2927]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Hi @paulmelnikow : 
The Badge relating to the "GitHub package.json version" and "GitHub package.json version (branch)" does not seem to work anymore.
Each time the result is "Invalid response data".

:link: **Link to the badge**
https://img.shields.io/github/package-json/v/react-native-community/react-native-camera.svg?style=flat

**Comment by paulmelnikow** [comment]
Hi! Could you try validating your `package.json`?

**Comment by Angelk90** [comment]
@paulmelnikow :  I tried them with my first but it does not work, so I put one that could take as an example a lot better.

**Comment by Angelk90** [comment]
@paulmelnikow : What do you mean exactly?
Same problem in the readme on npm.

**Comment by Angelk90** [comment]
@paulmelnikow : What do you mean exactly?
Same problem in the readme on npm.

is a site problem: https://shields.io/#/examples/version

Why the site: https://shields-staging.herokuapp.com/#/examples/version

It works from the right result.

**Comment by paulmelnikow** [comment]
For some reason, probably related to our GitHub code, the bug manifests in production but not in development or staging.

**Comment by Angelk90** [comment]
@paulmelnikow : So we just have to wait?

**Comment by paulmelnikow** [comment]
Is this a published npm package? You could use the npm version badge instead.

**Comment by chris48s** [comment]
This seems to be broken for everything that uses `fetchJsonFromRepo()`
https://img.shields.io/github/package-json/v/IcedFrisby/IcedFrisby.svg?style=flat
https://img.shields.io/github/manifest-json/v/RedSparr0w/IndieGala-Helper.svg?style=flat
I wonder if we're hitting a rate limit trying to access stuff via https://raw.githubusercontent.com ?
Do you think its worth switching to `cdn.jsdelivr.net` for this?

**Comment by paulmelnikow** [comment]
> I wonder if we're hitting a rate limit trying to access stuff via https://raw.githubusercontent.com ?
> Do you think its worth switching to `cdn.jsdelivr.net` for this?

Huh, is that rate limited? I didn't realize that 😝 

Looks like you're right: Microsoft/vscode#3708

We've got code in place specifically to _avoid using rate limit_ on these requests, though it could easily be disabled or removed. Wonder if that would fix it!

**Comment by Angelk90** [comment]
@paulmelnikow :  Actually I use both of them, so if I change something in the original project on github, I change the version and then when I have the public time. A way to remind me that I modified it.

**Comment by paulmelnikow** [comment]
I’m not really following that.

**Comment by paulmelnikow** [comment]
Seems to be fixed by #3035.
