### ISSUE TITLE
Symfony Insight Badges show "invalid response data" on projects that haven't been analyzed recently

### ISSUE THREAD

**Issue by arcanedev-maroc** [badges/shields#2928]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

![Insight Badge](https://img.shields.io/sensiolabs/i/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat-square)

I saw this problem on multiple PHP projects that are using symfony/insight and i have no clue what is the issue.

:link: **Link to the badge**

https://img.shields.io/sensiolabs/i/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat-square

**Repos**

* https://github.com/ARCANEDEV/noCAPTCHA
* https://github.com/ARCANEDEV/Localization
* https://github.com/ARCANEDEV/Gravatar
* https://github.com/ARCANEDEV/LogViewer

**Comment by calebcartwright** [comment]
@arcanedev-maroc by any chance do you have any guesses as to why there's no status values for those projects? We use the value of the status field to handle scenarios when a badge is requested for a project that is mid-analysis, so I want to make sure we don't break that. 

Would you be willing to re-run an analysis on one of your projects so that I can check the values before/during/after analysis? I don't use the service myself but would love to get this fixed, and that'd be a big help!

**Comment by arcanedev-maroc** [comment]
@calebcartwright 

I have no idea about the status values ! 

I've been using the badges for years with a default project `skeleton` and i'm not aware about the `value of the status field`. Is there something i need to setup in my projects or third party services ?

I've just re-run manually the analysis on one of my projects: https://insight.symfony.com/projects/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5

**Comment by calebcartwright** [comment]
Perfect thanks! The Symfony API response now has a status value of `finished` for that project which is what our code was expecting.

The badges are working for that project now:
https://img.shields.io/symfony/i/grade/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat
![](https://img.shields.io/symfony/i/grade/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat)

https://img.shields.io/symfony/i/violations/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat
![](https://img.shields.io/symfony/i/violations/ae37b4c0-5478-4afb-9a71-1fe5534d8ef5.svg?style=flat)

In the short term I think the easiest way to get the badges working again for your project would be to re-run analyses on them. My guess is that the `status` field may only have a value when there's been a recent analysis, but I'll keep digging into it

**Comment by arcanedev-maroc** [comment]
Yes indeed, i re-ran the analysis and it's seems the problem was solved for the projects i've mentioned.

Thanks for your work & time :+1:

**Comment by calebcartwright** [comment]
Hey @bkdotcom do you have any projects using Symfony Insight you could share? I'm trying to determine the range of values we can expect to see in the API response, in particular for projects that haven't been analyzed in a while (ideally not analyzed for a few weeks/months). 

I don't use the service myself, and the projects listed in the [Public Analysis section](https://insight.symfony.com/analyses) have all been run within the last few hours.

**Comment by arcanedev-maroc** [comment]
Hi @calebcartwright,

You can check my organization's profile: https://github.com/ARCANEDEV

It has some old repos with Symfony Insight.

**Comment by calebcartwright** [comment]
Just an FYI that I've added a fix for this in #2971 (which is also adding a Stars badge for Symfony Insight)
