### ISSUE TITLE
Badge request: drone.io

### ISSUE THREAD

**Issue by GeertJohan** [badges/shields#294]
Is it possible to provide drone.io status shields?
There was issue #150, drone now serves shields that are more compatible to the normal style shields but still no svg.

**Comment by bradrydzewski** [comment]
just a heads up, Drone now supports an endpoint to get the last build status for a given branch:
```
http://beta.drone.io/api/repos/drone/drone/builds/latest?branch=0.4.0
```

the endpoint format is as follows:
```
{{scheme}}://{{hostname}}/api/repo/{{user}}/{{repo}}/builds/latest?branch={{branch}}
```

note that the branch parameter is optional and will default to master.

example payload:

```
{
    "id": 215,
    "number": 94,
    "event": "push",
    "status": "success",
    "enqueued_at": 1445901238,
    "created_at": 1445901238,
    "started_at": 1445901239,
    "finished_at": 1445901521,
    "deploy_to": "",
    "commit": "2c5a3ae5ad1000fa0ac8c9a208a1618760c68235",
    "branch": "0.4.0",
    "ref": "refs/heads/0.4.0",
    "refspec": "",
    "remote": "https://github.com/drone/drone.git",
    "title": "",
    "message": "Merge pull request #1247 from tboerger/feature/fix-badge-links\n\nFix badge markup on repo badges page",
    "timestamp": 0,
    "author": "bradrydzewski",
    "author_avatar": "https://avatars.githubusercontent.com/u/817538?v=3",
    "author_email": "octocat@github.com",
    "link_url": "https://github.com/drone/drone/commit/2c5a3ae5ad1000fa0ac8c9a208a1618760c68235",
    "jobs": [
        {
            "id": 259,
            "number": 1,
            "status": "success",
            "exit_code": 0,
            "enqueued_at": 1445901238,
            "started_at": 1445901239,
            "finished_at": 1445901521,
            "environment": {}
        }
    ]
}
```

the `status` field should be used to determine which status to display on the badge, and which color to use. These are the possible status values:

* skipped
* pending
* running
* success
* failure
* killed
* error

remember that this is for self-hosted (open-source) drone so this would be implemented similar to jenkins:

```
https://img.shields.io/drone/s/http/beta.drone.io/drone/drone.svg
https://img.shields.io/drone/s/http/beta.drone.io/drone/drone/master.svg
```

open-source drone will eventually power drone.io (saas drone) at which point this would work for both.

**Comment by espadrine** [comment]
Fancy, thanks!

> beta.drone.io

Given I've got a few things to do for shields.io, I may implement this once it is out of beta. I won't refuse a PR, though.

**Comment by simonvpe** [comment]
I would consider providing a PR for this

**Comment by Daniel15** [comment]
@simonvpe - Great to hear! The [CONTRIBUTING.md](https://github.com/badges/shields/blob/master/CONTRIBUTING.md) file should help you get started, and we have a [tutorial on how to add a new badge](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). Feel free to reach out to us if you need any help!

**Comment by Daniel15** [comment]
Hey @simonvpe - Are you still interested in providing a PR for this?

**Comment by byCedric** [comment]
I took the liberty of trying to rip off some existing services and make a contraption that can serve as Drone badge. Sorry if I stole someones thunder here! but:

![giphy](https://user-images.githubusercontent.com/1203991/55281748-83251e80-5339-11e9-8e12-b67b1dadc07c.gif)

❤️ Cedric
