### ISSUE TITLE
Packagist invalid and GitHub repo not found

### ISSUE THREAD

**Issue by godbout** [badges/shields#2951]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

For whatever reason, my packagist badge and my github release badge are both not working. It's the first time I use shields.io and release a composer package, so the issue is probably a misunderstanding on my side. Thanks for opening my 👀️

:link: **Link to the badge**

Packagist: ![](https://img.shields.io/packagist/v/godbout/alfred-workflow-php.svg?style=flat)
https://img.shields.io/packagist/v/godbout/alfred-workflow-php.svg?style=flat

GitHub release: ![](https://img.shields.io/github/release/godbout/alfred-workflow-php.svg?style=flat)
https://img.shields.io/github/release/godbout/alfred-time.svg?style=flat

GitHub tag works: ![](https://img.shields.io/github/tag-date/godbout/alfred-workflow-php.svg?style=flat)
https://img.shields.io/github/tag-date/godbout/alfred-workflow-php.svg?style=flat

And some of my other project works for the GitHub release: ![](https://img.shields.io/github/release/godbout/alfred-time.svg?style=flat)
https://img.shields.io/github/release/godbout/alfred-time.svg?style=flat

Thank you!

**Comment by pxgamer** [comment]
The GitHub release badge works when you click on the direct link. It looks like GitHub is just caching it with their Camo service. The Packagist badge may take a little while to update from my experience. 👍

**Comment by godbout** [comment]
Ahhhh. @pxgamer thanks. I was guessing there was some cache issue but I couldn't find any info. Although for the GitHub release, unfortunately, I copied the wrong link. Copied the one of the project that works. The current one not working is:

https://img.shields.io/github/release/godbout/alfred-workflow-php.svg?style=flat

**Comment by pxgamer** [comment]
Ah, that makes more sense 😋 I think the GitHub release badge is only for releases rather than tags.
https://github.com/godbout/alfred-workflow-php/releases

You'd need to go to https://github.com/godbout/alfred-workflow-php/releases/new and create a new release as far as I know (Feel free to correct me if I'm wrong anyone).

**Comment by calebcartwright** [comment]
Hey @godbout it looks like you've pushed a tag in https://github.com/godbout/alfred-workflow-php/releases, but it doesn't look like a GitHub Release was created with that tag (as @pxgamer just noted). 

We've got a known issue (https://github.com/badges/shields/issues/2788) around providing a different message when there's no releases found

**Comment by godbout** [comment]
Oh. That makes a lot of sense now that I think about it. Sorry for the trouble and thank you guys! @pxgamer @calebcartwright. Because the tag showed up in `releases`, I thought the badge would work. Thanks again!

**Comment by calebcartwright** [comment]
No worries, we're here to help!
