### ISSUE TITLE
Nexus sonatype snapshots shows invalid response data

### ISSUE THREAD

**Issue by hugo-vrijswijk** [badges/shields#2978]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Nexus snapshots for my artifact shows 'Invalid response data'. Replacing 'snapshots' with 'releases' shows the correct version.

:link: Link to the badge

[![Sonatype Nexus (Snapshots)](https://img.shields.io/nexus/snapshots/https/oss.sonatype.org/io.stryker-mutator/stryker4s-core_2.12.svg)](https://oss.sonatype.org/content/repositories/snapshots/io/stryker-mutator/)
https://img.shields.io/nexus/snapshots/https/oss.sonatype.org/io.stryker-mutator/stryker4s-core_2.12.svg

groupId: `io.stryker-mutator`
artifactId: `stryker4s-core_2.12`

Link to the artifact snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/stryker-mutator/stryker4s-core_2.12/

💡 **Possible Solution**

Latest snapshot version showing on the badge

**Comment by chris48s** [comment]
Looks like the error here is

```
ValidationError: child "data" fails because [child "baseVersion" fails because ["baseVersion" with value "0.2.1+19-8844c122-SNAPSHOT" fails to match the required pattern: /^\d+(\.\d+)*(-.*)?$/]]
```
