### ISSUE TITLE
All badges showing vendor unresponsive

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#2991]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Badges (seemingly all of them) are failing with a `vendor | unresponsive` error
![image](https://user-images.githubusercontent.com/13042488/52755731-87cd8780-2fc4-11e9-894c-e44935945d27.png)

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by Giggitybyte** [comment]
Same problem here. It seems a few badges are coming back up, but the majority still seem to be non-functional.

**Comment by calebcartwright** [comment]
> It would seem all badges are working again.

Yup, we're working on it and they should all be starting to render again

**Comment by calebcartwright** [comment]
I'm going to close this for now as the badges and response times have returned to normal
