### ISSUE TITLE
Incorrect generated AsciiDoc code

### ISSUE THREAD

**Issue by manoelcampos** [badges/shields#3003]
Are you experiencing an issue with...

- [ x ] [shields.io](https://shields.io/#/)

:beetle: **Description**

The "Copy Badge URL" button is generating incorrect AsciiDoc code for the badge image.
An example of a generated Asciidoc code is `image:https://img.shields.io/travis/manoelcampos/sistema-bancario.svg?style=flat`, where the `[]` are missing.

:bulb: **Possible Solution**

An example of correct Asciidoc code is `image:https://img.shields.io/travis/manoelcampos/sistema-bancario.svg?style=flat[]`, including the `[]` at the end.

**Comment by paulmelnikow** [comment]
Fixed in #3003.
