### ISSUE TITLE
Automatically use dark text based on color

### ISSUE THREAD

**Issue by mbarkhau** [badges/shields#3015]
With the currently hard-coded white text I think most badges pick a darker colours so that there is enough contrast to the text. 

![image](https://user-images.githubusercontent.com/446561/52920067-00a44a80-3309-11e9-840d-53ed9dc28934.png)
![image](https://user-images.githubusercontent.com/446561/52920059-e23e4f00-3308-11e9-8358-04419b1683a3.png)

We could do something similar that was done for #2431 wrt. logos, choosing black or white text based on a luminance calculation for the background colour.

Perhaps part of the role of the shadow is to give the text at least some very faint outline in the case of a light background. If so, maybe it should be removed or changed in the case of black text.

**Comment by mbarkhau** [comment]
A concern with this is of course that it can change the rendering of existing badges (hopefully for the better), so it would be good to be able to see the impact on existing badges doing this.

**Comment by paulmelnikow** [comment]
I'd lean against automatically choosing a light color for uniformity's sake, though we could implement #504 to make this possible for people who really need to use light colors and want dark text.

**Comment by mbarkhau** [comment]
Ok, closing this in favour of #504.
