### ISSUE TITLE
colorB ignored for github/forks

### ISSUE THREAD

**Issue by felangel** [badges/shields#3053]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

colorB seems to be ignored for https://img.shields.io/github/forks whereas it works with https://img.shields.io/github/stars

doesn't work:
https://img.shields.io/github/forks/felangel/bloc.svg?colorB=yellow&label=Forks&logo=github

works:
https://img.shields.io/github/stars/felangel/bloc.svg?colorB=yellow&label=Stars&logo=github

**Comment by paulmelnikow** [comment]
Hi! Thanks for reporting this.

The overrides are now handled by BaseService, so this will be fixed on its own when the service is refactored to our new service model. We're down to our last few dozen of these. See #2320 and #2863 if you'd like to join in!
