### ISSUE TITLE
CircleCI test summary broken on daily-tests

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3054]
Some time between https://circleci.com/gh/badges/daily-tests/159 and https://circleci.com/gh/badges/daily-tests/160, the test summary stopped working on the daily-tests. The failures for services don't show up, and main is showing 77 passed tests but several missing failures.

Maybe related to a dependency bump? Or the Mocha config change?

**Comment by calebcartwright** [comment]
bummer. i'll take a look at this one

**Comment by calebcartwright** [comment]
So this may be a stretch, but the Mocha docs/v6 release notes enumerate which config files will be loaded automatically, and all the values listed are dot files

https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#tada-enhancements-1 
https://mochajs.org/#configuring-mocha-nodejs 

However, our [root level mocha rc file](https://github.com/badges/shields/blob/master/mocharc.yml) is `mocharc.yml` so I'm wondering how pedantic mocha's new auto-config loader is about dot vs. not dot

**Comment by calebcartwright** [comment]
Yup! https://github.com/mochajs/mocha/blob/master/lib/cli/config.js#L23 and confirmed in my own local env. 

I'm honestly really surprised by that this but oh well. I'll open a PR to rename ours to `.mocharc.yml` unless anyone strongly prefers that we add `--config mocharc.yml` to all our npm scripts running tests
