### ISSUE TITLE
Thank you for your service

### ISSUE THREAD

**Issue by adriens** [badges/shields#3082]
Hi, this is not a bug, nor a feature request, just an issue to thank you and tell you that I did mention your work in my latest [linkedIn article](https://www.linkedin.com/feed/update/urn:li:activity:6504917061146329088)

I think that it's an original use of your service that I really appreciate.

Thanks a lot, have a great week-end 🙏 👍

**Comment by adriens** [comment]
You can close this ticket when and as you want 👏

**Comment by paulmelnikow** [comment]
Appreciate it! And thanks for sharing that – It's a neat project!
