### ISSUE TITLE
Debounce badge updates from badge customizer

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3092]
Doing some testing for #2068 I noticed a single use of the badge customizer triggered about 10 badge requests.

Probably it would be good idea to throttle or debounce them! Maybe we could wait for the output to stabilize for about 250-500 ms before firing the request, sort of like how we handle the search.

**Comment by RedSparr0w** [comment]
Sounds like a good idea, the timing for the search seems reasonable, without feeling sluggish.

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/
Closing this issue as it relates to the previous frontend
