### ISSUE TITLE
Lightning talk about shields

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#3113]
I shared my love for this project in Berlin 14th of February at the "I love free software" day.
https://www.youtube.com/watch?v=abBdk8bSPKU&list=PLf9bd23pftk-oYkS22pcW_wKBKmSczse6&index=7&t=0s

I do not know what you would like to do with it. If nothing, you can just close the issue.

**Comment by paulmelnikow** [comment]
Aw, what a nice talk @niccokunzmann!

**Comment by PyvesB** [comment]
Thanks for sharing @niccokunzmann ! Nice talk, it will hopefully spread the word about Shields and more generally inspire people to talk more about what they do in the open-source world! 😉

**Comment by RedSparr0w** [comment]
:+1: 
Thanks for sharing this, I always enjoy seeing talks/articles regarding shields/badges,
And you explained the project quite well.

I believe @platan also did a talk about shields.io during hacktoberfest.

It would be nice to have a section somewhere in the README.md or another file to collate all of these.

**Comment by platan** [comment]
I had a flash talk during Hacktoberfest 2018 Poznań meeting. Here are [slides](https://github.com/hacktoberfest-poznan/presentations/blob/master/2018/Cool-badges-for-your-project.pdf) and [photos](https://www.facebook.com/pg/hacktoberfest/photos/?ref=page_internal).

**Comment by chris48s** [comment]
Once again, thanks for sharing this :heart: 
A year on, it probably doesn't still ned to be an open issue :smile:

**Comment by paulmelnikow** [comment]
Wanted to let you both know @niccokunzmann @platan that I've included your talks at https://github.com/badges/awesome-badges#talks 😀
