### ISSUE TITLE
Netlify status badge

### ISSUE THREAD

**Issue by AnandChowdhary** [badges/shields#3129]
:clipboard: **Description**

The popular CDN and static site host Netlify has added support for badges with build information (e.g., 
"success", "building" or "failed").

Badges can be added like: "netlify | success", just like the current "build | passing".

Details: https://www.netlify.com/docs/continuous-deployment/#status-badges

Example:

![Netlify badge example](https://img.shields.io/badge/netlify-success-brightgreen.svg)

:link: **Data**

A general API is available at https://www.netlify.com/docs/api/. This issue will be updated once the documentation for the particular build status API are published too.

:microphone: **Motivation**

Lots of websites are now using Netlify as opposed to GitHub Pages. According to their website, over 400,000 "developers trust Netlify", probably since it's free and has a great toolkit (e.g., Netlify CMS).

Since they have badges available now, they should be added to Shields.io too!

**Comment by PyvesB** [comment]
Hello @AnandChowdhary,

Thank you for your suggestion! Would you like to contribute to the project and have a go at implementing this new badge? We've got a nice [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to help you get started. 😉 

Cheers,

Pyves

**Comment by CodeMacabre** [comment]
Watching. I happened upon this issue as I was checking to see if anyone had built Shield.io-styled badges to replace the default Netlify ones:
![export for blog 2x](https://user-images.githubusercontent.com/19981049/53684967-2881ae00-3d0c-11e9-80c6-d99f5fc0d973.png)

I need my badges to be consistently-styled! 🤓

**Comment by AnandChowdhary** [comment]
I will be happy to build this service badge, please feel free to assign this issue to me.

I have gotten in touch with Netlify Support and they will get back to me soon about the API endpoints for this:

> I'm not sure but I have asked the developer who created the badges to help us out here.  Since she works in the EU and their workday is over I expect i'll only hear back from her tomorrow and be able to relay to you then :)

**Comment by AnandChowdhary** [comment]
Chris from Netlify has gotten back to me:

> [Getting the build status via API] is not currently possible. I've filed a feature request for you, but we do not currently have plans to implement it.

It seems like we have to be more patient. I will re-open this issue when Netlify has updated their API.

**Comment by PyvesB** [comment]
Oh, that's disappointing. Thanks for following up with them!

**Comment by AnandChowdhary** [comment]
Since Netlify has not provided an API for this, I have made an unofficial wrapper around their badges and hosted it on [Oswald Labs Platform](https://github.com/OswaldLabsOpenSource/platform). The source code is available [here](https://github.com/OswaldLabsOpenSource/platform/blob/master/services/netlify-status.js).

The wrapper checks the color of the Netlify badge and returns JSON in the [Sheids.io schema](https://shields.io/endpoint). This means that we can use Shields.io's Endpoint (beta) to generate these badges for now:

![Success badge](https://img.shields.io/badge/netlify-success-success.svg) ![Building badge](https://img.shields.io/badge/netlify-building-yellow.svg) ![Building badge](https://img.shields.io/badge/netlify-error-critical.svg)

**Live example:**

Schema endpoint: https://developer.oswaldlabs.com/netlify-status/e6d5a4e0-dee1-4261-833e-2f47f509c68f

![Netlify status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fdeveloper.oswaldlabs.com%2Fnetlify-status%2Fe6d5a4e0-dee1-4261-833e-2f47f509c68f)

```https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fdeveloper.oswaldlabs.com%2Fnetlify-status%2Fe6d5a4e0-dee1-4261-833e-2f47f509c68f```

**Usage:**

In your Netlify app, under General –> Status badges, you get a URL like this:

```[![Netlify Status](https://api.netlify.com/api/v1/badges/e6d5a4e0-dee1-4261-833e-2f47f509c68f/deploy-status)](https://app.netlify.com/sites/gitwriter/deploys)```

From the above URL, your "key" is `e6d5a4e0-dee1-4261-833e-2f47f509c68f`. Replace `{{YOUR_KEY}}` with your key below:

```https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fdeveloper.oswaldlabs.com%2Fnetlify-status%2F{{YOUR_KEY}}```

**Important note:**

Since this is not using an official API, this will fail if Netlify updates their badge colors. I will try my best to keep this updated and [Oswald Labs](https://oswaldlabs.com/platform/) will continue to run this service until we have an alternative.

**Comment by PyvesB** [comment]
Neat! By the way, if they have their own badges in SVG format, we also have some [functionality](https://github.com/badges/shields/blob/master/core/base-service/base-svg-scraping.js) to do scrapping. We have a few badges that are based on this `BaseSvgScrapingService` class. 😉

**Comment by calebcartwright** [comment]
If anyone's interested in implementing this, I've included some of our other badges that are using the `BaseSvgScrapingService` @PyvesB noted for reference:

- [Travis CI](https://github.com/badges/shields/blob/master/services/travis/travis-build.service.js)
- Azure DevOps [Build](https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-build.service.js) and [Release](https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-release.service.js)
- [Codeacy](https://github.com/badges/shields/blob/master/services/codacy/codacy-coverage.service.js)
- [Codeship](https://github.com/badges/shields/blob/master/services/codeship/codeship.service.js)
- [Gitlab Pipeline](https://github.com/badges/shields/blob/master/services/gitlab/gitlab-pipeline-status.service.js)

**Comment by AnandChowdhary** [comment]
I’ve made a draft pull request which finds the closest color to red/orange/green by parsing the Netlify SVG (since their badge has no text, only paths)

**Comment by Hongbo-Miao** [comment]
@AnandChowdhary thank you so much for providing this! Right now seems `?style=flat-square` does not work on this following method.

> **Usage:**
> 
> In your Netlify app, under General –> Status badges, you get a URL like this:
> 
> `[![Netlify Status](https://api.netlify.com/api/v1/badges/e6d5a4e0-dee1-4261-833e-2f47f509c68f/deploy-status)](https://app.netlify.com/sites/gitwriter/deploys)`
> 
> From the above URL, your "key" is `e6d5a4e0-dee1-4261-833e-2f47f509c68f`. Replace `{{YOUR_KEY}}` with your key below:
> 
> `https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fdeveloper.oswaldlabs.com%2Fnetlify-status%2F{{YOUR_KEY}}`

**Comment by AnandChowdhary** [comment]
Hi @Hongbo-Miao, you're right, this is just a small wrapper to make things work temporarily. I'm going to try and add Netlify to Shields itself (new PR #3953) and hopefully not need this endpoint anymore.

**Comment by AnandChowdhary** [comment]
#3953 is merged! We'll now have official support for Netlify!

> Since Netlify has not provided an API for this, I have made an unofficial wrapper around their badges and hosted it on Oswald Labs Platform. The source code is available here.

[Oswald Labs Platform](https://oswaldlabs.com/platform/) will continue to serve this wrapper endpoint this month as is, so no READMEs will break. In October 2019, I'll update the badge to show an upgrade notice, so people using it who're not in this issue will know:

![Netlify upgrade notice badge](https://img.shields.io/badge/netlify%20(needs%20upgrade)-success-brightgreen) or ![Alternate badge](https://img.shields.io/badge/netlify%20(upgrade%20shields%233129)-success-brightgreen)

On January 1, 2020, we'll deprecate this endpoint and READMEs will break if they still haven't upgraded to the official Shields endpoint. Sounds fair?
