### ISSUE TITLE
Add support for CircleCI

### ISSUE THREAD

**Issue by vslinko** [badges/shields#313]
They are have SVG badge to parse:
https://circleci.com/gh/vslinko-vstack/vstack-validator.svg?style=svg

SVG source:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="66" height="18">
	<rect x="0" fill="#229922" width="66" height="18" rx="3"/>
	<path fill="none" stroke="#ffffff" d="M4.2,10.5 c0.7,2.6,3,4.5,5.8,4.5c3.3,0,6-2.7,6-6s-2.7-6-6-6C7.2,3,4.9,4.9,4.2,7.5" stroke-width="1.4"/>
	<path fill="none" stroke="#ffffff" d="M9,11L7,9 M13,7 l-4,4" stroke-width="1.2"/>
	<text x="20" y="13" fill="#ffffff" font-family="Helvetica, Arial, sans-serif" font-size="10">PASSED</text>
</svg>
```

**Comment by dblandin** [comment]
I think we can get pretty far without implementing a solution that passes along a `circle-token`.

For **private** repositories, the image will show up without a `circle-token` as long as you're logged-in to CircleCI and have access to the repository:

https://circleci.com/docs/status-badges

> You can also link to the image without providing a circle-token, in which case the image will only appear for people who are currently logged-in to circleci.com!)

Fetching a badge for **public** repositories doesn't require a `circle-token` at all:

http://blog.circleci.com/a-step-into-open-source/

> Unauthenticated API access is now available for these projects, too, so badges no longer need purpose-specific API keys.

**Comment by g105b** [comment]
Working on this implementation: https://github.com/g105b/shields

**Comment by olivierlacan** [comment]
I think we made it very clear early on in this project that this kind of stuff would not be tolerated: 

![image](https://cloud.githubusercontent.com/assets/65950/5968193/377f06a4-a815-11e4-9bc6-78d637161ee8.png)

I hate to be forceful but I'd prefer removing this badge from the home page until it says `[build | passing]` like all other CI badges.

Badges are not ad banners, they're there to provide value by virtue of the information they provide. If services want users, they should provide a solid service. The badge can link back to them if they want to attract eyeballs.

What do you think @espadrine?

**Comment by espadrine** [comment]
I agree. This was an oversight on my part.

**Comment by g105b** [comment]
Oops, I got caught up in the implementation and had CircleCI on the brain,
will remove and treat like the other build status badges.

Thanks for bringing this up.

**Comment by espadrine** [comment]
@g105b It's ok, it's done and live.

**Comment by g105b** [comment]
Nice work!

**Comment by olivierlacan** [comment]
@g105b @espadrine No worries. Thanks for the quick merge Thaddee. :-)
