### ISSUE TITLE
Support for WooCommerce

### ISSUE THREAD

**Issue by seb86** [badges/shields#314]
It would be nice to add a badge for those releasing extensions for WooCommerce via GitHub.

This badge is generated -  ![Built for WooCommerce](http://img.shields.io/badge/Built%20for-WooCommerce-a46497.svg)
`http://img.shields.io/badge/Built%20for-WooCommerce-a46497.svg`

but I think it would be easy to remember if it did not have the colour variable at the end like so: 
`http://img.shields.io/badge/Built%20for-WooCommerce.svg`

Also if possible another one for the version of WooCommerce required for the extension to work.

![WooCommerce Version](http://img.shields.io/badge/WC%20Version-2.2-a46497.svg)
`http://img.shields.io/badge/WC%20Version-2.2-a46497.svg`

Again without the colour variable at the end.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
