### ISSUE TITLE
Error "repo not found" for docker repository that exists

### ISSUE THREAD

**Issue by acelaya** [badges/shields#3140]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

I'm getting a "repo not found" error for the "Docker build status" badge, but the repository exists and is public.

This is the repository: https://hub.docker.com/r/acelaya/blog

:link: **Link to the badge**

https://img.shields.io/docker/build/acelaya/blog.svg?style=flat-square

**Comment by PyvesB** [comment]
Hello @acelaya,

I believe this is the same issue as the ones reported in #1400, i.e. the [DockerHub API endpoint for your repository](https://hub.docker.com/v2/repositories/acelaya/blog/buildhistory) returns `Object not found`. Let's track things in that issue, but feel free to reopen this one if you think your problem has a different cause. 😉 

Cheers,

Pyves

**Comment by acelaya** [comment]
Oh, yes, it looks like the same issue indeed. Sorry for the spam, I should have checked if there was an existing issue 😅
