### ISSUE TITLE
Logos from simpleicons.org having space in its name not loading

### ISSUE THREAD

**Issue by ritzvik** [badges/shields#3155]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Logos from simpleicons.org not rendering when the logo has space in it's name. For example : "Code Climate"

:link: **Link to the badge**
https://img.shields.io/codeclimate/maintainability/einsteinpy/einsteinpy.svg?logo=Code%20Climate&style=flat-square

**Comment by RedSparr0w** [comment]
_Just leaving a note in case anyone comes across this issue._

The Code Climate logo was added to simple-icons on `v1.9.22` and our server is currently running `v1.9.21`,
The icon should load correctly once we update simple-icons.

**Comment by paulmelnikow** [comment]
Also, keep in mind that the canonical / recommended way to refer to simple-icons logos is now with a hyphen separator, e.g. `?logo=visual-studio-code`.

![](https://img.shields.io/badge/foo-bar-blue.svg?logo=visual-studio-code)

https://img.shields.io/badge/foo-bar-blue.svg?logo=visual-studio-code

<img width="600" alt="screen shot 2019-03-04 at 3 40 38 pm" src="https://user-images.githubusercontent.com/1487036/53761574-e1bec000-3e93-11e9-8949-ecb5fab48994.png">
