### ISSUE TITLE
Packagist badges show the latest unstable version

### ISSUE THREAD

**Issue by mnapoli** [badges/shields#319]
Packagist badges show the latest dev version, not the stable one.

For example:

```
https://img.shields.io/packagist/v/mnapoli/PHP-DI.svg
```

[![Latest Stable Version](https://img.shields.io/packagist/v/mnapoli/PHP-DI.svg)](https://packagist.org/packages/mnapoli/php-di)

Whereas with the Poser badges:

- stable: [![Latest Stable Version](https://poser.pugx.org/mnapoli/php-di/v/stable.svg)](https://packagist.org/packages/mnapoli/php-di)
- unstable: [![Latest Stable Version](https://poser.pugx.org/mnapoli/php-di/v/unstable.svg)](https://packagist.org/packages/mnapoli/php-di)

**Comment by francoispluchino** [comment]
@espadrine I have the same type of problem with the package [fxp/composer-asset-plugin](https://packagist.org/packages/fxp/composer-asset-plugin).

Packagist correctly returns the list of available versions:

> https://packagist.org/packages/fxp/composer-asset-plugin.json

- dev-master
- 1.0.x-dev
- v1.0.0
- v1.0.0-beta4
- v1.0.0-beta3
- v1.0.0-beta2
- v1.0.0-beta1

But the https://img.shields.io/packagist/v/fxp/composer-asset-plugin.svg link displays the `1.0.0-beta4` release and not the `1.0.0` version or `2.0.x-dev` version (if your service displays the latest dev version).

**Comment by espadrine** [comment]
@francoispluchino I have recently merged vpre support, which on `fxp/composer-asset-plugin` yields `v1.0.0-beta4` in v and `v1.0.x-dev` vpre. Not sure how Packagist's version comparison system works or what you would expect the latest stable / unstable version ordering to be, so feel free to improve it.

The current system for stable badges relies on semver ordering when possible, and ascii ordering otherwise, and the version ordering for prerelease is custom.

**Comment by francoispluchino** [comment]
In 2 cases, it is not the correct version that is displayed.

If the latest version displayed is:

- **stable**: must be `v1.0.0`
- **unstable**: must be `dev-master` alias `2.0.x-dev`

The version with `dev-{BRANCH_NAME}` is the development version for a branch that do not use the version number in its name.

The version with `Y.Z.x-dev` is the development version for a branch with a version name (ex. branch name: `1.0`, packagist: `1.0.x-dev`).

So, all the versions do not begin with `dev-` or ending with `-dev` is a `stable`/`RC`/`beta`/`alpha`/`patch` release (tags).

You will have more detail with the doc of Composer for the [schema version](https://getcomposer.org/doc/04-schema.md#version) and the [alias](https://getcomposer.org/doc/articles/aliases.md).

**Comment by espadrine** [comment]
Thanks a lot for all this information!

Just to make sure I understand correctly, the leading v is optional, showing aliases are always preferable to their numbered version counterpart, and

v0.9.0 < v1.0.0-dev < v1.0.x-dev < v1.0.0-patch = v1.0.0-p < v1.0.0-alpha = v1.0.0-a < v1.0.0-alpha2 = v1.0.0-a2 < v1.0.0-beta = v1.0.0-b < v1.0.0-RC < v1.0.0

and a version is stable if and only if it does not contain a dash?

**Comment by francoispluchino** [comment]
Yes, the prefix `v` is optional.

Regarding versions containing a dash, it's not entirely accurate.

**Is considered like:**

- **development** (X.Y.99999.99999):
  - dev-master (branch `master`)
  - 1.0.x-dev (branch `1.0`)
- **stable**:
  - `1.0.0-patch123` same as: `1.0.0-p123` or `v1.0.0-patch123` or `v1.0.0-p123`
  - `1.0.0-patch` same as: `1.0.0-p` or `1.0.0-patch1` or `1.0.0-p1` or `v1.0.0-patch` or `v1.0.0-p` or `v1.0.0-patch1` or `v1.0.0-p1`
  - `1.0.0`
- **release candidate**:
  - `1.0.0-RC2` same as: `v1.0.0-RC2`
  - `1.0.0-RC` same as: `1.0.0-RC1` or `v1.0.0-RC` or `v1.0.0-RC1`
- **beta**:
  - `1.0.0-beta2` same as: `v1.0.0-beta2` or `1.0.0-b2` or `v1.0.0-b2`
  - `1.0.0-beta` same as: `1.0.0-beta1` or `v1.0.0-beta` or `v1.0.0-beta1` or `1.0.0-b` or `1.0.0-b1` or `v1.0.0-b` or `v1.0.0-b1`
- **alpha**:
  - `1.0.0-alpha2` same as: `v1.0.0-alpha2` or `1.0.0-a2` or `v1.0.0-a2`
  - `1.0.0-alpha` same as: `1.0.0-alpha1` or `v1.0.0-alpha` or `v1.0.0-alpha1` or `1.0.0-a` or `1.0.0-a1` or `v1.0.0-a` or `v1.0.0-a1`

For the branch version with name (development, ex. dev-master), there may be an alias that you find in `extra.branch-alias.dev-{branch-name}`.

**Concerning the precedence of versions:**

`1.0.0-alpha` = `1.0.0-alpha1` < `1.0.0-alpha2` < `1.0.0-beta` = `1.0.0-beta1` < `1.0.0-beta2` < `1.0.0-RC` = `1.0.0-RC1` < `1.0.0-RC2` < `1.0.0` < `1.0.0-patch` = `1.0.0-patch1` < `1.0.0-patch2` < `1.0.x-dev` < `1.1.0-alpha1` ...

**For my package:**

`v1.0.0-beta1` < `v1.0.0-beta2` < `v1.0.0-beta3` < `v1.0.0-beta4` < `v1.0.0` < `1.0.x-dev` (branch `1.0`) < `dev-master` alias `2.0.x-dev` (branch `master`)

**Comment by francoispluchino** [comment]
I forget, when there is no release (tags), you should display the latest development version and not `invalid` (ex. `dev-master`).

**Comment by espadrine** [comment]
I'll put it live in 24h. @francoispluchino, if you wish, I'd love you to check if what I'm doing is ok by reviewing this part: https://github.com/badges/shields/blob/master/server.js#L3213

**Comment by francoispluchino** [comment]
On first reading, I'd say it's good.

**Comment by espadrine** [comment]
It's live! ☺

**Comment by francoispluchino** [comment]
@espadrine Thanks!

**Comment by mnapoli** [comment]
:+1: all good, the badges at the top of this issues can show it too ;)

Thank you very much for your work!
