### ISSUE TITLE
Docker build doesn't work when repository has a "." in it

### ISSUE THREAD

**Issue by russ0519** [badges/shields#3190]
Are you experiencing an issue with...

- [ x] [shields.io](https://shields.io/#/)
:beetle: **Description**

:link: https://img.shields.io/docker/build/russ0519/docker-airflow-2.7.svg

:bulb: **Possible Solution**

I'm guessing the regex is not escaping the "." properly.

**Comment by paulmelnikow** [comment]
Could this be the issue from #1400?

**Comment by russ0519** [comment]
@paulmelnikow Thank you, it was.
