### ISSUE TITLE
Downloads and installs badge for Visual Studio Marketplace does not work

### ISSUE THREAD

**Issue by BADF00D** [badges/shields#3197]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

When adding a badge for installs or downloads of my extension, there is an error that tells me that my extension was not found at Visual Studio Markedplace. But I used to "Copy ID" function of the [side](https://marketplace.visualstudio.com/items?itemName=DavidStormer.DisposableFixer). The same happens as I picked a random [other extension](https://marketplace.visualstudio.com/items?itemName=GiovanniBassi-MVP.CodeCrackerforVisualBasic)

:link: **Link to the badge**

Download
![Visual Studio Marketplace Downloads](https://img.shields.io/visual-studio-marketplace/d/CodeCracker.Vsix..5b99e64c-1418-4a06-990c-fd4cf01f1234.svg)

![Visual Studio Marketplace Downloads](https://img.shields.io/visual-studio-marketplace/d/DisposableFixer.Microsoft.e69d15ad-e40a-412c-a444-cfb06057928c.svg)

Install
![Visual Studio Marketplace Installs](https://img.shields.io/visual-studio-marketplace/i/CodeCracker.Vsix..5b99e64c-1418-4a06-990c-fd4cf01f1234.svg)

![Visual Studio Marketplace Installs](https://img.shields.io/visual-studio-marketplace/i/DisposableFixer.Microsoft.e69d15ad-e40a-412c-a444-cfb06057928c.svg)

:bulb: **Possible Solution**

**Comment by BADF00D** [comment]
Same problem with the version badge for Visual Studio Markedplace: ![Visual Studio Marketplace Version](https://img.shields.io/visual-studio-marketplace/v/DisposableFixer.Microsoft.e69d15ad-e40a-412c-a444-cfb06057928c.svg)

**Comment by chris48s** [comment]
The correct badge URLs for these would be:

GiovanniBassi-MVP.CodeCrackerforVisualBasic:
![](https://img.shields.io/visual-studio-marketplace/d/GiovanniBassi-MVP.CodeCrackerforVisualBasic.svg) - https://img.shields.io/visual-studio-marketplace/d/GiovanniBassi-MVP.CodeCrackerforVisualBasic.svg

DavidStormer.DisposableFixer:
![](https://img.shields.io/visual-studio-marketplace/d/DavidStormer.DisposableFixer.svg) - https://img.shields.io/visual-studio-marketplace/d/DavidStormer.DisposableFixer.svg

**Comment by calebcartwright** [comment]
Yup, you only need to specify the extension name (like `DavidStormer.DisposableFixer`) for the parameter, not the extension guid

**Comment by BADF00D** [comment]
Thanks very much!
