### ISSUE TITLE
Dynamic badges: add links to pages with query help

### ISSUE THREAD

**Issue by tooomm** [badges/shields#3203]
:clipboard: **Description**

I always find it difficult to come up with the correct query...

Possible links could be:
- JSON: https://jsonpath.com (as given in https://github.com/badges/shields/pull/820)
- XML: ~~https://www.freeformatter.com/xpath-tester.html~~ http://xpather.com (https://github.com/badges/shields/issues/3202#issuecomment-475439860)
- YAML: ?

**Comment by paulmelnikow** [comment]
Hi, thanks, those links do seem better than the ones we have which are linking to npmjs libraries. Feel free to open a PR if you like; the existing links should be hard-coded in the dynamic badge builder component.

The YAML badge works the same as the JSON badge. It uses JSONPath.

**Comment by tooomm** [comment]
I try to have a look next week 👍
