### ISSUE TITLE
GitHub Issues: customizing the right-hand-side

### ISSUE THREAD

**Issue by Tourorist** [badges/shields#321]
Is there a way now to change it to a number-only variable?
![](http://img.shields.io/github/issues/TEHGAM/ADR.svg?label=Задачи&style=flat)
In my example, I would like to omit the "open" part because the badge title is localized.

**Comment by espadrine** [comment]
Thanks for the kind words. It is live!

I'll try speaking to the chief of the french armies for that Mistral business. I'm sure we can come to a compromise, like sending only the upper half of the ship.

**Comment by Tourorist** [comment]
Looks good,
From now on I'll be sailing it everywhere i go across the Hub seas and beyond. :smile: 
![](http://giant.gfycat.com/GrandJointDog.gif)
