### ISSUE TITLE
Jitpack Downloads Badge

### ISSUE THREAD

**Issue by erayerdin** [badges/shields#3220]
:clipboard: **Description**

This badge is for Jitpack's downloads data. Shields already have a Jitpack badge, yet it doesn't
have download count. Jitpack apparently provides [downloads endpoint](https://jitpack.io/docs/API/#downloads) and it can be used to provide a badge.

This badge should be similar to other downloads badges, such as:

 - **Monthly Badge / Great Amount of Downloads Example:** ![](https://img.shields.io/badge/downloads-10k%2Fmonth-brightgreen.svg)
 - **Weekly Badge / No Downloads Example:** ![](https://img.shields.io/badge/downloads-0%2Fweek-red.svg)

:link: **Data**

The API is public and does not require authentication except it is a private repository (Jitpack version badge also only supports public repositories only). You can see the documentation [here](https://jitpack.io/docs/API/#downloads).

:microphone: **Motivation**

Any other packaging platforms have download badges but Jitpack does not.

**Comment by calebcartwright** [comment]
Added `needs-upstream-help` label as the underlying Jitpack API needs to stabilize before this can be completed

**Comment by erayerdin** [comment]
Seems #3291 has been merged. I think it is appropriate to close this issue @calebcartwright.
