### ISSUE TITLE
Option for unstable Ruby gem version

### ISSUE THREAD

**Issue by AlexWayfer** [badges/shields#3222]
:clipboard: **Description**

Hello!

I want an option for `gem version` badge about unstable versions.

Example: https://rubygems.org/gems/flame

The current badge has only `4.18.1` value.

I want to display `5.0.0.rc5` value for informing about preparing the new release.

Thanks.

**Comment by calebcartwright** [comment]
Do you know if unstable/rc versions are provided via an API response? 

We're currently using https://guides.rubygems.org/rubygems-org-api/#gem-methods, and the API response for the aforementioned gem lists the version as  `4.18.1`:

```json
{
  "name": "flame",
  "downloads": 61236,
  "version": "4.18.1",
  "version_downloads": 2563,
  "platform": "ruby",
  "authors": "Alexander Popov",
  "info": "Use controller's classes with instance methods as routing actions, mounting its in application 
  class.",
  "licenses": [
    "MIT"
  ],
  "metadata": {},
  "sha": "12533f702a8059a51d6d2ce2bea1858ec8ac2993e8549feedc300af64e310e88",
  "project_uri": "https://rubygems.org/gems/flame",
  "gem_uri": "https://rubygems.org/gems/flame-4.18.1.gem",
  "homepage_uri": "https://github.com/AlexWayfer/flame",
  "wiki_uri": null,
  "documentation_uri": "http://www.rubydoc.info/gems/flame/4.18.1",
  "mailing_list_uri": null,
  "source_code_uri": null,
  "bug_tracker_uri": null,
  "changelog_uri": null,
  "dependencies": {...}
}
```

**Comment by calebcartwright** [comment]
Perhaps this could be used:
https://guides.rubygems.org/rubygems-org-api/#gem-version-methods

**Comment by AlexWayfer** [comment]
> Do you know if unstable/rc versions are provided via an API response?

I didn't, but now I know. :slightly_smiling_face: 

> Perhaps this could be used: https://guides.rubygems.org/rubygems-org-api/#gem-version-methods

Yep, looks appropriate.

> calebcartwright added the good first issue  label

This is wrong if it about issue author, not like "good for the first PR". :smiley: 

https://github.com/badges/shields/issues?utf8=%E2%9C%93&q=author%3AAlexWayfer

**Comment by calebcartwright** [comment]
> This is wrong if it about issue author, not like "good for the first PR".  

The meaning of our labels is documented: 
https://github.com/badges/shields/labels 
https://github.com/badges/shields#contributing 

`good first issue` is a label we use to flag an issue that we as maintainers believe anyone, even new users, could potentially tackle. It does not have anything to do with how many issues an author has opened

**Comment by AlexWayfer** [comment]
> good first issue is a label we use to flag an issue that we as maintainers believe anyone, even new users, could potentially tackle. It does not have anything to do with how many issues an author has opened

OK, something like `PR welcome` or `Help wanted`, I got it, thanks.

**Comment by calebcartwright** [comment]
> OK, something like PR welcome or Help wanted, I got it, thanks.

Exactly! [Here is our tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) for anyone interested in working on this. 

It's fairly common for our version badges to support both scenarios: the latest stable version, and the latest version, prereleases/unstable or stable. The latter is what needs to be added here, and there's other version badges that can serve as a reference.

**Comment by profgrammer** [comment]
Hi, I'd like to work on this service badge addition. If I understand correctly, the `number` attribute of the first element of the array returned from `https://rubygems.org/api/v1/versions/{gemName}.json` is the version we are looking for right?

**Comment by profgrammer** [comment]
Hi, I am trying to work on adding this service but I cannot validate the version `5.0.0.rc6` using the existing regex patterns in `test-validators`. Can anyone please point me to some resources for this? Thanks!
