### ISSUE TITLE
allow expectBadge helper to assert links[] content

### ISSUE THREAD

**Issue by chris48s** [badges/shields#3242]
:clipboard: **Description**

If we could call

```
.expectBadge({ label: 'foo', message: 'bar', links: ['https://foo.bar/baz'] })
```

that would allow us to write more complete tests.

refs https://github.com/badges/shields/pull/3241#discussion_r270643671

**Comment by PyvesB** [comment]
My current thinking is to break down the expectations inside `expectBadge` into separate assertions as part of #2686 (this was also suggested in #2687). Tackling this issue would become very easy, we would add the `link` to the JSON response and add a new assertion inside `expectBadge` which would only be checked if `link` is defined in the input of `expectBadge`. I was planning on putting all the assertions inside an `afterJSON` block within `expectBadge`, however, [this bug](https://github.com/IcedFrisby/IcedFrisby/issues/206) in IcedFrisby is currently a blocker.
