### ISSUE TITLE
TeamCity Build Badge "Invalid response data"

### ISSUE THREAD

**Issue by Stupremee** [badges/shields#3244]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I tried to setup a badge for my TeamCity build status.
I'm pretty sure I did everything right.
However, the error is "Invalid Response Data".

:link: **Link to the badge**

https://img.shields.io/teamcity/https/my.teamcity.url/e/My_Build.svg?style=flat-square
I don't want to publish my TeamCity instance, because it is private.

:bulb: **Possible Solution**

I compared the API endpoints of https://teamcity.jetbrains.com and my server and noticed that the `guest` parameter must be set to 1 to get access. Otherwise, you get a 403 response.
It would work if you just add `guest=1` [here](https://github.com/badges/shields/blob/master/services/teamcity/teamcity-base.js#L20).
![Solution](https://i.imgur.com/otlrcTJ.png)

I could PR it if you want.

**Comment by calebcartwright** [comment]
Thanks @Stupremee, if you scroll down a bit in the code you referenced, you'll notice that we are already adding the `guest` query param, https://github.com/badges/shields/blob/master/services/teamcity/teamcity-base.js#L29

Just to clarify, are you trying to create a badge for a self-hosted TeamCity instance, or teamcity.jetbrains.com?

**Comment by Stupremee** [comment]
I try to do it with my own instance, it works for teamcity.jetbrains.com.
I will start my own Shields instance and try to debug the problem.

**Comment by calebcartwright** [comment]
Can you share the actual Shields badge URL you are trying to use?

**Comment by Stupremee** [comment]
https://img.shields.io/teamcity/https/tc.stu-dev.me/guestAuth/e/Mela_Build.svg?style=flat-square 
here it is

**Comment by calebcartwright** [comment]
Thanks, I think I see the problem. Confirming now

**Comment by calebcartwright** [comment]
Yeah the problem is with our regex on the `statusText` field. The `inspections` suffix on there is causing it to be rejected

**Comment by Stupremee** [comment]
Ahh okay. How fast can you fix this?

**Comment by calebcartwright** [comment]
It will most likely be a few days before this is fixed and deployed

**Comment by Stupremee** [comment]
Okay.
