### ISSUE TITLE
In CI, run e2e tests on the build

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3267]
#3262 added support for e2e tests. As I'm looking at some of the dependency bump PRs, I realize I could speed up review of those if I didn't have to open the review apps.

If e2e tests ran on the build (i.e. the same site I would see in the review app), then their passing would give me confidence the site is basically rendering, which is the main thing I check when reviewing a PR like #3248.

**Comment by calebcartwright** [comment]
I think there is a job that runs the e2e tests now (at least it's run on the most recent PRs i've opened like #3266). I wonder what endpoint the tests are targeting

**Comment by calebcartwright** [comment]
I bet whatever solution is applied here could also be a big help with #2816

**Comment by platan** [comment]
e2e job runs [`e2e`](https://github.com/badges/shields/blob/master/package.json#L111) script, which starts a server and runs e2e tests. We can easily run e2e tests targeting any instance by `CYPRESS_baseUrl=https://shields.io npm run test:e2e`. 
Do we create a staging instance for every PR automatically? If so, we can easily target staging instance because it have consistent naming (https://shields-staging-pr-3240.herokuapp.com/). We just need PR id. 
@paulmelnikow Is this what you want to achieve?

**Comment by paulmelnikow** [comment]
Is it starting the server using `npm start`? I think what we'd want to do instead is first run `npm run build`, and then `npm run start:server`. The tests could still use the server that's running locally, but cypress would get the same static build as a user would see in production.

I think Docker needs something slightly different: a way to start the container, run tests, then shut down the container.

**Comment by calebcartwright** [comment]
> I think Docker needs something slightly different: a way to start the container, run tests, then shut down the container.

I just meant that whatever we do to run the tests against an endpoint (like a staging app) could also be used as the validation piece against the container (just a different endpoint target)

**Comment by platan** [comment]
Yes, the CI job starts server using `start`. It shouldn't be a lot of work to change it to `npm run build` + `npm run start:server`. I can do it.

**Comment by paulmelnikow** [comment]
> I just meant that whatever we do to run the tests against an endpoint here (like a staging app) could also be leveraged in a similar fashion to do the validation piece against the container (just a different endpoint target). Just a matter of specifying the right value for `CYPRESS_baseUrl` if I follow correctly

Ahh, I see, you're suggesting using the e2e tests to validate the docker build. That makes sense. Though for Docker, I think we could get by with something simpler, like checking the result of the static badge endpoint, or if we want to check the frontend too, maybe loading the homepage.

**Comment by paulmelnikow** [comment]
Thanks @platan!
