### ISSUE TITLE
Support for Sonar coverage 

### ISSUE THREAD

**Issue by baev** [badges/shields#328]
SonarQube is an open source platform for continuous inspection of code quality. 

* Old API http://docs.sonarqube.org/pages/viewpage.action?pageId=2392180
* New API http://nemo.sonarqube.org/api_documentation#api/coverage

**Comment by cvrebert** [comment]
So, can this be closed in light of #335?

**Comment by espadrine** [comment]
Sure! Thanks for pointing it out!
