### ISSUE TITLE
Can't use "Let's Encrypt" Logo on Simple Icons with Shields.io

### ISSUE THREAD

**Issue by maidmeow4** [badges/shields#3297]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Can't make use of "Let's Encrypt" Logo on Simple Icons with Shields.io
Try to put a "Let's Encrypt" Logo on the badge, tried multiple URL formats, failed.

:link: **Link to the badge**

https://img.shields.io/badge/Secured_by-Let's_Encrypt-blue.svg?logo=let%27s-encrypt

:bulb: **Possible Solution**

prehaps that single quote is causing this problem?

**Comment by paulmelnikow** [comment]
Huh, it looks like that string is a single right quote. It'd be more expected to use an apostrophe, and would be easier to type! I wonder if they would change it.

In the meantime, this is working:

https://img.shields.io/badge/Secured_by-Let's_Encrypt-blue.svg?logo=let%E2%80%99s-encrypt

![](https://img.shields.io/badge/Secured_by-Let's_Encrypt-blue.svg?logo=let%E2%80%99s-encrypt)

**Comment by calebcartwright** [comment]
Wow, good catch! This one had me scratching my head too

**Comment by paulmelnikow** [comment]
I opened simple-icons/simple-icons#1362 to talk about adding URL- and code-friendly slugs to the package and the website.

**Comment by paulmelnikow** [comment]
Let's track this in #4273.
