### ISSUE TITLE
Badge Request: Gitlab Code Coverage

### ISSUE THREAD

**Issue by Aviortheking** [badges/shields#3333]
:clipboard: **Description**

- Service: Gitlab
- Information: Code Coverage
- ![badge](https://img.shields.io/badge/Coverage-13.76%25-orange.svg)

:link: **Data**

- public API: Yes
- API key: no
- doc: https://docs.gitlab.com/ce/api/pipelines.html#get-a-single-pipeline

- Example: 
_10779832_ is the project's id

from https://gitlab.com/api/v4/projects/10779832/pipelines get the latest pipeline id and then go to https://gitlab.com/api/v4/projects/10779832/pipelines/57333607 to get the `coverage`

:microphone: **Motivation**

You propose already multiple services for Codecoverage but for people who want to use Gitlab's one it would be better

**Comment by calebcartwright** [comment]
Hi @Aviortheking, are you sure there's no API key required here? The documentation you referenced mentions authentication, and I'm also getting HTTP 401 Unauthorized responses on the api calls you included.

**Comment by Aviortheking** [comment]
whoops sorry it's seems to access publics repositories you need the api token with the api scope after it will work for every public repositories
ex: curl --header "PRIVATE-TOKEN: <token>" https://gitlab.com/api/v4/projects/10779832/pipelines/57333607

**Comment by calebcartwright** [comment]
no worries! we'd definitely like to add more badges for GitLab but we need to first figure out how we're going to tackle the authentication piece, refs https://github.com/badges/shields/issues/541#issuecomment-484264221. 

We do already have support for the Pipeline Status badge, but only because we were able to scrape the native badges which didn't require auth.

I'm going to leave this open for now to track the specific badge request for coverage, and once the auth piece has been solved this should be something that could be picked up

**Comment by Aviortheking** [comment]
ok thanks :smile:

**Comment by riskycase** [comment]
Can we reverse engineer it from the svg code? For example if I navigate to 

https://gitlab.com/riskycase/broadcastem-core/badges/trunk/coverage.svg?style=flat-square

 I get the svg response as below

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="116" height="20">
  <g shape-rendering="crispEdges">
    <path fill="#555" d="M0 0 h62 v20 H0 z"/>
    <path fill="#4c1" d="M62 0 h54 v20 H62 z"/>
  </g>

  <g fill="#fff" text-anchor="middle">
    <g font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
      <text x="31" y="14">
        coverage
      </text>
      <text x="89" y="14">
        99.33%
      </text>
    </g>
  </g>
</svg>
```
The variables can be https://gitlab.com/:user/:repo/badges/:branch?/coverage.svg?style=flat-square, with branch defaulting to master

**Comment by calebcartwright** [comment]
Thanks @riskycase! I didn't realize GitLab provided their own coverage badge, but that's something we could certainly support given that it won't be subject to the same rate limiting constraints as the API. 

Though API's are generally preferred, we do have a few other badges we provide that are based on upstream scraping of the svg and have infrastructure accordingly to support that (our GitLab Pipeline Status Badge uses this too)

https://github.com/badges/shields/blob/master/services/gitlab/gitlab-pipeline-status.service.js#L37. 

This should be a pretty easy badge if anyone's interested!

**Comment by chris48s** [comment]
> with branch defaulting to master

This is what the existing GitLab pipelines badge currently does, but I think we should aim to resolve https://github.com/badges/shields/pull/5241 one way or another before we add another GitLab badge replicating that behaviour

**Comment by calebcartwright** [comment]
Yup agreed, I meant to make note of that but got distracted and forgot. Thanks Chris!

**Comment by riskycase** [comment]
> This should be a pretty easy badge if anyone's interested!

Can sure try giving it a go, however I might not be able to assure success if I work on it myself

@chris48s what's your call on skipping the default branch part altogether then?
