### ISSUE TITLE
C++ logo is not shown in the badge

### ISSUE THREAD

**Issue by vinitshahdeo** [badges/shields#3361]
`C++` logo is not showing in the badge. 

`https://img.shields.io/badge/C++-Solutions-blue.svg?style=flat&logo=cplusplus` 

or 

`https://img.shields.io/badge/C++-Solutions-blue.svg?style=flat&logo=c++` 

![badge](https://img.shields.io/badge/C++-Solutions-critical.svg?style=flat)

Link to the logo : [click](https://simpleicons.org/icons/cplusplus.svg)

**Comment by chris48s** [comment]
url-encode the plus signs to fix

https://img.shields.io/badge/C++-Solutions-blue.svg?style=flat&logo=c%2B%2B

![](https://img.shields.io/badge/C++-Solutions-blue.svg?style=flat&logo=c%2B%2B)
