### ISSUE TITLE
GH release asset count wrong

### ISSUE THREAD

**Issue by zbeekman** [badges/shields#3364]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

All the GH asset downloads badges for our project our broken: https://github.com/sourceryinstitute/OpenCoarrays/releases

This is reproducible from the shields.io website
:link: ![GitHub Releases (by Asset)](https://img.shields.io/github/downloads/sourceryinstitute/OpenCoarrays/latest/OpenCoarrays-2.6.3.tar.gz.svg)

`![GitHub Releases (by Asset)](https://img.shields.io/github/downloads/sourceryinstitute/OpenCoarrays/latest/OpenCoarrays-2.6.3.tar.gz.svg)`

The badges further down in older releases used to show the correct number of downloads

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
Looks like a case issue. In the interim, if you use all lower case the badge should work for you
https://img.shields.io/github/downloads/sourceryinstitute/OpenCoarrays/latest/cpencoarrays-2.6.3.tar.gz.svg
![](https://img.shields.io/github/downloads/sourceryinstitute/OpenCoarrays/latest/opencoarrays-2.6.3.tar.gz.svg)
