### ISSUE TITLE
Social buttons

### ISSUE THREAD

**Issue by espadrine** [badges/shields#337]
- GitHub's unofficial Fork / Star / Follow buttons (with counts) are here: http://ghbtns.com/
- Twitter's Tweet / Follow / Hashtag / Mention buttons (with page share count, for a tweet button) are here: https://about.twitter.com/resources/buttons
- Facebook's numerous plugin buttons, usually with a box specifying the number of friends / likes / etc.: https://developers.facebook.com/docs/plugins/follow-button
- Youtube's subscribe buttons (with a figure for the number of subscribers): https://developers.google.com/youtube/youtube_subscribe_button
- Google+ has "badges" that we don't want, but they also have a follow button that is reminiscent:
https://developers.google.com/+/web/follow/ and a +1 button that has no reason to be so different: https://developers.google.com/+/web/+1button/

All those buttons are iframes designed to track users, but I don't see why that should be the case. I believe we can offer consistent buttons that are really fast to load (grr, G+, I am looking at your huge
downloads!) and that do not track users.

Given access to their respective APIs, I can easily add a custom design to more closely match their button style (a clickable element next to a speech bubble with a number in it).

Challenges:

- The left-hand-side custom logo. Both GitHub and Twitter use an `url()` base64 image (SVG for GitHub, PNG for Twitter). We may simply detect GitHub-specific (etc.) badges, and include the correct logo. It is unclear how we will go about allowing any logo.
- The left-hand-side has a link, the right-hand-side has a different link. Links can be implemented by SVG's `xlink:href`. Dynamic CSS works, but not in every form. Both links and CSS don't work inside `<img>` tags, but they work in inline SVG, `<embed>`, `<object>`, `<iframe>`. What's great is that the same code, gracefully degraded in `<img>`, still gives a good result, just a static one. How we will receive those links, given the current API design, is unclear.

Some buttons, such as Twitter's, also do some menuitem magic to provide specific actions in the right-click menu. I doubt that can happen in our SVGs, but we never know.

**Comment by espadrine** [comment]
|Test|Image|
|----|----|
|img| ![](https://thefiletree.com/gh-badges/button.svg) |
|embed| <embed src=https://thefiletree.com/gh-badges/button.svg> |
|object| <object data=https://thefiletree.com/gh-badges/button.svg type="image/svg+xml"></object> |
|iframe| <iframe src=https://thefiletree.com/gh-badges/button.svg style="border:0;width:90px;height:20px"></iframe> |

Camo seems to refuse images inside SVG in an img.

**Comment by espadrine** [comment]
Issue mistake, it seems.

**Comment by espadrine** [comment]
While SVG in `<img>` is very limiting, it allows the use of SMIL. However, the implementation of SMIL seems lacking in Chrome. For instance, this fails:

```html
<rect id="llink" stroke="#d5d5d5" fill="url(#a)" x="0.5" y="0.5"
  width="51" height="19" rx="2"/>
<animate xlink:href="#llink" begin="llink.mouseover" end="llink.mouseout"
  attributeName="fill" from="url(#b)" to="url(#b)" dur="1s"/>
```

**Comment by espadrine** [comment]
It looks like Safari fails to show images directly in an SVG in an `<img>` tag. In any other occurrence (inline, embed, object, iframe), it shows up fine. [WebKit issue here](https://bugs.webkit.org/show_bug.cgi?id=127441).

**Comment by espadrine** [comment]
When live, this will work:

<https://img.shields.io//github/forks/badges/shields.svg?style=social&label=Fork&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNy4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI%2BDQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB3aWR0aD0iNDBweCIgaGVpZ2h0PSI0MHB4IiB2aWV3Qm94PSIxMiAxMiA0MCA0MCIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAxMiAxMiA0MCA0MCIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI%2BDQo8cGF0aCBmaWxsPSIjMzMzMzMzIiBkPSJNMzIsMTMuNGMtMTAuNSwwLTE5LDguNS0xOSwxOWMwLDguNCw1LjUsMTUuNSwxMywxOGMxLDAuMiwxLjMtMC40LDEuMy0wLjljMC0wLjUsMC0xLjcsMC0zLjINCgljLTUuMywxLjEtNi40LTIuNi02LjQtMi42QzIwLDQxLjYsMTguOCw0MSwxOC44LDQxYy0xLjctMS4yLDAuMS0xLjEsMC4xLTEuMWMxLjksMC4xLDIuOSwyLDIuOSwyYzEuNywyLjksNC41LDIuMSw1LjUsMS42DQoJYzAuMi0xLjIsMC43LTIuMSwxLjItMi42Yy00LjItMC41LTguNy0yLjEtOC43LTkuNGMwLTIuMSwwLjctMy43LDItNS4xYy0wLjItMC41LTAuOC0yLjQsMC4yLTVjMCwwLDEuNi0wLjUsNS4yLDINCgljMS41LTAuNCwzLjEtMC43LDQuOC0wLjdjMS42LDAsMy4zLDAuMiw0LjcsMC43YzMuNi0yLjQsNS4yLTIsNS4yLTJjMSwyLjYsMC40LDQuNiwwLjIsNWMxLjIsMS4zLDIsMywyLDUuMWMwLDcuMy00LjUsOC45LTguNyw5LjQNCgljMC43LDAuNiwxLjMsMS43LDEuMywzLjVjMCwyLjYsMCw0LjYsMCw1LjJjMCwwLjUsMC40LDEuMSwxLjMsMC45YzcuNS0yLjYsMTMtOS43LDEzLTE4LjFDNTEsMjEuOSw0Mi41LDEzLjQsMzIsMTMuNHoiLz4NCjwvc3ZnPg0K>

**Comment by hastebrot** [comment]
@espadrine `https://img.shields.io//` should be `https://img.shields.io/` without a second `/` at the end for the SVG path.

**Comment by espadrine** [comment]
Thanks! Fixed it. I'll put it live tonight.

**Comment by espadrine** [comment]
The WebKit issue that prevents Safari from showing the logo [was fixed a couple of months ago](https://bugs.webkit.org/show_bug.cgi?id=99677). It might be in Safari 9. I can confirm that WebKit Nightly does not have the bug.

**Comment by espadrine** [comment]
Here are examples of built-in logos:

![](http://img.shields.io/github/forks/badges/shields.svg?style=social&label=Fork)

![](http://img.shields.io/gratipay/Shields.svg?style=social&label=Donate)

**Comment by marcelstoer** [comment]
This is the only issue mentioning "Facebook" but _that_ shield is not yet available. Is something in the making for FB? Wouldn't have to be the follow shield with all the bells'n whistles. A simple [share shield](https://developers.facebook.com/docs/plugins/share-button/) would help.

**Comment by espadrine** [comment]
@marcelstoer You can definitely open a new issue for that. Big names like Facebook are slightly tricky in that we risk having tons of people use the badge, only to have it start failing once we reach a rate limit, so there is some analysis to be performed on that front. Ideally, we'd use whatever existing buttons already use, but obviously we don't make user agents download JS code, it's all server-side.

**Comment by marcelstoer** [comment]
Looking at the huge, largely uncommented PR backlog I felt very reluctant to invest any time. However, even though the JS universe is very new to me it felt doable with little effort. So, here it is: #861.
