### ISSUE TITLE
Library/cli sibling projects ?

### ISSUE THREAD

**Issue by albanm** [badges/shields#338]
Hello,

From what I see in the repos it seems that the code for badge making and for the server are not separated. I would like to generate badges respecting the shields specification but without using shields.io as a service.

Wouldn't it be nice to have three projects: 'shields-lib', 'shields-cli' and 'shields-server' ? The lib would be as lightweight as possible with the minimum amount of dependencies for easy integration in any project, build script, etc.

So, how about it ? For my needs I think I will extract a small library from you codebase anyway if you don't have objections.

**Comment by paulmelnikow** [comment]
Feel free to reopen if you'd like to discuss further.
