### ISSUE TITLE
Jitpack downloads badge is flaky

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3394]
The Jitpack downloads badges are the most failed tests in CI:

I tried lengthening the timeout to 10 seconds, and I'm still getting no badge. 

<img width="1048" alt="Screen Shot 2019-04-29 at 6 30 25 PM" src="https://user-images.githubusercontent.com/1487036/56931108-e1fec480-6aac-11e9-97f9-c92b502228de.png">

This request never seems to return:

https://jitpack.io/api/stats/com.github.erayerdin/kappdirs

I see a comment at #3220 about API stability so it seems like this was discussed. Any thoughts about how to move forward?

**Comment by calebcartwright** [comment]
Bulk of the conversation about the performance/stability of the Jitpack API can be found over in https://github.com/badges/shields/pull/3221#issuecomment-478675073 and below.

At the time it appeared as if the API had indeed stabilized but apparently not for very long unfortunately

**Comment by erayerdin** [comment]
It seems they still have the same problem. Maybe I can mock the response just for Jitpack Stats. However, that would only solve the testing side.

I will again send an email to Jitpack but it is up to them to solve this problem.

**Comment by calebcartwright** [comment]
Thanks @erayerdin. I've also opened up https://github.com/jitpack/jitpack.io/issues/3849 to see if we can get some updates on this. If this isn't addressed soon I think we'll likely need to deprecate our Jitpack downloads badge, at least temporarily.

With the API being unavailable, our badges are not working at all (in addition to the tests failing) and there's really no point in us presenting those badges to our users at the current time knowing that they are not usable.

**Comment by chris48s** [comment]
If we're consistently failing to render a badge in under 4 secs and there is no sign of resolution, I'd also be in favour of removing the badges. Looking at the grafana stats, we're seeing very few requests on jitpack downloads at this stage.
