### ISSUE TITLE
Node version support policy

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3404]
Tangentially related to #3403:

We should set a policy of which _additional_ Node versions we support for:

1. The npm package
2. Self-hosting
3. Development

For the **npm package**, I'm inclined to do the most popular thing in the JS community, which is supporting LTS versions. That would mean today we'd start requiring 8+, at the end of 2019 we'd require 10+, and a year from now in April 2021, 12+. This strategy is allowing the community to keep things moving forward, and avoiding spending lots of resources supporting very old versions.

For **self-hosting** it would be great if we could support only the ["current" version](https://github.com/nodejs/Release). Or maybe – to give self-hosting users time to upgrade – any version that has been "current" within the last three months. Or maybe – to reduce the frequency of those upgrades – the latest even-numbered version.

The advantage of keeping this window really small is that it gives us the most options with modern syntax, without introducing a transpilation step.

For example, Node 12 supports public static class fields. We can replace:

```js
static get route() {
  return {
    base: 'github/license',
    pattern: ':user/:repo',
  }
}
```

with 

```js
static route = {
  base: 'github/license',
  pattern: ':user/:repo',
}
```

I'm pretty excited to be able to do that.

I want to make sure it's reasonable to self-host this project, and I feel like in many environments it is no big deal to specify whatever node version you might need. Though I don't want to _overinvest_ in self-hosting either.

If there's anyone who's likely to have a problem it could be enterprise users with tightly controlled environments. I'm not anti-enterprise and I'm fine supporting those users (maybe through transpilation) though if the work isn't widely benefiting the community, I'd want to fund it through support contracts.

**Comment by calebcartwright** [comment]
What you've articulated above seems reasonable to me on all counts

I think that providing Shields via a Docker image (presumably through Dockerhub) would help a lot with the self-hosting scenarios. I think it's highly likely that most self-hosting users just want to have a Shields instance up and running and a working Docker image is a quick and easy means. 

I think how we version/tag our artifacts (the package, the Shields app, the potential Docker image, etc.) could be of use here as well (for example if someone _must_ use Node 6.x for whatever reason, then they  have to use older version X of the package, tag X of the repo, tag X of the docker image, etc.)

**Comment by chris48s** [comment]
We're already requiring node >=8 for the NPM package: https://github.com/badges/shields/blob/0a0b5b3f031178851c9d295b9967d81ede052723/gh-badges/package.json#L28 but agree with bumping it to >=10 once 12 becomes current. One thing that probably would be useful would be to explicitly run the package test suite against any node versions we claim to support in the CI build.

Broadly agree with @calebcartwright 's comments both on docker images and tags/releases for the self-hosted version (if we can say "if you need to run this on node 6, run version X or below", that makes a big difference). Maybe we should pick where we are now (or designate some milestone in the reasonably near future) and just tag a version, so we've got a baseline? Being an application (as opposed to a library) and having existed for >5 years without ever doing a "release", maybe calendar versioning makes the most sense for self-hosting. It might also help inform some sort of release cadence.

I'm also going to link https://github.com/badges/shields/pull/2296#issuecomment-456179414 here which is tangentially related.

**Comment by paulmelnikow** [comment]
It sounds like we are broadly on the same page.

Let's start with wrapping up how we handle the package, since that seems a bit simpler.

> One thing that probably would be useful would be to explicitly run the package test suite against any node versions we claim to support in the CI build.

Agreed. I'll open a PR for that once we sort this out. Think that would mean adding package tests for v10 and v11 – though perhaps we're not saying the same thing.

I'm proposing that the npm package support all the current, active, and maintenance versions. Here's the chart:

<img width="876" alt="Screen Shot 2019-05-05 at 9 53 27 PM" src="https://user-images.githubusercontent.com/1487036/57203686-3fe54d80-6f80-11e9-95b7-ba03b8823291.png">

Node 12 is already current. (It was released on 4/23.)

@chris48s Can I ask you to clarify?

**Comment by chris48s** [comment]
Hadn't focussed that there's a period where 8,10 and 12 are all under support simultaneously, or that 12 was released 2 weeks ago :open_mouth: 

What you said :)

**Comment by chris48s** [comment]
This was a useful conversation but I think going forwards, it now falls into the category of ongoing maintenance

For example, I think the next thing to do on this is covered by https://github.com/badges/shields/issues/4973
