### ISSUE TITLE
Licence badges (maybe) shouldn't be red

### ISSUE THREAD

**Issue by borntyping** [badges/shields#342]
Currently the various licence badges are coloured red when they successfully show a licence - this is slightly confusing as across the other badges red indicates a problem. It might be better to use green, or an unrelated colour?

**Comment by espadrine** [comment]
I agree. I feel like green can suggest that it could have been red, as well, which can be confusing. I can see that cocoapods' is black, which I recall was a decision from a member of their community. Would you like all of them to align to using black, or maybe use blue, which we use for a lot of badges with neutral meaning, such as versions?

**Comment by borntyping** [comment]
I think a neutral colour like blue would be better - red tends to mean error, and black/grey tend to mean an unknown state.

**Comment by espadrine** [comment]
This will be live in 24h.

**Comment by borntyping** [comment]
Thanks :smiley:
