### ISSUE TITLE
Transient failures in the e2e tests

### ISSUE THREAD

**Issue by platan** [badges/shields#3430]
E2e tests fails from time to time. It was noticed for the first time in https://github.com/badges/shields/pull/3415#issuecomment-489496658

Let's use this issue as a place for reporting such problems. More data can help in investigating the source of the problem. 

Additionally I would like to check how stable are these tests by running them multiple times.

**Comment by platan** [comment]
I run `e2e-on-build` task 100 times at container of `cypress/base:8` image (we are using this image in CircleCI). And all tests passed.

**Comment by paulmelnikow** [comment]
That sounds good!

Was that container being run on Circle itself, or on your own machine?

**Comment by platan** [comment]
On my own machine. But it's good idea to test it on CircleCI. I will try to do it.

**Comment by calebcartwright** [comment]
I just got the same e2e test failure referenced in the original comment on #3446 

https://circleci.com/gh/badges/shields/53812?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by paulmelnikow** [comment]
These seem to have been running well these days, am I right?

**Comment by calebcartwright** [comment]
> These seem to have been running well these days, am I right?

Agreed. I don't remember seeing this for quite some time

**Comment by platan** [comment]
Maybe updating Cypress from 3.3.0 to 3.3.1 helped somehow. 
Unfortunately I didn't run tests on CicrcleCI. But it seems we do not need it now.

**Comment by paulmelnikow** [comment]
Cool, let's reopen or open a new issue if this recurs!

**Comment by paulmelnikow** [comment]
Just noticed this on latest master: https://circleci.com/gh/badges/shields/59762

Rebuilding it here: https://circleci.com/gh/badges/shields/59772
