### ISSUE TITLE
Badge Request: GitHub repo size for git-lfs

### ISSUE THREAD

**Issue by PackardChan** [badges/shields#3436]
:clipboard: **Description**

Is it possible to display GitHub repo size including the git-lfs files? The current badge of GitHub repo size only reports the size without the git-lfs files.

**Comment by paulmelnikow** [comment]
Hmm, interesting. I'm not sure if GitHub provides a way to access that information except in aggregate.

- https://help.github.com/en/articles/viewing-your-git-large-file-storage-usage
- https://help.github.com/en/articles/about-billing-for-git-large-file-storage

**Comment by PackardChan** [comment]
Thanks for the reply. I have just posted on GitHub Community Forum requesting GitHub to provide this piece of information.

https://github.community/t5/GitHub-API-Development-and/Feature-request-can-GitHub-API-show-repo-size-including-git-lfs/m-p/23555#M1688

**Comment by paulmelnikow** [comment]
It looks like there's not much we can do about this, so closing for now. Feel free to comment on the issue if there's new information and one of the maintainers can reopen it.
