### ISSUE TITLE
MicroBadger doesn't work anymore

### ISSUE THREAD

**Issue by lenovouser** [badges/shields#3437]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

MicroBadger doesn't work anymore.

:link: **Link to the badge**

![](https://img.shields.io/microbadger/layers/layers/_%2Falpine.svg)

`https://img.shields.io/microbadger/layers/layers/_%2Falpine.svg`

**Comment by chris48s** [comment]
Thanks for reporting. Looks like their API has fallen over: https://api.microbadger.com/

I've raised an issue over at https://github.com/microscaling/microbadger/issues/60

**Comment by chris48s** [comment]
Upstream API is actually fine. Its our examples that are wrong:

![](https://img.shields.io/microbadger/layers/_%2Falpine.svg) - https://img.shields.io/microbadger/layers/_%2Falpine.svg

Opening a PR to fix..

**Comment by lenovouser** [comment]
Oh, I should've seen that myself 🤦🏻‍♂️
