### ISSUE TITLE
Ensure tutorial is accurate

### ISSUE THREAD

**Issue by chris48s** [badges/shields#3440]
Feedback from a user in discord

> I have one question guys, I'm trying to perform the tutorial implementing the example service
> I get an error that looks like there's no category for Example
> Do I need to add the Example service to some kind of configuration file or something like this? I'm really lost right now.

Tutorial was missing `static get category { return 'build' }` due to changes to the base class.

The concept of assigning a badge to a category isn't introduced until section 4.4 https://github.com/badges/shields/blob/master/doc/TUTORIAL.md#44-adding-an-example-to-the-front-page but we actually need it right at the start for the examples to run without throwing an error. This means we need to change the narrative of the tutorial a bit as well as just adding `static get category { return 'build' }` to a code example.

**Comment by JosepBernad** [comment]
Thanks @chris48s, this topic is being discussed in the PR #3435. Take a look at the changes if you can.
