### ISSUE TITLE
Mastodon follow

### ISSUE THREAD

**Issue by dessalines** [badges/shields#3458]
A badge, like the twitter follow, but for mastodon. Also shows how many mastodon followers there are. 

:link: **Data**
It comes from the open mastodon API. https://docs.joinmastodon.org/api/libraries/

:microphone: **Motivation**

I do updates for a project of mine on mastodon, this badge would allow ppl to follow the account from the readme.

**Comment by PyvesB** [comment]
Hello @dessalines,

Thanks for the suggestion! Would you like to try implementing this new badge? We have a [nice little tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to get you started. 😉

Cheers,

Pyves
