### ISSUE TITLE
How to put a color condition on a gitlab build pipeline status

### ISSUE THREAD

**Issue by Mnjaro** [badges/shields#3482]
I want to make my badge green if it the pipeline has a success status and red if it failed. I don't really understand how this is made.

**Comment by calebcartwright** [comment]
Hi @Mnjaro what you are describing is the default behavior of how our build status badges work, including for the GitLab pipeline status badge. All you have to do is add your badge wherever you want (like your project README) using the format: https://img.shields.io/gitlab/pipeline/:user/:repo.svg. The coloring is automatically set based on the status of the pipeline.

For example:
https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab-ce.svg
![](https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab-ce.svg)

**Comment by Mnjaro** [comment]
Hello @calebcartwright  thank you for your answer. That wasn't clear for me. Thanks a lot.
