### ISSUE TITLE
Add support for customizing badge colors

### ISSUE THREAD

**Issue by jgranick** [badges/shields#349]
Hey guys,

I am using the "GitHub" style badge in order to denote the latest release of https://github.com/openfl/openfl on Haxelib.

I would not expect Haxelib to be supported out of the box on shields.io, and the Github badge is working great, except I really would like to customize the color. Could this be added? Something like this:

![Haxelib Release](https://img.shields.io/github/tag/openfl/openfl.svg?style=flat&color=orange&label=release)

(but orange, using `color=orange`)

**Comment by espadrine** [comment]
Hi!

Badge colors are usually there to emphasize a point (such as, for tests, whether the tests pass). For versions, it distinguishes at a glance major version zero / pre-release (in the [semver](http://semver.org/) definition). Orange means that the provided API is unstable. Blue means stable.

We could definitely allow to override that color. Wouldn't it defeat its purpose, though?

**Comment by jgranick** [comment]
Ah, I thought it was hard-coded to use blue in order to match GitHub. In general, I believe that the standardized color codes is a good way to go, particularly when coming to `build | passed` or `build | failed` it's really clear.

Although it might ordinarily be discouraged, I feel the `label` value allows the tags to be used in ways, perhaps, they weren't originally intended. For example, it happens that I tag every release we make, so even though haxelib is not a supported type, I've leveraged it to give me what I want, but I didn't realize the significance.

Another system, "Badge Fury", uses green for versions: http://badge.fury.io

If you added support for doing "GitHub Issues", while specifying a tag name (at first I thought the `issues-raw` example was using a "raw" tag) then I would also be interested in replicating a waffle.io badge, by pointing at issues marked "ready", since I'd be faking a Waffle badge, it would be nice to use the same light blue color.

I think it would lend itself to using the existing functionality in creative ways :smile:

**Comment by espadrine** [comment]
Waffle support would definitely be great. So far, [the issue](https://github.com/badges/shields/issues/257) isn't solved, although [sending requests directly to GitHub](https://github.com/waffleio/waffle.io/issues/468#issuecomment-60815712) may solve it.

**Comment by Nijikokun** [comment]
> Badge colors are usually there to emphasize a point (such as, for tests, whether the tests pass). For versions, it distinguishes at a glance major version zero / pre-release (in the semver definition). Orange means that the provided API is unstable. Blue means stable.

What do you mean when you say "API is unstable"

**Comment by jgranick** [comment]
From http://semver.org:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by zbeekman** [comment]
I would like to be able to have some badge color override too

**Comment by dmarcelino** [comment]
:+1: for badge color override

**Comment by montanaflynn** [comment]
+1 

Could work just like the style through a query string such as `?color=brightgreen`

**Comment by timothyfcook** [comment]
This relates heavily to #401 e.g. there is no `color=purple` option which is necessary for a Heroku deploy button.

**Comment by espadrine** [comment]
@timothyfcook Isn't that orthogonal to the issue? We can definitely do this: `http://img.shields.io/badge/heroku-deploy-7251C2.svg`.

![](http://img.shields.io/badge/heroku-deploy-7251C2.svg)

**Comment by timothyfcook** [comment]
Cool. That's great. Maybe it's as simple as adding a bit to the Style section to explain that you can use hexadecimal color codes.

**Comment by espadrine** [comment]
It's meant to be implicit in the segment on how to build custom badges (see the badge color on the right): http://shields.io/#your-badge

**Comment by timothyfcook** [comment]
Just noticed that. Maybe let's highlight it somehow. Very subtle.

**Comment by miroswan** [comment]
How would you add color to a downloads badge?

**Comment by espadrine** [comment]
There is a PR for overriding colors now: https://github.com/badges/shields/pull/547

**Comment by paulmelnikow** [comment]
Related: #842

**Comment by paulmelnikow** [comment]
@RedSparr0w
