### ISSUE TITLE
Is there a way to do a linear color gradient?

### ISSUE THREAD

**Issue by ocefpaf** [badges/shields#3497]
I would like to create a badge with a color gradient from color A to B. If that is not possible and/or it is beyond the scope of shields.io please feel free to just close the issue.

**Comment by paulmelnikow** [comment]
Hi! I think our color validator only accepts known correct colors. A gradient would be a bit complex to specify.

How would this feature be used? What is the specific use case?

**Comment by ocefpaf** [comment]
It is a nice use and, like I mention above, feel free to close if it is beyond the scope, but... I would like two specify two colors and have a linear gradient between them. The goal would be to have the [top bar colors from this site](https://pangeo.io/) in the badge. (I believe it is a CSS like `linear-gradient(left, #5eb130, #003B71)`.)

**Comment by paulmelnikow** [comment]
I think this request is probably out of scope for Shields. One of our goals is to provide consistency in the badges, and I think a gradient background would push pretty hard against that. Thanks for the request!

**Comment by ocefpaf** [comment]
No problem. I understand. Thanks!
