### ISSUE TITLE
The published version of gh-badges is out of date

### ISSUE THREAD

**Issue by pierretasci** [badges/shields#3499]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [x] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
The published version of gh-badges installs with the `anafanafo` dependency at version `0.1.1` but the listed version in the `package.json` is `1.0.0`. I believe the published version in NPM needs to be updated to match the repository version.

:bulb: **Possible Solution**

Push a new version to NPM.

**Comment by chris48s** [comment]
We've just published [version 2.2.0](https://www.npmjs.com/package/gh-badges/v/2.2.0). Release notes are in the [changelog](https://github.com/badges/shields/blob/master/gh-badges/CHANGELOG.md#220)
