### ISSUE TITLE
Add ES5, ES6, ES6+

### ISSUE THREAD

**Issue by fundon** [badges/shields#350]
![es7](https://img.shields.io/badge/es-7-brightgreen.svg)
![es6+](https://img.shields.io/badge/es-6+-brightgreen.svg)
![es6](https://img.shields.io/badge/es-6-brightgreen.svg)
![es5](https://img.shields.io/badge/es-5-brightgreen.svg)

**Comment by espadrine** [comment]
In which context should this be used?

Thanks for the suggestion, anyway!

**Comment by fundon** [comment]
Maybe used for some modules, use es6 syntax for writing.

**Comment by espadrine** [comment]
For some modules? Do you mean npm modules? Is there a package.json field
that I am not aware of?

**Comment by fundon** [comment]
e.g. https://github.com/trekjs/routing
I'm using es6+ syntax to writing my npm module.
This's badge just display syntax status.

**Comment by espadrine** [comment]
What is the procedure for finding which syntax is being used?
