### ISSUE TITLE
Convenient way to provide custom templates

### ISSUE THREAD

**Issue by pcr910303** [badges/shields#3500]
:clipboard: **Description**

I would like a convenient way to provide a new template without having to submit it on this repo. For example, if I have a homemade template like [this](https://gist.githubusercontent.com/pcr910303/f4f4a518e0a5a50d7d1060d3259b9897/raw/d0b6e2df394aba541733a6d3e8a0ae485ad92dfa/modern-template.svg), I can request `https://img.shields.io/static/v1.svg?label=hello&message=world&color=success&url=https%3A%2F%2Fgist.githubusercontent.com%2Fpcr910303%2Ff4f4a518e0a5a50d7d1060d3259b9897%2Fraw%2Fd0b6e2df394aba541733a6d3e8a0ae485ad92dfa%2Fmodern-template.svg` to get a badge based on the provided template.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the ask.

I don't think this is something we should support, for two reasons:

1. DoT has a published security vulnerability and we're going to replace it with template literals (#2428), and I'd question the amount of security exposure relative to the amount of benefit in adding something like this.

2. An explicit goal of Shields to provide consistency of badges. It's been argued that we should provide _fewer_ formats, not more (see e.g. follow-on discussion in #1478). I'd like to add an action button format (see #2824) though I'm not sure there is consensus on that.

In general I feel like we should at most support new formats when there is a compelling use case that doesn't make sense with the other formats.

My suggestion would be to render the badge yourself in something like Runkit or Now 2.0. If you need dynamic data from an existing badge, you can hit the Shields JSON endpoint.

**Comment by pcr910303** [comment]
Okay, thanks for clarifying!
