### ISSUE TITLE
Display decimals when over 1 million

### ISSUE THREAD

**Issue by heaths** [badges/shields#3509]
:clipboard: **Description**

Once downloads hit 1 million, the resolution of downloads is simply an integer, e.g. 1M. Pretty big milestone for some projects, but getting to display 2M might take just as long if not longer. What about showing a single decimal digit, e.g. 1.2M which still fits within limits. Perhaps this drops off after 10M. Same would go for billions, etc.

**Comment by calebcartwright** [comment]
That sounds reasonable to me! 

If anyone is interested in having a look at implementing this, the download count badges leverage the `metric` formatter found [here](https://github.com/badges/shields/blob/master/services/text-formatters.js#L55) that would need to be updated to support this

**Comment by PyvesB** [comment]
This seems like a reasonable request to me. However, I personally think we should be consistent, and do the same for `k`, `G`, `T`, `P` as well, e.g. `1.2k`. The same "big milestone" rational applies to them as well. 😉

**Comment by phamcindy619** [comment]
Is anyone currently working on this? Otherwise, I'd like to give it a try.
