### ISSUE TITLE
Add support for http://issuestats.com/

### ISSUE THREAD

**Issue by adamralph** [badges/shields#351]
At the time of writing, badges at http://issuestats.com/ are redirected to http://shields.io/ but some stuff doesn't work, e.g. https://github.com/hstove/issue_stats/issues/16

**Comment by espadrine** [comment]
Thanks for suggesting this!

I know little about issuestats. I see no API. I'd expect something like `http://issuestats.com/github/joyent/node.json` to work, but alas. If you know more, let us know here.

**Comment by adamralph** [comment]
I've raised an issue over at issuestats asking about this - ttps://github.com/hstove/issue_stats/issues/17

**Comment by hstove** [comment]
Hey shields.io!

I just exposed a JSON endpoint for repositories, and added some special fields to make it easier for shields integration. There are two main badge types for a repository - 'issue close time' or 'pull request close time'. For each of these styles, there are `#{style}_badge_preamble`, `#{style}_badge_words`, and `#{style}_badge_color` attributes available.

**Comment by espadrine** [comment]
Thanks a lot!

**Comment by ChristopherKing42** [comment]
:+1:

**Comment by adamralph** [comment]
Great! Thanks all.
