### ISSUE TITLE
Elements continue offscreen in the badge view modal

### ISSUE THREAD

**Issue by Prouser123** [badges/shields#3513]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

After #3510, if you cannot display all of the UI elements for the badge modal, they continue offscreen and you cannot scroll down to see them.

Reverting the pr commit solves this issue.

:link: **Link**

Image example from #3508:
![image](https://user-images.githubusercontent.com/20697043/58718365-428f6300-83c5-11e9-8c19-5000629031a7.png)

**Comment by paulmelnikow** [comment]
Ack! Yea, agreed, that is worse.

Would welcome a PR to revert the change.

**Comment by calebcartwright** [comment]
I'm opening a PR to revert this momentarily
