### ISSUE TITLE
CircleCI badge for private repo giving "project not found"

### ISSUE THREAD

**Issue by Braden1996** [badges/shields#3514]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
When setting up a badge for my private repo, I just get `project not found`. From your tests, it seems what I'm trying to do should work: https://github.com/badges/shields/blob/master/services/circleci/circleci.tester.js#L36

I have created an API Token with "all" permissions, but this doesn't seem to work either: 
![image](https://user-images.githubusercontent.com/5165963/58754842-802ce280-84d0-11e9-8a96-bd7fbffd792c.png)

:link: **Link to the badge**
https://img.shields.io/circleci/build/gh/VulkFitness/vulk.svg?token=Redacted
(I've tried various edits)

Any ideas? If you need more information, please don't hesitate to ask.

**Comment by calebcartwright** [comment]
Thanks for reporting. I believe this is a bug on our end as we are using `token` for the query param, instead of `circle-token` which is what Circle is expecting

**Comment by calebcartwright** [comment]
@Braden1996 - fix has been deployed to our staging endpoint, can you check your project badge there? Believe it would be something like

https://shields-staging.herokuapp.com/circleci/build/gh/VulkFitness/Vulk.svg?token=...

**Comment by Braden1996** [comment]
@calebcartwright, brilliant! Seems to be working now :)

**Comment by calebcartwright** [comment]
Excellent. It should get deployed to prod in the near future. You can track [this comment](https://github.com/badges/shields/pull/3516#issuecomment-498045987) on the PR that will be updated by the bot once it's been deployed
