### ISSUE TITLE
Daily test runs error on publishing code coverage

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3515]
See https://circleci.com/gh/badges/daily-tests/368 for example

```
...

too many non-option arguments: got 1, maximum of 0
[error] "2019-06-01T15:51:29.091Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2019-06-01T15:51:29.092Z"  'input: ' ''
[error] "2019-06-01T15:51:29.093Z"  'error from convertLcovToCoveralls'

/home/circleci/project/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Failed to parse string
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! daily-tests@0.1.0 coveralls: `cd shields && node_modules/.bin/nyc report --reporter=text-lcov report | CIRCLE_SHA1=$(git rev-parse --verify HEAD) ../node_modules/.bin/coveralls`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the daily-tests@0.1.0 coveralls script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-06-01T15_51_29_100Z-debug.log
Exited with code 1
```

**Comment by paulmelnikow** [comment]
`node_modules/.bin/nyc report --reporter=text-lcov report`

Wondering if that should be

`node_modules/.bin/nyc --reporter=text-lcov report`

**Comment by calebcartwright** [comment]
Believe this was introduced when we bumped nyc from v14.0.0 to v14.1.1 in #3470 

I think you are right @paulmelnikow  that the final `report` option is probably the issue. Seems that the upgrade in nyc included a change (https://github.com/istanbuljs/nyc/pull/1100) that I _think_ is why we're now seeing an error on that. 

I'm going to try removing that `report` and see if the resolves

**Comment by calebcartwright** [comment]
Yup, fix in https://github.com/badges/daily-tests/pull/7 working as expected by removing the last `report` option

**Comment by calebcartwright** [comment]
Fixed in https://github.com/badges/daily-tests/commit/428d9d99399187a64086f85950db1acbc5207415
