### ISSUE TITLE
Support for CodeFactor

### ISSUE THREAD

**Issue by ryan-ccn** [badges/shields#3518]
Can you add support for CodeFactor badges?
The default badges for CodeFactor has round edges but I like the `flat-square` style.

![badge](https://img.shields.io/badge/can_you_please-add_this_feature-green.svg?style=flat-square)

**Comment by calebcartwright** [comment]
Hi @ryan-ccn, thanks for the request. We have an issue template for new badge requests that includes several key data points that are needed for adding a new badge. Would you be able to provide that additional data to assist anyone that wants to help add this badge? 

You can view the full issue template for new badge requests [here](https://github.com/badges/shields/issues/new?template=3_Badge_request.md), but the most relevant data points needed:

```
- Which service is this badge for e.g: GitHub, Travis CI
- What sort of information should this badge show?
  Provide an example in plain text e.g: "version | v1.01" or as a static badge
  (static badge generator can be found at https://shields.io)

Where can we get the data from?

- Is there a public API?
- Does the API requires an API key?
- Link to the API documentation.
```

**Comment by ryan-ccn** [comment]
Service: CodeFactor

Information: code quality

Example: ![CodeFactor](https://img.shields.io/badge/codefactor-A-green.svg)

Public API URL: `https://codefactor.io/repository/github/[username]/[repo]/badge`

I don't know Bitbucket one yet, because I don't use it :+1:

**Comment by ryan-ccn** [comment]
@JettChenT Any help on this, Mr. CodeFactor user?

**Comment by ryan-ccn** [comment]
I expect the Bitbucket one to be `https://www.codefactor.io/repository/bitbucket/[username]/[repo]/badge`.

**Comment by calebcartwright** [comment]
Is there a JSON API available to get the underlying data? We can do badge scraping, but prefer to do that as a fallback option when more friendly APIs are unavailable. 

Would also be worth finding out what all data points are available (just a letter grade) that may warrant a badge

**Comment by ryan-ccn** [comment]
I think not, because CodeFactor doesn't have any documentation on APIs or sth. like that. It's probably private.

**Comment by ryan-ccn** [comment]
:sob:

**Comment by calebcartwright** [comment]
No worries! 

We can certainly implement this badge using `BaseSvgScrapingService`. We've got a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) on creating new badges if anyone would be interested in helping with this. The [CircleCI Build](https://github.com/badges/shields/blob/master/services/circleci/circleci.service.js) and [Azure DevOps Build](https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-build.service.js#L30) badges are also implemented via svg scraping and should serve as a helpful reference.

We're also available to help, answer questions, etc. here and/or on Discord.

**Comment by ryan-ccn** [comment]
Thanks for helping!

**Comment by ryan-ccn** [comment]
Thanks for your help! :+1:
