### ISSUE TITLE
Add support for puppet forge

### ISSUE THREAD

**Issue by DavidJFelix** [badges/shields#353]
A number of puppet modules are hosted here on github. It would be nice for some features which are accessible from the puppet forge api https://forgeapi.puppetlabs.com/ to be visible as badges.

Off the top of my head, I think version would be the most useful badge.

Here are some links: 
- [Puppetlabs stdlib on github](https://github.com/puppetlabs/puppetlabs-stdlib)
- [Puppetlabs stdlib on puppet forge](https://forge.puppetlabs.com/puppetlabs/stdlib/license)
- [API which shows details about package](https://forgeapi.puppetlabs.com:443/v3/modules/puppetlabs-stdlib)

The version can be found in the "releases" property, which is an array of objects. In the object the "version" property holds the version.

**Comment by espadrine** [comment]
Thanks a lot for this information!

**Comment by kyrias** [comment]
If you want the current version then using the `current_release` from the `modules` endpoint seem more useful than using the `releases` endpoint.
