### ISSUE TITLE
Add support for gitter.im

### ISSUE THREAD

**Issue by nijikokun** [badges/shields#354]
So we can get rid of the inconsistent button at the end of button lists:

![Gitter Original](https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667)

I attempted to make a simple one I suppose this could work for it, the icon... is what irks me:

![Gitter](https://img.shields.io/badge/%E2%8A%AA%20GITTER%20-JOIN%20CHAT%20%E2%86%92-brightgreen.svg?style=flat)

```
https://img.shields.io/badge/%E2%8A%AA%20GITTER%20-JOIN%20CHAT%20%E2%86%92-brightgreen.svg?style=flat
```

**Comment by espadrine** [comment]
I agree wholeheartedly. We in fact have a very similar badge for talk.ai (a Shanghai-based equivalent).

Having more information would probably be nice. Talk.ai provides an API with the topic of the rooms and a room-specific color, for instance.

Regardless, this is probably, for now, the closest thing we can do that maintains the visual consistency:

`https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg`
![](https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg)

Lowercase is more readable, which is why it is used on all badges. With uppercase, you cannot distinguish letters by how high they go up or by how low they go down. That's in essence the result of a NASA finding I read at some point, which lead them to change their important warnings to be lowercase.

I am not sure how to add the logo. I could store the image server-side, I presume. I need this ability for this anyway: <https://github.com/badges/shields/issues/337>. In that case, you can help me by making it in SVG.

**Comment by espadrine** [comment]
Copy of @bardiharborow's issue:

Current Gitter badge looks like this: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
Discussions are underway [here](https://github.com/gitterHQ/gitter/issues/636) about switching to shields.io.

This is how a you can make a shields.io badge for Gitter currently: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-join%20chat-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-join%20chat-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
I thought it would be much better to have a badge which looks like this: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-4%20users%20online-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-4%20users%20online-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```

I will try to put together some API examples when I get a chance.

**Comment by bardiharborow** [comment]
@espadrine whoops. Sorry about the duplicate issue.

In terms of getting the icon to work, how about this: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://storage.googleapis.com/codepult-miscellaneous/github/badges/shields/354/badge.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
<svg xmlns="http://www.w3.org/2000/svg" width="142" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="142" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h52v20H0z"/><path fill="#4c1" d="M52 0h90v20H52z"/><path fill="url(#b)" d="M0 0h142v20H0z"/></g><g xmlns="http://www.w3.org/2000/svg" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><g xmlns="http://www.w3.org/2000/svg"><rect x="5" y="5" fill="#fff" width="1" height="5"/><rect x="7" y="6" fill="#fff" width="1" height="7"/><rect x="9" y="6" fill="#fff" width="1" height="7"/><rect x="11" y="6" fill="#fff" width="1" height="4"/></g><text x="31" y="15" fill="#010101" fill-opacity=".3">gitter</text><text x="31" y="14">gitter</text><text x="96" y="15" fill="#010101" fill-opacity=".3">4 users online</text><text x="96" y="14">4 users online</text></g></svg>
```

I got this to work by requesting a badge with `iiiigitter` (to make a space for the logo), removing the `i`s, inserting the logo (which is already SVG in the official badge) and adjusting the text to be centered again (probably isn't pixel perfect). I don't, however have any idea how to do that programmatically as I'm not familiar with the codebase.

**Comment by espadrine** [comment]
@bardiharborow SVG logos are the idea, except they'd be in base64 in an image tag. The tricky bit is to allow arbitrary logos. I think I'll add a `logo` URL parameter that accepts an SVG logo in base64, but I'm not sure how fast we'll hit the size limit and how problematic that'd be. For third-party users, it won't be an issue, since they'll be able to application/x-www-form-urlencoded it.

I'll try to make something tonight.

**Comment by malditogeek** [comment]
Hi! Mauro from Gitter here. I just create a PR with basic support for gitter badges. At the moment doesn't display usercount or anything else but at least will give people the option to personalise the style :)

wdyt? the PR is here #440

**Comment by kavdev** [comment]
@malditogeek, can you implement an api that would get @bardiharborow's badge to work (user count)? That would be something I'd be extremely interested in.

@espadrine, if this goes through, would you be willing to move forward with it?

**Comment by espadrine** [comment]
Sure!

**Comment by espadrine** [comment]
@malditogeek Should I open a bug in https://github.com/gitterHQ/realtime-client/issues to request an enhancement to the API?

Currently, the only way to fetch the number of users in a room is through

```
curl https://api.gitter.im/v1/rooms/555f74e315522ed4b3e0ce42/users -H 'Authorization: Bearer XXXX' -H 'Accept: application/json'
```

However, having `555f74e315522ed4b3e0ce42` as the input is way less clear than `Microsoft/TypeScript` (I don't even remember how I found the hex id, but it probably involved reading the JS downloaded from the page). Is there a way to map (what the doc calls) a `url` to a room id? Could we have `/room-from-url/:url/users`? Or even better, `/room-from-url/:url/usercount`?

**Comment by dregad** [comment]
@espadrine, greetings.

I was just wondering what the status of this is, considering that you have recently closed #440 with some commits pushed to master, yet there is still no Gitter badge on http://shields.io/ as I write this.

Thanks in advance for your feedback !

**Comment by espadrine** [comment]
@dregad It's been live a while, although there was no example for it on the main page. Fixed now!

<https://img.shields.io/gitter/room/nwjs/nw.js.svg>

**Comment by dregad** [comment]
Awesome, many thanks !

I don't care all that much about the room count, that's just a nice to have for me. On the other hand, it really bothered me that Gitter's standard button does not have the same look&feel than the others I use.

**Comment by dregad** [comment]
For the record, Gitter's "official" badge is now standardized

- **Official**: `https://badges.gitter.im/Join Chat.svg`  
  ![Gitter](https://badges.gitter.im/Join Chat.svg)
- **Shields.io**: `https://img.shields.io/gitter/room/badges/shields.svg`  
  ![Gitter](https://img.shields.io/gitter/room/badges/shields.svg)

With regards to the user count feature, here's the [feedback from Gitter team](https://github.com/gitterHQ/gitter/issues/636#issuecomment-162882413):

>>Does this mean you're not going to do the user count thing ? Or is that tracked somewhere else ? 

> Not right now. At the moment you have to have an auth token to make any api request.

**Comment by levithomason** [comment]
I also don't care much for the room count. However, `flat-squared` renders with no icon :(

![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg)
![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg?style=flat)
![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg?style=flat-square) <-- icon missing
```
![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg)
![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg?style=flat)
![](https://img.shields.io/gitter/room/TechnologyAdvice/Stardust.svg?style=flat-square)
```

**Comment by espadrine** [comment]
@levithomason Isn't there one? I see one. What browser and OS are you using?

**Comment by paulmelnikow** [comment]
If you have more information, feel free to open a new issue.

**Comment by levithomason** [comment]
I just got pinged from this issue, but not sure why the notification came just now.  At any rate, the issues seems to have been resolved.  At the time of writing, the icon was missing.
