### ISSUE TITLE
Platform and pod badge starts showing not found for our project

### ISSUE THREAD

**Issue by liuxuan30** [badges/shields#3544]
Hi there,

We have been using the awesome badges for our project https://github.com/danielgindi/Charts

Today I notice the home page and I found two badges `platform` and `pod` are showing `not found`. 

We didn't update any badge URL, just doing normal updates and releases, and I don't know why it's broken now. I tried to find the root cause but it seems it's totally a black box to me. Could you help take a look why these two badges broken?

Our CI and release page seems totally fine, and the `release` badge is showing the correct information.

I checked the pod trunk info, seems fine as well:
```
xuanliu$ pod trunk info Charts

Charts
    - Versions:
      ...
      - 3.2.0 (2018-09-17 02:07:03 UTC)
      - 3.2.1 (2018-10-08 20:02:33 UTC)
      - 3.2.2 (2019-02-13 02:17:58 UTC)
      - 3.3.0 (2019-04-24 02:35:02 UTC)
```

**Comment by calebcartwright** [comment]
Hi @liuxuan30 - I haven't had a chance to look into this in detail yet, but the API response for `Charts` is returning an http 404 resulting in the `not found` message

https://trunk.cocoapods.org/api/v1/pods/Charts/specs/latest

as compared to the API response for ChartsRealm which returns 200
https://trunk.cocoapods.org/api/v1/pods/ChartsRealm/specs/latest

**Comment by liuxuan30** [comment]
Hi @calebcartwright thanks for the quick look.

unfortunately both above URL I ran is 403 forbidden in my browser :( don't know why

But weeks ago I pushed a new 3.3.0 release to pod, everything is fine on my side, and 
`pod trunk info Charts` also shows 3.3.0:

```
xuanliu$ pod trunk info Charts
Charts
    - Versions:
    ...    
    - 3.3.0 (2019-04-24 02:35:02 UTC)
    - Owners:
```

will this be a pod issue? I just don't know how to easily fix it on my side, looks nothing wrong on my side

**Comment by liuxuan30** [comment]
I just checked the url with a HTTP client, and it shows
```
HTTP/1.1 302 Moved Temporarily
Date: Tue, 11 Jun 2019 02:36:58 GMT
Connection: close
Strict-Transport-Security: max-age=31536000
Content-Type: application/json
Location: https://raw.githubusercontent.com/CocoaPods/Specs/9bb09042dd0534d6b588e18731736d37713abecc/Specs/5/1/e/Charts/3.3.0/Charts.podspec.json
```
and 
>https://raw.githubusercontent.com/CocoaPods/Specs/9bb09042dd0534d6b588e18731736d37713abecc/Specs/5/1/e/Charts/3.3.0/Charts.podspec.json

is indeed 404, seems the upload is not successful.

I manually checked my laptop,

I can see a valid pod spec 
>~/.cocoapods/repos/master/Specs/5/1/e/Charts/3.3.0/Charts.podspec.json

in the location, the same path as githubusercontent.com domain.

now the problem could be how to reupload the pod spec easily

**Comment by liuxuan30** [comment]
@calebcartwright 
I have repush to pods again, and now the platform badge seems ok now, but the pod badge is still not found.

It seems the podspec json file location is changed with your API to 
>https://raw.githubusercontent.com/CocoaPods/Specs/97f63bceef235e0ec716ea93fd90a7be2a6d5cd0/Specs/5/1/e/Charts/3.3.0/Charts.podspec.json

and I can see this json file is valid now.

Should I just wait for shield to kind of refresh the cache to see the pod badge?

**Comment by liuxuan30** [comment]
oh yes, speak of the devil, the pod badge is ok now.

Thanks for the quick look so I can try fixing it
