### ISSUE TITLE
Alpine Linux package support

### ISSUE THREAD

**Issue by FranklinYu** [badges/shields#3555]
:clipboard: **Description**

This badge is for Alpine Linux. Package version should be shown. For example, for the package [bash-completion](https://pkgs.alpinelinux.org/packages?name=bash-completion&branch=edge) the badge should be:

![Alpine](https://img.shields.io/badge/Alpine-2.8--r0-blue.svg)

:link: **Data**

I'm not sure whether there is good API besides parsing the HTML page. Will work with Alpine team to find out.

:microphone: **Motivation**

Same as other package managers like APT for Ubuntu/Debian, or DNF for Fedora.

**Comment by PyvesB** [comment]
Hello @FranklinYu,

Thank you for your suggestion!

> I'm not sure whether there is good API besides parsing the HTML page. Will work with Alpine team to find out.

This would indeed be great to know! Please keep us posted. 😉 

Cheers,

Pyves

**Comment by FranklinYu** [comment]
They don't seem to provide official API for that. 😢 

Some users recommend third-party API provided by https://repology.org. Would that work for Shields?

**Comment by PyvesB** [comment]
The Repology API might be a good option, this was actually already requested a while back in #929. @scop recently worked on quite a few of our Linux package version badges, maybe he has some thoughts on this?

**Comment by FranklinYu** [comment]
Thanks a lot! I would track that issue instead.

**Comment by scop** [comment]
Yeah, I was not aware of repology when working on the "native" badges. Would definitively have used that if I had been. Or well TBH I may not have created any badges here at all in that case ;)
