### ISSUE TITLE
Bitbucket issues badge uses the old 1.0 API

### ISSUE THREAD

**Issue by kazssym** [badges/shields#3561]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The Bitbucket issues badge uses the old 1.0 API and no longer works. The pull requests badge can also be affected.

:link: **Link to the badge**

https://img.shields.io/bitbucket/issues/vx68k/netbeans-bitbucket-plugin.svg

:bulb: **Possible Solution**

Use the new 2.0 API instead. I will try to make a pull request.

**Comment by calebcartwright** [comment]
I was just looking at this one myself @kazssym. If you'd like to open a PR that would be great! Let me know, if not I'll take care of it.

https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/

**Comment by kazssym** [comment]
The pull requests badge looks OK.

**Comment by calebcartwright** [comment]
Yeah it's just the issues badge using the deprecated 1.0 api

https://github.com/badges/shields/blob/master/services/bitbucket/bitbucket-issues.service.js#L57

**Comment by calebcartwright** [comment]
@kazssym - thanks for reporting and willingness to submit a PR. I've got the fix for this already in my local env so I am going to go ahead and take care of this one

**Comment by kazssym** [comment]
OK, thanks.
