### ISSUE TITLE
The release badge doesn't work for repo names with dot (.)

### ISSUE THREAD

**Issue by hsluoyz** [badges/shields#3567]
I have a repo named ``Casbin.NET``. It contains a dot in the name. And I found the release badge will say: ``no releases or repo not found``. How to fix? Thanks.

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

``
[![Release](https://img.shields.io/github/release/casbin-net/Casbin.NET.svg)](https://github.com/casbin-net/Casbin.NET/releases/latest)
``

[![Release](https://img.shields.io/github/release/casbin-net/Casbin.NET.svg)](https://github.com/casbin-net/Casbin.NET/releases/latest)

**Comment by calebcartwright** [comment]
Hi @hsluoyz - it seems the badge is working.

https://img.shields.io/github/release/casbin-net/Casbin.NET.svg
![](https://img.shields.io/github/release/casbin-net/Casbin.NET.svg)

I took a look at your repo it seems like you created the 1.1.0 release roughly ~1 hour after opening this issue so I'm guessing that's what resolved this. 

I'm going to go ahead and close this but please feel free to reopen if you're still having an issue with the badge.

**Comment by hsluoyz** [comment]
I found the cause is that it has no releases. After releasing a version, the badge works. Thanks!
