### ISSUE TITLE
Codecov issues, "not authorized to access repository"

### ISSUE THREAD

**Issue by scottbedard** [badges/shields#3584]
:question: **Question**

Hi, I'm trying to use shields.io to display a coverage badge for a private repository. As best I can tell, I've got the correct graphing token included, but I'm still running into auth issues. The badge will display either `not authorized to access repository` or `vendor unresponsive`.

### Codecov's default badge:

`https://codecov.io/gh/spyfu/nacho/branch/dev/graph/badge.svg?token=GRpofazj52`

<img src="https://codecov.io/gh/spyfu/nacho/branch/dev/graph/badge.svg?token=GRpofazj52" />

### Various shields.io configurations:

`https://img.shields.io/codecov/c/github/spyfu/nacho.svg?token=GRpofazj52`

 <img src="https://img.shields.io/codecov/c/github/spyfu/nacho.svg?token=GRpofazj52">

`https://img.shields.io/codecov/c/gh/spyfu/nacho.svg?token=GRpofazj52`

<img src="https://img.shields.io/codecov/c/gh/spyfu/nacho.svg?token=GRpofazj52">

`https://img.shields.io/codecov/c/token/GRpofazj52/github/spyfu/nacho.svg`

<img src="https://img.shields.io/codecov/c/token/GRpofazj52/github/spyfu/nacho.svg" />

If anyone could point me in the right direction here I would really appreciate it.

**Comment by calebcartwright** [comment]
Hey @scottbedard 

We're getting a 401 error when making the Codecov API call with the information you've specified. 
Can you try one/both of the below options and let me know what kind of API response you are receiving?

https://codecov.io/api/gh/spyfu/nacho?access_token=GRpofazj52

Or https://codecov.io/api/gh/spyfu/nacho with a header `Authorization: token GRpofazj52`

**Comment by scottbedard** [comment]
Hi @calebcartwright, neither seemed to work for me, both requests were denied due to invalid credentials. Do you know if I need to do anything beyond providing the token? These badges used to work for me, but lost access a few months ago. Also, do you think this is more likely to be an issue with shields.io or with codecov?

**Comment by calebcartwright** [comment]
Thanks @scottbedard. Shields is reliant on the upstream service endpoints to get the relevant data. The Codecov endpoints you tested are the same ones that Shields has to use internally to get the coverage data. 

The fact that you are also getting 401 errors on those same API calls means that there's either an issue on the Codecov side (with their API and/or their documentation), or with that token. 

I use Codecov myself, but not with any public GH repos so I don't have any experience working with the tokens. I'd recommend going through the steps in their [authentication docs](https://docs.codecov.io/reference#authorization) to create a new token, and then see if you're able to get that new token to work (directly against the Codecov APIs and/or via the Shields badges)

**Comment by scottbedard** [comment]
@calebcartwright ahhh, what I needed was an access token, not a graphing token. Thanks for helping me get to the bottom of this!

**Comment by calebcartwright** [comment]
Excellent! Glad it's working now

**Comment by alanwilter** [comment]
I'm having the same issue but it seems worse because

https://codecov.io/api/gh/alanwilter/acpype

DOES work.

However, when I try:
![Codecov branch](https://img.shields.io/codecov/c/github/alanwilter/acpype/mv2poetry?style=plastic&token=a719f1fe-3a60-49a3-8804-9a44998c9e4a)

I get the nasty `not authorised`. What am I missing here?

**Comment by alanwilter** [comment]
Never mind, once I merged to master it's now working.
