### ISSUE TITLE
badge.js: Node callback should be err, response

### ISSUE THREAD

**Issue by knownasilya** [badges/shields#360]
The accepted format is:

``` js
function (error, response) {

}
```

If you don't use this format, then your API is not open to being promisified, e.g:

``` js
var Promise = require('bluebird');
var badge = Promise.promisify(require('gh-badges'));

badge({..})
  .then(function (svg) {
    // svg here
  })
  .catch(function (error) {
    // error here
  });
```

Basically how it currently is, you can't do the above.

**Comment by espadrine** [comment]
That's a fair point, although this change would obviously break backward-compatibility.

I suppose we could have this for v2.0.0. Let's [make an issue][] for that.

[make an issue]: https://github.com/badges/shields/issues/362
