### ISSUE TITLE
Shield for the "Used by" category on Github

### ISSUE THREAD

**Issue by SeppPenner** [badges/shields#3606]
:clipboard: **A shield for the Github network dependents**

It would be cool if a shield existed for the `Used by` section on Github:

![image](https://user-images.githubusercontent.com/9639361/60006569-015f3b80-9671-11e9-9101-5cc87224faa9.png)

I don't know if this already exists. I couldn't find any information on it, so I assume not.

**Comment by calebcartwright** [comment]
Hi @SeppPenner thanks for the suggestion!

This is a duplicate of #3566 which was closed in favor of tracking this feature request in #1550 (with explanation). 

As such I'm going to close this issue. Feel free to upvote/track/comment/etc. the request over in #1550

**Comment by SeppPenner** [comment]
@calebcartwright I didn't see those issues. This feature would be a great thing but I understand that you can't do anything without the API exposing the data.
