### ISSUE TITLE
img.shields.io is blocked in Russia

### ISSUE THREAD

**Issue by neongreen** [badges/shields#3611]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

One of IPs for <img.shields.io> is blocked in Russia, breaking all badges in the process. I'm not sure it's something you want to fix on shields.io side, but reporting just in case.

<img src="https://user-images.githubusercontent.com/1523306/60193745-e04d4500-9840-11e9-96c6-366f7ffeb6cd.png" width="300px">

:link: **Link to the badge**

N/A.

:bulb: **Possible Solution**

Make sure all provisioned servers are accessible in Russia, or put all servers behind a load balancer (then you only have to care about one IP – this is what I did for my projects).

**Comment by paulmelnikow** [comment]
Hi!

I'm not totally sure how to interpret the results from https://isitblockedinrussia.com/ which are related to different domains from Shields. img.shields.io is already proxied through Cloudflare, and 104.28.20.21 is a Cloudflare IP – which also seems to host other domains.

Are you still experiencing a problem loading badges? I wonder if it's possible that Cloudflare has blocked your IP address. Have you tried other badges and accessing from other IPs?

**Comment by neongreen** [comment]
> img.shields.io is already proxied through Cloudflare, and 104.28.20.21 is a Cloudflare IP – which also seems to host other domains.

Sure – so if this IP gets blocked, img.shields.io (in addition to other domains) gets blocked. I don't know whether it's possible to request a different IP from Cloudflare, but it might work.

This IP is also being reported as blocked according to https://blocklist.rkn.gov.ru/.

> Are you still experiencing a problem loading badges?

Not at the moment. I'm using a different ISP, though, and some ISPs are more lax about enforcing the ban than other ISPs.

**Comment by PyvesB** [comment]
We haven't heard any problems for a while, so I'll go ahead an close this.
