### ISSUE TITLE
Update dependency for simple-icons to version 1.10.0

### ISSUE THREAD

**Issue by rembik** [badges/shields#3619]
:clipboard: **Description**
Update dependency for simple-icons to version 1.10.0 to add more logos.
https://www.npmjs.com/package/simple-icons

**Comment by u3u** [comment]
The latest version has added a lot of icons, please update! 🙏

**Comment by paulmelnikow** [comment]
Resolved via #3622. Keep an eye on the deploy comment for that PR which will tell you when the change has gone live.
