### ISSUE TITLE
Add a country flags

### ISSUE THREAD

**Issue by WHK102** [badges/shields#3638]
Add a country flag, by example: Flag from Usa, Flag from Chile, Flag from Rusia powered, etc.

**Comment by chris48s** [comment]
The goal of shields.io is to provide integrations for services which are primarily used by developers or which are widely used by developers. This suggestion isn't a great fit for that mission.

While we would not want to actually generate badges that look like country flags, you can always make static badges using the flags in the emoji character set.

For example you can already do something like this:

https://img.shields.io/badge/%F0%9F%87%B3%F0%9F%87%B4%20made%20in%20norway-gray.svg
![](https://img.shields.io/badge/%F0%9F%87%B3%F0%9F%87%B4%20made%20in%20norway-gray.svg)

https://img.shields.io/badge/made%20in-%F0%9F%87%A7%F0%9F%87%AA%20belgium-blue.svg
![](https://img.shields.io/badge/made%20in-%F0%9F%87%A7%F0%9F%87%AA%20belgium-blue.svg)

**Comment by paulmelnikow** [comment]
Emoji is a nice solution for this. I'm not sure why, but they aren't rendering for me in Chrome:

Chrome: 
<img width="133" alt="Screen Shot 2019-07-03 at 9 43 12 AM" src="https://user-images.githubusercontent.com/1487036/60596429-ff832f80-9d76-11e9-9ee0-3519c5cf6c8a.png">

Firefox:
<img width="131" alt="Screen Shot 2019-07-03 at 9 43 03 AM" src="https://user-images.githubusercontent.com/1487036/60596425-fd20d580-9d76-11e9-9122-b29a1a54b8dd.png">

**Comment by WHK102** [comment]
> The goal of shields.io is to provide integrations for services which are primarily used by developers or which are widely used by developers. This suggestion isn't a great fit for that mission.

I am a developer and I would like my repository to indicate that it is an application created in Chile because in my country there are not many public developments.

Example: https://github.com/WHK102/wss

**Comment by chris48s** [comment]
We do already support the full [simpleicons](https://simpleicons.org/) set, so you can already make badges like that in userspace using the static badge e.g:

https://img.shields.io/badge/powered%20by%20python-blue.svg?logo=python&logoColor=white
![](https://img.shields.io/badge/powered%20by%20python-blue.svg?logo=python&logoColor=white)

https://img.shields.io/badge/powered%20by%20javascript-gray.svg?logo=javascript
![](https://img.shields.io/badge/powered%20by%20javascript-gray.svg?logo=javascript)

if you want. We also allow users to inject an arbitrary logo using a base64-encoded SVG. Given emjoi support for flag icons seems to be a bit patchy across browsers, another way to do what you want would be to use that feature to inject a custom image. For example:

https://img.shields.io/badge/made%20in%20chile-gray.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgc3R5bGU9Ii1tcy10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7LXdlYmtpdC10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7dHJhbnNmb3JtOnJvdGF0ZSgzNjBkZWcpIj48cGF0aCBmaWxsPSIjZWMxYzI0IiBkPSJNMCAzMnYxMWMwIDYgMyAxMSAxMCAxMWg0NGM3IDAgMTAtNSAxMC0xMVYzMkgweiIvPjxwYXRoIGZpbGw9IiNlNmU3ZTgiIGQ9Ik01NCAxMEgyM3YyMmg0MVYyMWMwLTYtMy0xMS0xMC0xMSIvPjxwYXRoIGZpbGw9IiMyYjM5OTAiIGQ9Ik0yMyAxMEgxMEMzIDEwIDAgMTUgMCAyMXYxMWgyM1YxMHoiLz48cGF0aCBmaWxsPSIjZTZlN2U4IiBkPSJNMTIgMTRsMiA1aDVsLTQgNCAxIDUtNC0zLTUgMyAxLTUtNC00aDV6Ii8+PHBhdGggZmlsbD0icmdiYSgwLCAwLCAwLCAwKSIgZD0iTTAgMGg2NHY2NEgweiIvPjwvc3ZnPg==

![](https://img.shields.io/badge/made%20in%20chile-gray.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgc3R5bGU9Ii1tcy10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7LXdlYmtpdC10cmFuc2Zvcm06cm90YXRlKDM2MGRlZyk7dHJhbnNmb3JtOnJvdGF0ZSgzNjBkZWcpIj48cGF0aCBmaWxsPSIjZWMxYzI0IiBkPSJNMCAzMnYxMWMwIDYgMyAxMSAxMCAxMWg0NGM3IDAgMTAtNSAxMC0xMVYzMkgweiIvPjxwYXRoIGZpbGw9IiNlNmU3ZTgiIGQ9Ik01NCAxMEgyM3YyMmg0MVYyMWMwLTYtMy0xMS0xMC0xMSIvPjxwYXRoIGZpbGw9IiMyYjM5OTAiIGQ9Ik0yMyAxMEgxMEMzIDEwIDAgMTUgMCAyMXYxMWgyM1YxMHoiLz48cGF0aCBmaWxsPSIjZTZlN2U4IiBkPSJNMTIgMTRsMiA1aDVsLTQgNCAxIDUtNC0zLTUgMyAxLTUtNC00aDV6Ii8+PHBhdGggZmlsbD0icmdiYSgwLCAwLCAwLCAwKSIgZD0iTTAgMGg2NHY2NEgweiIvPjwvc3ZnPg==)

:books: relevant docs: https://github.com/badges/shields/blob/master/doc/logos.md

**Comment by RedSparr0w** [comment]
Is it okay if we close this issue?

The general consensus seems to be, this is something we arent going to be implementing as it does not quite fit our guideline/mission, and there is a couple alternatives:
- use an svg logo
- use emojis _(less universal)_

**Comment by paulmelnikow** [comment]
For reasons @WHK102 explained, I think this fits the mission. I don't think we have the bandwidth to maintain svg flags within this repo, though given the issues with emojis, I'd be open to including a set of flag SVGs that were generated and maintained elsewhere.

**Comment by chris48s** [comment]
I'm not convinced on adding another icon set, be that flags or some other icon set. Incorporating SimpleIcons has probably been a net gain for us because we've used it as a way to stop accepting PRs for custom logos into core, but it also shows that pulling in an external icon set generates a non-zero maintenance/support overhead even if someone else maintains the library. Also its a very good fit for this project due to their focus on small sizes for the icons.

In theory, there are a couple of NPM packages of flag icon sets (e.g: https://www.npmjs.com/package/svg-country-flags https://www.npmjs.com/package/flag-icon-css ) which do have the advantage that someone else maintains them, but realistically they're not a good fit for this project IMO. One of the good things about shields is we typically deliver a badge in ~1Kb of SVG (admittedly a bit more with a logo). Although your simple tricolors etc are pretty small in these icon sets, more complex flags can be very large e.g:
https://github.com/hjnilsson/country-flags/blob/master/svg/es.svg (119Kb)
https://github.com/lipis/flag-icon-css/blob/master/flags/1x1/ad.svg (32Kb)
and its mostly used to encode detail that would be lost at the size we render them. You'd want quite a specialised simplified set.

Maybe if we've got hundreds of users upvoting this issue, its a topic to revisit but for the moment I reckon finding and encoding an appropriate image for their flag of choice is best left to the users who are interested in it.

One of the nice things about the custom logo feature is we don't have to include every image a user might want to use on a badge in core :)

**Comment by WHK102** [comment]
I think it would be good to sit down some time to think about the use of the service. To create the service no votes from potential users were needed (as is done in a market study), it was created to satisfy a specific need that could be of help to others. So most of my projects are to satisfy personal needs but at the same time I know that it would be useful to many more people. The flags and logos in general would be helpful to many people. If the service does not have a definition of use it is because it was created thinking about its possible utility in helping developers, as well as the icons and flags.

OVH can give you for 35 Euros a dedicated server with an excellent unlimited bandwidth. An icon on a label with good cache handling and cloudflare can significantly reduce traffic. On the contrary, having custom labels can save a lot of traffic by trying to render custom labels.

**Comment by calebcartwright** [comment]
I'm going to close this given both the age of the issue and the consensus opinion of the core team. Please note the distinction that our rationalization is about not wanting to expand the logo surface, and not commentary on the specific badge/logo combination. 

It's not a matter of resources/infrastructure; we're quite experienced with running the Shields platform (and actually used OVH in the earlier days of the project when the request volume was markedly lower). It's simply that we already provide a feature that can be used to achieve the desired result (as demonstrated above in this thread), and strategically we aren't going to add more custom svgs to manage nor are we willing to accept the tradeoffs/drawbacks of incorporating additional icon sets.

I've observed an increasing popular approach for certain icons where someone will enumerate badges/badge urls with various icons and logos, and which we can then add to our [Awesome Badges](https://github.com/badges/awesome-badges) list to help promote awareness.

That seems like a reasonable path for flag-based badges, but closing as there's no action to be taken here.

**Comment by saedyousef** [comment]
> Emoji is a nice solution for this. I'm not sure why, but they aren't rendering for me in Chrome:
> 
> Chrome: <img alt="Screen Shot 2019-07-03 at 9 43 12 AM" width="133" src="https://user-images.githubusercontent.com/1487036/60596429-ff832f80-9d76-11e9-9ee0-3519c5cf6c8a.png">
> 
> Firefox: <img alt="Screen Shot 2019-07-03 at 9 43 03 AM" width="131" src="https://user-images.githubusercontent.com/1487036/60596425-fd20d580-9d76-11e9-9122-b29a1a54b8dd.png">

This is Chrome on Windows.

**Comment by chris48s** [comment]
There is a bit more info on emoji sequence rendering in https://github.com/badges/shields/issues/5396
