### ISSUE TITLE
readthedocs icon not working

### ISSUE THREAD

**Issue by peterjc** [badges/shields#3639]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Trying to show a ReadTheDocs status, like:

:link: https://img.shields.io/readthedocs/thapbi-pict.svg

But with the readthedocs logo fails:

:link: https://img.shields.io/readthedocs/thapbi-pict.svg?logo=readthedocs
:link: https://img.shields.io/readthedocs/thapbi-pict.svg?logo=ReadTheDocs

Other simpleicons work:

https://img.shields.io/readthedocs/thapbi-pict.svg?logo=Adobe
https://img.shields.io/readthedocs/thapbi-pict.svg?logo=let%E2%80%99s-encrypt

Built in logos do work, e.g.

:link: https://img.shields.io/readthedocs/thapbi-pict.svg?logo=travis
:link: https://img.shields.io/readthedocs/thapbi-pict.svg?logo=appveyor

:bulb: Unsure where in the code to start looking

**Comment by calebcartwright** [comment]
https://img.shields.io/readthedocs/thapbi-pict.svg?logo=read-the-docs
![](https://img.shields.io/readthedocs/thapbi-pict.svg?logo=read-the-docs)

**Comment by calebcartwright** [comment]
Closing this as the icon works with correct icon reference, please feel free to reopen @peterjc if you feel otherwise!

**Comment by peterjc** [comment]
Not, that's fair. It was my mistake

On re-reading, https://shields.io/category/build says:

> ``?logo=appveyor``
>Insert one of the named logos from (bitcoin, dependabot, discord, gitlab, npm, paypal, serverfault, stackexchange, superuser, telegram, travis) or simple-icons. Simple-icons are referenced using names as they appear on the simple-icons site. If the name includes spaces, replace them with dashes (e.g: ?logo=visual-studio-code)

So yes, it does say lower case with dashes - evidently having looked at https://simpleicons.org/?q=read%20the%20docs and the name of the download being ``readthedocs.svg`` I must have assumed that's what you mean by "*as they appear on the simple-icons site*". Oops.

Thanks for the quick pointer at the expected solution.

**Comment by paulmelnikow** [comment]
Feel free to upvote simple-icons/simple-icons#1362, which I think would make this process easier for everyone!
