### ISSUE TITLE
Wrong Versioneye badge url

### ISSUE THREAD

**Issue by freezy-sk** [badges/shields#364]
Right now when I want working Versioneye badge, I must provide more data in URL than just repository name.
Wrong, but working: `https://img.shields.io/versioneye/d/php/yiisoft:yii2/dev-master.svg`
Expected from docs, but not working: `https://img.shields.io/versioneye/d/yiisoft/yii2.svg`

**Comment by espadrine** [comment]
I'm not knowledgeable on the inner workings of VersionEye, but their equivalent badge would be this but does not work: https://www.versioneye.com/yiisoft/yii2/badge.svg

We rely on the same syntax, so whatever works for them (here, https://www.versioneye.com/php/yiisoft:yii2/dev-master/badge.svg) works for us.

If you can provide me with more information as to why they have this syntax, I might be able to help.

**Comment by raindev** [comment]
Cannot get my shields.io VersionEye badge working as well. When I try to use example template for my project it just give's me grey "inaccessible" badge: https://img.shields.io/versioneye/d/raindev/benjamin.svg :neutral_face:

**Comment by freezy-sk** [comment]
@espadrine I looked it up little bit closer and found that VersionEye has different urls based on package language.
JavaScript: https://www.versioneye.com/javascript/jquery:jquery/1.4.5
PHP: https://www.versioneye.com/php/yiisoft:yii2/2.0.6
Ruby: https://www.versioneye.com/ruby/rails/4.2.4
So in case of ruby/rails it's not vendor/package but language/package and in case of other languages which uses vendors it's language/vendor:package

**Comment by julmot** [comment]
What's the URL for NodeJS projects? "javascript" doesn't work for me. It says "dependencies: none".

**Comment by julmot** [comment]
bump

**Comment by espadrine** [comment]
@julmot Without an example, I have no idea. That said, `https://img.shields.io/versioneye/d/javascript/jquery:jquery.svg` works.

**Comment by julmot** [comment]
@espadrine Take [this project](https://github.com/julmot/generator-jmboilerplate) as an example.

**Comment by espadrine** [comment]
@julmot `https://img.shields.io/versioneye/d/user/projects/56b7af26f6e506003a88f1fa.svg`.

I don't know the difference between this type of URL → `https://www.versioneye.com/javascript/jquery:jquery/2.2.0` and that type → `https://www.versioneye.com/user/projects/56b7af26f6e506003a88f1fa`.

**Comment by paulmelnikow** [comment]
Is this still an issue? Do we need help from versioneye?
