### ISSUE TITLE
On Maven-central the wrong 'latest' is used.

### ISSUE THREAD

**Issue by nielsbasjes** [badges/shields#3642]
I'm using this shield for my project

https://img.shields.io/maven-central/v/nl.basjes.parse.useragent/yauaa-parent.svg

The problem is that I see in the shield version 5.1, yet on maven central the latest one is 5.10.

See https://search.maven.org/search?q=g:nl.basjes.parse.useragent

Looks like 'alphabetical' sorting instead of 'version' sorting is used to determine what the latest version is.

**Comment by calebcartwright** [comment]
Best I can tell it looks like [this line](https://github.com/badges/shields/blob/master/services/maven-central/maven-central.service.js#L79) is resulting in the `5.10` version string being changed into `5.1`
