### ISSUE TITLE
Design a production deploy process for the raster server

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3647]
As of #3631 PNG generation is being moved into a microservice. 

PNG badges are a fringe but meaningful use case for badges in emails and services like Slack that don’t support svg. Moving it off-board simplifies the responsibilities of the badge server and hardens the server, as it prevents someone from overloading the server with raster requests. Each requires a subprocess, making them much more expensive than SVG badges. See #3112 for more of the reasoning.

As of now all activities related to the raster server are logged in the Zeit Now console. Deploys are done manually by aliasing `raster.shields.io` to the latest automated staging deploy. (See badges/svg-to-image-proxy#27.)

Let's design and document a process for the raster server production deploy.

As part of that, let's start to design the security program (#2577). We should determine who should have Member and Owner access to the Zeit account, and document that decision, too.

**Comment by paulmelnikow** [comment]
@espadrine mentioned offline a suggestion to include in our documentation an onboarding process for new administrators. 👍

**Comment by paulmelnikow** [comment]
I wanted to mention that I think we need to move ahead with evaluating the replacement for the raster server. The monthly bill is too high.

I was in touch a while back with @ngerakines who added a couple features to [svger](https://github.com/sslhound/svger) that I think would let us use it as a drop-in replacement.

It would be good to briefly read through the code (does anyone read C++ 😄) and consider replacing our current raster server with this one.

**Comment by ngerakines** [comment]
I'd be happy to to a walk-through of svger to explain the endpoints for integration, as well as what deployment looks like.

**Comment by paulmelnikow** [comment]
Our bill for the raster server last month almost doubled to $386. I'll get these posted to Open Collective this week.

**Comment by calebcartwright** [comment]
Thanks @ngerakines! Have you had any experience deploying `svger` to Heroku, and if so how'd you go about it? Would running it in a Docker container be feasible (it looks like it could be from a cursory glance)

**Comment by ngerakines** [comment]
> Thanks @ngerakines! Have you had any experience deploying `svger` to Heroku, and if so how'd you go about it? Would running it in a Docker container be feasible (it looks like it could be from a cursory glance)

Yeah, it can be run in a docker container on Heroku. There is also example kubernetes configuration for deploying it as a service. For the heroku deploy, the main thing that you'll want to keep in mind is the fall-through rules for internal proxying.

    [nginx] routing raster.shields.io/* <-> [svger] GET /*.png fetches <-> [shields.io] GET /*.svg

Alternatively, the PNG endpoints could be served from shields.io using the svger POST interface.

    [nginx] routing raster.shields.io/* <-> [shields.io] GET /*.png <-> [svger] POST /*.png

You can reference the https://github.com/sslhound/svger/packages/20199 docker image or build your own. Everything needed to build the project can be found in the Dockerfile. No host build tools or libraries are required.

**Comment by calebcartwright** [comment]
Closing as we've got this sorted with our proxy running on heroku
