### ISSUE TITLE
Improve docs for self-hosting raster server

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3648]
#3644 adds a version of this text to https://github.com/badges/shields/blob/master/doc/self-hosting.md:

> If you want to host PNG badges, you can also self-host a [raster server][] which points to your badge server.
>
>- In your raster instance, set `BASE_URL` to your Shields instance, e.g. `https://shields.example.co`.
> - Optionally, in your Shields, instance, configure `RASTER_URL` to the base URL, e.g. `https://raster.example.co`. This will send 301 redirects for the legacy raster URLs instead of 404's.

1. So yea, it would be great to improve and test these instructions.
2. It would be nice to ship a Docker image that includes a preconfigured raster server.

[raster server]: https://github.com/badges/svg-to-image-proxy

Ref #3631

**Comment by calebcartwright** [comment]
I'm going to close this given subsequent developments with squint. I think the existing text is sufficient for the Shields side of the equation, and the specifics for squint itself are already tracked in separate issues.
