### ISSUE TITLE
Node version badges "invalid"

### ISSUE THREAD

**Issue by dougwilson** [badges/shields#365]
Suddenly a bunch of my Node.js version badges are saying "invalid". An example is `https://img.shields.io/node/v/mime-db.svg`

**Comment by dougwilson** [comment]
Ah, I think it's from the Node.js 0.12 release yesterday. Looking at your source (https://github.com/badges/shields/blob/321c725949cf58f04fd6b0de5d30af9ce5a6a9b0/server.js#L940-L941), there is the assumption that the first line will contain a file name that is a Node.js binary. Now that ICU is part of Node.js, this is no longer the case (as the file names in that file are sorted alphabetically).

**Comment by espadrine** [comment]
Thanks a lot for your help! The fix is now live.

**Comment by dougwilson** [comment]
No problem :) Thanks for the quick turn-around :D shields.io is so awesome :100:
