### ISSUE TITLE
Proposal: Adopt TypeScript in the frontend

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3657]
I've been doing a lot of frontend work in TypeScript these days, and it's clear that it's dramatically easier to make behavior changes with types in place. Making major changes to the Shields frontend is always very effortful – and the support of types should make it both faster to work on, and a lot more fun.

Although there is a learning curve, I'm convinced the tradeoff is worth it. Here's my reasoning:

1. We haven't attracted a huge number of contributors to our frontend.
2. A type system will speed up experienced frontend developers, not slow them down.
3. We're more likely to attract good frontend developers if the developer experience is good. Types make that experience way better.
4. As code changes, PropTypes take even longer to maintain than TypeScript types, and they provide much less value.

TypeScript plays well with the tools we're already using: React, Prettier, ESLint, and styled-components. Unsurprisingly, it works great in VS Code, which might be the most popular editor for frontend work these days.

It also looks like [it works with Gatsby](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/) too, though I don't have personal experience using it with Gatsby. I expect most of our frontend libraries (like react-pose and react-select) have types, though there may be bit of work writing type defs for some of the smaller ones.

On the server side I still think we want to keep things tipped toward welcoming new contributors who are experienced programmers but not necessarily JS developers. I think our server framework provides a good experience, even for people who aren't familiar with JavaScript, and think @chris48s's work adding documentation with type annotations to our core library is a better way to help them.

**Comment by calebcartwright** [comment]
SGTM. I'm a big fan of TypeScript, but like everything in life, there's pros and cons associated with it that should be considered in context.

The rationale you've outlined above makes a strong case that the pros outweigh any cons in the context of the frontend IMO, so I'm on board!

**Comment by PyvesB** [comment]
I'm not familiar with Typescript and barely ever touch the frontend code anyway. No strong opinion either way.

**Comment by paulmelnikow** [comment]
This is done!
