### ISSUE TITLE
Color Black in "Your Badge"

### ISSUE THREAD

**Issue by Fefas** [badges/shields#367]
I saw this badge in the site main list ![Image](https://img.shields.io/cocoapods/l/AFNetworking.svg), and I found the black color great, but I could not get it with the custom url in the *Your Badge* section:

https://img.shields.io/badge/SUBJECT-STATUS-COLOR.svg

Is there an easy way to get it? If not, could you please add this feature :D :+1:

Thank you

**Comment by espadrine** [comment]
The hint comes from the list of color badges at the bottom of the page. You can use hex colors as a value for COLOR. Say, `https://img.shields.io/badge/SUBJECT-STATUS-000000.svg`, although that might be too dark.
