### ISSUE TITLE
Private codecov.io badge

### ISSUE THREAD

**Issue by zortje** [badges/shields#368]
Private codecov.io badges are accessed using a secret token like this:

```
https://codecov.io/github/{user}/{project}/coverage.svg?branch=master&token={token}
```

Related to #254

**Comment by espadrine** [comment]
Thanks for raising this issue!

This made me see something really peculiar. Currently, we rely on HTTP scraping for this.

This returns `X-Coverage: 100`:
```bash
curl -I 'https://codecov.io/github/codecov/example-python/coverage.png'
```

But this returns `X-Coverage: 91`:
```bash
curl -I 'https://codecov.io/github/codecov/example-python/coverage.svg'
```

I have no idea which is correct.

**Comment by espadrine** [comment]
Now, for private cases. Currently, we have (and cannot change) `/codecov/c/:repo.svg` or `/codecov/c/:repo/:branch.svg`. I noticed from co-workers that having slashes in branches is trendy, so we can't break that either. I'm not sure [what the regexp should look like](https://github.com/badges/shields/blob/master/server.js#L1309).

**Comment by joshdifabio** [comment]
It would be great to get this supported. Is there a really good reason for not using `GET` params to pass tokens to the shields server? It seems to be the most intuitive and simple solution to this.

`http://domain.tld/user/repo/branch.svg?token=foobar`
seems more correct than
`http://domain.tld/user/repo/branch/token.svg`

**Comment by espadrine** [comment]
I'd like to keep `GET` params global — they currently have meaning for any badge. If we took `token` to mean something specific to codecov, every time we want to add a global param, we'd have to make sure it doesn't collide with any GET param used in a vendor, which is a nightmare.

**Comment by joshdifabio** [comment]
Fair point, but most private badges seem to expect a token, it's not specific to codecov.

**Comment by espadrine** [comment]
> most private badges seem to expect a token

That's still very far from a global parameter.

I suppose we could have something like `/codecov/cp/:token/:repo/:branch.svg`.

**Comment by joshdifabio** [comment]
> That's still very far from a global parameter.

Odd. I'll leave you to it.

**Comment by krak3n** [comment]
I'm not great at Regex but took a stab at this and came up with:

``` regex
^\/codecov\/c\/(t:[A-Za-z1-9]+\/)?([^\/]+\/[^\/]+\/[^\/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)$
```

The match groups are:
1. (Optional) Token
2. Repository
3. (Optional) Branch
4. Format

This allows for the following URLs:

* Normal: `/codecov/c/github/codecov/example-python.svg`
* Branch: `/codecov/c/github/codecov/example-python/master.svg`
* Token: `/codecov/c/t:ATOKEN/github/codecov/example-python.svg`
* Token w/ Branch: `/codecov/c/t:ATOKEN/github/codecov/example-python/master.svg`

As I say regex isn't something I'm great at, this works except I can't get it to ignore the `/` on token matches, so for:

`/codecov/c/t:ATOKEN/github/codecov/example-python/master.svg`

The groups values are:

* `t:ATOKEN/`
* `github/codecov/example-python`
* `master`
* `svg`

So there would need to be some cleanup on the token value.

What do you think?

**Comment by espadrine** [comment]
Great work!

I presume, since the repo starts with github, that it lists possible repo registries. Assuming there won't be a `token` registry, we can simply have the following:

```
^\/codecov\/c\/(?:token\/(\w+))?[+\/]?([^\/]+\/[^\/]+\/[^\/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)
```

- token: `/codecov/c/token/ATOKEN/github/codecov/example-python.svg`
- token with branch: `/codecov/c/token/ATOKEN/github/codecov/example-python/master.svg`

**Comment by krak3n** [comment]
@espadrine yup Codecov supports Github, Bitbucket & Gitlab.

That regex is much better, I'll update the PR :+1:

**Comment by espadrine** [comment]
I think we can close this as a result, yes?

**Comment by krak3n** [comment]
:+1:
