### ISSUE TITLE
Github closed issue count

### ISSUE THREAD

**Issue by zbeekman** [badges/shields#369]
It would be nice to be able to list the closed github issues as well as the open ones in a badge

**Comment by olivierlacan** [comment]
Hmm, maybe we're veering a bit too deep into something GitHub displays literally a few hundred pixel away from the README. Do you mean to display elsewhere than on GitHub?

**Comment by zbeekman** [comment]
Where are the *closed* issues listed “a few hundred pixel away from the README?” It’s quite possible they are, but I don’t see them. I see the *open* issue count.

I do understand, however, that this may not be a priority.

**Comment by PeterDaveHello** [comment]
I think we can add a badge for it.

**Comment by montanaflynn** [comment]
Could use the official GitHub API for this, I just wish they included a total count as a header so you wouldn't have to go through pagination. https://api.github.com/repos/badges/shields/issues?state=closed

**Comment by espadrine** [comment]
Let's close the issue here, as we're resolving it there: https://github.com/badges/shields/issues/420
