### ISSUE TITLE
Static Badge Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3700]
:clock11: **When did the problem start?**
~6 days ago

:camera: **Live badge**
Any live static badge will work, seems to be an issue with the tests using the redirect

![]( url goes here )

:wrench: **Is the live badge working?**
Yes

:link: **CircleCI link**
Started failing in https://circleci.com/gh/badges/daily-tests/446

:beetle: **Stack trace**

```
StaticBadge Old static badge [ GET /foo/bar.png?color=blue ] - [ GET /foo/bar.png?color=blue ]
  AssertionError: expected an element of [ Array(1) ] to equal '/badge/foo-bar-blue.png'

StaticBadge Old static badge without a color [ GET /foo/bar.png ] - [ GET /foo/bar.png ]
  AssertionError: expected an element of [ Array(1) ] to equal '/badge/foo-bar-lightgray.png'
```

:bulb: **Possible solution**
Not sure yet

**Comment by paulmelnikow** [comment]
Ah! These were the routes that were removed in #3659. So the tests should be dropped too.

**Comment by calebcartwright** [comment]
Ah okay that makes sense. Semi-related question: would it be worth the effort to set up some daily/twice-daily test runs of the svg-to-image proxy server like we have for Shields?

**Comment by PyvesB** [comment]
There was a small typo in the PR's description, closing this manually!

**Comment by paulmelnikow** [comment]
If we want a live test we could run a local web server in process, and then it wouldn’t be necessary to segregate that test from the others. We could also schedule tests to run on master daily, though I’m not sure it’s necessary. We’ll get dependency bumps every month which is frequent enough for knowing the tooling is up to date.
