### ISSUE TITLE
Packagist internal error: Can't generate a version color for undefined

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3709]
https://sentry.io/organizations/shields/issues/1109294293/?referrer=github_plugin

```
Error: Error: Can't generate a version color for undefined
  File "/home/m/shields/core/server/log.js", line 40, in Function.error
    Raven.captureException(msg, sendErr => {
  File "/home/m/shields/core/base-service/base.js", line 298, in PackagistVersion._handleError
    log.error(error)
  File "/home/m/shields/core/base-service/base.js", line 386, in Function.invoke
    serviceData = serviceInstance._handleError(serviceError)
...
(1 additional frame(s) were not displayed)

Error: Error: Can't generate a version color for undefined
```

**Comment by paulmelnikow** [comment]
This is generating an "internal error" badge. The stack trace is obscure and I'm not sure exactly why that is. On Sentry, the additional stack frame looks like this:

<img width="735" alt="Screen Shot 2019-07-14 at 5 10 46 PM" src="https://user-images.githubusercontent.com/1487036/61189363-5b449700-a65a-11e9-883d-e534909e5e3b.png">

There's also this error:

<img width="784" alt="Screen Shot 2019-07-14 at 5 10 50 PM" src="https://user-images.githubusercontent.com/1487036/61189364-60094b00-a65a-11e9-8acc-1a3b18904d9e.png">

As of now, this has occurred 844 times in the last two days.

**Comment by paulmelnikow** [comment]
This is probably the same error as #3684.

**Comment by PyvesB** [comment]
> I'm not sure the schema forbids an empty versions object.

We may still end up with an empty versions list even though the schema forbids it. Indeed, there is a filter in the `PackagistVersion` implementation:
`versions.filter(version => !/^dev-/.test(version))`

The filter is probably still relevant, it was introduced many years ago [following this discussion](https://github.com/badges/shields/pull/366#issuecomment-75222477). If my understanding is correct, they aren't released versions, they just correspond to branches on a repository, hence the "dev" prefix.

I think a potential fix here is to check if any versions are left in the list before rendering the badge, and if not display something along the lines of `no released versions found` to the user instead.

I'll submit a PR for this. Given that we don't have much information on what caused this problem, there's no guarantee it will fix all the errors, however it still seems like a sensible check to do.

**Comment by PyvesB** [comment]
@paulmelnikow are there still any errors reported on Sentry about this?

**Comment by paulmelnikow** [comment]
I can't tell. Something really strange is going on with Sentry.

When I click on that error, I'm seeing the same stack trace (unsurprising) but a totally different message, "Error: Token pool is exhausted."

It seems like Sentry has started mixing all our errors together.

Some ideas on fixes:

- Migrating to the newer Sentry SDK (#3708)
- Dropping use of `domain`
- Upgrading to Node 12

**Comment by PyvesB** [comment]
@paulmelnikow that's annoying. I've started by reviewing the linked PR. 😉

**Comment by paulmelnikow** [comment]
I guess this is only affecting the Shields internal errors that bubble through our own error handling. These are the ones we started monitoring just recently, in #3706.

**Comment by paulmelnikow** [comment]
#3762 didn't seem to have an effect on this issue, however I did figure out how to see individual events (i.e. a single time the error happened). Here I can see the message that corresponds to each, though still not the full stack trace.

So, I can confirm this particular Packagist error is gone, though I'm getting a new one.

**Comment by PyvesB** [comment]
Okay, feel free to open another issue when you've got more info about this other error!

**Comment by paulmelnikow** [comment]
Thought I had, but I guess I didn't click the button! #3767
