### ISSUE TITLE
Use better <title> and metadata

### ISSUE THREAD

**Issue by olivierlacan** [badges/shields#372]
At the moment shields.io outputs "Image Server" as a page title with no description. We should try to improve this.

https://github.com/badges/shields/blob/46450af165c844300f4258d7bb0e93c97558b04a/try.html#L2
https://github.com/badges/shields/blob/a6d6018cc04d68d421c630ae6ebc32642702992e/index.html#L2

A good page title succinctly describes the purpose of the site. For example mailchimp.com:

> MailChimp: Send Better Email
> Online email marketing solution to manage contacts, send emails and track results. Offers plug-ins for other programs.

What do you think @espadrine?

This is our Twitter description: 
> Quality metadata badges for open source projects.

This is our repo description:
> An image server for legible & concise information.

The latter is a bit too abstract, it doesn't really describe the purpose of the project.

**Comment by espadrine** [comment]
That Twitter description is fairly eloquent. I'll put this in the `<title>`, if you agree.

```html
<title>Shields.io: Quality metadata badges for open source projects</title>
```

**Comment by olivierlacan** [comment]
I agree. :smiley:
