### ISSUE TITLE
Show sponsors on the website

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3737]
These companies make annual monetary contributions of $420:

- Status Hero
- LGTM
- GoJS

These companies donate services for Shields:

- Heroku
- Sentry
- Nodeping

Four others give us services for free as part of their free offerings (or as part of their free offerings for open-source projects):

- GitHub
- CircleCI
- Cloudflare
- Discord
- **Added:** Coveralls

I'd like to acknowledge all of these entities on Shields.io. I'm thinking to start with, I'd like to make a sponsors page that's linked to from the bottom of the main page, and put everyone's logos there.

In the future I could see have higher tiers for lead sponsors, and maybe companies paying more could have their logos at the bottom of the home page (or for that matter, the top of the home page). But a sponsor page with everyone's logos seems like a good place to start.

**Comment by platan** [comment]
We are using Coveralls (https://coveralls.io/github/badges/shields) as well.

**Comment by paulmelnikow** [comment]
I wanted to bump up this issue and see if anyone who's following this might be interested in taking this on!
