### ISSUE TITLE
PyPi Download Statistics Shield Inaccessible

### ISSUE THREAD

**Issue by caronc** [badges/shields#3744]
:beetle: **Description**
For me specifically, it appears that `https://img.shields.io/pypi/dm/apprise.svg?style=flat-square` produces an inaccessible icon. But it seems to be affecting other systems I test with too _([requests](https://img.shields.io/pypi/dm/requests.svg?style=flat-square) for example which is super popular)_.

It started to happen about a week ago; I figured that maybe the issue would go away eventually and chalked it up to probably just some server lagging or outages.  But having been a week now, I just thought I'd touch basis with you guys :slightly_smiling_face: .

The `dw`, `dd` options also provide the same problem. The product is available on PyPi ([here](https://pypi.org/project/apprise/)) and correctly registering statistics ([here](https://pypistats.org/packages/apprise)).

Demo:
[![PyPi](https://img.shields.io/pypi/dm/apprise.svg?style=flat-square)](https://pypi.org/project/apprise/)
Direct Link: [:link:](https://img.shields.io/pypi/dm/apprise.svg?style=flat-square)

:bulb: **Possible Solution**
I got nothing for this section of the bug report; sorry.

**Comment by calebcartwright** [comment]
The daily servicee tests for pypi download badges have been failing regularly too

**Comment by calebcartwright** [comment]
Looks like the pypi stats API is returning 503. 
https://pypistats.org/api/packages/requests/recent returns: 

503 TEMPORARILY DISABLED

**Comment by calebcartwright** [comment]
Here's why: https://github.com/crflynn/pypistats.org/issues/20

**Comment by caronc** [comment]
Great detective work!

Thank you for finding the source so quickly!.  I'm okay with waiting it out; I mean it's clearly out of your control at this time anyway :slightly_smiling_face: !

**Comment by chris48s** [comment]
If this is a long term issue, we could try switching from pypistats to pepy: https://pepy.tech/

https://pepy.tech/project/apprise
https://api.pepy.tech/api/projects/apprise

That would give us data for total, monthly and weekly downloads. Pepy also includes mirrors which is a feature that has been requested via discord.

**Comment by calebcartwright** [comment]
> If this is a long term issue, we could try switching from pypistats to pepy: https://pepy.tech/

Nice! Great to not only have an alternative, but one that in turn helps us add a new feature. Based on the other thread, I'm not too optimistic that pypistats will back online quickly.

**Comment by calebcartwright** [comment]
I stand corrected (happily 😄)

Looks like pypistats is back online, and our badges are accordingly working again as well. Going to close this out.
