### ISSUE TITLE
Example/url builder wrong for Nexus (Query Options) badge

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3745]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Refs https://github.com/badges/shields/pull/3717#discussion_r305450656

The defined [route pattern](https://github.com/badges/shields/blob/master/services/nexus/nexus.service.js#L49) for the Sonatype Nexus badges has an optional trailing route param (query options) that's _not_ separated from the preceeding route parameter with a `/`.

However, the [example listing route pattern](https://github.com/badges/shields/blob/master/services/nexus/nexus.service.js#L102) used for the Sonatype Nexus (Query Options) badge incorrectly inserts a `/`, resulting in generating a bad url/404

:link: **Link to the badge**

This badge url works:
https://img.shields.io/nexus/fs-public-snapshots/https/repository.jboss.org/nexus/com.progress.fuse/fusehq:c=agent-apple-osx:p=tar.gz.svg 
![](https://img.shields.io/nexus/fs-public-snapshots/https/repository.jboss.org/nexus/com.progress.fuse/fusehq:c=agent-apple-osx:p=tar.gz.svg) 

However, the badge url generated from the modal window does not (returns 404 badge not found):
https://img.shields.io/nexus/fs-public-snapshots/https/repository.jboss.org/nexus/com.progress.fuse/fusehq/:c=agent-apple-osx:p=tar.gz.svg 

:bulb: **Possible Solution**
We'll likely move the optional trailing `queryOpt` from a route param to a query param, with a respective redirector to maintain backwards compatibility

**Edit** - Fixed typos

**Comment by paulmelnikow** [comment]
Agreed that moving the host and/or query opt to the query string is a good idea, and suppose there probably is a reportable bug in `path-to-regexp` here, as well.
