### ISSUE TITLE
Jenkins coverage with Code Coverage API?  

### ISSUE THREAD

**Issue by henryborchers** [badges/shields#3761]
Is the standard [Jenkins Code Coverage API](https://plugins.jenkins.io/code-coverage-api) supported for generating coverage badges?

**Comment by calebcartwright** [comment]
We do support coverage badges from Jenkins, although I don't recall off hand which APIs Shields is using. 

https://img.shields.io/jenkins/coverage/cobertura/https/jenkins.sqlalchemy.org/job/alembic_coverage.svg 
![](https://img.shields.io/jenkins/coverage/cobertura/https/jenkins.sqlalchemy.org/job/alembic_coverage.svg)

**Comment by PyvesB** [comment]
Hello @henryborcher! We only currently support code coverage surfaced through the [JaCoCo](https://plugins.jenkins.io/jacoco) and [Cobertura](https://plugins.jenkins.io/cobertura) plugins. You have to use one of them to get Jenkins coverage badges. 😉

**Comment by henryborchers** [comment]
@PyvesB Well then. It's a non-starter for me. I stopped using those plugins directly when Jenkins came out with the unified coverage plugin. It unifies those formats into a single API so I don't have to worry about the various coverage formats. Plus, the UI is useful and pretty so I'm not going back.

oh well   I have a hacky way of doing it now anyways. It works for now.

**Comment by calebcartwright** [comment]
@henryborchers - if the plugin exposes coverage data via an API, then we'd certainly be open to extending our Jenkins support to provide coverage badges via that plugin as well.

**Comment by henryborchers** [comment]
it's really pretty easy.  All I needed to do was use this info to create my own. 
https://jenkins.io/blog/2018/08/17/code-coverage-api-plugin-1/#rest-api

My only issues is that I don't know enough about JSON querying to make it reduce the significant digits.  
My hacky example for reference: https://github.com/UIUCLibrary/Speedwagon/edit/master/README.rst

**Comment by henryborchers** [comment]
better link: https://github.com/jenkinsci/code-coverage-api-plugin#rest-api

**Comment by calebcartwright** [comment]
Thanks! I'll open up a new Badge Request issue with a cross reference to this thread. That way someone can pick this up and submit a PR if they have an interest in doing so
