### ISSUE TITLE
PackagistPhpVersion: message is required

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3767]
This is coming in through Sentry:

```
Error: ValidationError: {
  [41m"message"[0m[31m [1]: -- missing --[0m
}
[31m
[1] "message" is required[0m
```

**Comment by PyvesB** [comment]
Just to avoid any confusion, this is a different badge ([PackagistPhpVersion](https://github.com/badges/shields/blob/master/services/packagist/packagist-php-version.service.js)) than the one in #3709 ([PackagistVersion](https://github.com/badges/shields/blob/master/services/packagist/packagist-version.service.js)).

The [schema](https://github.com/badges/shields/blob/master/services/packagist/packagist-base.js#L14) does not require the PHP version to be set, therefore we may not be returning a `message` value when rendering the badge, which I think is the cause of the above error. I'll first try to find a example to reproduce this.
