### ISSUE TITLE
GitHub release badge shows "none"

### ISSUE THREAD

**Issue by driskell** [badges/shields#377]
This could be my fault but interestingly my repository shows as "none" instead of "v1.3":
https://img.shields.io/github/release/driskell/log-courier.svg

![](https://img.shields.io/github/release/driskell/log-courier.svg)

=====
Separate to my not-working-release-badge, looking at server.js the entire list of releases of downloaded and filtered/sorted (https://api.github.com/repos/driskell/log-courier/releases). Is there a reason it does not just request the latest (https://api.github.com/repos/driskell/log-courier/releases/latest)?
Documentation for latest request: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by espadrine** [comment]
You are right, the current design (which probably only exists because of copy and paste) is not ideal and your bug proves it. Let's use github's `/latest`. If you want to contribute to shields, I'll let you make a PR. Otherwise, tell me, and I'll fix it myself.

**Comment by driskell** [comment]
I raised PR to fix this as it looks like latestVersion is peculiar. Will raise another shortly for using the latest API instead - but I think latestVersion needs fixing still.

One question RE contributing:
https://github.com/badges/shields/blob/master/CONTRIBUTING.md

It says gh-badges is the chosen implementation moving forwards. Yet going to [gh-badges](https://github.com/badges/gh-badges), it says "Go to badges/shields" - little confused - should I be patching this somewhere else too?

**Comment by espadrine** [comment]
RE contributing, shields used to host (up to a year ago) only the design documents, and gh-badges hosted the website. Now, this repo does it all. I'll fix it to make it clearer.

**Comment by espadrine** [comment]
The PRs are now live on shields.io.

**Comment by driskell** [comment]
Thanks! Superb on getting it up so quick!
