### ISSUE TITLE
Provide the endpoint response's label and message as an alt text option

### ISSUE THREAD

**Issue by nodes777** [badges/shields#3795]
**Issue**
Currently, when using the [JSON endpoint method](https://shields.io/endpoint) of generating a badge, the returned img element has an alt="". A user should be able to use the endpoint's label and message to populate the alt attribute. This is a use case where presumably the badge information is being generated dynamically, and therefore a user can't reliably fill in the alt text themselves.

This creates an accessibility issue where screen reader users are not able to receive the same information. The information that is visually apparent is not programmatically present.

**Expected Behavior**
For example, if I'm grabbing some code coverage information from a third party, and return the following object:
`{
  "schemaVersion": 1,
  "label": "Line Coverage:",
  "message": "98%",
  "color": "orange"
}`

Then then generated badge img should be:

`<img alt="Line Coverage: 98%" src="<the-generated-url>">`

I'd suggest that the default behavior be that the label and message be the alt attribute, though providing the option to override that would also be appreciated.

Thank you!

**Comment by paulmelnikow** [comment]
Hi! Thanks for your question.

What do you mean, the returned img element? Are you talking about the "Copy HTML" option under the "Customize and test" section of the frontend?

**Comment by nodes777** [comment]
Hi Paul,

Thanks for your time!

I'm referring to the img element in the below picture from the [example JSON page](https://shields.io/endpoint). Where the "is it monday" img has an alt of null (alt=""). But I would expect the alt to contain the text in the image "is it monday no". And to be able to provide the label and message properties to the alt of any badge.

Let me know if that makes sense.

Thanks!

![Capture](https://user-images.githubusercontent.com/10222435/63356052-243a6300-c335-11e9-8d8a-12dd0eb3756c.PNG)

**Comment by paulmelnikow** [comment]
Hmm, I'm not totally sure what you want to accomplish.

When you embed the badge in a web page using an <img> element, if the badge is dynamic, that means you don't know what the text will be until the endpoint is hit. If the badge is always the same, sure, you can put the text in the alt attribute, though you may as well use a static badge instead of the endpoint badge.

The web page you're looking at is solely for previewing so the only thing that would make sense to use for an alt is something like "endpoint badge preview".

And again, there's the same issue which is that the alt attribute needs to be set on the frontend, and the contents of the badge is not known by the frontend.

Not quite sure what you're wanting to accomplish, though if accessibility is the goal maybe we could [emit something useful in the <title> of the svg](https://www.sitepoint.com/tips-accessible-svg/)?

**Comment by nodes777** [comment]
Hmm perhaps I'm not understanding the underlying technology here.

I would imagine if you're hitting an endpoint with the expected message and label values, you're using that to generate the img, and you could also return those values as the img alt.

I'm not flagging this issue as solely for this endpoint badge preview page, but for anyone using the service. For example, on my [github page](https://github.com/nodes777/flower-game-phaser3) the line coverage badge is being generated dynamically. But I'm manually filling in the alt text with "lines coverage", and as you say I can't provide the percentage covered.

I think I'm misunderstanding the technology here, I suppose in markdown the only alt that can be provided is the manual one. I think this can be closed until I have a clearer grasp on how the whole system works.

Thanks for investigating!

**Comment by paulmelnikow** [comment]
> I'm not flagging this issue as solely for this endpoint badge preview page, but for anyone using the service. For example, on my [github page](https://github.com/nodes777/flower-game-phaser3) the line coverage badge is being generated dynamically. But I'm manually filling in the alt text with "lines coverage", and as you say I can't provide the percentage covered.
>
> I think I'm misunderstanding the technology here, I suppose in markdown the only alt that can be provided is the manual one.

Yea, in general this is not possible using `<img alt>`, as the `<img>` is part of the source code of the calling web page and all we do is generate the source that the `<img>` points to. The alt text necessarily has to be set by the calling web page.

The only things I think we could possibly do here would be to set `<title>`, and we could add functionality to our UI to add a field that lets you type in a value that's used for the generated HTML. Feel free to experiment and if you think either of those makes sense, let us know. Thanks!

**Comment by chris48s** [comment]
While it is unrealistic to include actual badge text in an alt tag for the reasons Paul has explained, there is a reasonable point raised in this issue: On the shields.io website, there are several places where we've got `<img>` tags without any alt tag at all, and we can easily fix this. I've submitted PR #3903 to at least improve that
