### ISSUE TITLE
grey "fixed" shield for circleci should just be a green "passing" shield

### ISSUE THREAD

**Issue by bcherny** [badges/shields#380]
otherwise, the current state depends on the previous state (ie. sometimes a passing build shows up as "passing", sometimes as "fixed"). the behavior should be to always show either "failing" or "passing".

**Comment by espadrine** [comment]
Thanks for pointing this out! I'd love you to provide an example badge with gives "fixed", so that I can check that I'm… fixing… the issue.

**Comment by espadrine** [comment]
Tell me if this fixes things.
