### ISSUE TITLE
Add Mingle support

### ISSUE THREAD

**Issue by CraigCav** [badges/shields#381]
Integration with [Mingle](http://www.thoughtworks.com/mingle/) would be handy: 

I'm thinking something along the lines of having badges per github pull request, where the PR might correspond to a "card" in mingle. 

The badge could indicate the current Mingle status of the related card and might look something like this albeit with a different URL:

[![Mingle Card Status](https://img.shields.io/badge/mingle%20%23322-Development%20Complete-006b75.svg)](http://www.thoughtworks.com/mingle/#322)

``` md
[![Mingle Card Status](https://img.shields.io/badge/mingle%20%23322-Development%20Complete-006b75.svg)](http://www.thoughtworks.com/mingle/#322)
```

**Comment by espadrine** [comment]
Thanks for suggesting!

The API looks like it is documented [here](http://www.thoughtworks.com/products/docs/mingle/current/help/mingle_api.html).

**Comment by paulmelnikow** [comment]
PR: #382

**Comment by PyvesB** [comment]
Mingle will be retiring in July 2019 ([source](https://www.thoughtworks.com/mingle/news/2018/07/31/mingle-is-retiring.html)). It's therefore probably not useful to implement badges at this point. Therefore closing this issue.

Feel free to open new issues for any other ideas you may have! 😉
