### ISSUE TITLE
service tests for JenkinsTests failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3818]
:clock11: **When did the problem start?**
~2 days ago

:camera: **Live badge**
Badge itself is fine, looks like the target Jenkins instance used for these tests is offline/unavailable 

https://ci.eclipse.org/openj9

:wrench: **Is the live badge working?**

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/497

:beetle: **Stack trace**

```
Error: Request timed out after 5000 ms
```

:bulb: **Possible solution**
If the target Jenkins instance doesn't come back online within the next couple days, we can just find a different target instance

**Comment by PyvesB** [comment]
See this issue [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549790): the OpenJ9 project will be migrating to a more modern and stable Jenkins infrastructure shortly, so hopefully this should be resolved soon.

**Comment by PyvesB** [comment]
The migration was completed and if I'm not mistaken the error is no longer showing up in the latest daily tests, I suggest we close this issue for the time being. :wink:

**Comment by calebcartwright** [comment]
Agreed, looks like they've been passing since https://circleci.com/gh/badges/daily-tests/522
