### ISSUE TITLE
npm install error due sinon.js 7.4.0

### ISSUE THREAD

**Issue by Spragalas** [badges/shields#3834]
Build fails because npm does not find sinon.js 7.4.0 package

**Comment by calebcartwright** [comment]
Hi @Spragalas, can you please provide some more information? It's not clear what "build" you are referring to.

Specifically, what are you working with:
- [ ] [shields.io](https://shields.io/#/)
- [ ] Your own self-hosted instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

And what error message are you seeing, where are you seeing it?

I'm not sure about v7.4.0, but there is a version [v7.4.1 of Sinon](https://www.npmjs.com/package/sinon/v/7.4.1). Which will be satisfied by our [dev dependency reference on Sinon](https://github.com/badges/shields/blob/master/package.json#L243)

**Comment by Spragalas** [comment]
I was building my own self hosted instance. There was npm error which said that sinon@7.4.0 was not found. 

Sorry. I cant give you specific error since i am out for a weekend

**Comment by paulmelnikow** [comment]
Which is our lockfile specifying? If we’re on 7.4.0 probably we should bump to 7.4.1.

**Comment by Spragalas** [comment]
I agree. Once i bumped version in packages.json and deleted lock file everything went fine.

**Comment by calebcartwright** [comment]
I've been unable to reproduce this in any of our build environments, but I can reproduce it locally on both Linux (Node v8.11.2/npm v5.8.0)  and Windows (Node v10.9.0/npm v6.2.0)

**Comment by paulmelnikow** [comment]
Very strange… I wonder if it’s in a cache on the build machines.
