### ISSUE TITLE
host the API docs somewhere

### ISSUE THREAD

**Issue by chris48s** [badges/shields#3883]
:clipboard: **Description**

While the docs are by no means complete, we've got enough of the internal API documented that there is value in hosting the built docs somewhere so contributors can refer to them. Ideally we should build the docs in CI on a successful merge to master and deploy them somewhere so they are always up-to-date.

Related conversation: https://github.com/badges/shields/pull/3645#discussion_r300880256

**Comment by paulmelnikow** [comment]
If you're game to give Netlify a try I'm happy to set that up. It'll handle both the merges to master and PRs, which is a bonus when you're writing or editing new docs.

**Comment by chris48s** [comment]
Yeah absolutely :+1:

**Comment by chris48s** [comment]
I set up https://shields-docs.netlify.com/ It will rebuild on merge to master. There is very little to configure there, but I've sent you an invite to the account to increase :bus:-factor. If any other maintainer wants access, let me know and I'll add you.
