### ISSUE TITLE
sloc badge

### ISSUE THREAD

**Issue by szepeviktor** [badges/shields#390]
How to create a GitHub repo sloc badge?

**Comment by szepeviktor** [comment]
https://github.com/flosse/sloc/issues/47#issuecomment-81227898

**Comment by espadrine** [comment]
Once you have the data for it, you can obtain a badge to display your sloc, as described on shields.io:

`https://img.shields.io/badge/size-6.1K-blue.svg`

![](https://img.shields.io/badge/size-6.1K-blue.svg)

**Comment by szepeviktor** [comment]
Thank you. 
Do you know any CI-like way to count sloc?

**Comment by espadrine** [comment]
What do you mean by CI-like?

Isn't that what https://github.com/flosse/sloc does?

Something like this should work:

```bash
sloc project | awk something | xargs badge size > sloc.svg
```

**Comment by szepeviktor** [comment]
I mean a service that runs on every commit and reports the sloc value.
As I'm writing this I am thinking about a Travis script that does it.
But how to get the result from Travis?

So it should be automatic as Travis.

**Comment by szepeviktor** [comment]
Like in https://github.com/badges/shields/blob/master/.travis.yml

**Comment by szepeviktor** [comment]
OpenHub displays sloc:
https://www.openhub.net/p/wp-cli/widgets/project_partner_badge.gif
But it is not nice.

**Comment by espadrine** [comment]
I see. I don't see an API on openhub. I don't have a smart idea to solve this off the top of my head. There might be a CI that offers this service.

**Comment by ahmadnassri** [comment]
the service rebranded from ohloh to open hub, their API is documented here: https://github.com/blackducksw/ohloh_api

**Comment by szepeviktor** [comment]
Thank you!

**Comment by paulmelnikow** [comment]
Let's track this in #2731.
