### ISSUE TITLE
Add support for ShareLaTeX

### ISSUE THREAD

**Issue by jansegre** [badges/shields#391]
ShareLaTeX has some quite horrible badges:

 ![](https://www.sharelatex.com/github/repos/roboime/pfc-jan-bramigk/builds/latest/badge.svg)

It would be amazing to use badges from shield.io instead.

**Comment by espadrine** [comment]
Their API seems fairly empty: https://www.sharelatex.com/learn/API

Could you contact them to suggest using our badges?

**Comment by jansegre** [comment]
Upstream merged pull request with improved badge.

**Comment by espadrine** [comment]
Great!
