### ISSUE TITLE
Badge request: Leanpub book generation status

### ISSUE THREAD

**Issue by zcorpan** [badges/shields#3927]
:clipboard: **Description**

On Leanpub it's possible to auto-publish on each commit in GitHub. An email is sent with information on whether the generation was successful. Sometimes it's successful but still has some non-fatal errors.

Leanpub allows specifying a webhook after publication:

> The body of the preview and generate posts will be a JSON object that looks like this:
>
>     {"slug":"html-parser-book","generation_type":"publish",
>     "message":"A new version of Writing has been published",
>     "result":"success"}
>
> `generation_type` can be either `preview` or `publish`. `result` can be either `success` or `failure`. The message field is a readable string that can be shown but may change without notice, so don't depend on its current format.

The badge could say "Leanpub | Success" or "Leanpub | Failure".

:link: **Data**

`https://leanpub.com/<some_book>/edit_webhooks` to set up leanpub webhook for *some_book*. This page has documentation of the JSON submitted (see above).

:microphone: **Motivation**

For authors writing on GitHub, to see in their README if there's a problem with publication on Leanpub. Example: https://github.com/zcorpan/html-parser-book#readme

**Comment by PyvesB** [comment]
We deprecated Leanpub badges in #4479, as the API became no longer free. These badges had low usage anyway. Gonna go ahead and close this issue.
