### ISSUE TITLE
Chromatic Storybook badge

### ISSUE THREAD

**Issue by Hongbo-Miao** [badges/shields#3930]
:clipboard: **Description**

Which service is this badge for?
Chromatic https://www.chromaticqa.com/

What sort of information should this badge show?
`Storybook | passing`

:link: **Data**

Cannot find myself, I created an issue under Chroma's team repo at https://github.com/chromaui/storybook-chromatic/issues/3

Hopefully Chroma team can provide some info. 

:microphone: **Motivation**

It would be great to know visual test passing for pull request or branches like master.

**Comment by Hongbo-Miao** [comment]
Hmm, I am not sure this is a good idea now, because Chromatic storybook is not really tests, it need human to approve. So maybe official Storybook badge with link to Storybook might make sense. 

Something like this

<a href="https://www.chromaticqa.com/library?appId=5d626a63a601530020759b10"><img alt="Storybook" src="https://cdn.jsdelivr.net/gh/storybookjs/brand@master/badge/badge-storybook.svg" /></a>

So I will close this request. Thanks!

**Comment by IanVS** [comment]
For anyone else who might be looking for that badge, it is in https://github.com/storybookjs/brand/tree/master/badge.
