### ISSUE TITLE
progress bars

### ISSUE THREAD

**Issue by thosgood** [badges/shields#3932]
:clipboard: **Description**

Since `progresscode.io` is no longer active, it would be nice to have a replacement service, and `shields.io` seems most of the way there! In particular, it would be great to be able to pass a percentage to the message part of the badge and have it displayed as a progress bar. Optional extras, like custom colouring, would then be great (in particular, setting 0% and a 100% value colours, and then having the actual colour of the bar being calculated by interpolating between them).

**Comment by paulmelnikow** [comment]
Hey @thosgood, thanks for the request. This was asked for before just recently at #3775, though I don't think I have a full understanding of the use cases. Could you add some more detail to that thread?

In particular it would be useful to know:

1. Could you describe your use case, and ideally include a link to a repo or post some screenshots?
2. Where would the data come from?
