### ISSUE TITLE
Bower version shows void

### ISSUE THREAD

**Issue by s-a** [badges/shields#394]
https://img.shields.io/bower/v/look-at-this.svg any idea what i am doing wrong?

**Comment by espadrine** [comment]
```js
var bower = require('bower');
bower.commands.info('look-at-this', 'version')
  .on('end', function(version) {
    // Here, version is undefined.
  });
```

If you want to dig deeper, that's what I have. Do you get a different result?

**Comment by s-a** [comment]
Thanks for your reply. Just noticed that tags have not been pushed to GitHub. It works now.
