### ISSUE TITLE
Sync Delay for simple-icons new icons ?

### ISSUE THREAD

**Issue by noraj** [badges/shields#3945]
:question: **Question**

I saw you use simple-icons in the last version available 1.14.0 (commited 23h ago).

https://github.com/badges/shields/blob/0f687540d3aac87afe894d5cdc3e3287dc54ab49/package.json#L62

The simple-icons 1.14.0 brought 4 new icons (see https://github.com/simple-icons/simple-icons/pull/1597) that are not working yet.

![](https://img.shields.io/badge/test-3.2.1-black?logo=jet)
![](https://img.shields.io/badge/test-3.2.1-black?logo=deepin)

Is there a sync delay?

**Comment by calebcartwright** [comment]
Hasn't been deployed yet

https://github.com/badges/shields/compare/gh-pages...master

**Comment by noraj** [comment]
@calebcartwright Righr, thx for you answer.
