### ISSUE TITLE
Badges don't display on Bitbucket

### ISSUE THREAD

**Issue by bittner** [badges/shields#395]
shield.io badges don't display at all on Bitbucket in the **overview** and **file list**. They do display in the **file detail**, but they do seem to do harm to the rest of the page then.

Please compare: (example README)

* https://bitbucket.org/bittner/django-organice
* https://github.com/bittner/django-organice

I've opened [issue #11133 on the Bitbucket issue tracker](https://bitbucket.org/site/master/issue/11133/shieldsio-badges-svg-dont-display-in) about this problem. It contains specific details you may want to look into. I'm not sure whether the problem can be resolved on your side, or whether is completely up to Bitbucket (Atlassian).

**Comment by KapuzenSohn** [comment]
On both Links the Badges are shown, without any Problems or so.
Using Chrome 41 on Linux

**Comment by espadrine** [comment]
Given that it shows up correctly [here](https://bitbucket.org/bittner/django-organice/src/b556ba6da31e0bac02d4075830ab368ef33dc5ad/README.rst?at=develop) and that the reason it fails on the main page is a very poorly escaped HTML that could potentially be a security risk, I'm afraid there is nothing that I should change to shields.io.

Ill-escaped HTML:

```html
<object https:="" img.shields.io="" pypi="" v="" django-organice.svg"="" rel="nofollow" data="<a href=">https://img.shields.io/pypi/v/django-organice.svg" type="image/svg+xml"&gt;Latest version on PyPI</object>
```

Oddly, Travis' badge gets translated to an `<img>` tag and works smoothly.
