### ISSUE TITLE
Add documentation to Discord examples

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3952]
Questions pop up from time to time in our Discord channels, GitHub (for example https://github.com/badges/shields/issues/1659), etc. regarding the process for leveraging our Discord badges. 

It would be great to add those steps inline within the Discord example so that users could see that information directly on Shields.

For anyone interested in tackling this one, all that's needed is to add a `"documentation": ...` key to [this object](https://github.com/badges/shields/blob/master/services/discord/discord.service.js#L26) with the relevant info. 

Here's a couple examples of other Services with docs for reference:
- [CII Best Practices](https://github.com/badges/shields/blob/8621fe42d76b809e9ba4ae844920f8ed0373817a/services/cii-best-practices/cii-best-practices.service.js#L73)
- [Azure DevOps Build](https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-build.service.js#L7)

**Comment by seetd** [comment]
I will try doing this before attempting the W3C badge.

**Comment by calebcartwright** [comment]
Thanks!

**Comment by seetd** [comment]
@calebcartwright Should we include the instructions for enabling the Discord server widget. I made the following video but embedding it adds an image about 311k to the page.

![Discord_Server](https://user-images.githubusercontent.com/35116035/66178961-27fc1d80-e635-11e9-9be7-0101d203b9fb.gif)

**Comment by calebcartwright** [comment]
Ideally there'd be some external docs/guides/videos/etc that we could simply link to from our inline text

**Comment by PyvesB** [comment]
Closed by #4117, thanks @seetd !
