### ISSUE TITLE
Broken badge for Docker image if name has a dash

### ISSUE THREAD

**Issue by kelson42** [badges/shields#3959]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

:link: https://img.shields.io/docker/build/kiwix/kiwix-serve says "repo not found but is exists! See https://hub.docker.com/r/kiwix/kiwix-serve

**Comment by paulmelnikow** [comment]
Hi! I think you're looking for

https://img.shields.io/docker/cloud/build/kiwix/kiwix-serve
![](https://img.shields.io/docker/cloud/build/kiwix/kiwix-serve)

See https://github.com/badges/shields/issues/1400#issuecomment-469507416 for a little more information – the badge you've got is for the legacy Docker builds which is an older API.

**Comment by kelson42** [comment]
@paulmelnikow Thank you :)
