### ISSUE TITLE
Unicode issues with PNG images

### ISSUE THREAD

**Issue by alexfernandez** [badges/shields#396]
PNG images do not show some Unicode characters well, [example](https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.png):
![unicode-badge](https://cloud.githubusercontent.com/assets/876570/6826718/b8808d5e-d303-11e4-9bff-93254e826daa.png)

SVG images OTOH are fine, [example](https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.svg):
![unicode-svg](https://cloud.githubusercontent.com/assets/876570/6826729/cb10f2ec-d303-11e4-82db-4cd68dbf7ffa.png)

**Comment by espadrine** [comment]
I'll try to find the root cause. The use of SVG is heavily recommended, however, as it allows a much smaller download, is much faster to generate, and renders much better on modern screens.

**Comment by alexfernandez** [comment]
Thanks for that! Unfortunately the choice is not always ours, although we will use svg in the examples.

**Comment by paulmelnikow** [comment]
This now seems to be working as intended.

[https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.png](Example)

![quality- -green](https://cloud.githubusercontent.com/assets/1487036/25112319/62716cfe-23be-11e7-8b13-b3d516a8062b.png)
