### ISSUE TITLE
Badge Request: Go (golang) module version from GitHub

### ISSUE THREAD

**Issue by JulienBreux** [badges/shields#3960]
:clipboard: **Description**

- Which service is this badge for: `GitHub`
- What sort of information should this badge show?
`Go | v1.13`

:link: **Data**

- `go.mod` (Eg: https://github.com/JulienBreux/baleia/blob/master/go.mod#L3)

:microphone: **Motivation**

I love Go, I love Shield.io 😉 

👀 **Example**

![Example](https://img.shields.io/badge/go-v1.13-blue)

**Comment by calebcartwright** [comment]
For anyone interested in implementing this, you may want to take a look at the similar service that provides the version of an npm package from the package.json file in a GitHub repo

https://github.com/badges/shields/blob/master/services/github/github-package-json.service.js

**Comment by pedrofracassi** [comment]
I'll work on it later today.

**Comment by hjagodzinski** [comment]
I see @pedrofracassi you didn't make it. If you don't mind I will look into it.

**Comment by pedrofracassi** [comment]
@hjagodzinski please do.

**Comment by calebcartwright** [comment]
In my admittedly limited experience with Go, I've always found the mod file to be in the root of the repo. Is that something that's enforced/required, or would be it possible for someone to have the mod file in a subdirectory of the repo?

**Comment by pedrofracassi** [comment]
Only if it's a monorepo with multiple go packages, I believe. Maybe let people add the path to the badge URL?

**Comment by calebcartwright** [comment]
Thanks @pedrofracassi - that's exactly what I was thinking
