### ISSUE TITLE
Microbadger for Docker 'image size' is unreliable

### ISSUE THREAD

**Issue by rfgamaral** [badges/shields#3988]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

The microbadger to show a show Docker image size stopped working for me, it always says `unknown`.

:link: https://img.shields.io/microbadger/image-size/rfgamaral/gphotos-uploader.svg
:link: https://github.com/rfgamaral/docker-gphotos-uploader/blob/master/README.md (demo)

**Comment by maslick** [comment]
same here :(
https://hub.docker.com/r/maslick/minimalka
https://img.shields.io/microbadger/image-size/maslick/minimalka/latest.svg

**Comment by paulmelnikow** [comment]
We could return a message that makes it clear this is a temporary upstream issue. How about we use the schema to reject this? That way it would show **invalid response data**, which seems like the right thing to say.

Doesn't really help the problem though… seems like either way it would be nice to  have a replacement service.

**Comment by PyvesB** [comment]
> Doesn't really help the problem though… seems like either way it would be nice to have a replacement service.

Believe it or not, Microbadger was already a replacement for the ImageLayers service, which I deprecated a while back!

> If we know this badge is going to be flaky, how about we add that to the documentation and link to this issue for discussion?

Sounds like a good first step, I'll add a bit of documentation. Hitting the webhook does help, @rfgamaral I've just fixed your badge by doing so, so I'll explain how to do that as part of it. I'll also flag this to the Microbadger team again.

**Comment by PyvesB** [comment]
I've notified the Microbadger team again (see link above).

**Comment by PyvesB** [comment]
Good new and bad news:

> @PyvesB thanks for raising this. The issue is microbadger is now a side project and we have limited time to work on it. But we'll do what we can to improve the stability.
> 
> I'll talk with Liz and Anne and we'll see what we can do to improve the situation.

**Comment by PyvesB** [comment]
There's not much else we can do right now, and I don't expect we'll have to action anything on our side when they improve their service's stability. Closing for now.
