### ISSUE TITLE
Vaadin Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3989]
:clock11: **When did the problem start?**
~4 days ago (September 8th)

:camera: **Live badge**
I'm not particularly familiar with this platform, so this live badge is using our example listing.

https://img.shields.io/vaadin-directory/rating-count/vaadinvaadin-grid
![](https://img.shields.io/vaadin-directory/rating-count/vaadinvaadin-grid)

:wrench: **Is the live badge working?**
🤷‍♂ 

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/580

:beetle: **Stack trace**

```
VaadinDirectoryRating [live] rating of the component (eg: 4.2/5) 
  ValidationError: message mismatch: "value" with value "unparseable json response" fails to match the required pattern: /^\d\.\d\/5$/
```

:bulb: **Possible solution**
🤷‍♂

**Comment by chris48s** [comment]
https://vaadin.com/vaadincom/directory-service/components/search/findByUrlIdentifier?projection=summary&urlIdentifier=vaadinvaadin-grid

The error we're wrapping here is `SyntaxError: Unexpected end of JSON input` - its an issue with the API

**Comment by calebcartwright** [comment]
This seems to have been sorted upstream 🤞 

The last two scheduled test runs have passed and the badges appear to be working again as well. I'll close this out if the next daily test run passes
