### ISSUE TITLE
Sonarqube broke?

### ISSUE THREAD

**Issue by drdamour** [badges/shields#399]
out on http://shields.io/ i see sonarqube giving a badge that says invalid

![sonar](https://img.shields.io/sonar/http/sonar.qatools.ru/ru.yandex.qatools.allure:allure-core:master/coverage.svg)

is it broken?

i also setup my own shields server against my behind the firewall sonarqube and get the same thing.

**Comment by drdamour** [comment]
ok i got it to work internally, my port is not 80 so i had host/9000 not host:9000 cause i thought : would cause problems..duh.

the example on the website is still broken though.

**Comment by espadrine** [comment]
Full disclosure, I have no idea how sonarqube works. Maybe the badge is broken because the project it is meant to show has been discontinued. In that case, I'd love you to perform a pull request to use a working badge in `try.html`.
