### ISSUE TITLE
Tracking Issue for @hapi/joi v16.x upgrade

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4031]
Seems like the upgrade from v15.x to v16.x is going to be rather involved. Opening this so we can track this item, especially as I expect the dependabot PRs will continue to be closed/superseeded. 

Release notes for Joi 16: hapijs/joi#2037

https://github.com/badges/shields/pull/4010
https://github.com/badges/shields/pull/4008#issuecomment-531303928

Tasks:

- [x] Update joi-extension-semver for Joi 16 (dszakallas/joi-extension-semver#12)
- [x] Update IcedFrisby for Joi 16 (IcedFrisby/IcedFrisby#304)

**Comment by chris48s** [comment]
Having done the PRs to update those 2 plugins I've got fairly deep into the weeds when it comes to the differences between Joi 15 and 16. I'm happy to continue with the next steps on this

**Comment by paulmelnikow** [comment]
🎉
