### ISSUE TITLE
Drop `async` in the frontend?

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4035]
My understanding is that the global transform which transforms `async` calls in the frontend to promises adds a lot of bloat to the frontend build.

Does anyone know if that is true / still true?

We only use `async` in a few places and I think we could replace these with promises.

**Comment by calebcartwright** [comment]
Not this is particularly helpful, but I have no idea 😄

**Comment by paulmelnikow** [comment]
@Daniel15 any chance you could offer some quick insight on this?

**Comment by Daniel15** [comment]
@paulmelnikow - Just catching up on my emails... Sorry I missed this! Async/await is natively supported by the vast majority of browsers (~91% of users, as per https://caniuse.com/#feat=async-functions). Native async/await is actually more efficient than promises these days:
https://v8.dev/blog/fast-async
![](https://v8.dev/_img/fast-async/benchmark-optimization.svg)

And Chrome also has "zero-cost async stack traces", which means error stack traces include the entire async stack when using native async/await (whereas this is prohibitively expensive to do with callbacks or promises)

**Comment by PyvesB** [comment]
We no longer have any `async` calls in our frontend. Closing as this is no longer relevant.
