### ISSUE TITLE
Azure DevOps tests returns inaccessible

### ISSUE THREAD

**Issue by ChrisBlankDe** [badges/shields#4037]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I want to generate "Azure DevOps tests" badge.
PAT is defined as env var:
PAT has full access to Azure Devops
Badge looks like this: ![tests | inaccessible](https://img.shields.io/badge/tests-inaccessible-lightgrey)

"Azure DevOps builds" badge works perfekt.

Both happens in an Azure App Service (Container; shieldsio/shields:next) and on my local machine

Code i runned to create local Instance:

> mkdir c:\temp\shields\
> cd c:\temp\shields\
> git clone https://github.com/badges/shields.git
> cd shields
> npm ci 
> npm run build
> set AZURE_DEVOPS_TOKEN=5**************************************************q
> node server

Console Feedback:

> C:\Temp\shields\shields>node server
> Configuration:
> {
>   bind: { address: 'localhost' },
>   metrics: { prometheus: { enabled: false } },
>   ssl: { isSecure: false },
>   cors: { allowedOrigin: [ 'http://localhost:3000' ] },
>   persistence: { dir: './private' },
>   services: {
>     github: {
>       baseUri: 'https://api.github.com/',
>       debug: { enabled: false, intervalSeconds: 200 }
>     },
>     trace: false
>   },
>   profiling: { makeBadge: false },
>   cacheHeaders: { defaultCacheLengthSeconds: 120 },
>   rateLimit: false,
>   handleInternalErrors: false,
>   fetchLimit: '10MB'
> }
> 0917153715 FsTokenPersistence configured with C:\Temp\shields\shields\private\github-user-tokens.json
> 0917153715 Server is starting up: http://localhost/
> (node:816) UnhandledPromiseRejectionWarning: Error: Token pool is exhausted
>     at TokenPool._nextBatch (C:\Temp\shields\shields\core\token-pooling\token-pool.js:263:11)
>     at TokenPool.next (C:\Temp\shields\shields\core\token-pooling\token-pool.js:300:20)
>     at GithubApiProvider.tokenForUrl (C:\Temp\shields\shields\services\github\github-api-provider.js:155:33)
>     at GithubApiProvider.request (C:\Temp\shields\shields\services\github\github-api-provider.js:171:22)
>     at C:\Temp\shields\shields\services\github\github-api-provider.js:210:12
>     at new Promise (<anonymous>)
>     at GithubApiProvider.requestAsPromise (C:\Temp\shields\shields\services\github\github-api-provider.js:209:12)
>     at GithubForks._requestFetcher (C:\Temp\shields\shields\services\github\github-auth-service.js:13:23)
>     at GithubForks._request (C:\Temp\shields\shields\core\base-service\base.js:223:40)
>     at GithubForks._requestGraphql (C:\Temp\shields\shields\core\base-service\base-graphql.js:72:35)
> (node:816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:816) UnhandledPromiseRejectionWarning: Error: Token pool is exhausted
>     at TokenPool._nextBatch (C:\Temp\shields\shields\core\token-pooling\token-pool.js:263:11)
>     at TokenPool.next (C:\Temp\shields\shields\core\token-pooling\token-pool.js:300:20)
>     at GithubApiProvider.tokenForUrl (C:\Temp\shields\shields\services\github\github-api-provider.js:155:33)
>     at GithubApiProvider.request (C:\Temp\shields\shields\services\github\github-api-provider.js:171:22)
>     at C:\Temp\shields\shields\services\github\github-api-provider.js:210:12
>     at new Promise (<anonymous>)
>     at GithubApiProvider.requestAsPromise (C:\Temp\shields\shields\services\github\github-api-provider.js:209:12)
>     at GithubForks._requestFetcher (C:\Temp\shields\shields\services\github\github-auth-service.js:13:23)
>     at GithubForks._request (C:\Temp\shields\shields\core\base-service\base.js:223:40)
>     at GithubForks._requestGraphql (C:\Temp\shields\shields\core\base-service\base-graphql.js:72:35)
> (node:816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

:link: **Link to the badge**
My urls are looking like these (slightly modified for safety reasons):

- https://cblshields.azurewebsites.net/azure-devops/tests/cblcorp/Product_Skyfall/32
- http://localhost/azure-devops/tests/cblcorp/Product_Skyfall/32

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
hi @ChrisBlankDe, a few questions for you to verify my understanding of your context:

1) You have an Azure DevOps org, and you'd like badges (including the Test Results badge) from a pipeline that resides in a **private** Team Project in your Azure DevOps org
2) You are running self-hosted Shields instance, looks like you've tried it both locally as well as running self-hosted Shields in AppServices in Azure. 

Is that correct?

**Comment by ChrisBlankDe** [comment]
That's right.
sorry I forgot to mention that i want to use it for private repos.
And just to be sure: Its the Azure DevOps Cloud Service, not the onPrem version you can install in your own datacenter.

**Comment by calebcartwright** [comment]
Thanks! Can you also confirm that the PAT you are using is for a user that has a Basic license assigned, has access to the Team Project and target Pipelines, and has the minimum required scope permissions?

https://github.com/badges/shields/blob/master/doc/server-secrets.md#azure-devops

**Comment by ChrisBlankDe** [comment]
Jepp.
PAT has Full Access:
![image](https://user-images.githubusercontent.com/18051656/65063222-1bfa3580-d97e-11e9-9c9a-495ba649e4cf.png)
The associated user has the access level "VS Professional Subscription". should therefore be sufficient.

REST-Calls (via PowerShell) using this PAT against the devops API are successfully:
```powershell
$PAT = "5**************************************************q"
$Organization = "cblcorp"
$Project = "Product_Skyfall"
$BuildDefinition = 32
$branchName = "refs/heads/master"
$User = ""
$Base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $User, $PAT)))
$Headers = @{
    Authorization = ("Basic {0}" -f $Base64AuthInfo)
}
$Url = "https://dev.azure.com/{organization}/{project}/_apis/build/builds?definitions={definitions}&branchName={branchName}&top=1&maxBuildsPerDefinition=1&api-version=5.1".Replace("{organization}", $Organization).Replace("{project}", $Project).Replace("{definitions}", $BuildDefinition).Replace("{branchName}", $branchName)
$LastBuild=(Invoke-RestMethod -Uri $Url -Headers $Headers ).value
$Url = "https://dev.azure.com/{organization}/{project}/_apis/test/ResultSummaryByBuild?buildId={buildId}".Replace("{organization}", $Organization).Replace("{project}", $Project).Replace("{buildId}", $LastBuild.id)
$r = (Invoke-RestMethod -Uri $Url -Headers $Headers )
$r.aggregatedResultsAnalysis.totalTests #retuns: 49
$r.aggregatedResultsAnalysis.resultsByOutcome.Passed.count #retuns: 49
$r.aggregatedResultsAnalysis.resultsByOutcome.Failed.count #retuns: 0
```
i used the same Endpoints like these:
https://github.com/badges/shields/blob/ce0ddf93fc75e905743ac40db55c62a9bf44a53c/services/azure-devops/azure-devops-base.js#L40
https://github.com/badges/shields/blob/ce0ddf93fc75e905743ac40db55c62a9bf44a53c/services/azure-devops/azure-devops-tests.service.js#L210

**Comment by ChrisBlankDe** [comment]
Ok. I managed to get some trace information from the applikation (i am a node noop)
The failing request for the "Azure DevOps tests" badge:

```
 Service class
 AzureDevOpsTests
 Named params
 {
  organization: 'cblcorp',
  project: 'Product_Skyfall',
  definitionId: '32',
  branch: undefined
}
 Query params
 {
  color: undefined,
  colorA: undefined,
  colorB: undefined,
  compact_message: undefined,
  failed_label: undefined,
  label: undefined,
  labelColor: undefined,
  link: undefined,
  logo: undefined,
  logoColor: undefined,
  logoPosition: undefined,
  logoWidth: undefined,
  passed_label: undefined,
  skipped_label: undefined,
  style: undefined
}
 Query params after validation
{
  compact_message: undefined,
  failed_label: undefined,
  passed_label: undefined,
  skipped_label: undefined
}
 Query params after validation
 {
  color: undefined,
  colorA: undefined,
  colorB: undefined,
  compact_message: undefined,
  failed_label: undefined,
  label: undefined,
  labelColor: undefined,
  link: undefined,
  logo: undefined,
  logoColor: undefined,
  logoPosition: undefined,
  logoWidth: undefined,
  passed_label: undefined,
  skipped_label: undefined,
  style: undefined
}
 Request
 https://dev.azure.com/cblcorp/Product_Skyfall/_apis/build/builds
 Handled error
 Error: no auth mechanism defined
    at Auth.onRequest (c:\Temp\shields2\shields\node_modules\request\lib\auth.js:132:32)
    at Request.auth (c:\Temp\shields2\shields\node_modules\request\request.js:1347:14)
    at Request.init (c:\Temp\shields2\shields\node_modules\request\request.js:378:10)
    at new Request (c:\Temp\shields2\shields\node_modules\request\request.js:127:8)
    at request (c:\Temp\shields2\shields\node_modules\request\index.js:53:10)
    at cachingRequest (c:\Temp\shields2\shields\core\base-service\legacy-request-handler.js:211:17)
    at c:\Temp\shields2\shields\core\base-service\legacy-request-handler.js:60:7
    at new Promise (<anonymous>)
    at AzureDevOpsTests._requestFetcher (c:\Temp\shields2\shields\core\base-service\legacy-request-handler.js:59:5)
    at AzureDevOpsTests._request (c:\Temp\shields2\shields\core\base-service\base.js:223:40) {
  prettyMessage: 'inaccessible',
  response: undefined
}
 Service data
 { isError: true, message: 'inaccessible', color: 'lightgray' }

```

And the succeded call for the "Azure DevOps builds" badge:
```
 Service class
 AzureDevOpsBuild
 Named params
 {
  organization: 'cblcorp',
  projectId: '0e42062e-edc1-40c0-8352-************',
  definitionId: '32',
  branch: undefined
}
 Query params
 {
  color: undefined,
  colorA: undefined,
  colorB: undefined,
  label: undefined,
  labelColor: undefined,
  link: undefined,
  logo: undefined,
  logoColor: undefined,
  logoPosition: undefined,
  logoWidth: undefined,
  style: undefined
}
 Request
 https://dev.azure.com/cblcorp/0e42062e-edc1-40c0-8352-************/_apis/build/status/32
 Response status code
 200
 Response SVG
 <svg width="180.8" height="20.0" xmlns="http://www.w3.org/2000/svg">
  <linearGradient id="a" x2="0" y2="100%">
    <stop offset="0.0" stop-opacity="0.0" stop-color="#000" />
    <stop offset="1.0" stop-opacity="0.2" stop-color="#000" />
  </linearGradient>
  <clipPath id="c">
    <rect width="180.8" height="20.0" rx="3.0" />
  </clipPath>
  <g clip-path="url(#c)">
    <rect width="180.8" height="20.0" fill="#555555" />
    <rect width="68.9" height="20.0" fill="#4EC820" x="111.9" />
    <rect width="180.8" height="20.0" fill="url(#a)" />
  </g>
  <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" x="5" y="4">
    <g>
      <path fill-rule="evenodd" clip-rule="evenodd" d="M0 9H1V11H3L3 12H0V9Z" fill="#fff" />
      <path fill-rule="evenodd" clip-rule="evenodd" d="M0.666656 4H3.7352L6.20309 0.444336C6.38861 0.166992 6.70068 0 7.03479 0H11.5C11.7762 0 12 0.224609 12 0.5V4.96484C12 5.29883 11.8332 5.61133 11.5553 5.79688L8 8.26465V11.333C8 11.7012 7.70154 12 7.33334 12H5L4 11L5.25 9.75L4.25 8.75L2.99997 10L1.99997 9L3.25 7.75L2.25 6.75L1 8L0 7V4.66699C0 4.29883 0.298462 4 0.666656 4ZM10.5 3C10.5 3.82812 9.82843 4.5 9.00003 4.5C8.1716 4.5 7.50003 3.82812 7.50003 3C7.50003 2.17188 8.1716 1.5 9.00003 1.5C9.82843 1.5 10.5 2.17188 10.5 3Z" fill="#fff" />
    </g>
  </svg>
  <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="64.9" y="15.0" fill="#000" fill-opacity="0.3">Azure Pipelines</text>
    <text x="64.9" y="14.0" fill="#fff">Azure Pipelines</text>
    <text x="145.4" y="15.0" fill="#000" fill-opacity="0.3">succeeded</text>
    <text x="145.4" y="14.0" fill="#fff">succeeded</text>
  </g>
</svg>
 Response SVG (before validation)
{ message: 'succeeded' }
 Response after validation
{ message: 'succeeded' }
 Service data
 { label: undefined, message: 'passing', color: 'brightgreen' }

```

Does anybody what to do?
Is it a bug, missing documentation or am i just have to rtfm?

Thanks!

**Comment by calebcartwright** [comment]
Thanks so much this is helpful. Will get back to shortly

**Comment by calebcartwright** [comment]
@ChrisBlankDe - just wanted to let you know that I've been able to reproduce this/confirm it is a bug.
