### ISSUE TITLE
Skipped tests in Circle CI

### ISSUE THREAD

**Issue by chris48s** [badges/shields#4061]
When we run service tests in Circle CI (including the daily test run), we skip the tests for Twitch and Symfony Insight because we've got no tokens set up in the env vars. Is there any reason why we shouldn't add these?

**Comment by paulmelnikow** [comment]
Good idea. :+1: They get exposed to all CI jobs – and so we should basically consider them compromised – which just means we should use a separate set of credentials from anything else.

**Comment by PyvesB** [comment]
I had missed this issue. I took care of Twitch as part of #4781, that's all working fine on the CI now.

As far as Symfony is concerned, I remember having trouble last time I tried to obtain credentials and use the real API, see https://github.com/badges/shields/pull/3933#discussion_r319767086 . Will have another go at some point, but if someone is familiar with how Symfony works, please step in!

**Comment by PyvesB** [comment]
Symfony credentials were added to Circle CI. Kicked the daily tests, things seem to be working as expected! 🎉 

Nothing left to do, closing.
