### ISSUE TITLE
Coveralls badge not resolving

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [badges/shields#407]
For [ELLIOTTCABLE/Paws.js](/ELLIOTTCABLE/Paws.js), I'm unable to generate a Coveralls badge, despite there [being a project for it](https://coveralls.io/r/ELLIOTTCABLE/Paws.js):

https://img.shields.io/coveralls/ELLIOTTCABLE/Paws.js.svg → ![](https://img.shields.io/coveralls/ELLIOTTCABLE/Paws.js.svg)

**Comment by espadrine** [comment]
I can reproduce your issue. Coveralls are sending us inaccurate information. In fact, the copy-and-paste badge links they provide on their own website are inaccurate (see <https://coveralls.io/repos/ELLIOTTCABLE/Paws.js/badge.svg> → ![](https://coveralls.io/repos/ELLIOTTCABLE/Paws.js/badge.svg)). I'd love you to inform them of this issue; fixing it on their side will fix it on ours.

**Comment by espadrine** [comment]
On second look, it seems you use the branch `Master`, instead of `master`, which may trouble their system. Using this should work: <https://img.shields.io/coveralls/ELLIOTTCABLE/Paws.js/Master.svg> → ![](https://img.shields.io/coveralls/ELLIOTTCABLE/Paws.js/Master.svg)

**Comment by ELLIOTTCABLE** [comment]
Interesting; I'd think they'd use the HEAD branch. Thanks for the tip!
