### ISSUE TITLE
Frontend coverage

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4070]
When the frontend switched to TypeScript we lost code coverage. As I mentioned at https://github.com/badges/shields/pull/3722#discussion_r304641665 I don't think this is as big a deal for the frontend code.

However if someone is interested in working on this, there is a new answer posted at that may get things working.

https://github.com/piotrwitek/ts-mocha/issues/42#issuecomment-535521816

**Comment by PyvesB** [comment]
I feel like there's not much value in trying to get coverage for the frontend, especially since our migration to Docusaurus. Will go ahead and close this.
