### ISSUE TITLE
Make search work with category names

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#4100]
:clipboard: **Description**

I was reading through #4090 and wanted to see the state of our license badges. Instead of clicking on the category, I searched for the "license" keyword. Only three badges showed up out of eighteen in total.

In my opinion, we should include the category name as a search keyword for our badges. What do you think?

If we go forward with this, we should go through all our examples and make sure that none of them explicitly already use the category name in their keyword list.

**Comment by calebcartwright** [comment]
I've had a similar thought before too, definitely think it would be valuable. The other time I've found myself wanting to utilize a category was for running service tests (to be able to run all the service tests for a particular category)

**Comment by paulmelnikow** [comment]
I think this is a good idea. I wonder if it would be better to cherry-pick the categories and/or define the words this applies to, like version, license, etc.

It makes less sense to search for support to show everything in platform support, or code to see everything in code coverage.
