### ISSUE TITLE
Bugzilla badge broken

### ISSUE THREAD

**Issue by Jack-Works** [badges/shields#4102]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

<img src="https://img.shields.io/bugzilla/1536094?style=flat-square" />
https://img.shields.io/bugzilla/1536094?style=flat-square

**Comment by calebcartwright** [comment]
Looks like that API response for that bug has an emptry string for the `resolution` field which is being rejected

https://bugzilla.mozilla.org/rest/bug/1536094

For anyone interested in working on this one, I believe adding an `.allow('')` to the schema for the resolution field would resolve this

https://github.com/badges/shields/blob/362da5262ba0a46d59f37030891b84afcd80b0a5/services/bugzilla/bugzilla.service.js#L16

**Comment by Jack-Works** [comment]
Does it mean bugzilla is returned a invalid response or the scheme is maybe out of date?

**Comment by calebcartwright** [comment]
> Does it mean bugzilla is returned a invalid response or the scheme is maybe out of date?

No issues with the API, I just think we were expecting the API response to always include some value but that's clearly not always the case!

**Comment by seetd** [comment]
I would like to try fixing this as well

**Comment by calebcartwright** [comment]
Closed via #4106 4106
