### ISSUE TITLE
Make badges that rely on repository contents use default branch instead of "master"

### ISSUE THREAD

**Issue by h1nk** [badges/shields#4114]
:clipboard: **Description**

Continuation of the discussion started in PR #4096 (see [comment](https://github.com/badges/shields/pull/4096#issuecomment-537343737))

Essentially I asked whether it would be possible to automatically detect the default repository branch name for badges that rely on GitHub repository content and have the option to omit the branch name rather than simply defaulting to `master`.

**Comment by paulmelnikow** [comment]
Basically we'd need to switch these from fetching from githubusercontent.com, which does not require quota, to using the API.

Advantages:

- The implementation would get slightly simpler since it'd use the same code whether in prod/staging/self-hosting.

Disadvantages:

- We'd need to use GitHub API calls to fetch the contents, meaning it'd use our quota.

**Comment by h1nk** [comment]
Yes, I suppose the question is whether the API quota cost is worth it or not and also whether changing the default behavior of the branch-less option for the badges that have it is really necessary. I'm also going to assume that this will put an additional strain on badge load times vs. just simply using githubusercontent.com due to the added API query. Although some amount of caching could probably be used to reduce the added load time caused by having to check the default branch with the API on subsequent badge requests.

The only real reason I can see users wanting this is if they change the default branch name, which frankly doesn't happen very often I think.

Would love to hear some input from others if they think this would be a good or bad addition.

**Comment by h1nk** [comment]
It actually might be better to just do the branch name lookup via the API if githubusercontent.com returns a 404 for `master`, otherwise skip the unnecessary API query. I think this would be an excellent compromise and solve the problem of changed default branch names while minimizing unnecessary API requests.

**Comment by paulmelnikow** [comment]
It’d be better for quota, though in the 404 and non-master cases it’d double the number of requests and delay the response.

**Comment by chris48s** [comment]
One thing to bear in mind with the contents API is that it only allows files under 1Mb. For example, if I call https://raw.githubusercontent.com/jukbot/smart-industry/master/package-lock.json that gives me a file, but https://api.github.com/repos/jukbot/smart-industry/contents/package-lock.json throws an error. `package-lock.json` in particular can become quite large (ours is just under the 1Mb limit). You might say its not such a bad thing to refuse to parse a file over 1Mb, but it would probably be a break for some users.

> it’d double the number of requests and delay the response

Yeah I wouldn't like to introduce a second API call to every request of this type to cover this case :grimacing:

**Comment by h1nk** [comment]
Yeah I didn't consider that this would double the delay times, which would be really bad. I also wasn't aware of the 1MB limit with the v3 API for file content. Does the v4 API impose the same 1MB limit?

**Comment by chris48s** [comment]
Yeah good question. The v4 API truncates files, so you get something back but its unparseable if the data is in structured format like json. The [docs](https://developer.github.com/v4/object/blob/) don't explain what the limit is, but just doing a bit of ad-hoc testing, it seems that the V4 limit is lower than the V3 limit as opposed to higher.

The equivalent v4 API call for the above would be

```gql
{
  repository(owner: "jukbot", name: "smart-industry") {
    object(expression: "master:package-lock.json") {
      ... on Blob {
        text,
        isTruncated
      }
    }
  }
}
```

which returns

```json
{
  "data": {
    "repository": {
      "object": {
        "text": "load of text",
        "isTruncated": true
      }
    }
  }
}
```

**Comment by h1nk** [comment]
This is a really frustrating API limitation.

For this feature to work there would have to be a minimum of 2 requests:
1. Making an `/repos/:owner/:repo` API request (which could be executed concurrently with the current ` https://raw.githubusercontent.com/:owner/:repo/master/<file>` request)
2. Making a follow up `https://raw.githubusercontent.com/:owner/:repo/:branch/<file>` with the corrected `default_branch` name given by the API in the previous request.

So it's basically unavoidable to make 2 requests for repositories with a default branch that isn't `master` due to the file content truncation from the API. At least the request times fore current users wouldn't be impacted, but this kinda does suck.

**Comment by paulmelnikow** [comment]
Here's an idea:

1. When no branch is specified, default to the Contents API.
2. If the file is truncated, return an error like **for large files, branch must be specified**.
3. When the user specifies a branch, use the `raw.githubusercontent.com`. Specifying the branch explicitly is both (1) an optimization and (2) supports large files.
4. When self-hosting and a static GitHub token is configured or a GITHUB_API URL is set, always use the Contents API.

With this approach we do the helpful thing by default which is detecting the default branch. We force a little more user investment in what is probably an exception case, and we never make more than one request.

It's not the absolute worst thing to have to make two requests, though I don't see "needing to specify the branch in order to access large files" as a big limitation.

**Comment by calebcartwright** [comment]
That sounds reasonable to me. How involved would the implementation be for the 4th bullet? Does Shields have awareness of whether it is being self hosted?

**Comment by paulmelnikow** [comment]
> How involved would the implementation be for the 4th bullet? Does Shields have awareness of whether it is being self hosted?

Yea, basically something like the if statement that's in there now:

https://github.com/badges/shields/blob/b7235981c6769b81790783f6effa17b8acb04482/services/github/github-common-fetch.js#L34-L46

**Comment by calebcartwright** [comment]
Nice!

**Comment by h1nk** [comment]
This sounds very reasonable to me.

**Comment by chris48s** [comment]
It seems like there are essentially 2 edge cases we're trying to accommodate here.

* One is: "I need to extract info from a file larger than 1Mb"
* The other is: "my default branch is not called 'master'".

We have to make life slightly inconvenient for one of these groups of users by requiring them to specify the branch name (currently that is the "default branch is not master" group, but the proposed solution moves it to the "files larger than 1Mb" group). I guess it depends which of those groups of users we think is larger.. I don't think I have a handle on that :/

**Comment by paulmelnikow** [comment]
Fetching and parsing >1 MB to render a string is not really resource-ideal. I wouldn't advocate shutting it down, though I don't mind making it slightly inconvenient.

**Comment by Croydon** [comment]
I want to point out that this would be perfect for workflows which use versioned branches. At [Bincrafters](https://github.com/bincrafters) we do that for all Conan recipe repositories. The default branches therefore change regularly and having them hard-coded for a badge would be very painful

**Comment by paulmelnikow** [comment]
@Croydon Which badges are relevant to your versioned-branch use cases?

**Comment by Croydon** [comment]
Specifically the GitHub Commit Status badge. In total we are using 4 different CI platforms and which are active vary from repo to repo. I would like to get rid of individual CI specific badges and replace them with a single button. The GitHub Commit Status badge seems perfect for this

**Comment by paulmelnikow** [comment]
I think it would be best to open a new issue for that. Though it sounds similar to the issue described here, the concerns are different. This issue is about whether to use githubusercontent.com as a shortcut for the [Contents API](https://developer.github.com/v3/repos/contents/).

**Comment by chris48s** [comment]
https://github.com/badges/shields/pull/5234 resolves this for both cases :)
