### ISSUE TITLE
"Use this template" badge for GitHub repo

### ISSUE THREAD

**Issue by kerolloz** [badges/shields#4118]
:clipboard: **Description**
this badge is for GitHub
this badge should show: "repo-name | Use this template"

:link: **Data**

- repository name
- link to generate repo `https://github.com/<USER NAME>/<REPO NAME>/generate`

:microphone: **Motivation**

This badge would be cool if you are making a website for your template, so anyone could click on the badge to use this template without the need to go to the repository first. 
This badge would also be helpful to be in the README so the user does not have to scroll to the top press the `Use this template` button.

**Comment by chris48s** [comment]
Hello. This is already do-able :)

<a href="https://github.com/badges/shields/generate">
  <img src="https://img.shields.io/badge/use%20this-template-blue?logo=github">
</a>

```
<a href="https://github.com/badges/shields/generate">
  <img src="https://img.shields.io/badge/use%20this-template-blue?logo=github">
</a>
```

**Comment by kerolloz** [comment]
@chris48s 
Okay, Thank you :smiley:!

**Comment by paulmelnikow** [comment]
(Tagging as possibly related to #2824, which is a bit better designed for actions like "fork me." Though there also might be a more status-y way to say this!)
