### ISSUE TITLE
Server down & bugs?

### ISSUE THREAD

**Issue by tvvocold** [badges/shields#412]
i.e.
https://img.shields.io/travis/joyent/node.svg
```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by espadrine** [comment]
Indeed, it was down. Will investigate when I can.

**Comment by tvvocold** [comment]
Update:
Back to normal again.

**Comment by tvvocold** [comment]
BTW, i think there might be some bug in the code.
(There is no open issue in this [repo](https://github.com/spance/deblocus) but shields show there's [one](https://img.shields.io/github/issues/spance/deblocus.svg).)

**Comment by kyrias** [comment]
@tvvocold PR’s count for the issue count in the GitHub API.

**Comment by tvvocold** [comment]
OK...

**Comment by kyrias** [comment]
(To be more specific, pull requests are always attached to an issue, just not a separate one.)

**Comment by espadrine** [comment]
`open_issues_count` in <https://api.github.com/repos/spance/deblocus> shows up as 1.
