### ISSUE TITLE
"Dependencies none" is grey for David but green for Gemnasium?

### ISSUE THREAD

**Issue by bmpvieira** [badges/shields#413]
[Gemnasium example](http://shields.io/#miscellaneous)
[David example](http://github.com/bionode/bionode-fastq)

I think it should also be green (no dep is usually a good thing) for David.

**Comment by kyrias** [comment]
It seems that the issue is that the if/else tree doesn’t check for `none` at all, so it will just be the default. It’s a 2-line change to add it though, so nothing big.
