### ISSUE TITLE
AUR badge shows "invalid response data"

### ISSUE THREAD

**Issue by hashworks** [badges/shields#4142]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The AUR Badge of [dns-zone-blacklist-git](https://aur.archlinux.org/packages/dns-zone-blacklist-git/) shows "invalid response data" instead of the version.

:link: **Link to the badge**

![aur badge](https://img.shields.io/aur/version/dns-zone-blacklist-git)

**Comment by calebcartwright** [comment]
Hi @hashworks, thanks for letting us know. I'm taking a look at the schema now, json response from the API below for reference

```json
{ 
  "version":1,
  "type":"info",
  "resultcount":1,
  "results":{ 
    "ID":652911,
    "Name":"dns-zone-blacklist-git",
    "PackageBaseID":145571,
    "PackageBase":"dns-zone-blacklist-git",
    "Version":"r337.01caed5-1",
    "Description":"dnsmasq, bind and unbound zone files to be used in DNS based AD Blockers",
    "URL":"https:\/\/github.com\/oznu\/dns-zone-blacklist",
    "NumVotes":0,
    "OutOfDate":null,
    "Maintainer":"hashworks",
    "FirstSubmitted":1570281672,
    "LastModified":1570281856,
    "License":null,
    "URLPath":"\/cgit\/aur.git\/snapshot\/dns-zone-blacklist-git.tar.gz",
    "CategoryID":1
  }
}
```

**Comment by calebcartwright** [comment]
Okay I see the problem. Our schema was expecting a non-null value for the `License` field
