### ISSUE TITLE
Fork Badge not updating

### ISSUE THREAD

**Issue by harshraj22** [badges/shields#4149]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
The [fork](https://camo.githubusercontent.com/b6d68969f28da6caf9f6b3560e0b59645a82fbdc/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f666f726b732f736168696c62616e73616c31372f436f6d70657469746976655f436f64696e672e737667) badge at Sahil Bansal's [repo](https://github.com/sahilbansal17/Competitive_Coding) (https://github.com/sahilbansal17/Competitive_Coding) is not being updated. An [issue](https://github.com/sahilbansal17/Competitive_Coding/issues/498) regarding the same on his repo.

:link: **Link to the badge**
![Forks](https://img.shields.io/github/forks/sahilbansal17/Competitive_Coding.svg)
[link](https://img.shields.io/github/forks/sahilbansal17/Competitive_Coding.svg)

:bulb: **Possible Solution**
NA

**Comment by calebcartwright** [comment]
I'm not entirely sure what is meant by "badge not updating", although there is indeed a descrepancy between the count of forks shown on the badge, and what GitHub is showing in the UI. Is that what you are referring to?

We switched to GitHub's V4 API for the forks badges not too long ago so I'm wondering that may explain the difference

**Comment by harshraj22** [comment]
@calebcartwright Yeah, that's what I ment. :sweat_smile: 
So what should be done from repo maintainer/owners' side to make the count of forks shown on the badge same as that shown in the Github UI ?

**Comment by calebcartwright** [comment]
There's nothing you need to do as a Shields user.

We'll have to dig into the underlying issue. We're only showing the information we get from GitHub's API, so if the API is returning incorrect data then that's an upstream problem

**Comment by calebcartwright** [comment]
So the GitHub API is, unsurprisingly, returning 184 as the count for the GraphQL query:

```graphql
query {
  repository(owner: "sahilbansal17", name:"Competitive_Coding") {
    forks {
      totalCount
    }
  }
}
```

https://developer.github.com/v4/explorer/

**Comment by chris48s** [comment]
This is an interesting one..

```gql
{
  repository(owner: "sahilbansal17", name: "Competitive_Coding") {
    forks {
      totalCount
    }
  }
}
```

on the V4 API returns

```json
{
  "data": {
    "repository": {
      "forks": {
        "totalCount": 184
      }
    }
  }
}
```

whereas https://api.github.com/repos/sahilbansal17/Competitive_Coding (V3 API) returns

```json
{
  "forks": 198,
}
```

If you have a look at https://github.com/sahilbansal17/Competitive_Coding/network/members you can see that there are 13 repos listed which are forks of someone else's fork, or forks of forks of forks (second and third order forks). I guess the graphql query we're using is including _only first order forks_ . Doing a bit of searching, if we change the query to

```gql
{
  repository(owner: "sahilbansal17", name: "Competitive_Coding") {
    forkCount
  }
}
```

that will return


```json
{
  "data": {
    "repository": {
      "forkCount": 198
    }
  }
}
```

which is the same number used in the GH front-end and V3 API call. I'll do a PR for it in a sec..

**Comment by calebcartwright** [comment]
Good spot Chris!
