### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by nazar-pc** [badges/shields#415]
Would be nice to have [Docker](https://www.docker.com/) support: downloads count and stars, very often Docker images are automated builds based on GitHub repo.

**Comment by montanaflynn** [comment]
I found the docker hub API for stars but no luck with the downloads count which I'm more interested in. 

There's a bit of a quirk where official repos omit `/u/` and replace the owner with an underscore in their public docker hub URLs, so you must replace the underscore with `library` in the API path for it to work:

Official URL:  https://registry.hub.docker.com/_/redis/
User URL: https://registry.hub.docker.com/u/mashape/docker-kong/

Official stars API: https://registry.hub.docker.com/v2/repositories/library/redis/stars/count/
User stars API: https://registry.hub.docker.com/v2/repositories/mashape/docker-kong/stars/count/

**Comment by nazar-pc** [comment]
Where did you found that? There is only 1.5 version of API documentation on their website.

**Comment by montanaflynn** [comment]
@nazar-pc it's what the website uses internally. Do you have any feedback on how the badge should be formatted, regarding text and color? Here it is in docker blue with just the count + text, this leaves it open for having downloads (or pulls as the website sometimes refers to them as) when we find a data source.

![Docker Stars](https://img.shields.io/badge/docker-3432%20stars-008bb8.svg)

**Comment by nazar-pc** [comment]
Docker uses blue colors, so, I think it looks great.
Reported in docker repo question about downloads/pulls count: https://github.com/docker/docker/issues/12268

**Comment by montanaflynn** [comment]
Thanks, please ping me if you hear back. I filed a [pull request](https://github.com/badges/shields/issues/417) for the stars integration.

**Comment by nazar-pc** [comment]
Here is answer from Docker support team:
> Unfortunately we don't have that feature. Although, I agree it would be very nice to have it in general to show download counts along with stars.

> I'll pass along this feature request to the dev team.

**Comment by montanaflynn** [comment]
Looks like they shut off access to the stars API so the integration no longer works. Hopefully they build a public API for stars, downloads and other meta information around the docker hub in the near future.

**Comment by montanaflynn** [comment]
It's back online so I [built an API](https://gist.github.com/montanaflynn/957add5908beb3f676cf) that returns the total downloads and stars for repos. Hopefully I'll be able to get them both integrated into the PR tonight!

**Comment by nazar-pc** [comment]
@espadrine, any thoughts when merged PR will be live?
Or is it already available, but not mentioned on shields.io?

**Comment by espadrine** [comment]
@nazar-pc indeed, the website was not updated.

**Comment by espadrine** [comment]
Should we close this issue, then?

**Comment by mavam** [comment]
Do you have any plans to add support for the Docker image status, i.e., whether the last built was successful?

**Comment by pavel-paulau** [comment]
Does it make sense to add image size as well?

```
$ curl -s https://registry.hub.docker.com/v2/repositories/library/ubuntu/tags/latest/ | python -mjson.tool
{
    "creator": 7,
    "full_size": 48649684,
    "id": 2343,
    "image_id": null,
    "last_updated": "2016-06-03T16:19:34.176107Z",
    "last_updater": 621950,
    "name": "latest",
    "platforms": [
        1
    ],
    "repository": 130,
    "v2": true
}

```

**Comment by felixfbecker** [comment]
Is there a badge that shows the lastest version like we have for npm?
