### ISSUE TITLE
Inconsistent style for documentation lists

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#4170]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Discovered in #4168, quite a minor issue, but still worth reporting. When a badge's documentation contains a list of items, its display is quite different depending on the browser (observed on Windows 10):
* in Firefox the dots nicely start at the beginning of the text:
![firefox](https://user-images.githubusercontent.com/10694593/66705309-b0a54880-ed1c-11e9-9702-18497010896f.png)
* in a Chromium-based browser, the dots are left-aligned:
![opera](https://user-images.githubusercontent.com/10694593/66705323-e1857d80-ed1c-11e9-90bd-a4803e39f859.png)
* in Edge, left-aligned as well, but barely visible:
![edge](https://user-images.githubusercontent.com/10694593/66705335-0843b400-ed1d-11e9-8530-332bc847dc7c.png)

Can we make things more consistent?

:bulb: **Possible Solution**

Probably something involving HTML tags or attributes.

**Comment by paulmelnikow** [comment]
Thanks for opening this @PyvesB!

As part of fixing this, I'm thinking we probably should stop centering the text.

In terms of steps to move forward, probably best to post a screenshot as a design proposal and then get a :+1: before opening a PR.

**Comment by PyvesB** [comment]
Here are my attempts to align the documentation contents to the left.

- Firefox:
  ![left-firefox](https://user-images.githubusercontent.com/10694593/67634450-f08b3480-f8b3-11e9-8f21-7d890878d409.png)

- Chromium-based browser:
  ![left-chromium](https://user-images.githubusercontent.com/10694593/67634454-faad3300-f8b3-11e9-90ad-fd4874e27fc9.png)

Similar screenshots with the current centre alignment.

- Firefox:
  ![centre-firefox](https://user-images.githubusercontent.com/10694593/67634502-d867e500-f8b4-11e9-9f91-b93ff3bbdb5b.png)

- Chromium-based browser:
  ![centre-chromium](https://user-images.githubusercontent.com/10694593/67634506-de5dc600-f8b4-11e9-9052-9a53865de352.png)

**Comment by paulmelnikow** [comment]
The left alignment looks great!
