### ISSUE TITLE
Version issues with pub package firebase_core

### ISSUE THREAD

**Issue by eldracode** [badges/shields#4172]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The pub package **firebase_core**  shows version as v0.4.0+1 but on [pub.dev](https://pub.dev/packages/firebase_core) it's v0.4.0+9

![pub package](https://img.shields.io/pub/v/firebase_core)

:link: **Link to the badge**

https://img.shields.io/pub/v/firebase_core

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
The API response includes all versions, so this is probably just a bug in how we're selecting the "latest" version from the set of published versions

**Comment by calebcartwright** [comment]
Yeah I see the problem, and a potential fix.
