### ISSUE TITLE
What is the ETA for picking up changes from simpleicons.org ?

### ISSUE THREAD

**Issue by maxandersen** [badges/shields#4175]
:question: **Question**

Logo for Quarkus was added to simpleicons.org but https://img.shields.io/badge/style-flat-green?logo=quarkus&style=flat renders with empty logo.

I assume its due to some caching; and thus just wondering how long it takes before simpleicon releases are picked up ?

**Comment by calebcartwright** [comment]
hi @maxandersen. Shields provides the Simple Icons logo by leveraging the [simple-icons](https://www.npmjs.com/package/simple-icons) npm module. We're currently using v1.16.0 of the simple-icons module:

https://github.com/badges/shields/blob/b8d0ec42381540db7eeec48e5118fc0dd566978c/package.json#L62

Dependabot runs every Friday for us with PRs that bump the versions of our dependencies, so we'd most likely update to the latest version of simple-icons this Friday and that would be deployed to the production Shields.io servers at some point afterwards (most likely within a few days though there is no fixed schedule)

So under normal circumstances I'd guess the ETA would be somewhere in the 7-10 days range, roughly. If this is something you'd like to see sooner, feel free to open a PR that bumps the simple-icons dependency to a version that contains the Quarkus and it may very well get deployed to Shields.io sooner

**Comment by maxandersen** [comment]
Thank you for that great and detailed answer which will help others in future too!

I was okey for the 7-10 days wait, but since you offered it I opened https://github.com/badges/shields/pull/4179 :)

**Comment by calebcartwright** [comment]
Closed via #4179
