### ISSUE TITLE
Move remaining hostnames from route params to query params

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4178]
A follow up to #3714 with the last services that still have url/server/host parameters specified as route params instead of query params:

* [ ] [Jenkins (build, coverage, and tests)](https://github.com/badges/shields/tree/master/services/jenkins)
* [ ] ~~[Mozilla Observatory](https://github.com/badges/shields/blob/master/services/mozilla-observatory/mozilla-observatory.service.js#L61)~~
* [x] [Swagger](https://github.com/badges/shields/blob/master/services/swagger/swagger.service.js)

I _think_ that's all of them but if anyone sees any others please update this list/leave a comment

**Comment by paulmelnikow** [comment]
Thanks for opening this.

For what it’s worth I don’t mind it on the Observatory badge as it’s just a hostname, and thus fits nicely into the URL. Though if you prefer to make them all query params I could get behind that.

**Comment by calebcartwright** [comment]
> For what it’s worth I don’t mind it on the Observatory badge as it’s just a hostname, and thus fits nicely into the URL.

Ah okay, I didn't actually look that closely 😄 

> Though if you prefer to make them all query params I could get behind that.

WFM

**Comment by PyvesB** [comment]
Will pick up the Jenkins badges.
