### ISSUE TITLE
GitHub tag issue

### ISSUE THREAD

**Issue by XhmikosR** [badges/shields#418]
When trying to use shields.io with a project of mine I'm getting different results to what I'm getting with badge.fury.io.

```md
[![GitHub version](https://badge.fury.io/gh/mpc-hc%2Fmpc-hc.svg)](http://badge.fury.io/gh/mpc-hc%2Fmpc-hc)
[![GitHub Tag](https://img.shields.io/github/tag/mpc-hc/mpc-hc.svg)](https://github.com/mpc-hc/mpc-hc)
```

[![GitHub version](https://badge.fury.io/gh/mpc-hc%2Fmpc-hc.svg)](http://badge.fury.io/gh/mpc-hc%2Fmpc-hc) [![GitHub Tag](https://img.shields.io/github/tag/mpc-hc/mpc-hc.svg)](https://github.com/mpc-hc/mpc-hc)

The **latest** (sorted by date) tag is indeed 1.7.8, but sorting seems different for shields.io. Is there any way to fix this?

Thanks!

**Comment by kyrias** [comment]
The issue is that the shields.io function just uses the output of `https://api.github.com/repos/mpc-hc/mpc-hc/tags` which shouldn’t be done since it just returns the tags in lexicographical order.

**Comment by kyrias** [comment]
The only way to fix it is either

1) remove the old tags, or
2) Make proper GitHub releases and use the `/releases/latest` part of the api.

**Comment by kyrias** [comment]
Though, I’ll try asking the badge.fury.io people who they do it, and ask GitHub to add an API to get the tags sorted by time, but that might not happen..

**Comment by XhmikosR** [comment]
Those tags are from our SVN era :p After we moved to GitHub, we make proper tags.

Would be nice if you could fix this since I can't be the only one with this issue :)

**Comment by kyrias** [comment]
There isn’t really any easy way to fix it:

1) GitHub replied that they probably won’t anything like a sorted API for the tags.

2) Forcing the use of semver on shields’ side wouldn’t be appropriate since a *lot* of projects do not use it.

3) Which only really leaves you deleting the old tags from the repo, unfortunately.

Technically I guess we could make a separate endpoint, like `github/tag-semver/` or something that forces semver parsing, though I’m not sure what @espadrine would think of that.

**Comment by XhmikosR** [comment]
3) I can't do that unfortunately.

Your last suggestion sounds the best. Would be nice to have this if it's
not much trouble.

**Comment by kyrias** [comment]
That’s a shame. I can try implementing it later, if @espadrine would merge it.

**Comment by kyrias** [comment]
I have a basic node implementation that is working now, though it will require adding the semver module as a dependency.

**Comment by kyrias** [comment]
@espadrine I’ve made a WIP implementation of a separate semver parsing GitHub tag shield at kyrias/shields@a7e813f35 and I’d like your opinions on

1) On adding the `semver` dependency, and
2) Somehow adding a note to the homepage about the semver version forcing a semver parse instead of the lexicographically highest tag.

**Comment by XhmikosR** [comment]
In your branch semver is already included as a dependency; it's just an
older version.

**Comment by kyrias** [comment]
Heh, I completely missed that.

**Comment by kyrias** [comment]
See kyrias/shields@830970ff5c for the version without duplicate content. Second question still stands though. We need to be able to make the difference easy to see.

**Comment by espadrine** [comment]
I think adding a new API endpoint is overkill. I'll assume that people want the latest semver, defaulting to ascii ordering if it fails.

```diff
diff --git a/server.js b/server.js
index 330cd60..acdb4d8 100644
--- a/server.js
+++ b/server.js
@@ -1950,7 +1950,8 @@ cache(function(data, match, sendBadge, request) {
         return;  // Hope for the best in the cache.
       }
       var data = JSON.parse(buffer);
-      var tag = data[0].name;
+      var versions = data.map(function(e) { return e.name; });
+      var tag = latestVersion(versions);
       var vdata = versionColor(tag);
       badgeData.text[1] = vdata.version;
       badgeData.colorscheme = vdata.color;
```

**Comment by XhmikosR** [comment]
Thanks for this. Has this been deployed yet? I still see `release_v1_6_3` as the last tag.

**Comment by espadrine** [comment]
… and it's live.

**Comment by XhmikosR** [comment]
Awesome, thanks!
