### ISSUE TITLE
Wheelmap badges returning invalid token

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4181]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Wheelmap badges are not working

:link: **Link to the badge**
https://img.shields.io/wheelmap/a/26699541
![](https://img.shields.io/wheelmap/a/26699541)

:bulb: **Possible Solution**
Not sure. Perhaps the token has expired, or perhaps something has changed with the upstream API (Similar symptom reported a while ago in https://github.com/badges/shields/issues/2469)

**Comment by paulmelnikow** [comment]
The service tests are passing locally using my personal wheelmap token and failing using the production token. Do you want to troubleshoot it? I can share the credentials with you.

**Comment by calebcartwright** [comment]
Sure. I've no experience/familiarity with Wheelmap but i'll take a look

**Comment by PyvesB** [comment]
The badges work fine on the staging environment as well: ![](https://shields-staging.herokuapp.com/wheelmap/a/26699541). My credentials are used there.

The fix will probably be "renew the token", but it would be useful to see if any useful information comes back when doing an API request. I'm also happy to pick this one up.

**Comment by paulmelnikow** [comment]
@PyvesB I just shared it with you on Keybase!

@calebcartwright are you on Keybase? Could you add me, and probably also prove your GitHub identity?

https://keybase.io/paulmelnikow

**Comment by PyvesB** [comment]
The API response is not very helpful:
`{"error":"invalid API key."}`

However, I noticed there was a typo in the API key you shared on Keybase @paulmelnikow when comparing it to what is displayed on the Wheelmap.org profile. I've reuploaded the fixed version to Keybase.

**Comment by calebcartwright** [comment]
> @calebcartwright are you on Keybase

I am not though I'll try to set up an account soon

**Comment by calebcartwright** [comment]
@PyvesB - badges seem to working again, well done!

**Comment by paulmelnikow** [comment]
Nice! Yea, I've just deployed the config change.

**Comment by PyvesB** [comment]
Brilliant, nice teamwork! Let's close the issue! 👍 

By the way, you can also find me on Keybase: https://keybase.io/pyves
