### ISSUE TITLE
Badge Request - Crates.io Recent Downloads

### ISSUE THREAD

**Issue by 17cupsofcoffee** [badges/shields#4186]
:clipboard: **Description**

It would be helpful if Shields.io exposed a badge for recent downloads of a crate on Crates.io, as well as the existing total downloads badge.

The display would look something like:

![](https://img.shields.io/badge/recent%20downloads-100-success)

I'd like to pick this up as a PR later today/over the weekend, but I thought it'd be a good idea to raise an issue for feedback first.

:link: **Data**

The data is retrievable from the same API endpoint that the current 'downloads' badge uses, via the `recent_downloads` field.

It currently can only be accessed for the crate as a whole, not on a per-version basis - therefore the `:version` URL parameter would need to be either disallowed or ignored for this variant of the downloads badge.

:microphone: **Motivation**

Recent downloads are a better metric of the *current* popularity of a library than total downloads.

The concrete usecase for this is for an ecosystem guide that the Rust Game Development Working Group are working on - we'd like to display the recent downloads of various crates in a wiki page.

**Comment by calebcartwright** [comment]
Great idea! Most for our Download count badges to support intervals (based on what the upstream API makes available) to allow users to choose, so giving users the flexibility to choose total or recent for Crates would be a welcome addition.

> I'd like to pick this up as a PR later today/over the weekend, but I thought it'd be a good idea to raise an issue for feedback first.

❤️ 

It should be relatively straightforward to implement this

The schemas are defined in the [Crates base class](https://github.com/badges/shields/blob/master/services/crates/crates-base.js) and would need to be tweaked to include whatever field in the API response contains the recent download count.

Then the [Crates download service](https://github.com/badges/shields/blob/master/services/crates/crates-downloads.service.js) would need to be updated to support the `interval` param and to extract the correct value from the response based on the interval

It may also be worth moving that extraction logic into a new `transform` function
https://github.com/badges/shields/blob/7b3073149c1854e678e0ed8e95893648f582d83c/services/crates/crates-downloads.service.js#L74-L81

Feel free to ping us on this thread and/or Discord with any questions, open up a Draft PR to get early feedback, etc.

**Comment by 17cupsofcoffee** [comment]
Thank you for the guidance :)
