### ISSUE TITLE
Wrong npm version shown

### ISSUE THREAD

**Issue by binarykitchen** [badges/shields#419]
If you look at https://github.com/binarykitchen/videomail-client you see the blue npm badge saying it's version v3.5.0 but that's wrong. The videomail-client version is 1.0.79.

Any ideas why the shield is parsing that version the wrong way?

**Comment by espadrine** [comment]
Is [this](https://github.com/binarykitchen/videomail-client/pull/1) correct, or is the project related to https://www.npmjs.com/package/standard?

**Comment by binarykitchen** [comment]
ah, had a wrong name - fixed, thanks man
