### ISSUE TITLE
Should GitHub issue badge including pull requests?

### ISSUE THREAD

**Issue by PeterDaveHello** [badges/shields#420]
As you can see on the right side, GitHub put them in different pages and count individually, 
though we also get this info from GitHub api, but I wonder if this is a good flavor? Because it has different meaning with the count on GitHub project page.

Guys if you think they should be different, I can send a PR to adjust it, thanks!

**Comment by espadrine** [comment]
Does the GitHub API discriminate issues from pull requests somewhere? I don't see a field for that here: <https://api.github.com/repos/badges/shields>.

**Comment by PeterDaveHello** [comment]
https://api.github.com/search/issues?q=repo:cdnjs/cdnjs+is:issue+is:open

**Comment by espadrine** [comment]
That's great!

I too feel that the github issues thing is clunky. Let's make it a lot better.

I'd see something like `/github/issues/user/repo.svg` do the basic thing which already works (counting both open issues and pull requests), and `/github/issues-raw/user/repo.svg` do the same, without including "open" on the right-hand-side.

Then, we could also have `/github/issues-pr/user/repo.svg` for pull requests only, `/github/issues-issue-closed/user/repo.svg` for closed issues only, etc. We'd have dash-separated parameters, all calling the same GitHub API endpoint, and giving people the ability to pick exactly the badge they want. Raw, as before, would ensure that the right-hand-side of the badge only holds a number.

Could you do that in <https://github.com/badges/shields/pull/423>? It would be amazing.

**Comment by PeterDaveHello** [comment]
Sure.

**Comment by PeterDaveHello** [comment]
@espadrine All done.

**Comment by paulmelnikow** [comment]
Believe this was resolved in #1020.
