### ISSUE TITLE
Security issue on dependency

### ISSUE THREAD

**Issue by PeterDaveHello** [badges/shields#421]
There is a security issue, should better upgrade semver to version >= 4.3.2

https://github.com/badges/shields/blob/master/package.json#L27
> "semver": "~2.3.0",

https://nodesecurity.io/advisories/semver_redos
> Vulnerable: <4.3.2  Patched: >=4.3.2

**Comment by PeterDaveHello** [comment]
I found that most dependencies is a little bit old, let me send a PR to upgrade them.

**Comment by espadrine** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
np
