### ISSUE TITLE
Yesterday's server resource incident

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4227]
In https://github.com/badges/shields/issues/4223#issuecomment-545127052 @platan wrote:

> There is something strange happening with our servers in the last hours:
> https://metrics.shields.io/d/aESRBSjmz/services?orgId=1&from=now-3h&to=now
> https://metrics.shields.io/d/g_1B7zhik/prom-client-default-metrics?orgId=1&refresh=10s&from=now-3h&to=now

See also some discussion in the #ops channel.

I rolled back to 8a21c7746fc131bd8f2c621c331bc357c61e3b69 and so far things have been stable. It's not 100% clear if the rollback fixed the problem, or if one of these commits leading up to 54bcedc0f42a211e8b802001e28af27da024a621 caused it. We should try to re-deploy those commits and/or determine which one is causing the resource leak.

I'm a little busy in the next couple days. Wishing someone could help with this!

**Comment by paulmelnikow** [comment]
I'm curious, has anyone been tracking whether the problem has gone away since the rollback. The badges in the Shields repo seems okay, though there have been some more reports in #4223.

**Comment by calebcartwright** [comment]
I was keeping tabs on the stats yesterday and didn't notice anything in particular. Haven't been able to do much today though
