### ISSUE TITLE
Add support for Gitter.

### ISSUE THREAD

**Issue by bardiharborow** [badges/shields#426]
Current Gitter badge looks like this: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
Discussions are underway [here](https://github.com/gitterHQ/gitter/issues/636) about switching to shields.io.

This is how a you can make a shields.io badge for Gitter currently: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-join%20chat-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-join%20chat-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```
I thought it would be much better to have a badge which looks like this: [![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-4%20users%20online-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

```
[![Join the chat at https://gitter.im/sahat/hackathon-starter](https://img.shields.io/badge/GITTER-4%20users%20online-green.svg)](https://gitter.im/sahat/hackathon-starter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```

I will try to put together some API examples when I get a chance.

**Comment by espadrine** [comment]
Thanks for the suggestion!

The original issue is here: https://github.com/badges/shields/issues/354.
