### ISSUE TITLE
Letter spacing is incorrect on social badges

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4275]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [x] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The social badges display with incorrect letter spacing. 

:link: **Link to the badge**

https://img.shields.io/github/stars/badges/shields?style=social

![](https://img.shields.io/github/stars/badges/shields?style=social)

By removing the `textWidth` you can see what the letter spacing would be if the width were correct:

Correct:

<img width="102" alt="Screen Shot 2019-10-31 at 6 21 00 PM" src="https://user-images.githubusercontent.com/1487036/67990125-5147a380-fc0b-11e9-92ce-50216b07678d.png">

Incorrect:

<img width="102" alt="Screen Shot 2019-10-31 at 6 21 18 PM" src="https://user-images.githubusercontent.com/1487036/67990134-586eb180-fc0b-11e9-9599-65d9cdccdd23.png">

:bulb: **Possible Solution**

- Measure the text using the font used for display (I suppose Helvetica or Helvetica Neue)
- Measure the text in the correct weight (700)
- Make sure nothing else is getting in the way 🤓

**Comment by paulmelnikow** [comment]
Probably we should open an issue in https://github.com/metabolize/anafanafo and start the process over there, once we decide which font to use.

**Comment by calebcartwright** [comment]
I feel like this must be an early/late April fool's joke because they look identical to my eyes 😆

**Comment by paulmelnikow** [comment]
I think this is the letter spacing joke of the season: https://hellveticafont.com/ 😈 

The **9.4k** is the same (else really subtle) but I think it's more visible in **Stars**. Here's the correct one zoomed in:

<img width="478" alt="Screen Shot 2019-10-31 at 6 35 17 PM" src="https://user-images.githubusercontent.com/1487036/67990820-67566380-fc0d-11e9-8838-3869b2c2cc01.png">

Incorrect (production):

<img width="478" alt="Screen Shot 2019-10-31 at 6 34 46 PM" src="https://user-images.githubusercontent.com/1487036/67990816-645b7300-fc0d-11e9-8763-aac6e28945c6.png">

Is your display a 1x or 2x? I wonder if the problem is easier to see on Retina.

**Comment by calebcartwright** [comment]
> I think this is the letter spacing joke of the season: https://hellveticafont.com/ 😈

That gave me a good chuckle

> but I think it's more visible in Stars

Excellent that's where I thought I saw a slight difference. I feel like I found Waldo! 

> Is your display a 1x or 2x? I wonder if the problem is easier to see on Retina.

2x I believe. I don't have a great eye for this visual stuff anyway

**Comment by FTOH** [comment]
Another example
![image](https://user-images.githubusercontent.com/5018813/80342446-b9daaa80-8853-11ea-9ec3-7068f8e3ae1f.png)
![image](https://user-images.githubusercontent.com/5018813/80342457-be06c800-8853-11ea-9467-70f6b9e2df66.png)
[Source](https://github.com/pastelsky/bundlephobia#badges)

**Comment by paulmelnikow** [comment]
Hey @FTOH that is a different issue you're seeing, see #4813.
