### ISSUE TITLE
Code Climate doesn't work when there's a '.' character in the repo name

### ISSUE THREAD

**Issue by hughrawlinson** [badges/shields#428]
Shields.io: ![Code Climate](https://img.shields.io/codeclimate/hughrawlinson/wat%2Ejs/flow.svg?style=flat-square)

Code Climate: ![Code Climate](https://codeclimate.com/github/hughrawlinson/wat.js/badges/gpa.svg)

**Comment by espadrine** [comment]
I believe you are looking for `http://img.shields.io/codeclimate/github/hughrawlinson/wat.js.svg`: ![](http://img.shields.io/codeclimate/github/hughrawlinson/wat.js.svg).

If this is what you are looking for, please close this issue.

**Comment by hughrawlinson** [comment]
Thanks
