### ISSUE TITLE
support npm scopes

### ISSUE THREAD

**Issue by deepsweet** [badges/shields#429]
http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages

> Scopes are like namespaces for npm packages. Each npm user has their own scope.
>
> @username/project-name
>
> This means that you don’t have to worry about someone else taking your package name. Only you can add packages in your scope.

for example – https://www.npmjs.com/package/@yummies/inherit-loader – it should be possible to specify scope name at least for npm-version badge:

```
https://img.shields.io/npm/v/@yummies/inherit-loader.svg
```

**Comment by kgryte** [comment]
+1

**Comment by chmontgomery** [comment]
:+1:

**Comment by shinnn** [comment]
:+1:

**Comment by espadrine** [comment]
Thanks for the suggestion!

I wonder how it ties into their existing API.

**Comment by wilmoore** [comment]
This is mostly resolved with #435, the only caveat is downloads. See the PR for more detail.

**Comment by wilmoore** [comment]
This is fixed given #435 has been merged.

**Comment by jokeyrhyme** [comment]
This seems to have broken recently. I have many scoped packages using shield.io, and now they all display "npm | invalid", e.g.
- https://github.com/jokeyrhyme/promisify.js

Am I using the correct URL structure?

**Comment by joshrtay** [comment]
Ya. I agree. Just stopped working in last couple of days.

**Comment by joshrtay** [comment]
Looks like the npm registry changed it's api. `https://registry.npmjs.org/[@scope]/[package]/latest` no longer seems to be valid. Not sure what the new endpoint is.

**Comment by yordis** [comment]
:+1:

**Comment by espadrine** [comment]
I believe #616 fixed it.
