### ISSUE TITLE
how can I get a release badge for my repository?

### ISSUE THREAD

**Issue by nimasdj** [badges/shields#4293]
I did not understand how can I get a release badge for my repository?
When I add my url in your website I just get 4 badges, not other badges.

**Comment by calebcartwright** [comment]
Hi @nimasdj, are you looking for the GitHub Release badge? If so, try clicking the "Releases" link instead, or typing "github" or "releases" in the search box

**Comment by nimasdj** [comment]
Hi,
Thanks. I did and found this:
/github/v/release/:user/:repo
Now how to convert it to a cllickable markup?

**Comment by calebcartwright** [comment]
If you click on the badge listing there it will open up a window that will help you construct the badge for your repo, including the markdown

(I'd include some visuals but I'm on my phone at the moment)

**Comment by phplicengine** [comment]
Hi nimasdj,
When you got your shields link as Caleb said, you can use it in your github pages with this format:
[![Title](link you got from shields)(link to your github or packagist)]

You can see how we did use some shields badge on our page: 
https://github.com/phplicengine/bitly
and use like that for yours.

**Comment by calebcartwright** [comment]
From the badge listing page, you can click on any part of the listed examples to open the builder window for that badge type:
![image](https://user-images.githubusercontent.com/13042488/68091788-d15b4c80-fe49-11e9-9cc9-670a347a716e.png)

<br />
<br />

Once you have the window open, plug in the parameters for your repo/project/etc. You can then use the blue button at the bottom of the window to get a few different things for your badge. It defaults to the URL for your badge, but if you then click the the dropdown part of the button you'll see the other available auto-generated formats, including markdown

![image](https://user-images.githubusercontent.com/13042488/68091818-2a2ae500-fe4a-11e9-8af5-751f4b976bcb.png)

<br />
<br />

![image](https://user-images.githubusercontent.com/13042488/68091857-b937fd00-fe4a-11e9-9f10-99a12dcfe8c1.png)

The [GitHub Markdown Guide](https://guides.github.com/features/mastering-markdown/#images) also includes some information about embedding images into your markdown
