### ISSUE TITLE
Support other metrics for Sonar

### ISSUE THREAD

**Issue by victornoel** [badges/shields#430]
Hi,

Currently the sonar badge shows the "coverage" metric, but there is no reason to support other metrics (I'm personally interested in overall_coverage).

This would require a small change to the actual implementation of the sonar badge and would be retro-compatible with current badge API:

At https://github.com/badges/shields/blob/286c8069e45/server.js#L546, instead of matching "coverage" in the url, this should be replaced by a group that would be the name of the metrics to use for the argument metrics at https://github.com/badges/shields/blob/286c8069e45/server.js#L553.

I would love to write a PR but I don't know any javascript and it seems easy to do, but if you do want we to do it, I will try, thank you!

**Comment by espadrine** [comment]
Thanks for the suggestion!
