### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by monolithed** [badges/shields#434]
![1430211741501](https://cloud.githubusercontent.com/assets/803674/7366165/f0ffebf6-ed9e-11e4-8cf6-4c9c32e14203.png)
![1430211726912](https://cloud.githubusercontent.com/assets/803674/7366167/f6d797d6-ed9e-11e4-820c-4b628f158b00.png)

**Comment by espadrine** [comment]
Thanks for raising this. I'll investigate. It seems up now, at least.
