### ISSUE TITLE
Badge Request: REUSE compliance

### ISSUE THREAD

**Issue by mxmehl** [badges/shields#4365]
:clipboard: **Description**

It would be great to have a badge provided by shields.io for showing a project's compliance with the [REUSE best practices](https://reuse.software) that make licensing easier for everyone.

The project already has a service providing a badge but perhaps it's possible to also provide that over shields: https://api.reuse.software. It also offers a JSON endpoint. The overview page of a project looks a little something like this: https://api.reuse.software/info/github.com/fsfe/reuse-tool

The API requires a simple registration of a project.

:link: **Data**

The API is publicly accesisble, but only for repositories that have been registered: https://api.reuse.software/status/github.com/fsfe/reuse-tool

The provided information is faily simple, so no extensive documentation required.

:microphone: **Motivation**

For most developers, software licensing is a pain. There a dozens of suggestions how you should provide licensing and copyright information in a Free Software project. REUSE changes that by offering simple and logical best guidelines that make it easy to tag every file with the required information so it's easy to understand for humans and machines alike.

The API shows on first sight whether the current status is OK. For more detailed checks (e.g. different branches or in CI) there is the REUSE helper tool: https://github.com/fsfe/reuse-tool

**Comment by calebcartwright** [comment]
Thanks for the request @mxmehl! We have a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if you or anyone else is interested in implementing this badge.

**Comment by tapanchudasama** [comment]
Hey maintainer, If this issue is still up for grabs, I'd like to pick it up.

**Comment by mxmehl** [comment]
@tapanchudasama Sure, would be awesome! I won't be able to work on this in the next months.

**Comment by chris48s** [comment]
Feel free :+1:  Our tutorial for adding new badges is at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by tapanchudasama** [comment]
Hey @chris48s, I have raised a [PR](https://github.com/badges/shields/pull/6330) for this. Please have a look.

**Comment by mxmehl** [comment]
Thanks for working on this! For registered repos, it seems to work really well.

However, what about unregistered? They are labelled as such, but how do people learn about how to register them? Could we add a link to https://api.reuse.software/register ?

**Comment by chris48s** [comment]
The error handling for this is broadly in line with the error handling for other services. It is conceptually similar to if you request the coveralls badge with a repo that does exist but you don't use coveralls for measuring your coverage, or if you request the Cirrus CI badge with a repo that does exist but you don't use Cirrus as your Continuous Integration service. In general, badges do something useful if you're a user of the service and if you're not, they don't. We're not really trying to promote or drive signups to any particular service.
