### ISSUE TITLE
Badges to categorize software by privacy-awareness

### ISSUE THREAD

**Issue by jarun** [badges/shields#4366]
There can be several categories of software when it comes to privacy-awareness. Broadly they can be classified as:

- stores data that can be used to study user activity or behavioral patterns by default (e.g. an audio player that builds a library of all audio tracks as soon as it is installed, stores the date when a certain file was added to the library)
- provides configuration options to customize the information user shares (e.g. GNOME tracker)
- works without any need to store user-private data (say `ls`)
- can work without user-private data but certain features may be affected (e.g. bookmarking software)

There can be more.

While the best a user can do is to audit the open source code (s)he uses, it may not always be feasible. This is a feature request to provide some standard badges a software can use to declare how much privacy-aware it is. Thanks!

**Comment by calebcartwright** [comment]
@jarun can you elaborate a bit more on what you have in mind? The vast majority of the badges Shields provides are based on some upstream data source/API which Shields uses to retrieve data and then generate the corresponding badge. 

Shields also supports the ability for users to construct static badges where you can specify the label, message, and color. For example:

https://img.shields.io/badge/foo-bar-blue
![](https://img.shields.io/badge/foo-bar-blue)

If you could answer some of the below questions regarding your badge request that'd be a big help!

- Which service is this badge for e.g: GitHub, Travis CI
- What sort of information should this badge show?
  Provide an example in plain text e.g: "version | v1.01" or as a static badge
  (static badge generator can be found at https://shields.io)
- Where can we get the data from?
    - Is there a public API?
    - Does the API requires an API key?
    - Link to the API documentation.

**Comment by jarun** [comment]
> Shields also supports the ability for users to construct static badges where you can specify the label, message, and color.

Yes, I am aware that users can create custom badges using tokens. However, I am looking for some standard tokens given how important user-privacy is.

> Which service is this badge for e.g: GitHub, Travis CI

GitHub

> What sort of information should this badge show?

Something based on privacy-awareness level of the software. Probably on a scale of 0 to 5. The definition of the levels is the key and should be based on criteria such as the examples of software I cited in the issue description.

> Where can we get the data from?

A package or utility is supposed to pick a badge based on the privacy awareness. For example, a utility that doesn't touch any private information of the user should choose the badge of level 5.

**Comment by calebcartwright** [comment]
> However, I am looking for some standard tokens given how important user-privacy is.

So it sounds like you are ultimately requesting something that helps users construct static badges, i.e. something like

![](https://img.shields.io/badge/privacy-level%202-blue)
![](https://img.shields.io/badge/privacy-level%205-blue)

Is there any public standard/framework/etc. that defines those "privacy-awareness" levels and criteria?

**Comment by jarun** [comment]
> Is there any public standard/framework/etc. that defines those "privacy-awareness" levels and criteria?

There are many country/area-specific ones (e.g. GDPR - https://gdpr-info.eu/). But I do not see anything global.

It would have been great if a foundation like FSF could come up with such a standardization. I will see if I can take it forward or get something concrete on this.

For now, I think a badge that states a particular software is "privacy-aware" would be a good option.

**Comment by calebcartwright** [comment]
> It would have been great if a foundation like FSF could come up with such a standardization. I will see if I can take it forward or get something concrete on this.
> 
> For now, I think a badge that states a particular software is "privacy-aware" would be a good option.

Sounds good, though for now this is something that can be readily solved via static badges so I'm going to close this accordingly. Shields provides the static badge generator capability precisely for these types of scenarios for those that wish to create arbitrary badges that have no underlying data source. 

https://img.shields.io/badge/privacy-aware-blue
![](https://img.shields.io/badge/privacy-aware-blue)

**Comment by jarun** [comment]
Yes, I think that's good enough for now. :+1:
