### ISSUE TITLE
Badge request for GH version of R packages from the DESCRIPTION file

### ISSUE THREAD

**Issue by ajabadi** [badges/shields#4368]
:clipboard: **Description**

Thanks for the great work :)

It would be nice if R package developers could get public GH package version badges for their development versions from the DESCRIPTION file's line with structure: `Version: ${package_version} \n`

:link: **Data**

- The DESCRIPTION file's path is in https://github.com/${user}/${repo}/blob/${branch}/DESCRIPTION

- The policy that requires the aforementioned `Version: ` line structure can be found in http://r-pkgs.had.co.nz/description.html. 

- An example can be found [here](https://github.com/mixOmicsTeam/mixOmics/blob/RELEASE_3_10/DESCRIPTION).

:microphone: **Motivation**

It would be great if users could also have badges for their latest stable version not yet submitted on CRAN or Bioconductor so users can easily see if they need to update for the latest features or not.

**Comment by calebcartwright** [comment]
Thanks for the request @ajabadi! We have a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if you or anyone else is interested in implementing this badge.

We also have several similar badges that look at go.mod, pipenv, and package.json files in GH repos that can serve as good references.

https://github.com/badges/shields/blob/master/services/github/github-go-mod.service.js
https://github.com/badges/shields/blob/master/services/github/github-pipenv.service.js
https://github.com/badges/shields/blob/master/services/github/github-package-json.service.js

**Comment by ajabadi** [comment]
Thank you for implementing this! I could not see any updates on usage examples. Can you please provide one?
