### ISSUE TITLE
SensioLabsInsight inaccessible

### ISSUE THREAD

**Issue by nazar-pc** [badges/shields#437]
My project recently got Platinum medal, and from that moment I see "inaccessible" on badge.
Silver worked fine.
Here is how it looks now: [![SensioLabsInsight](https://img.shields.io/sensiolabs/i/eacdd55b-4a0e-4429-add5-e6a01adb12af.svg?label=SLInsight)](https://insight.sensiolabs.com/projects/eacdd55b-4a0e-4429-add5-e6a01adb12af)

**Comment by espadrine** [comment]
We receive a 401 Unauthorized. SensioLabs requires a secret token, and it is very obnoxious: https://github.com/badges/shields/pull/331.

I just checked, the tokens I use are the right ones.

I think they don't care enough. The best way for you to help on this issue is to contact the people behind SensioLabs directly, linking them to this issue.

**Comment by francoispluchino** [comment]
@espadrine I just contact the support of Sensio, I'll let you know.

**Comment by francoispluchino** [comment]
Response of sensio support: probably a problem with their servers. He must recontact me.

**Comment by espadrine** [comment]
Thanks!

**Comment by francoispluchino** [comment]
@espadrine The support needs more information. Will you give me a request of one badge for Sensio Insight, please?

**Comment by francoispluchino** [comment]
@espadrine OK, that's good, I found the line...

**Comment by espadrine** [comment]
@francoispluchino If you need it, I can send you the secret tokens, given your email address.

**Comment by francoispluchino** [comment]
@espadrine I just did test with my API credentials, and it's ok. I suggest you re-create a token. Otherwise, I still await news of the support.

**Comment by espadrine** [comment]
I regenerated a token, still no luck.

**Comment by francoispluchino** [comment]
They did tests (with admin user, and no admin user), and everything is OK for them. Nonetheless, I asked if they had not blocked your IPs... but I doubt for this point.

**Comment by francoispluchino** [comment]
@espadrine When is that you will deploy the fix of @smaftoul into production?

**Comment by espadrine** [comment]
Right about now ☺

**Comment by francoispluchino** [comment]
@espadrine Thanks!
