### ISSUE TITLE
img.shields.io using certificate with SHA-1 signature

### ISSUE THREAD

**Issue by willnorris** [badges/shields#439]
Chrome displays a warning about the certificate on <https://img.shields.io/> URLs:

![certificate](https://cloud.githubusercontent.com/assets/1112/7475529/fea916ac-f2fc-11e4-8ba3-dbff7833ab00.png)

which appears to be due to its use of SHA-1 for its signature.  Could that be updated to a certificate using a more up-to-date algorithm?

More info on Chrome's deprecation of SHA-1: http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

**Comment by espadrine** [comment]
I think @olivierlacan can help.

**Comment by justinmk** [comment]
Any update on this?

**Comment by espadrine** [comment]
Since the server switch, we are relying on CloudFlare's Full SSL offering, which fixes this issue in Chrome (it is using a SHA-2 certificate).

Do you have information on the trusted CA certificate list that bot-ci relies on?

**Comment by justinmk** [comment]
@espadrine TBH I am only guessing if the problem is with shields.io. We are getting this error in our travis-ci build which uses `wget https://img.shields.io/badge/clang_analysis-0-00ff00.svg -O badge.svg`:

```
--2015-09-12 08:20:27--  https://img.shields.io/badge/clang_analysis-0-00ff00.svg
Resolving img.shields.io (img.shields.io)... 104.18.45.160, 104.18.44.160
Connecting to img.shields.io (img.shields.io)|104.18.45.160|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.
```

I just found https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137 so it appears it is an ubuntu bug, something to do with TLSv1 + SSLv3.

So, disregard. Thanks

**Comment by espadrine** [comment]
Thanks for investigating the issue further!

Strangely, it does work on my machine (with GNU Wget 1.15 and OpenSSL 1.0.1e 11 Feb 2013).

**Comment by Adam-Goldman7** [comment]
adding `--secure-protocol=TLSv1` solved it for me
so in travis ci script I use
```
wget -O $BUILD_PATH/build-size.svg "https://img.shields.io/badge/build%20size-${BUILD_SIZE}-green.svg" --secure-protocol=TLSv1
```
