### ISSUE TITLE
App fails when using a named pipe for the port

### ISSUE THREAD

**Issue by hannesne** [badges/shields#4391]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

When hosting the app using iisnode (such as on an Azure App Service plan using Windows), the system exposes a named pipe for the port. This makes the validation logic in core/server/server.js fail, as it expects the port to be a tcp port number (integer 0 - 65560). 

:bulb: **Possible Solution**

Changing this validation rule to accept strings fixes the issue. I will post a PR.

**Comment by paulmelnikow** [comment]
A named pipe? That seems a bit odd!

Will Azure App Service allow running it in Linux instead?

**Comment by hannesne** [comment]
I had a quick go trying to run it in Linux, and couldn't get it to work. It didn't seem to respond appropriately to the pings from the underlying service fabric, and I've not yet figured out why. I'll try to have another look at it later. It did work on a Docker container in a Linux app service, but the container was 168MB big, which caused very long startup times when using a free app service plan. Some Windows features are also not necessarily always available in Linux.

**Comment by PyvesB** [comment]
According to Wikipedia regarding [named pipes in Windows](https://en.wikipedia.org/wiki/Named_pipe#In_Windows):

> They are very rarely seen by users, but there are notable exceptions. The VMware Workstation PC hardware virtualization tool, for instance, can expose emulated serial ports to the host system as named pipes

So ISS is maybe simply built using VMWare underneath the hood, which would explain this?

**Comment by hannesne** [comment]
I would be incredibly surprised to find any vmware in that stack. It all runs on hyper-v. This is the request handler that iis uses in app services when hosting node apps: https://github.com/Azure/iisnode

**Comment by PyvesB** [comment]
Closed by #4392 .
