### ISSUE TITLE
Customizing build status titles

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [badges/shields#4396]
:clipboard: **Description**
For example, I prefer to see `success` instead of `passing`. I think there are people that also prefer `success` or something else. AppVeyor already allows you to customize build status titles https://www.appveyor.com/docs/status-badges/#customizing-titles.

**Comment by paulmelnikow** [comment]
Hi! One of Shields' goals is to provide consistency and so we limit the amount of choices that are made available through the official badges.

We do have some test badges that allow overriding the message, however none of the build badges have this – they all use passing: https://shields.io/category/build

I understand that individual preferences might differ and one way to accomplish this if you feel strongly enough is to use endpoint badge, which lets you specify the exact content you want, while using img.shields.io for caching and formatting.

**Comment by calebcartwright** [comment]
Some relevant conversation on this topic over in https://github.com/badges/shields/issues/4393#issuecomment-561383287. 

I detailed my opinion over in the linked thread but just to summarize for inline awareness here: 

I definitely agree that we need consistent default values for green/red messages (which are respectively `passing` and `failing`) but I don't personally have any objections to allowing users to specify those messages via optional query params like we already do for the set of Tests badges and Status/Uptime badges.

**Comment by RedSparr0w** [comment]
I wouldn’t be opposed to allowing users to specify replacement text, what would the parameters look like though?
`passing=success&failing=failed`

**Comment by PyvesB** [comment]
Given that this is not a feature that our users have requested often, I would tend to agree with @paulmelnikow and aim for consistency and simplicity with regard to build status labels. 😉
