### ISSUE TITLE
Recieving "not found" JetBrains Downloads Plugin badge with valid plugin ID

### ISSUE THREAD

**Issue by exigow** [badges/shields#4397]
Hi,

generating a "Jetbrains Plugin Downloads" badge doesn't work in my case: output is always "not found". Unfortunately, I don't know what the reason may be but I suspect the problem may be the lack of stable distributions.

Details:
* Plugin repository: `https://plugins.jetbrains.com/plugin/13107-godot-gdscript`
* Identifier: `13107-godot-gdscript`
* Generated badge: `https://img.shields.io/jetbrains/plugin/d/13107-godot-gdscript` (**not working**)

Is this behavior intended?

**Comment by calebcartwright** [comment]
The JetBrains API is returning an empty response for that identifier:

https://plugins.jetbrains.com/plugins/list?pluginId=13107-godot-gdscript
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin-repository />
```

which represents the "Not Found" scenario from that API. I've no idea why the API is returning that not found response, but it's either an upstream issue with your plugin and/or with the API

**Comment by exigow** [comment]
Thank you for your answer. Issue is definitely not related to `shields.io`, sorry for the trouble. :)

**Comment by calebcartwright** [comment]
No worries!

**Comment by GodJiong** [comment]
> Hi,
> 
> generating a "Jetbrains Plugin Downloads" badge doesn't work in my case: output is always "not found". Unfortunately, I don't know what the reason may be but I suspect the problem may be the lack of stable distributions.
> 
> Details:
> 
> * Plugin repository: `https://plugins.jetbrains.com/plugin/13107-godot-gdscript`
> * Identifier: `13107-godot-gdscript`
> * Generated badge: `https://img.shields.io/jetbrains/plugin/d/13107-godot-gdscript` (**not working**)
> 
> Is this behavior intended?

hi，try this image link https://img.shields.io/jetbrains/plugin/v/13107
