### ISSUE TITLE
GitHub workflow badge cannot fetch the workflow name and always shows 'build'

### ISSUE THREAD

**Issue by mertyildiran** [badges/shields#4408]
:clipboard: **Description**

This is the Shiels.io GitHub workflow badge:

![](https://img.shields.io/github/workflow/status/DragonComputer/Dragonfire/Docker%20Build?logo=GitHub)

`https://img.shields.io/github/workflow/status/DragonComputer/Dragonfire/Docker%20Build?logo=GitHub`

and this is the badge generated by GitHub's own workflow badge generator:

![](https://github.com/DragonComputer/Dragonfire/workflows/Docker%20Build/badge.svg)

`https://github.com/DragonComputer/Dragonfire/workflows/Docker%20Build/badge.svg`

So I propose to show the workflow name(it's `Docker Build` in this example) on your badges. Currently the project like ours use mixture of Shields.io badges and GitHub's native badges which causes a visual inconsistency.

Also if people have multiple GitHub workflow Shields.io badges then they display `build` for all of the badges.

**Comment by calebcartwright** [comment]
@mertyildiran - you can use the label query parameter with any Shields badge to specify your desired label text `?label=Docker%20build`

https://img.shields.io/github/workflow/status/DragonComputer/Dragonfire/Docker%20Build?logo=GitHub&label=Docker%20Build
![](https://img.shields.io/github/workflow/status/DragonComputer/Dragonfire/Docker%20Build?logo=GitHub&label=Docker%20Build)

**Comment by mertyildiran** [comment]
@calebcartwright oh OK didn't know that thank you so much!

**Comment by calebcartwright** [comment]
No worries, happy to help@
