### ISSUE TITLE
SSL certificate issues

### ISSUE THREAD

**Issue by olivierlacan** [badges/shields#441]
Seems like our cert is having issues: 

![image](https://cloud.githubusercontent.com/assets/65950/7501345/456409c6-f401-11e4-890d-ccb212757a2a.png)

@whit537 I think you originally set this up. Anything you can do? I'm fine purchasing a new cert if need be, let me know.

**Comment by espadrine** [comment]
I believe this is a duplicate of https://github.com/badges/shields/issues/439

**Comment by olivierlacan** [comment]
Yep. GitHub search failed me.
