### ISSUE TITLE
Is ipv6 working?

### ISSUE THREAD

**Issue by elfet** [badges/shields#443]
Can not get my badge via ipv6: http://img.shields.io/travis/deployphp/deployer.svg?style=flat

**Comment by espadrine** [comment]
Hmm, it *should* work (and works locally if I fetch it as <http://[::1]:1111/try.html> on Firefox). Then again, Heroku might prevent that from working.

**Comment by elfet** [comment]
Thanks!

**Comment by espadrine** [comment]
Glad to help… although I didn't change a thing.
