### ISSUE TITLE
Azure Code Coverage badge, where is `definition id` value?

### ISSUE THREAD

**Issue by jtmoon79** [badges/shields#4433]
:question: I'm trying to add badge _Azure DevOps Code Coverage_ (a.k.a. _Azure Pipelines_) addressed in #2237.  **Where can I find the find the _value_ of the `definition id` field?**

This is for [my project that uses _cobertura_ code coverage tool](https://github.com/jtmoon79/goto_http_redirect_server/blob/516d13948a74b33c1416296cf48012789f15be04/.azure-pipelines/azure-pipelines.yml#L149-L155).

The `PublishCodeCoverageResults@2` task succeeds.  For example, this run reported [`Lines- 181 of 504 covered.`](https://dev.azure.com/jtmmoon/goto_http_redirect_server/_build/results?buildId=316&view=logs&j=a7c7ee29-70f5-5896-4a16-856e282d41cf&t=3691171b-27be-51f7-f378-fa7eedbfa19c&l=29).

However, in the [_Azure Devops Coverage_ badge helper popup](https://shields.io/category/coverage), I cannot render a badge that displays anything meaningful, no matter the value set in field `definition id`.  Most often the rendered text is _build pipeline not found_.

**How do I find the particular _value_ for the `definition id` field for this shields.io badge?**

**Comment by calebcartwright** [comment]
hey @jtmoon79 - I'm not sure what all you were trying, but you've only got the one pipeline in your `goto_http_redirect_server` project so I assume [this](https://dev.azure.com/jtmmoon/goto_http_redirect_server/_build?definitionId=1&_a=summary) is the pipeline you are targetting, and the definition id is `1`

https://img.shields.io/azure-devops/coverage/jtmmoon/goto_http_redirect_server/1 
![](https://img.shields.io/azure-devops/coverage/jtmmoon/goto_http_redirect_server/1)

On the helper popup on Shields.io for the Azure DevOps Coverage badge there is inline documentation and a screenshot (albeit one using the older `*.visualstudio.com/*` domains) that detail how you can get the id of your pipeline defition, but it's basically:

1) go to your AzDO project in your web browser
2) click on your target pipeline
3) look at the uri and grab the id

https://dev.azure.com/jtmmoon/goto_http_redirect_server/_build?definitionId=1&_a=summary

**Comment by jtmoon79** [comment]
I had entirely skimmed past `definitionId=1` in URL `https://dev.azure.com/jtmmoon/goto_http_redirect_server/_build?definitionId=1&_a=summary`.

Thanks @calebcartwright !
