### ISSUE TITLE
Please open a Security Advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [badges/shields#4438]
I'd like to report a security vulnerability.
Please open an advisory and add me to it.
https://github.com/badges/shields/security/advisories

**Comment by calebcartwright** [comment]
Thanks for reaching out @JLLeitschuh!

IIUC, only a [repo admin has access](https://help.github.com/en/github/managing-security-vulnerabilities/permission-levels-for-security-advisories#permissions-overview) to be able to add a user/collaborator to an advisory. 

@paulmelnikow is this something you have access to do?

**Comment by calebcartwright** [comment]
I've created one and added you as a collaborator @JLLeitschuh. I assume you would've received a notification with the advisory details but let us know if not

**Comment by calebcartwright** [comment]
Closing this in favor of continuing the dialog in the advisory
