### ISSUE TITLE
Include prerelase checkbox negative behavior

### ISSUE THREAD

**Issue by baruchiro** [badges/shields#4439]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

I'm trying to create a *Release Badge* to my new repo.

In my repo, there is one release, and this release is a **prerelase**.

[Releases](https://github.com/baruchiro/israeli-bank-scrapers-desktop/releases):
![image](https://user-images.githubusercontent.com/17686879/71236909-d5173580-2308-11ea-839b-7d4ebdae8331.png)

Badge include prerelease:
![image](https://user-images.githubusercontent.com/17686879/71236970-faa43f00-2308-11ea-9aa1-f7c56c1383da.png)

Badge without prerelease:
![image](https://user-images.githubusercontent.com/17686879/71237010-114a9600-2309-11ea-8098-9f9110389629.png)

**Comment by chris48s** [comment]
This is working as expected for me.

- ![](https://img.shields.io/github/v/release/baruchiro/israeli-bank-scrapers-desktop) - https://img.shields.io/github/v/release/baruchiro/israeli-bank-scrapers-desktop
- ![](https://img.shields.io/github/v/release/baruchiro/israeli-bank-scrapers-desktop?include_prereleases) - https://img.shields.io/github/v/release/baruchiro/israeli-bank-scrapers-desktop?include_prereleases

**Comment by calebcartwright** [comment]
It's working for me too, including in the modal Window
