### ISSUE TITLE
Question - github cache and images

### ISSUE THREAD

**Issue by max258** [badges/shields#444]
I'm not sure how your service work, becouse:
Github cache the images.
How do you change the image data?
For example Wordpress rating from 4 stars to 5 stars?
Is there any refresh interval to get the accurate data?

Code example on github:
```
<img src="https://camo.githubusercontent.com/095b8e13eb26f12a7e52a500ca1e56e68cd5ba93/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f746f74616c2e6a732e7376673f7374796c653d666c6174" alt="NPM version" data-canonical-src="https://img.shields.io/npm/v/total.js.svg?style=flat" style="max-width:100%;">
```
Thank you

**Comment by espadrine** [comment]
I plan on making a video to explain GitHub's caching mechanism. Basically, the hex hash is a URL that gets requested by GitHub every time (and cached only if the server lets them, which shields.io does not).

This project contains code for the shields service, which provides URLs for images that should always be accurate (see <https://shields.io>), an npm module to produce badges, and a CLI program, detailed here: https://github.com/badges/shields/blob/master/INSTALL.md.

If you believe some data is inaccurate, detail that. In your example, https://www.npmjs.com/package/total.js shows that indeed the version is 1.8.0.
