### ISSUE TITLE
'Waiting for img.shields.io" 

### ISSUE THREAD

**Issue by weitjong** [badges/shields#445]
After changing our project website to use shields.io, it frequently has long wait to render the badges. When we have problem in the badge rendering on our website, the http://shields.io/ also has the similar problem. So, I guess the problem is not on our side.

Is there any way to improve this? I am considering to switch back to use the original badges from their respective service providers. It is better to get a reliable low resolution version than an unreliable high resolution badge.

**Comment by espadrine** [comment]
I see you are using Coverity and Travis badges. I'll try to monitor their response times. Could you give me information about when they are not on par with what we should expect?

**Comment by weitjong** [comment]
Thanks for the prompt reply, much appreciated. I am sorry that I did not note down the exact time when it happened. What I can confirm that when it did happen, the sample badges on the http://shields.io/ were also not rendered. I may also add that the outage did not take long to recover. It is the outage frequency that worries me. I happened to catch it with the pant down three or four times already since we migrate.

**Comment by weitjong** [comment]
It is happening now.

**Comment by weitjong** [comment]
It seems it has recovered itself again.

**Comment by espadrine** [comment]
Thanks a lot for reporting. There seems to have been a surge in requests past 400 per seconds from servers at Amazon AWS. It has caused a lot of request time-outs, and has made Redis fail, which caused a marginal number of caught crashes (about 50).

There was also a Heroku slow-down at the same time caused by our using slighly over 512MB of memory, which made things worse.

I think I plan on switching away from Heroku. We can hopefully use a lot more memory and take surges like these with a better infrastructure.

**Comment by weitjong** [comment]
Thanks for looking into this.

**Comment by untitaker** [comment]
I frequently experience this with the Gratipay shields.

**Comment by ionelmc** [comment]
This issue still happens

**Comment by Stephn-R** [comment]
It is happening currently with rendering badges

**Comment by weitjong** [comment]
This may sound stupid (or arrogant depend on how you read it), but I was wondering whether this issue exists before I raised it. More precisely, did it exist before our project website switch to use shields.io badges? Or it it just because I am the first who bother to report it?

I would not reveal the link to our project website here to avoid the impression that I am promoting it but I believe it should contribute to quite an amount of workload on your server because:

- Our website has picked up a significant traffic recently.
- The badges are located in our default footer page template, i.e. the badges appear in the footer of all the generated pages, including our documentation pages.
- Before the switch, we have employed a small js to force browser to always download Travis-CI build status badges remotely instead of from local cache. This javascript is still in place after the switch.

With all these combined together, it means it does not matter where our website visitors navigate to, each page being rendered would generate a small workload on your server. The accumulated workloads could become significant depends on how well your server scale up on demand. Hence I am wondering could it be our own doing that cause this in the first place! I hope I am worrying too much tough.

**Comment by espadrine** [comment]
@weitjong Based on my server logs, there is no single website generating a majority of the traffic, although GitHub is the most significant. Issues related to the responsiveness of the server have existed as long as we have used the current configuration (see eg. https://github.com/badges/shields/issues/226), and have been solved by caches and algorithms so far. The main issue is that, as far as I know, the Heroku system doesn't give a way to the server software to detect when it enters slowdown mode. I will change server setup, however.

**Comment by weitjong** [comment]
Thanks for your prompt reply. Again much appreciated.

That is quite a relief to hear. I just want to come clean. :smile: 
Our website is hosted on github.io too. But I guess this statement does not change anything as you said the issue exists long before.

**Comment by ms-ati** [comment]
Just to add: the badges are still slow.

**Comment by mjackson** [comment]
I'm seeing timeouts on my Travis and npm badges today at https://github.com/rackt/history.

**Comment by jakirkham** [comment]
This issue seems to have reemerged.

**Comment by weitjong** [comment]
The problem seems to be getting worse. I have temporarily switch our website to use back the lower res badge from its original source instead of from shields.io. It probably does not make any differences to shields.io performance, but who knows.

**Comment by espadrine** [comment]
Indeed, it won't make a difference. Unfortunately, the server became unreachable at the worst possible time — just as I started going to sleep. I'm investigating the issue with my hosting provider.

**Comment by espadrine** [comment]
I have just rebooted the server, and things are running again.

**Comment by ms-ati** [comment]
@espadrine have you considered hosting the images on S3 behind CloudFront? Couldn't you cache them there, if not actually render them to their as a static site as the primary representation?

**Comment by espadrine** [comment]
@ms-ati There is a difference between having slow badges, having downtime, and having incorrect badges.

I strive to produce badges that are as correct as possible, as fast as possible, and with as little downtime as possible.

I switched hosting providers a week ago to fix the speed issue; badges should now be exactly as slow as the service that produces the information they provide (plus network lag, which is generally negligible). More importantly, while before the server entered a severe slowdown for one hour every week at peak times, that should no longer happen. So far, that seems accurate.

Today, the VPS went down and did not restart, for which I am talking to the provider. Having a CloudFront cache would not help a server that _is not running_ on a machine that _is not up_ to serve images.

Cache really is not the issue right now. I have a cache that I use when vendors (Travis CI, etc) do not respond, when data changes rarely, or when the server receives duplicate requests in rapid fire.

**Comment by gnzlbg** [comment]
Is it down again? :)

**Comment by ms-ati** [comment]
@espadrine Shouldn't a CloudFront or Fastly cache, simply in front of the badges system as a whole, smooth over any temporary outages? In other words, isn't HTTP caching itself a very well suited mechanism for increasing the availability of the badge urls?

**Comment by espadrine** [comment]
Yes, the server went dark again. I'm getting annoyed at OVH. I'd rather not spend another week of holidays setting things up yet again on a new server (say Digital Ocean), but two downtimes a week is obviously inacceptable. I sent them a mail, I will see what they say.

@ms-ati I use HTTP caching. Obviously, most people want badges to have accurate information, though. It is irrelevant anyway when you can't even access the IP that the DNS points your browser to.

**Comment by tankerkiller125** [comment]
@espadrine Would it make more sense to use AWS and automatic scaling load balanced instances? Thus handling large sums of traffic quickly and easily according to your auto scaling policy. So that when say 80% of CPU is being used AWS will automatically spin up an exact copy of that instance and start sending traffic to it and the other instance?

**Comment by ms-ati** [comment]
Would it also make sense to put a CDN in front, which is configured to
successfully return the last value when the origin is unreachable? This
would seem a good case for that?

On Mon, Oct 5, 2015 at 10:29 AM, tankerkiller125 <notifications@github.com>
wrote:

> @espadrine <https://github.com/espadrine> Would it make more sense to use
> AWS and automatic scaling load balanced instances? Thus handling large sums
> of traffic quickly and easily according to your auto scaling policy. So
> that when say 80% of CPU is being used AWS will automatically spin up an
> exact copy of that instance and start sending traffic to it and the other
> instance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/badges/shields/issues/445#issuecomment-145546410>.
>



-- 
Marc Siegel
Technology Specialist
American Technology Innovations

Email: marc@usainnov.com
Phone: 1 (617) 399-8145
Cell: 1 (617) 223-1220
Fax: 1 (617) 334-7975

**Comment by espadrine** [comment]
@tankerkiller125 Shields.io is not CPU-bound.

@ms-ati What is the difference between a CDN that returns the last value when the origin is unreachable, and a cache that does the same thing? We currently have the latter.

**Comment by ms-ati** [comment]
> What is the difference between a CDN that returns the last value when the origin
> is unreachable, and a cache that does the same thing? We currently have the latter.

@espadrine Good question! I believe the difference is in the area of _robustness_. Or downtime, like this ticket discusses.

Using a cache as we have today impacts _performance_, and it may provide _robustness_ against downtime of the data sources. However, as this ticket attests, it doesn't provide _robustness_ for the shields.io service endpoints itself.

I think that using a CDN "in front" of shields.io, which is configured to return successfully with the last value for any url it has cached when the origin is down, will provide _robustness_ to the service itself being down.

That way, badges that have previously been requested will continue to appear, and just won't be updated until the service is back up.

**Comment by tankerkiller125** [comment]
@ms-ati So for example how Cloudflare has its "Always Online" feature where any page cached is displayed to the user?

@espadrine The CPU was just an example there are many different parameters that you can use to define the scaling groups.

**Comment by espadrine** [comment]
That is a fair distinction. I wonder if CloudFlare allows that kind of behaviour. I'll look into it.

I also wonder what HTTP status code I should send for invalid badges. 504 Gateway Timeout seems right?

**Comment by tankerkiller125** [comment]
@espadrine Depending on the reason its invalid. If its invalid because say the project doesn't exist on the sources servers then it should be a 404. But if it is because shields.io is just unsuccessful reaching say for example github then it should return a 504.

**Comment by ms-ati** [comment]
@tankerkiller125 Yes, both CloudFlare and Cloud Front have support for this (IIRC).

@tankerkiller125 Agreed, 404 for a non-existent resource, 504 for temporarily unavailable

**Comment by tankerkiller125** [comment]
I might also note that putting a CDN in front of shields.io will help decrease the load as well (because cached request are served from them instead of the server)

**Comment by weitjong** [comment]
If the badge is for the build status then serving a cache version might not be desirable, especially for active project.

**Comment by ms-ati** [comment]
@weitjong: Do prefer to have badges unavailable, rather than serving the last known version, when the service is down? That is what we are discussing.

Caching is used regardless, and the badges should play well with HTTP caching semantics. The only change I'm advocating is to use a CDN configuration to ensure that, when the endpoint is down, the cached badges still show.

The only change, in other words, is from (no badge) => (last badge) when service is down. Everything else, including timeliness of updates, would stay the same.

**Comment by weitjong** [comment]
I see. Thanks for your explanation. I did misunderstand it earlier. Having said that,  I think I prefer "status unknown" or something like that instead of "last known".

**Comment by espadrine** [comment]
CloudFlare doesn't seem able to do what we want here. [Always Online](https://www.cloudflare.com/always-online/) works through a weekly crawler, which would never see any of our users' badges. It only caches HTML, and [up to 3 pages](https://support.cloudflare.com/hc/en-us/articles/202238800).

**Comment by tankerkiller125** [comment]
Maybe some of us with spare computing power laying around (like I have several older XP machines) could donate that power by running the application and then giving you the IP so that you can add it to some sort of load-balancing proxy? This would also help with Githubs Rate Limiting because we would all have different Keys.

**Comment by patrikhuber** [comment]
I've had my badges repeatedly not loading over the past few days, and right now, img.shields.io seems to even have gone down. Is anybody else experiencing similar problems?

**Comment by espadrine** [comment]
It doesn't seem down, and the load average is pretty low (0.75, 0.79, 0.83). We might improve performance with [node cluster](https://nodejs.org/api/cluster.html), it's hard to tell before we do it.

**Comment by tankerkiller125** [comment]
@espadrine If you ran a NGINX loadbalancer (not DNS roundrobin) it could verify and make sure that the server is online and you could also set weights (so that people with less network IO speed get less traffic than someone who has good network IO)

**Comment by patrikhuber** [comment]
I don't know, I get this very often, like more than 50% of the time:
![image](https://cloud.githubusercontent.com/assets/4967343/12276809/bf7542f0-b96f-11e5-899f-f2cee6bd112f.png)

Interestingly the travis badge loaded (which is also a shields.io badge - but it took half a second, while for example the appveyor badge loads instantly), the other ones did not.

It can't be my own ISP, can it?

**Comment by espadrine** [comment]
@patrikhuber Hmm, the camo thing is weird. On principle, camo simply remembers the link between each id and the corresponding URL, and calls that URL. Can you give me the link to the readme, or the URLs?

**Comment by patrikhuber** [comment]
@espadrine Sure! All my repos are affected in fact. See for example the readme of https://github.com/patrikhuber/4dface.

Ah, and I don't think it has anything to do with my ISP, since I have the same problem at Uni and via 4G. Maybe I'm just too dumb to set the links correctly or made another mistake somewhere? (but that seems a bit odd since there's not actually much one can do wrong ;-) )

**Comment by espadrine** [comment]
@patrikhuber Ah never mind, the camo URLs didn't work because there is a `…` in the middle. GitHub badges respond slowly currently, probably because I reached their rate limit. I'll try to reach out to them.

**Comment by patrikhuber** [comment]
@espadrine Right, the Chrome developer console inserted the `...` because the link is too long. However if you copy the correct URL by yourself, for example [this](https://camo.githubusercontent.com/1f8b6bd33a7dfd3ed65e72cc1f23b87ca46ef325/687474703a2f2f696d672e736869656c64732e696f2f6769746875622f72656c656173652f70617472696b68756265722f3464666163652e7376673f7374796c653d666c61742d737175617265), GitHub returns a "Not Found". Maybe that helps in your debugging.

**Comment by tankerkiller125** [comment]
@espadrine I've done some more research on the DNS Round Robin. Because of the way clients work they will continue trying new IP's returned by the DNS untill they get a valid response from a server. In other words if there are 50 servers and 25 of them down users are going to get a response 100% of the time because of the way the client software works.

> if one of the servers becomes unreachable, the client's web-browser will try the next IP address records returned by the DNS server and repeat the process to get the web-site.

I'm not sure how Githubs Camo service will handle it but I do know that a browser will be just fine (checked it out myself)

**Comment by AshleyMedway** [comment]
This is happen now. CloudFlare - HTTP error 522 - Connection timed out

**Comment by patrikhuber** [comment]
I think my issue is a different one. I'm still having this issue with camo.githubusercontent.com. It doesn't load my badges at all, see my repo https://github.com/patrikhuber/4dface. Any update on this, or anything I can do to help debug it?

**Comment by hotrush** [comment]
![scr](http://dl3.joxi.net/drive/0010/1661/693885/160203/c550d7f2c5.png)
![scr](http://dl1.joxi.net/drive/0010/1661/693885/160203/de68bd1a4a.png)
seems it just works when wants

**Comment by tankerkiller125** [comment]
@hotrush I think the load that the servers are under is causing the request to API's to occur to slowly for the software. Causing the vendor unresponsive errors.

**Comment by espadrine** [comment]
Note: I changed to having two servers with DNS round-robin. We'll see if there is some improvements.

**Comment by patrikhuber** [comment]
My badges still don't load (see my post & repo link above), do you have any idea what I could try?

**Comment by pkoretic** [comment]
@patrikhuber @espadrine 

I have the same problem, seems that github link for license badge inside readme doesn't work for some time now
replacing it with direct link works 

`[![License](http://img.shields.io/:license-mit-blue.svg)](http...)`

**Comment by patrikhuber** [comment]
I just checked and was very surprised to see the license and version badges load a few minutes ago. I refreshed a few times and it was working each time.

Now, 3 minutes or so later, the release badge is back to not loading.

**Comment by espadrine** [comment]
@patrikhuber That's probably GitHub's rate limit on one server kicking in. I suggest using `https://img.shields.io/badge/license-mit-blue.svg?style=flat-square` instead. That will essentially instantaneously load.

**Comment by algorys** [comment]
Hello,

I've the same issue with my badges.

Travis badge working well, other (Github Badge : License and Releases) sometimes appears, sometimes not.

https://github.com/algorys/agshmne/

@espadrine I'll try your solution.

**Comment by patrikhuber** [comment]
@espadrine Is there a workaround/solution for the release version badges?

**Comment by algorys** [comment]
@patrikhuber you can make the same with your release but you have to change manually for each versions / tags :

`[![GitHub release](https://img.shields.io/badge/release-v0.0.3-blue.svg)](https://github.com/algorys/agshmne/releases/latest)`

But as I said before, if you release often it'll be hard to maintain.

**Comment by espadrine** [comment]
@patrikhuber I'm exchanging with GitHub to figure out a solution. The main issue is here: https://github.com/badges/shields/issues/529. It does affect everyone, although we do have two servers, so two IPs, presumably treated separately.

**Comment by patrikhuber** [comment]
@algorys I know, but that's not really a great option unfortunately.

@espadrine Cool, that's great to hear! Awesome. And thanks to the link to #529. It just seems a bit disappointing that the conversation hasn't advanced since Sept 2015. Anyway, glad to see I'm not the only one having this issue, and I hope there will be a solution soon.

**Comment by marcelstoer** [comment]
I've just gone through the comments in this issue and those in its sibling #529. As a result I also contributed tokens using https://img.shields.io/github-auth.

What I don't understand is why GitHub would switch img src URLs from https://img.shields.io/ with those from https://camo.githubusercontent.com/ at all. After all, it'd be _the browser_ making those requests and thus hit shields.io. Why would GitHub want to redirect (and cache) those? To me that makes particularly little sense for "static" badges (i.e. those that don't need to access GitHub resources to render) such as license or Twitter.

**Comment by espadrine** [comment]
@marcelstoer Originally, the point was to avoid mixed-content warnings which browsers raise when a HTTPS page has resources (eg. images) fetching data over insecure HTTP. You can read more on the subject [on their README](https://github.com/atmos/camo/blob/master/README.md).

**Comment by marcelstoer** [comment]
Ahh, right... "mixed-content warnings" - except that shields.io can be accessed over HTTPS as well.

**Comment by espadrine** [comment]
@marcelstoer Camo is now also used to set CSP information, which they rely on to avoid a class of vulnerabilities, things that are part of XSS or CSRF.

**Comment by marcelstoer** [comment]
Would self-hosting be a sensible alternative to all of us loading from https://img.shields.io?

**Comment by pkoretic** [comment]
@marcelstoer I've put my static badges to separate branch and linked that over rawgit service after too much trouble with img.shields.io, it's just not available most of the time
I can confirm it works without issues, example: https://github.com/qaap/recurse

**Comment by marcelstoer** [comment]
@pkoretic I had already planned to do that for static badges as well. The majority of badges are dynamic, though (i.e. the make some API calls).

**Comment by pkoretic** [comment]
@marcelstoer yeah, I ignored them for now, probably the best is to add reverse caching proxy in front of them for your usage

**Comment by marcelstoer** [comment]
I believe there's a misunderstanding, either on your side or on mine 😉 What I meant was to host _this project_ myself at let's say https://shields.mydomain.io. Then in my READMEs I'd use _that_ domain. GitHub would still route them through camo but those requests wouldn't count against the https://img.shields.io rate limit.

**Comment by pkoretic** [comment]
@marcelstoer I understand, but it seems to much work for just badges
it would be better if we could give more servers into the pool, since I too have spare dedicated servers which could take on that load

Thats why I recommended reverse caching proxy (using nginx for example)

That way you can still use your domain https://shields.mydomain.io which is proxy to https://img.shields.io so when https://img.shields.io is not available you will still get cached results instead of hanging

**Comment by espadrine** [comment]
The load has increased quite a bit lately: it averages 170 req/s at peak time. I'll add a server to the pool (I currently rely on two servers).

GitHub rate limits are not the issue anymore.

**Comment by tankerkiller125** [comment]
@espadrine There is a module for Nginx that allows the load balancing feature to be controlled by a rest interface. And you could do an HTTP check on the servers like every 20s or so. This would allow people with additional servers to help out with handling the load with the minimal configuration for you to handle. Of course, this would need some authentication so that people can add and remove servers securely.

**Comment by paulmelnikow** [comment]
@espadrine Is there any action to take here?

**Comment by espadrine** [comment]
@paulmelnikow I believe the performance of the servers is more suitable nowadays.

**Comment by DudeWhoCode** [comment]
This is happening right now:(
