### ISSUE TITLE
How can I use Shields.io in local?

### ISSUE THREAD

**Issue by massinlaaouaj** [badges/shields#4456]
:question: **Question**

I'm interessed to use shields in local for ping testing, I wanna use in local because the host he don't has internet out.

How can I do?

Thanks.

**Comment by calebcartwright** [comment]
hi @massinlaaouaj! it's pretty easy to run your own Shields server, and we've got a lot of the approaches for doing so documented in https://github.com/badges/shields/blob/master/doc/self-hosting.md.
