### ISSUE TITLE
LeanPub Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4457]
:clock11: **When did the problem start?**
December ~12th 

:camera: **Live badge**
https://img.shields.io/leanpub/book/pages/hands-on-nodejs
![](https://img.shields.io/leanpub/book/pages/hands-on-nodejs)

https://img.shields.io/leanpub/book/pages/juice-shop
![](https://img.shields.io/leanpub/book/pages/juice-shop)

:wrench: **Is the live badge working?**
Doesn't appear to be working

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/787

:beetle: **Stack trace**

```
LeanpubBookSummaryService [live] known book pages [ GET /pages/juice-shop.json ] - [ GET /pages/juice-shop.json ]
  AssertionError: label mismatch: expected 'leanpub' to equal 'pages'

LeanpubBookSummaryService [live] known book sold [ GET /sold/juice-shop.json ] 
   AssertionError: label mismatch: expected 'leanpub' to equal 'sold'
```

:bulb: **Possible solution**

**Comment by chris48s** [comment]
Looks like LeanPub have restricted their API to pro plan users: https://leanpub.com/help/api

A pro plan is $12.99 per month so I suspect this means we probably just have to abandon these badges.

**Comment by calebcartwright** [comment]
So they have 🤔 That's a bummer!

**Comment by calebcartwright** [comment]
I agree that we shouldn't purchase a monthly subscription just to get access to the data (that could set a bad precedent and lead to it becoming **very** expensive to run the Shields service). 

I took a look at our metrics though and there was well north of 700 requests for Leanpub badges in the last 24 hours which indicates there's _some_ community interest in these badges and has me wondering if it'd be worth reaching out to them to see whether they'd be interested in offering Shields an API token. 

Do you think it's worth it or should we just go ahead and start working on deprecating them?

**Comment by chris48s** [comment]
I think given they've been broken for over a week and nobody has raised an issue about it or commented/reacted here we can probably just remove them, but if you're keen to see if we can get a key, feel free.

**Comment by calebcartwright** [comment]
SGTM!
