### ISSUE TITLE
GitHub Deployments

### ISSUE THREAD

**Issue by TrueBrain** [badges/shields#4477]
:clipboard: **Description**

GitHub has (basic) support for deployments. We started to use this, and I have been trying to get a badge for this. Sadly, the API is a bit too complicated to simply use the dynamic badge, or at least as far as I understand it. So having support for this, or helping me out how to do it, would be greatly appreciated :)

What I would like the badge to show, per environment, what the current state is of the latest deployment. So for example:

![GitHub Deployments](https://img.shields.io/badge/staging-success-green)

:link: **Data**

For example:
https://api.github.com/repos/OpenTTD/website/deployments?environment=staging

This gives an overview of all the deployments. We need the latest. In here is `statuses_url` which leads to:
https://api.github.com/repos/OpenTTD/website/deployments/191234207/statuses

Here the top result is the latest update of the deployment, the one I would like to see. The `status` field is the important part here.

See https://developer.github.com/v3/repos/deployments/ for more information.

:microphone: **Motivation**

As we are slowly migrating to having GitHub the center of the universe, having a badge with the latest deployment status is the next logic step.
The current issue I am having is that I have to make two dynamic calls for a single badge. I have no idea how I could be doing that.

**Comment by calebcartwright** [comment]
I wonder if the v4 API provides the data more readily available via a single request 🤔 

Definitely worth looking into supporting this badge, though in the immediate short term one possible solution would be to use our endpoint badge (https://shields.io/endpoint) type with a custom endpoint that makes those two API calls and returns the data in the required format

**Comment by calebcartwright** [comment]
Yup, looks like the latest deployment status data can be retrieved via a single request using the v4 GraphQL endpoint (https://developer.github.com/v4/object/deployment/)

Sample query:
```graphql
query($user: String!, $repo: String!, $environment: String!) {
  repository(owner: $user, name: $repo) {
    deployments(last: 1, environments: [$environment]) {
      nodes {
        latestStatus {
          state
        }
      }
    }
  }
}
```

If anyone is interested in working on this, we've a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) on implementing new badges!

There's a handful of our other GitHub badges that are using the new v4 endpoints that can be used as references as well: https://github.com/search?utf8=%E2%9C%93&q=extends+GithubAuthV4Service+repo%3Abadges%2Fshields+path%3A%2Fservices&type=Code&ref=advsearch&l=&l=

**Comment by TrueBrain** [comment]
That "good first issue" label is spot on. Thank you for the detailed feedback, that made it easy to produce a PR. Seriously: thank you!

**Comment by chris48s** [comment]
done in #4477
