### ISSUE TITLE
shields.io down?

### ISSUE THREAD

**Issue by shakna-israel** [badges/shields#448]
Noticed that the badges on mine, and a few other projects weren't loading, so I went over to the site, and none of the badges loaded on the page.

Trying to open the direct URL gets hit by a Heroku alert for an "Application error".

e.g. ```https://img.shields.io/pypi/dm/Django.svg``` returns:

# Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by weitjong** [comment]
This intermittent problem has been reported in #445.

**Comment by shakna-israel** [comment]
Is slow rendering the same as Heroku saying that the app has crashed?

**Comment by weitjong** [comment]
I think we are looking at a same issue. I also get the same error you got for my badges when using the direct URL. The long "Waiting for img.shields.io" also implies the badges do not get rendered eventually. i.e. they may get rendered or may be not at the end of the long wait.

**Comment by espadrine** [comment]
Closing, as this is related to #445.

**Comment by maravento** [comment]
reopen. https://shields.io/ is down or error

![Captura de pantalla -2022-02-12 10-51-59](https://user-images.githubusercontent.com/14880802/153718207-80094174-e8d7-4ca3-8cfd-da0e2898d29e.png)
