### ISSUE TITLE
TeamCity "Invalid response data" for build chain  

### ISSUE THREAD

**Issue by ernado** [badges/shields#4486]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Getting "invalid response data"

:link: **Link to the badge**

https://img.shields.io/teamcity/build/s/gortcd_MasterStatus?server=https%3A%2F%2Ftc.gortc.io

Default svg:
[![Master status](https://tc.gortc.io/app/rest/builds/buildType:(id:gortcd_MasterStatus)/statusIcon.svg)](https://tc.gortc.io/project.html?projectId=gortcd&tab=projectOverview&guest=1)

Shidelds.io svg:
[![Master status](https://img.shields.io/teamcity/build/s/gortcd_MasterStatus?server=https%3A%2F%2Ftc.gortc.io
)](https://tc.gortc.io/project.html?projectId=gortcd&tab=projectOverview&guest=1)

:bulb: **Possible Solution**

```console
$ curl  -H "Accept: application/json" "https://tc.gortc.io/app/rest/builds/buildType:(id:gortcd_MasterStatus)?guest=1" | jq
```

```json
{
  "id": 46071,
  "buildTypeId": "gortcd_MasterStatus",
  "number": "216",
  "status": "SUCCESS",
  "state": "finished",
  "composite": true,
  "branchName": "master",
  "defaultBranch": true,
  "href": "/app/rest/builds/id:46071",
  "webUrl": "https://tc.gortc.io/viewLog.html?buildId=46071&buildTypeId=gortcd_MasterStatus",
  "statusText": "Build chain finished (success: 9)",
  "buildType": {
    "id": "gortcd_MasterStatus",
    "name": "master status",
    "description": "Current status of master branch",
    "projectName": "gortcd",
    "projectId": "gortcd",
    "href": "/app/rest/buildTypes/id:gortcd_MasterStatus",
    "webUrl": "https://tc.gortc.io/viewType.html?buildTypeId=gortcd_MasterStatus"
  },
  "queuedDate": "20200103T154734+0100",
  "startDate": "20200103T154734+0100",
  "finishDate": "20200103T154744+0100",
}
```

Seems like the reason is schema for `statusText`. `Build chain finished (success: 9)` value fails to validate.

**Comment by calebcartwright** [comment]
Thanks for reporting @ernado! You are correct that it's a schema validation issue on the `statusText` field. 

I'm trying to remember why we were filtering that field so tightly as it's basically used as a passthrough 🤔

**Comment by ernado** [comment]
Thank you for quick response! 

I've also took a look at `/services/teamcity/teamcity-build.service.js`.
Seems like it is safe to just remove `buildStatusTextRegex`. Probably initially it was one of `Success|Failure|Error`, but it became an arbitrary status text that has no strict schema, so each update causes "invalid response data" and another regex adjustment.

>  it's basically used as a passthrough

Yep, just lowercase of that initial string.

**Comment by calebcartwright** [comment]
> Seems like it is safe to just remove buildStatusTextRegex

Agreed, seems like the best course of action. The schema should probably just be

```js
const buildStatusSchema = Joi.object({
  status: Joi.equal('SUCCESS', 'FAILURE', 'ERROR').required(),
  statusText: Joi.string().required(),
}).required()
```

Any chance you'd be interested in submitting a PR with the fix?

**Comment by ernado** [comment]
> Any chance you'd be interested in submitting a PR with the fix?

I would like to, but I'm afraid I'm not so experienced with node to make it right, sorry.

**Comment by calebcartwright** [comment]
No worries! For anyone interested in implementing this:

change these lines:
https://github.com/badges/shields/blob/02681cfe270b487dd82ebbcd170c7632fc518f5e/services/teamcity/teamcity-build.service.js#L7-L16

to:
```js
const buildStatusSchema = Joi.object({
  status: Joi.equal('SUCCESS', 'FAILURE', 'ERROR').required(),
  statusText: Joi.string().required(),
}).required()
```
