### ISSUE TITLE
Dockerhub build: "not found"

### ISSUE THREAD

**Issue by pauldraper** [badges/shields#4493]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The badge https://img.shields.io/docker/build/rivethealth/aws-saml shows "repo not found", despite the existence of the repo: https://hub.docker.com/r/rivethealth/aws-saml 

![badge](https://img.shields.io/docker/build/rivethealth/aws-saml)

**Comment by calebcartwright** [comment]
Try using the cloud build badge. The badge at the `../docker/build/..`  is more of a legacy badge to support "older" repositories that were created prior to docker's launch of the "new" docker hub (back in 2018)

https://img.shields.io/docker/cloud/build/rivethealth/aws-saml
![](https://img.shields.io/docker/cloud/build/rivethealth/aws-saml)

**Comment by calebcartwright** [comment]
I assume that's working for you @pauldraper, so going to close this. Feel free to re-open if needed
