### ISSUE TITLE
Badge for wikidata entity

### ISSUE THREAD

**Issue by tledoux** [badges/shields#4497]
:clipboard: **Description**

Create a badge to give access to a wikidata entity

For example, the badge for Q57699905 could be like:

[![Wikidata](https://img.shields.io/badge/-Q57699905-grey?logo=data:image/png;base64,UklGRsoAAABXRUJQVlA4TL0AAAAvJ0AFEAeBmJEk1Zw/xfkczz1bg1EkSZGSy/8PAdhBEezRiNq2kfM8PIfn+LO4Mo1tqxFBRpnlQ1IIdVEUzXxLWI/dmQCzKIeGFxpO/EIrigKiAgAgxJ1v/3Ee0JdQtZUVRV/ZePuG9JJMC9/xNQiU5ozAtpEkRfN4+AzHkH+cz+ZbEf1XkLYBsxn4JvApu7oghJQVIS2WYZ+8UgraWaX0QccZlPdSyoZJKTDO25pDCIgmhRAPOv5TfPi3LwkA)](https://www.wikidata.org/wiki/Q57699905)

Code:
```
[![Wikidata](https://img.shields.io/badge/-Q57699905-grey?logo=data:image/png;base64,UklGRsoAAABXRUJQVlA4TL0AAAAvJ0AFEAeBmJEk1Zw/xfkczz1bg1EkSZGSy/8PAdhBEezRiNq2kfM8PIfn+LO4Mo1tqxFBRpnlQ1IIdVEUzXxLWI/dmQCzKIeGFxpO/EIrigKiAgAgxJ1v/3Ee0JdQtZUVRV/ZePuG9JJMC9/xNQiU5ozAtpEkRfN4+AzHkH+cz+ZbEf1XkLYBsxn4JvApu7oghJQVIS2WYZ+8UgraWaX0QccZlPdSyoZJKTDO25pDCIgmhRAPOv5TfPi3LwkA)](https://www.wikidata.org/wiki/Q57699905)
```

This should be created simply via /wikidata/:qid

:link: **Data**

Any entity can be linked to directly.

:microphone: **Motivation**

The idea is to be able to reference wikidata entity in markdown documents with automatic link as well as a clear information about where the identifier comes from.

Thanks in advance

**Comment by calebcartwright** [comment]
@tledoux - Could you please clarify what you are asking for? AFAICT the request is simply a static badge with a static message, in which case you'd want to use Shields static badge as you did in the issue description.

**Comment by tledoux** [comment]
Indeed my main motivation was to simplify the markdown to something like:
```
[![Wikidata](https://img.shields.io/wikidata/Q57699905)](https://www.wikidata.org/wiki/Q57699905)
```

But I see that the main point is the logo which should be added to the standard ones, which is another matter.
Sorry for the annoyance and many thanks for the great badges...

**Comment by calebcartwright** [comment]
No worries! 

> But I see that the main point is the logo which should be added to the standard ones, which is another matter

Yup you've got it. We rely (mostly) on simple icons for logos, so you'd probably want to reach out over there to try to get the wikidata logo more readily available. That would get allow for badges like:

https://img.shields.io/badge/-Q57699905-grey?logo=wikidata

More info here on logos within Shields can be found here:
https://github.com/badges/shields/blob/master/doc/logos.md#contributing-logos
