### ISSUE TITLE
Badge request: Curseforge

### ISSUE THREAD

**Issue by LoneWanderer-GH** [badges/shields#4498]
:clipboard: **Description**

Badges for [CurseForge](https://www.curseforge.com/) addons.

- What sort of information should this badge show?
  - Repository name
  - Download count
  - Managed game versions

Simple example:
![](https://img.shields.io/badge/dynamic/json?label=Curse%20downloads&color=orange&query=downloadCount&url=https://addons-ecs.forgesvc.net/api/v2/addon/356973/)
One could also give a shot to the very nice project https://github.com/way2muchnoise/CurseForgeBadge  that does part of the job but may not be as popular a shileds

:link: **Data**

Where can we get the data from?

- Is there a public API? https://addons-ecs.forgesvc.net/api/v2/addon/<project number>  see example above
- Does the API requires an API key? seems not !
- Link to the API documentation **broken links** : https://www.curseforge.com/docs/api https://github.com/curseforge/api

:microphone: **Motivation**

Please explain why this feature should be implemented and how it would be used.
- What is the specific use case?
Most addons developper have a custom/own repo (say github) and might want to show some status of their addon on CurseForge. CurseForge is a repo of ready-to-use addons for video games and has addon managing tools (such as Twitch app)

Example of request result:

```
{
  "id": 356973,
  "name": "CoolLine (classic updated)",
  "authors": [
    {
      "name": "lonewanderer_twitch",
      "url": "https://www.curseforge.com/members/436037-lonewanderer_twitch?username=lonewanderer_twitch",
      "projectId": 356973,
      "id": 262075,
      "projectTitleId": null,
      "projectTitleTitle": null,
      "userId": 436037,
      "twitchId": 65711671
    }
  ],
  "attachments": [
    {
      "id": 242739,
      "projectId": 356973,
      "description": "",
      "isDefault": true,
      "thumbnailUrl": "https://media.forgecdn.net/avatars/thumbnails/242/739/256/256/637136000695779179.png",
      "title": "637136000695779179.png",
      "url": "https://media.forgecdn.net/avatars/242/739/637136000695779179.png",
      "status": 1
    }
  ],
  "websiteUrl": "https://www.curseforge.com/wow/addons/coolline-classic-updated",
  "gameId": 1,
  "summary": "CoolLine for retail and classic",
  "defaultFileId": 2854263,
  "downloadCount": 44,
  "latestFiles": [
    {
      "id": 2854263,
      "displayName": "8.0.008",
      "fileName": "CoolLine-8.0.008.zip",
      "fileDate": "2020-01-04T00:48:22.253Z",
      "fileLength": 19179,
      "releaseType": 1,
      "fileStatus": 4,
      "downloadUrl": "https://edge.forgecdn.net/files/2854/263/CoolLine-8.0.008.zip",
      "isAlternate": false,
      "alternateFileId": 0,
      "dependencies": [
        {
          "id": 34965097,
          "addonId": 14320,
          "type": 1,
          "fileId": 2854263
        },
        {
          "id": 34965098,
          "addonId": 14328,
          "type": 1,
          "fileId": 2854263
        },
        {
          "id": 34965096,
          "addonId": 15049,
          "type": 1,
          "fileId": 2854263
        }
      ],
      "isAvailable": true,
      "modules": [
        {
          "foldername": "CoolLine",
          "fingerprint": 2303328661,
          "type": 3
        }
      ],
      "packageFingerprint": 2273872717,
      "gameVersion": [
        "8.2.5"
      ],
      "sortableGameVersion": [
        {
          "gameVersionPadded": "0000000008.0000000002.0000000005",
          "gameVersion": "8.2.5",
          "gameVersionReleaseDate": "2019-09-23T00:00:00Z",
          "gameVersionName": "8.2.5"
        }
      ],
      "installMetadata": null,
      "changelog": null,
      "hasInstallScript": false,
      "isCompatibleWithClient": true,
      "categorySectionPackageType": 1,
      "restrictProjectFileAccess": 1,
      "projectStatus": 4,
      "renderCacheId": 1735174,
      "fileLegacyMappingId": null,
      "projectId": 356973,
      "parentProjectFileId": null,
      "parentFileLegacyMappingId": null,
      "fileTypeId": null,
      "exposeAsAlternative": null,
      "packageFingerprintId": 393936198,
      "gameVersionDateReleased": "2019-09-23T00:00:00Z",
      "gameVersionMappingId": 2051275,
      "gameVersionId": 7585,
      "gameId": 1,
      "isServerPack": false,
      "serverPackFileId": null,
      "gameVersionFlavor": "wow_retail"
    },
    {
      "id": 2854264,
      "displayName": "8.0.008-classic",
      "fileName": "CoolLine-8.0.008-classic.zip",
      "fileDate": "2020-01-04T00:48:24.72Z",
      "fileLength": 19176,
      "releaseType": 1,
      "fileStatus": 4,
      "downloadUrl": "https://edge.forgecdn.net/files/2854/264/CoolLine-8.0.008-classic.zip",
      "isAlternate": false,
      "alternateFileId": 0,
      "dependencies": [
        {
          "id": 34965101,
          "addonId": 14328,
          "type": 1,
          "fileId": 2854264
        },
        {
          "id": 34965099,
          "addonId": 15049,
          "type": 1,
          "fileId": 2854264
        },
        {
          "id": 34965100,
          "addonId": 14320,
          "type": 1,
          "fileId": 2854264
        }
      ],
      "isAvailable": true,
      "modules": [
        {
          "foldername": "CoolLine",
          "fingerprint": 2861867095,
          "type": 3
        }
      ],
      "packageFingerprint": 3555286068,
      "gameVersion": [
        "1.13.3"
      ],
      "sortableGameVersion": [
        {
          "gameVersionPadded": "0000000001.0000000013.0000000003",
          "gameVersion": "1.13.3",
          "gameVersionReleaseDate": "2001-01-01T00:00:00Z",
          "gameVersionName": "1.13.3"
        }
      ],
      "installMetadata": null,
      "changelog": null,
      "hasInstallScript": false,
      "isCompatibleWithClient": true,
      "categorySectionPackageType": 1,
      "restrictProjectFileAccess": 1,
      "projectStatus": 4,
      "renderCacheId": 1735175,
      "fileLegacyMappingId": null,
      "projectId": 356973,
      "parentProjectFileId": null,
      "parentFileLegacyMappingId": null,
      "fileTypeId": null,
      "exposeAsAlternative": null,
      "packageFingerprintId": 393936211,
      "gameVersionDateReleased": "2001-01-01T00:00:00Z",
      "gameVersionMappingId": 2051276,
      "gameVersionId": 7668,
      "gameId": 1,
      "isServerPack": false,
      "serverPackFileId": null,
      "gameVersionFlavor": "wow_classic"
    }
  ],
  "categories": [
    {
      "categoryId": 1019,
      "name": "Combat",
      "url": "https://www.curseforge.com/wow/addons/combat",
      "avatarUrl": "https://media.forgecdn.net/avatars/54/455/636135209724699753.png",
      "parentId": 1,
      "rootId": 1,
      "projectId": 356973,
      "avatarId": 54455,
      "gameId": 1
    },
    {
      "categoryId": 1017,
      "name": "Miscellaneous",
      "url": "https://www.curseforge.com/wow/addons/miscellaneous",
      "avatarUrl": "https://media.forgecdn.net/avatars/54/453/636135209712202362.png",
      "parentId": 1,
      "rootId": 1,
      "projectId": 356973,
      "avatarId": 54453,
      "gameId": 1
    },
    {
      "categoryId": 1017,
      "name": "Miscellaneous",
      "url": "https://www.curseforge.com/wow/addons/miscellaneous",
      "avatarUrl": "https://media.forgecdn.net/avatars/54/453/636135209712202362.png",
      "parentId": 1,
      "rootId": 1,
      "projectId": 356973,
      "avatarId": 54453,
      "gameId": 1
    }
  ],
  "status": 4,
  "primaryCategoryId": 1019,
  "categorySection": {
    "id": 1,
    "gameId": 1,
    "name": "Addons",
    "packageType": 1,
    "path": "Interface\\Addons",
    "initialInclusionPattern": "(?i)^([^/]+)[\\\\/]\\1\\.toc$",
    "extraIncludePattern": "(?i)^[^/\\\\]+[/\\\\]Bindings\\.xml$",
    "gameCategoryId": 1
  },
  "slug": "coolline-classic-updated",
  "gameVersionLatestFiles": [
    {
      "gameVersion": "1.13.3",
      "projectFileId": 2854264,
      "projectFileName": "CoolLine-8.0.008-classic.zip",
      "fileType": 1,
      "gameVersionFlavor": "wow_classic"
    },
    {
      "gameVersion": "8.2.5",
      "projectFileId": 2854263,
      "projectFileName": "CoolLine-8.0.008.zip",
      "fileType": 1,
      "gameVersionFlavor": "wow_retail"
    },
    {
      "gameVersion": "8.0.1",
      "projectFileId": 2853705,
      "projectFileName": "CoolLine-8.0.007c.zip",
      "fileType": 1,
      "gameVersionFlavor": "wow_retail"
    }
  ],
  "isFeatured": false,
  "popularityScore": 0,
  "gamePopularityRank": 999999,
  "primaryLanguage": "enUS",
  "gameSlug": "wow",
  "gameName": "World of Warcraft",
  "portalName": "www.curseforge.com",
  "dateModified": "2020-01-04T00:57:01.15Z",
  "dateCreated": "2020-01-02T22:14:29.53Z",
  "dateReleased": "2020-01-04T00:48:24.72Z",
  "isAvailable": true,
  "isExperiemental": false
}
```

**Comment by calebcartwright** [comment]
Thanks for the suggestion @LoneWanderer-GH! I'm not familiar with Curseforge at all, but based on all the info you collated and shared above this seems very doable.  

Few questions for you:
* How would users go about locating their project number? Is it common knowledge or would users of these badges on Shields need to know how to look up/locate their respective project number? 
* You mentioned `Repository name` in the issue description for one of the badges we could support. Can you provide more details on that one?
* Would badges with popularity data be of interest? It looks like there's `gamePopularityRank` and `popularityScore` in the response that could be used

**Comment by RedSparr0w** [comment]
Related issue here:
https://github.com/way2muchnoise/CurseForgeBadge/issues/15

**Comment by LoneWanderer-GH** [comment]
>     * How would users go about locating their project number? Is it common knowledge or would users of these badges on Shields need to know how to look up/locate their respective project number?

Most of the time, project owner or developper has to know project numbers since they can be used for webhooks/package api.
This is not a tricky thing to obtain see this screen of a project page:
![image](https://user-images.githubusercontent.com/19716859/72155921-82371800-33b4-11ea-8415-c6f7af08f013.png)

---

>     * You mentioned `Repository name` in the issue description for one of the badges we could support. Can you provide more details on that one?
I think RedSparr0w  answered the question.
This repo https://github.com/way2muchnoise/CurseForgeBadge has no commits on master since 31 oct. 2019. The project provides an API to build simple badges, and I guess it relies on a server hosted by repo owner. I found the shields.io API more flexible/appealing, but that's my taste.

---

>     * Would badges with popularity data be of interest? It looks like there's `gamePopularityRank` and `popularityScore` in the response that could be used
I can't tell for others, but yeah, downloads, versions supported, `gamePopularityRank` / `popularityScore` might be of interest.

---
_Side note, the curseforge api data available seems to be refreshed at a lower rate than the API used by the twitch application (project page download count and twitch app download count are accurately refreshed, by the above api reply is not (stayed at 44 for a while then jumped at 431.
Not really an issue, but worth to know if an actual badge support is provided. It may avoid lots of bug reports._

_For a better api, I could be a good idea to wireshark the Twitch app what is the app web api and if it has the same access level/techniques as https://addons-ecs.forgesvc.net/api/v2/addon/  (too bad curseforge does not provide a reliable page for this kind of matters_

**Comment by calebcartwright** [comment]
> This is not a tricky thing to obtain see this screen of a project page:

Great! We like to include some inline documentation in these types of circumstances to provide Shields users with guidance on how they can obtain the values they need for the badge parameters

> You mentioned Repository name in the issue description for one of the badges we could support. Can you provide more details on that one?
>> I think RedSparr0w answered the question.

I still do not understand what a "Curseforge repository name" badge would look like in the context of Shields. 

> Side note, the curseforge api data available seems to be refreshed at a lower rate than the API used by the twitch application (project page download count and twitch app download count are accurately refreshed, by the above api reply is not (stayed at 44 for a while then jumped at 431.
Not really an issue, but worth to know if an actual badge support is provided. It may avoid lots of bug reports.

Could simply be a caching issue on that inline badge, but worth keeping an eye on. It'd be helpful if someone with an account could do some comparisons of the API response values and whatever is shown within the actual app to see what, if any, latency there may be in the API

**Comment by NatoBoram** [comment]
It looks like the CurseForge had the time to break. I can't find a way to get a project's details.

This is the only thing I found that still works : https://bukkit.gamepedia.com/ServerMods_API

**Comment by YHDiamond** [comment]
https://api.cfwidget.com/{projectid}

I use this for all my purposes, it returns not much json that is easily parsable. I'd add it but I only know java

**Comment by NatoBoram** [comment]
I'm able to get this result with @YHDiamond's API.

[![CurseForge Downloads](https://img.shields.io/badge/dynamic/json?color=%23f16436&label=CurseForge&query=downloads.total&suffix=%20downloads&url=https%3A%2F%2Fapi.cfwidget.com%2F441128)](https://www.curseforge.com/minecraft/mc-mods/switcheroo/)

Pretty good tbh, the only problem is that CurseForge displays `1817` downloads while this API displays `downloads.total: 637`. Is there something wrong I'm doing?

**Comment by YHDiamond** [comment]
I am fairly certain the api caches download count for a while, I dont know exactly how much. Has the resource you are looking at grown significantly in the past few days?

**Comment by 1Turtle** [comment]
What is the current status of this?
I'd like to be able to have a badge for CurseForge downloads. The other alternatives for this right now don't fit to the shields badges as they use other structures and colors, so I would love to see this happening. ^^

**Comment by PyvesB** [comment]
Thanks to @Minecraftschurli's  and @SandroHc's  contributions, we now support three CurseForge badges:
* downloads: https://shields.io/badges/curse-forge-downloads
* version: https://shields.io/badges/curse-forge-version
* supported game versions: https://shields.io/badges/curse-forge-game-versions

Going to close this issue. Feel free to open a follow up issue or PRs to propose new CurseForge badges. 😉
