### ISSUE TITLE
Netlify shows failing when build cancelled due to no content update

### ISSUE THREAD

**Issue by MeStrak** [badges/shields#4525]
Are you experiencing an issue with...

- [x ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

My website is hosted on netlify. When I make any update to the repository, this triggers a deploy on Netlify.

If the update does not change the content of the website (e.g. if it's a docs update to the repository readme), netlify will cancel the deployment. When this happens the badge shows netlify as failing, but it didn't fail, it automatically cancelled the build because there was no change in my frontend code.

As I'm using mono repo this issue will happen anytime I change any documentation, or backend code without making a change to my frontend code.

:link: https://img.shields.io/netlify/484e088b-07df-469b-8ccf-69d0fae6d59d
![](https://img.shields.io/netlify/484e088b-07df-469b-8ccf-69d0fae6d59d)

:bulb: **Possible Solution**

If a Netlify build is in status cancelled, then the previous deployment is still active. Show the status of the previous deployment. I'm not certain that this is right though, and looking at Netlify's own status badge they have the same bug - the build shows as failed in this case using their badge URL:

[![Netlify Status](https://api.netlify.com/api/v1/badges/484e088b-07df-469b-8ccf-69d0fae6d59d/deploy-status)](https://app.netlify.com/sites/catkin/deploys)

**Comment by MeStrak** [comment]
Also opened a ticket with Netlify about this as I realised when writing it that it probably isn't directly a shields.io issue.

**Comment by calebcartwright** [comment]
> Also opened a ticket with Netlify about this as I realised when writing it that it probably isn't directly a shields.io issue.

I was just adding a comment along the same lines 😄 This is definitely an upstream issue with Netlify and nothing we can do about it on our end. 

I'm going to go ahead and close this for now, but feel free to re-open if the issue gets fixed on the Netlify side and there's still an issue with our badge

**Comment by MeStrak** [comment]
No worries, my bad. I'll post a message in here if I here anything back from them!

**Comment by MeStrak** [comment]
https://community.netlify.com/t/status-badge-incorrectly-shows-failing-when-deploy-is-auto-cancelled/7316
