### ISSUE TITLE
The second (numeric) half of badge crawls up as text

### ISSUE THREAD

**Issue by Tourorist** [badges/shields#454]
Hello,
Please see acemod/ACE3/pull/1410 (**[View](https://github.com/Tourorist/ACE3/blob/patch-2/README.md)**). This wasn't the case until recently. Am I correct to assume that labeling has become more strict (letter-case) as of late, or am I simply doing something wrong there?

**Comment by Tourorist** [comment]
To clarify, the badges in question are generic and are updated by hand with no templates behind them.

**Comment by Tourorist** [comment]
@espadrine, don't hit me too hard if this is in fact a repost of the #445 issue. :stuck_out_tongue::hammer:

**Comment by espadrine** [comment]
I see an uppercase V here: ![](http://img.shields.io/badge/Version-3.0.1-blue.svg?style=flat)

**Comment by espadrine** [comment]
Ah, sorry. Yes, Heroku is really slow now.

**Comment by Tourorist** [comment]
I'ill just wait for this to resolve on its own then. Thank you! :bow:

**Comment by Tourorist** [comment]
BTW, @espadrine, though it works in the URL, do you mean that `?label=` query is a more preferable way to handle the letter casing?

**Comment by espadrine** [comment]
When using `/badge/`, as far as I know, `label` is only necessary in complex cases where `-` escaping does not work. I even made `label` not necessary when the left-hand side text is empty. If it has an impact on letter casing, it's a bug.

**Comment by Tourorist** [comment]
I see, will keep that in mind.

Never mind the text links acting up, apparently [I am an idiot](https://github.com/acemod/ACE3/pull/1410#issuecomment-106288997).
