### ISSUE TITLE
PWA Shields

### ISSUE THREAD

**Issue by richardtaylordawson** [badges/shields#4560]
# Intro

I have created a new open source project called PWA Shields based on your Shields IO but specifically for PWA badges. The project is currently hosted at https://pwa-shields.com/. I think the idea behind it is there and it could really gain some traction, but I think it would be a project better suited under the badges repositories. I'd love to discuss moving this project over and having it be under the Badges umbrella. 😄 

:clipboard: **Description**

The badge is used to denote that a project is a PWA. It should show the PWA logo and some sort of indicator that it is a PWA, whether that be a checkmark, phrase, etc. 

:link: **Data**

This would just be a static badge unless you wanted to go farther into figuring out how to check if a site is a PWA or not. Maybe do it by checking if the site had a manifest.json or something like that.

:microphone: **Motivation**

I think we will start seeing more and more PWA's as they grow in popularity and become increasingly more like native applications. Because of this, I see people really wanting something like this and currently I haven't found something like it.

**Comment by calebcartwright** [comment]
hi there @richardtaylordawson 👋 

Could you elaborate more on exactly how/where/etc. you'd envision these within the Shields ecosystem? It's always great to see folks using badges to convey information, and definitely appreciate your shoutout to Shields on your site! 

However, a few a challenging items from my perspective:
1. The badges Shields provides are based on our [specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md), and although I've admittedly only had a cursory look at your badges, I'm not sure if/how well they conform to that spec
2.  In addition to the dynamic/status/etc. badges, Shields provides the capability to generate static badges (like https://img.shields.io/badge/foo-bar-orange) to let folks create their own badge. However, AFAIK we don't directly provide/market any pre-canned static badges

**Comment by richardtaylordawson** [comment]
@calebcartwright You make a very good point that the badges Shields provides are based on your specification and that you wouldn't want to compromise that because it goes against your messaging of being "consistent". My badges seem to conform to that specification except for the amount of padding around the words inside the badge. I do want to thank you for your time and consideration!

**Comment by PyvesB** [comment]
Thanks for sharing @richardtaylordawson, this seems like a nice little project! Even though they diverge slightly from the Shields styling, I like the unique feel of your badges as well. 😉
