### ISSUE TITLE
Intermittent failures of integration@node-latest build in CI

### ISSUE THREAD

**Issue by chris48s** [badges/shields#4561]
see https://github.com/badges/shields/pull/4535#issuecomment-575849981 for discussion

example build: https://circleci.com/gh/badges/shields/86544

failing test is:
> Github API provider with token pool should update the token with the final limit remaining and reset time - should update the token with the final limit remaining and reset time

**Comment by PyvesB** [comment]
I haven't seen this in a while (though maybe I've not been looking hard enough!). Shall we close this issue?

**Comment by chris48s** [comment]
Yeah just to fill in the history
- we disabled the tests https://github.com/badges/shields/pull/4616
- we dithered over a solution for a while https://github.com/badges/shields/pull/4590
- after ignoring it for a bit, the issue got fixed upstream
- we re-enabled the tests again https://github.com/badges/shields/pull/5711
- they've been stable since
