### ISSUE TITLE
Add functionality to render a specific NuGet version

### ISSUE THREAD

**Issue by StefH** [badges/shields#4581]
Currently you can generate a badge for a NuGet package like:
`![Nuget](https://img.shields.io/nuget/v/LinqKit)` which always shows the latest version:
==> ![Nuget](https://img.shields.io/nuget/v/LinqKit)

However, I would like to render a badge which shows a specific version.
Syntax could be like:
`![Nuget](https://img.shields.io/nuget/v/LinqKit?packageVersion=1.1.1.6)`

Is this possible?

**Comment by chris48s** [comment]
If you just want to render a badge which always has the same content every time, you can use the static badge:

![](https://img.shields.io/badge/nuget-v1.1.1.6-blue) - https://img.shields.io/badge/nuget-v1.1.1.6-blue
