### ISSUE TITLE
Update simple-icons to recent 2.3.0

### ISSUE THREAD

**Issue by xasx** [badges/shields#4586]
:clipboard: **Description**

The dependency to simple-icons is currently at 1.14.0.
Most recent version is 2.3.0 though, including many beautiful icons.

Can we please look into updating the dependency?

Or does this compete with #4273?

Thanks :heart_decoration:

**Comment by calebcartwright** [comment]
Hi @xasx, thanks for the question! 

> The dependency to simple-icons is currently at 1.14.0.

I don't think that's correct. If you take a look at the latest on master, you'll see that we're already bumped to 2.3.0, that particular commit just hasn't been deployed to production Shields.io yet.

https://github.com/badges/shields/blob/a8fbc5a179dde7c1ed351e680d746daebb221383/package.json#L62

And Production Shields.io is running 2.1.0 of simple-icons, not 1.14.0
https://github.com/badges/shields/compare/gh-pages...master

For example the coinbase icon was added in 2.1.0, and you'll see it's available in prod
https://img.shields.io/badge/foo-bar-orange?logo=coinbase
![](https://img.shields.io/badge/foo-bar-orange?logo=coinbase)

No fixed timeline on getting the 2.3.0 bump deployed to prod, but most likely won't be too long

**Comment by xasx** [comment]
Thank you for clarifying.
Don't know what I must have been looking at, old branch probably.

> No fixed timeline on getting the 2.3.0 bump deployed to prod, but most likely won't be too long

🤎 Like it!
