### ISSUE TITLE
Switch GitHub Workflow Status Badge to API

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4587]
There's now GitHub Actions/Workflow specific APIs that are available, and we'll probably want to switch over to use them (we're currently svg scraping since APIs weren't readily available/limited when we first rolled out support)

Details on the v3 API linked below, though we should probably see if the v4 endpoints are available first.

https://developer.github.com/v3/actions/
https://github.com/badges/shields/pull/3898#issuecomment-579006954

**Comment by calebcartwright** [comment]
One of the things that's going to be interesting with this is that the Actions API only supports specifying the desired Workflow by id or by the yaml file name where the Workflow is defined

https://developer.github.com/v3/actions/workflow_runs/#list-workflow-runs

However.. our current Workflow Status badge (which is svg scraping the native badge because the API wasn't readily available back then) is based off a third identifier, the Workflow _name_. 

On order to maintain BC for those existing badges, I see two paths forward:
1) We could keep the svg scraping class that will maintain BC for workflow-name based badges, and create a new one that leverages the API and accepts the workflow file or id 
2) We maintain BC for workflow-name param by making an extra API call ([list repository workflows](https://developer.github.com/v3/actions/workflows/#list-repository-workflows)) to extract the Workflow id, and then make the same API call.

Would there be any quota hit concerns with that second option? My sense is that we've got plenty of quota with the existing GH token pool, though I'm not sure if folks would have concerns with making multiple GH calls to render one badge

**Comment by vitr** [comment]
Have you got any updates on this? 
Please, correct me if I'm wrong, but without the switch, it's impossible to display private repo badges even on a self-hosted instance.

**Comment by simonhyll** [comment]
Ran into this issue while researching why my self hosted instance could create badges for things like commit activity but not for workflows. I assume this still isn't fixed.

What's the current issue that needs to be resolved? No one just hasn't bothered making it yet? Should I take a look at it?

> On order to maintain BC for those existing badges, I see two paths forward:

Can't you just do it as 2 queries, one for a complete list of all workflows in the repo, then match against the workflow name to get the id? Or maybe add a flag to change the behavior from workflow name to workflow id / yaml file? Personally I'd prefer specifying the yaml file since the name can result in a more awkward looking url.

**Comment by chris48s** [comment]
This is a useful bump in the context of:

- https://github.com/badges/shields/issues/8146
- https://github.com/badges/shields/pull/8475

We're looking at changing the current route anyway and switching to the yaml filename as the user supplied param anyway, so maybe that is the time to switch implementation too. I'll circle back to https://github.com/badges/shields/pull/8475 and have a look..

**Comment by chris48s** [comment]
See https://github.com/badges/shields/issues/8671 for the details of the fix for this
