### ISSUE TITLE
Suggestion: Visual Studio Gallery downloads

### ISSUE THREAD

**Issue by CKGrafico** [badges/shields#461]
I didn't find nothing similar to get template or extension downloads https://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361?SRC=Home

**Comment by espadrine** [comment]
Thanks for the suggestion!

This: https://www.visualstudio.com/en-us/integrate/get-started/rest/basics is your best bet, although it requires to have an account.

**Comment by CKGrafico** [comment]
Thanks for your reply, this link is for visual studio online API but I think that is not for Visual Studio Gallery

**Comment by paulmelnikow** [comment]
I believe this was done in #1074.
