### ISSUE TITLE
Nexus badges with custom repository don't automatically detect Nexus 3

### ISSUE THREAD

**Issue by nigredo-tori** [badges/shields#4639]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Shields created for Nexus 3 servers using the "Sonatype Nexus (repository)" UI say that the artifact is not found. Explicitly setting the `nexusVersion` parameter fixes the issue - but the parameter itself is not present in the UI.

:link: **Link to the badge**

Without `nexusVersion`: https://img.shields.io/nexus/omni/org.apache.commons/commons-lang3?server=https%3A%2F%2Fnexus.pentaho.org

With `nexusVersion`: https://img.shields.io/nexus/omni/org.apache.commons/commons-lang3?server=https%3A%2F%2Fnexus.pentaho.org&nexusVersion=3

:bulb: **Possible Solution**

Temporary workaround: manually append this to the badge's URL: `&nexusVersion=3`.

**Comment by PyvesB** [comment]
Hi @nigredo-tori, thanks for reporting. The fallback logic implemented in #4557 may no be working as expected, will look into it. 😉

**Comment by PyvesB** [comment]
From what I can tell with some further testinh, when hitting a Nexus 3 endpoint with Nexus 2 paths:
* `service/local/lucene/search` returns a 400 status code.
* `service/local/artifact/maven/resolve` returns a 404 status code.

The fallback logic only covered the first case. Handling the second one in the same way should do the trick, will submit a pull request shortly.
