### ISSUE TITLE
Nexus 3 "releases" badge searches all repositories

### ISSUE THREAD

**Issue by nigredo-tori** [badges/shields#4640]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Building a badge with the "Sonatype Nexus (releases)" UI results in a request to Nexus that doesn't restrict the repository in which the search is performed. This means that it can also return snapshot artifacts.

For example, on my self-hosted instance, badge URL like http://localhost/nexus/r/foo.bar/baz?nexusVersion=3&server=http%3A%2F%2Fnexus.example.com results in `GET /service/rest/v1/search?group=foo.bar&name=baz&sort=version`. As you can see, there is no repository parameter.

:link: **Link to the badge**

This badge returns a snapshot (timestamped) version: https://img.shields.io/nexus/r/org.pentaho.adaptive/daemon?nexusVersion=3&server=https%3A%2F%2Fnexus.pentaho.org

:bulb: **Possible Solution**

I'm not sure what can be done in the general case, and what the Nexus 2 implementation does. From the user side, the workaround is to explicitly specify the repository - however, this is complicated by #4639.

**Comment by nigredo-tori** [comment]
Looks like it should be enough to add `prerelease=false` to the request parameters.

**Comment by PyvesB** [comment]
Hello @nigredo-tori! Thanks for pointing this out! This was an oversight when I worked on  #4557, I assumed `prerelease=false` was the default. Would you like to submit a pull request? I'm happy to pick this up otherwise. 😉

**Comment by nigredo-tori** [comment]
> The documentation unhelpfully does not indicate what the default value is.

From my limited experimentation, the default is to not filter at all. So there are 3 possible states:
- `prerelease` is absent - we get both snapshots and releases;
- `prerelease=true` - we only get snapshots;
- `prerelease=false` - we only get releases.

> Would you like to submit a pull request

Sure, I'll try and do this myself today. Both the fix and the test for it should be relatively simple.

**Comment by nigredo-tori** [comment]
Done. I've spent far more time setting up the environment than actually fixing this. For some reason check-node-version failed miserably with Node/yarn installed via `Snap`, but I have no energy left to dig into it.

**Comment by PyvesB** [comment]
> From my limited experimentation, the default is to not filter at all. So there are 3 possible states:
> 
>     * `prerelease` is absent - we get both snapshots and releases;
> 
>     * `prerelease=true` - we only get snapshots;
> 
>     * `prerelease=false` - we only get releases.

Ah yes, you're probably right! Still wish this was documented, as the meaning of such a flag can be ambiguous! 😄 

> Done: #4659. I've spent far more time setting up the environment than actually fixing this. For some reason check-node-version failed miserably with Node/Yarn installed via Snap, but I have no energy left to dig into it.

Do you have a more specific error message? What is you Node.js version (`node -v`)?

**Comment by nigredo-tori** [comment]
> Do you have a more specific error message? What is you Node.js version (node -v)?

No, and I'm not eager to roll back all the changes I did to reproduce it. IIRC, `npm ci` just complained about needing Node 8 or higher - and that happened with Node 12, 10 and 8 (whatever the corresponding stable Snap channels happened to have). I tracked it down to `node_modules/check-dependency-version/bin.js --node '>=8.0'` or something like that, which printed something to the tune of
```
Command failed: yarn --version
```
, and didn't care that `yarn` was in the `PATH`, installed locally and/or globally, via NPM, etc..

**Comment by PyvesB** [comment]
Fair enough - let's not worry too much if you managed to solve it in the end.
