### ISSUE TITLE
pkgreview.dev: Average Ratings Badge

### ISSUE THREAD

**Issue by KumarAbhirup** [badges/shields#4641]
:clipboard: **Description**
Heya! I am the creator of [pkgreview.dev](https://pkgreview.dev)... Launched yesterday. [See this tweet](https://twitter.com/kumar_abhirup/status/1226549898163740673)!

[pkgreview.dev](https://pkgreview.dev) is a Ratings and Reviews website for #NPM packages where people could thank maintainers enough for their work! ⭐️⭐️⭐️

- **Which service is this badge for?** 👉 [pkgreview.dev](https://pkgreview.dev)

- **What sort of information should this badge show?**

   Example Sample Static Badge
   [![Example Badge](https://img.shields.io/badge/pkgreview.dev-%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%86%20%C2%B7%209%20reviews-%23000?style=for-the-badge&logo=npm)](https://pkgreview.dev/npm/react)

🖼 **pkgreview.dev**

![Landing Thumbnail](https://miro.medium.com/max/3000/1*XqaCZgJzV_lV1KOIS9lLYg.jpeg)

:link: **Data**

- **Is there a public API?**
  Yes.

- **Does the API requires an API key?**
  No.

- **Link to the API documentation.**
  I haven't created documentation for it yet.

  So, I will explain the API here.

  ### **API Endpoint** 🔰 
  ```
  GET https://pkgreview.dev/api/v1/:packageManager/:packageName
  ```

  > Currently, the only `packageManager` it supports is `npm`. Soon, it will support `pip`, `composer` and `docker-hub`.

  ### **Example Responses** 🔰

  #### 1
  Endpoint: `https://pkgreview.dev/api/v1/npm/@withkoji%2Fvcc`
  ```json
  {
    "name": "@withkoji/vcc",
    "type": "npm",
    "reviewsCount": 1,
    "rating": 0.6,
    "icon": "npm",
    "starString": "★★★☆☆"
  }
  ```

  #### 2
  Endpoint: `https://pkgreview.dev/api/v1/npm/react`
  ```json
  {
    "name": "react",
    "type": "npm",
    "reviewsCount": 3,
    "rating": 1,
    "icon": "npm",
    "starString": "★★★★★"
  }
  ```

  #### 3
  Endpoint: `https://pkgreview.dev/api/v1/npm/pkg-that-is-not-available`
  ```json
  {
    "error": true,
    "message": "The provided package does not exist"
  }
  ```

  ### Notes
 
  - When there are no reviews to a package, `rating` and `starString` will be `null`.
  
  - The `rating` value is a floating decimal between 0 to 1. It is the average rating score of a package. To convert it into a score out of 5, you'll have to multiply the `rating` by 5.

  - To show a badge like [![Example Badge](https://img.shields.io/badge/pkgreview.dev-%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%86%20%C2%B7%209%20reviews-%23000?style=for-the-badge&logo=npm)](https://pkgreview.dev/npm/react), you can use the `starString` value.

  - When there are yet no reviews to a package, the badge can look like this...
  [![Example Badge](https://img.shields.io/badge/pkgreview.dev-%E2%98%86%E2%98%86%E2%98%86%E2%98%86%E2%98%86%20%C2%B7%20Be%20the%20first%20to%20review-%23000?style=for-the-badge&logo=npm)](https://pkgreview.dev/npm/react)

  - The `icon` value will be the `logo` for shields.io badge. Currently, it supports `npm`... Soon it will support many more package managers.

:microphone: **Motivation**

There needed to be a way for people to thank open source maintainers enough for their work! And [pkgreview.dev](https://pkgreview.dev) allows users to do just that!

Currently, it supports only NPM. Soon it will support `pip`, `composer` and `Docker Hub`! I am aiming to make it the primary review website anyone can go to for any open-source module/package.

### Thanking shields.io in advance 🙌

**Comment by calebcartwright** [comment]
Thanks for the request/suggsetion @KumarAbhirup and all of the above details! I have a few comments and questions for you.

First up, questions:
* Thank you for confirming the API does not require a token. I'm assuming you're planning on that always being the case, as presumably this service would only be applicable for public packages on the various registries and never deal with private packages or packages that would require auth?
*  Just to confirm, you are planning on having a consistent API contract and route for all registry/package types?
    * ie will the route to get the reviews for an image from docker hub be something like `https://pkgreview.dev/api/v1/docker-hub/user/repo`/`https://pkgreview.dev/api/v1/docker-hub/user%2Frepo`

And a few comments for your awareness:
* Based on the data available via the API, there's two types of badges we could provide for this service, a `stars` badge and a `rating` badge
* One of Shields core goals is consistency in the badges we provide, so for badges like this which would fall under our `ratings` category, we'd need the defaults to be consistent with how we handle all our other ratings/reviews type badges. You can see what those look like at: https://shields.io/category/rating which has a listing of various rating and stars badges we provide. The same information is conveyed, but there would be some noticeable differences compared to the static badges you suggested in the OP.
    * The default value for the labels would be `rating` and `stars` (users have the option to override via the `?label` query param)
    * The default coloring will be set dynamically based on the actual values (overridable via `?color` query param)
    * The `stars` badge wouldn't include extra text/details on review count
    * The `rating` badge would include the details on the review count, though it would need to be in the compact representation our rating badges use.
* We don't bake any logos into the default badges we provide. We support a `logo` query parameter (via SimpleIcons) that Shields users can optionally leverage to add an icon, any icon, to their badge. https://github.com/badges/shields/blob/master/doc/logos.md

**Comment by KumarAbhirup** [comment]
Thanks for your reply @calebcartwright !

**Answers to the questions...**

1. **Thank you for confirming the API does not require a token. I'm assuming you're planning on that always being the case, as presumably, this service would only be applicable for public packages on the various registries and never deal with private packages or packages that would require auth?**
  - **Yes.** This service would only be applicable for public packages on the various registries and will never deal with private packages or packages that would require authentication.

2. **Just to confirm, you are planning on having a consistent API contract and route for all registry/package types?**
  - **Yes.**
    - For registries like docker (which require the username in the slug), the API would look like  `https://pkgreview.dev/api/v1/docker-hub/user%2Frepo`.
    - For registries like [PyPi](https://pypi.org/project/twine) and NPM, (that have plain unique slug for every module), the API would look like  `https://pkgreview.dev/api/v1/pip/repo`.

---

I took a look at [https://shields.io/category/rating](https://shields.io/category/rating) and understood the guidelines for Rating Type Badges.

The `stars` badge and the `rating` badge sounds good to me.

**So the two types of badges would look like these by default, right?**
  ![Might look like this](https://img.shields.io/spiget/rating/9089)
  ![Might look like this](https://img.shields.io/wordpress/plugin/stars/bbpress)

You can use the [pkgreview.dev](https://pkgreview.dev) API to build the badge as per your guidelines and how you see it fit. 😇

---

Thank you! Looking forward to hearing from you 🙌

**Comment by calebcartwright** [comment]
> So the two types of badges would look like these by default, right?

Exactly!

This should be really straightforward to implement, and good opportunity for anyone wishing to contribute to Shields (even first time contributors!).

We've a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if you or anyone else is interested in implementing this, and we're available here and on Discord if anyone has questions on implementation.

**Comment by KumarAbhirup** [comment]
Hi 🙌

Pull Request #4660 will handle this issue.

I have created badges. It works fine for slugs like `/npm/react`... 
But does not work fine for slugs like `/npm/@babel%2Fcore`.

To make it work, I will have to use `encodeUriComponent()` JavaScript Function. But I am not sure how it fits with shields.io routing mechanism.

Need your help here.

**Comment by chris48s** [comment]
use `pattern: ':pkgManager/:pkgSlug+'`

**Comment by KumarAbhirup** [comment]
Thank you so much @chris48s ! It worked!

Undrafted the PR for you guys to review :)

**Comment by KumarAbhirup** [comment]
#4660 

Pull Request almost done 😇

**Comment by calebcartwright** [comment]
@KumarAbhirup - The pkgreview.dev service appears to be non-functional at the moment, showing GraphQL errors for all packages

https://pkgreview.dev/npm/vue
https://pkgreview.dev/npm/react

https://pkgreview.dev/api/v1/npm/vue
```bash
$ curl -i https://pkgreview.dev/api/v1/npm/vue
HTTP/2 404 
content-type: application/json; charset=utf-8
cache-control: public, max-age=0, must-revalidate
content-length: 62
date: Fri, 13 Nov 2020 18:34:31 GMT
x-powered-by: Express
etag: W/"3e-4L73qA/si4Ol3KGDvMhT/N/isV4"
x-vercel-cache: MISS
age: 0
server: Vercel
x-vercel-id: cle1::sfo1::2pmvc-1605292470901-c6444df2c551
strict-transport-security: max-age=63072000

{"error":true,"message":"The provided package does not exist"}
```

![image](https://user-images.githubusercontent.com/13042488/99108258-b539d180-25ac-11eb-9b67-7046784c662b.png)

I've also just realized that your service doesn't appear to have an associated public repository (even one for reporting issues) nor any other contact channels, which is a bit concerning for us as we typically need some kind of method to contact the upstream providers in cases like this.

Can you please provide a status update on your service, as well as whether you have any plans to establish a contact channel for your service?

**Comment by KumarAbhirup** [comment]
Omg, thank you for notifying me!

At the moment, it is working fine again. 

Here's the associated public repository: https://github.com/iqubex-technologies/pkgreview.dev

I know that issue occurs twice-thrice times per month because the NPM API I depend on goes down on some Fridays.

Will try to make it stable enough!
