### ISSUE TITLE
Auto discovery of shippable id

### ISSUE THREAD

**Issue by RadAd** [badges/shields#4642]
Currently shield.io requires the shippable id to be used in the badge url.
ie https://img.shields.io/shippable/[id]

Shippable have recently changed their urls to use git hub details:
ie https://app.shippable.com/github/[user]/[repo]/dashboard

This dashboard shows the shippable id.

Would it be possible for shield.io to use a badge url of the form:
https://img.shields.io/shippable/github/[user]/[repo]

**Comment by calebcartwright** [comment]
Hi @RadAd thanks for reaching out. AFAICT, the Shippable REST API that Shields has to use to get the status from Shippable still requires the project id to be provided.

http://docs.shippable.com/platform/api/api-overview/#!/Runs/get_projects_projectId_branchRunStatus
api.shippable.com/projects/:projectId/branchRunStatus

Are you saying that is no longer the case, and if so can you provide a working example that shows the API supproting the `branchRunStatus` lookup with user/repo params?

**Comment by RadAd** [comment]
No it looks like the shippable api still requires the shippable id.
I was just wondering if shield.io could look up the id from the dashboard.

**Comment by calebcartwright** [comment]
> I was just wondering if shield.io could look up the id from the dashboard.

To be honest I doubt it, both for strategic and technical reasons.

We really try to avoid scenarios where Shields has to make multiple API calls in sequence to an upstream provider just to get the data needed to create the badges (for performance/latency, rate limiting, etc.)

For such a thing to even be technically possible, Shippable would have to provide an API that could be used to lookup and provide the corresponding project id for a given vcs/user/repo input. I don't see any such documented API (their entire API ecosystem is driven off keys like the project id)

**Comment by calebcartwright** [comment]
@RadAd - I'm going to close this one out given the above. Please feel free to circle back on this if things change on the Shippable end to make this possible from a technical standpoint, but it's not actionable at this time.

Thanks for the suggestion though!
