### ISSUE TITLE
Please add syntax documentation to each badge popup

### ISSUE THREAD

**Issue by kavdev** [badges/shields#466]
I've had some difficulty decoding the syntax for some of the badges. It'd be great to see some sort of syntax documentation on the "build badge" popup, possibly right below the "image" line.

Example: Travis:
syntax: `https://img.shields.io/travis/<username>/<project>.svg`

**Comment by espadrine** [comment]
The popup shows the real URL for the badge clicked on. We could put the syntax information directly on the right; it's really meant as an inline syntax documentation anyhow. In some cases, the actual example is more explanatory (knowing we must put a token isn't as helpful as knowing what the token looks like).

If you want to contribute changes in this regard, you may do so in `try.html`.

**Comment by kavdev** [comment]
Okay. I'll get started later this week.

**Comment by kavdev** [comment]
I looked at this over the weekend and found that it will take quite a bit of time (time I don't currently have). I'll comment here when I find time to work on this. For now, you can either set this to on hold or close it and I'll reopen it when I'm ready.

**Comment by paulmelnikow** [comment]
Related: #701, #777, #776

**Comment by paulmelnikow** [comment]
Closing in favor of #701.
