### ISSUE TITLE
Badge request: GitHub Sponsors

### ISSUE THREAD

**Issue by Prajwal-Koirala** [badges/shields#4683]
Hey,
Can we add one for github sponsors

Thanks.

**Comment by calebcartwright** [comment]
Hi @Prajwal-Koirala! Could you provide some additional information by responding to the below questions?

1. What sort of information should this badge show? Count of sponsors?
2. Would this be sponsors for a repo, org/user, both? (I think org sponsors are still in beta, but will be out at some point)
3. Where can the data be retrieved from/what's the API?
4. What's the use case/what value would it provide?

**Comment by Prajwal-Koirala** [comment]
1. Yes the count of sponsors
2. org/user / sponsors have been to the public for some time now https://github.com/sponsors
3. not sure
4. getting more sponsors

**Comment by calebcartwright** [comment]
> org/user / sponsors have been to the public for some time now https://github.com/sponsors

Per https://github.com/sponsors
> Note: GitHub Sponsors for organizations is currently in beta and subject to change.

I only noted the beta status because it is common for beta GitHub features to not have API availability or for the API documentation to not exists (we saw this with Actions and Packages for example).

**Comment by chris48s** [comment]
Info on sponsors is available via the v4 (GraphQL) API, but not the REST API.

https://developer.github.com/v4/object/sponsorship/

**Comment by hawkerm** [comment]
In the meantime, this creates a nice static badge:

```
https://img.shields.io/static/v1?label=Sponsor&message=%E2%9D%A4&logo=GitHub&link=<url>
```

<img src="https://img.shields.io/static/v1?label=Sponsor&message=%E2%9D%A4&logo=GitHub"/>

**Comment by patrikhuber** [comment]
A GitHub Sponsors button that we can include in our `README.md`'s and that is stylable to look like the original, would be really useful.

Original: 
![image](https://user-images.githubusercontent.com/4967343/89290185-5e893700-d650-11ea-8942-4579b2c96c2c.png)

Thinner version from https://buttons.github.io/: 
![image](https://user-images.githubusercontent.com/4967343/89290226-7660bb00-d650-11ea-9c30-3e4fc8502ad5.png)

**Comment by asarkar** [comment]
This ticket has been closed without any reference to how to actually show the requested badge.

**Comment by chris48s** [comment]
https://img.shields.io/github/sponsors/:user
e.g:
https://img.shields.io/github/sponsors/calebporzio

You can find and search examples/builder for all shields badges on [shields.io](https://shields.io/).

**Comment by warengonzaga** [comment]
I made a quick GitHub sponsor label using shields.

## Dark

[![sponsors](https://img.shields.io/badge/Sponsor-%E2%9D%A4-%23db61a2.svg?&logo=github&logoColor=white&labelColor=181717&style=flat-square)](https://github.com/sponsors/warengonzaga)

Code:

```
https://img.shields.io/badge/Sponsor-%E2%9D%A4-%23db61a2.svg?&logo=github&logoColor=white&labelColor=181717&style=flat-square
```

## White

[![sponsors](https://img.shields.io/badge/Sponsor-%E2%9D%A4-%23db61a2.svg?&logo=github&logoColor=181717&&style=flat-square&labelColor=white)](https://github.com/sponsors/warengonzaga)

Code:

```
https://img.shields.io/badge/Sponsor-%E2%9D%A4-%23db61a2.svg?&logo=github&logoColor=181717&&style=flat-square&labelColor=white
```
