### ISSUE TITLE
Badge request: Conda license

### ISSUE THREAD

**Issue by lewisacidic** [badges/shields#4684]
:clipboard: **Description**

A badge displaying the license from conda

:link: **Data**

Conda API, just like the other conda services:

URL: api.anaconda.org/package/:channel/:package

field: license

:microphone: **Motivation**

Get license information for conda-only packages.

**Comment by PyvesB** [comment]
Hello @lewisacidic, thanks for the suggestion! Would you like to submit a pull request? We've got a [nice little tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to get you started. 😉

**Comment by lewisacidic** [comment]
I've got no time for a few weeks - I'll put it on my list but it might take some time to get to it.

**Comment by mondeja** [comment]
This issue can be closed.
