### ISSUE TITLE
Common Vulnerability Scoring System (CVSS) badges

### ISSUE THREAD

**Issue by operatorequals** [badges/shields#4686]
:clipboard: **Description**
There is a thing called "*Common Vulnerability Scoring System(CVSS)*". This is a way to assign a 0 to 10 score to Security Vulnerabilities. You can find the official calculator here: https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator. It is the most popular Vulnerability Scoring System today, as most of the [CVEs](https://www.cvedetails.com/) get assigned a CVSS scored for publishment.

The Security Vulnerabilities are classified to the following categories using their CVSS score:
| Category | Minimum Score | Maximum Score | Usual Color|
| ------------- |:--: |:--:|--------:|
| Informational | 0   | 0   | Blue     |
| Low                | 0.1 | 4   | Green  |
| Medium         | 4.1 | 6.9 | Yellow |
| High               | 7  | 9    | Red    |
| Critical           | 9.1 | 10 | Purple  |

Additionally, to easily communicate all the parameters that create a CVSS rating, a string format is used as follows:
* [`AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C`](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C&version=3.1&version=3.1#)
This vulnerability has a score of CVSS3.1 `8.8` .
A badge for it would be: ![CVSS3.1-8.8](https://img.shields.io/badge/CVSS3.1-8.8-red)

* [`AV:P/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N/E:P/RL:W/RC:C`](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:P/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N/E:P/RL:W/RC:C&version=3.1#)
This vulnerability has a score of CVSS3.1 `4.9` .
A badge for it would be: ![CVSS3.1-4.9](https://img.shields.io/badge/CVSS3.1-4.9-yellow)

* [`AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P/RL:W/RC:C`](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P/RL:W/RC:C&version=3.1#)
This vulnerability has a score of CVSS3.1 `2.2` .
A badge for it would be: ![CVSS3.1-2.2](https://img.shields.io/badge/CVSS3.1-2.2-yellowgreen)

* [`AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C`](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C&version=3.1#)
This vulnerability has a score of CVSS3.1 `0` .
A badge for it would be: ![CVSS3.1-0](https://img.shields.io/badge/CVSS3.1-0-blue)

* [`AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H/E:H/RL:U/RC:C`](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H/E:H/RL:U/RC:C&version=3.1#)
This vulnerability has a score of CVSS3.1 `10` .
A badge for it would be: ![CVSS3.1-10](https://img.shields.io/badge/CVSS3.1-10-purple)

:link: **Data**

While the initial calculator exists (https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator) it probably does not support API `[citation needed]`.

Yet, there are several free projects that get strings as shown above and calculate the score:

* https://github.com/chandanbn/cvss
Standalone: https://cvssjs.github.io/cvssjs/
* https://github.com/ctxis/cvsslib
Is a Python component that can be turned into an API.

:microphone: **Motivation**

I am a Security Engineer doing inhouse security. I do occasional Penetration Tests and keep the reported vulnerabilities documented with MarkDown in a Github repo, along with all resources that were used during the PenTest (e.g. test files, PoCs, HTTP requests, etc).
In the report I include the vulnerability score as a CVSS string (explained above), and I would like a service where I could use a URL including that string and it would respond with a badge.

For example using `https://img.cvss.shields.io/?version=3.1&string=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C` would return  ![CVSS3.1-8.8](https://img.shields.io/badge/CVSS3.1-8.8-red)!

Thank you very much guys!

**Comment by operatorequals** [comment]
The issue looks resolved! I created a RunKit endpoint that evaluates CVSS strings to JSON responses and then used the `shields.io` endpoint functionality:
`https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N/E:P/RL:W/RC:C`:
![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N/E:P/RL:W/RC:C).

----
So all the badges described above are generated as below:
* ![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N/E:P/RL:W/RC:C)

* ![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:P/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:N/E:P/RL:W/RC:C)

* ![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P/RL:W/RC:C)

* ![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/E:P/RL:W/RC:C)

* ![](https://img.shields.io/endpoint?url=https://cvss3-shieldio-lwepmks9elms.runkit.sh/?vector=AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H/E:H/RL:U/RC:C)
----

**Comment by azisi** [comment]
🎖
