### ISSUE TITLE
How to use the #3443 Reddit-subscribers badge?

### ISSUE THREAD

**Issue by psprint** [badges/shields#4687]
:question: **How to use the #3443 Reddit-subscribers badge?**

The badge seems to be deployed however searching for "reddit" on the `shields.io` page doesn't find anything. How to use the badge in a README on GitHub?

**Comment by chris48s** [comment]
searching for reddit works for me:

![Screenshot at 2020-02-26 19-39-00](https://user-images.githubusercontent.com/6025893/75381456-ac935500-58d0-11ea-9e80-54296924e9ae.png)

example badge https://img.shields.io/reddit/subreddit-subscribers/drums?style=social

**Comment by psprint** [comment]
Thanks!
