### ISSUE TITLE
Add Snap CI build status support

### ISSUE THREAD

**Issue by tjrana** [badges/shields#471]
I would like to suggest that [Snap CI](https://snap-ci.com/) can also be integrated into this badges/shields project.

**Comment by espadrine** [comment]
Thanks for the suggestion!

**Comment by dmcclccam** [comment]
:+1:

**Comment by pine613** [comment]
:+1:

**Comment by kentcdodds** [comment]
Thanks @pine613! Any way we could get support for private repos as well? This would effectively turn [this line](https://github.com/pine613/shields/blob/87d20e4a86f6aec336e0938549dd97f99144bbdb/server.js#L3994)

```javascript
var url = 'https://snap-ci.com/' + userRepo + '/branch/' + branch + '/build_image.svg';
```

into this:

```javascript
var url = 'https://snap-ci.com/' + repoToken + '/build_image.svg';
```

I'm not 100% certain that I know what needs to change though...

**Comment by espadrine** [comment]
@kentcdodds Thanks for indicating this! I assume repoToken is meant to be secret, which makes testing awkward. Copying the same Snap CI code in shields under a different URL (say, `/snap-ci/private/TOKEN.svg`) ought to work?

I made a bit of a mistake during the review by not requiring `/snap-ci/ci/user/repo.svg`, but I hope it won't hurt too much in the future.

**Comment by kentcdodds** [comment]
Unfortunately `snap-ci/private/TOKEN.svg` doesn't currently work (were you saying that it would?)

**Comment by espadrine** [comment]
It doesn't, but it is a plausible Shields URL if it were to be implemented.
