### ISSUE TITLE
GitLab returning "branch not found"

### ISSUE THREAD

**Issue by HariSekhon** [badges/shields#4713]
I'm sure this was working earlier today and now it returns "branch not found":

https://img.shields.io/gitlab/pipeline/harisekhon/devops-bash-tools

https://img.shields.io/gitlab/pipeline/harisekhon/devops-bash-tools/master

I've tried capitalising to match the repo names etc but no luck... eg.

https://img.shields.io/gitlab/pipeline/HariSekhon/DevOps-Bash-tools

You can see the pipeline runs here:

https://gitlab.com/HariSekhon/DevOps-Bash-tools/pipelines

**Comment by chris48s** [comment]
Hello.
Out gitlab badge scrapes gitlab's own badge.
For your repo, this is reporting the build status as unknown: https://gitlab.com/HariSekhon/DevOps-Bash-tools/badges/master/pipeline.svg We wrap that error as "branch not found" as that's also what we usually get for a non-existent branch.
Maybe in this case, there is another issue which is causing gitlab to not report a build status for your project.

**Comment by HariSekhon** [comment]
I've figured it out, this was an issue with GitLab itself, it's own status badge was unknown after deleting and re-instantiating a branch, so must have been an internal issue.

Having just kicked it off manually in GitLab it's now detecting it in their badge and yours.

Thanks

Hari

**Comment by Chaostheorie** [comment]
This error also occurs when a commit doesn't trigger a CI build, e.g. when you have a CI that doesn't trigger on changes to README.md, and as such makes the build unknown. Is there any way to manually define the error label to display another message in case this happens?
