### ISSUE TITLE
Docker Cloud status reports failure, DockerHub reports not found, but clearly succeeding on DockerHub builds page

### ISSUE THREAD

**Issue by HariSekhon** [badges/shields#4716]
The docker cloud badge is reporting build failing:

https://img.shields.io/docker/cloud/build/harisekhon/bash-tools.svg

while the DockerHub badge doesn't even find the repo:

https://img.shields.io/docker/build/harisekhon/bash-tools.svg

but if you go to the DockerHub website you can clearly see the last build succeed:

https://hub.docker.com/r/harisekhon/bash-tools/builds

Also is the behaviour of this badge to check the last build or only the last latest tag build? Is there a way of choosing the last build status for a given tag?

**Comment by calebcartwright** [comment]
> while the DockerHub badge doesn't even find the repo:

The legacy `/docker/build/` badge is only to support repos that were created before the Docker hub merge a few years ago. `Not Found` is the expected result when attempting to use the legacy badge with non-legacy repos. See: #4663, #1400, #3140, and #4493 

> The docker cloud badge is reporting build failing:

https://img.shields.io/docker/cloud/build/harisekhon/bash-tools
![](https://img.shields.io/docker/cloud/build/harisekhon/bash-tools)

Shields uses the status provided by the Docker API. In the case of your repo, the Docker API is returning `failed`:

https://hub.docker.com/api/build/v1/source?image=harisekhon/bash-tools
```json
{
  "meta": {
    "limit": 25,
    "next": null,
    "offset": 0,
    "previous": null,
    "total_count": 1
  },
  "objects": [
    {
      "autotests": "OFF",
      "build_in_farm": true,
      "build_settings": [
        "/api/build/v1/setting/0d14d357-934f-4383-ae78-8d05ebf603d9/",
        "/api/build/v1/setting/d9502c76-dea1-4173-a154-7767855fef67/",
        "/api/build/v1/setting/f363f52a-017b-4ddc-a1ac-a442140bfcae/",
        "/api/build/v1/setting/9fd400fa-9187-4a9e-81db-f2b6df860e3e/",
        "/api/build/v1/setting/e194ddf1-fef8-4f6b-890d-a7d86cd8e29c/",
        "/api/build/v1/setting/0585ef02-8533-4da1-b2cc-9c5f5c08bd76/"
      ],
      "channel": "Stable",
      "image": "harisekhon/bash-tools",
      "owner": "HariSekhon",
      "provider": "Github",
      "repo_links": false,
      "repository": "Dockerfiles",
      "resource_uri": "/api/build/v1/source/64b19e5e-0cd5-462c-ab6e-af4d9b08c201/",
      "state": "Failed",
      "uuid": "64b19e5e-0cd5-462c-ab6e-af4d9b08c201"
    }
  ]
}
```

> Also is the behaviour of this badge to check the last build or only the last latest tag build? Is there a way of choosing the last build status for a given tag?

You'll have to check with the upstream platform on why the state is failed and what the behavior and capabilities are for the API. If there's additional parameters the upstream API accepets then we can certainly look into incorporating them within the Shields badge as well

**Comment by paulmelnikow** [comment]
If there's any more information on this, feel free to comment and/or reopen!

**Comment by calebcartwright** [comment]
@HariSekhon you may want to follow the upstream https://github.com/docker/hub-feedback/issues/1902 report of the same discrepancy between the Docker API and the site.
