### ISSUE TITLE
Cannot generate Atom.io badges

### ISSUE THREAD

**Issue by Stephn-R** [badges/shields#475]
I provided the following URL but no badges were returned:

https://atom.io/packages/sass-director

**Comment by espadrine** [comment]
See, I'm not sure what you did. I do know that https://img.shields.io/apm/dm/sass-director.svg works though.

Your being more specific would be helpful.

**Comment by Stephn-R** [comment]
Interesting, did you generate that manually? I was using the ```Suggest Badges``` option

**Comment by espadrine** [comment]
Ah, I see! Currently, badge suggestions only work for github URLs, and provide a limited number of badges. You can improve it by modifying `suggest.js`.

**Comment by espadrine** [comment]
> did you generate that manually?

I simply used what is displayed on the page. Typing "atom" on the search bar shows all badges related to it.

**Comment by Stephn-R** [comment]
Awesome! I will try and do a PR to update the suggestion tool for Atom packages :)
