### ISSUE TITLE
JitPack Downloads Service Test Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4754]
:clock11: **When did the problem start?**
~March 2nd

:camera: **Live badge**

https://img.shields.io/jitpack/dm/github/jitpack/maven-simple
![](https://img.shields.io/jitpack/dm/github/jitpack/maven-simple)

:wrench: **Is the live badge working?**
Doesn't look like it, seeing `invalid response data` error consistently

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/961

:beetle: **Stack trace**

```
1. JitpackDownloads [live] monthly (github) [ GET /dm/github/dcendents/android-maven-gradle-plugin.json ] 
  ValidationError: message mismatch: "value" with value "invalid response data" fails to match the required pattern: /^([1-9][0-9]*[kMGTPEZY]?|[1-9]\.[1-9][kMGTPEZY])\/(year|month|four weeks|week|day)$/

2. JitpackDownloads [live] unknown package (github) [ GET /dw/github/some-bogus-user/super-fake-project.json ]
  AssertionError: message mismatch: expected 'invalid response data' to equal '0/week'

3. JitpackDownloads [live] weekly (github) [ GET /dw/github/jitpack/maven-simple.json ] 
  ValidationError: message mismatch: "value" with value "invalid response data" fails to match the required pattern: /^([1-9][0-9]*[kMGTPEZY]?|[1-9]\.[1-9][kMGTPEZY])\/(year|month|four weeks|week|day)$/
```

:bulb: **Possible solution**
Not sure yet, guessing the upstream API contract has been changed and the response is missing or has renamed a field we need and have required in the schema

**Comment by calebcartwright** [comment]
Upstream issue with the API, which is oddly returning a 200 status code but with a response body that mentions a Mongo error 🤷‍♂ 

https://github.com/jitpack/jitpack.io/issues/4161

**Comment by hyeonchang** [comment]
I have a same issue.

**Comment by calebcartwright** [comment]
@hyeonchang -  unfortunately there's nothing we can do about this on the Shields, so you probably want to bump the upstream issue in the Jitpack repo

**Comment by calebcartwright** [comment]
Still no response from the upstream provider. We may need to disable the tests, and badge, at least temporarily.

**Comment by calebcartwright** [comment]
There's been no response from JitPack, and in all honesty there doesn't seem to have been much recent activity in the JitPack repo at all (no commits since Feb 23rd, lots of open issues with no response from maintainers over that time, etc.)

Accordingly, I'm going to open a PR to deprecate our JitPack Downloads badges. I'll leave the upstream issue open for a while longer, and if the JitPack API is ever back online we can re-enable these badges
