### ISSUE TITLE
Size badge shows higher size than the truth

### ISSUE THREAD

**Issue by lefetmeofefet** [badges/shields#4757]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

npm minified bundle size (min) badge shows 6.44kb, when the file size is 5.44.

:link: **Link to the badge**

https://img.shields.io/bundlephobia/min/htmel

The minified file I'm referring to:
https://github.com/lefetmeofefet/htmel/blob/master/dist/htmel.min.js

Thanks for this awesome service by the way, truly cool project :)

**Comment by chris48s** [comment]
Hi.

We don't calculate this value The bundlephobia badge reports the size from the bundlephobia API: https://bundlephobia.com/api/size?package=htmel If you think that is wrong, you could raise an issue on the bundlephobia repo: https://github.com/pastelsky/bundlephobia That said, bundlephobia is reporting the size of your entire npm package, not just one file, so we would expect the total reported bundle size to be a bit larger than just the size of that one file.

If you wanted to report just the size of one file in your GitHub repo, we do have a badge for that too:
https://img.shields.io/github/size/lefetmeofefet/htmel/dist/htmel.min.js

Thanks

**Comment by calebcartwright** [comment]
@chris48s beat me to it 😄 

https://bundlephobia.com/api/size?package=htmel
```json
{
  "assets": [
    {
      "gzip": 2515,
      "name": "main",
      "size": 6439,
      "type": "js"
    }
  ],
  "dependencyCount": 0,
  "dependencySizes": [
    {
      "approximateSize": 10812,
      "name": "htmel"
    }
  ],
  "description": "",
  "gzip": 2515,
  "hasJSModule": "./src/htmel.js",
  "hasJSNext": false,
  "hasSideEffects": true,
  "name": "htmel",
  "repository": "",
  "scoped": false,
  "size": 6439,
  "version": "1.0.3"
}
```

**Comment by lefetmeofefet** [comment]
Thanks for explaining :)
I'll be using the tag you linked
