### ISSUE TITLE
Many badges are broken, only after multiple page refresh I can see all badges correctly.

### ISSUE THREAD

**Issue by fabiocaccamo** [badges/shields#4758]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Many badges are broken, only after multiple page refresh I can see all badges correctly.
![Schermata 2020-03-11 alle 10 20 20](https://user-images.githubusercontent.com/1035294/76401305-f45eb580-6381-11ea-8a21-f1954b3cd377.png)

:link: **Link to the badge**
The screenshot is taken from this repo: https://github.com/fabiocaccamo/python-benedict  
The bug is visible on all my repositories which use **shields**, for example:

-   https://github.com/fabiocaccamo/django-admin-interface
-   https://github.com/fabiocaccamo/django-maintenance-mode
-   https://github.com/fabiocaccamo/django-colorfield
-   https://github.com/fabiocaccamo/django-treenode
-   https://github.com/fabiocaccamo/python-codicefiscale

:bulb: **Possible Solution**
I think this problem is related to cache/invalidation.

**Comment by calebcartwright** [comment]
Our infrastructure provider (OVH) where production Shields.io is hosted is having issues again, which in turn is impacting Shields.

**Comment by McLive** [comment]
I noticed the same

![image](https://user-images.githubusercontent.com/5620071/76439732-217c8980-63bd-11ea-8f51-c7ea36a49f50.png)

**Comment by fabiocaccamo** [comment]
@calebcartwright thank you for the quick feedback. 
Is it in your plans to change provider or have you any info about when this will be solved?

**Comment by PyvesB** [comment]
@paulmelnikow and I are working on a proposal for a new hosting solution. No ETA yet, but hopefully we'll be able to communicate about it soon. 😉

**Comment by apobekiaris** [comment]
maybe u can also consider a payed service, even if I use shields for my OS project happy to pay a few bucks to it. I do not think anonymous contributions is the way to go as this issue is active years now.

**Comment by ViRb3** [comment]
Can I vouch for using [Hetzner Cloud](https://www.hetzner.com/cloud)? Their services are the best value for money I have found, and their stability has caused me 0 issues over the course of years.

**Comment by paulmelnikow** [comment]
Resolved via #4929! Thanks for your patience!
