### ISSUE TITLE
Wrong "latest release" reported for sebastianbergmann/phpunit

### ISSUE THREAD

**Issue by sebastianbergmann** [badges/shields#477]
At the time of writing, `https://img.shields.io/github/release/sebastianbergmann/phpunit.svg?style=flat-square` generates an image showing `v3.7.32` as the latest version for https://github.com/sebastianbergmann/phpunit whereas the latest version is `4.7.4`.

**Comment by espadrine** [comment]
From what GitHub folks told me, https://github.com/sebastianbergmann/phpunit/releases shows manual releases and tags. https://api.github.com/repos/sebastianbergmann/phpunit/releases/latest shows only manual releases. Use https://img.shields.io/github/tag/sebastianbergmann/phpunit.svg?style=flat-square to get the tag.

**Comment by sebastianbergmann** [comment]
Ah, okay. Thanks!
