### ISSUE TITLE
pull requests since last version

### ISSUE THREAD

**Issue by diomed** [badges/shields#478]
is there any way badges could display progress of pull requests since last version of software was released, so people could see how much developing progressed?

**Comment by Stephn-R** [comment]
it might help if you can explain more and provide examples

**Comment by diomed** [comment]
ummm, i'm not sure I can explain it more than that, really.

for example, last version of program was 3.4.5
current version is 3.4.6. and it's being in development.

could there be a badge that would display number of new pull requests 
in comparison to previous version of software?

**Comment by espadrine** [comment]
Assuming you're focusing on GitHub, they would need to provide this information from their [api](https://api.github.com/). Until then, we don't have the necessary information to make that badge.

**Comment by diomed** [comment]
on this page there is a line that displays number of commits to master since *this release*
https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.4.7

can that number somehow be used?

**Comment by espadrine** [comment]
Hmm, that's very interesting. It probably means that having it in their API would be easier, since the code already exists. @diomed, I think you should reach out to GitHub to ask for support in the API.

**Comment by diomed** [comment]
Hi Kruno,

You can get that number by using the compare endpoint:

https://developer.github.com/v3/repos/commits/#compare-two-commits
I've got an answer from Github saying:

For the example that you mentioned, the URL would be:
https://api.github.com/repos/SubtitleEdit/subtitleedit/compare/3.4.7...master

The ahead_by field will contain the number you're looking for, if the head ref is ahead of the base ref:

› curl "https://api.github.com/repos/SubtitleEdit/subtitleedit/compare/3.4.7...master" | ack "ahead_by"    
  "ahead_by": 218,

**Comment by espadrine** [comment]
Nice! Thanks! Maybe something like `/github/pr-since/SubtitleEdit/subtitleedit/3.4.7.svg`?

**Comment by diomed** [comment]
sure. why not? :+1:
