### ISSUE TITLE
Badge request: Merge commits since version

### ISSUE THREAD

**Issue by rawtaz** [badges/shields#4782]
:clipboard: **Description**

For GitHub, there's a badge showing the number of commits since a given version.

In cases where new features or bug fixes are made directly onto e.g. master, with mostly one such change per commit, this makes sense.

But for projects that use merge commits to merge in PRs, where the merged branches can contain a lot of small commits that *combined* make up one relevant change (new feature, bug fix, etc), this badge doesn't provide much value.

I'm proposing a new badge, similar to the "commits since version", but more specifically "merge commits since version". It could simply be the same thing, but filtering on merge commits, which would then make for a more relevant indicator of how many real-world changes were merged into the project. That is, when a merged PR is what makes up such a relevant change.

Let me know if any of this is unclear, perhaps I'm not conveying the use case very well here.

:link: **Data**

Same data source as the "commits since version".

:microphone: **Motivation**

Being able to better get a feel for how many relevant changes there were to a project, instead of individual code changes, because the latter doesn't always indicate one new feature or bug fix - a merged branch might have ten commits all combined making up that one new feature or bug fix.

E.g. in the [restic](https://github.com/restic/restic) project there's right now around 147 changes since version v0.9.6, but only 48 merge commits. The number 48 is much more relevant than 147 when you want to convey how many changes of interest there might be in the upcoming release.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion.

Does GitHub provide an API for this?

**Comment by rawtaz** [comment]
I have no idea if GitHub provides an API for this. If they don't, it should be pretty simple to grab the date of the latest release and pick out only merge commits that are on or after that date.

**Comment by paulmelnikow** [comment]
I think that probably will require more API calls than we can do to render a single badge on the Shields server. It might be well suited to the Endpoint badge, though: https://shields.io/endpoint/

The general idea is that you can deploy your own data-fetching code on something like RunKit, and then point Shields to it, and Shields takes care of rendering and caching.

**Comment by rawtaz** [comment]
Yeah, fair enough. I will close this then as it's a wontfix thing probably :) Thanks for your time and the service in general!
