### ISSUE TITLE
NuGet package shield not working

### ISSUE THREAD

**Issue by jmezach** [badges/shields#4783]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I've recently created a new NuGet package and pushed it out to NuGet.org, but for some reason my badges still say that the NuGet package could not be found. At first I thought this was due to the fact that a stable release wasn't available yet, even though the pre-release shield also didn't show anything. But even now that I've pushed a stable release I'm still getting the same error:

:link: **Link to the badge**

https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj/ -> ![NuGet Package](https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj/)

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
Hello. The URL shouldn't have a trailing slash

* ![](https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj) - https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj or
* ![](https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj.svg) - https://img.shields.io/nuget/v/MSBuild.Sdk.SqlProj.svg

do work :)

**Comment by jmezach** [comment]
Owh, I feel so stupid now. You're absolutely right. Not sure why I thought I needed the trailing slash in the first place. But thanks for pointing it out. Its fixed now :).

**Comment by calebcartwright** [comment]
No worries @jmezach!
