### ISSUE TITLE
Badge request: POEditor

### ISSUE THREAD

**Issue by Cimbali** [badges/shields#4784]
:clipboard: **Description**

Showing translation progress per language, from the online platform l10n platform <https://poeditor.com>.

Right now, I make my own static badges for this. For example:

![Chinese: 22%](https://img.shields.io/badge/%F0%9F%87%A8%F0%9F%87%B3%20Chinese-22%25-f60)
![Chinese (TW): 22%](https://img.shields.io/badge/%F0%9F%87%B9%F0%9F%87%BC%20Chinese%20%28TW%29-22%25-f60)
![Spanish: 22%](https://img.shields.io/badge/%F0%9F%87%AA%F0%9F%87%B8%20Spanish-22%25-f60)
![Czech: 98%](https://img.shields.io/badge/%F0%9F%87%A8%F0%9F%87%BF%20Czech-98%25-1f0)
![French: 100%](https://img.shields.io/badge/%F0%9F%87%AB%F0%9F%87%B7%20French-100%25-0f0)
![German: 98%](https://img.shields.io/badge/%F0%9F%87%A9%F0%9F%87%AA%20German-98%25-1f0)
![Polish: 84%](https://img.shields.io/badge/%F0%9F%87%B5%F0%9F%87%B1%20Polish-84%25-5f0)

These contain:
- language name
- flag of country’s language (encoded utf8 symbols)
- progress as a percentage, and color-coded from red (0%) to green (100%)

:link: **Data**

The API 
- is public, 
- requires:
   - a project id
   - a (read-only) API key,
- is described at <https://poeditor.com/docs/api>, and
- works using _HTTP POST_ requests. 

For example for one of my projects, and with my public read-only API key, the request for Chinese would be:

    $ curl -s https://api.poeditor.com/v2/languages/list -d id=323337 -d api_token=7a666b44c0985d16a7b59748f488275c | jq '.result.languages[] | select(.code == "zh-CN")'
    {
      "name": "Chinese",
      "code": "zh-CN",
      "translations": 22,
      "percentage": 22,
      "updated": "2020-03-12T12:29:04+0000"
    }

The equivalent jsonpath expression is `$.result.languages[?(@.code=="zh-CN")]`.

I suppose the basic URL could be something like `/poeditor/:project-id/:language-code`.

---

The flags are of course very optional but they look nice. They are just the 2 country code letters (in the chinese example case CN) encoded as utf-8 “REGIONAL INDICATOR SYMBOL LETTER”. E.g.:

    function getUTF8Flag(countryCode) {
      const firstLetter = Character.codePointAt(countryCode, 0) - 0x41 + 0x1F1E6
      const secondLetter = Character.codePointAt(countryCode, 1) - 0x41 + 0x1F1E6
      return String(Character.toChars(firstLetter)) + String(Character.toChars(secondLetter))
    }

(0x41 represents uppercase A letter and 0x1F1E6 is REGIONAL INDICATOR SYMBOL LETTER A in the Unicode table.)

:microphone: **Motivation**

I like these badges to easily show to potential contributors what they can do to help out on FOSS projects.

**Comment by calebcartwright** [comment]
Thanks @Cimbali! The motivation/benefit and API seem straightforward enough (thanks for all the detail). 

Is the API token user/project specific, or can _any_ user's readonly token be used with the `/languages/list` API for any project?

We really try to avoid having Shields badges accept user-specific tokens as a route/query param unless it's absolutely necessary and the token can be scoped accordingly. It sounds like both of those conditions are true here, but if it's possible for Shields to create an account and use our own token (vs every user having to provide their own) that'd be preferrrable

**Comment by Cimbali** [comment]
I’ve just tried creating another account right now, and its API keys did not work to access my main account’s data (returned a 403). So it seems the public API key of the account holding the project is necessary.

**Comment by calebcartwright** [comment]
Oh well, worth a shot 😄 I'm okay with supporting this given the read-only token condition is true and we mention that in the badge doc.

This should be relatively easy to implement so adding the `good-first-issue` label. We've got a [great tutorial on adding new badges](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if you (or anyone else) is interested in working on it!

**Comment by chris48s** [comment]
think this one can actually be closed now #4812 is merged
