### ISSUE TITLE
Incorrect rendering of SVG shields in some WebKit browsers

### ISSUE THREAD

**Issue by Bob131** [badges/shields#479]
Exhibit A from ReadTheDocs:
![shield](https://cloud.githubusercontent.com/assets/4337852/8270393/99bbed4c-1821-11e5-9bc3-3f8ae896897b.png)

As I'm sure you'll agree, this is unreadable to a ridiculous degree. Almost every badge I see day-to-day renders the same way, with so few exceptions that I can only guess the ones that _are_ readable rely on generating shields internally.

I imagine the problem arises from the ordering of `path` tags in the SVG, confirmed by my own tinkering. Compare an excerpt from the original:

```
<g xmlns="http://www.w3.org/2000/svg" mask="url(#a)">
    <path fill="#555" d="M0 0h36v20H0z"/>
    <path fill="#4c1" d="M36 0h41v20H36z"/>
    <path fill="url(#b)" d="M0 0h77v20H0z"/>
</g>
```

to an edit:

```
<g xmlns="http://www.w3.org/2000/svg" mask="url(#a)">
    <path fill="url(#b)" d="M0 0h77v20H0z"/>
    <path fill="#555" d="M0 0h36v20H0z"/>
    <path fill="#4c1" d="M36 0h41v20H36z"/>
</g>
```

In my testing both render identically in Chromium, Firefox and rekonq, but only the second renders correctly in the other browsers I tested (Epiphany, Midori, dwb). My guess is it has something to do with using GNOME's built-in Adwaita Dark theme with applications that use GTK3 webkit bindings.

After experiencing this issue for a few months I've only just very quickly Googled around to get here, so here's hoping I've opened this bug report in the right place!

**Comment by espadrine** [comment]
That seems like a bug in WebKit-GTK, as the path you put first is actually partially transparent, in a way that fully respects the SVG 1.1 standard. Your patch would remove the transparent, slightly grayish gradient, which it looks like WebKit-GTK makes opaque.

Could you raise it as a bug in Epiphany (or Web as I believe it is now called)? I'm not even sure what package name it uses, and don't have it installed, so I am not a good fit to report the issue.

I don't know if there is a way to mitigate the issue without impacting the look of mainstream browsers.

**Comment by espadrine** [comment]
As an aside, could you confirm that the following badge shows up properly?

![](http://img.shields.io/badge/badge-visible-green.svg?style=flat-square)

**Comment by Bob131** [comment]
Yep, looks fine. I'll try raising it in the GNOME bugzilla for WebKit-GTK. Sorry for the misplaced ticket

**Comment by espadrine** [comment]
Thanks!

(The ticket isn't really misplaced. I'm glad to be aware of that issue.)

**Comment by SShrike** [comment]
Any updates on this issue? I'm still getting the SVG rendering bug with Gnome Web/Epiphany 3.18.3.

**Comment by espadrine** [comment]
The issue was raised on WebKit, but there doesn't seem to have been an update: https://bugs.webkit.org/show_bug.cgi?id=146217.

**Comment by SShrike** [comment]
Well that's dissapointing. Well written bug report though :+1:

**Comment by paulmelnikow** [comment]
Does this issue persist?

**Comment by Bob131** [comment]
I just quickly checked the GitHub Pages site in Epiphany and all the badges look fine. It's probably safe to close this bug now.
