### ISSUE TITLE
Grey AppVeyor "vendor: unresponsive" badges

### ISSUE THREAD

**Issue by hugovk** [badges/shields#480]
For AppVeyor builds, I'm getting grey "vendor: unresponsive" badges.

Any idea why?

For example:

https://ci.appveyor.com/project/Pythonpillow/pillow
https://img.shields.io/appveyor/ci/Pythonpillow/pillow.svg
https://img.shields.io/appveyor/ci/Pythonpillow/pillow/master.svg

Similarly:

https://ci.appveyor.com/project/hugovk/pillow
https://img.shields.io/appveyor/ci/hugovk/pillow.svg
https://img.shields.io/appveyor/ci/hugovk/pillow/master.svg

https://ci.appveyor.com/project/wiredfool/pillow
https://img.shields.io/appveyor/ci/wiredfool/pillow.svg
https://img.shields.io/appveyor/ci/wiredfool/pillow/master.svg

The example from the Shields.io homepage works:

--Update: They did work, but now they're also "vendor: unresponsive".

https://img.shields.io/appveyor/ci/gruntjs/grunt.svg
https://img.shields.io/appveyor/ci/gruntjs/grunt/master.svg

AppVeyor's own badges are working:

https://ci.appveyor.com/api/projects/status/github/hugovk/pillow
https://ci.appveyor.com/api/projects/status/github/wiredfool/pillow
https://ci.appveyor.com/api/projects/status/github/gruntjs/grunt

**Comment by espadrine** [comment]
"vendor: unresponsive" shows when the connection between the server and the data provider's server has timed out. Sometimes, the current server is slowed down by Heroku, making it more likely.

Closing as this is part of https://github.com/badges/shields/issues/445.

**Comment by hugovk** [comment]
Thanks!
