### ISSUE TITLE
badge request: Node LTS supported engines badge

### ISSUE THREAD

**Issue by regevbr** [badges/shields#4809]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

When adding a badge for node supported engines like
If only puts a green color if the package supports node 13 which is wrong in my opinion.
Node odd versions are not stable and most libraries don't bother supporting them

:link: **Link to the badge**

![node](https://img.shields.io/node/v/node-upgrade-checker)

:bulb: **Possible Solution**

We need to figure out the latest LTS version of node and not the latest release which might be a non LTS version.
This should be done here:
https://github.com/badges/shields/blob/a2c35a69c0150a7e1d9df94ab14b94d0eb3af473/services/node/node-version-color.js#L9

I found out that you can get the latest version by parsing:
https://github.com/nodejs/Release/blob/master/schedule.json
I will try to work on a quick PR later on today

**Comment by calebcartwright** [comment]
This is one of those changes to an existing badge that's a bit fuzzy in my mind as to whether or not it truly qualifies as a "breaking" change. 

Currently when folks see the green color on a badge on a lib, they know that green color tells them that Node 13 _is_ supported, but making this change would change the meaning of existing users' badges, and create the possibility of a green badge for a lib that doesn't support Node 13. 

Curious what other maintainers think, though I'm wondering if maybe we could add this as a new platform support badge (i.e. Node LTS) vs. changing the existing one

**Comment by regevbr** [comment]
@calebcartwright I'm good either way, but if we make it a new badge, we should properly document the existing one.
I think this is a breaking change, but a bug fix non the less.
Please let me know how you want to proceed and I will make the necessary changes

**Comment by calebcartwright** [comment]
> I think this is a breaking change, but a bug fix non the less.

I'd actually push back on categorizing this as a "bug". The current badge is based on all versions of Node, including odd-numbered versions and "current" regardless of the LTS cycle. That's a valid use case and is working correctly. 

However, I see value in also providing platform support badge that _is_ driven off the LTS cycle, we just don't have that (yet). 

IMO both are valid use cases and I'm a :+1: on supporting both by adding a new LTS-only badge, but I don't want to drop/break the other use case to do so.  

>  we should properly document the existing one.

Agreed, and that's super easy to do with inline badge documentation.

**Comment by regevbr** [comment]
Great I will change the pr to utilize a new badge instead. I will get it ready within 24 hours
