### ISSUE TITLE
Improve text appearance in Firefox on Windows

### ISSUE THREAD

**Issue by MacroPower** [badges/shields#4813]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

There is room to improve the badge kerning / keming.

Between "o" and "w".
![image](https://user-images.githubusercontent.com/5648814/77358082-99cd3e00-6d1f-11ea-89d7-ffd8e3846335.png)

As well as "z" and "e".
![image](https://user-images.githubusercontent.com/5648814/77358419-355eae80-6d20-11ea-9a26-d564e64b06d7.png)

:link: **Link to the badge**

This is an issue with the text on any badge with the aforementioned character combinations. (Possibly others that I have not noticed)

e.g. "Powershell", "bower"

Note that the issue does not appear on the `for-the-badge` style.

**Comment by paulmelnikow** [comment]
Hmmm, that does not look like Verdana. What OS are you on? Can you check if removing **DejaVu Sans** from the font-family list in the svg fixes it?

**Comment by MacroPower** [comment]
> Hmmm, that does not look like Verdana. What OS are you on? 

Windows 10

> Can you check if removing **DejaVu Sans** from the font-family list in the svg fixes it?

Removing that font did seem to fix it for me:

![image](https://user-images.githubusercontent.com/5648814/77372696-a44a0080-6d3c-11ea-8632-d61bd0314374.png)

**Comment by paulmelnikow** [comment]
I've never really understood why DejaVu Sans was there, especially first in the list.

**Comment by MacroPower** [comment]
I checked on MacOS today and it seems like it renders fine there.

**Comment by paulmelnikow** [comment]
I'd suggest we remove DejaVu Sans from the templates after #4756 is merged.

**Comment by paulmelnikow** [comment]
I opened #4979 to fix this. @MacroPower could you check in that PR's review app to see if it looks better now?

**Comment by FTOH** [comment]
With Verdana it looks better, but potentially it could still show up somewhere else.
With textLength: 
![Screen Shot 2020-04-30 at 16 14 59](https://user-images.githubusercontent.com/5018813/80694351-ed237080-8ac3-11ea-828e-3dcccd383c54.png)

Without
![Screen Shot 2020-04-30 at 16 15 18](https://user-images.githubusercontent.com/5018813/80694287-d11fcf00-8ac3-11ea-8cf9-230612ff4515.png)
In first case letters "c" and "d" are sticking together.

**Comment by MacroPower** [comment]
That's odd, I'm seeing the same thing on Windows @FTOH 

![image](https://user-images.githubusercontent.com/5648814/80753259-f4b23c00-8afa-11ea-9212-852075682dea.png)

Still much better than the original. But "cd" is in this label twice and the kerning is a lot different in each instance.

Per usual MacOS renders this without any issues as far as I could see.

**Comment by paulmelnikow** [comment]
Thanks for checking this out.

@FTOH is first screenshots taken from https://shields-staging-pr-4979.herokuapp.com/ and the second one is an svg you modified? Can you post the badge link, and also show a corresponding screenshot from master?

For what it's worth, there are surprisingly few kerning pairs in Verdana, at least in my copy. IIRC none of the alpha letter pairs have one. Solving this is less about kerning per se, than about computing a text width on the server which matches the text width in the front end. If we do change how the width is computed, some of that will have to be done in [anafanafo](https://github.com/metabolize/anafanafo) which builds the width lookup tables.

> That's odd, I'm seeing the same thing on Windows @FTOH

@MacroPower Not sure I understand what you mean. Could you elaborate?

**Comment by MacroPower** [comment]
@paulmelnikow Guess I was just expressing that it seems unusual that two different instances of that "cd" pair are rendered differently in the same label.

**Comment by paulmelnikow** [comment]
> @paulmelnikow Guess I was just expressing that it seems unusual that two different instances of that "cd" pair are rendered differently in the same label.

Yea, that's odd. I wonder if it's aligning letters to pixels?

**Comment by FTOH** [comment]
@paulmelnikow This is the link for the first screenshot.
https://shields-staging-pr-4979.herokuapp.com/badge/abcdefghijklmnopqrstuvwxy-339kB-blue
For the second one, I deleted textLength property in devtools.

> and also show a corresponding screenshot from master?

[img.shields.io](https://img.shields.io/badge/abcdefghijklmnopqrstuvwxy-339kB-blue)? If yes
![Screen Shot 2020-05-01 at 11 52 51](https://user-images.githubusercontent.com/5018813/80782951-a71fe880-8b67-11ea-93e7-ebcee14a9110.png)

**Comment by paulmelnikow** [comment]
It's strange, in this particular instance (abcdefghijkl...) the new one isn't looking better.

Can you confirm that it's rendering using Verdana and not one of the other fallback fonts? It looks like it is Verdana but I can't be sure.

Here what https://shields-staging-pr-4979.herokuapp.com/badge/abcdefghijklmnopqrstuvwxy-339kB-blue looks like on Mac OS:

<img width="230" alt="Screen Shot 2020-05-01 at 11 58 40 AM" src="https://user-images.githubusercontent.com/1487036/80819521-1ebf3900-8ba3-11ea-87c1-36fcc9cd5be9.png">

**Comment by chris48s** [comment]
Just as a data point, I use linux and have DejaVu Sans installed. This is what the 2 badges look like on my machine:

**img.shields.io:**
![img-shields-io](https://user-images.githubusercontent.com/6025893/80839035-4e496200-8bf2-11ea-875e-a69a116ae207.png)

**shields-staging-pr-4979**
![shields-staging-pr-4979](https://user-images.githubusercontent.com/6025893/80839039-4f7a8f00-8bf2-11ea-9087-cc38a5184391.png)

They're are very slightly different, but not by much its more noticeable if you flick between the two..

![GIFrecord_2020-05-01_212749](https://user-images.githubusercontent.com/6025893/80839207-b1d38f80-8bf2-11ea-88e9-76b7acf5f6ed.gif)


I honestly couldn't tell you if one or the other is "better"

**Comment by paulmelnikow** [comment]
Ooh, interesting, it is surprisingly close! Maybe we should leave DejaVu Sans in as a fallback, but swap it to the end of the priority list instead of the beginning.

Still not really sure how to make this look good on Windows…

**Comment by FTOH** [comment]
> Can you confirm that it's rendering using Verdana and not one of the other fallback fonts? It looks like it is Verdana but I can't be sure.

Yes on Chrome and Firefox
![image](https://user-images.githubusercontent.com/5018813/80852981-c036a100-8c1c-11ea-90c3-65487f3a0308.png)
![image](https://user-images.githubusercontent.com/5018813/80853011-dfcdc980-8c1c-11ea-82fc-87c05463446e.png)

I am opened badge on Chrome and it looks perfect. So it is Firefox specific problem..
![image](https://user-images.githubusercontent.com/5018813/80852920-19ea9b80-8c1c-11ea-89b2-41a9b166d518.png)
![image](https://user-images.githubusercontent.com/5018813/80852954-6afa8f80-8c1c-11ea-980e-e9a3dcd8ce16.png)

**Comment by paulmelnikow** [comment]
Could it be an issue with font size?

**Comment by FTOH** [comment]
I tried this script in console, the badge looks the same.
```javascript
$('text').parentNode.setAttribute('font-size', 11)
$$('text').forEach(el => {
  el.removeAttribute('transform')
  'x,y,textLength'.split(',').forEach(attr => { 
    el.setAttribute(attr, el.getAttribute(attr) / 10)
  })
})
```

Only the complete removal of the property "textLength" solves the problem, but breaks the paddings.

**Comment by paulmelnikow** [comment]
Can you tell that the effective font size and letter spacing is consistent with other browsers that don't have the problem? I really appreciate your help getting to the bottom of this!

**Comment by FTOH** [comment]
`$0.getComputedTextLength()` for Chrome returns 1549.0771484375, for Firefox: 1600
This is what they look like without the textLength attribute:
Verdana:
![image](https://user-images.githubusercontent.com/5018813/80907223-b38d7800-8d04-11ea-8f65-f056912a5a76.png)
DejaVu Sans
![image](https://user-images.githubusercontent.com/5018813/80907241-fe0ef480-8d04-11ea-8f94-69f3d2b4a346.png)

**Comment by FTOH** [comment]
I found a CSS property that fixes the error
`text-rendering: geometricprecision;`
![image](https://user-images.githubusercontent.com/5018813/80907740-0832f200-8d09-11ea-9c85-ad89754227da.png)
