### ISSUE TITLE
How to set my 'path' when hosting my own server

### ISSUE THREAD

**Issue by forp007** [badges/shields#4817]
:question: **Question**

Hi, I am hosting my own shields server,  is it possible to change the default path to be something like: http://myserver.example.com/shields. 

When doing testing,  I would like instead of 'http://localhost:3000'  my server set as http://localhost:3000/shields 

Thanks

**Comment by paulmelnikow** [comment]
There's nothing like this built in, or an easy place where this could be changed in one place. I think the easiest way to accomplish what you're asking would be to place a separate server like [nginx](https://nginx.org/en/) in front of the Node process running Shields.
