### ISSUE TITLE
Spiget downloads badge doesn't work if download refers to external site

### ISSUE THREAD

**Issue by Sytm** [badges/shields#4840]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [X] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
On [SpigotMC.org](https://spigotmc.org) resources can be either uploaded directly to their site or the download-button can redirect to an external site. In both cases, it is counted as a download and is registered on SpigotMC and Spiget. The problem is that if resources the download on an external site the response from Spiget is interpreted as invalid and the badge only shows "invalid response data".

:link: **Link to the badge**
https://img.shields.io/spiget/downloads/66647
![Spiget Downloads](https://img.shields.io/spiget/downloads/66647)

:bulb: **Possible Solution**
After a short investigation using a local instance, it turns out that the Spiget API reports a file size of `0` and an empty string as the unit if the file is not hosted on SpigotMC but rather on an external site. The problem is that for Joi an empty string is a completely missing property in the object and thus deems the response as invalid.

[Here is the line that causes the problem](https://github.com/badges/shields/blob/77a819cefe113cab8c624f8dab3863fcfe4d0f15/services/spiget/spiget-base.js#L10)

A possible solution would be to split the schema validation up, so the file related stuff would be separate, but that's not a clean solution, is it?

**Comment by PyvesB** [comment]
Hi @Sytm! Thanks for reporting this and adding all the details! We could loosen the Joi schema a bit with a `.allow('')` statement. In the size badge, we could then detect this case and display something along the lines of `size | resource hosted externally`. What do you think?

**Comment by Sytm** [comment]
> with a `.allow('')` statement.

I didn't know that this is possible, looks good to me.

> `size | resource hosted externally`

It does not really work, because for externally hosted resources the Spiget API (and probably Spigot itself) return `0` as the size, so that wouldn't be possible.

**Comment by PyvesB** [comment]
> It does not really work, because for externally hosted resources the Spiget API (and probably Spigot itself) return `0` as the size, so that wouldn't be possible.


What I meant is an explicit check in the code, for example:
```
    if (!unit) {
      return {
        message: 'resource hosted externally',
      }
    }
```

**Comment by Sytm** [comment]
> What I meant is an explicit check in the code, for example:

Ah yes, that would work of course

**Comment by PyvesB** [comment]
Would you like to submit a pull request? Help is always welcome! 😉

**Comment by Sytm** [comment]
I could try to submit one tomorrow, for today its too late for me to start something new
