### ISSUE TITLE
Service tests don't run with mocha 7

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#4842]
:beetle: **Description**

In #4841, @Sytm noticed that the Spiget service tests were not being run. I've checked this with several other services, and actually none of them are running anymore, which is confirmed by the latest daily test run on CircleCI. Tests are loaded, IcedFrisby's `skipWhen` checks for credentials are run and then the process terminates without any error message.

After a bit of digging, I managed to narrow down the culprit to #4822, bump of Mocha's version from 6.2.2 to 7.1.1. I checked things locally with older 7.0.0, it's broken there as well, so something changed in that release. The [changelog](https://github.com/mochajs/mocha/releases/tag/v7.0.0) lists a number of breaking changes, however, nothing that would impact us in this way as far as I can tell.

I've been digging around and trying various things for the past hour or so, but probably due to my lack of familiarity with the Mocha library, I've not made much progress. Any clues?

**Comment by calebcartwright** [comment]
Mocha 7 requires Node 10 (or 12 i forget) or higher doesn't it? It'd probably be best to just roll back to v6.x

**Comment by Sytm** [comment]
> Mocha 7 requires Node 10 (or 12 i forget) or higher doesn't it? It'd probably be best to just roll back to v6.x

On my local machine I have Node 13 installed and it didn't work either

**Comment by calebcartwright** [comment]
Thanks @Sytm. The Shields.io production environment is still running Node 9.x, so we don't want to have any dependencies within the Shields tree (development nor production deps) that require Node 10 or higher. As such, we need to revert back the Mocha dependency version to v6.x where the tests are indeed working. 

We can cross the Mocha v7 upgrade (and any associated changes) bridge when we get to that point.

**Comment by paulmelnikow** [comment]
When the time comes to upgrade, I would guess the problem lies somewhere near here:

https://github.com/badges/shields/blob/eb38bb756236e1739a5008ce3ea42b0b3de5f616/core/service-test-runner/cli.js#L128-L129

**Comment by PyvesB** [comment]
> Mocha 7 requires Node 10 (or 12 i forget) or higher doesn't it? It'd probably be best to just roll back to v6.x

The 7.0.0 changelog states support for Node 6.x was dropped, but as far as I can tell Node 8.x is still supported. The documentation on the mochajs.org website states that "As of v7.0.0, Mocha requires Node.js v8.0.0 or newer" and this [pull request](https://github.com/mochajs/mocha/pull/4155) on the project seems to imply that version 8.10.0 is the effectively minimum required version (at least at the time of the 7.0.0 release back in January). Based on that information, I would be inclined to say Node versions is not the problem here, though I'm happy to be proven wrong. :wink:

**Comment by calebcartwright** [comment]
> Based on that information, I would be inclined to say Node versions is not the problem here, though I'm happy to be proven wrong

Fair enough. I could've sworn I remembered seeing something but indeed seems that I'm wrong. 

Regardless, I'd still be inclined to rollback to the last working version of Mocha unless we believe we'll have this fixed in short order because to my knowledge we don't have any immediate needs for features added in v7+

**Comment by chris48s** [comment]
Whoops - my bad. Bit trigger happy on the merge button

**Comment by calebcartwright** [comment]
> Whoops - my bad. Bit trigger happy on the merge button

No worries. I don't think there's any way we could've caught this one proactively with our current setup (would've had to explicitly add service test to runs and then manually checked the logs in circle).

Anything we can feasibly do to better prevent silent failures in the future? This may be overkill but as an example, have something in the test runner ensure there are test results from execution when services were specified (i.e. `[spiget]`) and maybe even update the Dependabot config to include a `[some-service]` in those PR titles?

**Comment by chris48s** [comment]
Yeah maybe one thing we could do is essentially have a "make-sure-service-tests-run service" which always gets run regardless of what is in the [square brackets]. Even that wouldn't have failed the build for this particular case though as running the service tests under mocha 7 still exits with a zero exit code. It just doesn't select any tests to run. I'd still probably have not noticed and merged it.

**Comment by calebcartwright** [comment]
> Even that wouldn't have failed the build for this particular case though as running the service tests under mocha 7 still exits with a zero exit code

That's why I'm pondering/suggesting some kind of hook that checks something other than the exit code when we know that tests were supposed to be run (whether that's the console output or more likely checking the result from one of the reporters, like the `json` reporter). 

It may not be worth the investment, as Mocha returning a false-positive zero exit code doesn't seem to be a common or frequent problem, but there's probably some things we could check in addition to the exit code if we decide we do indeed want to ensure some tests actually ran

**Comment by paulmelnikow** [comment]
I kind of agree that a technical fix might not be worth it. It could be enough that we keep in mind, when upgrading Mocha, to pick a service test and then check that it has actually run.
