### ISSUE TITLE
How do I get the NuGet pre-release badge to show latest pre-release version?

### ISSUE THREAD

**Issue by anders9ustafsson** [badges/shields#485]
I want to use the *NuGet pre-release* badge to display the latest pre-release version of my NuGet package, but I have not been able to figure out how to do it. 

I have tried with the following markdown:

> \[!\[NuGet Pre Release](https://img.shields.io/nuget/vpre/Nuget.Core.svg)](https://www.nuget.org/packages/fo-dicom/)  

but it only displays a generic (stable release) version number: [![NuGet Pre Release](https://img.shields.io/nuget/vpre/Nuget.Core.svg)](https://www.nuget.org/packages/fo-dicom/)  

Do I need to change the URL to the NuGet package, and in that case *to what*? Or is there something wrong with the *NuGet pre-release* badge itself?

Many thanks in advance!
Anders @ Cureos

**Comment by espadrine** [comment]
```
curl 'https://www.nuget.org/api/v2/Packages%28%29?$filter=Id%20eq%20%27Nuget.Core%27%20and%20IsAbsoluteLatestVersion%20eq%20true' -H 'Accept: application/atom+json,application/json'
```

only shows v2.8.5. Are you sure you have registered a prerelease version?

Or perhaps your intention is not to show the version of Nuget.Core, but that of fo-dicom? `![](https://img.shields.io/nuget/vpre/fo-dicom.svg)`

**Comment by anders9ustafsson** [comment]
How stupid of me! I got a little confused and used the default *Nuget.Core* instead of *fo-dicom*. Many many thanks for leading me in the right direction, @espadrine !
