### ISSUE TITLE
Request time too long

### ISSUE THREAD

**Issue by IbrahimTanyalcin** [badges/shields#4880]
experiencing an issue with...

- request time of some badges

:beetle: **Description**

Request time of some badges takes too long (+10s):

https://img.shields.io/github/followers/IbrahimTanyalcin?style=social

https://img.shields.io/github/stars/IbrahimTanyalcin/LEXICON?style=social

https://img.shields.io/security-headers?color=success&style=plastic&url=https%3A%2F%2Fdeogen2.mutaframe.com%2F

:bulb: **Possible Solution**

The only solution I can think of is to cache the dataURLs on my own server and refresh once a day. Not very ideal, nor convenient right?

**Comment by IbrahimTanyalcin** [comment]
it's much better now, what's the catch ??

**Comment by calebcartwright** [comment]
Check out #4878 for more details, but the most likely culprit at this point is recurring maintenance and issues with our hosting provider

**Comment by IbrahimTanyalcin** [comment]
Allrighty, the issue seems fixed, I'm closing this.

**Comment by IbrahimTanyalcin** [comment]
Unfortunately had to reopen this issue. I ended up caching these on my own server.

**Comment by calebcartwright** [comment]
@IbrahimTanyalcin feel free to subscribe to the other linked issue in this thread, but I'm closing this one as a duplicate
