### ISSUE TITLE
Badge Request: JetBrains Plugin Rating

### ISSUE THREAD

**Issue by ChrisCarini** [badges/shields#4897]
:clipboard: **Description**

JetBrains provides an ecosystem of plugins for their IDEs. `shields` already has two badges for this ecosystem:

1. `downloads` - https://github.com/badges/shields/blob/master/services/jetbrains/jetbrains-downloads.service.js
1. `versions` - https://github.com/badges/shields/blob/master/services/jetbrains/jetbrains-version.service.js

It would be great to have another one for plugin `ratings`.

Examples:

- `rating | 4.5/5`
- `rating | ★★★★½`

:link: **Data**

The public API can be found here: `https://plugins.jetbrains.com/plugins/list?pluginId=<pluginId>`.

This is already easily accessible via [/services/jetbrains/jetbrains-base.js](https://github.com/badges/shields/blob/master/services/jetbrains/jetbrains-base.js).

:microphone: **Motivation**

It would be awesome to be able to display a shield with a JetBrains plugin rating!

**Comment by ChrisCarini** [comment]
Submitted PR #4898

**Comment by paulmelnikow** [comment]
Resolved via #4898. Thank you!

**Comment by ChrisCarini** [comment]
No problem! Glad to be able to contribute!
