### ISSUE TITLE
Badge request: Github number of files in directory filtering by type and/or extension

### ISSUE THREAD

**Issue by mondeja** [badges/shields#4899]
:clipboard: **Description**

For Github.
Include number of files inside repository directory.
Must filter by file extension and/or type. Valid types would be `file`, `dir` or without filtering (both types included).

![](https://img.shields.io/badge/files-100-brightgreen)
![](https://img.shields.io/badge/directories-45-brightgreen)

:link: **Data**

Data from [here](https://api.github.com/repos/badges/shields/contents/services) using the V3 Github API.
API key is optional.
[Endpoint documentation](https://developer.github.com/v3/repos/contents/#get-contents).

:microphone: **Motivation**
This feature will allow us to show how many services are supported currently for bages calling to [this endpoint](https://api.github.com/repos/badges/shields/contents/services) and filtering by `type="dir"`. For example:

![](https://img.shields.io/badge/services-180-brightgreen)

**Comment by KwanJunWen** [comment]
Can I tackle this issue ?

**Comment by calebcartwright** [comment]
Absolutely @KwanJunWen! We've got a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that walks through the process of creating a new badge, and you can ping us here and/or on Discord with any questions
