### ISSUE TITLE
Implement Jenkins "Open Tasks" counters

### ISSUE THREAD

**Issue by whit537** [badges/shields#49]
*Originally posted by @jhermann on the old badgr.co issue tracker.*

This would create a badge from a link like

* http://badgr.co/jenkins-ci/«scheme»/«host»/«path_parts...»/job/«jobname»/todo.png
* Example: http://badgr.co/jenkins-ci/http/huschteguzzel.de/hudson/view/jhermann/job/dput-webdav/todo.png

Note that this introduces an URL schema to support "many of the same" type of services (e.g. "Any Jenkins hosted somewhere on the web").

Badge would look like “[TODO][hi# / norm# / lo#]” (2nd field color green/yellow/red, depending on the TODO counter classes being >0), from these API calls:

* first, call «joburl»/tasks [example](http://huschteguzzel.de/hudson/view/jhermann/job/dput-webdav/tasks)
* tack on `api/json` to the redirect `Location` you get (urljoin) [example](http://huschteguzzel.de/hudson/view/jhermann/job/dput-webdav/63/tasksResult/api/json)
* decode JSON, render counters into image

If that works, things could be extended with …/build.png (build status), …/build_no.png (build #), and so on (there's a lot of data in the API).

**Comment by kyrias** [comment]
(This issue should be closed since it was implemented in #213)

**Comment by jhermann** [comment]
Well, in part, since the Jenkins plumbing is there, but more badge types could be added beyond 's(tatus)' and 't(ests)'. The question is how many people would use them…

**Comment by kyrias** [comment]
Ah, good point. It feels like it might be easier to close it as it is, and then if someone wants others they could open a more specific request.

**Comment by espadrine** [comment]
I believe we can close it ☺ If more features get PRed, the more the merrier…
