### ISSUE TITLE
github release with no stable includes beta releases without include_preleleases

### ISSUE THREAD

**Issue by othercorey** [badges/shields#4900]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: 

When a github repo has no stable release, the github release badge will include pre-release beta releases without setting `include_prereleases`. However, release candidate (RC) releases are properly ignored.

You end up with a badge that only shows the last beta release instead of no releases.

All the beta and RC releases on github are marked pre-release.

:link:

https://img.shields.io/github/v/release/cakephp/twig-view?sort=semver&style=flat-square

:bulb:

I assume that the badge should be 'no releases found' when `include_prereleases` is missing.

If the latest pre-release is supposed to show when there are no stable releases, then the badge should include RC releases.

**Comment by chris48s** [comment]
If there is no latest stable semver release, the intent is we should fall back to the latest pre-release here, which should be `1.0.0-RC1` for this repo.
I've opened PR #4901 with one proposed solution.

**Comment by chris48s** [comment]
I'm going to close this as fixed now that https://github.com/badges/shields/pull/4901 is merged and deployed, but its difficult to explicitly verify this particular example as the project now has a stable release anyway :)

**Comment by othercorey** [comment]
Thanks! We ended up going from RC to stable pretty quickly, but will be nice to have for next project!
