### ISSUE TITLE
Nexus Repository Version Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#4903]
:clock11: **When did the problem start?**
~24th March 

:camera: **Live badge**

https://img.shields.io/nexus/proxy-public-3rd-party-release/com.fasterxml.jackson.core/jackson-databind?server=https%3A%2F%2Fnexus.pentaho.org&nexusVersion=3
![](https://img.shields.io/nexus/proxy-public-3rd-party-release/com.fasterxml.jackson.core/jackson-databind?server=https%3A%2F%2Fnexus.pentaho.org&nexusVersion=3)

:wrench: **Is the live badge working?**
Yes

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/1036

:beetle: **Stack trace**

```
Nexus [live] Nexus 3 - repository version [ GET /proxy-public-3rd-party-release/com.fasterxml.jackson.core/jackson-databind.json?server=https://nexus.pentaho.org&nexusVersion=3 ]
  ValidationError: message mismatch: "value" with value "v2.11.0.rc1" fails to match the required pattern: /^v\d+(\.\d+)*([-+~].*)?$/
```

:bulb: **Possible solution**
Looks like it just needs a tweak on the schema used for test validation

**Comment by PyvesB** [comment]
I wrote this ~extremely reliable~ test, happy to pick this issue up. 😄
