### ISSUE TITLE
Shippable Badge branch is returning wrong status

### ISSUE THREAD

**Issue by HariSekhon** [badges/shields#4908]
The Shippable badge with branch is returning the wrong status.

eg.

https://img.shields.io/shippable/5e52c63645c70f0007ff5152/master?label=Shippable

returns failing:

<img width="465" alt="Screenshot 2020-04-15 at 11 53 32" src="https://user-images.githubusercontent.com/2211051/79329482-ca178f00-7f0f-11ea-8a26-cede03b36e43.png">

 but Shippable's own page shows their own badge is green:

https://app.shippable.com/github/HariSekhon/Nagios-Plugins/dashboard/badges

<img width="1655" alt="Screenshot 2020-04-15 at 11 54 38" src="https://user-images.githubusercontent.com/2211051/79329551-ea474e00-7f0f-11ea-8063-36d551bd1f78.png">

and the jobs page shows the latest master build is green:

https://app.shippable.com/github/HariSekhon/Nagios-Plugins/dashboard/jobs

<img width="2459" alt="Screenshot 2020-04-15 at 11 58 44" src="https://user-images.githubusercontent.com/2211051/79329905-7f4a4700-7f10-11ea-93ab-108ddb517a5e.png">

I've tried querying the builds API endpoint using a script I have on my GitHub but it's now failing to allow permissions to the build API endpoint so I've raised https://github.com/Shippable/support/issues/5068.

Shippable's status page says everything is operational including the API: http://status.shippable.com/

If this was an issue with the API similar to what I am currrently having trouble querying, then I'd expect the Shields badge to show status UNKNOWN or something similar?

If Shields is getting through to the API and returning Failed, then the question is whether this is Shippable returning the wrong status, which I cannot check right now, or whether this is a bug in shields returning the status for the other failed branch instead as shown in the last screenshot above?

**Comment by chris48s** [comment]
Hello.

For the shippable badges we call the `projects/<project_id>/branchRunStatus` endpoint e.g:
https://api.shippable.com/projects/5e52c63645c70f0007ff5152/branchRunStatus

Then we use the `statusCode` field to generate the badge according to the definitions at http://docs.shippable.com/ci/build_status/

If I call https://api.shippable.com/projects/5e52c63645c70f0007ff5152/branchRunStatus the status for this project is `80`, which corresponds to `failed`.

**Comment by paulmelnikow** [comment]
Thanks for the report @HariSekhon. If there's any new information feel free to reopen!
