### ISSUE TITLE
Upgrade to Review Apps v2

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4909]
I saw this notification in the Heroku console today:

<img width="390" alt="Screen Shot 2020-04-15 at 11 21 57 AM" src="https://user-images.githubusercontent.com/1487036/79355185-570c1980-7f0b-11ea-9cd8-ee39220a7de2.png">

https://devcenter.heroku.com/articles/github-integration-review-apps#changes

Shall we turn it on?

**Comment by chris48s** [comment]
Do any of these changes help us?

https://devcenter.heroku.com/articles/github-integration-review-apps#feature-changes

I think the only one I have any opinion on is

> The app names generated by review apps are no longer predictable

..which is going to be a mild annoyance.

**Comment by paulmelnikow** [comment]
Besides the unpredictable names, I think these two are relevant:

- inherited configuration is specified in app.json or in the Pipeline’s configuration variables.

- We use the token of the user who links the Pipeline to Github for creating Review Apps.

**Comment by chris48s** [comment]
I'm unclear what either of those change for us.

With config, at the moment, review apps share a common set of env vars. Presumably that would continue to be the case.

On the second one, presumably we'd continue to use the token associated with https://github.com/shields-cd , or does that men we have to go back to using a token associated with one of our personal accounts?

**Comment by paulmelnikow** [comment]
> With config, at the moment, review apps share a common set of env vars. Presumably that would continue to be the case.

Yes, I agree. Although it sounds like they will need to be configured on the pipeline instead of on the parent app.

> On the second one, presumably we'd continue to use the token associated with https://github.com/shields-cd , or does that men we have to go back to using a token associated with one of our personal accounts?

I think we can still use the shields-cd account. It might not be a change for us.

**Comment by chris48s** [comment]
Neither of those things are an improvement though. They're just things we might have to change in order to continue as we are, right?

**Comment by paulmelnikow** [comment]
Yes, that's right.

**Comment by chris48s** [comment]
I don't have really strong opinions on it, but in this particular case, since the new version offers us no improvements and removes one mildly useful feature, it seems like the winning strategy is actually to stick to the version we're on while its still available.

If heroku deprecate/drop support or upgrading adds something we want, then its worth changing it.

**Comment by paulmelnikow** [comment]
Sounds good. Let's leave it alone until we get forced onto the new platform. A couple things might break then, not sure, but we could address it when it happens (unless someone wants to deal with it proactively).

**Comment by paulmelnikow** [comment]
I'm using Review Apps v2 in another project and noticed today that you can opt into predictable app names:

<img width="410" alt="Screen Shot 2020-12-03 at 11 28 21 AM" src="https://user-images.githubusercontent.com/1487036/101058081-c1d19a00-355a-11eb-8538-99aded36e1dd.png">

**Comment by chris48s** [comment]
we might as well migrate it when we have a chance then
