### ISSUE TITLE
Shields returning 503

### ISSUE THREAD

**Issue by cdown** [badges/shields#491]
All shields appear to be returning 503 now, but the static part of the website is working.

```
% curl -sD - https://img.shields.io/myget/yolodev/dt/FSharpSupport.svg
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Server: Cowboy
Date: Wed, 08 Jul 2015 20:50:27 GMT
Content-Length: 484
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache, no-store

<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by stephen-hill** [comment]
Still seeing this message.

**Comment by steelbrain** [comment]
Yep, been an hour.

**Comment by espadrine** [comment]
Thanks for pointing it out. It should be better now.

**Comment by steelbrain** [comment]
Thanks :clap:

**Comment by zckrs** [comment]
I have always the same error :confused:

**Comment by lebedov** [comment]
Also seeing 503 as of the present time.

**Comment by lebedov** [comment]
Shields showing up successfully now.

**Comment by Krinkle** [comment]
Seems to be broken again.

https://img.shields.io/npm/v/es5-shim.svg?style=flat
> Application Error

**Comment by cdown** [comment]
This is happening again.

What's with the recent unrelability?

**Comment by espadrine** [comment]
@cdown Heroku. We're switching: https://github.com/badges/shields/issues/459

**Comment by cdown** [comment]
@espadrine :+1:

**Comment by jamescostian** [comment]
Down again :disappointed:

**Comment by espadrine** [comment]
@jamescostian It must have been a one-off error; there was no server failure then.

**Comment by ZevEisenberg** [comment]
Here, I'll embed an image in this post so when it's failing, you can tell: ![http://img.shields.io/travis/Raizlabs/BonMot.svg?style=flat](https://github.com/badges/shields/issues/491)

Currently failing for me on that URL:

![screen shot 2015-07-24 at 11 14 43 am](https://cloud.githubusercontent.com/assets/464574/8877775/35aa189a-31f5-11e5-97a8-8d5a5d2fd4fb.png)

**Comment by ezekg** [comment]
Been pretty unreliable the last couple weeks. Anything we can do to help out?

**Comment by espadrine** [comment]
@ezekg You're quite right, but I have plans! I *think* I've set up everything needed to switch servers: #459. I'll try to operate the switch this week-end, because we have less hits on the week-end.
Then, I'll try to set up DNS round-robin between multiple servers.
