### ISSUE TITLE
Add badge for Packagist stars (favers)

### ISSUE THREAD

**Issue by pixelbrackets** [badges/shields#4912]
:clipboard: **Description**

Feature Idea: Add a badge to show stars given on Packagist. Like `packagist stars | 19124` (see Rating section for other examples).

:link: **Data**

Packagist API: Docs https://packagist.org/apidoc - Endpoint `https://packagist.org/packages/<USER>/<PACKAGE>.json`, 

Example page: https://packagist.org/packages/guzzlehttp/guzzle → Stars are shown on the right box

Example API request: https://packagist.org/packages/guzzlehttp/guzzle.json → see `favers`fields

:microphone: **Motivation**

Add a link to package ratings instead of downloads. Since downloads are used to indicate the usefullness of a package… but this is not the case. A package with many stars may be much better than a package with a huge download count.

**Comment by PyvesB** [comment]
Hello @pixelbrackets , thanks for the suggestion! Would you like to contribute a pull request? We've got a [nice tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to help you get started. :wink:

**Comment by pixelbrackets** [comment]
Hey Hey, you are right, the tutorial is a nice starter indeed. I duplicated the downloads service and adapted it according to the code walktrough, ran the tests and finished my first node commit just now.

**Comment by PyvesB** [comment]
Brilliant, thanks for the contribution! Myself or one of the maintainers will pick up the review! 👍
