### ISSUE TITLE
Support for hosted GitLab

### ISSUE THREAD

**Issue by rokpu-wish** [badges/shields#4923]
:clipboard: **Description**

It would be great if there were support for passing in credentials to access hosted Gitlab solutions. It can be something similar to how users can override Github's information for private and hosted solutions.

Something like the following:
GITLAB_URL (yml: public.services.gitlab.baseUri)
GL_TOKEN (yml: private.gl_token)

GL_CLIENT_ID (yml: private.ghl_client_id)
GL_CLIENT_SECRET (yml: private.gl_client_secret)

**Comment by paulmelnikow** [comment]
Hi! Is this request related to the existing GitLab badge? That badge doesn't use the API, rather it scrapes GitLab's pipeline status badge. In a typical private GitLab, how does auth work on that badge URL? Is it possible to make an authenticated request?

**Comment by paulmelnikow** [comment]
> Is this request related to the existing GitLab badge?

Hi @rokpu-wish, could you clarify if this request is about the existing GitLab badge?

**Comment by paulmelnikow** [comment]
Feel free to respond at some point and we can reopen this!
