### ISSUE TITLE
Problem with Cocoapods badge

### ISSUE THREAD

**Issue by najeeb-ur-rehman** [badges/shields#4928]
I tried to create the shields but it is always saying "Invalid response data".
But I query pod trunk using this URL (trunk.cocoapods.org/api/v1/pods/TespoTextField/specs/latest)
and its giving the correct data. So where to go ?

**Comment by paulmelnikow** [comment]
Hi! Could you include some more details, like a link to the badge?

**Comment by chris48s** [comment]
It will be this issue again: https://github.com/badges/shields/issues/4688
You can work around it by declaring a licence, but we should also fix the schema so that the version/platform badges still work if the project doesn't specify any licence.

**Comment by paulmelnikow** [comment]
Thanks. Let's track in #4688.
