### ISSUE TITLE
Badge request: landscape.io

### ISSUE THREAD

**Issue by ad-m** [badges/shields#493]
Hello,

I am would like ask about landscape.io badge. It support FOSS project.

Greetings,

**Comment by espadrine** [comment]
Thanks for the suggestion!

I couldn't find a conventional API, but it might be possible to reverse-engineer it; they seem to have a program: https://landscape.canonical.com/static/doc/user-guide/ch09.html.

Having a link to an existing badge would equally be useful.

**Comment by ad-m** [comment]
Here is it:
https://landscape.io/github/watchdogpolska/poradnia/master/badges

Wysłano z urządzenia mobilnego.
21 lip 2015 9:48 AM "Thaddee Tyl" <notifications@github.com> napisał(a):

**Comment by glaslos** [comment]
Format is https://landscape.io/github/{org|user}/{repo}/{branch}/landscape.png

**Comment by espadrine** [comment]
Thanks for the information!

I'm getting Heroku's "Application Error" currently. "Try again later"?

**Comment by glaslos** [comment]
@espadrine https://twitter.com/landscapeio/status/640621993432367104

**Comment by ebertti** [comment]
I can find landscape on shields. Where is?

**Comment by bittner** [comment]
Any plans to implement a Landscape.io badge?

**Comment by peterjc** [comment]
The problems in late 2016 were addressed, Landscape is up and running. Can this be reopened please?

**Comment by paulmelnikow** [comment]
Hmm, https://landscape.io returns a page that says "Back soon…", so not sure this is actionable.

**Comment by paulmelnikow** [comment]
Does the service still exist?

**Comment by peterjc** [comment]
I honestly haven’t check recently, but from my linked comment it was unreliable three months back. Perhaps it will return...

**Comment by paulmelnikow** [comment]
Okay, let's reopen it if it comes back and folks still want this.
