### ISSUE TITLE
Coveralls Private Repo Badge

### ISSUE THREAD

**Issue by jondunning** [badges/shields#495]
Hi,  

Is it possible to use shields.io with a private coveralls repo?

I can do it for a private CircleCI repo where i pass in a token;
https://img.shields.io/circleci/token/YOURTOKEN/project/BrightFlair/PHP.Gt/master.svg

I don't see the same options for Coveralls. Can this be added? Can I assist in anyway?

<img width="802" alt="screen shot 2015-07-21 at 09 34 36" src="https://cloud.githubusercontent.com/assets/6370173/8796295/a2087e1c-2f8b-11e5-8f28-1d5b47061dfa.png">

Thanks,

Jon

**Comment by espadrine** [comment]
It may be possible; I know too little about Coveralls to know for sure. The
first step would definitely be to contact Coveralls and ask them for a
public API, which I believe they don't have (we perform scraping currently
for them).

Providing a URL to a Coveralls private badge would help, if that exists.

**Comment by jondunning** [comment]
An example badge link for a coveralls private repo below;

https://coveralls.io/repos/fortx/hardware/badge.svg?branch=master&service=github&t=e6AYxR

They do have an [API](https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference) but it doesn't seem to have an way of checking the status of a repo.

Your thoughts?

**Comment by espadrine** [comment]
I'd say you should contact them!

**Comment by nhodges** [comment]
@jondunning any update?

**Comment by d3ming** [comment]
@jondunning what's the `&t=e6AYxR` param for in the coveralls link you posted?  I'm trying to get the badge to work on my private repo too and just getting 'unknown'.  

Also, are there any documentation on how to get this to work at all?

**Comment by iwasrobbed** [comment]
@d3ming As a future FYI for others, the badge will show up on the repo page on Coveralls.io as soon as the initial code coverage files are pushed there. It won't show up before there's any coverage data. Then there will be a link with the proper tokens and whatnot in it

**Comment by jrodbeta** [comment]
@d3ming It looks like coveralls creates a token specifically for the badge.  You can see your full URL in the readme badge portion of the repo stats column for your repo in coveralls.
