### ISSUE TITLE
Discord badge not functioning

### ISSUE THREAD

**Issue by AugusDogus** [badges/shields#4957]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The discord badge is not working correctly.

:link: https://img.shields.io/discord/450716251099234306

I can verify that I have enabled the server widget as per instructed and the server id is correct.

![image](https://user-images.githubusercontent.com/9794679/80364685-f1ddef80-884b-11ea-85a2-d710bdb12d09.png)

**Comment by AugusDogus** [comment]
This looks like it will be solved with PR #4956.

**Comment by dodocodes** [comment]
![image](https://user-images.githubusercontent.com/63036448/80377755-ab978900-8869-11ea-9bd9-1043c5fdd7e4.png)

Seeing the same here.

**Comment by paulmelnikow** [comment]
Hi, thanks for the report. This came in via Discord last night. As an experiment, we've rolled over from our legacy servers to Heroku. A few of our services whitelist our IP address to avoid rate limiting reasons, and we forgot about those. This was patched this morning in #4956, but will need a long-term fix.

**Comment by calebcartwright** [comment]
@paulmelnikow I was thinking about closing this one (since it's Discord specific and the badges are working again) and creating a new issue to cover IP Whitelisting in the Heroku environment more holistically. 

Thoughts/concerns with that?

**Comment by paulmelnikow** [comment]
Sounds good to me 👍 Thank you!

**Comment by AugusDogus** [comment]
That sounds appropriate @calebcartwright. Thank you!
