### ISSUE TITLE
Speed up Heroku deploys

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4961]
A couple things are making the Heroku deploys slow unnecessarily:

1. We're installing Cypress unnecessarily.
2. We're not pruning dev dependencies because we've got NPM_CONFIG_PRODUCTION set to false on the staging app. The build logs say dev dependencies aren't being pruned because of that. I think we can remove this setting, and dev dependencies will still be there for the frontend build, and then removed.

We don't technically need a copy of the frontend build on the production badge server, but we do for staging and review apps, and it's simpler I think to keep it there for all.

**Comment by paulmelnikow** [comment]
`CYPRESS_INSTALL_BINARY=0` is effectively being set in `app.json` for the review apps. I've added it to the staging and production apps, which should take care of that part.

**Comment by paulmelnikow** [comment]
I've removed `NPM_CONFIG_PRODUCTION=false` on staging. The slug went from 124 MB to 39 MB. Looks like Cypress is not being installed, either. Sweet!

**Comment by calebcartwright** [comment]
> The slug went from 124 MB to 39 MB. Looks like Cypress is not being installed, either. Sweet!

Any noticeable improvement on the deploy time?

**Comment by paulmelnikow** [comment]
🤷 I'm not sure if you can really see how long the deploy is taking.
