### ISSUE TITLE
Matrix badges seem slow

### ISSUE THREAD

**Issue by julienw** [badges/shields#4963]
This is a follow-up to #4878.

I'd like to add the following badge to my github README:
https://img.shields.io/matrix/profiler:mozilla.org?server_fqdn=matrix.org&label=matrix

But this takes 8s at the moment, and as a result github's proxy times out on it.

I'm opening a new issue to track this as requested in #4878 :-)

Thanks for your great work!

**Comment by julienw** [comment]
I've been told that using directly Mozilla's matrix instance works better: eg https://img.shields.io/matrix/profiler:mozilla.org?server_fqdn=mozilla.modular.im&label=matrix

**Comment by julienw** [comment]
I think the issue was because of not using the "home" server for the channel.
sorry for the disturbance!

**Comment by paulmelnikow** [comment]
Hi! Would it be worth adding something to the documentation about this? Contributions welcome :)

**Comment by julienw** [comment]
I feel like the documentation already talks about using the right server, but it wasn't working for me because I didn't use the right one and that's why I ended up using matrix.org...
