### ISSUE TITLE
Show combined download counts for multiple packages?

### ISSUE THREAD

**Issue by FezVrasta** [badges/shields#4964]
:question: **Question**

Hi, is there any way to have a badge to display the combined downloads count of multiple npm packages? We changed package name and we'd like to show the total downloads rather than having two different badges (or worse, just one)

**Comment by paulmelnikow** [comment]
Hi! Thanks for the question. Something similar was requested for NuGet a few years back in #204 and [our suggested workaround](https://github.com/badges/shields/issues/204#issuecomment-456266743) is to use the Endpoint badge, which is a way you can write your own badge data fetching logic, emit JSON, and then use Shields for formatting, rendering, and caching. It's hard to bound the number of requests or request time for a badge like this, so I think [the Endpoint badge](https://shields.io/endpoint) is probably a good way to accomplish this.

**Comment by FezVrasta** [comment]
I see, I'll try with the RunKit + Endpoint badge solution then, thanks!

**Comment by FezVrasta** [comment]
For anyone interested, I published an endpoint here:

https://runkit.io/fezvrasta/combined-npm-downloads/1.0.0

You can use it as follows:

https://img.shields.io/endpoint?style=for-the-badge&url=https://runkit.io/fezvrasta/combined-npm-downloads/1.0.0?packages=popper.js,@popperjs/core

![demo](https://img.shields.io/endpoint?style=for-the-badge&url=https://runkit.io/fezvrasta/combined-npm-downloads/1.0.0?packages=popper.js,@popperjs/core)

Docs:

https://runkit.io/fezvrasta/combined-npm-downloads/1.0.0?packages=<pkg1>,<pkg2>,<pkg3>&period=<period>

- `packages` is a comma separated list of npm packages;
- `period` is `last-week`, `last-month`, `last-day`, and all the other standard npm periods;

**Comment by thetarnav** [comment]
@FezVrasta 
I just dug this thread up, and your solution seems to work the best.
But is seems to be a little bit broke currently. Adding `&period=last-week` at the end of the URL changes the download amount but the caption remains the same — "123K/MONTH".
Would you mind sharing the runkit source code, or correcting the message text?

**Comment by thetarnav** [comment]
Thank you :)
This is my take on it then: https://runkit.com/thetarnav/combined-weekly-npm-downloads
