### ISSUE TITLE
Last updated batch

### ISSUE THREAD

**Issue by maximousblk** [badges/shields#4967]
:clipboard: **Description**
A badge that would show the time since the last comit to a GitHub project

- This will be mainly for GitHub, but if other platforms are supported, that would only be better.

- This badge shows time paseed since the last comit.

Example:

`Last updated | 2 days ago`

Or

![Last Updated](https://img.shields.io/badge/Last%20Updated-2%20days%20ago-brightgreen?style=for-the-badge&logo=github)

:link: **Data**

- data can be obtained from the [GitHub API](https://developer.github.com/)

:microphone: **Motivation**

It can be used to show the last update on a GitHub pages project or anywhere you want people to acknowledge the time since last update.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the message. We've got a badge for this:

<img width="815" alt="Screen Shot 2020-04-28 at 5 01 34 PM" src="https://user-images.githubusercontent.com/1487036/80537382-f7cdf080-8971-11ea-84da-47c940e04525.png">

**Comment by maximousblk** [comment]
Thanks for letting me know.

If it's possible, it would be awesome to get this working for individual files.

Other than that, this issue is better closed.

**Comment by paulmelnikow** [comment]
Two follow-up questions:

1. Do you know if it's possible to get a file's last update date from the API?
2. What is the specific use case you have in mind? Can you link to the project?

Thanks!

**Comment by maximousblk** [comment]
I don't really know how shields.io works but you might wanna look at [this](https://stackoverflow.com/questions/50194241/)

Possible use cases was the blog one and for awesome lists.

It was just an idea that popped into my mind, I tried to search for it (using the key words: last updated) but couldn't find it, so I opened this issue.

Now that I think about it, there isn't a use case for this... yet.

**Comment by paulmelnikow** [comment]
Okay, want to open a new issue when you have a use case?

Also something to keep in mind is that you can use [the Endpoint badge](https://shields.io/endpoint/) to do something custom. [RunKit Endpoints](https://runkit.com/docs/endpoint) are an easy way to host them.

**Comment by maximousblk** [comment]
Thanks for your help. I really like what you guys are doing.

Would it be better if just reopened this issue?

**Comment by paulmelnikow** [comment]
Either way. A new issue is fine. Just fill out the template all the way with the info from here that's relevant. Thanks!
