### ISSUE TITLE
No service-response-time metrics for Heroku

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#4970]
Grafana is not displaying any [service-response-time](https://metrics.shields.io/d/service-response-time/service-response-time) metrics for the new Heroku servers (either staging or production environments).

**Comment by platan** [comment]
I moved charts from https://metrics.shields.io/d/service-response-time/service-response-time?orgId=1 to https://metrics.shields.io/d/aESRBSjmz/services ([info](https://github.com/badges/shields/pull/3948#issuecomment-529235077)). I will remove service-response-time dashboard.
