### ISSUE TITLE
upgrade prettier

### ISSUE THREAD

**Issue by chris48s** [badges/shields#4972]
:clipboard: **Description**

- review open PRs: anything big we want to try and get over the line first? (also a good time to do a  bit of a clean out)
- can we adopt some settings that mean we don't have to change _every single file_ in the codebase to upgrade it?

**Comment by calebcartwright** [comment]
Posting past discussion on the prettier upgrade here for reference

https://github.com/badges/shields/pull/4836#issuecomment-605339072
