### ISSUE TITLE
upgrade to node 12 in production

### ISSUE THREAD

**Issue by chris48s** [badges/shields#4973]
:clipboard: **Description**

We're currently on 10, but should now be no reason we can't adopt 12 soon.

**Comment by paulmelnikow** [comment]
12 makes sense to me.

Looks like we're testing on Node 8 and node@latest currently, so probably we should update that to @12 and @latest.

**Comment by calebcartwright** [comment]
Should we consider running on all LTS versions to cover the self-hosting cases, or should we just update the docs accordingly?

**Comment by chris48s** [comment]
We probably _should_, but there's also a tradeoff of build minutes/number of simultaneous builds, which is why I went with 10 and 12 in https://github.com/badges/shields/pull/4992 .
We could do [the nvm dance](https://github.com/badges/shields/blob/7385739a43abea17f304e05e2f568add9180c22a/.circleci/config.yml#L89-L99) in more places..

**Comment by paulmelnikow** [comment]
I think our call in #3404 for self-hosting is that we'll support current plus possibly whatever has been current in the past three months. (Right now I think that would be 12 + 14.)

> For **self-hosting** it would be great if we could support only the ["current" version](https://github.com/nodejs/Release). Or maybe – to give self-hosting users time to upgrade – any version that has been "current" within the last three months. Or maybe – to reduce the frequency of those upgrades – the latest even-numbered version.

**Comment by chris48s** [comment]
Lets get our own house in shape first then track that schedule moving forwards :)

**Comment by paulmelnikow** [comment]
Does this mean we can use static fields in the service classes?! 🤯

**Comment by chris48s** [comment]
oh yeah - there are probably some things like static/private class properties that are now unlocked
