### ISSUE TITLE
'NaN' in 'width' attribute inside rect element of anchor in generated svg

### ISSUE THREAD

**Issue by GuillauG** [badges/shields#4989]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Static Endpoint Combined with `<object>` tag fails : `NaN` in width element

:link: **Link to the badge**

```
<object data="https://img.shields.io/static/v1?labelColor=green&label=LABEL&message=MY%20MESSAGE&color=orange&style=flat-square&link=https%3a%2f%2fmy.domain.com"></object>
```

This code doesn't work but used to work.
It returns an invalid NaN in the `width` field of the rect element (child of anchor) of the generated svg

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="130" height="20">

<g shape-rendering="crispEdges">
<rect width="45" height="20" fill="#97ca00"/>
<rect x="45" width="85" height="20" fill="#fe7d37"/>
</g>

<g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110">
<text x="235" y="140" transform="scale(.1)" textLength="350">LABEL</text>
<text x="865" y="140" transform="scale(.1)" textLength="750">MY MESSAGE</text>
</g>

<a target="_blank" xlink:href="https://my.domain.com">
<rect width="NaN" height="20" fill="rgba(0,0,0,0)"/>
</a>

</svg>
```

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
Thanks for picking this up - there's a PR open for this issue at https://github.com/badges/shields/pull/4991
