### ISSUE TITLE
Does svg format cache itself?

### ISSUE THREAD

**Issue by jimcoven** [badges/shields#501]
Not exactly sure how it works, but does anyone know if the SVG format caches itself? if i have 10 requests for a badge [build | success] in a single page, will it make 10 separate requests. Thanks!

**Comment by kyrias** [comment]
Uhm, a file format doesn't "cache itself", servers do..

**Comment by jimcoven** [comment]
My bad, I didn't mean it that way. But the badges seem to be cached as though they are external documents. Just wanted to confirmed that its not retrieved on a per call basis. Thanks!

**Comment by espadrine** [comment]
There are a few layers of cache. Direct badges (the `/badge/` ones) ask the browsers to remember them. Other badges have a short-lived cache of 5s, plus a heuristic that guarantees a 75% accuracy.

Please don't make a bot that calls the server in a tight loop, and please don't fill the cache.

**Comment by jimcoven** [comment]
Not headed there. I was thinking whether I needed to create a local cache of those which are accessed more frequently rather than to poll a live server. But since caching is already handled, I guess its not necessary.
