### ISSUE TITLE
Badge for forkability.io

### ISSUE THREAD

**Issue by M-Zuber** [badges/shields#502]
I would like to enable [forkability](https://github.com/basicallydan/forkability) to offer a badge.

What do I need to add to the code so that we can make it work?

Initially I would go with yes/no, but in the future I would like to be able to offer a score of x passed/case tested

**Comment by espadrine** [comment]
Thanks for that suggestion!

It might be as simple as fetching a `/badge/` from shields.io. The question is, what should it show?

**Comment by M-Zuber** [comment]
It depends on the projects owner: cc @basicallydan 

The project gives an indication of how 'forkable' a repo is.
So an initial badge should probably give a pass/fail option based on an api call
Later we can give a more quantitative status.
There is a `Github Pages` site, but as far as I know, there is no web api that can be called to receive the information needed.
Basically I am looking for some guidance on how to set up such an api that can be used in  conjunction with `shields.io`

**Comment by basicallydan** [comment]
@M-Zuber This is a great idea! Looks like we'll have to set up some kinda web service for forkability for this.

So, @espadrine the way that Forkability works is like this:

* It's a commonjs JavaScript module which fetches GitHub repo information and runs it through a number of linters to measure the "Forkability" that @M-Zuber mentioned.
* It works in NodeJS, so it'd be fairly easy to run wrap it in a JSON API.
* It also works [in the browser](https://basicallydan.github.io/forkability) which is how it is currently used by most people.

I saw mention of the "Shields standard", and in the README saw mention of opening an issue to get a service supported which I guess @M-Zuber also saw.

Do we need to set up a web API for it, or is there any chance that Shields would be capable of scraping data from a JavaScript page? If it's the former, then @M-Zuber and I have some thinking to do! Maybe Heroku or NodeJitsu for now?

**Comment by espadrine** [comment]
@basicallydan You can simply generate this image when the result is overall positive, and provide copy-pasteable links in markdown, html, what have you, with a link to the forkability result: ![](http://img.shields.io/badge/forkable-yes-brightgreen.svg) (`http://img.shields.io/badge/forkable-yes-brightgreen.svg` / `http://img.shields.io/badge/forkable-no-red.svg`)

**Comment by basicallydan** [comment]
Ah great! @espadrine we can just give them that specific link, you're OK with that?

If so, @M-Zuber we don't really need an web API necessarily. Though in the ideal situation, I guess the badge would be an automated generation based on the most recent forkability result.

For now though, we should definitely add this to the results page and hopefully improve the "virality" of the service and get some more contributors. Thanks!

**Comment by espadrine** [comment]
Sure!

**Comment by M-Zuber** [comment]
Back from vacation :smile: 
Thank you @espadrine 
So, seeing that we are going with the static route (at least for now) this seems like a very nice solution.

One item is we will just have to hope that people don't use the badge without running the service, so maybe it shouldn't be added to the list on `shields.io`?

**Comment by espadrine** [comment]
I suppose a simple warning on your website suffices?

**Comment by M-Zuber** [comment]
that call has to be made by @basicallydan

**Comment by basicallydan** [comment]
@espadrine Yep, sounds good enough to me. I'll do it later though... getting late here in Seoul, and I'm getting tired! However, badges now are displayed after running Forkability, as long as your repo passes ;)

https://basicallydan.github.io/forkability/?u=badges&r=shields

**Comment by basicallydan** [comment]
Another thing is that the badge won't be shown to web app users unless they pass, so that should reduce the amount of people using it when they shouldn't.

Anyway I bucked up and added a little note: https://github.com/basicallydan/forkability/blob/master/README.md#badges

I'll leave it up to you, @espadrine, to decide whether to add it or not :)

**Comment by M-Zuber** [comment]
I am willing to make a PR to have it added, but I could not find clear instructions on how (mainly to which files changes need to be made)

**Comment by basicallydan** [comment]
CC @espadrine

**Comment by espadrine** [comment]
@M-Zuber I'm not sure exactly what you mean by "have it added". How should things work?

**Comment by M-Zuber** [comment]
I was referring to have it listed on shields.io

**Comment by espadrine** [comment]
@M-Zuber Hmm, that would be in `try.html` (with installation instructions in INSTALL.md for testing purposes), but the badge wouldn't be accurate when edited…

**Comment by M-Zuber** [comment]
In what way would the badge not be accurate? That people would use it without qualifying?

**Comment by espadrine** [comment]
The badges under Miscellaneous on shields.io have all been generated according to the parameters given in the URL. In that sense, they are all accurate (their data correspond to their parameters). If I recall correctly, the forkability badge is not able to retrieve the information that would presumably relate to the repository specified in the img.shields.io URL parameters.

**Comment by M-Zuber** [comment]
This is the badge markdown generated after running `forkability` on itself:
```
[![This is a forkable respository](https://img.shields.io/badge/forkable-yes-brightgreen.svg)](https://basicallydan.github.io/forkability/?u=basicallydan&r=forkability&l=nodejs)</li>
```
Unless the repo information used in the example (which would be forkability itself) is changed that link is still valid, as it is simply a link to the service with parameters already set.

Does this then solve your worry?

**Comment by espadrine** [comment]
I am not worried. I am simply unsure what you would like to see happen when one clicks on the badge and the popup opens. A patch would be unambiguous, though.

**Comment by M-Zuber** [comment]
cc @basicallydan what do you say?
Should we have the badge listed for exposure - but it's not clear how to build the link behind it. Or should we evangelize and hope people check us out after seeing the badge on another repo?

**Comment by basicallydan** [comment]
@M-Zuber I say we go with the latter.

If we try and get people to use it on shields.io at the moment then it'd be really confusing, since the URL isn't based on the name of your repo.

It'd be rad if it was based on the URL though. Maybe we should try turning this into an HTTP service.

@espadrine So if we did go with a service, the URL would serve up the shields.io badge right? And then you could set up a route on shields.io to point to our URL with the given params?

Until then, @M-Zuber I say we just evangelise. I'm gonna try and fix up my biggest repo (https://github.com/basicallydan/interfake) and hopefully that'll help a little. As soon as I get a few free moments. Still on the road...

**Comment by M-Zuber** [comment]
Great! I'll close this then. 
Enjoy the rest of your trip :smile:

**Comment by basicallydan** [comment]
@M-Zuber Thanks dude!
