### ISSUE TITLE
Support for styleci?

### ISSUE THREAD

**Issue by marktopper** [badges/shields#503]
Would it be possible to gain support for a [StyleCI](https://styleci.io/) with the status?

**Comment by espadrine** [comment]
Thanks for the suggestion!

I couldn't find a public API. Do you know if there is one?

**Comment by JayBizzle** [comment]
You can already use shields for StyleCI...

https://styleci.io/repos/{your_styleci_repo_id}/shield

You can append settings, see this commit https://github.com/StyleCI/StyleCI/commit/437517db00a9a0734cfe432aaa5eb0fc673d75bf

/ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
> I couldn't find a public API. Do you know if there is one?

We don't have a public API yet.

**Comment by GrahamCampbell** [comment]
> You can append settings, see this commit StyleCI/StyleCI@437517d

That commit doesn't actually change any behaviour of our shields. We've supported all 3 styles long before that commit. That commit is just a refactor commit with zero change to behaviour.

**Comment by GrahamCampbell** [comment]
The only thing it changes is that we're totally independent of shields.io because shields.io provides bad caching headers to github was caching old badges.

**Comment by GrahamCampbell** [comment]
This issue should probably be closed.

**Comment by marktopper** [comment]
I know this: https://styleci.io/api/repos/39950862?branch=master

Else if you need a API which will just return the color and the status message let me know and I will make it.

**Comment by GrahamCampbell** [comment]
> Else if you need a API which will just return the color and the status message let me know and I will make it.

That's not going to be possible I'm afraid. Our production service is more complex than our open source repo.

**Comment by GrahamCampbell** [comment]
I am planning to write an API at somepoint, but I want it to be good, so it'll take time.

**Comment by espadrine** [comment]
> shields.io provides bad caching

I'd call it “aggressive caching” ☺ Although it only lasts seconds.

**Comment by GrahamCampbell** [comment]
> Although it only lasts seconds.

We had problems because the caching was 12 hours.

**Comment by espadrine** [comment]
@GrahamCampbell That's weird. Could you tell me what headers were bad?

**Comment by GrahamCampbell** [comment]
The Cache-Control header.

**Comment by espadrine** [comment]
@GrahamCampbell Hmm, here's what the current code does:

```js
// Cache management - no cache, so it won't be cached by GitHub's CDN.
ask.res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
```

What is your suggested fix?

**Comment by GrahamCampbell** [comment]
That's not the header I was getting.

**Comment by GrahamCampbell** [comment]
This is the actual header: https://github.com/badges/shields/blob/master/server.js#L4130.

**Comment by espadrine** [comment]
@GrahamCampbell That is only for static badges (`/badge/` ones). Since they don't change, browsers can cache them.

I assumed you were talking about badges that show constantly updated information? Or do you mean that this header appears on non-static badges?

**Comment by GrahamCampbell** [comment]
I redirect users to the "static" badges.

**Comment by GrahamCampbell** [comment]
Then github caches that and ignores the fact the redirect said don't cache.

**Comment by espadrine** [comment]
@GrahamCampbell Ah, I see. What I could do is send the no-cache header if I receive a special header… What header could you send while redirecting to Shields?

**Comment by GrahamCampbell** [comment]
We're no longer using shields because of that issue. Sorry.

**Comment by espadrine** [comment]
@GrahamCampbell Fair enough. I'll still try to fix it. I'll keep the Cache-Control header I receive. Is that a good idea?

**Comment by Bilge** [comment]
So... what happened to StyleCI?

**Comment by GrahamCampbell** [comment]
We have our own badge system.

**Comment by Bilge** [comment]
@GrahamCampbell That's cute, but its style is inconsistent with every other major badge system out there including Shields and PUGX and every other major independent vendor including Travis and Coveralls. Are you just too hipster to conform to the style that absolutely everyone else is using?

**Comment by GrahamCampbell** [comment]
The StyleCI is not inconsistent. We downloaded the badges from shields.io...

**Comment by GrahamCampbell** [comment]
If you want the crappy default style that shields.io has, just apply `?style=flat` to the StyleCI URLs.

**Comment by GrahamCampbell** [comment]
Alternatively, just add `?style=flat-square` to your shields badges to make them look as nice as StyleCI's default badges.

**Comment by Bilge** [comment]
Don't you think it would be a good idea to have the different styles mentioned on the site somewhere? Also, I don't understand why you're opposed to Shields supporting badges for your service. No other major CI service provider seems to have the same issue.

**Comment by GrahamCampbell** [comment]
> I don't understand why you're opposed to Shields supporting badges for your service

I'm not. I'm just not going to contribute it. It's also going to be hard to add support because we don't yet have a public API so shields has no way to know what the status for each of our repos is.

**Comment by GrahamCampbell** [comment]
> I know this: https://styleci.io/api/repos/39950862?branch=master

That `/api` stuff isn't intended for external usage. That's just used by our own website and we'd happily make breaking changes to that without notice.

I'd recommend thus holding off until we launch api.styleci.io.

**Comment by GrahamCampbell** [comment]
Also, you'll have trouble calling `/api` endpoints atm for private repos to provide badges.

**Comment by peter-gribanov** [comment]
when will support?

**Comment by GrahamCampbell** [comment]
Once StyleCI has a fully featured public HTTP API. https://api.styleci.io/ doesn't support getting the status of analyses yet.

**Comment by paulmelnikow** [comment]
So, it sounds like the current status is: we're waiting for a public API.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed

**Comment by Bilge** [comment]
Since StyleCI actually does have (still undocumented?) flat styles there doesn't seem to be a lot of point in adding support to Shields anyway.

**Comment by paulmelnikow** [comment]
If it's helpful to be in the Shields supported list, another option, is to pull the text from the SVG badge using the parsing code in Shields.

**Comment by Bilge** [comment]
What do you mean? You're going to parse the image's text to rebuild a badge that looks identical to the image you parsed the text out of? How is that in any way helpful?

**Comment by paulmelnikow** [comment]
Might or might not be helpful. As I suggested, it might be helpful for the service to be listed in the Shields supported list. Shields might also support more formatting options.

**Comment by Bilge** [comment]
If all you want to do is make a list you may as well just link to the original implementation.
