### ISSUE TITLE
Badge request: Unsplash

### ISSUE THREAD

**Issue by Davoodeh** [badges/shields#5036]
:clipboard: **Description**

How about a badge for Unsplash?
Somethings like ![Unsplash Wallpaper](https://img.shields.io/badge/Wallpaper-Happy%20Face%20By%20Lidya%20Nada-lightgrey?style=flat-square&logo=unsplash&link=https://unsplash.com/photos/tXz6g8JYYoI/)
But with a working link?

:link: **Data**

An API key is required to automate the whole process...
But if the team can get their hands on one a lot of things can be done with it... For example, make it guess the name and title just by giving the link? (I'm pretty sure Unsplash/dev will welcome such an idea and give free API access or something to the team for this)

http://api.unsplash.com/

:microphone: **Motivation**

It can be useful for ricing communities...
They can share the wallpapers right of the bat in the README with one of these badges from Unsplash, which is one of the main sources of HQ wallpapers of ricing communities.

Pardon me for my poor English

**Comment by calebcartwright** [comment]
hi @MYDavoodeh :wave: thanks for the request. 

I'll admit I'm not familiar with the Unsplash service, but it's really unclear to me from the issue description what sort of badges these would be/what dynamic data would need to be retrieved. 

At the moment this seems to me like a standard use case where folks can use our static badge generator (just like you did in the issue description) to create and embed badges to their liking.

IMO we'd need more information in order for this to be potentially actionable.

**Comment by MYDavoodeh** [comment]
I'm afraid my English knowledge doesn't give me much of domain to describe the matter clearly.
Let me try with an example.
The dynamic badge can be potentially something like: https://img.shields.io/unsplash/tXz6g8JYYoI
where the input is the id of the image.
and the output will be automatically generated via shields.io. Having the title, artist name and clickable link all automatically set via the id given above. turning it into this: ![Unsplash Wallpaper](https://img.shields.io/badge/Wallpaper-Happy%20Face%20By%20Lidya%20Nada-lightgrey?style=flat-square&logo=unsplash&link=https://unsplash.com/photos/tXz6g8JYYoI/)

I hope this make the suggestion clear.

Thanks for the answer

**Comment by PyvesB** [comment]
As per our guidelines:
> Shields.io hosts integrations for services which are primarily used by developers or which are widely used by developers.

I don't feel that Unsplash really fits into that category.

Additionally, similarly to what was discussed in #5729, it's in my opinion overkill to kill an API to get something static like an image title. Handcrafting the badge, like you've done above, really feels like the simplest solution here.

**Comment by calebcartwright** [comment]
> Unless I've missed something, I would personally be keen to close this issue

Agreed

**Comment by ahmedshahriar** [comment]
> @Davoodeh 

Here is a workaround if anyone is looking for -

[![](https://img.shields.io/badge/Social%20Preview-%20brown%20eggs%20on%20white%20tray%20by%20Tengyart-lightgrey?style=flat-square&logo=Unsplash)](https://unsplash.com/photos/uh6msP8Md_E)

`Shields` supports [simple-icons](https://simpleicons.org)
code -
```
[![](https://img.shields.io/badge/Social%20Preview-%20brown%20eggs%20on%20white%20tray%20by%20Tengyart-lightgrey?style=flat-square&logo=Unsplash)](https://unsplash.com/photos/uh6msP8Md_E)
```
