### ISSUE TITLE
Path builder should percent-encode route components

### ISSUE THREAD

**Issue by webknjaz** [badges/shields#5042]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Generated links may contain unencoded spaces which breaks links in certain markups (like RST).

:link: **Link to the badge**

https://img.shields.io/github/workflow/status/ansible/pylibssh/%F0%9F%8F%97%20%F0%9F%93%A6%20&%20test%20&%20publish/devel

The problem was that shields.io generated RST with a link that had spaces. So it was `https://img.shields.io/github/workflow/status/ansible/pylibssh/🏗 📦 & test & publish/devel?label=GitHub%20Actions%20%5Btests%5D&logo=github` instead of `https://img.shields.io/github/workflow/status/ansible/pylibssh/🏗%20📦%20&%20test%20&%20publish/devel?label=GitHub%20Actions%20%5Btests%5D&logo=github`

:bulb: **Possible Solution**

I've fixed this for my repo with https://github.com/ansible/pylibssh/commit/66a1a2bb5a5b4e674cd3c2a2e9e0aafefe48292f but I think shields.io should generate proper links, at least having spaces %-encoded.

**Comment by webknjaz** [comment]
(label should be `bug`: #5043)

**Comment by paulmelnikow** [comment]
Hi! It sounds like this is a problem in the frontend, yea? Could you clarify the steps to reproduce? i.e. what need to be filled into which fields?

Are you clicking Copy Badge URL at the end or are you using the RsT option? If the RsT, does the problem still manifest if you use Copy Badge URL?

**Comment by webknjaz** [comment]
https://shields.io/category/build -> `GitHub Workflow Status (branch)` -> enter `ansible`/`pylibssh`/`🏗 📦 & test & publish`/`devel` -> `Copy Badge URL` (or `Copy reStructuredText`) -> `https://img.shields.io/github/workflow/status/ansible/pylibssh/🏗 📦 & test & publish/devel` which is wrong because most of the parsers will recognize only the part before the first space as a URL.

The copied URL should be `https://img.shields.io/github/workflow/status/ansible/pylibssh/🏗%20📦%20&%20test%20&%20publish/devel` instead.

**Comment by paulmelnikow** [comment]
Thanks for the steps! It's super helpful to have a detailed report.

It seems to me this may be a bug or feature request in path-to-regexp… though it might also be something we have to deal with ourselves.

The fix might be as simple as URL-encoding the path segments, though that will URL-encode everything, including some characters which I think in practice work just fine in URLs.

**Comment by PaulaBarszcz** [comment]
It seems to me that it works correctly now.

When I paste:
`https://img.shields.io/github/workflow/status/ansible/pylibssh/🏗 📦 & test & publish/devel?label=GitHub%20Actions%20%5Btests%5D&logo=github`
it redirects me to:
https://img.shields.io/github/workflow/status/ansible/pylibssh/%F0%9F%8F%97%20%F0%9F%93%A6%20&%20test%20&%20publish/devel?label=GitHub%20Actions%20%5Btests%5D&logo=github

<img width="1174" alt="Zrzut ekranu 2022-11-20 o 12 08 17" src="https://user-images.githubusercontent.com/31891675/202898822-452edbe5-fe7c-4da3-b161-4573be157291.png">

@chris48s  - can this be closed? :)

**Comment by chris48s** [comment]
Just to clarify, the bug being reported here was in the code for generating markdown/rst etc via the frontend.

Your browser may auto-correct `https://example.com/a b` to `https://example.com/a%20b` but that's a side-issue and not really a fix.

The bug being reported here was fixed in https://github.com/badges/shields/pull/5263 though.
