### ISSUE TITLE
Dockercloud builds are failing

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#5054]
I've noticed on commits to master such as https://github.com/badges/shields/commit/9ac2b41206a7f5894bbe2f5a2bd6fcff496f41e4 that the Dockercloud builds are failing.

I noticed we need to bump the Node version in the Docker image. That might fix it.

**Comment by chris48s** [comment]
I didn't actually intend to auto-close this issue in the PR without checking first, but looking at https://hub.docker.com/r/shieldsio/shields/builds I think that did the job
