### ISSUE TITLE
Add AppVeyor logo

### ISSUE THREAD

**Issue by techtonik** [badges/shields#507]
AppVeyor is for Windows, Travis is for Linux, but badges look the same - see https://github.com/gratipay/aspen-python for example. It will help if the badge was looking like official badge - with a logo - http://www.appveyor.com/docs/status-badges

**Comment by espadrine** [comment]
Shields does supports inserting arbitrary logos through a currently undocumented way, see https://github.com/badges/shields/issues/337 for more.

Since they already offer those badges, which conform to the Shields look, you might as well use them!

Otherwise, here's the logo:

```
  <g transform="matrix(0.045,0,0,0.045,0,1.0227272)">
    <path fill="#ccc" d="M242 48c86,0 155,69 155,154 0,86 -69,155 -155,155 -85,0 -154,-69 -154,-155 0,-85 69,-154 154,-154zm38 184c-17,22 -48,26 -69,9 -21,-16 -24,-47 -7,-69 18,-21 49,-25 70,-9 21,17 24,48 6,69zm-82 101l59 -57c-22,5 -45,1 -63,-14 -21,-16 -30,-43 -27,-68l-53 58c0,0 -7,-13 -9,-37l93 -73c28,-20 66,-21 93,0 30,24 36,68 14,101l-68 97c-10,0 -30,-3 -39,-7z"/>
  </g>
```

**Comment by techtonik** [comment]
The logo looks like just a plain gray circle - is it intended? http://jsfiddle.net/GNm8W/2151/

**Comment by espadrine** [comment]
Fair point. What a glorious circle it is, though! Here is a less aggressively nuked version:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="106" height="20" style="fill-rule:evenodd">
  <g transform="matrix(0.045,0,0,0.045,0,1.0227272)">
    <path fill="#ccc" d="M242 48c86,0 155,69 155,154 0,86 -69,155 -155,155 -85,0 -154,-69 -154,-155 0,-85 69,-154 154,-154zm38 184c-17,22 -48,26 -69,9 -21,-16 -24,-47 -7,-69 18,-21 49,-25 70,-9 21,17 24,48 6,69zm-82 101l59 -57c-22,5 -45,1 -63,-14 -21,-16 -30,-43 -27,-68l-53 58c0,0 -7,-13 -9,-37l93 -73c28,-20 66,-21 93,0 30,24 36,68 14,101l-68 97c-10,0 -30,-3 -39,-7z"/>
  </g>
</svg>
```

**Comment by techtonik** [comment]
Rendered logo on black background - http://jsfiddle.net/GNm8W/2156/

So, looks like it just needed to hack http://img.shields.io/gratipay/Shields.svg?style=social&label=Donate for AppVeyour.

**Comment by espadrine** [comment]
If you base64 the SVG logo, you can insert it through `?logo=`. Alternatively, you can add it to the project, in which case the logo can go in `logo/`. It would be appreciated if you'd contact AppVeyour before doing that, though.

**Comment by techtonik** [comment]
@espadrine isn't there a danger of XSS? I heard SVG can contain scripts?

**Comment by techtonik** [comment]
I'd better add the logo to the project. Sent a request for permission. Let's wait for reply. Speaking of logos, should they be accompanied by their asset licence / usage terms? I remember I've seen some documents about the usage of GitHub logos.

**Comment by espadrine** [comment]
@techtonik Standards force browsers to treat SVGs from an `<img>` (or `<image>`) tag to behave like an image. JS is blocked, as is any type of interactivity.

As for license etc., that is something I would like to know.

**Comment by techtonik** [comment]
Got official green light on using the logo for badges. =)

> Hi Anatoly,
>
> Absolutely, you can use our logo for build status badge! Thanks for your support!
>
> Let me know if you need any hi-res images in some format.

**Comment by techtonik** [comment]
As for licenses, I think that having exclusive permission is fine.

**Comment by techtonik** [comment]
It might need some optimizations as described in https://gist.github.com/mbostock/3094619 and https://jakearchibald.github.io/svgomg/

**Comment by espadrine** [comment]
Nice! Funnily enough, our twitter logo has a few bytes less.

**Comment by techtonik** [comment]
Optimized AppVeyor logo in #513. @FeodorFitsner you may want to fetch it back to save some resources.

**Comment by FeodorFitsner** [comment]
Thanks!

**Comment by techtonik** [comment]
So, now that #513 is merged, the task is to take http://img.shields.io/gratipay/Shields.svg?style=social&label=Donate and modify it to produce build button with logo.. Not sure about when I will be able to do that.. Need to switch from open source activities to money making for a while.

**Comment by espadrine** [comment]
@techtonik No problem, I know that struggle!

In case you (or I) end up having more time, this line is a good start: https://github.com/badges/shields/blob/6810895ff187d7908c1b9e64028ca91d947208d8/server.js#L4096.

**Comment by techtonik** [comment]
Okay. Got it to work with the following URL. SVG logo needs to be both base64 and urlencoded.

https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCIgdmlld0JveD0iMCAwIDQwIDQwIj4NCjxwYXRoIGZpbGw9IiMwOUE5RUQiIGQ9Ik0yMCAwYzExIDAgMjAgOSAyMCAyMHMtOSAyMC0yMCAyMFMwIDMxIDAgMjAgOSAwIDIwIDB6bTQuOSAyMy45YzIuMi0yLjggMS45LTYuOC0uOS04LjktMi43LTIuMS02LjctMS42LTkgMS4yLTIuMiAyLjgtMS45IDYuOC45IDguOSAyLjggMi4xIDYuOCAxLjYgOS0xLjJ6bS0xMC43IDEzYzEuMi41IDMuOCAxIDUuMSAxTDI4IDI1LjNjMi44LTQuMiAyLjEtOS45LTEuOC0xMy0zLjUtMi44LTguNC0yLjctMTEuOSAwTDIuMiAyMS42Yy4zIDMuMiAxLjIgNC44IDEuMiA0LjlsNi45LTcuNWMtLjUgMy4zLjcgNi43IDMuNSA4LjggMi40IDEuOSA1LjMgMi40IDguMSAxLjhsLTcuNyA3LjN6Ii8%2BDQo8L3N2Zz4%3D

![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCIgdmlld0JveD0iMCAwIDQwIDQwIj4NCjxwYXRoIGZpbGw9IiMwOUE5RUQiIGQ9Ik0yMCAwYzExIDAgMjAgOSAyMCAyMHMtOSAyMC0yMCAyMFMwIDMxIDAgMjAgOSAwIDIwIDB6bTQuOSAyMy45YzIuMi0yLjggMS45LTYuOC0uOS04LjktMi43LTIuMS02LjctMS42LTkgMS4yLTIuMiAyLjgtMS45IDYuOC45IDguOSAyLjggMi4xIDYuOCAxLjYgOS0xLjJ6bS0xMC43IDEzYzEuMi41IDMuOCAxIDUuMSAxTDI4IDI1LjNjMi44LTQuMiAyLjEtOS45LTEuOC0xMy0zLjUtMi44LTguNC0yLjctMTEuOSAwTDIuMiAyMS42Yy4zIDMuMiAxLjIgNC44IDEuMiA0LjlsNi45LTcuNWMtLjUgMy4zLjcgNi43IDMuNSA4LjggMi40IDEuOSA1LjMgMi40IDguMSAxLjhsLTcuNyA3LjN6Ii8%2BDQo8L3N2Zz4%3D)

**Comment by techtonik** [comment]
This one seems better:

![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=data%3Aimage%2Fsvg%2Bxml%2C%3Csvg+xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27+width%3D%2740%27+height%3D%2740%27+viewBox%3D%270+0+40+40%27%3E%3Cpath+fill%3D%27%23BBB%27+d%3D%27M20+0c11+0+20+9+20+20s-9+20-20+20S0+31+0+20+9+0+20+0zm4.9+23.9c2.2-2.8+1.9-6.8-.9-8.9-2.7-2.1-6.7-1.6-9+1.2-2.2+2.8-1.9+6.8.9+8.9+2.8+2.1+6.8+1.6+9-1.2zm-10.7+13c1.2.5+3.8+1+5.1+1L28+25.3c2.8-4.2+2.1-9.9-1.8-13-3.5-2.8-8.4-2.7-11.9+0L2.2+21.6c.3+3.2+1.2+4.8+1.2+4.9l6.9-7.5c-.5+3.3.7+6.7+3.5+8.8+2.4+1.9+5.3+2.4+8.1+1.8l-7.7+7.3z%27%2F%3E%3C%2Fsvg%3E)

**Comment by techtonik** [comment]
A couple variations with fill:

![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=data%3Aimage%2Fsvg%2Bxml%2C%3Csvg+xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27+width%3D%2740%27+height%3D%2740%27+viewBox%3D%270+0+40+40%27%3E%3Cpath+fill%3D%27%23FFF%27+d%3D%27M20+0c11+0+20+9+20+20s-9+20-20+20S0+31+0+20+9+0+20+0zm4.9+23.9c2.2-2.8+1.9-6.8-.9-8.9-2.7-2.1-6.7-1.6-9+1.2-2.2+2.8-1.9+6.8.9+8.9+2.8+2.1+6.8+1.6+9-1.2zm-10.7+13c1.2.5+3.8+1+5.1+1L28+25.3c2.8-4.2+2.1-9.9-1.8-13-3.5-2.8-8.4-2.7-11.9+0L2.2+21.6c.3+3.2+1.2+4.8+1.2+4.9l6.9-7.5c-.5+3.3.7+6.7+3.5+8.8+2.4+1.9+5.3+2.4+8.1+1.8l-7.7+7.3z%27%2F%3E%3C%2Fsvg%3E)

![](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?logo=data%3Aimage%2Fsvg%2Bxml%2C%3Csvg+xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27+width%3D%2740%27+height%3D%2740%27+viewBox%3D%270+0+40+40%27%3E%3Cpath+fill%3D%27%23DDD%27+d%3D%27M20+0c11+0+20+9+20+20s-9+20-20+20S0+31+0+20+9+0+20+0zm4.9+23.9c2.2-2.8+1.9-6.8-.9-8.9-2.7-2.1-6.7-1.6-9+1.2-2.2+2.8-1.9+6.8.9+8.9+2.8+2.1+6.8+1.6+9-1.2zm-10.7+13c1.2.5+3.8+1+5.1+1L28+25.3c2.8-4.2+2.1-9.9-1.8-13-3.5-2.8-8.4-2.7-11.9+0L2.2+21.6c.3+3.2+1.2+4.8+1.2+4.9l6.9-7.5c-.5+3.3.7+6.7+3.5+8.8+2.4+1.9+5.3+2.4+8.1+1.8l-7.7+7.3z%27%2F%3E%3C%2Fsvg%3E)

**Comment by techtonik** [comment]
Went with the last version #ddd.

**Comment by thisconnect** [comment]
What is needed for this to be merged? I would love the last version of @techtonik

**Comment by techtonik** [comment]
Logos above were pasted in syntax from this page https://codepen.io/tigt/post/optimizing-svgs-in-data-uris but it doesn't seem to work anymore.

**Comment by martincostello** [comment]
I intentionally used this badge so there was a consistent appearance in my repository README files between Travis CI and AppVeyor.

Could this not have been done as an opt-in with query string parmaeter so that the existing appearance could have been retained?

**Comment by techtonik** [comment]
@martincostello https://github.com/badges/shields/issues/983
