### ISSUE TITLE
Add GitHub watch badge.

### ISSUE THREAD

**Issue by adjohnson916** [badges/shields#508]
We already support GitHub stars, forks, and followers ([http://shields.io/#social](http://shields.io/#social)), so it might be nice to add a badge for GitHub watch count. This is the only badge we're missing that's included in [GitHub buttons](https://ghbtns.com/).

**Comment by espadrine** [comment]
Thanks for the suggestion! I'll use `/watchers/`.

**Comment by espadrine** [comment]
I'll merge it in 24h.

**Comment by adjohnson916** [comment]
@espadrine Thanks. Very quick implementation.
