### ISSUE TITLE
Open Science Framework badge

### ISSUE THREAD

**Issue by andrewbaxter439** [badges/shields#5080]
:clipboard: **Description**

### Open Science Framework badge

The [Open Science Framework](https://osf.io/) site is great for sharing research and links directly to github repos. I'm aiming to link my repos back to the relevant OSF project to point to more details etc. and link for future reporting.

:link: **Data**

I've had a rough go at creating one myself:

![OSF](https://img.shields.io/static/v1?label=OSF&message=osf.io%2F8u9jp&color=15A5EB&link=https://osf.io/8u9jp/&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAALrSURBVDiNjZRbaFRXFIb/fWaS1k5IpJiQeoGmFodesOIkRLBeUNoIQpW2AaFvgaJtRaUPFbwRrZdGQYtP3uJrKfpSVDLBNIH2QW1UmubWUqs+VM3MJMHEZGYyM+d8ffCccTIZnf5PZ6/zr3+v9a+9t1QEwGfAfSAGHCjGLya2CEgzHY0vyrFyki1gO9ABnAXmSloqye8gZcjm1APVwGmX+zXgK1TNjrxKeoBg7+N0+oPOYd6/GuPnoSTAp0B3HnfnjAolfZS3x+LLQ4mK/b3j10dTjhI2Ov7nxMMLdyf/klSbx91QSPB+LiNpo6MDk2fuxTM/ebGhpH3l+7uJ1riN8nCvkOA+SX2SNGWjwwMTiqcJ3hqrOmGMGpGakuNVW6ds3jrY90SJZ6KDknZ7C+P6t1JSSNKttkgi1dI/eWoiTdAYs+tmQ+WJ3FJCbdFtMmoJ+Kw737xdsXn9XL8tqU7SDWNMt9zJAnBteMrZ+MtIf204emh1F/78vrJoxh8Kx/Z+/Ovo77+NpBw33QE2G+CRpOoM0trOYU265wOjTbcbqn4spFcbjnyCzEVJKvMbdayZI7+RJP1rSZrhcFFglXifDpJDVsJvSfpOEn4jtSwpZ8ErvkEjHV44VnnxeXo1T+ZcMMYcmzfLunPovXKVWsb7dcwbynI9Nba742E6fmDw8cl4RouQ2XN7XeXZae22R5tARwI+/b3rndnbGl4rmS1pmaRrxpiuZ13APPd2kMg47OkZIxSOTgisUHtkY6gt2qhmrFA4Or73j3GSGW8W9LjXVJJ7bFzBVklN3jppow+7RgfiGecHGX3rhlvKSqz17ateffclXzZVks4ZYz6Xph/smlzGyz6jL4OBLRjqvJhltOyrNwNf5IlJ0hszjH7O42BdepAIr+iIsfxqjCsPkoNAKdCbx91eSNB7vjqBVtfTMsBJ2TBlZz2rB+YD54EutxBrhmAhAD5gJKeSDPD6/0p+geg64B8gAmwpxv8Pzpwmb9gDIfgAAAAASUVORK5CYII=)

See https://github.com/CenterForOpenScience/osf.io for the Center for Open Science OSF site.

:microphone: **Motivation**

Creating a new 'osf' logo name and standard badge would make linking easier, and open up for wider use.

I'm not in any way officially involved in this, but wasn't sure whether it was best to open here as a suggestion, or approach OSF admins directly first. Do close and redirect me if better practice.

**Comment by chris48s** [comment]
Hello. We don't usually add badges which are just static information. If you can generate it with a static badge its probably not a good candidate for inclusion. All of our badges have logos and links off by default, so the way you are already doing this is probably the right way to go for your use-case.

When it comes to logos, our named logos come from [simple-icons](https://simpleicons.org/) with a small number of exceptions. If Open Science Framework meets their criteria, you may want to look at whether you can contribute an OSF logo to the simple-icons project if you want to make it easier to use with shields (and other projects that use simpleicons):

SimpleIcons repo: https://github.com/simple-icons/simple-icons/
SimpleIcons contributing guidance: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

**Comment by andrewbaxter439** [comment]
Ah, that's helpful. Thanks @chris48s for getting back to me. Will close this issue and will continue to make use of shields.io accordingly. Thanks for the good work!
