### ISSUE TITLE
Update Kotlin icon

### ISSUE THREAD

**Issue by igorwojda** [badges/shields#5082]
Kotlin icon in this badge is incorrect
https://img.shields.io/github/languages/top/cortinico/kotlin-android-template?color=blue&logo=kotlin

Here is the correct Kotlin logo SVG
https://worldvectorlogo.com/logo/kotlin-1

**Comment by chris48s** [comment]
Hello. We don't maintain our own icon set - our named logos come from the simple icons library. If one of the logos in that library is outdated you can raise an issue on the simple icons tracker: https://github.com/simple-icons/simple-icons/issues

Thanks

**Comment by paulmelnikow** [comment]
If you want to use a different SVG from what's in simple-icons, you can also base64-encode the SVG and include it in the badge URL:

https://img.shields.io/github/languages/top/cortinico/kotlin-android-template?color=blue&logo=data:image/png;base64,…

**Comment by igorwojda** [comment]
everything is fine, my bad.
Let's close the issue
