### ISSUE TITLE
Add badge for GitHub user/org total stars received.

### ISSUE THREAD

**Issue by AndersDJohnson** [badges/shields#509]
Add another GitHub badge that indicates the total stars received for all repositories owned by a user or organization.

Perhaps rely on a module like [starz](https://github.com/yyx990803/starz), or a fork thereof, to get the data. See yyx990803/starz#2.

**Comment by espadrine** [comment]
Thanks for the suggestion!

**Comment by paulmelnikow** [comment]
Do you have an example of a place where a badge like this would be used?

**Comment by adjohnson916** [comment]
@paulmelnikow A personal website or an organization site advertising their GitHub presence.

**Comment by paulmelnikow** [comment]
Makes sense. Do you know if there's a way to get the data from the API without making a ton of requests?

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed

**Comment by idealclover** [comment]
Hi all!
I've made a new repository to provide an API~
https://github.com/idealclover/GitHub-Star-Counter
Example URL: https://github-star-counter.herokuapp.com/user/idealclover
So we can add badge like this:
![](https://img.shields.io/badge/dynamic/json?label=GitHub%20Total%20Stars&query=%24.stars&url=https%3A%2F%2Fgithub-star-counter.herokuapp.com%2Fuser%2Fidealclover)
![](https://github.com/idealclover/GitHub-Star-Counter/raw/master/assets/pic2.svg?sanitize=true)
Hope it can help you!
