### ISSUE TITLE
Internal Error: Github license badge

### ISSUE THREAD

**Issue by yooksi** [badges/shields#5106]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Github license badge is being displayed incorrectly.

Expected badge:
![2020-05-22_093915](https://user-images.githubusercontent.com/16436920/82643642-2dcc6080-9c10-11ea-9b58-dbfcc616dc28.png)

Actual badge:
![error](https://camo.githubusercontent.com/7f5889038d7d982504d842c038be51515d918dbf/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f796f6f6b73692f436f636f4c6962)

:link: **Link to the badge**

https://github.com/yooksi/cocolib/blob/master/README.md

:bulb: **Possible Solution**

Could be a problem with Github itself and not Shields.

**Comment by paulmelnikow** [comment]
Hi, thanks for the report. I think this was a transient issue. These badges are looking fine again.

<img width="135" alt="Screen Shot 2020-05-22 at 1 41 22 PM" src="https://user-images.githubusercontent.com/1487036/82694857-04bcc780-9c32-11ea-8148-f507c0d4221c.png">

**Comment by yooksi** [comment]
Indeed, the error seems to have resolved itself. Any idea what might have caused it?

**Comment by paulmelnikow** [comment]
GitHub is having all sorts of issues today, and I imagine the problem was somewhere among them.

https://www.githubstatus.com/incidents/6tcfpztf6j9m

**Comment by yooksi** [comment]
Okay thanks, good to know Shield is *most probably* not causing this.
