### ISSUE TITLE
Coverage inaccessable

### ISSUE THREAD

**Issue by montanaflynn** [badges/shields#512]
It seems coveralls.io badges are no longer working properly. 

This is true for both my [golang stats repo](https://github.com/montanaflynn/stats/blob/d6206bc42ddcd4acb4c688d6d95f0886ecd19322/README.md) and the http://shields.io website at the moment.

**Comment by montanaflynn** [comment]
They are back up and working as expected now, although you might want to check the logs to see if it was a coveralls API issue or an internal shields.io bug.

**Comment by montanaflynn** [comment]
And it's down again, here's Jekyll from the example shield:

[![Coveralls](https://img.shields.io/coveralls/jekyll/jekyll.svg)]()

**Comment by cdown** [comment]
Yeah, this is happening again. Any news on the migration?

**Comment by paulmelnikow** [comment]
These badges are working at present. If this issue recurs, please feel free to open a new issue.
