### ISSUE TITLE
Deploy proxy server for Discord hostname update

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#5130]
In #5105 the domain name for the Discord badge requests was updated. However in production this badge proxies the HTTP request to the old servers, due to Discord allowing unlimited requests from our production IPs (see #4962). Our current code can't be deployed to the production servers because of the node version. So, we need to cherry-pick the commit onto a new branch and deploy it specially.

The current commit on legacy s0 is 4999e557c9f974347f06a7b5b4c18fa2f0468d3a (plus the two deploy commits).

**Comment by PyvesB** [comment]
This will probably also be something to do when we merge #5079. Maybe we can wait for that PR to be landed to take care of both at the same time?

**Comment by PyvesB** [comment]
No longer required following #5346, closing.
