### ISSUE TITLE
pypi license reported as `Modified BSD License` when it should be `Proprietary`

### ISSUE THREAD

**Issue by siriobalmelli** [badges/shields#5134]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: The URL <https://img.shields.io/pypi/l/nrfutil.svg> gives `Modified BSD License` but:

- [PyPi](https://pypi.org/project/nrfutil/) reports `Other/Proprietary License`
- [The license itself](https://github.com/NordicSemiconductor/pc-nrfutil/blob/master/LICENSE) is clearly not FOSS

:link: 
https://img.shields.io/pypi/l/nrfutil.svg
![](https://img.shields.io/pypi/l/nrfutil)

Any help is much appreciated :)

**Comment by paulmelnikow** [comment]
Hi! Thanks for the question. I suspect that’s coming from the legacy license field:

https://github.com/NordicSemiconductor/pc-nrfutil/blob/master/setup.py#L140

**Comment by siriobalmelli** [comment]
Thank you very much for the fast response :)

I've filed a pull request to correct this here: https://github.com/NordicSemiconductor/pc-nrfutil/pull/325

**Comment by siriobalmelli** [comment]
Ok, pull request successful, but I am still currently seeing the incorrect badge.
See https://github.com/NordicSemiconductor/pc-nrfutil/blob/a0034f28359deda020632d64d71d8e15938a4082/setup.py#L140

Is this just a matter of waiting a day or so?

**Comment by paulmelnikow** [comment]
It needs to be published to PyPI as well.

**Comment by siriobalmelli** [comment]
Ah, gotcha. Thank you :)
