### ISSUE TITLE
Libscore NaN 

### ISSUE THREAD

**Issue by montanaflynn** [badges/shields#515]
From the example badge on http://shields.io:

[![Libscore](https://img.shields.io/libscore/s/jQuery.svg)]()

**Comment by espadrine** [comment]
How unfortunate, Libscore [broke its API contract](http://api.libscore.com/v1/libraries/jQuery)! Alas, `count` is a number no more.

@thomasdavis, might you know the significance of the list? Would you be so kind as to produce [a new PR](https://github.com/badges/shields/pull/333)?

**Comment by thomasdavis** [comment]
@Shapiro This one is fixed yeah?

**Comment by espadrine** [comment]
It was fixed in November 2015 by c986df7882a434d6389f4b1616f349c88f99a197.
