### ISSUE TITLE
img.shields.io is very unstable recently

### ISSUE THREAD

**Issue by mnovozhylov** [badges/shields#516]
we are using https://img.shields.io/github/release/*/*.svg badgets, and recently badgets are unavailable - right now it either "ERR_EMPTY_RESPONSE" or "Application Error: An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details.", in github repository it looks like ugly img-not-found

please, take a look

p.s. posting here, as far as i see many similar requests in this repository

**Comment by espadrine** [comment]
Thanks for voicing your concerns. We are going to switch servers to better respond to the load: https://github.com/badges/shields/issues/459.

**Comment by mnovozhylov** [comment]
@espadrine , thanks for the quick reaction! :)

**Comment by hannesvdvreken** [comment]
I get a lot of "vendor/unresponsive" responses from the img.shields.io server:

[](https://img.shields.io/github/release/hannesvdvreken/psr7-middlewares.svg?style=flat-square)

**Comment by espadrine** [comment]
@hannesvdvreken Thank you a lot for reporting this. We have switched servers recently, and there are rough edges. In that case, I believe the server might not be registering the GitHub API keys? I'll investigate.

**Comment by hannesvdvreken** [comment]
I think that's what currently happening. The version badge works only from time to time. Possibly it's not cached and the GitHub API limit is hit.

**Comment by espadrine** [comment]
The following issue correponds better to this issue: https://github.com/badges/shields/issues/529.

I will close this issue, and expand on my findings in the other issue, which you can subscribe to in order to get more information on the developments.
