### ISSUE TITLE
Badge Request: All Contributors

### ISSUE THREAD

**Issue by JoeIzzard** [badges/shields#5161]
:clipboard: **Description**

All Contributors is a specification designed to show all contributors no matter there contribution. Currently they have a bot that manually updates a manual Shield.io Badge in Repo's however this doesn't work too well. The alternative that works is the dynamic json endpoint with a query. This works but isn't the easiest to generate. A wrapper to make the URL nicer would be perfect. It would show the total contributors for a repo, as defined by that system. For examlple:

All Contributors | 29

:link: **Data**

The data already exists in repo's that use it as a JSON file that can be accessed via GitHub Raw. The url would be:

`https://raw.githubusercontent.com/*USER*/*REPO*/*BRANCH*/.all-contributorsrc`

As the Bot updates the master branch, it would be safe to use that branch to pull the stats from. Currently some are using Shields JSON Dynamic endpoint, with a query to count the contributors array. An example of Dynamic JSON URL is:

`https://img.shields.io/badge/dynamic/json?color=orange&style=flat-square&label=All%20Contributors&query=%24.contributors.length&url=https%3A%2F%2Fraw.githubusercontent.com%2FJoeIzzard%2F.github%2Fmaster%2F.all-contributorsrc`

This is dynamic url for my [.github](https://github.com/joeizzard/.github) repo.
 

:microphone: **Motivation**

Currently Contributor counts only include people that actually contribute code, where as the all contributors project also recognises those that contribute out side of committing code, such as graphics, bug reports and such. This allows you to show an accurate contributor count for projects that instead use that specification.

**Comment by JoeIzzard** [comment]
I'm going to have a go at implementing this, but not done anything for shields before so any tips more than welcome!

**Comment by chris48s** [comment]
We have a tutorial you can follow though for adding a new badge:
https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

This badge falls into the category of "grab a file from a hard-coded location in a github repo and extract some data from it". Fortunately this is a well trodden path - there are several other badges that do this. Some examples to crib from:

* https://github.com/badges/shields/blob/master/services/github/github-lerna-json.service.js
* https://github.com/badges/shields/blob/master/services/github/github-manifest.service.js
* https://github.com/badges/shields/blob/master/services/github/github-package-json.service.js
* https://github.com/badges/shields/blob/master/services/github/github-pipenv.service.js

`.all-contributorsrc` is json, so you can make use of the `fetchJsonFromRepo` common helper.

For developing a github badge, you might find you need to set a `GH_TOKEN` in your dev copy. See https://github.com/badges/shields/blob/master/doc/server-secrets.md for how to set up secrets. Looking forward to reviewing a PR.

**Comment by chris48s** [comment]
This is deployed now :tada: https://img.shields.io/github/all-contributors/all-contributors/all-contributors
