### ISSUE TITLE
add GitHub Pre-Release (latest by date)

### ISSUE THREAD

**Issue by techtimo** [badges/shields#5186]
You have the badge Github/Release (latest by date) but nothing for pre releases

**Comment by chris48s** [comment]
We do already have this. e.g:

![](https://img.shields.io/github/v/release/expressjs/express) - https://img.shields.io/github/v/release/expressjs/express
![](https://img.shields.io/github/v/release/expressjs/express?include_prereleases) - https://img.shields.io/github/v/release/expressjs/express?include_prereleases

**Comment by techtimo** [comment]
ahhh sorry i haven't seen the option `?include_prereleases` 
Thanks! :)
my bad!
