### ISSUE TITLE
Microsoft Sql Server icon not rendered

### ISSUE THREAD

**Issue by Giorgi** [badges/shields#5194]
For some reason [Microsoft Sql Server icon](https://simpleicons.org/icons/microsoftsqlserver.svg) isn't being rendered by shields.io

![No MS Sql logo](https://img.shields.io/badge/style-for--the--badge-green?logo=microsoftsqlserver&style=for-the-badge)

**Comment by calebcartwright** [comment]
Looks like you may have the wrong reference to the logo
`?logo=microsoft-sql-server`

https://img.shields.io/badge/style-for--the--badge-green?logo=microsoft-sql-server&style=for-the-badge

**Comment by Giorgi** [comment]
Thanks, I thought it used the same name as simple icon.
