### ISSUE TITLE
Gratipay badge no longer works

### ISSUE THREAD

**Issue by ARMmaster17** [badges/shields#520]
Gratipay recently updated their site, now the badge using shields.io reports that my incoming tips are anonymous, despite the fact that my settings show that I would like this information public.

**Comment by espadrine** [comment]
Thank you for raising this issue!

Currently, it is pending the resolution of [this issue](https://github.com/gratipay/gratipay.com/issues/3726) over on Gratipay's side.

**Comment by espadrine** [comment]
This was partially fixed by https://github.com/badges/shields/pull/533. Teams may show $0 even though the value is higher, because it is not yet implemented on Gratipay's side. We will implement the missing piece when it gets implemented.
