### ISSUE TITLE
Magnum CI

### ISSUE THREAD

**Issue by larsbrinkhoff** [badges/shields#523]
API: https://magnum-ci.com/docs/api

Sample badge: ![](https://magnum-ci.com/status/96ffb83fa700f069024921b0702e76ff.png)

**Comment by espadrine** [comment]
Thanks for the suggestion!

Sadly `curl 'https://magnum-ci.com/api/v1/project/builds?token=96ffb83fa700f069024921b0702e76ff'` is unsuccessful.

**Comment by larsbrinkhoff** [comment]
It seems the public token for the build badge is different from the private API token.

**Comment by larsbrinkhoff** [comment]
Would it be possible to guess the status from the contents of the PNG?

**Comment by espadrine** [comment]
@larsbrinkhoff OCR is the worst kind of scrapping; nobody wants a badge that takes more than a few second to be generated, and I doubt the servers would survive that well.

So the answer is yes, but a PR that does it wouldn't be merged.

On the other hand, many vendors that serve PNG badges populate the Content-Disposition HTTP header with all the information we need. HTTP scraping is much more practical and in fact used quite often in shields.

```bash
curl -I https://magnum-ci.com/status/96ffb83fa700f069024921b0702e76ff.png | grep Content-Disposition
# Content-Disposition: inline; filename="pass.png"
```

If you want to implement that, you can find a similar HTTP scrapper in server.js. We'd need to know what it returns if the test is failing, though.

**Comment by larsbrinkhoff** [comment]
> We'd need to know what it returns if the test is failing, though.

This:

    Content-Disposition: inline; filename="fail.png"

**Comment by larsbrinkhoff** [comment]
PR submitted: #584.
