### ISSUE TITLE
Ship.io

### ISSUE THREAD

**Issue by larsbrinkhoff** [badges/shields#524]
API: https://app.ship.io/api

Sample badge: ![](https://app.ship.io/jobs/7oIHDz28rgdvceSO/build_status.png)

**Comment by espadrine** [comment]
Thanks for the suggestion!

Dealing with authentication will be inconvenient. The user's authentication token is meant to be private.

**Comment by larsbrinkhoff** [comment]
Here's a direct link to the image:
https://app.ship.io/jobs/7oIHDz28rgdvceSO/build_status.png

**Comment by espadrine** [comment]
Unfortunately, they don't leak information in the HTTP headers, either.

**Comment by larsbrinkhoff** [comment]
They are closing down, so I guess the point is moot.

https://ship.io/ship-io-is-shutting-down/
