### ISSUE TITLE
Badge request: AppHarbor

### ISSUE THREAD

**Issue by larsbrinkhoff** [badges/shields#525]
API: https://support.appharbor.com/kb/api/builds-api-2

This one is especially interesting, because AppHarbor don't offer any badge themselves.

**Comment by espadrine** [comment]
Thanks for the suggestion!

It would presumably be something like `curl 'https://appharbor.com/applications/SLUG/builds'`. Having an example slug would help a lot.

**Comment by larsbrinkhoff** [comment]
My application is called `lbforth`.  When logged in, it's at https://appharbor.com/applications/lbforth.

Authentication is described here: https://support.appharbor.com/kb/api/api-overview

**Comment by espadrine** [comment]
Presumably, it will require something like `curl -H 'Authorization: BEARER token' 'https://appharbor.com/applications/lbforth/builds'`. The token would have to get fetched once from a shields account at appharbor (and hopefully would then have access to the information needed for any request).

**Comment by Marusyk** [comment]
Hello, any status?

**Comment by LiHRaM** [comment]
What's happening with this one?

**Comment by paulmelnikow** [comment]
@LiHRaM Would you like to make a pull request?

**Comment by LiHRaM** [comment]
@paulmelnikow I'll get started on that. ;)

**Comment by PyvesB** [comment]
Apparently AppHarbor has shut down: https://blog.appharbor.com/2022/11/09/shutting-down-appharbor

Closing this issue as it's no longer relevant.
