### ISSUE TITLE
Website service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5261]
:clock11: **When did the problem start?**
Seems to have started roughly around the 16th of June, and has failed on almost every run since

:camera: **Live badge**

https://img.shields.io/website?url=https%3A%2F%2Fshields.io
![](https://img.shields.io/website?url=https%3A%2F%2Fshields.io)

:wrench: **Is the live badge working?**
Yes

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/290/workflows/e5ab0410-dec1-4038-a1f1-279572030042/jobs/1187/steps

:beetle: **Stack trace**

There's two recurring sets of stack traces, one with:
```
Website [live] status of nonexistent domain [ GET /website.json?url=http://shields.io.io ] - [ GET /website.json?url=http://shields.io.io ]
/home/circleci/project/shields/core/service-test-runner/cli.js

Error: Request timed out after 5000 ms (4 attempts)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1255:37)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

And the other:
```
Website [live] status of nonexistent domain [ GET /website.json?url=http://shields.io.io ] - [ GET /website.json?url=http://shields.io.io ]
/home/circleci/project/shields/core/service-test-runner/cli.js

MultiError: first of 2 errors: ESOCKETTIMEDOUT
    at VError.errorFromList (node_modules/verror/lib/verror.js:325:10)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1292:13)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Probably just change the test target and/or increase the timeout on the test. I'm not really sure what's going on with the `shields.io.io` but observe the same slow behavior with the live badge rendering as well.

**Comment by paulmelnikow** [comment]
Uhh… why is it shields.io.io?!

**Comment by calebcartwright** [comment]
it's intended to be a bad uri, guessing it was a copy pasta job with an extra subdomain

**Comment by paulmelnikow** [comment]
Ah, right, that makes sense. I wonder if we should change then service so it times out after a few seconds by default. It’d be nice if we reported a failure in a reasonable time on a very slow site.
