### ISSUE TITLE
Twitter: follow user?

### ISSUE THREAD

**Issue by JamieMason** [badges/shields#527]
Hey,
I was wondering if someone could help me please. Is it possible to create a shield to follow a Twitter user? What I have below is mostly ok (I'm fine with it just being a link to my profile) but what I've done is adjust the tweet URL shield and I'd like to not show the counter if possible.

### Markdown

```markdown
[![Twitter URL](https://img.shields.io/twitter/url/https/twitter.com/fold_left.svg?style=social&label=Follow%20%40fold_left)](https://twitter.com/fold_left)
```

### Output

[![Twitter URL](https://img.shields.io/twitter/url/https/twitter.com/fold_left.svg?style=social&label=Follow%20%40fold_left)](https://twitter.com/fold_left)

I've looked around the source but can't see anything, it could be that this simply isn't available.

Thanks for such a useful service.

Jamie

**Comment by espadrine** [comment]
Oh, I know I had a self-note somewhere about something similar…

There! https://github.com/badges/shields/issues/518#issuecomment-135392648

(Self note: <https://dev.twitter.com/rest/reference/get/users/show> has user lookups, with `followers_count` and `statuses_count`; `curl 'http://cdn.api.twitter.com/1.1/users/lookup.json?screen_name=stefansiegl'` requires auth.)

The auth part is the thorn in our feet. The rate-limiting, too.

That said, you're right, we don't have the functionality currently.

**Comment by JamieMason** [comment]
Brilliant @espadrine, thanks so much.
