### ISSUE TITLE
Travis CI invalid badges (rate limiting?)

### ISSUE THREAD

**Issue by jakirkham** [badges/shields#528]
It appears that the repo `joyent/node` on GitHub was moved and renamed. However, Travis CI does not know this. So, changing the URLs for these badges is needed to fix the examples.

**Comment by jakirkham** [comment]
Also, seeing this for HHVM badges and MyGet.

**Comment by elboletaire** [comment]
Not just the examples. Mine were failing so far but whilst I write this post they appear to be ok.

![Watimage build status](https://img.shields.io/travis/elboletaire/Watimage.svg?style=flat-square)
![Less CakePHP Plugin build status](https://img.shields.io/travis/elboletaire/less-cake-plugin.svg?style=flat-square)

**Comment by elboletaire** [comment]
> Maybe is something with the cache of shields. If they're projects with a lot of movement and they're building very consecutively maybe shields shows us every time a cached image of an on-going build.

Forget that. I've just seen how it changed from passing to unaccessible to passing again and I'm not currently running any build.

**Comment by elfet** [comment]
Same for me!

**Comment by Mithgol** [comment]
+1

**Comment by feross** [comment]
+1

**Comment by kgryte** [comment]
I am frequently getting `inaccessible` travis-ci badges. If I refresh my browser two or three times, the badge changes to `success`. If I leave and come back, the badge says `inaccessible` again. This is in contrast to the badge directly provided by travis-ci which always shows `success`.

**Comment by espadrine** [comment]
I have added a log in prod to identify what causes that. The "normal" cause is that travis does not have that repo registered, which does not seem to be the case here. So far no luck.

**Comment by kgryte** [comment]
The problem seemed to start, at least for me, within the past week. For an example repo, see [here](https://github.com/kgryte/utils-fs-exists). If you keep refreshing, the travis-ci badge will randomly alternate between `inaccessible` and `success`.

**Comment by espadrine** [comment]
Here is what I have: sometimes, Travis CI returns `{"file":"not found"}` when downloading their badge. Is that a rate-limiting thing?

**Comment by espadrine** [comment]
Historically, we request badges instead of using the API because the straightforward API queries sometimes produce "pending", which is not a badge people ever want to see, and some other way to use the API to circumvent that had issues when dealing with branches. People wanted our badges to show the same information as the Travis CI badges (with the customizability that we offer).

- Original switch from png header sniffing to straightforward Travis API: https://github.com/badges/shields/commit/ee4c9f885a07147b4b5e45b091f137fe3110af9d
- Switch to builds.json to avoid "pending": https://github.com/badges/shields/commit/5050698c14f4530a559ad93ed769c25ae15571e1
- Issues with that, and switch to SVG scraping: https://github.com/badges/shields/issues/288

I have gone full circle, and switched it to only perform a HEAD request, on the svg headers this time. Let me know if it changes anything.

**Comment by bcomnes** [comment]
Seeing a lot of invalid travis badges this morning.

**Comment by TomasVotruba** [comment]
Same here:

- Shields invalid: https://img.shields.io/travis/Zenify/ModularPresenterMapping.svg
- Travis valid: https://travis-ci.org/Zenify/ModularPresenterMapping.svg?branch=master

**Comment by ankitpokhrel** [comment]
Same problem here!

**Comment by Mithgol** [comment]
It seems to me that the problem's gone. Is it a weekend's effect, I wonder.

**Comment by JayBizzle** [comment]
Still seeing the `Invalid` Travis badges

**Comment by netvl** [comment]
Indeed, having the same problem. Shields.io:
![](https://img.shields.io/travis/netvl/xml-rs.svg?style=flat-square) (https://img.shields.io/travis/netvl/xml-rs.svg?style=flat-square)
Travis:
![](https://travis-ci.org/netvl/xml-rs.svg?branch=master) (https://travis-ci.org/netvl/xml-rs.svg?branch=master)

Occasionally the shields badge becomes green but usually it is invalid.

**Comment by elboletaire** [comment]
I currently see them better than before the change. It's true that now they appear as "invalid" sometimes but it's less often than when they said "inaccessible".

**Comment by brianreavis** [comment]
Also getting a bunch of `Invalid` badges across many repos.

**Comment by artem-malko** [comment]
:+1:

**Comment by jakirkham** [comment]
TeamCity badge is malformed.

**Comment by paulmelnikow** [comment]
If this problem recurs, feel free to open a new issue.
