### ISSUE TITLE
Badges can't be used in Scratch

### ISSUE THREAD

**Issue by Ani-Xan** [badges/shields#5284]
:question: **Question**
My Badge, ![My Badge](https://img.shields.io/badge/dynamic/json?color=ff5959&label=Followers&query=%24.statistics.followers&url=https%3A%2F%2Fscratchdb.lefty.one%2Fv2%2Fuser%2Finfo%2FAni-Xan&style=flat-square) will not show up on a forum signature that uses BBcode. Here is an example of me using the "[img]" tag: ![Image 1](https://images2.imgbox.com/6f/40/20XcivPg_o.png) And here is me not using the "[img]" tag: ![Image 2](https://images2.imgbox.com/13/aa/mdhobJ43_o.png) A little help? (Maybe use the code function?)

**Comment by paulmelnikow** [comment]
Hi there. It looks like they only support images from certain hosts:

https://en.scratch-wiki.info/wiki/Image_Hosting

I don't think we can do anything about this. I think you would have to ask Scratch to allow requests to img.shields.io.

**Comment by Ani-Xan** [comment]
> Hi there. It looks like they only support images from certain hosts:
> 
> https://en.scratch-wiki.info/wiki/Image_Hosting
> 
> I don't think we can do anything about this. I think you would have to ask Scratch to allow requests to img.shields.io.

Thank you!
