### ISSUE TITLE
Website service failed with a status code of 204

### ISSUE THREAD

**Issue by OpportunityLiu** [badges/shields#5291]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

My website responed 204 to HEAD request, and the website service shown 'down'.

:link: **Link to the badge**

https://img.shields.io/website?label=backend&logo=nestjs&url=https%3A%2F%2Fehtt.azurewebsites.net%2Fdatabase
![](https://img.shields.io/website?label=backend&logo=nestjs&url=https%3A%2F%2Fehtt.azurewebsites.net%2Fdatabase)

:bulb: **Possible Solution**

I've debuged the code and got following error
https://github.com/badges/shields/blob/964ad087674edf57ae329d1b1aecf5a7c10cefc7/services/website/website.service.js#L80-L95
```
InvalidResponse: Invalid Response: Got status code 204 (expected 200)
buffer:""
defaultPrettyMessage:"invalid"
message:"Invalid Response: Got status code 204 (expected 200)"
name:"InvalidResponse"
prettyMessage:"invalid"
response:IncomingMessage {_readableState: ReadableState, readable: false, domain: null, …}
stack:"Error: Got status code 204 (expected 200)
    at ~\shields\core\base-service\check-error-response.js:16:26
    at Website._request (~\shields\core\base-service\base.js:228:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by chris48s** [comment]
I think we're catching the 204 here:

https://github.com/badges/shields/blob/13d75e0607334b700fdb4a533768cde341619a50/core/base-service/check-error-response.js#L15

I think we should consider any 2XX response success here, but given we run `checkErrorResponse()` on basically every request, I'm ever-so-slightly cautious.. does anyone see a good reason why we _shouldn't_ do that?

**Comment by paulmelnikow** [comment]
Perhaps we should make this modification specific to the website service, to your point that `checkErrorResponse()` is used on every request and the website badge is an anomaly.

Is a 204 really a website that is "up"? I guess I don't wanna have that argument. 😀

**Comment by OpportunityLiu** [comment]
```
// We consider all HTTP status codes below 310 as success. 
```
