### ISSUE TITLE
Travis build status returns error message

### ISSUE THREAD

**Issue by Tearth** [badges/shields#5293]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

This specified badge (Travis build status) displays a red error instead of green "passing" one. A similar one (with the different repository) works well. A few weeks ago I hadn't any issues with this, but it started failing last time (~1, 2 weeks).

:link: **Link to the badge**

https://img.shields.io/travis/Tearth/Oddity.svg?branch=master&style=flat-square&logo=travis-ci&logoColor=white&cacheSeconds=3600

**Comment by calebcartwright** [comment]
The branch needs to be provided as a route parameter, not a query parameter

https://img.shields.io/travis/Tearth/Oddity/master?style=flat-square&logo=travis-ci&logoColor=white
![](https://img.shields.io/travis/Tearth/Oddity/master?style=flat-square&logo=travis-ci&logoColor=white)

**Comment by Tearth** [comment]
Oh, right - my mistake. Thanx for help.
