### ISSUE TITLE
The @types/styled-components mess

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#5294]
Wanted to surface this here rather than burying it in a dependabot PR…

As @calebcartwright observed at https://github.com/badges/shields/pull/5277#issuecomment-653836259 the version of `@types/styled-components` that we've pinned as a result of DefinitelyTyped/DefinitelyTyped#33311 is now blocking us from updating TypeScript.

This is untenable.

Part of me wants to try to dive into the DefTyped repo and fix this though I just don't have a ton of bandwidth.

Increasingly the [hacky workaround](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33311#issuecomment-653938738) of deleting `node_modules/@types/react-native`, a package which of course should not be installed into Shields, is feeling like a reasonable way to handle this.

**Comment by paulmelnikow** [comment]
I'm using the hacky workaround in another project. It seems to be working fine and means we can use the up-to-date type defs and latest TypeScript.

If no one objects I'll open a PR to do that here.

**Comment by calebcartwright** [comment]
No objections whatsoever!

**Comment by paulmelnikow** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914

Hallelujah!
