### ISSUE TITLE
Copy As Markdown Button

### ISSUE THREAD

**Issue by Miserlou** [badges/shields#530]
Just an idea, feel free to close, but it'd be super convenient to have a 'copy Markdown to clipboard' button next to every item!

**Comment by espadrine** [comment]
If you click on the badge, it shows a popup in which you can click on the markdown, copy it, and paste it wherever you want.

I'll think about having a dedicated button to every entry.

**Comment by Miserlou** [comment]
Ah, okay. That's satisfactory!

**Comment by techtonik** [comment]
I completely missed the point that buttons are clickable. It may worth to underline service names and make them clickable.

**Comment by espadrine** [comment]
@techtonik That's not a bad idea. Currently, clicking them selects the URL. It may be good to delete `autoselectCode()` in https://github.com/badges/shields/blob/0536763b498b865e65db31243512356e7bcd2295/try.html#L1162 and instead add a click listenere here: https://github.com/badges/shields/blob/0536763b498b865e65db31243512356e7bcd2295/try.html#L1177.

**Comment by espadrine** [comment]
@techtonik Implemented! I'll put it live in 24h. Until then you can try it out on https://img.shields.io/try.html.
