### ISSUE TITLE
Cookie in use

### ISSUE THREAD

**Issue by decryp2kanon** [badges/shields#5324]
```
![GitHub All Releases](https://img.shields.io/github/downloads/sugarchain-project/sugarchain/total)
```

![image](https://user-images.githubusercontent.com/60179867/87760689-21165400-c7de-11ea-8d98-1e853cb6204e.png)

Hi, how to not use this cookie? I wanna remove this one. Any suggest?

**Comment by paulmelnikow** [comment]
Hi! The only way to turn it off is to [host your own copy of Shields](https://github.com/badges/shields/blob/master/doc/self-hosting.md). Would suggest following #3026 which discusses the alternatives.
