### ISSUE TITLE
Azure DevOps Build "inaccessible"

### ISSUE THREAD

**Issue by BenSova** [badges/shields#5349]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

I have a build badge for Azure DevOps and the badge says that the build in "inaccessible".
I checked both the Product and Definition ID and both are correct.

:link: **Link to the badge**

[![Azure Pipelines Build Status](https://img.shields.io/azure-devops/build/SwiftStars/cf764067-e0bf-47cf-ba14-ac21bb8771d8/2?logo=Azure%20Pipelines&logoColor=informational&style=flat-square&labelColor=363C43)](https://img.shields.io/azure-devops/build/SwiftStars/cf764067-e0bf-47cf-ba14-ac21bb8771d8/2?logo=Azure%20Pipelines&logoColor=informational&style=flat-square&labelColor=363C43)

https://img.shields.io/azure-devops/build/SwiftStars/cf764067-e0bf-47cf-ba14-ac21bb8771d8/2?logo=Azure%20Pipelines&logoColor=informational&style=flat-square&labelColor=363C43

**Comment by PyvesB** [comment]
Hello @BenSova,

I know very little about the Azure Devops service, but here's the response I get when hitting the API used by Shields (https://dev.azure.com/SwiftStars/cf764067-e0bf-47cf-ba14-ac21bb8771d8/_apis/build/status/2):

```
{"$id":"1","innerException":null,"message":"VS800075: The project with id 'cf764067-e0bf-47cf-ba14-ac21bb8771d8' does not exist, or you do not have permission to access it.","typeName":"Microsoft.TeamFoundation.Core.WebApi.ProjectDoesNotExistException, Microsoft.TeamFoundation.Core.WebApi","typeKey":"ProjectDoesNotExistException","errorCode":0,"eventId":3000}
```

Maybe the project is private or what or the IDs is not lining up?

**Comment by BenSova** [comment]
Turns out the project ID changed when I got rid of a typo in the project name... So, it kind of makes since but I don't get why the project ID can change because of the name. 
That's not a shields problem though, so I'll close this issue.

**Comment by calebcartwright** [comment]
FWIW @BenSova you can use the Team Project name instead if you prefer. When we first added the badge the upstream Azure DevOps endpoint only supported the project id, but both Id or Name are now an option

**Comment by BenSova** [comment]
That's nice to know, but I'll keep using project ID for at least this project. Thanks though.
