### ISSUE TITLE
Contributors badge not shown

### ISSUE THREAD

**Issue by alex4200** [badges/shields#5350]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)
- [x] Not sure: I just want to add a badge on my own repository

:beetle: **Description**

Following the example given on the `README` I tried to add a 'contributors' badge to my repo. I copied and pasted the link, and replaces the username and repo name, ending up with the following link:

`https://github.com/alex4200/pytracov/graphs/contributors`

:link: **Link to the badge**
Well, 

`https://github.com/alex4200/pytracov/graphs/contributors`

:bulb: **Possible Solution**

Maybe I misunderstand completely what 'shields' is or how to use it?

**Comment by calebcartwright** [comment]
@alex4200 - just to clarify, is `https://github.com/alex4200/pytracov/graphs/contributors` the literal url you tried to add to your readme to get a badge?

The Shields.io service provides badges (svg's) that you can use for things like embedding in your markdown files. The easiest way to get going with this is to leverage the Shields site (https://shields.io/) to let it help you generate the corresponding markdown snippets for you which can then be pasted in your project.

If you go the https://shields.io site, you can then browse available badges as well as search for specific ones (in your case you can search for "github contributors" to bring up that badge)

![image](https://user-images.githubusercontent.com/13042488/88403942-d0c96400-cd92-11ea-94bf-f1d148d43e2a.png)

If you click on a badge, it will bring up the badge builder window where you can enter your project details, and then use the "Copy badge url" button to get your badge url/info in various formats, including markdown

![image](https://user-images.githubusercontent.com/13042488/88404227-3cabcc80-cd93-11ea-9105-8876541dad33.png)

You can then take that url (or markdown if you prefer) and add it to your readme file
https://img.shields.io/github/contributors/alex4200/pytracov
![](https://img.shields.io/github/contributors/alex4200/pytracov)

**Comment by alex4200** [comment]
Ah ok, I seem to have missed that from the README. I checked the README twice, but did not find that explanation. 

Maybe you can make that a bit more clear on the README?

**Comment by calebcartwright** [comment]
> Maybe you can make that a bit more clear on the README?

If you have any specific suggestions, please feel free to propose them via a PR. However, I'd point out that there's already material under in the [Examples](https://github.com/badges/shields#examples) section. 

I'm not really sure where/how you got the "https://github.com/alex4200/pytracov/graphs/contributors" link you referenced in your original issue, nor what you were expecting by pasting that GitHub URL into your readme file. Shields.io and GitHub are very separate entities :wink:
