### ISSUE TITLE
Request for Slack Badge

### ISSUE THREAD

**Issue by balupton** [badges/shields#536]
Currently there is https://github.com/rauchg/slackin/blob/master/lib/badge.js via https://github.com/rauchg/slackin however it doesn't work via safari https://github.com/rauchg/slackin/issues/55 - perhaps slackin could be updated to use shields, or perhaps shields could be updated to use slackin

**Comment by espadrine** [comment]
The juicy bit is here: https://github.com/rauchg/slackin/blob/master/lib/slack.js#L20. A token is needed, however. We could imagine `/slack/users/TOKEN.svg` calling `curl 'https://slack.com/api/rtm.start?token=TOKEN` (but the token must correspond to someone on the socketio team).

> You can find your API token at api.slack.com/web – note that the user you use to generate the token must be an admin.

It isn't really safe to send the token to the shields servers, though. However, having it implemented would make it easier to run your own shields server which would be able to serve badges in the social style (similar to the one displayed by default by rauchg) or in the flat style (the one we designed for shields) without issue 55.

**Comment by balupton** [comment]
@espadrine that's very informative thanks, the need for a custom secret token rules that out for shields.io implementing a slack badge directly.

What if slackin worked by having the URL to badge - [handled by this](https://github.com/rauchg/slackin/blob/master/lib/index.js#L147-L153), simply redirect to a manually generated shields.io badge, like https://img.shields.io/badge/slack-3/8-pink.svg

**Comment by balupton** [comment]
Going to close, as an issue for slackin directly.
