### ISSUE TITLE
Some logo don't shown in badge

### ISSUE THREAD

**Issue by progfay** [badges/shields#5363]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

- Some logo don't shown.
- e.g.: IFTTT ![IFTTT](https://img.shields.io/static/v1?message=message&logo=ifttt)
  - Screenshot in production: <img src="https://user-images.githubusercontent.com/19568747/88451166-8c6fbe00-ce8f-11ea-8ae2-34cbb1c9e2a3.png" height="20">
  - `https://img.shields.io/static/v1?message=message&logo=ifttt`
  - Screenshot in development: <img src="https://user-images.githubusercontent.com/19568747/88451102-21be8280-ce8f-11ea-88f7-f2446b0467fc.png" height="20">
  - `http://localhost:8080/static/v1?message=message&logo=ifttt`

:link: **Link to the badge**

Badge list I found:

- ![IFTTT](https://img.shields.io/static/v1?message=IFTTT&logo=IFTTT)
- ![JBL](https://img.shields.io/static/v1?message=JBL&logo=JBL)
- ![OpenAI](https://img.shields.io/static/v1?message=OpenAI&logo=OpenAI)
- ![OpenAI Gym](https://img.shields.io/static/v1?message=OpenAI+Gym&logo=OpenAI+Gym)
- ![Pelican](https://img.shields.io/static/v1?message=Pelican&logo=Pelican)
- ![Philips Hue](https://img.shields.io/static/v1?message=Philips+Hue&logo=Philips+Hue)
- ![Planet](https://img.shields.io/static/v1?message=Planet&logo=Planet)
- ![RTÉ](https://img.shields.io/static/v1?message=RTÉ&logo=RTÉ)
- ![Bilibili](https://img.shields.io/static/v1?message=Bilibili&logo=Bilibili)
- ![Crowdin](https://img.shields.io/static/v1?message=Crowdin&logo=Crowdin)

Please check list of all badge with logo: [progfay/shields-with-icon](https://github.com/progfay/shields-with-icon/blob/master/Snippets.md)

**Comment by PyvesB** [comment]
Hello @progfay,

We're still running version 3.0.1 of simple-icons in production, the IFTTT logo was added a few days ago in [release 3.1.0](https://github.com/simple-icons/simple-icons/releases/tag/3.1.0). I'll deploy the new version to production, that should solve your problem. :wink:

**Comment by progfay** [comment]
OK, I'm looking forward to release😁

Thank you for your comment!

**Comment by PyvesB** [comment]
The logo is now available in production:
![](https://img.shields.io/static/v1?message=my-message&logo=ifttt)

**Comment by progfay** [comment]
Awesome 🎉
