### ISSUE TITLE
Discord badge shows "chat | invalid"

### ISSUE THREAD

**Issue by burner1024** [badges/shields#5365]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

Discord badge shows "chat | invalid". Maybe related to their recent domain change from discordapp.com to discord.com?

Right in your README:
![Captura de pantalla de 2020-07-25 20-13-50](https://user-images.githubusercontent.com/1279852/88457798-9e635800-ceb3-11ea-9cbb-a16a235a116d.png)

**Comment by PyvesB** [comment]
Hello @burner1024,

I just tried deploying #5346, unfortunately it did not go according to plan. I'm not too sure what's wrong yet. For now I've rolled back, the Discord badges should be back to normal.

**Comment by night** [comment]
@PyvesB the deploy looked fine from our end, but firewall misconfiguration still resulted in you getting limited. if you try redeploying again it should be fine this time around.

**Comment by PyvesB** [comment]
Thanks for looking into this and fixing the firewall configuration @night! I was going to send you a mail this morning, but was glad to see that you had already picked this up when I woke up! :)

I performed a new deployment, everything indeed seems to be working well now. Great stuff! 👍🏻
