### ISSUE TITLE
TYPO3 Badge

### ISSUE THREAD

**Issue by AMartinNo1** [badges/shields#5366]
:clipboard: **Description**

TYPO3 is a CMS with a large user base and in my opinion it would be neat to have the icon and color-set available. Extensions are commonly listed here https://extensions.typo3.org/. So, while referring to https://shields.io/category/monitoring the format could be TER and lead to the detail page https://extensions.typo3.org/extension/gpsnose/. So, one only provides the extension name and gets a badge with TYPO3 colors, icons and TER label (the left one).

:link: **Data**

https://typo3.org/

:microphone: **Motivation**

In detail I would enjoy pre-defined color-set and the typo3 icon displayed within the badge.

**Comment by AMartinNo1** [comment]
Just noticed that a TYPO3 logo is available already. So, that part is not necessary.

**Comment by calebcartwright** [comment]
Could you elaborate a bit on the ask here with specifics around the data points you think should be in the badge? The `label | message` format is particularly helpful.

**Comment by AMartinNo1** [comment]
Hmm, I have given it some more thoughts. As TYPO3 icon is provided by simple-icons there's no real need for my initial idea.
