### ISSUE TITLE
Biicode badges?

### ISSUE THREAD

**Issue by LB--** [badges/shields#537]
I just found this and noticed there's no [biicode](https://www.biicode.com/) badges that I could see.

Some example biicode badges:
* ![](https://webapi.biicode.com/v1/badges/LB/LB/events/master)
* ![](https://webapi.biicode.com/v1/badges/biicode/biicode/boost/master)
* ![](https://webapi.biicode.com/v1/badges/adafruit/adafruit/gfx_library/master)
* ![](https://webapi.biicode.com/v1/badges/florianwolters/florianwolters/uncopyable/master)

Whatever generates the badges doesn't always calculate the correct amount of space needed for the text.

**Comment by espadrine** [comment]
Thanks for the suggestion!

Can't find a public API, but this might be a start? https://github.com/biicode/bii-server/blob/master/rest/api_v1.py Cannot find anything about /badges/ however.

**Comment by LB--** [comment]
I'm closing this because [Biicode is dead](http://blog.biicode.com/biicode-just-the-company-post-mortem/).
