### ISSUE TITLE
VS Code Marketplace "Released On" and "Last Updated"  Badge

### ISSUE THREAD

**Issue by YashTotale** [badges/shields#5372]
:clipboard: **Description**

- The badges are for the Visual Studio Code Marketplace
- The badges should show the date an extension was released on and when it was last updated
- Examples:
  - ![Released On Badge](https://img.shields.io/static/v1?label=Released%20On&message=Jul%2031%202020)
  - ![Last Updated Badge](https://img.shields.io/static/v1?label=Last%20Updated&message=Jul%2031%202020)

:link: **Data**

- In [this file](https://github.com/badges/shields/blob/master/services/visual-studio-marketplace/visual-studio-marketplace-base.js), there is a function that makes requests to the VS Code Marketplace API. 
- Testing out the request myself, I see that the release date and the last updated date are returned in the response. This information can be used to create a "Released On" badge and a "Last Updated" badge.

:microphone: **Motivation**

- There is no clear way to see when an extension was released or last updated in VS Code.
- This info is only shown in tiny characters on the VS Code Marketplace website.
- When downloading an extension, a user would want to know if the creators are still actively working on the extension. These two badges could help with delivering that information easily.

<img width="1151" alt="Screen Shot 2020-07-31 at 11 11 32 AM" src="https://user-images.githubusercontent.com/30784592/89064439-db4da580-d31e-11ea-96f2-8585d8d2cac0.png">

**Comment by calebcartwright** [comment]
Thanks for the request @YashTotale, would you be interested in trying to implement support for these badges? Sounds like you may already be half way there anyway :smile: 

We're available to assist with any questions that may come up here and/or in Discord

**Comment by YashTotale** [comment]
Yeah, that sounds great. I'll start tomorrow.

**Comment by YashTotale** [comment]
@calebcartwright I have created a pull request for the "Release Date" badge: #5387

**Comment by YashTotale** [comment]
@calebcartwright I have created a pull request for the "Last Updated" badge: #5388

**Comment by rmsy** [comment]
It seems this issue was not properly linked to #5388, and can now be closed, seeing as that PR was merged.

**Comment by paulmelnikow** [comment]
Thanks!
