### ISSUE TITLE
Github Weekly Commit Activity Badge Not Working

### ISSUE THREAD

**Issue by YashTotale** [badges/shields#5373]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The **github weekly commit activity badge** does not seem to be working.
This is how it looks: 
[![Badge](https://img.shields.io/github/commit-activity/w/YashTotale/terminal-all-in-one?style=for-the-badge&labelColor=000000)](https://img.shields.io/github/commit-activity/w/YashTotale/terminal-all-in-one?style=for-the-badge&labelColor=000000)
This is the real weekly commit activity
<img width="981" alt="Screen Shot" src="https://user-images.githubusercontent.com/30784592/89087840-89227980-d34a-11ea-9cbd-c0f0c220447e.png">

:link: **Link to the badge**
https://img.shields.io/github/commit-activity/w/YashTotale/terminal-all-in-one?style=for-the-badge&labelColor=000000

:bulb: **Possible Solution**

😕 

_Note: Monthly (sometimes it's invalid) and Yearly badges work_

**Comment by calebcartwright** [comment]
I suspect this largely given by the fact that your referenced repository is very new (or at least seems to be). The GitHub API provides a year's worth of weekly commit data, and your repository is still in its first week of having commits. 

https://api.github.com/repos/YashTotale/terminal-all-in-one/stats/commit_activity
https://developer.github.com/v3/repos/statistics/#get-the-weekly-commit-activity
https://github.com/badges/shields/blob/master/services/github/github-commit-activity.service.js#L88

I suspect you'll start seeing expected data within the next couple days

**Comment by YashTotale** [comment]
Thanks!
