### ISSUE TITLE
Update Simple-Icons

### ISSUE THREAD

**Issue by adamalston** [badges/shields#5395]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

Icon is not showing on the badge. The production version of simple-icons is not up to date.

:link: **Link to the badge**

`![Dark Reader](https://img.shields.io/badge/-Dark&#160;Reader-000000?style=flat&logo=Dark-Reader&logoColor=FFFFFF)`

 ![Dark Reader](https://img.shields.io/badge/-Dark&#160;Reader-000000?style=flat&logo=Dark-Reader&logoColor=FFFFFF) 

:bulb: **Possible Solution**

Update simple-icons to 3.4.0 in production.

---

Prior analogous issue: #5363

**Comment by calebcartwright** [comment]
Thanks, but going to close this and refer you to https://github.com/badges/shields/discussions/5369
