### ISSUE TITLE
All shields down

### ISSUE THREAD

**Issue by RIAEvangelist** [badges/shields#540]
They are all broken.

![down shields](http://i.imgur.com/KNKnq3F.png)

**Comment by espadrine** [comment]
Thanks for notifying us! It should be fixed now.

**Comment by SimenB** [comment]
Down now as well.

![image](https://cloud.githubusercontent.com/assets/1404810/10185101/b2084e46-6744-11e5-8e38-963d81bfe7fa.png)

**Comment by espadrine** [comment]
Thanks! It's up again. I have a couple of ideas of what may be causing this, I'll try exploring them.

**Comment by RIAEvangelist** [comment]
should issue remain open in that case?

**Comment by espadrine** [comment]
There is more information and history here, if you want to subscribe: https://github.com/badges/shields/issues/481

**Comment by RIAEvangelist** [comment]
thanks

**Comment by arcanedev-maroc** [comment]
@espadrine the badges are down again

**Comment by espadrine** [comment]
@arcanedev-maroc Thanks for noticing. It restarted itself automatically. It seems to have been caused by an oom-kill.

**Comment by bogdanRada** [comment]
it is down again. Currently getting error 522

**Comment by espadrine** [comment]
Yet again, it seems that it restarted itself.
