### ISSUE TITLE
Badge for Total PowerShell Gallery Downloads from all published modules.

### ISSUE THREAD

**Issue by matthewjdegarmo** [badges/shields#5417]
:clipboard: **Description**
With the release of GitHub Profile README's, It would be nice to have a single badge to show your total PowerShell Gallery downloads from all of your published PowerShell Gallery Modules.

Something like |Total PowerShell Gallery Downloads| 2k|

I know there are great badges for single module downloads, but I'm not finding a way to add these values together into a single badge.

:microphone: **Motivation**
This would be nice to show on your GItHub Profile README showing your collective PowerShell Gallery downloads. Each project should have the download badge for themselves.

**Comment by calebcartwright** [comment]
Unless there's an official API endpoint that provides the aggregated stats for a user/owner, this seems like something that would probably be best handled via our [Endpoint badge](https://shields.io/endpoint)

**Comment by paulmelnikow** [comment]
Related: #204 #4964

**Comment by matthewjdegarmo** [comment]
I ended up creating an action that combines the individual download amounts, adds them up, and creates the generic https://img.shields.io/badge/<LABEL>-<MESSAGE>-<COLOR>.svg link which replaced the link in my README.md.

So I have what I want without an endpoint. Thank you!

**Comment by calebcartwright** [comment]
Great, going to close this then!
