### ISSUE TITLE
Inconsistent NuGet shield

### ISSUE THREAD

**Issue by qujck** [badges/shields#542]
Captain, we're seeing some strange NuGet readings on the shields:

[The readings](https://img.shields.io/nuget/dt/SimpleInjector.svg) are fluctuating between 234K and 249K

![shields2](https://cloud.githubusercontent.com/assets/4510990/10202943/344b28cc-67ab-11e5-8d5b-9d7a5ebfd515.png)

**Comment by espadrine** [comment]
It ought to match this result, which comes fresh from nuget.org:

```bash
curl -H 'Accept: application/json' "https://www.nuget.org/api/v2/Packages()?\$filter=Id%20eq%20'SimpleInjector'%20and%20IsLatestVersion%20eq%20true" | jq '.d.results[0].DownloadCount'
```

Right now, it seems to correspond. I'm tempted to attribute the inconsistence to a momentary NuGet instability?

**Comment by qujck** [comment]
I repeated every day for a week before raising the issue, I'll post here in the next few days if I see the issue again

**Comment by paulmelnikow** [comment]
Has this problem recurred?

**Comment by paulmelnikow** [comment]
Feel free to open a new issue if this problem recurs.
