### ISSUE TITLE
Add ability to specify badge color without losing dynamic color change

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [badges/shields#5437]
Hello,

Shields are awesome and having these dynamic badges is really cool.
It would be great if we could specify multiple colors for the right side of the badge.

:clipboard: **Description**
I want to change the color of the badge so it fits in with my styling, but I don't want to lose the dynamic color change.   
The GitHub pull requests badge has a default of brightgreen and changes to yellow when PR count > 0.
`/github/issues-pr-raw/:user/:repo`

![](https://img.shields.io/badge/open%20pull%20requests-2-yellow)  
![](https://img.shields.io/badge/open%20pull%20requests-0-brightgreen)

I can change the badge color to black so it fits in with my styling, but then I lose the color change to yellow.
![](https://img.shields.io/badge/open%20pull%20requests-2-yellow?color=black)  
![](https://img.shields.io/badge/open%20pull%20requests-0-brightgreen?color=black)

Could we specify multiple colors as an array, similar to the link parameter?  
`?color=black&color=red` or `?colors=black,red`

That way we could have different colors without losing the dynamic logic.  
`color: issueCount > 0 ? 'yellow' : 'brightgreen'`  

So the end result would be  
![](https://img.shields.io/badge/open%20pull%20requests-2-yellow?color=red)  
![](https://img.shields.io/badge/open%20pull%20requests-0-brightgreen?color=black)

-Christian

**Comment by calebcartwright** [comment]
This is a use case that would be better handled via our [Custom Endpoint badge](https://shields.io/endpoint). You could structure your custom endpoint to fetch the json data from Shields.io, transform as desired, and then add Endpoint badges to your readme (or wherever you're using them) which leverage your endpoint.

**Comment by DavidFrings** [comment]
I have a question to that. Can I change the color of the both states here: 
`https://img.shields.io/twitch/status/USERNAME?style=flat&logo=Twitch&logoColor=%23FFFFFF&label=Twitch%3A&labelColor=%235C16C5`
