### ISSUE TITLE
github-workflow-status: add event parameter

### ISSUE THREAD

**Issue by bastimeyer** [badges/shields#5439]
### Feature request

Currently, the github-workflow-status service doesn't support the event parameter:
https://github.com/badges/shields/blob/4059bdcdfa8b901c8c4c2676ad2fca02ff6b4489/services/github/github-workflow-status.service.js#L71-L74

The problem with this is that by not being able to filter for different events, a wrong build status can be returned. An example for this are scheduled workflow runs which cancel themselves if there's no new commit since the last scheduled run. Those canceled runs are being reported as "failed" by the unfiltered badge. Even if Github would report them as "canceled", the returned build status would be wrong, as it's showing a different event.

What I'm asking for is the addition of the `event` query string parameter, in addition to the already implemented `branch` parameter, so that users can filter for `push` events for example.
https://github.com/badges/shields/blob/4059bdcdfa8b901c8c4c2676ad2fca02ff6b4489/services/github/github-workflow-status.service.js#L74

Thank you!

**Comment by calebcartwright** [comment]
Are you sure that the native GitHub Workflow Status badges support filtering by events? Our badges are currently using an SVG scraping implementation, so we're explicitly constrained by the upstream options.

**Comment by bastimeyer** [comment]
Yes, you can check that when trying to create a new badge on a workflow page.

Click the breadcrumb button here for example:
https://github.com/badges/shields/actions?query=workflow%3A%22Run+service+tests%22

**Comment by calebcartwright** [comment]
Excellent, thank you!
