### ISSUE TITLE
Travis CI Badges returning "Invalid"

### ISSUE THREAD

**Issue by montanaflynn** [badges/shields#544]
Two of my repos using Travis CI and shields.io ([Toy Spelling Corrector](https://github.com/montanaflynn/toy-spelling-corrector) and [Stats](https://github.com/montanaflynn/stats)) are both showing "Build: Invalid".

I also saw this on the http://shields.io website for a minute but on refresh it went back to normal. I noticed that the example URL has the username / repo in uppercase, which I believe was not always the case.

**Comment by espadrine** [comment]
It is unclear as of yet what causes this. After all, I am literally downloading their badge currently. I presume it is some kind of rate limiting. I will pursue my investigation in https://github.com/badges/shields/issues/528.
