### ISSUE TITLE
The badge of Codecov doesn't get updated

### ISSUE THREAD

**Issue by wehs7661** [badges/shields#5457]
- [x] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
Hi Codecov developers, 
Recently I've found that my badge of Codecov in the master branch hasn't been updated for a while even if my code coverage actually changed. I'm not entirely sure if I should do anything according to the refactored implementation of Codecov, as indicated in issue #703 . Could you confirm if this is a solvable problem? Sorry if this is a naive question. Thanks!

(This is the repository that I've been working on: https://github.com/wehs7661/alchemistry_toolkit)

:link: **Link to the badge**
Here is the link to my badge: https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master/graph/badge.svg

**Comment by calebcartwright** [comment]
I'm not entirely clear what the issue or question is in reference to. This repo is for Shields.io, not Codecov.

If you have a question or issue with the Codecov service, that needs to be taken to Codecov.

The Codecov service is showing the coverage for your master branch as 96% 
https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master

Accordingly, the badge provided by the Codecov service shows 96%
https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master/graph/badge.svg
![](https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master/graph/badge.svg)

The badge Shields.io provides for coverage from Codecov also shows 96%
https://img.shields.io/codecov/c/github/wehs7661/alchemistry_toolkit
![](https://img.shields.io/codecov/c/github/wehs7661/alchemistry_toolkit)

**Comment by wehs7661** [comment]
Hi @calebcartwright, thank you for your reply and sorry I might have referred to the wrong repo.
However, you can see in your own command, even if https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master/graph/badge.svg shows 96%, the badge in Markdown (either your own comment or my README) shows 62%. This seems to be an issue of Codecov though. Maybe I'll try putting the one that Shields.io provides in my README. Thanks!

**Comment by calebcartwright** [comment]
> However, you can see in your own command, even if https://codecov.io/gh/wehs7661/alchemistry_toolkit/branch/master/graph/badge.svg shows 96%, the badge in Markdown (either your own comment or my README) shows 62%.

In my own command? Again, I don't know what you're referring to. I said the badges were showing as 96% because they are showing as 96% :smile: 

![image](https://user-images.githubusercontent.com/13042488/91646014-7f0a9e00-ea10-11ea-87ba-13a5dd07aa3e.png)

And then in your repo's readme

![image](https://user-images.githubusercontent.com/13042488/91646020-9fd2f380-ea10-11ea-8220-adfb466d2c58.png)

If you're seeing something else (and screenshots would be helpful), then maybe it's an issue with your system/browser?

**Comment by wehs7661** [comment]
Sorry by "command" I meant comment, it was a typo. Before you replied, I've replaced the badge on my repo with the one provided by Shield.io instead of Codecov, which showed the correct code coverage, but now the badges shown in your comments are also exhibiting 96%, so I think there might be just an issue with my browser. Thank you for your reply and I think maybe we could close the issue if there is nothing else weird! :smiley:

**Comment by calebcartwright** [comment]
> Thank you for your reply and I think maybe we could close the issue if there is nothing else weird! smiley

Thanks for confirming, glad it's working for you now!
