### ISSUE TITLE
Badge request: Localizely

### ISSUE THREAD

**Issue by lzoran** [badges/shields#5470]
:clipboard: **Description**

The [Localizely](https://localizely.com/) is a translation management system (TMS) that helps teams to automate, manage, and translate content.

It would be nice to have badges for this platform for showing overall and per-language translation progress.
Translation progress here represents a number of translations that are marked as reviewed.

Examples (static badges):

[![Localizely](https://img.shields.io/badge/localized-98%25-green)](https://app.localizely.com/)
[![Localizely](https://img.shields.io/badge/English%20(US)-100%25-brightgreen)](https://app.localizely.com/)
[![Localizely](https://img.shields.io/badge/German-96%25-green)](https://app.localizely.com/)

:link: **Data**

There is a public API for fetching the data.

The API requires:
- project id
- user read-only API token
- branch name (optional)

API documentation: https://api.localizely.com/swagger-ui.html#/Translation_Status_API

Example (API usage):

```
curl -X GET "https://api.localizely.com/v1/projects/84498921-8d05-4327-9e41-bdda5deb11fe/status" -H  "accept: */*" -H  "X-Api-Token: 158e1dc48121415d9a19408923184117ef40be841f014d72bc72c0198fe66372"
{
  "strings": 5,
  "reviewedProgress": 60,
  "languages": [
    {
      "langCode": "en-US",
      "langName": "English (US)",
      "strings": 5,
      "reviewed": 3,
      "reviewedProgress": 60
    },
    {
      "langCode": "de",
      "langName": "German",
      "strings": 5,
      "reviewed": 3,
      "reviewedProgress": 60
    }
  ]
}
```

:microphone: **Motivation**

It would be nice if we could easily show these badges to the potential users and contributors of the open-source projects. That way we would provide simple insight into the current state of the project and potentially new ideas and contributions.

(Note, in case you agree, I'm willing to implement this.)

**Comment by chris48s** [comment]
Sounds good. We'd be happy to review a PR for this. There's a tutorial for creating new badges at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md
