### ISSUE TITLE
Badges for Google Chrome Web store rating not working

### ISSUE THREAD

**Issue by jinliming2** [badges/shields#5475]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Google Chrome Web Store rating badges seems not working since a few weeks ago.

:link: **Link to the badge**

https://img.shields.io/chrome-web-store/rating-count/oenllhgkiiljibhfagbfogdbchhdchml.svg
![]( https://img.shields.io/chrome-web-store/rating-count/oenllhgkiiljibhfagbfogdbchhdchml.svg )

https://img.shields.io/chrome-web-store/rating/oenllhgkiiljibhfagbfogdbchhdchml.svg
![]( https://img.shields.io/chrome-web-store/rating/oenllhgkiiljibhfagbfogdbchhdchml.svg )

https://img.shields.io/chrome-web-store/stars/oenllhgkiiljibhfagbfogdbchhdchml.svg
![]( https://img.shields.io/chrome-web-store/stars/oenllhgkiiljibhfagbfogdbchhdchml.svg )

**Comment by PyvesB** [comment]
Hello @jinliming2,

Thanks for bringing this to our attention. Indeed, the two rating badges seem broken, [our daily tests](https://app.circleci.com/pipelines/github/badges/daily-tests/448/workflows/b07ad5a4-ed0c-469d-a135-c1f6414599b5/jobs/1346) are failings as well. From what I can tell, this is not a problem on the Shields.io side, but rather on one of our dependencies, [node-chrome-web-store-item-property](https://github.com/pandawing/node-chrome-web-store-item-property). I've tried the CLI tool from the same project, and here's the response I get for one of my own extensions:
```
{
  "name": "Night Video Tuner",
  "url": "https://chrome.google.com/webstore/detail/night-video-tuner/ogffaloegjglncjfehdfplabnoondfjo",
  "image": "https://lh3.googleusercontent.com/8KXkv8O7oRTruQpcsJvjX4YsoQKGw96NWfYgT306r-XGnHjmYNJ-2Pnikcpb2CbbQMrXB-NAbA=w128-h128-e365-rj-sc0x00ffffff",
  "version": "1.1.0",
  "price": "0",
  "priceCurrency": "USD",
  "interactionCount": {
    "UserDownloads": 605
  },
  "operatingSystem": "Chrome",
  "id": "ogffaloegjglncjfehdfplabnoondfjo"
}
```

As you can see, the rating information is no longer returned. Could you please raise an issue on that upstream project's repository?

**Comment by chris48s** [comment]
I've raised an issue on the upstream repo: https://github.com/pandawing/node-chrome-web-store-item-property/issues/275

But also, we are missing some error handling here. We should be throwing an `InvalidResponse` in this case, not rendering badges with `undefined`, `NaN` etc on them

**Comment by chris48s** [comment]
Looks like node-chrome-web-store-item-property will just drop the `ratingCount` and `ratingValue` properties, so I guess we just need to deprecate these badges

**Comment by sanemat** [comment]
Hi there.

Google changed the html of chrome web store. So it's not easy to return `ratingCount` and `ratingValue`.
https://github.com/pandawing/node-chrome-web-store-item-property/issues/275#issuecomment-687801815

**Comment by PyvesB** [comment]
Is there a case for pinging Google about this? It's a long shot, but I know there's a support email for the Chrome Web store - I used it once for a problem with one of my browser resources, a human part of the team responded and was helpful. If we expose our use case, i.e. ~15k daily badges impacted, as well as many other integrations relying on that bit of metadata they removed, there's a chance they may revert. And even if they don't do it, it's always a good reminder for them to provide a proper API.
