### ISSUE TITLE
Find In Page

### ISSUE THREAD

**Issue by lkiran5080** [badges/shields#5476]
:clipboard: Use Inbuilt "Find in page" search. It can literally save corps hundreds of thousand bucks. Search engine sucks.

:link: https://img.shields.io/badge/Use-Ctrl%20%2B%20F-blue?style=for-the-badge

:microphone: Find in Page Meme

**Comment by calebcartwright** [comment]
Closing this as there is nothing concrete in this request

**Comment by lkiran5080** [comment]
lmao sorrrry XD
