### ISSUE TITLE
Extend service to allow values from http request

### ISSUE THREAD

**Issue by azzlack** [badges/shields#548]
I need to have a badge with values that are only accessible via a http request. (TeamCity build statistics). How about making a form with some input parameters like request url, response type (plain text or json), cache time, response property (if json). The form can then store these settings and generate an url. A request to this generated url will then generate a request to the configured endpoint and the response set as the right side of the badge.

I realize that this might not be a "core" feature, and I'm considering making my own service for this if you do not want that functionality in the core.

**Comment by espadrine** [comment]
Just to be sure I understand what you mean, would that work operationally like that?

```
$ curl http://example.com/something
42
$ xdg-open https://img.shields.io/http/example.com/something.svg?label=something
```

![](https://img.shields.io/badge/something-42-brightgreen.svg)

**Comment by azzlack** [comment]
Yes, that is what I'd like :-)

**Comment by espadrine** [comment]
Do you have an example of a URL we can use like that (one that only returns a single number, or something like that), for demonstration and testing purposes?

**Comment by paulmelnikow** [comment]
@espadrine http://httpbin.org/ is great for stuff like that!

If I understand correctly #820 implements this.

**Comment by paulmelnikow** [comment]
#820 will definitely do that. You can return JSON instead of plain text, and then pick it back out.
