### ISSUE TITLE
The Badge "Libraries.io - Sourcerank" shows wrong data

### ISSUE THREAD

**Issue by Paebbels** [badges/shields#5494]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The badge "sourcerank" from Libraries.io shows in my case a rank of 8, while on Libraries.io, the actual rank is 4.

| Screenshot | Rank calculation |
| ------------ | ------------------ |
| ![image](https://user-images.githubusercontent.com/956109/92324235-25255c00-f040-11ea-92af-d516fc8c6258.png) | ![image](https://user-images.githubusercontent.com/956109/92324308-cf9d7f00-f040-11ea-8569-0e23cb7864e1.png) |

Libraries.io link: https://libraries.io/github/Paebbels/pyAttributes

:link: **Link to the badge**  
Generated URL from shields.io: https://img.shields.io/librariesio/sourcerank/pypi/pyAttributes

![Libraries.io SourceRank](https://img.shields.io/librariesio/sourcerank/pypi/pyAttributes)

:bulb: **Possible Solution**

As this discrepancy exists since days, I would exclude short time image caching.

**Comment by Paebbels** [comment]
This is related to:
* #1532

**Comment by chris48s** [comment]
The corresponding libraries.io link for that badge is https://libraries.io/pypi/pyAttributes

* https://libraries.io/pypi/pyAttributes reports a sourcerank of 11
* https://libraries.io/api/pypi/pyAttributes reports a sourcerank of 11
* https://img.shields.io/librariesio/sourcerank/pypi/pyAttributes reports a sourcerank of 11

so the badge is behaving as expected

**Comment by Paebbels** [comment]
So libraries.io has my "package" listed twice?
* the PyPI package
* the GitHub repository

**Comment by chris48s** [comment]
https://libraries.io/github/Paebbels/pyAttributes is the repository https://libraries.io/pypi/pyAttributes is the package.

Its an oddity of the platform that Libraries.io gives a different sourcerank score to a package and its corresponding source repository. This is true across the board (e.g: https://libraries.io/pypi/requests vs https://libraries.io/github/psf/requests ) but if you want to discuss that in more detail, an issue on https://github.com/librariesio/libraries.io/issues is the place to do that. We don't run libraries.io - we just consume their API.

**Comment by Paebbels** [comment]
@chris48s thanks for the support and clarifying that there are two views and also 2 ranks.
