### ISSUE TITLE
Release shield unreliable

### ISSUE THREAD

**Issue by cortesi** [badges/shields#550]
I recently added a release shield to a project of mine, and I've noticed that it's highly unreliable. It seems to frequently return a 404-not-found error (via the github caching mechanism). Making a direct request to the shields.io svg (https://img.shields.io/github/release/cortesi/devd.svg) shows a "vendor unresponsive" error. 

Now that I'm sensitised to this, I've also started noticing broken release badges on other projects, so it's not just me. Obviously the impression this creates for users is not very good, so I'll be removing the badge soon. 
<img width="475" alt="screen shot 2015-10-27 at 11 53 40 am" src="https://cloud.githubusercontent.com/assets/22544/10744921/5a8c5b76-7ca2-11e5-98ea-61a283fa0418.png">

**Comment by kimwalisch** [comment]
Your badges are awesome but unfortunately they are unreliable. Below are two websites with ugly unloaded badges which I just found:

![screenshot2](https://cloud.githubusercontent.com/assets/4656219/10953670/8bed9236-8349-11e5-929e-62b987faf81d.png)

![screenshot3](https://cloud.githubusercontent.com/assets/4656219/10953675/91d248ea-8349-11e5-95f9-46b4a9b7452e.png)

**Comment by smad2005** [comment]
Same

![shield io](https://cloud.githubusercontent.com/assets/1619549/10973405/00c16528-83e6-11e5-90b3-c68898040748.png)

```
[![GitHub release](https://img.shields.io/github/release/smad2005/poehud.svg)]() 
[![Github Releases](https://img.shields.io/github/downloads/smad2005/poehud/latest/total.svg)](https://github.com/smad2005/PoeHud/releases)

```

**Comment by espadrine** [comment]
Thanks for raising this issue. This is specific to GitHub rate-limiting, which I'll track here: https://github.com/badges/shields/issues/529.
