### ISSUE TITLE
Badge request: Flathub downloads

### ISSUE THREAD

**Issue by tooomm** [badges/shields#5506]
:clipboard: **Description**

- Which service is this badge for e.g: GitHub, Travis CI
Flathub: https://flathub.org
- What sort of information should this badge show?
Download count of a particular package. Currently only a version badge is supported.

- Provide an example in plain text e.g: "version | v1.01" or as a static badge
(static badge generator can be found at https://shields.io)
<kbd>Flathub Downloads | 123.456</kbd>

:link: **Data**

Where can we get the data from?

There is all the data at https://flathub.org/stats/ in various json files.
This page uses the data already: https://klausenbusk.github.io/flathub-stats/

:microphone: **Motivation**

- What is the specific use case?

Showing useful download data like all time, recent month etc. as with other services.

**Comment by chris48s** [comment]
I think the data in the structure at https://flathub.org/stats/ isn't workable for us: In order to query that on-the-fly in the form the data is provided (1 json file per day) we would have to make many network requests to get the stats for a single package over a period of time (i.e: to do downloads for 1 month we'd have to make ~30 requests).

It looks like https://klausenbusk.github.io/flathub-stats/ relies on a GH actions ETL job which runs on a schedule, harvests it all and writes it all back out to github in one-file-per-package format rather than one-file-per-day format: https://github.com/klausenbusk/flathub-stats/tree/gh-pages/data

**Comment by JakobDev** [comment]
There is now a API for that: https://flathub.org/api/v2/stats/{appid}. e.g to query the Stats of Firefox: https://flathub.org/api/v2/stats/org.mozilla.firefox

**Comment by JakobDev** [comment]
I created a Issue at Flathub to ask if it is safe to use. If not, we should take a look at https://klausenbusk.github.io/flathub-stats/ which linked above. We also may have a Problem with the Flathub version Badge, which uses Version 1 of the API.

**Comment by tooomm** [comment]
Thanks for adding this in #7724 @JakobDev! It works nicely. ❤️ 

I'm just wondering why you label it `downloads` if it's "only" `installs`. Downloads is misleading here IMHO, users don't know that flathub differentiates here further.
I think the badge would be more clear and helpful, if installs+updates stats would be combined, or the label states which subsection we display. Looks like in the flathub website repo and related issues (https://github.com/flathub/website/pull/67) it got mentioned as well... and they finally went with `Installs` as seen in the beta, e.g: https://beta.flathub.org/en/apps/details/org.mozilla.firefox
![Untitled](https://user-images.githubusercontent.com/9874850/168266203-320064af-b444-49e1-b0fc-1d1bef279ed7.png)

**Comment by JakobDev** [comment]
When I created the PR, it was ladled downloads. I later only make it work with the API changes. and forgot to change the Label. If that label bothered you too much, you can create a PR to change it.

**Comment by tooomm** [comment]
> I later only make it work with the API changes. and forgot to change the Label.

Nevermind. I just proposed a relabel. Please have a look if I got it right: https://github.com/badges/shields/pull/7958


Others might still want a real download badge (installs+updates) though.

**Comment by calebcartwright** [comment]
> Others might still want a real download badge (installs+updates) though.

Believe we've got another case or two where a service makes a distinction between installs and downloads (VS marketplace badges maybe?), but something I'm puzzled about in this case is that I see no such distinction in the Flathub API response. Are downloads/updates through a different, non-stats related endpoint?

If those data points actually exist I'd suggest creating a new issue to keep track of that ask if it's still of interest

**Comment by tooomm** [comment]
You are right, currently it seems to be various data on installs only in the API as far as I'm aware (total, last month, last week, individual days).

@JakobDev might know more here, he requested other API related stuff in the Flathub repos and runs his own service using them.

**Comment by JakobDev** [comment]
There are no API for the downloads of a App. The only source for the downloads is https://flathub.org/stats/, but it is per Day and not per App, so can't really use that for a Badge. The stats API of Flathub uses the Data from this site.
