### ISSUE TITLE
Stackage badges

### ISSUE THREAD

**Issue by ndmitchell** [badges/shields#551]
It would be nice if there were Stackage badges available along the lines of https://www.fpcomplete.com/blog/2015/10/stackage-badges, as it would be great to get all my badges from the same place, and to use the nice formatting controls available. CC'ing @zudov who wrote those badges, and @snoyberg who is more generally in charge of Stackage.

**Comment by zudov** [comment]
Hi. I considered adding stackage badges to `shields.io`, but at the moment I don't think it's worth it.

Most importantly, the badges on stackage.org rely on the information in stackage database. Thus to support the same badges, shields.io would have to either query some `stackage-server` API (which doesn't really exist yet) or to just redirect the badge requests to `stackage.org`.

First option creates additional overhead (both in terms of performance and amount of code to maintain). Second option doesn't really provide any additional value.

If you don't really need that feature (e.g. you are happy to bump the version in your badge at every new snapshot release) you already can use `shields.io` with url like  `https://img.shields.io/badge/stackage_lts--3-0.5.6.2-green.svg`.
Perhaps adding some visual formatting controls would be useful, but I personally would rather prefer if all/most of the stackage badges were (1) uniform (2) always up-to-date with actual stackage information.

Would be happy to hear some counter-arguments and reconsider my position :)

**Comment by ndmitchell** [comment]
I would expect sheilds.io to query stackage for the information. I am relying on the ability for the version number to be figured out automatically, since that's the whole benefit of badges - inserting dynamically queried content.

There are consistency advantages to sourcing all my badges from the same place, ensuring they all have the same style and customisation. At the moment i have 3 shields.io badges, see for example: https://github.com/ndmitchell/shake#readme . I have also customised all the labels to say what they mean to my project, e.g. instead of Appveyor I say Windows build. For consistency, I probably want `Stackage` rather than `stackage`, which requires a `label` argument (which is customisable with shields.io, and would be nice to add to Stackage, even if it doesn't get added to shields.io).

**Comment by zudov** [comment]
I see, we definitely should add customization options to badges on stackage.org. It would make sense to add all those shields.io features that would make sense with stackage. I'll open an issue there.

If we do that, the addition to `shields.io` probably would become less needed.

Anyway, if someone wants to add the support to `shields.io` I'll be glad to cooperate and provide needed API.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
