### ISSUE TITLE
Add support for colorscheme URL query param

### ISSUE THREAD

**Issue by joseluisq** [badges/shields#553]
Currently, `colorscheme` URL query param is not supported.
https://github.com/badges/shields/blob/master/server.js#L4363

It will be great a `colorscheme` URI param something like:
`https://img.shields.io/bower/v/bootstrap.svg?style=flat-square` **`&colorscheme=blue`**

Regards

**Comment by espadrine** [comment]
Thanks for the suggestion!

There is a similar PR that adds colorA / colorB. Would it cover your use-case?

**Comment by paulmelnikow** [comment]
Related: #349, #547.

Feel free to reopen if you'd like to discuss further.
