### ISSUE TITLE
Problem with Repo Size Badge

### ISSUE THREAD

**Issue by quickgrid** [badges/shields#5541]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

**Update: Now it showing `repo-size` which is smaller than `code-size`, but still problem with double repository exists.**

My repository size badge shows zero yet the other badges seem to work. I had repo with name `CodeLab` which had `repo-size
` badge. I deleted the whole repo and made a new one with same name. Now I am getting size `0 B`. 

I renamed the repo to `Code-Lab` but the repo size did not change. Renamed again to `CodeLab` and now it seems both `CodeLab`, `Code-Lab` are finding a repo even though `Code-Lab` no longer exists.

I tried adding the Shields GitHub application to github account but nothing changed. Changing browser did not help.

:link: **Link to the badge**

Current name,

https://img.shields.io/github/repo-size/quickgrid/CodeLab

https://img.shields.io/github/languages/code-size/quickgrid/CodeLab

Renamed repository(no other repo exist with this name),

https://img.shields.io/github/repo-size/quickgrid/Code-Lab

https://img.shields.io/github/languages/code-size/quickgrid/Code-Lab

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
Hello. Our repo size badge reports the size from `https://api.github.com/repos/<user>/<repo>` and the code size badge sums all the language values from `https://api.github.com/repos/<user>/<repo>/languages`

so the values for the quickgrid/CodeLab badges come from:

* https://api.github.com/repos/quickgrid/CodeLab
* https://api.github.com/repos/quickgrid/CodeLab/languages

and the values for the quickgrid/Code-Lab badges come from:

* https://api.github.com/repos/quickgrid/Code-Lab
* https://api.github.com/repos/quickgrid/Code-Lab/languages

There is a bit of extra info on the difference between 'code size' and 'repo size' at https://github.com/badges/shields/issues/2153

It looks like we are reporting those numbers from the API correctly. If you think there is a problem with those API responses you can raise an issue with github support.Ta

**Comment by quickgrid** [comment]
Thank you for your quick response. Now it makes sense about code size difference. It seems GitHub redirected old repo name to new name for compatibility that's why both were working. Size issue also seems on GitHub side could be due to reasons given here, https://github.com/harshjv/github-repo-size/issues/33.
