### ISSUE TITLE
Hacktoberfest 2020 Badge

### ISSUE THREAD

**Issue by vinitshahdeo** [badges/shields#5545]
:clipboard: **Description**

The current Hacktoberfest badge is for Hacktoberfest 2019. There's no option to change the year - `2019` is hardcoded.

![Screenshot 2020-09-15 at 10 55 34 AM](https://user-images.githubusercontent.com/20594326/93169118-0ad73680-f742-11ea-83f7-570c58239b60.png)

![GitHub Hacktoberfest combined status](https://img.shields.io/github/hacktoberfest/2019/vinitshahdeo/PortScanner)

:link: **Data**

This badge was already implemented in 2019, I hope the APIs exist with you.

:microphone: **Motivation**

Having a Hacktoberfest countdown badge will be great as [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) is approaching us.

**Comment by calebcartwright** [comment]
Just a heads up @vinitshahdeo that the badge for 2020 is live now and available

https://img.shields.io/github/hacktoberfest/2020/badges/shields?label=hacktoberfest%202020
[![Hacktoberfest 2020](https://img.shields.io/github/hacktoberfest/2020/badges/shields?label=hacktoberfest%202020)](https://github.com/badges/shields/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest)

https://img.shields.io/github/hacktoberfest/2019/badges/shields?label=hacktoberfest%202019
[![Hacktoberfest 2019](https://img.shields.io/github/hacktoberfest/2019/badges/shields?label=hacktoberfest%202019)](https://github.com/badges/shields/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest)
