### ISSUE TITLE
New service: winget

### ISSUE THREAD

**Issue by chris48s** [badges/shields#5548]
:clipboard: **Description**

TIL Microsoft are currently previewing winget: a package manager for Windows (a bit like Chocolatey or Scoop, but first-party). https://github.com/microsoft/winget-cli This might gain some traction, or it might be bit of a zune but the fact that it is the MS "blessed" solution to a real problem does make this noteworthy.

Manifest yaml format: https://github.com/microsoft/winget-pkgs#authoring-a-manifest
This would allow us to produce license/version badges.

:link: **Data**

Registry-wise they seem to be going down the cocoapods route where all the package manifests live in a big GH repo: https://github.com/microsoft/winget-pkgs

Somewhat unclear how stable/subject to change this all is.

:microphone: **Motivation**

I don't especially want to use this myself because :penguin: but I figure its useful to have a tracking issue for it.

**Comment by sitiom** [comment]
2 years later, any updates?

**Comment by chris48s** [comment]
Nope - still open if anyone would like to work on it.

**Comment by sitiom** [comment]
Meanwhile, here is a workaround by manually creating a custom query to Repology. Here is an example with [ElectronMail](https://repology.org/project/electronmail/versions):

```
![Winget version](https://img.shields.io/badge/dynamic/xml?label=Winget&prefix=v&query=%2F%2Ftr%5B%40id%3D%27winget%27%5D%2Ftd%5B3%5D%2Fspan%2Fa&url=https%3A%2F%2Frepology.org%2Fproject%2Felectronmail%2Fversions)
```

![Winget version](https://img.shields.io/badge/dynamic/xml?label=Winget&prefix=v&query=%2F%2Ftr%5B%40id%3D%27winget%27%5D%2Ftd%5B3%5D%2Fspan%2Fa&url=https%3A%2F%2Frepology.org%2Fproject%2Felectronmail%2Fversions)

**Comment by calebcartwright** [comment]
Thanks for sharing @sitiom!

It's highly unlikely that any of us maintainers will ever work on this, so it's only likely to ever come to fruition if someone from the community works on it. We've got a good [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that walks through the process of adding a badge if you or anyone else is interested

**Comment by jcs090218** [comment]
Any update on this? 🤔

**Comment by PyvesB** [comment]
> Any update on this? 🤔

As outlined by other maintainers:

> Nope - still open if anyone would like to work on it.

> It's highly unlikely that any of us maintainers will ever work on this, so it's only likely to ever come to fruition if someone from the community works on it. We've got a good [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that walks through the process of adding a badge if you or anyone else is interested
