### ISSUE TITLE
Pypi/pyversions not working for my project

### ISSUE THREAD

**Issue by 12944qwerty** [badges/shields#5550]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I'm trying to make a pyversion badge for my [pypi project](https://github.com/SnowballSH/ColorPalette) but I keep getting the `python|missing` type of badge instead. I'm looking for it like this: [http://img.shields.io/pypi/pyversions/.....svg](http://img.shields.io/pypi/pyversions/color_palette.svg) replacing the `......` with the project name, (replacing the dashes with underscores, and following the query string parameters) but I keep getting 404. 

:link: **Links**
[Pypi](https://pypi.python.org/pypi/color-palette/)
[Github](https://github.com/SnowballSH/ColorPalette)

How do I get the pyversions for my project?

**Comment by paulmelnikow** [comment]
Hi, thanks for the report. Our implementation reads trove classifiers (e.g. https://github.com/lace/vg/blob/ba4dc7f1418ef2b578237bdd557b1816af29b62f/setup.py#L39), not the [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) field – which I actually haven't seen before!

Probably it would be a good idea to support `python_requires` and fall back to trove classifiers when it's not specified.

Unfortunately `python_requires` doesn't use a SemVer range but a custom format so we'd have to implement parsing for that or find a library that does.

In the short term you could add the classifier and republish.

**Comment by 12944qwerty** [comment]
I will not be able to add support for that, unfortunately. I don't have much experience with javascript, and definitely not back-end javascript, so I wouldn't know how to add support for this. 

I will add the classifiers though, thank you!

**Comment by 12944qwerty** [comment]
Hi, I updated the [https://github.com/SnowballSH/ColorPalette/blob/master/setup.py#L31](classifiers) but I reloaded and did the different project names but I still got 404.

**Comment by 12944qwerty** [comment]
Question, the pypi projects look at the pypi website instead of github right? That may be why it's not working.....

Is there a way to change that?

**Comment by calebcartwright** [comment]
> Hi, I updated the [classifiers](https://github.com/SnowballSH/ColorPalette/blob/master/setup.py#L31) but I reloaded and did the different project names but I still got 404.

Did you republish your project after you made the update?

> Question, the pypi projects look at the pypi website instead of github right?

Yes, our pypi badges are based on the data from packages on pypi. 

> Is there a way to change that?

This is intentional. People can use whatever source control system they want to develop their packages that they then publish to PyPI, whether that's GitHub, Gitlab, Bitbucket, etc. So no, we cannot (and do not want to) change this badge. The easiest thing for you to do here would be to publish an updated version of your package.

**Comment by 12944qwerty** [comment]
Ok, thank you!

I believe this issue is closed now so I'll close it 👍
