### ISSUE TITLE
Customize "red" and "green" color for build status

### ISSUE THREAD

**Issue by jhpratt** [badges/shields#5557]
Semi-related: #4396

Would it be possible to set a custom color for "red" and "green" for the build status? I have a certain preference for pastel/muted colors, and the current colors "pop" a bit much for my liking. It is also inconsistent with the other badges I have adjacent to the build status.

**Comment by calebcartwright** [comment]
> It is also inconsistent with the other badges I have adjacent to the build status.

Which other badges are these? Are they Shields.io badges, and if so are they static badges with custom colors?

> Would it be possible to set a custom color for "red" and "green" for the build status?

I think we're unlikely to support this given the goals of the project, very similarly to why #4396 was declined. Your best bet would probably be to utilize our [Custom Endpoint badge](https://shields.io/endpoint)

**Comment by jhpratt** [comment]
Yes, they are shields.io badges with custom colors.

If the goal is standardization, why support custom colors at all? Having to implement (and host!) an endpoint seems like quite an extreme measure just to change a color.

**Comment by calebcartwright** [comment]
> If the goal is standardization, why support custom colors at all?

There's a difference between static badges which allow users to create whatever they want, and dynamic badges for certain categories (like build status) that have the consistency goal. You can't really compare the flexibility of the static badges with the core badge offering.

> Having to implement (and host!) an endpoint seems like quite an extreme measure just to change a color.

I don't see it that way. All an endpoint would need to do is call Shields.io with the `.json` extension (like https://img.shields.io/appveyor/build/gruntjs/grunt.json), and then look at the `value` or `message` response to apply whatever color you wanted, really just a couple lines of code. As mentioned in the linked Endpoint docs, it's really easy (and free!) to make that code available with environments like [RunKit](https://runkit.com/docs/endpoint)

> It is trivial in almost any framework, and is more compatible with hosting environments such as RunKit endpoints

**Comment by jhpratt** [comment]
I was aware of neither RunKit nor the JSON API; I naïvely assumed that I'd have to reimplement the full API myself. I'll give it a shot and see how difficult it is (it's been a while since I've used JavaScript for a server).

It still seems a bit wasteful on the shields.io end, as two requests will be performed instead of one, but that's also not my issue 🙂
