### ISSUE TITLE
Cocoa pods badges say "Invalid"

### ISSUE THREAD

**Issue by evgenyneu** [badges/shields#557]
Hi, not sure if this is the right repository for this.
All my cocoa pods badges say "invalid" today.

https://img.shields.io/cocoapods/v/Auk.svg?style=flat

**Comment by espadrine** [comment]
This is absolutely the right repository for this. It looks like this may have been a temporary issue on CocoaPod's side? The badge works now. I'll keep this in mind if this happens again.

**Comment by pavankataria** [comment]
How do you provide colours 
Given the following example:
https://img.shields.io/cocoapods/l/SwiftDataTables.svg?style=flat

Trying to make it green like so:
https://img.shields.io/cocoapods/l/SwiftDataTables-green.svg?style=flat or
https://img.shields.io/cocoapods/l/SwiftDataTables.svg?style=flat&color=green
both render the badge to read `POD|Invalid`

Any ideas?

**Comment by paulmelnikow** [comment]
The CocoaPods appears to be resolved.

Hi @pavankataria, could you open a new issue with your question?
