### ISSUE TITLE
Moment.js Maintenance Mode Announcement

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5573]
Some interesting news on Moment.js being deprecated (sort of). I don't see a need for any action, at least in the short term, given that they've said they'll continue to address security issues. However, opening for awareness and discussion.

https://momentjs.com/docs/#/-project-status/

> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.

> In practice, this means:

>    - We will not be adding new features or capabilities.
>    - We will not be changing Moment's API to be immutable.
>    - We will not be addressing tree shaking or bundle size issues.
>    - We will not be making any major changes (no version 3).
>    - We may choose to not fix bugs or behavioral quirks, especially if they are long-standing known issues.

> However, since we understand that Moment is well established in millions of existing projects:

>   - We will address critical security concerns as they arise.
>   - We will release data updates for Moment-Timezone following IANA time zone database releases.

**Comment by chris48s** [comment]
Yeah I also spotted this the other day. I'd agree with your perspective. There is no rush to migrate given it will continue to receive security updates. That said, our usage of moment is pretty light: we require it in less than 10 files, we're not heavily tied to it by another dependency which forces us to use it, and its not part of our service framework so if we do want to migrate to _something else_ its not an enormous job like request is, for example.

**Comment by paulmelnikow** [comment]
Yea, it should be an easy swap.

I'm curious, does anyone have experience with Day.js or the other alternatives?

**Comment by calebcartwright** [comment]
> I'm curious, does anyone have experience with Day.js or the other alternatives?

Nope, I've only ever used Moment

**Comment by calebcartwright** [comment]
Nearly 2 years on and updates are still coming (albeit small and far between) #8170

**Comment by chris48s** [comment]
Yes - moment does still receive major bugfixes, just not active development. It is one of the reasons why migrating away from it has fallen by the wayside (another being that it is not completely obvious what to migrate _to_ ).

**Comment by DenverCoder1** [comment]
dayjs has a very similar API to moment so is likely the easiest to migrate to. I've migrated from moment to dayjs before and for many things it's as simple as just replacing `moment()` with `dayjs()`.
