### ISSUE TITLE
Add instructions to adding to HTML and Markdown

### ISSUE THREAD

**Issue by techboyg5** [badges/shields#5577]
Instructions for adding the badges to HTML and Markdown should be added.

HTML:

    <a href="https://github.com/badges/shields"><img src="https://img.shields.io/badge/GitHub-Star-blue?logo=github" alt="Star on GitHub"></a>

Markdown:

    [![Star on GitHub](https://img.shields.io/badge/GitHub-Star-blue?logo=github)](https://github.com/badges/shields)

Both of which make the following badge:

[![Star on GitHub](https://img.shields.io/badge/GitHub-Star-blue?logo=github)](https://github.com/badges/shields)

**Comment by calebcartwright** [comment]
The Shields.io website actually will generate this (as well as rst and asciidoc) for you, but I'm not entirely convinced that it's Shields responsibility to provide educational material to folks on how to add images in html or markdown. 

![image](https://user-images.githubusercontent.com/13042488/93717452-9e8e7580-fb3b-11ea-918f-066d2e7a20f5.png)

**Comment by techboyg5** [comment]
I still think that adding something like in the first comment into the main page would be a good idea.

**Comment by calebcartwright** [comment]
> I still think that adding something like in the first comment into the main page would be a good idea.

I understand what you're asking for, but I respectfully disagree. The main and target audience for our service are technologists and developers, and adding this type of common, basic, content would only add unnecessary noise in a place where we already have challenges with users finding Shields specific content (like the endpoint and dynamic builders and docs).

99% of the consumers of Shields.io will already know how to embed an image, or can easily figure out how to do so via a quick Google search. 

I'd probably be okay with something like a [discussion](https://github.com/badges/shields/discussions) that includes some of this information which users could reference (even though there's myriad information readily available and discoverable elsewhere, but I'm strongly opposed to injecting "how to embed an image in html" type of material on the Shields.io site

**Comment by techboyg5** [comment]
Got it! Closing now.
