### ISSUE TITLE
Unparseable jsonpath query error on dynamic json badge

### ISSUE THREAD

**Issue by Haeri** [badges/shields#5580]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I am getting an `unparseable jsonpath query` error when trying to access a variable with a `-` inside.

:link: **Link to the badge**

Accessing `version-string` doesn't work
`https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$.version-string&color=blue`
![version](https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$.version-string&color=blue)

Even though accessing the `name` works fine for the same json
`https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$.name&color=blue`
![version](https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$.name&color=blue)

Here the simple json:
```
{
  "name": "elemd",
  "version-string": "0.0.1",
  "homepage": "",
  "description": "Portable C++ canvas library with a Vulkan backend. ",
  "dependencies": ["glfw3", "glslang", "stb", "freetype"]
}
```

**Comment by hemantsonu20** [comment]
Hi @Haeri can you try `https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$['version-string']&color=blue`
![](https://img.shields.io/badge/dynamic/json?url=https://raw.githubusercontent.com/Haeri/ElementalDraw/master/vcpkg.json&label=version&query=$['version-string']&color=blue)

hyphen in key `version-name` might be causing the issue, so you can try ~~`$.version-string`~~ `$['version-string']`

**Comment by Haeri** [comment]
Sweet! Thanks, works like a charm!
