### ISSUE TITLE
Github package.json version badge does not work when repo's default branch is "main"

### ISSUE THREAD

**Issue by wdspider** [badges/shields#5584]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The Github package.json version badge does not work when your repo's default branch is `main`

:link: **Link to the badge**

Broken:  https://img.shields.io/github/package-json/v/wdspider/queslarui
Working:  https://img.shields.io/github/package-json/v/wdspider/queslarui/main

:bulb: **Possible Solution**

Add support for a `main` default branch.

**Comment by chris48s** [comment]
This _should_ work. I suspect this line is the culprit:

https://github.com/badges/shields/blob/36395715a5ad3c99893bb94143e108e991d41456/services/github/github-common-fetch.js#L58

but I'll dig into it tomorrow
