### ISSUE TITLE
Add support for Codacy code coverage 

### ISSUE THREAD

**Issue by Lykegenes** [badges/shields#559]
Example URL : `https://api.codacy.com/project/badge/coverage/ff95c3e5360649638c61f2834bffd8b2`

**Comment by espadrine** [comment]
Thanks for the suggestion!

Does that go beyond what was implemented in https://github.com/badges/shields/issues/260? Is `https://img.shields.io/codacy/ff95c3e5360649638c61f2834bffd8b2.svg` what you suggest?

**Comment by Lykegenes** [comment]
Yes, they added it this week.
There is now two different badges : 
- `https://api.codacy.com/project/badge/grade/ff95c3e5360649638c61f2834bffd8b2` The one implemented in Shields. It is a code quality badge.
- `https://api.codacy.com/project/badge/coverage/ff95c3e5360649638c61f2834bffd8b2` The new one, it is a code coverage badge, like Scrutinizer, Code Climate, and many others.
