### ISSUE TITLE
Scrutinizer branches not handled correctly

### ISSUE THREAD

**Issue by leofeyer** [badges/shields#561]
The Scrutinizer integration only handles branches without slashes such as `develop` and fails to handle branches such as `feature/foobar` or `hotfix/foobar`.

```js
camp.route(/^\/scrutinizer\/(.*)\.(svg|png|gif|jpg|json)$/,
```

Other integrations such as Travis-CI or Coveralls use a different regex to handle these branches:

```js
camp.route(/^\/travis(-ci)?\/([^\/]+\/[^\/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)$/,
camp.route(/^\/coveralls\/([^\/]+\/[^\/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)$/,
```

**Comment by leofeyer** [comment]
@jublo @kyrias /cc

**Comment by kyrias** [comment]
Hmm, are you sure that those actually do handle branches with slashes?

**Comment by kyrias** [comment]
Oh, looking closer, the regex has nothing to do with it, it's later in the code it takes care of the branches. I'll look closer and see if I can clean it up somewhat.

**Comment by kyrias** [comment]
And looking even closer than that and at the scrutinizer API docs it seems that `gp` URLs can potentially be multiple formats, hmm... Might have to contact their support for more info.

**Comment by leofeyer** [comment]
>  it's later in the code it takes care of the branches

That is correct. The problematic line is `branch = repoParts[repoParts.length - 1];`, because it assumes that the branch name consists of a single repoPart only. It can contain of multiple repoParts though.

**Comment by kyrias** [comment]
The problem is bigger than just that, it's how the whole section of code works, but it's written that way (presumably) due to how scrutinizer's API works.

**Comment by espadrine** [comment]
@leofeyer Do you have an example nonworking badge to help me reproduce the issue?

**Comment by leofeyer** [comment]
Sure. Working:

```
https://img.shields.io/scrutinizer/g/contao/core-bundle/master.svg
```

Not working:

```
https://img.shields.io/scrutinizer/g/contao/core-bundle/feature/framwork-initializer.svg
```

The latter is due to the branch name being `feature/framwork-initializer`, which the current script does not handle correctly.

**Comment by espadrine** [comment]
Ah, I see the issue here. The `/g/` determines that there are two slashes in the first part `g/contao/core-bundle`, but we don't take into account. Let's.

**Comment by espadrine** [comment]
> Not working:
>
> <https://img.shields.io/scrutinizer/g/contao/core-bundle/feature/framwork-initializer.svg>

![](https://img.shields.io/scrutinizer/g/contao/core-bundle/feature/framwork-initializer.svg)

LGTM. @leofeyer can you confirm?

**Comment by leofeyer** [comment]
Yes, it works now. Thank you @espadrine.
