### ISSUE TITLE
the download number is not right

### ISSUE THREAD

**Issue by litaotao** [badges/shields#565]
project url: [ipython-dashboard](https://pypi.python.org/pypi/IPython-Dashboard)

***downloads in the last month*** from the project page on pypi:

<img width="377" alt="screen_shot 2015-11-17 at 4 59 38 pm" src="https://cloud.githubusercontent.com/assets/4660350/11206847/9f819ba0-8d4c-11e5-96c3-4524613a18d9.png">

***download number using shields***

url: [https://img.shields.io/pypi/dm/ipython-dashboard.svg](https://img.shields.io/pypi/dm/ipython-dashboard.svg)

<img width="552" alt="screen_shot 2015-11-17 at 5 00 30 pm" src="https://cloud.githubusercontent.com/assets/4660350/11206870/bf94af9a-8d4c-11e5-92b8-cec33a351108.png">

I'm a little confused, the  `721`  in `721/month` means 721 in total download in the last month or the 
average download number per month from the first release of this project ?

thanks

**Comment by espadrine** [comment]
We rely on the following data:

```
curl 'https://pypi.python.org/pypi/IPython-Dashboard/json' | jq .info.downloads
```

Currently, it returns 779, and the page returns `780 downloads in the last month`. Perhaps the API returns the value for the latest version, and the page returns the value for all versions?

**Comment by litaotao** [comment]
@espadrine  thanks a lot, I this the  data fetched from `https://pypi.python.org/pypi/IPython-Dashboard/json` does not refresh in real time. or at least the fresh time interval is larger than the refresh time of page `https://pypi.python.org/pypi/IPython-Dashboard` . anyway, it's not a big deal, thanks.
