### ISSUE TITLE
Use docker authentication for CircleCI builds

### ISSUE THREAD

**Issue by chris48s** [badges/shields#5663]
:clipboard: **Description**

:email:  Email from Circle CI:

> [Action Required] How to avoid Docker Hub rate limits for your CircleCI builds
> 
> Hi there,
> 
> On November 1st, [Docker Hub](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) will begin [limiting](https://docs.docker.com/docker-hub/download-rate-limit/) anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
> 
> Adding [Docker authentication](https://circleci.com/docs/2.0/private-images/) to your pipeline config is the easiest way to avoid any service disruptions. If you use the [Docker executor](https://circleci.com/docs/2.0/executor-types/#using-docker) or pull Docker images when using the [machine executor](https://circleci.com/docs/2.0/executor-types/#using-machine) on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
> 
> We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
> 
> For more information or to leave a question for us, please head over to [Discuss](https://discuss.circleci.com/t/authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567) or [contact support](https://support.circleci.com/hc/en-us/requests/new).
> 
> Thanks and happy building,
> 
>   The CircleCI team 

As our builds use the Docker executor we will need to adopt auth.

**Comment by calebcartwright** [comment]
I wonder if the rate limiting will impact any of the API calls we use for our badges

**Comment by chris48s** [comment]
My reading of the docker hub docs is that it only applies to the images themselves, not the JSON API

**Comment by chris48s** [comment]
We didn't do this. 1 Nov came and went and.. nothing happened

Looking at it, Circle CI have put an agreement in place with DockerHub to get round the rate limits: https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ
The advice from Circle is now

> rate limits may go into effect for CircleCI users in the future. That’s why we’re encouraging you and your team to add Docker Hub authentication to your CircleCI configuration and consider upgrading your Docker Hub plan, as appropriate, to prevent any impact from rate limits in the future

so.. they're "encouraging" us to use auth, but for the moment if we don't no bad things with happen. So.. I dunno. Might carry on ignoring it :shrug:

**Comment by paulmelnikow** [comment]
I've not done this in any project, nor run into any problems. Should we close this and reopen if we ever do run into problems?

**Comment by chris48s** [comment]
yes we can close this :+1:
