### ISSUE TITLE
JitPack downloads not available?

### ISSUE THREAD

**Issue by payne911** [badges/shields#5669]
My understanding is that there is an history of problems with the JitPack Downloads badge, but I believe [the latest PR merged was supposed to re-introduce it](https://github.com/badges/shields/pull/3533)?

... yet I don't see the badge featured in [your official GitHub Pages list](https://shields.io/category/downloads).

Is it available or not?

Thanks!

**Comment by paulmelnikow** [comment]
I've just re-deployed. Should be all set.

**Comment by payne911** [comment]
@paulmelnikow maybe I just don't know where to look.

![image](https://user-images.githubusercontent.com/38117856/95386192-ed1e6c80-08bc-11eb-9e28-74ff7170b182.png)

Is it supposed to be the ``GitHub`` ones? Or should it mention ``JitPack`` ?

**Comment by calebcartwright** [comment]
The JitPack Download badges were permanently deprecated, refs #4873. Unfortunately the service APIs were far too unstable and unreliable with no response from the provider for us to continue to provide the badges.

![](https://img.shields.io/jitpack/dw/github/jitpack/maven-simple)

**Comment by payne911** [comment]
I see. Thank you!

May I inquire what ``GitHub All Releases`` corresponds to, then?

**Comment by calebcartwright** [comment]
> May I inquire what `GitHub All Releases` corresponds to, then?

The aggregate count of downloads across all the releases in the GitHub repo, as reported by the GH API

**Comment by payne911** [comment]
> aggregate count of downloads across all the releases in the GitHub repo

That's precisely what I'm not certain about. Which action increases that counter?

It is by clicking [any of the assets of a specific tagged release](https://github.com/payne911/PieMenu/releases/tag/v5.0.0) ?

**Comment by calebcartwright** [comment]
> > aggregate count of downloads across all the releases in the GitHub repo
> 
> That's precisely what I'm not certain about. Which action increases that counter?
> 
> It is by clicking [any of the assets of a specific tagged release](https://github.com/payne911/PieMenu/releases/tag/v5.0.0) ?

This is a question probably best directed to the service, GitHub in this case, and/or their community forums. IIRC, it's driven on the binary assets of a release being downloaded, not a click counter.
