### ISSUE TITLE
Code Climate badges showing 'unknown' and 'not found'

### ISSUE THREAD

**Issue by timkurvers** [badges/shields#567]
Shields.io:

![Code Climate](https://img.shields.io/codeclimate/github/timkurvers/blizzardry.svg?style=flat)
![Test Coverage](https://img.shields.io/codeclimate/coverage/github/timkurvers/blizzardry.svg?style=flat)

Code Climate:

![Code Climate](https://codeclimate.com/github/timkurvers/blizzardry/badges/gpa.svg)
![Test Coverage](https://codeclimate.com/github/timkurvers/blizzardry/badges/coverage.svg)

Similar behaviour on http://shields.io/. Apologies if this was reported previously.

**Comment by hughrawlinson** [comment]
:+1:

**Comment by espadrine** [comment]
Their main website indicates that the whole site is down for maintenance: https://codeclimate.com. Have you contacted them through Twitter?

**Comment by travi** [comment]
that may be the case now, but was not when this issue was filed. shields.io badges for code climate have been showing incorrectly (as above) for a few days, but the ones provided directly from code climate were reporting correctly.

**Comment by espadrine** [comment]
> It appears that we experienced an unexpected spike in db performance that created a bottleneck for a few minutes.

— Nov. 19th, http://status.codeclimate.com

Maybe it is linked?

I'll wait until they resolve their current unscheduled outage to see whether it changes anything.

**Comment by espadrine** [comment]
```
curl -I 'https://codeclimate.com/github/timkurvers/blizzardry.png'
```

`Content-Disposition: inline; filename="/srv/data/codeclimate/app/assets/images/badges/code_climate-4-0.png"`

That is the first time I have seen this HTTP header show up like that. It feels wrong.

I contacted them through Twitter here: https://twitter.com/espadrine/status/668209253577039873.

**Comment by icambron** [comment]
@espadrine that certainly does seem wrong. Seems OK to make the regex a little more accepting, though, right:

 ```js
 var statusMatch = res.headers['content-disposition']
                           .match(/filename="code_climate-(.+)\.png"/);
```

Could just use `.*`

**Comment by timkurvers** [comment]
Thanks, works like a charm! :smile:

**Comment by djperrefort** [comment]
I noticed a few days ago that this problem has started again for some of the code climate badges. An example can be found by looking at [http://shields.io/](http://shields.io/).

**Comment by paulmelnikow** [comment]
Would you please open a new issue? Thanks!

**Comment by paulmelnikow** [comment]
Please also review the open issues: #1329 #1196 #1387.

**Comment by rocketspacer** [comment]
Can we reopen this? I'm encountering it now

**Comment by RedSparr0w** [comment]
@rocketspacer I'm on mobile right now, but i believe this has been fixed (still needs to be deployed), check issue #1518
