### ISSUE TITLE
Some logos from simple-icon doesn't work

### ISSUE THREAD

**Issue by JimiIT92** [badges/shields#5678]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I am creating some badges for a project on Github, and I want one badge to have the CurseForge logo, which can be found on simpleicons.org. However, if I add the `?logo=curseforge` I don't see the logo. I tested with other logos as well, for example KaiOS `?logo=kaios` and it works, so why this specific logo doesn't?

:link: **https://img.shields.io/badge/BundlesMod-1.16.3-success?logo=curseforge**

**Comment by calebcartwright** [comment]
hi @JimiIT92 

Please refer to [this Discussion thread](https://github.com/badges/shields/discussions/5369) for more information about logos and logo updates.

https://github.com/simple-icons/simple-icons/releases/tag/3.11.0
