### ISSUE TITLE
Deprecation of the Tweet count feature

### ISSUE THREAD

**Issue by thekondrashov** [badges/shields#568]
> Update Nov. 20, 2015: we have now shipped the updated Tweet Button and removed the Tweet count endpoint. 

– Source: [twitter blog](https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform)
> The [Twitter REST API's search endpoints](https://dev.twitter.com/rest/reference/get/search/tweets) are the best way to gather ad-hoc information about a URL shared on Twitter.

– Source: [twitter dev forums](https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791)

So for now we cannot get the count and all twitter's badges look like this:
![shields.io](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)

**Comment by espadrine** [comment]
:crying_cat_face: 

[This PR](https://github.com/badges/shields/pull/545) which hopes to introduce a follow Twitter badge tries to allow having no right-hand-side. If the "undefined" right-hand-side isn't shown, this badge can stay.

Unfortunately, the original author has disappeared for a month. Would you be interested in finishing his patch? What remains is to remove the nobubble parameter that he introduced, and change `templates/social-template.svg` to hide the right-hand-side if there is nothing to show.

**Comment by thekondrashov** [comment]
Great idea, but I'm not sure I can do it.
