### ISSUE TITLE
Python 3.9 badge is not shown

### ISSUE THREAD

**Issue by k0t3n** [badges/shields#5695]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
Python 3.9 is not shown using `Python >=3.6, <4.0` condition.

:link: **Link to the badge**
https://img.shields.io/pypi/pyversions/django-split-settings.svg

:bulb: **Possible Solution**

**Comment by paulmelnikow** [comment]
The badge is reading your PyPI classifiers. I took a quick peek and it wasn't clear how you were generating those. To include 3.9 on the badge, you'll need to publish a release with the **Programming Language :: Python :: 3.9** classifier.

See also #5551 which is about using `requires_python` as a fallback.

**Comment by k0t3n** [comment]
Seems that issue on PyPI side.
Thanks.

**Comment by chris48s** [comment]
As noted, the badge uses your classifiers from PyPI.

In your case, poetry generates a list of classifiers for you when you build your package based on your python requirement, but it uses a hard-coded list of valid versions https://github.com/python-poetry/poetry-core/blob/0db07bc81b989c5c4933cf019fec7a4f93fbd744/poetry/core/packages/package.py#L25-L35 if your python requirement is `^3.6` (from https://github.com/sobolevn/django-split-settings/blob/510bfd1a271a92113683e535fa70bc239c3b10c1/pyproject.toml#L48 ) and you're building a package that declares 

```
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
```

(from your `PKG-INFO` on pypi), with `poetry build` then I suspect you are using an outdated version of poetry (which doesn't have 3.9 in the list) and need to update poetry to build the desired package (which will have 3.9 in the list).

**Comment by k0t3n** [comment]
@chris48s thanks a lot for the details!
