### ISSUE TITLE
Package tests fail silently in CI

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#5713]
I was looking at #5696 and had a hard time making sense of the snapshot diff, which seemed like it had totally wrong values in it.

It turns out the snapshot is out of date, and the tests are failing in CI but showing as succeeded.

https://app.circleci.com/pipelines/github/badges/shields/3473/workflows/df50bd0c-8a58-4f20-9a75-9fd279fd6ea1/jobs/121024

One pretty easy way to fix this would be to quit after the first failure, although it would mean not testing any of the subsequent Node versions.

**Comment by calebcartwright** [comment]
Anyone recall why we're using `+e` here? https://github.com/badges/shields/blob/master/.circleci/config.yml#L93

I vaguely remember something related to allowing the tests to fail in a certain configuration but my GitHub search skills are failing me at the moment

**Comment by paulmelnikow** [comment]
I imagine it's to ensure that the cleanup steps run, even when tests fail.

**Comment by calebcartwright** [comment]
> I imagine it's to ensure that the cleanup steps run, even when tests fail.

Which cleanup steps? The removal of the node_modules directory? From what I recall that cleanup step is to give use an extra validation step against the package itself without having the main node_modules repo (we had some dependency related bugs in the package that was intended to catch).

If we use `-e` and bail on failed unit tests, is there any harm in exiting without removing the node modules dir?

**Comment by paulmelnikow** [comment]
Ah, you're right, I think there is not. And since we're using `npm ci` we don't even need the cleanup step.
