### ISSUE TITLE
Inconsistent kerning

### ISSUE THREAD

**Issue by adamalston** [badges/shields#5731]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

### Description
The text kerning on badges is inconsistent.

![test](https://img.shields.io/badge/-🔬&nbsp;test-fff)
URL: https://img.shields.io/badge/-🔬&nbsp;test-fff

![test](https://img.shields.io/badge/-🛰️&nbsp;test-fff)
URL: https://img.shields.io/badge/-🛰️&nbsp;test-fff

The only difference in these 2 badges is the emoji used. Another example below.

![test](https://img.shields.io/badge/-🌎&nbsp;test-fff)
URL: https://img.shields.io/badge/-🌎&nbsp;test-fff

![test](https://img.shields.io/badge/-🗺️&nbsp;test-fff)
URL: https://img.shields.io/badge/-🗺️&nbsp;test-fff

**Comment by paulmelnikow** [comment]
What do the badges look like for you? I’m on iOS and I’m seeing black rectangles on those second sets of emoji.

Letter spacing problems are due to wrong length estimates. My first guess is that whatever emoji you are using is not in the version of Verdana that was used used to generate the width lookup table.

![D6AB64A0-FB0E-480B-B9F3-F306B1A06152](https://user-images.githubusercontent.com/1487036/96359788-d65dee00-10e4-11eb-91d9-2444c19f9be3.png)

(Also, the URLs in your post do not match the badges.)

**Comment by adamalston** [comment]
![Screenshot_2020-10-18 Inconsistent kerning · Issue #5731 · badges shields](https://user-images.githubusercontent.com/18297826/96366033-03c19080-1113-11eb-823e-457d335ef18d.png)

---

Here's the markdown for all 4 of those badges...

![test](https://img.shields.io/badge/-🔬&nbsp;test-fff?)
Markdown: `![test](https://img.shields.io/badge/-🔬&nbsp;test-fff?)`

![test](https://img.shields.io/badge/-🛰️&nbsp;test-fff?)
Markdown: `![test](https://img.shields.io/badge/-🛰️&nbsp;test-fff?)`

![test](https://img.shields.io/badge/-🌎&nbsp;test-fff?)
Markdown: `![test](https://img.shields.io/badge/-🌎&nbsp;test-fff?)`

![test](https://img.shields.io/badge/-🗺️&nbsp;test-fff?)
Markdown: `![test](https://img.shields.io/badge/-🗺️&nbsp;test-fff?)`

Nevertheless, the kerning issue persists.

**Comment by paulmelnikow** [comment]
If you click those links you'll see that you get a different badge.

**Comment by paulmelnikow** [comment]
The second one seems to work correctly if you use an ordinary space:


![](https://img.shields.io/badge/-🛰%20test-fff)

https://img.shields.io/badge/-🛰%20test-fff

It may be that markdown is doing something weird with the `&nbsp;` or else that Shields doesn't correctly handle a nbsp.

In any case I would suggest against embedding HTML entities in your badge URLs. Better to get the badge URL working in your browser, and then paste it into Markdown. The way to encode a space in a URL is `%20`; putting `&nbsp;` into it is indirection through Markdown, and very confusing.

**Comment by adamalston** [comment]
Would you recommend keeping the raw emoji in the URL or encoding them?

**Comment by paulmelnikow** [comment]
Raw emoji are probably more maintainable… so I guess use them if they work?

**Comment by adamalston** [comment]
Thanks for the assistance!
