### ISSUE TITLE
Bitrise.io

### ISSUE THREAD

**Issue by larsbrinkhoff** [badges/shields#574]
[Bitrise](http://www.bitrise.io) is a hosted CI service for MacOS X.

I'm not sure there's a way to get at the build status, but here are the docs:
http://devcenter.bitrise.io/

**Comment by larsbrinkhoff** [comment]
Sample:
![Bitrise](https://www.bitrise.io/app/f60bdf36bd956896.svg?token=_RL3uOO0yD9gE\
ebW-Tqr0g)

**Comment by larsbrinkhoff** [comment]
I don't see anything about an API to get at the build status.  And the build badge HTTP headers doesn't seem to leak any useful info.

Maybe detect green/red in the PNG?

**Comment by Zhukn1** [comment]
If you click on the badge inside Bitrise's dashboard you will be presented with a popup.

Inside the popup you have the option to choose a branch and the link format: ImageURL or Markdown.

This is an example of the Markdown one from one of my repositories:
```[![Build Status](https://www.bitrise.io/app/865b8202a70ccb07.svg?token=pSNcntf_xtpD1glCA31v1g&branch=master)](https://www.bitrise.io/app/865b8202a70ccb07)```

which turns into:

[![Build Status](https://www.bitrise.io/app/865b8202a70ccb07.svg?token=pSNcntf_xtpD1glCA31v1g&branch=master)](https://www.bitrise.io/app/865b8202a70ccb07)

There is a [feature request](https://bitrise.uservoice.com/forums/235233-general/suggestions/9771471-api-call-to-get-a-build-status) for build checking via API, so if you really need it don't hesitate to upvote. The team takes this serious and integrates the most upvoted features rather fast.

**Comment by paulmelnikow** [comment]
Are we still waiting for an API?

**Comment by larsbrinkhoff** [comment]
Supposedly, an API is being implemented:  
https://discuss.bitrise.io/t/bitrise-public-api/37/39

**Comment by larsbrinkhoff** [comment]
Ping @viktorbenei.

**Comment by viktorbenei** [comment]
Thanks for the ping @larsbrinkhoff !

API docs and Token gen coming soon ( https://discuss.bitrise.io/t/bitrise-public-api/37/39?u=viktorbenei ), feel free to comment there, or point me to the docs what you'd need the API to return (and how).

**Comment by paulmelnikow** [comment]
@viktorbenei Most of the services provide an HTTPS GET endpoint to obtain the project status, using the default branch. The endpoint should also allow obtaining the build status of a specific branch. Since the token becomes public, it should be read-only, and ideally be limited to build status.

Cool company! It's good to have more CI options for OS X. 👍

**Comment by viktorbenei** [comment]
Thanks @paulmelnikow ;)

> HTTPS GET endpoint to obtain the project status, using the default branch. The endpoint should also allow obtaining the build status of a specific branch. Since the token becomes public, it should be read-only, and ideally be limited to build status.

That's exactly what we have, but right now only for the badge image (SVG endpoint), it doesn't have a JSON response.

I can schedule a JSON response for the endpoint too - do you have a preferred JSON response/example?

**Comment by paulmelnikow** [comment]
Here's [an example](https://circleci.com/api/v1/project/BrightFlair/PHP.Gt?circle-token=0a5143728784b263d9f0238b8d595522689b3af2&limit=1&filter=completed) I pulled from a link in the source code. We don't need so much, though.

A JSON response with a `status` string is sufficient, e.g. `success`, `failure`, `error`, `no tests`, `never built`. You could throw in the timestamp if you want. The status code should be 200.

When the auth token is bad or the repo is not found, the response should be clearly distinguishable so we can provide a helpful error, like "invalid token or repo not found". To avoid leaking information you may not want to distinguish between these, which is fine. These could be 403.

**Comment by viktorbenei** [comment]
We finally had the time to implement the required changes to the endpoint, and it's now in production. We actually decided to change the URL a little bit. The previous endpoint still exists, but that only supports the SVG badge response, as it did previously.

You can find the API docs here: http://devcenter.bitrise.io/api/app-status-badge/

I think it should cover everything you mentioned @paulmelnikow , if not, just let me know!
