### ISSUE TITLE
Inconsistent build status labels

### ISSUE THREAD

**Issue by larsbrinkhoff** [badges/shields#575]
A successful build status is inconsistently labelled `passing`, `passed`, `success`, and `shippable`.  I haven't checked other statuses such as `failed`, `pending`, etc.  I guess the string is passed straight from the API.

I submit that it would be a moderate improvement if the status was uniform across different services.

Here's a sample.  I hope they are still all succesful... er passing.

![AppVeyor](https://img.shields.io/appveyor/ci/gruntjs/grunt.svg?label=AppVeyor)
![Travis CI](https://img.shields.io/travis/larsbrinkhoff/forth-continuous-integration.svg?label=TravisCI)
![Circle CI](https://img.shields.io/circleci/project/larsbrinkhoff/forth-continuous-integration.svg?label=CircleCI)
![Jenkins](https://img.shields.io/jenkins/s/https/jenkins.qa.ubuntu.com/precise-desktop-amd64_default.svg?label=Jenkins)

![Wercker](https://img.shields.io/wercker/ci/larsbrinkhoff/forth-continuous-integration.svg?label=Wercker)
![Snap CI](https://img.shields.io/snap-ci/larsbrinkhoff/forth-continuous-integration/master.svg?label=SnapCI)
![Codeship](https://img.shields.io/codeship/d6c1ddd0-16a3-0132-5f85-2e35c05e22b1.svg?label=Codeship)

![TeamCity](https://img.shields.io/teamcity/http/teamcity.jetbrains.com/s/bt345.svg?label=TeamCity)

![Shippable](https://img.shields.io/shippable/5656a5321895ca4474245e90.svg?label=Shippable)

**Comment by espadrine** [comment]
I don't object to changing Coverity as well, if you are up for another PR.

**Comment by larsbrinkhoff** [comment]
Will do!
