### ISSUE TITLE
Licence Badge Rendering

### ISSUE THREAD

**Issue by DakshKK** [badges/shields#5755]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **License Badge render issue**

The licence badge for my repo says licence not specified if I leave it with the default style, or choose flat-square, but for any other style or explicitly stated flat, it renders the licence name.

:link: **https://img.shields.io/github/license/DakshKK/BaseConverter?style=flat-square**

:bulb: **Possible Solution**

I have no idea about why this is happening, but if I put any value for the optional parameters, the badge renders or if I put an `&` after the `?` and before the word `style` in the link.

**Comment by calebcartwright** [comment]
I'm not seeing the behavior you are describing

https://img.shields.io/github/license/DakshKK/BaseConverter?style=flat-square
![](https://img.shields.io/github/license/DakshKK/BaseConverter?style=flat-square)

https://img.shields.io/github/license/DakshKK/BaseConverter?style=flat
![](https://img.shields.io/github/license/DakshKK/BaseConverter?style=flat)

https://img.shields.io/github/license/DakshKK/BaseConverter?style=for-the-badge
![](https://img.shields.io/github/license/DakshKK/BaseConverter?style=for-the-badge)

https://img.shields.io/github/license/DakshKK/BaseConverter
![](https://img.shields.io/github/license/DakshKK/BaseConverter)

**Comment by DakshKK** [comment]
Sorry to cause trouble. I just rechecked on my repo, and now it is showing the badge. Wasn't showing for about 20/25 mins, then what I mentioned in the issue, a friend suggested. Now it works without issue. Thank you for your time.

**Comment by calebcartwright** [comment]
No worries!

**Comment by paulmelnikow** [comment]
If I recall correctly, we cache most license badges for something like 15 or 30 minutes, so that might have been a reason you were seeing stale data.

**Comment by chris48s** [comment]
Yeah license badges have a relatively long cache length on them because a project changing license is quite rare.
