### ISSUE TITLE
Problem does not appear the correct count !!!

### ISSUE THREAD

**Issue by netdragoon** [badges/shields#576]
I have a package that adding the nuget badges does not show the total downloads , why?

GitHub https://github.com/netdragoon/tutorial/blob/master/READMEDATATABLESENT.md
Package Nuget: https://www.nuget.org/packages/Canducci.DataTables.EntityFramework/

????????????????????????????????????????

**Comment by espadrine** [comment]
[This link](https://www.nuget.org/api/v2/Packages()?$filter=Id%20eq%20%27Canducci.DataTables.EntityFramework%27%20and%20IsLatestVersion%20eq%20true) to their API yields a download count at zero.

**Comment by netdragoon** [comment]
O link correct is: [link](https://www.nuget.org/api/v2/Packages(Id='Canducci.DataTables.EntityFramework',Version='1.0.0') ) and the result was satisfactory !!!

**Comment by espadrine** [comment]
I don't have a deep understanding of their API. @Alxandr, do you have some insight?

**Comment by Alxandr** [comment]
Best bet, without looking into it much, is simply cache. That being said, it might be good to look into changing to api v3 (which is also json, so easier).

**Comment by netdragoon** [comment]
I found this issue open the link: https://github.com/NuGet/Home/issues/1544

Using this form works: https://api-v3search-0.nuget.org/query?q=Id:Canducci.DataTables.EntityFramework

```JSON
{
  "@context": {
    "@vocab": "http://schema.nuget.org/schema#"
  },
  "totalHits": 1,
  "lastReopen": "2015-12-08T00:34:16.7370970Z",
  "index": "v3-lucene0-031115",
  "data": [
    {
      "@id": "https://api.nuget.org/v3/registration0/canducci.datatables.entityframework/1.0.0.json",
      "@type": "Package",
      "registration": "https://api.nuget.org/v3/registration0/canducci.datatables.entityframework/index.json",
      "id": "Canducci.DataTables.EntityFramework",
      "description": "Class Wrapper",
      "title": "Canducci DataTables Entity Framework - NET 4.5",
      "iconUrl": "http://i666.photobucket.com/albums/vv25/netdragoon/1445749817_f-table-cell_128_zpschpxbzxv.png",
      "projectUrl": "https://github.com/netdragoon/tutorial/blob/master/READMEDATATABLESENT.md",
      "tags": [
        "jquery.datatables"
      ],
      "authors": [
        "Canducci"
      ],
      "totalDownloads": 68,
      "version": "1.0.0",
      "versions": [
        {
          "version": "1.0.0",
          "downloads": 68,
          "@id": "https://api.nuget.org/v3/registration0/canducci.datatables.entityframework/1.0.0.json"
        }
      ]
    }
  ]
}
```


###I hope to have contributed to future solution

**Comment by netdragoon** [comment]
Any Solution ?

**Comment by espadrine** [comment]
@netdragoon If you want to work on it, here may be a good start: https://github.com/badges/shields/blob/7ab838b6480ded7caff73a1590fa1389049b1172/server.js#L3228.

**Comment by netdragoon** [comment]
I checked the data in the current time of this post and the values are correct.
