### ISSUE TITLE
Website Monitoring Badge with custom HTTP Header Support

### ISSUE THREAD

**Issue by Uskompuf** [badges/shields#5776]
:clipboard: **Description**

I am looking for a version of the website Monitoring Badge which allows me to include specific HTTP headers.

:link: **Data**

I'm not sure how the existing website badge is implemented but I imagine it could be used as a starting point for this badge or even just adding HTTP option to existing badge.

One website for example is https://api.commbank.com.au/public/cds-au/v1/banking/products

Without passing through the necessary headers the page returns 403. If I pass through the two required headers the page returns 200.

![Screenshot_2020-10-30-21-55-39-68](https://user-images.githubusercontent.com/22492406/97697136-b114ab00-1afa-11eb-94ea-646008c7d51f.jpg)

:microphone: **Motivation**

I want to monitor some APIs without having to run any scripts locally or subscribe to a service. The API returns 403 if I don't provide the necessary API version header which shows as offline with the badge.

**Comment by calebcartwright** [comment]
hi @Uskompuf, thanks for reaching out.

> I want to monitor some APIs without having to run any scripts locally or subscribe to a service.

While I can appreciate this desire, please note that's not really what Shields is intended for :wink:

Your immediate use case may seem simple and straightforward in your specific context, but I have concerns that accepting custom headers on our native badges could snowball quickly. That could really complicate our jobs maintaining and supporting Shields for it's core mission of providing badges that are most often embedded in project readme files. 

This ask seems best suited to our [Endpoint](https://shields.io/endpoint) badge offering. With this approach you can deploy a small snippet of code, often for free with something simple like [RunKit](https://runkit.com/docs/endpoint), that can call your API(s) with whatever set of additional headers you may need, and then send a response that conforms to the Endpoint-expected schema

**Comment by Uskompuf** [comment]
Ok thanks, I will have a look into that.

**Comment by Uskompuf** [comment]
I've never done anything with Javascript or RunKit so this is purely just me copy-pasting snippets. I've gotten my headers implemented but not sure how to return JSON from the endpoint. If you have a moment I would appreciate it if you could give me any pointers: https://stackoverflow.com/questions/64618944/runkit-endpoint-which-returns-status-code-of-website

**Comment by chris48s** [comment]
The basic issue with that code is if you're using a callback-based API like request, you can't return a value from a callback. You need to think of it the other way round and pass request a callback function that can do that.

I've not tried setting up your example and running this, but I _think_ a working version of that code would look like

```js
function testAPI(cb) {
    request(options, cb);
}

exports.endpoint = function(request, response) {
    var callback = function(e,r,b) {
        console.log(r.statusCode);
        response.end(r.statusCode)
    }
    testAPI(callback);
}
```

**Comment by Uskompuf** [comment]
Hi @chris48s thanks for that, I've added the code here: https://runkit.com/uskompuf/testing but I still seem to be running into an issue with endpoint returning:

```
{
  "error": "socket hang up",
  "message": "ECONNRESET"
}
```

Any ideas?
Cheers

**Comment by chris48s** [comment]
Oh. Try `response.end(r.statusCode.toString())`

**Comment by Uskompuf** [comment]
Perfect cheers.

**Comment by Uskompuf** [comment]
@chris48s It seems to work if the website is up but doesn't work if the website is down. I think it might need to be in a try statement?

You can see the code here: https://runkit.com/uskompuf/testing/3.0.0

This works when hitting the endpoint here: https://runkit.io/uskompuf/testing/3.0.0

However, if I change the URL to a page which does not exist it times out and gives the same `socket hang up` error.

I know this isn't completely relevant here so feel free to delete if I'm wasting your time.

Cheers

**Comment by chris48s** [comment]
This has kind of turned into "how do I write javascript/use request" more than "how do I use shields.io", so I think this is the last post I'm going to make on this thread, but if the website is down (as opposed to up, but returning a status other than 200), the response variable (`r` in your callback function) will be `undefined` because you didn't receive any response. The info will be in the error variable (`e` in your callback function) in that case.
