### ISSUE TITLE
[Codemagic] Add support for Codemagic builds results

### ISSUE THREAD

**Issue by retyui** [badges/shields#5790]
:clipboard: **Description**

:link: **Data**

:microphone: **Motivation**

**Comment by calebcartwright** [comment]
Thanks for reaching out @retyui. Could I ask you to please provide the values for the data points listed in our issue template? Copied in here for visibility:


- Which service is this badge for e.g: GitHub, Travis CI
- What sort of information should this badge show?
  Provide an example in plain text e.g: "version | v1.01" or as a static badge
  (static badge generator can be found at https://shields.io)

- Is there a public API?
- Does the API requires an API key?
- Link to the API documentation.

- What is the specific use case?

**Comment by calebcartwright** [comment]
Closing this as the issue template was not filled out and no information has been provided about the requested service.

@retyui if you (or anyone else) would like to see badges for this service then please follow up with some basic information and we can reconsider

**Comment by Ismoh** [comment]
- Which service is this badge for e.g: **GitHub**
- What sort of information should this badge show?
Provide an example in plain text e.g: "version | v1.01" or as a static badge
(static badge generator can be found at https://shields.io/)
**https://api.codemagic.io/apps/6235ab7a854b72331755551b/default-workflow/status_badge.svg**
- Is there a public API? **https://docs.codemagic.io/rest-api/codemagic-rest-api/**
- Does the API requires an API key? **https://docs.codemagic.io/rest-api/codemagic-rest-api/#authentication**
- Link to the API documentation. **https://docs.codemagic.io/rest-api/codemagic-rest-api/**
- What is the specific use case? **build status**

**Comment by Ismoh** [comment]
@calebcartwright would you reopen this issue?

**Comment by chris48s** [comment]
Do you know how the auth for this works? I can't find any info in the docs.
If I were to make an API call using Alice's API key, can I see Bob's projects too, or only Alice's?
If only Alice's, is it possible to generate a narrowly scoped token that would not expose any sensitive information or allow write access to any resources? If no, this one probably is not viable. We'd need to either be able to use one token at service level for all projects, or if every user needs to provide their own token, that has to be a token which can be exposed in public with no negative consequences to that user.

**Comment by Ismoh** [comment]
Take a look here:
https://docs.codemagic.io/rest-api/codemagic-rest-api/#authentication

Looks like every user has its own Codemagic API token, which might include sensitive data.

![image](https://user-images.githubusercontent.com/12631485/162014209-fe8ccedd-8bb7-44c3-aa37-5590bf15eb67.png)

**Comment by Ismoh** [comment]
Why closed? Did anyone check the auth problem?
