### ISSUE TITLE
Talk to / implement Bintray

### ISSUE THREAD

**Issue by jhermann** [badges/shields#58]
Bintray as a new player could have the same badges as PyPI and other repos (# of downloads, latest version, etc). 

The [REST API](https://bintray.com/docs/api/ makes this quite easy; the only special thing to take care of is keeping an eye on the rate limits, and cache data so that not every shield request leads to an API request.

**Comment by stuartpb** [comment]
It sounds like there's a pretty definitive answer vis-a-vis lifting the rate limit there. Can this move forward then?

**Comment by espadrine** [comment]
What we have for many services is a secret user/token couple. Of course, that's sensitive data that is usually not too hard to re-generate should I... err... accidentally rm the file. Here, it would require extra careful handling, I guess. Beyond that, there's a bit of coding to be done, if anyone is up to the task.

**Comment by PeterDaveHello** [comment]
```
$ curl https://bintray.com/docs/api.html
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by hastebrot** [comment]
@PeterDaveHello: The new URL is https://bintray.com/docs/api/ (or https://bintray.com/docs/api/#_get_version for the Get Version method).

**Comment by PeterDaveHello** [comment]
Oh yeah, I found it, but it'll be better to redirect instead of 404 ha ...

**Comment by jbaruch** [comment]
Why one would CURL to .html?

**Comment by PeterDaveHello** [comment]
Just easy to understand and faster then a screenshot.

**Comment by jbaruch** [comment]
Got it. Where the old URL comes from?

**Comment by PeterDaveHello** [comment]
The top of this issue.

**Comment by jbaruch** [comment]
Will add redirect.

**Comment by adjohnson916** [comment]
+1

**Comment by ajoberstar** [comment]
This issue, #234, and #284 can all be closed now that #517 has been merged, right?

**Comment by espadrine** [comment]
Implemented by https://github.com/badges/shields/pull/517/files.

**Comment by Icar05** [comment]
Is there way to get version in plain text ( not svg)?

**Comment by paulmelnikow** [comment]
Hi there, feel free to open a new issue with your question.
