### ISSUE TITLE
badge for bithound.io

### ISSUE THREAD

**Issue by thisconnect** [badges/shields#581]
```
https://www.bithound.io/github/<user>/<repo>/badges/score.svg
```

i.e. https://www.bithound.io/github/vuejs/vue/badges/score.svg

**Comment by espadrine** [comment]
Thanks for suggesting this! There is in fact a PR here: https://github.com/badges/shields/pull/452. If you wish to carry it to completion, go ahead!

**Comment by thisconnect** [comment]
Works nicely! Thanks
