### ISSUE TITLE
Continuousphp failures

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#5811]
:clock11: **When did the problem start?**

~October 23rd

:camera: **Live badge**

https://img.shields.io/continuousphp/git-hub/doctrine/dbal

![](https://img.shields.io/continuousphp/git-hub/doctrine/dbal)

:wrench: **Is the live badge working?**

When a branch is specified (e.g. https://img.shields.io/continuousphp/git-hub/doctrine/dbal/master) generally yes, otherwise no.

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/576/workflows/4312f83c-2831-4b69-a4e6-b266911c2809/jobs/1474/tests

Some of the other continuousphp  tests timeout as well, but only occasionally.

:beetle: **Stack trace**

```
ContinuousPhp [live] build status on default branch [ GET /git-hub/doctrine/dbal.json ] - [ GET /git-hub/doctrine/dbal.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

Error: Request timed out after 5000 ms (4 attempts)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1255:37)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

Hitting the API directly seems to also result in a Gateway Timeout: https://status.continuousphp.com/git-hub/doctrine/dbal/status-info

I didn't see an obvious place where to report status API bugs in their public repositories, so I've tried contacting them by mail with the details.

**Comment by PyvesB** [comment]
I haven't heard anything back following the mail I sent. Maybe the mail indicated on the [GitHub organisation](https://github.com/continuousphp) is not actively monitored?

@ppaulis could you help us out on this one? You contributed the initial implementation and still seem to work for ContinuousPHP. 😉

**Comment by calebcartwright** [comment]
I'd propose we go ahead and deprecate this badge if we don't hear back from anyone any time soon (perhaps by the end of the month)?

**Comment by PyvesB** [comment]
The API/badge does still seem to work most of the time when the branch name is specified. By deprecation, do you mean making it a mandatory parameter or dropping the whole service?

**Comment by calebcartwright** [comment]
Oops! Sorry I missed the nuance here about it still working with explicit branches. I thought everything had been offline/unavailable for nearly a month with no response from the provider, so was originally thinking of a full deprecation of the badge, but am now backtracking on that idea a bit

**Comment by PyvesB** [comment]
To summarise:
* when no branch is specified, systematically fails.
* when a branch is specified, works fine most of the time, though I did see a few occasional CI failures as well.

One thing to keep in mind is that the Continuous PHP service isn't really used a lot. In the past week, there were a grand total of 208 requests according to our Grafana metrics, and I'm guessing most of them will have come from displaying this issue or us experimenting with the badge. The main repository that was using the badge, _doctrine/dbal_, moved away from ContinuousPHP a few months ago (see https://github.com/doctrine/dbal/commit/2834455355b3480f21afd1de78f189e4209e746c), a GitHub search for ContinuousPHP badges only seems to return old forks of that repository. That may be an argument in favour of full deprecation.

**Comment by PyvesB** [comment]
Cc @fdewinne, @oswaldderiemaecker, @Pierozi and @gkdg - I saw you're all part of the @continuousphp organisation, so you may be able to unblock this. 😉

**Comment by PyvesB** [comment]
Even the test that does specify a branch has been increasingly flaky recently:
https://app.circleci.com/pipelines/github/badges/daily-tests/644/workflows/cfe1880c-1edf-48b5-879e-1f44f9d0bbd1/jobs/1542
https://app.circleci.com/pipelines/github/badges/daily-tests/642/workflows/056a0b45-3d14-4cb3-a4a9-7f3ff2090317/jobs/1540
https://app.circleci.com/pipelines/github/badges/daily-tests/635/workflows/9c2681e1-20e2-4639-9279-4f28ff19d5be/jobs/1533
https://app.circleci.com/pipelines/github/badges/daily-tests/634/workflows/5547d899-326f-48f6-bd8a-9fde51002d31/jobs/1532
https://app.circleci.com/pipelines/github/badges/daily-tests/632/workflows/b0926cad-ef48-45f2-93bb-f66dc18da0b7/jobs/1530

Given how little this badge is actually used, and given that the API provider has been completely unresponsive for over a month now, I'm gonna go ahead and submit a pull request for full deprecation.
