### ISSUE TITLE
Badge request: vcpkg

### ISSUE THREAD

**Issue by PragmaTwice** [badges/shields#5816]
:clipboard: **Description**
[Vcpkg](https://github.com/microsoft/vcpkg) is a rising C++ Library Manager for Windows, Linux, and MacOS, which is developed by Microsoft.
We want to have a vcpkg package badge to show our project can be found in vcpkg library manager, such as "vcpkg | v1.0.0" or other similiar format.

:link: **Data**

Package data can be found in the [repo of vcpkg](https://github.com/microsoft/vcpkg) itself.
Information of all package are stored in the directory [`ports/`](https://github.com/microsoft/vcpkg/tree/master/ports). 
For example, you can find info of package `protopuf` in [`ports/protopuf/vcpkg.json`](https://github.com/microsoft/vcpkg/blob/master/ports/protopuf/vcpkg.json).
No API key is required.

:microphone: **Motivation**

Vcpkg is becoming more and more popular. 
I hope to have a badge after releasing my library, and I think other library developers also have this demand. 
And because it is very simple to obtain library information, I think it may not be difficult to implement.

**Comment by PyvesB** [comment]
Hello @PragmaTwice! 👋🏻 

Thanks for the suggestion, this sounds reasonable. I would expect the implementation to end up looking quite similar to our existing [Scoop service](https://github.com/badges/shields/blob/master/services/scoop/scoop-version.service.js), but simpler given that retrieving a separate list of buckets won't be needed here.

Would you like to submit a pull request? In addition to exiting implementations, you can use [our new-contributor-friendly tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). 😉

**Comment by PragmaTwice** [comment]
I'm willing to try it when I have time.
