### ISSUE TITLE
invalid response data with Discourse badge

### ISSUE THREAD

**Issue by oncleben31** [badges/shields#5817]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I try to add a Discourse/Topic Count badge for the Discourse instance of my community. The number is replaced by `invalid response data`
I have check the `about.json` file seems available and correct.
I don't know how to investigate deeper.

:link: **Link to the badge**

![Discourse topics](https://img.shields.io/discourse/topics?server=https%3A%2F%2Fforum.hacf.fr)

:bulb: **Possible Solution**

**Comment by PyvesB** [comment]
Hello @oncleben31! 👋🏻 

I'm not familiar with Discourse, but I believe Shields looks for an API at the following location: https://forum.hacf.fr/site/statistics.json

See our implementation here:
https://github.com/badges/shields/blob/71299a81788c95363bbafc4a2c75af960b12d5b9/services/discourse/discourse.service.js#L36

That seems to simply redirect to the website's homepage, which is probably why Shields.io returns `invalid response data`. 😉

**Comment by oncleben31** [comment]
@PyvesB Thank you very much. I know where to investigate now. I will check with the forum administrator why this file is redirected to home page.
