### ISSUE TITLE
Install intelliJ IDEA plugins.

### ISSUE THREAD

**Issue by AlexanderPrendota** [badges/shields#5838]
:clipboard: **Description**
**Service** JetBrains Marketplace
**What sort of information should this badge show**. Label: _install_. Text: _${pluginName} in IDEA._

Example:
[![example](https://img.shields.io/badge/install-Scala%20in%20IDEA-blue)](https://plugins.jetbrains.com/embeddable/install/1347) 

:link: **Data**

[Link to the Scala Plugin to install](https://plugins.jetbrains.com/embeddable/install/1347)
[Marketplace documentation for embeddable content](https://plugins.jetbrains.com/docs/marketplace/embeddable-content.html#including-iframe)

:microphone: **Motivation**

The main reason to have the badge: an easy way to install an IDEA plugin from README.md.
Plugin example: [Fortran plugin](https://github.com/satamas/fortran-plugin)

**Comment by calebcartwright** [comment]
Thank you for the suggestion @AlexanderPrendota but going to close this one.

We provide the capability for users to build badges with our static badge builder (as you did in the issue description), but we deliberately do not provide pre-canned static badges as requested in this issue.

**Comment by AlexanderPrendota** [comment]
Hey @calebcartwright , but why? I just wanna put the plugin id, for example, Scala = 1347, and get the badge.

**Comment by AlexanderPrendota** [comment]
I can send the PR, btw

**Comment by calebcartwright** [comment]
> I can send the PR, btw

No, it would be rejected.

> but why? I just wanna put the plugin id, for example, Scala = 1347, and get the badge.

As I stated before.. we provide the static badge builder capability which users can use to create an essentially infinite number of badges; we do not and will not provide pre-canned static badges.

Creating a static badge with our service is a quick, easy, and one-time operation. Adding additional code/features to Shields.io to make building a certain static badge a _little_ easier only adds marginal value, and the extra overhead on the codebase and our maintenance effort is simply not worth it. I know you're asking from the narrow focus of the specific type of static badge you'd like to use, but you've got to think about it in the broader context of the Shields service.

If we do this for one badge, we have to do it for all the others (and again, the static badge builder is a free for all so we're talking about a practical infinite set of combinations) and/or be in the business of curating which pre-canned static badges warrant inclusion. Neither of these is remotely acceptable.
