### ISSUE TITLE
ValidationError: "redirectUri" is not allowed

### ISSUE THREAD

**Issue by chris48s** [badges/shields#5839]
Are you experiencing an issue with...

- [x] Self-hosted instance

:beetle: **Description**

Bug reported by a self-hosting user:

> I've just encountered the following error:

```
redirectUri: 'https://shields-nginx.xxxxx.com' 

/usr/src/app/node_modules/@hapi/joi/lib/index.js:243
    throw error;
    ^

ValidationError: "redirectUri" is not allowed

```
> any idea what could this be?

The issue is that the setting doesn't match up with the schema:

* https://github.com/badges/shields/blob/1fab1a7140850f3630aeb94a049c0908ff722d14/config/custom-environment-variables.yml#L24
* https://github.com/badges/shields/blob/783a1077718b0e8372b6388b0bff98234cf75723/core/server/server.js#L116

:bulb: **Possible Solution**

Unsure if the fix is that we should change the setting to match the schema or change the schema to match the setting. Anyone got any clarity on the intention here?

**Comment by paulmelnikow** [comment]
Since we tried to migrate everything to `url`, I'd suggest using `redirectUrl` in `custom-environment-variables.yml`.

We could change the env var too, though the simple thing would be to sync up the keys and leave the env var be.

**Comment by chris48s** [comment]
Thanks. Looking over it in more detail, we're already using `redirectUrl` in the other yaml files and we document `REDIRECT_URI` in the docs. I think that's the least disruptive solution
