### ISSUE TITLE
Youtube view count shield broken

### ISSUE THREAD

**Issue by boaz-codota** [badges/shields#5842]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [  ] My own instance
- [  ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The Youtube view count badge stopped working (validated on two different videos)

:link: **Link to the badge**
![https://img.shields.io/youtube/views/y1o8enBHnG0?style=social](https://img.shields.io/youtube/views/y1o8enBHnG0?style=social)
https://img.shields.io/youtube/views/TKLkXh_c-Gw?style=social
![https://img.shields.io/youtube/views/y1o8enBHnG0?style=social](https://img.shields.io/youtube/views/y1o8enBHnG0?style=social)
https://img.shields.io/youtube/views/y1o8enBHnG0?style=social

:bulb: **Possible Solution**

**Comment by boaz-codota** [comment]
Seems fixed (probably a YouTube issue). Thanks!

**Comment by PyvesB** [comment]
Our API quota was increased (see #6276 for more details), intermittent issues should go away. 😉
