### ISSUE TITLE
PNG (raster) font does not have enough letter spacing

### ISSUE THREAD

**Issue by boaz-codota** [badges/shields#5844]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [  ] My own instance
- [  ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The numbers inside the raster.shields.io social badge (png version) have letter spacing that is too small, making the text not readable.

:link: **Link to the badge**
![https://raster.shields.io/github/stars/codota/tabnine-intellij?style=social](https://raster.shields.io/github/stars/codota/tabnine-intellij?style=social)

:bulb: **Possible Solution**

Increase letter spacing

**Comment by calebcartwright** [comment]
Thanks for the report @boaz-codota! We're in the process of rewriting our rasterization proxy which produces the png badges, and while the pngs are always going to be less pixel-perfect than the svgs, I do think you can expect to see an improvement once we're done (which should be fairly soon).

Here's a screen grab of what your badge looks like with the new version (sorry for the blur, taken from my local):
![image](https://user-images.githubusercontent.com/13042488/99554032-62816080-2984-11eb-8a10-7c2e1e37ef2b.png)

**Comment by boaz-codota** [comment]
Can't wait, we love the product in https://tabnine.com/ and use it to display social information in Jetbrains Marketplace and VSCode Marketplace

**Comment by chris48s** [comment]
@boaz-codota Out of interest, what's your use-case for using raster badges in preference to SVG? We know we still serve a lot of PNGs but we don't really have a great handle on where and why they are used over SVG.

**Comment by boaz-codota** [comment]
I'm glad you asked! We embed those badges in our Jetbrains plugin page.
While the web version renders the svgs perfectly: https://plugins.jetbrains.com/plugin/12798-tabnine-ai-autocomplete-javascript-c-java-python-ruby-rust-go-php--

The IDE cannot render SVGs at all (didn't save a pic of it, but trust me on that one). The PNG version on the other hand works perfectly: 
![image](https://user-images.githubusercontent.com/69103343/99640371-7646c880-2a51-11eb-930a-ee91071832a8.png)
