### ISSUE TITLE
Add support for Jenkins with additional path

### ISSUE THREAD

**Issue by ctron** [badges/shields#586]
Currently only a jenkins server URI of the type http://server.com/ is supported.

However Jeknins/Hudson can also be deploy with an additional path prefix: http://server.com/my-jenkins

**Comment by espadrine** [comment]
Thanks for submitting! I thought we already provided that functionality. Can you give me an example of a URL for which we cannot produce a badge?

**Comment by ctron** [comment]
Thanks for looking into this.

I do have a problem with: https://hudson.eclipse.org/package-drone/job/package-drone/

**Comment by ctron** [comment]
I would have thought the shields URL would be https://img.shields.io/jenkins/s/https/hudson.eclipse.org/package-drone/package-drone.svg ... but this only results in a gray badge "build|building", which is not true.

**Comment by espadrine** [comment]
Fantastic! Thanks a lot! Apparently, we only consider `https://hudson.eclipse.org/package-drone/job/package-drone/api/json?tree=color` to be successful when it returns 'blue'. It returns 'green' in your case. I assume it ought to be passing, can you confirm?

**Comment by ctron** [comment]
just tested, works fine! Thanks a lot! :+1:
