### ISSUE TITLE
/endpoint badge can't handle gzip compressed json 

### ISSUE THREAD

**Issue by devhawk** [badges/shields#5868]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

My [shields.io endpoint JSON file](https://neobctk.blob.core.windows.net/packages/badges/vpre/neo.blockchaintoolkit3.json) renders a badge reading "unparsable json response". I believe the problem is that the JSON file is gzip compressed.

:link: **Link to the badge**

![](https://img.shields.io/endpoint?url=https://neobctk.blob.core.windows.net/packages/badges/vpre/neo.blockchaintoolkit3.json)

https://img.shields.io/endpoint?url=https://neobctk.blob.core.windows.net/packages/badges/vpre/neo.blockchaintoolkit3.json

:bulb: **Possible Solution**

enable gzip decompression for /endpoint badges

**Comment by paulmelnikow** [comment]
Hi! Thanks for the report. Yes, your assessment seems to be correct. I managed to fix this by telling `request` to work with compressed responses. Opening a PR with that fix.

It makes sense to me that we should support this, though curious to hear the other maintainers' perspectives.

**Comment by chris48s** [comment]
Gzip compressed responses are common. I'm surprised we haven't hit this sooner tbh.
I don't think there's really any downside to accepting them is there?

**Comment by paulmelnikow** [comment]
I don't think there is. Security would be the only thing that comes to mind, but I'm not aware of any security issues related to gzip. This functionality is in Node core, and I imagine any such vulnerabilities would be fixed quickly.
