### ISSUE TITLE
Sonarqube 8.5 quality gate parameter componentKey

### ISSUE THREAD

**Issue by blink38** [badges/shields#5882]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [X] My own instance (docker instance)
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Sonarqube 8.5 quality gate parameter componentKey**

When retrieve the metrics from sonarqube instance, url used parameter named componentKey

`GET /api/measures/component?componentKey=org.app%3AmyApp&metricKeys=alert_status`

It seem that the parameter *componentKey* have been renamed to *component* in sonarqube.

So, it should be :
 
`GET /api/measures/component?component=org.app%3AmyApp&metricKeys=alert_status`

:link: **Link to the badge**

:bulb: **Possible Solution**

In services/sonar/sonar-base.js, rename componentKey to component
`qs = {                                                                           
        componentKey: component,
        metricKeys: metricName,                                                                     
      }`

to

`qs = {                                                                           
        component: component,
        metricKeys: metricName,                                                                     
      }`

**Comment by calebcartwright** [comment]
Thanks for reaching out @blink38, could you please provide some additional context? Is there a problem you are seeing with the badges? Is there any release notes from Sonar Source announcing breaking API changes?

**Comment by blink38** [comment]
When selecting *Analysis* > *Sonar Quality Gate* :

![image](https://user-images.githubusercontent.com/1789267/100479731-54071780-30ef-11eb-9b22-2481f4312759.png)

The output is a badge with "invalid" [text.]
![quality-gate-invalid](https://user-images.githubusercontent.com/1789267/100479653-25893c80-30ef-11eb-860b-eff80b12ea8a.png)


The URL called by shields.io is :
http://mysonar/api/measures/component?componentKey=org.app%3AmyApp&metricKeys=alert_status

The response of the url is :
```
{"errors":[{"msg":"The 'component' parameter is missing"}]}
```

----
Now, I made some change in services/sonar/sonar-base.js :
```
--- sonar-base.js.origin        2020-11-27 20:09:30.000000000 +0100
+++ sonar-base.js       2020-11-27 20:13:13.000000000 +0100
@@ -71,7 +71,7 @@
       schema = modernSchema
       url = `${server}/api/measures/component`
       qs = {
-        componentKey: component,
+        component: component,
         metricKeys: metricName,
       }
     }
```

The URL called is now :
http://mysonar/api/measures/component?component=org.app%3AmyApp&metricKeys=alert_status

The response of the url is :
```
{"component":{"id": ... ,"qualifier":"TRK","measures":[{"metric":"alert_status","value":"OK"}]}}
```

And the badge text output is "passed".
![quality-gate-passed](https://user-images.githubusercontent.com/1789267/100479679-320d9500-30ef-11eb-97e7-d7e9dc058911.png)


 --------

On this page : https://gazelle.ihe.net/sonar/web_api/api/measures?deprecated=true, if you look at the parameters of GET api/measures/component, you will read that the componentKey is deprecated since 6.6

This issue https://jira.sonarsource.com/browse/SONAR-9676 discuss about renaming componentKey to component, fixed in 6.6

**Comment by jgangemi** [comment]
i am also experiencing this issue, but with version 8.4.2

**Comment by chkpnt** [comment]
I can confirm this issue with SonarQube 8.9.1 (LTS)
