### ISSUE TITLE
Third Party Requests to Google Fonts

### ISSUE THREAD

**Issue by samuel-p** [badges/shields#5883]
:clipboard: **Description**

At the moment shields does third party requests to Google. CDNs are bad from a privacy and security perspective. So please replace them completely with self-hosted files or at least provide an option to disable it for self-hosted instances. You can download the fonts from [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/fonts) if you want to self-host it.

![Bildschirmfoto von 2020-11-28 00-16-20](https://user-images.githubusercontent.com/7959516/100488787-90973b00-3110-11eb-8d2f-240b1d4e5986.png)

https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fshields.io%2F#requests

**Comment by calebcartwright** [comment]
Relevant discussion in #4864 and #3026

**Comment by SISheogorath** [comment]
I just added a new version of my previous PR that resolves the fonts using NPM packages instead of manually maintaining the fonts inside the project.

I hope this will help to resolve the situation.

**Comment by PyvesB** [comment]
Aforementioned pull request is now live on our servers, thanks again @SISheogorath  for the contribution and @samuel-p for raising the issue. Do let us know if you have any further concerns by opening a new issue, for now I'll close this one. 😉
