### ISSUE TITLE
Removing default style override in GitHub Sponsors badge

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5887]
## Overview
The purpose of this issue is to inform the community that we will be removing the default overridden style in the GitHub Sponsors badge. Based on information from our observability solution and searches on GitHub we do not believe this will impact any existing badges, but are posting this for transparency and awareness.

### Action Steps
If you are currently using the GitHub Sponsors badge **_without_** the `style=social` query parameter in your badge url and would like to continue utilizing the `social` style for your GitHub Sponsors badge, then you will need to add the `?style=social` query parameter to your badge url.

 E.g. `https://img.shields.io/github/sponsors/homebrew` --> `https://img.shields.io/github/sponsors/homebrew?style=social`

If you already have the `style` query parameter then there is no action needed.

## Background
Shields.io supports several different style options for our badges which can be controlled via the `?style=...` query parameter on the badge urls. More information can be found under the styles section on the shields.io site - https://shields.io/#styles

The default stye is `flat`, so a badge requested with a url that does not explicitly specify the desired style with the `style` param will default to the flat style. 

For example:

The default flat style can be observed with the npm version badge.
https://img.shields.io/npm/v/badge-maker
![](https://img.shields.io/npm/v/badge-maker)

but can be changed to a different style with an explicit query param
https://img.shields.io/npm/v/badge-maker?style=social
![](https://img.shields.io/npm/v/badge-maker?style=social)

However, there are a couple of badges that have _overridden_ that default style for that specific badge to use a default other than `flat`.

This can be seen with the Twitter badges where the style utilized by default is `social` instead of `flat`
https://img.shields.io/twitter/follow/shields
![](https://img.shields.io/twitter/follow/shields)

but the style can of course still be set/overridden explicitly
https://img.shields.io/twitter/follow/shields?style=flat
![](https://img.shields.io/twitter/follow/shields?style=flat)

We typically avoid badge-specific overrides of the default style, but there are a few such instances within our [social category of badges](https://shields.io/category/social), including the GitHub Sponsors badge, where this is done.

https://img.shields.io/github/sponsors/homebrew
![](https://img.shields.io/github/sponsors/homebrew)

## Motivation
The GitHub Sponsors badge was added relatively recently, and was added to our offering in the `social` category with the default style overridden to be `social` as well. This was done based on the initial discussion and request for the badge to look similar to the native sponsor button within the GitHub interface, and a general desire for our social style with the new badge.

However, there were some subsequent discussions and questions about the category (funding vs. social) and whether we truly want to override the default style for this badge. While there's still some ongoing discussion about the category, we have determined that we need to remove the default style override for the GitHub Sponsors badge.

**Comment by calebcartwright** [comment]
Going to go ahead and close this as the default style override has already been removed and change deployed (as such a few of the example badges in the PR descriptions have styles that no longer match their associated text).

Will keep it pinned for a while longer though for awareness

**Comment by chris48s** [comment]
think this has done its job as a pinned issue now
