### ISSUE TITLE
Allow specifying path for lines of code (tokei) badge

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [badges/shields#5890]
:clipboard: Add functionality similar to the custom path version of GitHub repo file count to the *Lines of code* (via tokei) badge (See [the size category](https://shields.io/category/size)). The line count should be the one output by `tokei :path`.

I am simply reiterating desire expressed by @feluelle and @jnm2 in #2731.

Currently the only way to achieve a similar result is to add a `.tokeignore` file which may be annoying for various reasons.

**Comment by chris48s** [comment]
Our badges are based on scraping the ones from by tokei.rs (we don't run tokei as a library in our own codebase)
https://github.com/XAMPPRocky/tokei#badges
I don't think their service has that feature, so I think this is a feature request for the upstream.

**Comment by aureooms** [comment]
Here is a link to the relevant upstream issue: https://github.com/XAMPPRocky/tokei_rs/issues/2.

**Comment by paulmelnikow** [comment]
Since this is out of Shields' hands I'm going to close this, though feel free to reply here if there is any new information, and if it becomes actionable by shields we can reopen it.
