### ISSUE TITLE
Running shields instance behind reverse proxy breaks page URLs

### ISSUE THREAD

**Issue by voodoodror** [badges/shields#5894]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

As part of effort in securing my shields server using nginx reverse proxy (i.e. with queryparameter validation), it looks like page URLs are set with a slash:
```
href="/.....' 
src="/.....' 
data="/.....' 
```
and as a result I'm unable to use badges nor links. Tried also rewriting the URLs using nginx without any success.

:bulb: **Possible Solution**

Unfortunately, I didn't find any workaround.

**Comment by paulmelnikow** [comment]
Could you explain why the slash is causing a problem?

**Comment by voodoodror** [comment]
@paulmelnikow Sorry, my bad. forgot to mention that I used different path on nginx for reverse proxy, instead of root folder, it redirects to `www.myurl.com/shields/`

**Comment by paulmelnikow** [comment]
You could try setting `GATSBY_BASE_URL` before running the build.

Why do you need to host it from a subfolder?

**Comment by voodoodror** [comment]
@paulmelnikow I will be trying `GATSBY_BASE_URL` and let you know.
