### ISSUE TITLE
Access https version of shields.io

### ISSUE THREAD

**Issue by hugoboos** [badges/shields#590]
Hi,

When accessing shields.io with https, i'l get a CloudFlare `Error 522 Connection timed out `.
The site through http does work.

**Comment by espadrine** [comment]
Yes. GitHub Pages currently only work on HTTP, not HTTPS. It is a common problem that many people face.

**Comment by hugoboos** [comment]
Thanks for the clarification.

**Comment by bogdanRada** [comment]
actually HTTP seems to redirect to HTTPS. So currently badges only work on HTTPS.  
And i do have same issue with time out on HTTPS.

**Comment by espadrine** [comment]
@bogdanRada There is a difference between shields.io and img.shields.io. shields.io (which is what the current issue was targeting) is HTTP-only. img.shields.io redirects HTTP to HTTPS badges for enhanced security.

Could you give me the URL of the badge causing a 522 error?

**Comment by bogdanRada** [comment]
it seems now to be working. maybe was just a temporary glitch . thanks though. 
i only noticed that on my repository bogdanRada/ruby-gem-downloads-badge. all badges were having that issue. but seems now to be fixed.
