### ISSUE TITLE
unparseable jsonpath query

### ISSUE THREAD

**Issue by ahmadalkaddor** [badges/shields#5915]
hey, 
I am trying to make a badge with the leader of a game but i get the following error: Unparseable jsonpath query.

the image url that i am filling in gitlab:
https://img.shields.io/badge/dynamic/json?url=https://devops-proxy.atlantis.ugent.be/api/leaderboard&label=Leader&query=$[0].['name']&color=yellow&prefix=""&suffix=""

url where i am fetching data from:
https://devops-proxy.atlantis.ugent.be/api/leaderboard

i just need the name of the first json object(the one with highest score in the game)
can someone please tell what is wrong?

**Comment by calebcartwright** [comment]
Wouldn't something like `&query=0.name` get you what you want? `&query=$[0].name` or `&query=$[0]['name']` should be viable as well

**Comment by ahmadalkaddor** [comment]
> Wouldn't something like `&query=0.name` get you what you want? `&query=$[0].name` or `&query=$[0]['name']` should be viable as well
i tried it and it give a query error.
i found it: in the url I replaced the ':' with %3A and every '/' with %2F. 
so the url should be like:
https%3A%2F%2Fdevops-proxy.atlantis.ugent.be%2Fapi%2Fleaderboard

**Comment by ahmadalkaddor** [comment]
solved: in the url I replaced the ':' with %3A and every '/' with %2F. 
so the url should be like:
https%3A%2F%2Fdevops-proxy.atlantis.ugent.be%2Fapi%2Fleaderboard

**Comment by ahmadalkaddor** [comment]
in the url I replaced the ':' with %3A and every '/' with %2F. 
so the url should be like:
https%3A%2F%2Fdevops-proxy.atlantis.ugent.be%2Fapi%2Fleaderboard
