### ISSUE TITLE
🚀 SimpleIcons 4

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5916]
Logos on shields.io are provided by SimpleIcons. We've just upgraded to [SimpleIcons 4](https://github.com/simple-icons/simple-icons/releases/tag/4.0.0) which renames or removes several icons.

These icons have been removed completely:
- `mixer`

These icons have been renamed. If you use any of these, update your badge URL:
- `adobe-lightroom-cc` --> `adobe-lightroom`
- `google-hangouts-chat` --> `google-chat`
- `google-hangouts-meet` --> `google-meet`
- `groovy` --> `apache-groovy`
- `postwoman` --> `hoppscotch` (note the logo has been changed as well)
- `riot` --> `element` (note the logo has been changed as well)
- `tor` --> `tor-project` (note the logo has been slightly modified as well)

**Comment by emmysteven** [comment]
Thanks for the information

**Comment by chris48s** [comment]
think this has done its job as a pinned issue now
