### ISSUE TITLE
open-vsx badges don't work; results in "inaccessible"

### ISSUE THREAD

**Issue by Janne252** [badges/shields#5922]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

`open-vsx` badges don't work; even the example input of `redhat` / `java` results in "inaccessible"

![image](https://user-images.githubusercontent.com/4705573/101795310-70a04800-3b10-11eb-8310-129b066e3813.png)

:link: https://img.shields.io/open-vsx/v/redhat/java

![Open VSX Version](https://img.shields.io/open-vsx/v/redhat/java)

**Comment by calebcartwright** [comment]
I observed the same earlier today. During that window while the badge was showing inaccessible (~45 minutes after the issue posting), the API was responsive and providing the expected responses and our service test runs were also passing.

Things seem to be fine again at the moment though but we'll keep an eye out. Could've been a simple transient issue or there could be some upstream throttling/blocking that was preventing our prod servers from being able to access the registry.

**Comment by Janne252** [comment]
Thanks for checking! The badges seem to have been working flawlessly today. I consider the issue to be resolved for now.

**Comment by chris48s** [comment]
Lets assume it was a transient issue for now. If it recurrs feel free to reopen
