### ISSUE TITLE
Distelli support?

### ISSUE THREAD

**Issue by crazy4groovy** [badges/shields#594]
Would be neat :)

**Comment by espadrine** [comment]
Thanks for the suggestion! It seems to have [builds](https://www.distelli.com/) much like Travis CI, we may have build badges.

The API is here: [click me](https://www.distelli.com/docs/api).

**Comment by romani** [comment]
+1

**Comment by amcdnl** [comment]
@espadrine anything come of this?

**Comment by ramonsaraiva** [comment]
+1

**Comment by paulmelnikow** [comment]
Hey @ramonsaraiva would you be interested in working on this? We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md).

**Comment by ramonsaraiva** [comment]
Yeah i'm thinking about tackling this when i get some free time.

**Comment by paulmelnikow** [comment]
Awesome. If you have any questions feel free to post them here.

**Comment by paulmelnikow** [comment]
Tagging **needs-upstream-help** based on https://github.com/badges/shields/pull/1310#discussion_r154740710.

**Comment by paulmelnikow** [comment]
Distelli is now part of Puppet, so I'm not sure if this is still a thing.

If it is, and read-only token have become available, feel free to ping this issue and one of the maintainers will reopen!

**Comment by romani** [comment]
It is still working CI, do you need to find some issue tracker of distelli ? To request a token ?

**Comment by paulmelnikow** [comment]
Does it have support for [read-only tokens](https://github.com/badges/shields/pull/1310#discussion_r154508870)?
