### ISSUE TITLE
Badge request: (standardised) open-source project Criticality Score

### ISSUE THREAD

**Issue by sadielbartholomew** [badges/shields#5941]
:clipboard: **Description**

* This is a badge for GitHub.
* The badge would give the [Criticality Score metric (a float between 0 and 1) as calculated from the standard (non-customised) algorithm](https://github.com/ossf/criticality_score#criticality-score) so as to be fairly comparable across projects.
* There could be incremental colour grading based on the value (1 as the ideal best to 0 as the worst score) to imply the standard of the criticality at a glance. 
* The format that seems natural to me for the badge is `criticality score: N` where N is the score between 0 and 1, noting that strictly the name Criticality Score is capitalised (going by the usage of the creators) but for consistency with the shields style it should be in lower case.

:link: **Data**

* API is provided via the public [ossf/criticality_score](https://github.com/ossf/criticality_score) repository.
* A GitHub access token is required.
* There is basic documentation provided in [the repository README](https://github.com/ossf/criticality_score/blob/main/README.md) but it looks like it could easily be sufficient.

:microphone: **Motivation**

The Open Source Project Criticality Score is a recently-announced metric created by Google's OpenSSF, as detailed [in this dedicated blog post](https://opensource.googleblog.com/2020/12/finding-critical-open-source-projects.html). Having this metric in a badge:
* would be a very useful way for someone looking at a public project on GitHub to gauge immediately that is objectively rated as being influential and important (or otherwise), with the 0 to 1 nature being very simple to comprehend;
* would allow projects rated as critical to advertise that they are deemed critical and gain further esteem based on that;
* would facilitate inter-comparison of the criticality of projects.

**Comment by calebcartwright** [comment]
Thanks for the suggestion @sadielbartholomew. While it does seem like a bade that would be good to support, I'm not sure it's really a viable candidate in its current state.

In order for us to be able to provide a badge we need something like a rest endpoint that quickly provides machine readable quickly which we then use to construct the badges. Our badge servicing process is primarily i/o bound on the fetching of the target data points from the systems of record, as we don't produce or calculate any such raw data points ourselves nor do we really run other tools/binaries on our production environment which do.

AFAICT what exists today for the criticality score is a command line tool which makes multiple requests to GitHub to fetch various data points that are then used for calculating the value, but that's not really something we can utilize for getting the criticality score for badges.

We'd need something like a rest api that our badge servers could reach out to with a GitHub repository which would return the corresponding criticality score, and would need that response to take no more than 2 or 3 seconds at an absolute maximum.

**Comment by paulmelnikow** [comment]
Agreed that to implement this we'd need an API to hit that could compute and cache the result. Would love to include this badge, though we're not in a position to implement or maintain that API, so that'd be a prerequisite for including this in Shields.

Another possible way to integrate this would be [our Endpoint badge](https://shields.io/endpoint), though it still requires running the analysis externally.

**Comment by sadielbartholomew** [comment]
Hi @calebcartwright and @paulmelnikow: sorry I missed your original comment Caleb, I think it must have got lost in the noise of my GitHub notifications. Both, thanks for your replies. If it's not possible to have this badge, then fair enough, though I will keep an eye on the status of the criticality score project in case a possibility does indeed open up for a viable badge on Shields, in which case I will tag one of you here. Thanks!
