### ISSUE TITLE
move docs site to gh-pages

### ISSUE THREAD

**Issue by chris48s** [badges/shields#5944]
:clipboard: **Description**

The main reason I set up https://contributing.shields.io/ on netlify was because the gh-pages branch was occupied by the frontend. Now that we're not using it for the frontend any more, I might move it off netlify and deploy it on gh-pages with a github action instead. We've had the netlify previews turned off for ages anyway because we were burning though too many build minutes and that was pretty much the only value add.

**Comment by avinal** [comment]
Hello @chris48s, I want to work on this issue. Please explain what exactly needs to be done. I am somewhat experienced in creating GitHub Actions for documentation and other purposes. I get it that the docs site needs to be moved to the gh-pages. Do you need to rewrite them or just host existing Markdown files or use a static site generator? 

Thank you!

**Comment by chris48s** [comment]
Thanks for the offer. This probably isn't a great issue for a first contribution. The GH action to run `npm run build-docs` and push the output to `gh-pages` will only be a few lines. I haven't got as far as working out whether anything else will need to change. The other tasks around this (removing netlify integrations, moving the DNS in CloudFlare, etc) will need to be done by one of the core team.

If you're interested in working on the project the issues marked [good first issue](https://github.com/badges/shields/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) should all be good onboarding issues for a first contribution.

**Comment by avinal** [comment]
No problem, I will see other issues, Thanks :)

**Comment by chris48s** [comment]
https://contributing.shields.io/ is now serving from GH pages
