### ISSUE TITLE
Contributor count doesn't match GitHub's

### ISSUE THREAD

**Issue by rmzelle** [badges/shields#5969]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

As of right now, https://github.com/citation-style-language/styles/ reports 872 contributors in the side-bar:

![image](https://user-images.githubusercontent.com/77951/102722431-1309b980-42cf-11eb-8877-d35b1d0a8929.png)

I thought I would be able to get this number in a badge, but neither of the following two "GitHub contributors" badges give the same number:

![GitHub contributors](https://img.shields.io/github/contributors/citation-style-language/styles) (410 contributors)
![GitHub contributors](https://img.shields.io/github/contributors-anon/citation-style-language/styles) (943 contributors-anon)

I'm also curious how "contributors" and "contributors-anon" differ. Is this documented somewhere?

:link: **Link to the badge**

https://img.shields.io/github/contributors/citation-style-language/styles
https://img.shields.io/github/contributors-anon/citation-style-language/styles

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
As is the case with all our badges, we utilize upstream APIs on the respective platforms to get the data that we need to produce the badges.

In the case of the GitHub Contributors badge, that upstream endpoint is GitHub's List Repository Contributors API

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors

This API supports including (or not including) anonymous contributions via the `anon` query parameter, which is reflected in `contributors` vs. `contributors-anon`

Whether a given upstream service has a discrepancy between their own UI and their APIs is really something you'll have to take up with said upstream service; we can't speak for them.

If you look at the corresponding responses from the GitHub API calls for your app, you'll see our badges are reflecting what GitHub is telling us:

https://api.github.com/repos/citation-style-language/styles/contributors?per_page=100
https://api.github.com/repos/citation-style-language/styles/contributors?per_page=100&page=2
https://api.github.com/repos/citation-style-language/styles/contributors?per_page=100&page=3
https://api.github.com/repos/citation-style-language/styles/contributors?per_page=100&page=4
https://api.github.com/repos/citation-style-language/styles/contributors?per_page=100&page=5

(100 known contributors on the first four pages and 10 known contributors on the 5th = 410 contributors).

You'll see the same story with the calls permitting the inclusion of anonymous contributors as well. The only guess I'll proffer is that I think the Contributors section on the GitHub UI's repo landing page excludes contributions from bots/apps/etc. that the API may not

**Comment by rmzelle** [comment]
Thanks! (I found some additional discussion about the GitHub API results at https://stackoverflow.com/a/36462386/1712389)

**Comment by chris48s** [comment]
Looks like that SO post mostly covers things, but just to give an example of what the `anon` param really means:

An anonymous contribution is a commit where the email address on the commit isn't liked to a github user, so https://github.com/citation-style-language/styles/commit/e6279d0ea2f9cdc4e08e7831c857c05950c32696 is an anonymous contribution, whereas https://github.com/citation-style-language/styles/commit/aa5ba1c00ddfa20be8d1aef62e2755dd4ac97fe8 is a non-anonymous contribution.
