### ISSUE TITLE
img.shields.io site is down! (Heroku error)

### ISSUE THREAD

**Issue by sayantan300** [badges/shields#5971]
I was trying the below link for my purposes, but heroku error log showed up.
https://img.shields.io/static/v1?label=rovel&message=js&color=red&style=for-the-badge&logo=appveyor

**Comment by lucasgdb** [comment]
shields.io too!

**Comment by sayantan300** [comment]
Wait, what?! I just copied the base URL of making a badge from there! Will this become like google blackout?
There are millions of repos using this badges! And I love this because it can generate for the badge style ones...

**Comment by lucasgdb** [comment]
it's working now

**Comment by sayantan300** [comment]
Maybe nodemon restarted it

**Comment by chris48s** [comment]
The immediate downtime is fixed, but cause is unknown.. For the benefit of other maintainers: I think we were down for about 15 mins. Promoting staging to production fixed it. I think we went over the heroku memory quota, but unsure why.

Probably best followed up in team chat, but here's what the outage looked like.The commit hash marker is where I re-deployed

![Screenshot at 2020-12-21 16-48-58](https://user-images.githubusercontent.com/6025893/102801222-d14f4080-43ac-11eb-8bd9-e83917a5e460.png)
