### ISSUE TITLE
Badge for "Tested with QUnit"

### ISSUE THREAD

**Issue by Krinkle** [badges/shields#5996]
:clipboard: **Description**

A badge for prominent tooling used by a project in ts development. For example, the linter or testing framework.

Manual workaround / Example:

[![Tested with QUnit](https://img.shields.io/badge/tested_with-qunit-9c3493.svg)](https://qunitjs.com/)
[![Tested with ESLint](https://img.shields.io/badge/tested_with-eslint-4B32C3.svg)](https://eslint.org/)

```md
[![Tested with QUnit](https://img.shields.io/badge/tested_with-qunit-9c3493.svg)](https://qunitjs.com/)
[![Tested with ESLint](https://img.shields.io/badge/tested_with-eslint-4B32C3.svg)](https://eslint.org/)
```

* Tested with: QUnit
* Tested with: ESLint
* Tested with: Mocha
* Tested with: Karma

:link: **Data**

(Declarative, static)

:microphone: **Motivation**

Developers sometimes enjoy showing which tools their projects are tested, built, or released with. Perhaps as self-documenting way to give a sense of how the project is developed, or out of pride/support for the tools they choose. It might give potential contributors a sense of familiarity if they know the tools, or might spread awareness of new and upcoming indie tools that are not yet mainstream.

Inspired by [aleen42/badges](https://github.com/aleen42/badges/blob/1.1.9/README.md#coder), which has these and many others listed already. However, those often use logos and don't use the more descriptive and scalable approach that makes shields.io useful. I'm open to prefixes other than "tested with". Other categories to consider instead, or in addition to, might be `built with …` , `released with`, or `uses …` (á la [Uses This](https://usesthis.com/)).

**Comment by chris48s** [comment]
Hello. The examples you've given (e.g: https://img.shields.io/badge/tested_with-qunit-9c3493.svg ) are the correct way to do this. That's what the customizable static badge is for :)
