### ISSUE TITLE
Invalid appveyor badge?

### ISSUE THREAD

**Issue by caspervonb** [badges/shields#601]
```markdown
![](https://img.shields.io/appveyor/ci/caspervonb/node-browser_process.svg)
```

Yields the following invalid badge

![](https://img.shields.io/appveyor/ci/caspervonb/node-browser_process.svg)

Sending a request to `https://ci.appveyor.com/api/projects/caspervonb/node-browser_process` yields a response with "
```json
{"message":"Project not found or access denied."}
```

Project status is available at https://ci.appveyor.com/project/caspervonb/node-browser-process so kinda stumped

**Comment by caspervonb** [comment]
Yeah so underscores are replaced by dashes by appveyor, so foo_bar becomes foo-bar.

**Comment by espadrine** [comment]
Ah right, so `https://img.shields.io/appveyor/ci/caspervonb/node-browser-process.svg` works. Good to know, thanks!
