### ISSUE TITLE
Different badges depending on how a license is specified in a Python package

### ISSUE THREAD

**Issue by Paebbels** [badges/shields#6013]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Shields.io generates different license shields for PyPI dependent on how a license is specified in `setup.py`.

| Specified via...        | PyPI Package | Badge |
| --- | --- | --- |
| Parameter | Coverage | ![PyPI - License](https://img.shields.io/pypi/l/Coverage) |
| Classifier | pyMetaClasses | ![PyPI - License](https://img.shields.io/pypi/l/pyMetaClasses) |
 

**Specified via parameter**
Example repository: https://github.com/nedbat/coveragepy  
PyPI Package: https://pypi.org/project/coverage/  
Badge: ![PyPI - License](https://img.shields.io/pypi/l/Coverage)
```python
setup(
# ...
  license='Apache 2.0',
  classifiers=[
    # ...
    "License :: OSI Approved :: Apache Software License",
    # ...
    ]
# ...
)
```
Source: https://github.com/nedbat/coveragepy/blob/master/setup.py?ts=2#L112

**Specified via license classifier**
Example repository: https://github.com/Paebbels/pyMetaClasses
PyPI Package: https://pypi.org/project/pyMetaClasses/  
Badge: ![PyPI - License](https://img.shields.io/pypi/l/pyMetaClasses)
```python
setup(
# ...
  classifiers=[
    # ...
    "License :: OSI Approved :: Apache Software License",
    # ...
  ]
# ...
)
```
Source: https://github.com/Paebbels/pyMetaClasses/blob/master/setup.py?ts=2#L74

The `license` parameter for `setuptools.setup()` is not documented in the user guide (see [setuptools "keywords"](https://setuptools.readthedocs.io/en/latest/userguide/keywords.html)), but in [full "keyword" list](https://setuptools.readthedocs.io/en/latest/references/keywords.html?highlight=license#keywords) and also not [recommended anymore](https://setuptools.readthedocs.io/en/latest/history.html?highlight=license#id232):
> v41.1.0 - Documentation changes: Use license classifiers rather than the license field.

:bulb: **Possible Solution**

Please check why shields.io produces different results based on how a license is specified in a package or how PyPI reports the result. My expectation is an equal result for the old and new style.

**Comment by chris48s** [comment]
Hello.

When we grab the API response from PyPI (e.g: https://pypi.org/pypi/pyVHDLModel/json ) if the license key isn't populated, we just grab text from the classifier string so the reason the badge is `license | apache software` and not `license | apache 2.0` is because the classifier is `License :: OSI Approved :: Apache Software License` and not `License :: OSI Approved :: Apache 2.0 License`. We don't make any attempt to match the classifier string to an SPDX id.

Relevant code:
https://github.com/badges/shields/blob/d3a7afdec0e97af80c16e598e4836dbff11a5602/services/pypi/pypi-helpers.js#L41-L78

It looks like we're converting classifiers to lowercase to make them easier to parse but I think in the case of licenses this is a mistake because it stops the formatting from working if the parsed license _does_ match a known SPDX ID in https://github.com/badges/shields/blob/fcf6678a127c9679b0d68284b860181c2580fe26/services/licenses.js (which are case-sensitive).

**Comment by calebcartwright** [comment]
Maybe I'm missing something, but all the example badges above look the same to me. Just for clarification, is the implication here that there's inconsistency between instances of our badges for different packages, or that the Shields license badge message differs from what's observed on the upstream service (PyPI in this case)

![image](https://user-images.githubusercontent.com/13042488/103483256-91745a00-4dab-11eb-808a-85c97275b0ce.png)

**Comment by Paebbels** [comment]
@calebcartwright I added as a quick workaround the parameter `license` in my package description, so I could go on. I'm sorry for the confusion. I have more packages on PyPI, so let me exchange the example to `pyMetaClasses` :). It will show the same effect.

The problem is: For the same license (here `Apache License, 2.0`), different colors and license texts/license identifiers are shown:  
![image](https://user-images.githubusercontent.com/956109/103483718-817b6b00-4de9-11eb-86cc-cd3ace14e607.png)  
(This time, I took a screenshot to preserve the moment.)

@chris48s  
The idea of shields it to unify information and present same/similar information in same style, right? So my expectation is that independent on how a package management system, programming language, API, etc. saves or transmits a license name, Shields.io will always present the same unique license as the same badge (color, size, text, ...).

A solution could be displaying licenses as short and/or long SDPX identifier. So in my example case, Python/PyPI classifiers are transformed to SPDX identifiers.

**Comment by Paebbels** [comment]
@chris48s as you pointed out, to underlying problem is mainly PyPI reporting no license via JSON API. I started an issue at PyPA to discuss the missing information in their API when changing the style of how to specify a license.

See pypa/warehouse#8960

While this may take time to be fixed, can you review the idea of a lookup table for shields.io to resolve the issue as a workaround?

**Comment by chris48s** [comment]
I've subscribed to https://github.com/pypa/warehouse/issues/8960 I'd be interested in what the guidance is from the PyPI folks on whether we should be prioritising the license field or classifiers. It is news to me that classifiers are now being recommended over the license field in setuptools (I'm not saying I doubt the link you posted).

I think if someone knows of/wants to contribute a mapping of PyPI classifiers to SPDX IDs we would accept a PR for it.
Doing some research it looks like, the relevant full list of classifiers is:

```
License :: OSI Approved :: Academic Free License (AFL)
License :: OSI Approved :: Apache Software License
License :: OSI Approved :: Apple Public Source License
License :: OSI Approved :: Artistic License
License :: OSI Approved :: Attribution Assurance License
License :: OSI Approved :: BSD License
License :: OSI Approved :: Boost Software License 1.0 (BSL-1.0)
License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)
License :: OSI Approved :: Common Development and Distribution License 1.0 (CDDL-1.0)
License :: OSI Approved :: Common Public License
License :: OSI Approved :: Eclipse Public License 1.0 (EPL-1.0)
License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)
License :: OSI Approved :: Eiffel Forum License
License :: OSI Approved :: European Union Public Licence 1.0 (EUPL 1.0)
License :: OSI Approved :: European Union Public Licence 1.1 (EUPL 1.1)
License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)
License :: OSI Approved :: GNU Affero General Public License v3
License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)
License :: OSI Approved :: GNU Free Documentation License (FDL)
License :: OSI Approved :: GNU General Public License (GPL)
License :: OSI Approved :: GNU General Public License v2 (GPLv2)
License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
License :: OSI Approved :: GNU General Public License v3 (GPLv3)
License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)
License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)
License :: OSI Approved :: IBM Public License
License :: OSI Approved :: ISC License (ISCL)
License :: OSI Approved :: Intel Open Source License
License :: OSI Approved :: Jabber Open Source License
License :: OSI Approved :: MIT License
License :: OSI Approved :: MITRE Collaborative Virtual Workspace License (CVW)
License :: OSI Approved :: MirOS License (MirOS)
License :: OSI Approved :: Motosoto License
License :: OSI Approved :: Mozilla Public License 1.0 (MPL)
License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)
License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)
License :: OSI Approved :: Nethack General Public License
License :: OSI Approved :: Nokia Open Source License
License :: OSI Approved :: Open Group Test Suite License
License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)
License :: OSI Approved :: PostgreSQL License
License :: OSI Approved :: Python License (CNRI Python License)
License :: OSI Approved :: Python Software Foundation License
License :: OSI Approved :: Qt Public License (QPL)
License :: OSI Approved :: Ricoh Source Code Public License
License :: OSI Approved :: SIL Open Font License 1.1 (OFL-1.1)
License :: OSI Approved :: Sleepycat License
License :: OSI Approved :: Sun Industry Standards Source License (SISSL)
License :: OSI Approved :: Sun Public License
License :: OSI Approved :: The Unlicense (Unlicense)
License :: OSI Approved :: Universal Permissive License (UPL)
License :: OSI Approved :: University of Illinois/NCSA Open Source License
License :: OSI Approved :: Vovida Software License 1.0
License :: OSI Approved :: W3C License
License :: OSI Approved :: X.Net License
License :: OSI Approved :: Zope Public License
License :: OSI Approved :: zlib/libpng License
```

That said, I suspect you could probably pick the most common 10 or 15 licenses on that list to map and it would cover 90% of packages or something, so a partial mapping would be a valid improvement.

Also preserving the casing would make some of these (e.g: BSD, MIT) normalise to the right thing anyway.

**Comment by Paebbels** [comment]
@chris48s Many thanks !
