### ISSUE TITLE
can't create badge for phonepe, infosys icons on simple icons

### ISSUE THREAD

**Issue by hasthamalp** [badges/shields#6015]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

icon is udated on simpleicons site but can't create badge on shield.io

:link: **Link to the badge**

![PHONEPE](https://img.shields.io/badge/Phonepe-Version-5F259F?style=for-the-badge&logo=phonepe)

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
Please refer to https://github.com/badges/shields/discussions/5369 for information on how updates to SimpleIcons get incorporated
