### ISSUE TITLE
pypi-python-versions values should be naturally sorted

### ISSUE THREAD

**Issue by dmyersturnbull** [badges/shields#6019]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Not sure why I'm bothering with this :) I guess it just *bothered* me.

`pypi-python-versions` is sorting like this: *3.10*, *3.8*, *3.9*.  
It should be *3.8*, *3.9*, *3.10*.

:link: https://img.shields.io/pypi/pyversions/tyrannosaurus

:bulb: **Possible Solution**

Is the issue somewhere [here](https://github.com/badges/shields/blob/master/services/pypi/pypi-python-versions.spec.js)?  
Oddly, this looks correct.

```javascript
    // Versions are properly sorted according to their Semver segments.
    given({ versions: ['3.10', '3.9', '3.8', '3.7', '3.6'] }).expect({
      message: '3.6 | 3.7 | 3.8 | 3.9 | 3.10',
      color: 'blue',
    })
```

**Comment by calebcartwright** [comment]
This has been fixed in source (d3a7afdec0e97af80c16e598e4836dbff11a5602) but not yet deployed to production
