### ISSUE TITLE
New SimpleIcons images are not getting displayed

### ISSUE THREAD

**Issue by rajat19** [badges/shields#6020]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
Simple-icons added a new release https://github.com/simple-icons/simple-icons/releases/tag/4.5.0
and new icons like 
- Express js - https://simpleicons.org/icons/express.svg
- Google colab - https://simpleicons.org/icons/googlecolab.svg
- Shields.io - https://simpleicons.org/icons/shields-dot-io.svg
etc.  were added in this release

But these images are not getting displayed while i am adding name of the logo in badges
https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=googlecolab&logoColor=white
![Google Colab](https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=googlecolab&logoColor=white)
I've even tried doing `google-colab` instead of `googlecolab`
https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=google-colab&logoColor=white
![Google Colab](https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=google-colab&logoColor=white)
https://img.shields.io/badge/express_js-000000?style=for-the-badge&logo=express&logoColor=white
![Express Js](https://img.shields.io/badge/express_js-000000?style=for-the-badge&logo=express&logoColor=white)
https://img.shields.io/badge/shields_io-000000?style=for-the-badge&logo=shields.io&logoColor=white
![Shields](https://img.shields.io/badge/shields_io-000000?style=for-the-badge&logo=shields.io&logoColor=white)

Whereas old icons are coming correctly
https://img.shields.io/badge/slack-4A154B?style=for-the-badge&logo=slack&logoColor=white
![Slack](https://img.shields.io/badge/slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)
https://img.shields.io/badge/socket_io-010101?style=for-the-badge&logo=socket.io&logoColor=white
![Socket](https://img.shields.io/badge/socket_io-010101?style=for-the-badge&logo=socket.io&logoColor=white)

:link: **Link to the badge**
https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=google-colab&logoColor=white
https://img.shields.io/badge/google_colab-F9AB00?style=for-the-badge&logo=googlecolab&logoColor=white
https://img.shields.io/badge/express-F9AB00?style=for-the-badge&logo=express&logoColor=white
https://img.shields.io/badge/shields_io-000000?style=for-the-badge&logo=shields.io&logoColor=white

**Comment by calebcartwright** [comment]
Please refer to #5369 for information on how updates to SimpleIcons get incorporated

**Comment by rajat19** [comment]
Thanks for the update
