### ISSUE TITLE
Support Wercker private projects

### ISSUE THREAD

**Issue by kilianc** [badges/shields#604]
Turns out both methods don't work with private projects. Wercker makes available their own badge using this API that we should probably use 

```
$ curl https://app.wercker.com/status/248faefe7474c5f7ff299c53f5a79f5e
```

With badge available at: https://app.wercker.com/status/248faefe7474c5f7ff299c53f5a79f5e/m

![](https://app.wercker.com/status/248faefe7474c5f7ff299c53f5a79f5e/m)

**Comment by espadrine** [comment]
Thanks for the suggestion!
How easy is it for users to find the `248faefe7474c5f7ff299c53f5a79f5e` bit?

**Comment by kilianc** [comment]
URL bar

**Comment by kilianc** [comment]
Actually. It is in the share page

![](https://www.dropbox.com/s/ugyant6obquwwfq/Screenshot%202015-12-30%2008.44.43.png?dl=1)

**Comment by espadrine** [comment]
I'll need to add this image to the documentation (we have a brand-new documentation system for the front page: https://github.com/badges/shields/commit/0536763b498b865e65db31243512356e7bcd2295#diff-20b51e3176fb8c62d5ce21aee43e6cd1R1029).

However, the front page already has a lot of image downloads. I'll consider this issue to depend on https://github.com/badges/shields/issues/633.

**Comment by paulmelnikow** [comment]
The wercker service has been ported and we've got a good pattern in place for secrets config now, so this should be fairly straightforward to add.

**Comment by chris48s** [comment]
Oracle shut down Wercker on 31 October so this is no longer relevant
