### ISSUE TITLE
Not recognizing MIT license on my github repo

### ISSUE THREAD

**Issue by invigorate** [badges/shields#6040]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The github license shield is not recognizing the MIT license on my repo: https://github.com/bytechem/dis-calc/ . says "not specified"

:link: **Link to the badge**

![license](https://img.shields.io/github/license/bytechem/dis-calc)

**Comment by calebcartwright** [comment]
I see you've updated the file extension in your repository, so I'm going to close this.

Shields gets the data from the upstream providers, we don't make determination about the licenses ourselves. I believe you can find more info [here](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license) on how GitHub does license detection on repositories

**Comment by invigorate** [comment]
Huh. Originally it wasn't working even after changing the extension. Maybe
the old one was cached...

**Comment by calebcartwright** [comment]
> Maybe the old one was cached...

Yes, we utilizing caching and have different lengths for different badge types. Licenses tend to be borderline static so they have a longer cache than say a build status badge

**Comment by invigorate** [comment]
Thanks for the heads up!
