### ISSUE TITLE
"staticPreview.link" is not allowed

### ISSUE THREAD

**Issue by rajat19** [badges/shields#6042]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
While working on https://github.com/badges/shields/issues/2271
I came across an issue 
`[ValidationError]: Example for GithubCommitActivity at index 0 "staticPreview.link" is not allowed`

The issue is generated if someone adds link in response to a service's render function and code for static Preview for that service uses `this.render`
example
```javascript
staticPreview: this.render({ interval: 'm', commitCount: 457, user: 'badges', repo: 'shields' })
```

example for github commit activity, If i change my function to 
```javascript
static render({ user, repo, interval, commitCount }) {
    const intervalLabel = {
      y: '/year',
      m: '/month',
      '4w': '/four weeks',
      w: '/week',
    }[interval]
    const slug = `${encodeURIComponent(user)}/${encodeURIComponent(repo)}`

    return {
      message: `${metric(commitCount)}${intervalLabel}`,
      link: [
        `https://github.com/${slug}`,
        `https://github.com/${slug}/graphs/code-frequency`,
      ]
    }
  }
```

Apparently found an earlier todo for the same https://github.com/badges/shields/blob/7ac57d993a7e776519c37ee8d321ef72653194c9/services/github/github-stars.service.js#L29-L30

Has there been any work on this todo ?
For now should i directly provide object (without link key) in `staticPreview` wherever I would be adding link in render's response ?

**Comment by PyvesB** [comment]
`staticPreview` is no longer a thing in our examples nowadays. Closing as this is no longer relevant.
