### ISSUE TITLE
Badge request: GitHub NPM package.json - optionalDependencies

### ISSUE THREAD

**Issue by Zimtir** [badges/shields#6044]
:clipboard:  - `optionalDependencies` from NPM package.json at GitHub need be supported like it supported `dependencies` and `devDependencies`. 

Example of view: `dependencyName: version`.

:link:  - similar to the getting of GitHub package.json `devDependencies` and `dependencies`

:microphone:  - **by default badges demonstrates packages that required to use, but optionalDependencies will provide info to user about packages that used, but can be substituted without damage to package**

**Comment by chris48s** [comment]
Just to clarify the request here, at the moment the "GitHub package.json dependency version" badge can optionally accept a `:kind` param telling it to look at dev or peer dependencies. This could be expanded to also cover optional .
https://github.com/badges/shields/blob/7ac57d993a7e776519c37ee8d321ef72653194c9/services/github/github-package-json.service.js#L83

**Comment by chris48s** [comment]
@Nazeeh21 - go for it :+1:

**Comment by calebcartwright** [comment]
I thought this was sorted by #6749 (pending merge)?

**Comment by chris48s** [comment]
Oh yes so it is - scratch that!
