### ISSUE TITLE
Add homebrew logo to homebrew/homebrew-cask badges

### ISSUE THREAD

**Issue by ddelange** [badges/shields#6046]
Homebrew logo was added a while ago (ref https://github.com/simple-icons/simple-icons/pull/3395):

![homebrew](https://img.shields.io/homebrew/v/pipgrip?logo=homebrew&logoColor=white)

[`https://img.shields.io/homebrew/v/pipgrip?logo=homebrew&logoColor=white`](https://img.shields.io/homebrew/v/pipgrip?logo=homebrew&logoColor=white)

Can the logo be added by default?

![image](https://user-images.githubusercontent.com/14880945/104158205-28b16100-53ed-11eb-92e5-fa7f1619758c.png)

**Comment by chris48s** [comment]
AS noted in the docs https://github.com/badges/shields/blob/fcf6678a127c9679b0d68284b860181c2580fe26/CONTRIBUTING.md#badge-guidelines logos are always off by default for badges using the default style. If you want to add a logo, adding `logo=homebrew` to your query string, as you've done in your post is the correct way to do it. :+1:
