### ISSUE TITLE
Would be cool for updown.io badges

### ISSUE THREAD

**Issue by balupton** [badges/shields#605]
https://updown.io/api / https://updown.io/gn4o

**Comment by espadrine** [comment]
Thanks for the suggestion! What kind of badges would you like to see? Can you provide examples with `/badge/` shields.io links?

**Comment by balupton** [comment]
I guess just an online/offline badge based on whether the website is up or not. Maybe also the uptime stat as a badge too, would be nice, but not something I really care about. The online/offline one would be useful in the same way the travis badge is useful.

**Comment by UdoKifferbrehl** [comment]
+1

**Comment by RedSparr0w** [comment]
This could probably be closed as `https://img.shields.io/website/http/shields.io.svg` fills the purpose of online|offline badges?

**Comment by espadrine** [comment]
Ok, I think it addresses the use-case.

**Comment by HugoOppels** [comment]
I am interested in an updown.io integration too, especially the 30 days uptime ratio. 

By the way, is the online|offline badge using  `https://img.shields.io/website/http/shields.io.svg`
working in the same way like updown.io, NodePing or Uptime Robot? 
![up](https://user-images.githubusercontent.com/62393988/82740443-09c06a80-9d49-11ea-9258-d95bbe139486.PNG)
