### ISSUE TITLE
SoloLearn Shield

### ISSUE THREAD

**Issue by anabeatrizzz** [badges/shields#6050]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Hello,
I would like to know why SoloLearn icon isn't displaying in my shield (link below).
I'm using [Simple Icons](https://simpleicons.org/?q=sololearn).

:link: **Link to the badge**
https://img.shields.io/badge/sololearn-1ABC9C?logo=SoloLearn&labelColor=000000&style=for-the-badge

**Comment by calebcartwright** [comment]
Please review #5369 for more information about how upstream updates to SimpleIcons get pulled into the Shields ecosystem
