### ISSUE TITLE
Badge Request: Default Branch

### ISSUE THREAD

**Issue by hnarasaki** [badges/shields#6065]
:clipboard: **Description**

When creating a new repo, sometimes the default branch defaults to main, sometimes it defaults to master, etc. 
In a repo, if the default branch has been changed from `master` to `main` for example, would like a visual cue to indicate that for contributors.

**Comment by calebcartwright** [comment]
> In a repo, if the default branch has been changed from master to main for example, would like a visual cue to indicate that for contributors.

It's not entirely clear to me what you're asking of Shields. If a maintainer of a repository wants to use a badge from our service that indicates what their default branch is, then I suppose they could simply use our static badge builder:

https://img.shields.io/badge/default%20branch-main-blue
![](https://img.shields.io/badge/default%20branch-main-blue)

However, Shields has no insight into historical branch history, so there's no way we could reflect that at some point in the past a repository had a different default branch name which was subsequently changed
