### ISSUE TITLE
SimpleIcons Blazor won't work

### ISSUE THREAD

**Issue by Hona** [badges/shields#6079]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

[The SimpleIcons Blazor](https://simpleicons.org/?q=blazor) icon won't work

:link: **Link to the badge**

<img src="https://img.shields.io/badge/Blazor-512BD4.svg?&style=for-the-badge&logo=Blazor&logoColor=white">
<a href="https://img.shields.io/badge/Blazor-512BD4.svg?&style=for-the-badge&logo=Blazor&logoColor=white">https://img.shields.io/badge/Blazor-512BD4.svg?&style=for-the-badge&logo=Blazor&logoColor=white</a>

**Comment by calebcartwright** [comment]
Please review our documented process for incorporating updates fro the upstream SimpleIcons package in https://github.com/badges/shields/discussions/5369
