### ISSUE TITLE
shields.io is tracked by CloudFlare

### ISSUE THREAD

**Issue by techtonik** [badges/shields#608]
Chrome page audit shows that requiest to shields.io sends 8.9KB of cookies. The guilty is this CloudFlare cookie which seems to be impossible to turn off:

http://webmasters.stackexchange.com/questions/59226/disable-cfduid-cookie-from-cloudflare

What are other alternatives to CloudFlare?

**Comment by espadrine** [comment]
Huh, I didn't know about it. That said, it is only on the main page, not on badges, so the harm is limited.

CloudFlare provides us TLS with valid certificates. An alternative would be let's encrypt, but at this point, it would be quite a hassle to set up.

**Comment by techtonik** [comment]
@espadrine why do you think it is only on the main page? GitHub just caches all that content, so there are no direct requests to CloudFare.

**Comment by espadrine** [comment]
Ah, true. The cookie spans `.shields.io`. I understand CloudFlare's justification, but it feels like something that they should allow disabling. [Their argument](https://support.cloudflare.com/hc/en-us/articles/200169816-Can-I-serve-a-cookieless-domain-or-subdomain-through-CloudFlare-) doesn't apply here since they cannot cache my content, even if I wanted them to.

I'll try to use let's encrypt instead.

**Comment by techtonik** [comment]
let's encrypt is not a CDN. Do you mean switch to self-hosting shields?

**Comment by espadrine** [comment]
We already self-host shields. We don't have a CDN. The only thing we use CloudFlare for is its free TLS certificates.

**Comment by techtonik** [comment]
So, what server is used? Is the production configuration explained somewhere? From https://github.com/badges/shields/blob/master/INSTALL.md#start-the-server it looks like it is running Node. Is there `nginx` or something?

**Comment by techtonik** [comment]
[Different ways to fetch certificates](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins)

**Comment by espadrine** [comment]
I tried adding more information. I use a node server pretty much directly.

**Comment by anantshri** [comment]
Today i have started to get cloudflare warnings on img.shields.io as per this conversation looks like cloudflare was suppose to only work on shields.io. Can you check and suggest.

**Comment by paulmelnikow** [comment]
I think this should be fixed for the home page, which no longer uses Cloudflare.
