### ISSUE TITLE
Voting badges

### ISSUE THREAD

**Issue by LucBerge** [badges/shields#6099]
:clipboard: **Description**

The idea would be to have voting badges like [this project](https://github.com/azu/voting-badge). Azu's project is using Shield.io API to create the badges. Integrating it to Shield.io would easier since it is not maintained since 7 years...

2 endpoints:
- Get the badge.
- Vote by incrementing the value.

:link: **Data**

There must be a database where to store the counter value. Either by using a github workaround or by using shield.io's database.

:microphone: **Motivation**

Let's imagine you want users to be able to rate the repo [badges/shields](https://github.com/badges/shields) between `unsatisfied`, `correct`, `great` and `ammazing`. People juste have to click on the badge to increment the value. **Of course, spamming shouldn't be allowed...**

You can also do quick surveys, about anything you want.

**Comment by chris48s** [comment]
I don't think we'd ever accept a badge implementation that requires us to store persistent state like this into core. If it is going to exist, it will have to be a userspace implementation (like the one you've linked to).

> using shield.io's database

We don't have one :) Being a read-only service which is almost completely stateless is one of the properties that allows us to run this service at the scale we do with the level of resources we have.

**Comment by LucBerge** [comment]
I was expecting this answer... At least I tried. Then I'll try to do my own JSON endpoint and use your JSON endpoint API.
