### ISSUE TITLE
[Youtube] subscriber counter/ total view time

### ISSUE THREAD

**Issue by Gamemap** [badges/shields#6111]
:clipboard: **Description**

Service: Youtube
<img src="https://img.shields.io/badge/Total%20Subscriber-135-green" />
<img src="https://img.shields.io/badge/Total%20View%20Time-135h-red" />

:link: **Data**

-Youtube API   (I don't know exactly how)

:microphone: **Motivation**

Maks the information on an internetsite visible to show how "good" the youtube channel is.

**Comment by PyvesB** [comment]
Hello @Gamemap ! 👋🏻 

I believe we can get the number of subscribers to a channel using the following API: https://developers.google.com/youtube/v3/docs/channels

However, after a quick read through the documentation, I see no way of retrieving a total view time. Could you please have a browse through as well to make sure I haven't missed anything?

**Comment by Gamemap** [comment]
Hi,

in the Json list I found this:
 

> "statistics": {
>     "viewCount": unsigned long,
>     "subscriberCount": unsigned long,  // this value is rounded to three significant figures
>     "hiddenSubscriberCount": boolean,
>     "videoCount": unsigned long
>   },
> 

The tabel says:

> statistics.viewCount |   The number of times the channel has been viewed.

Is this we are searching for?

Could you also add the total videos count?

> statistics.videoCount |  The number of public videos uploaded to the channel. Note that the value reflects the count of         the                  >                                    channel's public videos only, even to owners. This behavior is consistent with counts         shown on the >                                    YouTube website.


Thank you,
Gamemap

**Comment by PyvesB** [comment]
> > statistics.viewCount |   The number of times the channel has been viewed.
> 
> Is this we are searching for?

Well, not really, that gives us no clue of the total view time for a given channel. Videos in a channel will have different lengths and most users would not watch them in full anyway, so you can't link the number of users who pressed play to a duration.

**Comment by Gamemap** [comment]
Is this the time, which is displayed on the Youtube Creators site?

**Comment by PyvesB** [comment]
> Is this the time, which is displayed on the Youtube Creators site?

I wouldn't know for sure, I don't think I've ever used that part of YouTube before.

**Comment by Gamemap** [comment]
You find at https://studio.youtube.com the subscribers and the monetization tab shows the viewtime (if you don't have reacht the goal) (I found only this place with viewtime)

**Comment by PyvesB** [comment]
Okay, so coming back to my initial question, you are confirming that there is no way to retrieve the total view time via the API?

**Comment by Gamemap** [comment]
Yes, I think so.

**Comment by PyvesB** [comment]
> I found this: https://developers.google.com/youtube/reporting/v1/reports/metrics#watch_time_minutes
> There you can also find `subscribers_gained` or other cool statistics.

As far as I can tell, that API is deprecated and there doesn't seem to be an obvious equivalent in the v3 one.

**Comment by Gamemap** [comment]
Ok

**Comment by PyvesB** [comment]
The total subscriber badge can still probably be done though, feel free to submit a pull request. We've got an [nice tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) on how to add badges and you can also leverage the implementation I wrote for the existing Youtube badges. 😉

**Comment by Gamemap** [comment]
Thank you for this tutorial but unfortunately I don't have time to learn this at the moment. If you or someone else have the time to code it would be great but there is no hurry.

**Comment by PyvesB** [comment]
This has now been deployed to production, thanks to @tarun7singh for his contribution! 🍾

**Comment by Gamemap** [comment]
Thank you very much!
