### ISSUE TITLE
Depfu badge shows "not found"

### ISSUE THREAD

**Issue by Hongbo-Miao** [badges/shields#6112]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

The Shield version Depfu badge works before. However, today I renamed a sub-folder from `server` to `api`. The badge becomes "not found".

I did update the info on Depfu to let it scan `api` sub-folder instead of old `server`.

However, Shield version Depfu badge still shows "not found" after around four hours.
![Depfu](https://img.shields.io/depfu/Hongbo-Miao/hongbomiao.com)

Official badge from Depfu works after I updating the info.
[![Depfu](https://badges.depfu.com/badges/99b1d5970eb895164b0b0914bd65eb71/overview.svg)](https://depfu.com/github/Hongbo-Miao/hongbomiao.com)

:link: **Link to the badge**

Shield version: https://img.shields.io/depfu/Hongbo-Miao/hongbomiao.com
Depfu own version: https://badges.depfu.com/badges/99b1d5970eb895164b0b0914bd65eb71/overview.svg

The project on Depfu is at https://depfu.com/github/Hongbo-Miao/hongbomiao.com

**Comment by chris48s** [comment]
Hello. We call and endpoint on the depfu service. For your project, we're getting a 404 on that endpoint:

```
$ curl -I "https://depfu.com/github/shields/Hongbo-Miao/hongbomiao.com"
HTTP/1.1 404 Not Found
```

but it seems to be working ok for other projects:

```
$ curl -I "https://depfu.com/github/shields/depfu/example-ruby"
HTTP/1.1 200 OK
```

Can you raise this as an issue with depfu. I don't think it is an issue with shields.

**Comment by Hongbo-Miao** [comment]
Thanks @chris48s ! I will follow up with Depfu. And report back for what I found!

**Comment by halfbyte** [comment]
@Hongbo-Miao @chris48s Hi Jan from Depfu here. Yes this was a problem with us, the state of the Repo was not up to date. As you can see in the original text the shields.io badge now shows the correct value.

**Comment by Hongbo-Miao** [comment]
Thanks @halfbyte for the help!

**Comment by smshuja** [comment]
@halfbyte This seems to be broken again.
