### ISSUE TITLE
Nuget badge shows "Package not found"

### ISSUE THREAD

**Issue by MrYossu** [badges/shields#6134]
Are you experiencing an issue with...

- [x ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: Not sure if this is a bug, or something I've done wrong. I created a badge for a Nuget package using the URL generator on your site, and copied it into my Readme.md file in GitHub. Here is the markdown...

[![Pixata.Blazor Nuget package](https://img.shields.io/nuget/v/Pixata.Blazor, "Pixata.Blazor Nuget package")](https://www.nuget.org/packages/Pixata.Blazor/)

Note that your generator added a trailing slash to the URL, which caused it not to work at all. Removing the slash showed a badge, but without the version number...

:link: https://img.shields.io/nuget/v/Pixata.Blazor

Anyone any idea what I'm doing wrong? Thanks

**Comment by MrYossu** [comment]
Hmm, not sure if this is the same issue, but I'm having a problem with the "Last commit" badge as well. I generated a URL for the main GitHub repository...

https://img.shields.io/github/last-commit/MrYossu/Pixata.Utilities/master

If I view this in a browser, it shows fine. If I use it in a markdown file as follows...

    ![Last commit to master](https://img.shields.io/github/last-commit/MrYossu/Pixata.Utilities/master, "Last commit to master")

...the the badge shows, but it says "repo not found"...

![Last commit to master](https://img.shields.io/github/last-commit/MrYossu/Pixata.Utilities/master, "Last commit to master")

If this is a separate problem, please let me know and I'll open a new issue for it.

Thanks for any help you can give.

**Comment by chris48s** [comment]
https://img.shields.io/nuget/v/Pixata.Blazor works fine for me and I can't reproduce the builder adding a trailing slash. Please give us steps to make this happen if you can reproduce it.

Your markdown link should be `![Last commit to master](https://img.shields.io/github/last-commit/MrYossu/Pixata.Utilities/master)`

In markdown the alt text goes between the square brackets and the link in the round ones, so in your markdown snippet `, "Last commit to master"` is being passed as part of the branch name.

**Comment by MrYossu** [comment]
@chris48s Thanks for the reply. Your Markdown correction fixed both problems. 

As for the trailing slash, all I did was use the generator on https://shields.io/. However, I just tried it again and it didn't include a trailing slash, so whether this was Visual Studio being "helpful" and adding one (possible), or me being dopey (very likely) I don't know.

Either way, works now, so thanks very much.
