### ISSUE TITLE
Make Twitch a social badge

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6158]
:clipboard: **Description**

Our Twitch badges are currently part of the `activity` category. All other badges in that category refer to release dates or contributions, whereas the Twitch badge only really indicates "is this user currently streaming live?", which feels quite unrelated. The `social` category seems much more appropriate, and I suggest we also modify the badge's default style to be social as well.

What do people think?

**Comment by calebcartwright** [comment]
> The `social` category seems much more appropriate, and I suggest we also modify the badge's default style to be social as well.
> 
> What do people think?

I think that's a reasonable category change. I often struggle to place the category for some badges which can seemingly go in multiple, but I can see the social category being a better argument for this one.

Could you elaborate on the change to the default style? Does that mean that existing twitch badges that don't have an explicit `style` query param set would all be changed to the social style?

**Comment by PyvesB** [comment]
> Could you elaborate on the change to the default style? Does that mean that existing twitch badges that don't have an explicit `style` query param set would all be changed to the social style?

Yes, I'm suggesting changing the default style of all Twitch badges without an explicit style parameter. Three thoughts to justify this:
* users can always go back to the previous style by adding the query parameter.
* Twitch badges aren't massively popular so impact would actually be quite limited. In  #4778 and  #5214 we took several weeks before noticing the badge was completely broken, with no users reporting the problems.
* not giving them the social style would mandate that links be removed in  #6159, which is a different potential impact on existing users.

**Comment by calebcartwright** [comment]
Those are sound arguments which make for a logically defensible position :+1: 

Making any change in Shields that results in any impact on any existing badge always gives me great angst, but I can get on board with this as long as we do the typical messaging campaign before actually deploying the change

**Comment by calebcartwright** [comment]
Actually one other point for consideration from recent discussions I'd already forgotten about :laughing: 

We recently removed the default style override to social on the GitHub sponsors badge in #5888 and my recollection is that we generally wanted to try to avoid overriding the default. Do others recall that discussion, and/or is it inapplicable here (or worth overriding in this case anyway)?

I generally don't have a strong opinion on this one way or the other, just trying to recall any recent relevant conversation

**Comment by PyvesB** [comment]
I've probably missed a subtlety here: GitHub Sponsors still effectively defaults to `social` from the point of view of a user going through our homepage, given that the UI will add `style=social` by default for those badges. #5888 effectively moved things from being a backend override to a UI preview one. I suggest we stay consistent for Twitch badges: change the category and the style default in the homepage, but leave existing users as is.
