### ISSUE TITLE
Github badges are down

### ISSUE THREAD

**Issue by AdrieanKhisbe** [badges/shields#617]
Currently github badges give a `vendor | unresponsive` after few seconds

ex: 
https://img.shields.io/github/tag/strongloop/express.svg -> ![](https://img.shields.io/github/tag/strongloop/express.svg)

**Comment by espadrine** [comment]
That's odd! It means that the request took more than 20 seconds. It seems fine now; I'll try to see what happened.

**Comment by AdrieanKhisbe** [comment]
indeed it's good now it seems

**Comment by AdrieanKhisbe** [comment]
shall I close the issue, or wait you investigate?

**Comment by remexre** [comment]
Looks like it might be back, at least once for me.

**Comment by espadrine** [comment]
@remexre back as in live, or back as in down?

**Comment by remexre** [comment]
Back down for at least 4 or 5 minutes. They didn't load at all when embedded, but when I went to the URL directly, I got the vendor unresponsive message. Ditto for cURLing them. Last I checked, they were up again, so intermittent weirdness?

**Comment by pydsigner** [comment]
They're down again for me.

**Comment by AriaFallah** [comment]
Down again right now :/

<img width="912" alt="screen shot 2016-01-19 at 9 59 53 am" src="https://cloud.githubusercontent.com/assets/9424976/12422153/762466c0-be93-11e5-9f94-2257d8e8f567.png">

**Comment by davej** [comment]
Down again, timing out.

**Comment by lots0logs** [comment]
```
Failed to load resource: the server responded with a status of 522 (OK)
https://img.shields.io/imagelayers/image-size/_/ubuntu/latest.svg Failed to load resource: the server responded with a status of 522 (OK)
https://img.shields.io/imagelayers/layers/_/ubuntu/latest.svg Failed to load resource: the server responded with a status of 522 (OK)
https://img.shields.io/david/dev/strongloop/express.svg Failed to load resource: the server responded with a status of 522 (OK)
https://img.shields.io/gem/u/raphink.svg Failed to load resource: the server responded with a status of 522 (OK)
```

**Comment by espadrine** [comment]
Sorry, Linux crashed. I took about 20 hours to notice.

**Comment by MDXDave** [comment]
https://github.com/MDXDave/ModernWebif/blob/master/README.md

Release version not recognized or image not shown due to timeout

**Comment by paulmelnikow** [comment]
Feel free to open a new issue if this issue recurs.
