### ISSUE TITLE
HHVM Branch 500 error

### ISSUE THREAD

**Issue by KorvinSzanto** [badges/shields#618]
Example: ![](https://img.shields.io/hhvm/concrete5/concrete5/develop.svg)

Trying to use the HHVM badge with a branch results in a "hhvm | invalid" badge. When you navigate to the built hhvm.h4cc.de url, [you actually get a 500 error](http://hhvm.h4cc.de/badge/concrete5/concrete5.json?branch=develop).

**Comment by espadrine** [comment]
https://img.shields.io/hhvm/symfony/symfony/master.svg works, so I'd assume it has to do with your URL in particular.

As you might have guessed, we perform a request to http://hhvm.h4cc.de/badge/concrete5/concrete5.json?branch=develop, which fails.

A request to http://hhvm.h4cc.de/package/concrete5/concrete5.json suggests that you are actually looking for https://img.shields.io/hhvm/concrete5/concrete5/dev-develop.svg, which works.

Does that solve your issue?

**Comment by KorvinSzanto** [comment]
@espadrine It does solve my issue assuming that dev-develop would map to my git develop branch, see https://github.com/concrete5/concrete5/tree/develop

**Comment by espadrine** [comment]
I don't know enough about HHVM to know for sure how it maps things up. You could try pinging someone in their team.
