### ISSUE TITLE
pkgreview badges failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6186]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Pkgreview badges all fail with 'unparseable json response' e.g: https://img.shields.io/pkgreview/rating/npm/react

:link: **Link to the badge**

https://img.shields.io/pkgreview/rating/npm/react

:bulb: **Possible Solution**

The reason the badges are failing is because https://pkgreview.dev/ is just serving a "This domain has expired" page.
@KumarAbhirup - do you have any intention of bringing this service back to life, or is it gone for good?

**Comment by PyvesB** [comment]
This is probably related:
https://twitter.com/kumar_abhirup/status/1351450580326129665?s=19

I believe he's moved it to pkgreview.now.sh.

**Comment by KumarAbhirup** [comment]
Oh yes, the domain is moved now, was freeing up domains haha. 

It will just require changing the domain name to `https://pkgreview.now.sh` to get it working.
