### ISSUE TITLE
?label= override not working

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [badges/shields#619]
According to the shields.io landing page,

    Here are a few other parameters you can use:
        ?label=healthinesses        Override the default left-hand-side text

I can't get this to work: Trying to squeeze another couple badges into the available space on a GitHub README, and I can't for the life of me get this badge to change from `dependencies` to plain `deps`:

`https://img.shields.io/gemnasium/ELLIOTTCABLE/Paws.js.svg?label=deps` ![](https://img.shields.io/gemnasium/ELLIOTTCABLE/Paws.js.svg?label=deps)

**Comment by AdrieanKhisbe** [comment]
@ELLIOTTCABLE, can't reproduce.
The labelling is working fine.

**Comment by ELLIOTTCABLE** [comment]
…

<img width="543" alt="screen shot 2016-01-26 at 8 54 52 pm" src="https://cloud.githubusercontent.com/assets/200/12602452/1083996c-c46f-11e5-87ef-854e492dab6f.png">

**Comment by AdrieanKhisbe** [comment]
@ELLIOTTCABLE. Now I do. :D
When I did it, I had `deps`, (believe me, I swear :smiley:), but I had some invalid or timeout.
Might be related.

> Ps: No, no, no, that was not denial :D

**Comment by ELLIOTTCABLE** [comment]
@AdrieanKhisbe hahahaha. Sorry my reply was so short! I was just, like “wat. Is it *resolving* differently for me, then? 'cuz that's *especially* weird.”

Let me know if there's anything else I can do to help track it down! (=

**Comment by espadrine** [comment]
Thanks for reporting!

**Comment by makus82** [comment]
[![Linux Build Status](https://travis-ci.org/OpenApoc/OpenApoc.svg?branch=master&label=linux)](https://travis-ci.org/OpenApoc/OpenApoc)

**Comment by makus82** [comment]
https://img.shields.io/gemnasium/ELLIOTTCABLE/Paws.js.svg?label=test
