### ISSUE TITLE
Add homebrew download stats

### ISSUE THREAD

**Issue by kdheepak** [badges/shields#6190]
:clipboard: **Description**

- Which service is this badge for: Homebrew
- What sort of information should this badge show?: Download stats
  Provide an example in plain text e.g: "downloads | 1200/year" 

:link: **Data**

Where can we get the data from?

- Is there a public API?: yes
- Does the API requires an API key?: No
- Link to the API documentation: https://formulae.brew.sh/formula/

:microphone: **Motivation**

Please explain why this feature should be implemented and how it would be used.

- What is the specific use case?

It would be nice to show download stats from homebrew, similar to how we can now show download stats from github releases.

**Comment by calebcartwright** [comment]
I'm having a bit of deja vu with this request, though can't seem to find any issues where we've discussed it previously.

We wouldn't want to use https://formulae.brew.sh/api/formula.json as that's way too big and takes way too long to retrieve, but i guess we could look at the analytics.install fields in the formula-specific api response (which is what we use for the version badges) to get the raw data.

This would be a relatively easy badge to add, and would recommend anyone interested in implementing take a look at our [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) as well as the existing [homebrew version badge code](https://github.com/badges/shields/blob/master/services/homebrew/homebrew.service.js) for reference. Note it might be beneficial to extract the common bits out (like the `fetch` function) into a separate helpers file or a base class that the existing version badge and future downloads badge could extend

**Comment by kdheepak** [comment]
Thanks for the comment! I submitted a PR for this.
