### ISSUE TITLE
Support for build status from jenkins.ci.cloudbees.com

### ISSUE THREAD

**Issue by damianszczepanik** [badges/shields#621]
Several Jenkins plugins are hosted over [https://github.com/jenkinsci](Github) and even [[https://github.com/jenkinsci/cucumber-reports-plugin/pull/10](built) on jenkins.ci.cloudbees.com when PR is submitted.

That would be nice to be able to put shield on README page and show build [https://jenkins.ci.cloudbees.com/job/plugins/](status)

**Comment by espadrine** [comment]
Is this related to https://github.com/badges/shields/issues/622? It sounds like the same issue, but I might be missing something.

**Comment by damianszczepanik** [comment]
Same
