### ISSUE TITLE
Support for Jenkins plugin version

### ISSUE THREAD

**Issue by damianszczepanik** [badges/shields#622]
Jenkins supports list of the plugins with versions as [JSON](http://updates.jenkins-ci.org/update-center.json) file. It would be great if I can put shield on my README to inform everyone about last release which has been published over Jenkins repository.

This is already supported for many repository so why not Jenkins?

**Comment by espadrine** [comment]
Thanks for the suggestion! What URL would you like to have for that feature?

**Comment by damianszczepanik** [comment]
It should work similar to maven repository. Instead maven central repository, above json could be used as provider

**Comment by mikkopiu** [comment]
Added quick PR here: #1158
