### ISSUE TITLE
Is it possible to set the "subject" color?

### ISSUE THREAD

**Issue by IonicaBizau** [badges/shields#623]
Currently we can set the status color. But is it possible to set the background color of the subject? 

It would be a nice feature!

Thanks for amazing service! :sparkles:

**Comment by Foorack** [comment]
:+1:

**Comment by IonicaBizau** [comment]
My workaround was to download the svg file, edit it in InkScape and upload it on GitHub Pages and then use it. :smile: Maybe it helps someone.

**Comment by Foorack** [comment]
@IonicaBizau Thanks, will try it once the service comes back online. ^^

**Comment by espadrine** [comment]
Thanks for raising this issue! There's an old PR for that: https://github.com/badges/shields/pull/547, if you're interested in finishing it.

**Comment by IonicaBizau** [comment]
@espadrine That's great. I'm a bit busy right now, but I +1'ed that PR. :grin:

**Comment by jasonkarns** [comment]
#547 has been closed. this issue can be closed

(tldr: right-side bgcolor can be specified via query param `colorA`.
