### ISSUE TITLE
Google Scholar Badge

### ISSUE THREAD

**Issue by stalhabukhari** [badges/shields#6231]
:clipboard: **Description**
I wish to have a badge for Google Scholar, similar to [this badge for Twitter](https://img.shields.io/badge/twitter-%230077B5.svg?&style=for-the-badge&logo=twitter&logoColor=white&color=00acee).

:microphone: **Motivation**
For my webpage!

**Comment by calebcartwright** [comment]
Thanks for reaching out, but going to close this as there's no action to be taken. 

The link you've provided is an instance of our static badge build service that's already available for anyone to build any badge they want. 

https://img.shields.io/badge/twitter-%230077B5.svg?&style=for-the-badge&logo=twitter&logoColor=white&color=00acee
![](https://img.shields.io/badge/twitter-%230077B5.svg?&style=for-the-badge&logo=twitter&logoColor=white&color=00acee)

https://img.shields.io/badge/badge%20can%20be-anything%20you%20want-orange?style=flat-square&logo=github&logoColor=white
![](https://img.shields.io/badge/badge%20can%20be-anything%20you%20want-orange?style=flat-square&logo=github&logoColor=white)

The issue description did not contain enough data to suggest a specific badge url for you, but the Shields.io site has a section that can be leveraged interactively to help you build out your badge url with whatever attributes you need.

https://shields.io/#your-badge
