### ISSUE TITLE
The first thing You

### ISSUE THREAD

**Issue by Mexicool** [badges/shields#6232]
:clock11: **When did the problem start?**

:camera: **Live badge**

![]( url goes here )

:wrench: **Is the live badge working?**

:link: **CircleCI link**

:beetle: **Stack trace**

```
<!-- Provide the complete stack trace from the CircleCI test summary. -->
```

:bulb: **Possible solution**

**Comment by calebcartwright** [comment]
Going to close this as it seems like spam. If you are indeed attempting to report a failing service test, please make sure there's not already an open issue, and fill out the requisite data points enumerated in the issue template.
