### ISSUE TITLE
Badge request: GitHub last-commit variant based on "committer" timestamp

### ISSUE THREAD

**Issue by pukkandan** [badges/shields#6236]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Some commits can have a different "commit created" date and "committed date". This is especially seen when cherry-picking. In this case, the last commit badge shows the date of commit creation rather than the "committed date". 
![image](https://user-images.githubusercontent.com/6623388/109649500-0385d700-7b82-11eb-881c-7e6b8a8ac302.png)

I don't know if this is intended behaviour - hence why I am opening this as a bug report. If this is indeed how it is expected to work, please consider this as a feature request to add a badge of the latter

:link: https://img.shields.io/github/last-commit/yt-dlp/yt-dlp/master

![Last Commit](https://img.shields.io/github/last-commit/yt-dlp/yt-dlp/master) 
Since the badge will change as soon as I push a new commit, I am also attaching a screenshot of how it looks like as of https://github.com/yt-dlp/yt-dlp/commit/097b056c5a4f0374595798db0c663b9282acdf01
![image](https://user-images.githubusercontent.com/6623388/109648845-1ba92680-7b81-11eb-8cb6-f1a1cc324d75.png)

**Comment by pukkandan** [comment]
I'm sure I opened this as a bug report. No idea how it got tagged as `question`

**Comment by chris48s** [comment]
You're right that this badge looks at the "author" timestamp rather than the "committer" timestamp. It has been like that since the badge was added in 2017 so we wouldn't make that behaviour change to the existing badge now.
We could accept a PR for a second variant that shows the "committer" date instead if someone is interested in working on it.

https://github.com/badges/shields/blob/cf7c9c11471bb227069c013657491d842f6c7940/services/github/github-last-commit.service.js#L72

**Comment by rammba** [comment]
Here is one example where author & committer are really different:

<img width="185" height="63" alt="Image" src="https://github.com/user-attachments/assets/a83d0917-9d56-4836-8856-437a6de45785" />

https://img.shields.io/github/last-commit/notepad-plus-plus/notepad-plus-plus?label=committer&path=PowerEditor/installer/nativeLang&display_timestamp=committer
https://img.shields.io/github/last-commit/notepad-plus-plus/notepad-plus-plus?label=author&path=PowerEditor/installer/nativeLang&display_timestamp=author

**Comment by jNullj** [comment]
@rammba if you found a new bug please open a new issue and don't bump and old closed one.
