### ISSUE TITLE
Missing Microsoft Teams Icon on shields.io

### ISSUE THREAD

**Issue by jannismain** [badges/shields#6237]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

As far as I understand, you are pulling icons from [Simple Icons](https://simple-icons.github.io/simple-icons-website/). There, I can find an [Icon for Microsoft Teams](https://simple-icons.github.io/simple-icons-website/?q=microsoftteams) but when trying to generate a badge with this name, it won't show the icon. 

What am I missing?

:link: **Link to the badge**
https://img.shields.io/badge/MS_Teams-Go_to_Channel-6264A7?logo=microsoftteams

**Comment by calebcartwright** [comment]
The logo reference is supposed to be `microsoft-teams`, e.g. 
https://img.shields.io/badge/MS_Teams-Go_to_Channel-6264A7?logo=microsoft-teams
![](https://img.shields.io/badge/MS_Teams-Go_to_Channel-6264A7?logo=microsoft-teams)

The need to use dashes in place of spaces for multi-word logo references is mentioned in our docs on https://shields.io/#styles

> Simple-icons are referenced using names as they appear on the simple-icons site. If the name includes spaces, replace them with dashes (e.g: ?logo=visual-studio-code)
