### ISSUE TITLE
badge-maker undefined fields

### ISSUE THREAD

**Issue by kaos** [badges/shields#6238]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [x] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

```
error TS2345: Argument of type '{ message: string; color: string | null; label: string | null; labelColor: string | null; style: "plastic" | "flat" | "flat-square" | "for-the-badge" | "social" | null; }' is not assignable to parameter of type 'Format'.
  Types of property 'label' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

65           return makeBadge(format);
                              ~~~~~~


Found 1 error.
```

https://github.com/badges/shields/blob/ddc9ee5394e9de218b2089df7c1a64048e969c82/badge-maker/lib/index.js#L45

EDIT: Bah, I found a work-around for the type issue, only to find that the suggested fix doesn't help since we get caught by `_validate()` before `_clean()` is called.

:bulb: **Possible Solution**

Check for `undefined` instead of/in addition to `null` in `_clean(format)` ;)

**Comment by paulmelnikow** [comment]
Hi! Could you include your code which triggers the error?

**Comment by kaos** [comment]
Absolutely.

```js
          const format = {
            message: badge.message,
            color: badge.color || null,
            label: badge.label || null,
            labelColor: badge.labelColor || null,
            style: badge.style || null,
          }; // as Format; // adding the "as Format" gets me past the typescript compiler
          return makeBadge(format);
```

I've reverted to default to empty strings, which worked ok for all fields, except `style`.

Example work-around:

```js
          const format = {
            message: badge.message,
            color: badge.color || '#36BAA2',
            label: badge.label || '',
            labelColor: badge.labelColor || '',
            style: badge.style || 'flat-square',
          } as Format;
          return makeBadge(format);
```

https://github.com/kaos/backstage/blob/1b4730f79474f1216c32c589999f1f7ffcd45ef1/plugins/badges-backend/src/lib/BadgeBuilder/DefaultBadgeBuilder.ts#L56-L63

**Comment by paulmelnikow** [comment]
I think it will work fine if you pass `undefined` instead of `null`.

**Comment by kaos** [comment]
Well, no, since the test explicitly tests for `...` gngnghh. Sorry, I got bitten by javascripts ambiguities.. that `undefined != null === false`.

My apologies.
