### ISSUE TITLE
Codeship status badge shows inaccessible

### ISSUE THREAD

**Issue by moroshko** [badges/shields#625]
This used to work:

`https://img.shields.io/codeship/41810250-aa07-0132-fbf4-4e62e8945e03/master.svg`

But, now it shows:

![](https://img.shields.io/codeship/41810250-aa07-0132-fbf4-4e62e8945e03/master.svg)

Why?

**Comment by AdrieanKhisbe** [comment]
@moroshko 
Vendor is unresponsive, If you try to access the url, you'll get the badge. `Vendor: Unresponsive`
Since github timeout before you have a `Not Found`

**Comment by espadrine** [comment]
It seems to work currently. Can we close this issue?
