### ISSUE TITLE
Different user agent

### ISSUE THREAD

**Issue by muety** [badges/shields#6251]
This is not particularly a bug, but might also not necessarily be intended "behavior". The `User-Agent` header in requests performed by Shields against custom JSON endpoints used to start with `Shields.io/`, followed by a version number, if I recall correctly. After #6160, the user agent now reads `got (https://github.com/sindresorhus/got)` instead. Is this intended? 

I came across this issue as [wakapi](https://github.com/muety/wakapi), which I am the maintainer of, used to check that header in incoming requests to its Shields.io-compatible for a certain pattern to conditionally let the request succeed or not. Although that check didn't give a lot of benefit anyway, it makes a good example of how the change may cause side effects on other projects.

Just wanted to bring this up in case it was a mistake :)

**Comment by calebcartwright** [comment]
Thank you for letting us know! I imagine this will come as no surprise given the value of that header, but we're in the process of switching over to `got` and I think this just slipped through the cracks.

cc @badges/shields-ops
