### ISSUE TITLE
Liberapay Badge shows "invalid response data"

### ISSUE THREAD

**Issue by fschrempf** [badges/shields#6254]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

My Liberapay badges don't work and just show "invalid response data", though the data is accessible at https://liberapay.com/frsc/public.json. Badges of other users seem to work fine.

:link: **Link to the badge**

![Badge](https://img.shields.io/liberapay/gives/frsc.svg?logo=liberapay)

https://img.shields.io/liberapay/gives/frsc.svg?logo=liberapay

**Comment by calebcartwright** [comment]
Thanks for reaching out. Our schema validation (used to process the response) is expecting the `goal` key to always exist, even if it has a null value. For some reason, the response for your entity does not have the `goal` key at all, which is causing the response validation to fail.

If the absence of the `goal` key is an expected/valid scenario, then we'd need to update our schema accordingly

https://github.com/badges/shields/blob/2359eb278beb4612ea8e579b062648463dc79813/services/liberapay/liberapay-base.js#L9-L31

**Comment by chris48s** [comment]
Looking at the liberapay source/tests, it is expected that in some situations `public.json` will not include a "goal" key e.g:
https://github.com/liberapay/liberapay.com/blob/ca814ed2478108b119fef4498a8ee521a5553914/tests/py/test_public_json.py#L38-L41

We should split the schema for liberapay so that only the goal badge fails if there's no goal key - badges that don't need it shouldn't fail if it is not there.

**Comment by Changaco** [comment]
I suggest simply removing the `.required()` call in the schema. The goal badge should then [error with the message "no public goals"](https://github.com/badges/shields/blob/fd7eddc7bb406b272b8bbf4155315c5f3b198a03/services/liberapay/liberapay-goal.service.js#L28) when the goal is missing.

**Comment by fschrempf** [comment]
Thanks for fixing, works as expected!
