### ISSUE TITLE
[Request] Bitbucket issue badges

### ISSUE THREAD

**Issue by SamWhited** [badges/shields#626]
I would like to request badges similar to the GitHub issue badges but for Bitbucket.

This can be accomplished quite easily using the v1 API, eg. using something like this:

```
https://bitbucket.org/api/1.0/repositories/{accountname}/{repo_slug}/issues/?limit=0
```

which returns a JSON blob like the following:

```json
{
  "count": 15,
  "filter": {},
  "search": null,
  "issues": []
}
```

Tags, releases, and commits are also GitHub badges that would be nice to have for Bitbucket, but this ticket is for the issues list in particular.

**Comment by espadrine** [comment]
Thank you for your suggestion!

What repository should we provide as an example?

**Comment by SamWhited** [comment]
> What repository should we provide as an example?

I'm not sure; where would this example repo show up? The badges on the site don't appear to actually link to anything in particular.

If you need something, this repo (BitBucket API wrapper) might be a good choice as an example: https://bitbucket.org/atlassian/python-bitbucket

Eg. to get all issues via the API you would get: `https://bitbucket.org/api/1.0/repositories/atlassian/python-bitbucket/issues/?limit=0&status=new&status=open`

(I didn't mention `status=new&status=open` in the original request, but I assume that's what we generally want to list; that'll give the same count the issue tracker on Bitbucket shows by default)

**Comment by espadrine** [comment]
Thanks! It is done: https://img.shields.io/bitbucket/issues-raw/atlassian/python-bitbucket.svg.
