### ISSUE TITLE
Support filtering by prefix in GitHub latest Release and Tag Badges

### ISSUE THREAD

**Issue by xingao267** [badges/shields#6275]
:clipboard: **Description**

Please see context and discussions at https://github.com/badges/shields/discussions/6253

**Comment by DAmNRelentless** [comment]
I'd love to see this as well, my reason is mentioned here #7082

**Comment by mvndaai** [comment]
I want this for having multiple go packages with their own `go.mod` files within the same repo. Go allows versioning the subpackages by tagging like `subfolder/v0.0.1`. I would like to show badges for each subpackage in a table on the readme. That is why I made that PR ^.

The only issue I have in the PR is that the code already limits to getting 100 tags when sorting so if one subpackage is never updated and others have more that 100 releases then the filter might not work.

**Comment by razonyang** [comment]
Hi, is there any updates? Need this for Go modules in same repo.

**Comment by ricardojdsilva87** [comment]
Hello, this feature would be really helpfull.
On the README we have we are checking for releases for an helm chart for example for argoCD.
https://github.com/argoproj/argo-helm/releases
In this case we have several different helm releases for the different argocd components, like events, workflows, etc.
It would be usefull if we can have some kind of regex filter to show for example per date the release for argo-events-* or argo-cd-*.
This way we could monitor different components in the same repo.
Keep up the good work!
Thanks

**Comment by chris48s** [comment]
Hello. We have just shipped a new feature which allows you to pass an arbitrary filter to the github tag and release badges. For example

The `filter` param can be used to apply a filter to the project's tag or release names before selecting the latest from the list. Two constructs are available: `*` is a wildcard matching zero or more characters, and if the pattern starts with a `!`, the whole pattern is negated.

e.g:
https://img.shields.io/github/v/tag/badges/shields
https://img.shields.io/github/v/tag/badges/shields?filter=%21server-%2A

This feature should be powerful and flexible enough to enable this use-case (and a bunch of others).

**Comment by razonyang** [comment]
Hi @chris48s, is there an option to transform the tag name, in some context, the prefix (`modules/socials`) is redundant.

![Image](https://img.shields.io/github/v/tag/hbstack/header?filter=modules/socials%2A)

**Comment by chris48s** [comment]
No the tag badge will always just display the name of the tag.
For releases you can pick either the tag name or the release name.
