### ISSUE TITLE
Github license and issue badges are not working

### ISSUE THREAD

**Issue by caarlos0** [badges/shields#628]
"Vendor unresponsible"

![image](https://cloud.githubusercontent.com/assets/245435/12242032/bbb144f4-b87d-11e5-921b-f2e014974d61.png)

or sometimes just this:

![image](https://cloud.githubusercontent.com/assets/245435/12242049/e3916c92-b87d-11e5-9747-f61d7447a940.png) (repo: https://github.com/getantibody/antibody)

**Comment by hlandau** [comment]
Experiencing this also, for github/release and github/downloads. It takes so long to respond that camo.githubusercontent.com times out, so you don't even see 'vendor unresponsive'. What's going on here?

**Comment by tomschenkjr** [comment]
Also experiencing long latency in loading the embedded shields. Reported in Chicago/opengrid#137 and confirmed for some other repos.

**Comment by sotojuan** [comment]
Yeah none of my badges are loading, and I am just using the Travis one :/

**Comment by Bilge** [comment]
Confirmed, long-standing issue with GitHub badges.

**Comment by zbeekman** [comment]
I too am experiencing this problem. A real show stopper, thinking about removing shields.io badges from project due to this.

**Comment by groggemans** [comment]
+1, Any idea what's going on? or when this will be fixed?

**Comment by lillian-lemmer** [comment]
I find that the license working is a bit of a cointoss...

**Comment by espadrine** [comment]
Yep, the original issue is here: https://github.com/badges/shields/issues/529. I contacted GitHub on the subject. I'll close this issue to keep details on the old one.
