### ISSUE TITLE
Support for donorbox.org

### ISSUE THREAD

**Issue by svoop** [badges/shields#629]
With donorbox.org, it's possible to easily add donations to OS projects, support for it's badges on Shields similar to Gratipay would be great:

https://img.shields.io/gratipay/user/dougwilson.svg

**Comment by svoop** [comment]
Note: I created this issue for beerpay.io first, but then changed to donorbox.org. While beerpay.io is very easy to setup, the fees are higher and only USD are supported (which causes additional conversion fees for non-USD developers). Donorbox is only slightly more clicks to setup.

**Comment by espadrine** [comment]
Thanks for your suggestion! I edited your comment to say donorbox.org.

I don't see any documented API to access their data, however.

**Comment by espadrine** [comment]
Beerpay now has its own issue: https://github.com/badges/shields/issues/659

**Comment by chris48s** [comment]
An API does exist for this https://github.com/donorbox/donorbox-api but requires per-user authentication. This would require a user to expose a sensitive API key allowing access to sensitive info so wouldn't be suitable for shields.io. We'd need an unauthenticated API or 'public info' key for this to be suitable

**Comment by paulmelnikow** [comment]
Closing pending "public info" keys becoming available.
