### ISSUE TITLE
New Badge: Upptime

### ISSUE THREAD

**Issue by benaltair** [badges/shields#6307]
:clipboard: **Description**

[Upptime](https://upptime.js.org/) is a GitHub-powered open-source uptime monitor and status page. It's quite novel, as it runs entirely on Github with actions and pages. It is already set up to provide API endpoints that are compatible with [shields.io](https://shields.io/). It would be great to have it officially implemented on the main website.

:link: **Data**

As [documented](https://upptime.js.org/docs/badges) Upptime already generates API endpoints that look similar to:
```json
{
  "schemaVersion": 1,
  "label": "uptime",
  "message": "100%",
  "color": "brightgreen"
}
```
The current method is to navigate to `https://raw.githubusercontent.com/[USER]/[REPO]/master/api/[SITE]/uptime.json`. For example this URL would work, using their demo:
https://raw.githubusercontent.com/upptime/upptime/master/api/google/uptime.json

Translating into: 
![Uptime](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fupptime%2Fupptime%2Fmaster%2Fapi%2Fgoogle%2Fuptime.json)

Here is the legend for the three fields that need to be filled (from the above template):
| Variable | Description |
| --- | --- |
| USER | The Github user or organization |
| REPO| The Github repo for the Upptime instance |
| SITE | The slug found in your `/api/` folder within the `master` branch of the Upptime repo |

:microphone: **Motivation**

Right now users have to use the endpoint method, prefixing their URLs with `https://img.shields.io/endpoint?url=`. Perhaps the pattern above could be incorporated into a documented [shields.io](https://shields.io/) schema. Most of the work is already done, and if possible incorporating the service directly would increase accessibility for devs just getting started. It can also help cross-pollinate users across the services. For instance, I first heard about shields.io through Upptime documentation not too long ago.

**Comment by PyvesB** [comment]
Hello @benaltair ! 👋🏻 

Thank you for the suggestion. To be able to implement this on the main Shields.io website, we would need a proper JSON API rather than one that follows the endpoint badge structure and imposes its own fields on generated badges. See https://github.com/badges/shields/pull/5701#discussion_r513048352 and surrounding comments for a bit more context and explanations.

Is such an API already available for the Upptime service?

**Comment by benaltair** [comment]
Hi @PyvesB thanks for the reply. From what I understand, the only API that Upptime provides would be the semi-dynamic (updated every 5 minutes by default) endpoints shown here:
[![image](https://user-images.githubusercontent.com/17771229/112197455-57a43a00-8bc9-11eb-804e-d1fcff1575e1.png)](https://github.com/bahaistudies/status/tree/master/api/association-for-baha-i-studies)

Would this need to be a centralized API, rather than using each user's GitHub repo to be included?

I checked out https://shields.io/endpoint and the issue you mentioned. Thanks. I'm still just a little unclear on the conventions within shields.io and what sort of API would be prefered.

**Comment by PyvesB** [comment]
> From what I understand, the only API that Upptime provides would be the semi-dynamic (updated every 5 minutes by default)

If the uptime/status information is pushed to GitHub on a regular basis, that would also do the trick. We have quite a few badges that rely on GitHub files, any implementation that extends `ConditionalGithubAuthV3Service` would be doing this. A nice and simple example is our Lerna badge: https://github.com/badges/shields/blob/master/services/github/github-lerna-json.service.js

**Comment by chris48s** [comment]
Yes. Upptime isn't a service. It is a more like a library. You self-host it in your own github repo. It does the status checks with scheduled github actions and writes status back to the repo. We do have other badges that have a custom route that allows us to fetch some file in a defined format from a known location in a github repo and parse some data out of it, so in some ways it would be reasonable to think of this in the same way.

> imposes its own fields on generated badges

If we wanted to add it but you're worried about "control", you could treat the `message` field as the "API" value. We hard-code the label and implement our own colouring logic, much as we might do with other badges of that type.

All that said, I'm not convinced it is a great idea to add this. The documented solution seems pretty good to me: https://upptime.js.org/docs/badges and is exactly the sort of use-case the endpoint badge is there to enable :tada: I don't think there is any value-add or additonal functionality we would provide on top of what already exists and if the project author can provide a solution that uses our service and we don't have to maintain it.. seems like everything is working how it supposed to :)

**Comment by PyvesB** [comment]
> If we wanted to add it but you're worried about "control", you could treat the `message` field as the "API" value. We hard-code the label and implement our own colouring logic, much as we might do with other badges of that type.

We had pretty much the same discussion for the Localazy service back in October and decided to reject the badge following an ops meeting. Unless something has changed since then, I would rather we be consistent and follow the same stance here.

**Comment by calebcartwright** [comment]
Generally agreed with the overall theme that this may not really make sense to add, and that the semi-recent Localazy case is good precedent.

I think a reasonable rule of thumb is that our native badges should avoid working with a specialized file/API that's specifically designed to _set_ our badge attributes. As noted already, we provide the Endpoint badge explicitly for _that_ purpose, and I think the delineation makes sense to maintain.

What I would look for in order to add a native/direct Upptime badge would be a non-badge specific API (or file) that a user of the Upptime service would consume for non-badge driven programmatic purposes, and which included the raw data for average response time, uptime, etc.

Yes, we could use the existing file and strip off the `%`, convert to a number, apply _our_ colors, etc. but it just feels like doing so would be trying to force an Endpoint badge into a native badge which I'm not terribly keen on.

**Comment by benaltair** [comment]
This is very helpful everyone, thanks. If the team wants to close the issue, feel free. The reasons stated above make a lot of sense. 

Perhaps another way of approaching this is actually to submit a PR bolstering the Upptime doc page so it has a bit more context and is more specific. I found it a little difficult to follow with just an example.

**Comment by PyvesB** [comment]
> Perhaps another way of approaching this is actually to submit a PR bolstering the Upptime doc page so it has a bit more context and is more specific. I found it a little difficult to follow with just an example.

I think that's a good idea! 👍🏻 

Will close this for now - though if ever Upptime provided a non-badge specific API, we would be happy to rediscuss native integration in Shields.io.
