### ISSUE TITLE
Add Minecraft server stats (online players, server online status)

### ISSUE THREAD

**Issue by YHDiamond** [badges/shields#6308]
:clipboard: **Description**

A badge to show the amount of players on a Minecraft server at one time and other stats about a server

- This is a service for Minecraft servers
- Can show online server status (https://img.shields.io/badge/Minecraft%20server-online-brightgreen or https://img.shields.io/badge/Minecraft%20server-offline-red)
- Can show number of online players (https://img.shields.io/badge/Online%20Players-126-blue)
- Can show server software (https://img.shields.io/badge/Server%20Software-Paper-blue)
- Can show server version (https://img.shields.io/badge/Server%20Version-1.16.5-green)
- Online players over player slots (https://img.shields.io/badge/Online%20players-12%2F20-yellow)

:link: **Data**

https://api.mcsrvstat.us/ this is an API that would probably work for most (if not all) of these things.

:microphone: **Motivation**

This would be most useful for Minecraft projects with a server or test server (GeyserMC and Mineweb are just 2 that I can name off the top of my head, I am sure there are more).

**Comment by PyvesB** [comment]
Hello @YHDiamond ! 👋🏻 

> This would be most useful for Minecraft projects with a server or test server (GeyserMC and Mineweb are just 2 that I can name off the top of my head, I am sure there are more).

Being somewhat involved in the Minecraft community myself, I can also confirm that some projects do have test servers as you've described.

However, going back to our [contributing guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md):

> Shields.io hosts integrations for services which are primarily used by developers or which are widely used by developers.

I feel that saying that a Minecraft server is a service primarily/widely used by developers is somewhat stretching things. I'm not against this badge per say, but I think it would be useful for other maintainers to share their views as well. 😉

**Comment by calebcartwright** [comment]
> I feel that saying that a Minecraft server is a service primarily/widely used by developers is somewhat stretching things. I'm not against this badge per say, but I think it would be useful for other maintainers to share their views as well.

Yeah I had the same reaction. I think this would be best suited to the endpoint badge.

**Comment by PyvesB** [comment]
Going to close this for now. We can always reopen if a use case that truly fits with the core Shields.io mission comes to light in the future. For reference, documentation about the endpoint badge mentioned by @calebcartwright can be found here: https://shields.io/endpoint
