### ISSUE TITLE
Only load website images when they are in the viewport

### ISSUE THREAD

**Issue by espadrine** [badges/shields#633]
Currently, when loading the website, it downloads a very large amount of images.

We should only load the images that are currently in the viewport.

This requires to change all `<img src=…>` to `<img data-src=…>` and some JS code that identifies viewport changes (say, upon scrolling but only every 300ms) and changes the images' `data-src` attribute into a `src` attribute.

**Comment by matteodelabre** [comment]
Using `data-src` might not be a good idea if people visit the page with JS disabled.
I think hiding images with `display: none` (before page load) with JS would be a better strategy.
This could cause some layout glitches though, so you might want to wrap badges in pre-sized `<div>`s.

**Comment by espadrine** [comment]
Undisplayed images are still shown. It is a common technique to preload images. As soon as the browser sees `<img src=…>`, it is already too late. The only thing that works is wrapping all images in `<noscript>`, but my eyes haven't witnessed such a terrifying sight since *Ringu*.

A solution I am exploring is using either traditional browser caching, or service workers.

**Comment by espadrine** [comment]
I now use HTTP caching for badges on the front page. When going to shields.io, the badges hit the browser cache. However, when reloading the page, they are reloaded.

**Comment by darkmorpher** [comment]
Status request @espadrine

> When going to shields.io, the badges hit the browser cache. However, when reloading the page, they are reloaded.

I see significant memory usage in browsers, each time shields.io page is visited.

**Comment by paulmelnikow** [comment]
Since we have separate pages per category, this isn’t really a problem anymore.
