### ISSUE TITLE
Netlify badge down

### ISSUE THREAD

**Issue by adamalston** [badges/shields#6334]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The Netlify badge appears to be down.

:link: **Link to the badge**

![Netlify Status](https://img.shields.io/netlify/332bbd91-59b7-4091-8781-6f41330399b4)
```markdown
![Netlify Status](https://img.shields.io/netlify/332bbd91-59b7-4091-8781-6f41330399b4)
```

---

For comparison, here is the badge that Netlify provides.

![Netlify Status](https://api.netlify.com/api/v1/badges/332bbd91-59b7-4091-8781-6f41330399b4/deploy-status)
```markdown
![Netlify Status](https://api.netlify.com/api/v1/badges/332bbd91-59b7-4091-8781-6f41330399b4/deploy-status)
```

Notice that both project id's are the same.

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
Service tests for netlify are also failing.
The netlify badge is based on scraping netlify's badges so I guess their format has changed a bit and we need to update the code which extracts the status value from their SVG.

**Comment by calebcartwright** [comment]
Please do @tarun7singh!

**Comment by tarun7singh** [comment]
I mistakenly added the fix to this issue in my previous pull request. 
[PR](https://github.com/badges/shields/pull/6333)
What should do to remove it from there and add to a new PR?

**Comment by calebcartwright** [comment]
> What should do to remove it from there and add to a new PR, or should i leave it be?

Yes, please remove the netlify commit from the youtube PR and open a separate PR for the netlify changes to keep things separate.

**Comment by PyvesB** [comment]
@tarun7singh's fix has been successfully deployed to production! 🍾

**Comment by tarun7singh** [comment]
Thanks @PyvesB
