### ISSUE TITLE
Slow load on specific packages

### ISSUE THREAD

**Issue by IonicaBizau** [badges/shields#634]
![image](https://cloud.githubusercontent.com/assets/2864371/12388149/cad82a40-bdd9-11e5-9e9b-b49db16aafc8.png)

The code looks like this:

``` md
# parse-url [![Travis](https://img.shields.io/travis/IonicaBizau/parse-url.svg)](https://travis-ci.org/IonicaBizau/parse-url/) [![Version](https://img.shields.io/npm/v/parse-url.svg)](https://www.npmjs.com/package/parse-url) [![Downloads](https://img.shields.io/npm/dt/parse-url.svg)](https://www.npmjs.com/package/parse-url) [![Get help on Codementor](https://cdn.codementor.io/badges/get_help_github.svg)](https://www.codementor.io/johnnyb?utm_source=github&utm_medium=button&utm_term=johnnyb&utm_campaign=github)
```

And when it's rendered looks like this:
# parse-url [![Travis](https://img.shields.io/travis/IonicaBizau/parse-url.svg)](https://travis-ci.org/IonicaBizau/parse-url/) [![Version](https://img.shields.io/npm/v/parse-url.svg)](https://www.npmjs.com/package/parse-url) [![Downloads](https://img.shields.io/npm/dt/parse-url.svg)](https://www.npmjs.com/package/parse-url) [![Get help on Codementor](https://cdn.codementor.io/badges/get_help_github.svg)](https://www.codementor.io/johnnyb?utm_source=github&utm_medium=button&utm_term=johnnyb&utm_campaign=github)

Why are these soo slow?

**Comment by IonicaBizau** [comment]
This happens especially for *new* packages right after `npm publish`.

**Comment by gabipetrovay** [comment]
:+1:

**Comment by espadrine** [comment]
Travis and GitHub rate-limits us.
