### ISSUE TITLE
npm downloads for new packages

### ISSUE THREAD

**Issue by IonicaBizau** [badges/shields#635]
![image](https://cloud.githubusercontent.com/assets/2864371/12398453/7c6f852c-be1c-11e5-98bc-f51b990e2e5e.png)

![image](https://cloud.githubusercontent.com/assets/2864371/12398460/83900d68-be1c-11e5-85ab-0418b91f9ad9.png)

Instead of showing **invalid** it should show `0` or something.

**Comment by lcristianiim** [comment]
:+1:

**Comment by IonicaBizau** [comment]
@espadrine Thanks for fixing! :sparkles:

**Comment by espadrine** [comment]
Thank you for reporting! Sorry it took time.
