### ISSUE TITLE
add chrome extension version badge

### ISSUE THREAD

**Issue by nschloe** [badges/shields#636]
I'd be nice to be able to associate a source code repository with a [Chrome Extension](https://chrome.google.com/webstore/category/extensions).

**Comment by AdrieanKhisbe** [comment]
@nschloe, can you elaborate more on that please. Giving an example :)

**Comment by nschloe** [comment]
For example, the [PaperHive extension](https://chrome.google.com/webstore/detail/paperhive/fihafdlllifbanclcjljledeifcdjbok) exists as version 0.2.0 in the Chrome Web Store. It'd be great if this could be reflected as a badge, much like PyPi & friends.

There is the [Chrome Web Store API](https://developer.chrome.com/webstore/webstore_api/items), but right now I cannot find a non-authenticated endpoint for actually retrieving this information.

**Comment by AdrieanKhisbe** [comment]
Okey, now I see

**Comment by bfred-it** [comment]
This module can be used to retrieve the the information, it doesn't need any authentication
https://github.com/pandawing/node-chrome-web-store-item-property

**Comment by espadrine** [comment]
Prior art: https://github.com/badges/shields/pull/505

**Comment by bfred-it** [comment]
Owww why though? If something changes it can always be fixed. Why have nothing instead of something?

Ping @sanemat

**Comment by espadrine** [comment]
The underlying code will soon be 1 year-old. If it still works, I would absolutely be open to merging the PR. The issue I raised is mostly for pages that change more often than every 6 months.

**Comment by sanemat** [comment]
hi, I re-send #687 :smile_cat:

**Comment by espadrine** [comment]
Thanks to all of you!
