### ISSUE TITLE
Replace 4183C4 with blue?

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6363]
Four of our GitHub badges use the `4183C4` colour when used in their non social form:
* ![](https://img.shields.io/github/followers/espadrine)
* ![](https://img.shields.io/github/forks/badges/shields)
* ![](https://img.shields.io/github/sponsors/Homebrew)
* ![](https://img.shields.io/github/watchers/badges/shields)

This is not quite consistent with the usual informational `blue` that is used throughout our services, in particular for other similar GitHub badges, e.g. stars:
![](https://img.shields.io/github/stars/badges)

I could find references to `4183C4` in the code from 2014, my guess is that it was just picked as a colour that looked nice back then and at some point we deviated with a slightly different tone of blue.

Are folks happy with me to make the change, or can you think of any strong reason why we should leave things as they are?

**Comment by chris48s** [comment]
I reckon just change it and see if anyone notices..

**Comment by PyvesB** [comment]
Change deployed to production. Do let us know if ever this change has impacted you in a negative way.
