### ISSUE TITLE
Support David's path query parameter

### ISSUE THREAD

**Issue by Jerska** [badges/shields#637]
Hi,

David [now supports](http://davidiswatching.tumblr.com/post/132882415144/non-root-packagejson) `package.json` files which aren't in the root of the GitHub repository through a `path` query parameter.

That's how

``` md
![devDependency Status](https://david-dm.org/algolia/algoliasearch-zendesk/dev-status.svg?path=app)
```

renders like this: [![devDependency Status](https://david-dm.org/algolia/algoliasearch-zendesk/dev-status.svg?path=app)](https://david-dm.org/algolia/algoliasearch-zendesk?path=app#info=devDependencies) , based on the `package.json` in the `app/` directory of this project instead of the root. I'd like to see shield.io also support it.

I'm not really sure of how it could be handled at the URL level, maybe just passing along the query parameter? Or maybe just adding it after the repo name?

``` txt
https://img.shields.io/david/<type>/<repo owner>/<repo name><path to the package.json>.svg
https://img.shields.io/david/dev/algolia/algoliasearch-zendesk/app.svg
```

Would that make sense for you?

**Comment by espadrine** [comment]
Does David DM have the guarantee that there is always a repo owner *and* a repo name?

**Comment by danez** [comment]
According to the mainpage of david-dm there is always a owner (user) and name (repo).

https://david-dm.org/

![bildschirmfoto 2016-07-25 um 15 57 06](https://cloud.githubusercontent.com/assets/231804/17103834/9599e8c8-5280-11e6-90f0-cac73cbc830c.png)

**Comment by deepsweet** [comment]
They have a slightly different green color than on our badges, I just can't live with this :) Sorry for asking, but is there any plans to implement this?

**Comment by paulmelnikow** [comment]
Would you like to make a pull request?
