### ISSUE TITLE
Homebrew version number

### ISSUE THREAD

**Issue by zbeekman** [badges/shields#638]
It would be great if shields.io could provide badges for indicating the version of a package in Homebrew. One possible place that data could be scraped from, or to work with to expose formula versions through an API is braumeister.org

https://github.com/koraktor/braumeister.org/issues/35

**Comment by koraktor** [comment]
braumeister.org now supports the following minimal API:

http://braumeister.org/formula/git/version
http://braumeister.org/repos/Homebrew/homebrew-versions/formula/tomcat7/version

**Comment by zbeekman** [comment]
This has been implemented by @gep13 🙇 🎉
