### ISSUE TITLE
Parameter for GitHub Semantic Version prefix e.g. *-rc, *-rtw etc

### ISSUE THREAD

**Issue by unclehowell** [badges/shields#6384]
My organisations' releases on github are set to contain various semantic version prefixes e.g. v0.0.9-rc.01 , v0.0.9-rtw.01 etc
Is there a parameter to make the badge displays (and link to) the corresponding release, but with the corresponding prefix ??
Otherwise the html badge takes the website visitor to the corresponding release, but not the corresponding prefix.
Which means the website visitor will be left to guess which one corresponds to the creative content they were just looking at e.g. website, software GUI etc

**Comment by chris48s** [comment]
I don't think I understand the question.
Can you explain what badge this relates to and give us an example of a badge URL showing the problem you are trying to explain.
Cheers

**Comment by PyvesB** [comment]
I'm going to close this issue, feel free to reopen if and when you're able to provide clarification. 😉
