### ISSUE TITLE
most badges timeout on shields.io

### ISSUE THREAD

**Issue by thisconnect** [badges/shields#640]
Is it just me? Do the badges work on http://shields.io/ for somebody?

![screen shot 2016-01-22 at 4 58 27 pm](https://cloud.githubusercontent.com/assets/546900/12515597/6e0ca8f6-c129-11e5-8f82-ad0e67b8dbd6.png)

**Comment by pmonks** [comment]
Very sporadic for me - they don't work more often than they do.

**Comment by pmonks** [comment]
See also issue #628.

**Comment by zbeekman** [comment]
I too am experiencing this problem. I am thinking of removing shields.io badges from my projects due to this ongoing issue.

**Comment by Foorack** [comment]
I'm also experiencing this issue as of 30 Jan. It worked an hour ago.

**Comment by zbeekman** [comment]
We have moved all of our badges to other service providers, and downloaded and saved static badges as local assets due to this unreliable performance.

**Comment by aantron** [comment]
:+1:

Second time last two weeks. Considering doing what @zbeekman did, annoying as it is.

![screen shot 2016-01-30 at 12 45 26](https://cloud.githubusercontent.com/assets/12073668/12697717/8737762c-c74f-11e5-8929-4778493b1d18.png)

**Comment by espadrine** [comment]
Thanks for reporting. Since it was at a time before we split the load between two servers, I believe this issue is resolved.

**Comment by FezVrasta** [comment]
I'm still experiencing it often @espadrine

**Comment by espadrine** [comment]
@FezVrasta We've had a bad player today ☹.

![image](https://cloud.githubusercontent.com/assets/100689/22027467/486b73ee-dcd4-11e6-9319-a3cd9e6d9b7c.png)

Currently, I don't enforce rate limits. Maybe I should do that?

**Comment by FezVrasta** [comment]
Not sure it's the problem, I'm experiencing these problems daily

**Comment by espadrine** [comment]
There's two other items that are painful for the RAM, which gets the server swapped, which probably doesn't help:

- bower [downloads](https://github.com/badges/shields/blob/21ae49ad852aca7df1204a2de9efdf2a0c2a1cef/server.js#L4189) a lot of data over git. It can probably be implemented using https://bower.io/docs/api/ instead.
- For PNG images, I spawn headless google chrome instances, which take about 1.3 GB of virtual memory. It is not too common, but usually when it happens, someone was loading a page which has several of them on it. Using inkscape instead would probably be less expensive (and also potentially fails at providing a number of features, but PNG is for compatibility anyway).

**Comment by FezVrasta** [comment]
Why do you need Chrome or Inkscape for editing PNGs sever side? Isn't imagemagick enough?

**Comment by FezVrasta** [comment]
https://github.com/badges/shields/pull/860
