### ISSUE TITLE
Separate search and suggest features on website

### ISSUE THREAD

**Issue by ChristopherKing42** [badges/shields#642]
There should be a box at the top where you can enter a repository, and then shield.io will format the urls to reflect that repository, so it doesn't need to be done manually.

**Comment by zbeekman** [comment]
This exists already

**Comment by TheKing42** [comment]
Oh, sorry. (Maybe make it more apparent?)

**Comment by espadrine** [comment]
Sorry that it was not more apparent. Do you have an idea of something that may help?

**Comment by ChristopherKing42** [comment]
@espadrine Maybe make the search and repo url boxes separate? (It might just be that I'm dumb though.)

**Comment by paulmelnikow** [comment]
Let's consider this as part of #1899.
