### ISSUE TITLE
Badge request for OpenMined and PySyft

### ISSUE THREAD

**Issue by arghyadeep99** [badges/shields#6425]
:clipboard: OpenMined is a relatively famous community now that is working on federated learning. We need a logo for the same now. PySyft is one of their open-source products that is aimed at facilitating secure and private AI. 

A clear and concise description of the new badge.

- Which service is this badge for e.g: OpenMined
- What sort of information should this badge show?
  Provide an example in plain text e.g: OpenMined/PySyft

:link: **Data**

Where can we get the data from?

- Is there a public API?
    Yes. [PySyft](https://raw.githubusercontent.com/OpenMined/PySyft/master/docs/img/logo_big.png), [OpenMined](https://avatars.githubusercontent.com/u/30185530?s=200&v=4)
- Does the API requires an API key? No

:microphone: **Motivation**

OpenMined is a relatively famous community now that is working on federated learning. We need a logo for the same now. PySyft is one of their open-source products that is aimed at facilitating secure and private AI.

**Comment by PyvesB** [comment]
Hello @arghyadeep99 ! 👋🏻 

Thanks for suggesting this. Our preferred way of enabling a new logo on Shields.io is to do it via SimpleIcons. See our [documentation](https://github.com/badges/shields/blob/master/doc/logos.md) for a bit more information. 😉

**Comment by arghyadeep99** [comment]
@PyvesB aah yes, my bad, I forgot. The last request I made was back in 2019 for PyTorch, which was accepted, and it's been a while since then. Totally forgot the procedure. Will make the request at the appropriate place. Thanks a lot!

**Comment by PyvesB** [comment]
No worries! I see you've raised https://github.com/simple-icons/simple-icons/issues/5535 and https://github.com/simple-icons/simple-icons/issues/5536, will go ahead and close this issue.
