### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by tusharmath** [badges/shields#644]
Wouldn't it be great if we could just update our markdown files using a command line interface? Integrate multiple Badges in one go using an interactive console?

**Comment by IonicaBizau** [comment]
@tusharmath I'm using [`blah`](https://github.com/IonicaBizau/blah) for that and there you can configure your `ejs` template. Mine looks like [this](https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs).

If I understood correctly, you want a tool that will automatically generate all these badges and their links based on files you have in the repo (e.g. `package.json`, `.travis.yml` etc)?

**Comment by espadrine** [comment]
> Wouldn't it be great if we could just update our markdown files using a command line interface?

Absolutely! `npm install -g gh-badges` and `badge build passed :green .png > mybadge.png` for instance.

It is documented in https://github.com/badges/shields/blob/master/INSTALL.md#use-the-cli. Is there a way to make it clearer?

**Comment by tusharmath** [comment]
@espadrine I tried to get this command to work eventually but its not really what I am asking here, though @IonicaBizau solution would work perfectly if I have to create a new README. What I want to achieve is actually update an already existing readme file with multiple badges.

**Comment by espadrine** [comment]
Interesting. This may be slightly out of scope for shields, but blah sounds like it fits!
