### ISSUE TITLE
Pull Request status checks badge shows different number of checks

### ISSUE THREAD

**Issue by niveathika** [badges/shields#6450]
Are you experiencing an issue with ,

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Pull request checks status badge shows a different number of checks. The following PR has 7 checks, badge only shows 1

:link: **https://img.shields.io/github/status/contexts/pulls/ballerina-platform/module-ballerinax-choreo/70**

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
Hi. This is a bit of a confusing feature of github - there are two different things reported in the same place on PRs: checks and statuses. See the docs at https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github for more info about this

In this case, the number on this badge is based on calling
https://api.github.com/repos/ballerina-platform/module-ballerinax-choreo/commits/7591240de7e9bce2abd24e98a1b191a93a6f1c04/status
which reports one status so it is doing what it is supposed to, but that isn't what you wanted.

There is also an open feature request at https://github.com/badges/shields/issues/4364 to add a corresponding badge for checks, but we don't currently have a badge for it.

**Comment by niveathika** [comment]
@chirs48s Thank you for the clarification, yes we need the checks badge. Will close this issue and follow the feature request.
