### ISSUE TITLE
Add typescript-eslint scoped packages to useless check

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#6467]
We currently utilize GitHub Actions to get some bot-driven help on processing dependency PRs. This includes a check that inspects the Gatsby related dependencies because those packages are maintained in a monorepo and often times the "bump" of a specific gatsby package hasn't actually just been changed; it just had another version published due to the release management practices of that monorepo.

That check in our Actions processing can be found at:
https://github.com/badges/shields/blob/2aa253695de8348118e627858b0935ec15374ca9/.github/actions/approve-bot/helpers.js#L36

It seems like the `@typescript-eslint` scoped packages have moved to a similar monorepo publishing approach, so we're now getting some useless bumps of those packages as well. It'd be good to update our processing to inspect and autoclose those as well

refs #6462 and #6453

**Comment by profgrammer** [comment]
Upon inspection of the `isPointlessGatsbyBump` function and #6462 and #6463, I think if we just check whether the first line of the PR body includes the link `https://github.com/typescript-eslint/typescript-eslint/` through regex matching, along with the other checks in the helper function, it would be sufficient to take the decision to autoclose the PR. I have a few questions regarding this approach:
- I think it would be good to have an array of links that we should check for in the first line to make it easy to add more such cases in the future if required. Thoughts?
- Is there any way to test the GitHub actions locally?

Also, it's interesting to see dependabot PRs using shields 😁

**Comment by calebcartwright** [comment]
>  I think if we just check whether the first line of the PR body includes the link https://github.com/typescript-eslint/typescript-eslint/ through regex matching, along with the other checks in the helper function, it would be sufficient to take the decision to autoclose the PR

That sounds reasonable to me 

> I think it would be good to have an array of links that we should check for in the first line to make it easy to add more such cases in the future if required. Thoughts?

Agreed :+1: 

>  Is there any way to test the GitHub actions locally?

I'm not sure what if any local testing paradigms are viable with Actions, though lots of what we have for this custom action is just standard functions that could be unit tested like other parts of the codebase

**Comment by PyvesB** [comment]
Thanks for sorting this out @profgrammer!
