### ISSUE TITLE
Support download count of private npm packages

### ISSUE THREAD

**Issue by rafaelrinaldi** [badges/shields#647]
Currently, is there a way to add a badge to display the downloads count of a private npm package published as public? It's a common approach to make use of the namespace and avoid conflicts with canonical packages.

Examples:

*[`@cycle/core`](https://www.npmjs.com/package/@cycle/core)
*[`@rafaelrinaldi/hn-cli`](https://www.npmjs.com/package/@rafaelrinaldi/hn-cli)

I've tried the obvious of adding the full URL and the escaped version of the URL but it doesn't seem to work.
Is this currently supported? If not, is there any interest of supporting it at all?

Thanks.

**Comment by espadrine** [comment]
Thanks for the suggestion! As you may know, it is implemented now.

**Comment by espadrine** [comment]
Thanks for the suggestion! As you may know, it is implemented now.

**Comment by rafaelrinaldi** [comment]
@espadrine Hey thanks for the answer! Can you help me understand how the URL should look like? I tried a few combinations without success. For example, how do I fetch downloads for the [`@cycle/core`](https://www.npmjs.com/package/@cycle/core) package?

**Comment by espadrine** [comment]
On principle, it should be https://img.shields.io/npm/dt/@cycle/core.svg. However, downloads are unsupported by npm for private packages, it seems: https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/%40cycle%2Fcore. You may notice that there is no download information under Stats on [@cycle/core](https://www.npmjs.com/package/@cycle/core). You may contact npm to ask why that is.

That said, it is implemented on our side; as soon as they make it available, the badge should start working.

**Comment by rafaelrinaldi** [comment]
@espadrine Gotcha. I have filled a feature request on npm's issue tracker and will let others know on this issue when/if this gets implemented.

Thanks!

**Comment by yvele** [comment]
@rafaelrinaldi can you please copy/paste the npm issue url here? I would like to subscribe to it
