### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by talentlessguy** [badges/shields#6473]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

website is down

![image](https://user-images.githubusercontent.com/35937217/117832270-0423a380-b27e-11eb-9c44-4d85959495f5.png)

:link: ![](https://img.shields.io/github/workflow/status/talentlessguy/tinyws/CI?style=flat-square)

:bulb: **Possible Solution**

restart heroku

**Comment by GrahamSH-LLK** [comment]
Can repro. It's also down for me and is probably breaking millions of readmes.

**Comment by talentlessguy** [comment]
yay thank u!

**Comment by Pzoom522** [comment]
Static ones are back; dynamic ones (e.g., the "github stars") are still unavailable on my site.

**Comment by GrowtopiaJaw** [comment]
> Static ones are back; dynamic ones (e.g., the "github stars") are still unavailable on my site.

Ah yes, the same thing happens on my side

**Comment by talentlessguy** [comment]
:thinking: 

https://img.shields.io/github/workflow/status/talentlessguy/tinyws/CI?style=flat-square

![image](https://user-images.githubusercontent.com/35937217/117834224-a7c18380-b27f-11eb-87b2-695cb42db114.png)
