### ISSUE TITLE
Can't load ONNX icon

### ISSUE THREAD

**Issue by lukesalamone** [badges/shields#6477]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Cannot load ONNX icon even though it is on simpleicons.org

:link: **Link to the badge**
https://img.shields.io/badge/onnx-005CED?style=for-the-badge&logo=onnx&logoColor=white

https://simpleicons.org/?q=onnx

:bulb: **Possible Solution**

The icon is in the ONNX repo: https://github.com/simple-icons/simple-icons/blob/develop/icons/onnx.svg

It is also on simpleicons.org: https://simpleicons.org/?q=onnx

Why can't I load it in a shield? https://img.shields.io/badge/onnx-005CED?style=for-the-badge&logo=onnx&logoColor=white
 isn't working.

**Comment by PyvesB** [comment]
Hello @lukesalamone ! 👋🏻 

I recommend checking out [this discussion](https://github.com/badges/shields/discussions/5369), it will most likely answer your question. 😉

**Comment by lukesalamone** [comment]
@PyvesB thanks
