### ISSUE TITLE
Browser version Badges

### ISSUE THREAD

**Issue by Dangoo** [badges/shields#650]
How about adding badges for browser versions, based on the API of [browserslist](https://github.com/ai/browserslist)?

``` bash
# /browser/<browserName>/<query>.format

# Latest version of chrome ('last 1 chrome version')
https://img.shields.io/browser/chrome/last%201%20chrome%20version.svg    # [ chrome | 48 ]

# Simple alias for 'last 1 chrome version'
https://img.shields.io/browser/chrome/latest.svg    # [ chrome | 48 ]

# Next-to-last version of chrome ('last 2 chrome version, not last 1 chrome version')
https://img.shields.io/browser/chrome/last%202%20chrome%20versions,not%20last%201%chrome%version.svg    # [ chrome | 47 ]

# N-to-last version of chrome ('last <n> chrome versions, not last <n - 1> chrome versions')
https://img.shields.io/browser/chrome/last%20%3Cn%3E%20chrome%20versions%2C%20not%20last%20%3Cn%20-%201%3E%20chrome%20versions.svg    # [ chrome | N ]
```

The url encoding looks a little bit scary, but it would give you direct access to the browserslist API.
Alternatively one could do a mapping for common usecases such as:

``` json
{
    "chrome": {
        "latest": "last 1 chrome version",
        "latest-1": "last 2 chrome versions, not last 1 version",
        "latest-n": "last <n> chrome versions, not last <n - 1> versions"
    }
}
```

For a little bit optical sugar one could add a browser icon for each vendor (e.g. from [browser-logos](https://github.com/alrra/browser-logos))…

**Update**
Or maybe the [IcoMoon Free Icons](https://github.com/Keyamoon/IcoMoon-Free) (of course the SVG version)
![Firefox](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/475-firefox.png)
![Chrome](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/474-chrome.png)
![IE](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/476-IE.png)
![Edge](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/477-edge.png)
![Safari](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/478-safari.png)
![Opera](https://raw.githubusercontent.com/Keyamoon/IcoMoon-Free/master/PNG/48px/479-opera.png)

What do you think?

**Comment by espadrine** [comment]
Thanks for the suggestion! Could you give me an idea, with a `/badge/` URL, of how a badge would look like?

**Comment by Dangoo** [comment]
I'd keep it simple and use the existing structure of the gitter badge: ![gitter badge](https://img.shields.io/gitter/room/nwjs/nw.js.svg)

So a browser badge for the search query…:
```
# Latest version of chrome ('last 1 chrome version')
https://img.shields.io/browser/chrome/last%201%20chrome%20version.svg    # [ chrome | 50 ]
```
…could look like this:
![chrome50](https://cloud.githubusercontent.com/assets/1252204/14087926/bff8b5a6-f52c-11e5-89a7-f1bd2d7b036a.png)


PS: Sorry for the small image, here is the base64 string for the svg version:

```
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5NiIgaGVpZ2h0PSIyMCIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxsaW5lYXJHcmFkaWVudCBpZD0iYiIgeDI9IjAiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiNiYmIiIHN0b3Atb3BhY2l0eT0iLjEiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3Atb3BhY2l0eT0iLjEiLz48L2xpbmVhckdyYWRpZW50PjxtYXNrIGlkPSJhIj48cmVjdCB3aWR0aD0iOTYiIGhlaWdodD0iMjAiIGZpbGw9IiNmZmYiIHJ4PSIzIi8+PC9tYXNrPjxnIG1hc2s9InVybCgjYSkiPjxwYXRoIGZpbGw9IiM1NTUiIGQ9Ik0wIDBoNzJ2MjBIMHoiLz48cGF0aCBmaWxsPSIjNGMxIiBkPSJNNzIgMGg1N3YyMEg3MnoiLz48cGF0aCBmaWxsPSJ1cmwoI2IpIiBkPSJNMCAwaDk2djIwSDB6Ii8+PC9nPjxnIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJEZWphVnUgU2FucyxWZXJkYW5hLEdlbmV2YSxzYW5zLXNlcmlmIiBmb250LXNpemU9IjExIj48aW1hZ2Ugd2lkdGg9IjE0IiBoZWlnaHQ9IjE0IiB4PSI1IiB5PSIzIiB4bGluazpocmVmPSJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBEOTRiV3dnZG1WeWMybHZiajBpTVM0d0lpQmxibU52WkdsdVp6MGlkWFJtTFRnaVB6NDhJVVJQUTFSWlVFVWdjM1puSUZCVlFreEpReUFpTFM4dlZ6TkRMeTlFVkVRZ1UxWkhJREV1TVM4dlJVNGlJQ0pvZEhSd09pOHZkM2QzTG5jekxtOXlaeTlIY21Gd2FHbGpjeTlUVmtjdk1TNHhMMFJVUkM5emRtY3hNUzVrZEdRaVBqeHpkbWNnZG1WeWMybHZiajBpTVM0eElpQjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIaHRiRzV6T25oc2FXNXJQU0pvZEhSd09pOHZkM2QzTG5jekxtOXlaeTh4T1RrNUwzaHNhVzVySWlCM2FXUjBhRDBpTVRZaUlHaGxhV2RvZEQwaU1UWWlJSFpwWlhkQ2IzZzlJakFnTUNBeE5pQXhOaUkrUEhCaGRHZ2dabWxzYkQwaUkyWm1abVptWmlJZ1pEMGlUVFF1TURNMklEWXVPVGMzYkMweUxqSTVMVE11T1RZMll6RXVORFkyTFRFdU9ETTFJRE11TnpJeUxUTXVNREV5SURZdU1qVTBMVE11TURFeUlESXVPVEk1SURBZ05TNDBPRGtnTVM0MU56UWdOaTQ0T0RNZ015NDVNakpvTFRZdU5USTRZeTB3TGpFeE55MHdMakF4TUMwd0xqSXpOaTB3TGpBeE5pMHdMak0xTmkwd0xqQXhOaTB4TGprd05DQXdMVE11TlRBNUlERXVNekEzTFRNdU9UWTBJRE11TURjeGVrMHhNQzQ0TmpRZ05TNHdOemhvTkM0MU9EVmpNQzR6TlRVZ01DNDVNRFVnTUM0MU5URWdNUzQ0T1RFZ01DNDFOVEVnTWk0NU1qSWdNQ0EwTGpNNE9DMHpMalV6TXlBM0xqazFMVGN1T1RBNUlEY3VPVGs1YkRNdU1qY3lMVFV1TmpZM1l6QXVORFl4TFRBdU5qWXlJREF1TnpNeExURXVORFkySURBdU56TXhMVEl1TXpNeUlEQXRNUzR4TkRNdE1DNDBOekV0TWk0eE56Z3RNUzR5TXkweUxqa3lNbnBOTlM0d09UUWdPR013TFRFdU5qQXpJREV1TXpBMExUSXVPVEEySURJdU9UQTJMVEl1T1RBMmN6SXVPVEEySURFdU16QTBJREl1T1RBMklESXVPVEEyWXpBZ01TNDJNREl0TVM0ek1EUWdNaTQ1TURZdE1pNDVNRFlnTWk0NU1EWnpMVEl1T1RBMkxURXVNekEwTFRJdU9UQTJMVEl1T1RBMmVrMDVMakE1TnlBeE1TNDVORFJzTFRJdU1qa2dNeTQ1TmpkakxUTXVPRFV5TFRBdU5UYzJMVFl1T0RBMkxUTXVPRGs1TFRZdU9EQTJMVGN1T1RFeElEQXRNUzQwTWpVZ01DNHpOek10TWk0M05qTWdNUzR3TWpZdE15NDVNakpzTXk0eU5qWWdOUzQyTlRkak1DNDJOVFFnTVM0ek9USWdNaTR3TnpBZ01pNHpOVGtnTXk0M01EY2dNaTR6TlRrZ01DNHpPQ0F3SURBdU56UTNMVEF1TURVeUlERXVNRGszTFRBdU1UUTVlaUkrUEM5d1lYUm9Qand2YzNablBnPT0iLz48dGV4dCB4PSI0NCIgeT0iMTUiIGZpbGw9IiMwMTAxMDEiIGZpbGwtb3BhY2l0eT0iLjMiPmNocm9tZTwvdGV4dD48dGV4dCB4PSI0NCIgeT0iMTQiPmNocm9tZTwvdGV4dD48dGV4dCB4PSI4NCIgeT0iMTUiIGZpbGw9IiMwMTAxMDEiIGZpbGwtb3BhY2l0eT0iLjMiPjUwPC90ZXh0Pjx0ZXh0IHg9Ijg0IiB5PSIxNCI+NTA8L3RleHQ+PC9nPjwvc3ZnPg==```

**Comment by espadrine** [comment]
It uses caniuse [internally](https://github.com/ai/browserslist/blob/master/index.js#L1). It is [a big JSON blob](https://github.com/Fyrd/caniuse/blob/master/data.json), so it wouldn't be up-to-date.

**Comment by paulmelnikow** [comment]
I'm not sure I understand this idea. When would a project display a badge like this?

**Comment by Dangoo** [comment]
@paulmelnikow just rediscovered this issue, sry for the delayed response…

It could be quite useful to represent browser matrixes in Readme.md files.
For example:

<image src="https://user-images.githubusercontent.com/1252204/76119438-bcf1b100-5fef-11ea-820f-76c3e497c12a.png" width="280" height="133" alt="browsers" />

This is quite similar to the supporting node version:
![](https://img.shields.io/badge/node-12.0.0-brightgreen)

Or in a slightly different approach, reading the `browserlist` field in package.json and querrying for a given name could use the same API as a repos dependencies  🤔:
```
/github/package-json/browserslist/:user/:repo/:browsername

/github/package-json/browserslist/evil-corp/page-for-customer/chrome
```

**Comment by unangst** [comment]
I had to build out something like this to easily spot the version of Chrome (ChromeOS) on our school Chromebooks.  We use this on our student [academic portal](https://woodridge.k12.oh.us/portal).

We want all of our students on a specific version of Chrome OS via the Long-term Support (LTS) channel controlled by the Google Admin Console.  Many K-12 students aren't aware that their devices are on an older Chrome OS version and even though we have them set to 'force' the updates, some machines don't get the updates.  Additionally, new testing applications only support newer versions of ChromeOS.  The code below allows you to quickly display the version of Chrome (first example) or, in our deployment case, the version of Chrome and in RED if it's an older version (second example).  

Hope this helps!

Here's a working example which just displays the version of Chrome in a Shields.io format:
Example: <img id="chrome-badge" src="https://img.shields.io/badge/Chrome-131-brightgreen" alt="Chrome Version Badge">

```
<script>
        // Function to get Chrome version from the user agent string
        function getChromeVersion() {
            var userAgent = navigator.userAgent;
            var chromeIndex = userAgent.indexOf("Chrome/");
            if (chromeIndex > -1) {
                var chromeVersion = userAgent.substring(chromeIndex + 7);
                chromeVersion = chromeVersion.split(" ")[0]; // Extract just the version number
                return chromeVersion;
            }
            return null;
        }
        var chromeVersion = getChromeVersion();
        if (chromeVersion) {
            var badgeUrl = `https://img.shields.io/badge/Chrome-${chromeVersion}-brightgreen`;
            document.getElementById("chrome-badge").src = badgeUrl;
        } else {
            document.getElementById("chrome-badge").src = "https://img.shields.io/badge/Browser-Not_Chrome-red";
        }
    </script>
```

And a second version which changes the color to RED when it's an older version of Chrome (in this case, earlier than Chrome v126):

Example: <img id="chrome-badge" src="https://img.shields.io/badge/Chrome-120-red" alt="Chrome Version Badge">
```
<script>
        // Function to get Chrome version from the user agent string
        function getChromeVersion() {
            var userAgent = navigator.userAgent;
            var chromeIndex = userAgent.indexOf("Chrome/");
            if (chromeIndex > -1) {
                var chromeVersion = userAgent.substring(chromeIndex + 7);
                chromeVersion = chromeVersion.split(" ")[0]; // Extract just the version number
                return parseFloat(chromeVersion); // Return version as a number
            }
            return null;
        }

        // Update the badge with Chrome version
        var chromeVersion = getChromeVersion();
        if (chromeVersion) {
            var color = chromeVersion < 126 ? "red" : "brightgreen"; // Set color based on version
            var badgeUrl = `https://img.shields.io/badge/Chrome-${chromeVersion}-${color}`;
            document.getElementById("chrome-badge").src = badgeUrl;
        } else {
            document.getElementById("chrome-badge").src = "https://img.shields.io/badge/Browser-Not_Chrome-red";
        }
    </script>
```
