### ISSUE TITLE
Add DownloadTracker

### ISSUE THREAD

**Issue by Lorenzo0111** [badges/shields#6504]
:clipboard: **Description**

Service: DownloadTracker
Description: DownloadTracker is an expressjs server to track downloads of a file.
Example: ![example](https://img.shields.io/badge/Downloads-15-informational)

:link: **Data**

EndPoint URL: e.g https://example.com/badge/
Project: e.g ProjectName. Use all for total downloads
Version: e.g 1.0. Do not add it if you want total downloads of a project

Template:
 - htttps://example.com/badge/all
 - htttps://example.com/badge/:project/
 - htttps://example.com/badge/:project/:version

Working Example: https://dl.rocketplugins.space/badge/all

:microphone: **Motivation**

It may be usefull for an easier way to get a DownloadTracker badge.
The project is new and it's born some days ago.

**Comment by PyvesB** [comment]
Hello @Lorenzo0111 ! 👋🏻 

Thanks for sharing this suggestion!

The website (I presume [this one](https://dl.rocketplugins.space) seems to be non functional at the minute, I land on an error page stating that the database is not connected. The working example you linked has also returned some sort of method invocation error. Looking at the commits on the repository, it appears that this is a personal project in its very early days.

If you really wanted to integrate native Shields.io badges:
* the service would need to be functional and stable.
* the service would need to have proper online resources, explaining how it works, what its purpose is and how to get in touch with support channels.
* there would need to be an API that is non Shields-specific (see #6368 for more details on what is meant by this).
* said API would need to be documented as per our [guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines).
* ideally the service should already have users and momentum.

For the time being, I think that leveraging our endpoint badges is the best course of action (https://shields.io/endpoint), and in a few months we can re-evaluate adding the native Shields.io badges if all aforementioned conditions are met. 😉
