### ISSUE TITLE
Badge request: piwheels package version

### ISSUE THREAD

**Issue by lordmauve** [badges/shields#6506]
:clipboard: **Description**

Show the current version of a Python package on piwheels.org:

```
piwheels | 0.3.0
```

:link: **Data**

piwheels has a JSON API, documented here: https://www.piwheels.org/json.html

:microphone: **Motivation**

piwheels.org is a mirror of PyPI, the Python Package Index, with packages rebuilt on Raspberry Pi OS for ARM CPUs. I'd like to include a "piwheels" badge to show support for piwheels and also to allow me to spot if piwheels has fallen behind PyPI (because a package is not building successfully for Raspberry PI).

**Comment by PyvesB** [comment]
Hello @lordmauve ! 👋🏻 

Thanks for the suggestion. Do you know if there are any rate-limiting constraints on the piwheels API?

**Comment by lordmauve** [comment]
@bennuttall, one of the creators of the service, may be able to answer.

**Comment by bennuttall** [comment]
There's no constraint as the JSON API is statically generated.

I was considering implementing this in piwheels, see https://github.com/piwheels/piwheels/issues/216

What would be the best way forward?

**Comment by PyvesB** [comment]
> What would be the best way forward?

That's entirely up to you!

Obviously, you can freely use the endpoint badge you mentioned in https://github.com/piwheels/piwheels/issues/216.  There aren't any restrictions there, though we obviously do encourage users to do sensible things!

The barrier of entry for integrating a badge as part of the core Shields.io service is higher. However, a badge integrating with the piwheels service would meet our [badge guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines) as far as I can tell. In particular it's a service targetted at developers with an easy-to-use and documented API.

If you want to get a feel of the work involved, you can check [our tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) out, or take a look at our existing [PyPi implementation](https://github.com/badges/shields/blob/master/services/pypi/pypi-version.service.js).

**Comment by bennuttall** [comment]
Ok cool I think it should be easy enough to add to piwheels. @lordmauve if you fancy pairing on it that would be fun.
