### ISSUE TITLE
Packagist badges shows “not found” but the package itself is published

### ISSUE THREAD

**Issue by Neur0toxine** [badges/shields#6509]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Packagist badge renders with "not found" error instead of the package version. I published it yesterday, but badge still doesn't work. The "PHP from Packagist" badge also doesn't  work. 

Package: https://packagist.org/packages/neur0toxine/pock
Packagist badge: [![Latest stable](https://img.shields.io/packagist/v/neur0toxine/pock.svg?style=flat-square)](https://packagist.org/packages/neur0toxine/pock)
PHP from Packagist badge: [![PHP from Packagist](https://img.shields.io/packagist/php-v/neur0toxine/pock.svg?logo=php&logoColor=white&style=flat-square)](https://packagist.org/packages/neur0toxine/pock)

:link: **https://img.shields.io/packagist/v/neur0toxine/pock.svg?style=flat-square**
:link: **https://img.shields.io/packagist/php-v/neur0toxine/pock.svg?logo=php&logoColor=white&style=flat-square**

:bulb: **Possible Solution**

**Comment by PyvesB** [comment]
Hello @Neur0toxine ! 👋🏻 

This seems related to #6508. Wouldn't it fix your issue, once merged? Feel free to help us out and give that pull request a preliminary review. 😉

**Comment by Neur0toxine** [comment]
Yes, this will fix my issue. I doubt that my review for the PR would be of much help, but the code itself looks fine to me.

Thanks for your answer.

**Comment by paulmelnikow** [comment]
If this recurs please feel free to open a new issue!
