### ISSUE TITLE
Delete deprecated services

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6514]
We've currently got 22 deprecated service families, some of which containing more than one `deprecatedService` (29 of them in total). Our earliest deprecation, Gratipay, dates all the way back to 2017.

The number of deprecated services will keep growing over time if we do nothing about them. This is not an immediate problem per say, but it would be nice to tidy after ourselves and keep things under control.

Back in https://github.com/badges/shields/pull/1449#issuecomment-370189049, @paulmelnikow had suggested retaining them around for about a year before removing them for good. What do people think?

Whatever removal policy we come up with, let's document it here: https://github.com/badges/shields/blob/master/doc/deprecating-badges.md

**Comment by chris48s** [comment]
:+1:  I'm on board with just binning anything we deprecated more than a year ago if you are up for doing a spring clean :broom:

**Comment by calebcartwright** [comment]
Agreed. Do folks think it'd be worthwhile to have a list in a markdown file of badges that were deprecated and removed for posterity? I realize users and ourselves can always search for and look back at issues and PRs that did deprecation and removal but might be easier to have a single file somewhere we could point to

**Comment by PyvesB** [comment]
> Do folks think it'd be worthwhile to have a list in a markdown file of badges that were deprecated and removed for posterity?

> Whatever removal policy we come up with, let's document it here: https://github.com/badges/shields/blob/master/doc/deprecating-badges.md

We could for example have a section along the lines of `Once a service is deprecated, what happens next?` and list the deleted ones there.

**Comment by calebcartwright** [comment]
> We could for example have a section along the lines of Once a service is deprecated, what happens next? and list the deleted ones there.

Yup, I really like that idea!
