### ISSUE TITLE
Change server module to ESM from CommonJS

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#6528]
Several core dependencies within our tree have cut over from CommonJS to ESM which is blocking updates (#6419).

This was discussed at the last ops meeting and consensus seems to be that we'll need to completely move the server over to ESM sooner rather than later

**Comment by PyvesB** [comment]
Have started looking into this in a bit more details. Not sure how far I'll get, but hopefully I'll have something to share soon-ish.

**Comment by paulmelnikow** [comment]
🚀 🎉

**Comment by chris48s** [comment]
Now that the CommonJS to ESM migration is done there is a follow up job of upgrading the dependencies we have been ignoring. Do we have a list of what dependency upgrades this unblocks aside from escape-string-regexp ?
