### ISSUE TITLE
error while installing "gh-badges" 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [badges/shields#653]
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gh-badges" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

**Comment by andrewhead** [comment]
Hi kuldeepkeshwar.  I am also seeing this error when trying to install gh-badges.  It looks like a problem with compiling `canvas@1.1.6`.  Did you end up finding a solution?

**Comment by kuldeepkeshwar** [comment]
Hi andrewhead , my use case was quite specific , wanted to generate coverage  badge during the build using grunt, so I ended up writing my own [plugin](https://github.com/node-libs/grunt-coverage-badger) which down the line uses "shields.io" api.
i.e  
`https://img.shields.io/badge/<label>-<value>-<color>.svg`
e.g
https://img.shields.io/badge/coverage-50%-red.svg

**Comment by andrewhead** [comment]
Thanks for this, @kuldeepkeshwar.  Was hoping to use gh-badges as a local dependency for quickly drawing badges in a D3 application, though the online API could work.  I appreciate your response!

**Comment by espadrine** [comment]
Unfortunately, solving this requires to rewrite the tests with a new testing framework.

**Comment by andrewhead** [comment]
Ah, I see.  I have my bases covered by porting the `badges.js` and `measure-text.js` files into my project.  Though I would love to hear if this eventually gets fixed.  Thanks for the update!

**Comment by mister-walter** [comment]
Had the same issue trying to install gh-badges from NPM on Ubuntu 16.04. For some reason, it works fine when installing using NPM with the Github URL though.

**Comment by paulmelnikow** [comment]
Since #496 we're using pdfkit instead of canvas, so I imagine this problem has gone away. If it's persisting, could you let me know which version of the package, and the steps to reproduce?

**Comment by mattbk** [comment]
I've run into the ELIFECYCLE code on Windows and Ubuntu. Running `node server.js` directly seems to work.

**Comment by paulmelnikow** [comment]
Could you open a new issue and post details? Thanks!
