### ISSUE TITLE
Opening a new Tab/Window when creating a badge

### ISSUE THREAD

**Issue by SamuelEnglard** [badges/shields#6534]
On the website, when you make a badge you are show the badge in the same window/tab. It would be great if this opened a new window/tab so that I can easily tweak what I input (since it's loss on going back).

**Comment by paulmelnikow** [comment]
Hi! Could you post a screenshot of which page you’re talking about?

**Comment by SamuelEnglard** [comment]
![image](https://user-images.githubusercontent.com/1119883/119557145-cfc7e100-bd6d-11eb-8398-223a7844dbfd.png)

The two "Make Badge" buttons

**Comment by PyvesB** [comment]
Hello @SamuelEnglard! 👋🏻 

Makes much more sense with the screenshot and the explanation, thanks. Would you be up for contributing this and submitting a pull request?

**Comment by SamuelEnglard** [comment]
Sure! should be easy enough, though I'm not sure how fast I can get to it myself
