### ISSUE TITLE
Nuget  badges inaccessible

### ISSUE THREAD

**Issue by 304NotModified** [badges/shields#655]
(Comment hijacked to summarize the advancement.)

https://github.com/badges/shields/blob/5e4c71181372b5ec86b844aded99acb5f0270b28/server.js#L3163

NuGet returns a different content type, which is probably why shields.io breaks on the XML/Atom response received from NuGet.

Using the v3 API:

* Append the package identifier + index.json, for example: `https://api.nuget.org/v3/flatcontainer/{packageid-lowercase}/index.json`. The JSON has all versions of the package and can tell you in one go what the latest version is. eg, https://api.nuget.org/v3/flatcontainer/microsoft.aspnet.mvc/index.json 
* Get the latest version: (latest = last item in the list, latest stable is last one in the list that does not have a - in the version number)

There is no download information in v3, we'd have to keep the old system which still works for Chocolatey.

Chocolatey doesn't seem to use the v3: https://api.chocolatey.org/v3/flatcontainer/scriptcs/index.json, so we can't use it even for versions.

We cannot find the v3 endpoint for myget: neither https://www.myget.org/F/yolodev/api/v3/flatcontainer/fsharpsupport/index.json nor https://api.myget.org/F/yolodev/v3/flatcontainer/fsharpsupport/index.json work.

---

(Original comment here.)

The NuGet badges are inaccessible for days. Is this a rate limit? Is there something I can do? Is this for every visitor?  Can you cache more at your side?

Current what I see:

![image](https://cloud.githubusercontent.com/assets/5808377/13143570/1815b736-d645-11e5-9dc8-7802284a3136.png)

One of the links:

- https://img.shields.io/nuget/v/NLog.svg 
- https://www.nuget.org/packages/NLog

We see it also on shield.io:

![image](https://cloud.githubusercontent.com/assets/5808377/13143605/579a4980-d645-11e5-9e29-03ac21218f5e.png)

We have arround 5K views/day

![image](https://cloud.githubusercontent.com/assets/5808377/13143639/988f6024-d645-11e5-9d0b-7a56d9117dc9.png)

**Comment by MathewSachin** [comment]
I also experience the same issue on my repository with not that man views.

It is noticeable that the badge is also in **inaccessible** state at shields.io

**Comment by odinserj** [comment]
I have the same with [Hangfire](http://hangfire.io) project.

**Comment by 304NotModified** [comment]
Too bad there seems that there is no support here.

**Comment by t1st3** [comment]
seems it is fixed (2016/02/23 11PM LMT)

**Comment by odinserj** [comment]
Confirming, fixed :tada:

**Comment by 304NotModified** [comment]
Down again

**Comment by 304NotModified** [comment]
we moved partly to https://badge.fury.io/for/nu, which do work (but has less features)

**Comment by dustinmoris** [comment]
Shields NuGet badges stopped working for me as well so I added support for NuGet badges to [buildstats.info](https://github.com/dustinmoris/CI-BuildStats#user-content-nuget-badge).

**Comment by SimonCropp** [comment]
any update on this?

**Comment by maartenba** [comment]
What is the request shields.io is making to NuGet?

**Comment by 304NotModified** [comment]
@maartenba thx for the tech info! 

@espadrine can you help us with this?

**Comment by danbarua** [comment]
The MyGet badge is broken too.

**Comment by 304NotModified** [comment]
> The MyGet badge is broken too.

Good luck. We have issues with the NuGet badges for more then 30 days, without any response of shields.io team.

**Comment by dustinmoris** [comment]
@danbarua I have [added a MyGet badge to buildstats.info](https://github.com/dustinmoris/CI-BuildStats#myget-badge). Please have a look if it suits you...

**Comment by SimonCropp** [comment]
i moved to buildstats

**Comment by danbarua** [comment]
@dustinmoris Sweet, thanks!

**Comment by kzu** [comment]
Confirmed to still be broken :(

**Comment by Yortw** [comment]
Still broken for me too.

**Comment by atifaziz** [comment]
Likewise

**Comment by espadrine** [comment]
> We have issues with the NuGet badges for more then 30 days, without any response of shields.io team.

Sorry. PRs get priority treatment, which unfortunately can only go as fast as I can review them.

> NuGet returns a different content type, which is probably why shields.io breaks on the XML/Atom response received from NuGet.

Yes, I receive XML which I parse as JSON. @Alxandr do you know if there is an easy fix?

**Comment by AArnott** [comment]
@espadrine: @maartenba's [prescribed fix](https://github.com/badges/shields/issues/655#issuecomment-191274714) looks pretty simple, and his URLs result in JSON responses so it would avoid you having to parse XML.

**Comment by espadrine** [comment]
@AArnott I am very much open to PRs on this. I know very little about NuGet, let alone its API. Given the range of what we support, it feels nontrivial for me to replace it without breaking Chocolatey, even if the described fix was clear. But as I said, I cannot find `RegistrationBaseAddress` in https://api.nuget.org/v3/index.json, and https://api.nuget.org/v3/flatcontainer/Microsoft.AspNet.Mvc/index.json yields nothing.

**Comment by maartenba** [comment]
Oops, need to be `RegistrationsBaseUrl`.
ANd all URLs sould be lowercase at all times.

**Comment by AArnott** [comment]
@espadrine: for what it's worth, both I and @vbfox tried to prepare a PR for this change, but we couldn't get your project's dependencies installed locally to prepare the fix. We both have Windows machines, and @vbfox even tried setting up a Linux box.

**Comment by espadrine** [comment]
@maartenba thanks. What is the purpose of the registration URL? Do you know if there is a way to ask for the latest version, as we had before when using filters? Also, where is the download information?

Is there a good link to the most exhaustive piece of documentation on the v3 API?

@AArnott A change I merged yesterday should make local testing much easier, as the project no longer relies on Cairo.

**Comment by maartenba** [comment]
@espadrine The registration URL has all versions of the package. There is also `PackageBaseAddress/3.0.0` which has just the list of versions, for example https://api.nuget.org/v3/flatcontainer/microsoft.aspnet.mvc/index.json (latest = last item in the list, latest stable is last one in the list that does not have a `-` in the version number)

Regarding downloads, there is no API for that currently.

**Comment by espadrine** [comment]
Unfortunately, chocolatey doesn't seem to use the v3: https://api.chocolatey.org/v3/flatcontainer/scriptcs/index.json

**Comment by kzu** [comment]
shouldn't all those be different paths though? Why would chocolatey or myget limit what API you use for nuget.org? Aren't (or shouldn't) they different badges altogether?

**Comment by espadrine** [comment]
They had different domains, but the same code is running on each of those domains, so we could perform the same requests.

**Comment by Alxandr** [comment]
Myget supports v3. Chocolatey I have no idea.

**Comment by espadrine** [comment]
@Alexandr do you know what URL I should try for MyGet?

**Comment by Alxandr** [comment]
The entrypoint of a feed is herehttps://www.myget.org/F/dotnet/api/v3/index.json

If you just go to the nuget gallery and pick a random feed (like I just did) it'll tell you.

**Comment by espadrine** [comment]
> The entrypoint of a feed is here https://www.myget.org/F/dotnet/api/v3/index.json

I can see https://dotnet.myget.org/F/dotnet-corert/api/v3/flatcontainer/ in there. I'm not sure how to get fsharpsupport, for instance: https://dotnet.myget.org/F/dotnet-corert/api/v3/flatcontainer/fsharpsupport/index.json

**Comment by Alxandr** [comment]
The dotnet feed and the yolodev feed are not the same. 


https://dotnet.myget.org/F/dotnet-corert/api/v3/flatcontainer/Microsoft.DotNet.AppDep/index.json

**Comment by espadrine** [comment]
The yolodev feed still exists, though, right? https://www.myget.org/F/yolodev/api/v3/flatcontainer/FSharpSupport/index.json yields nothing, and yet https://yolodev.myget.org/F/yolodev/api/v3/index.json yields https://www.myget.org/F/yolodev/api/v3/flatcontainer/.

**Comment by Alxandr** [comment]
Yes, but that package no longer does :)

https://www.myget.org/F/yolodev/api/v3/flatcontainer/YoloDev.Dnx.FSharp/index.json

**Comment by espadrine** [comment]
Unfortunately, the download information is lost in translation for both nuget and myget.

**Comment by 304NotModified** [comment]
Thanks for the fix!

**Comment by kzu** [comment]
Awesome! Thanks!

**Comment by atifaziz** [comment]
Cheers! :clap:
