### ISSUE TITLE
The Vue.js icon is invalid

### ISSUE THREAD

**Issue by fz6m** [badges/shields#6572]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

![Vue](https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=Vue.js&logoColor=fff)

```js
  https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=Vue.js&logoColor=fff
```

I found [simple-icons](https://simpleicons.org/) updated `Vue.js` to `vuedotjs`, but it still couldn't load the icon

New vue icon link: [https://github.com/simple-icons/simple-icons/blob/develop/icons/vuedotjs.svg](https://github.com/simple-icons/simple-icons/blob/develop/icons/vuedotjs.svg)

![Vue](https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vuedotjs&logoColor=fff)

```js
  https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vuedotjs&logoColor=fff
```

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
The correct icon slug at the moment is still the old `vue-dot-js`

https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vue-dot-js&logoColor=fff
![](https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vuedotjs&logoColor=fff)

In their latest release (couple days back), the Simple Icons team have updated a number of their slugs. However, those updates don't just automatically cascade everywhere. The next time we update the version of the simple-icons package that Shields uses we will pull in those changes, and the slugs will accordingly be impacted, but for the time being you should continue to use the historical slug.

**Comment by kuohuanhuan** [comment]
Update: currently `https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vuedotjs&logoColor=white` does work:
![vuejsdemo](https://img.shields.io/badge/-Vue-4fc08d?style=flat&logo=vuedotjs&logoColor=white)

**Comment by alevirdz** [comment]
Les dejo un ejemplo para usarlo en su git README

[![VUE](https://img.shields.io/badge/VUE.JS-000000?style=for-the-badge&logo=vuedotjs&logoColor=44E192)]()
