### ISSUE TITLE
/github/workflow/status/:user/:repo/:workflow is not able to find the workflow

### ISSUE THREAD

**Issue by ithinkthisisnotreal** [badges/shields#6593]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I want to add a workflow badge, so from shields.io I took this url

> /github/workflow/status/:user/:repo/:workflow

and wanted to test it with any public repository, I'm using this for testing purposes

https://github.com/thenativeweb/wolkenkit/blob/main/.github/workflows/qa.yml

Unfortunately the badge is not able to find the workflow.

:link: **Link to the badge**

https://img.shields.io/github/workflow/status/thenativeweb/wolkenkit/qa

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close. As noted in various previous issues, our badges utilize the user-specified workflow _name_ (defined _within_ the yaml file) which is case sensitive; not the yaml filename of the workflow definition.

You've defined `QA` (note the upper case) as your workflow name [here](https://github.com/thenativeweb/wolkenkit/blob/main/.github/workflows/qa.yml#L1) therefore you need to use the identical `QA` for the route parameter.

Try this instead:
https://img.shields.io/github/workflow/status/thenativeweb/wolkenkit/QA
![](https://img.shields.io/github/workflow/status/thenativeweb/wolkenkit/QA)
