### ISSUE TITLE
Allow custom background colour for the label section

### ISSUE THREAD

**Issue by abrahammurciano** [badges/shields#6595]
:clipboard: **Description**

It would be great if I were able to specify a custom background colour for the label as well, instead of it always being dark grey.

If this is something you'd consider supporting, I wouldn't mind having a go at implementing it myself.

**Comment by chris48s** [comment]
Hi. There is already a `labelColor` param e.g: https://img.shields.io/badge/label-message-blue?labelColor=red

**Comment by abrahammurciano** [comment]
I see, I was looking for it but I didn't find it. Thanks
