### ISSUE TITLE
shields.io status page not working

### ISSUE THREAD

**Issue by tooomm** [badges/shields#6598]
![status](https://user-images.githubusercontent.com/9874850/121647372-a067e280-ca96-11eb-8f9c-a67eb51075de.png)

--> https://status.shields.io/

**Comment by PyvesB** [comment]
Hello @tooomm ! 👋🏻 

Thanks for raising. I'm aware (https://github.com/badges/shields/pull/6327#issuecomment-838065081), it's on my list of things to fix. 😉

**Comment by PyvesB** [comment]
UptimeRobot no longer supports custom domains as part of its free plan. It's probably not worth upgrading to Pro just for that feature, let's use the standard URL instead: https://stats.uptimerobot.com/PjXogHB5p
