### ISSUE TITLE
Color changes for custom dynamic badges

### ISSUE THREAD

**Issue by tooomm** [badges/shields#6599]
:clipboard: **Description**

Assuming a custom dynamic badge displays e.g. numeric values.
I would like to configure certain thresholds that change the badge color.

Example result:
![](https://img.shields.io/badge/example%20value-10-green)
![](https://img.shields.io/badge/example%20value-100-yellow)
![](https://img.shields.io/badge/example%20value-1000-red)

**Comment by chris48s** [comment]
Hello. It isn't possible to do this with the dynamic json/xml/yaml badges and we don't plan to that feature to those badge.
If you want this level of customisation for a completely bespoke badge it can be done with the endpoint badge https://shields.io/endpoint this requires a bit more setup but it is much more customisable :)
