### ISSUE TITLE
No proper error handling when I paste improper URL 

### ISSUE THREAD

**Issue by susheelg1197** [badges/shields#6627]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Steps to create this error,
1. Copy your github profile URL ( Note: this is your profile URL must not consist any repo)
2. Click on Suggest badges button after pasting the URL.
3. Screen goes blank with a console error `react-dom.production.min.js:216 TypeError: Expected "repo" to be a string`
![image](https://user-images.githubusercontent.com/62594644/121702731-c40b4700-caef-11eb-9057-b3f92c5ac801.png)

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by susheelg1197** [comment]
Assign this issue to me

**Comment by paulmelnikow** [comment]
Thanks! If you get stuck, feel free to post here and one of the maintainers can help!

**Comment by PyvesB** [comment]
> Assign this issue to me

@susheelg1197 any luck looking into this issue?

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/ including a new builder UI

Closing this issue as it relates to the previous frontend
