### ISSUE TITLE
Custom shields documentation

### ISSUE THREAD

**Issue by djap96** [badges/shields#663]
Hello, thanks for your amazing work, keep it up!
I think is very important to make custom shield generator more noticeable in [shields.io](http://shields.io). 
INSTALL.md points custom shields to [img.shields.io](http://img.shields.io) which redirect to [shields.io](http://shields.io).
Also in README.md there is no specification to generate your own shield.

**Comment by espadrine** [comment]
Thanks for your suggestion!
