### ISSUE TITLE
Add support for VS Marketplace badges to Suggest badges feature

### ISSUE THREAD

**Issue by wenfangdu** [badges/shields#6632]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

I expected to see all VS Marketplace extension-related badges, but only the Twitter badge showed up:

![image](https://user-images.githubusercontent.com/28700378/121825592-ef578700-cce5-11eb-83df-260fdd7c56db.png)

:link: **Link to the extension**

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

:bulb: **Possible Solution**

When clicking `suggest badges`, show all VS Marketplace extension-related badges.

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/ including a new builder UI

Closing this issue as it relates to a removed feature from the previous frontend

**Comment by wenfangdu** [comment]
@chris48s Thanks for the update, the design looks way better.

**Comment by wenfangdu** [comment]
@chris48s Thanks for the update, the new design looks way better.
