### ISSUE TITLE
Scrutinizer badge not working with numeric branch

### ISSUE THREAD

**Issue by floriankraemer** [badges/shields#6635]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

It is not generating a badge for branch called `2.0`

:link: https://img.shields.io/scrutinizer/quality/g/Phauthentic/authentication/2.0.svg?style=flat-square
![](https://img.shields.io/scrutinizer/quality/g/Phauthentic/authentication/2.0.svg?style=flat-square)

It works for master:

:link: https://img.shields.io/scrutinizer/quality/g/Phauthentic/authentication/master.svg?style=flat-square

:bulb: **Possible Solution**

Make it work. :)

(Edit: added embedded badge for visual)

**Comment by calebcartwright** [comment]
Are you sure you've executed against your 2.0 branch? We don't run any of the tools/scans/etc. provided by the upstream services, we just query the data they make available.

The API response we're getting from Scrutinizer for your project doesn't show any runs against any branches other than your `master` branch.

If you think that's a mistake, then that's something you'll want to take up with Scrutinizer themselves

https://scrutinizer-ci.com/api/repositories/g/Phauthentic/Authentication

**Comment by calebcartwright** [comment]
The badge is rendering now, and unsurprisingly that's because the data is now showing in the Scrutinizer API response. I'm going to assume that either you triggered an initial scan of that branch after opening this issue, or Scrutinizer had some kind of delay on their end providing the data.

Either way, going to close since the badge is working
