### ISSUE TITLE
Unparseable json response for lines of code badge

### ISSUE THREAD

**Issue by Hongbo-Miao** [badges/shields#6637]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The lines of code badge works before, however, since several days ago, it shows: unparseable json response.

Issue badge screenshot:
![image](https://user-images.githubusercontent.com/3375461/122435367-86645d80-cfca-11eb-9bb8-38c7006b99ab.png)

Live version:
<a href="https://github.com/Hongbo-Miao/hongbomiao.com"><img alt="Lines of code" src="https://img.shields.io/tokei/lines/github/Hongbo-Miao/hongbomiao.com" /></a>

:link: https://img.shields.io/tokei/lines/github/Hongbo-Miao/hongbomiao.com

**Comment by chris48s** [comment]
Hello. This is happening because https://tokei.rs/b1/github/Hongbo-Miao/hongbomiao.com it is returning a non-JSON response

```
curl -H "Accept: application/json" "https://tokei.rs/b1/github/Hongbo-Miao/hongbomiao.com"
```

If I call another URL like

```
curl -H "Accept: application/json" "https://tokei.rs/b1/github/badges/shields"
```

that returns JSON as expected. This appears to be an issue with the tokei.rs service so can you raise an issue with them please.

**Comment by Hongbo-Miao** [comment]
Thanks @chris48s ! Created at https://github.com/XAMPPRocky/tokei/issues/794
