### ISSUE TITLE
Sudden change in server availability

### ISSUE THREAD

**Issue by tonious** [badges/shields#665]
<img width="703" alt="screen shot 2016-03-04 at 2 12 18 pm" src="https://cloud.githubusercontent.com/assets/93585/13537671/fa3c498e-e213-11e5-8743-8afde3417a7e.png">
<img width="710" alt="screen shot 2016-03-04 at 2 12 33 pm" src="https://cloud.githubusercontent.com/assets/93585/13537672/fa3d1c88-e213-11e5-9a65-26cbf39ab01f.png">

According to pingdom, shields.io badge availability has drastically changed yesterday.  Is there anything that can be done to bring stability back to what it was?

**Comment by satazor** [comment]
@tonious I'm experiencing this for 2 months now.. I hope this changes or I will be forced to change my badges :(

![image](https://i.imgur.com/gdtYsuo.png)

**Comment by espadrine** [comment]
Servers restarted. Sorry!

**Comment by satazor** [comment]
@espadrine the restart solved but the issue is happening again..

**Comment by espadrine** [comment]
A server had ran out of disk capacity because bower cache used 5Go. I killed the cache. I am still seeing timeouts from vendors; not sure why yet.

**Comment by satazor** [comment]
@espadrine did you took any measure to delete the bower cache often? Maybe a crontab that runs once a day?

**Comment by satazor** [comment]
Update: I'm seeing this now ![image](https://i.imgur.com/HP9cjtG.png)

**Comment by espadrine** [comment]
OVH has just flagged the incoming traffic as a DDoS after I restarted the server.

**Comment by satazor** [comment]
This will only solve the issue temporarly. What can be done to make this more stable?

**Comment by espadrine** [comment]
For starters, this event was definitely not ongoing for 2 months. What badge do you have issues with? Some vendors, such as Travis or GitHub, regularly block shields.io's IPs because the load is too large.

Beyond that, I am the only one that's doing the servers' sysadmin. What happens in my sleep cannot be fixed unless someone living at the opposite side of the earth wants to perform sysadmin for no pay.

**Comment by satazor** [comment]
I'm having issues with travis and coveralls badges. I understand the highload and we could implement strategies to throttle requests to thirdparty but it would require a restructure of how things are done technically.

**Comment by tonious** [comment]
<img width="715" alt="screen shot 2016-03-05 at 9 04 47 pm" src="https://cloud.githubusercontent.com/assets/93585/13551848/d76180c0-e315-11e5-9a64-761824bd9b68.png">
Looks like things have returned to normal.
