### ISSUE TITLE
"Heavy Black Heart" emoji does not display correctly

### ISSUE THREAD

**Issue by Xiphe** [badges/shields#666]
Lookslike: [![Heavy Black Heart](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-heart-ff00ff.svg)](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-heart-ff00ff.svg)

Url: `https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-heart-ff00ff.svg`

Whereas "Yellow Heart" works fine

Lookslike: [![Heavy Black Heart](https://img.shields.io/badge/%F0%9F%92%9B-yellow_heart-eecc00.svg)](https://img.shields.io/badge/%F0%9F%92%9B-yellow_heart-eecc00.svg)

Url: `https://img.shields.io/badge/%F0%9F%92%9B-yellow_heart-eecc00.svg`

Any idea how to fix this?

**Comment by espadrine** [comment]
How should it display?

It looks like this to me, which seems fine: 
![heart](https://cloud.githubusercontent.com/assets/100689/14398779/138655a8-fde7-11e5-989d-c100daab7fbf.png)

**Comment by espadrine** [comment]
So, I tried it on OS X 10.11.5 in Chrome 50.0.2661.102. It looks as intended. (Apart from subtle font rendering differences, it's about the same as the Linux PNG I posted.)

Could you be missing a font? I believe Chrome is meant to try a default system font when it can't find a glyph, and the default system font is meant to contain a very large amount of glyphs. At least one of the fonts OS X ships with should probably have that glyph.

Could you try installing [Symbola](http://users.teilar.gr/~g1951d/Symbola.zip), to rule out other possibilities?

**Comment by Xiphe** [comment]
ah, i can't reproduce it anymore, too. thanks for caring ❤️
