### ISSUE TITLE
Shippable Badges seem to not work anymore

### ISSUE THREAD

**Issue by thomasWeise** [badges/shields#667]
It seems to me that the badges for [shippable](http://app.shippable.com) do not work anymore.

This holds for my own project as well as for the badges on the [examples page](http://shields.io/); see, for instance, ![https://img.shields.io/shippable/54d119db5ab6cc13528ab183.svg](https://img.shields.io/shippable/54d119db5ab6cc13528ab183.svg).

At least when I access them (from China), they all render to "build inaccessible."

**Comment by espadrine** [comment]
Thanks for raising the issue.

First of all, it seems that this issue is not limited to China. In fact, Shippable's own badge shows "none": https://api.shippable.com/projects/54d119db5ab6cc13528ab183/badge. Do you know whether there is a Shippable badge that does not show "none"?

**Comment by thomasWeise** [comment]
How about:

![https://api.shippable.com/projects/56981e821895ca4474685412/badge](https://api.shippable.com/projects/56981e821895ca4474685412/badge): <a href="https://api.shippable.com/projects/56981e821895ca4474685412/badge">https://api.shippable.com/projects/56981e821895ca4474685412/badge</a>

corresponding to

![https://img.shields.io/shippable/56981e821895ca4474685412.svg](https://img.shields.io/shippable/56981e821895ca4474685412.svg): <a href="https://img.shields.io/shippable/56981e821895ca4474685412.svg">https://img.shields.io/shippable/56981e821895ca4474685412.svg</a>

**Comment by espadrine** [comment]
I believe #711 fixed this. Please reopen if you disagree.
