### ISSUE TITLE
Badge request: Debian User Repository

### ISSUE THREAD

**Issue by hwittenborn** [badges/shields#6680]
:clipboard: **Description**

The Debian User Repository is an AUR-like platform designed for Debian users.

:link: **Data**

Link: https://dur.hunterwittenborn.com/
Data: API requests take the same format as the AUR.

:microphone: **Motivation**

It only has a few packages at the moment (and is still quite experimental), but being able to see things like version stats for the DUR, even right now, would be a huge plus.

It shouldn't be too hard to hook into it as well, as pretty much everything should be identical to that of the AUR.

**Comment by paulmelnikow** [comment]
Hi! Thanks for reaching out.

Could I suggest Shields consider integrating with this service after it's gotten a bit more adoption?

In the meantime [the Shields Endpoint badge](https://shields.io/endpoint) provides a recommended way for a third party to implement a badge data source that can be rendered and cached by img.shields.io.

**Comment by hwittenborn** [comment]
Yep, that's fine.

I'll look into the shield endpoint stuff to see what I can do.

**Comment by paulmelnikow** [comment]
Sounds good. Let us know if you need any help with that!

I've also started a list of dynamic data providers which work with Shields, and happy to include this there once you have it working: https://github.com/badges/awesome-badges#dynamic-data-providers

Going to close this for now, but feel free to reply here if you need more help.
