### ISSUE TITLE
Deprecate Microbadger service

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6703]
:clipboard: **Description**

- Tests for all badges are failing
- https://microbadger.com is down.
- Looks like they've officially shuttered it: https://twitter.com/microscaling/status/1361054926399557644

**Comment by calebcartwright** [comment]
Good find. Fortunately we've already extended our Dockerhub-based capabilities to provide size badges and folks should be able to switch their badges over easily. The only one that's actually gone is the layer count badge and we may be able to do the same depending on whether the Docker APIs make the data available
