### ISSUE TITLE
Weird LICENSE badge bug on my two normal repositories

### ISSUE THREAD

**Issue by sabertazimi** [badges/shields#6714]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When it comes to `for-the-badge` style license badge, bug happened.

`https://img.shields.io/github/license/sabertazimi/boilerplate?style=for-the-badge` got `NOT SPECIFIED`,
and `https://img.shields.io/github/license/sabertazimi/mdb?style=for-the-badge` got `NOT IDENTIFIABLE BY GITHUB`.

But when I add override label `LICENSE` to them, seeking for methods of bugfix, it works.
`https://img.shields.io/github/license/sabertazimi/boilerplate?label=LICENSE&style=for-the-badge` and
`https://img.shields.io/github/license/sabertazimi/mdb?label=LICENSE&style=for-the-badge` got right license badge.

### 🔗 Link to the badge

- [Wrong LICENSE Badge for @sabertazimi/boilerplate](https://img.shields.io/github/license/sabertazimi/boilerplate?style=for-the-badge)
- [Wrong LICENSE Badge for @sabertazimi/mdb](https://img.shields.io/github/license/sabertazimi/mdb?style=for-the-badge)
- [Bug-free LICENSE Badge for @sabertazimi/boilerplate by adding override label](https://img.shields.io/github/license/sabertazimi/boilerplate?label=LICENSE&style=for-the-badge)
- [Bug-free LICENSE Badge for @sabertazimi/mdb by adding override label](https://img.shields.io/github/license/sabertazimi/mdb?label=LICENSE&style=for-the-badge)

### 💡 Possible Solution

Adding override label `label=LICENSE` works.

**Comment by calebcartwright** [comment]
Thank you for reaching out but your diagnosis is incorrect. You were trying to get the badges to render immediately after first adding the license files to your repositories, but GitHub does not instantaneously pick up license changes the second it receives the commits.

If you'd waited for a few minutes you would've seen the data start to flow through on its own after the cached version expired, whereas adding the additional `label` query param simply forced a cache bust

https://img.shields.io/github/license/sabertazimi/boilerplate?style=for-the-badge
![](https://img.shields.io/github/license/sabertazimi/boilerplate?style=for-the-badge)

https://img.shields.io/github/license/sabertazimi/mdb?style=for-the-badge
![](https://img.shields.io/github/license/sabertazimi/mdb?style=for-the-badge)

https://img.shields.io/github/license/sabertazimi/boilerplate?label=LICENSE&style=for-the-badge
![](https://img.shields.io/github/license/sabertazimi/boilerplate?label=LICENSE&style=for-the-badge)

https://img.shields.io/github/license/sabertazimi/mdb?label=LICENSE&style=for-the-badge
![](https://img.shields.io/github/license/sabertazimi/mdb?label=LICENSE&style=for-the-badge)

**Comment by sabertazimi** [comment]
THX!
