### ISSUE TITLE
Support for snyk.io

### ISSUE THREAD

**Issue by graingert** [badges/shields#673]
It would be super great if you could support snyk.io badges

**Comment by espadrine** [comment]
Thanks for your suggestion!

I suppose we could have, say, `/snyk/vuln/<NPM PACKAGE NAME>.svg` with the number of vulnerabilities found.

snyk.io has documentation, though no API, it seems: https://snyk.io/docs/. However, they do serve badges: https://snyk.io/test/npm/jsbin/badge.svg. You can change the style as per shields.io, although you cannot change the label and things like that.

**Comment by paulmelnikow** [comment]
Looks like moving forward on this would require an API.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
