### ISSUE TITLE
Badge Request: Open in Visual Studio Code

### ISSUE THREAD

**Issue by marcobiedermann** [badges/shields#6752]
:clipboard: **Description**

Open any GitHub repository in Visual Studio Code
The fastest way to open a repo in VS Code.

You can add a badge to your repo's readme using this Markdown, replacing organization/repository with the values for your repo:

```md
[![Open in Visual Studio Code](https://open.vscode.dev/badges/open-in-vscode.svg)](https://open.vscode.dev/organization/repository)
```

:link: **Data**

https://open.vscode.dev/

**Comment by calebcartwright** [comment]
Thanks for reaching out, but there's not really any action to be taken here so I am going to close.

You might want to consider submitting a PR to add that bade to the [Awesome badges list](https://github.com/badges/awesome-badges), most likely under the Static badges section
