### ISSUE TITLE
NuGet download count no longer works

### ISSUE THREAD

**Issue by Daniel15** [badges/shields#678]
eg. http://img.shields.io/nuget/dt/RouteJs.Mvc4.svg

I understand that this was due to #655, but it would be good to have some solution to retrieve download counts. Visual Studio shows download count in the package browser when using v3 endpoints, so the data must be available somewhere.

**Comment by espadrine** [comment]
I would recommend contacting someone knowledgeable about v3, someone at Microsoft perhaps?

**Comment by Daniel15** [comment]
I was going to work on this but I can't even find the source code for NuGet API v3 to determine all the available endpoints.The NuGet Gallery codebase only contains the v1 and v2 APIs. Perhaps I should proxy Visual Studio to see how it does it, although I imagine it uses a search endpoint.

**Comment by Daniel15** [comment]
Cross-posted to NuGet repo: https://github.com/NuGet/Home/issues/2596

**Comment by paulmelnikow** [comment]
In #792, @kzu posted:

> The new APIs in NuGet v3 server should make this fairly straightforward now.
>
> For example, to get the stats for GitLink, you would issue an HTTP get to:
>
> https://api-v2v3search-0.nuget.org/query?q=packageid:gitlink
>
> Which gives you json with `data.totalDownloads = 11605` as of this writing.

**Comment by paulmelnikow** [comment]
@Daniel15 or @kzu, would one of you like to open a pull request?

**Comment by Daniel15** [comment]
Sure, I'll take a look!

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>

**Comment by Daniel15** [comment]
PR submitted: #945

**Comment by paulmelnikow** [comment]
Merged! Will be deployed soon.

**Comment by kzu** [comment]
Awesome guys, thank you!!!
