### ISSUE TITLE
Why my lines of code are 0?

### ISSUE THREAD

**Issue by KartoshkaPy** [badges/shields#6833]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi! I added lines of code badge to my README.md, but I have no lines

I noticed a problem in my repo https://github.com/KartoshkaPy/Sweet-Coin-Market

I know that it's using Tokei
I installed Tokei locally and everything works correctly
![image](https://user-images.githubusercontent.com/59607313/126936164-687b46f8-d47f-416b-9e41-5474901d7fba.png)

Is it really bug?

This badge also don't works in my other repos
For example https://github.com/qBasket-File-Sharing-Platform/Cloud-Service

But I didn't change anything
Everything worked before, but now it doesn’t

I thought I was wrong somewhere, but any badges have 0 lines
![image](https://user-images.githubusercontent.com/59607313/126936805-69790df5-69df-4452-b239-e49f3a13f6f6.png)

### 🔗 Link to the badge

https://img.shields.io/tokei/lines/github.com/KartoshkaPy/Sweet-Coin-Market?style=for-the-badge

**Comment by calebcartwright** [comment]
Presumably due to https://github.com/XAMPPRocky/tokei/issues/804

**Comment by KartoshkaPy** [comment]
The problem was fixed.
![image](https://user-images.githubusercontent.com/59607313/126965974-51849f4b-2680-4965-8da6-c7bc39f14261.png)
