### ISSUE TITLE
Shippable build not working for branches except master

### ISSUE THREAD

**Issue by mbrodala** [badges/shields#684]
I've noticed that images for Shippable builds are not working for branches except master.

Thus the following three images always yield the same result (from master):

```
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/master.svg
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/staging.svg
https://img.shields.io/shippable/54d119db5ab6cc13528ab183/production.svg
```

As soon as we trigger a build on master, all three badges change to `build | pending` and return to `build | passing` after it completes. A build on `staging` and `production` do not yield any change.

**Comment by espadrine** [comment]
I believe #711 fixed this. Please reopen if you disagree.

**Comment by mbrodala** [comment]
Works wonderfully, thanks a lot. :-)
