### ISSUE TITLE
Incorrect License (Packagist)

### ISSUE THREAD

**Issue by PHLAK** [badges/shields#685]
I'm getting the wrong license for my package on Packagist.  It's showing "proprietary" (and it was at one point) but the latest version (and master) are both published as MIT.
- Example image: https://img.shields.io/packagist/l/iodatacenters/oktasdk.svg
- Packagist page: https://packagist.org/packages/iodatacenters/oktasdk ([json](https://packagist.org/packages/iodatacenters/oktasdk.json))

**Comment by modwizcode** [comment]
This appears to be fixed now.

**Comment by paulmelnikow** [comment]
If this issue recurs, please feel free to comment or reopen.
