### ISSUE TITLE
support for jarkeeper.com

### ISSUE THREAD

**Issue by netizer** [badges/shields#686]
As far as I know currently no service is supported that would show info about dependencies in a clojure project. Jarkeeper does just that. 

For example:
https://jarkeeper.com/netizer/relational_mapper

**Comment by espadrine** [comment]
Thanks for your suggestion. I notice that they support badges that seem to conform to our specification. Is there a functionality that you feel is lacking, that you would like Shields.io to support?

**Comment by netizer** [comment]
I think right now their badges look pretty cool. When I created this pull request it wasn't the case.

**Comment by espadrine** [comment]
I am glad you like it now!
