### ISSUE TITLE
github tag badges no longer showing pre-release tags

### ISSUE THREAD

**Issue by groggemans** [badges/shields#688]
Since a few days github tag badges no longer show tags marked as "pre-release" (or tags without release info following a pre-release tag). Only tags marked as normal releases are shown (or tags following them).

Any idea what's going on?

**Comment by groggemans** [comment]
Update;

It seems the pre-releases aren't the problem. The problem is in the tag names!

Works:
- `v1.0.0`

Does not work
- `v1.0.0-rc1`
- `v1.0.0-Beta`
- `v1.0.0-Alpha`

**Comment by espadrine** [comment]
Could you help me pinpoint the problem by giving me a link to a faulty badge?

Badges related to versions have implementation nastiness in them, because I have to detect whether versions need to be ordered according to semver, PHP's custom system, a generic version detection I wrote to handle most cases, and, as the last resort, ASCII ordering. I need more information to know which layer is impacted.

**Comment by groggemans** [comment]
https://img.shields.io/github/tag/ellipsis/ellipsis-compiler.svg

Current tag for the badge is 'v0.0.2-Alpha', hope this helps!

**Comment by chrisfilo** [comment]
I can confirm this bug.

**Comment by ShyPixie** [comment]
Would not this be expected behavior? Pre-releases are not releases.
The tag named v1.0.0 works because it's not a pre-release name.

May need a new badge for pre-releases.

**Comment by sfdeveloperhub** [comment]
It would be great to have pre-release badges. Interested to hear some updates on this one.

**Comment by paulmelnikow** [comment]
Would someone like to dig into this and open a PR?

**Comment by groggemans** [comment]
Had a quick look and it's no longer working as before because the API no longer returns pre-releases when requesting the latest release. (https://developer.github.com/v3/repos/releases/#get-the-latest-release)

@paulmelnikow Just tested a successful fix. My idea is to make `/github/release/user/repo.svg` work for all releases, and add a new API endpoint `/github/release/user/repo/full.svg` that only works for full releases. Would that be ok?

**Comment by paulmelnikow** [comment]
Returning the pre-releases by default seems reasonable (though not returning draft releases).

Do you see a need for a badge that excludes prereleases? I could see wanting "latest stable release", though a release could be non-prerelease without being stable.

**Comment by paulmelnikow** [comment]
By the way, thanks for looking into this! Would be great to resolve this, one way or another.

**Comment by groggemans** [comment]
Pre-releases are often not intended for regular end-users. So defaulting to full releases only seems a good idea.

Projects targeted at devs or labels for technical sites like GitHub can then use the `all` endpoint which provides pre-release support.

I'll make some time this evening to open a PR.

**Comment by paulmelnikow** [comment]
Makes sense, I'm fine with that.

**Comment by groggemans** [comment]
@paulmelnikow PR #959
