### ISSUE TITLE
Number of commits between two GitHub commits/tags (1-indexed)

### ISSUE THREAD

**Issue by ghost** [badges/shields#6901]
:clipboard: **Description**

- **Which service is this badge for?** GitHub
- **What sort of information should this badge show?**
  [![Commits](https://img.shields.io/badge/dynamic/json?style=flat-square&label=Commits&logo=git&query=%24.total_commits&logoColor=ffffff&labelColor=212121&color=0093ed&url=https%3A%2F%2Fapi.github.com%2Frepos%2FSNDST00M%2Fmaterial-dynmap%2Fcompare%2Fv0.5.0...v0.6.0)](https://img.shields.io/badge/dynamic/json?style=flat-square&label=Commits&logo=git&query=%24.total_commits&logoColor=ffffff&labelColor=212121&color=0093ed&url=https%3A%2F%2Fapi.github.com%2Frepos%2FSNDST00M%2Fmaterial-dynmap%2Fcompare%2Fv0.5.0...v0.6.0)

:link: **Data**

- **Is there a public API?** Yes
- **Does the API requires an API key?** No
- **Link to the API documentation.**
  https://api.github.com/repos/SNDST00M/material-dynmap/compare/v0.5.0...v0.6.0 (total_commits)
  

:microphone: **Motivation**

Counting commits in release descriptions, with a link to the actual commits.

**Comment by chris48s** [comment]
The issue with doing this via the v3/REST API is that if there are many commits between Tag A and Tag B the output will be paginated and we might have to make many HTTP requests to count them. Another approach would be to use the v4/GraphQL API and make a request like this:

```gql
query {
  first: repository(owner:"SNDST00M", name:"material-dynmap") {
    object(expression:"v0.5.0") {
      ... on Commit {
        history {
          totalCount
        }
      }
    }
  }
  second: repository(owner:"SNDST00M", name:"material-dynmap") {
    object(expression:"v0.6.0") {
      ... on Commit {
        history {
          totalCount
        }
      }
    }
  }
}
```

That would return an object like

```json
{
  "data": {
    "first": {
      "object": {
        "history": {
          "totalCount": 93
        }
      }
    },
    "second": {
      "object": {
        "history": {
          "totalCount": 106
        }
      }
    }
  }
}
```

and we could use the difference between the two totals to give us the difference with only one request regardless of the number of commits. There is a `GithubAuthV4Service` for working with the GraphQL API if anyone is interesting in working on this.

**Comment by SNDST00M** [comment]
That begs the question, how did Github determine the number of commits here:

https://github.com/microsoft/vscode/compare/1.58.0...1.59.0

**Comment by chris48s** [comment]
Aah. We wouldn't actually need to page through and count the commits with the REST API call. The `total_commits` field knows all. :facepalm: The v3/REST API call will work fine :+1:

**Comment by PaulaBarszcz** [comment]
I'd like to pick this one up, thanks for the analysis @chris48s  :)
