### ISSUE TITLE
Weird buttons + Pull Request

### ISSUE THREAD

**Issue by mcccs** [badges/shields#693]
On this [page](http://shields.io/#social) Fork, Star etc. and Donate buttons are weird. Here are the exact buttons:

<img src='https://img.shields.io/github/forks/badges/shields.svg?style=social&label=Fork?maxAge=2592000' alt=''/> 

<img src='https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Star?maxAge=2592000' alt=''/>

 <img src='https://img.shields.io/github/watchers/badges/shields.svg?style=social&label=Watch?maxAge=2592000' alt=''/> 

<img src='https://img.shields.io/github/followers/espadrine.svg?style=social&label=Follow?maxAge=2592000' alt=''/>

<a href='https://www.gratipay.com/Shields/'><img src='https://img.shields.io/gratipay/Shields.svg?style=social&label=Donate?maxAge=2592000' alt='Donate to us!'/></a>

Fork's weird code: (line 539, index.html)

```html
<td><img src='https://img.shields.io/github/forks/badges/shields.svg?style=social&label=Fork?maxAge=2592000' alt=''/></td>
```

Donate's weird code: (line 956, index.html)
```html
<a href='https://www.gratipay.com/Shields/'><img src='https://img.shields.io/gratipay/Shields.svg?style=social&label=Donate?maxAge=2592000' alt='Donate to us!'/></a>
```

Confirmed this bug? [Click me](https://github.com/badges/shields/compare/master...mcccs:patch-1) to fix weird looking lines, ~~or [click me](https://github.com/badges/shields/compare/master...mcccs:patch-2) if  you want to remove maxAge from all lines in this file~~ The problem is not maxAge, problem is maxAge doesn't work on these buttons.

**Comment by espadrine** [comment]
The 89affa4 commit is responsible, as @fordhurley noticed. The backstory is that I implemented three different approaches in parallel to see which one worked best, and I implemented `?` detection in two of them. I thought I had already fixed it!
