### ISSUE TITLE
hit-counter request

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [badges/shields#6933]
:clipboard: **Description**

:link: **Data**

:microphone: **Motivation**

**Comment by ELEVENStudio-Main** [comment]
Description:
Count the numbers the website is visited.
eg. Google | 1.8k
Data:
I don't know.
Motivation:
Any hit-counter currently are too slow.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close this. If additional data becomes available please feel free to share and we will reconsider.

Shields serves up badges in SVG or raster format, and those badges display text that reflects a point-in-time value from when the badge was served. The badges themselves are neither dynamic nor interactive, and the textual values that go into them have to be pulled from some upstream system of record (a platform or service like TravisCI or GitHub).

Shields could certainly provide a badge which displayed a point-in-time metric of the number of hits, but that number would have to be fetched from _somewhere_, and accessible via REST. You would need to provide the details of a service or platform that would meet those criteria in order for this request to be actionable, and the absence of that critical information is why I'm going to close for now.
