### ISSUE TITLE
Badge text suddenly white

### ISSUE THREAD

**Issue by TobiasBg** [badges/shields#6936]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Starting yesterday (August 21), badge text suddenly is white instead of black (on white background).

I could imagine that this is related to the `brightnessThreshold` change in https://github.com/badges/shields/commit/e8c78d55b3ffb767e7b6ff056cac77c149a979c9 maybe.

### 🔗 Link to the badge

https://img.shields.io/github/v/release/arduino/arduino-ide?color=white&label=&style=flat-square

**Comment by chris48s** [comment]
Fix PR open at https://github.com/badges/shields/pull/6939
