### ISSUE TITLE
Badges not working for Ansible Galaxy

### ISSUE THREAD

**Issue by elboletaire** [badges/shields#694]
Since a few weeks ago the ansible galaxy badges appear all as `errored`:

[![Ansible Role](https://img.shields.io/ansible/role/3078.svg?style=flat-square)](https://galaxy.ansible.com/list#/roles/3078)
[![Ansible galaxy](https://img.shields.io/ansible/role/5518.svg?style=flat-square)](https://galaxy.ansible.com/list#/roles/5518)
[![Ansible galaxy](https://img.shields.io/ansible/role/5517.svg?style=flat-square)](https://galaxy.ansible.com/list#/roles/5517)

**Comment by espadrine** [comment]
It seems to have been fixed. If you disagree, don't hesitate to reopen the issue.

**Comment by abn** [comment]
Looks like it got resolved again. O_o
