### ISSUE TITLE
Reconsider message text and color for VS Marketplace that haven't been rated by anyone

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#6957]
Our badges for extensions that haven't received any ratings currently display with a value of `0.0/5 (0)` with a red message color. I don't recall if this was done intentionally when we added these badges, nor whether it's consistent with other such rating badges. However, I'm increasingly feeling this is the wrong behavior, because it conflates the absence of data (positive or negative) in a way that connotes an error/issue/failure as our red coloring is used in other badges, and I want to propose we change the message to be something like `unrated`, `not rated`, etc. and the color to be more like `inactive` or `informational`

For context, it's fairly common in my experience for extensions to have no, or minimal, reviews left on that marketplace. For example, the 21st most installed extension with over 8.5 million installs only has 2 reviews:

https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency
https://img.shields.io/visual-studio-marketplace/r/vscjava.vscode-java-dependency
![](https://img.shields.io/visual-studio-marketplace/r/vscjava.vscode-java-dependency)

I feel like this is a source of friction for maintainers of new extensions because of the negative connotations of the current badge and the impact of those connotations on potential consumers of their extension. However, it's also not something that necessarily goes away over time after an extension gains in age and popularity. For example, there's definitely popular extensions which have been around a while that have never received any reviews either. Few quick examples:

https://marketplace.visualstudio.com/items?itemName=mindaro-dev.file-downloader
https://img.shields.io/visual-studio-marketplace/r/mindaro-dev.file-downloader (187k installs)
![](https://img.shields.io/visual-studio-marketplace/r/mindaro-dev.file-downloader)

https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-yaml
https://img.shields.io/visual-studio-marketplace/r/docsmsft.docs-yaml (132k installs)
![](https://img.shields.io/visual-studio-marketplace/r/docsmsft.docs-yaml)

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit-nightly
https://img.shields.io/visual-studio-marketplace/r/ms-vscode-remote.remote-ssh-edit-nightly (98k installs)
![](https://img.shields.io/visual-studio-marketplace/r/ms-vscode-remote.remote-ssh-edit-nightly)

I do of course realize that popularity and install count are separate and distinct from ratings, and I'm not suggesting one should influence the other. My perspective, however, is that I think our existing ratings badge gives a specious, negative impression on a platform where the _absence_ of data is relatively common both for new/unpopular extensions as well as established/popular ones, and that at least warrants a discussion on changing what our badges look like in this not-uncommon scenario.

**Comment by PyvesB** [comment]
> we change the message to be something like `unrated`, `not rated`, etc. and the color to be more like `inactive`

Agreed, sounds good.

**Comment by calebcartwright** [comment]
Cool, updating the labels accordingly :+1:
