### ISSUE TITLE
GitHub Accept header is not set as intended

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6960]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

We attempt to set the `Accept` header for GitHub API calls here:
https://github.com/badges/shields/blob/be3fa207b5883eddfde1ffb5518bba806c6d3670/services/github/github-api-provider.js#L181

However, two lines below that line of code, we merge options that were passed in the `request` function call:
https://github.com/badges/shields/blob/be3fa207b5883eddfde1ffb5518bba806c6d3670/services/github/github-api-provider.js#L183

The passed in headers will contain the default of the base class (`application/json` for both `BaseGraphqlService` and `BaseJsonService`). In other words, `application/vnd.github.v3+json` is systematically overwritten.

For the GraphQL API, this bug is not a bad thing, as we wouldn't want to be setting an `application/vnd.github.v3+json` header anyway. For the other JSON endpoints, we're slightly deviating from GitHub's recommendations, and there's a theoretical chance that things could break if they changed the default version of the API in the future. Unsure how likely that is though, especially as they seem to be pushing the GraphQL API nowadays.

### 💡 Possible Solution

Definitely nothing major going on here, but probably best to avoid some head scratching in the future due to this confusing state of things.

We could either:
* override the defaults from `BaseJsonService` here: https://github.com/badges/shields/blob/master/services/github/github-auth-service.js. However, having them in _github-api-provider.js_ makes more sense than _github-auth-service.js_.
* remove the `application/vnd.github.v3+json` line entirely as it won't change from today's behaviour anyway. We can always revisit in the future if we have specific `Accept` header needs in the future. This may well be the pragmatic thing to do.

**Comment by chris48s** [comment]
One thing we need to be mindful of here is that we can still override the Accept header if needed.

Sometimes GitHub introduce a preview for a new API but require a special Accept header to enable it which we do occasionally use. For example, the actions API was `application/vnd.github.antiope-preview+json`. I don't think either of your suggestions would prevent that but it might be useful to include a test case with a service extending `GithubAuthV3Service` and setting a custom Accept header just to nail that down.
