### ISSUE TITLE
Add MPR badge

### ISSUE THREAD

**Issue by q60** [badges/shields#6961]
:clipboard: **Description**

add MPR package badges like AUR has.

![image](https://user-images.githubusercontent.com/61933599/131249270-9536358e-965e-46ec-ab87-58742e427d55.png)

it shouldn't be hard, because it's just the same webpage like AUR, but in different colors and with different URL. it's made for Debian and derivatives.

MPR: https://mpr.hunterwittenborn.com/

package example: https://mpr.hunterwittenborn.com/packages/disfetch/

i tried to do something myself via dynamic badges, but it just doesn't work with correct URL and correct XPATH.

this URL: https://mpr.hunterwittenborn.com/cgit/aur.git/?h=disfetch

and these XPATHs:

+ `(//html/body/div[@id="cgit"]/div[@class="content"]/table[@class="list nowrap"]/tbody/tr/td/a)[1]/text()`

+ `(//html/body/div/div/table/tbody/tr/td/a)[1]/text()`

+ `//html/body/div/div/table/tbody/tr/td/a`

+ `//div/div/table/tbody/tr/td/a`

each of them yields <ins>no result</ins>

:link: **Data**

you can just copy script for AUR and adapt it, so it works with MPR

:microphone: **Motivation**

MPR is pretty new project, but it becomes more popular and it would be nice to see MPR badges.

**Comment by calebcartwright** [comment]
I'm going to close this for now. We do not add badges that scrape html, and accordingly the AUR badges, mentioned as a comparison, don't scrape html either; we get AUR data via an API call so there's nothing to "copy".

In order for this request to become actionable, we'd want to see the service increase in popularity and provide a standard JSON (or XML, but not preferred) API that provides the underlying package metadata. Please feel free to follow up if/when that occurs!

**Comment by hwittenborn** [comment]
> we get AUR data via an API call

You should also be able to do so from the MPR just fine, it actually uses the same backend platform as the AUR, so virtually everything should transfer over just fine.

P.s. I'm the maintainer of the MPR project; I thought I'd just clear up that misconception here.

**Comment by calebcartwright** [comment]
@hwittenborn do you have a MPR API documentation link that can be shared, or at a minimum some example API calls?

**Comment by hwittenborn** [comment]
@calebcartwright Should be exactly the same as for the AUR, just with a different base URL.

i.e.

- https://mpr.hunterwittenborn.com/rpc/?v=5&type=info&arg[]=makedeb (returns results for `makedeb`)
- https://mpr.hunterwittenborn.com/rpc/?v=5&type=info&arg[]=makedeb&arg[]=makedeb-beta (returns results for `makedeb` and `makedeb-beta`)

**Comment by hwittenborn** [comment]
@calebcartwright Any update on this?

Honestly I think it might just work out better if Shields would just allow a custom endpoint for the AUR to be provided, then I think this any any future projects that use the AUR codebase could just start using this immediately.

**Comment by chris48s** [comment]
> Any update on this?

No. If anyone plans to work on it, they'll post here or submit a PR. Shields is an open contribution community project.

In general a pretty good heuristic for us as maintainers is that if we're going to take on the maintenance of code for a new service badge at this point then we'd like to see that there is at least enough popularity/interest in the service that one person in the community is willing to submit a PR to add the badge. Its not a particularly high bar, but also it is frequently not met.

In terms of implementation, sharing helper code with the AUR integration would be one valid way to address this if anyone is interested. Allowing AUR to take a registry param might be another a valid way to address this. It is an approach I suggested for Thunderbird Add-ons in https://github.com/badges/shields/issues/6994#issuecomment-914544264 This would seem particularly appealing if there are other registries using the same API. Do you know of any other registries that are API compatible with AUR.

**Comment by calebcartwright** [comment]
:100: agree with Chris (apologies this slipped through my notifications list). The only concern I'd have with the query param path would be whether or not it's obvious and transparent to all end users that their registry has precise API compatibility. It's definitely a common, and often preferable, path for badges that can target multiple instances (e.g. Jenkins, Sonar, GitLab, etc.) but in those cases it's also completely obvious to the user that it's just another instance of the tool; they don't have know the underlying API surface that Shields consumes and whether other targets have that same contract.

**Comment by hwittenborn** [comment]
> Do you know of any other registries that are API compatible with AUR.

Besides the MPR I don't think any other project is using the AUR codebase, no.

What exactly was your concern @calebcartwright? I couldn't figure out what you meant :P

The only reason I can't do much of a PR right is I haven't gotten a chance to learn JavaScript yet, so I wouldn't know much of what to do. I'm sure I could spend some time on learning it, but that would require quite a bit of time that I'd really like to focus on other things, or at least right now.

**Comment by calebcartwright** [comment]
> What exactly was your concern @calebcartwright? I couldn't figure out what you meant :P

I'm asking clarifying questions that would, in my opinion, play a factor in the solution, particularly related to the user experience of Shields users.

One of the proposed solutions, as I understand it, is for our existing AUR badges to take a query parameter that allows the user to provide the link for an AUR endpoint (which would be a functionally required query parameter for MPR). It's not clear to me whether one of our users who is a maintainer of a package that's hosted on MPR will find it immediately clear that they should use our AUR badge route and or search/browse on our shields.io website to generate a badge for their MPR-hosted package.

My question is whether a reasonable MPR consumer would view/expect that to be a different registry of sorts, regardless of the fact that under the proverbial hood it happens to use the same API.

As an example, if the GitLab API uri path and response object for repo tags was identical to the GitHub API uri path and response object for tags with the only difference being the base URL, would it make sense for Shields to expose a "GitHub Tag" badge that GitLab users can also use by selecting the GitHub badge and then providing a query parameter for GitLab.

I'd argue pretty strongly that hypothetical would be a terrible idea :laughing: I'm not an Arch user, so I'm just not aware of how similar/different the AUR/MPR would be comparatively (i.e. are they basically synonymous, as divergent as say deb vs. snaps or rpm vs flatpack, somewhere in between, etc.)

**Comment by hwittenborn** [comment]
Gotcha, that makes more sense :)

The entire ecosystem around MPR is pretty Arch Linux-centric, and most of the users know about the AUR and the tools required to build packages from the AUR. The MPR and it's installation tools are actually _all_ forks of tools that originated in the Arch Linux ecosystem, providing further resemblance to there as well.
