### ISSUE TITLE
Badge color dynamic by percentage

### ISSUE THREAD

**Issue by lucasrusso95** [badges/shields#6962]
:clipboard: **Description**

Badge color dynamic by percentage

:link: **Data**

:microphone: **Motivation**

I need a api that i put 10% and return the color in code coverage.

**Comment by calebcartwright** [comment]
It's not _entirely_ clear what you're asking for given the dearth of information, however, I'd imagine what you're seeking could be handled with our [Custom Endpoint Badge](https://shields.io/endpoint).

As such I'm going to go ahead and close, but please feel free to follow up with the relevant information if you still feel there's a non-custom endpoint solution you have in mind.
