### ISSUE TITLE
Gemnasium badge fails (sometimes)

### ISSUE THREAD

**Issue by DannyBen** [badges/shields#699]
Every now and then the Gemnasium badge shows a gray "invalid".

This is sometimes working, and sometimes not. Saw it as "invalid" more than once.

This is the URL I am using:
[![Gemnasium](https://img.shields.io/gemnasium/DannyBen/bobkit.svg?style=flat-square)](https://gemnasium.com/DannyBen/bobkit)

Saw this issue was mentioned and closed in the past in #591

**Comment by gravis** [comment]
Hi, we found a node of our cluster responding with 502 errors, and not being detected after several days, causing some badges to fail rendering. It was fixed, and you should not see intermittent "invalid" badges now. I think you can close this, and reopen if the problem occurs again.
Thanks, and sorry for that!

**Comment by DannyBen** [comment]
Excellent, thanks.
