### ISSUE TITLE
💡 Badge Request: ghcr.io Docker

### ISSUE THREAD

**Issue by mrclfd** [badges/shields#6997]
- For **ghcr.io Docker** services like [this](https://ghcr.io/mrclfd/lamphor:latest)
- Information type:
`"download by tag | {download by tag}"`, `"total download | {total download}"`, `"image size | {size}MB"`, `"version | {version}` or `version | v{version}`"

**Comment by chris48s** [comment]
Thanks. This is a valid feature request, but I'm going to close as I think it is a duplicate of https://github.com/badges/shields/issues/5594
Lets track it there

**Comment by mrclfd** [comment]
oh sorry, thanks Sur
