### ISSUE TITLE
Add Username and Repo Name to Shield Creation fields

### ISSUE THREAD

**Issue by oscarmorrison** [badges/shields#701]
As a new user to Shields.io badges it is not obvious where in the URL 
should be the username and the repository name. 
It would be helpful to add fields such as 

**Github User Name**
**Repo Name**

to Shield Creation form such as below:
(obviously this would be different field names per badge)

![Screenshot](http://i.imgur.com/JIAQ3Fd.png)

**Comment by oscarmorrison** [comment]
CC @espadrine

**Comment by nnadeau** [comment]
+1

**Comment by paulmelnikow** [comment]
Related to #466.

**Comment by tooomm** [comment]
See https://github.com/badges/shields/pull/1331#issuecomment-349474676 and following:
**Request to add a `direct link to generated/shown custom image` and a `custom parameter` field.**

**Comment by paulmelnikow** [comment]
Let's track this in #2496.
