### ISSUE TITLE
pypi downloads: invalid

### ISSUE THREAD

**Issue by casperdcl** [badges/shields#7022]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

`/pypi/:period/:packageName` shows "invalid" for all packages

### 🔗 Link to the badge

![dm-tqdm](https://img.shields.io/pypi/dm/tqdm.svg)

### 💡 Possible Solution

Maybe due to https://pypi.org/pypi/{package}/json returning `-1` for download counts?

**Comment by calebcartwright** [comment]
Thanks for reaching out, though it seems to have already sorted itself. If the upstream API was returning a negative value then that would explain an `invalid..` type of message, as that's obviously indicative of an issue in the data (at least I can't imagine how a package would have negative one downloads :smile:)

Will leave this open for a while in case it's an intermittent issue, but as of this moment there's no action for us to take

**Comment by calebcartwright** [comment]
Recurrence
![image](https://user-images.githubusercontent.com/13042488/133544254-1b05c262-7a9b-4b1e-8781-e9070d7c3eed.png)

**Comment by Lex-2008** [comment]
can confirm, still happening. I assume shields.io developers are aware of that, but worth mentioning that pypi.org themselves don't publish download numbers, as per this SO answer: https://stackoverflow.com/a/38102521/12242716

Instead, https://pypistats.org/about#downstream claim that they provide download numbers for shields.io, and for me they quite often say "429 RATE LIMIT EXCEEDED".

**Comment by chris48s** [comment]
Indeed. We don't get our numbers from pypi - they don't serve download stats via their API any more. Our numbers come from pypistats.

It is possible we are hitting 429s - there do seem to be other users hitting this at the moment https://github.com/crflynn/pypistats.org/issues/42 but we don't have logging for cleanly handled errors. If I catch it at a time when we're seeing this error I'll try to confirm it. The ability to log certain upstream error codes (like 429) to sentry but serve an error badge cleanly would probably be useful though.. hmm :thinking: 

Pypistats have had problems with abuse in the past https://github.com/crflynn/pypistats.org/issues/20 so probably introduced rate limiting for _good reasons_ .

**Comment by Sodium-Hydrogen** [comment]
pepy.tech may be an alternative while pypistats.org is having issues with their rate limiter.

**Comment by foxwhite25** [comment]
> pepy.tech may be an alternative while pypistats.org is having issues with their rate limiter.

pepy.tech have a much different number than pypistats.org, pepy.tech shows my project having 8k download/ month, where as pypistats.org shows 1k

**Comment by Sodium-Hydrogen** [comment]
>pepy.tech have a much different number than pypistats.org, pepy.tech shows my project having 8k download/ month, where as pypistats.org shows 1k

I believe pypistats.org excludes mirrors and tries to get the most accurate count possible while pype.tech just publishes the raw data without extra filtering.

**Comment by Gbox4** [comment]
> pepy.tech have a much different number than pypistats.org, pepy.tech shows my project having 8k download/ month, where as pypistats.org shows 1k


Might not be perfect, but certainly works for me. Certainly better than pypistats returning nothing :P

**Comment by hugovk** [comment]
The https://pepy.tech API is `https://api.pepy.tech/api/projects/[project]`

For example: https://api.pepy.tech/api/projects/requests

```json
{"id": "requests", "total_downloads": 3450302764, "downloads": {"2022-02-02": 5279705, "2022-02-01": 5343174, "2022-01-31": 5308588, "2022-01-30": 3278722, "2022-01-29": 3413606, "2022-01-28": 5010187, "2022-01-27": 5297114, "2022-01-26": 5259445, "2022-01-25": 5492501, "2022-01-24": 5147523, "2022-01-23": 3313044, "2022-01-22": 3403899, "2022-01-21": 5169011, "2022-01-20": 5356003, "2022-01-19": 5270038, "2022-01-18": 5058865, "2022-01-17": 4611753, "2022-01-16": 3185163, "2022-01-15": 3281521, "2022-01-14": 4911317, "2022-01-13": 5335780, "2022-01-12": 5329281, "2022-01-11": 5210965, "2022-01-10": 5038494, "2022-01-09": 3257114, "2022-01-08": 3291420, "2022-01-07": 4830933, "2022-01-06": 5106647, "2022-01-05": 5079085, "2022-01-04": 4860283}}
```

**Comment by Sodium-Hydrogen** [comment]
If you want to use pepy.tech but also have the styles from shields.io you can use shields dynamic option.

Ex: ![shields.io dynamic](https://img.shields.io/badge/dynamic/xml?style=for-the-badge&color=green&label=downloads&query=%2F%2F%2A%5Blocal-name%28%29%20%3D%20%27text%27%5D%5Blast%28%29%5D&suffix=%2Fmonth&url=https%3A%2F%2Fstatic.pepy.tech%2Fbadge%2Frequests%2Fmonth)

Since they only provide daily statistics from the api I put the url of the badge they generate into the url `https://static.pepy.tech/badge/requests/month` used type `xml` and set the following query `//*[local-name() = 'text'][last()]`

Then all I had left to get the badge looking the way I wanted was set the label, color, style, and suffix

**Comment by Sodium-Hydrogen** [comment]
Upstream fixed the rate limiter

crflynn/pypistats.org#42

**Comment by calebcartwright** [comment]
Closing as this indeed seems to be working again, but if there's any immediate term recurrence please post here so we can reopen
