### ISSUE TITLE
Gemnasium is now using triplets as project identifiers

### ISSUE THREAD

**Issue by gravis** [badges/shields#708]
While `[org]/[repo]` is still valid for all github projects, please note that we now also support bitbucket, and urls are gaining a new part: `[SOURCE]/[org]/[repo]`. We currently only support `github.com` and `bitbucket.org` as sources, but this list will be extended in the future.

**Comment by PyvesB** [comment]
As Gemnasium will soon be shutting down (see #1524 and #1523), this issue is no longer relevant, therefore closing it.
