### ISSUE TITLE
Incorrect number shown

### ISSUE THREAD

**Issue by mathiasrw** [badges/shields#709]
Thanks for a great service. 

The projekt AlaSQL has 72 open issues with label "! Bug"
https://github.com/agershun/alasql/labels/%21%20Bug (not really proud of that many - but thats not the important for this issue)

When I generate a badge for the same lable it displays "30": 
https://img.shields.io/github/issues/agershun/alasql/%21%20Bug.svg

Question: 
- Could this be caused because of a "!" in the name?

**Comment by espadrine** [comment]
Thanks for reporting!

It may be a matter of GitHub paging their API; this shows 30 entries: https://api.github.com/repos/agershun/alasql/issues?labels=!%20Bug.

It would be nice if the count was specified on https://developer.github.com/v3/issues/labels/.

[GitHub Search](https://developer.github.com/v3/search/#search-issues) can do it, but it is rate-limited to 30 req/s.

**Comment by mathiasrw** [comment]
Makes sense. 

Thanks for fast response.
