### ISSUE TITLE
Support customization for Shippable badges

### ISSUE THREAD

**Issue by harryi3t** [badges/shields#710]
We (Shippable) received a request https://github.com/Shippable/support/issues/2461 for customizing the badges that we provide.

For this extend the logic of the Shippable integration to use query parameters.
## Query parameters to support

|    Key   		 	  |                Purpose                   |Default Value|
|---------------------------|------------------------------------------|-------------|
|   label		          |       left text in badge                 | build         |
|   colorA	                  | left side color in badge  	        | ![#555555][555555]      |
|   successLabel 	  | label when build is passing     		 | passing   |
|   successColor 	  | color when build is passing     		 | ![#44CC11][44CC11]   |
|   failLabel		  | label when build is failing     		 | failing     |
|   failColor		  | color when build is failing     		 | ![#DC5F59][DC5F59]   |
|   cancelledLabel	  | label when build is cancelled   		 | cancelled   |
|   cancelledColor	  | color when build is cancelled   		 | ![#6BAFBD][6BAFBD]   |
|   unstableLabel	  | label when build is unstable     		 | unstable    |
|   unstableColor	  | color when build is unstable     		 | ![#CEA61B][CEA61B]   |
|   pendingLabel	  | label when build is pending     		 | pending     |
|   pendingColor	  | color when build is pending     		 | ![#5183A0][5183A0]   |
|   skippedLabel	  | label when build is skipped     		 | skipped     |
|   skippedColor	  | color when build is skipped     		 | ![#F8A97D][F8A97D]   |
|   noBuildLabel	  | label when there is no build    		 | none        |
|   noBuildColor	  | color when there is no build    		 | ![#A1ABAB][A1ABAB]   |
|   inaccessibleLabel | label when Shippable API is inaccessible | inaccessible|
|   inaccessibleColor | color when Shippable API is inaccessible | ![#A1ABAB][A1ABAB]   |

[44CC11]:https://cloud.githubusercontent.com/assets/5207331/15141458/ae3a99da-16bd-11e6-9132-bb46875d3fe7.png
[555555]:https://cloud.githubusercontent.com/assets/5207331/15141509/f8db5d12-16bd-11e6-8e84-8498ef69a596.png
[DC5F59]:https://cloud.githubusercontent.com/assets/5207331/15141552/3741edf0-16be-11e6-8922-9ae46d633f75.png
[6BAFBD]:https://cloud.githubusercontent.com/assets/5207331/15141560/4014c042-16be-11e6-8374-b62914126ba4.png
[CEA61B]:https://cloud.githubusercontent.com/assets/5207331/15141568/48feaec0-16be-11e6-84fb-b48a66a783d6.png
[5183A0]:https://cloud.githubusercontent.com/assets/5207331/15141575/4f9862f8-16be-11e6-83a8-aa9b0ec4f392.png
[F8A97D]:https://cloud.githubusercontent.com/assets/5207331/15141580/56aa568c-16be-11e6-84f5-0ea50f374fa0.png
[A1ABAB]:https://cloud.githubusercontent.com/assets/5207331/15141586/5bc93dc2-16be-11e6-8d53-ea3c434cb58b.png

**Comment by espadrine** [comment]
I believe #711 fixed this. Please reopen if you disagree.
