### ISSUE TITLE
Update documentation for GitHub Workflow Status Badges

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7102]
Our GitHub Workflow Status badges use an upstream GitHub API endpoint that requires we utilize the Workflow _name_. [GitHub provides native badges for Workflow status](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) which requires users specify the _**file**_ name that contains the workflow definition.

For one reason or another, many of our users assume that Shields also wants the file name parameter, and are then confused when our badges show 404/not found type messages (e.g. #6593, #6255)

I anticipate this will continue to be a recurrent issue for some, but it'd likely help avoid some confusion if we extended the modal badge window documentation for these badges to stress this. We could consider changing the parameter name to something more explicit too (e.g. `workflow` --> `workflowName`).

The text that displays is configured via the `documentation` key on each example in the service class definition, some of the example listings for the Worklow Status badge class linked below for reference. We have a default `documentation` value for all our GitHub badges, so any updates/augmentation we make to the Workflow badge examples would need to be an extension that retained the standard GitHub help text and added additional info

https://github.com/badges/shields/blob/4ad822c42ee82cdebeee6d63d2e245e5d387946f/services/github/github-workflow-status.service.js#L27-L56

**Comment by chrysillala** [comment]
Hi @calebcartwright I would like to work on this issue, could you provide more details? Thanks!

**Comment by calebcartwright** [comment]
hi @chrysillala, that'd be great! 

> could you provide more details?

I feel like the issue description is already very thorough, and provides both a direct link to the location in code where the change would be made as well as the additional information that needs to be added. I'm not really sure what else I could add to that without practically writing the code myself :smile:

Do you have any specific questions or find anything unclear?

**Comment by ppizarror** [comment]
Hi, I had the same problem. From the hints provided on the website, I thought the name was the same as the .yml file. Maybe a hint or further explanation might work.

**Comment by aditya1abhinav** [comment]
Hi @calebcartwright I would like to work on this issue.

**Comment by chris48s** [comment]
This one will become irrelevant if we merge #8475
I think its best we ignore it for now as it will hopefully become a non-issue.

**Comment by chris48s** [comment]
This is now irrelevant due to https://github.com/badges/shields/issues/8671
