### ISSUE TITLE
Coverage on GitHub using ReportGenerator

### ISSUE THREAD

**Issue by mu88** [badges/shields#7103]
:clipboard: **Coverage on GitHub using ReportGenerator**

I'm calculating the code coverage of my .NET project on GitHub with [this GitHub workflow](https://github.com/mu88/BlazorFotoManager/blob/main/.github/workflows/CI.yml) using the [ReportGenerator Action](https://github.com/marketplace/actions/reportgenerator).

ReportGenerator offers the possibility to generate a code coverage report and a code coverage badge as well. But when executing the GitHub workflow and calculating these data, they are persisted as a GitHub Artifact - a ZIP file containing either the coverage report, the badge, etc. ([see this example](https://github.com/mu88/BlazorFotoManager/suites/3939193533/artifacts/98724949))

Since the coverage results are always within a ZIP file, they cannot be referenced, e. g. within a `README.md`.

:link: **Data**

Data are available via GitHub Artifacts.

:microphone: **Motivation**

More and more people are using GitHub as their CI environment as well. There are already several ways to calculate the code coverage using GitHub Actions. But there is no first-class way of display a code coverage badge.

Therefore it would be great if Shields would offer a way to display the code coverage of a GitHub workflow.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close this.

We definitely appreciate the desire for coverage badges, and I remain optimistic that as GitHub matures their product they will incorporate some native coverage reporting features like Jenkins, Azure DevOps, TeamCity, and other pipeline engines do. 

However, it's neither practical nor incumbent on Shields to solve GitHub's feature gap. We're reliant on the upstream data sources to provide the requisite data points in a standard, easily consumable manner like a Rest or GraphQL endpoint, or something like an accessible json document. We're not going to support downloads of arbitrary archive files to our servers, which we would then have to extract and process the contents.

For folks that are using GitHub Actions, the recommended/viable options for coverage badges remain:

- Utilize a coverage service, like Codecov or Coveralls
- Utilize an analysis-like service that supports code coverage, like CodeClimate or SonarCloud/Qube
- Leverage a [Custom Endpoint](https://shields.io/endpoint) that handles grabbing whatever coverage content you need
- Use our [badge-maker](https://www.npmjs.com/package/badge-maker) npm package (as a lib or cli) to generate the svgs
- If your coverage engine is capable of generating an XML or JSON report, publish that raw file (not an archive) somewhere that's directly accessible to the Shields.io service (or your self-hosted Shields server), and use one of our respective [Dynamic Badges](https://shields.io/#dynamic) to produce your badge
- Explore available Actions for dynamically generating badges, for example [cobertura-coverage-xml-badges](https://github.com/action-badges/cobertura-coverage-xml-badges) (developed by one of the Shields maintainers)
