### ISSUE TITLE
Finalize migration to squint

### ISSUE THREAD

**Issue by chris48s** [badges/shields#7161]
We've been running this four a couple of weeks and all seems to be well so far. @calebcartwright  - I had a few points swirling around in my head so I wanted to get them noted down somewhere. Can you edit this post to add any stuff that I haven't thought of to the list.

- [x] Shut down vercel app, ensure our vercel costs are zero
- [x] Update references to svg-to-image-proxy in docs:
    - https://github.com/badges/shields/blob/4a8c1d1d0fa01e5c043e172fa24614e180c7a1c3/doc/production-hosting.md
    - https://github.com/badges/shields/blob/7d452472defa0e0bd71d6443393e522e8457f856/SECURITY.md
    - https://github.com/badges/shields/blob/f4781804f612f91256f512502d9b920663d52eec/doc/self-hosting.md
- [x] Deprecate svg-to-image-proxy NPM package https://www.npmjs.com/package/svg-to-image-proxy
- [x] Archive svg-to-image-proxy repo https://github.com/badges/svg-to-image-proxy
- [x] Review/update DNS settings in Cloudflare (e.g. http -> https, caching, etc.)
- [x] Turn off the Vercel app on the svg-to-image-proxy repo (and anywhere else we've got it turned on)

**Comment by calebcartwright** [comment]
Probably need to review the DNS settings too as I think we had the Clourflare configuration largely hands off since Vercel/Now handled some of those concerns internally.

Is there a need to deprecate the package necessarily? I know we haven't exactly been keeping up with the maintenance which is arguably a good reason in and of itself; someone could always fork if they wanted to keep it going.

**Comment by calebcartwright** [comment]
Actually, after some reflection I think archiving the repo and deprecating the package is a good call. It's a small simple project that didn't need much in the way of maintenance, but we weren't even keeping the dependencies up to date so I think the archival route is the right move to reflect the fact we aren't maintaining anymore.

**Comment by chris48s** [comment]
### Cloudflare

At the moment we've got raster.shields.io set to "DNS only" in Cloudflare (i.e: no CDN). Any reason why we shouldn't switch this to "Proxied" (which would turn on downstream cache)? I guess this isn't a huge issue as we serve so little traffic but if it serves the right headers, we may as well enable it.

### Vercel

Vercel is still charging us $2.36 per month for.. something, despite the fact we're not serving any traffic from it.

![Screenshot at 2021-12-05 15-31-53](https://user-images.githubusercontent.com/6025893/144753024-278a6e69-84dd-433f-ac79-566565e7fadc.png)

We've disabled review apps, but it would be useful to completely shut this down. I had a poke about in vercel but it looks like only the account owner can disconnect the github repo or delete the app. @paulmelnikow - you're the owner on this. Are you ok to find a few mins to completely decommission that at some point before we archive the repo.

**Comment by calebcartwright** [comment]
> At the moment we've got raster.shields.io set to "DNS only" in Cloudflare (i.e: no CDN)

Correct. That was necessary with Vercel but is one of the types of things (along with http -> https redirect) I was referring to in https://github.com/badges/shields/issues/7161#issuecomment-944980522. I added the second to last checkbox to the list to track all that (` Review/update DNS settings in Cloudflare (e.g. http -> https, caching, etc.)`) but certainly feel free to adjust/break down if helpful

**Comment by chris48s** [comment]
Right yes - Vercel provided its own CDN.

- I checked and squint is forwarding the original `Cache-Control` headers so I've switched the DNS record to proxied. If we hit any issues with that we can change it it back.
- HTTP --> HTTPS redirect is covered by a page rule that applies to `*shields.io/*` so no worries there.
- I can't think of any other Cloudflare stuff we need to check. Can you?

**Comment by calebcartwright** [comment]
> I checked and squint is forwarding the original Cache-Control headers so I've switched the DNS record to proxied. If we hit any issues with that we can change it it back.

Indeed, as configured here https://github.com/badges/squint/blob/8f76e6b041a3b30c26ee4819d361219382597737/src/server.rs#L22

At the time I only did it because the code was there in the original svg-to-image-proxy, but it ended up working out well

> HTTP --> HTTPS redirect is covered by a page rule that applies to *shields.io/* so no worries there.

I could've sworn I was getting responses over http at some point but certainly seeing the redirects happening now :man_shrugging: 

> I can't think of any other Cloudflare stuff we need to check. Can you?

Nope not off hand. Those were the only two so will check the box in the issue description

**Comment by chris48s** [comment]
Not sure why we left archiving https://github.com/badges/svg-to-image-proxy to mature for a year, but it is done now
