### ISSUE TITLE
Stack exchange badge no longer loads (in some cases)

### ISSUE THREAD

**Issue by rnicholus** [badges/shields#717]
While it appears to load on the shields demo page, it now times out and fails to load in a repo I maintain at  https://github.com/FineUploader/fine-uploader#readme. It was loading fine until yesterday. 

Could this be related to #699?

**Comment by rnicholus** [comment]
After a full day of not loading, it is now loading again literally 10 seconds after posting this issue :-0

**Comment by paulmelnikow** [comment]
If this issue recurs, please feel free to reopen.
