### ISSUE TITLE
Apply consistent button styling

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#7172]
As suggested in #7129, let's adopt a consistent style for the action buttons on the site, in place of the default button styles we've got in place now.

In terms of a design process, let's agree on the visual design in this thread and then once the design is approved, open a PR.

My suggestion as a starting point would be to mimic the styling of the button on the badge customizer (but without the dropdown):

<img width="214" alt="Screen Shot 2021-10-19 at 2 42 14 PM" src="https://user-images.githubusercontent.com/1487036/137971430-cfe296e4-712e-4df8-93b8-604f79b90a70.png">

**Comment by paulmelnikow** [comment]
Happy for us to remove the gradient. In terms of action-button color, I think using the azureish blue is clearer than green, in part because the color is further from the Shields badge color scheme, so it makes a clearer difference between the action buttons and the example badges. I don't think action buttons need to be green.

**Comment by Andre601** [comment]
Of course. The important part here is to just find a consistent colouring in terms of what action-type should have what colour and such. This should perhaps go after #7176 to avoid bad colour combinations or badly readable buttons.

**Comment by itsajay1029** [comment]
Hey @paulmelnikow  , can you assign me this issue so that I can get started working on it ?

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/

Closing this issue as it relates to the previous frontend
