### ISSUE TITLE
Move documentation of global query parameters to a separate page

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#7173]
As suggested in #7129:

> **Make proper documentation pages for label options**

> Having everything on one page is nice, but it also feels a bit cluttered and hard to find the option you're looking for.
Putting them into a dedicated page could also give you the option of adding extra info such as examples to it to show how the options can be used.

Agree with this. I suggest we start by adding a Customization page which includes all the styles and the query options. We could create linkable anchors so it's easy to share links to the documentation when people are asking for support. include one or more rendered example where it's helpful.

In terms of process, let's make a decision about what information will go where, then mock up the page (potentially in a draft PR), and do a quick design review after that before wrapping up the code review.

**Comment by RMeissnerCC** [comment]
Is this issue still open?

**Comment by BhaveshAnandpara** [comment]
Hey @paulmelnikow  is this Issue still open ??

**Comment by YashasviChaurasia** [comment]
@paulmelnikow I would like to work on this issue.
Thank you

**Comment by itsajay1029** [comment]
Hey @paulmelnikow  , can you assign me this issue so that I can get started working on it ?

**Comment by chris48s** [comment]
I think this one is currently totally well defined what the output should look like. Maybe this is best considered under slightly wider (re)design thinking.

**Comment by chris48s** [comment]
We have just launched a completely redesigned frontend https://shields.io/

Closing this issue as it relates to the previous frontend

The new frontend documents all the global query params on every badge builder page
