### ISSUE TITLE
add "maintenance status" badge e.g. "actively-developed" vs "deprecated" vs ...

### ISSUE THREAD

**Issue by jokeyrhyme** [badges/shields#7242]
:clipboard: **Description**

Howdie, thanks so much for sharing this project and service

I have begun to deprecate some older projects and it occurred to me that some sort of "maintenance status" badge would be nice to have

Rust crates have this concept ( https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section ) with the following options:

 - `actively-developed`: New features are being added and bugs are being fixed.
 - `passively-maintained`: There are no plans for new features, but the maintainer intends to respond to issues that get filed.
 - `as-is`: The crate is feature complete, the maintainer does not intend to continue working on it or providing support, but it works for the purposes it was designed for.
 - `experimental`: The author wants to share it with the community but is not intending to meet anyone's particular use case.
 - `looking-for-maintainer`: The current maintainer would like to transfer the crate to someone else.
 - `deprecated`: The maintainer does not recommend using this crate (the description of the crate can describe why, there could be a better solution available or there could be problems with the crate that the author does not want to fix).
 - `none`: Displays no badge on crates.io, since the maintainer has not chosen to specify their intentions, potential crate users will need to investigate on their own.

:link: **Data**

- for Rust crates, the data could be fetched from the Cargo.toml file
- however, as this is very human/social information, I think it's probably best if it wasn't automatic, but hardcoded as part of the badge's text / URL

:microphone: **Motivation**

Beyond marking projects as "deprecated", I think this type of badge would be useful for projects in any of the above listed stages of a project's lifecycle

**Comment by calebcartwright** [comment]
Have you taken a look at our existing maintenance status badge? It doesn't use the exact literals, but it's targeted for the same goal.

Beyond that existing badge, I think any additional static-badge type requests (e.g. the not-parsing-cargo-manifest-route) would be best left to the individual user to leverage our existing static badge capability,

Static badge route:
https://img.shields.io/badge/maintenance%20status-deprecated-red
![](https://img.shields.io/badge/maintenance%20status-deprecated-red)

https://img.shields.io/badge/maintenance%20status-actively%20developed-brightgreen
![](https://img.shields.io/badge/maintenance%20status-actively%20developed-brightgreen)

Maintenance badge route:
https://img.shields.io/maintenance/yes/2021
![](https://img.shields.io/maintenance/yes/2021)

https://img.shields.io/maintenance/yes/2018
![](https://img.shields.io/maintenance/yes/2018)

**Comment by chris48s** [comment]
The other one that might be worth a look is the OSS Lifecycle badge  e.g: https://img.shields.io/osslifecycle/Teevity/ice
which looks at an `OSSMETADATA` file in a github repo like  https://github.com/Netflix/osstracker/blob/master/OSSMETADATA

**Comment by jokeyrhyme** [comment]
@calebcartwright bah, I swear I clicked through the website trying to find these, not sure how I missed them

Seems like what I'm looking for already exists, thanks so much!

I'm happy to consider this issue resolved for now, unless you'd like to keep it open to explore the automation/API side of things

**Comment by calebcartwright** [comment]
Thanks @jokeyrhyme and no worries.. I'm going to go ahead and close accordingly.

Given the rather binary nature of deprecation, I concur with your prior statement about being able to defer that determination largely to the maintainers. I don't think it would make sense to attempt to parse the Cargo.toml badges value (fwiw I actually feel like I remember an RFC or discussion somewhere about the badges getting dropped from either the site and/or the manifest). Similarly, even if the crates.io API were to surface the information, I don't think it'd be worth the extra load on the API to fetch that data point dynamically.
