### ISSUE TITLE
Observatory Mozilla on pending when results aren't fetched in a while

### ISSUE THREAD

**Issue by Macleykun** [badges/shields#7244]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When visiting my readme page i see that the observatory is pending:
[![Mozilla HTTP Observatory Grade](https://img.shields.io/mozilla-observatory/grade-score/rockraidersx.com?publish)](https://observatory.mozilla.org/analyze/rockraidersx.com)
![image](https://user-images.githubusercontent.com/26381427/140988477-00f1a1b1-8d75-4899-a0c7-7a71f5aa5a43.png)

The weird thing is, that when i was writing this issue, it didn't work (tried it with a different one aswell). But when inserting it in this issue, it seems to fetch the data again? You need to wait about a day or 3-4 until it goes back to pending.

### 🔗 Link to the badge

[![Mozilla HTTP Observatory Grade](https://img.shields.io/mozilla-observatory/grade-score/rockraidersx.com?publish)](https://observatory.mozilla.org/analyze/rockraidersx.com)

### 💡 Possible Solution

Only when i click on the button/visit the observatory URL i see the score after refreshing the readme page.

**Comment by chris48s** [comment]
One thing to be aware of is that this badge gets served with a `cache-control: max-age=120, s-maxage=120` header so our downstream cache and your browser will cache it for 2 mins so if you've viewed the badge while the job is pending and then it completes it will take a couple of mins for the badge to update. Does that explain what you're seeing?

**Comment by Macleykun** [comment]
> One thing to be aware of is that this badge gets served with a `cache-control: max-age=120, s-maxage=120` header so our downstream cache and your browser will cache it for 2 mins so if you've viewed the badge while the job is pending and then it completes it will take a couple of mins for the badge to update. Does that explain what you're seeing?

Hmm, I’m pretty sure I’ve checked the readme page/badge with an interval longer the 2 minutes

but, isn’t it strange that the badge returns to pending after a few days? No matter the cache?

**Comment by chris48s** [comment]
Right. I now see what you mean by "results aren't fetched in a while". This is basically a characteristic of the upstream service: https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#invoke-assessment It'll cache your result for 24 hours. If it doesn't have a cached result then it will initiate a new scan. I wonder if it always returns a pending result immediately, or only if the scan is taking too long to return an immediate response..

**Comment by Macleykun** [comment]
> Right. I now see what you mean by "results aren't fetched in a while". This is basically a characteristic of the upstream service: https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md#invoke-assessment It'll cache your result for 24 hours. If it doesn't have a cached result then it will initiate a new scan. I wonder if it always returns a pending result immediately, or only if the scan is taking too long to return an immediate response..

Hm, maybe. I'm sure i've included the force part correctly.
But that could perhaps be the reason, but it somehow doesn't line up all, perhaps it's best to check in a couple of days here, hoping nobody has clicked on the badge meanwhile, so that either one of us can see it being on pending, and checking it a few times with 2 mins interval.

**Comment by Macleykun** [comment]
I retract my statement!
I checked this page of mine: https://github.com/TheVoxSiren/voxsiren.net
And while i checked it, was on pending, and ivé checked about  ~15mins later, and it sure enough was showing the results!

I assume we can rather ignore the fact that'll likely need a minute or 5 after 24h to show the results :-)
Closing it now, but feel free to comment if People think otherwise!
