### ISSUE TITLE
"Compatible with matrix vX"

### ISSUE THREAD

**Issue by ShadowJonathan** [badges/shields#7245]
:clipboard: **Description**

This service is for [Matrix](https://matrix.org), an open-source and decentralised system for instant communication across multiple independent servers.

This badge would show compatibility info with a certain "Version" of matrix, [Matrix just announced v1.1](https://matrix.org/blog/2021/11/09/matrix-v-1-1-release), and plans to keep up this cadence every quarter.

These matrix versions would show that cadence, and include a heap of compatibility info.

The badge would look like `Compatible with matrix | v1.0 | v1.1 | v1.2`

:link: **Data**

There is no data to "grab" here in a uniform format, I think it'll manual entry.

:microphone: **Motivation**

This badge could help developers see at a glance which "versions" of matrix this project would be compatible with, it only needs a set intersection (i.e. only both sides need to support *one* common version) for it to be compatible.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close as non-actionable given this:

> There is no data to "grab" here in a uniform format, I think it'll manual entry.

Our service provides a few different buckets of capabilities, including what we call a static badge builder that anyone can use to create any type of badge they want, e.g.

https://img.shields.io/badge/Compatible%20with%20matrix-v1.0%20|%20v1.1-blue
![](https://img.shields.io/badge/Compatible%20with%20matrix-v1.0%20|%20v1.1-blue)

We also provide various forms of dynamic badges where our service can go fetch data from an authoritative source, and we then use that data to construct the badge to return to the user.

However, we deliberately do not provide prebuilt static/hardcoded badges. We provide the static badge builder, users can leverage that for their static/manually specified badges

**Comment by ShadowJonathan** [comment]
Thanks, I guess then the URL would be composed of;

```
https://img.shields.io/badge/Compatible with matrix-v1.0 | v1.1-blue?logo=matrix
```
