### ISSUE TITLE
Servers down? Lots of 521s

### ISSUE THREAD

**Issue by MeirionHughes** [badges/shields#725]
I've noticed that shields seems very inconsistent recently; thought it was a github issue (they show up as 404 there); but this is from shields.io site directly: 

![](http://i.imgur.com/X1KnSoS.png)

**Comment by espadrine** [comment]
You are right. One server is inaccessible on port 443 for some reason. I investigate.

**Comment by espadrine** [comment]
I had an outdated node version. It is fixed now. Thanks for raising the issue!
