### ISSUE TITLE
Cache-control header is 86400, despite setting maxAge

### ISSUE THREAD

**Issue by hermanschaaf** [badges/shields#726]
Maybe I misunderstand the limitations of the maxAge functionality, but given this:

```
curl -vk 'https://img.shields.io/badge/go_report-A+-brightgreen.svg?style=flat&maxAge=3600' 2>&1 | grep 'Cache-Control'
```

I get:

```
< Cache-Control: max-age=86400
```

where I would have expected to see 3600 there. I saw the [reasonably recent thread about caching](https://github.com/badges/shields/issues/534), but this seems like it is unrelated to Cloudflare. Am I doing something wrong (is it not supported for custom badges?), or is it a bug?

**Comment by hermanschaaf** [comment]
I found the relevant part inside the code for hosting any badge:

```
  // Cache management - the badge is constant.
  var cacheDuration = (3600*24*1)|0;    // 1 day.
  ask.res.setHeader('Cache-Control', 'max-age=' + cacheDuration);
```

(from [here](https://github.com/badges/shields/blob/0769bebfa587f012449da36223d3f78af5e65a8d/server.js#L5325-L5327))

What is the reasoning behind not supporting the maxAge parameter for this request?

**Comment by ngryman** [comment]
@hermanschaaf If the badge never changes, what the point of taking control of the cache, it will always be the same. I think they do that to alleviate server load.
