### ISSUE TITLE
Satoshi

### ISSUE THREAD

**Issue by termud** [badges/shields#7279]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

AIphan

### 🔗 Link to the badge

https://img.shields.io/endpoint?color=%C4%91%E1%BB%8F&label=AIphanbade%E2%81%B9%C2%B3&logo=AIphanbade&logoColor=%C4%91%E1%BB%8F&url=phanbade.com

**Comment by calebcartwright** [comment]
Closing because this seems like spam. If you have a real question please feel free to follow up
