### ISSUE TITLE
rainbow badge

### ISSUE THREAD

**Issue by gruppjo** [badges/shields#728]
In light of the recent events in Orlando I would very much like to express my support with a rainbow badge. This might be a great way to raise awareness for LGBTIQ\* in Open Source in general.

What do you think?

**Comment by un1versal** [comment]
A nice idea but isnt rainbow something for Gay pride

**Comment by gruppjo** [comment]
That as well: https://en.wikipedia.org/wiki/Rainbow_flag_(LGBT_movement)

**Comment by espadrine** [comment]
Thanks for the suggestion. The murders occurring across the globe, feeding on the people's fear through news reports, deserve all our spite. Their blind obsession towards those that do not conform to their idea of what humanity should look like deserves all our anger. 

The code is currently not generic enough to support having more that two sections of colors, however. We would need to discuss [a format change](https://github.com/badges/shields/blob/master/INSTALL.md#format) to support that. Maybe `"color": [list of hex colors]`?

**Comment by gruppjo** [comment]
@espadrine, sorry for the delay. That would be wonderful and opens a lot of other use-cases as well.

**Comment by paulmelnikow** [comment]
As an LGBTQ person, I'm all for our project being welcoming and showing support for LGBTQ people, and helping other projects do the same. I think a static badge might be a better way to do that than a badge background. And I think a code of conduct is probably a better step for Shields itself to take in this direction.

🏳️‍🌈🏳️‍🌈🏳️‍🌈❤️❤️❤️
