### ISSUE TITLE
Failed to load plugin 'flowtype' declared in 'BaseConfig starting dev server

### ISSUE THREAD

**Issue by chris48s** [badges/shields#7282]
To reproduce: `npm start`

```
Failed to load plugin 'flowtype' declared in 'BaseConfig »
shields/node_modules/gatsby/node_modules/eslint-config-react-app/index.js': Package subpath
'./lib/rules/no-unused-expressions' is not defined by "exports" in shields/node_modules/eslint/package.json
failed Building development bundle - 6.365s
ERROR in Failed to load plugin 'flowtype' declared in 'BaseConfig » 
```

This isn't preventing us deploying - production frontend build still works. It is just `gatsby develop` that throws. I think this was introduced in #7235 as downgrading to ESLint 7 with `npm install --save eslint@7.32.0` fixes the issue. I haven't figured out if there's a way we can fix it and keep ESLint 8, or why Gatsby needs a linter to start the dev server.

**Comment by calebcartwright** [comment]
I think I have some (vague) memories of gnarly peer dependency issues between eslint and gatsby+friends

**Comment by calebcartwright** [comment]
Do you think we should hold off on updating more dependencies for the time being? Not sure what my own thinking is on that question tbh, but wanted to ask since I imagine that the more we update the other dependencies the more difficult this may be to unwind

**Comment by chris48s** [comment]
I agree. I've submitted https://github.com/badges/shields/pull/7304 - lets merge that before we process this week's dependency bumps.

Didn't really have time for it last night but I spent a bit of time on it this evening. I was hoping updating the latest gatsby release might fix us but we need to wait for https://github.com/gatsbyjs/gatsby/pull/33785 to get sorted upstream.

**Comment by amarg26** [comment]
@chris48s  Can we have a fix for this? I have updated to the latest Eslint version. Getting too much of this message on `npm start`
