### ISSUE TITLE
Get version from monorepo sub project's package.json.

### ISSUE THREAD

**Issue by YanceyOfficial** [badges/shields#7308]
How can i get version from monorepo sub project's package.json.

{
  apps: {
     A: {
      ...
      packages.json
      ...
     },
    B: {
      ...
      packages.json
      ...
     },
  }
}

**Comment by calebcartwright** [comment]
I'm actually a bit surprised we don't already support this natively. Many of our badges already support this, including the ability to get a _dependency_ version from a nested package.json manifest in a subdirectory of a monorepo.

e.g. 
https://img.shields.io/github/package-json/dependency-version/metabolize/anafanafo/puppeteer?filename=packages%2Fchar-width-table-builder%2Fpackage.json
![](https://img.shields.io/github/package-json/dependency-version/metabolize/anafanafo/puppeteer?filename=packages%2Fchar-width-table-builder%2Fpackage.json)

In the interim, your best bet is to use the Dynamic Json badge to point to the package.json file in source and use a simple jsonpath query to grab the version from the manifest.

Adding support for the ability to specify a path to the package.json file would be pretty straightforward for anyone interested in working on this, as we'd just need to incorporate the same filename query parameter on the `GithubPackageJsonVersion` class and route that already exists on the `GithubPackageJsonDependencyVersion` class and route

https://github.com/badges/shields/blob/master/services/github/github-package-json.service.js
