### ISSUE TITLE
GitHub Workflow Status Badges Always Report Failure

### ISSUE THREAD

**Issue by ProfessorManhattan** [badges/shields#7318]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I am trying to use the GitHub workflow badge for a workflow. The issue is that it always reports as a failure even though the past 50+ times on master it is a success. The workflow I'm trying to create a badge for is:

https://github.com/ProfessorManhattan/ansible-androidstudio/actions/workflows/macOS.yml

And the badge URL is:

https://img.shields.io/github/workflow/status/ProfessorManhattan/ansible-androidstudio/macOS

Am I missing something or do these badges just not work?

### 🔗 Link to the badge

https://img.shields.io/github/workflow/status/ProfessorManhattan/ansible-androidstudio/macOS

**Comment by ProfessorManhattan** [comment]
Looks like I have to use the title instead of the workflows slug. Closing this issue.

**Comment by ProfessorManhattan** [comment]
Closing.

**Comment by calebcartwright** [comment]
> Looks like I have to use the title instead of the workflows slug. Closing this issue.

Was just posting the same :wink:
