### ISSUE TITLE
Blurry corner radius

### ISSUE THREAD

**Issue by Haroenv** [badges/shields#732]
Currently badges from shields.io are blurry/pixelated on some screens (retina). The Travis badge doesn't have this issue: 

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="90" height="20">

  <linearGradient id="a" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1" />
    <stop offset="1" stop-opacity=".1" />
  </linearGradient>

  <rect rx="3" width="90" height="20" fill="#555" />
  <rect rx="3" x="37" width="53" height="20" fill="#4c1" />
  <path fill="#4c1" d="M37 0h4v20h-4z" />
  <rect rx="3" width="90" height="20" fill="url(#a)" />

  <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="19.5" y="15" fill="#010101" fill-opacity=".3">build</text>
    <text x="19.5" y="14">build</text>
    <text x="62.5" y="15" fill="#010101" fill-opacity=".3">passing</text>
    <text x="62.5" y="14">passing</text>
  </g>

</svg>
```

The main difference is seemingly that their `mask` is done with paths and not via a real mask.

``` svg
  <mask id="round">
    <rect width="{{=it.widths[0]+it.widths[1]}}" height="20" rx="3" fill="#fff"/>
  </mask>

  <g mask="url(#round)">
    <rect width="{{=it.widths[0]}}" height="20" fill="{{=it.escapeXml(it.colorA||"#555")}}"/>
    <rect x="{{=it.widths[0]}}" width="{{=it.widths[1]}}" height="20" fill="{{=it.escapeXml(it.colorB||"#4c1")}}"/>
    <rect width="{{=it.widths[0]+it.widths[1]}}" height="20" fill="url(#smooth)"/>
  </g>
```

Screenshot of the difference in corners: 

![comparison of badges, left Travis, right shields.io](https://i.imgur.com/GPHvIUj.png)

(left Travis, right shields.io)

**Comment by citrusui** [comment]
Seriously, why has this not been fixed? SVGs were designed to prevent blurry images, not encourage them.

**Comment by espadrine** [comment]
Which browser are you using, and on which operating system?

It doesn't seem present on Linux with neither Chrome nor Firefox.

**Comment by Haroenv** [comment]
This is visible on iOS and maxOS Safari (can't check chrome now but I think it was too)

**Comment by RedSparr0w** [comment]
IOS 9.2.1 for me

Sent from my iPhone

On 11/11/2016, at 10:05 AM, Thadd?e Tyl <notifications@github.com<mailto:notifications@github.com>> wrote:


Which browser are you using, and on which operating system?

It doesn't seem present on Linux with neither Chrome nor Firefox.

-

**Comment by espadrine** [comment]
I saw this issue with a version of Safari, but it seems like the problem is no longer present on 10.0.1. I guess this is a fixed WebKit bug. If there is a Safari version beyond 10.0.1 with the blur issue, please reopen the issue.

**Comment by Haroenv** [comment]
I can still reproduce with Safari (Technical Preview Release 19 (Safari 10.1, WebKit 12603.1.14.2))

**Comment by citrusui** [comment]
Also reproduced with iOS 10.2 [User Agent: AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1]

**Comment by espadrine** [comment]
Huh, really? Not sure why it works on my machine. Well, I'll reopen it. Since I don't have the faulty configuration, could you report a bug to WebKit please? https://webkit.org/reporting-bugs/

(It could be related to https://bugs.webkit.org/show_bug.cgi?id=125289, but since I can't test it, I can't test it.)

**Comment by Haroenv** [comment]
Did you check with the image in a <img> tag, or inline svg?

**Comment by citrusui** [comment]
I checked the badges in this repo's README. They seem to be using `<img>` tags.

**Comment by espadrine** [comment]
Ah! That's where I saw the bug! It looks fine in normal SVG, but the problem is in `<img src=.svg>`.

**Comment by espadrine** [comment]
The corresponding WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=135616.

I have a plausible fix, tested on Chrome, Safari, Firefox. And Edge.

**Comment by espadrine** [comment]
I'll try to push this live in 24h. It would be dangerous for me to push it live right before I go to sleep.

**Comment by citrusui** [comment]
Understood. Thanks for the quick responses!

**Comment by espadrine** [comment]
It should look good now! (hopefully.)

**Comment by Haroenv** [comment]
Yes, perfect :heart:
