### ISSUE TITLE
Static badge `Make Badge` button always disabled on Safari

### ISSUE THREAD

**Issue by LitoMore** [badges/shields#7324]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

**Operating system:** macOS Monetary
**Browser version:** Safari 15.1

#### How to reproduce

1. Open Safari
2. Open https://shields.io
3. Fill inputs for `Make Badge`

<img  width="370" src="https://user-images.githubusercontent.com/8186898/144363935-12d1b0a4-b59c-4622-9a82-7406f738a1fc.png">

#### Relevant issue

I cannot open `http://localhost:3000` on my local. It always shows the error view. This issue can only be reproduced on Safari.

<img width="1259" alt="CleanShot 2021-12-02 at 13 43 51@2x" src="https://user-images.githubusercontent.com/8186898/144364777-1d68e1bf-d92a-4a95-ac39-1fbd086e7ea6.png">

~~I guess it's a `gatsby`-related issue.~~

**Comment by paulmelnikow** [comment]
Confirmed on Safari 14.1.2. Thanks for the report.

<img width="549" alt="Screen Shot 2021-12-02 at 9 12 35 AM" src="https://user-images.githubusercontent.com/1487036/144438506-345145f3-158a-4e96-91a4-4daae3a451a2.png">

I see that exception in the JavaScript console too though I am not sure if it is related to the button activation.

Pull requests welcome!

**Comment by chris48s** [comment]
This is an issue where it would be great to get a community contribution for the fix, or a bit of time from you @paulmelnikow if nobody steps in. I don't use a mac so can't reproduce/debug this and I'm pretty sure Caleb/P-Y don't use macs either

**Comment by calebcartwright** [comment]
Correct, I've no way of testing this. I was curious whether any automated testing (with Cypress or otherwise) would be capable of detecting/confirming/preventing this sort of thing, though I suppose we'd at least need a Mac build/CI environment to test on

**Comment by LitoMore** [comment]
OK. I can give a check.

**Comment by chris48s** [comment]
My theory is that this issue is caused by https://github.com/sindresorhus/decamelize/issues/36 after upgrading decamelize in https://github.com/badges/shields/pull/7098

I've submitted a PR over at #7449 to revert decamelize to version 5. I have no way of testing this myself but is someone who has an i-Device of some description able to check the staging deploy at https://shields-staging-pr-7449.herokuapp.com/ and see if that fixes it in Safari? The staging deploy is on a dyno that goes to sleep so it might take a while to load

**Comment by paulmelnikow** [comment]
Unfortunately no dice:

<img width="1094" alt="Screen Shot 2022-01-05 at 4 28 10 PM" src="https://user-images.githubusercontent.com/1487036/148291994-d66d0ef6-491e-4c3d-99e1-c826778b0042.png">

**Comment by LitoMore** [comment]
@chris48s Sindre already mentioned that. You should [stay on version 3](https://github.com/sindresorhus/decamelize/issues/24).

**Comment by chris48s** [comment]
New staging deploy up. Can we try this one?
https://shields-staging-pr-7449.herokuapp.com/

**Comment by LitoMore** [comment]
Tested on map Mac. Works well.

![CleanShot 2022-01-07 at 03 36 00@2x](https://user-images.githubusercontent.com/8186898/148440856-8e681926-9525-4d72-9602-472c2146a5e5.png)
