### ISSUE TITLE
Upstream PyPI Download Issue 

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7325]
Not much we can do here, but this is already impacting our service tests using the daily variant as well as daily badges in general showing 0 per day

https://img.shields.io/pypi/dd/Django
![](https://img.shields.io/pypi/dd/Django)

https://status.python.org/incidents/2jj696st6yn5
https://github.com/crflynn/pypistats.org/issues/44

**Comment by hugovk** [comment]
https://github.com/crflynn/pypistats.org/issues/44 / https://status.python.org/incidents/2jj696st6yn5 / https://github.com/pypa/linehaul-cloud-function/issues/54 has been resolved.
