### ISSUE TITLE
www.website.com/path/to/page not working

### ISSUE THREAD

**Issue by numbfall** [badges/shields#733]
for website up/down badge, path on server

does not work
https://img.shields.io/website/http/github.com/badges.svg
![website](https://img.shields.io/website/http/github.com/badges/shields.svg?label=github.com/badges)

only this does
https://img.shields.io/website/http/github.com.svg
![website](https://img.shields.io/website/http/github.com.svg?label=girhub.com)

**Comment by RedSparr0w** [comment]
apparently you need to use the entire url after `https://img.shields.io/website/`

[this line in the index.html](https://github.com/badges/shields/blob/master/index.html#L1058) needs to be updated to be correct

#### Works:
`https://img.shields.io/website/https://github.com/badges.svg`
![test](https://img.shields.io/website/https://github.com/badges.svg?label=https://github.com/badges)

#### Does not work:
`https://img.shields.io/website/https/github.com/badges.svg`
![test](https://img.shields.io/website/https/github.com/badges.svg?label=https/github.com/badges)

**Comment by RedSparr0w** [comment]
#720 Should fix this

**Comment by paulmelnikow** [comment]
I just merged #720 (though it's not deployed yet).

Does the doc still need to be updated @RedSparr0w?

**Comment by paulmelnikow** [comment]
@RedSparr0w I just noticed this was still open. Do the docs still need updating?

**Comment by RedSparr0w** [comment]
`https://img.shields.io/website/https/github.com.svg`
![Alt Text](https://img.shields.io/website/https/github.com.svg?label=https/github.com)
`https://img.shields.io/website/https/github.com/badges.svg`
![Alt Text](https://img.shields.io/website/https/github.com/badges.svg?label=https/github.com/badges)
`https://img.shields.io/website/https/github.com/badges/shields.svg`
![Alt Text](https://img.shields.io/website/https/github.com/badges/shields.svg?label=https://github.com/badges/shields)

Looks like it is working as expected now. 👍 
Although some badges aren't showing and are instead showing the alt text but i assume that's a separate problem with GitHub/Shields servers
