### ISSUE TITLE
GitHubIssueDetail Closed issues message color

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7372]
GitHub's experience tiers have switched from displaying closed issues as red to purple (e.g. see our own closed issues https://github.com/badges/shields/issues?q=is%3Aissue+is%3Aclosed), ostensibly to avoid categorically connoting the failed/rejected/etc. theme of red.

I'm wondering if we should do the same for our issue status badge (PRs will remain the same since they already differentiate between merged/rejected) and curious what others think. I confess I'm still on the fence myself, but think I'm leaning towards changing to purple

**Comment by paulmelnikow** [comment]
I'd lean toward changing them too.

**Comment by calebcartwright** [comment]
Sounds like sufficient consensus to me, will take a look at implementing later today. Do we think this will be one of those things that'll need a query param for toggling between red/purple in order to satiate those preferring to maintain the red?

**Comment by chris48s** [comment]
I think we can just YOLO it
