### ISSUE TITLE
YouTube video view count: "invalid response data"

### ISSUE THREAD

**Issue by Symbian9** [badges/shields#7373]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All YouTube video view counts shows `invalid response data` in a field of number of views.

### 🔗 Link to the badge

- https://github.com/Symbian9/SolveSpace-Daily-Engineering#showcases
  - https://img.shields.io/youtube/views/1uZgUpjTg18?style=social&logo=youtube
  - https://img.shields.io/youtube/views/KY95-xrbSNo?style=social&logo=youtube
  - https://img.shields.io/youtube/views/XrbDdYCB_Hs?style=social&logo=youtube
  - https://img.shields.io/youtube/views/-DfILpX7v-4?style=social&logo=youtube
  - https://img.shields.io/youtube/views/8kiYJYwhXHc?style=social&logo=youtube
  - https://img.shields.io/youtube/views/rYYxQSBI2c8?style=social&logo=youtube

**Comment by calebcartwright** [comment]
Thank you for the report! Looks like Youtube have changed their API response structure, as it now includes objects under the `items` field which do not have the dislike count nor subscriber count failing schema validation:

https://www.googleapis.com/youtube/v3/videos?part=statistics&id=abBdk8bSPKU

```json
{
  "kind": "youtube#videoListResponse",
  "etag": "oolaHBsncBupkZFd7QlP8ZRIPKI",
  "items": [
    {
      "kind": "youtube#video",
      "etag": "pl3CDI4TqeRo5CsjDhJrUX5NAhE",
      "id": "abBdk8bSPKU",
      "statistics": {
        "viewCount": "400",
        "likeCount": "7",
        "favoriteCount": "0",
        "commentCount": "0"
      }
    }
  ],
  "pageInfo": {
    "totalResults": 1,
    "resultsPerPage": 1
  }
}
```

https://github.com/badges/shields/blob/49f49f16ba50208705faa2a09a05819035b7620e/services/youtube/youtube-base.js#L10-L31

I'm going to guess that Youtube has either dropped the dislike counts outright, or has switched to eliding the field if the value is zero, and we'll need to account for that, both in the schema linked above and then some handling of that scenario in the likes badge
