### ISSUE TITLE
Document the colors supported by the custom Shield

### ISSUE THREAD

**Issue by olivierlacan** [badges/shields#74]
We should list the colors supported since it appears that `grey` and `gray` don't work: http://img.shields.io/cheez/whiz.png?color=grey
http://img.shields.io/cheez/whiz.png?color=gray

That's one more point in the camp of #61 by the way.

**Comment by olivierlacan** [comment]
I think the colors are well documented on http://shields.io/

**Comment by scottschreckengaust** [comment]
I found that HEX values were case-sensitive...
