### ISSUE TITLE
Pipe separator for dynamic badges pointing at lists

### ISSUE THREAD

**Issue by H0R5E** [badges/shields#7402]
:clipboard: **Description**

The [dynamic badge](https://shields.io/#dynamic-badge) feature is super useful, thanks. It would be nice, however, if the behaviour when pointing to lists looked like other common badges, i.e. using a pipe symbol rather than a comma as the item separator. For instance, I would like this badge:

```
https://img.shields.io/badge/dynamic/yaml?label=os&query=$.jobs.pytest.strategy.matrix.os[:]&url=https://raw.githubusercontent.com/Data-Only-Greater/SNL-Delft3D-CEC-Verify/main/.github/workflows/unit_tests.yml
```

to look like this:

![](https://img.shields.io/badge/os-windows--latest%20%7C%20ubuntu--latest-blue)

rather than this:

![](https://img.shields.io/badge/dynamic/yaml?label=os&query=%24.jobs.pytest.strategy.matrix.os[:]&url=https%3A%2F%2Fraw.githubusercontent.com%2FData-Only-Greater%2FSNL-Delft3D-CEC-Verify%2Fmain%2F.github%2Fworkflows%2Funit_tests.yml)

Is this possible?

**Comment by calebcartwright** [comment]
If you'd like that level of control over formatting then I'd encourage you to take a look at our [Custom Endpoint Badge](https://shields.io/endpoint) instead, which is basically a more powerful version of the Dynamic badges that provide greater customization.

**Comment by H0R5E** [comment]
Guess I'll just suffer the comma.

**Comment by calebcartwright** [comment]
Obviously that's up to you and each individual user, which is really the intent. Shields offers a great deal of customization out of the box, but we realized long ago it wouldn't be practical to attempt to support the myriad subjective formatting desires of individual users.

The Endpoint badge is a great compromise. Yes, you need to "deploy" some code, but that can be done succinctly and for free in various serverless capacities. All of our badges also have a json endpoint that provides the underlying data via a simple call which can be more easily transformed, e.g.

https://img.shields.io/badge/dynamic/yaml.json?label=os&query=%24.jobs.pytest.strategy.matrix.os[:]&url=https%3A%2F%2Fraw.githubusercontent.com%2FData-Only-Greater%2FSNL-Delft3D-CEC-Verify%2Fmain%2F.github%2Fworkflows%2Funit_tests.yml

```json
{"label":"os","message":"windows-latest, ubuntu-latest","color":"blue","link":[],"name":"os","value":"windows-latest, ubuntu-latest"}
```
So a custom endpoint implementation would be rather trivial

**Comment by H0R5E** [comment]
OK, yes, thanks for adding the additional detail, I think I understand a little better now how to get it to work. I am also having a look at [this article](https://tnodes.medium.com/dynamic-badges-with-shields-io-and-runkit-9e80283f1b47), which also removes the fear a little. It's just that the [Custom Endpoint](https://shields.io/endpoint) documentation feels like a big leap from the friendly hand holding of everything else on [sheilds.io](https://shields.io/).

I totally understand you don't want to support every possible customization of labels. I would argue that this request is not that nichey, but I imagine that even creating a way of specifying you want this opens up a can of worms.

**Comment by calebcartwright** [comment]
Yup you've nailed it. Individually, such requests seem trivial and innocuous, but it's the aggregated snowballing that starts to get problematic quickly.

Thanks for sharing your experience and reaction with the endpoint docs. I think it's fair to say that there's a general consensus amongst the core team that we could provide more/clearer information, though I'm not sure if we know precisely what that should be (nor are we necessarily the best candidates for identifying what's most clear for new folks). In many cases it's as simple as writing, or even copying, a few lines of code and pasting them into a service like runkit, but definitely agree that simplicity isn't necessarily obvious.

Please feel free to suggest changes to the [endpoint docs](https://github.com/badges/shields/blob/master/frontend/pages/endpoint.tsx) if you've got any ideas on how they could be improved!

**Comment by chris48s** [comment]
Might be opening a bit of a can of worms, but I think there's actually an interesting meta point here about how we format badges that show multiple values.

At the moment we have a bit of a random mashup of pipe and comma. For example:
* ![](https://img.shields.io/pypi/pyversions/Django) https://img.shields.io/pypi/pyversions/Django
* ![](https://img.shields.io/github/package-json/keywords/developit/microbundle) https://img.shields.io/github/package-json/keywords/developit/microbundle
* ![](https://img.shields.io/powershellgallery/p/DNS.1.1.1.1) https://img.shields.io/powershellgallery/p/DNS.1.1.1.1
* ![](https://img.shields.io/appveyor/tests/NZSmartie/coap-net-iu0to/master) https://img.shields.io/appveyor/tests/NZSmartie/coap-net-iu0to/master
* ![](https://img.shields.io/appveyor/tests/NZSmartie/coap-net-iu0to/master?compact_message) https://img.shields.io/appveyor/tests/NZSmartie/coap-net-iu0to/master?compact_message

There might be a rule there for when we use each, but I couldn't really tell you what it is.

**Comment by calebcartwright** [comment]
Yeah I had that in the back of my mind too but was going to leave that one canned for the time being :laughing: 

We've seen time and time again where making a forced change on an existing badge brings out the folks with their pitch forks and we often end up reverting or having to introduce a query param to support both. As such, absent a functioning time machine I'm skeptical there's much that can be done with what already exists. There's a fair share of cases where, to use an oft phrase of mine, we _are_ inconsistently consistent, and this could certainly fall under that umbrella (though my sense was typically pipes for numerical/versions and commas for the more wordy/human text).

I've no objections to codifying some defaults we can use as a guide for any future additions, however, while I realize no one is suggesting otherwise, just want to reiterate that IMO a generic "allow users to pick separator" fits pretty squarely into the message format customization territory that we punt to Endpoint badges e.g. https://github.com/badges/shields/discussions/6135#discussioncomment-329581
