### ISSUE TITLE
Badge Request: Polymart

### ISSUE THREAD

**Issue by MherZaqaryan** [badges/shields#7429]
:clipboard: **Description**
[Polymart](https://polymart.org/) this is a website similar to [Spigot](https://www.spigotmc.org/) (Spiget) which badge's also available at the moment.
<img src="https://img.shields.io/spiget/download-size/1234"> (https://img.shields.io/spiget/download-size/1234)

:link: **Link**
Official website: https://polymart.org
Public API: https://api.polymart.org
API Documentation: https://polymart.org/wiki/api

:microphone: **Motivation**
This should help Polymart resources look better and also will help some sellers to make their resources look good.
Good Luck!

**Comment by sunnyjain15699** [comment]
Hi Would like to work on this issue.
Can you guide me ?

**Comment by calebcartwright** [comment]
> Hi Would like to work on this issue. Can you guide me ?

Great! We've got a detailed [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that walks through the process of adding a badge, so would encourage you to start there and then feel free to ask any questions here and/or on Discord if you have any

**Comment by gogoiakash2311** [comment]
Heyy! Would like to work on this issue, is it still open?

**Comment by MherZaqaryan** [comment]
> Heyy! Would like to work on this issue, is it still open?

Yep, but I am gonna work on this soon, I already made a pull request!

**Comment by gogoiakash2311** [comment]
Okay then! Let me know if I can provide any help
