### ISSUE TITLE
discord badge does not invite

### ISSUE THREAD

**Issue by Goldziher** [badges/shields#7438]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi there. The discord badge doesn't invite new members to the server, unlike the discord official widget. 

If you press the widget you only get an image of the widget. 

### 🔗 Link to the badge

https://img.shields.io/discord/919193495116337154?color=blue&label=chat%20on%20discord&logo=discord

### 💡 Possible Solution

I hacked my way into a "solution" by converting the shield to this:

```html
<a href="https://discord.com/widget?id=919193495116337154&theme=dark">
   <img src=https://img.shields.io/discord/919193495116337154?color=blue&label=chat%20on%20discord&logo=discord />
</a>
```

When pressing this you get the official discord functionality.

**Comment by calebcartwright** [comment]
This is expected behavior; you have to provide the associated markdown (or markup) url.

The `?link=...` query parameter can also be used to embed links within the svg itself, but that is rather constrained (doesn't work in markup languages, has to be in an object tag not an img tag, etc.)
