### ISSUE TITLE
In Windows Firefox, labels and status text in badges overlap and push outside boundaries

### ISSUE THREAD

**Issue by un1versal** [badges/shields#746]
Here are a few examples from [shields.io](http://shields.io/) website, to illustrate whats happening in projects Im involved in, clearly this is now a global issue.

[![bitHound](https://img.shields.io/bithound/devDependencies/github/rexxars/sse-channel.svg?maxAge=2592000)]()  
[![Gem](https://img.shields.io/gem/dtv/rails.svg?maxAge=2592000)]()  
[![Crates.io](https://img.shields.io/crates/dv/rustc-serialize.svg?maxAge=2592000)]()  
[![MyGet tenant](https://img.shields.io/dotnet.myget/dotnet-coreclr/v/Microsoft.DotNet.CoreCLR.svg?maxAge=2592000)]()  
[![MyGet tenant](https://img.shields.io/dotnet.myget/dotnet-coreclr/v/Microsoft.DotNet.CoreCLR.svg?maxAge=2592000)]()  
[![David](https://img.shields.io/david/optional/elnounch/byebye.svg?maxAge=2592000)]()  
[![CocoaPods](https://img.shields.io/cocoapods/p/AFNetworking.svg?maxAge=2592000)]()

Would you guys consider adding padding to left and right of label portion and left and right of status portion?

**Comment by un1versal** [comment]
anyone?

**Comment by un1versal** [comment]
![capture](https://cloud.githubusercontent.com/assets/3521959/17268995/0a4e60d4-5634-11e6-92d4-8a294f955db5.PNG)

this is todays coverity, it is pretty much unreadable...

@badges is there a point reporting issues here on GH issue tracker or? just no replies at all... makes one wonder

**Comment by espadrine** [comment]
Could you provide us with a list of fonts available on your computer among the following names, please?

- DejaVu Sans
- Verdana
- Geneva

Could you also provide us with an exact version number corresponding to your operating system and one corresponding to your browser?

Thanks a lot for reporting this!

**Comment by un1versal** [comment]
The issue is visible on Windows 7 sp1 all up-to-date + Firefox 47.0.1 its not always been the case.

LInux ubuntu variant 16.04 + Firefox 47.0 is OK

Fonts available (checked) The others are not available on Windows by default.

- [ ] DejaVu Sans
- [x] Verdana
- [ ] Geneva

I also tried to using a font revert thing for GitHub...

```
@-moz-document regexp("^https?://((gist|guides|help|raw|status|developer)\.)?github\.com((?!generated_pages\/preview).)*$"), domain("render.githubusercontent.com"), domain("raw.githubusercontent.com") {

body, .markdown-body {

    font-family: Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;

  }

}
```
Which reverts the fonts GitHub currently uses, however shield IO badges are unaffected. with or without the issue is there.

Screenshot of Vanilla windows...

![capture](https://cloud.githubusercontent.com/assets/3521959/17274543/13a61780-56de-11e6-9b11-b3959ee56b6b.PNG)

**Comment by un1versal** [comment]
@espadrine any advance on this?

**Comment by mralexgray** [comment]
are these people even alive?

**Comment by un1versal** [comment]
> are these people even alive?

Clearly its not an important issue to them like paying the bills or world hunger etc.

**Comment by mralexgray** [comment]
it actually looks decent on Safari (MacOS)... this must be a browset-specific issue... <<sigh>>

![screen shot 2016-09-23 at 11 58 10 pm](https://cloud.githubusercontent.com/assets/262517/18805956/d208add8-81e9-11e6-954b-4d94a85192bb.png)

**Comment by un1versal** [comment]
This isnt a OSX or Linux issue

**Comment by RedSparr0w** [comment]
There seems to have been only relatively small updates since i started following this project.

assume its just lack of people with privileges to accept PR's ect. as there seems to be lots of people willing to work in this and create PR's but nothing is getting done about them.

**Comment by un1versal** [comment]
Firefox 49.01 and Win 7 sp1 still same issue.

**Comment by paulmelnikow** [comment]
I joined the project a few weeks ago and have been steadily merging PRs. Thaddée has been deploying the updates.

Some further research was done in #797. Would be great if someone could dig into this problem further.

If we can isolate the problem, maybe running some tests on Sauce Labs would help diagnose the problem thoroughly and prevent a regression.

cc @aburgd @mralexgray

**Comment by aburgd** [comment]
I've found that the badges are showing up properly on my laptop running WX
with Chrome.

**Comment by the-j0k3r** [comment]
@paulmelnikow 

I just noticed this problem and came looking for a report or make my own.
Ive not tested in other OS's

The issue exists with svg badges only as far as I cant tell, with png badges the issue is gone, but of course the text is quite small in comparison.

My environment:
```
Windows 10
Firefox 56 64bit
```
Issue test

[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg)]()
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.png)]()

as above
```
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg)]()
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.png)]()
```

Screenshot as I see it.

![capture](https://user-images.githubusercontent.com/31389848/31187072-94094af8-a928-11e7-8729-c72f132c4b3c.PNG)

**Comment by paulmelnikow** [comment]
Thanks for the info.

Could you include your answer to Thaddée's question in https://github.com/badges/shields/issues/746#issuecomment-236384036?

> The issue exists with svg badges only as far as I can tell, with png badges the issue is gone, but of course the text is quite small in comparison.

Yea, that's right, it's only with the svg badges. The png badges are rasterized on the server, so they look the same everywhere.

**Comment by the-j0k3r** [comment]
@paulmelnikow request dupe-reply here

---

@paulmelnikow 

I just noticed this problem and came looking for a report or make my own.
Ive not tested in other OS's

The issue exists with svg badges only as far as I can tell, with png badges the issue is gone, but of course the text is quite small in comparison.

My environment:
```
Windows 10
Firefox 56 64bit
```
Issue test

[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg)]()
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.png)]()

as above
```
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg)]()
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.png)]()
```

Screenshot as I see it.

![capture](https://user-images.githubusercontent.com/31389848/31187072-94094af8-a928-11e7-8729-c72f132c4b3c.PNG)

**Comment by paulmelnikow** [comment]
It looks like you tried to reply but I'm not seeing it. I mean: which of those fonts do you have installed?

**Comment by the-j0k3r** [comment]
Its Windows, doubtful it will have Dejavu Sans or any Dejavu or Geneva, verdana yes.

 DejaVu Sans -- No
 Verdana -- Yes
 Geneva --No

**Comment by paulmelnikow** [comment]
It's rendering with Verdana on my Mac OS machine too. I'm not sure why the size is so different.

```
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg)]()
[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.png)]()
```

Here's what I'm seeing:

<img width="178" alt="screen shot 2017-10-04 at 4 46 51 pm" src="https://user-images.githubusercontent.com/1487036/31198849-a8ed9366-a923-11e7-86d9-596d3f4fdefd.png">

Is the problem observed in Firefox, and not in Chrome or IE?

**Comment by paulmelnikow** [comment]
There's a known issue with minimum font size. Do you have that turned on? (#848)

**Comment by the-j0k3r** [comment]
> There's a known issue with minimum font size. Do you have that turned on? (#848)

**You nailed it, that seems to be the problem.** 👍 🍾 🥇 disable minimum size and issue is gone. 😊 

Im not sure when or why that setting changed here but its off now.

One thing though, #848 report doesnt mention which browser or version, even no OS or version either

> Is the problem observed in Firefox, and not in Chrome or IE?

If you have read through both tickets, https://github.com/badges/shields/issues/797#issuecomment-249511923 and https://github.com/badges/shields/issues/797#issuecomment-249436383 cover those questions.

But Firefox side you now know that is the minimum size thing.

**Comment by paulmelnikow** [comment]
@RedSparr0w has a brilliant fix! Could you help us test it @the-j0k3r, by turning min-font-size back on till the problem comes back, and then screenshotting this page?

http://whois.paulmelnikow.com/extra/1132.html

**Comment by the-j0k3r** [comment]
My pleasure, to help out, least I can do :)

![capture](https://user-images.githubusercontent.com/31389848/31255145-449fa2e0-aa23-11e7-989e-df8d8215ccea.PNG)

**Comment by the-j0k3r** [comment]
This issue is still present, I though once PR was merged it would go away.

**Comment by RedSparr0w** [comment]
Doesn't look like the change has gone live yet, it can take a few weeks after being merged to the master branch before it is pushed through.

Sent from my iPhone

On 21/10/2017, at 6:35 PM, the-j0k3r <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue is still present, I though once PR was merged it would go away.

**Comment by the-j0k3r** [comment]
Ah, well lets hope thats soon.
