### ISSUE TITLE
Matrix spaces

### ISSUE THREAD

**Issue by ZekeSmith** [badges/shields#7466]
:clipboard: **Description**

A clear and concise description of the new badge.

- Matrix
- Users in a matrix space
  Space | 10

:link: **Data**

Where can we get the data from?

- I believe it is similar to how the matrix badge functions and likely just requires a little bit of a change

:microphone: **Motivation**

Matrix spaces is out of beta and is a good option for opensource projects, being able to link a shield to them will help with usabilty and connection to these spaces

**Comment by calebcartwright** [comment]
I'm not terribly familiar with Matrix myself, so I think some material links would be helpful to include in the description, both for general awareness and for anyone interested in working on the badge.

I'd also encourage you to try to find the API specifics to make this actionable. It's pretty common for first-time contributors to look for such issues, but we've got a number of them on the backlog already and ones that have API details are more likely to get worked on than those that don't

**Comment by ZekeSmith** [comment]
I wouldnt know enough details unfortunately and would probably have to have someone else look into it. All I know is that spaces function similar to how rooms do and likely would be similar with how the shield is made.

**Comment by ZekeSmith** [comment]
Badges actually work with matrix room badges space permissions where just not set properly. I am closing this issue
