### ISSUE TITLE
Accessing github private repositories when self-hosting

### ISSUE THREAD

**Issue by rcruzper** [badges/shields#747]
Hi,

I'm trying to run shields.io in heroku to use with my organization private repositories.
I created a secret.json with gh_client_id and gh_client_secret, but when in try to get a badge it returns 'none' as value.
Have I missed something?

**Comment by bittner** [comment]
(Anyone monitoring this issue?)

It would be nice to have some explanation on using badges with private repositories in the [README](https://github.com/badges/shields/blob/master/README.md), on the [GitHub page](https://badges.github.io/gh-badges/) or [on Shields.io](http://shields.io/).

**Comment by bittner** [comment]
Related issue: #593
