### ISSUE TITLE
Cannot Add Subgroup Repo for GitLab Code Coverage

### ISSUE THREAD

**Issue by ProfessorManhattan** [badges/shields#7473]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Similar to the GitLab build status (which was fixed), the GitLab code coverage badge needs to be updated to allow repositories that are part of subgroups. For instance, if the URL is https://gitlab.com/user/subgroup/go-cli then the GitLab code coverage badge will always report 404 because it has not been designed to allow subgroups.

This was fixed for the GitLab build status badge. I imagine all the GitLab badges that weren't updated will still need an update to accomodate repositories that are nested in subgroups.

In the example link below, you can see that the badge shows up as 404 when it should show up as "Coverage not set up"

### 🔗 Link to the badge

https://img.shields.io/gitlab/coverage/megabyte-labs/go/cli/bodega/master

### 💡 Possible Solution

Apply same fix that was applied to the GitLab build status

**Comment by chris48s** [comment]
Yes the fix for this should be similar to https://github.com/badges/shields/pull/7159

I think the other GitLab badges that use the API should all be fine
related reading: https://github.com/badges/shields/pull/7021#discussion_r728418226
