### ISSUE TITLE
Depfu for Gitlab repos

### ISSUE THREAD

**Issue by kris7t** [badges/shields#7474]
:clipboard: **Description**

The [Depfu](https://github.com/badges/shields/pull/2204/files#diff-07f982763d8a47feb189c97cf5053d5fb2d7251a649340d3b7d3c0706fe66692R13) service is using the `/github/shields` endpoint of Depfu, which means it can only query the status of Github repos. It would be nice to be able to query Gitlab repos.

:link: **Data**

Depfu also has a `https://depfu.com/gitlab/shields/${userRepo}` endpoint, which acts the same as the `/github/shields` endpoint, but for Gitlab repos.

:microphone: **Motivation**

While Depfu provides built-in badges, their style cannot be customized (e.g., `?style=flat-square`), so it would be still useful to have this as a `shields.io` badge.

**Comment by chris48s** [comment]
I think the way to do this will be to make new routes

- `/depfu/github/:userRepo+`
- `/depfu/gitlab/:userRepo+`

and then redirect `/depfu/anything/else` to `/depfu/github/anything/else` for backwards compatibility

**Comment by kris7t** [comment]
Btw, I managed to find a workaround by using the underlying JSON endpoint directly, such as

```
https://img.shields.io/badge/dynamic/json?color=colorscheme&label=dependencies&query=text&url=https%3A%2F%2Fdepfu.com%2Fgitlab%2Fshields%2F{user}%2F{repo}&style=flat-square
```

But adding the routes would certainly be much nicer. I could try adding it myself, if I can manage to understand how redirectors and routes are set up. :slightly_smiling_face:

**Comment by chris48s** [comment]
If you are interested in looking at it https://github.com/badges/shields/blob/c73072deed8eb6a5b9f51a06377f5f396ef21842/services/circleci/circleci.service.js is probably a good example to crib from
