### ISSUE TITLE
dependencyci.com Support 

### ISSUE THREAD

**Issue by qoomon** [badges/shields#748]
please add dependency-ci support

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion.

Is there an API?

**Comment by qoomon** [comment]
https://dependencyci.com/docs -> Readme Badge

**Comment by paulmelnikow** [comment]
I see they have SVG badges – generated by us!

Is there a way to grab the build status from an API, in a more parseable format like JSON?

**Comment by paulmelnikow** [comment]
I know now that we have tools to parse SVG badges!

**Comment by qoomon** [comment]
No this service does not exists anymore.
