### ISSUE TITLE
Micronaut - Java framework for build microservices - Logo

### ISSUE THREAD

**Issue by AlexanderKhudoev** [badges/shields#7498]
:clipboard: **Description**

Micronaut - a modern, jvm-based, full-stack framework for building modular, easily testable microservice and serverless applications

:link: **Data**

[Micronaut framework](https://micronaut.io/brand-guidelines/micronaut-logos/)

:microphone: **Motivation**

Need a badge with Micronaut logo for portfolio

**Comment by calebcartwright** [comment]
Thanks for reaching out, but it's not at all clear what you're asking. It sounds like you're asking for the ability to use a logo on your badge, in which case I'd point you to our docs on https://github.com/badges/shields/blob/master/doc/logos.md and https://shields.io/#styles.

**Comment by AlexanderKhudoev** [comment]
> Thanks for reaching out, but it's not at all clear what you're asking. It sounds like you're asking for the ability to use a logo on your badge, in which case I'd point you to our docs on https://github.com/badges/shields/blob/master/doc/logos.md and https://shields.io/#styles.

Thank you, I should use 'Custom logo' variant

**Comment by calebcartwright** [comment]
Excellent, glad this is sorted then. Going to close accordingly
