### ISSUE TITLE
allow other branches than master for Travis CI

### ISSUE THREAD

**Issue by whit537** [badges/shields#75]
As of https://github.com/gittip/img.shields.io/pull/1 we now peg Travis CI badges to master. Travis currently allows for badges for non-master branches with a ?branch= querystring. We should do something similar.

**Comment by piskvorky** [comment]
Any progress on this?

I just got bitten by this -- the `branch` parameter is simply silently ignored.

**Comment by espadrine** [comment]
@piskvorky Are you sure? This issue is very old and should have been closed a very long time ago. The `?branch` parameter should not be ignored, and I have definitely seen it work. Can you provide an example where it did not?

**Comment by piskvorky** [comment]
Sure:

https://img.shields.io/travis/piskvorky/gensim.svg?branch=master
vs. 
https://api.travis-ci.org/piskvorky/gensim.png?branch=master

I get the same green "passing" image from shields.io, no matter what branch I specify (including non-existent ones).

Or am I doing it wrong?

**Comment by espadrine** [comment]
The syntax for branches isn't the same as the one used for travis:

[`https://img.shields.io/travis/piskvorky/gensim/master.svg`](https://img.shields.io/travis/piskvorky/gensim/master.svg)

**Comment by piskvorky** [comment]
Thanks!
