### ISSUE TITLE
`packageManager` field

### ISSUE THREAD

**Issue by arcanis** [badges/shields#7515]
:clipboard: **Description**

Node now supports a new [`packageManager` field](https://nodejs.org/api/packages.html#packagemanager) used to denotate which package manager is supposed to be used when cloning the project to work on it (it doesn't affect which package manager the end user can use once the package is published; any of them should work). For example:

https://github.com/nodejs/corepack/blob/main/package.json#L20

It'd be nice if we could use this field to make a badge exposing this information:

![](https://img.shields.io/badge/package%20manager%20-Yarn%203.1.0-blue)

**Comment by calebcartwright** [comment]
Thanks for sharing your suggestion!

First want to note that in addition to a handful of specific-key coded badges, we also support a dynamic package.json badge that can be used to grab any present field:

https://img.shields.io/github/package-json/packageManager/nodejs/corepack
![](https://img.shields.io/github/package-json/packageManager/nodejs/corepack)

To the best of my knowledge, we've not had any explicit conversations yet to define any kind of process or criteria to decide when it makes sense to hoist out a new, dedicated badge route for a package.json key vs. the aforementioned dynamic key process.

Personally, I think we should lean on the dynamic key badge as much as possible (less code to maintain) and only implement a dedicated badge if/when there's significant enough volume for a given key, or if a given key can be painful to use (for example, the dynamic key is case sensitive so `packageManager` will work while `packagemanager` will not.

I'd be interested to hear what other maintainers think, both for this specific key and badges for package.json keys in general

**Comment by chris48s** [comment]
Yeah I reckon https://img.shields.io/github/package-json/packageManager/nodejs/corepack means we already have a solution to this

**Comment by calebcartwright** [comment]
> Yeah I reckon https://img.shields.io/github/package-json/packageManager/nodejs/corepack means we already have a solution to this

:+1: 

Are we good pointing to this for any/all fields going forward? My memory may be off, but I feel like we originally started down the badge-per-key route which led to some of the ones we see today before ultimately adding the dynamic package.json one that ostensibly covers all scenarios

**Comment by chris48s** [comment]
Mostly. I think yes for anything informational, but potentially there are values where it would be useful to apply colour based on the value and in that case it might be valid to do something custom.

**Comment by calebcartwright** [comment]
Sounds reasonable to me. Going to close given the above as I don't see a need for any specific default rendering concerns being needed for this key
