### ISSUE TITLE
Add [Reddit] Chat static-social badge

### ISSUE THREAD

**Issue by TheAlienDrew** [badges/shields#7518]
:clipboard: **Description**

- Service for: GitHub
- Information shown: "Reddit Chat" / "Chat on Reddit" / "Chat via Reddit" (static badge)

:link: **Data**

- Get Reddit user info from: `https://www.reddit.com/user/[USERNAME]/about.json` (this is required to fill out data for finalized link)
  - From the **`about.json`**, retrieve values from `kind` and `id`
- Generate link from data with following URL: `https://www.reddit.com/chat/user_id/[KIND]_[ID]?link_sharing=true`
  - Note: the `link_sharing` parameter is optional, but without it will open the entire reddit chat window as a full page (instead of opening in the bottom right on the reddit homepage)

- Additionally, using the generator / tweaking it using the docs, I was able to get a working prototype below:
  - [![Chat with @Alien_Drew](https://img.shields.io/badge/Chat_with_@Alien__Drew--URL?style=social&logo=reddit&link=https%3A%2F%2Fwww.reddit.com%2Fchat%2Fuser_id%2Ft2_1091wg)](https://www.reddit.com/chat/user_id/t2_1091wg)
  https://img.shields.io/badge/Chat_with_@Alien__Drew--URL?style=social&logo=reddit&link=https%3A%2F%2Fwww.reddit.com%2Fchat%2Fuser_id%2Ft2_1091wg

:microphone: **Motivation**

Personally, and I'm sure others don't care to user Twitter often, this would provide alternative means of contact via social media.

**Comment by calebcartwright** [comment]
Thanks for reaching out with your suggestion!

I've made a minor edit to the issue description to include the badge url to make it more visible for anyone else that wants a similar badge, but I am also going to close this issue as it's not going to be actionable for us.

In addition to our native and dynamic badges, we also provide the static badge (which you've utilized here) and an npm package that users can use to generate badges of their choosing. However, we're not in the business of providing dedicated instances of utilizations of our static badge, and certainly not ones that add work on our servers to repeatedly make API calls to fetch static data that's already known/available to the user.

I appreciate that the initial creation of such a badge would be easier if we had a dedicated badge, but that one-time user convenience doesn't warrant the maintenance and runtime drawbacks of Shields having to repeatedly do that work.
