### ISSUE TITLE
"unknown license" for github license badge

### ISSUE THREAD

**Issue by Jire** [badges/shields#754]
Why doesn't Shields recognize my project's badge?

https://github.com/Jire/KTON

[![license](https://img.shields.io/github/license/Jire/KTON.svg)](https://github.com/Jire/KTON/blob/master/LICENSE.txt)

``` markdown
[![license](https://img.shields.io/github/license/Jire/KTON.svg)](https://github.com/Jire/KTON/blob/master/LICENSE.txt)
```

**Comment by un1versal** [comment]
recognizes glpv2 on ours, very odd.

**Comment by nevillelyh** [comment]
Doesn't work on my new project either. I wonder if it's because the "unknown license" image was cached before I added a LICENSE file?

**Comment by giggio** [comment]
Same problem here: [![License](https://img.shields.io/github/license/Lambda3/dotnet-commands.svg)](https://github.com/Lambda3/dotnet-commands/blob/master/LICENSE.txt)

**Comment by un1versal** [comment]
It wont solve anything, but havent you guys ever heard of relative linking?
[![License](https://img.shields.io/github/license/Lambda3/dotnet-commands.svg)](./LICENSE.txt)
`[![License](https://img.shields.io/github/license/Lambda3/dotnet-commands.svg)](./LICENSE.txt)`

in any event you guys can workaround this issue easily until this issue is resolved

[![License](https://img.shields.io/badge/Licence-Apache%202.0-blue.svg)](./LICENSE.txt)
`[![License](https://img.shields.io/badge/Licence-Apache%202.0-blue.svg)](./LICENSE.txt)`

**Comment by KevinPlus3** [comment]
We are running into this issue as well:
```
[![license](https://img.shields.io/github/license/plus3it/watchmaker.svg)](./LICENSE)
```
Interestingly, enough, it seems to work fine with:
```
[![license](https://img.shields.io/github/license/plus3it/systemprep.svg)](./LICENSE)
```
But both projects have the same LICENSE file.  I haven't been able to pinpoint the exact problem with the `plus3it/watchmaker` project.
I downloaded and installed `benbalter/licensee` (which I believe is what `github/license` uses) and got back the following:
```
C:\Users\Vekyllis\GitHubRepos>licensee watchmaker
License file: LICENSE
Attribution: Copyright 2015 Maintainers of plus3it/watchmaker
License: Apache License 2.0
Confidence: 99.89%
Method: Licensee::Matchers::Dice
```
So `licensee` seems to be outputting correctly which leads me to believe that the call to `https://img.shields.io/github/license/` is producing the incorrect response somehow.

**Comment by KevinPlus3** [comment]
Also, while I added the above information in support of the issue. I think Shields itself is not the problem since it just creates the badge in response to an API call.  I think the underlying issue may be with GitHub's call itself so I sent an support ticket to GitHub to see if they could look into it.

**Comment by un1versal** [comment]
> so I sent a support ticket to GitHub to see if they could look into it.

bah, good luck, you have a better chance of winning the lottery, 9/1 they will palm it off to some side project they use.

**Comment by alphp** [comment]
PHP License is see as "Other":
[![license](https://img.shields.io/github/license/alphp/win32service.svg)](https://github.com/alphp/win32service/blob/master/LICENSE)
`[![license](https://img.shields.io/github/license/alphp/win32service.svg)](https://github.com/alphp/win32service/blob/master/LICENSE)`

**Comment by platan** [comment]
Shields.io currently uses Github REST API (`license` fragment from `/repos/:owner/:repo` resource) to get license name. 
@Jire GitHub API returns `null` as a license for https://github.com/Jire/KTON
```
curl "https://api.github.com/repos/Jire/KTON" -H "Accept: application/vnd.github.drax-preview+json" -s | jq '.license' 
null
```
I renamed license file to LICENSE in my fork and it returns rigth license name:
```
curl "https://api.github.com/repos/platan/KTON" -H "Accept: application/vnd.github.drax-preview+json" -s | jq '.license' 
{
  "key": "apache-2.0",
  "name": "Apache License 2.0",
  "spdx_id": "Apache-2.0",
  "url": "https://api.github.com/licenses/apache-2.0",
  "featured": true
}
```
License badge (see https://github.com/platan/KTON) works as well.

**Comment by platan** [comment]
@giggio It seems that it works properly for your repo now.

**Comment by platan** [comment]
@KevinPlus3 I see that license badge works properly for your repos.

**Comment by platan** [comment]
@alphp GitHub recognizes your license as:
curl "https://api.github.com/repos/alphp/win32service" -H "Accept: application/vnd.github.drax-preview+json" -s | jq '.license.name'
"Other"
I can see you added custom badge.

**Comment by paulmelnikow** [comment]
Seems like this can be closed, then?

**Comment by platan** [comment]
I think so.

**Comment by alphp** [comment]
Issue clarified, GitHub does not have the PHP license between the list of "recognized" licenses and tag the project's license as "Other".

**Comment by platan** [comment]
@paulmelnikow We can close this issue now.

**Comment by frugan-dev** [comment]
I don't know if the problem actually depends on this, but in my case it was enough to update the license text by copying it from https://choosealicense.com
