### ISSUE TITLE
License for NPM scoped packages not working?

### ISSUE THREAD

**Issue by cedx** [badges/shields#757]
See my own projects released as NPM scoped packages:
https://www.npmjs.com/package/@cedx/gulp-david
https://www.npmjs.com/package/@cedx/reverse-proxy

License is `invalid`. Used `https://img.shields.io/npm/l/@cedx/gulp-david.svg` for badge source, but it seems that this feature is either not implemented, or not working.

**Comment by ericclemmons** [comment]
Confirmed:
> https://img.shields.io/npm/l/@terse/webpack.svg

**Comment by arcanis** [comment]
I've just submitted a PR, I hope someone will be able to merge it relatively soon :/

**Comment by arcanis** [comment]
Related issue on the NPM side: https://github.com/npm/registry/issues/34

**Comment by aureooms** [comment]
Same for
  - https://img.shields.io/npm/dm/@scope/name.svg, and
  - https://img.shields.io/npm/dt/@scope/name.svg.
