### ISSUE TITLE
GitHub release badge shows "none" in Markdown

### ISSUE THREAD

**Issue by tony19** [badges/shields#759]
When I access this badge URL directly, I see the badge with the expected release version:

> https://img.shields.io/github/release/tony19/x-user-dropdown.svg?maxAge=2592000

![screen shot 2016-08-06 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/26580/17458521/b57d356c-5bd8-11e6-9a3b-051c6a977104.png)

But if I put that in Markdown format:

```markdown
[![GitHub release](https://img.shields.io/github/release/tony19/x-user-dropdown.svg?maxAge=2592000)]()
```
![screen shot 2016-08-06 at 1 20 39 pm](https://cloud.githubusercontent.com/assets/26580/17458515/9b0d0a22-5bd8-11e6-9130-4c7bee0d179c.png)

[demo](https://github.com/tony19/x-user-dropdown/blob/2d78ded/README.md)

Why is that?

**Comment by espadrine** [comment]
Could you try removing the maxAge part please?

**Comment by tony19** [comment]
That works. Thanks

**Comment by espadrine** [comment]
I'll make that error less easy to make by removing the maxAge from the dialog on the front page.
