### ISSUE TITLE
Link as href for icon

### ISSUE THREAD

**Issue by buckle2000** [badges/shields#760]
Now we can do this:
`?logo=data:image/png;base64,…`
But if I want to use a link as icon,
`?logo=http://example.com/favicon.ico`
shields.io will automatically add `data:` in front of it in _svg_.
Can you remove this "feature"?

PS: I also tried `http%2A//`

**Comment by espadrine** [comment]
What would you have it do? Shields could download it and provide it as data:, but the file size could be arbitrarily large, causing stain on the server that would be hard to mitigate. It could pass the request through, but then the downloaded image would no longer work, for the user, like a normal image: it would force the user's browser to download something, causing risks of user tracking and ddos. Plus, non-svg images would be broken.

Obviously, we can't allow all prefixes, like file: which would leak user information to Shields, and http: which would risk causing mixed content in an HTTPS website (the browser would then show the security as compromised).

**Comment by buckle2000** [comment]
I want to just insert the link into svg image, so user's browser to download it.
Sure, there maybe user tracking and ddos problems, but it depends on how people use shields.io
what about only allowing logo with https prefix?

**Comment by espadrine** [comment]
Well, there's also the issue of CORS and CSP. For instance, GitHub's https://github.com/atmos/camo will block https links in images: https://github.com/atmos/camo/blob/master/server.coffee#L43
In that case, there will be a blank instead of the logo appearing.

**Comment by espadrine** [comment]
And there is still the issue of non-svg images, wherein the server will be forced to download the image, which is of arbitrary size, which is hard to design for, hard to  sysadmin, hard to scale. Right now, the conversion to PNG process is only limited in cpu time, not memory, and it does not have much memory left to play with anyway.

**Comment by buckle2000** [comment]
What about only allowing image reference with svg but not png and etc.?

**Comment by calebcartwright** [comment]
This has been discussed ad nauseam but we seem to always forget to close the issue. Closing now, as our posture has been conveyed in multiple places: we aren't going to support this request
