### ISSUE TITLE
shields.io is down with HTTP 503

### ISSUE THREAD

**Issue by AmauryOrtega** [badges/shields#7607]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The website shields.io and image URLs for img.shields.io are both down. They both provide the same generic Heroku's application error and HTTP 503

### 💡 Possible Solution

Check logs at Heroku to identify problem

**Comment by SynthesisDu** [comment]
similar issue

https://shields.io/category/coverage Shows this:

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by AmauryOrtega** [comment]
Exactly the same message I got when accessing the main website and the
badge URLs

**Comment by chris48s** [comment]
now resolved

**Comment by AmauryOrtega** [comment]
Thank you! Are there insights into what happened?
