### ISSUE TITLE
Shield.io Down

### ISSUE THREAD

**Issue by nxtexe** [badges/shields#7610]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All of my shields.io badges aren't loading in my README.md. When I checked the badge URL I saw a Heroku Application Error. Same thing on [main page](https://img.shields.io). Not exactly an issue but bringing this to your attention since there's nothing I can really do to help. This seems to be a hosting issue.

### 🔗 Link to the badge

https://img.shields.io/npm/v/react-motion-router

### 💡 Possible Solution

Check the logs on your Heroku app for details on the error.

**Comment by chetanrakheja** [comment]
Was getting Same Error

**Comment by SynthesisDu** [comment]
similar issue

https://shields.io/category/coverage Shows this:

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by talwat** [comment]
I looked at some other apps with Heroku and they seem to be working... I wonder what the issue is?

**Comment by nxtexe** [comment]
Looks like it's back up now. Closing this issue.
