### ISSUE TITLE
Not working with Jenkins when job is in folder

### ISSUE THREAD

**Issue by marekwasielewski** [badges/shields#762]
I can`t get build badges on Jenkins when job is in folder. I have Jenkins ver. 2.7.2 server on Windows. My api url looks like this:
JENKINS_URL/job/FOLDER_NAME/job/JOB_NAME/api/json 
Is there some way to generate build badge?

**Comment by DarthGandalf** [comment]
I've managed to forge the URL by studying the source... It inserts `/job/` before the last JOB_NAME, so this works:
`https://img.shields.io/jenkins/s/https/JENKINS_URL/job/FOLDER_NAME/JOB_NAME.svg`
With more nested folders, it would be `URL/job/FOLDER1/job/FOLDER2/NAME.svg`

But I consider this a hack.

**Comment by marekwasielewski** [comment]
Now it works.
Thanks.
