### ISSUE TITLE
Hex.pm badges display "invalid response data" when a package has never had a stable release

### ISSUE THREAD

**Issue by Fs00** [badges/shields#7658]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hex.pm badges display the "invalid response data" error when a package has only unstable (beta/rc) releases and no stable releases.
Ideally, the badge should fallback to showing the latest unstable release when there are no stable releases.

### 🔗 Link to the badge

https://img.shields.io/hexpm/v/prima_opentelemetry_ex.svg
![](https://img.shields.io/hexpm/v/prima_opentelemetry_ex)

### 💡 Possible Solution

Currently, the badge looks at the `latest_stable_version` field returned by Hex.pm API to retrieve the latest version.
When that field is null, such as [in this example](https://hex.pm/api/packages/prima_opentelemetry_ex), the badge could look at the `latest_version` field.

**Comment by PyvesB** [comment]
Thanks for reporting this @Fs00 , we'll get a fix landed soon!
