### ISSUE TITLE
Icon request: GitHub Star

### ISSUE THREAD

**Issue by tianyuanhao** [badges/shields#7683]
We should have a "Star" icon here. Simple Icons only collects brand icons, so I submit the request here.

Here is the SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill="#eac54f" fill-rule="evenodd" d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25z"/></svg>
```

Here's what it looks like:
[![](https://img.shields.io/badge/Starware-eac54f?labelColor=gray&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PHBhdGggZmlsbD0iI2VhYzU0ZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCAuMjVhLjc1Ljc1IDAgMCAxIC42NzMuNDE4bDEuODgyIDMuODE1IDQuMjEuNjEyYS43NS43NSAwIDAgMSAuNDE2IDEuMjc5bC0zLjA0NiAyLjk3LjcxOSA0LjE5MmEuNzUuNzUgMCAwIDEtMS4wODguNzkxTDggMTIuMzQ3bC0zLjc2NiAxLjk4YS43NS43NSAwIDAgMS0xLjA4OC0uNzlsLjcyLTQuMTk0TC44MTggNi4zNzRhLjc1Ljc1IDAgMCAxIC40MTYtMS4yOGw0LjIxLS42MTFMNy4zMjcuNjY4QS43NS43NSAwIDAgMSA4IC4yNXoiLz48L3N2Zz4=)](https://github.com/zepfietje/starware)

**Comment by calebcartwright** [comment]
Thank you for reaching out with your suggestion, but I'm going to close as this doesn't really fit with our strategy around logos as documented [here](https://github.com/badges/shields/blob/master/doc/logos.md) and on the Shields.io site.

As demonstrated in your issue description, the end result can already be obtained via our existing `customLogo` feature and there's no need for us to try incorporate yet another logo we'd have to maintain (we're trying to get rid of the couple we have left)
