### ISSUE TITLE
Simple Icons or custom Shields logos?

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#7684]
As you may already be aware, Shields.io supports adding logos to badges by leveraging the [Simple-Icons project](https://github.com/simple-icons/simple-icons). However, it still maintains a small set of custom icons, which can be found in [this directory](https://github.com/badges/shields/tree/6e803367e0f3c8e0cc4196a700af37fac1629f4d/logo). We decided to keep these as they were deemed nicer than the Simple Icons versions at the time (see #2510 for the full history).

In #6208, we've been discussing whether we should get rid of the remaining icons, and fully rely on Simple Icons. Reasons for considering a removal include the following:
* many Simple Icons have improved. Their 2022 versions arguably look better than the ones that had led us to prefer our custom logos back in 2018.
* we're keen on simplifying things on the Shields.io side, in terms of the code on the startup path that handles logo loading and in terms of codebase maintenance. My estimate is that we'd be able to shred a few dozen lines of bespoke code.
* we want to make things easier and reduce confusion for users. In particular, one caveat is that our custom icons do not work in conjunction with the `logoColor` query parameter. Users occasionally open issues about this (e.g. #6208, #7576).
* users can still fall back to the old custom logos by using our `logo` parameter with a base64-encoded image.

However:
* some of our custom logos still arguably look better than the 2022 Simple Icons ones.
* retaining the ability to add new custom logos that are different or don't exist in Simple Icons might come in handy at some point in the future.
* our custom Travis icon is too large and cannot be used as is as a base64-encoded image.

The main point of debate is aesthetics, and it's a highly subjective matter. If you have badges that use one of our custom logos listed below, we're keen on hearing what you think! For each logo that I'll be posting in follow up messages, either add 🎉 if you prefer the custom Shields.io version, a 🚀 if you prefer the Simple Icons version, or 👀 if you're undecided. If you don't use or intend on ever using some of the listed logos, you can simply skip voting on those.

A logo with a majority of votes in favour of the Simple-Icons version will be considered for removal from the Shields.io codebase. If there is a significant drive towards Simple-Icons for several logos, we'll discuss whether visual concerns for the remaining ones outweigh the gains that could be achieved by a full removal. We'll examine the votes carefully to inform our decisions, but the maintainer team will be responsible for making the final call.

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| bitcoin | ![](https://img.shields.io/badge/shields-bitcoin-blue?logo=bitcoin) | ![simple-icons bitcoin](https://user-images.githubusercontent.com/10694593/152679199-4891cc78-d555-4a79-9fe6-e2f33b1be60b.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| dependabot | ![](https://img.shields.io/badge/shields-dependabot-blue?logo=dependabot) | ![simple-icons dependabot](https://user-images.githubusercontent.com/10694593/152679242-4bcdf9e2-c6af-4294-9f3c-af7b1f991780.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| gitlab | ![](https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab) | ![simple-icons gitlab](https://user-images.githubusercontent.com/10694593/152679253-0a66c854-b9e9-4916-a359-8a392c976ffa.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| npm | ![](https://img.shields.io/badge/shields-npm-blue?logo=npm) | ![simple-icons npm](https://user-images.githubusercontent.com/10694593/152679265-20900643-d127-430e-946f-b2994b80e9bb.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| paypal | ![](https://img.shields.io/badge/shields-paypal-blue?logo=paypal) | ![simple-icons paypal](https://user-images.githubusercontent.com/10694593/152679285-7ead6cda-96e3-4dd4-ae85-26b9a5614985.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| serverfault | ![](https://img.shields.io/badge/shields-serverfault-blue?logo=serverfault) | ![simple-icons serverfault](https://user-images.githubusercontent.com/10694593/152679306-da4a573a-9920-42bf-828b-e5c05a77c857.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| stackexchange | ![](https://img.shields.io/badge/shields-stackexchange-blue?logo=stackexchange) | ![simple-icons stackexchange](https://user-images.githubusercontent.com/10694593/152679327-5cf5821f-c2fc-4683-bd77-4148e47623ca.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| superuser | ![](https://img.shields.io/badge/shields-superuser-blue?logo=superuser) | ![simple-icons superuser](https://user-images.githubusercontent.com/10694593/152679413-9b9789f0-69dc-4640-9702-29adddad9371.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| telegram | ![](https://img.shields.io/badge/shields-telegram-blue?logo=telegram)| ![simple-icons telegram](https://user-images.githubusercontent.com/10694593/152679342-cfe171f9-2036-4020-a189-10d9ba3e4752.svg) |

**Comment by PyvesB** [comment]
| Logo                 | Shields.io 🎉        | Simple-Icons 🚀  |
| -----------------|:--------------------|:--------------------|
| travis-ci | ![](https://img.shields.io/badge/shields-travis--ci-blue?logo=travis) | ![simple-icons travis-ci](https://user-images.githubusercontent.com/10694593/152679491-bd92a34a-8ffc-4fbd-a69d-3a8ec920dcb3.svg) |

**Comment by mondeja** [comment]
Hi, I'm a maintainer of the simple-icons project. Do you have considered to accept an array of colors to fill closed or inferred closed subpaths, just in same the order that are defined them? I'm aware that you probably are not yet faimliarized with the internal of SVG `path[d]` commands, in that case just let me know.

**Comment by dtaivpp** [comment]
"as they were deemed nicer" - while I appreciate that several of them might look nicer however I want to ask are they explicitly brand compliant? If not then are the ones maintained by the simply icons project brand compliant (@mondeja)? 

As a contributor to an open source project I know that is generally one of our biggest concerns.

**Comment by dtaivpp** [comment]
@calebcartwright  as I see it the only reason that people want to keep the ones here is because the other ones aren't brand compliant, so it is part of the issue. Maybe people really do have a preference on which is hosted where but from what you have described the issue seems to be that people want the correct icons which simple icons doesn't have all of at the moment.

**Comment by calebcartwright** [comment]
> @calebcartwright as I see it the only reason that people want to keep the ones here is because the other ones aren't brand compliant, so it is part of the issue

Appreciate your willingness to share your opinion, but it's not so I'm going to minimize these last comments as off topic. If you'd like to comment on brand compliance or categorically paint why people would want one icon or another there are better places to share that perspective, but it's not this issue.

**Comment by davidmpaz** [comment]
Hi,

I came to this thread cause the issue linked just above. So these are my 5 cents, for me was useful the fact that all icons would look consistently, same theme so to speak, I wanted to avoid a colourful table full of badges of different colours.

Hope it helps,
Cheers and thanks,
David

**Comment by regseb** [comment]
I propose this rules which should satisfy everyone:

- without `logoColor` query parameter: display [custom Shields logo](https://github.com/badges/shields/tree/22380c5e9435e2a59e236d2a58ff55d1db7c8f1e/logo) multiple colors;
- with `logoColor` query parameter: display [Simple Icon](https://github.com/simple-icons/simple-icons) by changing the color.

If you want:

- custom Shields logo multiple colors: `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab`
- Simple Icon with the default color (you must specify it): `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab&logoColor=FC6D26`
- Simple Icon with specific color: `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab&logoColor=white`

**Comment by regseb** [comment]
I open a **pull request #8263** to my [previous message](https://github.com/badges/shields/issues/7684#issuecomment-1171086881):

- without `logoColor` query parameter: display custom Shields logo multiple colors;
- with `logoColor` query parameter: display Simple Icon by changing the color.

**Comment by calebcartwright** [comment]
I appreciate everyone's willingness to share their feedback! However, I want to gently remind everyone that this issue is simply a poll with one specific question.

This is just one, small part of a broader set of discussions (the links to which can be found above), and here we're really trying to get a pulse on our user's binary subjective sentiment/preference between the respective icon pairs. We pulled out this one particular part of the broader discussion into a dedicated issue to make it easier to have a focused poll on tha tone topic.

However, we'd really like to avoid bifurcating discussions or repeating/diving into those other topics and data points here in this poll. Anyone and everyone is always free to join participate in conversations in our community, but if you'd like to address something beyond the "I personally prefer the custom logo" or "I personally prefer the SimpleIcons logo" question of this poll, then that feedback would be best directed elsewhere, such as #6208

**Comment by chris48s** [comment]
We've just merged and deployed #8263 which implements a compromise for this:

In cases where we hold a custom (multi-coloured) logo, that one will be used in preference to SimpleIcons.
If the `logoColor` param is passed, the SimpleIcons logo will be used and the `logoColor` applied.
For example:

- ![multiple](https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab) custom Shields logo multiple colors: `https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab`
- ![orange](https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab&logoColor=FC6D26) Simple Icon with the default color (you must specify color): `https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab&logoColor=FC6D26`
- ![white](https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab&logoColor=white) Simple Icon with specific color: `https://img.shields.io/badge/logo-gitlab-blue?logo=gitlab&logoColor=white`

This does represent a behaviour change for any existing badges using a custom logo with `logoColor` specified (previously this was ignored), but we think this represents the best compromise. Thanks to @regseb for this solution.

**Comment by PyvesB** [comment]
In light of the above compromise and given the survey results, I'll go ahead and close this for the time being.

**Comment by PyvesB** [comment]
Worth noting that the Gitlab and Paypal logos have since then been updated on the Simple-Icons side (https://github.com/simple-icons/simple-icons/pull/7364 and https://github.com/simple-icons/simple-icons/pull/9579), and should be more legible and appealing when used on a Shields.io badge. Above tables do not reflect the latest status.
