### ISSUE TITLE
Discord user

### ISSUE THREAD

**Issue by JoshPaulie** [badges/shields#7694]
:clipboard: **Description**

A badge that redirects you to a discord user, not a server.

:link: **Data**

https://discordapp.com/users/177131156028784640
Here is mine, for example. The syntax is `https://discordapp.com/users/<discord_user_id>`

:microphone: **Motivation**

I would like for people to be able to reach out to me directly, instead of a public discord server.

**Comment by chris48s** [comment]
The existing discord badge doesn't include a link - you could wrap in in a link to a user if you wanted, just as you could wrap any other badge with that link. For example:

```markdown
[![discord](https://img.shields.io/badge/contact-me-blue?logo=discord&logoColor=white)](https://discordapp.com/users/177131156028784640)
```

[![discord](https://img.shields.io/badge/contact-me-blue?logo=discord&logoColor=white)](https://discordapp.com/users/177131156028784640)

Unless it needs some dynamic data, this doesn't require a new badge

**Comment by JoshPaulie** [comment]
Oh I understand now. That's my bad, thanks for the explanation and for correcting the tag.
