### ISSUE TITLE
CodeClimate badges returning "Invalid response data" for one repo

### ISSUE THREAD

**Issue by SolalPirelli** [badges/shields#7695]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I help run a software development course in which we provide [a dashboard for the code quality of all teams](https://dslab.epfl.ch/teaching/sweng/proj#projects-dashboard).
One, and only one, team currently has badges that return "Invalid response data" despite CodeClimate being set up properly.
This was also happening to another team on Sunday, but starting Monday only one team has this issue.
FWIW, we set up those badges before some of the teams had fully set up their repos, so perhaps there's some caching issue, but I would not expect errors to be cached >24h.

### 🔗 Link to the badge

![](https://img.shields.io/codeclimate/maintainability/swift-wallet/sdp2022?label=&style=for-the-badge)

![](https://img.shields.io/codeclimate/coverage/swift-wallet/sdp2022?label=&style=for-the-badge)

For comparison, working ones:

![](https://img.shields.io/codeclimate/maintainability/PalFinderTeam/palFinder?label=&style=for-the-badge)

![](https://img.shields.io/codeclimate/coverage/PalFinderTeam/palFinder?label=&style=for-the-badge)

**Comment by chris48s** [comment]
I haven't had a chance to properly look at this, but if anyone else comes to it, this is failing with `ValidationError: "data" must contain less than or equal to 1 items` when we call https://api.codeclimate.com/v1/repos?github_slug=swift-wallet%2Fsdp2022

**Comment by PyvesB** [comment]
The API response for the Swift Wallet team contains two elements in the data array. We're being a bit restrictive and only expecting one:
https://github.com/badges/shields/blob/53cb1da830900697e61b58f6780f9e632504a397/services/codeclimate/codeclimate-common.js#L10

In this case, one of the two elements contains the id we're looking for, the other doesn't. We'll need to change our implementation to loop through all elements, and find one that does contain `latest_default_branch_snapshot` or `latest_default_branch_test_report` data, respectively for the analysis and coverage badges.

I'll aim at picking this up during the weekend if no one does in the meantime.
