### ISSUE TITLE
PyPI version returns "invalid response data"

### ISSUE THREAD

**Issue by stephane-caron** [badges/shields#7728]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The version number is not found for the [lpsolvers](https://github.com/stephane-caron/lpsolvers) package on PyPI.

(Alternatives such as [this one](https://badge.fury.io/py/lpsolvers.svg) find the version number without any issue.)

### 🔗 Link to the badge

https://img.shields.io/pypi/v/lpsolvers → ![pypi invalid response data](https://user-images.githubusercontent.com/1189580/158545170-3108fb5c-c23f-41f2-998b-8317d6837d97.svg)

**Comment by chris48s** [comment]
This is failing with `[ValidationError: "info.license" must be a string]` because license is `null` in https://pypi.org/pypi/lpsolvers/json
I guess we need to split the schema so license is only required for license badges.

**Comment by stephane-caron** [comment]
Interesting, the license field used to be ``""`` but it has become `null` in the past 10 days or so. Either the behavior changed on PyPI or on [Flit](https://flit.readthedocs.io/en/latest/index.html) after an update. On March 5 the old behavior was still in place, as seen e.g. in this badge:

![qpsolvers](https://img.shields.io/pypi/v/qpsolvers)
