### ISSUE TITLE
Uptime Robot status badges saying "inaccessible" but hosts are up

### ISSUE THREAD

**Issue by pflegende** [badges/shields#7729]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

# Uptime Robot status badges saying "inaccessible"

### How is the issue described?

The hosts are operating and accessible.
This issue was seen on 5 different hosts on different continents from different hosters/providers.

Sometimes it works. Sometimes doesnt.
Today (2022-mrt-17) we see delays of 30 sec to 2 Min

Worked as we saw, some months without such behavior.
Today we 1st noticed the issue.

We waited some hour to send the issue.
So we do it
`17.3.2022, 19:12:50`
 now ...

:)

### operational repo affected by the issue

https://github.com/pflegende/agatab

you find the badges by C-f "operation"

### data of the badges

```

![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790129794-6d88280073c87ef883c7bd36?label=DP_WP)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130194-21af5e9a1aa0d99994111d1e?label=scotch)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130241-dc96a8abd23bf4f3b4ea8d51?label=ether)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130295-6aafb2b5815657c62fb1af37?label=bmk)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130965-192d351d97c75b777fe68ebd?label=alparis)
```
 

### 🔗 Link to the badge

![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790129794-6d88280073c87ef883c7bd36?label=DP_WP)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130194-21af5e9a1aa0d99994111d1e?label=scotch)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130241-dc96a8abd23bf4f3b4ea8d51?label=ether)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130295-6aafb2b5815657c62fb1af37?label=bmk)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130965-192d351d97c75b777fe68ebd?label=alparis)

### 💡 Possible Solution

sorry, not a suggestion in my mind.
dont hesistate to call for support and testing 

:)

**Comment by pflegende** [comment]
17.3.2022, 19:19:15

now after posting 3 badges show "up":

![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790129794-6d88280073c87ef883c7bd36?label=DP_WP)
now up ![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130194-21af5e9a1aa0d99994111d1e?label=scotch)
![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130241-dc96a8abd23bf4f3b4ea8d51?label=ether)
now up ![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130295-6aafb2b5815657c62fb1af37?label=bmk)
now up ![Uptime Robot status](https://img.shields.io/uptimerobot/status/m790130965-192d351d97c75b777fe68ebd?label=alparis)

**Comment by pflegende** [comment]
Seems we hasnt wait long enough ...
Now all show "up".

`17.3.2022, 19:24:14`

**Comment by pflegende** [comment]
---
To save your time, we close the problem.
---

**Comment by GoudronViande24** [comment]
Hi, I currently have a similar problem:
The badge says unavailable even if it shows online in UptimeRobot dashboard.
It shows online if I do not provide a label option in the badge URL, which is kind of weird...

**Comment by calebcartwright** [comment]
We display whatever the upstream provider, UptimeRobot in this instance, provides. Also remember that we have a cache layer, and the various other components along the way (including your browser) will cache content as well. 

> It shows online if I do not provide a label option in the badge URL, which is kind of weird...

Changing the label (and yes, not providing a custom label query parameter == a different/changed label) produces a different badge, which won't already be cached.
