### ISSUE TITLE
After clicking a badge on the website, it's not clear what to do

### ISSUE THREAD

**Issue by techtonik** [badges/shields#777]
Current interface for AppVeyor is not intuitive:

![cropped](https://cloud.githubusercontent.com/assets/515889/17921620/7404b2cc-69e3-11e6-9c6b-b226f79f9cc6.png)

Much better interface would be to accept "AppVeyor Link", such as https://ci.appveyor.com/project/techtonik/hexdump, parse it on modify, and allow to adjust parsed information, such as target link for it.

**Comment by paulmelnikow** [comment]
Let's track this in #2496.
