### ISSUE TITLE
Badge issue 

### ISSUE THREAD

**Issue by mig-25** [badges/shields#778]
I have linked a badge for codecov from shields.io
It works in the browser and on the shields.io page but github shows it as a broken link :(

This is my shields.io code:

`[![Codecov](https:/codecov.io/github/mig-25/Canis-familiaris/badge.svg?style=flat-square)](https://codecov.io/gh/mig-25/Canis-familiaris)`

What am I missing here?

**Comment by paulmelnikow** [comment]
That's not a shields.io link. Could you report that issue to Codecov.io instead?
