### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by SKY-ALIN** [badges/shields#7785]
Service is not available since yesterday.
[shields.io](https://shields.io/) and [img.shields.io](https://img.shields.io/) are down and show this message:

---

### Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command `heroku logs --tail`

---

**Comment by Nishant1500** [comment]
Its back up and working fine now :D

**Comment by SKY-ALIN** [comment]
Thanks 🙏
