### ISSUE TITLE
The service is down and all badges broken

### ISSUE THREAD

**Issue by Keith-CY** [badges/shields#7787]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The homepage is down
![image](https://user-images.githubusercontent.com/7271329/160970973-48a5e29c-2bd9-4c5f-95c7-0572a23135e9.png)

All badges are broken
![image](https://user-images.githubusercontent.com/7271329/160971278-aa9f1ba2-e686-458c-9c5f-900306db3e54.png)

**Comment by Nishant1500** [comment]
It's up now :D
