### ISSUE TITLE
maintenance status always no

### ISSUE THREAD

**Issue by lcnittl** [badges/shields#7882]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The maintenance badge shows "no", independent of the used URL (yes/no)

Can also be observed here:
https://github.com/badges/shields/issues/7242#issuecomment-962503073

Cheers, lcnittl

### 🔗 Link to the badge

https://img.shields.io/maintenance/yes/2021
![maintained: yes](https://img.shields.io/maintenance/yes/2021)

https://img.shields.io/maintenance/no/2021
![maintained: no](https://img.shields.io/maintenance/no/2021)

**Comment by calebcartwright** [comment]
Not quite sure what you mean when you say "independent of the url". Given that the current year, as of the time of this post, is 2022 any prior years are expected to display "no".

https://img.shields.io/maintenance/yes/2022
![](https://img.shields.io/maintenance/yes/2022)

https://img.shields.io/maintenance/yes/2023
![](https://img.shields.io/maintenance/yes/2023)

https://img.shields.io/maintenance/no/2022
![](https://img.shields.io/maintenance/no/2022)

**Comment by lcnittl** [comment]
Ah, I see - seems I had not understood the exact functionality. Thanks for the explanation!

**Comment by calebcartwright** [comment]
No worries, thanks for reaching out!
