### ISSUE TITLE
GitHub Gist "last commit" Badge

### ISSUE THREAD

**Issue by smeinecke** [badges/shields#7884]
:clipboard: **Description**

A badge for the latest update on a GitHub gist would be nice.
Right now it's possible to add a custom badge that shows the full date, but that does not change color based on freshness or shows a short DateTime.

Custom Bade example: 
![GitHub last update](https://img.shields.io/badge/dynamic/json?color=lightgray&style=flat&label=last%20update&query=%24.updated_at&url=https%3A%2F%2Fapi.github.com%2Fgists%2F4401361&cacheSeconds=86400)

Normal "Latest commit" badge:
![GitHub last commit](https://img.shields.io/github/last-commit/disposable/static-disposable-lists)

:link: **Data**

Github API: https://docs.github.com/en/rest/gists/gists#get-a-gist
`updated_at` field.

:microphone: **Motivation**

Would like to present the "freshness" of a list as it gets updated every now and then:

https://github.com/disposable/disposable#external-sources

**Comment by PaulaBarszcz** [comment]
It seems that it already works:

`![1.3.0](https://img.shields.io/github/last-commit/badges/shields/1.3.0)`
![1.3.0](https://img.shields.io/github/last-commit/badges/shields/1.3.0)

--
`![master](https://img.shields.io/github/last-commit/badges/shields/master)`
![master](https://img.shields.io/github/last-commit/badges/shields/master)

--
`![integration-docs](https://img.shields.io/github/last-commit/badges/shields/integration-docs)`
![integration-docs](https://img.shields.io/github/last-commit/badges/shields/integration-docs)

--
`![server-2021-10-04](https://img.shields.io/github/last-commit/badges/shields/server-2021-10-04)`
![server-2021-10-04](https://img.shields.io/github/last-commit/badges/shields/server-2021-10-04)


Print screen for posteriority:
![image](https://user-images.githubusercontent.com/31891675/181460591-45c5cc4c-cacc-4015-9b2c-aaf4b7459352.png)


@chris48s  Can this issue be closed? :)

**Comment by chris48s** [comment]
The examples you've posted there are all last commit for a _repo_ . This feature request is last commit for a _gist_ (which is a different thing)

**Comment by PaulaBarszcz** [comment]
True @chris48s, thanks for pointing it out!
I would like to work on this issue :)

**Comment by chris48s** [comment]
Feel free. All the info needed is in the top post. Thanks

**Comment by PaulaBarszcz** [comment]
This issue can be closed thanks to the #8272 sitting already happily on master. Thanks :)
