### ISSUE TITLE
Bitbucket open pull requests badge

### ISSUE THREAD

**Issue by chapulina** [badges/shields#789]
Similar to issue #626, but for open pull requests, like the ones for GitHub.

Using the v2 API:

https://bitbucket.org/api/2.0/repositories/{accountname}/{repo_slug}/pullrequests/?limit=0&state=OPEN

**Comment by qzb** [comment]
It's quite easy to implement, but what's the point of creating pull request since it wouldn't be merged anyway. This project is half-dead, apparently @espadrine doesn't have time for maintaining it anymore and there is no other people with permissions to merge PR.

**Comment by chapulina** [comment]
Oh I wasn't aware of the project status... It seemed to me that it would take a long time but it would eventually be merged. 

That's disappointing... We were looking forward to have this feature without needing to host it ourselves. Do you know of a nice alternative? Thanks!

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion. I joined up a few weeks ago. There is a big backlog of issues and PRs, but I'm [reviewing and merging at a steady clip](https://github.com/badges/shields/pulse) and Thaddée is deploying the changes. If you'd like to get involved, let me know!

And certainly, please do open a PR for the bitbucket badge.

**Comment by chapulina** [comment]
Added on pul request #790
