### ISSUE TITLE
add [PUB] popularity badge

### ISSUE THREAD

**Issue by G1Joshi** [badges/shields#7919]
![PUB Popularity](https://img.shields.io/badge/popularity-100%25-brightgreen)

:clipboard: **Description**

- This badge is for `Dart/Flutter` packages/plugins.
- This badge shows the pub popularity for packages/plugins.

:link: **Data**

- There is a public API for this data i.e `https://pub.dev/api/packages/<packageName>/score`.
- This API doesn't require an API key and returns a JSON object.

:microphone: **Motivation**

- This badge is a measure of how many developers use a package.
- This provides insight into what other developers are using.

**Comment by sambhav2358** [comment]
jhbß˚jxvnßkxvnzsdiugxkfjnzsiufkjdnwisakfjdn
