### ISSUE TITLE
Restore or replace Heroku Review Apps

### ISSUE THREAD

**Issue by chris48s** [badges/shields#7924]
:clipboard: **Description**

Until https://status.heroku.com/incidents/2413 happened we were using Heroku review apps to build a preview site for each PR. This was a big help for reviewing contributions and dependency bumps.

The latest update from Heroku is

> For the protection of our customers, we will not be reconnecting to GitHub until we are certain that we can do so safely, which may take some time. We recommend that customers use alternate methods rather than waiting for us to restore this integration.
> 
> The simplest approach to deploy Heroku apps is directly using [git push heroku main](https://devcenter.heroku.com/articles/git). Alternatively, you can refer to one of the add-ons listed in the Continuous Integration and Delivery section of the [Heroku Ecosystem Marketplace](https://elements.heroku.com/addons#ci-cd) or other third party CI/CD products that offer Heroku support, such as [Circle CI](https://circleci.com/integrations/heroku/). You can also use community-maintained integrations such as [this GitHub Action for deploying to Heroku](https://github.com/AkhileshNS/heroku-deploy).
> 
> We sincerely regret any inconvenience you may have experienced because of this issue and appreciate your trust in us as we continue to make your success our top priority. Please continue to visit [status.heroku.com](https://status.heroku.com/incidents/2413) for the latest updates.

The key phrase there for me is:

> **We recommend that customers use alternate methods rather than waiting for us to restore this integration**

Investigate how we could re-enable review apps, either using Heroku via some other avenue or by migrating away from Heroku. One possible thing we could look at is https://github.com/superfly/fly-pr-review-apps

**Comment by calebcartwright** [comment]
One of the challenges I think we'd run into with the Fly review apps model is that it's predicated on having a GitHub Actions secret available, but those are disabled and unavailable on PRs coming from forks for security reasons

**Comment by calebcartwright** [comment]
https://blog.heroku.com/github-integration-update (some progress but still not resolved)

**Comment by chris48s** [comment]
Good find and good point about the fly review apps. I think in the short term re-enabling Heroku review apps when they enable github deploys again is probably the play.

@SnoozeThis wait until May 26 2022

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/X6ov_cwqaA8) I will wait until Thu, 26 May 2022 00:00:00 UTC and then add a comment.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by chris48s** [comment]
https://blog.heroku.com/github-integration-update

**Comment by chris48s** [comment]
partially done in

https://github.com/badges/shields/pull/8213#issue-1311675359

but not really

**Comment by calebcartwright** [comment]
I know we've discussed already, but it continues to surprise me that the review apps for squint just continue to work while the ones for shields are all out of whack :man_shrugging:  (e.g. https://github.com/badges/squint/pull/111)

**Comment by chris48s** [comment]
Presumably we also had to re-connect the squint ones after the long heroku security outage. I wonder if we did anything differently?

**Comment by calebcartwright** [comment]
That's the thing, I didn't. Squint just started working

**Comment by chris48s** [comment]
Haunted. No other explanation.

**Comment by calebcartwright** [comment]
:ghost:

**Comment by chris48s** [comment]
Looks like our review apps are now failing with `code=H82 desc="Free app running time quota exhausted"`
