### ISSUE TITLE
Question and other marks are not displayed

### ISSUE THREAD

**Issue by JTorresConsulta** [badges/shields#7925]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I am trying to pass in the image text a question mark.  "?"
Obviously it is not shown because it is used to define parameters in the URL get

They don't work either:

HTML Entity:	&#63; &#x3F; &quest;
UTF-8 Encoding:	0x3F
UTF-16 Encoding:	0x003F

### 🔗 Link to the badge

https://img.shields.io/badge/SERVER-PRIVATE&#63;-1?style=for-the-badge&logo=&logoColor=white&color=000

https://img.shields.io/badge/SERVER-PRIVATE0x003F-1?style=for-the-badge&logo=&logoColor=white&color=000

### 💡 Possible Solution

Integrate in your server a function that detects an especial code for some symbols that url cant have.
For example:  +q+ for question mark

Love and thanks  <3

**Comment by chris48s** [comment]
You need to use URL encoding: `%3F`
example: https://img.shields.io/badge/questionmark-%3F-blue
