### ISSUE TITLE
Support bitbucket for coveralls badges

### ISSUE THREAD

**Issue by satazor** [badges/shields#793]
Coveralls added support for bitbucket last year.

The badge URL looks like this: https://coveralls.io/repos/bitbucket/schinckel/django-boardinghouse/badge.svg?branch=coverage-badge

Looking at the code, it seems that `shields` is using `badges.coveralls.io` which doesn't support bitbucket apparently. In order to support bitbucket, the code needs to fetch the above URL instead.

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this.

Would you like to open a pull request?

**Comment by piekar294** [comment]
i would like to work on this feature

**Comment by paulmelnikow** [comment]
Excellent! Feel free to post in this issue if you have any questions.
