### ISSUE TITLE
NuGet tags displaying unlisted package for newest version

### ISSUE THREAD

**Issue by ThadHouse** [badges/shields#795]
I made a mistake with one of my projects, which made a specific version have an extra high version number. I unlisted the package, however my shield for NuGet now always shows that version, and since it is a much higher version number then I will ever use, I can't just use a higher version number.

Here is my NuGet repo, which only shows the 3.0 packages
https://www.nuget.org/packages/FRC.NetworkTables.Core/

However for my readme (look at the (Core) one), 2017 shows up even though I have unlisted 2017 from NuGet
https://github.com/robotdotnet/NetworkTables/blob/master/Readme.md

**Comment by ThadHouse** [comment]
Oh whoops. I searched issues but not PR's. Looks like #769 fixes this issue. Any idea when that is going to get merged?

**Comment by pshort** [comment]
I too have an interest in this getting merged, my lib is showing 1.0.0 instead of 0.1.18 because of a silly appveyor incident. :S

**Comment by ThadHouse** [comment]
So I think I made a mistake closing this issue since it still needs to be fixed, so reopening it.

**Comment by vip32** [comment]
ran into the same issue. now the shields are displaying unlisted packages :( 
hopefully maartens (https://github.com/badges/shields/pull/769) PR will fix this

**Comment by kbrimble** [comment]
I have the same problem. Hopefully #769 will be merged soon 🤞

**Comment by espadrine** [comment]
Thanks for reporting this issue! I started reviewing the patch; unfortunately it needs a bit of work.
