### ISSUE TITLE
Facebook Page likes and Group member count

### ISSUE THREAD

**Issue by ReenigneArcher** [badges/shields#7980]
:clipboard: **Description**

A badge to show Facebook Group member count would be nice.

:link: **Data**

Without an API the data can be obtained from the webpages.
**Page**
Example page url: https://www.facebook.com/RetroArcherFB
The page likes can be found between the word `text` and `likes`... e.g. `"text":"30 likes"`

**Group**
Example group url: https://www.facebook.com/groups/retroracher
The member count follows this text: `formatted_count_text`

Facebook also has an API which would probably be better than using regex, although more complicated to get going initially.

Graph API docs: https://developers.facebook.com/docs/graph-api

It requires a token, which does expire; however, here is method to obtain a permanent access token. https://github.com/ReenigneArcher/facebook-post-action#-how-to-get-a-facebook-permanent-access-token

:microphone: **Motivation**

Would extend Shields social badges.
![image](https://user-images.githubusercontent.com/42013603/168926317-35b95fc9-1ef2-4011-bbf8-c7f620063e06.png)

**Comment by calebcartwright** [comment]
Thank you for reaching out and sharing your idea.

Facebook badges have actually been requested on a few prior occasions (#6711, #2120) but had to be rejected due to a combination of rate limiting and overall fit.

I think all of those prior concerns still hold which means we'll likely need to close this as a duplicate

**Comment by chris48s** [comment]
Agreed - I think the rate limit is still a blocker for us

**Comment by ReenigneArcher** [comment]
If anyone finds this looking for the same thing, I have a work around using GitHub actions to cache the response from Facebook's graph api.

I'm using python and here is the relevant code. -> https://github.com/LizardByte/uno/blob/cd723981d20bc907137b77dd1cb11dcef96fcfc2/update.py#L79-L97

![image](https://user-images.githubusercontent.com/42013603/194204538-c7c9bf52-facc-4a4e-a229-25d80cc41738.png)

![image](https://user-images.githubusercontent.com/42013603/194204559-37a5b7ea-e418-4780-8076-1f717313f94a.png)
