### ISSUE TITLE
Cloudflare security challenge breaks badges for non-US locations

### ISSUE THREAD

**Issue by cdiener** [badges/shields#800]
The security settings for cloudflare lead to cases where non-malicious users are presented with a security challenge for shields.io. In image links (meaning the badges) this simply leads to a broken link. Unfortunately, the security settings for shields.io are quite agressive and block many non-US users. For instance from inside a mexican government institution (even though I can get some people might see that as "malicious") shields.io will always present a security challenge...

This should also affect Tor users on a regular basis.

**Comment by paulmelnikow** [comment]
Thanks for this issue. Realize it's been a few months here. Can you clarify whether or not this is still happening? Are there easy steps to test/reproduce?

There's been some other discussion of CloudFlare in #608 and #445.

**Comment by cdiener** [comment]
Thanks for getting back to me. 

No, at the moment the problem does not occur for me anymore. So I think the issue can be closed. I contacted cloudflare a while ago and they stated that some IP ranges from large TelCos are flagged in Mexico, however that gets reverted after clearing security challenges successfully for some time frame.

It might be a problem for TOR users since they will always get security challenges by cloudflare if not explicitly whitelisted.

**Comment by paulmelnikow** [comment]
Feel free to reopen if this recurs, or if there are steps to reproduce using tor.
