### ISSUE TITLE
CircleCI job status

### ISSUE THREAD

**Issue by epassaro** [badges/shields#8002]
:clipboard: **Description**

I would like a badge that displays the result of a certain job of a CircleCI pipeline.

`<circleci logo> job_name | status`

Currently CircleCI badges support only filtering by branch. I'm not sure if this is a limitation coming from the CircleCI API.

:link: **Data**

I don't really know.

:microphone: **Motivation**

**Comment by chris48s** [comment]
Yeah I don't think there is a way we can do this with the Circle CI as it stands.
