### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by karlbateman** [badges/shields#802]
Hey all,
I am working on a pull request and have noticed that [this line](https://github.com/badges/shields/blob/master/test/test.js#L17) is causing an issue. Removing the ellipsis allows the test to run.

``` javascript
assert[k] = function(...args) {
    try {
        assertion[k].apply(null, args);
    } catch(e) { reject(e); }
};
```

Not sure how that managed to sneak in there 🕵️

Regards,
K

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this. The fix is to upgrade to Node 6.

After discussion in #902 we've decided not to support earlier versions.
