### ISSUE TITLE
Website up/down with domain-name

### ISSUE THREAD

**Issue by anionDev** [badges/shields#8023]
:clipboard: **Description**

The usual Website up/down badge markdown-content looks like

```
![Website](https://img.shields.io/website?url=https%3A%2F%2Fexample.com)
```

which results in:
![image](https://user-images.githubusercontent.com/19505692/170861930-8a99e515-b6ff-480f-83b4-e9347e17512f.png)

This is nice but not ideal when you use this badge multiple times (with different domains): You do not know which website is up and which is down.

It seems that changing the text in the square-brackets at the beginning does not have any effect. The left text in the badge is always `website`, it does not seem to be customizable.

It would be nice if we are at least able to set the domain-name as text for the left part to have a badge-text like "example.com | up".

**Comment by calebcartwright** [comment]
You need to use the `?label` query parameter to override the text of the label, e.g. 
https://img.shields.io/website?url=https%3A%2F%2Fexample.com&label=example.com
![Website](https://img.shields.io/website?url=https%3A%2F%2Fexample.com&label=example.com)

**Comment by anionDev** [comment]
This is exactly what I am looking for, thank you very much!
