### ISSUE TITLE
Add startrack badge

### ISSUE THREAD

**Issue by jacobhq** [badges/shields#8028]
:clipboard: **Description**

This badge is for my service Startrack, which provides pages for easy starring of repos as a github oauth app. The badge would provide a link to Startrack's starring page for that repo, which is in this format:
```
https://startrack.vercel.app/star/[OWNER]/[REPO]
```
Here is the URL for a static badge:
```
https://img.shields.io/badge/startrack-star-yellow
```

:link: **Data**

This would be a static badge, so data would not be required.

:microphone: **Motivation**

I'd like people who are using my project to be able to display a badge in their READMEs, and having it listed on shields would be a nice place for them to get it from. This could also increase discoverability.

Thanks so much!

**Comment by calebcartwright** [comment]
Thanks for reaching out but I am going to close.

We do not add native badge routes for static badges.
