### ISSUE TITLE
Bug: Unable to use hyphen in project name

### ISSUE THREAD

**Issue by andreped** [badges/shields#8043]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I wanted to add a download count per month for my PyPI package in the corresponding github repo readme.

However, I was prompted that the package could not be found, which I believe might be because of the hyphen (project name: `gradient-accumulator`).

This problem has been observed by others: https://github.com/badges/shields/pull/7633#issuecomment-1090454711

Where the only solution seem to be to remove the hyphen altogether, which is suboptimal and non-ideal for my projects (which often contains hyphens in their names).

### 🔗 Link to the badge

This counter does not work, as package is not found:
[![Pip Downloads](https://img.shields.io/pypi/dm/gradient-accumulator?label=pip%20downloads&logo=python)](https://pypi.org/project/gradient-accumulator/)

However, this one works just fine:
[![Pip Downloads](https://img.shields.io/pypi/dm/livermask?label=pip%20downloads&logo=python)](https://pypi.org/project/livermask/)

NOTE: I own both these projects.

### 💡 Possible Solution

I believe the problem is that the `gradient-accumulator` project name has a hyphen in it, which does not appear to work in this context. I have tried using double hyphen like so "--" to no avail.

**Comment by calebcartwright** [comment]
Thanks for reaching out and sharing your thoughts, however, I think you're on the wrong track with the hyphens.

Shields is not a system of record. We have to fetch data from the upstream providers, and display what they respond. We use pypistats for pypi downloads, and pypistats is returning a 404 for your `gradient-accumulator` package:

```
$ curl -I https://pypistats.org/api/packages/gradient-accumulator/recent
HTTP/2 404 
server: gunicorn/19.10.0
date: Sun, 05 Jun 2022 23:46:50 GMT
content-type: text/html; charset=utf-8
content-length: 3
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```
Given how new your package is, and the number of packages, without a hyphen in the name, which exhibit the same behavior, I'd guess you're more likely running into something like https://github.com/crflynn/pypistats.org/issues/43

> This problem has been observed by others: https://github.com/badges/shields/pull/7633#issuecomment-1090454711

I appreciate you trying to search for existing issues before opening this, but that's completely unrelated in any shape or form to what you're experiencing with the pypi downloads badge. The conversation in that PR is strictly related to naming conventions on parts of the Shields codebase, like class names/file names, and the static text we choose as our prefix (you can think of that as being analogous to us starting our badge route with `pypi` vs `py-pi`) and has nothing to do with parameters/project names.

**Comment by andreped** [comment]
Just wanted to mention that there was nothing wrong with having a hyphen in the package name. It just took 24 hours (I think) for the download count to be available, which makes sense.
