### ISSUE TITLE
Add Python version badge

### ISSUE THREAD

**Issue by RixInGithub** [badges/shields#8078]
:clipboard: **Description**

This badge is for Python, this badge would show what Python version is a project using; ex.:

![Python release v3.8.12](https://img.shields.io/badge/Python%20release-v3.8.12-blue?logo=python)

:microphone: **Motivation**

- # Compatability
  There ton are differences between Python 3 and Python 2, ex.

  ```py
  print "Python doesn't suck"
  ```

  Would only run in Python 2, where in Python 3 a difference is met:

  ```py
  print("Python doesn't suck")
  ```

  I also discovered that

  ```py
  import Tkinter
  ```

  Can only be ran in Python 2, where in Python 3, all modules need to be lowercase

  And I believe there are many more differences... :snake:

**Comment by DenverCoder1** [comment]
This partially exists already.

If using pipenv (Pipfile.lock):

![image](https://user-images.githubusercontent.com/20955511/173367770-d3a7384e-bf84-4ee1-8257-4e4a550db42c.png) - https://img.shields.io/github/pipenv/locked/python-version/:user/:repo
![image](https://user-images.githubusercontent.com/20955511/173368079-8206b2c3-1fdb-441b-ae10-5074c21d079c.png) - https://img.shields.io/github/pipenv/locked/python-version/:user/:repo/:branch

If using Pypi:

![image](https://user-images.githubusercontent.com/20955511/173368315-4be48428-1600-4bb8-8c8e-13fb6b02b704.png) - https://img.shields.io/pypi/pyversions/:packageName

Where do you want it to get the info from, and have you considered using a static badge instead?

**Comment by RixInGithub** [comment]
OK

**Comment by RixInGithub** [comment]
![python repo not found, branch not found, or Pipfile.lock missing](https://img.shields.io/github/pipenv/locked/python-version/RixInGithub/RixLint)
...

**Comment by DenverCoder1** [comment]
It won't work if you don't have a `Pipfile.lock` file. As you don't, your options are: **(1)** use a static badge to display the number, **(2)** add to your issue description which type of file you *are* using to store your Python version so contributors here know to add support for it, or **(3)** change the repo to use Pipenv (`Pipfile`/`Pipfile.lock`).
