### ISSUE TITLE
Feature Request: opencollective

### ISSUE THREAD

**Issue by keithamus** [badges/shields#808]
It would be nice to support [opencollective](https://opencollective.com), which currently have badges for counting the number of backers - for example https://opencollective.com/chaijs/backers/badge.svg

**Comment by mbrandau** [comment]
What badges should I implement? I'm currently trying to implement one for backers and one for sponsors.
But I can't quite figure out how to get the amount of those from the API. Do you guys know what determines a member of a collective to be a backer or a sponsor?

API Docs: https://developer.opencollective.com/#/

**Comment by paulmelnikow** [comment]
“Backers” is probably a tier and it looks like there’s an endpoint to get contributors per tier: https://developer.opencollective.com/#/api/collectives

**Comment by mbrandau** [comment]
I think I figured it out: every one that donated is a backer except organizations which are called sponsors instead of backers. As you can see in the data below neither _tier_ nor _totalAmountDonated_ seem to have anything to do with a member being recognized as backer or sponsor.

<img width="751" alt="bildschirmfoto 2019-01-05 um 18 35 09" src="https://user-images.githubusercontent.com/12972798/50727270-df045080-1118-11e9-9802-2a3b35be3499.png">

Data from https://opencollective.com/shields/members.json

**Comment by paulmelnikow** [comment]
Ah, so it's `role: "BACKER"`, and then `type: "USER"` makes you a backer, and `type: "ORGANIZATION"` makes you a sponsor?

It'd be good to have a badge that has parity with theirs.

It might be good to have one for tiers, too! That's something I don't think their badge can do.

**Comment by mbrandau** [comment]
I think so.

I'm going to implement three badges then:

- "open collective Backers"
- "open collective Sponsors"
- "open collective contributors by tier" (is that an appropriate description?)

**Comment by paulmelnikow** [comment]
Sounds great!

**Comment by mbrandau** [comment]
<img width="962" alt="examples of the new badges" src="https://user-images.githubusercontent.com/12972798/50727858-50480180-1121-11e9-8768-ca91d6be8fe6.png">
I added a fourth badge with the total amount of backers (backers + sponsors). I'm not sure about the title and the label of the badge though. Any opinions?

**Comment by paulmelnikow** [comment]
How about **backers and sponsors**?

**Comment by mbrandau** [comment]
Sounds good. 👍🏻 I'm going to have a look at what tests I can write and follow up with the PR.

**Comment by paulmelnikow** [comment]
@calebcartwright When Maximilian is ready want to pick up the PR review?

**Comment by calebcartwright** [comment]
@paulmelnikow sure!

**Comment by paulmelnikow** [comment]
🎉 🎉 🎉 

![https://img.shields.io/opencollective/all/shields.svg](https://img.shields.io/opencollective/all/shields.svg)
