### ISSUE TITLE
Broken link at opencollective.com/shields

### ISSUE THREAD

**Issue by DenverCoder1** [badges/shields#8089]
This is not part of the repository, but there is a broken link at https://opencollective.com/shields which shields.io links to.

The "Code repository" button leads to `https://github.com/badge/shields` when instead it should lead to [`https://github.com/badges/shields`](https://github.com/badges/shields) (note the additional `s`).

![image](https://user-images.githubusercontent.com/20955511/174215146-45dc83cb-7614-4f46-bcdf-d0dbd3b0a655.png)

**Comment by chris48s** [comment]
Ha - well spotted. I did log in to OpenCollective to see if I can change this but I don't have permission. I think this is one that @paulmelnikow will have to fix.

**Comment by PaulaBarszcz** [comment]
This one was already fixed by someone and can be closed :)

https://opencollective.com/shields

 
![777](https://user-images.githubusercontent.com/31891675/198870697-716242c9-d0c6-41bd-9b45-5efc10dfd61a.jpg)
