### ISSUE TITLE
GoDoc.org shield

### ISSUE THREAD

**Issue by nathany** [badges/shields#81]
We recently added a badge to [GoDoc.org](http://godoc.org/) using a PNG generated with [buckler.repl.ca](http://buckler.repl.ca). https://github.com/garyburd/gddo/issues/107

People were already linking to GoDoc.org to provide documentation (much like [Read the Docs](https://readthedocs.org/) or [RubyDoc.info](http://rubydoc.info/). Having a badge/shield was a nice step in making that metadata more harmonious (as you say). We still have some work to do before the badge provides useful metadata (documentation quality) instead of just being "branding".

I'd be interested in using the shields.io image server/API, once SSL #66 is in place, and in particular, when there is an additional advantage, like Retina support https://github.com/gittip/shields.io/issues/80 and analytics.

**Comment by pspeter3** [comment]
Is this available?

**Comment by espadrine** [comment]
I have seen such badges, so I would presume so. In fact, you can simply link to whichever project you have by having something like:

```markdown
[![](https://godoc.org/github.com/nathany/looper?status.svg)](http://godoc.org/github.com/nathany/looper)
```

or whatever project you have.

So I'm closing this. If there was something additional you wanted out of it, I can re-open it.

**Comment by pspeter3** [comment]
Can you make it the flat squared style?

**Comment by espadrine** [comment]
That is a distinct possibility.

<http://img.shields.io/badge/godoc-reference-5272B4.svg?style=flat-square>

![](http://img.shields.io/badge/godoc-reference-5272B4.svg?style=flat-square)

Is it suitable?

**Comment by nathany** [comment]
I used the style that matched Travis CI and other Shield badges (though I like the flat squared style too).

**Comment by pspeter3** [comment]
That works perfectly well for me. It just seems like the godoc is generating one that may have some meaning?

**Comment by sagikazarmark** [comment]
No, it's not generated: https://github.com/golang/gddo/blob/c782c79e0a3c3282dacdaaebeff9e6fd99cb2919/gddo-server/assets/status.svg
