### ISSUE TITLE
Bitbucket server badges for build

### ISSUE THREAD

**Issue by sharvesh06** [badges/shields#8103]
:clipboard: **Description**

:link: **Data**

:microphone: **Motivation**

**Comment by chris48s** [comment]
Can you fill out the issue template with a bit more info on this suggestion. An issue like this would be a good example of the details we are looking for: https://github.com/badges/shields/issues/7919

**Comment by calebcartwright** [comment]
I'm going to close given the lack of info in the OP and subsequent absence of follow up.

Additionally, it's unclear to me what this would have even been referring to. As far as I know, Bitbucket Pipelines remains a cloud-only service, so were we talking about.. Bamboo?

Furthermore, given Atlassian's prior announcements about decommissioning large swaths of their server products (including Bitbucket and Bamboo), I don't think it would be practical for us to try to add support for server-only badges, even if they are still selling DC licenses.
