### ISSUE TITLE
[Bug]: badges are returning error 504

### ISSUE THREAD

**Issue by maurodesouza** [badges/shields#8104]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Some badgets are returning error 504.

![image](https://user-images.githubusercontent.com/54520907/174399297-e55fe4c4-7ed7-4c54-9466-09701c77f2f0.png)

I checked some other repositories and they have the same error.

### 🔗 Link to the badge

Some links:

- https://img.shields.io/github/stars/maurodesouza/profile-readme-generator?
- https://img.shields.io/github/commit-activity/m/maurodesouza/profile-readme-generator?
- https://img.shields.io/github/last-commit/maurodesouza/profile-readme-generator?
- https://img.shields.io/github/issues/maurodesouza/profile-readme-generator?

Some repositories with the problem:

- [Profile Readme Generator](https://github.com/maurodesouza/profile-readme-generator)
- [Github Profile Readme Generator](https://github.com/rahuldkjain/github-profile-readme-generator)
- [Shields](https://github.com/badges/shields)

**Comment by calebcartwright** [comment]
You may need to refresh, but we believe things should be fine now
