### ISSUE TITLE
Gitlab badge. not respecting logoColor

### ISSUE THREAD

**Issue by davidmpaz** [badges/shields#8139]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi,

When specifying **logoColor** for the icon, this is not taken into account. Notice please the difference with the one for Github:

Github
https://img.shields.io/badge/CICD-Github-informational?style=flat&logo=github&logoColor=white&color=FFFFFF
![CICD][1]

Gitlab
https://img.shields.io/badge/CICD-Gitlab-informational?style=flat&logo=gitlab&logoColor=white&color=FFFFFF
![CICD][2]

Many thanks in advance for this project.

Cheers,
David

[1]: https://img.shields.io/badge/CICD-Github-informational?style=flat&logo=github&logoColor=white&color=FFFFFF 
[2]: https://img.shields.io/badge/CICD-Gitlab-informational?style=flat&logo=gitlab&logoColor=white&color=FFFFFF 

### 🔗 Link to the badge

https://img.shields.io/badge/CICD-Gitlab-informational?style=flat&logo=gitlab&logoColor=white&color=FFFFFF

**Comment by chris48s** [comment]
update: https://github.com/badges/shields/issues/6208#issuecomment-1328051956
