### ISSUE TITLE
`Java` logo isn't showing up when badge is embedded in markdown

### ISSUE THREAD

**Issue by eureka-cpu** [badges/shields#8142]
### Are you experiencing an issue with...

shields.io

## The Java logo is missing here:

![Java](https://img.shields.io/badge/Java-%23ED8B00.svg?style=for-the-badge&logo=java&logoColor=white)

### 🔗 Link to the badge

https://github.com/eureka-cpu/eureka-cpu

**Comment by eureka-cpu** [comment]
Is this because it's missing from `SimpleIcons`? [Here](https://github.com/simple-icons/simple-icons/blob/develop/slugs.md) at line 992 there is not `slug` for `Java`.

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close.

SimpleIcons had to remove that icon from their set, see https://github.com/simple-icons/simple-icons/pull/7378 and #8066
