### ISSUE TITLE
SSL handshake error reported for shields.io domain

### ISSUE THREAD

**Issue by andypiper** [badges/shields#8165]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm seeing repeated CloudFlare error pages when trying to access shields.io (from the UK, but tried on various VPN and with alternate network routes).

**Comment by calebcartwright** [comment]
Thank you for reaching out. Our certs have expired, apologies for the inconvenience

**Comment by calebcartwright** [comment]
Things should be back to good working order, but will keep this open for a bit longer just in case

**Comment by egonw** [comment]
They work for me again, thanks!

**Comment by andypiper** [comment]
Looking good here, thank you Caleb!

**Comment by Z4urce** [comment]
The same problem happened again through Cloudflare Frankfurt.
