### ISSUE TITLE
Docker version missing when two tags use same version

### ISSUE THREAD

**Issue by ptr727** [badges/shields#8188]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

It appears that if a docker image shares the same version with two labelled tags that the version is not printing.

From the examples notice that the DWSpectrum badge reports the `stable` version as `stable`, not `4.2.0.32842` as expected.  
This only seems to happen when the `latest` and `stable` tags use the same version number, but I am not sure if that is the cause.

E.g. an example of `buildx` from GitHub Actions:

```
buildx build --build-arg DOWNLOAD_VERSION=4.2.0.32842 --build-arg DOWNLOAD_URL=https://updates.networkoptix.com/digitalwatchdog/32842/linux/dwspectrum-server-4.2.0.32842-linux64.deb --file ./DWSpectrum/Dockerfile --iidfile /tmp/docker-build-push-80Xz5p/iidfile --platform linux/amd64 --tag ***/dwspectrum:stable --tag ***/dwspectrum:4.2.0.32842 --metadata-file /tmp/docker-build-push-80Xz5p/metadata-file --push ./DWSpectrum
```

Used in [this](https://github.com/ptr727/NxWitness) project.

### 🔗 Link to the badge

[NxWitness](https://hub.docker.com/r/ptr727/nxwitness)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxwitness/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxwitness/stable?label=stable&logo=docker)

[NxWitness-LSIO](https://hub.docker.com/r/ptr727/nxwitness-lsio)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxwitness-lsio/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxwitness-lsio/stable?label=stable&logo=docker)

[NxMeta](https://hub.docker.com/r/ptr727/nxmeta)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxmeta/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxmeta/stable?label=stable&logo=docker)

[NxMeta-LSIO](https://hub.docker.com/r/ptr727/nxmeta-lsio)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxmeta-lsio/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/nxmeta-lsio/stable?label=stable&logo=docker)

[DWSpectrum](https://hub.docker.com/r/ptr727/dwspectrum)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/dwspectrum/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/dwspectrum/stable?label=stable&logo=docker)

[DWSpectrum-LSIO](https://hub.docker.com/r/ptr727/dwspectrum-lsio)  
![Docker Image Version](https://img.shields.io/docker/v/ptr727/dwspectrum-lsio/latest?label=latest&logo=docker)
![Docker Image Version](https://img.shields.io/docker/v/ptr727/dwspectrum-lsio/stable?label=stable&logo=docker)

**Comment by chris48s** [comment]
If I have a look at https://img.shields.io/docker/v/ptr727/dwspectrum-lsio/stable the response from https://registry.hub.docker.com/v2/repositories/ptr727/dwspectrum-lsio/tags?page_size=100&ordering=last_updated (stripped down to the bits we need) is

```js
{
  count: 8,
  results: [
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:b0633dfbd38f48234458196414248c17a1820d76fd8498c48f566cb3b3e67b7c'
        }
      ],
      name: '4.2.0.32842'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:b0633dfbd38f48234458196414248c17a1820d76fd8498c48f566cb3b3e67b7c'
        }
      ],
      name: 'latest'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:174786b302b13c17a181793566ed3d3dbd4ef444864d9c1a4f690706afb37014'
        }
      ],
      name: 'stable'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:992cefc1635d5f290607cf01c7cd715b817c1086ad5c3ef8f67fbb9f6849dbab'
        }
      ],
      name: '4.1.0.31401'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:2c3403e4e5913a4a60fe413ce8a5038e27576fcb6ff2b3501643316dc9d814aa'
        }
      ],
      name: '4.2.0.32660'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:2ca4fc9650942f1e1607b9378fb270ed7d54504693fe1c6592e0dc9070f46bbc'
        }
      ],
      name: '4.1.0.32045'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:d85ffdf53badab3aa6676a456cc0fd7ab379423bab0c47e529243942d77d15c9'
        }
      ],
      name: 'develop-latest'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:b9a05e4e92824c37ceca063f4be80df098c5b6279a9c11ad49d0756f1e872eb6'
        }
      ],
      name: 'latest-develop'
    }
  ]
}
```

The way we get the version for a tag is we look for another record with the same digest. For `latest` we've got two:

```js
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:b0633dfbd38f48234458196414248c17a1820d76fd8498c48f566cb3b3e67b7c'
        }
      ],
      name: '4.2.0.32842'
    },
    {
      images: [
        {
          architecture: 'amd64',
          digest: 'sha256:b0633dfbd38f48234458196414248c17a1820d76fd8498c48f566cb3b3e67b7c'
        }
      ],
      name: 'latest'
    },
```

so we match `latest` to `4.2.0.32842`.

If we look at `stable`, there is no other record in that response with the digest value `sha256:174786b302b13c17a181793566ed3d3dbd4ef444864d9c1a4f690706afb37014` so there is no numbered version we can match the tag to.

**Comment by ptr727** [comment]
I see, looks like the last image using the same version as tag replaces the previous image, resulting in the digest no longer matching.

I should probably ask docker, but do you have any ideas?

**Comment by chris48s** [comment]
Sorry - I'm not clear enough on your process for building/publishing docker images to suggest a concrete fix but I think you'd need to find a way to push the exact same image artifact for all 3 tags.

I don't think its a bug with the badge though so I am going to close the issue. Feel free to update the thread if you find a solution that might help others hitting something similar.
