### ISSUE TITLE
Badge suggestions show incorrect license

### ISSUE THREAD

**Issue by ercpe** [badges/shields#821]
On http://shields.io/ (via suggest badges), GPL-licensed Github repositories are incorrectly shown as AGPL licensed. E.g.:
- https://github.com/ercpe/djunin
- https://github.com/ercpe/amavisvt

**Comment by paulmelnikow** [comment]
Hi, thanks for this issue.

Confirmed, when I use the suggest feature, though, it shows an AGPL badge:

<img width="944" alt="screen shot 2017-04-07 at 5 56 41 pm" src="https://cloud.githubusercontent.com/assets/1487036/24821266/9ac83e94-1bbb-11e7-9033-f232df3f8a1d.png">

The Github license badges are themselves working fine:

https://img.shields.io/github/license/ercpe/djunin.svg:

![djunin](https://cloud.githubusercontent.com/assets/1487036/24821231/65de78a6-1bbb-11e7-83f7-ccc8a2849364.png)

https://img.shields.io/github/license/ercpe/amavisvt.svg:

![amavisvt](https://cloud.githubusercontent.com/assets/1487036/24821235/6934d950-1bbb-11e7-9357-f631061a71d7.png)

**Comment by platan** [comment]
I just want to make sure that we can use GitHub license badge in suggestions. There is a lot of code for license suggestions https://github.com/badges/shields/blob/master/lib/suggest.js#L93 and it will be removed.

**Comment by paulmelnikow** [comment]
That's fine by me. Now that Github has a license endpoint we can rely on it.

**Comment by platan** [comment]
Thanks. I will fix this bug.
