### ISSUE TITLE
Support for KDE project's Jenkins badges

### ISSUE THREAD

**Issue by staniek** [badges/shields#822]
Hi,
Awesome work for the open source community! 
I am wondering, would it be possible to add support for KDE project's Jenkins badges?
KDE is one of largest FOSS communities.

Example location is here: https://build.kde.org/job/kexi%20master%20kf5-qt5/badge

Jenkins only supports SVG which is not working on our Mediawiki pages, e.g. at https://community.kde.org/Kexi. So we'd like to convert to PNG and cache it. We're already successfully converting the Coverity scan badges this way, e.g. https://img.shields.io/coverity/scan/7960.png.

Please let me know if you need more info.

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

You can accomplish this using the Jenkins badge:

- https://img.shields.io/jenkins/s/https/build.kde.org/kexi%20master%20kf5-qt5.svg
- https://img.shields.io/jenkins/s/https/build.kde.org/kexi%20master%20kf5-qt5.png
