### ISSUE TITLE
UptimeRobot Shield

### ISSUE THREAD

**Issue by UdoKifferbrehl** [badges/shields#824]
What do you think of adding an [Uptime Robot](https://uptimerobot.com/) shield?

**Comment by paulmelnikow** [comment]
Thanks for the suggestion.

How would authorization work? Would the badge include a [monitor-specific API key](https://uptimerobot.com/api)?

**Comment by crazy-max** [comment]
Would be nice 🙃

**Comment by paulmelnikow** [comment]
@crazy-max Would you like to make a pull request? There is [a tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md).

**Comment by crazy-max** [comment]
@paulmelnikow I have tried to make StatusCake badges #864 but they do not plan to include read-only API keys and i'm afraid it's the same for Uptime Robot for now.

**Comment by paulmelnikow** [comment]
Gotcha. Will mark both of these as awaiting help from the vendor, then.

**Comment by crazy-max** [comment]
Great news from Uptime Robot staff :

> Hi,
>  
> Yes. Details below :).
>  
> Currently, there are account API keys that can fetch all the account data.
>  
> And, there are "per monitor API keys" which are read-only and can only get the data of that monitor. Considering a badge will be per monitor, that looks like it'll be a perfect fit.
>  
> The "per monitor API keys" can be created from My Settings page>API and the API docs can be found at: https://uptimerobot.com/api .
>  
> 
> Have a great day,
>  
> Umut Muhaddisoglu
> http://www.uptimerobot.com
> http://twitter.com/uptimerobot

**Comment by crazy-max** [comment]
I have created the PR #947

**Comment by Daniel15** [comment]
I'm going to close this issue as the pull request has been merged. It hasn't been deployed yet, but you can follow along in #947. Thanks for your contribution!
