### ISSUE TITLE
PyPI Framework Version Badge

### ISSUE THREAD

**Issue by ericof** [badges/shields#8246]
:clipboard: **Description**

- Plone version badge (Implemented via PyPI API)
- Example: "plone version: 5.2|6.0"

:link: **Data**

- Implemented via PyPI API, in a similar way it is done with _PyPI - Django Version:_

:microphone: **Motivation**

Plone is one of the most popular open-source CMS, and many of our add-ons already use shields.io to display PyPi and GitHub information.

**Comment by chris48s** [comment]
I don't disagree with this as a feature request, and I appreciate we do currently have a specific badge for django versions (fun fact: the django versions badge was my first contribution to shields many years ago), but I wonder if it would actually make sense to approach this in a slightly more general way.

PyPI supports a whole bunch of these classifiers https://github.com/pypa/trove-classifiers/blob/d4ad70c1b4c79ef2e0649c4a3b3184432f19a108/src/trove_classifiers/__init__.py#L71-L209 and a badge listing compatible Wagtail or Django CMS versions is as valid as Django or Plone.

I think we could probably generalise this to a framework classifiers versions badge and convert the existing djversions route to a redirect.

I think the most sensible route for this would probably be `/pypi/frameworkversions/:frameworkName/:packageName` e.g: `/pypi/frameworkversions/django%20cms/djangocms-history`.

**Comment by ericof** [comment]
Hello @chris48s!

I just reviewed the [Trove Classifiers](https://pypi.org/classifiers/), and for `Frameworks` I came with the following table of possible options:

| Framework | Regex 1 | Regex Alt |
| --- | --- | --- |
| AWS CDK | \d+  |  |
| Django | \d+.\d+ | \d+ |
| Django CMS | \d+.\d+ |  |
| JupyterLab | \d+ |  |
| Odoo | \d+.\d+ |  |
| Plone | \d+.\d+ |  |
| Wagtail | \d+ |  |
| Zope | \d+ |  |

I could prepare a PR to implement that with a route like `/pypi/frameworkversions/:frameworkName/:packageName` but I would consider the following restrictions:

- Only Frameworks on the table above would be valid
- `frameworkName` should be case sensitive (to avoid "guessing the correct spelling")

And I have no idea - yet - how to implement the redirect ;-)

What do you think?
