### ISSUE TITLE
flat-square broken for a long badge

### ISSUE THREAD

**Issue by DevAndArtist** [badges/shields#826]
Today I noticed that one of my badges on my repository is broken.

I get the following message:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```

Broken badge:
```
![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg?style=flat-square)
```

![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg?style=flat-square)

VS. standard badge:
```
![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg)
```

![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg)

Any idea?

**Comment by DevAndArtist** [comment]
I just found a temporary workaround, but this is definitely bugged.

```
![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg?maxAge=3600&style=flat-square)
```

![Compatibility](https://img.shields.io/badge/Compatibility-Carthage%20%7C%20Swift%20Package%20Manager-0099ff.svg?maxAge=3600&style=flat-square)

**Comment by paulmelnikow** [comment]
It appears this has been fixed. If the problem is still observed, could you ping or reopen this thread?
