### ISSUE TITLE
Opera Add-ons

### ISSUE THREAD

**Issue by perceptron8** [badges/shields#827]
Hi! Could you, please, add badges for Opera add-ons (https://addons.opera.com)? Something similar to "Chrome Web Store" and "Mozilla Add-on" would be great. Let me know if I can help you.

**Comment by espadrine** [comment]
Thanks for the suggestion! Do they have a public API?

**Comment by perceptron8** [comment]
Probably not, I couldn't find any.

**Comment by perceptron8** [comment]
Couldn't wait any longer ;) Please, check my PR. I used Chrome Web Store support as some kind of guideline. This one should be even simpler thanks to html-soup.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed

**Comment by perceptron8** [comment]
Thanks for wasting my time.
