### ISSUE TITLE
Downloads badge does not show counts correctly

### ISSUE THREAD

**Issue by sametcelikbicak** [badges/shields#8296]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi all, when I check my  [enum2array](https://www.npmjs.com/package/enum2array) npm package "all-time download count" with this site: https://npm-stat.com/charts.html?package=enum2array&from=2021-01-01&to=2023-01-01
It gives over 6k downloads 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/5312741/183672359-57147bcf-ab1b-41b4-be8d-667d2f651ba6.png">
but when I checked the download badge it shows 5.7k for a while
<img width="655" alt="image" src="https://user-images.githubusercontent.com/5312741/183672618-76733fb0-8f82-4908-a701-dd436a47406b.png">

### 🔗 Link to the badge

https://shields.io/category/downloads

<img width="473" alt="image" src="https://user-images.githubusercontent.com/5312741/183673121-2d440370-6eb2-4c64-9526-88d2cf29a62f.png">

**Comment by chris48s** [comment]
I don't know where the numbers on https://npm-stat.com/ are from. Tbh, this is the first time I've heard of it. What we report on the NPM total downloads badge is based on querying the NPM API. In your case, that is https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/enum2array - if you add them all up, that gives us 5,651 (or 5.7k rounded).

**Comment by calebcartwright** [comment]
IIRC the npm api has an implicit time window, 18 months maybe? We've had some discussions in the past about trying to essentially make paginated calls to go back farther in history but those never moved forward. Additionally, given that the npm/github teams are actively in the process of applying rate limits to their apis I think at a minimum we'd need to wait to see how that shakes out before attempting to make any changes on our end that increase the amount of traffic we send their way

**Comment by sametcelikbicak** [comment]
Ok 👍  thanks for the help  in this case I will never get the whole number of downloads because for the time range does not allow it.
