### ISSUE TITLE
:bug:  Docker stars broken (invalid) :star: 

### ISSUE THREAD

**Issue by adriens** [badges/shields#8314]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Docker stars shield is broken : 

![image](https://user-images.githubusercontent.com/5235127/184984278-43dd5859-685c-4444-be48-7376ba876bba.png)

While docker repo is ok : 

https://hub.docker.com/r/optnc/api-transitaires

### 🔗 Link to the badge

Can be reproduced on any docker image with `/docker/stars/`

### 💡 Possible Solution

Maybe point to this API `https://hub.docker.com/v2/repositories/optnc` which makes it possible to get the stars with `star_count` attribute

**Comment by chris48s** [comment]
Looking at it, calls to the `/stars/count` endpoint are failing with a `401 Unauthorized`.

Calls to `/repositories`are still working ok though, so I think switching to get the star count from there (as suggested) is the way forward

**Comment by adriens** [comment]
Thanks a lot for your fast feedback : your shields are really cool :heavy_heart_exclamation:

**Comment by adriens** [comment]
You mean... I can test it now :grey_question: :open_mouth:

**Comment by adriens** [comment]
Let me know when you want me to give it a try :pray: :rocket:

**Comment by adriens** [comment]
> Looking at it, calls to the `/stars/count` endpoint are failing with a `401 Unauthorized`.
> 
> Calls to `/repositories`are still working ok though, so I think switching to get the star count from there (as suggested) is the way forward

The fun thing is that I discovered and started to play recenlty with DockerHub API cf https://dev.to/optnc/show-me-your-dockerhub-public-images-in-your-terminal-39n4

**Comment by chris48s** [comment]
its deployed now

**Comment by adriens** [comment]
...and works perfectly well :heavy_heart_exclamation: 
Thanks a lot for your kind and efficient support :muscle: :pray: 

![image](https://user-images.githubusercontent.com/5235127/185491734-68a476ec-1b9e-4d2d-abea-52b47d2cb33a.png)
