### ISSUE TITLE
[github] Count all contributors in organization

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [badges/shields#834]
Now there is a badge, which represents count of contributors of specified Repo
e.g. `https://img.shields.io/github/contributors/cdnjs/cdnjs.svg` 

Please create the badge which will count all unique contributors for specified organization.
kind of `https://img.shields.io/github/contributors/cdnjs.svg`

- Since micro-services architecture becoming popular and more and more teams organize their tools in multi-repo structure
- It should count unique contributors (by mail, or by login) to avoid duplication when 1 member make input in several repos.

**Comment by DzmitryHumianiuk** [comment]
code examples:
http://hvelarde.blogspot.com.by/2014/01/how-to-get-statistics-about-your.html
https://codegists.com/code/count%20github%20contributions/

**Comment by paulmelnikow** [comment]
Thanks for the suggestion.

Does the Github API have a way to get this information without making a lot of calls?

**Comment by DzmitryHumianiuk** [comment]
@paulmelnikow no, there is no single API method to get this info.
This should be aggregated by 2 calls.

**justification:**
more and more project use micro-services architecture and keep services in multiply repos.

**Comment by paulmelnikow** [comment]
What are the two calls?

**Comment by avarabyeu** [comment]
@paulmelnikow Need to obtain [names of organization's repos](https://developer.github.com/v3/repos/#list-organization-repositories) and [then retrieve contributors of each repo](https://developer.github.com/v3/repos/#list-contributors). Actually, it's n+1 calls. Are there any way to make some custom badge and just point it to endpoint which returns already aggregated info?

**Comment by paulmelnikow** [comment]
Yes, that is possible. There is a PR open #820 to provide a custom badge from a JSON URL.

Another possibility, perhaps simpler, is for the endpoint doing the aggregation to issue a redirect to img.shields.io with the data in the URL, e.g.:

https://img.shields.io/badge/organization-10%20contributors-blue.svg

**Comment by avarabyeu** [comment]
@paulmelnikow #820 is good option for us. Since we want this badge to be used in MDs, there is no possibility to use JS to obtain aggregated data for building URL from option 2. When PR could me merged? Thanks for the help!

**Comment by paulmelnikow** [comment]
@avarabyeu #820 needs some work. Would you like to take a look at it?

**Comment by paulmelnikow** [comment]
#820 is finally merged!
