### ISSUE TITLE
Social badge right-hand-side as query parameter

### ISSUE THREAD

**Issue by leog** [badges/shields#835]
Hello there!

I was wondering if there is any ~~hidden~~ (no hidden way, just checked the code :) way to define the social badge right-hand-side text with a query parameter. If not, is there any chance it can be added as a feature request?

Thanks a lot in advance and long live the badge revolution!

**Comment by espadrine** [comment]
Thanks for the suggestion!

If you use a `/badge/` URL, you can set the right-hand-side text: ![](https://img.shields.io/badge/left-right-green.svg) https://img.shields.io/badge/left-right-green.svg.

Otherwise, the right-hand-side is meant to convey custom information, which means setting it would remove the custom information.

Could you delve into what you want to achieve, please?

**Comment by leog** [comment]
Thanks for the feedback. Makes sense that giving that option would kind of defeat the purpose of the badge by itself so let me explain a little bit my use case.

I want to start using shields.io to show information on my company's repositories with a custom logo.  So I was trying to simplify the URL for its usage using an URL shortener which should include all the common parts of any future badges. To do that I need to be able to have the customizable parts as URLs, that is the status. 

So instead of:
```
https://img.shields.io/badge/Standards-javascript--library%20v1.0.0-blue.svg?style=social&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAMAAAAolt3jAAAAwFBMVEUNcLTz9PT6%2BvqRuXGw1eiuytyXzdKTuaquyKdUjkE0bq2zzpVastDV4%2BY5l8zW49LJ3ds0r%2BBblsbI2eVzp0Q7jpBurqsMlcp3stMci4sMicfp6urp8vbh6%2BxclD9px74nczp%2FskZ4nsYJm9dyysEaYKgaV59HnGsKfb9pn0Cg1%2B0ttKfO3rxRfLHk7%2FQEodzp7uVAvOdAg0cgnJUqhb4krJ%2Bbw3VctpZItauIo8Zukr0FpeBxn2gcnNF%2Bq1rk5%2BkohkRdAAAArUlEQVR42i3H6RpCQBQA0HtHtiGmiJjIYMqnjfa993%2BrtJx%2FBwghzG7btiYfXVHPwttmMPnXvWdRUTzqX9Ewt9tHGNrrbxslNe92HDu9T9H109Tw4ioeTwgCWr7%2FdNGpKsfr2ghfWA2qFYCGCJYQYomY7AGGfQRFiKObJMkYJFURjPn8VJal1qNS5i9go2h3WEwZy6WkHnA92p21Pucqnc0uwFkQsBfn3LtSunoDNakQuaVS6JQAAAAASUVORK5CYII%3D
```

It could be something like:
```
http://bit.ly/badge?status=javascript--library%20v1.0.0
```

I know that this kind of thing would be best to achieve it running our own shields server but before I could even try to do that I need to build a strong case with what I have at hand right now and part of that strong case would be an easy way of including a badge without such a long URL to include.

**Comment by leog** [comment]
@espadrine any news on this?

**Comment by leog** [comment]
Closing in favor of direct implementation presented on #852 rather than this workaround.
