### ISSUE TITLE
codeclimate badge not found

### ISSUE THREAD

**Issue by Yang09701194** [badges/shields#8353]
### Are you experiencing an issue with...

shields.io

### Description

codeclimate badge not found, is there way to fix 

### 🔗 Link to the badge

https://img.shields.io/codeclimate/github/karma-runner/karma.svg?style=flat-square

**Comment by calebcartwright** [comment]
It's not clear which badge you are trying to use based off the example badge url you've shared. We offer several Code Climate badges, and you'd need to update your route parameters to match.

If you go to shields.io and type "code climate" into the search box at the top of the page you will see the available badges:

![image](https://user-images.githubusercontent.com/13042488/187713097-67c4e61b-76d1-4a61-99e1-4807415cd5b7.png)

From there you can click on your target badge to bring up the badge builder window which will help you construct the correct route. You may also want to check out #8185 for more information.

Most likely you are looking for something like this:

https://img.shields.io/codeclimate/maintainability/karma-runner/karma
![](https://img.shields.io/codeclimate/maintainability/karma-runner/karma)

**Comment by Yang09701194** [comment]
Thank you for the information.
