### ISSUE TITLE
Pixelmator PXM Badge Idea (attached)

### ISSUE THREAD

**Issue by chrismochinski** [badges/shields#8354]
Built in Figma, submitting here. I appreciate your consideration!

Cheers!

![pixelmator-github-shield](https://user-images.githubusercontent.com/85808922/187761107-6a174126-cd58-43a8-a977-012a60a3471e.svg)

:link: **Data**

:microphone: **Motivation**

**Comment by chrismochinski** [comment]
One more...how about one for Final Cut Pro? (attached)

![fcp-github-shield](https://user-images.githubusercontent.com/85808922/187764242-66bec1a7-b69c-46e0-a80e-677b08ea8ce4.svg)

**Comment by chrismochinski** [comment]
I'm so sorry for the string, but I just whipped together one more...

I'm a huge fan of Anime Studio Pro / Moho. Been using it for years. Great for animators/designers...

![moho-github-shield](https://user-images.githubusercontent.com/85808922/187765895-b2be9306-3c28-4041-bc4e-64a3c1205fb1.svg)

**Comment by chris48s** [comment]
Hi - we don't add badges to shields that just display static text/images. If you wanted to generate badges like that via shields.io, you could do it using the static badge route and [custom logos](https://github.com/badges/shields/blob/master/doc/logos.md#custom-logos), but also if what you want is an some images with those text/logos in them.. looks like you already made them :)
