### ISSUE TITLE
Badge request: WhatPulse

### ISSUE THREAD

**Issue by jerone** [badges/shields#8356]
:clipboard: **Description**

> [WhatPulse](https://whatpulse.org/) is a small application that measures your keyboard/mouse usage, down- & uploads and your uptime. 
> 
> The software tracks a user's pressed keys, mouse clicks and used bandwidth and the uptime of the system. 
> Users can see where they are in a leaderboard of people who have joined the program and compare themselves against people from their own countries. Users can also join teams, which enables them to compare themselves against people with similar interests.

Example user profile: https://whatpulse.org/jerone

It would be great to have badges for those data-points and ranks.

:link: **Data**

Web data is available here: https://help.whatpulse.org/api/web-api
The API is publicly available and doesn't need any (authorization) tokens or keys.

As seen in the [example](https://help.whatpulse.org/api/web-api#results), data is available for every data-points & ranks:
* Keys 
* Clicks 
* Download 
* Upload 
* UptimeShort (UptimeLong & UptimeSeconds are probably not interesting/useful) 
* Ranks:
  * Keys 
  * Clicks 
  * Download 
  * Upload 
  * Uptime 

There is also data & ranks available for [teams](https://help.whatpulse.org/api/web-api#team-stats). That would be a good second feature.

Besides choosing one of the above keys, an username is required.

Example badges using real data from my account (images are clickable to see the dynamic url):
<table>
<tr>
	<th>Data key
	<th>Stats
	<th>Rank
<tr>
	<td>Keys
	<td>

[![WhatPulse Keys](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Keys&query=Keys&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Keys&query=Keys&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<td>

[![WhatPulse Keys](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Keys&query=Ranks.Keys&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Keys&query=Ranks.Keys&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<tr>
	<td>Clicks
	<td>

[![WhatPulse Clicks](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Clicks&query=Clicks&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Clicks&query=Clicks&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<td>

[![WhatPulse Clicks](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Clicks&query=Ranks.Clicks&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Clicks&query=Ranks.Clicks&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<tr>
	<td>Download
	<td>

[![WhatPulse Download](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Download&query=Download&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Download&query=Download&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
	<td>

[![WhatPulse Download](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Download&query=Ranks.Download&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Download&query=Ranks.Download&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<tr>
	<td>Upload
	<td>

[![WhatPulse Upload](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Upload&query=Upload&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Upload&query=Upload&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
	<td>

[![WhatPulse Upload](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Upload&query=Ranks.Upload&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Upload&query=Ranks.Upload&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
<tr>
	<td>Uptime
	<td>

[![WhatPulse Uptime](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Uptime&query=UptimeShort&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Uptime&query=UptimeShort&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
	<td>

[![WhatPulse Uptime](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Uptime&query=Ranks.Uptime&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)](https://img.shields.io/badge/dynamic/json?label=WhatPulse%20Uptime&query=Ranks.Uptime&suffix=th&url=https%3A%2F%2Fapi.whatpulse.org%2Fuser.php%3Fuser%3Djerone%26format%3Djson&color=2C5B75)
</table>

~~Colors are debatable. No opinion here. WhatPulse doesn't really have an distinct [brand](https://whatpulse.org/pages/assets/) color.~~ The author of WhatPulse [suggest](http://forums.whatpulse.org/t/whatpulse-badge-shield/20210/5?u=jerone) using one of the following colors: #374856 and #2C5B75

:microphone: **Motivation**

WhatPulse keeps records of all your data and compares that against other users and teams. It would be nice to show your own stats and ranks.

I would use this in my GitHub Readme and in forum signatures.

The example badges in the table above are created with the dynamic api from shield.io. This works great for the stats-badges. But for the rank-badges it is missing an dynamic suffix. Right now it's hardcoded "th" behind the value, for demo purposes. An custom implementation here would be needed to calculate the correct suffix based on the value.

**Comment by PaulaBarszcz** [comment]
I'd like to pick this one up :)
