### ISSUE TITLE
how can i change the height of badges?

### ISSUE THREAD

**Issue by glepnir** [badges/shields#8378]
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

I using some badges in my website. I found some height of badges too big, some height of badges too small. How can i make them has a same height width.

![image](https://user-images.githubusercontent.com/41671631/188520344-40a35725-921b-4735-b71f-4ac5db84f20c.png)

### 🔗 Link to the badge

I use these badges

```html
      <img class="lang-img" src="https://img.shields.io/badge/neovim-%2357A143.svg?&style=plastic&logo=neovim&logoColor=white?"/>
      <img class="lang-img" src ="https://img.shields.io/badge/c-%2300599C.svg?style=plastic&logo=c&logoColor=white">
      <img class="lang-img" src ="https://img.shields.io/badge/c++-%2300599C.svg?style=plastic&logo=c%2B%2B&logoColor=white">
      <img class="lang-img" src="https://img.shields.io/badge/go-%2300ADD8.svg?&style=plastic&logo=go&logoColor=white" />
      <img class="lang-img" src="https://img.shields.io/badge/lua-%232C2D72.svg?&style=platic&logo=lua&logoColor=white"/>
      <img class="lang-img" src="https://img.shields.io/badge/rust-%23000000.svg?&style=plastic&logo=rust&logoColor=white"/>
      <img class="lang-img" src="https://img.shields.io/badge/Zig-%23F7A41D.svg?style=plastic&logo=zig&logoColor=white"/>
      <img class="lang-img" src="https://img.shields.io/badge/python-3670A0?style=plastic&logo=python&logoColor=ffdd54"/>


```

### 💡 Possible Solution

N/A

**Comment by chris48s** [comment]
If I paste that snippet into an issue, I get this:

<img class="lang-img" src="https://img.shields.io/badge/neovim-%2357A143.svg?&style=plastic&logo=neovim&logoColor=white?"/>
<img class="lang-img" src ="https://img.shields.io/badge/c-%2300599C.svg?style=plastic&logo=c&logoColor=white">
<img class="lang-img" src ="https://img.shields.io/badge/c++-%2300599C.svg?style=plastic&logo=c%2B%2B&logoColor=white">
<img class="lang-img" src="https://img.shields.io/badge/go-%2300ADD8.svg?&style=plastic&logo=go&logoColor=white" />
<img class="lang-img" src="https://img.shields.io/badge/lua-%232C2D72.svg?&style=platic&logo=lua&logoColor=white"/>
<img class="lang-img" src="https://img.shields.io/badge/rust-%23000000.svg?&style=plastic&logo=rust&logoColor=white"/>
<img class="lang-img" src="https://img.shields.io/badge/Zig-%23F7A41D.svg?style=plastic&logo=zig&logoColor=white"/>
<img class="lang-img" src="https://img.shields.io/badge/python-3670A0?style=plastic&logo=python&logoColor=ffdd54"/>

I think there is some other CSS in your page that is applying additional styling to the image tags.

That said, its just an img tag, so you can use CSS or the height and width params so you can do for example

```html
<img src="https://shields.io/badge/massive-badge-blue" height="100"/>
```

<img src="https://shields.io/badge/massive-badge-blue" height="100"/>

if you want, but you shouldn't need to.

**Comment by glepnir** [comment]
you should use a html test. in md it's okay
