### ISSUE TITLE
colorB query parameter ignored

### ISSUE THREAD

**Issue by kieranpotts** [badges/shields#842]
Providing a 3-character or 6-character color hex as the value of the colorB query parameter does NOT change the color of the right-side of the shield. Other query parameters, including colorB, are OK. Example:

https://img.shields.io/codeclimate/github/nirvarnia/exceptions.svg?colorB=0099ff

**Comment by aaronschubert0** [comment]
+1 this would be good to fix

**Comment by FezVrasta** [comment]
I'm not sure if it's related, but on the cdnjs badge, the `colorB` argument isn't applied all the times, what I mean is, if I watch it 10 times, 6 times it will be default blue, other 4 times will be the color I specified.

![img](https://img.shields.io/cdnjs/v/popper.js.svg?colorB=brightgreen)

**Comment by espadrine** [comment]
@kieranpotts I believe this was fixed by 2ba7ded391c9d0dff88e6619d6f3f032c7301fe0.

@FezVrasta I believe this was fixed by a440c0840be2df3bb0af7b1b3c594ab7c0cb7a49. By the way, `?colorB` only supports hex colors. I improved the website documentation to be clearer.

**Comment by FezVrasta** [comment]
Thanks, why did it work with `brightgreen`? :P Also, what's the HEX of `brightgreen` pls?

**Comment by FezVrasta** [comment]
PS, seems like it's `44CC11`

**Comment by espadrine** [comment]
@FezVrasta the full list is here: https://github.com/badges/shields/tree/master/colorscheme.json.
