### ISSUE TITLE
By default Ruby gem version is beta even when there is a stable release

### ISSUE THREAD

**Issue by AlexWayfer** [badges/shields#8425]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

There is a gem: https://rubygems.org/gems/filewatcher

As you can see, it had a few beta-versions (of 2.0).

By default, `gem` (or Bundler) doesn't recognize them (until specific lock version).

But… there is 2.0.0 stable release. And it's newer, and it's stable.

But the badge still "dangerous" about beta-versions: https://img.shields.io/gem/v/filewatcher?include_prereleases&style=flat-square

![image](https://user-images.githubusercontent.com/6510020/191872379-19a30402-07c6-49a1-932f-0d0cfbc60ca3.png)

Now I see there is `include_prereleases` param, but I believe it should count released versions.

### 🔗 Link to the badge

https://img.shields.io/gem/v/filewatcher?include_prereleases&style=flat-square

### 💡 Possible Solution

Reject any `.beta`, `.rc`, etc. versions if there is a stable version with the same digits.

**Comment by chris48s** [comment]
This is happening because we're attempting to use semver sorting, which assumes the pre-release identifier is separated from the main part of the version number by a `-`, rather than a `.`. I've opened a PR to fix this at https://github.com/badges/shields/pull/8434

**Comment by AlexWayfer** [comment]
> This is happening because we're attempting to use semver sorting, which assumes the pre-release identifier is separated from the main part of the version number by a `-`, rather than a `.`. I've opened a PR to fix this at #8434

Thank you, I didn't know about this Semver detail.

And yeah, as you have found, RubyGems suggest only dots. I guess, `-` will break them, but didn't check.
