### ISSUE TITLE
Online tool for custom badges

### ISSUE THREAD

**Issue by rozaxe** [badges/shields#843]
Hi ! I am a huge fan of those badges and I was surprised there were no easy way to create custom badges.

That is why I designed on online tool for generating badges :

- A **dedicated tool** to create custom badge with subject, value, color and style
- **On the fly rendering** computed locally so Shields.io's server is not unnecessarily requested 

With that I though you could check this out ?

[Badges Factory Website](https://rozaxe.github.io/factory/) ~ [Source code](https://github.com/rozaxe/factory)

**Comment by espadrine** [comment]
Very neat! You can absolutely contribute it to [https://shields.io/#your-badge](https://github.com/badges/shields/blob/78494dd6ffd9e3cab3fe1909f4bc3e030ed68e2c/try.html#L973) if you want.

**Comment by rozaxe** [comment]
Thanks, I will try !

**Comment by paulmelnikow** [comment]
Hi @rozaxe! We have a brand new React-based frontend. Would you be interested in adding your custom badge UI? Would be happy to help you with that, if you'd like.

**Comment by rozaxe** [comment]
Sorry @paulmelnikow, I did not saw the notification. If you are still considering adding a custom badge UI, I would be really happy to contribute to it !

**Comment by mbrandau** [comment]
@rozaxe I'm currently preparing the frontend so we can implement your badge factory.
The factory will be available through the page `/your-badge`.
I'll follow up with further details in a few days.

**Comment by mbrandau** [comment]
@rozaxe I started implementing the feature at https://github.com/mbrandau/shields. Have a look at `frontend/components/static-badge-maker.js`. That's the file where this will be implement.
Btw, https://reactjs.org/ has a quite good getting started guide.

**Comment by rozaxe** [comment]
@mbrandau I am going to look at it !

**Comment by paulmelnikow** [comment]
Let's track this work in #1899.
