### ISSUE TITLE
Relay icon does not appear in the badge

### ISSUE THREAD

**Issue by beceluiz** [badges/shields#8438]
### Are you experiencing an issue with...

badge-maker NPM package

### 🐞 Description

The Relay icon does not appear, even though it is already available on the simple icons website

### 🔗 Link to the badge

https://img.shields.io/badge/relay-F26B00?style=for-the-badge&logo=relay&logoColor=white

**Comment by chris48s** [comment]
Icon for relay was added in simple-icons 7.13.0. We're still running 7.12.0.
For more info on our update process for icons see https://github.com/badges/shields/discussions/5369
We usually review dependencies over the weekend so it'll probably be available in about a week.
