### ISSUE TITLE
docs.rs badges are "always failed" if the package is an executable

### ISSUE THREAD

**Issue by Gankra** [badges/shields#8440]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

This clearly functioning documentation page on docs.rs includes a badge for itself... saying the docs failed to build: https://docs.rs/crate/minidump-stackwalk/latest

The badge url is the standard "schema" used by all rust packages for their libraries. It seems that the pipeline here only really understands libraries and considers executables to always be failed.

### 🔗 Link to the badge

https://docs.rs/minidump-stackwalk/badge.svg

which redirects to

https://img.shields.io/docsrs/minidump-stackwalk/latest

### 💡 Possible Solution

This may require upstream work with docs.rs. Currently the build report they emit:

https://docs.rs/crate/minidump-stackwalk/latest/builds.json

provides no indication that this is an executable, and indeed specifies `build_status: false`. I was told to file this bug with y'all, but I expect docs.rs will need to do something for you first.

**Comment by chris48s** [comment]
You've kind of answered your own question :) To get the data to render the badge, we call https://docs.rs/crate/minidump-stackwalk/latest/builds.json The reason why we're saying the build status is failed is because https://docs.rs/crate/minidump-stackwalk/latest/builds.json reports `build_status: false`.

**Comment by calebcartwright** [comment]
Going to close this for now given the current plans to update things on the docs.rs side. We can revisit and reopen if it becomes necessary for us to make any changes on this end.
