### ISSUE TITLE
IPv6 connection times out

### ISSUE THREAD

**Issue by pke** [badges/shields#8441]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Maybe a recent heroku change, but since a couple of days the IPv6 requests to shields.io do timeout.
I found out when using the fastlane badge tooling, where [an issue exists](https://github.com/HazAT/badge/issues/111#issuecomment-1259965774) describing the problem

### 🔗 Link to the badge

```bash
$ wget -6 -v --timeout=10 --tries=1 https://img.shields.io/badge/feature-1.71.18-purple.svg
--2022-09-27 21:35:04--  https://img.shields.io/badge/feature-1.71.18-purple.svg
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving img.shields.io (img.shields.io)... 2606:4700:e4::ac40:ae10, 2606:4700:e4::ac40:af10
Connecting to img.shields.io (img.shields.io)|2606:4700:e4::ac40:ae10|:443... failed: Connection timed out.
Connecting to img.shields.io (img.shields.io)|2606:4700:e4::ac40:af10|:443... failed: Connection timed out.
Giving up.
```

### 💡 Possible Solution

Fix the IPv6 config, maybe port 443 is not connected.

**Comment by chris48s** [comment]
Hmm. This one is going to be tricky to reproduce/debug as my ISP doesn't support ipv6 my VPN provider blocks ipv6 traffic.

This isn't a solution, but just to provide a bit more info..

We use CloudFlare for DNS and CDN.

Just looking at the logs above and in https://github.com/HazAT/badge/issues/111 the IP you're getting a timeout trying to contact ( `2606:4700:e4::ac40:af10` ) is in CloudFlare's IPv6 range (source: https://www.cloudflare.com/ips-v6 ) and the one you're getting a response from ( `172.64.174.16` ) is in CloudFlare's IPv4 range (source: https://www.cloudflare.com/ips-v4 ).. which is what I'd expect tbh.

This shouldn't have a bearing on anything here but we're not on Heroku any more. We switched to Fly.io about 6 months back. As I say, I don't think this is directly related to that switch as you say this was working up to a couple of days ago, but we're not on Heroku any more.

Any of the other maintainers in a situation where you can easily reproduce this with a normally working ipv6 setup?

**Comment by calebcartwright** [comment]
> Any of the other maintainers in a situation where you can easily reproduce this with a normally working ipv6 setup?

I don't seem to be able to repro

> $ wget -6 -v --timeout=10 --tries=1 https://img.shields.io/badge/feature-1.71.18-purple.svg
--2022-09-28 15:57:55--  https://img.shields.io/badge/feature-1.71.18-purple.svg
Resolving img.shields.io (img.shields.io)... 2606:4700:e2::ac40:8406, 2606:4700:e2::ac40:8506
Connecting to img.shields.io (img.shields.io)|2606:4700:e2::ac40:8406|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/svg+xml]
Saving to: ‘feature-1.71.18-purple.svg’
>
> feature-1.71.18-pur     [ <=>                ]   1.12K  --.-KB/s    in 0s      
>
> 2022-09-28 15:57:55 (5.36 MB/s) - ‘feature-1.71.18-purple.svg’ saved [1148]

**Comment by pke** [comment]
I seems to work now again, maybe cloudflare fixed something on their side, when they saw the errors in their logs.
