### ISSUE TITLE
BITBUCKET_USER and BITBUCKET_PASS can't be passed as environment vars

### ISSUE THREAD

**Issue by ferarias** [badges/shields#8445]
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

I try to use the official docker image of shields.io on-premises.
When invoking docker run with env params runs fine, eg:

`docker run -p 16880:16880 -e PORT=16880 shieldsio/shields:next`

However when passing our bitbucket credentials to reach private repos it fails

`docker run -p 16880:16880 -e BITBUCKET_USER=xxxx -e BITBUCKET_PASS=xxxx shieldsio/shields:next`

```
Configuration:
{
  bind: { address: '0.0.0.0' },
  metrics: {
    prometheus: { enabled: false, endpointEnabled: false },
    influx: { enabled: false, timeoutMilliseconds: 1000, intervalSeconds: 15 }
  },
  ssl: { isSecure: false },
  cors: { allowedOrigin: [] },
  services: {
    github: {
      baseUri: 'https://api.github.com/',
      debug: { enabled: false, intervalSeconds: 200 }
    },
    obs: { authorizedOrigins: 'https://api.opensuse.org' },
    weblate: { authorizedOrigins: 'https://hosted.weblate.org' },
    trace: false
  },
  cacheHeaders: { defaultCacheLengthSeconds: 120 },
  handleInternalErrors: true,
  fetchLimit: '10MB',
  userAgentBase: 'shields (self-hosted)',
  requestTimeoutSeconds: 120,
  requestTimeoutMaxAgeSeconds: 30,
  requireCloudflare: false
}
file:///usr/src/app/core/server/server.js:277
      throw Error(
            ^

Error: Private configuration is invalid. Check these paths: bitbucket_username
    at Server.validatePrivateConfig (file:///usr/src/app/core/server/server.js:277:13)
    at new Server (file:///usr/src/app/core/server/server.js:230:32)
    at file:///usr/src/app/server.js:56:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

```

### 💡 Possible Solution

Not a node developer, however taking a look at the code, here

https://github.com/badges/shields/blob/8821ff85fcd494ebb802bf9bb26ddcba11d21ec8/core/server/server.js

It looks like `privateConfigSchema` does not include `bitbucket_username` nor `bitbucket_password`, only `bitbucket_server_username `and `bitbucket_server_password`

https://github.com/badges/shields/blob/8821ff85fcd494ebb802bf9bb26ddcba11d21ec8/core/server/server.js#L160

**Comment by chris48s** [comment]
Cheers. PR up with a fix at https://github.com/badges/shields/pull/8472

**Comment by ferarias** [comment]
Wow. Tha was quick! Thanks a lot.

**Comment by ferarias** [comment]
Thanks. I will try this
