### ISSUE TITLE
Maven Central badge should be based on repo1.maven.org rather than search.maven.org

### ISSUE THREAD

**Issue by fabriziocucci** [badges/shields#846]
According to [this](http://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central):

> Upon release, your component will be published to Central: this typically occurs within 10 minutes, though updates to search can take up to two hours.

So, besides the delay, [if the indexing jobs for search.maven.org are paused](https://issues.sonatype.org/browse/OSSRH-27247), it may take quite some time to see the last artifact version even though it has been actually released on Maven Central.

**Comment by paulmelnikow** [comment]
Hi, thanks for suggesting this.

Would you like to open a pull request?

**Comment by fabriziocucci** [comment]
@paulmelnikow sure, today I'll give it a try! :sunglasses:
