### ISSUE TITLE
Hacktoberfest 2022 Badge 

### ISSUE THREAD

**Issue by vinitshahdeo** [badges/shields#8469]
:clipboard: **Description**

The current Hacktoberfest badge is for 2021. The option for changing the year to 2022 is missing.

<img width="616" alt="Screenshot 2022-10-02 at 2 58 08 PM" src="https://user-images.githubusercontent.com/20594326/193447471-7d46fccf-e313-4ba3-b299-3259dc5cd771.png">

:link: **Data**

This badge was already implemented in 2021, I hope the APIs exist with you.

:microphone: **Motivation**

Having a Hacktoberfest countdown badge will be great as [Hacktoberfest 2022](https://hacktoberfest.digitalocean.com/) has arrived.

**Comment by calebcartwright** [comment]
Resolved via #8468 - I'll deploy the changes later today

**Comment by calebcartwright** [comment]
Just posting a follow up message to note that the changes are live
