### ISSUE TITLE
SVG layout when a minimum font size is enforced

### ISSUE THREAD

**Issue by insin** [badges/shields#848]
I use my browser's minimum font size setting to prevent sites from using unreadable font sizes. Unfortunately it has this effect on shields.io SVG badges:

![firefox_2017-01-05_19-31-57](https://cloud.githubusercontent.com/assets/226692/21675546/e8f25914-d37d-11e6-8335-7516ca1dfd39.png)

Is there something which could be done to make SVG badges scale instead of squishing text like this?

**Comment by paulmelnikow** [comment]
Thanks for this issue.

This would be great to fix. Can you give steps to reproduce the problem?

**Comment by paulmelnikow** [comment]
Maybe duplicate of: #746 #797
