### ISSUE TITLE
The sponsor count badge doesn't show the correct count

### ISSUE THREAD

**Issue by jwellbelove** [badges/shields#8481]
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

My project has '7' sponsors, but the sponsor badge only ever shows '2'.
<img width="658" alt="Screenshot 2022-10-07 093950" src="https://user-images.githubusercontent.com/9266447/194511399-600dfb1a-01d6-4e46-b363-a6eea624b666.png">

### 🔗 Link to the badge

https://img.shields.io/github/sponsors/ETLCPP

**Comment by jwellbelove** [comment]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9266447/194513187-3bb4eed2-29af-4769-ba9a-57951e61fd9a.png">

**Comment by chris48s** [comment]
The answer is in your screenshot. Of your 7 sponsors, 5 are private and 2 are public. We can only see and report public sponsors so we only know about the 2 public ones.
