### ISSUE TITLE
Badge idea: GitHub issue badge with title text in badge

### ISSUE THREAD

**Issue by aaronsteers** [badges/shields#8515]
I have a use case where I want to use Shields.io's badges to render GitHub issues titles when issues are non-private, and some other text or description if they are private. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/18150651/194779705-3cfc319b-2091-42f8-b8ca-05fb3095be64.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/18150651/194779732-f79e1b8a-3f55-4cca-9b28-5451e705f68b.png">

<img width="284" alt="image" src="https://user-images.githubusercontent.com/18150651/194779787-9b5679e7-2a08-459b-b4e5-ff0b221a22c7.png">

Mockup

I was actually able to do this with the `/badge/dynamic` shields.io endpoint:

```js
https://img.shields.io/badge/dynamic/json?color=blueviolet&label=PR%20%2<PR_NUMBER>&prefix=%28closed%29%20&query=%24.title&url=http%3A%2F%2Fapi.github.com%2Frepos%2F<ORG>%2F<REPO>%2Fissues%2F<ISSUE_NUMBER>
```

For example:

https://img.shields.io/badge/dynamic/json?color=blueviolet&label=PR%20%23123&prefix=%28closed%29%20&query=%24.title&url=http%3A%2F%2Fapi.github.com%2Frepos%2Fmeltano%2Fmeltano%2Fissues%2F123

![PR #123](https://img.shields.io/badge/dynamic/json?color=blueviolet&label=PR%20%23123&prefix=%28closed%29%20&query=%24.title&url=http%3A%2F%2Fapi.github.com%2Frepos%2Fmeltano%2Fmeltano%2Fissues%2F123)

This is hard to type though, and also there's no handling in the above for how to render badges for private issues. When pointed at a private repo, the image rendered is:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/18150651/194784724-fccbdff3-d4d5-4cd3-be09-d5523bcfe355.png">

:link: **Data**

This uses the API endpoint:

https://api.github.com/repos/meltano/meltano/issues/123

The endpoint works for PRs as well as Issues, since Pull Requests are a subset of "Issues" in the GitHub Issues API.

**Benefits**

- Provides the end user a nice view of 'what is this issue anyway' while not requiring the user to type the description, and still have the description updated to reflect the latest title if the title changes.
- The data returned also provides metadata on whether the type is `issue` or `pr` and whether the issue/PR is closed or open. These could all influence how the badge is rendered.
- A custom solution could also render something like '[Confidential Issue or Issue not found]` if the link is in a private repo.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close. This isn't possible given GitHub's behavior in http responses, and even if it were, I don't think this would make sense for us to take on.

Admittedly I don't understand the motivation/benefit of the use case, but if it's something you still feel strongly about then I'd recommend considering using our [custom Endpoint badge](https://shields.io/endpoint) instead which will allow you to insert your own custom logic for handling GitHub's semi-ambiguous 404 responses.
