### ISSUE TITLE
Wrong percentage for codecov

### ISSUE THREAD

**Issue by jmsche** [badges/shields#8545]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi,

For some reason I don't understand, the coverage percentage displayed on the codecov badge for my repository is wrong.

* Package name (on GitHub): leapt/core-bundle
* Badge from codecov: https://codecov.io/gh/leapt/core-bundle/branch/4.x/graph/badge.svg
* Codecov link: https://app.codecov.io/github/leapt/core-bundle/tree/4.x

### 🔗 Link to the badge

https://img.shields.io/codecov/c/github/leapt/core-bundle/4.x?style=flat-square

**Comment by chris48s** [comment]
Interesting.

Any idea why these 2 report completely different numbers?

https://codecov.io/gh/leapt/core-bundle/branch/4.x/graph/badge.svg
https://codecov.io/gh/leapt/core-bundle/branches/4.x/graph/badge.svg

**Comment by jmsche** [comment]
No idea why there's a difference between these :/ 

Submitted an issue on their community board: https://community.codecov.com/t/difference-between-branch-and-branches-for-badges/3923

**Comment by jmsche** [comment]
Hi! 

So I got an answer from Tom:

> branch is correct. branches ignores the 4.x and defaults to your default branch, in this case master. You can see the last [commits](https://app.codecov.io/gh/leapt/core-bundle/commits) show 25.74% coverage.

So I guess Shields uses /branches but should use /branch instead?

Meanwhile I set the default branch to 4.x on the codecov side to fix the badge percentage, but I guess I'll have the same issue next year when tagging 5.0 :/

**Comment by chris48s** [comment]
Thanks for following this up. PR up at #8565

**Comment by jmsche** [comment]
Thanks :)
