### ISSUE TITLE
Swagger badge does not work

### ISSUE THREAD

**Issue by RobinTail** [badges/shields#8566]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Swagger validation badge does not work. Noticed that several days ago.

### 🔗 Link to the badge

![Swagger Validator](https://img.shields.io/swagger/valid/3.0?specUrl=https%3A%2F%2Fraw.githubusercontent.com%2FRobinTail%2Fexpress-zod-api%2Fmaster%2Fexample%2Fexample.swagger.yaml)

### 💡 Possible Solution

I presume that the validation API changed.
See https://validator.swagger.io/#/Validator/

It seems that now we should use `https://validator.swagger.io/validator/debug?url=` endpoint and check the emptiness of `schemaValidationMessages` prop in the response. Probably.

Since `https://validator.swagger.io/validator/?url=` endpoint now returns their own graphics.

**Comment by chris48s** [comment]
I submitted a PR at https://github.com/badges/shields/pull/8564 which fixes this. Useful to know it only started a few days ago.

**Comment by RobinTail** [comment]
@chris48s , could you tell me please, after your PR merged, when should I expect the issue with this badge to be fixed?

**Comment by chris48s** [comment]
I'll get a deploy done later this evening

**Comment by RobinTail** [comment]
Now it works again. Thank you!
