### ISSUE TITLE
Badge request: Blockchain Solana

### ISSUE THREAD

**Issue by KevinFiorentino** [badges/shields#8567]
:clipboard: **Description**

I would like to show my experience working with Solana Blockchain in a simple badge. I've seen others logos about Blockchain such as Bitcoin and Ethereum.

The link for the Solana badge could be: https://img.shields.io/badge/solana-9945FF?style=for-the-badge&logo=solana&logoColor=white

:link: **Data**

Like all Blockchains, Solana is OpenSource and you can find its logo on the [official website](https://solana.com/). It's very nice!

:microphone: **Motivation**

Solana is perhaps the second favorite Blockchain in the world for developers, behind Ethereum. It is the fastest and cheapest Blockchain, ideal for communication projects or NFTs!

Solana will be one of the most important projects in the future for decentralized applications and deserves some attention to show a simple badge.

Thanks!

**Comment by chris48s** [comment]
This seems like your request is really for a blockchain solana logo.

The named logos we use on shields come from simple icons so you might consider submitting a request over at https://github.com/simple-icons/simple-icons/issues (please review their guidelines https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon to see if blockchain solana is a good fit)

Alternatively, you may be able to just use a custom logo, like this https://github.com/badges/shields/blob/master/doc/logos.md#custom-logos
