### ISSUE TITLE
shields.io is down

### ISSUE THREAD

**Issue by salmonb** [badges/shields#8579]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

<img width="1097" alt="Screenshot 2022-10-28 at 15 58 51" src="https://user-images.githubusercontent.com/15129227/198664642-b0d79327-daff-406b-bcd2-f798a26133ab.png">

**Comment by ReenigneArcher** [comment]
The website is working for me

**Comment by chris48s** [comment]
I think we're affected by this fly.io outage https://status.flyio.net/
We've got some crashed containers that can't restart. I'm monitoring, but I suspect this is mostly out of our hands for a bit.

**Comment by salmonb** [comment]
> The website is working for me

Right, I confirm shields.io just went back for me too. But it has definitely be down for a few hours today.

> I think we're affected by this fly.io outage https://status.flyio.net/
> We've got some crashed containers that can't restart. I'm monitoring, but I suspect this is mostly out of our hands for a bit.

Thanks for monitoring.

Should I close this issue?

**Comment by chris48s** [comment]
I'll probably leave it open until the fly incident is closed. If we have any kind of an outage or wobble it is useful to keep an issue open near the top of the list to reduce duplicates :)

**Comment by chris48s** [comment]
Fly incident is still open, but all of our stopped containers are back up and serving traffic so I'm going to close this out.
