### ISSUE TITLE
Docker badges invalid

### ISSUE THREAD

**Issue by ReenigneArcher** [badges/shields#8580]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Docker badges are failing

### 🔗 Link to the badge

https://img.shields.io/docker/pulls/lizardbyte/plexyglass?style=for-the-badge&logo=docker

https://img.shields.io/docker/pulls/lizardbyte/sunshine?style=for-the-badge&logo=docker

### 💡 Possible Solution

- Cache data and show last known number of pulls
- Use multiple accounts for API requests
- Discuss with Docker to request a rate limit increase for shields.io

**Comment by ReenigneArcher** [comment]
Working now, guess it was related to https://github.com/badges/shields/issues/8579

**Comment by ReenigneArcher** [comment]
I seem to be having this issue again today, so maybe not related to that issue.
![image](https://user-images.githubusercontent.com/42013603/198837102-a92cfeee-912a-42d5-b544-94921fa6a539.png)

https://img.shields.io/docker/pulls/lizardbyte/themerr-plex?style=for-the-badge&logo=docker

What is odd is that the badge works if I open the URL directly, but not in my readme on GitHub.

I tired opening in a private window to ensure it's not a cache issue on my end. Any ideas?

**Comment by calebcartwright** [comment]
The INVALID message means we got something like an http 500 response from the upstream provider. There's really nothing we can do about that, and it's unrelated to #8579 (an issue on our end/with our hosting provider).

> What is odd is that the badge works if I open the URL directly, but not in my readme on GitHub.

GitHub caches pretty aggressively, and doing something locally like a private window won't impact that. You can try the purge techniques described in their docs within https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls, but probably easier to just give it some time and check to see if there's any known issues upstream in Dockerhub
