### ISSUE TITLE
Factorio Mod Portal

### ISSUE THREAD

**Issue by aSemy** [badges/shields#8582]
:clipboard: **Description**

Please could you add badges for mods hosted on the Factorio Mod Portal https://mods.factorio.com/

Factorio Mod Portal hosts fan-made mods for the game Factorio. The mods are identified by a unique name, and mods can have multiple versions. The mod portal enforces a semver version pattern.

Factorio mods are compatible with major versions of the base Factorio game. For example, `Signalized_Couplers_0.1.0` is compatible with Factorio 1.0, while `Signalized_Couplers_0.1.3` (the latest version) is compatible with Factorio 1.1.

API: https://mods.factorio.com/api/mods/Signalized_Couplers/

Mod portal: https://mods.factorio.com/mod/Signalized_Couplers/downloads

![image](https://user-images.githubusercontent.com/897017/198896440-f12e09f2-bb42-4215-b416-ed1dda2b9908.png)

I would like a badge to show the latest version of my mod.

https://img.shields.io/badge/Factorio%20Mod%20Portal-1.2.3-brightgreen

The following two badges would be nice, but they are not very important to me.

1. display the last-updated date/time https://img.shields.io/badge/Factorio%20Mod%20Updated-31.12.21-blue
2. a badge showing a mod's compatibility with Factorio https://img.shields.io/badge/Factorio%20Compatibility-1.1-blue

:link: **Data**

The Factorio Mod Portal has a documented API for fetching the available versions of mods. 

> The Mod Portal API is used to both browse and download all mods available on the [official Factorio mod portal](https://mods.factorio.com/). Using the API does not require any kind of authentication or account information.

Documentation: https://wiki.factorio.com/Mod_portal_API#/api/mods/{mod_name}

Example: 

`https://mods.factorio.com/api/mods/Signalized_Couplers`

```json
{
  "category": "trains",
  "downloads_count": 1369,
  "name": "Signalized_Couplers",
  "owner": "digital_pet",
  "releases": [
    {
      "download_url": "/download/Signalized_Couplers/5f36e9280854c13400b6e2a3",
      "file_name": "Signalized_Couplers_0.1.0.zip",
      "info_json": {
        "factorio_version": "1.0"
      },
      "released_at": "2020-08-14T19:42:32.428000Z",
      "sha1": "bd106a1102e67900eae455489dd5d79294c7d6e3",
      "version": "0.1.0"
    },
    {
      "download_url": "/download/Signalized_Couplers/5f377a5c2a978e4ff535be7f",
      "file_name": "Signalized_Couplers_0.1.1.zip",
      "info_json": {
        "factorio_version": "1.0"
      },
      "released_at": "2020-08-15T06:02:04.023000Z",
      "sha1": "aa502fcfdb0dd59b3c37332c18e67448e4f5eb44",
      "version": "0.1.1"
    },
    {
      "download_url": "/download/Signalized_Couplers/62142e1f310b1408689a12d0",
      "file_name": "Signalized_Couplers_0.1.2.zip",
      "info_json": {
        "factorio_version": "1.1"
      },
      "released_at": "2022-02-22T00:28:15.458000Z",
      "sha1": "c594ed31125366af3d8c08efa217538c4ee4064c",
      "version": "0.1.2"
    },
    {
      "download_url": "/download/Signalized_Couplers/621561d6c8ceb7b112cda861",
      "file_name": "Signalized_Couplers_0.1.3.zip",
      "info_json": {
        "factorio_version": "1.1"
      },
      "released_at": "2022-02-22T22:21:10.288000Z",
      "sha1": "35eb6374871b1fdb445b1a174e5c33c1c34e14d4",
      "version": "0.1.3"
    }
  ],
  "score": -3.3000000000000007,
  "summary": "Adds signals to allow stations to couple/uncouple trains automatically.",
  "thumbnail": "/assets/70301b74c90271c958ad0f5dc79401f1b20c5201.thumb.png",
  "title": "🇺🇦 Signalized Couplers"
}
```

There is an additional API to get more details - in particular, the 'last updated' date

`curl https://mods.factorio.com/api/mods/Signalized_Couplers/full | jq`

```json
{
  "category": "trains",
  "changelog": "..."
  "downloads_count": 1369,
  "github_path": "digital-pet/signalized-couplers",
  "homepage": "",
  "images": [
    {
      "id": "7560147df12d5dafe6bd5e3aebe8229f9f9c975a",
      "thumbnail": "https://assets-mod.factorio.com/assets/7560147df12d5dafe6bd5e3aebe8229f9f9c975a.thumb.png",
      "url": "https://assets-mod.factorio.com/assets/7560147df12d5dafe6bd5e3aebe8229f9f9c975a.png"
    }
  ],
  "license": {
    "description": "A permissive license that is short and to the point. It lets people do anything with your code with proper attribution and without warranty.",
    "id": "default_mit",
    "name": "mit",
    "title": "MIT",
    "url": "https://opensource.org/licenses/MIT"
  },
  "name": "Signalized_Couplers",
  "owner": "digital_pet",
  "releases": [
    ...
    {
      "download_url": "/download/Signalized_Couplers/621561d6c8ceb7b112cda861",
      "file_name": "Signalized_Couplers_0.1.3.zip",
      "info_json": {
        "dependencies": [],
        "factorio_version": "1.1"
      },
      "released_at": "2022-02-22T22:21:10.288000Z",
      "sha1": "35eb6374871b1fdb445b1a174e5c33c1c34e14d4",
      "version": "0.1.3"
    }
  ],
  "score": -3.3000000000000007,
  "source_url": "https://github.com/y-a-f-m/signalized-couplers",
  "summary": "Adds signals to allow stations to couple/uncouple trains automatically.",
  "tag": {
    "name": "trains"
  },
  "thumbnail": "/assets/70301b74c90271c958ad0f5dc79401f1b20c5201.thumb.png",
  "title": "🇺🇦 Signalized Couplers",
  "updated_at": "2022-02-22T22:21:10.288000Z"
}
```

:microphone: **Motivation**

I want to have an auto-updating badge on my GitHub page that shows the latest version of the mod, so users can see the latest version, click to navigate to it. Also, I will be able to check that the latest version has deployed correctly.

**Comment by aSemy** [comment]
I just figured out how to do this with the 'dynamic' API!

[![Mod Portal](https://img.shields.io/badge/dynamic/json?label=Mod%20Portal&query=%24.releases%5B-1%3A%5D.version&url=https%3A%2F%2Fmods.factorio.com%2Fapi%2Fmods%2Fkafkatorio-events&style=flat-square&color=%23600401)](https://mods.factorio.com/mod/kafkatorio-events)
[![Factorio Version](https://img.shields.io/badge/dynamic/json?label=Factorio%20Version&query=%24.releases%5B-1%3A%5D.info_json.factorio_version&url=https%3A%2F%2Fmods.factorio.com%2Fapi%2Fmods%2Fkafkatorio-events&style=flat-square&color=%23d7cdf6)](https://mods.factorio.com/mod/kafkatorio-events)

I saw the dynamic badge bit originally, but I got confused because it's not explained, so I clicked the link above it, 'Create badges from [your own JSON endpoint](https://shields.io/endpoint)`, and that lead to a page which also didn't explain much, and seemed to indicate that the dynamic badges only worked if the server had a compatible endpoint

**Comment by sohailgi** [comment]
Would like to work on it. But I am a newbie. Can you help me with the process?

**Comment by chris48s** [comment]
Our tutorial is at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md That covers the basics for adding a new badge and writing tests.
