### ISSUE TITLE
StackOverflow badge shows 'invalid parameters' instead of reputation count

### ISSUE THREAD

**Issue by denisrasulev** [badges/shields#8583]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

StackOverflow badge shows 'invalid parameters' instead of reputation count

![Screenshot 2022-10-31 at 11 08 18](https://user-images.githubusercontent.com/10368869/198983855-aba38670-1c5e-45ae-87ee-15a06d1e4f99.png)

**Comment by cdhunt** [comment]
https://github.com/badges/shields/pull/8539

**Comment by chris48s** [comment]
Yeah I'm going to close this one as a dupe of https://github.com/badges/shields/issues/5415
