### ISSUE TITLE
The v prefix is displayed on the release name if the release name shares the tag name

### ISSUE THREAD

**Issue by PQCraft** [badges/shields#8598]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

`/github/v/release/PQCraft/CaveCube?display_name=release` displays `v0.4.5` while `/github/v/release/PQCraft/PlatinumSrc?display_name=release` displays `Build 2022011900`.
CaveCube's release name is the same as the tag name while PlatinumSrc adds "Build" before it.

### 🔗 Link to the badge

Correct: ![](https://img.shields.io/github/v/release/PQCraft/PlatinumSrc?display_name=release)
Incorrect: ![](https://img.shields.io/github/v/release/PQCraft/CaveCube?display_name=release)

**Comment by chris48s** [comment]
Formatting version numbers (or in this case, a release name which is a version number) with a leading v is a conscious decision. This is a discussion that has come up before and we've decided previously to keep this not user-configurable.

I think #6135 is probably the clearest articulation of it but there is some previous discussion in issues like #3200 and #1181

I'm going to close this as a duplicate. Cheers.

**Comment by PQCraft** [comment]
bruh :neutral_face: ![](https://img.shields.io/badge/dynamic/json?color=blue&label=Latest%20release&query=tag_name&url=https%3A%2F%2Fapi.github.com%2Frepos%2FPQCraft%2FCaveCube%2Freleases%2Flatest)

**Comment by PQCraft** [comment]
That moment when your project is open source but doesn't like being open source

**Comment by calebcartwright** [comment]
> That moment when your project is open source but doesn't like being open source

It's unclear what outcome you were seeking with these comments, but this comes across as snarky and isn't particularly helpful. Projects that make their source code free and publicly available do not cede their ability to make decisions about the project, nor are they obliged to accept every request.



> bruh neutral_face ![](https://camo.githubusercontent.com/e5f2dbe517b080931ca17cdc6fe4d554a2fc201a76e1074978dad8ee9c484005/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e3f636f6c6f723d626c7565266c6162656c3d4c617465737425323072656c656173652671756572793d7461675f6e616d652675726c3d68747470732533412532462532466170692e6769746875622e636f6d2532467265706f7325324650514372616674253246436176654375626525324672656c65617365732532466c6174657374)

For the benefit of other readers, this :point_up: from the prior comment is a dynamic badge constructed with the below badge url. Shields provides both general purpose/less opinionated badge builders in the form of our dynamic badges and endpoint badge, along with the more opinionated and consistent native badges.

The release badges for various platforms and services, including those mentioned in the OP are native badges, and thus have the message consistency applied. The dynamic badges are arbitrary, and do not.

https://img.shields.io/badge/dynamic/json?color=blue&label=Latest%20release&query=tag_name&url=https%3A%2F%2Fapi.github.com%2Frepos%2FPQCraft%2FCaveCube%2Freleases%2Flatest

**Comment by PQCraft** [comment]
> t's unclear what outcome you were seeking with these comments, but this comes across as snarky and isn't particularly helpful. Projects that make their source code free and publicly available do not cede their ability to make decisions about the project, nor are they obliged to accept every request.

I was referring to the lack of customization options.

**Comment by PQCraft** [comment]
Like I can't even change the background color of the label text

**Comment by PQCraft** [comment]
It's very easy to add an option to remove the v prefix (add a `formatVersion` option or something) but no. Now I have to use the "inconsistent" endpoint badge that happens to be more consistent than the native badge.
