### ISSUE TITLE
Accept GitHub Sponsors

### ISSUE THREAD

**Issue by janosh** [badges/shields#8599]
How about adding [GitHub Sponsors](https://github.com/sponsors) to the list of support options?

![Screenshot 2022-11-07 at 09 25 25](https://user-images.githubusercontent.com/30958850/200375111-38887a76-3cd9-42c7-ae60-102f564cbbe7.png)

**Comment by calebcartwright** [comment]
Thanks for (ostensibly) your interest in supporting the project, but I'm going to close because the reasons articulated in https://github.com/badges/shields/issues/7415#issuecomment-1003780394 still hold true, including with GitHub Sponsors
