### ISSUE TITLE
Discord member count in ?style=social badge

### ISSUE THREAD

**Issue by FevGrave** [badges/shields#8620]
:clipboard: **Description**
This badge is just adding a social Discord badge that displays the member count on the server but in the style of this 
[![Generic badge](https://img.shields.io/twitter/follow/EDF_OFFICIAL_EN?style=social)](https://twitter.com/EDF_OFFICIAL_EN)
(For testing or building the badge for the member count on the server is close to 6 thousand users or 5,782 members at the time of sending this)

:link: **Data**
Link to the game mod github repo: https://github.com/FevGrave/EDF_6-1
Public "Earth Defense Force" Discord Server: https://discord.gg/a9JKEV8xHS

:microphone: **Motivation**
Hello, I'm a modder for a niche video game series called Earth Defense Force, and the provided link to a mod will be in the works once EDF 6 releases on PC. Within that linked page is the social media bar, and having this badge makes the discord badge link in the same style as the other four links. Thanks in advance!

**Comment by chris48s** [comment]
There's a couple of things to address in this issue.

You can use the social style for any badge so for example the discord badge in our readme is

![](https://img.shields.io/discord/308323056592486420?logo=discord) https://img.shields.io/discord/308323056592486420?logo=discord

but I can append `&style=social` to use the social style instead

![](https://img.shields.io/discord/308323056592486420?logo=discord&style=social) https://img.shields.io/discord/308323056592486420?logo=discord&style=social

(although that is number of users online now)

The request for a badge showing a the total number of users (as opposed to the number online now) is a duplicate of https://github.com/badges/shields/issues/4500 so lets keep the conversation for that one there.

**Comment by FevGrave** [comment]
thanks
