### ISSUE TITLE
Custom Badge Builder From Images

### ISSUE THREAD

**Issue by dhakalnirajan** [badges/shields#8626]
There are several Instances when we search for badges and can't find them. Some badges are not like the one user prefers. So, to minimize the issue, I propose drag-and-drop-image badge making feature.

Often in Markdown, I faced a lot of issues for Matplotlib or Sympy badges and these are only examples. So, it would be a good idea to build upon the previous features like ?logoColor and logoStyle and the image reads on the style and badge color and creates badge. When the user uploads image (.svg file format is preferred), the image is stored in a database and when somebody requests for particular badge like Matplotlib for example, the URL is displayed in a textbox.

Another feature would be the directory of various libraries and Framework badges. When searching in the search button, many of them do not appear. So, a good feature would be to display particular set of results according to search results.

**Comment by chris48s** [comment]
> Another feature would be the directory of various libraries and Framework badges. When searching in the search button, many of them do not appear. So, a good feature would be to display particular set of results according to search results.

It seems like the thing you're looking for here is a directory of _static_ badges. We don't add badges to shields.io that just display static text/images. Shields.io only lists badges that show dynamic content. Beyond that, we provide the static badge routes that allow you to make whatever badge you want e.g: https://img.shields.io/badge/anything-you%20like-blue

There are some external projects that maintain some kind of directory of pre-set static badge you can make with shields e.g:

https://badges.pages.dev/
https://github.com/alexandresanlim/Badges4-README.md-Profile

Maybe one of those is something like what you want but it is something we've explicitly decided we're not to maintain ourselves.

---

With regards to the rest of it, again, I don't think this is something we'd build, host or maintain, but broadly the API exists for it to be developed as a community project if someone out there wanted to maintain it.

As a side note: You might also want to look at [custom logos](https://github.com/badges/shields/blob/master/doc/logos.md#custom-logos) if the issue you have is that you want to use logos which don't exist in [SimpleIcons](https://simpleicons.org/)
