### ISSUE TITLE
Waffle.io badges are "invalid"

### ISSUE THREAD

**Issue by Relequestual** [badges/shields#863]
Recently I added waffle.io badges to some open source projects. Today I noticed that waffle.io badges are now invalid. Seems the example on the shields.io page is also broken. Guessing it's a problem their end, but just in case it's not, I'm filing an issue here also.

**Comment by marcelstoer** [comment]
Can't confirm (anymore). The example at https://img.shields.io/waffle/label/evancohen/smart-mirror/in%20progress.svg works just fine.

**Comment by Relequestual** [comment]
Thanks @marcelstoer, seems to be working again as you say. Wonder if it was just an outage on their side.
