### ISSUE TITLE
Hyvä Themes Badge Request

### ISSUE THREAD

**Issue by MaximGns** [badges/shields#8631]
:clipboard: **Description**

Hyvä is a new frontend stack for Magento 2. https://hyva.io/. 

Hyvä Themes offers a brand-new Magento frontend, built from scratch, using the Magento templating system, but written entirely from the ground up.

:link: **Data**

There is not something to get data from. The docs are here: https://docs.hyva.io/.
This badge will only tell the package is Hyvä compatible.

:microphone: **Motivation**

Hyvä has a growing community and has more and more upcomming existing magento composer packages that are being made compatible with the Hyvä stack. The use of this badge will make it more clearer to potentional users that the package is usable with the Hyvä front-end stack.

**Comment by MaximGns** [comment]
Working on this PR myself.

**Comment by calebcartwright** [comment]
Thank you for reaching out, but I'm going to close based on the information that's provided. It's not uncommon for our static badge builder feature to be utilized to generate such badges, but we do not add native routes for static badge instances

https://shields.io/#your-badge
