### ISSUE TITLE
StatusCake badges

### ISSUE THREAD

**Issue by crazy-max** [badges/shields#864]
Would be nice to have a shields.io badge for the StatusCake service.
For the moment i use the StatusCake badges but like you can see on the README.md of [this repository](https://github.com/crazy-max/neard-website), the integration is pretty awful...

An example link provided by StatusCake :

```html
<a href="https://www.statuscake.com" title="Website Uptime Monitoring"><img src="https://app.statuscake.com/button/index.php?Track=mZ96VTLi6T&Days=1&Design=6" /></a>
````

Basic parameters are :

* track_id (string)
* days (integer between 1 and 1000)

Example :

1 day for track_id `mZ96VTLi6T` : [![StatusCake Uptime](https://app.statuscake.com/button/index.php?Track=mZ96VTLi6T&Days=1&Design=6)](https://www.statuscake.com)

Thanks!

**Comment by crazy-max** [comment]
Also based on the API you can grad tests by their IDs.

Example : https://app.statuscake.com/API/Tests/Details/?TestID=1811593

```json
{
   "Method":"GET",
   "TestID":1811593,
   "TestType":"HTTP",
   "Paused":false,
   "WebsiteName":"neard.io",
   "URI":"http:\/\/neard.io",
   "ContactGroup":null,
   "ContactID":0,
   "ContactGroups":[

   ],
   "Status":"Up",
   "Uptime":100,
   "CheckRate":300,
   "Timeout":40,
   "LogoImage":"",
   "Confirmation":"2",
   "WebsiteHost":"Github",
   "NodeLocations":[
      ""
   ],
   "FindString":"",
   "DoNotFind":false,
   "LastTested":"2017-01-22 16:52:27",
   "NextLocation":"JP1",
   "Processing":false,
   "ProcessingState":"Complete",
   "ProcessingOn":"SSDVPS1",
   "DownTimes":"0",
   "TriggerRate":"0",
   "Sensitive":false,
   "EnableSSLWarning":false,
   "FollowRedirect":false,
   "DNSIP":"",
   "DNSServer":"",
   "CustomHeader":""
}
```

Then we can create two badges for status and uptime.

**Comment by crazy-max** [comment]
But the API required an API key or a username/password :(

**Comment by FezVrasta** [comment]
Don't they provide read only API keys? It would be good enough to be able to read the datum

**Comment by crazy-max** [comment]
@FezVrasta I have posted an issue to StatusCake about it, i'll kepp you in touch

**Comment by crazy-max** [comment]
> **StatusCake:** Hey there, that's correct - we don't currently include the read-only keys, and currently only provide the standard key that you see in the User Details section :)
**Me:** Ok thanks, do you plan to include read-only API keys ?
**StatusCake:** I've put this in as a feature suggestion but no current plans I'm afraid!

**Comment by StatusCakeDaniel** [comment]
We'd be more than happy to make a call that suits - what would be the ideal response / call? 

~Dan @ StatusCake

**Comment by crazy-max** [comment]
Hi @StatusCakeDaniel,

You can read the issue #824 i opened for UptimeRobot Shield and read my modification on the PR #947.
The blocking issue is that StatusCake does not provide a public (read-only) API key. If you have more info, i can develop a similar badge as UptimeRobot.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
