### ISSUE TITLE
photo is not updated when changed

### ISSUE THREAD

**Issue by Thatkookooguy** [badges/shields#866]
I'm changing the shield text on my server side but GitHub doesn't refresh the shield itself.
when I open the path in a new tab, I get the new image. But on GitHub, I get the old one.
 I thought it might be caching, so I added all the headers I know of that disable caching, but still no success.

```javascript
app.get('/achievementsBadge', function(req, res) {
  badge.loadFont('./Verdana.ttf', function(err) {
    badge({ text: ["achievements", _.keys(achievements).length], colorA: "#894597", colorB: "#5d5d5d", template: "flat" },
      function(svg, err) {
        res.setHeader('Content-Type', 'image/svg+xml;charset=utf-8');
        res.setHeader('Pragma-directive', 'no-cache');
        res.setHeader('Cache-directive', 'no-cache');
        res.setHeader('Cache-control', 'no-cache');
        res.setHeader('Pragma','no-cache');
        res.setHeader('Expires','0');
        res.send(svg);
      });
  });
});
```

Any hints on how to solve this problem?

Thanks :-)

**Comment by espadrine** [comment]
Does [this](https://github.com/badges/shields/blob/225ed98663832cbd97095d1bdc017f47f115369f/server.js#L184) help?

**Comment by Thatkookooguy** [comment]
Yes, the header you sent a reference to did help and made our shield update :-)

Sorry it took some time. testing cache required some waiting time haha

thanks a lot for the help!
closing this issue as **solved**

**Comment by espadrine** [comment]
No worries!
