### ISSUE TITLE
Badge request: Dub score

### ISSUE THREAD

**Issue by al1-ce** [badges/shields#8662]
:clipboard: **Description**
Dub score. Dub scores packages with [dub score](https://dub.pm/develop#package-scoring)
![](https://img.shields.io/badge/SCORE-0.7-blue?style=for-the-badge) 

:link: **Data**
At https://code.dlang.org/api/packages/:package-name/stats, i.e https://code.dlang.org/api/packages/vibe-d/stats 

:microphone: **Motivation**
Just how AUR has votes for packages dub has data that can show how "popular" or "mature" package is. This might be useful for repos containing dub packages

**Comment by chris48s** [comment]
If anyone is interested in working on this, we've already got a couple of existing badges for dub in https://github.com/badges/shields/tree/master/services/dub and the tutorial for adding new badges is at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by pr7prashant** [comment]
@chris48s I can take this one for a change.

**Comment by calebcartwright** [comment]
Awesome, thanks @pr7prashant!
