### ISSUE TITLE
Badge request: PR count by user in repository /github/issues-pr/:owner/:repo/:user

### ISSUE THREAD

**Issue by jakkdl** [badges/shields#8664]
:clipboard: Description
Display the number of PR's contributed by a specific user to a specific (GitHub) repo.

:link: **Data**
`https://api.github.com/search/issues?q=is:pr+author:USER+repo:OWNER/REPO+state:STATE&per_page=1` and check the value of `total_count`
Example:
"shields pull requests by jakkdl | 32"
"open shields pull requests by jakkdl | 32"
"closed shields pull requests by jakkdl | 32"

:microphone: **Motivation**
I want to showcase my FOSS contributions in my readme, there are other badges that show total PR's committed - but I have loads of personal repositories that nobody cares about, so I would like to specifically highlight how many PR's I have to some specific large repositories.

**Comment by calebcartwright** [comment]
Thank you for reaching out with your request. We do already support this via our existing GitHub Issues Custom Query badge:

e.g.
https://img.shields.io/github/issues-search?label=shields%20pull%20requests%20by%20caleb&query=is%3Apr%20author%3Acalebcartwright%20repo%3Abadges%2Fshields
![](https://img.shields.io/github/issues-search?label=shields%20pull%20requests%20by%20caleb&query=is%3Apr%20author%3Acalebcartwright%20repo%3Abadges%2Fshields)

My inclination is to leverage this existing capability, as we largely provide it to handle such circumstances where users have various query-driven badges they'd like to have. I don't think there's a large enough need for this particular badge to justify the overhead on the codebase of having a dedicated badge route just to make things a tad simpler for this specific query/set of queries.

I'll hold off to see if others disagree, but would move we close this issue

**Comment by jakkdl** [comment]
Ah, I'd missed that was a thing. Makes perfect sense to use custom queries for niche requests, and I agree with your logic in the PR that it should be seen as the general solution.

I saw that it was possible to create your own endpoint but somehow missed the custom query completely, so maybe it's a good idea to make it more prominent. Could e.g. put an example or two on the top of pages such as https://shields.io/category/issue-tracking

**Comment by calebcartwright** [comment]
There already are a few examples there amongst the listings (GitHub issue custom search in repo):

![image](https://user-images.githubusercontent.com/13042488/212784436-90e2fd72-69b8-436d-a017-19ae76cc9194.png)

But we are currently undergoing a process (albeit a rather long and complicated one) to overhaul the site UX so perhaps there will be opportunities there to make things pop a bit more.

Going to go ahead and close this for now given the above discussion
