### ISSUE TITLE
Nuget Shield displays soft-deleted version

### ISSUE THREAD

**Issue by matthiaslischka** [badges/shields#867]
On NuGet you can mark specific Versions of your Package as "not listed" (aka soft-delete).
The NuGet shield displays the latest NuGet package, weather it is marked as listed or not on NuGet.
Since not listed NuGet packages are not visible to the public anymore the shield should display the latest package that is marked to be listed.

BR Matthias

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this.

Would you like to look into it and open a pull request?

**Comment by paulmelnikow** [comment]
@Daniel15 Do you know if your PR #945 fixes this?

**Comment by Daniel15** [comment]
It's possible! NuGet is a little bit inconsistent and some endpoints continue returning unlisted packages, whereas others don't. @matthiaslischka Do you have an example of a package that has an unlisted version?

**Comment by matthiaslischka** [comment]
Seems to be fixed. Tested with https://www.nuget.org/packages/CatlightApi/
Latest not listened version is 1.0.1.18118
Actual listed version is 1.0.1

Works fine now. Think this issue can be closed.

**Comment by paulmelnikow** [comment]
Thanks. Since #945 isn't deployed yet, we should test on master too.

**Comment by paulmelnikow** [comment]
Still working post-deploy. Sweet!
