### ISSUE TITLE
Support WordPress theme statistics

### ISSUE THREAD

**Issue by mistermantas** [badges/shields#869]
WordPress plugin badges are supported, but this isn’t the case for themes. Badges for the downloads, ratings, and other statistics would be lovely!

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion.

Do you know if the theme stats are available through an API?

**Comment by onlinemantas** [comment]
I don’t see why not! Perhaps [this](https://codex.wordpress.org/WordPress.org_API) could help? I saw something about a theme check from a quick Google search.

**Comment by paulmelnikow** [comment]
Yup, indeed, looks like it!

Would you like to make a PR?

**Comment by onlinemantas** [comment]
Can’t, sorry, swepped with other stuff and I barely know how to code *well* since I started only a year ago.

This isn’t a huge deal for me, but I feel like at least someone would find this useful.

**Comment by bgun** [comment]
I'd like to take this on, for downloads and ratings at least.
