### ISSUE TITLE
shield.io DNS issue?

### ISSUE THREAD

**Issue by johanblomgren** [badges/shields#871]
I'm seeing the current issue when trying to load https://www.shield.io/.

![screen shot 2017-02-06 at 10 28 38](https://cloud.githubusercontent.com/assets/11459008/22641468/2a0ad4b6-ec57-11e6-922f-8c118ff2b23c.png)

Applications using shield.io are timing out.

**Comment by Sam-Spencer** [comment]
Having the same issue here - can replicate this.

**Comment by espadrine** [comment]
We do not own shield.io. The correct address is https://shields.io.

Is there a faulty link somewhere to shield.io when it should be shields.io?

**Comment by bittner** [comment]
There's a single occurrence, each, of "Shield.io" in two source files in this repository, but it's only text:

- [index.html](https://github.com/badges/shields/blob/master/index.html#L1188), line 1188
- [try.html](https://github.com/badges/shields/blob/master/try.html#L1187), line 1187

Should probably be corrected anyway.
