### ISSUE TITLE
The npm version supports "versionPrefix"

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [badges/shields#8715]
I want to select the latest version of "@ wangeditor/editor for vue", which should be 5. x.x.
However, "1.0.2" is recently released, and only "1.0.2" can be selected at present

https://img.shields.io/npm/v/@wangeditor/editor-for-vue：
<img src="https://img.shields.io/npm/v/@wangeditor/editor-for-vue">

**Comment by xuxiaowei-com-cn** [comment]
使用 https://img.shields.io/npm/v/@wangeditor/editor-for-vue?versionPrefix=5 无效：
<img src="https://img.shields.io/npm/v/@wangeditor/editor-for-vue?versionPrefix=5">

**Comment by chris48s** [comment]
Hmm. It is hard to know exactly what has happened here, but this behaviour can be explained by looking at the dist-tags. See

https://registry.npmjs.org/-/package/@wangeditor%2Feditor-for-vue/dist-tags

```
{
  "latest": "1.0.2",
  "last": "5.1.0",
  "next": "5.1.12"
}
```

I think my recommendation here would be that you want to follow the 'last' or 'next' tag with either

https://img.shields.io/npm/v/@wangeditor/editor-for-vue/last
https://img.shields.io/npm/v/@wangeditor/editor-for-vue/next

https://img.shields.io/npm/v/@wangeditor/editor-for-vue


but it is hard to know the exact intent of the package authors here.

We shouldn't implement your suggested solution though, well meaning as it is.

**Comment by xuxiaowei-com-cn** [comment]
> Hmm. It is hard to know exactly what has happened here, but this behaviour can be explained by looking at the dist-tags. See
> 
> https://registry.npmjs.org/-/package/@wangeditor%2Feditor-for-vue/dist-tags
> 
> ```
> {
>   "latest": "1.0.2",
>   "last": "5.1.0",
>   "next": "5.1.12"
> }
> ```
> 
> I think my recommendation here would be that you want to follow the 'last' or 'next' tag with either
> 
> https://img.shields.io/npm/v/@wangeditor/editor-for-vue/last https://img.shields.io/npm/v/@wangeditor/editor-for-vue/next
> 
> but it is hard to know the exact intent of the package authors here.
> 
> https://img.shields.io/npm/v/@wangeditor/editor-for-vue is basically the same as https://img.shields.io/npm/v/@wangeditor/editor-for-vue/latest
> 
> We shouldn't implement your suggested solution though, well meaning as it is.

thank you
