### ISSUE TITLE
[GitHub Actions] "invalid response data" for pending jobs

### ISSUE THREAD

**Issue by kevinoid** [badges/shields#8716]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

After switching to the new route for GitHub Actions workflows, as described in https://github.com/badges/shields/issues/8671 , the badge shows "invalid response data" when the workflow is running, rather than "running" or "pending" or a more informative status.

### 🔗 Link to the badge

https://img.shields.io/github/actions/workflow/status/kevinoid/example-slow-workflow/ci.yml?branch=main

**Comment by chris48s** [comment]
PR up for review from another maintainer https://github.com/badges/shields/pull/8717

**Comment by kevinoid** [comment]
Thanks for the fast fix @chris48s!
