### ISSUE TITLE
shields.io is extremely slow causing timeouts

### ISSUE THREAD

**Issue by ppolewicz** [badges/shields#872]
https://img.shields.io/travis/Backblaze/B2_Command_Line_Tool/master.svg?label=Travis%20CI <- this loads for 7 to 12 seconds, causing a timeout in standard image requests when we use the shields in `README.md`

![shield-b2-timeout](https://cloud.githubusercontent.com/assets/726553/22657201/f3d68428-ec95-11e6-952b-1720e54c55de.png)

**Comment by GMaiolo** [comment]
+1

**Comment by espadrine** [comment]
Thanks for raising the issue. Let's merge this issue with https://github.com/badges/shields/issues/868.
