### ISSUE TITLE
invalid query parameter: branch

### ISSUE THREAD

**Issue by Yurunsoft** [badges/shields#8720]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

invalid query parameter: branch

### 🔗 Link to the badge

https://img.shields.io/github/actions/workflow/status/imiphp/imi/ci.yml?branch=2.1

**Comment by chris48s** [comment]
We've just merged https://github.com/badges/shields/pull/8734 and deployed to production, which fixes this bug.
