### ISSUE TITLE
SensioLabs Insights Inaccessible

### ISSUE THREAD

**Issue by REBELinBLUE** [badges/shields#873]
My Insights badge shows as inaccessible https://github.com/REBELinBLUE/deployer/blob/master/README.md

and so does the example on https://shields.io/

**Comment by ResidentMario** [comment]
Probably a dupe of #868.

**Comment by enumag** [comment]
@ResidentMario I don't think so. That problem has different effect.

**Comment by francoispluchino** [comment]
I just tested, and the url `https://insight.sensiolabs.com/api/projects/{project_id}` requires authentication. Would not the problem be here? (The server has not auth information, see https://github.com/badges/shields/blob/a4a46b070cc4f17f412e54ac3d17eeb0059436a5/server.js#L1210).

**Comment by arcanedev-maroc** [comment]
Same here: https://github.com/ARCANEDEV/LaravelAuth/blob/master/README.md

**Comment by deemru** [comment]
You can find a reason here: https://insight.sensiolabs.com/account

> HTTP Basic Authentication is required for all API requests. 
Your user is xxxxxx. 
Your password (API token) is xxxxxxxxxx.

**Comment by francoispluchino** [comment]
Yes, and this was not the case before for public projects.

**Comment by francoispluchino** [comment]
I have just contacted SensioLabs support.

**Comment by francoispluchino** [comment]
My memory plays tricks on me. The authentication was always required, see the issue #437.

@espadrine Try to regenerate your API token? It worked 2 years ago.

**Comment by enumag** [comment]
Any update? Badges still don't work.

**Comment by zavoloklom** [comment]
Any changes? "Regenerate an API token" advice doesn't work.

**Comment by paulmelnikow** [comment]
It looks like there is code to send auth information:

https://github.com/badges/shields/blob/a4a46b070cc4f17f412e54ac3d17eeb0059436a5/server.js#L1222-L1227

@espadrine Maybe it is a matter of regenerating the API token.

**Comment by tamtamchik** [comment]
Any update?

**Comment by espadrine** [comment]
@deemru Thanks a lot! That URL https://insight.sensiolabs.com/account indeed contains all the explanation necessary.

It should be better now.

**Comment by enumag** [comment]
@espadrine Indeed it works now. Thanks!

**Comment by salaros** [comment]
sensiolabs badge stopped working for me, how can we fix it?

**Comment by paulmelnikow** [comment]
This is an old issue. Could you open a new one? Thanks!

**Comment by salaros** [comment]
@paulmelnikow OK, sure
