### ISSUE TITLE
"Invalid" on npm badge that previously worked

### ISSUE THREAD

**Issue by davidmurdoch** [badges/shields#8737]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

This npm badge used to not say "invalid", now it does.

### 🔗 Link to the badge

https://img.shields.io/npm/dm/ganache?color=b98b5b&style=for-the-badge&labelColor=3c2c30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTAuMzEgMjE0Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2U0YTY2Mzt9LmNscy0ye2ZpbGw6IzVlNDY0ZDt9LmNscy0ze2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPmdhbmFjaGUtbG9nb21hcms8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl84IiBkYXRhLW5hbWU9IkxheWVyIDgiPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTE2NS4zOCwxNjAuMzFjMi4yNCwwLDMtLjUyLDQuMDYtMi4zM3MuNTUtNC43NS41MS01LjU1Yy0uMS0xLjc2LS42OS0zLjcyLS43Ni00LjctLjA1LS42LDAtNC40My4wOS02LDEuMzQtMjQuODQsMTItMzAuNzUsMTUuMDctMzEuNDJhOC41OSw4LjU5LDAsMCwxLDUuOTQuNGwwLTM4aDBsMC0uNTRWNjIuMDljMC01LjQ5LTMuOTEtMTIuMjQtOC42Ni0xNWwtNzcuODctNDVDOTktLjY5LDkxLjE5LS42OSw4Ni40MywyLjA2TDguNjUsNDdDMy44OSw0OS43MSwwLDU2LjQ2LDAsNjJ2OS44MnMwLC4xMSwwLC4xN1Y4Ni4zM2MuNDUuMjUuOTEuNTEsMS4zNi43OSwxLjUsMSwzLDEuNTUsNC41MSwyLjZhNjguNDMsNjguNDMsMCwwLDEsMTIsOS4yOGMuNy42OCwzLjA3LDMuNjYsMy42NCw0LjM2YTQ3LjIyLDQ3LjIyLDAsMCwwLDUuNzcsNi42LDIwLjYyLDIwLjYyLDAsMCwwLDMuODcsMi43OGMyLjI4LDEuMTksNi4wNy45Miw4LC4wNywxNC44Mi02LjQyLDI0LjEyLTMuMiwyOC40MS0uNjIsMTAuNjEsNi4zNywxNC4xNSwxNS4yOCwxNS4yOCwyNi4xYTI5LjIyLDI5LjIyLDAsMCwxLC4xNCw0LjIyYzAsMi41Ny0uMDksNi43LDIuNjIsNy4zOSwzLjg5LDEsNC44My0zLjE2LDUuNDEtNS45MiwxLjMyLTYuMjUsOS42My0xMC4zNSwxNS43Mi03LjIsNC4yLDIuMTcsNS45MiwzLjQsMTAuMDcsMS41Nyw1LjItMi4yOSw3Ljg3LTguMTIsOS42OC0xMS4yMkExOSwxOSwwLDAsMSwxMzQsMTIwYzguMTEtNS4wNSwyOC40Ni0zLjc0LDI5LjIxLDE4LjcsMCwxLjIyLDAsNC4zNCwwLDYuMjQsMCwyLjE0LjA3LDQuMjMtLjA3LDYuNDQtLjA4LDEuNDctLjM1LDMtLjQ5LDQuNTFDMTYyLjU1LDE1NS45LDE2MS43OSwxNjAuMjksMTY1LjM4LDE2MC4zMVoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xOTAuMjgsMTEwLjc1Yy0uNTYtLjE3LTIuMTYtMS4yMi01LjkzLS40LTMuMDkuNjctMTMuNzMsNi41OC0xNS4wNywzMS40Mi0uMDgsMS41My0uMTQsNS4zNi0uMDksNiwuMDcsMSwuNjYsMi45NC43Niw0LjcsMCwuOC42MiwzLjctLjUxLDUuNTVzLTEuODIsMi4zNC00LjA2LDIuMzNjLTMuNTksMC0yLjgzLTQuNDEtMi44My00LjQxLjE0LTEuNDkuNDEtMywuNDktNC41MS4xNC0yLjIxLjA3LTQuMy4wNy02LjQ0LDAtMS45LDAtNSwwLTYuMjRDMTYyLjQxLDExNi4yNywxNDIuMDYsMTE1LDEzNCwxMjBhMTksMTksMCwwLDAtNy40OCw3LjEyYy0xLjgxLDMuMS00LjQ4LDguOTMtOS42OCwxMS4yMi00LjE1LDEuODMtNS44Ny42LTEwLjA3LTEuNTctNi4wOS0zLjE1LTE0LjQuOTUtMTUuNzIsNy4yLS41OCwyLjc2LTEuNTIsNi45MS01LjQxLDUuOTItMi43MS0uNjktMi42Mi00LjgyLTIuNjItNy4zOWEyOS4yMiwyOS4yMiwwLDAsMC0uMTQtNC4yMmMtMS4xMy0xMC44Mi00LjY3LTE5LjczLTE1LjI4LTI2LjEtNC4yOS0yLjU4LTEzLjU5LTUuOC0yOC40MS42Mi0yLC44NS01Ljc0LDEuMTItOC0uMDdBMjAuNjIsMjAuNjIsMCwwLDEsMjcuMjUsMTEwYTQ3LjIyLDQ3LjIyLDAsMCwxLTUuNzctNi42Yy0uNTctLjctMi45NC0zLjY4LTMuNjQtNC4zNmE2OC40Myw2OC40MywwLDAsMC0xMi05LjI4Yy0xLjUyLTEtMy0xLjY0LTQuNTEtMi42LS40NS0uMjgtLjkxLS41NC0xLjM2LS43OWwwLDY1LjU3YzAsNS41LDMuOSwxMi4yNSw4LjY2LDE1bDc3Ljg2LDQ1YzQuNzYsMi43NiwxMi41NSwyLjc2LDE3LjMxLDBMMTgxLjY2LDE2N2M0Ljc2LTIuNzUsOC42NS05LjUsOC42NS0xNVoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik0xMDUsOTkuNzNjLTUuMzksMy4xMS0xNC4yLDMuMTEtMTkuNTgsMGwtNzkuNjEtNDJjLjkuODksODAuNzMsNDcuMjcsODAuNzMsNDcuMjcsNC43NiwyLjc2LDEyLjU1LDIuNzYsMTcuMzEsMCwwLDAsNzkuNzQtNDYuMjQsODAuNjMtNDcuMTNaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNODUuMzIsOC4wOEM5MC43MSw1LDk5LjUyLDUsMTA0LjksOC4wOWw5LjY1LDRjLS45LS44OS0xMC43OC03LjI5LTEwLjc4LTcuMjktNC43NS0yLjc1LTEyLjU0LTIuNzYtMTcuMywwLDAsMC0xNS43Nyw5LjI3LTE2LjY3LDEwLjE1WiIvPjwvZz48L2c+PC9zdmc+

**Comment by chris48s** [comment]
Interesting. The badge itself works
https://img.shields.io/npm/dm/ganache?color=b98b5b&style=for-the-badge&labelColor=3c2c30
its the logo that is breaking it.

There is a limit on the total size of an incoming request (including headers) we can accept. My _guess_ would be something somewhere has changed (maybe on CloudFlare or Fly) that changes a request header or adds an extra request one before the request hits us, and that was enough to push it over the limit?

Fortunately, that SVG image can be further minified without losing any detail that matters when rendered at badge scale, so my suggestion would be to swap it out for

https://img.shields.io/npm/dm/ganache?color=b98b5b&style=for-the-badge&labelColor=3c2c30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTAuMyAyMTQiPjxkZWZzPjxzdHlsZT4uY2xzLTN7ZmlsbDojZmZmfTwvc3R5bGU+PC9kZWZzPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl84IiBkYXRhLW5hbWU9IkxheWVyIDgiPjxwYXRoIGQ9Ik0xNjUgMTYwYzMgMCAzIDAgNC0ybDEtNi0xLTR2LTZjMi0yNSAxMi0zMSAxNS0zMmE5IDkgMCAwIDEgNiAxVjYyYzAtNS00LTEyLTgtMTVMMTA0IDJjLTUtMy0xMy0zLTE4IDBMOSA0N2MtNSAzLTkgOS05IDE1djI0bDEgMSA1IDNhNjggNjggMCAwIDEgMTIgOWw0IDRhNDcgNDcgMCAwIDAgNSA3IDIxIDIxIDAgMCAwIDQgM2g4YzE1LTcgMjQtMyAyOS0xIDEwIDcgMTQgMTUgMTUgMjZhMjkgMjkgMCAwIDEgMCA1YzAgMiAwIDYgMyA3czQtMyA1LTZjMS02IDEwLTEwIDE2LTcgNCAyIDYgMyAxMCAxIDUtMiA4LTggOS0xMWExOSAxOSAwIDAgMSA4LTdjOC01IDI4LTQgMjkgMTl2MTdzLTEgNCAyIDRaIiBzdHlsZT0iZmlsbDojZTRhNjYzIi8+PHBhdGggZD0ibTE5MCAxMTEtNi0xYy0zIDEtMTMgNy0xNSAzMnY2bDEgNGMwIDEgMSA0LTEgNnMtMSAyLTQgMi0yLTQtMi00di0xN2MtMS0yMy0yMS0yNC0yOS0xOWExOSAxOSAwIDAgMC03IDdjLTIgMy01IDktMTAgMTEtNCAyLTYgMS0xMC0xLTYtMy0xNSAxLTE2IDctMSAzLTEgNy01IDYtMy0xLTMtNS0zLThhMjkgMjkgMCAwIDAgMC00Yy0xLTExLTUtMTktMTUtMjYtNS0yLTE0LTYtMjkgMWgtOGEyMSAyMSAwIDAgMS00LTMgNDcgNDcgMCAwIDEtNi03bC0zLTRhNjggNjggMCAwIDAtMTItOWwtNS0zLTEtMXY2NmMwIDUgNCAxMiA5IDE1bDc3IDQ1YzUgMyAxMyAzIDE4IDBsNzgtNDVjNC0zIDgtOSA4LTE1WiIgc3R5bGU9ImZpbGw6IzVlNDY0ZCIvPjxwYXRoIGNsYXNzPSJjbHMtMyIgZD0iTTEwNSAxMDBjLTUgMy0xNCAzLTIwIDBMNiA1OGw4MSA0N2M0IDMgMTIgMyAxNyAwbDgwLTQ3Wk04NSA4YzYtMyAxNS0zIDIwIDBsMTAgNC0xMS03Yy01LTMtMTMtMy0xOCAwTDcwIDE1WiIvPjwvZz48L2c+PC9zdmc+

**Comment by davidmurdoch** [comment]
Sounds plausible. When I view it embedded in a github page while logged in it doesn't work, logged out worked. But if I log in under a private browser it does with! Quite strange. Here is where it is embedded (I'm on mobile right now so I can't debug headers to see if my current mobile season is sending additional headers, or if it is a cache issue): https://github.com/trufflesuite/ganache

It now always works for me when opened directly as an image.

I'll switch it to a smaller version next week either way. Thanks!

**Comment by davidmurdoch** [comment]
Update: it just started working again. Perhaps it was cached in GitHub's "camo" service. It's probably safe to close this; I'll let you do the honors, in case you want to keep the issue around to reproduce.
