### ISSUE TITLE
[REQ] Standard badges for Sourcefoge

### ISSUE THREAD

**Issue by forart** [badges/shields#8741]
### 📋 Description

It would be really useful to have "standard" badges for SF too:
- license
- last commit
- language
- etc

We suggest to use guitarix (wich seems one of the most updated there) for testings: https://sourceforge.net/projects/guitarix/

Hope that inspires.

### 🔗 Data

Dunno if APIs are available but login shouldn't be needed

### 🎤 Motivation

Uses in links collection like https://github.com/forart/HyMPS

**Comment by chris48s** [comment]
If anyone is interested in working on this, we've already got a couple of existing badges for SourceForge in https://github.com/badges/shields/tree/master/services/sourceforge and top-level project stats can be retrieved from `https://sourceforge.net/rest/p/{projectName}` for example, for 7-zip: https://sourceforge.net/rest/p/sevenzip
