### ISSUE TITLE
Semver tags not updating for /github/tag

### ISSUE THREAD

**Issue by Mottie** [badges/shields#875]
When I add a repo tag with a version number prefixed with a "v", the shields badge will properly update. But if I add a tag without a "v", it does not update.

For example, I created a [tag](https://github.com/StylishThemes/Stackoverflow-Dark/tags) `2.9.37` today and `2.9.36` ten days ago, but the shields badge is still showing `v2.9.35` when I did include a "v" prefix.

[![](https://img.shields.io/github/tag/StylishThemes/Stackoverflow-Dark.svg)](https://img.shields.io/github/tag/StylishThemes/Stackoverflow-Dark.svg)

I don't want to start a [debate](https://github.com/mojombo/semver/issues/204) about valid semver, but I think that a tag without a "v" should update the displayed tag.... Semver 2.0.0 states that a "v" prefix is [not a valid semantic version](https://github.com/mojombo/semver/blob/master/semver.md#is-v123-a-semantic-version), but [Git tagging documentation](https://git-scm.com/book/en/v2/Git-Basics-Tagging) only shows examples of tags with a "v" prefix.

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this.

If you're able to look into it further, please feel free to open a PR.

**Comment by platan** [comment]
GitHub tags API returns tags sorted alphabetically by name (https://stackoverflow.com/a/19615235/629762)
```
curl "https://api.github.com/repos/StylishThemes/Stackoverflow-Dark/tags?per_page=100&page=1" -s | jq '.[].name'
"v2.10.22"
"v2.10.21"
"v2.10.20"
...
"v2.5.2"
"v2.5.1"
"v2.5"
curl "https://api.github.com/repos/StylishThemes/Stackoverflow-Dark/tags?per_page=100&page=2" -s | jq '.[].name'
"v2.4"
"v2.3.3"
"v2.3.2"
"v2.3.1"
"2.9.41"
"2.9.37"
"2.9.36"
```
And we are fetching only first 30 tags. It would be hard to solve this problem without loading all tags.

**Comment by Mottie** [comment]
What if you use GraphQL?

Try this command in [the explorer](https://developer.github.com/v4/explorer/)

```
{
  repository(owner: "StylishThemes", name: "Stackoverflow-Dark") {
    tags: refs(refPrefix: "refs/tags/", last: 1) {
      edges {
        tag: node {
          name
        }
      }
    }
  }
}
```

**Comment by paulmelnikow** [comment]
Interesting. The sort is different for a GraphQL query? We aren't making any GraphQL queries today. What's involved? Would you be interested in opening a PR.

Related: #672

**Comment by Mottie** [comment]
Sadly, my time is limited so I won't be able to tackle this right now. And, I haven't really been using GraphQL because doesn't support anonymous queries, yet...

Quote from [this ref](https://platform.github.community/t/anonymous-access/2093/3):

> That's correct, there's no support for anonymous GraphQL queries right now. Almost everything is in the context of a viewer. As we get to closer to full parity with the current REST API, that may change, but we don't have a timeline for that right now.

**Comment by platan** [comment]
In my opinion sorting is identical. `last: 1` returns `v2.10.22` and `first: 10` returns
```
{
  "data": {
    "repository": {
      "tags": {
        "edges": [
          {
            "tag": {
              "name": "2.9.36"
            }
          },
          {
            "tag": {
              "name": "2.9.37"
            }
          },
          {
            "tag": {
              "name": "2.9.41"
            }
          },
          {
            "tag": {
              "name": "v2.3.1"
            }
          },
          {
            "tag": {
              "name": "v2.3.2"
            }
          },
          {
            "tag": {
              "name": "v2.3.3"
            }
          },
          {
            "tag": {
              "name": "v2.4"
            }
          },
          {
            "tag": {
              "name": "v2.5"
            }
          },
          {
            "tag": {
              "name": "v2.5.1"
            }
          },
          {
            "tag": {
              "name": "v2.5.2"
            }
          }
        ]
      }
    }
  }
}
```
So tags without a `v` prefix are at the top of the list.

**Comment by chris48s** [comment]
I'm going to close this one off as the behaviour of this badge was changed in #1628 resolving the issue reported in the first post.
