### ISSUE TITLE
Add version badge for VPM Repository

### ISSUE THREAD

**Issue by anatawa12** [badges/shields#8752]
### 📋 Description

> - Which service is this badge for?

The version badge for VPM, VRChat Package Manager.

> - What sort of information should this badge show?

As other version badges show, version name should be shown.

For `com.anatawa12.animator-controller-as-a-code` at https://vpm.anatawa12.com/vpm.json, badge should be ![](https://img.shields.io/badge/version-0.1.0-orange).

### 🔗 Data

> - Where can we get the data from?
> - Is there a public API?

We can get from VPM Repository JSON.
As there's no official repository to publish user packages, I think it's good to request users for URL to VPM Repository.

> - Does the API require authentication or an API key?

AFAIK, we cannot have access restrictions for VPM repositories. We should just HTTP Get request to the json.

> - Link to the API documentation.

Here's documentation for format of VPM repository: https://vcc.docs.vrchat.com/vpm/repos

### 🎤 Motivation

> What is the specific use case?

Same as endpoints for other package version badges, I wait to put badge on the README.

**Comment by amanakhtar78** [comment]
Hay there, I am new to open source, can you please mentor me and assign me some new basic issue which I can solve and give back to this open source community.
