### ISSUE TITLE
Failure to note that new badge URL is case sensitive causes "Repo or workflow not found" after #8671

### ISSUE THREAD

**Issue by rcmaehl** [badges/shields#8753]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Changing from

`<img src="https://img.shields.io/github/workflow/status/rcmaehl/MSEdgeRedirect/mser?style=for-the-badge" height="45px" /></a>`

to 

`<img src="https://img.shields.io/github/actions/workflow/status/rcmaehl/MSEdgeRedirect/mser.yml?branch=0.8.0.0-dev&style=for-the-badge" height="45px" /></a>`

Causes "Repo or workflow not found". This is due to the previous method not being case sensitive for workflows, and the new method being case sensitive.

### 🔗 Link to the badge

<img src="https://img.shields.io/github/actions/workflow/status/rcmaehl/MSEdgeRedirect/mser.yml?branch=0.8.0.0-dev&style=for-the-badge" height="45px" /></a>

### 💡 Possible Solution

Update documentation and #8671 to note this discrepancy

**Comment by chris48s** [comment]
I've added a note to the top post in https://github.com/badges/shields/issues/8671 that it is case sensitive.
