### ISSUE TITLE
Customising YouTube subscriber badge provides "Invalid" badge

### ISSUE THREAD

**Issue by VeckoTheGecko** [badges/shields#8758]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Overiding label, color, logo, or logo color provides an invalid subscriber count. Default behaviour is unchanged.

![image](https://user-images.githubusercontent.com/36369090/210041686-e876b4b7-d8bc-4883-b9f6-81916bc2a5c2.png)
![image](https://user-images.githubusercontent.com/36369090/210041755-ff136556-ddf6-4939-86cf-12311a748d74.png)

### 🔗 Link to the badge

https://img.shields.io/youtube/channel/subscribers/UCuVLG9pThvBABcYCm7pkNkA?label=test&style=for-the-badge

**Comment by VeckoTheGecko** [comment]
Likely a bug introduced by a recent merge/change, as this badge was working recently.

**Comment by chris48s** [comment]
https://img.shields.io/youtube/channel/subscribers/UCuVLG9pThvBABcYCm7pkNkA?label=test&style=for-the-badge works for me.
I think this is probably the same issue as https://github.com/badges/shields/issues/8605
Once again, I didn't catch it while it was not working. I wonder if we are being rate limited.
Lets track it in https://github.com/badges/shields/issues/8605
