### ISSUE TITLE
Cannot get java icon badge

### ISSUE THREAD

**Issue by mftakhullaziz** [badges/shields#8769]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I using that link https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=java&logoColor=white and the java icon badges not showing

### 🔗 Link to the badge

https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=java&logoColor=white

**Comment by chris48s** [comment]
Hi. The named logos in shields come from the [SimpleIcons](https://github.com/simple-icons/simple-icons) project. The java logo was removed from the SimpleIcons set in version 7. It won't be re-introduced.

More info: https://github.com/simple-icons/simple-icons/issues/7374
