### ISSUE TITLE
Deprecate LGTM

### ISSUE THREAD

**Issue by chris48s** [badges/shields#8770]
:clipboard: **Description**

On 16 December 2022 lgtm.com was shut down

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/#16th-of-december-lgtm-com-will-be-shut-down

We should deprecate the service and also remove the dead LGTM badge from our own README.

@PaulaBarszcz - if you were looking for a quick issue to pick off, this is a nice easy bit of maintenance. When upstream services go away like this, first we convert them to a `deprecatedService` before eventually removing the route completely. This PR is a good example https://github.com/badges/shields/pull/8501

(also I need to circle back to https://github.com/badges/shields/pull/8621 but that is another issue)

**Comment by PaulaBarszcz** [comment]
> @PaulaBarszcz - if you were looking for a quick issue to pick off, this is a nice easy bit of maintenance.

Correct, thanks! Good idea. I'd like to work on it :)
