### ISSUE TITLE
Deprecate Atom Package Manager (APM)

### ISSUE THREAD

**Issue by jameschensmith** [badges/shields#8772]
#### Description

On December 15th, 2022, the Atom text editor and all the projects under the Atom organization were sunsetted. This also included APM. The endpoints associated with APM should be cleaned up.

#### Are you willing to work on this?

Yes.

#### Additional resources

- [Sunsetting Atom | The GitHub Blog](https://github.blog/2022-06-08-sunsetting-atom/)

**Comment by chris48s** [comment]
Thanks. Since you've indicated you are happy to work on this: When upstream services go away like this, first we convert them to a `deprecatedService` before eventually removing the route completely. This PR is a good example to look at https://github.com/badges/shields/pull/8501
