### ISSUE TITLE
Only use badge rendering (locally)

### ISSUE THREAD

**Issue by bittner** [badges/shields#878]
Is there a way to use the badges locally [without having to install](https://github.com/badges/shields/blob/master/INSTALL.md) the npm package and set up a server?

Motivation
-----------
I run a site that manages projects, and displays status information about various external services (hosted repositories, CI servers, monitoring, etc.) for each of them in a list. It would look nice if I used badges for all kind of status information (e.g. things I have in my local database). Creating a server request to shields.io, or a self-hosted instance, for each badge would be possible but seems like an overkill to me.

Is there a sensible way to use the design of the shields badges in a local project?

Example
----------
I'm running Django, so I would create a Django app that may provide a [template tag](https://docs.djangoproject.com/en/stable/ref/templates/builtins/) to easily render badges in template files, e.g.

``` django
{% badge "Last commit" "24 minutes ago" "orange" %}
{% badge "GitLab CI" "running" "lightblue" %}
{% badge "Sentry" "0 issues" "green" %}
```  

Can I reuse some functionality from this project? (Ideally, I would like depend on your implementation - **not** _copy_ source code -, so any of your design changes automatically promote to the app.)

**Comment by cdornan** [comment]
I am doing similar -- I just download the svgs into my images folder. In some instances I am editing the images with sed-like tools.

**Comment by espadrine** [comment]
You can simply fetch a shields.io image, eg. https://img.shields.io/badge/last%20commit-24%20minutes%20ago-orange.svg, and cache it or store it locally, so that you don't perform a request every time.

If you want to not rely on the shields.io servers, you can also use the CLI program:

```
$ sudo npm install -g gh-badges
$ badge 'last commit' '24 minutes ago' :orange @flat
<svg…>…</svg>
```

Or, if you use Node.js, you can use shields.io as a standalone library

```js
var badge = require('gh-badges');
badge.loadFont('/path/to/Verdana.ttf', function(err) {
  badge({ text: ["build", "passed"], colorscheme: "green", template: "flat" },
    function(svg, err) {
      // svg is a String of your badge.
    });
});
```

Those options are described in INSTALL.md.

**Comment by paulmelnikow** [comment]
Three good suggestions.

On a web server, the subprocess route might be a little slow. Running `node gh-badge.js 'last commit' 'hi' :orange @flat` takes 650 ms on my system.

I imagine that could be optimized.

**Comment by paulmelnikow** [comment]
Feel free to reopen if you'd like to discuss further.
