### ISSUE TITLE
Add Github clones count

### ISSUE THREAD

**Issue by OmgImAlexis** [badges/shields#880]
Since our project uses git to handle updating we don't actually get any downloads from the releases zip files which means our downloads badge would be at 0 forever.

Would it be possible for clone counts to be added as an option for the downloads badge?
I'm not sure if Github allows this in their API or if they'd be willing to add it.

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

Would it be helpful to show, say, one week's worth of clones?

The API provides 14 days of clone data: https://developer.github.com/v3/repos/traffic/#clones

**Comment by OmgImAlexis** [comment]
That'd be a great start. 👍

**Comment by paulmelnikow** [comment]
We have [a tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md). Would you like to open a PR?

**Comment by platan** [comment]
According to https://developer.github.com/v3/repos/traffic/:
> For repositories that you have push access to, the traffic API provides access to the information provided in the graphs section.

So we cannot get information about number of clones. Traffic data is available only for repo owner (push access), no matter how it is accessed (REST API or webpage).

**Comment by paulmelnikow** [comment]
Seems like this would be difficult to do then, except perhaps for privately hosted Shields servers.

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
