### ISSUE TITLE
Github shields for other projects

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#881]
Thanks for this great project! I love it and use it often.

How feasible would it be to show shields for other projects?

For example, here is [a list of zsh plugins](https://github.com/unixorn/awesome-zsh-plugins#plugins). The "awesome lists" tend to list a lot of github repos. When looking at a list like that, it'd be helpful to know which ones have stars, forks, the number of contributors, and so on.

At a high level, what would be involved?

**Comment by agboom** [comment]
I'm curious as to what you mean with "other projects". Knowing which projects have stars involves just adding the right Shields integration to the corresponding project.

E.g. the first in the list of zsh plugins would be:
```markdown
[![GitHub stars](https://img.shields.io/github/stars/dalefukami/accurev-zsh.svg?style=social&label=Star)]()
```
Resulting in:
[![GitHub stars](https://img.shields.io/github/stars/dalefukami/accurev-zsh.svg?style=social&label=Star)]()

You can fork and edit the awesome list to add those shields :)

**Comment by paulmelnikow** [comment]
Yeah, indeed!
