### ISSUE TITLE
add down_message and up_message to uptime robot badge

### ISSUE THREAD

**Issue by M4TZ3-op** [badges/shields#8816]
would be verry nice, thanks :)

**Comment by chris48s** [comment]
If someone wants to work on this, there are helpers in https://github.com/badges/shields/blob/master/services/website-status.js which are used by `website` and `nodeping` services that could be applied to uptimerobot as well.

**Comment by pr7prashant** [comment]
Will try this one.

**Comment by filipgrudzien** [comment]
Since it's not done yet, I will try to fix it

**Comment by filipgrudzien** [comment]
https://github.com/badges/shields/pull/9662 I attempted to add it, please let me know if this is what was expected.
