### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by jerome724** [badges/shields#882]
Oi,

I can't get the node version shield working. I don't really get how the shield is working, when i use ``https://img.shields.io/node/v/v.svg`` i get ``>=6.0.0`` or when i use ``lol`` i get ``>=0.6.0``.

How can i get the latest version? eg v7.7.2? Or can i even get the node version from my package.json?

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

I'm not sure I understand what you want to do. Could you clarify?

**Comment by jerome724** [comment]
Well, i would like to display a specific node version on the node versions badge, but i don't really get how i can set, let's say, the latest node version.
