### ISSUE TITLE
Download count wrong?

### ISSUE THREAD

**Issue by Zibri** [badges/shields#8822]
https://img.shields.io/github/downloads/Zibri/VICE/total
[![GitHub all releases](https://img.shields.io/github/downloads/Zibri/VICE/total?style=for-the-badge)](https://github.com/Zibri/VICE/releases)

Says 2300 downloads but that's wrong. I had 266.

**Comment by chris48s** [comment]
The total downloads badge for GitHub shows the total for all your releases, so its the sum of all the `download_count` values in https://api.github.com/repos/Zibri/VICE/releases?per_page=500
Where are you getting 266 from?

**Comment by Zibri** [comment]
my bad.. I counted wrong :D  sorry.
