### ISSUE TITLE
badge cli .output does not work

### ISSUE THREAD

**Issue by Jeansen** [badges/shields#883]
I can run `badge build passed :green @flat` and will get SVG output.  `badge build passed :green .png @flat` will not output anything. The same is true for just  `badge build passed :green` though everything after subject and status is optional.

**Comment by paulmelnikow** [comment]
Hi, have you tried installing `imagemagick`? On a Mac, you can run `brew install imagemagick`. That's what fixes this problem on my machine.

**Comment by paulmelnikow** [comment]
Seems likely that's the issue. If that doesn't solve it, please reopen.

The CLI should report an error instead of giving empty output. Let's track that in #914.
