### ISSUE TITLE
GitHub file size badge shows a different size than GitHub

### ISSUE THREAD

**Issue by loreanvictor** [badges/shields#8845]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

As the title says, GitHub file size badge shows a different file size compared to GitHub itself:

- [The file on GitHub](https://github.com/loreanvictor/nokss/blob/gh-pages/nokss.css.br) (shows 8.93kB as of now, might change)
- [The badge](https://img.shields.io/github/size/loreanvictor/nokss/nokss.css.br?branch=gh-pages) (shows 9.14kB as of now, might change)

The difference is not substantial of course, meaning at least for my use case this is not a serious issue, but an annoyance nonetheless.

### 🔗 Link to the badge

https://img.shields.io/github/size/loreanvictor/nokss/nokss.css.br?branch=gh-pages

**Comment by chris48s** [comment]
This is a kilobytes (1000) vs kibibytes (1024) issue.

9140 bytes/1000 = 9.14 kilobytes
9140 bytes/2014 = 8.93 kibibytes

Pretty-bytes (the library we use for formatting these numbers) uses kilobytes
https://github.com/sindresorhus/pretty-bytes#pretty-bytes

```
import prettyBytes from 'pretty-bytes';
console.log(prettyBytes(9140)); // prints '9.14 kB'
```

btw, where on https://github.com/loreanvictor/nokss/blob/gh-pages/nokss.css.br does it show a file size?

**Comment by loreanvictor** [comment]
Yeah just noticed that GitHub uses `KB` not `kB`:

<img width="678" alt="Screenshot 2023-01-26 at 09 34 32" src="https://user-images.githubusercontent.com/13572283/214791380-88dc891e-0a35-447c-ad04-dfd32c71c58b.png">

Thanks for the response!

**Comment by chris48s** [comment]
Thought I was losing my mind there. GitHub shows really different views depending on whether you are logged in or logged out (and only shows the size if you're logged out)

**logged in:**
![Screenshot at 2023-01-27 20-41-13](https://user-images.githubusercontent.com/6025893/215193214-9520a181-94f9-4232-8f8e-92d02e4c824b.png)


**logged out:**
![Screenshot at 2023-01-27 20-41-55](https://user-images.githubusercontent.com/6025893/215193239-a1cd9222-aded-40cb-ba8a-2b6d0c5773be.png)

**Comment by loreanvictor** [comment]
thats strange. I always see the size of the file, regardless of whether I am logged in or not, a contributor or not, github can show the contents or not, etc.
