### ISSUE TITLE
Alchemy icon missing

### ISSUE THREAD

**Issue by sntgchns** [badges/shields#8847]
When adding the following in HTML
<img height="24" src="https://img.shields.io/badge/-Alchemy-0d1117?logo=alchemy&logoColor=0C0C0E&style=flat-square" />

the icon is not shown, as it is shown for example in
<img height="24" src="https://img.shields.io/badge/-Ethereum-0d1117?logo=ethereum&logoColor=3C3C3D&style=flat-square" />

**Comment by chris48s** [comment]
The first simpleicons release containing an alchemy icon was 8.3.
I deployed a release with that simpleicons version today, so probably yesterday that icon didn't exist yet.
Also, now that it does, you've set the `logoColor` really close to your background colour, so it is nearly invisible.

![](https://img.shields.io/badge/-Alchemy-0d1117?logo=alchemy&logoColor=0C0C0E&style=flat-square) - https://img.shields.io/badge/-Alchemy-0d1117?logo=alchemy&logoColor=0C0C0E&style=flat-square
![](https://img.shields.io/badge/-Alchemy-0d1117?logo=alchemy&style=flat-square) - https://img.shields.io/badge/-Alchemy-0d1117?logo=alchemy&style=flat-square

**Comment by sntgchns** [comment]
It's crazy, but believe it or not, the problem is in the color of the icon, if I add the parameter "&logoColor=0C0C0E" the icon is not displayed, it's not that it gets confused with the background. If I add "&logoColor=ffffff" it looks perfectly. Very strange, because in the explorer it is displayed well. Thank you anyway.

**Comment by sntgchns** [comment]
ok, found a solution, adding #0c0c0e instead #0C0C0E color fix the problem!

**Comment by chris48s** [comment]
I think you might have just been looking at a cached copy tbh. We set quite a long max-age on these static badges.
