### ISSUE TITLE
Dockerhub automated build status badges (ok|error)

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#886]
I would like to add the dockerhub automated build as a status.
I already made an [implementation](https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/README.md).

[![](https://dockerbuildbadges.quelltext.eu/status.svg?organization=niccokunzmann&repository=dockerhub-build-status-image)](https://hub.docker.com/r/niccokunzmann/dockerhub-build-status-image/builds/)

I will see if I can make an implementation here.
If you have any guidance, I am grateful to receive it.

**Comment by niccokunzmann** [comment]
@jrottenberg You may be interested in this. I will look at your PR and learn from it.

**Comment by niccokunzmann** [comment]
Currently, I am struggling to get the secrets to work in `private/secret.json`. Where do I get those?

**Comment by niccokunzmann** [comment]
I figured out, I do not need the secrets. It is just that port 80 is not usable.

**Comment by paulmelnikow** [comment]
This would be a great feature to have. It's been discussed before, see #241. Closing this as a duplicate.
