### ISSUE TITLE
Cloudburst integration 

### ISSUE THREAD

**Issue by IndianBartonka** [badges/shields#8870]
:clipboard: **Add cloudburst integration like a spigot**

https://cloudburstmc.org
https://cloudburstmc.org/resources/

**Comment by chris48s** [comment]
Hello. We have a specific issue template for new badge requests which lays out all the information we'd need to work out if this would be viable and allow someone to work on it if so: https://github.com/badges/shields/issues/new?assignees=&labels=service-badge&template=3_Badge_request.yml
Would you be able to fill that out or update this issue with the missing info? The most important thing I'm not seeing is info on where the data would come from (is there a CloudBurst API?). Thanks

**Comment by IndianBartonka** [comment]
hmmm i don't know if cloudburst has any api

**Comment by chris48s** [comment]
OK. In that case there would be nowhere to get the information from. Feel free to re-open in future if there is a viable data source available.

**Comment by IndianBartonka** [comment]
Oh okey
