### ISSUE TITLE
Wrong (expired?) TLS Certificate on https://shields.io

### ISSUE THREAD

**Issue by matteocorti** [badges/shields#8888]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

CloudFlare is giving "SSL handshake failed"

### 💡 Possible Solution

Update/check your TLS certifcates for shields.io (img.shields.io is OK)

**Comment by calebcartwright** [comment]
Closing as a duplicate of https://github.com/badges/shields/issues/8424
