### ISSUE TITLE
Investigate GitHub merge queues

### ISSUE THREAD

**Issue by chris48s** [badges/shields#8892]
:clipboard: **Description**

Launched today: https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

At the moment we are using repo ranger for this. Try out GH's native implementation on a test repo. Would this give us the same functionality we currently get from repo ranger?

**Comment by chris48s** [comment]
We now have the beta enabled on our repo

![Screenshot at 2023-02-10 14-31-58](https://user-images.githubusercontent.com/6025893/218117322-7567f933-ae5b-4810-8b02-21faf7369404.png)

**Comment by chris48s** [comment]
OK. I enabled this, got it working ( https://github.com/badges/shields/pull/8943 ) and merged this week's dependabot PRs using the GH merge queue instead of repo ranger.

Initial thoughts:

- **Pro**: If we queue a bunch of PRs to merge, this gets all the PRs merged much faster than repo ranger (while maintaining the "Require branches to be up to date before merging" property)
- **Pro**: If we queue a bunch of PRs to merge, this performs fewer builds than repo ranger, reducing the scope for us to hit rate limits
- **Pro**: Because the merge queue doesn't update the source branch, we won't have the issue that `@dependabot rebase` won't work because another bot has committed to the branch
- **Con**: We will run service tests on the initial PR, but once they're in the queue, the service test builds say "No services found. Nothing to do.". This is because the selection of services to run are normally picked up from the PR title and once a commit is in the queue, its not a PR anymore. It is on a `gh-readonly-queue/**` branch. There is probably no workaround for this.
- **Unknown**: I haven't really got a handle on failure modes. I am not clear what happens if a  build fails. What happens to the commit it failed on, and then what happens to the other commits behind it in the queue?
- **Unknown**: I haven't really got a handle on merge conflict handling, either

Based on my experience so far, I think I'm of the opinion that a GH merge queue has enough advantages over Repo Ranger that we should go with this and remove Repo Ranger, but we will continue to evaluate.

@calebcartwright  @PyvesB  - would be interesting to get any feedback from you as well.

Now that the queue is enabled, once we've approved a PR, "merge when ready" will add it to the queue.

![Screenshot at 2023-07-14 18-12-18](https://github.com/badges/shields/assets/6025893/610a64b1-8643-498f-b9e9-10ff5032d4c3)

https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

**Comment by calebcartwright** [comment]
> Con: We will run service tests on the initial PR, but once they're in the queue, the service test builds say "No services found. Nothing to do.". This is because the selection of services to run are normally picked up from the PR title and once a commit is in the queue, its not a PR anymore. It is on a gh-readonly-queue/** branch. There is probably no workaround for this.

IIUC the only (potential) implication of this would be if the successful merging of a PR going first somehow causes service test failures for a different PR that initially passed its service tests but is already in the queue?

I.e. PR-1 and PR-2 both have their CI and respective service tests executed and pass -> both get added to the merge queue -> PR-1 lands but contains code that is somehow incompatible with the changes in PR-2 in a way that would cause the service tests to fail for PR-2 if they were re-executed -> PR-2 still gets merged from the queue because its associated service tests don't get executed -> some type of kaboom, as there's now failing service tests on master

Is that close/accurate?

**Comment by chris48s** [comment]
Yep.

So the point of the "Require branches to be up to date before merging" rule is that we might have 2 open PRs which both pass when tested against master in isolation but one changes something that requires the other to be updated if we merge it first.

So just to make that a bit more tangible with a n example:

- In https://github.com/badges/shields/pull/9233 at the same time we renamed `errorMessages` to `httpErrors`. Imagine that PR is still open.
- If we had another PR open adding a new service, it will still be using `errorMessages`, that is correct when tested against `master`, but if we merge https://github.com/badges/shields/pull/9233 first then the code needs to be updated to use `httpErrors` instead.

So the point of our current "Require branches to be up to date before merging" / repo ranger setup is that we always have to run the tests against an up-to-date master, which hopefully catches that class of error (or increases our chance of catching that class of error).

Using repo ranger achieves that objective. Every PR gets master merged into it before it can be merged.

Using GitHub merge queues, that property is achieved for all the "normal" tests and builds (main, integration, package, e2e, etc). Each commit in the queue gets tested against a branch with the commits ahead of it in the queue already merged onto it. In principle, it could also tun service tests, but because we infer what tests to run from the PR title (and the thing it is actually running the tests on is not a PR any more) we always select zero service tests to run once it is in the queue.

I am going to have a think about whether there is any workaround for that, but there might not be one.

**Comment by PyvesB** [comment]
Having read the above, I'd tend to say pros of switching to GitHub merge queues outweigh the cons.

**Comment by chris48s** [comment]
First time I've seen a conflict in the queue. The process for dealing with queued PRs that will have conflicts seems to be pretty sensible. I think next time I'll let one reach the head of the queue and see what happens if I don't remove it.

![conflict](https://github.com/badges/shields/assets/6025893/e50a4ab0-3a7a-4857-a20a-d5c49d27f09c)
