### ISSUE TITLE
/endpoint returning stale data

### ISSUE THREAD

**Issue by juliendelort** [badges/shields#8905]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

`/endpoint` seems to return stale data. Here is an example:

The following URL: 
 ```
https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/juliendelort/a679662706fd6e691c79282fffa16ada/raw/informel-tests-webkit.json
```
returns the following badge:

![badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/juliendelort/a679662706fd6e691c79282fffa16ada/raw/informel-tests-webkit.json)

(at time of writing the badge says "Webkit (Safari) tests 249/249")

while [the passed url](https://gist.githubusercontent.com/juliendelort/a679662706fd6e691c79282fffa16ada/raw/informel-tests-webkit.json) currently returns:

```js
{
  "schemaVersion": 1,
  "label": "Webkit (Safari) tests",
  "message": "519/520",
  "color": "red"
}
```

I initially thought about the 300 seconds of `cacheSeconds` but it's been like this for almost 24 hours. I also tried different browsers, incognito, different networks etc...

### 🔗 Link to the badge

https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/juliendelort/a679662706fd6e691c79282fffa16ada/raw/informel-tests-webkit.json

**Comment by chris48s** [comment]
Hello. There is a github outage relating to cache invalidation on `githubusercontent.com` domain. See https://github.com/orgs/community/discussions/46691 for details. I suspect it is related to that rather an an issue on our end. I suspect this is sorted now but I reckon track https://github.com/orgs/community/discussions/46691 for updates. Cheers
