### ISSUE TITLE
Proposal: migrate GitHub token pool to fly.io postgres

### ISSUE THREAD

**Issue by chris48s** [badges/shields#8921]
:clipboard: **Description**

There are several known issues with our existing approach to storing all of our tokens in a redis set.
1. The number of tokens we now have is quite large. The size of the data has somewhat outgrown the approach.
2. Storing everything in a single redis key has been kind of a blocker to https://github.com/badges/shields/issues/4169 . We ended up abandoning https://github.com/badges/shields/pull/7037 mainly because we couldn't agree on how best to smoosh more structured data into it, rather than because the idea was fundamentally bad.
3. ComposeDB is kinda expensive for what we actually use it for. In a typical month we spend ~$70 with fly.io, $7 with Heroku and $18.50 with ComposeDB.

I've been mostly ignoring this because it is _not on fire right now_ and the token pool code is a giant PITA, but ComposeDB is shutting down in 2 weeks and finding a drop-in replacement that retains all the same things we had from ComposeDB has been not impossible but also not trivial (conversation about that on Discord). So now this is _on fire right now_ 🔥.

I think the next place we should head to is storing our tokens in a SQL database. In the past running a whole managed SQL database for the one table we need would have been kinda overkill, but fly kinda changes the game. On fly.io we can run a single node, 1x shared CPU, 256MB RAM, 1GB disk [semi-managed](https://fly.io/docs/postgres/getting-started/what-you-should-know/) postgres server for $1.94/mo, which should be plenty tbh (but untested). We'd be responsible for our own upgrades, but backups are included. Having everything inside fly.io (rather than straddling multiple clouds) is also convenient. Moving to a table with one row per token also makes it natural to start adding columns to store permissions against tokens so we can do stuff like `SELECT FROM tokens WHERE read_packages=True` when we need a token with the `read:packages` scope, for example.

There are a few things that occur to me as possible considerations:

1. If you want to work on the token pool, you'll need to run postgres locally. This is already the case for redis - at the moment if you want to work on the token pool, you need to run redis locally. We mostly abstract it from 99% of contributors with redis and we can continue to do so with postgres. Not a big deal IMO.
2. We'll need to run postgres in CI to run the integration tests. This also isn't a big deal. We can run postgres as a service in a GH workflow in much the same way we do with redis.
3. We'll need to migrate our data from redis to postgres. Again, I don't think this is a huge deal. We'll just need to write a one-off script to move the data from A to B.
4. It ties us more to fly.io. At the moment, its pretty easy for us to jump ship from fly to something else. We basically need a docker container and some env vars. Hosted database is a pretty common PaaS feature, but not at the price point fly has it. Having our data in the same place as the compute increases the friction if we need to move because we have to migrate our data too. Postgres is cheap as chips on fly, but we may not be on fly forever.
5. There's a possible impact on self-hosting users. My suspicion is that there are probably zero self-hosting users running their own token pool, but this is something we do need to consider. One option is we just make the change, document it as a breaking change in the next changelog and then if someone is using it, they can stick on an old docker tag while they work out their migration plan. That said, I think we could actually provide a smoother transition if we wanted. At the moment, the persistence layer for redis is https://github.com/badges/shields/blob/1e168b71ef42d66301fa10b30aee1b1666804f84/core/token-pooling/redis-token-persistence.js . I've not tested it, but I reckon the absolute minimum viable redis set to SQL table migration would be leave everything else exactly the same and swap that out for a backend that does something to the effect of (pseudo-code):

```js
export default class SQLTokenPersistence {
  async initialize() {
    return await this.conn.execute("SELECT * FROM tokens;")
  }

  async onTokenAdded(token) {
    await this.conn.execute("INSERT INTO tokens (token) VALUES ($1);", [token])
  }

  async onTokenRemoved(token) {
    await this.conn.execute("DELETE FROM tokens WHERE token=$1;", [token])
  }

  //...
}
```

which is API-compatible with `RedisTokenPersistence`. Then that would allow us to make that a setting, say

> `RedisTokenPersistence` can still be used but its deprecated and will be removed in a future release. Please migrate to `SQLTokenPersistence`.

Then that would provide a clean migration path. Then when we want to start doing something more complicated than just storing a list of tokens we drop `RedisTokenPersistence` in a future release. I suspect that is probably solving a problem nobody has but it is an option if we want to do it. I reckon that MVP implementation may be a good starting point either way.

In the grand scheme of things, I reckon its the way forward medium-term.

**Comment by chris48s** [comment]
decided to shoot first and ask questions later :see_no_evil: https://github.com/badges/shields/pull/8922

**Comment by calebcartwright** [comment]
Generally in favor of this proposal :+1:

**Comment by chris48s** [comment]
token pool is now running on fly postgres in prod
