### ISSUE TITLE
Remove `RedisTokenPersistence`

### ISSUE THREAD

**Issue by chris48s** [badges/shields#8932]
:clipboard: **Description**

Lets leave it in for the March and April releases then after we've done the April release, remove it so it is gone in the May release.

@SnoozeThis wait until April 2 2023

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/XjxEWFli9B4) I will wait until Sun, 02 Apr 2023 00:00:00 UTC and then add a comment.

**Comment by chris48s** [comment]
also remember `REDIS_URL`, associated documentation, integration tests, etc

**Comment by SnoozeThis** [comment]
Resolved.
