### ISSUE TITLE
Include secret.json.sample to make server work in development

### ISSUE THREAD

**Issue by olivierlacan** [badges/shields#894]
@espadrine Is it possible for you to include an example secret.json so people can run the server locally? 

I'm guessing the listing displayed in [CONTRIBUTING](https://github.com/badges/shields/blob/master/INSTALL.md#secretjson) is mentioning all the required keys but that's not very clear. 

It would be much easier to include a file to be copied with a setup task and populated by people locally with their own API keys.

**Comment by paulmelnikow** [comment]
Hi @olivierlacan, thanks for your question.

Wanted to introduce myself as well! I joined the project last week. Have been working on triaging, starting to review PRs, linting, and generally getting up to speed.

The server will run locally without any secrets. It's a bit confusing the way the message is presented (with stack trace), but it's really more of a warning.

I'll open a PR to make this a bit clearer.

**Comment by paulmelnikow** [comment]
See #918

**Comment by olivierlacan** [comment]
Thanks @paulmelnikow. :+1:
