### ISSUE TITLE
Need badges for Github Repo Code frequency or status

### ISSUE THREAD

**Issue by gaohailang** [badges/shields#897]
is there any way to create a badge, which shows the repo(user/repo)'s status, like:

last commit date/time
how about commit frequency(like aggregation 4/weekly, 53/yearly)

Thanks

**Comment by mskonovalov** [comment]
Created PR .
Not sure if that is what @gaohailang  mean, but github provides lack of stats in API

**Comment by gaohailang** [comment]
@mskonovalov exactly~. THX. they are good indicates for repo whether outdated~
