### ISSUE TITLE
YouTube shields show 'invalid' subscriber count

### ISSUE THREAD

**Issue by adamlui** [badges/shields#8989]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Sub counts no longer display on YouTube shield:

![image](https://user-images.githubusercontent.com/10906554/224854901-cee541b5-3694-419d-a50a-a093c5fadf1e.png)

### 🔗 Link to the badge

https://img.shields.io/youtube/channel/subscribers/UCgBMqK7SRL5R__3qM-YAcSg?label=Follow%20%40AdamLuiTube&style=social

**Comment by calebcartwright** [comment]
Thanks but closing as a duplicate of #8605
