### ISSUE TITLE
A command-line tool for making badges

### ISSUE THREAD

**Issue by aleen42** [badges/shields#899]
Here is [a repository](https://github.com/aleen42/badges) I have designed before for making badges more acceptable in documenting, as well as for a collection of standard badges, generated by a command-line tool. The source code of the tool is released in the folder `tool`, and I hope that it will helps shields to make more acceptable and standard badges for different interesting things.

**Comment by paulmelnikow** [comment]
Interesting project. If you have suggestions on how we could use it, let us know.

**Comment by aleen42** [comment]
From the institution of README, you will be taught how to use such a tool to build a qute badge with icons. It's recommended to use svg files as icon input for the parameter `p`. Color can be specified through the parameter `c`. With such a tool, I hope that people can build their standard badges for anything, like brands, tools, etc. No matter what badges have you built, if you appreciate your works, and hope them to be collected in my list, just open an issue like https://github.com/aleen42/badges/issues/1.

**Comment by aleen42** [comment]
@paulmelnikow I hope the tool can be widely used for building amazing badges more easily.

**Comment by paulmelnikow** [comment]
Okay. This issues list is for the code and documentation in this repository, the https://shields.io/ service, and the [gh-badges npm package](https://www.npmjs.com/package/gh-badges). I'm not sure I see an action item. Do you have something to propose?

**Comment by aleen42** [comment]
@paulmelnikow Nothing more, thank you.

**Comment by sword1202** [comment]
So it says we can add badge by command line?
