### ISSUE TITLE
I noticed both Github and Gitlab are supported, any plans to support codeberg?

### ISSUE THREAD

**Issue by Jieiku** [badges/shields#8991]
I noticed both Github and Gitlab are supported, any plans to support [Codeberg.org](https://codeberg.org/) or [git.42l.fr](https://git.42l.fr/) both are based on Gitea

https://shields.io/category/issue-tracking

**Comment by calebcartwright** [comment]
Short answer, no there are no plans but you're welcome to make [specific badge requests](https://github.com/badges/shields/issues/new?assignees=&labels=service-badge&template=3_Badge_request.yml) and/or submit PRs.

Longer answer:

Shields is very much a community project stewarded by a core maintainer team of volunteers. There's a ton of work on our plates, and the number of active maintainers from that team is particularly low these days, so we don't have bandwidth to add any new badges ourselves. It will typically require a member of the community to submit an implementation in order for a new badge to come to fruition.

Any proposals for new badges will be taken under consideration, provided it meets our [guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines) and other relevant criteria (e.g. responsive data source). However, those bandwidth limitations also means that our PR review capacity is strained as well so it could still take quite some time.

Other available-today options that can be utilized are our [Custom Endpoint](https://shields.io/endpoint) feature, and in some cases, our dynamic badges.

Going to go ahead and close this given it was a more general question that's been answered, feel free to open separate issues for specific badge requests if that's something you're interested in.

**Comment by Jieiku** [comment]
Thanks for that, I am going to see if I can figure out how to use the custom Endpoint, no idea if theres a way to make that work or not for gitea based servers.

**Comment by Jieiku** [comment]
Both seem to be compliant, thanks so much for linking the other issue:

https://codeberg.org/ElnuDev/soudan (2 stars)

curl -X GET "https://codeberg.org/api/v1/repos/ElnuDev/soudan/" -H "accept: application/json"|jq -r .stars_count

https://git.42l.fr/HugoTrentesaux/toucan (0 stars)

curl -X GET "https://git.42l.fr/api/v1/repos/HugoTrentesaux/toucan/" -H "accept: application/json"|jq -r .stars_count
