### ISSUE TITLE
JitPack.io support

### ISSUE THREAD

**Issue by kariminf** [badges/shields#900]
Hi,
Thank you for this great project. 

I would like to suggest another service to be added to shields support (JitPack for JVM packaging)

You can find here, the documentation with the default badge
https://jitpack.io/docs/

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion.

Could you make a pull request?

**Comment by kariminf** [comment]
Hi,
I added a pull request 
https://github.com/badges/shields/pull/1049
