### ISSUE TITLE
SimpleX Chat badges

### ISSUE THREAD

**Issue by epoberezkin** [badges/shields#9011]
### 📋 Description

[SimpleX Chat](https://github.com/simplex-chat/simplex-chat#readme) social badges to connect to the users and join groups. The badge would have SimpleX logo with one of the texts:

- Connect to @name
- Join @group"

### 🔗 Data

No external data is necessary, the SimpleX Chat address will be added in HTML / markdown

### 🎤 Motivation

[SimpleX Chat](https://github.com/simplex-chat/simplex-chat#readme) is the first messenger that has no user IDs (not even random numbers), unlike all other communication platforms do.

Since it was [audited by Trail of Bits in November](https://simplex.chat/blog/20221108-simplex-chat-v4.2-security-audit-new-website.html) the users have been growing, and we get the requests for the social icons so people can share their SimpleX contact address more and more frequently. The users also want to share public group addresses.

GitHub users and software developers are our very important users - long before there were mobile apps they used SimpleX CLI. It would be great if you'd allow adding shields.io badges – happy to contribute if that's ok.

Thank you!

**Comment by epoberezkin** [comment]
Ah, great, and I can see somebody just add this: https://github.com/simple-icons/simple-icons/issues/8444

So once it's in simple-icons we can use it without base64 workaround.

What I'd love to be able to do though as to have it listed in your list of social icons, even though it's static - that'll add some   discovery point for SimpleX Chat. Would you be ok with that?

**Comment by chris48s** [comment]
No. As noted in the issue template, we don't add specific routes for badges which only show static information.

We don't list static badges on shields.io, even ones that are really commonly used like
https://github.com/prettier/prettier#badge and
https://github.com/psf/black#show-your-style

Sometimes we do provide a static fallback for badges that used to show some dynamic content (twitter is the most notable example of this).

The directory is there to help users discover and construct the dynamic badges we host. It isn't a promotional tool.

**Comment by epoberezkin** [comment]
Yep, no problem!

Could be a source for the revenue for the service probably?

**Comment by calebcartwright** [comment]
One potential alternative would be a mention out on https://github.com/badges/awesome-badges which is where it's a bit more practical to enumerate various badge "things"

> Could be a source for the revenue for the service probably?

The project receives a sufficient number of donations to be able to cover the operational costs of hosting Shields.io (though any and all donations are still appreciated :smile:). However, there's a massive gap between that operational cost threshold and amount that would be needed for any of the maintainers, all volunteers, to realistically be able to do more with the project (and that's assuming any would even want to; I think we're largely content as volunteers atm though only speaking authoritatively for myself)
