### ISSUE TITLE
Gratipay projects

### ISSUE THREAD

**Issue by lhunath** [badges/shields#904]
There are shields for teams and individuals but apparently not for projects.  Either that - or I'm confused about how to use them.

eg.
project: https://gratipay.com/MasterPassword/
user shield? https://img.shields.io/gratipay/user/MasterPassword.svg
team shield? https://img.shields.io/gratipay/team/MasterPassword.svg
project shield? https://img.shields.io/gratipay/project/MasterPassword.svg

OTOH, both 'team' and 'user' work for my user:
https://img.shields.io/gratipay/user/lhunath.svg
https://img.shields.io/gratipay/team/lhunath.svg

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

I'm not familiar with Gratipay, though I see there was some related discussion in #533.

@dougwilson, I see you were involved in implementing this. Would you have a moment to respond to this question?

**Comment by dougwilson** [comment]
Since projects never existed back when I made a contribution, I really have no idea. I assume that someone would have to add that feature (Teams were launched Dec 12 2016 according to https://gratipay.news/from-teams-to-projects-45c46718507b).

**Comment by paulmelnikow** [comment]
Closed via #1053.
