### ISSUE TITLE
Snapcraft

### ISSUE THREAD

**Issue by slaclau** [badges/shields#9103]
### 📋 Description

It would be great to be able to publish a badge showing the version of a a package in the snap store for the various channels

### 🔗 Data

api.snapcraft.io

### 🎤 Motivation

Lots of packages are published as snaps

**Comment by chris48s** [comment]
Is this a public API? There used to be some docs at https://dashboard.snapcraft.io/docs/api/snap.html#obtaining-information-about-a-snap (refs https://github.com/badges/shields/issues/2544 ) but that link is dead now and I'm not able to find a link to public api docs for snapcraft.

**Comment by slaclau** [comment]
Hi, yes - it is a public API - the docs are at http://api.snapcraft.io/docs/

**Comment by jcs090218** [comment]
It would be great if this is implemented. :D

**Comment by jNullj** [comment]
I can add this one.

**Comment by jNullj** [comment]
This is a small try at it at #9976 
Example render for redis: 
![image](https://github.com/badges/shields/assets/15849761/a4b20f86-e47d-44e4-bf9e-0ce8786c2e8a)

**Comment by jcs090218** [comment]
Wow, this is awesome! You rock! 😍
