### ISSUE TITLE
Cocoapods badges are not fetched 

### ISSUE THREAD

**Issue by MikePendo** [badges/shields#9121]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

some of the badges can be fetched for instance:
![Cocoapods](https://img.shields.io/cocoapods/v/Pendo?color=brightgreen&label=Pendo)
![Cocoapods platforms](https://img.shields.io/cocoapods/p/Pendo?color=brightgreen&label=Pendo)
![Cocoapods](https://img.shields.io/badge/xcframework-compatibale-brightgreen)
Is it because of the cocoapods? Orr it can be resolved on your side?

### 🔗 Link to the badge

![Cocoapods](https://img.shields.io/cocoapods/v/Pendo?color=brightgreen&label=Pendo)
![Cocoapods platforms](https://img.shields.io/cocoapods/p/Pendo?color=brightgreen&label=Pendo)
![Cocoapods](https://img.shields.io/badge/xcframework-compatibale-brightgreen)

**Comment by MikePendo** [comment]
We could use the tag but it doesnt seem like to have a correct sort order:
![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/MikePendo/pendo-mobile-ios)
While the latest one is 2.21.0

**Comment by calebcartwright** [comment]
> Is it because of the cocoapods?

Ultimately yes, in combination with some GitHub behavior. For whatever reason, the CocoaPods API is running brutally slow right now, for example:

```terminal
$ time curl https://trunk.cocoapods.org/api/v1/pods/Pendo/specs/latest

real	0m14.615s
user	0m0.116s
sys	0m0.026s
```

GitHub refuses to render any static content that takes more than 3-4 seconds to respond, which is what is happening here. Our badge server is stuck waiting to get the response from the upstream CocoaPods API and by the time those 15+ seconds (I tested with a few other targets, some taking 20 and 30 seconds) have past and we have a badge ready, GitHub has already long ago decided to not render.

If you try using the badge url outside the GitHub markdown rendering process you'll notice it'll eventually return.

Given how extremely slow the API is I don't think there's really anything we can do on our end; increasing cache duration isn't going to help much and isn't a resolution for a functionally non-responsive API. Someone should try reaching out to the CocoaPods team to see if they can figure out what's going on.

> We could use the tag but it doesnt seem like to have a correct sort order:
> ![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/MikePendo/pendo-mobile-ios)

No, it's correct, but I suspect you may have specified the wrong repo. The badge url you used was https://img.shields.io/github/v/tag/MikePendo/pendo-mobile-ios (btw it's helpful to include the actual badge link in addition to the embeds, even more so when reporting badges that aren't rendering. to that end, i've edited some of your comments to include the url). If you look at GitHub, you'll see your fork's latest tag is indeed v2.12.0

https://github.com/MikePendo/pendo-mobile-ios/tags

![image](https://user-images.githubusercontent.com/13042488/234468220-5799b6eb-d48a-44e4-8a8d-7ab1493b9ef6.png)

I suspect you may have been trying to use the badge for the upstream repo:

**Comment by MikePendo** [comment]
Hi
Thanks a lot, I totally forgot that I forked it (long time ago).
The **swiftui**  is a beta branch and should not be used in official SDK
last question will the following format 
https://img.shields.io/github/v/tag/pendo-io/pendo-mobile-ios?color=brightgreen&label=version&sort=semver
![GitHub tag](https://img.shields.io/github/v/tag/pendo-io/pendo-mobile-ios?color=brightgreen&label=version&sort=semver)
Will assure that no prefixes will be used?
