### ISSUE TITLE
Software maturity badge

### ISSUE THREAD

**Issue by FedericoCeratto** [badges/shields#9151]
### 📋 Description

Hello and thank for the shields.io project.
A badge to describe project maturity would be nice. Values could be experimental / alpha / beta / stable / mature.

Unlike https://github.com/badges/shields/issues/7242 , this is not meant to indicate the speed of development but the level of reliability of the existing codebase and frequency of breaking changes.

### 🔗 Data

Manually selected, no API.

### 🎤 Motivation

It's difficult to gauge the level of stability and maturity of a project at a glance.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close.

We already provide our [static badge builder](https://shields.io/#your-badge) that can be used to produce any type of static badge (one with manually specified attributes) one desires. We only add direct/native badge routes for our dynamic badges (those which fetch changing data from some upstream system of record), and we never add a dedicated route for a specific static badge instance

I.e.

https://img.shields.io/badge/maturity-alpha-orange
![](https://img.shields.io/badge/maturity-alpha-orange)

https://img.shields.io/badge/maturity-stable-blue
![](https://img.shields.io/badge/maturity-stable-blue)
