### ISSUE TITLE
Why widget is not working for my server? widget disabled

### ISSUE THREAD

**Issue by FurkanGozukara** [badges/shields#9160]
I am testing this url and not working any ideas?

https://img.shields.io/discord/772774097734074388?label=Discord&logo=discord

my server : https://discord.com/servers/software-engineering-courses-secourses-772774097734074388

**Comment by chris48s** [comment]
https://img.shields.io/discord/772774097734074388?label=Discord&logo=discord looks like it is working to me

**Comment by calebcartwright** [comment]
Agreed, this seems live and functional so going to close. Feel free to follow up with any questions

https://img.shields.io/discord/772774097734074388?label=Discord&logo=discord
![](https://img.shields.io/discord/772774097734074388?label=Discord&logo=discord)
