### ISSUE TITLE
URL encoding problem...

### ISSUE THREAD

**Issue by Mqxx** [badges/shields#9194]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I have a problem with special URL encoding:

**Does not work:**
`[![Releases Downloads](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads&labelColor=343b42&logo=docusign&logoColor=959DA5)](https://github.com/TypeScriptPlayground/Serial/releases)`

**Works:**
`[![Releases Downloads](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads%20&labelColor=343b42&logo=docusign&logoColor=959DA5)](https://github.com/TypeScriptPlayground/Serial/releases)`

**Problem:**
The problem is the `&label=Downloads` attribute in combination with the `&labelColor=343b42` attribute. The color is not applied when using the label with normal parameters (basic text for example).

When I add `%20` to the end of the `&label=` attribute it works again.

### 🔗 Link to the badge

![Works not](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads&labelColor=343b42&logo=docusign&logoColor=959DA5) ❌ [link](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads&labelColor=343b42&logo=docusign&logoColor=959DA5)
![Releases Downloads](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads%20&labelColor=343b42&logo=docusign&logoColor=959DA5) ✔ [link](https://img.shields.io/github/downloads/TypeScriptPlayground/Serial/total?color=2ebc4b&label=Downloads%20&labelColor=343b42&logo=docusign&logoColor=959DA5)

### 💡 Possible Solution

Adding `%20` to the end of the attribute fixed the problem for me but I don't think this is the solution to the problem. Looks like some sort of encoding/decoding problem of the parameters/attributes from the url.
#9195 

Edit: I am not sure why it did not worked the first time... Now it looks like it does work.

**Comment by chris48s** [comment]
Those two badges both look the same to me.

**Comment by Mqxx** [comment]
Yea...

> Edit: I am not sure why it did not worked the first time... Now it looks like it does work.
