### ISSUE TITLE
Branding / Logotype

### ISSUE THREAD

**Issue by bryanveloso** [badges/shields#92]
#### Recruitment Pitch

![design | needed](https://f.cloud.github.com/assets/134455/1874601/fde9c308-78d5-11e3-880d-deb285b36cda.png)

_The following was written by @whit537, not @bryanveloso._

Shields is an effort to standardize metadata badges across open-source projects. See the [README](https://github.com/badges/shields#readme) for an overview. From a technical standpoint, we have a number of implementations that are now collected under the [badges](https://github.com/badges) GitHub organization, and we're hashing out how to proceed.

On this ticket we are working on the brand identity for Shields (and trying to figure out how open-source design is supposed to work :sheep:). Our proposed process is:
1. Get a bunch of mocks on the table.
2. Discuss mocks in light of our [project definition](https://github.com/badges/shields#specification).
3. Select a single design direction.
4. Iterate from there to completion.

If you'd like to participate, please post mocks as inline images in comments to this ticket.

Thanks! :-)

---
#### Original Description

_from @bryanveloso_

Took a shot at this. A bit abstract, but I believe it gets the point across:

![shields](https://f.cloud.github.com/assets/1258/1843029/52d56be0-74c8-11e3-9a63-56ccab424138.png)

**Comment by olivierlacan** [comment]
Funny enough this design has never matched better than now: 

![](https://camo.githubusercontent.com/cc9e06913c274e4aa42d9804136a7459a5316eec/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313235382f313834333032392f35326435366265302d373463382d313165332d396136332d3536636361623432343133382e706e67)

**Comment by olivierlacan** [comment]
@bryanveloso Did you keep the source files around for this?

**Comment by paulmelnikow** [comment]
@bryanveloso If you've got these files around, hit me up!
