### ISSUE TITLE
Discord new snowflake IDs is invalid

### ISSUE THREAD

**Issue by harshfeudal** [badges/shields#9208]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Discord 2023 new snowflake is invalided with current Shields API

### 🔗 Link to the badge

[![Discord](https://img.shields.io/discord/1103255588051357696?style=flat&logo=discord)](https://discord.gg/pAZZfqC5ST)

### 💡 Possible Solution

As a Discord library contributor, I advise changing API from v6 to v10 in this line:
https://github.com/badges/shields/blob/da615eeef7f2b2d0a8bb62d920218cc5ad428f74/services/discord/discord.service.js#L60

Outdated Discord API may result in an error on defining servers with 19 digits snowflake.

**Comment by chris48s** [comment]
I've just tried the ID in your badge ( 1103255588051357696 ) with the v10 API https://discord.com/api/v10/guilds/1103255588051357696/widget.json and I still get the "Widget Disabled" response.

Do you have an example of a server with a 19-digit ID that has this enabled that we can test with?

If 1103255588051357696 is your discord and you're just trying to get a badge working, can you try following https://player.vimeo.com/video/364220040 as a first step.

Ta

**Comment by harshfeudal** [comment]
Oh cool, I forgot to enable the widget. thanks a lot!
