### ISSUE TITLE
Document private/secret.json

### ISSUE THREAD

**Issue by niccokunzmann** [badges/shields#923]
`private/secret.json` contains all information necessary to use APIs with authentication.

Please add the following to the documentation:

- In the [INSTALL.md][s]
  - [ ] a JSON example that shows the form but is not usable
  - [ ] What the [output](https://github.com/badges/shields/blob/2fb5c72ec663ad34a53c2a28059e53d30a3af6bd/server.js#L27) means and that the server works without
  - for each attribute
    - `bintray_apikey` and `bintray_user`
      - [ ] What is it for and what can you do with it.
      - [ ] How to generate it
      - [ ] Examples that describe the form
      - [ ] How to check if it works
    - `gh_client_id` and `gh_client_secret`
      - [ ] What is it for and what can you do with it.
      - [ ] How to generate it
      - [ ] Examples that describe the form
      - [ ] How to check if it works
    - `shieldsIps` and `shieldsSecret`
      - [ ] What is it for and what can you do with it.
      - [ ] How to generate it
      - [ ] Examples that describe the form
      - [ ] How to check if it works
    - `sl_insight_apiToken` and `sl_insight_userUuid`
      - [ ] What is it for and what can you do with it.
      - [ ] How to generate it
      - [ ] Examples that describe the form
      - [ ] How to check if it works
  - [ ] add a description of what the documentation requires if you add a new attribute
  - [ ] Link to [tutorial][t]
- [ ] Fill the tutorial section about [authentication][t]
  - [ ] How to add a new attribut
  - [ ] How to check if it is present
  - [ ] Link to [secrets section][s]

Further Reading:

- Related issues: #593 #747
- Related Code:
  - https://github.com/badges/shields/blob/master/server.js#L36
  - Search for [serverSecrets](https://github.com/badges/shields/search?utf8=%E2%9C%93&q=serverSecrets+&type=)
- [Tutorial][t]
- [secrets section][s]

[s]: https://github.com/badges/shields/blob/master/INSTALL.md#secretjson
[t]: https://github.com/badges/shields/blob/master/doc/TUTORIAL.md#42-querying-an-api-with-authentication

**Comment by paulmelnikow** [comment]
There was some discussion of this in #2573. Let's tackle it in some form.

**Comment by paulmelnikow** [comment]
Thanks for sorting this!
