### ISSUE TITLE
jsDelivr shield falsely shows 0/month

### ISSUE THREAD

**Issue by adamlui** [badges/shields#9236]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

At times (like the time of this writing) the jsDelivr shield falsely shows 0 hits/month:
![image](https://github.com/badges/shields/assets/10906554/f2d5a6b0-9643-429b-a91f-bc820e186a3c)

### 🔗 Link to the badge

https://img.shields.io/jsdelivr/gh/hm/chatgptjs/chatgpt.js?color=ff6427&label=jsDelivr+Requests

### 💡 Possible Solution

Show 'unavailable' if reponse = 0

**Comment by adamlui** [comment]
I just noticed sometime after passing midnight PST 16 mins ago, the counter works again, so it seems like a rate limit issue

**Comment by chris48s** [comment]
This sounds more like a transient issue with the upstream API tbh. If we were getting rate limited, I would expect the upstream API to return a `429 Too Many Requests` (which would cause us to show an error badge, rather than report zero). We'd only render a badge saying `0/month` if we get back a `200 OK` response saying `{ "total": 0 }`.

Also the jsDelivr API docs say

> The API is free to use and imposes no rate limits


I wonder if @MartinKolarik can shed any light on this one?

**Comment by MartinKolarik** [comment]
Yes, there was an issue with the data availability earlier today, which resulted in zero totals being reported.

**Comment by adamlui** [comment]
@MartinKolarik is it an issue with jsDelivr? If so is it common? (Because weeks ago I had tested this shield on shields.io but it showed 0 so I thought it doesn't work with GitHub libs)

**Comment by adamlui** [comment]
@chris48s i just noticed your gravatar looks like Heisenberg 😄

**Comment by MartinKolarik** [comment]
It seems to happen occasionally around midnight, I opened a task to fix it. Availability of the library is not affected, and the stats are always collected as well, it's just an issue with generating reports for the API.

**Comment by chris48s** [comment]
I'm going to close this issue as there is a fix in progress with the upstream service. Thanks!

**Comment by adamlui** [comment]
@MartinKolarik fyi it happened a few mins ago

**Comment by MartinKolarik** [comment]
Yes, I expect a fix in about two weeks.

**Comment by MartinKolarik** [comment]
We've made some improvements that should prevent this from happening and are further monitoring the stats to confirm 100% availability.

**Comment by adamlui** [comment]
@MartinKolarik this is really great news! I had a related question, today I transferred ownership of chatgptjs/chatgpt.js to kudoai/chatgpt.js. I noticed when I updated the shield it shows 0 monthly hits, but old repo URL shows 103k. Does this mean it will only measure hits for the org used in import URL (so that I will need to wait for users to update URL + 30 days to reach 100k again) or is it smart and combines them?

**Comment by MartinKolarik** [comment]
Stats are per URL, we don't currently have any mapping or special handling for renamed projects - so you'll only get stats for the new project after users update their links.

**Comment by adamlui** [comment]
@MartinKolarik so as I continue to use old badge, the number will shrink as URLs get updated because it measures the last 30 days right?

**Comment by adamlui** [comment]
...and the new badge will grow day by day starting from today?

**Comment by MartinKolarik** [comment]
Yes, that's correct.

**Comment by adamlui** [comment]
Ok that's unfortunate, thanks for the fix though this is a great service!
