### ISSUE TITLE
npm version for tag

### ISSUE THREAD

**Issue by caseyWebb** [badges/shields#925]
It would be nice to be able to show an npm version tag for a branch that is published under something other than the `latest` tag, e.g. `next`.

I'd like to do a PR for this if there is interest.

Proposed URLs:

`https://img.shields.io/npm/v/npm/next.svg`
`https://img.shields.io/npm/v/@cycle/core/canary.svg`

**Comment by paulmelnikow** [comment]
Hi, thanks for this suggestion and the PR!

**Comment by paulmelnikow** [comment]
Resolved via #926.
