### ISSUE TITLE
Badge request: PrimeNG

### ISSUE THREAD

**Issue by m4n50n** [badges/shields#9255]
### 📋 Description

I would like to request the PrimeNG library badge: https://primeng.org/

### 🔗 Data

Only static badge

### 🎤 Motivation

Im working with PrimeNG components

**Comment by chris48s** [comment]
Hello.

As we say in the issue template

> This issue template is for suggesting new badges which **fetch and display data from an upstream service**. If your suggestion is for a static badge (which shows the same information every time it is requested), it is [already possible to make these](https://github.com/badges/shields/blob/master/doc/static-badges.md). We don't add specific routes for badges which only show static information.

Cheers
