### ISSUE TITLE
Invalid Response Data for a Valid Chocolatey Package

### ISSUE THREAD

**Issue by aandrew-me** [badges/shields#9257]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I am facing issue with the Chocolatey Version badge for a particular package. That package is [available on chocolatey](https://community.chocolatey.org/packages/tgpt) but no info is being fetched.

### 🔗 Link to the badge

https://img.shields.io/chocolatey/v/tgpt

### 💡 Possible Solution

It could be a problem on Chocolatey's side

**Comment by chris48s** [comment]
Hmm.

The reason this is failing is because we're expecting the query

```
curl "https://community.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27tgpt%27+and+IsLatestVersion+eq+true" -H "Accept: application/json"
```

to return a single object in the `results` array, but we are getting back 2.

Any idea how both `1.6.7` and `1.6.8` have got `"IsLatestVersion": true` set on them?

**Comment by aandrew-me** [comment]
I see. I had pushed 1.6.8 before 1.6.7 got approved and then they both got approved together and looks like it messed things up. I guess pushing an update would fix it

**Comment by chris48s** [comment]
OK. I'm going to close this as I think this one is something to be resolved upstream, rather than something we want to try and implement behaviour to handle.
