### ISSUE TITLE
badges/website says my site is down, when it's not

### ISSUE THREAD

**Issue by bananabrann** [badges/shields#9279]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

My shield is saying my website is offline, when my website is actually up

![image](https://github.com/badges/shields/assets/43423455/48757e1a-c231-4dd8-814b-7d801cafe926)

But if you go to [the website](https://tv.brannan.cloud), you can see it is up and running just fine. I host the site on Vercel, and have gotten the same results using Vercel's app URLs (https://vercel.com/bananabrann/tv-brannan-cloud/MUcQri9mo4HTNqdDsrmtMGKgGJVQ and https://tv-brannan-cloud.vercel.app/)

Other pics at https://github.com/bananabrann/tv.brannan.cloud/issues/26

### 🔗 Link to the badge

![Website](https://img.shields.io/website?down_color=red&url=https%3A%2F%2Ftv-brannan-cloud.vercel.app%2F&logo=vercel)

```
![Website](https://img.shields.io/website?down_color=red&url=https%3A%2F%2Ftv-brannan-cloud.vercel.app%2F&logo=vercel)
```

### 💡 Possible Solution

I saw [this issue from 2017](https://github.com/badges/shields/issues/1072) and how OP's problem was that a WordPress plugin was making a HEAD request instead of a GET request

However, I'm using a simple SvelteKit app, and am not changing the headers (to my knowledge). If I also look at my dev tools, I see a 200 on initial website load. I'm not sure how to debug this further, so I figured I'd submit a bug/issue. If it's not and I'm doing something wrong, any additional tidbits of info or help would be appreciated. Thank you! 😀

**Comment by chris48s** [comment]
We make a HEAD request to your application, which for https://tv-brannan-cloud.vercel.app/ is returning a 500 response.

You can reproduce with `curl -I "https://tv-brannan-cloud.vercel.app/"`. Don't think I can help you much more than that. Once your app responds to the HEAD with a 200 OK, the badge will say it is up.

**Comment by bananabrann** [comment]
Just an update incase someone finds this later...

I don't know for sure, but this problem actually completely went away when switching to Azure Static Web Apps, and to the "svelte-adapter-azure-swa" SvelteKit adapter. I didn't change any other config: https://github.com/bananabrann/tv.brannan.cloud/pull/31
