### ISSUE TITLE
Move some more docs to the website

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9286]
:clipboard: **Description**

There are a few bits of documentation (like https://github.com/badges/shields/blob/master/doc/static-badges.md and https://github.com/badges/shields/blob/master/doc/logos.md ) which are user-facing (how to use shields.io) rather than developer-facing that ended up being markdown files in the repo, just because the old website made it difficult to put them anywhere sensible.

It is now much easier to make a website page based on a markdown file and link it up in a menu. Lets review this documentation and move it on to shields.io where appropriate.

**Comment by uncenter** [comment]
Both documents look fine but we just have to remember to update the links in the `static-badges.md` document:
> Full documentation of styles and parameters: https://shields.io/#styles
> 
> More documentation on logos: <https://github.com/badges/shields/blob/master/doc/logos.md>

The first link used to reference the styles section on the old homepage but should probably now go to <https://shields.io/badges/static-badge>? And then assuming we move the `logos.md` document to the website as well we should change the "more documentation on logos" link to the actual page on the website.

**Comment by calebcartwright** [comment]
For my own clarity, are we suggesting moving these from markdown to something else?

If so I'd have some reservations about doing that for developer/contributor facing docs. I think there's a high degree of value in having something in-repo that can easily be rendered and viewed, without internet access, and without having to build and run the server

**Comment by chris48s** [comment]
Definitely not for developer/contributor-facing docs.

So stuff like

- https://github.com/badges/shields/blob/master/doc/self-hosting.md
- https://github.com/badges/shields/blob/master/doc/TUTORIAL.md
- https://github.com/badges/shields/blob/master/doc/code-walkthrough.md

Unambiguously stays where it is. No change.

I am just talking about documentation of the form "how to use shields.io as an end user" which has ended up in /doc because the old website was so awkward.
