### ISSUE TITLE
NPM Dev Dependency in Subfolder

### ISSUE THREAD

**Issue by uvulpos** [badges/shields#9314]
### 📋 Description

As a project template maintainer, I want to display the dev dependency of a subfolder, to show the user which version of their favorite web framework I'm using. 

### 🔗 Data

Like the https://shields.io/badges/git-hub-package-json-dependency-version-subfolder-of-monorepo badge, I just need the enhancement of getting it from a subdirectory. I could not get it to work with this or other badges

### 🎤 Motivation

Writing this information to the main readme file can help users to decide for or against my template when they see everything is up-to-date or just outdated.

**Comment by chris48s** [comment]
It is already possible to make this badge.

Here's an example of a badge that picks the version of `concurrently` from https://github.com/cloud-annotations/docusaurus-openapi/blob/main/packages/docusaurus-theme-openapi/package.json

![](https://img.shields.io/github/package-json/dependency-version/cloud-annotations/docusaurus-openapi/dev/concurrently?filename=packages%2Fdocusaurus-theme-openapi%2Fpackage.json) - https://img.shields.io/github/package-json/dependency-version/cloud-annotations/docusaurus-openapi/dev/concurrently?filename=packages%2Fdocusaurus-theme-openapi%2Fpackage.json

We've recently migrated to a new frontend, and reviewing the exact combinations of  examples of each badge variant that we show on the website is something we are working on. At the moment this is imperfect.

**Comment by calebcartwright** [comment]
Going to close as the badge already exists as noted above
