### ISSUE TITLE
Snyk vulnerabilities shield shows 'Invalid response data'

### ISSUE THREAD

**Issue by adamlui** [badges/shields#9325]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Instead of count it shows 'Invalid response data'

![image](https://github.com/codefactor-io/codefactor/assets/10906554/6c579bad-8851-49f7-bd2a-9b238dd6fb54)

### 🔗 Link to the badge

https://img.shields.io/snyk/vulnerabilities/github/adamlui/chatgpt-infinity?label=Vulnerabilities&labelColor=464646&color=gold

### 💡 Possible Solution

I wanted to open an issue in Snyk's GitHub but couldn't find an appropriate repo

**Comment by chris48s** [comment]
The specific error this is failing with is `ValidationError: "message" with value "monitored" fails to match the required pattern: /^\d*$/`

The snyk badges are basically just wrappers or "scrapers" for snyk's native badges which allow you to show the same data but using apply the shields.io styles.

Up until recently (looks like this was still passing in the daily test runs up until yesterday), the native badges showed a number of vulnerabilities. This now seems to have changed: https://snyk.io/test/github/adamlui/chatgpt-infinity/badge.svg
So we're failing to parse a number out of that.

I don't think there is any way we can restore the previous functionality. AFAIK:

- There isn't another native badge we can scrape
- Snyk doesn't have a public API. They have a API where you can authenticate and get data about/perform operations on your own projects, but I don't think they have any API where you can get summary data about everyone's projects.

Happy to be proved wrong on either of those though :pray: 

I guess the other options are:

- Switch our badge to show.. whatever the upstream now shows: monitored or.. other things. Not sure what this really shows/what the other status values would be.
- Retire the snyk badge

**Comment by lprimak** [comment]
Getting the same problem. If it doesn't work, retire it.
