### ISSUE TITLE
pypi versions not properly recognized for wheels-only

### ISSUE THREAD

**Issue by nschloe** [badges/shields#933]
For pypi packages which only distribute wheels, e.g., [pygmsh](https://pypi.python.org/pypi/pygmsh), shields.io doesn't generate a proper version badge, https://img.shields.io/pypi/v/pygmsh.svg.

**Comment by paulmelnikow** [comment]
Thanks for this issue. Would like to get this resolved.

Do you think you could make a PR?

**Comment by nschloe** [comment]
Where in the code would I have to look?

**Comment by paulmelnikow** [comment]
Yep, that's the one.

You can run `npm install` to pull in the dependencies, then `node server.js 1111 localhost`, and open `http://localhost:1111/try.html`.

If you don't have node 6+ installed, you'll need that first. Would suggest installing it via `nodenv` or `nvm` which are available in most package managers.

**Comment by nschloe** [comment]
I just noticed that it suddenly works. This was probably an issue on pypi's end. Closing.
