### ISSUE TITLE
opencollective members counts are imprecise

### ISSUE THREAD

**Issue by xxchan** [badges/shields#9345]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

e.g., `npm run badge -- opencollective/backers/logseq`

request `https://opencollective.com/logseq/members/users.json` returns 990 members. But https://opencollective.com/logseq has more

### 🔗 Link to the badge

https://img.shields.io/opencollective/backers/logseq

### 💡 Possible Solution

Maybe paging is needed?

There's another API https://opencollective.com/logseq.json, which contains `"backersCount":5260`, but it includes both individual backers and organizations (sponsors).

**Comment by xxchan** [comment]
Oh, there are new graphQL API.

**Comment by chris48s** [comment]
This is still an issue, but there is a PR at https://github.com/badges/shields/pull/9346 which takes some steps towards solving it.

In order for that to be viable, we also need to:

- Implement authentication
- Increase the length of time we cache the badges for

Pointers:

- There is a helper for Query String Auth in in https://github.com/badges/shields/blob/master/core/base-service/auth-helper.js and examples of other services using it https://github.com/search?q=repo%3Abadges%2Fshields%20withQueryStringAuth&type=code
- There is documentation for adding new config variables in https://github.com/badges/shields/blob/master/doc/adding-new-config-values.md
- We can sort out an API key to use in production. The anon rate limit should be ok under test and on staging.
- We set the max-age for badges using the  `_cacheLength` property e.g: https://github.com/badges/shields/pull/9343 I'd suggest increasing this to 900 seconds (15 minutes) for the OpenCollective GraphQL badges as a starting point.
