### ISSUE TITLE
How do you provide colours

### ISSUE THREAD

**Issue by pavankataria** [badges/shields#938]
How do you provide colours
Given the following example:
https://img.shields.io/cocoapods/l/SwiftDataTables.svg?style=flat

Trying to make it green like so:
https://img.shields.io/cocoapods/l/SwiftDataTables-green.svg?style=flat or
https://img.shields.io/cocoapods/l/SwiftDataTables.svg?style=flat&color=green
both render the badge to read POD|Invalid

Any ideas?

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

To my knowledge, The [CocoaPods license badge](https://github.com/badges/shields/blob/aa981cba84da6a7e45fd60718da20ede0f0f8ed7/server.js#L2902-L2952) doesn't support overriding the color. Nor do most of the license badges.

Consistency in the badges is useful to users. Most of our license badges seem to be blue, so ideally we'd make this one match.

If you would really like to make the license badge a different color, you could embed a custom badge.

e.g. https://img.shields.io/badge/license-GPL-red.svg

**Comment by paulmelnikow** [comment]
Related: #349 #842
