### ISSUE TITLE
Possible bug fetching Pipfile.lock for public repository

### ISSUE THREAD

**Issue by jackdewinter** [badges/shields#9388]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

As part of the [Application Properties](https://github.com/jackdewinter/application_properties) package, we have a public repo hosted on GitHub.

Using the predefined format and through https://shields.io/badges/git-hub-pipenv-locked-dependency-version-1, with the following properties:
- user: jackdewinter
- repo: application_properties
- packageName: black
- branch: main
the url: https://img.shields.io/github/pipenv/locked/dependency-version/jackdewinter/application_properties/black/main is created.

This URL seems to always show: Default dependency not found.

I have tried various changes and forms of the URL, and each seems to produce the same result.  I have double checked that https://github.com/jackdewinter/application_properties/blob/main/Pipfile.lock contains a valid file.  Based on this information, I would expect it to work, but it is not.

### 🔗 Link to the badge

https://github.com/jackdewinter/application_properties/blob/main/README.md

**Comment by chris48s** [comment]
It is because black is a dev dependency. You want

https://img.shields.io/github/pipenv/locked/dependency-version/jackdewinter/application_properties/dev/black/main

I'm aware the docs for some of these badges with a number of variants are a bit all over the place at the moment. We're working on improving them.

**Comment by jackdewinter** [comment]
Cool... when I went to https://shields.io/badges/git-hub-pipenv-locked-dependency-version-branch to check, there was little information for me to understand that because they are dev dependencies, that they need to be treated differently.

Any way I can help by suggesting better doc wording or anything?

**Comment by chris48s** [comment]
Thanks for the offer of help.

When we launched the new website, we did a bit of a "best effort" conversion of the examples and documentation. One of the next jobs is to review the examples and documentation but at the moment, this process is a bit blocked: The next thing that needs to fall into place is getting https://github.com/badges/shields/pull/9320 merged.
