### ISSUE TITLE
NPM monthly and weekly downloads

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#939]
Not sure when it started but looks like all of the npm total downloads badges are incorrectly showing as zero. Monthly downloads appear to still be working. I noticed this on my own project but a few examples of well known packages below:

https://img.shields.io/npm/dt/express.svg ![](https://img.shields.io/npm/dt/express.svg)
https://img.shields.io/npm/dt/angular.svg ![](https://img.shields.io/npm/dt/angular.svg)
https://img.shields.io/npm/dt/mocha.svg ![](https://img.shields.io/npm/dt/mocha.svg)

https://img.shields.io/npm/dm/express.svg ![](https://img.shields.io/npm/dm/express.svg)
https://img.shields.io/npm/dm/angular.svg ![](https://img.shields.io/npm/dm/angular.svg)
https://img.shields.io/npm/dm/mocha.svg ![](https://img.shields.io/npm/dm/mocha.svg)

**Comment by mesaugat** [comment]
Yes. Looks like it's the same for PyPi.

[![PyPI](https://img.shields.io/pypi/dd/Django.svg)]()
[![PyPI](https://img.shields.io/pypi/dw/Django.svg)]()
[![PyPI](https://img.shields.io/pypi/dm/Django.svg)]()

**Comment by mitchallen** [comment]
It looks like the code for npm/dt is making a call like this:  https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/uuid which returns:  {"error":"exceeded max days of 365"}

Note that npm/dm works fine.  Internally it makes a call like this:  https://api.npmjs.org/downloads/point/last-month/uuid that properly returns:  {"downloads":19184120,"start":"2017-03-14","end":"2017-04-12","package":"uuid"}

**Comment by mesaugat** [comment]
Looks like they have updated the API and now only support download counts for a year or not more than 365 days. 

This works:
https://api.npmjs.org/downloads/range/2017-01-01:2018-01-01/uuid

We'll have to make multiple requests for counting total number of downloads for a package. It's better to switch to a `downloads/year` metric now.

**Comment by espadrine** [comment]
Makes sense. Using `https://api.npmjs.org/downloads/range/` is not that useful with this restriction. Let's switch to `https://api.npmjs.org/downloads/point/last-year/`.

For compatibility purposes, let's have npm/dt return the yearly count, as it's the best we can do. If we again get a way to display dt, we'll switch it to give the more accurate result.

And let's add an npm/dy badge.

**Comment by mesaugat** [comment]
Seems good to me 👍

**Comment by espadrine** [comment]
@mesaugat As for PyPi, there's little we can do for now: https://github.com/pypa/pypi-legacy/issues/396#issuecomment-237634069
Sometimes badges die…
The corresponding issue is  https://github.com/badges/shields/issues/716.

**Comment by mesaugat** [comment]
@espadrine I see, thanks! 

I've not looked at the code properly but I think I will be able to work on `npm/dt` and `npm/dy` as you said.

**Comment by paulmelnikow** [comment]
Am I right that `npm/dt` used to return the cumulative total downloads? That's what it looks like from a query like this:

https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/uuid

I could reach out to the npm registry folks. This badge seems popular with developers. Maybe they would add an endpoint for us.

**Comment by mesaugat** [comment]
Yes, it's quite popular. If we can get an endpoint it would be awesome.

**Comment by mitchallen** [comment]
For npm talk to Benjamin Coe:   https://github.com/bcoe https://twitter.com/BenjaminCoe

**Comment by mesaugat** [comment]
Here's the GitHub repo: https://github.com/npm/download-counts

Reference: http://blog.npmjs.org/post/78719826768/download-counts-are-back

**Comment by mitchallen** [comment]
Via Twitter:  	
		
Benjamin Coe
@BenjaminCoe	
Apr 13
 
@mitchallen @espadrine we're going to lift the limit for the time being, and will introduce an all-time shorthand soon too.

**Comment by paulmelnikow** [comment]
Nice!

**Comment by paulmelnikow** [comment]
Looks like we will need a code change:

https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/uuid

```
{
    error: "unknown error"
}
```

https://api.npmjs.org/downloads/range/2015-01-01:2018-01-01/uuid

```
{
start: "2015-01-01",
end: "2017-04-14",
package: "uuid",
downloads: [
{
downloads: 0,
day: "2015-01-01"
},
{
downloads: 0,
day: "2015-01-02"
},
{
downloads: 0,
day: "2015-01-03"
},
{
downloads: 0,
day: "2015-01-04"
},
...
```

**Comment by bcoe** [comment]
@paulmelnikow I'm adding a change to protect you from this query; should be out in 10 minutes, will keep you updated.

**Comment by bcoe** [comment]
okay, things should magically start working again; I've pinned dates to our epoch, and an appropriate point in the future, so that requesting `1000:3000` doesn't result in an expensive query.

**Comment by paulmelnikow** [comment]
`dt` badges are back! Thanks for the fast response!

**Comment by mesaugat** [comment]
Great, we should add a `downloads/week` and a `downloads/year` badge for npm too.

**Comment by paulmelnikow** [comment]
Agreed. Would you like to open a PR?

**Comment by mesaugat** [comment]
Sure, I will look into it when I find some time.

**Comment by calebcartwright** [comment]
just to say well done folks. thanks for getting this taken care of so quickly!

**Comment by elect86** [comment]
sorry for the ot

but how am I supposed to use the npm badge?
`[![npm](https://img.shields.io/npm/dm/localeval.svg)]()`

I tried
`https://img.shields.io/npm/dm/kotlin-graphics/kotlin-unsigned.svg`

but returns 0..

**Comment by Ebrahim-Ramadan** [comment]
![Image](https://github.com/user-attachments/assets/ec6e894a-67a2-432d-a18e-77ac18ca79ef)

damn
