### ISSUE TITLE
OpenVSX download count badge without version number fails to load

### ISSUE THREAD

**Issue by empathicqubit** [badges/shields#9405]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

My badges on this project don't load: https://github.com/empathicqubit/vscode-cc65-debugger

The reason I think this works is because the openvsx api doesn't like trailing slashes.

I'm not sure if it breaks other stuff, so I have not submitted a pull request.

### 🔗 Link to the badge

Working: https://shields.io/open-vsx/dt/entan-gl/cc65-vice/6.8.1
Not working: https://shields.io/open-vsx/dt/entan-gl/cc65-vice

### 💡 Possible Solution

```diff
diff --git a/services/open-vsx/open-vsx-base.js b/services/open-vsx/open-vsx-bas
e.js
index b7a796566..d6549e894 100644
--- a/services/open-vsx/open-vsx-base.js
+++ b/services/open-vsx/open-vsx-base.js
@@ -31,8 +31,8 @@ export default class OpenVSXBase extends BaseJsonService {
   async fetch({ namespace, extension, version }) {
     return this._requestJson({
       schema: extensionQuerySchema,
-      url: `https://open-vsx.org/api/${namespace}/${extension}/${
-        version || ''
+      url: `https://open-vsx.org/api/${namespace}/${extension}${
+        version ? `/${version}` : ``
       }`,
       httpErrors: {
         400: 'invalid extension id',
```

**Comment by calebcartwright** [comment]
Seeing the same, and that looks like a reasonable fix. Feel free to submit a PR with the change :pray:
