### ISSUE TITLE
Badge request: OrgManager

### ISSUE THREAD

**Issue by m1guelpf** [badges/shields#943]
OrgManager is an invite system for GitHub Organizations.
It'd be nice to have a "join org" badge or a badge for the number of invites sent, you can get the data using the API.

**Comment by paulmelnikow** [comment]
Hi, sounds like an interesting project. Could you point me to a couple projects that are using it? I can't access the [Medium article](https://hackernoon.com/orgmanager-free-invite-system-for-your-github-orgs-4dd6c96a3a6) because of SSL errors.

**Comment by m1guelpf** [comment]
@paulmelnikow [Alternative link to the medium article](https://medium.com/hacker-daily/orgmanager-free-invite-system-for-your-github-orgs-4dd6c96a3a6). I've started a list of project that use OrgManager, but it still needs work (such as automating) so some organizations are missing. In total, `36` organizations use the hosted version, althrough some may selfhost it. I total, 115 invites have been delivered using the hosted version.

**Comment by paulmelnikow** [comment]
Thanks for those links. How about a social badge? It could say `Join <- 26`, with a link to orgmanager. "Join" conveys the idea that it's an open organization, which seems to be the thrust of your project.

It could show the member count of the github organization. That number seems more informative than the invite count. I imagine github has an API for that. I doubt it's public though. Could your server could provide an API to obtain that information for participating projects?

**Comment by m1guelpf** [comment]
@paulmelnikow OrgManager provides an invite count, but it seems like you can't get the member count anywhere. I suggest sticking with the invite count.

**Comment by paulmelnikow** [comment]
Okay, I'm fine with that.

**Comment by m1guelpf** [comment]
@paulmelnikow About the tokens: We currently don't offer read-only tokens, but while they're created, creating an user without any organizations should work, as the API allows to edit them but not to create them.

**Comment by paulmelnikow** [comment]
An orgmanager user? Or, does it need to be a github user?

**Comment by PyvesB** [comment]
My impression is that https://github.com/orgmanager/orgmanager is not maintained anymore. I'll go ahead and close this issue.
