### ISSUE TITLE
Adding a Bazel logo

### ISSUE THREAD

**Issue by sgammon** [badges/shields#9478]
Hi, I asked for a [Bazel](https://bazel.build) logo in #9475 and #9474. These issues and PRs weren't up to snuff so it has been suggested that another issue be filed (with clean history, for _whatever_ reason) to track this feature.

I am happy to copy-and-paste in my previous Bazel arguments regarding adoption, but they are quite long and the previous threads are locked, precluding me from copying and pasting the markup. In lieu of this evidence I would simply ask that people click the linked issues.

**Comment by calebcartwright** [comment]
Thanks, think we had the same thought wrt these two new issues, but let's close this in favor of #9477.

Definitely feel free to participate/make the case there, but I'd also ask that we keep it more technical and constructive and avoid adding any noise from the prior discussions. I'd really like to keep that focused on the logo itself and not continue rehashing the rest.
