### ISSUE TITLE
Update name and logo from Twitter to X

### ISSUE THREAD

**Issue by mbledkowski** [badges/shields#9479]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Formerly known as Twitter, social media platform changed its name to X

**Comment by calebcartwright** [comment]
We don't own/control the logo, it comes from SimpleIcons, and it looks like they are working towards this already - https://github.com/simple-icons/simple-icons/issues/9313

Though I'll leave this open as I suppose we could (should?) update our own badge routes and internal names in the code, although I'm a bit miffed at the notion of adding yet another redirector into the twitter badge processing (we had to change the badge pretty dramatically in response to their api changes)

**Comment by chris48s** [comment]
Yes. Our twitter badge is a static fallback. It doesn't show dynamic data any more so it is really a legacy artefact anyway. I think we can leave the route as it is.
I think we probably follow simple-icons on this. If they alias the `twitter` slug to the `x` logo, then we'll inherit that decision.
We could update the docs in the frontend though.
