### ISSUE TITLE
Controlling text foreground color

### ISSUE THREAD

**Issue by kaerez** [badges/shields#9504]
:clipboard: **Custom Styling**

I know there have been numerous requests for controlling the left and right side of the text.
I need to implement [TLP](https://www.first.org/tlp/) and as the text color cannot be controlled, the only way
of using Shields is with images :(

**Comment by calebcartwright** [comment]
I think it'd be helpful if you could clarify/update the description to be more precise about what specifically you are asking for (as opposed to the "custom styling" framing which is rather general).

I presume that all you're really asking for is the ability to control the font color. If that's correct then I'd encourage you to expand your scenario to help make the case around why this is a decision we should revisit, why the reasoning and points of discussion in those prior issues/requests (e.g. #5455, #4661, #504) shouldn't apply here, etc.

**Comment by calebcartwright** [comment]
Thank you for the additional detail. However, I'm going to close as I don't view this as being actionable for us.

We have our own very specific specification and aesthetic target that we're built around (https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) and it's explicitly a non-goal to try to support any/all others.

The closest you could get today would probably be something like this:

https://img.shields.io/badge/TLP:GREEN-black?style=for-the-badge
![](https://img.shields.io/badge/TLP:GREEN-black?style=for-the-badge)

but even beyond the font color, they'd still be non-compliant (at least AIUI) based on the font face and padding.

Ultimately, our specification and the TLP specification are just too divergent, and we'd have to make way too many changes (IMO) to support this; not to mention that doing so would have the potential to open the floodgates
