### ISSUE TITLE
static-badge-builder documentation is totally confusing for a newbie

### ISSUE THREAD

**Issue by zola-25** [badges/shields#9545]
:clipboard: Documentation confusing.

**'style':** One of: flat (default), flat-square, plastic, for-the-badge, social

What do these mean?

**'label string'**

'Override the default left-hand-side text ([URL-Encoding](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding) needed for spaces or special characters!)'

Except **'build status'** with a whitespace character works fine, adding special characters just prints them encoded.

**'badge-content',** after just removing the label string, works with a hyphenated (unescaped)-color. So no html escaping on needed input there either?

Finally, **'Static Badge builder'** implies it builds static content, like an SVG. But it just creates another URL, whatever format you choose. So there's not much more particularly 'static' about it.

None of this would matter if there were other links in the document explaining these parameters, but there aren't.

Sorry if I sound blunt, I'm just being clear, a very frustrating experience that left me looking at other options.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close as this strikes me as a sharing of an opinion/experience vs. any specific action item.

In general, I'd note:

* We just did a revamp of the front end, so some things are admittedly still a work in progress
* As a self-described newbie, I'd encourage looking at some of the more intro/newbie oriented documentation, including:
  * https://shields.io/docs
  * https://shields.io/docs/static-badges

> What do these mean?

Not entirely clear what this is asking. Shields supports several different styles of badges, users can choose which style they want for any given badge, and the `style` parameter is how one specifies their desired style. Are you asking for a textual description of those individual styles?

> So no html escaping on needed input there either?

Very unclear what you're asking or even referring to here given the preceding text.

> Finally, 'Static Badge builder' implies it builds static content, like an SVG.

It does. the URL is how you access the SVG. Shields serves up badges, primarily as SVGs, and those badges are accessed via specific url routes; the badge builder in the UX exists to help folks figure out the url they need to get the badge they want.

<hr />

I'm unsure how to help/respond to any other aspects in the description as they come across as more of an unstructured criticism as opposed to specific questions/seeking more information. Feel free to ask any follow up questions either here and/or Discord if you prefer.
