### ISSUE TITLE
Not found icon next to the Mastodon badge appears

### ISSUE THREAD

**Issue by smoretti** [badges/shields#9590]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I followed the https://shields.io/badges/mastodon-follow page tutorial to add a Mastodon badge.
Everything looks fine but a "not found" badge appears next to the Mastodon one.

You can look at it at https://github.com/BgeeDB/bgee_pipeline/blob/develop/README.md

What does it mean? What is the problem?

### 🔗 Link to the badge

https://github.com/BgeeDB/bgee_pipeline/blob/develop/README.md

**Comment by chris48s** [comment]
You need to specify the domain param.
I think the correct URL for you would be https://img.shields.io/mastodon/follow/109308703977124988?domain=https%3A%2F%2Fgenomic.social
domain defaults to https://mastodon.social if not supplied.
