### ISSUE TITLE
Ansible Galaxy badge does not work with new galaxy

### ISSUE THREAD

**Issue by cmeissner** [badges/shields#9631]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Ansible Galaxy badge shows `resource not found` since there is the new Ansible galaxy version live.

![image](https://github.com/badges/shields/assets/14936920/9d5edd2d-e9e7-41a3-a321-f9876e259c95)

Setting up a Galaxy badge want a `collectionId` which is not part of the data provided by api

![image](https://github.com/badges/shields/assets/14936920/1b6bf21f-98c2-4d7b-b091-ad6b4e30455a)

```shell
curl -s -XGET https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/index/codeaffen/phpipam/ | jq
{
  "href": "/api/v3/plugin/ansible/content/published/collections/index/codeaffen/phpipam/",
  "namespace": "codeaffen",
  "name": "phpipam",
  "deprecated": false,
  "versions_url": "/api/v3/plugin/ansible/content/published/collections/index/codeaffen/phpipam/versions/",
  "highest_version": {
    "href": "/api/v3/plugin/ansible/content/published/collections/index/codeaffen/phpipam/versions/1.7.0/",
    "version": "1.7.0"
  },
  "created_at": "2023-05-08T23:18:48.027350Z",
  "updated_at": "2023-10-01T09:12:16.157683Z",
  "download_count": 11649
}
```

### 🔗 Link to the badge

https://img.shields.io/badge/dynamic/json?style=flat&label=galaxy&prefix=v&url=https://galaxy.ansible.com/api/v2/collections/codeaffen/phpipam/&query=latest_version.version

### 💡 Possible Solution

The service need to use the current pulp API [1] for getting data for Ansible collections. 

[1] - [Get a specific collection](https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/community/api_v3/#get-a-specific-collection)

**Comment by chris48s** [comment]
So it looks like you're right that our native badges do need updating to the new API version. Thanks for flagging.

but the link you've posted is a dynamic badge, which you could update yourself: https://img.shields.io/badge/dynamic/json?style=flat&label=galaxy&prefix=v&url=https://galaxy.ansible.com/api/v3/collections/codeaffen/phpipam/&query=highest_version.version

**Comment by chris48s** [comment]
Looks like the ansible role and ansible role name badges are still working.

Collection and quality score need updates but we on first glance at the docs it looks like we might not be able to retain the current URLs.

**Comment by cmeissner** [comment]
> So it looks like you're right that our native badges do need updating to the new API version. Thanks for flagging.
> 
> but the link you've posted is a dynamic badge, which you could update yourself: https://img.shields.io/badge/dynamic/json?style=flat&label=galaxy&prefix=v&url=https://galaxy.ansible.com/api/v3/collections/codeaffen/phpipam/&query=highest_version.version

ACK, did it already this way around. Thank you for your assistance.

**Comment by artis3n** [comment]
Just to note if anyone else gets here: the role badges do still work but I found the IDs for roles have changed - e.g. https://github.com/artis3n/ansible-role-tailscale/pull/375 for mine. You can find the new `id` for the role here: https://galaxy.ansible.com/api/v1/roles/ . The old ID is now labeled `upstreamId`.

**Comment by chris48s** [comment]
Have now merged https://github.com/badges/shields/pull/9648

**Comment by artis3n** [comment]
Thanks @chris48s
