### ISSUE TITLE
Github badge for total downloads shows "no release found"

### ISSUE THREAD

**Issue by bucanero** [badges/shields#9633]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm trying to show a badge for total downloads on my GitHub project, but the image keeps saying `no releases found`, when I do have a release published and it has over 800 downloads, as it can be verified from Github's API:

https://api.github.com/repos/bucanero/pkgi-psp/releases/latest

Link to the repo release: 
https://github.com/bucanero/pkgi-psp/releases/tag/v0.8.0

### 🔗 Link to the badge

https://img.shields.io/github/downloads/bucanero/pkgi-psp/total

**Comment by chris48s** [comment]
The endpoint we call for download counts is https://api.github.com/repos/bucanero/pkgi-psp/releases which is returning zero releases for your repo.

I'm pretty sure this is a cache/outdated data issue and it will fix itself in the next ~day or so, but if it doesn't contact GitHub support. Once https://api.github.com/repos/bucanero/pkgi-psp/releases is listing some releases, we'll be able to report a number on the badge. Thanks
