### ISSUE TITLE
Hacktoberfest 2023 Badge Request

### ISSUE THREAD

**Issue by isayakmondal** [badges/shields#9636]
### 📋 Description

Hey, I would like to propose the idea of adding the Hacktoberfest 2023 badge while the event is ongoing in order for the repository owners to mention it with the badge in their repository.
We can add something like this:
![Static Badge](https://img.shields.io/badge/is%20going%20on!%20(549%20PRs%20opened)-message?logoColor=green&label=hacktoberfest)
Inspiration:
![previous-year-badge](https://img.shields.io/github/hacktoberfest/2022/FreeCodeCamp/FreeCodeCamp)

### 🔗 Data

Yes, I think the procedure is the same as it was done in the previous years using the GitHub API.
For eg. https://img.shields.io/github/hacktoberfest/2022/FreeCodeCamp/FreeCodeCamp

### 🎤 Motivation

The idea of adding a "Hacktoberfest 2023" badge in the readme would serve 2 purpose:

1.  It would indicate that the repo is a part of hacktoberfest 2023 (besides the GitHub tags).
2.  It would also the show active number of PR's for this year's hacktoberfest.

**Comment by akshayitzme** [comment]
+1
