### ISSUE TITLE
Record stats by service

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#966]
Logging stats by service would allow us to identify which badges are used the most often. This would be useful for prioritizing fixes and feature requests. It would also help with questions like [the one I raised here](https://github.com/badges/shields/pull/919#issue-218040241):

> A standard API key with https://libraries.io/ covers 60 requests per minute. Will that be enough for the public server?

Currently we're recording stats by format. Those stats were used to drive the choice of the default format. Since that's now been established, there's no need to keep doing that.

In the process of doing that, it'd be great to move the stats code into separate modules, and get some tests around that code.

We could consider removing support for Redis, which is not used on the production servers.

(Much of above comes from an offline conversation with @espadrine)

**Comment by paulmelnikow** [comment]
Started by moving the code into a module and adding a test of the analytics endpoint: #970.

**Comment by techtonik** [comment]
Just be careful not to overanalyze it. There is still `No tracking` promise on http://shields.io =)

**Comment by paulmelnikow** [comment]
It's really fascinating to see all this data! It's always been such a mystery of what people are really using and I have to say, it's really fun to see the numbers climb! Some badges which I personally don't notice that often are more popular than I might have expected! It's interesting to see. 🍬

@platan I tried adding some dashboards but I'm finding the process a bit confusing!

These are some of the ideas I had:

- A pie chart showing badges in the last 7 days by **category**
- A table showing the 50 most popular **individual services** over the last 7 days
- A stacked graph, like the one in Cloudflare (below), showing total requests per day **per server**
- A table showing all the services **families** showing the percentage of the total badges over the last 7 days.

<img width="1008" alt="screen shot 2019-02-27 at 7 30 07 pm" src="https://user-images.githubusercontent.com/1487036/53532772-2b8b5d00-3ac6-11e9-9cd6-9d3bf55633e8.png">

**Comment by chris48s** [comment]
Yeah well done on getting this shipped. Its amazing to finally get some understanding of which integrations are popular and what sort of numbers are involved. There are some quite surprising results in there.
It is probably a bit weirdly skewed in that we probably log less traffic in there on badges that are usually served up via a proxy than ones which aren't, but its great to have these stats.

**Comment by platan** [comment]
@paulmelnikow thanks for ideas for graphs. It would be pleasure for me to add them to grafana. I can do it at the beginning of the next week. This week I don't have access to my pc.

**Comment by paulmelnikow** [comment]
@platan That sounds awesome!

**Comment by platan** [comment]
I've prepared first version of a dashboard with service stats: https://metrics.shields.io/d/aESRBSjmz/services?orgId=2. Feel free to update it (especially names of the graphs/tables). All graph except "Total requests per day per server" show data for selected time range (you can select a time range using 
![screenshot_2019-03-05 grafana - services](https://user-images.githubusercontent.com/1526000/53836074-5591c300-3f8f-11e9-9d61-69fbb9da9f27.png)). 
Do you have ideas for more graphs?

**Comment by paulmelnikow** [comment]
It is so fascinating to see this information!

**Comment by paulmelnikow** [comment]
Seems like this is done! Thanks @platan! Let's open a new issue for any follow-on work.

**Comment by techtonik** [comment]
> Do you have ideas for more graphs?

Horizontal bar chart for badge types - digits are hard to compare. But `grafana` looks like a wrong tool for that kind of dashboards. https://community.grafana.com/t/horizontal-bar-chart-plugin/5269

I also like a blue on white color schema earlier in this thread.

**Comment by paulmelnikow** [comment]
> Horizontal bar chart for badge types - digits are hard to compare.

Do you mean the "All the individual services" and "All the service families" charts?

**Comment by techtonik** [comment]
Both.

![image](https://user-images.githubusercontent.com/515889/64436089-53d6c280-d0cc-11e9-98c2-542845c5dafc.png)

**Comment by paulmelnikow** [comment]
Could you open a new issue?

**Comment by techtonik** [comment]
@paulmelnikow reticketed additional features to #3954.
