### ISSUE TITLE
Dash Escaping is not working anymore in statics

### ISSUE THREAD

**Issue by Eforen** [badges/shields#9679]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

```
https://img.shields.io/badge/test--test2?label=wtf
```

Should be producing `[ wtf | test-test2 ]`
But is `[ wtf |  ]`

### Current Example
![Static Badge](https://img.shields.io/badge/test--test2?label=wtf)

### 🔗 Link to the badge

https://img.shields.io/badge/test--test2?label=wtf

### 💡 Possible Solution

seems that double-dash is exploading the backend somehow

**Comment by chris48s** [comment]
If you want a badge that says `[ wtf | test-test2 ]` using dash escaping, then you should do something like

https://img.shields.io/badge/wtf-test--test2-blue (or whatever colour you want in place of blue)

https://img.shields.io/badge/test--test2 is rendering a badge with:

- the label `test`
- no message
- the colour `test2` (which doesn't exist, so its falling back to the default)

..and then you're overriding the label with `wtf` as a URL param.

**Comment by Eforen** [comment]
That fixed my issue hope it also helps someone else
