### ISSUE TITLE
Does shields.io have a gitter room or something similar?

### ISSUE THREAD

**Issue by samayo** [badges/shields#968]
I am making a badge similar to those found in shields website, and I had some questions to ask. I recon github issue is not the right place. So, it would be nice to add have a gitter page if you don't. Otherwise, great job

**Comment by paulmelnikow** [comment]
Hi! Thanks for the suggestion. I've been chatting with @Daniel15 about this very thing!

We thought we would give Discord a try. Reactiflux adopted it a couple years ago when they outgrew Slack. See reactiflux/volunteers#25 for the discussion which led to that decision.

If that doesn't work out well, we can try Gitter. Gitter's advantage is Github login, though the UI is not as nice.

Stay tuned, will post here when that's online.

Meanwhile, you could open an issue for the new badge, to describe what you want to do and ask questions. Or you could DM me on Gitter.

**Comment by samayo** [comment]
Great!! I will wait for any announcements.

**Comment by paulmelnikow** [comment]
I created a Discord room: https://discord.gg/HjJCwm5

I sense a [Discord badge](https://github.com/badges/shields/pull/977) in our future. 🔮 

Let's finish setting things up and then publicize it!

**Comment by paulmelnikow** [comment]
Badge added to readme in #982.
