### ISSUE TITLE
SLSA Badge

### ISSUE THREAD

**Issue by Dentrax** [badges/shields#9680]
### 📋 Description

https://slsa.dev/images/gh-badge-level3.svg

```
https://slsa.dev/images/gh-badge-level{1,2,3,4}.svg
```

### 🔗 Data

No data

### 🎤 Motivation

https://slsa.dev/

**Comment by chris48s** [comment]
From in the issue template:

> This issue template is for suggesting new badges which **fetch and display data from an upstream service**. If your suggestion is for a static badge (which shows the same information every time it is requested), it is [already possible to make these](https://shields.io/docs/static-badges). We don't add specific routes for badges which only show static information.
