### ISSUE TITLE
Dynamic JSON Badge doesn't work correctly when there are dots in the key.

### ISSUE THREAD

**Issue by EvanHsieh0415** [badges/shields#9688]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When I try to use `$.["admin.mute.can_t_owner"]` to grab the data from https://raw.githubusercontent.com/AlexCai2019/Cartoland/master/lang/tw.json, it shows that 
![image](https://github.com/badges/shields/assets/74277414/1bd78d59-128d-4e73-82a4-d64be10056e3)

But he should be working properly (https://stackoverflow.com/a/22245630/17517140), as shown in this picture: ![Image](https://github.com/badges/shields/assets/74277414/2c9d20bc-4800-45ee-a0de-e97079f0dc54)

### 🔗 Link to the badge

- `https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24.%5B%22admin.mute.can_t_owner%22%5D`

![https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24.%5B%22admin.mute.can_t_owner%22%5D](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24.%5B%22admin.mute.can_t_owner%22%5D
)

**Comment by chris48s** [comment]
Quick fix:
https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24..%5B%22admin.mute.can_t_owner%22%5D

More explanation: https://github.com/badges/shields/issues/8585#issuecomment-1299117946

**Comment by EvanHsieh0415** [comment]
`$["admin.mute.can_t_owner"]` works
![](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24%5B%22admin.mute.can_t_owner%22%5D)

**Comment by EvanHsieh0415** [comment]
`$["admin.mute.can_t_owner"]` works
![](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FAlexCai2019%2FCartoland%2Fmaster%2Flang%2Ftw.json&query=%24%5B%22admin.mute.can_t_owner%22%5D)
