### ISSUE TITLE
"unparseable svg" error with GitHub Actions workflow again

### ISSUE THREAD

**Issue by krlmlr** [badges/shields#9699]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm trying to use shields.io for working around GitHub's limitation of showing their badges on a non-GitHub web page (?). My ultimate use case is the correct display of a page like the following: https://krlmlr.github.io/actions-sync/ .

When trying to use shields.io for one of my workflows, I'm seeing the "unparseable svg" response documented in #9315 and apparently fixed in #9322. Is this supposed to work now?

This particular workflow uses composite actions from a subdirectory of `.github/workflows` : https://github.com/cynkra/dm/blob/main/.github/workflows/R-CMD-check-dev.yaml

### 🔗 Link to the badge

https://shields.io/github/actions/workflow/status/cynkra/dm/rcc%20dev

**Comment by krlmlr** [comment]
Worked around by using https://shields.io/github/actions/workflow/status/cynkra/dm/R-CMD-check-dev.yaml instead, I still wonder if using the workflow name should work too.

**Comment by chris48s** [comment]
https://img.shields.io/github/actions/workflow/status/cynkra/dm/R-CMD-check-dev.yaml is the correct URL to get a badge for this workflow. It is not a workaround.

Workflow names were used in the past, but not any more. See https://github.com/badges/shields/issues/8671

**Comment by krlmlr** [comment]
Thanks. Should the path parameter be called `workflow_file` in the docs?
