### ISSUE TITLE
Incorrect image size for Docker Hub

### ISSUE THREAD

**Issue by Feriman22** [badges/shields#9703]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The Docker Image Size badge displays an incorrect size of a Docker Image. In the example, the badge shows 4.21MB, but the size of the latest version is only 4.02MB.

![image](https://github.com/badges/shields/assets/22872515/a92f5933-4cba-472d-b219-579cd5389ade)

![image](https://github.com/badges/shields/assets/22872515/0da3e7fe-8037-45e1-9608-511437b49130)

### 🔗 Link to the badge

[![Docker Image Size](https://img.shields.io/docker/image-size/feriman25/freednsupdater/latest?logo=docker&style=for-the-badge)](https://hub.docker.com/r/feriman25/freednsupdater/tags)

**Comment by calebcartwright** [comment]
Haven't looked closely at the API response from Docker Hub, but suspect this is just Mebibytes vs. Megabytes

**Comment by Feriman22** [comment]
Yes, it's possible. However, the badge should show the same value as on the Docker Hub.

**Comment by chris48s** [comment]
Yes it is that. The size of the image is reported in bytes via the DockerHub API. This image is 4210627 bytes

4210627/1024/1024 = 4.015...
4210627/1000/1000 = 4.210...

In general, we use https://github.com/sindresorhus/pretty-bytes#pretty-bytes for formatting, which uses kilobytes. I think if someone wants to add a kibibytes formatter which can be used for size badges where the upstream convention is to report kibibytes, we can take a look at a PR.

**Comment by calebcartwright** [comment]
I agree it would be good for us to support this, though I'd prefer that we do so via providing conditional support to give users control. That's because this is an instance where I think we should try to be consistent across our own ecosystem by default and not trying to match what upstream services do
