### ISSUE TITLE
default style for social badges in documentation

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9704]
For some badges, we render them using the social style by default. For example:

https://img.shields.io/youtube/channel/views/UC8butISFwT-Wl7EV0hUK0BQ

Some badges are in the "social" category, but we don't render them using the social style by default. For example:

https://img.shields.io/gitlab/forks/gitlab-org%2Fgitlab

You have to explicitly pass `?style=social`

https://img.shields.io/gitlab/forks/gitlab-org%2Fgitlab?style=social

but then passing `?style=social` does some extra things, like adding a default logo.

This means that on the documentation page for https://shields.io/badges/you-tube-channel-views we render this badge as social by default, but on https://shields.io/badges/git-lab-forks we don't, even though they're both in the "social" category.

We used to deal with this in the frontend by automatically appending `?style=social` for badges in the social category. With the new frontend, we don't have a mechanism to easily insert a param like this.

One solution to this is to make all the social badges render social even when no style param is passed, but I can't remember the history behind this. There may have been some relevant conversation. Was there a reason why we don't do this in some cases, or is it just inconsistency?

**Comment by PyvesB** [comment]
I don't recall any reason, I'm guessing this is inconsistency, or someone who contributed a social badge and happened to not like the social style. I don't think many badges were in this case anyway (though on mobile at the moment, so can't do archeology easily). :)

**Comment by PyvesB** [comment]
> One solution to this is to make all the social badges render social even when no style param is passed

Not necessarily against it, but it'd be a "breaking" change for users, whether it be those who intentionally removed the style param from the badge generated in thebold UI, or the few social category badges that didn't have a social-styled example. It's not too bad though in the sense that they can always override style to go back to a non-social badge if they wanted to.
