### ISSUE TITLE
BlueSky Badge

### ISSUE THREAD

**Issue by kellertuer** [badges/shields#9717]
### 📋 Description

I would like to link to a BlueSky account, similar to linking to Mastodon.
It should show the BlueSky Icon to the left and the Username / full name (like Mastodon) to the right) a static one without the logo is for example

![BlueSky](https://img.shields.io/badge/Bluesky-juliamanifolds.bsky.social-%23007df5?style=plastic)

And I would like to have the BlueSky logo, which might just be a blue rounded square?

### 🔗 Data

HM I just want a logo there is no data, this would be static

### 🎤 Motivation

There are simple logos for Mastodon and such, so I would like to have the same.

**Comment by chris48s** [comment]
From in the issue template:

> This issue template is for suggesting new badges which **fetch and display data from an upstream service**. If your suggestion is for a static badge (which shows the same information every time it is requested), it is [already possible to make these](https://shields.io/docs/static-badges). We don't add specific routes for badges which only show static information.

If what you want is a logo, the icon set we use is simple-icons https://simpleicons.org/ I'd suggest following the conversation in:

- https://github.com/simple-icons/simple-icons/issues/8935
- https://github.com/simple-icons/simple-icons/pull/8856

You could also consider using a custom logo. https://shields.io/docs/logos

**Comment by kellertuer** [comment]
Thanks for the links – I will check out those then.

**Comment by Remi-Gau** [comment]
In case this saves time for anyone::

https://img.shields.io/badge/bluesky-Follow_us_on_bluesky-blue?logo=bluesky

![](https://img.shields.io/badge/bluesky-Follow_us_on_bluesky-blue?logo=bluesky)
