### ISSUE TITLE
Self-hosted shields.io: RequestError: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mehawk5** [badges/shields#9718]
Are you experiencing an issue with...
shields.io

🐞 Description

We have hosted shields.io in our company Openshift server, we added the self signed certificates to Dockerfile and they appear when checking the security tab after deploying the service. But whenever we try to generate a badge using a test api we created and hosted in Openshift as well, it shows: 

{
  "headers": {
    "Accept": "application/json"
  },
  "decompress": true
}
 Handled error  🙅
 RequestError: unable to get local issuer certificate
    at ClientRequest.<anonymous> (file:///usr/src/app/node_modules/got/dist/source/core/index.js:792:107)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket._finishInit (node:_tls_wrap:1017:8)
    at ssl.onhandshakedone (node:_tls_wrap:803:12) {
  prettyMessage: 'inaccessible',
  cacheSeconds: undefined,
  response: undefined
}
 Service data  🛡
 { isError: true, message: 'inaccessible', color: 'lightgray' }

Is there any solution for this?

**Comment by chris48s** [comment]
I don't have any experience with using self-signed certs, so I might be way off base here.


That said, my guess would be that if you want got to make a request using a local cert, some additional config would be required here:

https://github.com/badges/shields/blob/3ea96c31c085454e25a3f989fae0f6c0ef6cbad5/core/base-service/got.js#L10-L18

See got docs here: https://github.com/sindresorhus/got/blob/main/documentation/5-https.md

I think that would be the first place to look.

If you get a patch working, I think we could look at a PR for this, but it isn't an issue that would be high priority for us to work on. It would only be relevant to self-hosted installs. It is not a feature needed by shields.io.

**Comment by mehawk5** [comment]
This actually led me to find the solution, Thank you, I modified _fetchFactory function as follows:

`function _fetchFactory(fetchLimitBytes = fetchLimitBytesDefault) {
  const gotWithLimit = got.extend({
    handlers: [
      (options, next) => {
        const promiseOrStream = next(options)
        promiseOrStream.on('downloadProgress', progress => {
          if (
            progress.transferred > fetchLimitBytes &&
            // just accept the file if we've already finished downloading
            // the entire file before we went over the limit
            progress.percent !== 1
          ) {
            /*
            TODO: we should be able to pass cancel() a message
            https://github.com/sindresorhus/got/blob/main/documentation/advanced-creation.md#examples
            but by the time we catch it, err.message is just "Promise was canceled"
            */
            promiseOrStream.cancel('Maximum response size exceeded')
          }
        })

        return promiseOrStream
      },
    ],
//added this
    https: {
      certificateAuthority: [
        fs.readFileSync('path/to/your/cert.pem'),
        fs.readFileSync('path/to/your/cert2.pem'),
      ],
    },
  })
  return sendRequest.bind(sendRequest, gotWithLimit)
}
`
