### ISSUE TITLE
Pepy Downloads Badge "invalid" on any package

### ISSUE THREAD

**Issue by MrTeferi** [badges/shields#9730]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

**Downloads** > [**Pepy Total Downloads**](https://shields.io/badges/pepy-total-downlods)
Badge  Is failing on any package given, provides a gray "invalid" badge. Also there is a typo in the title for this badge "Pepy Total Downlods" should be amended to "Downloads", which is a simple enough fix.

## To Reproduce
Try with package "django". You can see the service still works on their [main site here](https://www.pepy.tech/projects/django).

### 🔗 Link to the badge

https://shields.io/badges/pepy-total-downlods

### 💡 Possible Solution

Unsure at this time.

**Comment by chris48s** [comment]
This is failing because we're getting a `401 Unauthorized` from pepy.

I've followed up with pepy: https://github.com/psincraian/pepy/issues/573#issuecomment-1807199431

**Comment by MrTeferi** [comment]
Thanks for the followup and clarification :)

**Comment by chris48s** [comment]
Next jobs:

- Update https://github.com/badges/shields/blob/master/services/pepy/pepy-downloads.service.js to pass auth in a `X-Api-Key` header. We should be able to use the `withApiKeyHeader()` auth helper
- Set API keys in CI, staging and prod environments
- Share pepy credentials with rest of team
