### ISSUE TITLE
Rust MSRV Badge

### ISSUE THREAD

**Issue by Sky9x** [badges/shields#9733]
### 📋 Description

Rust crates can specify an "MSRV" (minimum supported rust version), which means that that crate requires a rust compiler of at least that version or newer. Crates.io, the package repository, displays this information on the crate page ([Example](https://crates.io/crates/serde), look on the right under "Metadata").

Service: crates.io (maybe github)
Possible Examples:
![Static Badge](https://img.shields.io/badge/MSRV-v1.72-lightgrey?logo=rust)
![Static Badge](https://img.shields.io/badge/MSRV-v1.72+-lightgrey?logo=rust)
![Static Badge](https://img.shields.io/badge/MSRV-rust%20v1.72.0-lightgrey)
![Static Badge](https://img.shields.io/badge/MSRV-v1.72.0-lightgrey)
![Static Badge](https://img.shields.io/badge/MSRV-unknown-red) (if the crate doesn't specify one)

### 🔗 Data

The MSRV is specified in the `package.rust-version` key in a package's `Cargo.toml` (manifest).

Data can be pulled from crates.io (latest or specific version of a specific crate) and maybe github/etc.
shields.io already has crates.io/github sourced badges, so this could just use that pre-existing architecture.

### 🎤 Motivation

Most crates specify a MSRV for compatibility.
This would be used primarily in project readmes to indicate to users the minimum rust version they need.
Crates like [serde](https://github.com/serde-rs/serde/blob/4676abdc9e6bbbddfb33a00ce8d7e81e92f01120/README.md) (one of the most popular crates) already do this manually, so providing an automatic way to do it would be useful.

**Comment by chris48s** [comment]
Looks like the key in the crates.io API is called `rust_version`

**Comment by calebcartwright** [comment]
Agreed this seems a reasonable badge to add. However, I think we'd want to have two distinct badges, one coming from crates and another (potentially) that's pulling from the manifest from various source control systems.

I'd definitely advise starting with the former, and then we gauge what the appetite would be for the latter once the former has been available for a while

**Comment by Sky9x** [comment]
> Agreed this seems a reasonable badge to add. However, I think we'd want to have two distinct badges, one coming from crates and another (potentially) that's pulling from the manifest from various source control systems.

Agreed. crates.io would be the primary source of information, and I only included github etc because other similar badges like version and license have a github option.
