### ISSUE TITLE
Having Trouble with Minus in JsonPath

### ISSUE THREAD

**Issue by ulfgebhardt** [badges/shields#9739]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When trying to reference `vue-i18n` with a jsonpath badge, I get `unparseable jsonpath query` while https://jsonpath.com/ says everything works fine.

The json ressource is: https://raw.githubusercontent.com/IT4Change/boilerplate-frontend/master/package.json
The queries, which all work on jsonpath, but not on the badge for some reasons are:
- `dependencies.vue-i18n`
- `dependencies.$['vue-i18n']`
- `dependencies.'vue-i18n'`
- ...

Related issue: https://github.com/badges/shields/issues/5580

### 🔗 Link to the badge

https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FIT4Change%2Fboilerplate-frontend%2Fmaster%2Fpackage.json&query=dependencies.vue-i18n&label=vue-i18n&color=green

![.](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FIT4Change%2Fboilerplate-frontend%2Fmaster%2Fpackage.json&query=dependencies.vue-i18n&label=vue-i18n&color=green
)

### 💡 Possible Solution

Unknown

Related issue, which did not solve my problem even tho it did for the author: https://github.com/badges/shields/issues/5580

**Comment by chris48s** [comment]
Looks like https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FIT4Change%2Fboilerplate-frontend%2Fmaster%2Fpackage.json&query=dependencies[%27vue-i18n%27]&label=vue-i18n&color=green is what you're trying to do?

That's `dependencies['vue-i18n']` with the single quotes URL encoded.

**Comment by ulfgebhardt** [comment]
Works like a charm, thank you ❤️ 

Sorry for borthering.
