### ISSUE TITLE
SVG datasets

### ISSUE THREAD

**Issue by shubhamagarwal92** [badges/shields#9753]
:clipboard: **Description**

Hi! 

Interesting work with a nice vibrant community! 

Do you maintain a collection of SVGs that are open-sourced? Is there any API to download the SVGs for research purposes?

**Comment by calebcartwright** [comment]
Thanks for the kind words! 

> Do you maintain a collection of SVGs that are open-sourced? Is there any API to download the SVGs for research purposes?


Not really, at least not in the sense I think you're asking the question. Shields consists of a package/cli and a web service that provide the ability to generate svgs on the fly; we don't have a larged catalog of canned svg files that can be readily grabbed
