### ISSUE TITLE
github repository age

### ISSUE THREAD

**Issue by nektro** [badges/shields#9754]
### 📋 Description

- github
- either the created on date itself, or something like "3 months" / "2 years"

### 🔗 Data

`https://api.github.com/repos/{:owner}/{:repository}` + `.created_at`

### 🎤 Motivation

this info isn't shown on github desktop by default and would be nice to show off the maturity of a project

**Comment by erayerdin** [comment]
@chris48s, if it's okay, I can take this. The only question is how we'd render the datetime. There are three ways I can come up with:

# Prettified Human-Readable Format

Would look similar to these:

![minutes ago badge](https://github.com/badges/shields/assets/2399084/5acb670c-d915-40ec-b2cc-9f3836619a2e)
![years ago badge](https://github.com/badges/shields/assets/2399084/b898bf46-2c3c-40a6-ad06-ea74c11b34bb)
![just now badge](https://github.com/badges/shields/assets/2399084/11eee54b-60cc-47b2-b75a-96dad0e57da0)

Pros:

 - Look pretty
 - Human-readable

Cons:
 - Ambiguous (5 months ago but when exactly?)
 - Would require to introduce another dependency to the codebase unless [this kinda thing](https://dev.to/sh20raj/converting-dates-into-human-readable-time-ago-format-in-javascript-595g) is enough

# Standardized

Might be [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601). Example:

![iso badge](https://github.com/badges/shields/assets/2399084/00a6555d-b9a6-4aa2-bc41-6cbe023f090b)

Pros:
 - A little bit verbose
Cons:
 - Too much verbose if we are going to include time and timezone
 - There are other standards to think about. See [this beautiful thing](https://ijmacd.github.io/rfc3339-iso8601/).

***

So, there are a couple of questions as well.

 - In two cases (and even more than two if we consider the other standards), should we create distinct services for that? If so:
   - Pretty badges would lay under `/github/created-at/pretty/:username/:reponame`.
   - What about the standardized ones? Should we (a) distinct each as `/github/created-at/iso/:username/:reponame` and `/github/created-at/rfc/:username/:reponame` and such or (b) use `/github/created-at/standardized/:username/:reponame?format=rfc` with `format` query parameter defaulting to `iso`?

Case (a) requires two different classes (maybe extending a base `CreatedAtBase`?) while case (b) can be done in a single class but requires query parameters, which must be documented. Documentation part for case (b) is easy anyway, OpenAPI spec already handles that, but case (a) seems more expressive than the other when you think about it.

**Comment by erayerdin** [comment]
Apart from @nektro's assertion "nice to show off the maturity of a project", in the current UI of Github, the only way to know exactly when a project started is to do these steps:

**Step 1:** Click the commit count on the project page.
![click commit count](https://github.com/badges/shields/assets/2399084/03955a5d-a216-432f-808d-74e3d37f4b4a)

**Step 2:** Click next until you reach the initial commit / until the big bang. If the commit count is several hundred, this is really painful.
![click next until the big bang](https://github.com/badges/shields/assets/2399084/7ca27ac1-bbc4-4f5d-9cae-b42971fad981)

**Step 3:** Hover over the prettified datetime on the initial commit to learn when you've started the project.
![hover over the prettified datetime](https://github.com/badges/shields/assets/2399084/fa356979-3a64-4bf9-b6b7-4726138b7076)

AFAIK, there's no other easier way (unless one `curl`s to the API). So, this would really benefit the community.

**Comment by erayerdin** [comment]
New to the codebase so wasn't aware this was a thing. So, I take this as I can start working on a PR?
