### ISSUE TITLE
reddit badge returning "private" when subreddit is actually public

### ISSUE THREAD

**Issue by ReenigneArcher** [badges/shields#9817]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I was asked to open a new issue in #9256 

For the past week or so, reddit badge says my subreddit is private even though it is public.

![image](https://private-user-images.githubusercontent.com/42013603/291009794-5828d21d-b769-4237-9159-bf868b98be12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjE1NTcsIm5iZiI6MTcwMjgyMTI1NywicGF0aCI6Ii80MjAxMzYwMy8yOTEwMDk3OTQtNTgyOGQyMWQtYjc2OS00MjM3LTkxNTktYmY4NjhiOThiZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEzNTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NmJkNWM0NDk0ZDgwNWVkZThlYmJmNmY4NmIzMzQ0M2Q0OTU0Y2FlMjdhYWY1MjE4YTJiN2M0ZjYwYTIyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rx9Uofq6HXQXUKxn12tokYJ9mGjQpbn_5JbiQ_ZSbFU)

![image](https://private-user-images.githubusercontent.com/42013603/291009845-2a897ac7-7f22-4ef5-a909-c2c4fd9f2949.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjE1NTcsIm5iZiI6MTcwMjgyMTI1NywicGF0aCI6Ii80MjAxMzYwMy8yOTEwMDk4NDUtMmE4OTdhYzctN2YyMi00ZWY1LWE5MDktYzJjNGZkOWYyOTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEzNTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmY3ZTg1NTQzMjNhZGZlZTU5NWU0OTVjMTJlMDllYjBiMWZlMmIwYjExM2Y2Y2Y2ZDc5YmE4NWI5OGFkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Snbr2ydBh931NxwYx-Vpg5tH-wRv05paUViXywF7O90)

### 🔗 Link to the badge

https://img.shields.io/reddit/subreddit-subscribers/lizardbyte?labelColor=FF4500&color=FF4500&logoColor=ffffff&label=Reddit&style=for-the-badge&logo=reddit

**Comment by chris48s** [comment]
OK. This is interesting.

In production, all (non-cached) badges seem to be returning this `subreddit is private` error.

Locally, I get a response from https://www.reddit.com/r/lizardbyte/about.json just fine and the badge renders.

Staging and CI. Also getting the 403. The response body is:

```
<!doctype html>
     <html>
  <head>
    <title>Blocked</title>
    <style>
      body {
          font: small verdana, arial, helvetica, sans-serif;
          width: 600px;
          margin: 0 auto;
      }

      h1 {
          height: 40px;
          background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;
      }
    </style>
  </head>
  <body>
    <h1>whoa there, pardner!</h1>

<p>Your request has been blocked due to a network policy.</p>

<p>Try logging in or creating an account <a href=https://www.reddit.com/login/>here</a> to get back to browsing.</p>

<p>If you're running a script or application, please register or sign in with your developer credentials <a href=https://www.reddit.com/wiki/api/>here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
try changing back to default as that can sometimes result in a block.</p>

<p>You can read Reddit's Terms of Service <a href=https://www.reddit.com/wiki/api/>here</a>.</p>

<p>if you think that we've incorrectly blocked you or you would like to discuss
easier ways to get the data you want, please file a ticket <a href=https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140>here</a>.</p>

<p>when contacting us, please include your ip address which is: <strong>[redacted]</strong> and reddit account</p>
  </body>
</html>
```

So it looks like we are explicitly being blocked, probably by IPs rather than user-agent as I have a shields user agent set locally.

Up to 5 days ago, we were seeing `429 calling https://www.reddit.com` being logged but that has stopped.

So.. looks like this is probably related to https://github.com/badges/shields/issues/9256 (sorry - you were right first time). We'll need to implement auth to fix.

**Comment by ReenigneArcher** [comment]
Interesting... I also cannot access this URL from a GitHub runner.

**Comment by chris48s** [comment]
Yep - same for us. Staging and CI/GH actions also blocked

**Comment by chris48s** [comment]
I filled in https://reddithelp.com/hc/en-us/requests/new?ticket_form_id=14868593862164 requesting either an API key or an unban. I linked to this issue and https://github.com/badges/shields/issues/9256

We'll see where it goes.

**Comment by ReenigneArcher** [comment]
I have a reddit bot written in Python which uses PRAW.

I was able to create my own application and authenticate to that, without any support ticket.

https://praw.readthedocs.io/en/stable/getting_started/authentication.html

I definitely am not making as many API requests as Shields would though, so not sure how that would affect everything.

**Comment by ReenigneArcher** [comment]
Is this fixed? Or just working randomly?

![image](https://github.com/user-attachments/assets/a6fccfef-70cc-466d-9a68-2b55bfa9b963)

https://img.shields.io/reddit/subreddit-subscribers/lizardbyte?labelColor=FF4500&color=FF4500&logoColor=ffffff&label=Reddit&style=for-the-badge&logo=reddit

**Comment by ReenigneArcher** [comment]
Now, rate limited: 
![image](https://github.com/user-attachments/assets/3d011657-8e33-4826-8f37-1c22405ed038)

I guess this is an improvement. Can I ask if changes were made here, or if something changed on reddit's side? If something on reddit's side, I can probably cache the data using gh-actions and then use a custom query badge.

**Comment by chris48s** [comment]
We haven't made any changes on our side. Anything that is different has changed on reddit's end.

**Comment by ReenigneArcher** [comment]
This has been working fine lately.
