### ISSUE TITLE
Update thunderstore API call

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9837]
:clipboard: **Description**

Currently the thunderstore version badge relies on an "experimental" endpoint.

There's an upstream issue to get this into a stable /v1 endpoint: https://github.com/thunderstore-io/Thunderstore/issues/970

Once this is done, update our code to use it.

/cc @Lordfirespeed

**Comment by chris48s** [comment]
Looks like the upstream issue is now closed - https://github.com/thunderstore-io/Thunderstore/issues/970

@Lordfirespeed - are you still happy to follow this one up?

**Comment by Lordfirespeed** [comment]
Absolutely! I'm just waiting on the next Thunderstore deploy (I don't think their live API has been updated yet)

**Comment by Lordfirespeed** [comment]
Here's a test URL:
https://thunderstore.io/api/v1/package-metrics/BepInEx/BepInExPack/
