### ISSUE TITLE
Bluesky logo not working

### ISSUE THREAD

**Issue by acelaya** [badges/shields#9843]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Recently, the bluesky logo was added to simple icons, but it is not displayed when trying to use it on a badge.

https://simpleicons.org/?q=Bluesky

### 🔗 Link to the badge

https://img.shields.io/static/v1?label=&message=Bluesky&color=0285FF&logo=bluesky&style=for-the-badge&logoColor=white

### 💡 Possible Solution

I haven't found a suitable workaround. Other icons work just fine.

**Comment by chris48s** [comment]
The bluesky icon was added in simple-icons 10.4. We're still running 10.3

As noted in https://github.com/badges/shields/discussions/5369 (linked from https://github.com/badges/shields/issues/new/choose ) we update packages once a week. We'll update to simple-icons 10.4 next time we process package upgrades, at which point new icons in 10.4 https://github.com/simple-icons/simple-icons/releases/tag/10.4.0 (including bluesky) will become available.

**Comment by acelaya** [comment]
Thanks!
