### ISSUE TITLE
Add Discord button to bottom of try.html

### ISSUE THREAD

**Issue by Daniel15** [badges/shields#985]
Comment from https://github.com/badges/shields/pull/982 after adding the Discord button to the readme.

> Would you like to add it to try.html too? There are some social links in the footer.

**Comment by JHart9** [comment]
It appears it's been added now.
https://github.com/badges/shields/blob/master/try.html#L976

**Comment by Daniel15** [comment]
Sorry, I should clarify. This task means that a Discord badge for Shields' Discord server should be added to the very bottom of the page, where the other social stuff is: https://github.com/badges/shields/blob/master/try.html#L1175
