### ISSUE TITLE
Go Report badge

### ISSUE THREAD

**Issue by crazy-max** [badges/shields#988]
[Go Report](https://github.com/gojp/goreportcard) only provides rounded corners badge and i want flat-square :grinning:

But Go Report does not expose any API. Can you confirm @hermanschaaf ?

**Comment by hermanschaaf** [comment]
@crazy-max It is possible to specify the style on the Go Report Card image, the same as on shields.io, e.g.

```
https://goreportcard.com/badge/github.com/gojp/goreportcard?style=flat-square
```

or 

```
https://goreportcard.com/badge/github.com/gojp/goreportcard?style=plastic
```

**Comment by crazy-max** [comment]
@hermanschaaf Thanks :)
