### ISSUE TITLE
Discord badge missing icon

### ISSUE THREAD

**Issue by Haarolean** [badges/shields#9882]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

![Static Badge](https://img.shields.io/badge/-Discord-5865F2?logo=Discord)
^ this badge is missing icon

The icon has been added to simple-icons [3 years ago](https://github.com/simple-icons/simple-icons/blame/master/slugs.md):
<img width="662" alt="image" src="https://github.com/badges/shields/assets/1494347/1ba03659-642d-408f-9651-e8197189f864">

Other icons from that commit work alright, say, discogs:
![Static Badge](https://img.shields.io/badge/-Discord-5865F2?logo=Discogs)

### 🔗 Link to the badge

https://img.shields.io/badge/-Discord-5865F2?logo=Discord

**Comment by PyvesB** [comment]
Hello @Haarolean 👋🏻 

The icon is there, it's just hard to see as the background color you chose is the same as the icon's default color. You can change the logo color, for example: https://img.shields.io/badge/-Discord-5865F2?logo=Discord&logoColor=white ![](https://img.shields.io/badge/-Discord-5865F2?logo=Discord&logoColor=white)

**Comment by Haarolean** [comment]
@PyvesB ah, my bad, sorry! Lol, didn't even think that the background color is the same as the logo's.
Thank you very much!

**Comment by PyvesB** [comment]
No worries. Happy badging!
