### ISSUE TITLE
Greenkeeper badge

### ISSUE THREAD

**Issue by stevenvachon** [badges/shields#991]
https://greenkeeper.io/

https://github.com/greenkeeperio/greenkeeper/issues/416

The badge could say "dependencies: monitored", similar to the [david-dm](https://david-dm.org) badge.

**Comment by Daniel15** [comment]
I assume you'd want a badge that shows something like "dependencies: up to date" like the david-dm one. Does Greenkeeper provide an API for that?

> The badge could say "dependencies: monitored",

If all you want is "dependencies: monitored", you could simply use a static badge:

![](https://img.shields.io/badge/dependencies-monitored-green.svg)

https://img.shields.io/badge/dependencies-monitored-green.svg

**Comment by stevenvachon** [comment]
@Daniel15 I don't think there currently is, but there's this: https://github.com/greenkeeperio/greenkeeper/issues/422

**Comment by paulmelnikow** [comment]
I'm marking all the **needs-upstream-help** issues closed.

If there's new information from the upstream service, please post in the thread. If they're actionable by Shields, a maintainer will reopen the issue.

If anyone wants to follow up with these vendors, feel free to do that! Even though the unresolved issues are closed, they are easy to find:

https://github.com/badges/shields/issues?q=label%3Aneeds-upstream-help+is%3Aclosed
