### ISSUE TITLE
Kerning problems on windows

### ISSUE THREAD

**Issue by IRus** [badges/shields#992]
Hi, is it possible to fix kerning for `W` letter on windows (Reproduced on Windows 10)?

![grafik](https://cloud.githubusercontent.com/assets/493656/25946822/6dd27332-3655-11e7-9d23-022893fa5ec0.png)

On linux works without problems.

**Comment by paulmelnikow** [comment]
Hi, thanks for the question. Is that with Verdana installed?

**Comment by paulmelnikow** [comment]
@RedSparr0w Are you able to reproduce this issue?

**Comment by RedSparr0w** [comment]
Can't seem to reproduce this.

Windows 10:
`No fallback font set. Unable to load fallback font. Using Helvetica-Bold instead.`
![windows 10](https://svgur.com/i/9Ss.svg)

Windows 10:
`Verdana`
![windows 10](https://svgur.com/i/9T8.svg)

**Comment by RedSparr0w** [comment]
Closing as this should no longer be an issue now with #2311 merged.
