### ISSUE TITLE
A badge for "unpacked size" in NPM

### ISSUE THREAD

**Issue by erayerdin** [badges/shields#9952]
### 📋 Description

NPM has unpacked size section in every library page.

![unpacked size on npm website](https://github.com/badges/shields/assets/2399084/ade654c4-9ad3-4140-aed0-d128a7ebec34)

However, the badge is not implemented.

### 🔗 Data

Unpacked size is available in registry API. [This](https://registry.npmjs.com/firereact) shows every version and [this](https://registry.npmjs.com/firereact/latest) shows only the latest version.

Unpacked size can be seen in "dist.unpackedSize", which is in bytes.

### 🎤 Motivation

A badge for unpacked size would be good as a developer might decide to include it in their front end project. Normally, they'd check this with bundlephobia, which is already implemented and only shows minified and min+gzipped sizes. The problem is, sometimes, due to the lack of entry point in `package.json`, bundlephobia will not respond with a size, see [react-firebase-hooks](https://bundlephobia.com/package/react-firebase-hooks).

Thus, the only remaining thing a developer can rely on would be unpacked size for this case.

+ would be better

**Comment by erayerdin** [comment]
If possible, I'd like to take this on.

**Comment by chris48s** [comment]
> I'd like to take this on

Feel free :+1: 

There's a tutorial for adding new badges at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md
and the code for the existing NPM badges is in https://github.com/badges/shields/tree/master/services/npm
