### ISSUE TITLE
Mozilla Add-ons badge cannot override label

### ISSUE THREAD

**Issue by hudson6666** [badges/shields#996]
![](https://img.shields.io/amo/users/dustman.svg?label=mozilla%20add-on)
![](https://img.shields.io/amo/rating/dustman.svg?label=mozilla%20add-on)
![](https://img.shields.io/amo/stars/dustman.svg?label=mozilla%20add-on)

**Comment by paulmelnikow** [comment]
Fixed! Thanks @RedSparr0w.
