### ISSUE TITLE
npm-stat badges failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9964]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All badges fetching data from https://npm-stat.com have stopped working

### 🔗 Link to the badge

https://img.shields.io/npm-stat/dw/dukeluo

### 💡 Possible Solution

Looks like the upstream service is down

I'm going to subscribe to https://github.com/pvorb/npm-stat.com/issues/135 and see if there is any update.

If it doesn't get fixed, I guess we drop them

**Comment by ParticleCore** [comment]
Chrome Web Store badges are also affected by this or is it a different issue?

Example: ![](https://img.shields.io/chrome-web-store/users/iocghaljaochhkgajdilelogdkejkiil)
https://img.shields.io/chrome-web-store/users/iocghaljaochhkgajdilelogdkejkiil

**Comment by chris48s** [comment]
No. We don't get information about chrome plugins from npm-stat.com this is another issue.
I'm going to raise a new issue for that

**Comment by pvorb** [comment]
Oh, I wasn't aware that my site is used for these badges.

**Comment by pvorb** [comment]
The service is back again. @chris48s Can you verify that badges are working again?

**Comment by chris48s** [comment]
Yep they're working again - thanks :+1: 

Is it a _problem_ that we're using npm-stat.com as a data source?

**Comment by pvorb** [comment]
🤷 No, I guess that's okay.

**Comment by pvorb** [comment]
TBH I completely stopped tracking usage of the site when GDPR came around. I unlinked Google Analytics and also completely disabled access logging on my server to avoid any issues with GDPR. So I have no clue how much traffic you generate. Feel free to cause requests until the hardware's glowing. 😉
