### ISSUE TITLE
logo - Papers With Code is not working.

### ISSUE THREAD

**Issue by childult-programmer** [badges/shields#9979]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

In Static Badge, the other logos from [slug.md](https://github.com/simple-icons/simple-icons/blob/master/slugs.md) works fine, but the logo from Papers With Code doesn't seem to work.

**Comment by chris48s** [comment]
We're currently running simple-icons v11.4.0 in production.
Papers With Code is a new icon in simple-icons v11.5.0 https://github.com/simple-icons/simple-icons/releases/tag/11.5.0
It will become available when we upgrade on our usual schedule. For more info, see https://github.com/badges/shields/discussions/5369 (which was linked from https://github.com/badges/shields/issues/new/choose )
