### ISSUE TITLE
Custom bucket URLs for Scoop version shield.

### ISSUE THREAD

**Issue by jewlexx** [badges/shields#9982]
:clipboard:
In addition to referencing Scoop's [bucket list](https://github.com/ScoopInstaller/Scoop/blob/master/buckets.json), shields could take in a URL as a bucket parameter for the Scoop version shield.

After `if (!bucketUrl)`, before throwing the error, shields could check if the bucket parameter is a valid GitHub URL, and attempt to extract the user & repo from that, using the same `gitHubRepoRegExp`, allowing users to reference buckets that are not in the official list.

**Comment by chris48s** [comment]
Seems reasonable to me. Are you up for submitting a PR?

**Comment by jewlexx** [comment]
Sure, I'll see what I can do.
